### ISSUE TITLE
Viewer return values only work on certain backends

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1056]
@tonysyu and I hashed this out two days ago while preparing for the tutorials. Basically, some backends go through a lot of trouble to make the viewer call non-blocking, in which case, the returned object contains just the original, uninitialized values!

At the very least, this should be documented. At best, we need to rethink this interface to make it work on asynchronous backends. (Aside: @tonysyu is reluctant to do this because he would rather spend more effort on reproducing the viewer stuff using IPython widgets.)

Here's some code to reproduce the bug. It works with the MacOSX backend, but not Qt. Others are untested.

``` python
from skimage import viewer
from skimage import data
from skimage.viewer.plugins.lineprofile import LineProfile
image = data.camera()
view = viewer.ImageViewer(image)
view += LineProfile()
d = view.show() # fiddle with the line being traced in the viewer here
from matplotlib import pyplot as plt
plt.imshow(d[0][0])
plt.show()
```

This will show the updated value if the call to `view.show` was blocking, but the original middle line if it was non-blocking.

**Comment by mkcor** [comment]
Closing following #6160.
