### ISSUE TITLE
Document networkx dependency

### ISSUE THREAD

**Issue by cdeil** [scikit-image/scikit-image#1067]
Could you please document that `networkx` is now a dependency for `scikit-image`?

I get a test error and the Sphinx docs build doesn't work any more:

```
$ make html
python tools/build_modref_templates.py
('WARNING: Empty -', 'skimage._shared')
Traceback (most recent call last):
  File "tools/build_modref_templates.py", line 55, in <module>
    docwriter.write_api_docs(outdir)
  File "/Users/deil/temp/scikit-image2/doc/tools/apigen.py", line 423, in write_api_docs
    self.write_modules_api(modules,outdir)
  File "/Users/deil/temp/scikit-image2/doc/tools/apigen.py", line 390, in write_modules_api
    api_str = self.generate_api_doc(m)
  File "/Users/deil/temp/scikit-image2/doc/tools/apigen.py", line 261, in generate_api_doc
    functions, classes = self._parse_module_with_import(uri)
  File "/Users/deil/temp/scikit-image2/doc/tools/apigen.py", line 203, in _parse_module_with_import
    mod = __import__(uri, fromlist=[uri])
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/scikit_image-0.11dev-py2.7-macosx-10.9-x86_64.egg/skimage/graph/__init__.py", line 3, in <module>
    from .rag import rag_mean_color, RAG
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/scikit_image-0.11dev-py2.7-macosx-10.9-x86_64.egg/skimage/graph/rag.py", line 1, in <module>
    import networkx as nx
ImportError: No module named networkx
make: *** [api] Error 1
```

I saw there was a discussion on the mailing list if / how `networkx` should be handled as a dependency. If it's not used heavily at the moment (say for more than 10% or 20% or the current functionality), you could consider simply moving this `networkx` imports into the functions where it's used and to mark the tests as optional (see e.g. how [astropy does this](http://astropy.readthedocs.org/en/latest/development/testguide.html#tests-requiring-optional-dependencies)) and declare it an "optional dependency", i.e. most parts of scikit-image (and the tests and docs build) would run even if it's not present.

Here's the test errors I see (not all related to `networkx` I think): https://gist.github.com/cdeil/5b73041e440c7741b170

**Comment by cdeil** [comment]
Possibly there's still an issue because the `networkx` dependency isn't declared in `setup.py` ... or I'm using `pip` incorrectly. https://github.com/astropy/photutils/issues/255

**Comment by stefanv** [comment]
We're working on this right now.

**Comment by cdeil** [comment]
@stefanv – I think the dependency issue for scikit-image has now been fixed?
Can you please make a bugfix release soon?
If you're waiting for other fixes, I'll try and change our `pip-install-requirements` on readthedocs to pip-install scikit-image from the development version on github.

```
conda create -n skimage-pip scipy pip
source activate skimage-pip
pip install scikit-image # fails because six is not installed and not declared as a dependency to pip
```

What's the correct invocation to pip-install the development version?
This didn't work for me:
```
$ pip install git+https://github.com/scikit-image/scikit-image.git#egg=scikit-image
Collecting scikit-image from git+https://github.com/scikit-image/scikit-image.git#egg=scikit-image
  Cloning https://github.com/scikit-image/scikit-image.git to /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-loenex2f/scikit-image
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Operation timed out

Clone of 'git://github.com/matthew-brett/gitwash.git' into submodule path 'doc/tools/gitwash' failed
  Complete output from command /opt/local/bin/git submodule update --init --recursive -q:
  
  ----------------------------------------
  Command "/opt/local/bin/git submodule update --init --recursive -q" failed with error code 1 in /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-loenex2f/scikit-image
```

**Comment by stefanv** [comment]
Thanks for the reminder--I can do that tomorrow.

**Comment by stefanv** [comment]
Done (OSX wheels should appear in due course)

**Comment by cdeil** [comment]
@stefanv – Problem solved, thanks!

The pip install of scikit-image on readthedocs now works again ([first successful build for the project where I had the issue](https://readthedocs.org/builds/gammapy/2517961/))

**Comment by stefanv** [comment]
Excellent, thanks for the feedback!
