### ISSUE TITLE
Improve morphology performance by supporting structuring element decomposition

### ISSUE THREAD

**Issue by blowekamp** [scikit-image/scikit-image#1070]
When doing grayscale or binary morphology, significant performance can be obtained by decomposing a structuring element in to a series of smaller elements. Perhaps the best case for this in decomposing a large box into two 1-D lines, horizontal and vertical, reducing the cost from O(N^2) to O(2N). Other examples exist for diamonds, and octagons too.

One way to add support for this would be to support a list of structuring elements for the function which take structuring elements, and have the se generator functions also return a list for the sequence of elements to run.

**Comment by grlee77** [comment]
it is implemented in #5482, #6150, #6151
