### ISSUE TITLE
Segfault after loading images, then using scikit learns job lib

### ISSUE THREAD

**Issue by erikbrinkman** [scikit-image/scikit-image#1088]
After loading images using `imread` with the default plugin, and then ostensibly clearing them from memory, I get a segfault when using scikit learn's joblib utility. I realize that this could be a bug in joblib or scikit learn.

Example code

``` python
import gc

import numpy as np
from sklearn import svm, grid_search
from skimage import io

urls = ['http://farm4.static.flickr.com/3040/2946102733_9b9c9cf24e.jpg',
        'http://farm3.static.flickr.com/2093/2288303747_c62c007531.jpg',
        'http://www.zuidafrikaonline.nl/images/zuid-afrika-reis-giraffe.jpg',
        'http://farm1.static.flickr.com/145/430300483_21e993670c.jpg',
        'http://farm2.static.flickr.com/1005/3352960681_37b9c1d27b.jpg',
        'http://farm1.static.flickr.com/27/51009336_a9663af3dd.jpg',
        'http://farm4.static.flickr.com/3025/2444687979_bf7bc8df21.jpg',
        ]

images = [io.imread(u) for u in urls]
del images
gc.collect()

n = 1000
m = 100
X = np.random.rand(n * m).reshape(n, m)
y = np.int_(np.random.rand(n) * 3)

clf = svm.LinearSVC()
grid = {'C': [1]}
param_search = grid_search.GridSearchCV(clf, grid, n_jobs=2)
param_search.fit(X, y)
```

Produces the following error on my mac:

```
Process:         Python [12715]
Path:            /usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:      Python
Version:         2.7.8 (2.7.8)
Code Type:       X86-64 (Native)
Parent Process:  Python [12714]
Responsible:     Terminal [303]
User ID:         502

OS Version:      Mac OS X 10.9.4 (13E28)
Report Version:  11


Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000110
```

And my package versions are:

```
numpy==1.8.1
scikit-image==0.10.0
scikit-learn==0.14.1
scipy==0.14.0
```

This could be caused by simply using too much memory, but if I don't load the images, and learn on much larger data (to the point of thrashing), it doesn't segfault. It only segfaults after the images are loaded, and they should be cleaned from memory after calling `del` on the images followed by a manual garbage collect, which seems suspicious.

However, I need to parallelize grid search (i.e. use joblib) to get the segfault, I also need to use a multi label svm, which seems to indicate that it may be an issue with scikit learn.

I realize this issue may be too vague and machine dependent replicate or bother working on, but I'm more than happy to post more information to help debug this.

**Comment by ivannz** [comment]
I stumbled upon the very same **segfault**, when I was trying to fit multiple PCA's in parallel
to a bootstrapped sample. I noticed, that this fault takes place **only** when I import **matplotlib.pyplot**
for plotting purposes. The process seems to crash inside a call to BLAS.

I attach an archive with a small sufficient example, a crash report and a frozen list of pip packages.

[matplotlib_crash.zip](https://github.com/scikit-image/scikit-image/files/117797/matplotlib_crash.zip)

**Comment by stefanv** [comment]
@ivannz Is this related to skimage?  It does not look that way.

**Comment by ivannz** [comment]
No, it does not. I decided to write an update to this issue, because the dump information from @erikbrinkman pointed to what appeared to be the same call that caused the crash in my case.

Apparently the [reason](https://github.com/joblib/joblib/issues/310) for this crash is bad interaction of Apple's **Accelerate** linear algebra library (the **DGEMM** call for matrix [operations](http://www.math.utah.edu/software/lapack/lapack-blas/dgemm.html) on lines 1, and 2) and **joblib** (used by **grid_search.GridSearchCV** with `n_jobs>1`).
