### ISSUE TITLE
Region props optimisation (and adding 3D/nD support)

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1092]
Hi all,

Since my main research project uses regionprops to extract image features, I've been more concerned with optimising those functions. I've made a [notebook](http://nbviewer.ipython.org/github/jni/profile-regionprops/blob/master/regionprops-profiling-results.ipynb) with some profiling info. Interestingly, some functions, such as **`bbox`**, appear to suffer quite dramatically from the `@_cached_property` decorator. (I made a [branch](https://github.com/jni/scikit-image/tree/speed-regionprops) to measure this.) Others, like the **convex hull-based properties**, are sort of outside our control so might not be ideal to optimise. Finally, many many features depend on **moments calculation**, so making that 3D and optimising the crap out of it should be fruitful. =)

Thoughts welcome!

**Comment by soupault** [comment]
@jni Having https://github.com/scikit-image/scikit-image/pull/2603 merged and https://github.com/scikit-image/scikit-image/pull/2847 on its way to `master`, do you think that this issue should be closed?
For extension of 3D/nD support we have a dedicated issue - https://github.com/scikit-image/scikit-image/issues/1489.

**Comment by jni** [comment]
@soupault that is a grand idea, closing, thanks for spotting this one! =)
