### ISSUE TITLE
poly2mask

### ISSUE THREAD

**Issue by dpereira84** [scikit-image/scikit-image#1103]
Hi everybody,

I need a function poly2mask equal to function in Maltlab, someone could tell me if there is already some implementation in Python ?

Regards
Danilo

**Comment by zhangda82** [comment]
Hello jni,

Can you help clarify the meaning of parameters for draw.polygon() ? From your example the 1st and 2nd parameters are list of row and col coordinates of the vertex, but from the official document of skimage.draw.polygon(), they are y and x coordinates defined elsewhere. Thanks!

Da

**Comment by MalikAsif** [comment]
i am getting this issue.
from .._shared.utils import warn

ImportError: cannot import name 'warn'
anyone can help

**Comment by hmaarrfk** [comment]
@MalikAsif this issue is 4 years old. Please open a new issue and describe the issue you are having from the beginning.

**Comment by stefanv** [comment]
Yes, why not.

**Comment by MalikAsif** [comment]
Thanks, got it

**Comment by hadim** [comment]
I confirm this is a useful function.

For the record, I have been experimenting with a matplotlib-based similar function. I compared it to the one provided by @jni.

Both give similar results and the skimage's one seems more efficient. The speed is probably dependent on the shape of the polygon and the size of the image so you should benchmark with your own data both implementations (if speed is a concern for you).

See more details here: https://gist.github.com/hadim/fa89b50bbd240c486c61787d205d28a6

**Comment by jni** [comment]
I'm going to reopen this to note that we want to have this function added to skimage. Thanks for chiming in, @hadim!

**Comment by hadim** [comment]
I felt like I needed to submit this PR after making you reopen the issue xD

See https://github.com/scikit-image/scikit-image/pull/3971

**Comment by soupault** [comment]
Added in #3971 .
