### ISSUE TITLE
installation issue when installed over older version (with Windows binary installer)

### ISSUE THREAD

**Issue by hayne** [scikit-image/scikit-image#1173]
I am using the binary installer scikit-image-0.10.1.win32-py2.7.exe (from http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image)

It seems that if there was a previous version of skimage installed, the installation doesn't work correctly since there is a problem when trying to use skimage.
I get the error:
"cannot import name find_contours"

I am using Python 2.7.8 on Windows XP.
Using Windows' Add/Remove Programs to remove skimage and then re-running the installer seems to fix the problem.

**Comment by khizaryz** [comment]
Would somebody help me with the following installation error.
![error](https://cloud.githubusercontent.com/assets/10580774/5791608/7b99430a-9efa-11e4-9c3e-e26c43b4c64b.png)

**Comment by khizaryz** [comment]
Would somebody help me addressing the following installation error please:

![error](https://cloud.githubusercontent.com/assets/10580774/5791613/d32f3f48-9efa-11e4-8f55-ecdb7dd1e98b.png)
