### ISSUE TITLE
Lab and Luv color conversion bugs

### ISSUE THREAD

**Issue by connellybarnes** [scikit-image/scikit-image#1201]
In Scikit-image 0.10.1 the RGB <-> Lab and RGB <-> Luv color conversions appear to have bugs.

Run this test code:
http://connellybarnes.com/dump/skimage_bug

This converts an sRGB 10x10x3 image of uniform randoms in [0, 1] to Lab/Luv, clamps L to the range [0, 0.01], converts back to sRGB, and verifies that the minimum sRGB value is non-negative.

It should output 'lab2rgb: OK' and 'luv2rgb: OK'.

Instead it outputs two tracebacks showing a bug in each method due to negative sRGB values.

You can also run the same clamp test on an input image of your choice. The correct output is a nearly black output image but scikit-image produces some strange colored artifacts.

You can get correct results from MATLAB, and correct codes from Bruce Lindbloom here:

http://www.brucelindbloom.com/index.html?WorkingSpaceInfo.html

**Comment by blink1073** [comment]
I believe what we're seeing is that one cannot perform arbitrary operations on the Lightness channel while expecting a* and b* remain valid.  For example, as you shrink the Lightness down to zero, the perceivable ranges of a* and b* also shrink.  Plugging some of the resulting `L*a*b*` values in to our reference [color calculator](http://www.easyrgb.com/index.php?X=CALC) yields errors: `Z < 0`.  
I think the question is how to do handle *invalid* data in colorspace transformations (related to #1079).  Should we raise an error, raise a warning, or truncate to a valid range?

**Comment by stefanv** [comment]
Truncate with warning?

**Comment by blink1073** [comment]
Sounds reasonable to me, it makes sense for the color calculator to barf since its only working on one value at a time, but I don't think we should throw the baby out with the bathwater.

**Comment by stefanv** [comment]
I agree.  You are self-assigned to this issue--are you still happy to work on it?

**Comment by blink1073** [comment]
Yep

**Comment by blink1073** [comment]
I was just waiting for another opinion.

**Comment by blink1073** [comment]
I'm calling this closed by #1079.  Feel free to reopen if you disagree @connellybarnes.

**Comment by connellybarnes** [comment]
Nice. It looks like the script I linked before [1] now returns OK on both tests, and reports a warning for color data out of range for a few pixels. This seems totally reasonable.

[1]. http://connellybarnes.com/dump/skimage_bug
