### ISSUE TITLE
Request Access to OSX Testing on Travis

### ISSUE THREAD

**Issue by blink1073** [scikit-image/scikit-image#1215]
http://docs.travis-ci.com/user/multi-os/

"We are at capacity with Mac workers in both .org and .com environments. Consequently, we are not accepting requests for the multi-OS feature at this time. As more capacity is added, we will resume accepting requests."

**Comment by soupault** [comment]
"We are still working on building up the tool chain on the Mac worker."

**Comment by soupault** [comment]
"The feature described in this document is considered beta. Some features may not work as described." :+1:

**Comment by stefanv** [comment]
Let's find out: https://github.com/scikit-image/scikit-image/pull/2038

**Comment by soupault** [comment]
Closed via #2038.
