### ISSUE TITLE
Weird 'skimage.transform.rotate' behaviour

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#1224]
Suppose, we have following code:

```python
import numpy as np
import matplotlib.pyplot as plt
from skimage.transform import rotate

w, h = 255, 255

[buggy code]
img[50:206, 50:206] = 50

img_rotated = rotate(img, 30, resize=0)

f, ax = plt.subplots(1, 2)
ax1, ax2 = ax
ax1.imshow(img, cmap=plt.cm.gray)
ax2.imshow(img_rotated, cmap=plt.cm.gray)

plt.show()
```

For various values of `buggy code`:
```python
img = np.zeros((w, h), dtype=np.int32)
```
![int32_no_add](https://cloud.githubusercontent.com/assets/1315589/5046840/1bb20ea2-6c20-11e4-93c2-d200f64eb6c1.png)

```python
img = np.zeros((w, h), dtype=np.int32) + 1
```
![int32_add](https://cloud.githubusercontent.com/assets/1315589/5046844/1d31a65c-6c20-11e4-9ade-3e7293a1b7eb.png)

```python
img = np.zeros((w, h), dtype=np.float64)
```
![float64_no_add](https://cloud.githubusercontent.com/assets/1315589/5046846/1f4abd48-6c20-11e4-912e-19afd529b445.png)

```python
img = np.zeros((w, h), dtype=np.float64) + 1
```
![float64_add](https://cloud.githubusercontent.com/assets/1315589/5046847/21efa6e4-6c20-11e4-9738-66139099b9ff.png)

Picture number 4 is a subject.

Btw, can't pass `np.float32` and `np.int64` to `dtype` here due to some errors.
Don't we want to have unified behaviour here?

**Comment by ahojnnes** [comment]
This should be fixed since we have the `clip` and `preserve_range` parameters in https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/_geometric.py#L1160 ?

Closing this issue, please reopen if necessary.
