### ISSUE TITLE
peak_local_max should have saner defaults

### ISSUE THREAD

**Issue by anntzer** [scikit-image/scikit-image#1246]
While I understand the usefulness of `threshold_abs` and `threshold_rel`, it seems that defaults of respectively `-np.inf` and `None` (ie., don't use)  would be much more reasonable (`-np.inf` as default for `threshold_rel` would fail if the values in the image were all negative...).  It seems to me that when one calls a function named `peak_local_max`, one expects it to just return local maxima, not to add on top of that its own interpretation of what kind of maxima are significant.

In fact, it isn't even obvious to me what value I should use for `threshold_rel` if I don't know whether the input array can have negative values...

On a different issue, it is a bit strange that `exclude_border` always uses `min_distance`, even when `threshold` is given.  It would make much more sense to use `threshold` when available (in fact, it would be even better to merge the two arguments, `min_distance` and `threshold`, in a single one).

**Comment by JDWarner** [comment]
Closed by #1898 - thanks @ahojnnes!
