### ISSUE TITLE
Enhancements to data types policy and handling

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1266]
This follows from a lot of discussion in #1224 and on [gitter.im](https://gitter.im/scikit-image/scikit-image) (search for "vmin"). Summary:

- many images represent physical quantities and doing an `img_as_whatever` on it can result in precision loss and/or confusion for the user. 
- we should thus minimize messing with users' data ranges *except where required*
- where it makes sense, we should still assume correct input according to the current data policy. For example, just as rescaling user data before doing e.g. a dilation can be misleading/confusing, so can rescaling the display range, as matplotlib does by default. That's why the mpl plugin for `io.imshow` by default uses the image ranges displayed in our data types.

To do here:

- [ ] Update `doc/source/user_guide/data_types.txt` to say that input data types will be respected wherever possible.
- [x] Update morphology functions to support all dtypes, see #1216, #1074, and #1049.
- [x] Update the MPL `io.imshow` plugin to raise warnings when image range exceeds the expected range *and* when image range is too small to display within the expected range (1/255. of the expected range).

**Comment by stefanv** [comment]
If this needs to happen before 0.11, we'd better get on it.  Do we have a volunteer for updating the data types docs?  I think the MPL plugin is done, right?

**Comment by blink1073** [comment]
Was this closed by #1352?

**Comment by stefanv** [comment]
Indeed, thanks!

**Comment by jni** [comment]
@blink1073 @stefanv My OCD prompted me to come back and tick that final tick box. =P =P =P
