### ISSUE TITLE
Use fused types for warping

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#1287]
Use fused types for image warping, so cast to double is not necessary.

**Comment by stefanv** [comment]
@ahojnnes Are you planning on working on this one?

**Comment by ahojnnes** [comment]
Nope. Not for now...

**Comment by soupault** [comment]
Implemented in #3486

**Comment by hmaarrfk** [comment]
Unfortuantely, not really. It implemented it in denoise, but warp still casts to float64.

**Comment by rfezzani** [comment]
Fixed by #4128 ;-) Closing
