### ISSUE TITLE
skimage.segmentation throw Exception TypeError

### ISSUE THREAD

**Issue by tonal** [scikit-image/scikit-image#1308]
Step for reproduction:
$ python -c 'from skimage import segmentation'
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x7fcde38b1d10>> ignored

My OS: Kubuntu 14.04 with all updates
skimage from standart repozitories: python-skimage (0.9.3-4build1)

**Comment by emmanuelle** [comment]
I also think that it might come from the random walker code.

**Comment by emmanuelle** [comment]
and this code in particular

```
try:
    from scipy.sparse.linalg.dsolve import umfpack
    old_del = umfpack.UmfpackContext.__del__

    def new_del(self):
        try:
            old_del(self)
        except AttributeError:
            pass
    umfpack.UmfpackContext.__del__ = new_del
    UmfpackContext = umfpack.UmfpackContext()
except:
    UmfpackContext = None
```

**Comment by budiaji** [comment]
Hi @jni,
I am using scipy version 0.13.3

**Comment by stefanv** [comment]
Can you please provide a short code snippet?

**Comment by jni** [comment]
@stefanv read the post again. All it takes is "from skimage import segmentation" and then quitting. However, I can't reproduce... I just created a conda env with scipy 0.13.3 and scikit-image 0.10.1 and the provided code works fine.

@JDWarner do you have any ideas about this? What's the above code trying to achieve?

**Comment by stefanv** [comment]
@jni Sorry, this arrived as a blank email yesterday--not sure what happened there.  

I don't see this on my system any more  (although I do recall seeing that message before while running the test suite).

**Comment by falaktheoptimist** [comment]
I am using Ubuntu 14.04 with Eclipse IDE, scikit-image 0.9.3, and just a single line of the code:
from skimage import segmentation.
generates the error message: 
"Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x7f1f46f99ad0>> ignored"
However, the same line runs fine with Idle (python shell 2.7.6). Cannot figure out the error.

**Comment by r3vl1s** [comment]
Tested this out in Ubuntu 14.04 with 0.10.1 (& scipy 0.13.3)

I ran a few of the segmentation examples and they worked:
http://scikit-image.org/docs/dev/auto_examples/plot_random_walker_segmentation.html
http://scikit-image.org/docs/dev/auto_examples/plot_segmentations.html

When the script ends I get the error reported: 
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x7fe92124ad10>> ignored

**Comment by jdmcbr** [comment]
I'm seeing the same essential behavior. It does not cause me any problems that I am aware of though. In python 2.7.6, in Ubuntu 14.04:

    In [1]: import scipy

    In [2]: scipy.__version__ 
    Out[2]: '0.13.3'

    In [3]: import skimage

    In [4]: skimage.__version__
    Out[4]: '0.10.1'

    In [5]: from skimage import segmentation

    In [6]: 
    Do you really want to exit ([y]/n)? y
    Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x7ffed0ea1390>> ignored

**Comment by gongenhao** [comment]
same here:
Python 2.7.9 (default, Apr  1 2015, 18:18:03) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'0.12.1'
>>> import skimage
>>> skimage.__version__
'0.11.3'
>>> from skimage import segmentation
>>> exit()

Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x7fc0bedf9a90>> ignored

**Comment by stefanv** [comment]
Can anyone else reproduce this with the latest scipy + skimage?

**Comment by gongenhao** [comment]
I confirmed there is no error with the latest scipy

Python 2.7.9 (default, Apr  1 2015, 18:18:03) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'0.15.0'
>>> import skimage
>>> skimage.__version__
'0.11.3'
>>> from skimage import segmentation
>>> exit()

No warning shows up after that.

**Comment by RojunLin** [comment]
I have met the same problem in Ubuntu14.04 with scikit-image 0.12.3. As I  import segmentation module in py file, it returns:
`Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x7efcffa935d0>> ignored`
Do anyone else have resolved this problem?

**Comment by soupault** [comment]
Confirmed by @RojunLin once again that everything is fine with the lastest (as of June 2017) `scipy` and `scikit-image`.
