### ISSUE TITLE
PyQt4 runtime incompatible with Pillow 2.6 (using PyQt5)

### ISSUE THREAD

**Issue by flying-sheep** [scikit-image/scikit-image#1316]
when loading an image and later ImageViewer, things break because Pillow 2.6 loads PyQt5.

On Pillow master, this can be circumvented by manually importing PyQt4.QtGui since python-pillow/Pillow@f3284e57a63871756acd82dda3e137df32300f8b: [`if 'PyQt4.QtGui' not in sys.modules`](https://github.com/python-pillow/Pillow/blob/f3284e57a63871756acd82dda3e137df32300f8b/PIL/ImageQt.py#L23)

it would of course be useful if you switched to PyQt5, anyway.

/edit: yeah, definitely. matplotlib also uses PyQt5.

**Comment by blink1073** [comment]
@flying-sheep,  did #1318 fix this for you?

**Comment by blink1073** [comment]
I'm calling this closed, feel free to open if you run into any more problems @flying-sheep.

**Comment by flying-sheep** [comment]
oops, sorry for not replying!

interestingly it works when calling the example as

```sh-session
$ python -m viewer_examples.viewers.image_viewer
```

but not when calling

```sh-session
$ python viewer_examples/viewers/image_viewer.py
```

then it still raises:

```pytb
Traceback (most recent call last):
  File "viewer_examples/viewers/image_viewer.py", line 2, in <module>
    from skimage.viewer import ImageViewer
  File "/usr/lib/python3.4/site-packages/skimage/viewer/__init__.py", line 1, in <module>
    from .viewers import ImageViewer, CollectionViewer
  File "/usr/lib/python3.4/site-packages/skimage/viewer/viewers/__init__.py", line 1, in <module>
    from .core import ImageViewer, CollectionViewer
  File "/usr/lib/python3.4/site-packages/skimage/viewer/viewers/core.py", line 4, in <module>
    from ..qt import QtGui, qt_api
  File "/usr/lib/python3.4/site-packages/skimage/viewer/qt/QtGui.py", line 6, in <module>
    from PyQt4.QtGui import *
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

**Comment by blink1073** [comment]
Excellent!

**Comment by stonebig** [comment]
Hi,

I see [DEPENDS.txt](https://github.com/scikit-image/scikit-image/blob/master/DEPENDS.txt) still write PyQt4 (only), shouldn't it change ?

**Comment by blink1073** [comment]
Would you like to add a note about PyQt5 in a PR?



—

**Comment by stonebig** [comment]
Please do, I'm not really confident in any PyQt5 matters I notice.
