### ISSUE TITLE
Cannot find example data

### ISSUE THREAD

**Issue by JamesOwers** [scikit-image/scikit-image#1326]
Hello,

I'm trying to run through the example here: http://scikit-image.org/docs/dev/auto_examples/plot_brief.html. Running the script as is it throws the error:
AttributeError: 'module' object has no attribute 'astronaut'.

I'm running Python 2.7.9 :: Anaconda 2.1.0 (x86_64) on mac 10.10.1. I installed scikit-image via conda.

Any advice gratefully received.

James

**Comment by anuragvvworkspace** [comment]
was there a solution to this problem?

**Comment by sciunto** [comment]
I think so. The reporter used a version older than the one for which the content was added.
