### ISSUE TITLE
Affine transform

### ISSUE THREAD

**Issue by Borda** [scikit-image/scikit-image#1332]
Well is not really issue, but missing feature, is there a way how to apply affine transform defined by matrix within rotation such that the rotation is performed around image center (not initial [0,0] in top left corner)? Thanks

**Comment by ahojnnes** [comment]
Look at skimage.transform.rotate.

**Comment by Borda** [comment]
ok, but this take just one parameter, so if I have complex transformation matrix A, how to extract all partial operations like rotate, scale, etc...

**Comment by stefanv** [comment]
You always have the option of composing several transformations using the
"+" operator.  That way, you can shift your image to have the center around
the origin, apply your transformation, then shift it back.

**Comment by matthew-brett** [comment]
Forgive my general ignorance of scikit-image, but I have some code to decompose affine matrices into component transformations here : https://github.com/matthew-brett/transforms3d/blob/master/transforms3d/affines.py#L210

**Comment by matthew-brett** [comment]
If y'all don't have code like this, you're welcome to include the transforms3d code in scikit-image.

**Comment by ahojnnes** [comment]
@matthew-brett Thanks for sharing. You can do that in skimage too (for 2D transformations). Look at the scale, rotation, translation properties.

**Comment by ahojnnes** [comment]
Closing as resolved, reopen if necessary.
