### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'Files.obj' 

### ISSUE THREAD

**Issue by khizaryz** [scikit-image/scikit-image#1342]
Would somebody help me addressing the following installation error please. I was trying to install scikit-image:

![error](https://cloud.githubusercontent.com/assets/10580774/5791613/d32f3f48-9efa-11e4-8f55-ecdb7dd1e98b.png)

**Comment by blink1073** [comment]
@khizaryz, how were you trying to install?  From a git checkout, pip install, otherwise?

**Comment by khizaryz** [comment]
it was a pip install.

**Comment by blink1073** [comment]
Can you try removing any existing skimage folder in you site-packages directory and try again?

**Comment by khizaryz** [comment]
no skimage folder in site-packages.

**Comment by blink1073** [comment]
Are you able to `pip install tifffile` (one of my packages, it has a C extension)?

**Comment by khizaryz** [comment]
Tifffle installed successfully

**Comment by blink1073** [comment]
Well shucks, I'm out of my limited depth.  You may try installing from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/).

**Comment by khizaryz** [comment]
Already tried but in vain.
BTW I'm on Windows 7 and My suspect is microsoft as I have vc6 and vc2008 command prompt. I guess the spaces and brackets in paths, e.g. "Program Files (x86)"

**Comment by blink1073** [comment]
You could try moving ActivePython to C:\ and try again.

**Comment by khizaryz** [comment]
reinstall? or just copy paste would work?

**Comment by blink1073** [comment]
You may have to update your PATH variable, but otherwise a copy should work.

**Comment by blink1073** [comment]
I've never use ActivePython.  May I suggest Anaconda, which has a prebuilt skimage.  :)

**Comment by ivoflipse** [comment]
I'm getting the same error currently on AppVeyor when trying to build the current master branch on conda-forge: https://ci.appveyor.com/project/conda-forge/scikit-image-feedstock/build/1.0.5/job/hamsfyua8lmm4kg2

https://github.com/conda-forge/scikit-image-feedstock/pull/2

**Comment by msarahan** [comment]
I think it's related to pypa/setuptools#728 - pinning setuptools to a 23.x release might work.
