### ISSUE TITLE
Consider reimplementing ``segmentation.relabel_sequential`` using ``np.digitize``

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1349]
Basic idea:

```
def remap_range(image):
    image = image.astype(int)
    unique_values = np.unique(image)
    index = np.digitize(image.reshape(-1,), unique_values) - 1

    return index.reshape(image.shape)
```

**Comment by spark1729** [comment]
I am new to scikit-image development and have recently been trying to understand the code base. When I came across this issue, I looked up at ``relabel_sequential ``, in the ``_join.py`` in ``segmentation`` module. I tried to understand the above mentioned implementation, I found that the subtraction of 1 in the ``digitize`` line was producing wrong indices. ``np.digitize `` directly gives the matrix `` relabeled  `` when implemented.

This is the re-modeled code that I tried out:

    def relabel_sequential(image, offset=1):
        m = image.max()
        if not np.issubdtype(image.dtype, np.int):
            new_type = np.min_scalar_type(int(m))
            image = image.astype(new_type)
            m = m.astype(new_type)  # Ensures m is an integer
    
        labels = np.unique(image)
        index = np.digitize(image.reshape(-1,), unique_values) 
        relabeled =  index.reshape(image.shape)
   
        forward_map = np.zeros(m + 1, int)
        forward_map[labels0] = np.arange(offset, offset + len(labels0))
        if not (labels == 0).any():
            labels = np.concatenate(([0], labels))
        inverse_map = np.zeros(offset - 1 + len(labels), dtype=np.intp)
        inverse_map[(offset - 1):] = labels
    
        return relabeled, forward_map, inverse_map
    
Are we to implement the find ``forward_map`` and ``inverse_map`` using ``relabeled``?

**Comment by spark1729** [comment]
I would really appreciate if anyone could point out any issues and guide me forward

**Comment by soupault** [comment]
Whoa! That is a very cool function!

**Comment by sinha-kirti** [comment]
Is anyone working on it at present? I would like to attempt it.

**Comment by jni** [comment]
@sinha-kirti there is a PR that has not received any attention in many months: https://github.com/scikit-image/scikit-image/pull/1531 You could try to start from that branch and:

- time the new version and the old version — is either faster?
- try to simplify the code
- rebase it on master

Then you can make a new PR with both the original commits and yours, to supersede the existing PR.

Thanks!

**Comment by sinha-kirti** [comment]
@jni Thanks for the consideration. I'll get started on it from today.

Cheers to this coding collaboration!

**Comment by jni** [comment]
Given the history of this issue and #1531, I'm going to close it. I don't think digitize offers a compelling advantage over the existing implementation.

I *will* point out that the current implementation is fragile around edge cases, because of the use of NumPy indexing for mapping. This means that the forward map has size `np.max(labels)`. I could give you the input `np.array([1, 1e10], dtype=int)`, and the resulting forward map would take up 80GB of memory. Therefore, creating a class that does the mapping as fast, and with the same `__getitem__` interface, but using reasonable memory, would be desirable.

**Comment by jni** [comment]
(But I don't consider this issue critical enough to warrant raising a new issue. @scikit-image/core feel free to disagree.)
