### ISSUE TITLE
Add skimage.future package, mention it in the documentation, move RAG code into it.

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1350]
This stems from a gitter discussion. The idea here would be to put in functionality for which we haven't quite nailed down the API, to enable fast iteration on it as more people use it. The functionality would be guaranteed to stay in skimage, but the API would not be expected to be stable from version to version and would not follow our standard deprecation paths.

The RAG code from @vighneshbirodkar fits this description: it's working and useful (and on master), but we have not extensively tested it in real-world scenarios, so we don't have a good idea of whether the API is suitable for all use cases.

**Comment by jni** [comment]
This needs to wait for #1100.

**Comment by vighneshbirodkar** [comment]
Hi
To achieve this, should I move all the code I have written under `skimage.graph` to `skimage.future.graph` ?

**Comment by jni** [comment]
Hi @vighneshbirodkar! Yes! I was actually planning to do this, but if you are feeling keen, go for it! But you'll need to be responsive over the coming week because we really want to get 0.11 out before next Saturday.

**Comment by vighneshbirodkar** [comment]
Hi @jni
I can't say for sure if I'll be able to find time this week. You can go ahead.

**Comment by blink1073** [comment]
Closed by #1365.
