### ISSUE TITLE
Bug in feature.peak_local_max leading to IndexError for ND arrays, N != 2

### ISSUE THREAD

**Issue by kevin-keraudren** [scikit-image/scikit-image#1354]
Hi,

There is a bug there:

https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/peak.py#L152

this line assumes that we are working with 2D arrays while the rest of the code is for ND arrays.

I propose the following fix:

    intensities = image.flat[np.ravel_multi_index(coordinates,image.shape)]

I usually follow the rule "if it's not broken, don't fix it", so you can ignore the following suggestion:

https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/peak.py#L149

    coordinates = np.transpose((image > peak_threshold).nonzero())

could be written:

    coordinates = np.argwhere(image > peak_threshold)

See http://docs.scipy.org/doc/numpy/reference/generated/numpy.argwhere.html

"np.argwhere(a) is the same as np.transpose(np.nonzero(a))."

Kind regards,

Kevin

**Comment by ahojnnes** [comment]
Hi Kevin,

All of what you write sounds right. Would you be willing to open a new PR to fix the issue and add a short test-case that covers the bug?

Thanks.

**Comment by kevin-keraudren** [comment]
Ok, I shall find some time before Monday.

**Comment by kevin-keraudren** [comment]
Actually, parameter multi_index must be a sequence of length len(image.shape), so we need to transpose coordinates to follow the requirements of np.ravel_multi_index:

    intensities = image.flat[np.ravel_multi_index(coordinates.transpose(),image.shape)]

**Comment by blink1073** [comment]
Closed by #1355, thanks @kevin-keraudren!
