### ISSUE TITLE
skimage.novice not handling alpha values (or maybe something worse)

### ISSUE THREAD

**Issue by gvwilson** [scikit-image/scikit-image#1358]
We'd like to use `skimage.novice` to teach image manipulation in Software Carpentry, but it looks like `skimage.novice` isn't handling alpha values correctly (though the problem may be deeper).

Test image is a shrunken survey map of Antarctic:

![ant](https://cloud.githubusercontent.com/assets/911566/5956124/ec8f23c4-a777-11e4-8d15-d32ffa153dbe.jpg)

Step 1: load and display using ipython 2.2.0 via conda 3.7.3 on Mac OS X 10.10.1:

~~~
In [1]: from skimage import novice
In [2]: p1 = novice.open('ant.jpg')
In [3]: p1.show()
~~~

![screen shot 2015-01-29 at 5 23 22 am](https://cloud.githubusercontent.com/assets/911566/5956100/b6e1caa6-a777-11e4-8ddc-cd4d15a7410f.png)

That's not right...

Step 2: paint the lower left green:

~~~
In [4]: p1.size
Out[4]: (120, 121)
In [5]: p1[0:60, 0:60] = (0, 255, 0)
In [6]: p1.show()
~~~

![screen shot 2015-01-29 at 5 24 02 am](https://cloud.githubusercontent.com/assets/911566/5956102/be1fda60-a777-11e4-8bcb-9a7f22ab8cb3.png)

Looks like alpha blending is going on.

Step 3: create a new blank white canvas:

~~~
In [7]: p2 = novice.Picture.from_size((200, 200), (255, 255, 255))
In [8]: p2.show()
~~~

![screen shot 2015-01-29 at 5 24 32 am](https://cloud.githubusercontent.com/assets/911566/5956106/c9872b2e-a777-11e4-8c7b-26ecb18a2c88.png)

That looks OK, but now color part of it green:

~~~
In [9]: p2[0:60, 0:60] = (0, 255, 0)
In [10]: p2.show()
~~~

![screen shot 2015-01-29 at 5 24 54 am](https://cloud.githubusercontent.com/assets/911566/5956119/e4e3828c-a777-11e4-8a53-f276d4dde3bf.png)

and the green doesn't show up at all.

**Comment by tonysyu** [comment]
Actually, this looks to be a bug with `io.imread`. The following gives the same results:

```python
from skimage import io
import matplotlib.pyplot as plt

image = io.imread('ant.jpg')
plt.imshow(image)
plt.show()
```

**Comment by jni** [comment]
@tonysyu is this true of master? Or just 0.10?

**Comment by tonysyu** [comment]
I'm running it on master. Using the image that @gvwilson shared, my normal image viewer shows the jet-like image, while the above code snippet shows a mostly white image.

**Comment by tonysyu** [comment]
A quick check suggests that the matplotlib backend works fine with this image, but the pil backend does not.

**Comment by jni** [comment]
@tonysyu @gvwilson Well... That sucks. =P

**Comment by tonysyu** [comment]
maybe it's a PIL vs pillow issue. I don't have pillow installed right now so I can't check.

**Comment by matthew-brett** [comment]
Current OSX wheels of Matplotlib and Pillow display an image like the initial image on this issue for me (round with blue background green / red interior).

**Comment by blink1073** [comment]
I'll take this one.

**Comment by blink1073** [comment]
Just some notes: 

- `pyplot.imread` works fine
- `imread.imread` yields a different image from skimage, but is still not right

![figure_1](https://cloud.githubusercontent.com/assets/2096628/5983691/1a9c4bca-a895-11e4-9f78-da1cb6e52a84.png)

**Comment by blink1073** [comment]
cc/ @tacaswell

**Comment by blink1073** [comment]
cc/ @almarklein

**Comment by blink1073** [comment]
I'd say `imageio` is the only one getting it right.

**Comment by blink1073** [comment]
Nice work @almarklein!

**Comment by tacaswell** [comment]
it looks like mpl just exposes a slightly different interface to PIL/pillow.

**Comment by tacaswell** [comment]
Digikam is telling me that this jpeg in CMYK encoded.  If that is the case then I suspect that the internal conversion CMYK -> RGB is the source of the problems and this is an upstream/weird(?) image problem.

**Comment by tacaswell** [comment]
exif tool is a bit less sure:

```
tcaswell@eowyn:~$ exiftool so.jpeg 
ExifTool Version Number         : 9.46
File Name                       : so.jpeg
Directory                       : .
File Size                       : 13 kB
File Modification Date/Time     : 2015:01:30 17:37:11-05:00
File Access Date/Time           : 2015:01:30 17:37:27-05:00
File Inode Change Date/Time     : 2015:01:30 17:37:26-05:00
File Permissions                : rw-r-----
File Type                       : JPEG
MIME Type                       : image/jpeg
DCT Encode Version              : 100
APP14 Flags 0                   : (none)
APP14 Flags 1                   : (none)
Color Transform                 : Unknown (RGB or CMYK)
Image Width                     : 120
Image Height                    : 121
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 4
Image Size                      : 120x121

```

**Comment by gvwilson** [comment]
But the image created by `novice.Picture.from_size` should be OK, shouldn't it?

**Comment by blink1073** [comment]
Right @gvwilson, there are two bugs here.

**Comment by blink1073** [comment]
@gvwilson, I have a fix, I'd like to add a test for CMYK images.  Is that image copyrighted?

**Comment by gvwilson** [comment]
Sorry, I don't know where the original came from or what its license is.

**Comment by almarklein** [comment]
> I'd say imageio is the only one getting it right.
> Nice work @almarklein!

Credit goes to http://freeimage.sourceforge.net/ :)
