### ISSUE TITLE
Cython version

### ISSUE THREAD

**Issue by jaimebayes** [scikit-image/scikit-image#1364]
Hi all,

After I run 
>>>print cython.__version__
it shows 0.21.2, I mean, the lastest version of cython. I have Anaconda suite installed on Ubuntu.

But, when I try to run 
>>>sudo python setup.py develop 
after merging origin/master, but It appears this error:
ImportError: You need `Cython` version 0.21 or later,found version 0.20.1post0.

How can I fix this error, because I want to work with Scikit-Image latest version.

Thanks in advance, Jaime

**Comment by blink1073** [comment]
@jaimebayes, try without the sudo.  Sudo grabs your system python instead of the Anaconda one (usually).

**Comment by jaimebayes** [comment]
Hi blink1073,

I try your suggestion, 
>>>python setup.py develop
but it shows this:
>>>IOError: [Errno 13] Permission denied: 'skimage/version.py'
How can overcome this one? Could it be the word 'develop'? I dont know.

Thanks, Jaime

**Comment by blink1073** [comment]
What is the output of `which python` and `sudo which python`?

**Comment by jaimebayes** [comment]
>>> which python
/home/jaimebayes/anaconda/bin/python
>>> sudo which python
[sudo] password for jaimebayes: 
/usr/bin/python

**Comment by blink1073** [comment]
Do you have user write access in the scikit-image directory?  `touch foo.tmp`

**Comment by jaimebayes** [comment]
>cd scikit-image/
>touch foo.tmp
>ls -l foo.tmp
-rw-rw-r-- 1 jaimebayes jaimebayes 0 feb  2 18:53 foo.tmp

**Comment by blink1073** [comment]
Hmmm, do you need to use `sudo` for `pip`?

**Comment by jaimebayes** [comment]
no, I dont need it.

**Comment by blink1073** [comment]
How about trying `pip install -e .`?

**Comment by JDWarner** [comment]
I've seen this before. Even if the package was installed without `sudo`, if you use `sudo` to try to compile it the compiled and generated files - one of which is `skimage/version.py` - will have elevated privileges. 

The solution is to run 
``` bash
sudo chown -R your_username_here ./*
```
in your skimage root directory. That should transfer all files to your user privilege level. Then run `python setup.py develop` again.

**Comment by blink1073** [comment]
@JDWarner, do you think it would be wise for us to call `os.chmod` on any files that we create (for this reason)?

**Comment by JDWarner** [comment]
`chmod` could be used to open up all files for reading, but I'm not sure I'd call that a great solution. Even though the risk is minor, it discloses to all users that scikit-image is present. Not sure why that could be an issue, but I just don't feel right mucking about with permissions. It's also worth noting a lot of packages work this way, so it's not confined to our package.

However, if we wanted to be clever... try this on for size. Instead of `os.chmod`, we assume the owner of `setup.py` is the desired owner of the package. Introspecting that can be done with

``` python
import os
import pwd

username = pwd.getpwuid(os.stat('./setup.py').st_uid).pw_name

# After install complete, execute os.chown recursively ...
# or just execute the shell command with -R flag in a subprocess
```

Still not completely convinced it's anything but a solution searching for a problem, but if we want to do something about this I'd feel better "restoring ownership."

**Comment by stefanv** [comment]
Can't we simply inform the user as to what's happening, and then have them execute any necessary instructions themselves?

**Comment by JDWarner** [comment]
@stefanv How does catching an `IOError` when `skimage/version.py` gets written to provide a useful message sound?

**Comment by stefanv** [comment]
It sounds non-magical yet effective!

**Comment by jaimebayes** [comment]
Hi,

Thank you @JDWarner <https://github.com/JDWarner>, your suggestions works
fine.I run setup.py already without errors.
I want to say thank you to @stefanv <https://github.com/stefanv> for his
interest that I resolve this soon.

Big hug friends,
Jaime

On Mon, Feb 2, 2015 at 8:05 PM, Josh Warner <notifications@github.com>
wrote:

> I've seen this before. Even if the package was installed without sudo, if
> you use sudo to try to compile it the compiled and generated files - one
> of which is skimage/version.py - will have elevated privileges.
>
> The solution is to run
>
> sudo chown -R your_username_here ./*
>
> in your skimage root directory. That should transfer all files to your
> user privilege level. Then run python setup.py develop again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scikit-image/scikit-image/issues/1364#issuecomment-72572554>
> .
>



-- 

*Jaime Lopez Carvajal*

**Comment by stefanv** [comment]
@JDWarner Are you going to put in a PR for this?

**Comment by jaimebayes** [comment]
Hi @JDWarner, sorry but I dont know what PR mean, could you explain me, please?

**Comment by blink1073** [comment]
Jaime, Stefan was asking JD to make a pull request - you're in the clear!  If you are interested, see the docs here:  http://scikit-image.org/docs/0.10.x/contribute.html

**Comment by jaimebayes** [comment]
Thanks @blink1073 for explanation, I will review the docs...maybe some day I can contribute to this great package.

**Comment by JDWarner** [comment]
@stefanv sure thing! I've got a couple minutes here...

**Comment by blink1073** [comment]
@jaimebayes, I'm calling this one closed.
