### ISSUE TITLE
Apparent error when trying to load an image from a URL?

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1369]
Haven't done any digging on this but am upset enough that it doesn't work out of the box to post it here. =P

```python
from skimage import io

coins = io.imread('https://github.com/scikit-image/scikit-image/blob/v0.10.1/skimage/data/coins.png')
print(type(coins), coins.shape, coins.dtype)
plt.imshow(coins)
```

Results in:

```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-9ac4ddbe14da> in <module>()
      1 from skimage import io
      2 
----> 3 coins = io.imread('https://github.com/scikit-image/scikit-image/blob/v0.10.1/skimage/data/coins.png')
      4 print(type(coins), coins.shape, coins.dtype)
      5 plt.imshow(coins)

/Users/nuneziglesiasj/anaconda/envs/py3k/lib/python3.4/site-packages/skimage/io/_io.py in imread(fname, as_grey, plugin, flatten, **plugin_args)
     95 
     96     with file_or_url_context(fname) as fname:
---> 97         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     98 
     99     if as_grey and getattr(img, 'ndim', 0) >= 3:

/Users/nuneziglesiasj/anaconda/envs/py3k/lib/python3.4/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    207                                (plugin, kind))
    208 
--> 209     return func(*args, **kwargs)
    210 
    211 

/Users/nuneziglesiasj/anaconda/envs/py3k/lib/python3.4/site-packages/skimage/io/_plugins/pil_plugin.py in imread(fname, dtype)
     21 
     22     """
---> 23     im = Image.open(fname)
     24     if im.mode == 'P':
     25         if _palette_is_grayscale(im):

/Users/nuneziglesiasj/anaconda/envs/py3k/lib/python3.4/site-packages/PIL/Image.py in open(fp, mode)
   2254 
   2255     raise IOError("cannot identify image file %r"
-> 2256                   % (filename if filename else fp))
   2257 
   2258 

OSError: cannot identify image file '/var/folders/25/dnnk9t55369c3s4g4_3zdq4h0000gn/T/tmpbz7et_58.png'
```

**Comment by jni** [comment]
Ok, so having followed the thread, I can't figure out why the `file_or_url_context` context manager is not doing its job. Can anyone else reproduce this on Python 3.4/skimage 0.10.1? (checking master now)

**Comment by r3vl1s** [comment]
I'm getting the same error with python 3.4 and 0.10.1.

**Comment by r3vl1s** [comment]
When I use this link I don't get the error:
https://raw.githubusercontent.com/scikit-image/scikit-image/v0.10.1/skimage/data/coins.png
I think it's because the link in your example doesn't point to the actual image despite it's extension.

**Comment by jni** [comment]
@r3vl1s fascinating! Thanks for the tip! Incidentally, it actually displays correctly in Markdown *in the notebook*. (Not here on github comments.)

I'm wondering whether, rather than a manual bytes copy, as is done with urlllib now, a "get" operation would be more effective and robust to redirects...

**Comment by stefanv** [comment]
+1 for following redirects

**Comment by vighneshbirodkar** [comment]
Hello guys.

The following code works fine for me
```python
from skimage import io
from matplotlib import pyplot as plt

coins = io.imread('http://bit.ly/1Du0YsO')
print(type(coins), coins.shape, coins.dtype)
io.imshow(coins)
io.show()
```

`urllib2` does follow redirects by default. What @jni entered is really a web page containing the image.

**Comment by jni** [comment]
A case of too much magic causing confusion! It looks like the markdown rendering in IPython notebook is being clever with GitHub links and automatically linking to the raw file! Thanks @vighneshbirodkar for the investigation! =)
