### ISSUE TITLE
Seam Carving

### ISSUE THREAD

**Issue by vighneshbirodkar** [scikit-image/scikit-image#1372]
Is [Seam Carving](http://en.wikipedia.org/wiki/Seam_carving) something that scikit-image would like to have ? A while back I had given it a shot in pure python and it was very slow, but with Cython code it should be practical.

Thoughts ?

**Comment by ahojnnes** [comment]
+1

This would definitely be a nice function to have!

**Comment by stefanv** [comment]
@vighneshbirodkar I had the same experience when I implemented it.  I have a student report that sums up the various methods quite well--I'll try and get hold of it.

**Comment by stefanv** [comment]
Also see: https://groups.google.com/forum/#!topic/scikit-image/UcetT7gwGyw

**Comment by RONNCC** [comment]
iirc this paper http://www.merl.com/publications/docs/TR2008-064.pdf had
pretty decent performance bounds - also a few hundred citations

**Comment by vighneshbirodkar** [comment]
@stefanv 
The link you posted on the mailing list does not work. Did you delete that branch ?

**Comment by stefanv** [comment]
This may be the same one, not sure: https://github.com/stefanv/scikit-image/tree/seam_carving

**Comment by vighneshbirodkar** [comment]
@RONNCC 
Is there any particular reason why a graph cut would out perform the DP approach in the [original paper](http://www.win.tue.nl/~wstahw/edu/2IV05/seamcarving.pdf) ?

The original approach just required one operation (a bunch of comparisons and additions) per pixel, for each seam removal. Won't the graph cut approach require a reconstruction of the graph after removing a single seam ?

**Comment by jni** [comment]
Addressed by #1459.
