### ISSUE TITLE
transform 2D matrix

### ISSUE THREAD

**Issue by Borda** [scikit-image/scikit-image#1373]
May I ask if there is a simple way how to transform an image which is a 2D matrix. I need to transform a segmentation (labeling) of an image. Actually I see an option to add 2 more colour channels even they are zeros and after all remove them...  
according http://scikit-image.org/docs/dev/api/skimage.transform.html#warp

**Comment by ahojnnes** [comment]
skimage.transform.warp works for N-D images, so also for 2-D. If not for you, please post a simple usage example.

**Comment by JDWarner** [comment]
Generally speaking all images we work with are dense n-dimensional arrays. With a rank of 2, they can be conceptualized as 2D matrices. 

Could you clarify and explain exactly what you mean by "transformation"? A *transformation* from our perspective is defined simply as a warping of the image. If you want to do something like map particular segmentation labels to colors, that would be a different task. We need a bit more info to help.

**Comment by Borda** [comment]
ok, my fault, it works with 2D matrixes if they are as float 0. - 1.

import matplotlib.pyplot as plt
import skimage.transform as imgTrans

seg = np.hstack(( np.zeros((10,5)), np.ones((10,5)), 2*np.ones((10,5)) )) +1
seg = np.array( seg, dtype=np.int)
plt.figure(), plt.imshow(seg), plt.axis('off')

alpha, t1, t2 = 30, 0, 0
img = np.asarray(seg) * 1.
tf_rotate = imgTrans.AffineTransform(rotation=np.deg2rad(alpha))
tf_shift_inv = imgTrans.AffineTransform(translation=[t1, t2])
tform = (tf_rotate + tf_shift_inv)

img = imgTrans.warp(img, tform.inverse, order=0)
segW = np.array( img , dtype=np.int)

plt.figure(), plt.imshow(segW), plt.axis('off')
plt.show()

**Comment by ahojnnes** [comment]
If you grab the latest version from github, you can use the preserve_range parameter to use values outside 0-1.

(btw, I just visited CMP a couple weeks ago, in case you remember me :-))

**Comment by Borda** [comment]
ok and is somewhere described, how to specify the new range? 
http://scikit-image.org/docs/dev/api/skimage.transform.html?highlight=warp#skimage.transform.warp

(btw, how did you like CMP? :)

**Comment by ahojnnes** [comment]
The documentation on the website is not yet updated, but it is in the doc string:

https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/_geometric.py#L1197
