### ISSUE TITLE
Question: ImageViewer and series of plugins

### ISSUE THREAD

**Issue by arve0** [scikit-image/scikit-image#1381]
Hi!
I'm trying to find a nice way to use a series of plugins for exploring my options on segmentation. In specific, I want to try out a combination of (7) pre-filters and (6) post-filters.

In [probabilistic_hough.py](../blob/master/viewer_examples/plugins/probabilistic_hough.py) an example with two plugins is shown. I want the same kind of workflow, but with the first window having the pre-filters and the second the post-filters.

I've tried naively to add two filters to ImageViewer, but as expected the last filter changed is the one that is rendered (as they both do an update to viewer.image).

My next though was to create a SeriesPlugins class, where one can append filters. When adding a filter it should create an extra image in a list, where the previous image in the list is the input for the filter added. The last image in the list should be the one that is sent to viewer.image. Does this sound like a good approach?

**Comment by blink1073** [comment]
Hi @arve0!  Personally, I would do the following:

```python
def link(plugin1, plugin2):
    plugin1.image_changed.connect(plugin2._update_original_image)
```

Where `plugin1` and `plugin2` are instances.

**Comment by blink1073** [comment]
Or, using public functions:

```python
def link(plugin1, plugin2);
    plugin1.image_change.connect(plugin2.image_viewer.update_image)
```

**Comment by arve0** [comment]
Sweet! Suspected there was an easy way. Thanks a lot! :octocat:

**Comment by arve0** [comment]
Btw, why is `update_image` implemented in [CollectionViewer](https://github.com/scikit-image/scikit-image/blob/master/skimage/viewer/viewers/core.py#L475-481) and not in `ImageViewer`?

**Comment by blink1073** [comment]
Ah, whoops!  That's because ImageViewer was never intended to have the original image change.  But now we see a use case.

**Comment by stefanv** [comment]
+1 for a consistent and well documented viewer API

**Comment by arve0** [comment]
Ended up with overriding `Plugin.attach` and `ImageViewer.__add__`, so that `ImageViewer.original_image_updated` doesn't trigger all plugins and thereafter the linked plugins (which results in a waterfall of `filter_image()`).

**Plugin.attach**
```
class Plugin(base.Plugin):
    "override attach"
    
    def attach(self, image_viewer):
        """Attach the plugin to an ImageViewer.
        Note that the ImageViewer will automatically call this method when the
        plugin is added to the ImageViewer. For example::
            viewer += Plugin(...)
        Also note that `attach` automatically calls the filter function so that
        the image matches the filtered value specified by attached widgets.
        """
        self.setParent(image_viewer)
        self.setWindowFlags(QtCore.Qt.Dialog)

        self.image_viewer = image_viewer
        if len(image_viewer.plugins) == 0:
            self.arguments = [image_viewer.image]
            image_viewer.original_image_changed.connect(self._update_original_image)
        else:
            self.arguments = [image_viewer.plugins[-1].arguments[0]]
            image_viewer.plugins[-1].image_changed.connect(self._update_original_image)
        
        image_viewer.plugins.append(self)
        self.filter_image()
```

**ImageViewer.__add__**
```
class ImageViewer(viewers.ImageViewer):
    "override plugin add to not emit plugin.update"
    
    #copied from scikit-image
    def __add__(self, plugin):
        """Add plugin to ImageViewer"""
        plugin.attach(self)
    #    self.original_image_changed.connect(plugin._update_original_image)

        if plugin.dock:
            location = self.dock_areas[plugin.dock]
            dock_location = Qt.DockWidgetArea(location)
            dock = QtWidgets.QDockWidget()
            dock.setWidget(plugin)
            dock.setWindowTitle(plugin.name)
            self.addDockWidget(dock_location, dock)

            horiz = (self.dock_areas['left'], self.dock_areas['right'])
            dimension = 'width' if location in horiz else 'height'
            self._add_widget_size(plugin, dimension=dimension)

        return self
```

**Comment by stefanv** [comment]
I think we should sit down and draw out a reasonable API that can hopefully later be transported to the javascript widgets.  Anyone interested?

**Comment by blink1073** [comment]
Perhaps @tonysyu and I can hammer this out properly at SciPy?

**Comment by stefanv** [comment]
@blink1073 That is an excellent suggestion.

**Comment by stefanv** [comment]
(Please include me in the discussions)

**Comment by blink1073** [comment]
Yessir, boss-man!

**Comment by tonysyu** [comment]
@blink1073: That sounds like a plan, although, I'd hope to get some sort of skeleton implementation well before that. (Coincidentally, I just started playing around the webagg implementation.)

We should definitely develop this with as much input from possible users as possible. We don't want to get in the situation where someone drops a bunch of code that no one else understands and just stops contributing ;)
