### ISSUE TITLE
Plugin.add_widget always override widget.callback

### ISSUE THREAD

**Issue by arve0** [scikit-image/scikit-image#1386]
Ex:

``` python
self.add_widget(CheckBox('enable', ptype='plugin', callback=self.fn))
```

CheckBox.callback will be [overridden](https://github.com/scikit-image/scikit-image/blob/9b16b35d961cab3f65885d385eb78cc932dd966f/skimage/viewer/plugins/base.py#L147).

But this will work:

``` python
cb = CheckBox('enable', ptype='plugin', callback=self.fn)
self.add_widget(cb)
cb.callback = self.fn
```

**Comment by arve0** [comment]
Adding to this: Setting callback to both `filter_image` and `update_plugin` creates bugs where you do not have `*args` in `filter_image` definition, as callback is allways called with signature `callback(name, value)`.

https://github.com/scikit-image/scikit-image/blob/9b16b35d961cab3f65885d385eb78cc932dd966f/skimage/viewer/plugins/base.py#L142

**Comment by blink1073** [comment]
Would having a private `_callback` and a public `callback` solve your first issue?  

For the second issue, you are trying to have two callbacks, one for `filter_image`, and one for `update_plugin` using the same `Plugin`?

**Comment by arve0** [comment]
> Would having a private _callback and a public callback solve your first issue?

No, I do not think so. As `viewer.plugins.Plugin.add_widget` is always overriding the callback, don't see how a public/private callback would solve this. Unless one wants several callbacks upon change, then there could be a private one too.

> For the second issue, you are trying to have two callbacks, one for filter_image, and one for update_plugin using the same Plugin?

I'm not trying to have two callbacks. Its just my confusion, as `filter_imager` doesn't take any arguments elsewhere in the code. I see now that it's in fact documented, but [below the docstring](https://github.com/scikit-image/scikit-image/blob/master/skimage/viewer/plugins/base.py#L161-162).

**Comment by blink1073** [comment]
Are you trying to override the default callback or provide an additional one?

**Comment by arve0** [comment]
I'm not overriding, I'm supplying callback to the widget: 

```python
my_widget = Widget('enable', ptype='plugin', callback=my_callback)
my_plugin.add_widget(my_widget) # this will override my_widget.callback
```

**Comment by arve0** [comment]
Ergo, the widget kw-argument `callback` has no meaning.

**Comment by arve0** [comment]
In general, this is a pattern that goes several places in the viewer API, which makes it hard to find the program flow. In example, plugins [append themselves](https://github.com/scikit-image/scikit-image/blob/master/skimage/viewer/plugins/base.py#L122) to the viewer, though the viewer [calls attach](https://github.com/scikit-image/scikit-image/blob/master/skimage/viewer/viewers/core.py#L249).

To me, it seems more clean to have the code modifying the object inside the same object. That way, reading the source for one class will give you a fairly good overview of all the internals of the class.

If this sounds fair, I'll gladly do some cleaning.

**Comment by JDWarner** [comment]
@arve0 I'm all for some refactoring in the name of clarity and maintainability. When working with the viewer in the past I've noticed I have to go hunting to figure out what is actually happening, but wasn't able to articulate it quite as nicely as you did just now.
