### ISSUE TITLE
skimage.feature.hessian_matrix_eigvals - probably mistake

### ISSUE THREAD

**Issue by Gregosh** [scikit-image/scikit-image#1389]
Maybe I didn't understand properly the code and method but I suspect small mistake in the code.

In the module skimage.feature exist function  - hessian_matrix_eigvals (line 257).

This function should calculate eigenvalues of the hessian matrix.
It is done by calling _image_orthogonal_matrix22_eigvals function in line 291.
 
But the arguments which are given to the function which calculates eigenvalues are : Hyy, Hxy, Hyy. 
It is my question. It is ok?

In my opinion there is a mistake, because these agruments shuld be: Hxx, Hxy, Hyy.

Thank you in advance for your time and response.

**Comment by ahojnnes** [comment]
That is indeed a bug. Would you mind filing a pull request with a fix?

Thanks for reporting.

**Comment by ahojnnes** [comment]
See issue #1391
