### ISSUE TITLE
slic superpixel compactness and enforce_connectivity crash

### ISSUE THREAD

**Issue by cxy7452** [scikit-image/scikit-image#1390]
Hi, I tried to use slic from skimage, and it seems that when enforce_connectivity is set to True, a low compactness value (how low to crash the program depends on the input image) crashes the program:

segments = slic(image, n_segments = 500, compactness = 2, enforce_connectivity = True)
**\* Error in `/usr/bin/python3.4': double free or corruption (!prev): 0x0000000003103540 ***
Aborted (core dumped)

when I turn off the enforce_connectivity parameter, then the problem no longer exist. However, enforce_connectivity is pretty important for my task, anyone (@amueller) know what is causing this issue? Thanks.

**Comment by cpu90** [comment]
Forgot to include some more details, my python version is 3.4.1 and using the latest scikit image which I downloaded just yesterday.

**Comment by jni** [comment]
@cpu90 looks serious! Can you provide a test image?

**Comment by cpu90** [comment]
Of course, the image can be downloaded here:
https://dl.dropboxusercontent.com/u/10279069/test.jpg

and the code that produced the crash is as followed:

from skimage.segmentation import slic
from skimage.util import img_as_float
from skimage import io

# load the image and convert it to a floating point data type
image = img_as_float(io.imread("test.jpg"))

# apply SLIC and extract (approximately) the supplied number
segments = slic(image, n_segments = 500, compactness = 2, sigma = 1, enforce_connectivity = True)


It appears that the value of sigma is not problematic, so is compactness when enforce_connectivity is set to False. But once enforce_connectivity is set to True, a lower compactness value (sometimes less than 3, sometimes less than 7, depending on different images) causes the crash.

**Comment by rorschach122** [comment]
I'm facing the same problem. I tried using try-except to no avail. Not sure where the error is.

**Comment by amueller** [comment]
I'll try to have a look but I can't promise anything ;)

**Comment by dzenteno2** [comment]
I'm facing exactly the same problem. I don't have experience in Cython, but I will try to understand better the issue.

Thank you in advance.

**Comment by dzenteno2** [comment]
I have been playing a little bit with the parameters and I have found that you could avoid the problem by adjusting min_size_factor and max_size_factor.

These are the parameters that did the trick for me:


            segments = segmentation.slic(input_data,
                                         n_segments=100,
                                         compactness=0.1,
                                         sigma=2.0,
                                         convert2lab=False,
                                         enforce_connectivity=True,
                                         min_size_factor=0.01,
                                         max_size_factor=20)

**Comment by soupault** [comment]
Can't replicate with Python neither `2.7.11` nor `3.5.1`. `Scikit-image` version is `0.11.3`.

**Comment by stefanv** [comment]
I haven't been able to replicate this problem either, but someone would need to run this through Valgrind or similar to ensure we don't leak any memory.

**Comment by soupault** [comment]
There are similiar issues though https://github.com/scikit-image/scikit-image/issues/1448 and https://github.com/scikit-image/scikit-image/issues/1635

**Comment by rfezzani** [comment]
Similar issues #1448 and #1635 being Fixed, I assume this one is also. Closing.
