### ISSUE TITLE
Add required libraries to setup.py

### ISSUE THREAD

**Issue by josephmisiti** [scikit-image/scikit-image#1400]
When I try to install `scikit-image` via `pip`, it fails and tells me I need `matplotlib` and `scipy`. Just added them to the requirements so they are installed by default.

**Comment by stefanv** [comment]
@josephmisiti They are already listed under ``requirements.txt`` as far as I can tell?

**Comment by stefanv** [comment]
Ah, I see what you mean--you want setup.py to be updated.

**Comment by matthew-brett** [comment]
Are scipy / matplotlib needed to install sckit-image?

**Comment by stefanv** [comment]
No, that's what I just realized--for usage, yes, for installation, no.

**Comment by matthew-brett** [comment]
Hmm.  Doesn't setup.py read requirements.txt already?   The wheel build failure is because of this - setup.py requires scipy : https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/53028183

**Comment by josephmisiti** [comment]
I just installed it in a fresh virtualenv and it failed multiple times because I was missing 4 libraries

**Comment by JDWarner** [comment]
I fixed this in scikit-fuzzy per https://caremad.io/2013/07/setup-vs-requirement/ via a standalone file. A separate text file for requirements can redirect `pip` to `setup.py` to pick up dependencies. 

```
#################################
# Requirements for scikit-fuzzy #
#################################
# The current requirements to install and run the package are stored in
# ./setup.py and are grabbed from there at install time via Pip.

-e .
```

**Comment by josephmisiti** [comment]
thanks!

**Comment by stefanv** [comment]
I don't think we need scipy anywhere, so we can relax this restriction.

**Comment by neothemachine** [comment]
Just do what other libraries are doing... add manual checks for your install-time dependencies and include the rest in `install_requires`. This is how it should be. How you avoid duplication with requirements.txt isn't relevant at this point. That's a separate problem.

**Comment by tacaswell** [comment]
Having every library maintain code to manually check for dependencies is a major community-level regression.

**Comment by neothemachine** [comment]
True, but what are the alternatives for install-time dependencies?

**Comment by tacaswell** [comment]
`conda` :smiling_imp:

**Comment by neothemachine** [comment]
Well played sir, well played! I agree that binary packages are a pain and that conda solves some of those issues. But going conda-only is probably also not the best idea. Maybe wheels will solve this problem for Linux as well in the future, but for now it looks like ugly setup.py's are still necessary...

**Comment by JDWarner** [comment]
While I like being platform and Python distribution agnostic as much as anyone, I feel obliged to point out that conda works great on Linux.

**Comment by neothemachine** [comment]
Oh yeah, I think I misphrased that a bit. I just wanted to say that wheels for Linux (if they ever come) may solve the same problem that conda already solved.
