### ISSUE TITLE
measure._ccomp

### ISSUE THREAD

**Issue by jaimebayes** [scikit-image/scikit-image#1401]
Hi friends,

Recently, I erased my scikit-image installation, and installed it again, but now I got this error:
ImportError: No module named measure._ccomp
I followed the same install steps, but now it doesnt work.
I just try to run this short piece of code:
>>> from skimage import graph, data, io, segmentation, color

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "skimage/segmentation/__init__.py", line 2, in <module>
    from ._felzenszwalb import felzenszwalb
  File "skimage/segmentation/_felzenszwalb.py", line 4, in <module>
    from ._felzenszwalb_cy import _felzenszwalb_grey
  File "_felzenszwalb_cy.pyx", line 1, in init skimage.segmentation._felzenszwalb_cy (skimage/segmentation/_felzenszwalb_cy.c:5563)
ImportError: No module named measure._ccomp

I have Ubuntu 14, 64-bit machine, Anaconda preinstalled, scikit-image 0.11.0
How can I fix this error?
thanks in advance, Jaime

**Comment by emmanuelle** [comment]
Hi @jaimebayes, how did you install scikit-image 0.11.0?

**Comment by jaimebayes** [comment]
Hi @emmanuelle 

I fix that problem already, it was related with use of sudo, I mean, when I installed using just 
>>> python setup.py develop
it works OK, but when I used 
>>> sudo python setup.py develop
it raised that ImportError, I dont know why exactly, because I run this before 
>>> chow -R jaimebayes ./* 
inside scikit-image directory to have all privileges there.

thanks, Jaime

**Comment by emmanuelle** [comment]
OK, so I think I can close the issue? It seems that the issue is more related to your installation, so I would recommend discussing it on the mailing-list if you encounter similar problems. 

Also, using "make clean" before installing might remove the ".so" file and solve the issue.

**Comment by jaimebayes** [comment]
OK, @emmanuelle, I will do next time.
Thanks for suggestion, Jaime
