### ISSUE TITLE
future.graph

### ISSUE THREAD

**Issue by jaimebayes** [scikit-image/scikit-image#1405]
Hi @blink1073 

Could you explain me how to install this module (future.graph)?, because I followed these two install instructions but they didn't work.

On windows:
>>>pip install scikit-image --upgrade

On ubuntu: 
>>>cd scikit-image
>>>git checkout master
>>>git fetch origin
>>>git merge origin/master
>>>sudo python setup.py develop

Or how I pull the commit related to this module?

thanks in advance, Jaime

**Comment by JDWarner** [comment]
Couple quick things to check:

You are attempting to import using `from skimage.future import graph`, right? `import future.graph` will not work - it exists only within our package's namespace.

Second, the Ubuntu install/develop method just pulls down the Git repo you cloned. If you cloned the main scikit-image/scikit-image repo, then that should work to keep everything up to date. If you cloned your personal fork, though, it will not. I just checked and your personal fork is over 1,000 commits behind upstream/master. We can help you fix this, but we need to know how your Git repo is configured. Run

```bash
git remote show
```

then for each name shown (there will be at least one named "origin") run

```bash
git remote show [name]
```

and paste the results here.

**Comment by jaimebayes** [comment]
Hi @JDWarner, 

this is the results I got following your suggestion:
~/scikit-image$ git remote show
origin
jaimebayes@jaimebayes-OptiPlex-755:~/scikit-image$ git remote show origin
* remote origin
  Fetch URL: http://github.com/scikit-image/scikit-image.git
  Push  URL: http://github.com/scikit-image/scikit-image.git
  HEAD branch: master
  Remote branches:
    debian                               tracked
    master                               tracked
    revert-1274-use-wheelhouse-simpleitk tracked
    v0.10.x                              tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (local out of date)

**Comment by JDWarner** [comment]
OK, so you are tracking the upstream repo. Did the command `python setup.py develop` complete successfully? What happens when you open a Python shell and attempt to run `from skimage.future import graph`?

**Comment by jaimebayes** [comment]
Hi, 

Yeah, It runs successfully with sudo, I mean:
>>>sudo python setup.py develop

When I run from skimage.future import graph, I got this:

Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Dec 15 2014, 10:33:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from skimage.future import graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "skimage/future/__init__.py", line 8, in <module>
    from . import graph
  File "skimage/future/graph/__init__.py", line 2, in <module>
    from .rag import rag_mean_color, RAG, draw_rag
  File "skimage/future/graph/rag.py", line 17, in <module>
    from ... import draw, measure, segmentation, util, color
  File "skimage/draw/__init__.py", line 1, in <module>
    from .draw import circle, ellipse, set_color
  File "skimage/draw/draw.py", line 3, in <module>
    from ._draw import _coords_inside_image
  File "_draw.pyx", line 1, in init skimage.draw._draw (skimage/draw/_draw.c:23696)
ImportError: No module named _shared.geometry

**Comment by JDWarner** [comment]
Does it fail without `sudo`? Anaconda shouldn't require elevated privileges.

I just built and compiled successfully on Windows 7 x64. `import skimage; print(skimage.__version__)` yields 0.12dev, and `from skimage.future import graph` works and is populated properly.

**Comment by jaimebayes** [comment]
Yes, it fails without sudo...

jaimebayes@jaimebayes-OptiPlex-755:~/scikit-image$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 125, in <module>
    write_version_py()
  File "setup.py", line 79, in write_version_py
    vfile.close()
UnboundLocalError: local variable 'vfile' referenced before assignment

scikit-image version:
>>> import skimage
>>> print skimage.__version__
0.11.0

Could you recommend that I erase the whole scikit-image folder and clone it again?

Jaime

**Comment by JDWarner** [comment]
Go ahead and try that. The "scorched earth" method is essentially guaranteed to fix the permissions. It will destroy any local branches you haven't pushed up, but is the easiest fix.

Alternatively, from package root you can run (note carefully the dot before the slash)

```bash
sudo chown -R your_username ./*
```

to recursively change ownership of all files lower in the tree to your_username.

**Comment by JDWarner** [comment]
@jaimebayes marking this issue resolved - if it isn't, feel free to reopen.
