### ISSUE TITLE
BUG: Website `Table of contents` for 0.11.x returns 404

### ISSUE THREAD

**Issue by opyate** [scikit-image/scikit-image#1409]
http://scikit-image.org/docs/0.11.x/contents.html is a broken link.

**Comment by opyate** [comment]
Generally some content issues, e.g. "line" is not in module "draw", see http://scikit-image.org/docs/0.11.x/api/skimage.draw.html#line

**Comment by stefanv** [comment]
Sorry, I don't understand: line is in the module draw?  Are you running 0.11?

**Comment by ahojnnes** [comment]
@stefanv He means, that the line function does not appear in the documentation on that page, even though it should.

**Comment by stefanv** [comment]
Ah, I see!
​

**Comment by emmanuelle** [comment]
thank you @opyate . It's true that clicking on the "table of contents" link from the documentation page links to a broken link from http://scikit-image.org/docs/dev/ (not the case for http://scikit-image.org/docs/0.10.x/contents.html)

**Comment by soupault** [comment]
`Table of Contents` had been removed after the release of `0.10`.
I've cleaned up these dead links in 0.11 page with https://github.com/scikit-image/docs/commit/a4ee4fb1a735912f94f12dbc61e9cb0c2e8f0f21.
