### ISSUE TITLE
Drawing Region Adjacency Graphs (RAGs) error

### ISSUE THREAD

**Issue by daniorerio** [scikit-image/scikit-image#1410]
I tried out the plot_rag_draw.ipynb notebook and couldn't get it to run with the error:
...
/Users/xxx/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/skimage/measure/_regionprops.pyc in moments(self)
    236     @_cached_property
    237     def moments(self):
--> 238         return _moments.moments(self.image.astype(np.uint8), 3)
    239 
    240     @_cached_property

/Users/xxx/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/skimage/measure/_moments.so in skimage.measure._moments.moments (skimage/measure/_moments.c:1415)()

ValueError: Buffer dtype mismatch, expected 'double' but got 'unsigned char'

I have 0.11.2 installed.

thanks!

**Comment by emmanuelle** [comment]
hi @daniorerio !
how did you install 0.11.2? With pip install? From github?

**Comment by daniorerio** [comment]
Thanks for the reply.  I used 
pip install -U scikit-image
on an OSX machine with Enthought Canopy python.

**Comment by emmanuelle** [comment]
OK, thanks. When you run the python script within the Ipython shell (not the notebook), do you get the same error?

**Comment by buratono** [comment]
I got a similar problem, when I access regionprops.centroid
Can somebody help me?
(I'm running Windows 7 64-bit, Python 2.7, pip install)

    region_props[t][0:2] = [regions[largest_region_id].centroid]
  File "C:\Anaconda\lib\site-packages\skimage\measure\_regionprops.py", line 129, in centroid
    row, col = self.local_centroid
  File "C:\Anaconda\lib\site-packages\skimage\measure\_regionprops.py", line 209, in local_centroid
    m = self.moments
  File "C:\Anaconda\lib\site-packages\skimage\measure\_regionprops.py", line 103, in __get__
    value = self.func(obj)
  File "C:\Anaconda\lib\site-packages\skimage\measure\_regionprops.py", line 238, in moments
    return _moments.moments(self.image.astype(np.uint8), 3)
  File "_moments.pyx", line 8, in skimage.measure._moments.moments (skimage\measure\_moments.c:1470)
ValueError: Buffer dtype mismatch, expected 'double' but got 'unsigned char'

**Comment by JDWarner** [comment]
(removed unrelated comment)

**Comment by jni** [comment]
@daniorerio did you resolve this issue?

**Comment by daniorerio** [comment]
Yes, problem with enthought canopy, not scikit image
