### ISSUE TITLE
Trivial tests in morphology/test.binary.py ?

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1418]
In https://github.com/scikit-image/scikit-image/blob/master/skimage/morphology/tests/test_binary.py#L11,
assigning `bw_img = img > 100`  results in a zero-only array `bw_img`, since `img` takes values in [0, 1]. 

Hence, all tests of test_binary.py that use `bw_img` are not very meaningful...

I checked rapidly what happens when changing the threshold, e.g. from 100 to 100./255, and tests fail in that case. 

I will investigate this issue and submit a PR when I find a bit of time, but I thought I'd first submit an issue for the record.

**Comment by jni** [comment]
Holy moly! =\

**Comment by soupault** [comment]
Closed via #2945
