### ISSUE TITLE
median filter is only available for integer-type images

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1419]
`filters.median` only operates on integer images. For float images, we could return the output of `ndimage.median_filter`.

**Comment by jni** [comment]
:+1: ! Have a look at the `default_fallback` decorator in `morphology.misc`. Solves exactly the same problem for morphological functions. (Or it did prior to 0.11, actually.)

**Comment by glemaitre** [comment]
I was thinking to pick up this issue.

The suggestion was to use the SciPy functions. Would it make sense to adapt the Cython code instead to deal with floating images instead?

**Comment by glemaitre** [comment]
OK I see. So defaulting on the scipy depending on the dtype would still be correct then.

**Comment by stefanv** [comment]
It's probably not great to have different implementations for ints and floats, especially not in different packages. Then, rather two implementations, with a "See Also" referring to the other location.

**Comment by emmanuelle** [comment]
OK, here is what I suggest: how about
- ``skimage.filters.median`` calls ``ndimage.median_filter`` for all data types
- and ``skimage.filters.rank.median`` is imported from the ``rank`` submodule only, and only for integer data types?

**Comment by glemaitre** [comment]
`ndimage.median_filter` does not support an option `mask`. I could deprecate the parameter and fallback to the `skimage.rank.median` for 2 release cycle.
I also have to check the `mode` policy for the borders to be sure that both implementation will given similar results.
