### ISSUE TITLE
sciki-image fails to install from pypi unless networkx is present

### ISSUE THREAD

**Issue by jbwexler** [scikit-image/scikit-image#1427]
networkx should be an explicit dependency in setup.py

**Comment by blink1073** [comment]
We're working on this: see #1426.

**Comment by blink1073** [comment]
@jni, @stefanv, how about we take the following tack:  we designate `six` and `scipy` as "core" requirements, and break on those.  Then, we test for the presence of the rest and issue a harsh warning if they are not present.  This is similar to the way matplotlib handles it.

**Comment by blink1073** [comment]
I add `scipy` to that list because there are whole subpackages that break if `scipy` is not available.

**Comment by jni** [comment]
@blink1073 I'm completely agnostic as to which decision we take with regards to dealing with missed requirements. Your approach sounds reasonable.

**Comment by stefanv** [comment]
@blink1073 Is the approach in #1426 insufficient?

**Comment by blink1073** [comment]
@stefanv, I've been poking hard at this and here's what I've come up with:
- Right now, we are calling `check_requirements` before anything else, which is preventing `install_requires` from ever being run.
- `install_requires` runs *after* the build extension step in `setup`, which means we can't pick up `cython`, and since we do not ship the `cython` c-files, the user is sunk.

**Comment by blink1073** [comment]
Aha, we need to use `setup_requires` for `cython`.

**Comment by blink1073** [comment]
I can make the whole thing work using `setup_requires` and `install_requires` if we require Pillow explicitly instead of PIL.

**Comment by blink1073** [comment]
I would change `requirements.txt` to be just `-e .`, and use the following in `setup.py`:

```python
SETUP_REQUIRES = 'cython>=0.21'
INSTALL_REQUIRES = """
matplotlib>=1.1.0
numpy>=1.6.1
scipy>=0.9
six>=1.3
networkx>=1.8
pillow>=1.7.8
""".strip().splitlines()
```
