### ISSUE TITLE
Implement Haar-like features

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1431]
https://en.wikipedia.org/wiki/Haar-like_features

**Comment by syedTabish** [comment]
@stefanv  this one seems related to #953. I'll have to my lazy self to revisit that PR. I'll finish it up when I get time this weekend.

**Comment by JDWarner** [comment]
@syedTabish that would be great, thanks!

**Comment by spark1729** [comment]
@JDWarner @stefanv 
1. How is the implementation of this to be done ? As in, should there be a function evaluating the haar feature at a point (x,y) and for a two rectangle feature of (h,w). 

Evaluating a two rectangle horizontal feature: 

    def haar_feature(x,y,h,w):
    bright = (i[x+h-1,y+w-1]+i[x-1,y-1])-(i[x-1,y+w-1]+i[x+h-1,y-1])       
    dark = (i[x+2*h-1,y+w-1]+i[x+h-1,y-1])-(i[x+h-1,y+w-1]+i[x+2*h-1,y-1])
    haar_feature = bright-dark    
      // i is the integral image

**Comment by spark1729** [comment]
@JDWarner @stefanv 
1. How is the implementation of this to be done ? As in, should there be a function evaluating the haar feature at a point (x,y) and for a two rectangle feature of (h,w).

Evaluating a two rectangle horizontal feature:

    def haar_feature(i,x,y,h,w):
    bright = (i[x+h-1,y+w-1]+i[x-1,y-1])-(i[x-1,y+w-1]+i[x+h-1,y-1])       
    dark = (i[x+2*h-1,y+w-1]+i[x+h-1,y-1])-(i[x+h-1,y+w-1]+i[x+2*h-1,y-1])
    haar_feature = bright-dark    
    // i is the integral image

Not the final code. conditional statements will be added.

**Comment by spark1729** [comment]
import numpy as np
    from skimage import data
    from skimage.transform import integral_image

    feature = np.array([[2,1],[1,2],[3,1],[1,3],[2,2]])
    framesize=24
    features=5
    count =0
    haar_features1=np.empty((0,0))
    image=data.coins()
    im=integral_image(image)

    def haar_feature(integral_image,x,y,height,width,feature):
        if feature=1:
            bright = (i[x+h-1,y+w-1]+i[x-1,y-1])-(i[x-1,y+w-1]+i[x+h-1,y-1])       
            dark = (i[x+2*h-1,y+w-1]+i[x+h-1,y-1])-(i[x+h-1,y+w-1]+i[x+2*h-1,y-1])
            haar_feature = bright-dark    
            return haar_feature
    
    for i in range(features):
        sizeX = feature[i][0]
        sizeY = feature[i][1]
        width =sizeX
    
        for width in range(sizeX,framesize,sizeX):
            for height in range(sizeY,framesize,sizeY):
                for x in range(0,framesize-height,1):
                    for y in range(0,framesize-height,1):
                        haar_features1=np.append(haar_features1,haar_feature_horizontal(im,x,y,sizeX,sizeY,i))
                        count =count+1
                        
                
    print count
    print haar_features1

I have implemented the function for extracting haar features. 
I have worked alonside the Voila Jones publication
The code given above calculates the horizontal 2 rectangle haar feature and also computes the number of features for every 24 pixel frame.
the result of execution of the program is 


        haar_implementation.py:16: RuntimeWarning: overflow encountered in ulong_scalars
          dark = (i[x+2*h-1,y+w-1]+i[x+h-1,y-1])-(i[x+h-1,y+w-1]+i[x+2*h-1,y-1])
        haar_implementation.py:17: RuntimeWarning: overflow encountered in ulong_scalars
          haar_feature = bright-dark
        haar_implementation.py:15: RuntimeWarning: overflow encountered in ulong_scalars
          bright = (i[x+h-1,y+w-1]+i[x-1,y-1])-(i[x-1,y+w-1]+i[x+h-1,y-1])
        175628
        [  1.12387020e+07   1.84467441e+19   1.84467441e+19 ...,   1.84467441e+19
          0 1.84467441e+19   4.30000000e+01]
 

The result has come as 175628 which is in accordance with the paper which say about 180000 features are calcuated.
I would appreciate if anyone could help in resolving the  RuntimeWarning  

Some Links that i followed
http://en.wikipedia.org/wiki/Viola%E2%80%93Jones_object_detection_framework
http://www.vision.caltech.edu/html-files/EE148-2005-Spring/pprs/viola04ijcv.pdf

**Comment by glemaitre** [comment]
This could probably be closed :)
