### ISSUE TITLE
`hough_line` function is not included in API docs

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1435]
See live docs for `skimage.transform` in http://scikit-image.org/docs/dev/api/skimage.transform.html

Despite this being a publicly exposed function available in the package, it is absent from the docs.

**Comment by JDWarner** [comment]
Follow up and verify this is fixed once #1432 is merged.

**Comment by bennlich** [comment]
The same is true for `skimage.transform.probabilistic_hough_line`.

**Comment by JDWarner** [comment]
@stefanv this should be fixed as of #1468, but I'm not seeing it in the live dev docs yet. Do they need to be manually pushed?

**Comment by stefanv** [comment]
I've rebuilt and pushed the docs.
