### ISSUE TITLE
ImageCollection broken when using freeimage

### ISSUE THREAD

**Issue by raubtaube** [scikit-image/scikit-image#1439]
Basically this one below breaks, with scikit-image 0.12 and freeimage-3.15.4.  
```python
io.use_plugin('freeimage')
ic = ImageCollection( join(dir, '*.png' ) )
img = ic[0]
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-cb6c412db3ff> in <module>()
----> 1 create_single_epi(dir, rows/2, pix_shift = 0 )

/export/home/mgutsche/scripts/HelperFunctions/create_epis.py in create_single_epi(dir, row, pix_shift)
     19     io.use_plugin('freeimage')
     20     ic = ImageCollection( join(dir, '*.png' ) )
---> 21     rows, cols, channels = ic[0].shape
     22     if channels >= 4:
     23         channels = 3

/export/home/mgutsche/anaconda/lib/python2.7/site-packages/skimage/io/collection.pyc in __getitem__(self, n)
    258                     fname, img_num = self._frame_index[n]
    259                     self.data[idx] = self.load_func(fname, img_num=img_num,
--> 260                                                     **self.load_func_kwargs)
    261                 else:
    262                     self.data[idx] = self.load_func(self.files[n],

/export/home/mgutsche/anaconda/lib/python2.7/site-packages/skimage/io/_io.pyc in imread(fname, as_grey, plugin, flatten, **plugin_args)
     95 
     96     with file_or_url_context(fname) as fname:
---> 97         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     98 
     99     if as_grey and getattr(img, 'ndim', 0) >= 3:

/export/home/mgutsche/anaconda/lib/python2.7/site-packages/skimage/io/manage_plugins.pyc in call_plugin(kind, *args, **kwargs)
    205                                (plugin, kind))
    206 
--> 207     return func(*args, **kwargs)
    208 
    209 

TypeError: imread() got an unexpected keyword argument 'img_num'
```

**Comment by jni** [comment]
@raubtaube can you check that the latest master fixes this? Thanks for reporting!

**Comment by raubtaube** [comment]
@Juan, You're welcome! I would check the latest fix if there is an easy way
to get the latest master using conda. Everything beyond pip install and
conda install, is a new territory for me.

2015-03-25 4:23 GMT+01:00 Juan Nunez-Iglesias <notifications@github.com>:

**Comment by jni** [comment]
@raubtaube teaching time! =)

1. create new environment with `conda create -n skimage-master-test cython matplotlib numpy scipy six networkx pillow`
2. activate the environment with `source activate skimage-master-test`
3. install scikit-image master with pip using `pip install git+https://github.com/scikit-image/scikit-image.git`. No git usage required!
4. give it a try! =)

The only kink in that plan is that it might not pick up your system freeimage...

**Comment by raubtaube** [comment]
Hi,

it took a while and I followed your steps. Unfortunately the same error
persists with skimage.__version__ = '0.12dev'... This time the error also
appears without using freeimage...



2015-03-25 10:16 GMT+01:00 Juan Nunez-Iglesias <notifications@github.com>:

**Comment by blink1073** [comment]
@raubtaube, I'm not sure what to say.  I tried your example with and without `freeimage` using the latest master and it works fine for me.

**Comment by stefanv** [comment]
I'm afraid I cannot reproduce this behavior either.
