### ISSUE TITLE
Maintain a changelog

### ISSUE THREAD

**Issue by neothemachine** [scikit-image/scikit-image#1445]
Using scikit-image in production is slightly tricky without knowing whether a new version introduced breaking changes. Please maintain a changelog, it's a good thing to have in general as well, and no, the git log is not a changelog, it's way too detailed. :)

For example, between 0.10.1 and 0.11.0 you added more dependencies, and as the setup.py script currently is written to just [bomb out](https://github.com/scikit-image/scikit-image/issues/1400) on missing dependencies instead of installing them (for runtime dependencies) this is a massive breaking change I just stumbled upon. And as the version scheme is not following semantic versioning one has to spend a lot of effort to find out whether a new version of skimage will break the build or not.

**Comment by tacaswell** [comment]
mpl has effectively abandoned the changelog for the followring

 - explicit list of API changes (api_changes.rst)
 - explicit list of new futures (whats_new.api)
 - using the merge PRs commit messages as changelog like entries

**Comment by stefanv** [comment]
@neothemachine All API changes are documented in the release notes.  No breaking changes are made on minor versions (i.e., 0.10.0 to 0.10.1, e.g.).  The setup script has been fixed.

**Comment by neothemachine** [comment]
Where are the release notes? I didn't find them in the repo and neither attached to the github release or git tag.

**Comment by JDWarner** [comment]
Release notes are on the homepage - could probably be linked a bit easier
to find, currently available in Documentation -> API (*Changes*)
http://scikit-image.org/docs/stable/api_changes.html

The source file is located at
https://github.com/scikit-image/scikit-image/blob/master/doc/source/api_changes.txt

**Comment by neothemachine** [comment]
So release notes = API changes? What about new features or important bugfixes?

**Comment by JDWarner** [comment]
I apologize, full release notes are here
https://github.com/scikit-image/scikit-image/blob/master/doc/release/release_0.11.txt

**Comment by neothemachine** [comment]
Ok, that's great to see :) This definitely has to be linked prominently from somewhere.

**Comment by stefanv** [comment]
Good idea--help us with a suggestion or a pull request!

**Comment by neothemachine** [comment]
How about creating a hyperlink with "(release notes)" next to the "Stable" text on the top right of the website linking to the relevant release notes (direct link to github, then it's easy to find the older ones as well). As you seem to have only minor version release notes you could do that by using only the first two version components, "0.11" and then linking to https://github.com/scikit-image/scikit-image/blob/master/doc/release/release_0.11.txt. As you already have javascript in place for fetching the version info this should be easy I guess.

**Comment by JDWarner** [comment]
Alternatively or in conjunction, we could link to the release notes under Announcements for each announced major release.

**Comment by neothemachine** [comment]
Yes, I would do that in addition. The thing is I don't scroll down as soon as I find the version information on the top right. Currently I expected the release notes when clicking on the download button, but putting them (the link to them) directly into the initial field of view (as described earlier) would be better I think.

**Comment by stefanv** [comment]
Would you please make a PR?  I'd be happy to rebuild the website.

**Comment by neothemachine** [comment]
https://github.com/scikit-image/scikit-image-web/pull/24
