### ISSUE TITLE
ImageCollection loads images prematurely

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1447]
``ImageCollection('*.jpg')`` loads all JPG images, even when conserve_memory is set to True.  What used to be an instantaneous operation is now very slow.

/cc @blink1073

**Comment by blink1073** [comment]
How many images are in that folder?  I did a quick check and `conserve_memory` is still being respected, in that the `data` member is only populated when it is False.  However, we are now *opening* each file to see how many images it contains.  That could be what you're seeing.

**Comment by stefanv** [comment]
Yes, I think we may have to change that--I have 2000 images in my folder,
and it takes forever.
​

**Comment by blink1073** [comment]
Then we'd have no way of knowing which if any files had multiple images in them.  Tough nut here...

**Comment by jni** [comment]
@blink1073 

- do we need to know this in advance?
- maybe we can only check tifs?
- when you open each image, I presume it's loading up the whole image. For TIFFs, it should be possible to check the number of pages just by looking at the header. (Though this might require learning more about the format than you care to find out!)

**Comment by blink1073** [comment]
Right now we support TIFFs and GIFs.  This is turning out to be a major source of confusion.  Perhaps image collection should only deal with flat images, and leave it up to imread whether to allow indexing on image number.

**Comment by jni** [comment]
Even just turning off checking for any file that's not a TIFF and GIF would fix @stefanv's use case. Gotta keep the boss happy. =P

**Comment by blink1073** [comment]
Works for me.

**Comment by stefanv** [comment]
I would argue that "the boss" should keep everyone else happy, but hey... I
appreciate the thought :)
