### ISSUE TITLE
Add support for multipage tiff files with the freeimage plugin

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1450]
Currently, our Freeimage TIFF reader just reads the first plane of a multipage tiff and calls it a day. It would be good to figure out how to support multipage tiff properly. (Though tifffile handles it admirably, users might set freeimage for whatever reason, and be stuck with buggy code.)

See #1440 for a related issue.

**Comment by jakirkham** [comment]
As an end user, not a huge fan of this becoming dependent on freeimage for this reason. ( https://github.com/scikit-image/scikit-image/issues/1605#issuecomment-120953609 )

Not having CI is a bit scary. Building freeimage, from past experience, required some serious patching. They pin the compiler version to gcc-4.0, which seems unnecessary. If it is necessary, I am worried. Sticking to CVS long after support is gone is also scary.

**Comment by JDWarner** [comment]
We ship tifffile. Is there any reason a multipage tiff _shouldn't_ be read using tifffile? In the short term, I'd say just read all multipage TIFFs with tifffile, potentially emitting a warning telling the user that we encountered such a file and are using the appropriate backend, instead of what they specified.

I'm only comfortable with this because the Freeimage behavior is buggy/broken.

**Comment by blink1073** [comment]
We're already doing that in the PIL plugin: https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_plugins/pil_plugin.py#L43

**Comment by jakirkham** [comment]
`tifffile` works great. Normally, I use either that or `pylibtiff` (believe it is not called `libtiff` confusingly).

**Comment by JDWarner** [comment]
@blink1073 lovely - Do you want to patch it, or shall I?

**Comment by blink1073** [comment]
Do we want to do this here instead? https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_io.py#L17

**Comment by JDWarner** [comment]
Yes, agreed, catch it before any plugins get called. Also document in the Notes that tifffile will always be used when reading .TIF[F] files.
