### ISSUE TITLE
Appveyor builds take to long to be useful.

### ISSUE THREAD

**Issue by blink1073** [scikit-image/scikit-image#1456]
The Appveyor builds run in serial, as opposed to Travis.  I suggest we limit the Appveyor build to one 32bit build.  The Python 3.4 build has been randomly timing out, so I'd suggest the Python 2.7 one.

**Comment by JDWarner** [comment]
Agreed, though the serial nature isn't the only problem. I've documented occasions where no job in a build has started after 4+ hours in the queue. That really affects an efficient workflow, and I've merged low risk or time sensitive PRs on basis of Travis alone.

**Comment by stefanv** [comment]
FWIW, I met with someone from Microsoft about this and there is a solution
on the horizon.

In the meantime, perhaps we should switch to an internally hosted Windows
machine?  I have access to one of those, if someone is willing to take up
the administrative load of setting up a buildbot.

**Comment by blink1073** [comment]
I'm not sure if any of us have that expertise.  :smile:  
I still vote to go down to one build on Appveyor until they make improvements.

**Comment by stefanv** [comment]
OK, let's do that for now--we really just need it as a backup check.
​

**Comment by matthew-brett** [comment]
I'm happy to set up the buildbot.

**Comment by stefanv** [comment]
That would be very helpful, Matthew.  Which build system do you recommend
for tying in with GitHub?
