### ISSUE TITLE
orb.detect_and_extract returns IndexError for faint images

### ISSUE THREAD

**Issue by indiajoe** [scikit-image/scikit-image#1472]
While using ORB ("Oriented FAST and rotated BRIEF") feature detector from skimage.feature
on a faint image, It is returning IndexError.
It works perfectly on bright images with lots of features.
My doubt is, why is it raising an IndexError, shouldn't it be instead raising some error which tells user the image is too faint to detect any feature, or probably just return an empty list for detected feature?

Following is how to reproduce the error.
I have kept the sample 8MB grayscale image (.npy) in the link here  https://drive.google.com/file/d/0B7lhjArL8VfLVW5BTmFQSEtQT28/view?usp=sharing

```
img = np.load('FaintImage.npy')
from skimage.feature import ORB
orb = ORB(n_keypoints=4000, fast_threshold=0.05)
orb.detect_and_extract(img)
```

It will raise an IndexError: list index out of range

**Comment by vighneshbirodkar** [comment]
@indiajoe , you are right, while going through the code, I was very puzzled as to what this `if` block is trying to achieve.
https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/orb.py#L305

**Comment by dcd2** [comment]
I can confirm this behaviour as well. I've had some luck with equalizing the histogram of the image, but this doesn't always work. I agree w/ @indiajoe , it would be nice if ORB would just return an empty list of features.

**Comment by rfezzani** [comment]
Running the code of @indiajoe, no more IndexError is raised but a
```python
RuntimeError: ORB found no features. Try passing in an image containing greater intensity contrasts between adjacent pixels.
```
Closing. Feel free to reopen ;-)
