### ISSUE TITLE
'slic' function hangs when used in a multiprocessing framework.

### ISSUE THREAD

**Issue by gongenhao** [scikit-image/scikit-image#1473]
slic and quickshift hangs in the multiprocessing (multiprocessing.Pool.map())
but felzenszwalb works.

**Comment by stefanv** [comment]
Any idea why?  Also, can you provide a minimal code snippet to reproduce?

**Comment by jni** [comment]
@stefanv sorry, this slipped through, but I have seen this behaviour as well. I have no idea what's causing it though as I have only a passing understanding of the various parallel frameworks...

I'm on OSX, in case it helps. @gongenhao what about you?

**Comment by gongenhao** [comment]
@jni 
I am also on OSX. I will try to provide an example code to reproduce.

**Comment by soupault** [comment]
@gongenhao, hi! How is it going with example? :)

**Comment by soupault** [comment]
Hi all!
I cannot reproduce the issue with skimage 0.18.1, neither on Linux (Ubuntu 20.04) nor on MacOS  (see below). The execution time will naturally grow with larger images. Since the topic is a bit stale and missing sufficient details, I am going to close the issue.
@gongenhao, please, feel free to reopen if you manage to come up with a working (i.e. failing) example.

Test code:
```python
from time import time
import multiprocessing
from skimage import data, segmentation


def do_slic(img):
    slic = segmentation.slic(img, n_segments=200, start_label=1)
    return slic


def do_quickshift(img):
    qs = segmentation.quickshift(img)
    return qs


def main():
    t0 = time()
    xs = [data.immunohistochemistry() for _ in range(100)]
    pool = multiprocessing.Pool(processes=24)  # 4 with MacOS
    _ = pool.map(do_slic, xs)
    pool.close()
    print(f"Time SLIC: {time()-t0}s")

    t0 = time()
    xs = [data.astronaut() for _ in range(100)]
    pool = multiprocessing.Pool(processes=24)  # 4 with MacOS
    _ = pool.map(do_quickshift, xs)
    pool.close()
    print(f"Time Quickshift: {time() - t0}s")


if __name__ == '__main__':
    main()
```

Output, Linux:
```bash
Time SLIC: 9.470462560653687s
Time Quickshift: 33.95531940460205s
```

Output, MacOS:
```bash
Time SLIC: 19.087873935699463s
Time Quickshift: 177.32385206222534s
```
