### ISSUE TITLE
Minor issue in the doc

### ISSUE THREAD

**Issue by kowalsy** [scikit-image/scikit-image#1476]
Hi everyone,

I noticed a minor issue in the doc about eccentricity property regarding the function :  skimage.measure.regionprops
I quote the doc : Eccentricity of the ellipse that has the same second-moments as the region. The eccentricity is the ratio of the distance between its minor and major axis length.
Whereas, the definition of the eccentricity is the ratio of the focal distance over the major axis length.

The value of the parameter seems to agree with the correct definition (no problem in the code).

Thanks,

**Comment by emmanuelle** [comment]
Thank you for noticing this! Indeed this part of the docstring would need to be corrected. Would you have the time to submit a pull request?

**Comment by JDWarner** [comment]
Closed by #1523.
