### ISSUE TITLE
regionprops doesn't check shape equivalence between label_image and intensity_image

### ISSUE THREAD

**Issue by stevendbrown** [scikit-image/scikit-image#1477]
Since shape equivalence is required according to the documentation, should regionprops throw an Exception when label_image.shape != intensity_image.shape?

**Comment by stefanv** [comment]
You're right!  Would you please file a PR (including a test)?

**Comment by stevendbrown** [comment]
I've just learned how to make a "proper" pull request and will hopefully be able to make one for this issue this week.

**Comment by stefanv** [comment]
Thanks, Steven!

**Comment by emmanuelle** [comment]
Closed by #1777.
