### ISSUE TITLE
Segmentation fault using skimage.measures.label

### ISSUE THREAD

**Issue by eltechnic0** [scikit-image/scikit-image#1479]
Hi, I have tested this with both the "label image region" tutorial and in my own application. The following code throws a reproducible segfault in my system:

```python
import numpy as np
from skimage.measure import label
a = np.random.sample((5,5))
label(a>0.5) # segfault here
# Replacing the above line with the following also segfaults
# b = np.zeros_like(a)
# b[a>0.5] = 1
# label(b)
```

The versions I have are:
- python 3.4.0
- numpy 1.9.2
- scikit-image 0.11.3
- ubuntu 14.04 32bit

PS. Sometimes the first run throws two warnings and some exception. From the second run on I get segfaults. The warnings are:
```
/usr/local/lib/python3.4/site-packages/skimage/filters/thresholding.py:132: RuntimeWarning: invalid value encountered in true_divide
  mean1 = np.cumsum(hist * bin_centers) / weight1
/usr/local/lib/python3.4/site-packages/skimage/filters/thresholding.py:133: RuntimeWarning: invalid value encountered in true_divide
  mean2 = (np.cumsum((hist * bin_centers)[::-1]) / weight2[::-1])[::-1]
```

**Comment by jni** [comment]
Hmm. I can't reproduce on my system (OSX)... Anyone else seeing anything like this? 

@eltechnic0 could you try setting a random seed for numpy in order to ensure complete reproducibility? Also, knowing the details of how you installed the packages might be relevant.

**Comment by eltechnic0** [comment]
I went ahead and installed python3.4.3 from source and installed the relevant packages for it, in this order:
- sudo atp-get build-dep python3.4
- ./configure; make; make test; sudo make install (for building python3.4.3)
- sudo pip3.4 install numpy, cairocffi, matplotlib
- sudo apt-get install gfortran libopenblas-dev liblapack-dev
- sudo pip3.4 install scipy scikit-image

The versions are the same as before, except for python, which is 3.4.3. I am still getting the segfault.

If you can't reproduce the error, then it must be something about my system, but I have no clue about what else to do. Any advice? Is there any way to extract info from a segfault?

**Comment by eltechnic0** [comment]
One more think. When running the code above with python3.4.0 I now get this traceback:
```
Traceback (most recent call last):
  File "segtest.py", line 3, in <module>
    from skimage.measure import label
  File "/usr/local/lib/python3.4/site-packages/skimage/measure/__init__.py", line 4, in <module>
    from ._regionprops import regionprops, perimeter
  File "/usr/local/lib/python3.4/site-packages/skimage/measure/_regionprops.py", line 5, in <module>
    from scipy import ndimage
  File "/usr/local/lib/python3.4/site-packages/scipy/ndimage/__init__.py", line 172, in <module>
    from .filters import *
  File "/usr/local/lib/python3.4/site-packages/scipy/ndimage/filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "/usr/local/lib/python3.4/site-packages/scipy/misc/__init__.py", line 47, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/usr/local/lib/python3.4/site-packages/scipy/special/__init__.py", line 593, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
  File "/usr/local/lib/python3.4/site-packages/scipy/special/_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
  File "_ellip_harm_2.pyx", line 2, in init scipy.special._ellip_harm_2 (scipy/special/_ellip_harm_2.c:7480)
  File "/usr/local/lib/python3.4/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /usr/local/lib/python3.4/lib-dynload/_ctypes.cpython-34m.so: undefined symbol: _PyTraceback_Add
```

**Comment by stefanv** [comment]
This works on my 3.4.3 with the latest numpy and scikit-image.  Does someone else have a 32-bit system to test on?

**Comment by emmanuelle** [comment]
I would recommend that you run the test suites of the different scientific python packages, especially numpy, scipy and scikit-image, to see if there is something wrong with your installation. 

Would it be useful to install gfortran before numpy? (or maybe it doesn't matter because pip only copies binary files... not sure about that...)

**Comment by eltechnic0** [comment]
Most likely there is something wrong with my installation, even though I have installed it twice, for python 3.4.0 and 3.4.3, and still have the problem. Who knows where it might be... For now I am using the scipy.ndimage label() function, which does work.

**Comment by colbrydi** [comment]
Hello,

We were able to reproduce the segmentation fault on CentOS 7 with the following libraries (Anaconda Install):

python 3.73 
numpy 1.16.2 
skimage 0.14.2 

The size of the image we are trying to label is a 3D block of size 864x1867x1867 (3 gb).  Not sure what the core problem is but switching to scipy.ndimage label() worked.
