### ISSUE TITLE
Upgrading version after installation from synaptic

### ISSUE THREAD

**Issue by falaktheoptimist** [scikit-image/scikit-image#1481]
I tried upgrading skimage version from 0.6.1 which is the version getting installed via synaptic package manager to 0.11.3
`sudo pip install scikit-image==0.11.3
Collecting scikit-image
  Using cached scikit-image-0.11.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade):
matplotlib>=1.1.0 in /usr/lib/pymodules/python2.7 (from scikit-image)
Requirement already satisfied (use --upgrade to upgrade): six>=1.3 in
/usr/local/lib/python2.7/dist-packages (from scikit-image)
Requirement already satisfied (use --upgrade to upgrade):
networkx>=1.8 in /usr/local/lib/python2.7/dist-packages (from
scikit-image)
Requirement already satisfied (use --upgrade to upgrade):
pillow>=1.7.8 in /usr/local/lib/python2.7/dist-packages (from
scikit-image)
Collecting decorator>=3.4.0 (from networkx>=1.8->scikit-image)
  Using cached decorator-3.4.2.tar.gz
Installing collected packages: scikit-image, decorator
  Running setup.py install for scikit-image`

The installation gets stuck here each time for hours and the memory occupied goes on increasing. What could be the reason?

**Comment by stefanv** [comment]
I'm not sure what would cause that.  Could you check out the source from
Git and build it (``python setup.py build_ext -i``) to see if that works OK?

**Comment by falaktheoptimist** [comment]
Thanks @stefanv , that worked- it took almost 2 hours for building on Raspberry pi-2, but in the end the build worked. Many thanks again.

**Comment by JDWarner** [comment]
For posterity, yes compilation takes quite a while on the RPi generally
speaking, and it can appear to hang during.

**Comment by stefanv** [comment]
If you run Raspian you can at least get an old version binary.  And, we are working with our Debian maintainers to get a new package out there ASAP!

**Comment by WillyFoley** [comment]
So if I am having the same issue during install on Kali then my distribution is the problem? Any workarounds for debian at the moment?

**Comment by stefanv** [comment]
Solving the current Debian bugs is the best way to move this forward: https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=skimage

**Comment by WillyFoley** [comment]
Thank you for your prompt reply - I figured everything out. But maybe you can help me with my current problem - when i use imglab as directed in the dlib docs, the labeler comes up and it is simply a gray screen, as if I have no images. Sure enough, when I vi the file, there is nothing between the <image> tags, although everything else is in place. I made sure I have images in the target directory, and then even moved imglab to the directory with the image files and achieved the same results. Any idea what the problem could be? There are ZERO helpful pages on the internet about this. 

Date: Wed, 16 Sep 2015 00:39:28 -0700

**Comment by WillyFoley** [comment]
Solved problem - all images must be jpg formatted 

Will Foley
601-329-1194
