### ISSUE TITLE
Remove ``Image`` class

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1484]
I believe that the ``Image`` class defined in ``io._io.py`` is not used anywhere in the package anymore. Should we get rid of this part of the code in order to avoid having "dead code" and to make make maintenance easier?

If other people concur, I'll file a pull request.

**Comment by JDWarner** [comment]
:+1:

**Comment by blink1073** [comment]
:+1:

**Comment by emmanuelle** [comment]
thanks for the quick answers, see #1486

**Comment by emmanuelle** [comment]
Closing this issue since #1486 has been merged.
