### ISSUE TITLE
io.imsave taking a long time

### ISSUE THREAD

**Issue by bouncehead13** [scikit-image/scikit-image#1491]
Hello,

I have a `np.ndarray` of RGB values which I am trying to save using the `io.imsave()` function. However, this single line takes a long time to complete and I am trying to reduce this time. Can you give a brief explanation to why this function takes a long time?

Note: I am working with a PNG file with dimensions 4928x3264.

Thanks!
Matt

**Comment by stefanv** [comment]
We just use the underlying implementation of either PIL, matplotlib,
etc.  You are storing a large image, and that takes time--but perhaps
you can compare it against the time it takes to save the same image in
Gimp, e.g.?

**Comment by bouncehead13** [comment]
Okay, makes sense. Just checked and I use PIL so I'll send them a message to see if they have more insight into the question. Also, thanks for the idea of checking out Gimp, I'll do that.

**Comment by stefanv** [comment]
You can also switch out the io backend to see if it helps:

```
io.imsave(..., plugin='matplotlib')
io.imsave(..., plugin='freeimage')
```

etc.
