### ISSUE TITLE
Error installing skimage-

### ISSUE THREAD

**Issue by gsanrey** [scikit-image/scikit-image#1506]
Hi!
I've install skimage on a MacOs 10.10, like it's said in the documentation:
pip install -U scikit-image
and it say that need scipy to work, I had to install it to work.

**Comment by JDWarner** [comment]
That is correct and the intended behavior. Required dependencies must be installed first, then scikit-image... at least when one uses pip.

pip itself is not a package manager. If you want that, a distribution like Anaconda or Canopy will "just work" by grabbing all necessary dependencies and then what you asked for.

**Comment by matthew-brett** [comment]
Well - I think pip is a package manager - and if you install scikit-image, pip will also install:

```
Installing collected packages: scikit-image, networkx, matplotlib, pillow, six, decorator, nose, pytz, numpy, python-dateutil, mock, pyparsing
```

It's just that scipy is not among the declared dependencies for the install.  Should it be?

**Comment by JDWarner** [comment]
Looking a little further, scipy >= 0.9 is declared in [requirements.txt](https://github.com/scikit-image/scikit-image/blob/master/requirements.txt) so it should be brought along.

**Comment by matthew-brett** [comment]
I can't remember the exact source of the discussion, but I think it was deliberate that the requirements.txt requirements were different from the default pip / source install requirements.

**Comment by stefanv** [comment]
Here is the reason for it:

```
# do not attempt to install numpy and scipy until they have eggs available
INSTALL_REQUIRES = [r for r in INSTALL_REQUIRES
                                     if not r.startswith(('scipy', 'numpy'))]
```

**Comment by matthew-brett** [comment]
Hum - well - they do have 'eggs' available for OSX, but not for Windows or Linux.  So.... ?

**Comment by blink1073** [comment]
We could special case 'darwn' and leave it as-is on other platforms until
eggs are available.

**Comment by matthew-brett** [comment]
Just to be clear - we mean 'wheels' right?   I think eggs have definitely gone off.

**Comment by stefanv** [comment]
Is it important that eggs are available?  Why can't we let pip 
compile scipy from source (as long as it doesn't upgrade 
unnecessarily)?

**Comment by matthew-brett** [comment]
a) It will upgrade unnecessarily if someone upgrades scikit-image;
b) Scipy does take a long time and a fortran compiler - so it's pretty error prone for Linux, out of the question on Windows.  For OSX, there should always be a wheel.

**Comment by stefanv** [comment]
I thought the upgrade happens only when you specified a version. 
Or does it *always* upgrade?  That's pretty lousy.

**Comment by matthew-brett** [comment]
It always upgrades:

https://pip.pypa.io/en/latest/user_guide.html#only-if-needed-recursive-upgrade
https://github.com/pypa/pip/issues/304

Yes, it's lousy.

**Comment by blink1073** [comment]
Yes, I meant to say `wheels`, and yes, the behavior of `pip install -U` is quite lousy.

**Comment by arve0** [comment]
I'm pretty sure this problem will go away (updating numpy, scipy, etc) if one does not define version (e.g. `>=1.6.1`) in `setup.py`. The dependency will be met if scipy is installed and only `scipy` is required. This has been discussed several times, but declined as one did not want to define dependencies in two places (or write a requirements.txt parser - which I think is silly for 7 requirements).

My take is that duplicating 7 requirements is worth it, and be rid of this installation trouble.

To be clear, the proposal is replacing 

```
INSTALL_REQUIRES = [r for r in INSTALL_REQUIRES
                                     if not r.startswith(('scipy', 'numpy'))]
```

with

```
INSTALL_REQUIRES = [
    'cython',
    'matplotlib',
    'numpy',
    'scipy',
    'six',
    'networkx',
    'pillow' ]
```

**Comment by blink1073** [comment]
From the `pip` documentation:

https://pip.pypa.io/en/latest/reference/pip_install.html#cmdoption-U

"Upgrade all specified packages to the newest available version. This process is recursive regardless of whether a dependency is already satisfied."

**Comment by blink1073** [comment]
@arve0, even if we do not specify the version, we will still have this mess.

**Comment by arve0** [comment]
@blink1073 Sorry, I'm not following you. How will `pip install scikit-image` (*without* -U) be a mess, when all dependencies are declared?

This implies that the user either will get compiled wheels for his operating system (true for all dependencies on Mac and windows I believe), or has a system with compiler (should be added to the docs how the most popular, read Ubuntu, get that installed).

Are my assumptions wrong, or what have I missed?

**Comment by arve0** [comment]
For people wanting to upgrade, that will be `pip install --upgrade --no-deps scikit-image`, but the original poster was having trouble *installing*, not upgrading.

**Comment by blink1073** [comment]
But when we add a new dependency (like dask), that would not work. 



—

**Comment by blink1073** [comment]
We could recommend `pip uninstall scikit-image; pip install scikit-image`



—

**Comment by arve0** [comment]
or `pip install --upgrade --no-deps scikit-image; pip install scikit-image` (from the pip manual).

**Comment by blink1073** [comment]
So that should work today without any changes to our setup.py, no?

**Comment by arve0** [comment]
All dependencies will have to be added (scipy and numpy), but versions should be stripped to avoid upgrading system-installed packages like scipy, matplotlib, etc.

**Comment by arve0** [comment]
In other words; dependencies will be either soft dependencies or hard dependencies.

- Hard dependencies will require a specific version installed (this should in a perfect world only consist of python-only packages)
- Soft dependencies will only require the package (and should not force upgrades)

E.g.
- six is a hard dependency (we need above 1.3)
- numpy is a soft dependency

Might add; there is nothing wrong with having (sane) hard dependencies in requirements.txt for developers. A developer should definitely have reasonable updated numpy/scipy/etc.

**Comment by blink1073** [comment]
@arve, the listed versions *are* hard dependencies in that we rely on functions or an API provided by those versions or the version is the minimum we can test against. 



—

**Comment by arve0** [comment]
Well, then one should just replace

```
INSTALL_REQUIRES = [r for r in INSTALL_REQUIRES
                                     if not r.startswith(('scipy', 'numpy'))]
```

with 

```
INSTALL_REQUIRES = [r for r in INSTALL_REQUIRES]
```

**Comment by arve0** [comment]
Haha, sorry! I mean, remove it! :laughing:

**Comment by blink1073** [comment]
Agreed, with the new suggested incantation we can certainly simplify setup.py, can to take a crack at the fix and the documentation update?



—

**Comment by arve0** [comment]
I can take a look at it in the evening (GMT+1).

**Comment by blink1073** [comment]
Thanks brother, keep keeping us honest.  😜
