### ISSUE TITLE
High memory usage during DAISY computation for large images

### ISSUE THREAD

**Issue by joschkazj** [scikit-image/scikit-image#1508]
First of all I would like to thank all contributors for this excellent package and the continuous extension of features, I have been using scikit-image in my research for several years (and citing the webpage/paper).

Recently I used the HOG and DAISY descriptors for image classification and noticed that DAISY computation requires a lot of memory when working with large images (6 - 9 MPixel) due to its (though elegant) use of temporary arrays for intermediate results and vectorized computation.

I attached the output of [memory_profiler](https://github.com/fabianp/memory_profiler) for an image with 9Mpixels, which used **13.5 GiB** during computation. As I run out of memory when using `orientations` > 18, I am looking for workarounds. These do not necessarily have to involve changes to the codebase, but maybe a reduced memory footprint would benefit others as well.

Simple optimizations:
* delete intermediate results once they are no longer used (I had good results with explicitly calling `gc.collect()` in my batch scripts with many large images)
* split the computation for large images and merge resulting descriptors

What do you suggest?
(ping @andersbll as he authored the original PR)

```
Using 9.165214 MPixel image (3142 x 2917 pixels)
Compute descriptors for 8 orientations...success.

Line #    Mem usage    Increment   Line Contents
================================================
     9   87.832 MiB    0.000 MiB   @profile
    10                             def daisy(img, step=4, radius=15, rings=3, histograms=8, orientations=8,
    11                                       normalization='l1', sigmas=None, ring_radii=None, visualize=False):
    12                                 '''Extract DAISY feature descriptors densely for the given image.

[...]
    
    98   87.832 MiB    0.000 MiB       assert_nD(img, 2, 'img')
    99                             
   100  157.902 MiB   70.070 MiB       img = img_as_float(img)
   101                             
   102                                 # Validate parameters.
   103  157.902 MiB    0.000 MiB       if sigmas is not None and ring_radii is not None \
   104                                         and len(sigmas) - 1 != len(ring_radii):
   105                                     raise ValueError('`len(sigmas)-1 != len(ring_radii)`')
   106  157.902 MiB    0.000 MiB       if ring_radii is not None:
   107                                     rings = len(ring_radii)
   108                                     radius = ring_radii[-1]
   109  157.902 MiB    0.000 MiB       if sigmas is not None:
   110                                     rings = len(sigmas) - 1
   111  157.902 MiB    0.000 MiB       if sigmas is None:
   112  157.902 MiB    0.000 MiB           sigmas = [radius * (i + 1) / float(2 * rings) for i in range(rings)]
   113  157.902 MiB    0.000 MiB       if ring_radii is None:
   114  157.902 MiB    0.000 MiB           ring_radii = [radius * (i + 1) / float(rings) for i in range(rings)]
   115  157.902 MiB    0.000 MiB       if normalization not in ['l1', 'l2', 'daisy', 'off']:
   116                                     raise ValueError('Invalid normalization method.')
   117                             
   118                                 # Compute image derivatives.
   119  157.910 MiB    0.008 MiB       dx = np.zeros(img.shape)
   120  157.914 MiB    0.004 MiB       dy = np.zeros(img.shape)
   121  228.043 MiB   70.129 MiB       dx[:, :-1] = np.diff(img, n=1, axis=1)
   122  298.078 MiB   70.035 MiB       dy[:-1, :] = np.diff(img, n=1, axis=0)
   123                             
   124                                 # Compute gradient orientation and magnitude and their contribution
   125                                 # to the histograms.
   126  368.168 MiB   70.090 MiB       grad_mag = sqrt(dx ** 2 + dy ** 2)
   127  438.234 MiB   70.066 MiB       grad_ori = arctan2(dy, dx)
   128  438.234 MiB    0.000 MiB       orientation_kappa = orientations / pi
   129  438.234 MiB    0.000 MiB       orientation_angles = [2 * o * pi / orientations - pi
   130  438.234 MiB    0.000 MiB                             for o in range(orientations)]
   131  438.238 MiB    0.004 MiB       hist = np.empty((orientations,) + img.shape, dtype=float)
   132  998.734 MiB  560.496 MiB       for i, o in enumerate(orientation_angles):
   133                                     # Weigh bin contribution by the circular normal distribution
   134  998.734 MiB    0.000 MiB           hist[i, :, :] = exp(orientation_kappa * cos(grad_ori - o))
   135                                     # Weigh bin contribution by the gradient magnitude
   136  998.734 MiB    0.000 MiB           hist[i, :, :] = np.multiply(hist[i, :, :], grad_mag)
   137                             
   138                                 # Smooth orientation histograms for the center and all rings.
   139  998.734 MiB    0.000 MiB       sigmas = [sigmas[0]] + sigmas
   140  998.746 MiB    0.012 MiB       hist_smooth = np.empty((rings + 1,) + hist.shape, dtype=float)
   141 3241.133 MiB 2242.387 MiB       for i in range(rings + 1):
   142 3241.133 MiB    0.000 MiB           for j in range(orientations):
   143 3171.074 MiB  -70.059 MiB               hist_smooth[i, j, :, :] = gaussian_filter(hist[j, :, :],
   144 3241.133 MiB   70.059 MiB                                                         sigma=sigmas[i])
   145                             
   146                                 # Assemble descriptor grid.
   147 3241.133 MiB    0.000 MiB       theta = [2 * pi * j / histograms for j in range(histograms)]
   148 3241.133 MiB    0.000 MiB       desc_dims = (rings * histograms + 1) * orientations
   149 3241.133 MiB    0.000 MiB       descs = np.empty((desc_dims, img.shape[0] - 2 * radius,
   150 3241.164 MiB    0.031 MiB                         img.shape[1] - 2 * radius))
   151 3241.164 MiB    0.000 MiB       descs[:orientations, :, :] = hist_smooth[0, :, radius:-radius,
   152 3790.598 MiB  549.434 MiB                                                radius:-radius]
   153 3790.598 MiB    0.000 MiB       idx = orientations
   154 13851.793 MiB 10061.195 MiB       for i in range(rings):
   155 13851.785 MiB   -0.008 MiB           for j in range(histograms):
   156 13821.375 MiB  -30.410 MiB               y_min = radius + int(round(ring_radii[i] * sin(theta[j])))
   157 13821.375 MiB    0.000 MiB               y_max = descs.shape[1] + y_min
   158 13821.375 MiB    0.000 MiB               x_min = radius + int(round(ring_radii[i] * cos(theta[j])))
   159 13821.375 MiB    0.000 MiB               x_max = descs.shape[2] + x_min
   160 13821.375 MiB    0.000 MiB               descs[idx:idx + orientations, :, :] = hist_smooth[i + 1, :,
   161 13821.375 MiB    0.000 MiB                                                                 y_min:y_max,
   162 13851.777 MiB   30.402 MiB                                                                 x_min:x_max]
   163 13851.777 MiB    0.000 MiB               idx += orientations
   164 13851.793 MiB    0.016 MiB       descs = descs[:, ::step, ::step]
   165 13851.812 MiB    0.020 MiB       descs = descs.swapaxes(0, 1).swapaxes(1, 2)
   166                             
   167                                 # Normalize descriptors.
   168 13851.812 MiB    0.000 MiB       if normalization != 'off':
   169 13778.258 MiB  -73.555 MiB           descs += 1e-10
   170 13778.262 MiB    0.004 MiB           if normalization == 'l1':
   171 13746.465 MiB  -31.797 MiB               descs /= np.sum(descs, axis=2)[:, :, np.newaxis]
   172                                     elif normalization == 'l2':
   173                                         descs /= sqrt(np.sum(descs ** 2, axis=2))[:, :, np.newaxis]
   174                                     elif normalization == 'daisy':
   175                                         for i in range(0, desc_dims, orientations):
   176                                             norms = sqrt(np.sum(descs[:, :, i:i + orientations] ** 2,
   177                                                                 axis=2))
   178                                             descs[:, :, i:i + orientations] /= norms[:, :, np.newaxis]
   179                             
 
 [...]
```

**Comment by andersbll** [comment]
Hey, I'll be happy to take a look at this in a few days when I have the time.

**Comment by joschkazj** [comment]
Thank you in advance!
I can integrate some optimizations myself and file a pull request, if you point out what options are most promising or suitable for library usage (e.g. use a threshold on image size to consider computation/memory tradeoff for windowed computation?).

**Comment by andersbll** [comment]
The memory problem is caused by the size of `descs` that becomes >12 GB for an input image of 9 Mpix with 18 gradient orientations. This cannot be fixed with more aggressive garbage collection.

Some considerations:
- I think an image of size 9 Mpix is _huge_ for computer vision. Maybe you can scale down your image size?
- 18 gradient orientations are quite a lot compared to most other descriptors. You should be able to get decent performance with fewer orientations.
- A memory footprint of 13 GB doesn't really seem that big a deal to me for scientific computing applications.

Therefore, I don't think the implementation of `daisy()` should be made more memory efficient by processing the input image in chunks as this would increase code complexity. Rather, I think you should subdivide your input image and call `daisy()` for each image chunk.

Best,
Anders

**Comment by joschkazj** [comment]
Thanks for looking into this and your analysis.

> I think an image of size 9 Mpix is huge for computer vision. Maybe you can scale down your image size?

I am analyzing high-resolution surface image in an industrial application and need the resolution, so this is not an option.

>     18 gradient orientations are quite a lot compared to most other descriptors. You should be able to get decent performance with fewer orientations.

As I am using the descriptors not for matching but as a cheap way to compute texture features, I want to compare different parameter values especially with respect to angular resolution/number of orientations. One assumption for my application is that it would benefit from higher angular resolution and I wanted to validate this.

>     A memory footprint of 13 GB doesn't really seem that big a deal to me for scientific computing applications.

It isn't, and this example runs fine on my machine with 16 GB, but for more orientations it still becomes a problem.

> Therefore, I don't think the implementation of daisy() should be made more memory efficient by processing the input image in chunks as this would increase code complexity. Rather, I think you should subdivide your input image and call daisy() for each image chunk.

Thank you for your conclusion, I will proceed this way and process smaller image regions. I just wanted to know if you saw any other starting points for optimization.

For me this issue is closed. :-)

**Comment by andersbll** [comment]
Cool, you might also want to experiment with texture descriptors. DAISY/SIFT/HOG are mainly designed for capturing image geometry.

**Comment by stefanv** [comment]
Also see https://github.com/scikit-image/scikit-image/pull/1493

**Comment by stefanv** [comment]
@joschkazj Thank you for using (and citing!) scikit-image; we are grateful for your helpful feedback, and always happy to try and improve the package where needed.

**Comment by joschkazj** [comment]
> Also see #1493

Thank you for the pointer, this looks really interesting. At the moment I'm mostly using joblib and view_as_windows for this purpose.
