### ISSUE TITLE
Release the GIL whenever possible

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1512]
From discussion in #1493, @mrocklin pointed out the many benefits of releasing the GIL for parallelization/serialization.

For many of our Cython files and functions this would be as simple as wrapping contents in a `with nogil:` block

```python
with nogil:
    # function contents here
```

Opening as a separate issue to facilitate discussion.

**Comment by mrocklin** [comment]
In original experiments by @cowlicks we were only able to get a 30% increase when using canny edge detection in multiple threads.  I/O wasn't an issue so we assumed that the GIL was to blame.

A case study of removing the GIL and using `apply_chunks` from #1493 on a single algorithm might teach us something.  We're happy to support from the dask side.

**Comment by stefanv** [comment]
Yes, please--any energy going to this is good, because we have been *very bad* on this front.

**Comment by tacaswell** [comment]
Commenting so I get emails from this thread, sorry for the noise.

**Comment by stefanv** [comment]
Is there anyone who has Airspeed Velocity set up?  It would be quite useful at this point.

https://github.com/spacetelescope/asv/

@yarikoptic, any advice?

**Comment by jni** [comment]
@stefanv using asv reliably needs a dedicated server, in my understanding, so that the benchmarks are comparable across timepoints. (I have not yet tried this myself.)

I met someone at MPUG (Melbourne Python Users Group) who has been playing around with asv. I've pinged him over email because I don't know his Github handle. He might be able to contribute here!

**Comment by stefanv** [comment]
Perhaps the astropy team would be willing to help, @cdeil?

**Comment by koenvb** [comment]
Happy to contribute here. I played around a bit with asv but as noted in the [talk from scipy 2014] (https://www.youtube.com/watch?v=OsxJ5O6h8s0) the benchmarks are tied to the particular machine and software.  Next is the benchmarks you want to run. This is the [repo](https://github.com/astropy/astropy-benchmarks) with benchmarks from astropy using asv.  The setup is straightforward and it just comes down to defining which benchmarks and which test matrix you want.

**Comment by jni** [comment]
@koenvb how about you fork scikit-image and define a couple of benchmarks? The [gallery](http://scikit-image.org/docs/dev/auto_examples/) is a good place to start.

**Comment by anderspitman** [comment]
@koenvb happy to share our experience setting up asv if you have any questions. It's a great project and pretty straight forward to set up, but there are definitely some subtleties, and the operation can be a bit opaque and difficult to debug when something goes wrong.

**Comment by cdeil** [comment]
I've only played around with asv. For Astropy it's @mdboom and @astrofrog that have the most experience with asv and I think are running cron jobs to continuously run asv.

Yes, you need to find a dedicated machine to run the benchmarks. But that can come later, getting familiar with asv and implementing a useful set of benchmarks can come first.

You also need to discuss a bit about what kind of benchmarks you want and how they can be helpful to you without taking too much time to implement and run and then review and discuss the results. The main aspect of asv is that it runs the same benchmark for many commits in your repo, so you'll mainly learn something useful if there's a change in performance, i.e. a regression or improvement.

**Comment by sciunto** [comment]
Probably most of you are familiar with the GIL, but I felt the need to learn more about it. I found this article well done, with an enlightening video. http://lbolla.info/blog/2013/12/23/python-threads-cython-gil

**Comment by JDWarner** [comment]
Closed by #1519

**Comment by mrocklin** [comment]
Well that was fast!
