### ISSUE TITLE
interpolation.pxd:  split to separate .pxd/.pyx ?

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#1515]
Is there a good reason that the shared cython interpolation code is stored within `_shared/interpolation.pxd ` itself rather than having just the declarations in the .pxd and the actual code in a separate interpolation.pyx file?  It seems like splitting into two files would avoid duplicating the C code each time a different .pyx file includes functions from interpolation.pxd.  

For example, denoise_cy.pyx uses only get_pixel3d from that file, but *all* functions in the pxd get included and compiled in denoise_cy.c.

**Comment by JDWarner** [comment]
I'm inclined to agree.

**Comment by stefanv** [comment]
Yes, that would be a good refactoring!

**Comment by grlee77** [comment]
okay.  I will submit a pull request later this weekend

**Comment by ahojnnes** [comment]
These functions are inlined... they should stay in the header file?

**Comment by stefanv** [comment]
I should have checked for that--thanks Johannes.

**Comment by grlee77** [comment]
makes sense.  closing this issue
