### ISSUE TITLE
Undefined 'min_mask' in "get_min_ncut"

### ISSUE THREAD

**Issue by christian-rauch** [scikit-image/scikit-image#1538]
In my current installation (scikit-image 0.11.3) I get:
`UnboundLocalError: local variable 'min_mask' referenced before assignment` in line 208 of future/graph/graph_cut.py (function `get_min_ncut`).
This only can happen if `cost` keeps the value `np.inf`. `min_mask` will never be assigned before it is returned.

To fix this `min_mask` should be initialized properly at the beginning of the loop.

**Comment by vighneshbirodkar** [comment]
Thanks for pointing this out. I will try to fix this within the next day or two.

**Comment by vighneshbirodkar** [comment]
@christian-rauch Can you share the code that lead to this ? I am surprised that `cost` was never less that infinity.

**Comment by christian-rauch** [comment]
@vighneshbirodkar That is difficult as I am using the library within a more complex framework. I will try to identify the image data and the parameters with which this error is caused. At least I can tell that this is happening for calling `cut_normalized` with larger thresholds on a RAG with weights from similarity mode. E.g., I was testing with thresholds [0.05, 0.1, 0.2, 0.5] and it happened with threshold 0.5.

**Comment by vighneshbirodkar** [comment]
@christian-rauch In any case I think putting the necessary check won't cause any harm. If possible, can you tell me what exactly are you using this for (just for my curiosity) ?

**Comment by christian-rauch** [comment]
Those are the parameters given to get_min_ncut(ev, d, w, num_cuts) that cause the error:
ev:
  [ nan  nan  nan]
d:
  (0, 0)	3.0
  (1, 1)	3.0
  (2, 2)	3.0 
w:
  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (0, 2)	1.0
  (1, 2)	1.0
  (2, 2)	1.0 
num_cuts:
  10

**Comment by christian-rauch** [comment]
@vighneshbirodkar The nan eigen vector results from the normalization of the vector whose values are all equal (at "ev = _ncut.normalize(vectors[:, index2])" in "_ncut_relabel").

**Comment by vighneshbirodkar** [comment]
I remember @stefanv pointing this out and @jni suggested to let that remain as error. Seeing that you ran into this problem, we have to fix this.
The bigger question is, what is the normalized value given that all your samples are equal ?

**Comment by christian-rauch** [comment]
@vighneshbirodkar I did not follow the whole algorithm but I think it is resulting from the weight matrix having all weights equal to 1.0 at some place in the subdivision of the graph. So the questions is basically how the original algorithm is dealing with this situation.
