### ISSUE TITLE
crash in CLAHE adapthist

### ISSUE THREAD

**Issue by hunter-87** [scikit-image/scikit-image#1541]
Hi,
i've found a possible bug in the adapthist implementation:
to replicate the bug, it happens with the following input:

function:  skimage.exposure.equalize_adapthist
with input
any image of shape (1000, 236)
tile_num_x = 12
tile_num_y = 50

it crash with error:
```
<type 'exceptions.ValueError'>: ((0, 54), (0, -2)) cannot contain negative values.
```
reading the code i think is in the part where w_pad and h_pad is calculated ( in this case w_pad is -2)

i tried to fix it to avoid the crash but i'm unsure if it's the right solution:
after line 135: https://github.com/scikit-image/scikit-image/blob/master/skimage/exposure/_adapthist.py#L135
i added:
```
if w_pad <0:
    w_pad += width
if h_pad <0:
    h_pad += height
```

do you think there is a better solution?

edit: to replicate use

```
import numpy as np
from skimage.exposure import equalize_adapthist
a = np.ones((1000, 236))
equalize_adapthist(a , ntiles_x= 12, ntiles_y=50)
```

**Comment by blink1073** [comment]
@hunter-87, this is definitely a bug.  We need to handle the image partitioning better overall, with the option to specify the tile size instead of the number of tiles.  FYI, in the current implementation, the number of tiles is clipped at 16.

**Comment by blink1073** [comment]
@stefanv, here is my proposal:

Use `view_as_window` instead of `view_as_blocks`, to allow the windows to overlap.  
Deprecate the `ntiles*` kwargs in favor of `kernel_size : integer or 2-tuple, optional`.

The downside to `view_as_window` is that if the `kernel_size` is not square, you can have a substantial overlap in the dimension with the larger size, since we would have to use the smaller of the two dimensions to set the `step` parameter.

**Comment by blink1073** [comment]
This also relates to mailing list post:  https://groups.google.com/forum/#!topic/scikit-image/2elntOClGOY

**Comment by jni** [comment]
@blink1073 I've only been following this superficially, but why can't the step be different in each dimension as well?

**Comment by blink1073** [comment]
@jni, `view_as_window` takes a single integer for `step`, which becomes the stride of the new array.

**Comment by blink1073** [comment]
Or I should say it influences the stride of the new array.

**Comment by stefanv** [comment]
Should we change step to accept a tuple of ndim?

**Comment by blink1073** [comment]
Looks like our friends at sklearn already have it implemented: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/feature_extraction/image.py#L242

**Comment by jni** [comment]
Allowing tuple input seems both feasible and desirable.
