### ISSUE TITLE
skimage.external.tifffile fails to use the compiled tifffile extension

### ISSUE THREAD

**Issue by stuarteberg** [scikit-image/scikit-image#1548]
**Update:** As noted below, #1549 fixes the original problem described here, but we've run into a second issue which also prevents the `_tifffile.so` extension from loading properly. Explanation below.

----

The version of `tifffile.py` included in `skimage.external` is slightly out-of-date with respect to the [version on the author's website](http://www.lfd.uci.edu/~gohlke/code/tifffile.py.html).

Critically, the version in scikit-image includes a typo in the [`_replace_by`](https://github.com/scikit-image/scikit-image/blob/1b38c172800b45c04fcf958c4e8712ae7374ea8a/skimage/external/tifffile/tifffile_local.py#L3117) function, which prevents the C-extension code in `_tifffile.so` from getting imported.  Thus, although the `_tifffile.so` C-extension is built properly, it isn't ever used.

Fortunately, a pure-python implementation of `decodelzw()` exists as a fallback. Unfortunately, it is an order of magnitude slower than the C implementation.

**Comment by JDWarner** [comment]
Thanks for the report, @stuarteberg - I believe I just pushed a PR with a fix. Can you verify #1549 resolves the problem?

**Comment by stuarteberg** [comment]
@JDWarner, sorry for the delayed response.  I took a look at your fix today (which I see was already merged).  To my surprise, your change wasn't enough to fix the problem.

Or rather, there is actually a second problem.  You fixed the typo, but there is an additional exception that prevents the `_replace_by` function from working properly.  The tifffile code assumes that `_tifffile.so` can be found on `sys.path`.  Since `skimage.external.tifffile` is not on `sys.path`, the `_tifffile.so` module is not found.

I just pushed a PR (#1551) with a potential fix, but I'm not sure if it's a good idea to get out-of-sync with the original `tifffile` module.

**Comment by JDWarner** [comment]
Interesting - ping @blink1073

**Comment by blink1073** [comment]
I've got an eye infection, I'll be out of commission for a bit. 



—

**Comment by blink1073** [comment]
@stuarteberg, you raise a good point.  In the PyPI package, both modules are copied to site-packages, so `_tifffile.so` is available on the path.  I will adjust the `skimage` version to be a package to avoid this problem.

**Comment by blink1073** [comment]
@stuarteberg, I just went ahead and made the PyPI version use a package, which makes it easier to keep us in sync.  See #1553.

**Comment by stuarteberg** [comment]
I haven't tested your fix yet, but I don't understand it.  Does this change put `_tifffile.so` on `sys.path`?  I think that is required to make the `_replace_by` decorator work correctly.

You could verify that `_replace_by` is behaving properly by adding a check for `tifffile.decodelzw == _tifffile.decodelzw`.

(See the example in PR #1551)

Otherwise, problems with `_replace_by` easily go undetected until you notice the poor performance.

**Comment by blink1073** [comment]
Good point @stuarteberg, I added an explicit test to make sure the functions are being replaced by the compiled ones.

**Comment by stuarteberg** [comment]
This issue can be closed when #1553 is merged.
