### ISSUE TITLE
how to install scikit-image

### ISSUE THREAD

**Issue by antonio19812** [scikit-image/scikit-image#1556]
I have to work with python on suse 13.2 in a a VM running in windows.
I installed eclipse and pydev to use python 2.7 and everythingch l is working.
Which are the correct steps to install scikit image with all its requirements?? I can not understand it for suse in the documentation. Please help!

**Comment by emmanuelle** [comment]
Hi Antonio, as described in http://scikit-image.org/download#linux-and-osx you can use pip install
``pip install -U scikit-image``.

**Comment by antonio19812** [comment]
And this should install scikit and the other required packages???

**Comment by emmanuelle** [comment]
yes!

**Comment by antonio19812** [comment]
I will try, thanks so much!!!

**Comment by antonio19812** [comment]
I did it but I obtained an error , it is this one from terminal :

ntonio@linux-rosd:/home> pip install -U scikit-image
Downloading/unpacking scikit-image
  Downloading scikit-image-0.11.3.tar.gz (18.6MB): 18.6MB downloaded
  Running setup.py (path:/tmp/pip_build_antonio/scikit-image/setup.py) egg_info for package scikit-image
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_antonio/scikit-image/setup.py", line 76, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named 'numpy'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_antonio/scikit-image/setup.py", line 76, in <module>

    from numpy.distutils.core import setup

ImportError: No module named 'numpy'

I have to say that Numpy is installed properly and I can use it in Python with Eclipse.

**Comment by stefanv** [comment]
Unfortunately, that means that numpy is not yet installed properly. Try the
pip install command with numpy first?

**Comment by antonio19812** [comment]
I have just tried 
pip install numpy 

and these are the last lines I obtained  : 
File "numpy/core/setup.py", line 293, in check_types

    "Cannot compile 'Python.h'. Perhaps you need to "\

SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

what should I do?

**Comment by JDWarner** [comment]
This error means - as it states - that your system Python lacks some of the development headers needed to install NumPy. It is telling you to install python-dev or python-devel using your distribution's package manager first.

**Comment by antonio19812** [comment]
unfortunately I verified from yast software manager that I have python-devel yet installed, so I wonder why it says I need to install it

**Comment by blink1073** [comment]
@antonio19812, can you try installing `python-scipy` with yast?  This will also install `numpy`.

**Comment by antonio19812** [comment]
The funny thing is that I installed scipy with yast and when I open python in eclipse and I try to use both scipy and numpy they both work, but then in the installation of scikit-image I receive that message!

**Comment by blink1073** [comment]
Hmm, perhaps you are in a virtual env?  Can you post the output of these commands?:

```bash
echo $VIRTUAL_ENV
which pip
which python
```

**Comment by antonio19812** [comment]
yes, I execute them and do it, if you can help me it would be great...

**Comment by blink1073** [comment]
Can you paste the output here?

**Comment by antonio19812** [comment]
this is what I got  : 

antonio@linux-rosd:~> echo $VIRTUAL_ENV

antonio@linux-rosd:~> which pip
/usr/bin/pip
antonio@linux-rosd:~> which python
/usr/bin/python
antonio@linux-rosd:~>

**Comment by blink1073** [comment]
And `python -c "import numpy"`?



—

**Comment by antonio19812** [comment]
this is : 

antonio@linux-rosd:~> python -c "import numpy"
antonio@linux-rosd:~>

**Comment by antonio19812** [comment]
that is strange... I obtained nothing

**Comment by antonio19812** [comment]
Otherwise I can set a new VM again and I would ask you the best way to install scikit and all the requirements correctly :)

**Comment by JDWarner** [comment]
No output means NumPy was imported without errors.

`pip install -U scikit-image` should take you from there, or at least it shouldn't give you the same error message.

**Comment by antonio19812** [comment]
this is the output after pip install -U scikit-image : 

ntonio@linux-rosd:~> pip install -U scikit-image
Downloading/unpacking scikit-image
  Downloading scikit-image-0.11.3.tar.gz (18.6MB): 18.6MB downloaded
  Running setup.py (path:/tmp/pip_build_antonio/scikit-image/setup.py) egg_info for package scikit-image
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_antonio/scikit-image/setup.py", line 76, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named 'numpy'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_antonio/scikit-image/setup.py", line 76, in <module>

    from numpy.distutils.core import setup

ImportError: No module named 'numpy'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_antonio/scikit-image
Storing debug log for failure in /home/antonio/.pip/pip.log

**Comment by blink1073** [comment]
Weird, how about `python -c "from numpy.distutils.core import setup"`?

**Comment by antonio19812** [comment]
yes, really weird, and the new output is  : 

antonio@linux-rosd:~> python -c "from numpy.distutils.core import setup"
antonio@linux-rosd:~> 

this too is not missing...

**Comment by sciunto** [comment]
Can you provide the outputs of

```
pip -V
python -V
```

**Comment by sciunto** [comment]
This issue should be closed.

**Comment by blink1073** [comment]
Closing in favor of #1559.
