### ISSUE TITLE
Problems installing scikit-image

### ISSUE THREAD

**Issue by antonio19812** [scikit-image/scikit-image#1559]
Please if someone can help me to install properly scikit-image.. I already made various attempts and tests in issue #1556   but I still can not find a solution..

**Comment by blink1073** [comment]
are you able to `pip install` anything else that depends on `numpy`?  Perhaps `scikit-learn`?

**Comment by blink1073** [comment]
I'm wondering if there's something unique about our `setup.py` file that might be causing you problems.

**Comment by antonio19812** [comment]
I can try.. ! and what should I do if setup.py is not that good?

**Comment by blink1073** [comment]
We may have to adopt something like what they're doing in our repo.  :smile:

**Comment by antonio19812** [comment]
now I will try and then I will tell you ;)

**Comment by antonio19812** [comment]
this is the output : 

antonio@linux-rosd:~> pip install scikit-learn
Downloading/unpacking scikit-learn
  Downloading scikit-learn-0.16.1.tar.gz (7.3MB): 7.3MB downloaded
  Running setup.py (path:/tmp/pip_build_antonio/scikit-learn/setup.py) egg_info for package scikit-learn
    Partial import of sklearn during the build process.
    
Installing collected packages: scikit-learn
  Running setup.py install for scikit-learn
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_antonio/scikit-learn/setup.py", line 173, in <module>
        setup_package()
      File "/tmp/pip_build_antonio/scikit-learn/setup.py", line 165, in setup_package
        from numpy.distutils.core import setup
    ImportError: No module named 'numpy'
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_antonio/scikit-learn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4fx6fkkm-record/install-record.txt --single-version-externally-managed --compile:
    Partial import of sklearn during the build process.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_antonio/scikit-learn/setup.py", line 173, in <module>

    setup_package()

  File "/tmp/pip_build_antonio/scikit-learn/setup.py", line 165, in setup_package

    from numpy.distutils.core import setup

ImportError: No module named 'numpy'

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_antonio/scikit-learn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4fx6fkkm-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_antonio/scikit-learn
Storing debug log for failure in /home/antonio/.pip/pip.log

**Comment by blink1073** [comment]
I am very much stumped at this point.  If you want an escape hatch, you could install Miniconda and then `conda install scikit-image` will give you v0.11.

http://conda.pydata.org/miniconda

**Comment by sciunto** [comment]
Can you provide the outputs of

```
pip -V
python -V
```

**Comment by antonio19812** [comment]
Yes i will execute now

**Comment by antonio19812** [comment]
and thanks blink1073 i can try miniconda if I will not find a solution!! what about installing the whole anaconda after creating a new cleaned VM of suse?

**Comment by blink1073** [comment]
@antonio19812, that works too, I just didn't want to flood you with packages you may not need.  :smile:

**Comment by sciunto** [comment]
I'm wondering if pip and python are of the same version. If pip refers to another version (bad symlink...), it could explain why the import of numpy works and pip could not find it.

**Comment by antonio19812** [comment]
this is the output >
antonio@linux-rosd:~> pip -V
pip 1.5.6 from /usr/lib/python3.4/site-packages (python 3.4)

antonio@linux-rosd:~> python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib64/python2.7/site.pyc matches /usr/lib64/python2.7/site.py
import site # precompiled from /usr/lib64/python2.7/site.pyc
# /usr/lib64/python2.7/os.pyc matches /usr/lib64/python2.7/os.py
import os # precompiled from /usr/lib64/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib64/python2.7/posixpath.pyc matches /usr/lib64/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib64/python2.7/posixpath.pyc
# /usr/lib64/python2.7/stat.pyc matches /usr/lib64/python2.7/stat.py
import stat # precompiled from /usr/lib64/python2.7/stat.pyc
# /usr/lib64/python2.7/genericpath.pyc matches /usr/lib64/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib64/python2.7/genericpath.pyc
# /usr/lib64/python2.7/warnings.pyc matches /usr/lib64/python2.7/warnings.py
import warnings # precompiled from /usr/lib64/python2.7/warnings.pyc
# /usr/lib64/python2.7/linecache.pyc matches /usr/lib64/python2.7/linecache.py
import linecache # precompiled from /usr/lib64/python2.7/linecache.pyc
# /usr/lib64/python2.7/types.pyc matches /usr/lib64/python2.7/types.py
import types # precompiled from /usr/lib64/python2.7/types.pyc
# /usr/lib64/python2.7/UserDict.pyc matches /usr/lib64/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib64/python2.7/UserDict.pyc
# /usr/lib64/python2.7/_abcoll.pyc matches /usr/lib64/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib64/python2.7/_abcoll.pyc
# /usr/lib64/python2.7/abc.pyc matches /usr/lib64/python2.7/abc.py
import abc # precompiled from /usr/lib64/python2.7/abc.pyc
# /usr/lib64/python2.7/_weakrefset.pyc matches /usr/lib64/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib64/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib64/python2.7/copy_reg.pyc matches /usr/lib64/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib64/python2.7/copy_reg.pyc
# /usr/lib64/python2.7/traceback.pyc matches /usr/lib64/python2.7/traceback.py
import traceback # precompiled from /usr/lib64/python2.7/traceback.pyc
# /usr/lib64/python2.7/sysconfig.pyc matches /usr/lib64/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib64/python2.7/sysconfig.pyc
# /usr/lib64/python2.7/re.pyc matches /usr/lib64/python2.7/re.py
import re # precompiled from /usr/lib64/python2.7/re.pyc
# /usr/lib64/python2.7/sre_compile.pyc matches /usr/lib64/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib64/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib64/python2.7/sre_parse.pyc matches /usr/lib64/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib64/python2.7/sre_parse.pyc
# /usr/lib64/python2.7/sre_constants.pyc matches /usr/lib64/python2.7/sre_constnts.py
import sre_constants # precompiled from /usr/lib64/python2.7/sre_constants.pyc
# /usr/lib64/python2.7/_sysconfigdata.pyc matches /usr/lib64/python2.7/_sysconfgdata.py
import _sysconfigdata # precompiled from /usr/lib64/python2.7/_sysconfigdata.py
import encodings # directory /usr/lib64/python2.7/encodings
# /usr/lib64/python2.7/encodings/__init__.pyc matches /usr/lib64/python2.7/encoings/__init__.py
import encodings # precompiled from /usr/lib64/python2.7/encodings/__init__.pyc
# /usr/lib64/python2.7/codecs.pyc matches /usr/lib64/python2.7/codecs.py
import codecs # precompiled from /usr/lib64/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib64/python2.7/encodings/aliases.pyc matches /usr/lib64/python2.7/encodngs/aliases.py
import encodings.aliases # precompiled from /usr/lib64/python2.7/encodings/aliaes.pyc
# /usr/lib64/python2.7/encodings/utf_8.pyc matches /usr/lib64/python2.7/encodins/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib64/python2.7/encodings/utf_8.yc
Python 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/lib64/python2.7/lib-dynload/readline.so", 2);
import readline # dynamically loaded from /usr/lib64/python2.7/lib-dynload/readine.so
# /usr/lib64/python2.7/atexit.pyc matches /usr/lib64/python2.7/atexit.py
import atexit # precompiled from /usr/lib64/python2.7/atexit.pyc
# /usr/lib64/python2.7/rlcompleter.pyc matches /usr/lib64/python2.7/rlcompleterpy
import rlcompleter # precompiled from /usr/lib64/python2.7/rlcompleter.pyc
>>> 
KeyboardInterrupt
>>>

**Comment by sciunto** [comment]
pip 3.4 vs python 2.7, that's the reason!

**Comment by antonio19812** [comment]
yes I realized this now, and what should I do ? uninstall pip or what?

**Comment by sciunto** [comment]
I asked python -V not -v, which is less verbose, but doesn't matter :)

Check if you can find a command like pip2  or pip2.7, or if you can install it. It seems that two versions are badly mixed.

**Comment by blink1073** [comment]
@antonio19812, did you install `python-pip` from yast?
You can force a pip install using: https://bootstrap.pypa.io/get-pip.py (create a local file, paste that in there), and run it as root).

**Comment by antonio19812** [comment]
i removed python3-pip with YAST manager

**Comment by antonio19812** [comment]
now I have not PIP installed

**Comment by antonio19812** [comment]
now I have the pip for python 2.7, I tried again to install scikit image and this is : 

antonio@linux-rosd:~> pip -V
pip 1.5 from /usr/lib/python2.7/site-packages (python 2.7)
antonio@linux-rosd:~> pip install -U scikit-image
Downloading/unpacking scikit-image

pip can't proceed with requirement 'scikit-image' due to a pre-existing build directory.
 location: /tmp/pip_build_antonio/scikit-image
This is likely due to a previous installation that failed.
pip is being responsible and not assuming it can delete this.
Please delete it and try again.

Storing debug log for failure in /home/antonio/.pip/pip.log
antonio@linux-rosd:~> 

how can i delete that ?

**Comment by antonio19812** [comment]
ok I tried finally to install scikit-image after deleting the bad directory , and these are the problems : 

antonio@linux-rosd:~> pip install -U scikit-image
Downloading/unpacking scikit-image
  Downloading scikit-image-0.11.3.tar.gz (18.6MB): 18.6MB downloaded
  Running setup.py (path:/tmp/pip_build_antonio/scikit-image/setup.py) egg_info for package scikit-image
    Cython not found; falling back to pre-built geometry.c
    Cython not found; falling back to pre-built transform.c
    Cython not found; falling back to pre-built _draw.c
    Cython not found; falling back to pre-built corner_cy.c
    Cython not found; falling back to pre-built censure_cy.c
    Cython not found; falling back to pre-built orb_cy.c
    Cython not found; falling back to pre-built brief_cy.c
    Cython not found; falling back to pre-built _texture.c
    Cython not found; falling back to pre-built _hessian_det_appx.c
    Cython not found; falling back to pre-built _unwrap_1d.c
    Cython not found; falling back to pre-built _unwrap_2d.c
    Cython not found; falling back to pre-built _unwrap_3d.c
    Cython not found; falling back to pre-built _denoise_cy.c
    Cython not found; falling back to pre-built _nl_means_denoising.c
    Cython not found; falling back to pre-built _ctmf.c
    Cython not found; falling back to pre-built rank/core_cy.c
    Cython not found; falling back to pre-built rank/generic_cy.c
    Cython not found; falling back to pre-built rank/percentile_cy.c
    Cython not found; falling back to pre-built rank/bilateral_cy.c
    Cython not found; falling back to pre-built _ncut_cy.c
    Cython not found; falling back to pre-built _spath.c
    Cython not found; falling back to pre-built _mcp.c
    Cython not found; falling back to pre-built heap.c
    Cython not found; falling back to pre-built _plugins/_colormixer.c _plugins/_histograms.c
    Cython not found; falling back to pre-built _ccomp.c
    Cython not found; falling back to pre-built _find_contours_cy.c
    Cython not found; falling back to pre-built _moments_cy.c
    Cython not found; falling back to pre-built _marching_cubes_cy.c
    Cython not found; falling back to pre-built _pnpoly.c
    Cython not found; falling back to pre-built _watershed.c
    Cython not found; falling back to pre-built _skeletonize_cy.c
    Cython not found; falling back to pre-built _convex_hull.c
    Cython not found; falling back to pre-built _greyreconstruct.c
    Cython not found; falling back to pre-built _hough_transform.c
    Cython not found; falling back to pre-built _warps_cy.c
    Cython not found; falling back to pre-built _radon_transform.c
    Cython not found; falling back to pre-built _felzenszwalb_cy.c
    Cython not found; falling back to pre-built _quickshift.c
    Cython not found; falling back to pre-built _slic.c
    build_src
    building extension "skimage._shared.geometry" sources
    building extension "skimage._shared.transform" sources
    building extension "skimage.draw._draw" sources
    building extension "skimage.feature.corner_cy" sources
    building extension "skimage.feature.censure_cy" sources
    building extension "skimage.feature.orb_cy" sources
    building extension "skimage.feature.brief_cy" sources
    building extension "skimage.feature._texture" sources
    building extension "skimage.feature._hessian_det_appx" sources
    building extension "skimage.restoration._unwrap_1d" sources
    building extension "skimage.restoration._unwrap_2d" sources
    building extension "skimage.restoration._unwrap_3d" sources
    building extension "skimage.restoration._denoise_cy" sources
    building extension "skimage.restoration._nl_means_denoising" sources
    building extension "skimage.filters._ctmf" sources
    building extension "skimage.filters.rank.core_cy" sources
    building extension "skimage.filters.rank.generic_cy" sources
    building extension "skimage.filters.rank.percentile_cy" sources
    building extension "skimage.filters.rank.bilateral_cy" sources
    building extension "skimage.future.graph._ncut_cy" sources
    building extension "skimage.graph._spath" sources
    building extension "skimage.graph._mcp" sources
    building extension "skimage.graph.heap" sources
    building extension "skimage.io._plugins._colormixer" sources
    building extension "skimage.io._plugins._histograms" sources
    building extension "skimage.measure._ccomp" sources
    building extension "skimage.measure._find_contours_cy" sources
    building extension "skimage.measure._moments_cy" sources
    building extension "skimage.measure._marching_cubes_cy" sources
    building extension "skimage.measure._pnpoly" sources
    building extension "skimage.morphology._watershed" sources
    building extension "skimage.morphology._skeletonize_cy" sources
    building extension "skimage.morphology._convex_hull" sources
    building extension "skimage.morphology._greyreconstruct" sources
    building extension "skimage.transform._hough_transform" sources
    building extension "skimage.transform._warps_cy" sources
    building extension "skimage.transform._radon_transform" sources
    building extension "skimage.segmentation._felzenszwalb_cy" sources
    building extension "skimage.segmentation._quickshift" sources
    building extension "skimage.segmentation._slic" sources
    building extension "skimage.external.tifffile._tifffile" sources
    building data_files sources
    build_src: building npy-pkg config files
    
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/gh-pages'
Downloading/unpacking matplotlib>=1.1.0 from https://pypi.python.org/packages/source/m/matplotlib/matplotlib-1.4.3.tar.gz#md5=86af2e3e3c61849ac7576a6f5ca44267 (from scikit-image)
  Downloading matplotlib-1.4.3.tar.gz (50.4MB): 50.4MB downloaded
  Running setup.py (path:/tmp/pip_build_antonio/matplotlib/setup.py) egg_info for package matplotlib
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [1.4.3]
                    python: yes [2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]]
                  platform: yes [linux2]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.9.0]
                       six: yes [using six version 1.8.0]
                  dateutil: yes [using dateutil version 2.1]
                      pytz: yes [using pytz version 2014.4]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [using pyparsing version 2.0.1]
                     pycxx: yes [Couldn't import.  Using local copy.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: yes [nose 0.11.1 or later is required to run the
                            matplotlib test suite.  pip/easy_install may attempt
                            to install it after matplotlib. / mock is required
                            to run the matplotlib test suite.  pip/easy_install
                            may attempt to install it after matplotlib.]
            toolkits_tests: yes [nose 0.11.1 or later is required to run the
                            matplotlib test suite.  pip/easy_install may attempt
                            to install it after matplotlib. / mock is required
                            to run the matplotlib test suite.  pip/easy_install
                            may attempt to install it after matplotlib.]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PyQt5 not found]
                    qt4agg: yes [installing, Qt: 4.8.6, PyQt: 4.8.6]
                    pyside: no  [PySide not found]
                   gtk3agg: yes [installing, version 3.3.14]
                 gtk3cairo: yes [installing, version 3.3.14]
                    gtkagg: no  [The C/C++ header for gtk (gtk/gtk.h) could not
                            be found.  You may need to install the development
                            package.]
                     tkagg: no  [The C/C++ header for Tk (tk.h) could not be
                            found.  You may need to install the development
                            package.]
                     wxagg: no  [requires wxPython]
                       gtk: no  [The C/C++ header for gtk (gtk/gtk.h) could not
                            be found.  You may need to install the development
                            package.]
                       agg: yes [installing]
                     cairo: yes [installing, pycairo version 1.10.0]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: yes [version 9.15]
                     latex: no
                   pdftops: yes [version 0.26.5]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
    Complete output from command python setup.py egg_info:
    ============================================================================

Edit setup.cfg to change the build options



BUILDING MATPLOTLIB

            matplotlib: yes [1.4.3]

                python: yes [2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]]

              platform: yes [linux2]



REQUIRED DEPENDENCIES AND EXTENSIONS

                 numpy: yes [version 1.9.0]

                   six: yes [using six version 1.8.0]

              dateutil: yes [using dateutil version 2.1]

                  pytz: yes [using pytz version 2014.4]

               tornado: yes [tornado was not found. It is required for the

                        WebAgg backend. pip/easy_install may attempt to

                        install it after matplotlib.]

             pyparsing: yes [using pyparsing version 2.0.1]

                 pycxx: yes [Couldn't import.  Using local copy.]

                libagg: yes [pkg-config information for 'libagg' could not

                        be found. Using local copy.]

              freetype: no  [The C/C++ header for freetype2 (ft2build.h)

                        could not be found.  You may need to install the

                        development package.]

                   png: no  [pkg-config information for 'libpng' could not

                        be found.]

                 qhull: yes [pkg-config information for 'qhull' could not be

                        found. Using local copy.]



OPTIONAL SUBPACKAGES

           sample_data: yes [installing]

              toolkits: yes [installing]

                 tests: yes [nose 0.11.1 or later is required to run the

                        matplotlib test suite.  pip/easy_install may attempt

                        to install it after matplotlib. / mock is required

                        to run the matplotlib test suite.  pip/easy_install

                        may attempt to install it after matplotlib.]

        toolkits_tests: yes [nose 0.11.1 or later is required to run the

                        matplotlib test suite.  pip/easy_install may attempt

                        to install it after matplotlib. / mock is required

                        to run the matplotlib test suite.  pip/easy_install

                        may attempt to install it after matplotlib.]



OPTIONAL BACKEND EXTENSIONS

                macosx: no  [Mac OS-X only]

                qt5agg: no  [PyQt5 not found]

                qt4agg: yes [installing, Qt: 4.8.6, PyQt: 4.8.6]

                pyside: no  [PySide not found]

               gtk3agg: yes [installing, version 3.3.14]

             gtk3cairo: yes [installing, version 3.3.14]

                gtkagg: no  [The C/C++ header for gtk (gtk/gtk.h) could not

                        be found.  You may need to install the development

                        package.]

                 tkagg: no  [The C/C++ header for Tk (tk.h) could not be

                        found.  You may need to install the development

                        package.]

                 wxagg: no  [requires wxPython]

                   gtk: no  [The C/C++ header for gtk (gtk/gtk.h) could not

                        be found.  You may need to install the development

                        package.]

                   agg: yes [installing]

                 cairo: yes [installing, pycairo version 1.10.0]

             windowing: no  [Microsoft Windows only]



OPTIONAL LATEX DEPENDENCIES

                dvipng: no

           ghostscript: yes [version 9.15]

                 latex: no

               pdftops: yes [version 0.26.5]



============================================================================

                        * The following required packages can not be built:

                        * freetype, png

**Comment by blink1073** [comment]
You can install `python-matplotlib` with yast.

**Comment by antonio19812** [comment]
I already have it installed, I saw this from YAST, now I  am installing Cython, with pip install Cython

**Comment by antonio19812** [comment]
I have installed cython from pip, and freetype from Yast, but png seems to be already installed, so why should I need to install it again?

**Comment by antonio19812** [comment]
now I only obtained : 

the following required packages can not be built:

                        * png

but from YAST i saw that libpng16-16 and libpng16-16-32bit are installed

**Comment by blink1073** [comment]
Try a pip install without the -U, it is trying to upgrade matplotlib.



—

**Comment by antonio19812** [comment]
ok, I will try it!!

**Comment by antonio19812** [comment]
at the moment it is running and installing without stopping , as it stopped in the previous attempts..

**Comment by antonio19812** [comment]
gosh!! i have to install it again adding sudo at the beginning, otherwise it can not add scikit to the packages of python...

**Comment by antonio19812** [comment]
installed!!!!! thanks so much to everyone!!! you can not even imagine the huge you all gave to me!! thanks

**Comment by antonio19812** [comment]
then i will try if it works but the installation was successful, so thanks
