### ISSUE TITLE
MB-LBP example does not show plot.

### ISSUE THREAD

**Issue by vighneshbirodkar** [scikit-image/scikit-image#1561]
At the end of `plot_multiblock_local_binary_pattern.py` we need to add a `plt.show()` command so that executing it with the shell also outputs the plot.

@warmspringwinds Should be a quick fix.

**Comment by warmspringwinds** [comment]
@vighneshbirodkar 
Thank you. I forgot to add it.

**Comment by JDWarner** [comment]
Closed by #1562
