### ISSUE TITLE
Aliasing for line_aa with slope greater than 1

### ISSUE THREAD

**Issue by connellybarnes** [scikit-image/scikit-image#1563]
skimage.draw.line_aa() aliases when the slope is greater than 1 in magnitude. It works correctly, however, when the slope is less than 1 in magnitude.

Below is a unit test. When the bug is fixed, the final assertion should succeed. Also, once the bug is fixed, you should be able to see that the two printed arrays are near transposes of each other.

Test code:

    from skimage.draw import line_aa
    import numpy

    img1 = numpy.zeros((10, 10), dtype=numpy.uint8)
    rr, cc, val = line_aa(4, 1, 5, 8)       # Draw almost horizontal line
    img1[rr, cc] = val * 255
    print 'Correct:'
    print img1

    img2 = numpy.zeros((10, 10), dtype=numpy.uint8)
    rr, cc, val = line_aa(1, 4, 8, 5)       # Draw almost vertical line
    img2[rr, cc] = val * 255
    print 'Incorrect (aliased):'
    print img2

    # Take difference between transposed img2 and img1
    diff = (numpy.array(img1, float)-numpy.array(img2.transpose(),float))
    print 'Difference between the two after transposition:'
    print diff
    diff_ssd = numpy.sqrt(numpy.sum(diff**2))
    assert diff_ssd < 50, 'Expected difference to be small'

**Comment by connellybarnes** [comment]
Below is a trivial fix that simply transposes the call to the underlying C line_aa() function if the magnitude of the slope is greater than one. It passes the above unit test. But a cleaner fix could be made by fixing the underlying C line_aa() implementation.

    # Trivial fix for scikit-image bug #1563
    def line_aa(y1, x1, y2, x2):
        dx = abs(x2-x1)
        dy = abs(y2-y1)
        if dx >= dy:
            return skimage.draw.line_aa(y1, x1, y2, x2)
        else:
            (Y, X, intensity) = skimage.draw.line_aa(x1, y1, x2, y2)
            return (X, Y, intensity)

**Comment by JDWarner** [comment]
Ping @ahojnnes, the master of our line drawing functions.

**Comment by JDWarner** [comment]
I can reproduce this. The results look passable from a distance, but something is definitely amiss. They are are discernibly more jagged when you know what to look for, even from afar.

A cleaner script, and its result:

``` python
import numpy as np
import matplotlib.pyplot as plt
from skimage.draw import line_aa

fig, (ax0, ax1, ax2) = plt.subplots(ncols=3, figsize=(10, 6))

# Make some example images
img1 = np.zeros((25, 25))
img2 = np.zeros((25, 25))

# Near-horizontal line
rr, cc, val = line_aa(10, 2, 12, 20)
img1[rr, cc] = val

# Near-vertical (transpose of prior)
rr, cc, val = line_aa(2, 10, 20, 12)
img2[rr, cc] = val

# Difference - should be zero
diff = img1 - img2.T

# Plot the results
ax0.imshow(img1, cmap='gray', interpolation='nearest')
ax1.imshow(img2, cmap='gray', interpolation='nearest')
ax2.imshow(diff, cmap='gray', interpolation='nearest')
plt.show()
```

![image](https://cloud.githubusercontent.com/assets/2184487/8632072/f1b2dcd4-2750-11e5-8c5e-2341ad7e2397.png)
