### ISSUE TITLE
threshold_li Modifies Passed data

### ISSUE THREAD

**Issue by david-hoffman** [scikit-image/scikit-image#1567]
When calling `skimage.features.threshold_li(image)` the image is modified. The code most likely at fault is line 342:

```python
image -= offset
```

An easy workaround is to simply call `skimage.features.threshold_li(image.copy())` so that only a copy of the image is passed to the function. And the original data is left unmodified.

**Comment by JDWarner** [comment]
You're correct, and while your workaround is usable this is a bug and we will fix it.

**Comment by sciunto** [comment]
I started a PR with some thoughts. Please, comment! :)
