### ISSUE TITLE
Can not successfully run plot_blob.py

### ISSUE THREAD

**Issue by liuyifly06** [scikit-image/scikit-image#1574]
I have already installed "$ brew install libtiff libjpeg webp little-cms2" and "$ pip install Pillow".

Please help me.

Traceback (most recent call last):
  File "plot_blob.py", line 46, in <module>
    image = data.hubble_deep_field()[0:500, 0:500]
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/data/__init__.py", line 243, in hubble_deep_field
    return load("hubble_deep_field.jpg")
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/data/__init__.py", line 46, in load
    return imread(_os.path.join(data_dir, f))
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/io/_io.py", line 100, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/io/_plugins/pil_plugin.py", line 52, in imread
    raise ValueError('Could not load "%s"\nPlease see documentation at: %s' % (fname, site))
ValueError: Could not load "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/data/hubble_deep_field.jpg"
Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries

**Comment by blink1073** [comment]
Hi @liuyifly06, can you try the following and post the output?

```bash
$ cd /Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/data/
$ python -c "from PIL import Image; print(Image.open('hubble_deep_field.jpg').getdata())"
```

**Comment by liuyifly06** [comment]
Hi @blink1073 , thank you for your reply. The following error appeared with that command:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 63, in <module>
    warnings.warn(
ImportError: cannot import name _imaging

**Comment by blink1073** [comment]
Hmm, `imaging.so` is a compiled extension in PIL, it looks like something went wrong in with `pip install Pillow`.  Can you try the following and post the output?

```bash
$ pip uninstall Pillow -y
$ pip install Pillow
```

**Comment by liuyifly06** [comment]
@blink1073  still not working after doing that. Same error.
When I was installing first time, I used command:

$ brew install libtiff libjpeg webp little-cms2
$ pip install Pillow

not idea why it is not working

**Comment by blink1073** [comment]
The pillow install itself completed without error?

**Comment by liuyifly06** [comment]
@blink1073  yes, I think so.

LiuYis-MacBook-Air:data liuyi$ sudo pip uninstall pillow -y
The directory '/Users/liuyi/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/liuyi/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling Pillow-2.8.2:
  Successfully uninstalled Pillow-2.8.2
LiuYis-MacBook-Air:data liuyi$ sudo pip install pillow
The directory '/Users/liuyi/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/liuyi/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pillow
/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Pillow-2.8.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.8MB)
    100% |████████████████████████████████| 2.8MB 120kB/s 
Installing collected packages: pillow
Successfully installed pillow-2.8.2

**Comment by JDWarner** [comment]
I think we may be dealing with two separate Python installs.

The original report points to `/Library/Python/2.7` while the attempt to run Pillow points to `/usr/local/lib/python2.7`

What are the results of 

```
which python
which pip
```

**Comment by liuyifly06** [comment]
@ JDWarner
LiuYis-MacBook-Air:data liuyi$ which python
/usr/bin/python
LiuYis-MacBook-Air:data liuyi$ which pip
/usr/local/bin/pip
LiuYis-MacBook-Air:data liuyi$

**Comment by blink1073** [comment]
How about 

```bash
$ cat `which pip`
```

**Comment by liuyifly06** [comment]
@blink1073 
Here is the result 

LiuYis-MacBook-Air:python liuyi$ cat `which pip`
#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from pip import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

Also when I try to run plot_blob.py now,  it shows:

LiuYis-MacBook-Air:python liuyi$ python plot_blob.py
Traceback (most recent call last):
  File "plot_blob.py", line 41, in <module>
    from skimage import data
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/data/__init__.py", line 12, in <module>
    from ..io import imread, use_plugin
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/io/manage_plugins.py", line 27, in <module>
    from .collection import imread_collection_wrapper
  File "/Library/Python/2.7/site-packages/scikit_image-0.11.3-py2.7-macosx-10.10-intel.egg/skimage/io/collection.py", line 12, in <module>
    from PIL import Image
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 63, in <module>
ImportError: cannot import name _imaging

**Comment by liuyifly06** [comment]
Also, When I type:
$ Python -V
....
>>> import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Image

**Comment by liuyifly06** [comment]
Not sure if this information helps
$Python -V
$ .....
$ >>> import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Image

**Comment by blink1073** [comment]
@liuyifly06, the command is `from PIL import Image`.

**Comment by liuyifly06** [comment]
@blink1073 
LiuYis-MacBook-Air:~ liuyi$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
$ >>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 63, in <module>
ImportError: cannot import name _imaging
$ >>>

**Comment by liuyifly06** [comment]
should I try this ?  @blink1073 
someone mentioned  that

 "I ran into this problem as well. It can happen if you have PIL installed, then install Pillow on top of it.

Go to /usr/local/lib/python2.7/dist-packages/ and delete anything with "PIL" in the name (including directories). If the Pillow .egg file is there you might as well delete that too. Then re-install Pillow.

substitute "python2.7" for the version of python you're using."

**Comment by liuyifly06** [comment]
Never Mind, Actually, I can not find that directory (/dist-packages/ )...

**Comment by JDWarner** [comment]
It would be `/site-packages/`

**Comment by liuyifly06** [comment]
@JDWarner   @blink1073 
seems work

After remove PIL from /site-packages/.
and type $ brew uninstall pillow
$ brew install pillow
$ brew link pillow
error appears about conflict files.
then delete every conflict files appeared in link process
$ brew link pillow

then type

LiuYis-MacBook-Air:data liuyi$ python -c "from PIL import Image; print(Image.open('hubble_deep_field.jpg').getdata())"
<ImagingCore object at 0x10d082130>
LiuYis-MacBook-Air:data liuyi$ s

**Comment by liuyifly06** [comment]
Everything works fine now. Thanks for your help. @blink1073   @JDWarner

**Comment by blink1073** [comment]
Great, cheers.
