### ISSUE TITLE
help

### ISSUE THREAD

**Issue by antonio19812** [scikit-image/scikit-image#1577]
This is not really an issue but it is the only way I can ask for some help or hints.
I am creating a GUI for my image processing project and I would like to use the ImageViewer interface adding some plugins that can be useful for me. The problem is that the explanation about how to create a new plugin with its widget is not so clear for me. Where could I find some more elements? or where could I talk with someone can help me?

**Comment by blink1073** [comment]
Hi @antonio19812, we could certainly stand to document the process better.  Have you seen this [example](https://github.com/scikit-image/scikit-image/blob/master/viewer_examples/plugins/collection_plugin.py)?  

If you give more information of what you are trying to achieve, we should be able to talk you through it.

**Comment by antonio19812** [comment]
yes, this example seems really to be better I will look through it and if it won't be enough I will ask for help again. But I hope I will not have to annoy all of you again!!

thanks  so far!!

**Comment by blink1073** [comment]
You're helping us get better, not annoying us :smile:  

Cheers!

**Comment by antonio19812** [comment]
Actually for what I have quickly seen, this example is quite helpful about how to create a plugin, the example in the ImageViewer section of the scikit-image site does not provide some general elements to do it. 
I will give you some updates ;)

**Comment by stefanv** [comment]
Other channels of support, for future reference: the [mailing list](http://groups.google.com/group/scikit-image) and the [Gitter channel](https://gitter.im/scikit-image/scikit-image).

**Comment by antonio19812** [comment]
so is it better to write there about this aspects? or even here?

**Comment by stefanv** [comment]
I think better to try chat and, if you don't get a response, ping the mailing list.  Issues we keep for discussions relating to development.
