### ISSUE TITLE
In user guide, "Image Segmentation" should be listed under tutorials

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1579]
http://scikit-image.org/docs/stable/user_guide.html

**Comment by michaelpacer** [comment]
https://github.com/scikit-image/scikit-image/pull/1600 should cover this.

**Comment by robintw** [comment]
This seems to be fixed now - see http://scikit-image.org/docs/stable/user_guide.html

**Comment by stefanv** [comment]
Closed by #1600
