### ISSUE TITLE
Add visual feedback to `skimage.novice`

### ISSUE THREAD

**Issue by library111** [scikit-image/scikit-image#1588]
A novice user is not getting visual feedback while going through the lesson. When fixing, should keep in mind 
- some users may use the terminal, ipython and/or ipython notebook
- would also be nice to save the original image in case a mistake is made
  - side note, some commands on how to "undo" should a mistake be made

**Comment by souravsingh** [comment]
I would like to work on the issue.How do I start?

**Comment by stefanv** [comment]
@souravsingh What do you need to know?  How to start technically, or how to address the issue?  I think the latter is clear from the above, so I presume you mean the prior:

http://scikit-image.org/docs/stable/contribute.html

**Comment by souravsingh** [comment]
I am sorry. I wanted to know about how to save the image if a mistake is made.Others are understandable.

**Comment by stefanv** [comment]
Reading through the code here would be a good start: https://github.com/scikit-image/scikit-image/blob/master/skimage/novice/_novice.py

**Comment by sciunto** [comment]
@souravsingh Did you work on this task?

**Comment by soupault** [comment]
`novice` module is to be removed (see #2742)
