### ISSUE TITLE
Module Novice: original image should be shown alongside modified image

### ISSUE THREAD

**Issue by david1koeller** [scikit-image/scikit-image#1589]
A novice user would benefit from seeing the original image along with the modified image in the novice module. Additionally, a third image could display the difference between the original and modified could be displayed. Currently, no image is displayed, which leaves novice users confused to the modifications they are doing.

**Comment by soupault** [comment]
This issue is essentially a duplicate of https://github.com/scikit-image/scikit-image/issues/1588.
Reopen if disagree.
