### ISSUE TITLE
Documentation does not explain how to build the docs

### ISSUE THREAD

**Issue by library111** [scikit-image/scikit-image#1591]
(go in to the docs directory and type 'make')

**Comment by library111** [comment]
Found it here:

https://github.com/scikit-image/scikit-image/blob/master/doc/README.md

It's not being built into HTML by Sphinx.

**Comment by stefanv** [comment]
That file is markdown format, so isn't meant to be included.  Where would you ideally like this information to be displayed?

**Comment by library111** [comment]
This is where we looked:

http://scikit-image.org/docs/dev/contribute.html

**Comment by emmanuelle** [comment]
I think that http://scikit-image.org/docs/dev/contribute.html would be the right place to explain how to build the docs, since it's typically contributors who will do it.
