### ISSUE TITLE
import configparser for python2

### ISSUE THREAD

**Issue by CharlesMei** [scikit-image/scikit-image#1611]
I use python2.7
File "Anaconda\lib\site-packages\skimage\io\manage_plugins.py", line 101, in _parse_config_file
    parser = ConfigParser()
this is because the wrong import of configparser,
from configparser import ConfigParser works for no exception, so the except part doesn't run
we can change 
try:
    from configparser import ConfigParser  # Python 3
except ImportError:
    from ConfigParser import ConfigParser  # Python 2
to the following code 
import sys
PY2 = sys.version[0] == '2'
PY3 = sys.version[0] == '3'
if PY2:
	from ConfigParser import ConfigParser  # Python 2
else:
	from configparser import ConfigParser  # Python 3

**Comment by stefanv** [comment]
I'm confused--how did this manage to pass all the unit tests?

**Comment by blink1073** [comment]
I tried `from configparser import ConfigParser` on Python 2.7, it gives an `ImportError` as expected.  Something must be off on your system @CharlesMei.

**Comment by blink1073** [comment]
But, we could certainly be more explicit here.

**Comment by CharlesMei** [comment]
@blink1073 Maybe you are right. I  test it on another pc, it gives an ImportError as you say. I think this may owing to my installation of theano. I use anaconda (python2.7) and create an env python3.4, after the installation of theano for python2.7, i can't start spyder for python3.4 now(some error about configparser and theano), but i can use theano for python2.7 even with gpu. Thank you.
