### ISSUE TITLE
[RFC] Cache intersphinx inventory for NumPy / SciPy / Scikit-Learn

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1615]
Sphinx 1.3 adds the ability to specify a per-inventory (set of) fallback(s) in `conf.py` if loading intersphinx inventories fail: http://sphinx-doc.org/ext/intersphinx.html

SourceForge has been having problems all day long, which has kept the scikit-learn.org page offline. Thus, all of our builds fail when they attempt to load the intersphinx inventory from scikit-learn.

The benefits are obvious, but this would mean requiring Sphinx 1.3 for building the docs and periodically updating the cache.

**Comment by JDWarner** [comment]
I would have led with a PR for this, but I still can't retrieve the scikit-learn inventory to cache it :(

**Comment by stefanv** [comment]
No problem moving this dependency to 1.3.

**Comment by stefanv** [comment]
Closed by #1628.
