### ISSUE TITLE
ImportError: cannot import name blob_dog

### ISSUE THREAD

**Issue by liuyifly06** [scikit-image/scikit-image#1619]
After installing on Ubuntu, trying to run plot_blob.py.
yi@yi-Linux:~/Desktop/python$ python plot_blob.py
Traceback (most recent call last):
  File "plot_blob.py", line 42, in <module>
    from skimage.feature import blob_dog, blob_log, blob_doh
ImportError: cannot import name blob_dog

can not figure out why

**Comment by JDWarner** [comment]
Please post the result of `python -c "import skimage; print(skimage.__version__)"`

**Comment by liuyifly06** [comment]
0.9.3

**Comment by liuyifly06** [comment]
Actually, how to update it ...

**Comment by liuyifly06** [comment]
Solved by following: https://blackbricksoftware.com/bit-on-bytes/95-scikit-image-installation-for-ubuntu-14-04

**Comment by stefanv** [comment]
Also, if it would be helpful to have better installation instructions, please file a pull request!
