### ISSUE TITLE
NetworkX dropped support for Python 2.6 in version 1.10

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1629]
See [networkx/1185](https://github.com/networkx/networkx/issues/1185). Apparently Python 2.6 is now almost two years past end-of-life, and this was used as justification to drop official support. NetworkX still works perfectly fine on 2.6, but that version was removed from the support matrix so pip doesn't recognize this.

As of 8/2, when NetworkX 1.10 was released, every 2.6 build fails when attempting to install NetworkX.

The rest of the SciPy Stack continues to support and test against 2.6, as the burden is minimal if 2.7 is supported. I know of several production systems/workstations which still use 2.6 at my institution, and I fully expect many other systems continue to use variants of Enterprise Linux 6 which shipped with 2.6.x. RHEL 6 continues with full support until Q2 2016, and with security updates until 2020. If we drop 2.6 without good reason, these users will be justifiably displeased.

In my strongest opinion, when continuing support is trivial we should make every effort to do so. We should discuss with NetworkX devs if this support can be reinstated.

cc @ysitu @hagberg

**Comment by hagberg** [comment]
Those are good arguments for maintaining support for 2.6.  I'm willing to look into how hard it would be to make a 2.6-friendly release for networkx-1.10.  I don't have a Python2.6 setup right now to check for issues and fixes; it may not be that difficult.   If someone could help here we might be able to figure that out sooner than later. 

Generally I have been advocating for developing new modules with contemporary Python version style and idioms.  It makes it simpler and easier for developers.  Even though it may not be that much harder to support older versions, practically the project has to choose where to put our limited time and resources.   Fortunately, NetworkX has been growing very fast in the past few months with many new developers so the ability to develop and maintain high-quality well-tested code is expanding too.   Even so I don't expect that we are likely to want to support 2.6 significantly farther into the future.

**Comment by ysitu** [comment]
Backport of set literals, dict/set comprehension and `OrderedDict` in Python 2.7 makes it actually quite different from Python 2.6. Moreover, there have been numerous uses of these features in NetworkX 1.10 (in other words, NetworkX no longer "works perfectly fine on 2.6"). In fact, ordered graph classes, based on `OrderedDict`, is a major new feature in the 1.10 release. So there *is* good reason in dropping support for Python 2.6. Continuing to support Python 2.6 either prevents adoption of modern language features or creates extra development and maintenance burden. In particular, it is unreasonable to expect support for Python 2.6 till 2020, when Python 2.7 itself will also EOL after an exceptionally long lifetime. I believe that the more practical solution is to modify the setup script of SciPy and friends to use NetworkX 1.9.1 when testing against Python 2.6.

**Comment by tacaswell** [comment]
Personally, I would like to drop 2.6 for mpl as well asap (probably next year).  `OrderedDict` and dict comprehensions would both be super helpful.  

It is easy enough to install conda on older systems to get modern python and old versions will continue to work on old python.  It is unrealistic to expect to run a bleeding edge scientific stack on end-of-lifed system python.

**Comment by JDWarner** [comment]
For reference, `OrderedDict` can be supported all the way back to 2.4 with a conditional import of [this MIT-licensed backport](http://code.activestate.com/recipes/576693/).

**Comment by soupault** [comment]
@JDWarner Could we close this?

**Comment by JDWarner** [comment]
Yes, this is no longer an issue as of 0.13dev. For those few who may still be on Python 2.6, there are multiple robust options to get a newer Python version, even without root.
