### ISSUE TITLE
imsave() produces incorrect output for 3D array with width or height 1

### ISSUE THREAD

**Issue by connellybarnes** [scikit-image/scikit-image#1632]
To reproduce this bug, simply construct a 3D array with width or height 1 and use skimage.io.imsave(). For instance, we could save a 1x1 color image:

    >>> a=numpy.random.random((1,1,3))
    >>> skimage.io.imsave('a.png', a)
    ...
      File "/usr/local/lib/python2.7/site-packages/skimage/io/_plugins/pil_plugin.py", line 258, in imsave
        raise ValueError("Invalid shape for image array: %s" % arr.shape)
    ValueError: Invalid shape for image array: 3

The correct result would be to save a 1x1 PNG file.

Or we could save a width 1, height 3 color image:

    >>> a=numpy.random.random((3,1,3))
    >>> skimage.io.imsave('a.png', a)
    >>> skimage.io.imread('a.png').shape
    (3, 3)

This saves a 3x3 greyscale image instead!

The culprit is line 258 of skimage/io/_plugins/pil_plugin.py:

    arr = np.asanyarray(arr).squeeze()

The squeeze function removes all size one dimensions, which makes it impossible to save images with width or height one.

The exact fix depends on the desired semantics.

One conjectures that the squeeze() function is currently being used for convenience if one wants to save malformed slices from a high dimensional array. In general though, for this use case, it will be impossible to determine which dimensions correspond to actual height and width, and which correspond to size one slices that should be squeezed away. One possible resolution to this ambiguity is to assume that only trailing dimensions are "auto-squeezed" if the dimensionality is too large. That is, replace the above line with:

    arr = np.asanyarray(arr)
    if arr.ndim > 3:
      remaining_shape = arr.shape[3:]
      if remaining_shape == (1,)*len(remaining_shape):
        arr = arr.reshape(arr.shape[:3])
      else: 
        raise ValueError('malformed image shape: image array is more than 3 dims and trailing dimensions are not all one so they cannot be auto-squeezed')

**Comment by stefanv** [comment]
I think we should avoid too much magic and remove the squeeze.

**Comment by ahojnnes** [comment]
+1 I am always for less magic :-)

**Comment by JDWarner** [comment]
:+1: from me as well.

If we simply remove the squeeze, the exception remains informative for an image of shape (M, N, x) where x is anything except 3 or 4:

``` python
ValueError: Invalid number of channels in image array.
```

**Comment by JDWarner** [comment]
I have a fix on the way for this (as well as Travis).
