### ISSUE TITLE
enforce_label_connectivity with SLIC results in segfault

### ISSUE THREAD

**Issue by xkjyeah** [scikit-image/scikit-image#1635]
On certain images, enforce_label_connectivity fails with a segfault.

**Comment by ahojnnes** [comment]
This is not very useful without providing the images or a stack trace. Could you provide either of those?

**Comment by xkjyeah** [comment]
Thanks... it's a 4 channel image. I'm not sure how to attach it... Could I attach a .pickle instead? How should I do that?

**Comment by xkjyeah** [comment]
http://squidssquids.mooo.com/fails_slic.pickle

**Comment by emmanuelle** [comment]
It might be the same issue as #1448

**Comment by soupault** [comment]
This has to be verified against latest github version of `scikit-image` as #1448 has been fixed in it.

**Comment by stefanv** [comment]
I cannot load this pickle on either 2 or 3.  Can someone convert it to a png or .npy file?

**Comment by stefanv** [comment]
This works fine for me with the latest dev version under Python 3.  Closing unless someone else can replicate.
