### ISSUE TITLE
Add background keyword to remove_small_objects

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1642]
It could be nice to have a ``background`` keyword argument for ``morphology.remove_small_objects``, that would remove small holes instead of small objects. It's straightforward to do it with two calls to ``np.logical_not``, but it might be nicer to have the option within the function. Also, what should be the name of the keyword argument? I was thinking ``background=False``, but ``invert=False`` might be a solution as well.

**Comment by stefanv** [comment]
How about `morphology.remove_small_holes`? :)

**Comment by ahojnnes** [comment]
@stefanv +1

**Comment by emmanuelle** [comment]
I guess it makes sense :-).

**Comment by ashkurti** [comment]
I am going to start the sprint with this.

**Comment by ashkurti** [comment]
Before doing any modifications I wanted to have scikit-image up and running on my laptop. I have had the following problems so far with tests described at #1664 (that I managed to solve) and #1668.

**Comment by emmanuelle** [comment]
@ashkurti it's too bad that we haven't been able yet to fix #1668 for you, but I think this does not prevent you from working on ``remove_small_objects`` if you feel like to. Thank you!

**Comment by oew1v07** [comment]
@ashkurti Is it ok to start working on this? It'll take me a little while before I start doing anything so feel free to get back at any time.

**Comment by oew1v07** [comment]
I'm working on this now

**Comment by kshitij10496** [comment]
Is this issue still open ?

**Comment by oew1v07** [comment]
No my merge should have dealt with this - it will be available in v0.12

**Comment by jni** [comment]
@kshitij10496 thanks for helping with the triage!

**Comment by kshitij10496** [comment]
@jni Cool
