### ISSUE TITLE
Automated Retinex 

### ISSUE THREAD

**Issue by AbdullahAmer86** [scikit-image/scikit-image#1643]
Hi I'm working on retinex algorithm MSRCR and im trying to make the surround function to be automated not manually changed so is there any ideas or support regarding to my point ?
Abdullah Amer

**Comment by emmanuelle** [comment]
@AbdullahAmer86 Hi Abdullah, it is not clear to me how this is a related to an issue of the scikit-image package, could you please explain? If you're looking for help on image processing with scikit-image, the mailing-list (scikit-image@googlegroups.com) might be a better place to ask, but I think you need to give more details.
