### ISSUE TITLE
Cannot import modules in Anaconda 3

### ISSUE THREAD

**Issue by cpieringer** [scikit-image/scikit-image#1644]
Hi,

I installed Anaconda 3. I'm trying to import some modules from scikit-image but when I run my script it gives me an error. For example, if I want to convert an image to gray scale:

    import skimage
    img_gray = skimage.color.rgb2gray(img)

    [out] AttributeError: 'module' object has no attribute 'color'

Somebody have the same problem?

Best regards

**Comment by blink1073** [comment]
Hi @cpieringer, we purposely do not import all of the subpackages by default, to improve loading time.  You'd have to use something like:

```python
from skimage import color
img_gray = color.rgb2gray(img)
```

**Comment by cpieringer** [comment]
@blink1073 Thank you very much!

**Comment by blink1073** [comment]
Cheers!  Closing this as it seems your problem is solved, feel free to reopen if you disagree.
