### ISSUE TITLE
Should we rename gaussian_filter and gabor_filter to gaussian and gabor?

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1647]
All other filters are using just the name of the filter, so this could improve the consistency of the API. For example, ``median_filter`` has already been renamed to ``median``.

**Comment by JDWarner** [comment]
:+1:

**Comment by sumitbinnani** [comment]
Working on it :-)

**Comment by kshitij10496** [comment]
Shouldn't this issue be closed ?

**Comment by sumitbinnani** [comment]
The issue has been fixed. Not sure how to close it.

**Comment by JDWarner** [comment]
Thanks for the reminder - that's our job ;)
