### ISSUE TITLE
plot_hog.py results in strangely-looking figure in the gallery

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1648]
Compare http://scikit-image.org/docs/dev/_images/plot_hog_1.png and http://scikit-image.org/docs/0.11.x/_images/plot_hog_1.png

I don't think the example changed, so it must be inside the hog functions or in one of the functions called by this function.

**Comment by emmanuelle** [comment]
@ivoflipse you have been working on HOG recently, so you may have an idea of what is going wrong for the example. If you find a little time to take a look at it, that'd be awesome!

**Comment by ivoflipse** [comment]
Sorry @emmanuelle I had missed your mention, but I'm looking into it right now

**Comment by stefanv** [comment]
Thanks for doing that, @ivoflipse

**Comment by ivoflipse** [comment]
As a simple proxy for what could be wrong it seems that there's a large difference in the maximum values of both hog images. The old method gives an image with a max of **0.26** whereas the new method gives a max of **67.78**.

Since the code is pretty much the same up to the call to _hoghistogram and the hog_image code gives the same results, the problem seems isolated to the loop we replaced.

**Comment by ivoflipse** [comment]
After reading through the code some more, I think the difference is in the fact that the old approach masked the magnitude image, then applied a uniform filter and then subsampled the filtered magnitudes.

The new approach simply sums all magnitude values for coordinates that have the correct orientations in a small window (which I guess acts as a filter or subsampling strategy). However, it didn't correct the total. So if you divide total by (cell_rows * cell_columns), you get the following image:

![image](https://cloud.githubusercontent.com/assets/485186/11117153/adc03352-8937-11e5-8ebf-e9cb544cfd5e.png)

When I subtract the old result from this one, we get the following difference:

![image](https://cloud.githubusercontent.com/assets/485186/11117136/8f5524d6-8937-11e5-9416-38946d75b96e.png)

Which might still not be entirely what we want, but at least much closer to what we had before.

On a side-note I noticed that inside cell_hog we calculate 
```
   range_rows_stop = cell_rows/2
    range_rows_start = -range_rows_stop
    range_columns_stop = cell_columns/2
    range_columns_start = -range_columns_stop
```
Which are constant for all iterations, so we could move that calculation outside all the loops and just pass it along.

**Comment by Korijn** [comment]
I assume this correction is sufficient to resolve?

**Comment by stefanv** [comment]
What is the status of this issue?  If possible, we should resolve this
before releasing 0.12.

**Comment by ivoflipse** [comment]
@stefanv there are still small differences between the two implementations and I don't know how to adapt the Cython implementation to get rid of them.

I can make a PR with the changes that I made though and discuss it further there.

**Comment by Korijn** [comment]
After some new insights, the PR pretty much fixes all HOG related issues at this point. Ready to merge!
