### ISSUE TITLE
Structuring the example gallery a little more

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1651]
We're starting to have a large number of examples in the gallery (hurray!!), which makes it a bit difficult to find a specific application. I was thinking that might add one structuring layer on top of the gallery, with different sections. 

Possible sections could be

- color and exposure
- filtering, enhancement and denoising
- segmentation
- feature detection
- geometric transformations
- visualization

What do you think?

**Comment by stefanv** [comment]
I'm +1 on adding some sub-headings, but I would like for everything to
still appear visible on one page if possible.  I saw with scikit-learn
they make small icons that then blow up when you move the mouse across.

**Comment by emmanuelle** [comment]
+1 also for having everything on the same page.

**Comment by emmanuelle** [comment]
About the gallery, did you known about the ``sphinx-gallery`` package https://github.com/sphinx-gallery/sphinx-gallery ? It might be interesting for us to use it at some point, in order to have less maintenance for the gallery.

**Comment by ahojnnes** [comment]
+1 on having sections - ideally with a one-to-one correspondence with the `skimage.*` modules.

**Comment by emmanuelle** [comment]
@ahojnnes another possibility to have a correspondence with the user guide sections. Indeed, I think that people coming to the gallery are more thinking in terms of tasks to do, than in terms of submodules (although some sections of the user guide correspond to some submodules, of course).

**Comment by emmanuelle** [comment]
Also, one nice thing of ``sphinx-gallery`` is that you can link automatically to examples using a specific function inside the docstring of the function.

**Comment by ahojnnes** [comment]
@emmanuelle sounds good! Any kind of sectioning of the gallery would be
good. I don't have a strong opinion on the kind of sectioning.

**Comment by emmanuelle** [comment]
I'm currently working on sectioning the gallery. For this purpose, I'm using broad categories from the user guide and from submodules, but I've also downloaded statistics of page visits (thanks to @sciunto 's piwik logs!), and it's interesting to see which pages get visited together. Clustering pages thanks to the graph of visits shows trends in agreement with pre-defined categories, but it's also interesting to see visits as a graph and not only as clusters. 

Therefore, I was wondering whether it could be possible to add a "See also" at the end of a gallery example, to suggest pages that are often visited after the page. I don't see an obvious way to do this with sphinx, but others may have better ideas...

**Comment by emmanuelle** [comment]
Solved by #1823, closing.
