### ISSUE TITLE
Link to github source for example

### ISSUE THREAD

**Issue by rougier** [scikit-image/scikit-image#1654]
I'm currently trying to get rid of ticks and labels in the gallery examples and I realize that there is no direct link to the github source file.

For example, if I look at `http://scikit-image.org/docs/dev/auto_examples/plot_adapt_rgb.html`, how do I know the relevant file is `https://github.com/scikit-image/scikit-image/blob/master/doc/examples/plot_adapt_rgb.py` (my browser does not display the full url) ?

**Comment by stefanv** [comment]
You mean other than their names being the same?

**Comment by rougier** [comment]
Yes. This is how I find the revelant file in the end. Maybe it's enough if this naming scheme is consistent over all the examples.

**Comment by stefanv** [comment]
I think it should be 100% consistent.

**Comment by stefanv** [comment]
(Also, the download link downloads a .py file with the same base name.)

BTW, hi @rougier :)

**Comment by rougier** [comment]
Hi @stevanv ! BTW, Really great work on the viridis colormap and great talk at Scipy by Nathaniel.
