### ISSUE TITLE
Replace cubehelix colormap with viridis

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1661]
Also useful for normalized images @jni @rougier

**Comment by jwiggins** [comment]
@stefanv: The only mention of cubehelix that I can find is in `skimage.external.tifffile.tifffile` on line 4602. COuld that really be the only place which needs to be changed?

**Comment by jni** [comment]
@stefanv it seems you're forgetting that @blink1073 already did this LOL

**Comment by jni** [comment]
@stefanv #1599 =)

**Comment by jni** [comment]
Actually, @jwiggins, if you're looking for quick fixing, cubehelix is still used in `doc/examples/plot_rag_draw.py`

**Comment by jwiggins** [comment]
Yeah, I can fix that.

**Comment by jwiggins** [comment]
Hmm... Well. I can fix this, but not test it since I don't run the bleeding edge matplotlib

**Comment by kshitij10496** [comment]
Isn't this issue fixed ?
