### ISSUE TITLE
Daisy example faulty output

### ISSUE THREAD

**Issue by rougier** [scikit-image/scikit-image#1665]
If you look at the example in http://scikit-image.org/docs/dev/auto_examples/plot_daisy.html:

![](http://scikit-image.org/docs/dev/_images/plot_daisy_1.png)

it seems some pixel are "missing". When you run the example localy, you don't have such problem but the overall quality of the circles and line is not so good I would say (circles appears very roughly antialiased).

**Comment by jni** [comment]
@rougier I think this is an issue with Matplotlib, which resamples images when displaying. If you save the `descs_img`, do you see the same issue?

**Comment by rougier** [comment]
When I save the whole fig, the circles are ok (but still "badly" drawn).

**Comment by soupault** [comment]
@tcaswell, could you comment on issue, please?

**Comment by soupault** [comment]
@tacaswell, could you comment on issue, please?

**Comment by tacaswell** [comment]
Is there any way to visualize the daisies using circle and line objects?

I think the problem is that `desc_img` is an image full of one pixel wide features which is interacting badly with the aliasing when it is raterized on to the canvas.

On a phone so hard to dig much deeper.

**Comment by soupault** [comment]
Yes, thanks.
I don't know if someone uses `descs_img` besides this example, but we can for sure re-implement it using `matplotlib` primitives.

**Comment by stefanv** [comment]
How about some anti-aliased drawing?  See #1827!

**Comment by soupault** [comment]
Looks better I guess:
![screenshot from 2015-12-14 23-19-18](https://cloud.githubusercontent.com/assets/1315589/11792881/82b8b102-a2b9-11e5-98b1-5c4c62e20711.png)
