### ISSUE TITLE
Travis builds are slow

### ISSUE THREAD

**Issue by jwiggins** [scikit-image/scikit-image#1678]
I noticed this during the EuSciPy sprint last night, but I'm new here so I'd love to hear the opinion of people who've actually worked on this.

So, for illustration, here's a recent Travis run: https://travis-ci.org/scikit-image/scikit-image/builds/77734058
If we look at the Python 2.7 build for that run, we see that it took about 20 minutes. Of that 20 minutes, nearly 7 minutes was consumed by the install step in `.travis.yml`:
```
install:
    - python setup.py build_ext --inplace
    - python setup.py install
```
If you look at the output for each of those commands, the compilation of extension modules appears to be happening in both. This was most recently changed in 095160f1c63327d25cd0f5c98c56f79b869f66cf. @blink1073: Can you comment on why this was needed? I think it might be possible to just run the `install` command.

I've started a `travis-speedups` branch in my fork to experiment with possible solutions.

**Comment by emmanuelle** [comment]
I wonder whether we need ``python setup.py build_ext --inplace`` to build the doc (but I'm not sure about it :-/)

Comment Close and comment

**Comment by blink1073** [comment]
We've had that step all along, I had accidentally removed it in a PR.  Either way, we need to have a compile step in order to test the library, since we do not have compiled extensions in version control.

**Comment by tacaswell** [comment]
setuptools is also clever enough to not re-compile things if not needed, I suspect that the second line is very fast compared to the first.

**Comment by jwiggins** [comment]
@tacaswell: Surprisingly, it's not much faster. I've got a PR (jwiggins/scikit-image#1) open on my repo where I'm trying some thing out. I'll open a PR here if I come to any useful conclusions.

**Comment by jwiggins** [comment]
I don't think `pyamg` is actually being installed when the tests run on Travis

**Comment by emmanuelle** [comment]
@jwiggins I don't think either. ``pyamg`` is only used for one function (``segmentation.random_walker``), and the package has not been ported to Python 3 :-(.

**Comment by jwiggins** [comment]
PR started at #1683

Here are my conclusions and questions:
  * `imread` fell out of the optional package installation in a939eb4ce655b554c7b91ea8b2395566300ba3c4, so I added it back. The Python 2.7 build failed in my PR in a way that might be related. This should be investigated.
  * Breaking the tests up into multiple passes (using multiple `env` entries) will not give a speedup without a significantly faster install. The installation step is slow because it takes a while to build the library but it might be possible to speed things up with `ccache`.
  * Travis runs are particularly slow because the entire test suite is run twice. First with minimal requirements installed, then once more with all optional requirements installed and a modified `matplotlibrc`. It's not trivial to refactor this, but if it's sufficiently painful, then it should at least be considered.
  * Why is a `virtualenv` being created? Travis is already running in a `virtualenv`.
  * The `pyamg` installation was failing when running from my repository, but it doesn't appear to be a problem from the main skimage repo. It's possible that this was a transient error.

**Comment by blink1073** [comment]
- I rebuilt our wheelhouse version of `imread` for Python 2.7, hopefully that clears up the issue.  
- Caching would work if we could detect which extensions if any have changed.
- We purposely test with minimum requirements to make sure the test suite passes with just the min requirements, and then test again with as many optional requirements as possible to make sure we get good test coverage.
- We create a new virtualenv to isolate ourselves from any changes made in the default Travis virtualenv.

**Comment by jwiggins** [comment]
#1699 enables ccache

**Comment by blink1073** [comment]
Looks like we can tell Sphinx to use a global cache directory too, see the `-d` option:

http://sphinx-doc.org/invocation.html

**Comment by blink1073** [comment]
We won this battle @jwiggins.
