### ISSUE TITLE
Round-trip save/load of grayscale float image through PNG format returns inconsistent result

### ISSUE THREAD

**Issue by connellybarnes** [scikit-image/scikit-image#1680]
If we construct a grayscale float array, save it to PNG, and load it back, we get a different result:

    >>> I=numpy.eye(3)
    >>> skimage.io.imsave('I.png', I)
    >>> Ip=skimage.img_as_float(skimage.io.imread('I.png'))
    >>> numpy.sum(numpy.abs(Ip-I))       # This number should be very small!
    2.9999084493610795
    >>> assert numpy.sum(numpy.abs(Ip-I)) < 1e-3
    (Assertion error)

The problem appears to be because `skimage.io.imread()` on a grayscale 16-bit PNG in fact returns a numpy array of `int32` format. The bug disappears if `imread()` casts its output to `uint16` type.

The deeper underlying problem causing this is that PIL returns type `'I'` (32-bit signed integer) when loading a grayscale 16-bit PNG since PIL does not have a mode for 16-bit signed integers.

My proposed workaround for the PIL limitation is to when reading an image simply detect the special case of a "32-bits per channel" PNG (which does not exist according to the PNG standard), and cast this to a 16-bit unsigned array. Specifically, add the following two lines to `skimage/io/_plugins/pil_plugin.py`, function `pil_to_ndarray()`. In unified diff format:

    +++ pil_plugin.py	2015-08-29 12:15:25.000000000 -0400
    @@ -78,6 +78,9 @@
                 i += 1
                 continue
     
    +        if im.format == 'PNG' and im.mode == 'I' and dtype is None:
    +            dtype = 'uint16'
    
             if im.mode == 'P':
                 if grayscale is None:
                     grayscale = _palette_is_grayscale(im)

**Comment by blink1073** [comment]
@connellybarnes, sounds reasonable to me, would you like to submit a PR?
