### ISSUE TITLE
hough_circle radii does not accept scalars/lists

### ISSUE THREAD

**Issue by juliusbierk** [scikit-image/scikit-image#1682]
If I would like to run hough_circle for a known radius, I find it annoying that I have to do `hough_circle(img,np.array([radius])`. Maybe it should also accept Python lists and python scalars?

**Comment by emmanuelle** [comment]
:+1: for accepting scalars and lists

**Comment by emmanuelle** [comment]
I guess that you can use ``np.atleast_1d(np.asarray(radii))``

**Comment by juliusbierk** [comment]
Great! Hadn't seen atleast_1d before. I'll make a PR right away.

**Comment by stefanv** [comment]
Closed by #1684.
