### ISSUE TITLE
Example on the homepage (change `filter` to `filters`).

### ISSUE THREAD

**Issue by h4k1m0u** [scikit-image/scikit-image#1703]
Hello,

On the example appearing on the home page http://scikit-image.org/, first line.
I think it should be be:

``` python
from skimage import data, io, filters
```
(`filters` replace `filter`).

Otherwise, I got this `warning` on `Ubuntu 14`, when importing `filter` (as in the home page now, instead of `filters`):
``` python
>>> from skimage import data, io, filter
/usr/local/lib/python2.7/dist-packages/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
```

**Comment by JDWarner** [comment]
You're correct, we deprecated the filter module due to conflict with a base Python module. This should be changed.

We should do a pass through the entire docs to change all instances to filters.

**Comment by emmanuelle** [comment]
This issue was fixed by https://github.com/scikit-image/scikit-image-web/pull/28, but we need to update the website now...
