### ISSUE TITLE
Building documentation not possible: missing conf.py

### ISSUE THREAD

**Issue by cartisan** [scikit-image/scikit-image#1707]
I wanted to build the doc for offline access on my Windows machine. However that errors with:
```
~: .\make.bat html 
Error: Config directory doesn't contain a conf.py file.

Build finished. The HTML pages are in _build/html.
```

To reproduce:
1. Checkout code from repo
2. `cd .\doc`
3. ` .\make.bat html `
... or any other option than html.

Quick lookup on Google revealed that conf.py should contain settings for sphinx.

**Comment by JDWarner** [comment]
Thanks for the report! We do have `conf.py` and it's set up correctly, however, it lives in the `docs/source` subdirectory. The .bat file needs to point Sphinx at the `source` subdir. I should have a fix momentarily.
