### ISSUE TITLE
Any way to run scikit-image on GPU

### ISSUE THREAD

**Issue by ttback** [scikit-image/scikit-image#1727]
a new user here. I am trying to use scikit-image to restore some old images. Is there a way to leverage GPU for the operation?

**Comment by emmanuelle** [comment]
Hello @ttback, welcome here! No, scikit-image functions do not use GPUs, since they rely on NumPy operations, Python and Cython code. If you can parallelize your workflow, you can use several cores instead: see for example http://scikit-image.org/docs/stable/user_guide/tutorial_parallelization.html

**Comment by baibaidj** [comment]
Is it possible that in the near future scikit-image will support GPU acceleration?  For sematic segmenation using deep learning, image processing remains a crucial part of the workflow. In the study of vertebral body segmentation, I used scikit-image for preprocessing and postpossessing, which is a great help, but is also the most time-consuming part. 5 seconds for model inference but 120 seconds for postprocessing. As GPU becomes cheaper and cheaper, more people can afford GPU. If scikit-image can add GPU acceleration, it will be highly welcomed in CV community.

**Comment by hmaarrfk** [comment]
If you are so inclined, I would look into [`cupy`](https://github.com/cupy/cupy). You could find the algorithms you need to implement on the GPU, and work through the kinks to get them working on the GPU. That is the beauty of open source :D. It helped me to do that for one algorithm.

Keep in mind that not all algorithms can be parallelized. Often smarter thinking beats more raw power. .
