### ISSUE TITLE
Error while importing "transform" from skimage

### ISSUE THREAD

**Issue by ShivaniBhardwaj** [scikit-image/scikit-image#1728]
I am a newbie for skimage. I am trying to use skimage for basic image processing. 
I am getting following error while importing transform : 

![dlib](https://cloud.githubusercontent.com/assets/6955202/10089505/849b2042-62f2-11e5-91d6-a7e0e93a00b7.JPG)

I am using python 2.7
Code:
>> from skimage import transform

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from skimage import transform
  File "C:\Python27\lib\site-packages\skimage\transform\__init__.py", line 1, in <module>
    from ._hough_transform import (hough_ellipse, hough_line,
ImportError: DLL load failed: The specified module could not be found.
>>> 
I tried reinstalling skimage, however it is not working.

**Comment by vighneshbirodkar** [comment]
Hello,  can you tell us how you installed scikit-image  ?

**Comment by ShivaniBhardwaj** [comment]
I downloaded numpy, scipy and scikit-image from Christoph Gohlke’s website. 
and used pip for installation:
pip install scikit_image-0.11.3-cp27-none-win32.whl

**Comment by vighneshbirodkar** [comment]
Could you share the folder structure of this folder from your system ? 
`C:\Python27\lib\site-packages\skimage\transform`
And were there any error messages while doing the pip install ?

**Comment by ShivaniBhardwaj** [comment]
no error message while installation.
you can find the folder structure here:
https://github.com/ShivaniBhardwaj/skimage/tree/master/transform

**Comment by vighneshbirodkar** [comment]
I meant folder structure on your local pc.

**Comment by teknogeek** [comment]
@vighneshbirodkar yes that is his local PC folder uploaded to git it seems

**Comment by teknogeek** [comment]
i am also having this problem, same folder structure here

**Comment by teknogeek** [comment]
@vighneshbirodkar @ShivaniBhardwaj installing [numpy+mkl](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) seemed to fix the error for me

**Comment by emmanuelle** [comment]
@ShivaniBhardwaj did you try the solution recommended by @teknogeek ?
