### ISSUE TITLE
Pyramid Guassian producing static

### ISSUE THREAD

**Issue by gregpinero** [scikit-image/scikit-image#1729]
I posted code and pictures here:
http://stackoverflow.com/questions/32785495/skimage-pyramid-guassian-not-working-as-expected

I'm doing everything like I've seen in examples so I'm thinking it's not a user error?

**Comment by ahojnnes** [comment]
The output of all geoemtric transformation functions in skimage is a double
array. You need to convert back to uint8.

**Comment by ahojnnes** [comment]
@gregpinero Did this solve your problem?

**Comment by stefanv** [comment]
No feedback given.  Closing.
