### ISSUE TITLE
measure fractal dimension

### ISSUE THREAD

**Issue by SalvatoreScaramuzzino** [scikit-image/scikit-image#1730]
recently i implemented a python version of differential box counting as method for fractal dimension estimation for grayscale images.

this is a very common tool for complexity estimation in various fields, in particular in medical imaging.
more informations can be found at 
http://cdn.intechopen.com/pdfs-wm/39360.pdf

if the measure is of interest for skimage community i can integrate it "measure" module

**Comment by stefanv** [comment]
Thank you for kindly offering your code!

We are happy to accept implementations of well-cited papers.  This paper, according to Google, only seems to have been cited six times, though.  Do you have another reference that may be better to look up?

**Comment by pratapvardhan** [comment]
I remeber implementaing it couple of years back (in Matalb though). Differential Box Counting (DBC) was proposed by N. Sarker, B. B. Chaudhuri, *An efficient differential box-counting approach to compute fractal dimension of image*, [IEEE Transaction on Systems, Man, and Cybernetics, 24, 115-120 ], (1994). This is fairly popular paper (Cited over 500 times.)

**Comment by stefanv** [comment]
That sounds reasonable, then.  I'm going to close this ticket for now, and then we can discuss the code on the (forthcoming) pull request.  Thank you!

**Comment by yasoob** [comment]
Hey was there any pull request regarding this issue?

**Comment by SalvatoreScaramuzzino** [comment]
not yet, but i'm going to do it, in a few months. Do you have any particular urgency about this feature?

**Comment by yasoob** [comment]
The project is machine learning for Alzheimer's prediction. Currently I am doing feature extraction from MRI scans. One step involves calculating the fractal dimensions of the filtered image. This upcoming PR would allow me to do it easily without a lot of custom code. :smile:

**Comment by softwaremechanic** [comment]
+1

**Comment by trummelbummel** [comment]
+ 1
