### ISSUE TITLE
peak_local_max Incorrect output type 

### ISSUE THREAD

**Issue by escorciav** [scikit-image/scikit-image#1731]
This [function](http://scikit-image.org/docs/dev/api/skimage.feature.html#peak-local-max) is returning a `list` instead of an `ndarray` if no peaks are detected.

I traced the problem till this [line](https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/peak.py#L122). However, I have to check if there is other case (beyond this line) that produces an incorrect output.

I will work on it this weekend and submit a pull-request or a code snippet here

**Comment by stefanv** [comment]
Thanks, @escorciav!
