### ISSUE TITLE
scikit-image installing on different python version of Mac

### ISSUE THREAD

**Issue by om27** [scikit-image/scikit-image#1735]
My mac has default python 2.7 version. I have installed python 3.5. I installed scikit-image using pip but it was installed on the default python 2.7. How do I install it on python 3.5

**Comment by blink1073** [comment]
Hi @om27, you'll need to use the `pip` that comes with python 3.5, either by adding its directory to the front of your PATH variable or by using `/path/to/my/3.5/pip install scikit-image`.

**Comment by matthew-brett** [comment]
I think `pip3.5` on its own will also work on a default installation.

If you want this to be the default, you could add something like:

```
alias pip=pip3.5
```

to your `$HOME/.bash_profile`.

**Comment by om27** [comment]
Thank you for the quick help. 
But when I use pip3.5, i am getting the following error :+1:

 Command "/usr/local/opt/python3/bin/python3.5 -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-qwodeudw/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iy0nyp60-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-qwodeudw/pillow

**Comment by matthew-brett** [comment]
I think that's because the `Pillow` project hasn't released wheels for Python 3.5 yet.  I believe they are just in the process of doing that.   sckit-image hasn't built one yet either.  I'm afraid you're getting paper cuts from being on the bleeding edge :).  In a week, I guess this will work fine.

**Comment by om27** [comment]
I hope this will be set soon. Thanks a lot for your timely help or else I would have been stuck at this point.

**Comment by wiredfool** [comment]
It's up now. https://pypi.python.org/pypi/Pillow/3.0.0

**Comment by matthew-brett** [comment]
Great - thanks.   I'll try building a wheel for scikit-image now.

**Comment by matthew-brett** [comment]
Done - @om27 - try now?

**Comment by om27** [comment]
Perfectly Installed :) :+1: ! 
Thanks a lot !

**Comment by matthew-brett** [comment]
No problem, glad it worked.
