### ISSUE TITLE
Consider not converting images when using `img_as_float` on a float32 image

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1737]
See e.g. #1627

**Comment by stefanv** [comment]
Yes, `img_as_float` should not convert the range of images that are already floating point.  We may rely on the type being float64 in some Cython code, so we'll probably still have to change the dtype.

**Comment by stefanv** [comment]
Given that the underlying Cython code requires doubles, what do you say?  Should we leave ``img_as_float`` as is?

**Comment by jni** [comment]
@stefanv One word: fused types. =P

**Comment by stefanv** [comment]
That seems like a perfectly reasonable suggestion, although it would require changing *all* Cython functions that expect doubles.

**Comment by taion** [comment]
It would be great if `img_as_float` didn't generally convert float32 to float64. We're seeing that when running something like `warp` on a `float32` image, a significant fraction of the time is spent unnecessarily converting the image into `float64`, which does little to really improve the output quality.

**Comment by jni** [comment]
Pinging this, as I was reminded of it while writing #3052.

**Comment by jni** [comment]
We should have some prioritisation tags I think... Is there a reason we don't have them?

Anyway I would call this high priority.

**Comment by jni** [comment]
Well, the problem is then you end up switching a massive number of `0.14.0optional` tags to `0.15.0optional` tags...

**Comment by soupault** [comment]
@jni This is why we don't use such notation, and all of our current milestones are the `must` ones. :trollface:

**Comment by stefanv** [comment]
Also addressed by #3110.  Also note https://github.com/scikit-image/scikit-image/issues/3111

**Comment by jni** [comment]
Closed by #3110
