### ISSUE TITLE
`img_as_uint` fails with >=32bit integer dtypes.

### ISSUE THREAD

**Issue by anntzer** [scikit-image/scikit-image#1739]
```
In [3]: exposure.equalize_adapthist(np.random.randint(256, size=(32, 32)).astype(np.uint32))
/usr/lib/python3.5/site-packages/skimage/util/dtype.py:111: UserWarning: Possible precision loss when converting from uint32 to uint16
  "%s to %s" % (dtypeobj_in, dtypeobj))
Out[3]: 
array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [4]: exposure.equalize_adapthist(np.random.randint(256, size=(32, 32)))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-253568f6b83d> in <module>()
----> 1 exposure.equalize_adapthist(np.random.randint(256, size=(32, 32)))

/usr/lib/python3.5/site-packages/skimage/color/adapt_rgb.py in image_filter_adapted(image, *args, **kwargs)
     38                 return apply_to_rgb(image_filter, image, *args, **kwargs)
     39             else:
---> 40                 return image_filter(image, *args, **kwargs)
     41         return image_filter_adapted
     42     return decorator

/usr/lib/python3.5/site-packages/skimage/exposure/_adapthist.py in equalize_adapthist(image, ntiles_x, ntiles_y, clip_limit, nbins)
     75     .. [2] https://en.wikipedia.org/wiki/CLAHE#CLAHE
     76     """
---> 77     image = img_as_uint(image)
     78     image = rescale_intensity(image, out_range=(0, NR_OF_GREY - 1))
     79     out = _clahe(image, ntiles_x, ntiles_y, clip_limit * nbins, nbins)

/usr/lib/python3.5/site-packages/skimage/util/dtype.py in img_as_uint(image, force_copy)
    313 
    314     """
--> 315     return convert(image, np.uint16, force_copy)
    316 
    317 

/usr/lib/python3.5/site-packages/skimage/util/dtype.py in convert(image, dtype, force_copy, uniform)
    101 
    102     if not (dtype_in in _supported_types and dtype in _supported_types):
--> 103         raise ValueError("can not convert %s to %s." % (dtypeobj_in, dtypeobj))
    104 
    105     def sign_loss():

ValueError: can not convert int64 to uint16.
```
Arch Linux, Python 3.5.0, numpy 1.9.3, skimage 0.11.3

**Comment by blink1073** [comment]
Hi @anntzer, I updated your title to highlight the root cause, thanks for reporting.  My thought is that we should allow this conversion and warn, what do you think, @jni?

**Comment by anntzer** [comment]
Actually I don't see why you need to convert to uint8 first; in fact if the conversion is linear (I guess it is?) then you may well be destroying at that stage some of the contrast that you were hoping to enhance by CLAHE.
(Here I used `randint(256)` but that was probably a bad example, histogram equalization should work just as well for 16+bits images.)

**Comment by blink1073** [comment]
The reference implementation for CLAHE uses 12-bit resolution.  I'd argue that any more than that is just playing with noise.

**Comment by anntzer** [comment]
Then adapthist could support at least 16bit images? (as there's no 12bit in numpy and 8bit is certainly a bit short)

**Comment by blink1073** [comment]
Right, `img_as_uint` converts to a 16-bit image.

**Comment by anntzer** [comment]
Fair enough.
Regardless of the "usefulness" of keeping more than 12 bits while doing contrast enhancement (which I understand well), is there a real computational cost to supporting such images?

**Comment by blink1073** [comment]
I'd say supporting them is fine, as an input, but the calculations should still be done as-is, on a 16bit image, since is already tested and known.  We take the stance that the data type of the image is not guaranteed to be the same after an image transform in general.

**Comment by jni** [comment]
@blink1073 I don't understand why we are arguing about 12 bits but `NR_OF_GREY` in `_adapthist.py` is `2**14`?

Either way, yes, we should certainly support any type of input image. This again relates to #1234.

**Comment by blink1073** [comment]
Ha, you're right @jni, I was mis-remembering.

**Comment by jni** [comment]
@stefanv Just had a look at the code. In this case, we should not rescale, imho, but the whole `convert` machinery revolves around rescaling. I don't know how to fix this without extreme special-casing... Suggestions welcome!

**Comment by stefanv** [comment]
Raise a warning and assume 64-bit int is actually a 16-bit image?

**Comment by blink1073** [comment]
Seems reasonable to me to do what we do in `imsave`, and check the max value when downcasting, and issue a warning if we assume it should not be rescaled.
