### ISSUE TITLE
Support for Older Python Versions?

### ISSUE THREAD

**Issue by blink1073** [scikit-image/scikit-image#1740]
Dask is not tested against Py32: https://github.com/blaze/dask/blob/master/.travis.yml.
I am getting Dask-related failures in #1738 on Py32.  https://travis-ci.org/scikit-image/scikit-image/jobs/83461034#L3074.
We have Dask as a required dependency.  We have already seen this problem with networkx dropping support for Py26.  I think we need to make both of these libraries optional, or drop support for those versions of Python ourselves.

**Comment by blink1073** [comment]
We have a looming problem with Matplotlib as well, which will be dropping support for Py26 and Py32 soon: https://mail.python.org/pipermail/matplotlib-devel/2015-September/000068.html.

**Comment by blink1073** [comment]
Ah, actually, Matplotlib already dropped 3.2 and will be dropping 3.3.

**Comment by blink1073** [comment]
The other option is to pin versions known to work with these, as we have already been doing in https://github.com/scikit-image/scikit-image/blob/master/tools/travis_before_install.sh#L37

**Comment by blink1073** [comment]
Fyi @mrocklin, it looks like Dask 0.7.1 was the last version to work properly with Python 3.2.
After that, we get this error:

```
Traceback (most recent call last):
  File "/home/travis/venv/lib/python3.2/site-packages/dask/base.py", line 175, in normalize_array
    data = md5(x.view('i1').data).hexdigest()
BufferError: Buffer must be single dimension
```

**Comment by tacaswell** [comment]
I (obviously) advocate that skimage drop at least 2.6.  

I am still looking for an argument _to_ keep supporting 2.6 that does not boil down to maintaining the status quo.

**Comment by mrocklin** [comment]
Fixing this particular problem within dask is easy.  (see https://github.com/blaze/dask/pull/768)

However given the slight usage of dask within scikit-image it still might make sense to move dask to an optional dependency anyway (unless you all plan to use it more heavily in the future.)

Dask does support Python 2.6 though, (see https://github.com/blaze/dask/blob/master/.travis.yml#L4).  Based on usage numbers it looks like a nontrivial set of people still use 2.6 (sadly.)  I'm less convinced that Python 3.2 is commonly used though.  Someone would have had to be an early adopter (hop on to 3.2) and then very quickly shift to not adopting anything. Dask is likely to drop 3.3 support in the near future as well.

**Comment by blink1073** [comment]
Thanks @mrocklin, sorry, I glanced past the 2.6 build in your matrix.

**Comment by JDWarner** [comment]
I do think we need broader support for Dask in scikit-image. In the last month I've run into several cases where scikit-image tools were impossible to use on large composite images from optical or confocal microscopes. These were on the order of 100 megapixels. Even under 64-bit Python with plenty of RAM I got memory errors upon load when the NumPy method `.asarray(np.float64)` was called.

Consider that prosumer cameras (Canon 5DS) are now over 50 megapixels, my 16 megapixel DSLR can nearly choke scikit-image algorithms, yet the GIMP handles these without issue on the same hardware.

**Comment by blink1073** [comment]
So, do we drop 3.2 support in favor of 3.5?  I think that is a practical way forward until Scipy stops supporting 2.6.

**Comment by JDWarner** [comment]
Agreed that 3.2 can almost certainly be dropped without issue. I do know of several systems that yet run Python 2.6, doing production work on a LTS release of RHEL, which were set up before Canopy or Anaconda existed. Such production systems are usually quite reluctant to upgrade, or to transition to newer better solutions, which is why I have advocated to maintain 2.6 support.

**Comment by blink1073** [comment]
Yeah, we should probably have a special section in the documentation for Python 2.6 users, especially once Matplotlib drops support.

**Comment by tacaswell** [comment]
Those systems which are still on 2.6 which are reluctant to update are presumably _also_ reluctant to update the rest of their libraries.   The versions that currently work will continue to work.

At some point, if you do not want to update your underlying python, you have to accept that you will not get new features.  Users unwilling to upgrade can not keep imposing the constraints and costs of supporting a deprecated version of python on everyone else.

Dropping this link yet again: http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html  One of the things that Nick says is to stop using RHEL as an argument as there are paths to get modern python on old RHEL using RHEL tools.

**Comment by stefanv** [comment]
Agreed, let's drop 3.2.  If we can keep 2.6 support with minimal effort, why not.  But it's not a high priority.

**Comment by blink1073** [comment]
Great, I updated #1738, closing.
