### ISSUE TITLE
Upgrading included tifffile

### ISSUE THREAD

**Issue by jakirkham** [scikit-image/scikit-image#1742]
Should the `tifffile` included be bumped up to latest version of `tifffile`? Currently 0.7.0 at the time of this posting.

**Comment by blink1073** [comment]
Yep, see #1743.

**Comment by jakirkham** [comment]
Cool, thanks @blink1073.

**Comment by blink1073** [comment]
It looks like we're already using it.

**Comment by jakirkham** [comment]
Sorry, I just assumed from the last commit message in the directory ( https://github.com/scikit-image/scikit-image/tree/master/skimage/external ) that it is still `0.6.2`.
