### ISSUE TITLE
Bug in Template Matching 

### ISSUE THREAD

**Issue by theasder** [scikit-image/scikit-image#1755]
I have been testing template matching function and have found a following bug: 
![screen shot 2015-10-23 at 1 02 06 pm](https://cloud.githubusercontent.com/assets/3380261/10689799/705eadec-7986-11e5-9368-f7886bf5865c.png)
Very interesting to find out why did it happen.

**Comment by MartinSavc** [comment]
The code and original files would be useful.

**Comment by stefanv** [comment]
No feedback given--closing.
