### ISSUE TITLE
Incorrect indentation leads to lists wrapped in blockquote

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1774]
These lists should not be indented. Because of the leading whitespace Sphinx wraps them in a blockquote.

http://scikit-image.org/docs/dev/auto_examples/plot_shapes.html (also choose better `figsize` to minimize whitespace)
http://scikit-image.org/docs/dev/auto_examples/plot_rank_mean.html
http://scikit-image.org/docs/dev/auto_examples/plot_radon_transform.html
http://scikit-image.org/docs/dev/auto_examples/plot_hog.html

For reference, this is how a list should be rendered sans blockquote. It is the only correctly rendered list in our example gallery.
http://scikit-image.org/docs/dev/auto_examples/plot_medial_transform.html

**Comment by soupault** [comment]
Fixed with #1806 .
