### ISSUE TITLE
tifffile methods missing?

### ISSUE THREAD

**Issue by apiszcz** [scikit-image/scikit-image#1776]
I do not see TiffWriter support? Is there another import required?
I am trying to understand if this is possible?
tifout=skitf.TiffWriter(tifoutpath,bigtiff=True)

from skimage.external import tifffile as skitf
(Pdb) dir(skitf)
['TiffFile', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'imread', 'imsave']

**Comment by blink1073** [comment]
Hi @apiszcz, here's what I get:

```python
In [1]: from skimage.external import tifffile as skitf

In [2]: dir(skitf)
Out[2]:
['TiffFile',
 'TiffSequence',
 'TiffWriter',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_tifffile',
 'imread',
 'imsave',
 'imshow',
 'tifffile']
In [2]: skitf.TiffWriter
Out[2]: skimage.external.tifffile.tifffile.TiffWriter
```

It could be that it is only available in the dev version.  We are releasing a new version (hopefully) within the next couple of weeks.
