### ISSUE TITLE
Add complexity evalutaion to docstrings

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#1793]
Hi!

I dare to say that large part of users (inc. myself) typically use `skimage` for fast prototyping of image processing pipelines. Do you think if it might be a good idea to add an estimation of complexity metrics to algorithms' docstrings?

This way, it also might be easier both for maintainers and community to identify "outdated" algorithms implementations.

**Comment by stefanv** [comment]
Yes, I see no reason why we cannot do that.  If the complexity is known, simply add it under the "Notes" section of the specified algorithm.  That said, I don't know who will do the work of retroactively studying all the algorithms to figure this out, so please feel free to file PRs.

**Comment by soupault** [comment]
@stefanv OK, thanks!
