### ISSUE TITLE
Problem still remaining with skimage/_io readimage with (3,N,M) tiff images

### ISSUE THREAD

**Issue by patquem** [scikit-image/scikit-image#1796]
Hello,

It's my first topic in this site (so, be indulgent with me, please, if I don't do the things in the right way).
My issue is relative to the one reported in may named :
     Fix skimage.io.imread returns incorrect dimensions #1498
I realize the modifications proposed in this issue, but in my case, the dimension stays incorrect (when as_grey = True).
To fix the problem I have done the following changes in imread() :
        if img.shape[-1] not in (3, 4) and img.shape[-3] in (3, 4):
            #img = np.swapaxes(img, -1, -3)
            #img = np.swapaxes(img, -1, -3)
            tmp = np.ndarray((img.shape[1],img.shape[2],img.shape[0]))
            tmp[:,:,0] = img[0,:,:]
            tmp[:,:,1] = img[1,:,:]
            tmp[:,:,2] = img[2,:,:]
            img = tmp
It is not really elegant, but it works in my case.

yours,
Patrick

**Comment by JDWarner** [comment]
@patquem are you running the development version (0.12dev), or the latest release (0.11.3)? You can check this with `import skimage; skimage.__version__`.

Those fixes are only in the development version at present, but we anticipate releasing 0.12 soon.

**Comment by patquem** [comment]
I work with version = '0.11.3'
I have just reported the changes I read in issued  #1498 in my local version (What I have observed is np.swapaxes doesn't fix the problem .. for me :)

**Comment by patquem** [comment]
Hello,
In fact, when I have tried to fix the problem, I have pick up the modifications in :
https://github.com/scikit-image/scikit-image/commit/3c8bf02fa5a9749f5de1bc4bbd6b2e2abb7d1a25
which specified the (wrong) changes : 
         img = np.swapaxes(img, -1, -3)
         img = np.swapaxes(img, -1, -2)
Since may, second line have been changed in : 
         img = np.swapaxes(img, -1, -3)
         img = np.swapaxes(img, -2, -3)
and it works correctly.

**Comment by emmanuelle** [comment]
@patquem  can we consider that your problem is solved and close the issue?

**Comment by patquem** [comment]
Yes. You can close the issue.
Thanks.
