### ISSUE TITLE
Deprecate Python 2.6 after release of 0.12

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1807]

**Comment by jni** [comment]
:+1:

**Comment by JDWarner** [comment]
It's probably time.

**Comment by emmanuelle** [comment]
So, if I understand well, 0.12 will still support Python 2.6 but 0.13 won't? Is that what you suggest? 

Where should we warn users still using Python 2.6 that the next release won't support their version of Python any more? Obvisouly in DEPENDS.txt, anywhere else? Should we issue a warning when users import skimage ?

**Comment by stefanv** [comment]
Yes, that's right.  Since even numpy will probably move to 2.7, I think we've waited long enough.  A warning on Python 2.6 is a good idea.
