### ISSUE TITLE
regionprops: document each property for introspection purposes

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1809]

**Comment by ahojnnes** [comment]
+1! Maybe we can automatically populate the doc string of the regionprops function from the members of the private _RegionProps class.

**Comment by stefanv** [comment]
That would be great!

**Comment by emmanuelle** [comment]
@stefanv I don't understand the suggestion. Do you mean that some properties are not mentioned in the doctring of ``measure.regionprops``?

**Comment by JDWarner** [comment]
I think the idea is to document this once, in one place, and have other instances pulled from there instead of needing to do multiple changes in multiple places (which inevitably results in inconsistencies)

**Comment by emmanuelle** [comment]
thanks, makes sense
