### ISSUE TITLE
Figure of edge modes example is too small

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1816]
in http://scikit-image.org/docs/dev/auto_examples/plot_edge_modes.html, all 5 subplots are on a single row, resulting in tiny windows. A 2-line plot would be better.

**Comment by mronian** [comment]
I'd like to work on this. Can I take this one?

**Comment by soupault** [comment]
@mronian Don't ask, go for it! :)

**Comment by emmanuelle** [comment]
thanks @mronian !
