### ISSUE TITLE
"plot holes and peaks" gallery example displays empty subplots

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1822]
In http://scikit-image.org/docs/dev/auto_examples/plot_holes_and_peaks.html, a figure with 4 subplots are created. Since each subplot is created one at a time, the figure is showed several times, between blocks of text. In the html page, this results in several images with empty subplots, including the thumbnail displayed in the gallery (which is the first one of them). 

I was wondering whether it wouldn't be better to have a single figure with all subplots that are plotted.

**Comment by soupault** [comment]
I agree. I think we should discuss on template for gallery articles and rework all existing entries in accordance to it.

    [Short description]
    [Images]
    [Code with _plenty_ of comments]
    [Theory with references]

seems reasonable to me.

**Comment by tonysyu** [comment]
@emmanuelle: The original example just had four individual plots, but this layout was altered in https://github.com/scikit-image/scikit-image/pull/1704.

**Comment by soupault** [comment]
@emmanuelle may I ask for your opinion on this? I personally like the current implementation. One thing I'd change is to hide 2nd row (`axes[1, [0, 1]]`) for the first two plots.

**Comment by sciunto** [comment]
This is fixed: http://scikit-image.org/docs/dev/auto_examples/features_detection/plot_holes_and_peaks.html
