### ISSUE TITLE
``apply_parallel`` slower than (what I) expected

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1836]
I'm not sure whether this problem qualifies as an issue, but I've been playing with ``util.apply_parallel`` (I badly need this kind of feature for large images), and it turns out that the result is slower than what I expected. Here is a little script that I tried, I just would like to know if other people get the same orders of magnitude as I do, or if there is something wrong with my installation.

```
from skimage import util, filters
import numpy as np
from time import time

l = 5000
im = np.random.random((l, l))

t1 = time()
im_gaussian = filters.gaussian(im, 2)
t2 = time()
print('Gaussian filter computed in %f s' %(t2 - t1))

def wrapped(array):
    return filters.gaussian(array, 2)

t3 = time()
res = util.apply_parallel(wrapped, im, chunks=100)
t4 = time()
print('Gaussian filter computed in %f s with apply_parallel' %(t4 - t3))
```

the result is 
```
In [2]: %run test_dask.py
Gaussian filter computed in 0.857147 s
Gaussian filter computed in 12.149871 s with apply_parallel
```

Therefore, apply_parallel turns out to be more than 10x slower. I run the example on an Ubuntu laptop with 4 cores (as confirmed by multiprocessing.cpu_count()), but I had the impression (using top) that only one core was used. However, even on one core, I did not expect such a large overhead coming from apply_parallel. Am I doing something wrong? Obviously, the fact that there are no examples in the docstring and no section in the user guide does not help. I could contribute to improving the documentation, but first I need to understand what's going on :-).

I'm running scikit-image master, and I installed dask[array] (dask version 0.7.0) using pip install (I was a bit annoyed that a different numpy was installed together with dask...).

**Comment by soupault** [comment]
I have the same behaviour.
I've checked also

    res = util.apply_parallel(wrapped, im, chunks=5000)

and it works 2 times slower than un`dask`ed version.

**Comment by emmanuelle** [comment]
I guess the example was not chosen well enough since the computation is so fast that parallelization is not worth doing. I gave it a try with a slower function (``restoration.denoise_tv_chambolle``) and I could gain a factor of 2 with ``apply_parallel`` (with my 4 processors). I also compared with ``joblib.Parallel`` (in threading mode) and the time taken by ``util.apply_parallel`` and ``joblib.Parallel`` were very close (with joblib often slightly faster).

**Comment by emmanuelle** [comment]
I think it's safe to close this issue, I'll just leave it open for a couple of days in case someone wishes to add something.

**Comment by JDWarner** [comment]
Generally speaking, if you have enough RAM to hold the image I find `apply_parallel` best used with the number of chunks equal to your number of physical processor cores. Trying to break things up further may well incur a lot of additional overhead. For images too large to fit into RAM, I again usually try to break them up into a number of chunks which each can fit.

Which seems to be consistent with your experience, @emmanuelle.

**Comment by emmanuelle** [comment]
@JDWarner thanks for sharing your experience. Therefore the default behaviour of ``apply_parallel`` (with ``chunks=None``) is quite good.
