### ISSUE TITLE
Make PyWavelets a required dependency

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1838]
Several recent PRs use PyWavelets to support advanced algorithms (#1833, #1837, many additional possibilities).

Rather than attempt to patch in optional support and manage inherent the CI testing issues, we should add PyWavelets as a required dependency for scikit-image.

A reasonable target for this is 0.13.

**Comment by JDWarner** [comment]
Dramatic performance gains will be realized in PyWavelets 0.4.0; ideally we would depend on 0.4.0+.

**Comment by sciunto** [comment]
@scikit-image/core We probably need to take a decision on this.

**Comment by JDWarner** [comment]
Closed and implemented by #2190
