### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1854]

**Comment by tacaswell** [comment]
:+1:   

Over at mpl we have gotten zero complaints about doing this.  The only 2.6 related issues have been someone fixing a few places where 2.6 support was broken (and _had_ been broken in 1.4.3 but were not covered in tests).   It was noted that 1.5 (which does not 'officially' support 2.6) has fewer 2.6 specific bugs than 1.4.3 (which does support 2.6).

**Comment by JDWarner** [comment]
:+1: 
I've been the historical holdout for 2.6 support, but since the last time we discussed this I no longer see the need.

**Comment by soupault** [comment]
Closed via #2033 .
