### ISSUE TITLE
Removal of 'lena' image

### ISSUE THREAD

**Issue by sergiopasra** [scikit-image/scikit-image#1855]
The lena image has been removed from scipy and matplotlib due to its copyright

* https://github.com/matplotlib/matplotlib/issues/4927
* https://github.com/scipy/scipy/pull/5162

Debian considers the image non-free
* https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html

Fedora thinks the same
* https://bugzilla.redhat.com/show_bug.cgi?id=1295193

It seems that this image has been removed from examples and tests
* https://github.com/scikit-image/scikit-image/pull/1126

But it is still in the distribution. I suggest to go the scipy way and deprecate the data.lena() function but raise a RuntimeError

**Comment by stefanv** [comment]
Agreed.  Would you please make a pull request?  We are finalizing the 0.12 release and this can still get in on time.

**Comment by sergiopasra** [comment]
@stefanv I can. Unfortunately there are several tests that depend on that image and I don't have the knowledge to rewrite them. I can only remove them:

In skimage/feature/tests/test_brief.py
* test_normal_mode
* test_uniform_mode

In skimage/feature/tests/test_corner.py
* test_corner_orientations_lena

In skimage/feature/tests/test_hog.py
* test_histogram_of_oriented_gradients_output_correctness

In skimage/feature/tests/test_match.py
* test_binary_descriptors_lena_rotation_crosscheck_false
* test_binary_descriptors_lena_rotation_crosscheck_true

In skimage/feature/tests/test_match.py
* all tests

In skimage/feature/tests/test_match.py
* test_otsu_lena_image

In skimage/morphology/tests/test_grey.py
* All tests in class TestMorphology

**Comment by stefanv** [comment]
Those tests will unfortunately need to be rewritten. If you could file an
issue for each group of tests, that would be very helpful. I will assign
the issues to milestone 0.13, then we can complete the deprication in time.
Also, you can continue to add a deprecated warning to the lena function--it
will only finally be removed in 0.14, as per our deprication policy.

**Comment by sergiopasra** [comment]
@stefanv I have created issues and a PR (#1866)

**Comment by stefanv** [comment]
Perfect, thank you very much Sergio.

**Comment by soupault** [comment]
It's all done. Closing. :fireworks:

**Comment by BarnabasSzabolcs** [comment]
What is the copyright-free standard alternative for Lena?

**Comment by jni** [comment]
We use data.astronaut() in most places where we used to use Lena.
