### ISSUE TITLE
Tests in skimage/feature/tests/test_hog.py use lena

### ISSUE THREAD

**Issue by sergiopasra** [scikit-image/scikit-image#1861]
To remove the lena image (#1855) some tests have to be rewritten to use a different image.
The following tests in ``skimage/feature/tests/test_hog.py`` use lena

* test_histogram_of_oriented_gradients_output_correctness

**Comment by ivoflipse** [comment]
I think this test just verifies that the output is still similar, so we don't get regressions like we had after the last PR for HOG. So fixing this should simply be a matter of running the code on another image and storing the result.

**Comment by stefanv** [comment]
Thanks, Ivo, that's helpful.

/cc OrkoHunter

**Comment by OrkoHunter** [comment]
This can be closed now. Fixed in #1877.

**Comment by JDWarner** [comment]
Closed by #1877
