### ISSUE TITLE
Bug in scipy.ndimage.affine_transform - what should we do?

### ISSUE THREAD

**Issue by matthew-brett** [scikit-image/scikit-image#1873]
There's a discussion going on over here : https://github.com/scipy/scipy/issues/1547 - about a nasty bug in `scipy.ndimage.affine_transform`, where the result of `affine_transform` depends on how you specified the transformation matrix (as vector to be interpreted as diagonal, or full matrix).

We now have to decide whether to just fix this, or wait and warn, or not fix - see : https://github.com/scipy/scipy/issues/1547#issuecomment-171029805

Do y'all have any views?

**Comment by JDWarner** [comment]
Thanks for the note, @matthew-brett - I chimed in over at the original PR.

Basically, since we can detect the previously faulty case, I would lean toward fixing it immediately and raising an informative note to users which pass a vector to the function.

**Comment by soupault** [comment]
The original issue in `scipy` has been fixed. Closing.
