### ISSUE TITLE
HOG normalise doesn't work on images with negative values

### ISSUE THREAD

**Issue by ivoflipse** [scikit-image/scikit-image#1889]
I'm working with (medical) DICOM images, which can have negative values. When I use HOG to calculate a feature vector for a given patch with normalise turned on, I get a feature vector that contains NaN and that makes scikit-learn unhappy.

The problem seems to be due to the np.sqrt(image) step, since the other normalization part adds a small epsilon to prevent divide by zero, so that's unlikely to be the culprit. 

Is there a better way to perform the normalization if the regular assumptions don't hold? Or should I simply apply some sort of offset, since I'm only interested in gradients anyway. In the latter case, it would be helpful if the function did that for me, since I won't be the first to stumble over this.

**Comment by JDWarner** [comment]
Looking through the HOG function, it seems like there should be inherent normalization so long as the kwarg `normalise` is set to the default of `False`. Do you set `normalise=True`? 

This is a badly named kwarg, because it applies a power law transform rather than any true normalization of the input data.

**Comment by ivoflipse** [comment]
Yes I'm setting normalise to True, but I've used the same code on other medical images with satisfactory results (but obviously without negative values), so while it might not be necessary, I kept it turned on.

Even if it's a badly named kwarg, does that mean we should be offering actual normalization as an alternative?

**Comment by JDWarner** [comment]
@ivoflipse apologies. This is a poorly named, unintuitive kwarg which we should fix. The idea is that applying a log or power transform will make subtle variations more apparent in the final result, but `normalise` was an unfortunate API choice.

In the meantime, as a workaround you could simply make your images exclusively positive with an offset before calling this. As it's based on gradients you won't get into trouble; just subtract the minimum value of the input array from the array in the call.

**Comment by ivoflipse** [comment]
Fair enough! I guess I can close this issue, since your response and PR will take care of the rest
