### ISSUE TITLE
random walker preconditioner

### ISSUE THREAD

**Issue by johnwog** [scikit-image/scikit-image#1890]
Hi 

I am using the random_walker filter.
If I use the 'bf' solver it works fine 
However on exactly the same dataset if i switch to 'cg_mg' solver i get the following error

X = _clean_labels_ar(X + 1, labels).reshape(dims)

UnboundLocalError: local variable 'X' referenced before assignment

Any hints on what could be the cause?
It is exactly the same image in both cases and it works for one but not for the other.

It's like some variable is not defined within the solver or something...

**Comment by JDWarner** [comment]
`X` is the output of the linear system and should be assigned before [this point](https://github.com/scikit-image/scikit-image/blob/master/skimage/segmentation/random_walker_segmentation.py#L464) which is the error you're seeing. 

It sounds like you're interpreting the error correctly, but the only code path I can see where `X` would not be defined there is if the mode flag was set to something other than `'bf'`, `'cg'`, or `'cg_mg'`. In this case the linear system is not solved at all, and `X` would not be assigned. Can you double check that your call includes the exact kwarg `mode='cg_mg'`?

**Comment by stefanv** [comment]
I cannot replicate this problem with the latest Git version.
​

**Comment by johnwog** [comment]
@JDWarner 
I did double check

@stefanv 
i did a
condo update -all
seems to be working now

what is really strange for me is that bf mode is faster than cg_mg in a 2016x2016 image...

**Comment by JDWarner** [comment]
@johnwog 'cg_mg' should be faster, but you must have pyamg installed to use it. Check to see if you have pyamg installed. If not, when 'cg_mg' is selected it falls back to 'cg' which uses a SciPy solver. The 'cg' solver is more memory-efficient but not a great deal faster than brute force.

**Comment by johnwog** [comment]
i run the code again after conda updates 
bf mode: 227.448886871
cg_mg mode: 1113.91149902
pyamg is installed in my machine.
I am using Sierra OS.
Any ideas what can be causing this issue?

**Comment by stefanv** [comment]
If you have a minimal and runnable example, I can benchmark on my machines.
