### ISSUE TITLE
HOG kwarg 'normalise' does not normalize data, replace it

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1894]
When `normalise=True`, HOG operates on the square root of the raw input data. See [this line](https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/_hog.py#L70).

This is a problem because `np.sqrt` is not a normalization. It is a transform of the data. The data is not scaled or guaranteed to have a particular range after it is applied; it's just a square root. What's more, the square root is not defined for all input data.

As a result, users will apply this kwarg thinking it will normalize their data when in fact it may be creating problems (see #1889).

Generally, kwargs should have intuitive names. This one is bad enough I think it should be loudly deprecated in advance of 0.12. 

An acceptable resolution would include:

* Replace `normalise` with something like `transform_sqrt`.
* If this code path is used, check the minimum value of the input array. If it is negative, warn the user their result will have NaNs.

**Comment by JDWarner** [comment]
Alternatively, we could keep `normalise` but subtract the minimum value of the input array from said array prior to the sqrt call (potentially only if the minimum value is negative).

**Comment by Korijn** [comment]
You could consider moving the transform to a separate function (although that would make it a really silly piece of code, as its only calling `np.sqrt`), as it's more of a preprocessing step than a feature of the HOG algorithm. I'd actually vote for just removing the parameter.

**Comment by OrkoHunter** [comment]
@JDWarner I've created #1899 in favor of renaming the kwarg. We can work on a good normalisation method, afterwards.

**Comment by JDWarner** [comment]
Closing in favor of #1899, continue discussion there.
