### ISSUE TITLE
VisibleDeprecationWarning: boolean index did not match indexed array along dimension

### ISSUE THREAD

**Issue by jstaker7** [scikit-image/scikit-image#1896]
This warning comes up when using equalize_adapthist (CLAHE).

    from skimage import exposure
    from skimage import data
    
    img = data.coins()
    eq = exposure.equalize_adapthist(img)

Example output:
/python2.7/site-packages/skimage/exposure/_adapthist.py:262: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 256 but corresponding boolean dimension is 16
  hist[under] += 1
/python2.7/site-packages/skimage/exposure/_adapthist.py:263: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 256 but corresponding boolean dimension is 16
  n_excess -= hist[under].size

**Comment by OrkoHunter** [comment]
Hey @jstaker7, I am unable to reproduce it.

```python
In [1]: from skimage import exposure

In [2]: from skimage import data

In [3]: img = data.coins()

In [4]: eq = exposure.equalize_adapthist(img)
/home/hunter/workspace/scikit-image/skimage/exposure/_adapthist.py:82: skimage_deprecation: 
`ntiles_*` have been deprecated in favor of `kernel_size`.  The `ntiles_*` keyword 
arguments will be removed in v0.14
  'will be removed in v0.14', skimage_deprecation)
```

Which version of `skimage` are you using? Check it with 

```python
>>> import skimage
>>> print(skimage.__version__)
0.12dev
```

**Comment by jstaker7** [comment]
This is under 0.11.3, which appears to be the most recent pip-installable version. I'll wait for the next update, although the output still seems to be working. From your comment it looks like there are other deprecation issues with CLAHE? Is this how I should continue to call this function, or is it getting replaced with an alternative?

**Comment by blink1073** [comment]
Hi @jstaker7, the way you're calling it (with no keyword arguments passed), will work just fine.  The warning you're seeing is actually a bug that we've since corrected.  The updated docs for the function in the coming version (with the new keyword arguments) are here:  http://scikit-image.org/docs/stable/api/skimage.exposure.html#equalize-adapthist

**Comment by jstaker7** [comment]
Excellent. Thanks!
