### ISSUE TITLE
skimage.measure.regionprops area seems to be different data type from documented 

### ISSUE THREAD

**Issue by r-atwood** [scikit-image/scikit-image#1906]
Tried in v 10 and now v 11

The documenation ( and common sense) shows that the area in pixels should be integer. 
But the program gets a float64 value. 

area : int
    Number of pixels of region.

 95 blobprops=skimage.measure.regionprops(labels,intensity_image=flat,cache=True)
 96
 97 for blob in range(nblobs-1):
 98    thisblob=blobprops[blob]
 99    print blob,rmap[blob],"label=",thisblob.label,"area=",thisblob.area,thisblob.max_intensity,thisblob.mean_intensity,thisblob.min_intensity
100    print thisblob.area.dtype

Example output: 

181 181 label= 182 area= 1.0 43132 43132.0 43132
float64

**Comment by jni** [comment]
@r-atwood this is actually fixed in the current master, where it returns a numpy.int64. Would you still consider that a bug? (vs a Python int)

**Comment by soupault** [comment]
@jni Should the issue be closed?

**Comment by jni** [comment]
@soupault I think so. Thanks for the triaging. =) @r-atwood Feel free to re-open if you think this should be replaced by a Python int. (Although I suspect that such a change would require a lot of discussion.)
