### ISSUE TITLE
deltaE_cmc can return NaN for valid input values

### ISSUE THREAD

**Issue by orlp** [scikit-image/scikit-image#1908]
Simple to reproduce:

```
import numpy as np
from skimage import color

c = np.array([0., 1.59607713, 0.87755709])
print(color.deltaE_cmc(c, c))
```

**Comment by soupault** [comment]
I suppose the docstrings need some improvement also.

**Comment by arokem** [comment]
This is because for values that should be equal to 0, `get_dH2` can return very small, but negative numbers, due to floating point error. I have an idea, PR to follow.

**Comment by arokem** [comment]
I'll take a look at the docstring as well, while I'm at it.

**Comment by arokem** [comment]
Sorry @soupault : what's wrong with the docstring?

**Comment by soupault** [comment]
@arokem I couldn't find any `skimage` conventions on color representation, so I though it would be helpful to specify valid intervals for input arguments.
