### ISSUE TITLE
Refactor `warn` to use `stacklevel=2`

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1910]
Probably refactor all instances of `warn` to instead use ``skimage._shared.warn`` and then implement it to always use `stacklevel=2`.

Also see http://permalink.gmane.org/gmane.comp.python.numeric.general/62455

**Comment by blink1073** [comment]
Seems reasonable to me.

**Comment by JDWarner** [comment]
Love this approach; the double line in warnings always seems messy.
