### ISSUE TITLE
restoration.richardson-lucy NDimensional arrays

### ISSUE THREAD

**Issue by simone-codeluppi** [scikit-image/scikit-image#1911]
Hi  
I have been trying to deconvolve a 3d image using the `restoration.richardson_lucy` restoration method. The image is a `numpy.ndarray` of `(26, 2000, 2000)` and I tested psf of different size `(12, 100, 100)`,`(26, 100, 100)`,`(26, 2000, 2000)`. All the pfs tested are smaller or equal than the image.  
When I run the `restoration.richardson_lucy(Img,psf,iterations=20)` I get the following error: 

    `-> 373 relative_blur = image / convolve2d(im_deconv, psf, 'same')    
    374 im_deconv *= convolve2d(relative_blur, psf_mirror, 'same')    
    -> 701 out = sigtools._convolve2d(in1, in2, 1, val, bval, fillvalue)
    ValueError: object too deep for desired array`

The function help report that it accept Ndimensional arrays but from this part of the error `relative_blur = image / convolve2d(im_deconv, psf, 'same') `  I think that the function works only with 2d arrays.
If it is correct can this function be implemented for 3d arrays? Or is there something I am missing?
If this is not the right place to post this, I am sorry
Thanks a lot!
Simone

**Comment by JDWarner** [comment]
@simone-codeluppi, I just checked and this is fixed in master. The available deconvolution methods are now truly n-dimensional (and faster!). This functionality will be available in the upcoming 0.12 release. If you need it now, you can acquire and install scikit-image from source.

**Comment by simone-codeluppi** [comment]
@JDWarner Thanks a lot for the help!
