### ISSUE TITLE
Image comparison functions should share a common prefix

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1914]
Before #1897, we really only had one quantitative image comparison metric: structural similarity, available in `skimage.measure.structural_similarity`. Now we have three more, based on the PSNR, MSE, and NRMSE. 

Each of these directly compares two like-shaped arrays and yields a floating point result, indicating the degree of similarity. **All similar functions should share a prefix, to improve accessibility.**

In #1897 I proposed `compare_*` as such a prefix. Other options were `compare_with_*`, `compare_by_*`, and `metrics_`. I'd also toss in `imcompare_*`, but I dislike the Matlab feel.

As we add more features in the future, I think `metrics_*` is too broad.

**Comment by jni** [comment]
@JDWarner thanks for opening this! What about a namespace instead of a prefix? `compare.psnr(im1, im2)`

There is also the issue of scope... Will this prefix only apply to comparing images, or also label images? e.g. will rand_index, variation_of_information, and boundary_precision_recall, when they come, also live here?

**Comment by stefanv** [comment]
Do we have enough for a new namespace yet?  How about we use a prefix for
now, and when we see that we have enough for a namespace, break out the
namespace and add aliases from the current functions there.

**Comment by ahojnnes** [comment]
+1 for compare_*

**Comment by emmanuelle** [comment]
:+1: for compare_* from me too

**Comment by JDWarner** [comment]
Thanks for the input, I'll make a PR to this effect tomorrow on top of (now merged) #1897.

**Comment by jni** [comment]
@stefanv @JDWarner why make a prefix that we are almost certain to deprecate? Deprecations are painful and imho should be avoided if possible. If the argument is that we might *never* move the functions, sure, but if we think we are likely to move them, I would strongly favour making the namespace straight away, even if we consider it will be sparse to begin with.

Incidentally, if we want to include label images in that namespace, I can whip up rand index, adjusted rand index, and variation of information pretty quickly.

**Comment by JDWarner** [comment]
Prefixes are more accessible than namespaces. By accessible I mean easily discovered by a naive user. Our design across the package is basically to have a single level of bins within which are many similar functions. People using this package don't expect to have to traverse an additional level to find what they need. Ergo, functions sharing a prefix (which is also consistent with other, past design decisions) are more consistent with the typical user experience. There are points where this would break down, of course. If we had 500 functions in `measure` things would be different.

I'm not sure we'll have to deprecate this. Structural similarity is still the best of the bunch, and we don't need to throw the kitchen sink at this problem. Right now there are four functions which basically do the same thing, and I don't see a pressing need to add more.

At least, that's what is going through my head.
