### ISSUE TITLE
DOC: Reduce size image in plot_inpaint

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#1922]
In reference to #1920 

* Reduce the size of the image in  doc/examples/filters/plot_inpaint.py to show more clearly the result of the algorithm.

**Comment by sciunto** [comment]
OK, I fixed my virtualenv. Now, I can work on  a patch :)

**Comment by sciunto** [comment]
@emmanuelle Is it something like this that you had in mind?

![fig](https://framapic.org/nPfLnaBJKyrR/hLq2iA5sd285)

**Comment by stefanv** [comment]
Hopefully we can get rid of all that space in the middle.

**Comment by sciunto** [comment]
From sphinx, it'll look like that. it's just that I used mpl GUI and depending on the window size, the save button gives different results.
![plot_inpaint_1](https://cloud.githubusercontent.com/assets/335370/12772698/c6edfd04-ca01-11e5-84ce-175edb5a166e.png)

**Comment by soupault** [comment]
@sciunto I'd also add one small rectangle in the `hair`-area.
In literature, inpainting algorithms are usually evaluated on several types of underlying data:

1. homogenical regions :[addressed], 
2. sharp edges along and across the defect region [addressed], 
3. textures [that's what was missing earlier, but we should address here], 
4. regions with smooth gradients [kind of addressed by the overall impression], 
5. texts [nobody cares, really :)], etc. 

I also wanted to show how to it works with boundary conditions, so what's why the left region is there.

**Comment by sciunto** [comment]
@soupault i'm not. I just looked at the new features (a bit late, I have to admit) and I catched a typo :)
