### ISSUE TITLE
Images of type float need NOT be from -1 to 1

### ISSUE THREAD

**Issue by nashv** [scikit-image/scikit-image#1929]
A 32-bit floating point TIFF can have any IEEE 32-bit value. Scientific image processing requires that the such images be read and represented correctly.

Scikit-image can only allows values from -1 to 1 or 0 to 1 for floating point. This is an artificial restriction.

**Comment by jni** [comment]
Hi @nashv,

This is not a restriction, but an assumption that many functions in skimage make whenever a function *needs* to make an assumption about the range of the image. But you can work with 32-bit float tiffs no problem:

```python
In [1]: from skimage import io

In [2]: import numpy as np

In [3]: image = np.array([[-2.5, 0.5, 1e7 + 5.8]])

In [4]: io.imsave('im.tif', image, plugin='tifffile')

In [5]: image_read = io.imread('im.tif', plugin='tifffile')

In [6]: image_read
Out[6]: array([[ -2.50000000e+00,   5.00000000e-01,   1.00000058e+07]])
```

Image processing functions also work fine, e.g. grayscale dilation, with "out-of-range" images.

This is specified, perhaps not very clearly, [here](http://scikit-image.org/docs/dev/user_guide/data_types.html):

> Although **we aim to preserve the data range and type of input images**, functions may support only a subset of these data-types.

If you find a specific function that makes the [-1, 1] or [0, 1] assumption but shouldn't, please raise a new issue.

Thanks!
