### ISSUE TITLE
Link to PEP8 in contributor guidelines broken

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1947]
Should be an absolute link, but is relative.

**Comment by soupault** [comment]
Is it? https://github.com/scikit-image/scikit-image/blob/master/CONTRIBUTING.txt#L143

**Comment by stefanv** [comment]
It is broken on the website still, so did someone fix this recently?

**Comment by soupault** [comment]
Hmm... The link in http://scikit-image.org/docs/dev/contribute.html#stylistic-guidelines works fine for me.

**Comment by soupault** [comment]
Oh, I see. You are probably talking about 0.11.x docs. The link is relative there indeed.

**Comment by yash14123** [comment]
I am on it.

**Comment by soupault** [comment]
Not sure what are you going to fix here...

**Comment by soupault** [comment]
Ping @stefanv
