### ISSUE TITLE
Add Issue templates and declutter root directory

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#1949]
GitHub [now supports a `.github/` directory for their new Issue/PR templates](https://github.com/blog/2111-issue-and-pull-request-templates). There are common enough things we should know in essentially all Issues we should probably enable the Issue template requesting Python version, scikit-image version, and ensure full tracebacks are included if available.

We should also move `CONTRIBUTING.txt` into that directory, decluttering the root. It's always been less than ideal having `CONTRIBUTORS.txt` and `CONTRIBUTING.txt` right next to each other.

These are easy, quality-of-life changes which do not need to go in before 0.12.

**Comment by ahojnnes** [comment]
+1

**Comment by stefanv** [comment]
Good idea!

**Comment by soupault** [comment]
Do you have any proposals on the structure of templates?
I've had a thought about `ISSUE_TEMPLATE` recently and it seems we should consider one targetting 2 major cases: 
- __bugreport__ (description, code snippet/way to reproduce, software versions, {OS info}, {hardware specs})
- __proposal/feature request__ (description, {ideas on} preliminary solution, references[analogs in another projects/packages/languages], references[articles]).

Not really sure how to nicely merge these two structures.
Any other opinions?

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image/pull/1954 .
