### ISSUE TITLE
skimage.feature.peak_local_max's "exclude_border" functionality should not use "min_distance"

### ISSUE THREAD

**Issue by jmetz** [scikit-image/scikit-image#1950]
I just tried using `peak_local_max` and was puzzled to find no peaks (on a small test image). 
After reading the code I realized it was because the default `min_distance` of 10 (for minimum peak--peak separation) is also used as the border width of the `exclude_border` functionality. 

I find this behaviour bizarre frankly; usually exclude border for this type of algorithm means exclude border pixels, not a larger width (which is tied to a separate functionality!). 

I would suggest one of the following changes: 

* Either set the border width to be 1 pixel when `exclude_border` is `True`
* Or change `exclude_border` to be a border width (possible renaming?) such that e.g. `exclude_border=0` includes the border, while e.g. `exclude_border=5` excludes a border region of 5 pixels.

**Comment by stefanv** [comment]
Closed by #1951.
