### ISSUE TITLE
How to iradon transform

### ISSUE THREAD

**Issue by cpyman** [scikit-image/scikit-image#1953]
Hi, Emmanuelle

I have two pictures generated from 0deg and 90deg of a object. Currently, I want to make iradon transfromation to reconstruct the object, but, I can't understand the example of skimage.transform. iradon. How should I do? Could you give me a small example to do this?

**Comment by soupault** [comment]
@cpyman where exaclty do you have difficulties?
Have you seen http://scikit-image.org/docs/dev/auto_examples/plot_radon_transform.html ?

Here is a simple example, in case the information above is somehow not enough:
```
import numpy as np
from skimage.transform import radon, iradon
import matplotlib.pyplot as plt


img_orig = np.zeros((10, 10))
img_orig[2:4, 2:4] = 1
img_orig[7:9, 2:4] = 1

# Case 1. Reference sinogram
# sinogram = radon(img_orig, theta=[0, 90], circle=True)

# Case 2. "Your sinogram"
proj_0 = np.zeros((10, 1))
proj_90 = np.zeros((10, 1))
proj_0[2:4, :] = 2
proj_90[2:4, :] = 1
proj_90[7:9, :] = 1
sinogram = np.hstack((proj_0, proj_90))

img_rec = iradon(sinogram, theta=[0, 90], output_size=10)

fig, axes = plt.subplots(ncols=2)
axes[0].matshow(img_orig, cmap=plt.cm.Greys_r, interpolation='none')
axes[1].matshow(img_rec, cmap=plt.cm.Greys_r, interpolation='none')
plt.tight_layout()
plt.show()
```
![radon](https://cloud.githubusercontent.com/assets/1315589/13195642/d4e21d6c-d7c8-11e5-841a-79df62781b9b.png)

**Comment by soupault** [comment]
Btw, @scikit-image/core, I think it would be nice to show what is the direction of `theta=0` in the docsting. Any :+1: 's?

**Comment by cpyman** [comment]
Hi,

Below is my two pictures. One is for 0 degree, and the other is for 90 degree.

![halo_x](https://cloud.githubusercontent.com/assets/8341044/13195788/e6685182-d7f5-11e5-990c-234b8cb44de0.png)
![halo_y](https://cloud.githubusercontent.com/assets/8341044/13195790/f10de6ce-d7f5-11e5-8fce-c26fd8b647a4.png)

**Comment by soupault** [comment]
@cpyman Saw them. What is your question then?
Try to substitute `proj_0` and `proj_90` vectors in the example above with your data.

**Comment by cpyman** [comment]
Hi, soupault

My original picture as below. This is a halo ellipse, But the iradon transformation can't reconstruct this ellipse. I get a odd picture only.
origin picture
![halo_2d](https://cloud.githubusercontent.com/assets/8341044/13196638/6ef9551a-d80e-11e5-9113-d82b6d7a02f4.png)

iradon picture
![iradon_halo_2d](https://cloud.githubusercontent.com/assets/8341044/13196641/cd88aff4-d80e-11e5-96d5-e0afcd6111b9.png)

**Comment by soupault** [comment]
@cpyman It seems like you are using only one of the projections during the reconstruction process.
Notice, that `sinogram` should have as many columns as many projections you have, and also `theta` parameter should be set to the list of corresponding projection angles.

If you could paste you code somewhere, it'll be much faster for to figure the issue out.

**Comment by cpyman** [comment]
```python
import numpy as np
from skimage.transform import radon, iradon
import matplotlib.pyplot as plt
a = 1#mm
b = 0.1#mm
c = 1000#mm
eps0=8.854187817*10**(-12)
x0 = np.linspace(-10, 10, 1000)
rho = 8./3./np.pi**(1.5)/a/b/c*x0**2/b**2*np.exp(-x0**2/b**2)
rho1 = 8./3./np.pi**(1.5)/a/b/c*x0**2/a**2*np.exp(-x0**2/a**2)
proj_0 = np.array(rho)
proj_90 = np.array(rho1)
sinogram = np.vstack((proj_0, proj_90)).T
img_rec = iradon(sinogram, theta=[0, 90], output_size=10)
fig, axes = plt.subplots(ncols=2)
axes[1].matshow(img_rec, cmap=plt.cm.Greys_r, interpolation='none')
plt.tight_layout()
plt.show()

```

**Comment by cpyman** [comment]
Below is the halo ellipse code.
```python
import numpy as np
from mayavi import mlab
a = 1
b = 0.1
c = 0.5
x,y=np.ogrid [-10:10:500j,-2:2:160j]
z=8./3./np.pi**(1.5)/a/b/c*(x**2/a**2+y**2/b**2)*np.exp(-x**2/a**2-y**2/b**2)
pl=mlab.surf(x,y,z,warp_scale=2)
mlab.axes(xlabel='x',ylabel='y',zlabel='z')
mlab.outline(pl)
mlab.show()
```

**Comment by soupault** [comment]
@cpyman The code is doing the right thing. The only thing you should fix is the `output_size` value in `iradon` call.
Regarding your data: the elipse has badly-balanced axes, the discretization step is not so high and, finally, the number of projections (2) is really low to get sweet result.

Closing the issue as solved.
