### ISSUE TITLE
Bilateral filter win_size

### ISSUE THREAD

**Issue by rvdboomgaard** [scikit-image/scikit-image#1955]
The denoise_bilateral filter does not adjust the win_size in case sigma_spatial is set. So

denoise_bilateral(f, sigma_range=.1, sigma_spatial=3)

uses a 5x5 neighborhood which is way too small for a spatial scale of 3. I think that specifying sigma_spatial should adjust the win_size like

win_size = 2 * ceil( 3*sigma_spatial)  + 1

(the factor 3 could be reduced to something larger then 2 to speed up things)

**Comment by emmanuelle** [comment]
Hi @rvdboomgaard ! Thanks for the useful comment. I agree that ``ẁin_size`` should scale with ``sigma_spatial``. For the gaussian filter (``filters.gaussian``) we (or rather ``scipy.ndimage``) truncates the filter at 4 standard deviations. In the case of denoising (where we have already noise in the image) we can lower slightly the accuracy, truncating at 3 standard deviations (exp(-3**2/2) < 1%), as you suggest, seems like a good idea.

However, we should also let the possibility to the user to truncate heavily, say to two standard deviations, if he or she wishes so (it will often be good enough, even if it's not a "true" bilateral filter). Maybe a solution would be 
* to have a default value of ``None`` for win_size and, if None, to choose 
``win_size = max(5, 2 * ceil( 3*sigma_spatial) + 1)``

* if set by the user, not to modify it (but maybe issue a warning if the truncation is very strong).

What would you think about this solution?

It's likely that other people will also comment on this issue, and might have differing opinions. But if a possible solution emerges, would you be willing to write a pull request that would implement such an improvement?

**Comment by ahojnnes** [comment]
@emmanuelle +1 on your proposal, and +1 on renaming `sigma_range` to `sigma_color`.

**Comment by JDWarner** [comment]
:+1: for @emmanuelle's proposal as well as `sigma_color`.

**Comment by rvdboomgaard** [comment]
HI @emmanuelle 

i will dive into the source code and see what i can do. I never made a pull request for skimage, so maybe i will need some help there. I hope to have some spare time coming weekend.

**Comment by emmanuelle** [comment]
Hi @rvdboomgaard thanks! http://scikit-image.org/docs/stable/contribute.html is a good start for learning how to contribute a pull request, and of course, we're here to help if you have questions

**Comment by soupault** [comment]
Closed via #1981 .
