### ISSUE TITLE
Clarify difference between filled_area, area, and convex_area in regionprops

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1961]
Update the regionprops docstring to clarify the above.

**Comment by yash14123** [comment]
Please provide the link to the particular file where I can make changes.
Thanks.

**Comment by vighneshbirodkar** [comment]
Hello @yash14123 . You can find it yourself.
`grep` is a good place to start if you have no idea where to look
```shell
$> git grep filled_area
skimage/measure/_regionprops.py:    'FilledArea': 'filled_area',
skimage/measure/_regionprops.py:    def filled_area(self):
skimage/measure/_regionprops.py:    **filled_area** : int
skimage/measure/tests/test_regionprops.py:def test_filled_area():
skimage/measure/tests/test_regionprops.py:    area = regionprops(SAMPLE)[0].filled_area
skimage/measure/tests/test_regionprops.py:    area = regionprops(SAMPLE_mod)[0].filled_area
```

**Comment by yash14123** [comment]
No. I meant the documentation link. I am a newbie. Just help me out with the documentation page link.

**Comment by vighneshbirodkar** [comment]
The documentation is generated from the source files. As indicated with the grep search, the file is.
https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_regionprops.py

**Comment by tseclaudia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clarify difference between filled_area, area, and convex_hull_area in regionprops](https://trello.com/c/AK4AQzxZ/4-clarify-difference-between-filled-area-area-and-convex-hull-area-in-regionprops)

**Comment by stefanv** [comment]
See #2344
