### ISSUE TITLE
No labels on images, unclear for new comers

### ISSUE THREAD

**Issue by theaverageguy** [scikit-image/scikit-image#1967]
http://scikit-image.org/docs/dev/auto_examples/plot_censure.html

**Comment by soupault** [comment]
@yash14123 Hi! Would you like to proceed with Pull Request? Target file is https://github.com/scikit-image/scikit-image/blob/master/doc/examples/features_detection/plot_censure.py

**Comment by yash14123** [comment]
On it.

**Comment by soupault** [comment]
Incorporated into https://github.com/scikit-image/scikit-image/issues/1773, to be closed via https://github.com/scikit-image/scikit-image/pull/2144.
