### ISSUE TITLE
Adjust spacing in the gallery overview

### ISSUE THREAD

**Issue by theaverageguy** [scikit-image/scikit-image#1968]
http://scikit-image.org/docs/dev/auto_examples/index.html
![m](https://cloud.githubusercontent.com/assets/9817962/13400578/74a68ad8-df2e-11e5-940b-1803f6a5d873.png)

**Comment by yash14123** [comment]
Please provide link to this so I can fix this @soupault .

**Comment by vighneshbirodkar** [comment]
@yash14123 Can you elaborate what you mean ?

**Comment by yash14123** [comment]
The spacing is very less between "Segmentation of objects" and the upper examples. It is not consistent with other spacing.

**Comment by yash14123** [comment]
The spacing is very less between "Segmentation of objects" and the upper examples. It is not consistent with other spacing.

**Comment by yash14123** [comment]
The spacing is very less between "Segmentation of objects" and the upper examples. It is not consistent with other spacing.

**Comment by sciunto** [comment]
This problem does not exist anymore (probably with sphinx-gallery updates).

**Comment by soupault** [comment]
LOL, what's that `orphan:` thing for?

**Comment by sciunto** [comment]
no idea. I noted on my todo list to check that and report if necessary.
