### ISSUE TITLE
Large whitespaces in docs 

### ISSUE THREAD

**Issue by theaverageguy** [scikit-image/scikit-image#1969]
These are likely just due to extremely simple visualizations which could be enhanced, possibly in a separate PR or with tight_layout

 http://scikit-image.org/docs/dev/auto_examples/plot_ncut.html
 http://scikit-image.org/docs/dev/auto_examples/plot_rag_draw.html
 http://scikit-image.org/docs/dev/auto_examples/plot_rag_mean_color.html
 http://scikit-image.org/docs/dev/auto_examples/plot_rag_merge.html
 http://scikit-image.org/docs/dev/auto_examples/plot_windowed_histogram.html
 http://scikit-image.org/docs/dev/auto_examples/applications/plot_geometric.html (first figure needs better figsize)

**Comment by alexandrejaguar** [comment]
Hi @yash14123, I was working on that issue too! Thanks for doing that!
I solve that using plt.tight_layout() and changing the size for that figures. I finished these examples:
http://scikit-image.org/docs/dev/auto_examples/plot_convex_hull.html
http://scikit-image.org/docs/dev/auto_examples/plot_censure.html
Check #1810 if you'd like :)
Have a nice one!

**Comment by yash14123** [comment]
I will add a PR today. Thanks for the help @alexandrejaguar :)

**Comment by soupault** [comment]
Incorporated into https://github.com/scikit-image/scikit-image/issues/1773, to be closed via https://github.com/scikit-image/scikit-image/pull/2144.
