### ISSUE TITLE
Rework gallery to use `sphinx-gallery`

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1973]
See https://github.com/sphinx-gallery/sphinx-gallery

**Comment by emmanuelle** [comment]
That'd be really cool. ``sphinx-gallery`` is a great way to join forces between projects, and galleries are such an awesome way to learn!

**Comment by emmanuelle** [comment]
Since ``sphinx-gallery`` is not packaged for Debian how should we proceed? It's possible that it will be packaged by the time 0.13 is out, or we could also copy the code of sphinx-gallery (as did the ``nilearn`` project, for example).

**Comment by emmanuelle** [comment]
@stefanv Did you open this issue cause you're planning to work on it, or is a call for volunteers?

**Comment by stefanv** [comment]
I opened an issue as a reminder, but I don't have time to do this right now.

I think we shouldn't worry too much about Debian--Yarik and I find
workarounds for most problems :)

​

**Comment by emmanuelle** [comment]
It might be a good challenge for the Easter week-end :-), I'll be starting on it.

**Comment by soupault** [comment]
Closed via #2078.
