### ISSUE TITLE
Remove duplicate mean of template calculation in skimage.feature.match_template

### ISSUE THREAD

**Issue by jmetz** [scikit-image/scikit-image#1978]
Reviewing `match_template` I found 

    template_volume = np.prod(template.shape)
    template_ssd = np.sum((template - template.mean()) ** 2)

    if image.ndim == 2:
        xcorr = fftconvolve(image, template[::-1, ::-1],
                            mode="valid")[1:-1, 1:-1]
    elif image.ndim == 3:
        xcorr = fftconvolve(image, template[::-1, ::-1, ::-1],
                            mode="valid")[1:-1, 1:-1, 1:-1]

    nom = xcorr - image_window_sum * (template.sum() / template_volume)

I.e. `template.mean()` is calculated once, and then further down `template.sum() / template_volume`; presumably we can make this faster using e.g. 

    template_mean = template.mean()

and using that both times it's needed?

**Comment by jmetz** [comment]
Would suggest the labels: "easy" and "enhancement" (or a new "optimization" label?)

**Comment by JDWarner** [comment]
:+1:, yes this should be precalculated and referenced. Thanks for the review!

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image/pull/1980.
