### ISSUE TITLE
bento.info lists autogenerated file skimage/morphology/_skeletonize_3d_cy.pyx

### ISSUE THREAD

**Issue by ev-br** [scikit-image/scikit-image#1988]
... instead of the actual source file .pyx.in.

This adds to recent woes with regards to the cython templating, I'm afraid. This fell through the cracks of gh-1923 --- I added the pyx file to bento.info to silence the CI which checks consistency of bento.info and setup.py. But eventually this is weird because the file is autogenerated. No idea whether this is serious or not, just flagging this up. I also note that SciPy bento.info only lists C files, for both pyx and pyx.in sources.

**Comment by stefanv** [comment]
I guess I am the only person still using Bento.  Time to drop it?
​

**Comment by ev-br** [comment]
No idea, to be honest. Ralf is/was saying he is using it.

**Comment by JDWarner** [comment]
Does pip build in parallel now? I never got into bento, but thought that
was the main selling point.

**Comment by stefanv** [comment]
Closed by https://github.com/scikit-image/scikit-image/pull/2776
