### ISSUE TITLE
Problem installing scikit

### ISSUE THREAD

**Issue by mkranthikmr** [scikit-image/scikit-image#1997]
```
PS C:\WINDOWS\system32> pip install -U scikit-image
Downloading/unpacking scikit-image
  Running setup.py (path:C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scikit-image\setup.py) egg_info for package scikit-image
    Unable to find pgen, not compiling formal grammar.
    No eggs found in C:\Users\Maddala\AppData\Local\Temp\easy_install-u84fy7nh\Cython-0.23.4\egg-dist-tmp-81wvqary (setup script problem?)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scikit-image\setup.py", line 146, in <module>
        **extra
      File "C:\Python34\lib\site-packages\numpy\distutils\core.py", line 126, in setup
        dist = setup(**new_attr)
      File "C:\Python34\lib\site-packages\numpy\distutils\core.py", line 169, in setup
        return old_setup(**new_attr)
      File "C:\Python34\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Python34\lib\site-packages\numpy\distutils\numpy_distribution.py", line 16, in __init__
        Distribution.__init__(self, attrs)
      File "C:\Python34\lib\site-packages\setuptools\dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "C:\Python34\lib\site-packages\setuptools\dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "C:\Python34\lib\site-packages\pkg_resources.py", line 572, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: cython>=0.21
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.

No eggs found in C:\Users\Maddala\AppData\Local\Temp\easy_install-u84fy7nh\Cython-0.23.4\egg-dist-tmp-81wvqary (setup sc
ript problem?)
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scikit-image\setup.py", line 146, in <module>
    **extra
  File "C:\Python34\lib\site-packages\numpy\distutils\core.py", line 126, in setup
    dist = setup(**new_attr)
  File "C:\Python34\lib\site-packages\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\Python34\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Python34\lib\site-packages\numpy\distutils\numpy_distribution.py", line 16, in __init__
    Distribution.__init__(self, attrs)
  File "C:\Python34\lib\site-packages\setuptools\dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "C:\Python34\lib\site-packages\setuptools\dist.py", line 263, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 572, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cython>=0.21
----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\sciki
t-image
Storing debug log for failure in C:\Users\Maddala\pip\pip.log
```

**Comment by soupault** [comment]
> pkg_resources.DistributionNotFound: cython>=0.21

@mkranthikmr what is the version of installed `cython`?
If you aren't feel confident about solving this kind of issues with `pip`, you should use pre-built `.whl` files from:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#cython
http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image

**Comment by mkranthikmr** [comment]
PS C:\Users\Maddala\Downloads> python --version
Python 3.4.2

Can you let me know how to do that with .whl files? i downloaded those .whl files what is next?

**Comment by soupault** [comment]
@mkranthikmr I was asking about `cython` version, not `python`. To see it, call `pip show cython`.

Regarding .whl: these are complete packages for Python and can be installed via, for example: `pip install some-package.whl`.

**Comment by emmanuelle** [comment]
@mkranthikmr it's the version of cython that @soupault was asking about, so you should type "cython -V".

Also, how did you install Python, and SciPy ? With Anaconda or Canopy ?

**Comment by mkranthikmr** [comment]
PS C:\Users\Maddala\Downloads> cython --version
Cython version 0.23.4

**Comment by mkranthikmr** [comment]
I am unable to install Scipy even... @emmanuelle 

PS C:\Users\Maddala\Downloads> pip install scipy
Downloading/unpacking scipy
  Running setup.py (path:C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scipy\setup.py) egg_info for package scip
y

    warning: no previously-included files matching '*_subr_*.f' found under directory 'scipy\linalg\src\id_dist\src'
    no previously-included directories found matching 'benchmarks\env'
    no previously-included directories found matching 'benchmarks\results'
    no previously-included directories found matching 'benchmarks\html'
    no previously-included directories found matching 'benchmarks\scipy'
    no previously-included directories found matching 'scipy\special\tests\data\boost'
    no previously-included directories found matching 'scipy\special\tests\data\gsl'
    no previously-included directories found matching 'doc\build'
    no previously-included directories found matching 'doc\source\generated'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.bak' found anywhere in distribution
    warning: no previously-included files matching '*.swp' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
Installing collected packages: scipy
  Running setup.py install for scipy
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['C:\\Python34\\lib', 'C:\\', 'C:\\Python34\\libs']
      NOT AVAILABLE

    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['C:\\Python34\\lib', 'C:\\', 'C:\\Python34\\libs']
      NOT AVAILABLE

      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['C:\\Python34\\lib', 'C:\\', 'C:\\Python34\\libs']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    C:\Python34\lib\site-packages\numpy\distutils\system_info.py:635: UserWarning: Specified path C:\projects\np-wheel-b
uilder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    C:\Python34\lib\site-packages\numpy\distutils\system_info.py:1552: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    C:\Python34\lib\site-packages\numpy\distutils\system_info.py:1563: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    C:\Python34\lib\site-packages\numpy\distutils\system_info.py:1566: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scipy\setup.py", line 265, in <module>
        setup_package()
      File "C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scipy\setup.py", line 262, in setup_package
        setup(**metadata)
      File "C:\Python34\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scipy\setup.py", line 182, in configuration
        config.add_subpackage('scipy')
      File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    Complete output from command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Maddala\\Ap
pData\\Local\\Temp\\pip_build_Maddala\\scipy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().re
place('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Maddala\AppData\Local\Temp\pip-_rmjx_5_-record\instal
l-record.txt --single-version-externally-managed --compile:
    lapack_opt_info:

openblas_lapack_info:

  libraries openblas not found in ['C:\\Python34\\lib', 'C:\\', 'C:\\Python34\\libs']

  NOT AVAILABLE



lapack_mkl_info:

mkl_info:

  libraries mkl,vml,guide not found in ['C:\\Python34\\lib', 'C:\\', 'C:\\Python34\\libs']

  NOT AVAILABLE



  NOT AVAILABLE



atlas_3_10_threads_info:

Setting PTATLAS=ATLAS

<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>

  NOT AVAILABLE



atlas_3_10_info:

<class 'numpy.distutils.system_info.atlas_3_10_info'>

  NOT AVAILABLE



atlas_threads_info:

Setting PTATLAS=ATLAS

<class 'numpy.distutils.system_info.atlas_threads_info'>

  NOT AVAILABLE



atlas_info:

<class 'numpy.distutils.system_info.atlas_info'>

  NOT AVAILABLE



lapack_info:

  libraries lapack not found in ['C:\\Python34\\lib', 'C:\\', 'C:\\Python34\\libs']

  NOT AVAILABLE



lapack_src_info:

  NOT AVAILABLE



  NOT AVAILABLE



C:\Python34\lib\site-packages\numpy\distutils\system_info.py:635: UserWarning: Specified path C:\projects\np-wheel-build
er\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

C:\Python34\lib\site-packages\numpy\distutils\system_info.py:1552: UserWarning:

    Atlas (http://math-atlas.sourceforge.net/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [atlas]) or by setting

    the ATLAS environment variable.

  warnings.warn(AtlasNotFoundError.__doc__)

C:\Python34\lib\site-packages\numpy\distutils\system_info.py:1563: UserWarning:

    Lapack (http://www.netlib.org/lapack/) libraries not found.

    Directories to search for the libraries can be specified in the

    numpy/distutils/site.cfg file (section [lapack]) or by setting

    the LAPACK environment variable.

  warnings.warn(LapackNotFoundError.__doc__)

C:\Python34\lib\site-packages\numpy\distutils\system_info.py:1566: UserWarning:

    Lapack (http://www.netlib.org/lapack/) sources not found.

    Directories to search for the sources can be specified in the

    numpy/distutils/site.cfg file (section [lapack_src]) or by setting

    the LAPACK_SRC environment variable.

  warnings.warn(LapackSrcNotFoundError.__doc__)

Running from scipy source directory.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scipy\setup.py", line 265, in <module>

    setup_package()

  File "C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scipy\setup.py", line 262, in setup_package

    setup(**metadata)

  File "C:\Python34\lib\site-packages\numpy\distutils\core.py", line 135, in setup

    config = configuration()

  File "C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scipy\setup.py", line 182, in configuration

    config.add_subpackage('scipy')

  File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 1002, in add_subpackage

    caller_level = 2)

  File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 971, in get_subpackage

    caller_level = caller_level + 1)

  File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 908, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "scipy\setup.py", line 15, in configuration

    config.add_subpackage('linalg')

  File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 1002, in add_subpackage

    caller_level = 2)

  File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 971, in get_subpackage

    caller_level = caller_level + 1)

  File "C:\Python34\lib\site-packages\numpy\distutils\misc_util.py", line 908, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "scipy\linalg\setup.py", line 20, in configuration

    raise NotFoundError('no lapack/blas resources found')

numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

----------------------------------------
Cleaning up...
Command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Maddala\\AppData\\Local\\Temp\\pip_b
uild_Maddala\\scipy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __fi
le__, 'exec'))" install --record C:\Users\Maddala\AppData\Local\Temp\pip-_rmjx_5_-record\install-record.txt --single-ver
sion-externally-managed --compile failed with error code 1 in C:\Users\Maddala\AppData\Local\Temp\pip_build_Maddala\scip
y
Storing debug log for failure in C:\Users\Maddala\pip\pip.log

**Comment by soupault** [comment]
@mkranthikmr Have you read this through https://docs.scipy.org/doc/numpy-1.10.1/user/install.html , https://www.scipy.org/install.html ?
**Shortly**: It is nearly impossible to build `numpy` and `scipy` on Windows by yourself without well-prepared building environment. It is better for you to use either [conda package manager](http://conda.pydata.org/docs/) or already mentioned [packages from C.Gohlke](www.lfd.uci.edu/~gohlke/pythonlibs/). For example, I'm using `conda` for my Windows PC.

P.S. Please, do not paste here huge logs - just post them to `pastebin.com` and provide a link.

**Comment by stefanv** [comment]
We are about to upload Windows wheels for all the required packages. I'll
check with Matthew Brett what the status is.

**Comment by emmanuelle** [comment]
@stefanv Christoph Gohlke has already uploaded wheels for scikit-image 0.12.3
http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image
Do you think it would be possible to ask him if we can use his wheels on PyPi?

**Comment by stefanv** [comment]
We can just upload the wheels generated by AppVeyor for 0.12.3. Will do
that when I get back to a computer.

**Comment by stefanv** [comment]
Turns out we only have a 2.7, 32-bit wheel from that build.  @cgohlke,
could we convince you to upload your wheels to pypi?

**Comment by matthew-brett** [comment]
Why don't you build wheels for the other platforms on appveyor?​

**Comment by cgohlke** [comment]
Feel free to redistribute the wheel files from <http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image>. Things to consider:
* the binaries require numpy 1.10.
* the wheel files require pip version 8+ because they use the ABI tag.
* `pip install scikit-image` will likely fail because there are still no scipy wheels on PyPI.

**Comment by soupault** [comment]
@mkranthikmr have you succeed to install the `scikit-image` either via `conda` or C.Gohlke's `.whl`s?

**Comment by soupault** [comment]
Closing the issue due to the lack of activity.
Feel free to reopen with update.

**Comment by stefanv** [comment]
Just to update everyone, we're waiting for builds of numpy and scipy to
become available. Also, I now have a Windows build machine that Matthew
Brett and I will use to build the scikit-image wheels.

**Comment by dongzhuoyao** [comment]
pip install Cython --upgrade
