### ISSUE TITLE
ValueError: win_size exceeds image extent in compare_ssim

### ISSUE THREAD

**Issue by elpaso** [scikit-image/scikit-image#1998]
I've got an error in compare_ssim ValueError: win_size exceeds image extent, should I file a bug?
the image is a simple PNG, shape returns (248, 248, 3), it obviously fail because default win_size is set to 7 and 3 - 7 < 0, see: https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_structural_similarity.py#L141

Shouldn't this check be in the first two array elements only?

**Comment by grlee77** [comment]
Hi @elpaso 
I assume this is for the current release?  If so, you will need to set `multichannel=True` when calling `compare_ssim` on color images.  Otherwise, it is treating as a 3D array, not 2D+channels and tries to filter along all three axis.  When multichannel=True, the function is called separately for each color axis and the average SSIM metric across channels is returned.

When implementing this there was a debate about defaulting `multichannel` to None and then auto-setting it to True if image.shape[-1] was 3 or 4 or False otherwise, but we ended up with a consensus to explicitly require the `multichannel` argument.

**Comment by elpaso** [comment]
Yes, current release, thanks for claryfying!

I suppose this can be closed.

**Comment by grlee77** [comment]
I just submitted a PR to make the multichannel=True suggestion a part of the error message

**Comment by elpaso** [comment]
Awesome, Thanks!

**Comment by jamiechoi1995** [comment]
when your input image is too small (eg. one of its size is less than 7) it will also rise this error even if setting `multichannel=True`,
this is caused by https://github.com/scikit-image/scikit-image/blob/e6769c5269eedf4b5850d14c321df30e75c7dc18/skimage/measure/_structural_similarity.py#L144

**Comment by cy19980615** [comment]
> when your input image is too small (eg. one of its size is less than 7) it will also rise this error even if setting multichannel=True,
> this is caused by 
>   
>     
>       scikit-image/skimage/measure/_structural_similarity.py
>     
>     
>         Lines 144 to 146
>       in
>       e6769c5
>     
>     
>     
>     
> 
>         
>           
>            if np.any((np.asarray(X.shape) - win_size) < 0): 
>         
> 
>         
>           
>                raise ValueError( 
>         
> 
>         
>           
>                    "win_size exceeds image extent.  If the input is a multichannel "

my input image is 128*128 also has this error,the min size with no error is 256 or how much?thanks

**Comment by Adarsh-Vemali** [comment]
> when your input image is too small (eg. one of its size is less than 7) it will also rise this error even if setting `multichannel=True`,
> this is caused by
> 
> https://github.com/scikit-image/scikit-image/blob/e6769c5269eedf4b5850d14c321df30e75c7dc18/skimage/measure/_structural_similarity.py#L144-L146

What is the solution to this?

**Comment by grlee77** [comment]
> What is the solution to this?

Can you give a little more context of the shape of the data you are working with? Do you have an axis less than size 7 that is not a "channels" (color) axis? 

If your data has color channels, the color channel needs to be the last axis and you should set `multichannel=True`. If the spatial axes are really so small that size is <7 then I don't know that using structural similarity as a metric is reasonable.

**Comment by Adarsh-Vemali** [comment]
Yes, I got it. The shape of my data had dimensions less than 7.  A quick and dirty solution I used was resizing the image to 7.
Also, yes using SSIM is not reasonable as well. Thanks for the reply.

**Comment by Adarsh-Vemali** [comment]
> > What is the solution to this?
> 
> Can you give a little more context of the shape of the data you are working with? Do you have an axis less than size 7 that is not a "channels" (color) axis?
> 
> If your data has color channels, the color channel needs to be the last axis and you should set `multichannel=True`. If the spatial axes are really so small that size is <7 then I don't know that using structural similarity as a metric is reasonable.

Yes, I got it. The shape of my data had dimensions less than 7. A quick and dirty solution I used was resizing the image to 7.
Also, yes using SSIM is not reasonable as well. Thanks for the reply.

**Comment by aliabdari** [comment]
I face this issue too. my image size is (5,8,3), and when I imshow it, it does not show an understandable image
what is the best solution for comparing these kinds of small images?
Is it reasonable to divide our approach into two parts for comparing big and small images?

**Comment by grlee77** [comment]
`skimage.metrics.normalized_root_mse` or `skimage.metrics.peak_signal_noise_ratio` can be used with small images like that. I think such images are just too small for `structural_similarity` to be a reasonable comparison.

> Is it reasonable to divide our approach into two parts for comparing big and small images?

This probably depends what you are trying to do, but it may just be preferable to use a different metric that can be used on all sizes encountered in your application.
