### ISSUE TITLE
skimage.segmentation.quickshift signature is missing from API docs

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2005]
See http://scikit-image.org/docs/dev/api/skimage.segmentation.html#quickshift .
Probably, due to `float` in https://github.com/scikit-image/scikit-image/blob/master/skimage/segmentation/_quickshift.pyx#L17 .

**Comment by soupault** [comment]
@ahojnnes Hi! How the docs are being deployed? When to expect website to be updated to verify the fix?

**Comment by blink1073** [comment]
@soupault, the dev docs are automatically deployed when a PR is merged.  https://github.com/blink1073/scikit-image/blob/master/tools/deploy_docs.sh

**Comment by soupault** [comment]
@blink1073 I see, thanks!
The issue isn't fixed then. :( Any other ideas on the cause?

**Comment by ahojnnes** [comment]
@soupault The function needs a pure python wrapper, see e.g. `slic()`.

**Comment by soupault** [comment]
@ahojnnes That was one of my top2 guesses :). It is really strange to me that the docstring is handled correctly, while the signature isn't.

**Comment by blink1073** [comment]
Probably just a limitation of sphinx.

**Comment by soupault** [comment]
Finally! :fireworks:
