### ISSUE TITLE
active_contour gallery example contains service info

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2007]
I suggest to remove `scipy` version checks:
https://github.com/scikit-image/scikit-image/blob/master/doc/examples/edges/plot_active_contours.py#L34-L39
https://github.com/scikit-image/scikit-image/blob/master/doc/examples/edges/plot_active_contours.py#L49-L54

**Comment by stefanv** [comment]
That would make our tests fail on older versions of scipy, wouldn't it?

**Comment by soupault** [comment]
@stefanv , oh, fair enough. Thanks for the hint!
