### ISSUE TITLE
Why are scikit-image documentation files .txt files (instead of .rst)?

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#2026]
Since sphinx promotes the use of .rst by default, I'm wondering why we are using .txt and not .rst for our (ReST) documentation files. It looks like a non-standard choice, but maybe there was a good reason at some point to prefer the .txt extension?

I ran into this issue when trying use sphinx-gallery for scikit-image (issue #1973), since sphinx-gallery only produces .rst files for the examples.

**Comment by stefanv** [comment]
I think because my editor handled .txt better at the time :) Feel free to
rename.

**Comment by emmanuelle** [comment]
Ok thanks :-). Renaming to .rst might indeed be the easiest option.
