### ISSUE TITLE
Is the "TypeError("'NoneType' object is not callable",)" exception still not be settled when import skimage.segmentation? 

### ISSUE THREAD

**Issue by wenchieh** [scikit-image/scikit-image#2027]
I find the earliest bug reporting about "the program will throw exception after exit when import `skimage.segmentation`" was issued in  Dec 7, 2014. But I still get in the same trouble in  version 0.11.3 in ubuntu 14.04 64bits and python 2.7.

here is the test code example:

```
 import numpy as np
 from PIL import Image
 from skimage import segmentation

 img = np.array(Image.open('test.jpg'))
 segs = segmentation.slic(img, n_segments=100, sigma=5)
 print segs.shape
```

which throws the exception:
```
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0xb56bb1cc>> ignored**
```
Although I only import the related packages and libraries,  the same exception still occurs. 
I'm looking forward someone could give me a hand,  thank you!

**Comment by soupault** [comment]
xref https://github.com/scikit-image/scikit-image/issues/1308

**Comment by JDWarner** [comment]
Update scipy, that should solve the problem.

**Comment by wenchieh** [comment]
@JDWarner, thank you for you suggestion, but the problem seems haven't any improvement  after updating the scipy from v0.13.0 to v0.17.0,

**Comment by wenchieh** [comment]
Thank you for you suggestion,   It does solve the problem  after updating the scipy from v0.13.0 to v0.17.0,
