### ISSUE TITLE
Inconsistent cython version requirements

### ISSUE THREAD

**Issue by opoplawski** [scikit-image/scikit-image#2035]
## Description

setup.py requires cython >= 0.21 while skimage/_build.py requires >= 0.23.  Also, the two checks seem redundant.

**Comment by stefanv** [comment]
Do you mind filing a pull request to fix it?

**Comment by opoplawski** [comment]
Sure.  The main reason I didn't is that my sense would be to remove the test in skimage/_build.py.  Also, I managed to build fine with cython 0.19, so I'm curious as to why 0.23 is required.

**Comment by stefanv** [comment]
Are you sure you built the latest version?  We are using some features that were introduced after 0.19!

**Comment by stefanv** [comment]
(Do a "make clean; make" to be sure)

**Comment by opoplawski** [comment]
Ah, so the tarball ships the .pyx files.  So do we actually need Cython installed then to build from that?

**Comment by stefanv** [comment]
No, if you have the .pyx and .md5 files, you should be set.​
