### ISSUE TITLE
Using deprecated numpy api

### ISSUE THREAD

**Issue by opoplawski** [scikit-image/scikit-image#2037]
## Description

Building scikit-image with numpy 1.11.0 results in lots of messages like:

```
In file included from /usr/lib64/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/lib64/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/lib64/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from skimage/restoration/_denoise_cy.c:250:
/usr/lib64/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
```
## Way to reproduce

[If reporting a bug, please include the following important information:]
- [ ] Operating system and version: 
  Fedora Rawhide
- [ ] Python version: 
  2.7.11
- [ ] scikit-image version (run `skimage.__version__`): 
  0.12.3

**Comment by stefanv** [comment]
This is due to code produced by Cython, so I guess there's not much we can do to fix it.  Hopefully, later versions of Cython will get rid of them!

**Comment by stefanv** [comment]
What is your Cython version, by the way?  Or did you use the pre-packaged .pyx files?

**Comment by sciunto** [comment]
@stefanv I do have a similar output in my virtual env. I'm using Cython 0.24. I ran `make clean` before `python setup.py build`

**Comment by opoplawski** [comment]
I'm using the pre-packaged .pyx files.

**Comment by soupault** [comment]
I agree with Stefan, not much to do from our side. Let's just wait :)
