### ISSUE TITLE
`SimilarityTransform.estimate` returns unstable, wrong value

### ISSUE THREAD

**Issue by goretkin** [scikit-image/scikit-image#2039]
## Description

It appears that `SimilarityTransform.estimate` is returning very wrong answers for over-determined data. In this case, the data does not lead to a well-fitting similarity transform. But the offsets of ~1e17 in the translation parameters of the transformation matrix are very wrong.

```python
import numpy as np
import skimage.transform

desired_points = np.array([[  0.75,  10.  ],
       [  0.75,  10.5 ],
       [  1.25,  10.5 ],
       [  1.25,  10.  ],
       [  0.75,  10.  ],
       [  0.75,  10.5 ],
       [  1.25,  10.5 ],
       [  1.25,  10.  ]])

actual_points = np.array([[3066,  344],
       [3066,  144],
       [2864,  144],
       [2864,  346],
       [2422,  348],
       [2422,  146],
       [2220,  150],
       [2222,  350]])

t = skimage.transform.SimilarityTransform()
t.estimate(dst=actual_points, src=desired_points)
t.params
```

On one machine 
I get 
```python
array([[ -8.67142009e+02,   6.46331840e+01,  -2.19998003e+17],
       [ -6.46331840e+01,  -8.67142009e+02,  -4.25662457e+16],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])
```

on another
```python
array([[  0.00000000e+00,   3.47821456e+02,   1.14356273e+18],
       [ -3.47821456e+02,   0.00000000e+00,  -8.88987484e+18],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])
```

in both cases, the `fit` call returns `True` 

## Way to reproduce
One machine:
```
In [83]: sys.version                                                                                                                     
Out[83]: '3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

In [84]: skimage.__version__
Out[84]: '0.11.3'

In [85]: np.version.full_version
Out[85]: '1.10.4'
```

another
```
skimage.__version__
'0.11.3'

sys.version
'3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55) \n[GCC 4.2.1 (Apple Inc. build 5577)]'

np.version.full_version
'1.10.4'
```

**Comment by soupault** [comment]
@goretkin Hi! Thanks for reporting!
Is it possible for you to update `skimage` to `0.12.3` and check if results are _at least_ consistant?

Python 2.7+3.5, skimage 0.12.3, numpy 1.11.0:
```
[[ -9.45041049e+02  -1.04124787e+02  -1.55011909e+17]
 [  1.04124787e+02  -9.45041049e+02  -3.98643759e+16]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]
```

I will investigate it better.

**Comment by ahojnnes** [comment]
You basically have two sets of identical points.

**Comment by ahojnnes** [comment]
To expand a little more: remove the second set and you should get a reasonable estimate.

**Comment by goretkin** [comment]
@ahojnnes Don't you think I should get a "reasonable", numerically-stable estimate with the data I used? The set of points I am using aren't degenerate.

The following isn't a similarity transform (because the approach of using the pseudo-inverse doesn't constrain uniform scaling) but it illustrates that the question is well posed.

```python
desired_points = np.array([[  0.75,  10.  ],
       [  0.75,  10.5 ],
       [  1.25,  10.5 ],
       [  1.25,  10.  ],
       [  0.75,  10.  ],
       [  0.75,  10.5 ],
       [  1.25,  10.5 ],
       [  1.25,  10.  ]])

actual_points = np.array([[3066,  344],
       [3066,  144],
       [2864,  144],
       [2864,  346],
       [2422,  348],
       [2422,  146],
       [2220,  150],
       [2222,  350]])

desired_points_h = np.concatenate((desired_points, np.ones((len(desired_points),1))), axis=1)
actual_points_h = np.concatenate((actual_points, np.ones((len(actual_points),1))), axis=1)

t_mat = (desired_points_h.T).dot(np.linalg.pinv(actual_points_h.T))
print(t_mat)


plt.figure()
plt.plot(actual_points[:,0], actual_points[:,1], 'b.')
plt.gca().set_aspect(1)


desired_points_attempt_h = t_mat.dot(actual_points_h.T).T

plt.figure()
plt.plot(desired_points[:,0], desired_points[:,1], 'r.')
plt.gca().set_aspect(1)

plt.plot(desired_points_attempt_h[:,0], desired_points_attempt_h[:,1], 'b.')
plt.gca().set_aspect(1)
```

```
python
[[ -2.21519958e-04   8.97503505e-06   1.58332028e+00]
 [ -1.62854212e-05  -2.48736722e-03   1.09061825e+01]
 [  1.08420217e-18   1.08420217e-18   1.00000000e+00]]
```

![blue](https://cloud.githubusercontent.com/assets/581043/14353072/7f09002a-fca5-11e5-91a8-311695ad4e96.png)

![redblue](https://cloud.githubusercontent.com/assets/581043/14353079/860287fc-fca5-11e5-8095-f483e7b89168.png)

(Note that there are actually 8 red points, however 4 of them are duplicates, as @ahojnnes pointed out to me)

**Comment by ahojnnes** [comment]
I am sorry, I just looked at the first set of points. This should produce a reasonable result. Give me some time and I'll look into it. If I forget, feel free to ping me again.

**Comment by stefanv** [comment]
Is this input valid?

desired_points[0] == [0.75, 10] and maps to [3066, 344]
desired_points[4] == [0.75, 10] and maps to [2422,  348]
​

**Comment by goretkin** [comment]
@stefanv What do you mean? Possibly I am misunderstanding the documentation:

> You can determine the over-, well- and under-determined parameters with the total least-squares method.

The points over-determine the parameters.

**Comment by stefanv** [comment]
But what should the resulting transformation be, if you want to map two inputs to the same output?

**Comment by goretkin** [comment]
@stefanv The documentation for this function says it does total least-squares. It should minimize the sum of squares of the residuals in the input and output space. Each point-pair, as I understand it, contributes four residual values (two points, each with an x and y error). If we accept this, then there isn't any room to question the validity of the inputs, or question whether or not such a transformation exists.

The resulting transformation should be the one that minimizes sum of these residuals. It looks like this: https://gist.github.com/goretkin/c2705a98046e49d70dc3fe3a2688055f. I roughly followed the notation in [1].

It is perfectly well-defined to seek a resulting transformation that maps, in the least-error sense, two distinct inputs to the same output. If we consider only translations, I can ask "what is the best mapping that maps all these input points to the single output point `[0,0]`. The answer would be the translation corresponding to the set of the input points.

[1] http://people.csail.mit.edu/bkph/papers/Absolute_Orientation.pdf

**Comment by stefanv** [comment]
Here you can see exactly what the code does:

https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/_geometric.py#L640
​

**Comment by ahojnnes** [comment]
This is most likely an issue of numerical stability. We probably want to implement http://graphics.stanford.edu/courses/cs164-09-spring/Handouts/paper_Umeyama.pdf at some point for better stability.

**Comment by goretkin** [comment]
@stefanv, yes, I saw it but unfortunately I don't quite understand it. Is there a reference for the method? Regardless, the documentation and the actual behavior of the function are at odds.

@ahojnnes intresting paper. It cites the Horn paper I mentioned, and claims to improves upon it by making sure to returns proper rotations (det = 1) and not reflections (det = -1). I don't understand the issue intimately, but this issue probably cannot affect the 2D case, because the rotations are parameterized by a single number (the angle) and not a matrix.

**Comment by ahojnnes** [comment]
@goretkin Please, have a look at https://github.com/scikit-image/scikit-image/pull/2044. This should fix the issues here.

**Comment by soupault** [comment]
@jni what's the status of this? :trollface:

**Comment by ahojnnes** [comment]
This is fixed. Feel free to reopen.
