### ISSUE TITLE
allow tifffile.imsave to handle file/io objects

### ISSUE THREAD

**Issue by jwittenbach** [scikit-image/scikit-image#2045]
Currently, image saving in `sklearn.external.tifffile.imsave` only allows the user to supply the name of the file to which the image will be written. This precludes the possibility of writing to more general IO objects -- e.g. byte streams.

I would be interested in putting together a PR that allows the user to supply either a string or a file/io object to be written to, but I wanted to gauge interest and get some feedback before diving in.

**Comment by stefanv** [comment]
s/sklearn/skimage, but yes, go for it!

**Comment by jwittenbach** [comment]
Hah, my fingers betrayed me there =) But great, I'll put it together!

**Comment by stefanv** [comment]
A PR will go a long way to restoring our faith in your loyalty ;)​

**Comment by soupault** [comment]
Closed via #2046.
