### ISSUE TITLE
Functions' signatures are missing from the docs

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2047]
## Description
Following functions' signatures are missing from the documentation.

Solution could be the same as in https://github.com/scikit-image/scikit-image/issues/2005 .

Module `draw`:
- [x] http://scikit-image.org/docs/dev/api/skimage.draw.html#bezier-curve
- [x] http://scikit-image.org/docs/dev/api/skimage.draw.html#circle-perimeter
- [x] http://scikit-image.org/docs/dev/api/skimage.draw.html#circle-perimeter-aa
- [x] http://scikit-image.org/docs/dev/api/skimage.draw.html#ellipse-perimeter
- [x] http://scikit-image.org/docs/dev/api/skimage.draw.html#line
- [x] http://scikit-image.org/docs/dev/api/skimage.draw.html#line-aa
- [x] http://scikit-image.org/docs/dev/api/skimage.draw.html#polygon

Module `feature`:
- [x] http://scikit-image.org/docs/dev/api/skimage.feature.html#corner-moravec
- [x] http://scikit-image.org/docs/dev/api/skimage.feature.html#corner-orientations

Module `measure`:
- [x] http://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.points_in_poly
- [x] http://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.grid_points_in_poly

**Comment by JDWarner** [comment]
`points_in_poly` needs a public, pure-Python wrapper. That's the general fix; Sphinx doesn't pull the sig from Cython functions.

The `[source]` link is missing too, which will be fixed the same way.

**Comment by soupault** [comment]
I've updated the issue with the other cases. 

@JDWarner sorry, your comment is slightly out of the point now. :wink: .

**Comment by soupault** [comment]
xref https://github.com/scikit-image/scikit-image/issues/1323, https://github.com/scikit-image/scikit-image/pull/1432

**Comment by soupault** [comment]
To check (from https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt):
```
The function signature is normally found by introspection and displayed by the help function. For some functions (notably those written in C) the signature is not available, so we have to specify it as the first line of the docstring:

"""
add(a, b)

The sum of two numbers.

"""
```

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image/pull/2303.
