### ISSUE TITLE
compare_ssim calls deprecated structural_similarity when using multichannel=True

### ISSUE THREAD

**Issue by asztrajman** [scikit-image/scikit-image#2048]
## Description
When calling skimage.measure.compare_ssim with multichannel=True the function calls the deprecated structural_similarity, which produces the following warning (times the number of channels):
/usr/local/lib/python2.7/dist-packages/skimage/measure/_structural_similarity.py:224: skimage_deprecation: Call to deprecated function ``structural_similarity``. Use ``compare_ssim`` instead.

Skimage version: 0.12.3
Python version: 2.7

**Comment by JDWarner** [comment]
Thanks for the report, @asztrajman. 

Really thought I got all of the uses of `structural_similarity`... and I think I did, in other files. Quite embarrassing I missed this instance in the function itself!

I'll sort this out today.

**Comment by JDWarner** [comment]
Actually, I can't find any uses of `structural_similarity` in this function. The recursive call is to `compare_ssim` [in this line](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_structural_similarity.py#L105). Are you using a fully up to date version?

**Comment by soupault** [comment]
@JDWarner as far as dive into it, may also I ask you to change [dtype in the docstring](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_structural_similarity.py#L33) to boolean? The current one is really weird.
Thanks in advance!

**Comment by asztrajman** [comment]
That's exactly it, in my version (0.12.3) that line calls to structural_similarity. Thanks!

**Comment by soupault** [comment]
@asztrajman could the issue be closed then?

**Comment by aeslaughter** [comment]
I am having this issue with the following code, using scikit-image 0.12.3 on python 2.7.11 (installed with miniconda on OSX):

```
#!/usr/bin/env python
import matplotlib.pyplot as plt
import skimage.measure

file0 = 'gold/simple.png'
file1 = 'simple.png'

image0 = plt.imread(file0)
image1 = plt.imread(file1)

print skimage.measure.compare_ssim(image0, image1, multichannel=True)
```

**Comment by ndamclean** [comment]
This issue still exists in the most recent tagged release of skimage (0.12.3). When will there be a new release with this fix?

**Comment by soupault** [comment]
@ndamclean not yet, not yet... You can watch our schedule at https://github.com/scikit-image/scikit-image/milestone/6. (By the way, we are always happy to see new contributors, who is eager to speedup the development cycle. :wink:)

**Comment by halehawk** [comment]
I got the warning whenever calling skimage.measure.compare_ssim with multichannel=True. Is it possible to disable the warning?
scikit-image 12.1.3
python 2.7.8

**Comment by soupault** [comment]
@halehawk what kind of warning? Also, please, specify the correct `skimage` version of your environment.

**Comment by halehawk** [comment]
Here is the deprecation message I got whenever I called compare_ssim:
/glade/apps/opt/scikit-image/12.1.3/gnu/4.8.2/lib/python2.7/site-packages/skimage/measure/_structural_similarity.py:224: skimage_deprecation: Call to deprecated function ``structural_similarity``. Use ``compare_ssim`` instead.

I used skimage 0.12.3

**Comment by soupault** [comment]
@halehawk that is already fixed via https://github.com/scikit-image/scikit-image/commit/5ac3255065f69a07d15080ac1e98536afde07de1.
You should wait for the new release, or use `dev` version instead.

**Comment by halehawk** [comment]
Is there an easy way to install dev version?

**Comment by soupault** [comment]
@halehawk I see nothing complicated - http://scikit-image.org/docs/dev/install.html#running-the-development-version . :wink:

**Comment by halehawk** [comment]
Great. Thanks.
