### ISSUE TITLE
problem with ImageCollection

### ISSUE THREAD

**Issue by ProgRoman** [scikit-image/scikit-image#2050]
## Description

I have a problem with the ImageCollection when used own loader function
## Way to reproduce

Python version

> Python 2.7.11 |Anaconda custom (64-bit)|  
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
> scikit-image              0.12.3              np110py27_0

I have the following code

```
import cPickle as pickle
import numpy as np

import skimage.io as io
from skimage.color import rgb2gray
from skimage.transform import resize

IMAGE_SIZE = 96

def transformImage(f):
        img = io.imread(f)
        img_gray = rgb2gray(img)        
        im_res = resize(img_gray,(IMAGE_SIZE,IMAGE_SIZE))

        return im_res

if __name__ == "__main__":
    img_collections = io.ImageCollection('/home/user/work/pic/cars/*.jpg',load_func=transformImage)
        img_collections[1].shape

```

I receive the following message

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/anaconda2/lib/python2.7/site-packages/skimage/io/collection.py", line 260, in **getitem**
>     **kwargs)
> TypeError: transformImage() got an unexpected keyword argument 'img_num'

if remove own  load_func(=transformImage) then everything works correctly

**Comment by blink1073** [comment]
@ProgRoman, as a workaround, you can change your function definition to `transformImage(f, image_num=None)` for now, but this is a bug on our end.

**Comment by JDWarner** [comment]
This isn't a bug, it's correct documented behavior.

```
For files with multiple images, the images will be flattened into a list
    and added to the list of available images.  In this case, ``load_func``
    should accept the keyword argument ``img_num``.
```

**Comment by blink1073** [comment]
It is a bug in that it should not be required.  We can detect the `TypeError` and call the function without an `img_num`.

**Comment by soupault** [comment]
@JDWarner but those are regular .jpg, aren't they? I tend to agree with @blink1073

**Comment by ProgRoman** [comment]
> you can change your function definition to transformImage(f, img_num=None) for now, but this is a bug on our end. 
Thank you! After the fixes to transformImage(f, img_num=None) it works!
