### ISSUE TITLE
A error happens when it's executes Local binary pattern method several times

### ISSUE THREAD

**Issue by rockbass2560** [scikit-image/scikit-image#2051]
## Description
Hi, I got an error when I execute the local binary pattern method into a for instruction. The error appears randomly and its description is **Buffer not C contiguous.**

The next code contains the code line with the error. I left part of the code so that you can take context.

  ```
          for (x, y, w, h) in faces[:1]:
                roi = img[y:y + h, x:x + w] #Region de interes
                eyes = eye_cascade.detectMultiScale(roi)
                for (ex, ey, ew, eh) in eyes[:2]: #Primeros dos elementos
                    roi_eye = roi[y:ey+eh,x:ex+ew]

                    #Here is the problem.
                    lbp = feature.local_binary_pattern(roi_eye, 8, 1,'uniform')


                    hist = np.histogram(lbp.ravel())
                    labels.append(emocion)
                    data.append(hist)

                mouths = mouth_cascade.detectMultiScale(roi,3,5)
                for (mx,my,mw,mh) in mouths[:1]: #Primer Elemento
                    roi_mouth = roi[y:my+mh,x:mx+mw]

                     #Here is the problem.
                     lbp = feature.local_binary_pattern(roi_mouth, 8, 1,'uniform')


                    hist = np.histogram(lbp.ravel())
                    labels.append(emocion)
                    data.append(hist)
```

Technical Info.
Windows 10 64 bits Microsoft [Versión 10.0.10586]
Python 2.7.11
scikit-image version 0.12.3

Thanks for your help.

**Comment by soupault** [comment]
@rockbass2560 it doesn't seem related to `skimage`.

**Comment by rockbass2560** [comment]
The error occurs with this code line:
feature.local_binary_pattern(roi_eye, 8, 1,'uniform')

So where I should put this error, I need to work and the library only inform:
Buffer not C contiguous.

**Comment by soupault** [comment]
@rockbass2560 ok, if you are sure, I'd like to ask you to prepare _minimal_ example which reproduces the error. No `cv2`, `sklearn`, etc and with some dummy data included.
Could you manage to do that, please?

**Comment by rockbass2560** [comment]
I'm going to edit the info.

**Comment by soupault** [comment]
I'm actually surprised you're getting this error on `local_binary_pattern`, because there is an [explicit call to get contiguous array](https://github.com/scikit-image/scikit-image/blob/401c1fd9c7db4b50ae9c4e0a9f4fd7ef1262ea3c/skimage/feature/texture.py#L295). 
Looking forward to seeing the shortened example.

**Comment by rockbass2560** [comment]
I edited the info, If you need more information please let me know. I'm surpised too... :(

**Comment by soupault** [comment]
@rockbass2560, interesting unpacking here:
```
for (ex, ey, ew, eh) in eyes[:2]: #Primeros dos elementos
```
Should be `eyes[:1]`, I suppose.

To debug, you could catch exception in `feature.local_binary_pattern` and print the values of `w, ew, y, ey, h, eh, x, ex`, `roi_eye.size` and `roi_eye.shape` when it occurs. This should help a lot.

**Comment by rockbass2560** [comment]
Ok, I will reviews the values, by the way, reviewing I found out this info. Apparently the error happens after np.ascontiguousarray is called.
![screenshot_5](https://cloud.githubusercontent.com/assets/2618632/14652676/96a09a54-0632-11e6-9bd3-81f4ca1ce9ed.png)

**Comment by rockbass2560** [comment]
I need 2 eyes. I used roi_eye.size directly I don't know if it is right.

The values are:

x:177, y:274, w:342, h:342
ex:198, ey:120, ew:63, eh:31, roi_eye.shape:(0, 84), roi_eye.size:0
ex:73, ey:119, ew:63, eh:32, roi_eye.shape:(0, 0), roi_eye.size:0
mx:92, my:256, mw:80, mh:40

**Comment by soupault** [comment]
@rockbass2560 so, basically, you're passing empty arrays to `local_binary_pattern`.
That should raise more meaningful error, but the results shouldn't differ.

**Comment by rockbass2560** [comment]
You're right, It seems I'm guilty so that I repaired the images, thanks for your time.

**Comment by stefanv** [comment]
Egor, will you please file an issue so we can fix the poor error message?

**Comment by soupault** [comment]
@stefanv Done, see https://github.com/scikit-image/scikit-image/issues/2053 .

**Comment by soupault** [comment]
@rockbass2560 glad you've figured everything out!
