### ISSUE TITLE
`min_size` is not strictly conformed in the implementation of felzenszwalb

### ISSUE THREAD

**Issue by mljli** [scikit-image/scikit-image#2056]
## Description
With `min_size` specified, there're still some segments with sizes that less than it. I don't know if it is an inherent flaw of the algorithm.

## Way to reproduce

    >>> I = skimage.io.imread('dragonbaby.jpg')
    >>> fz = felzenszwalb(I, scale=300, sigma=0.8, min_size=80)
    >>> (fz==9).sum()
    1

![dragonbaby](https://cloud.githubusercontent.com/assets/7010007/14789864/39cd4a56-0ad4-11e6-88a4-235ebdd1e2fd.jpg)

**Comment by mljli** [comment]
I have compared the output with that of Felzenszwalb's code, definitely there's a bug in the skimage's implementation.

**Comment by soupault** [comment]
Hi @mljli !
Thank you for reporting! We'll be happy if you decide to go for a PR with the fix :wink: .

**Comment by mljli** [comment]
@soupault I've found the problem. Current implementation processes each channel separately and then merges their results. It's the merging criterion that breaks the `min_size` constraint. I wonder if there's a clean solution without rewriting all the code.

**Comment by soupault** [comment]
@mljli Sounds reasonable. Are you aware of any recommendations from literature?

**Comment by jmetz** [comment]
Thought implementing the "official" multi-channel version might be a good way to go: implemented this here : #2088

**Comment by jmetz** [comment]
By "official" above I meant instead of operating on the channels independently (as implemented before, and in the 2004 version of Felzenszwalb's algorithm), using the 2006 update e.g.: https://github.com/cvjena/Felzenszwalb-Segmentation/blob/master/segment-image.h
