### ISSUE TITLE
Website does not show version number correctly

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#2066]
See http://scikit-image.org/, in the sidebar.
![screenshot](https://cloud.githubusercontent.com/assets/134307/14982774/fcd6cb2a-1138-11e6-8d9a-d19a6393c3e3.jpg)

**Comment by stefanv** [comment]
Do you ha email Javascript enabled? Did the load get interrupted?

**Comment by JDWarner** [comment]
I can reproduce.

**Comment by ahojnnes** [comment]
I guess it's this error message:
```
Refused to execute script from 'http://pypi.python.org/pypi/scikit-image/json?callback=jQuery11110477365951010035_1462340119020&_=1462340119021' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
```

**Comment by ahojnnes** [comment]
*Chrome 50.xx under OSX.

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image-web/pull/32.
