### ISSUE TITLE
difference between sigma and kernel_size in quickshift

### ISSUE THREAD

**Issue by stamaimer** [scikit-image/scikit-image#2068]
kernel_size : float, optional (default 5)

        Width of Gaussian kernel used in smoothing the sample density. Higher means fewer clusters.

        sigma : float, optional (default 0)

        Width for Gaussian smoothing as preprocessing. Zero means no smoothing.

And i saw `sigma controls the scale of the local density approximation` in [Comparison of segmentation and superpixel algorithms](http://scikit-image.org/docs/dev/auto_examples/plot_segmentations.html).

But i saw `Kernel size. The pixel density and its modes are estimated by using a Parzen window estimator with a Gaussian kernel of the specified size (vl_quickshift_set_kernel_size). The larger the size, the larger the neighborhoods of pixels considered.` in [Quick shift image segmentation](http://www.vlfeat.org/api/quickshift.html)

**Comment by noahstier** [comment]
ksize refers to the size of the kernel in pixels. Larger ksize means larger window for convolution.

sigma refers to the parameter sigma in the gaussian function, which controls the width of the bell curve independently from the size of the filter window.

Examples:

![20-5](https://cloud.githubusercontent.com/assets/7936971/15694165/29d8b7dc-2750-11e6-8c48-4f1bc758e0cc.png)
![20-10](https://cloud.githubusercontent.com/assets/7936971/15694164/29d56500-2750-11e6-8396-7c24140285df.png)
![30-10](https://cloud.githubusercontent.com/assets/7936971/15694166/29dc4bd6-2750-11e6-89d7-7ab839b08bfd.png)
