### ISSUE TITLE
Direct new users to HTTPS, remove all mention of SSH from getting started guide.

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#2079]
I strongly feel we should direct new contributors to HTTPS and remove all mention of SSH from the new contributor guide. I don't care if SSH is the "right" way, this is one place where we want the "easy" way. It's a getting started guide, not a reference.

Git itself is plenty for new contributors to wrap their heads around. No need to force them to dive into SSH keys as well. Every additional barrier we raise before their first PR is another place potential contributors will get frustrated and give up. We should remove every unnecessary barrier, and this one is 100% unnecessary.

**Comment by jni** [comment]
Mmm, I'm not sure about this one. I always start SWC git lessons by getting people up to speed with SSH, because if there's anything more annoying than setting up keys, it's typing your password in over and over and over. Perhaps what we should do is direct them to the Github GUI client?

**Comment by JDWarner** [comment]
No, please lets not direct to the GUI. It's not cross platform, and the entire interface is a moving target.

Typing in a password may be annoying to you and I, @jni, but that's because when you go down this road you end up pushing tens of commits per day.

For a new contributor, this is expected behavior for a web service. Set up a new account, get prompted for a password. When writing these things, we have to put ourselves in the shoes of someone completely new to Git and distributed development. They've got a neat idea, modification, or patch - that's it.

I'm perfectly fine with footnoting SSH, or saying there's a way for _more advanced contributors_ to remove the need to enter their passwords repeatedly. But that should be downplayed and not the course we guide them on. I'm going to stand firm on this one: SSH has no place in the getting started guide. This is a _new_ contributor guide, it should be _minimal_ in scope.

**Comment by emmanuelle** [comment]
+1 for putting first the "easy" option. Lowering the entry barrier would be at no cost here, since it doesn't affect scikit-image, just the contributing process.

**Comment by soupault** [comment]
Although I think this is a superfluous optimization, I'm with Josh on it. GitHub manual on setting up SSH keys is far from perfect and one usually has to dive into cryptography basics to understand the reasoning behind and set all things up.
On the other hand, I'm with Stefan regarding the educational side. If we prefer new contributors to use API over SSH, we shouldn't remove the mention of alternative approach.
To sum up, :+1: from me to Josh's idea on footnoting the SSH option.
BTW, the detailed manual already has corresponding references (see http://scikit-image.org/docs/dev/gitwash/forking_hell.html). Perhaps, we should consider making it more easily available.

The question I'd actually ask is 'how to lower the code barrier?'. Simplification of the contributor's guide is, in my opinion, not the right way to increase the number of people who contribute to the project. I suppose, that people are more scared of the large codebase they are unfamiliar with.

**Comment by stefanv** [comment]
I am ok with the footnote. It may be good to include a screenshot of where
to find the url on GitHub (which should show users with ssh keys the ssh
address by default).

**Comment by vighneshbirodkar** [comment]
I was wondering if a guide like this might be helpful
https://github.com/sightmachine/SimpleCV/wiki/Dev-Guide

It certainly helped me with my first Open Source contribution
