### ISSUE TITLE
skimage.feature.canny(im)

### ISSUE THREAD

**Issue by SaeedIqbal** [scikit-image/scikit-image#2081]
I am running the following code:
```
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi
from skimage import feature


# Generate noisy image of a square
im = np.zeros((128, 128))
im[32:-32, 32:-32] = 1

im = ndi.rotate(im, 15, mode='constant')
im = ndi.gaussian_filter(im, 4)
im += 0.2 * np.random.random(im.shape)

# Compute the Canny filter for two values of sigma
edges1 = features.corner(im)
edges2 = features.canny(im, sigma=3)

# display results
fig, (ax1, ax2, ax3) = plt.subplots(nrows=1, ncols=3, figsize=(8, 3), sharex=True, sharey=True)

ax1.imshow(im, cmap=plt.cm.jet)
ax1.axis('off')
ax1.set_title('noisy image', fontsize=20)

ax2.imshow(edges1, cmap=plt.cm.gray)
ax2.axis('off')
ax2.set_title('Canny filter, $\sigma=1$', fontsize=20)

ax3.imshow(edges2, cmap=plt.cm.gray)
ax3.axis('off')
ax3.set_title('Canny filter, $\sigma=3$', fontsize=20)

fig.subplots_adjust(wspace=0.02, hspace=0.02, top=0.9,
                    bottom=0.02, left=0.02, right=0.98)

plt.show()
```

and python shell I faced the the below error:

edges1 = features.corner(im)
NameError: name 'features' is not defined

How can I resolve the above mentioned issue, Kindly help me.

Python 2.7.6 and 3.5.1 
and scikit-image version is 0.9.3.

**Comment by soupault** [comment]
@SaeedIqbal hi!
The error is speaking for itself, there is no module `features` in `skimage`, neither there is a function `corner`.
I'd suggest you to search through the documentation once again for the fix. For futher questions on usage of `skimage`, please, consider using stackoverflow.com and add `scikit-image` tag to your questions - some of core team members do monitor that as well.

Closing this as not an issue of `skimage`.

**Comment by JDWarner** [comment]
Note that you imported and aliased skimage.feature to  the name feature. You then must use that exact name, not the plural featureS, to access it.
