### ISSUE TITLE
please remove non-free lenna image

### ISSUE THREAD

**Issue by LocutusOfBorg** [scikit-image/scikit-image#2091]
Hi, you can see a reason for removing that image on the corresponding Debian bug report [1]
do you think you can replace that image with a more "open source" one?

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794859

thanks!

**Comment by stefanv** [comment]
This has already been fixed upstream.

**Comment by LocutusOfBorg** [comment]
oops, thanks then!

**Comment by LocutusOfBorg** [comment]
well @stefanv can I update the Debian package to the latest release? do you want to give me a dsc file?
I asked the maintainer of bug 823140 to fix the package, what is your opinion? do you have any stopper?

**Comment by stefanv** [comment]
I have been working on the Debian packaging, but it's not quite done.  If
you want to help, I'd be most grateful (you can find me online at
https://gitter.im/scikit-image/scikit-image )

My current Debian branch is here:

https://github.com/stefanv/scikit-image/tree/debian
