### ISSUE TITLE
Add description to RAG's merging example

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2099]
## Description
Add description to RAG's merging example or, at least, hide `TODO` from the public.

See [webpage](http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_boundary_merge.html#example-segmentation-plot-boundary-merge-py) or [source code](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/segmentation/plot_boundary_merge.py#L6) for some fun :).

**Comment by vighneshbirodkar** [comment]
Oh crap. I am guilty of that mistake.

**Comment by jni** [comment]
Me too! LOL #codereviewfail

**Comment by sciunto** [comment]
@vighneshbirodkar Would you like to make a PR with a text for that example?

**Comment by vighneshbirodkar** [comment]
@sciunto I'm making one right now

**Comment by vighneshbirodkar** [comment]
See 
https://github.com/scikit-image/scikit-image/pull/2106
