### ISSUE TITLE
DOC a note with references is not printed in the doc

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2101]
In measure/_ccomp.pyx, this note in the top of the file is not the built doc.

I noted that at two different places in that file, there is a comment above functions that refers to one of the references.
```
_ccomp.pyx:360:# Connected components search as described in Fiorio et al.
_ccomp.pyx:456:# Connected components search as described in Fiorio et al.
```

```See also:

  Christophe Fiorio and Jens Gustedt,
  "Two linear time Union-Find strategies for image processing",
  Theoretical Computer Science 154 (1996), pp. 165-181.

  Kensheng Wu, Ekow Otoo and Arie Shoshani,
  "Optimizing connected component labeling algorithms",
  Paper LBNL-56864, 2005,
  Lawrence Berkeley National Laboratory
  (University of California),
  http://repositories.cdlib.org/lbnl/LBNL-56864
```

I'm not sure what's the best thing to do.

**Comment by soupault** [comment]
@sciunto I believe the codebase needs a lot of refactoring and PEP-ifying besides this :). We could consider filling a meta-issue to collect all the shortcommings, like we the one we have for the gallery.

Regarding the issue, I'd prefer the following:
The reference block at the top of `measure/_ccomp.pyx` should be added to `def label(...)` docstring. Numpy docstrings have a standard of doing this ([see section 11. References](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections)).
Function `_label` should have little to no docsting. Everything significant has to be presented in the docsting of `label`.

Commentary strings in front of the functions' definitions have to be removed:
https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_ccomp.pyx#L360
https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_ccomp.pyx#L456

**Comment by sciunto** [comment]
@soupault I made some code maintenance in #2100. flakes didn't see much PEP8 mistakes on my side though.

Let me know if it looks good or not.

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image/pull/2100.
