### ISSUE TITLE
circles aren't rounded well...

### ISSUE THREAD

**Issue by jamesbondo** [scikit-image/scikit-image#2112]
So i was trying this: 
[draw a circle](https://github.com/scikit-image/scikit-image/blob/master/skimage/draw/draw.py#L19)
with these code:

```
import numpy as np
from skimage.draw import circle
img = np.zeros((32, 32), dtype=np.uint8)
rr, cc = circle(16, 16, 15)
img[rr, cc] = 1
print img
import matplotlib.pyplot as plt
plt.imshow(img,cmap='gray',vmin=0,vmax=1, interpolation = 'nearest')
plt.show()
```

It seems there's too much horizontal area on the mid of each edge.. This happens when the total pixel number is small. Hope someone can take a quick look.

**Comment by stefanv** [comment]
I think this line:

https://github.com/scikit-image/scikit-image/blob/master/skimage/draw/draw.py#L16

Should be `<= 1`?  What do you think.

**Comment by soupault** [comment]
@jamesbondo @stefanv that does help:

| before | after |
|:-------------:|:-------------:|
| ![figure_1](https://cloud.githubusercontent.com/assets/1315589/15648993/bfcae8bc-2676-11e6-9ffa-2e515d70f997.png) | ![figure_2](https://cloud.githubusercontent.com/assets/1315589/15648994/c10b9a14-2676-11e6-841b-c5ea90b441e5.png) |

**Comment by jamesbondo** [comment]
Nice! Well done!


发自 网易邮箱大师
On 05/30/2016 19:58, Egor Panfilov wrote:

@jamesbondo@stefanv that does help:

| before | after |
| | |

**Comment by soupault** [comment]
@jamesbondo would you like to submit a PR?

**Comment by stefanv** [comment]
I wonder if there is a better algorithm for circles? For drawing with aa,
we also have
http://scikit-image.org/docs/dev/api/skimage.draw.html#skimage.draw.circle_perimeter_aa

**Comment by jamesbondo** [comment]
@stefanv 
aa still have the problem i think...
```
from skimage.draw import circle_perimeter_aa
img = np.zeros((32, 32), dtype=np.uint8)
rr, cc, val = circle_perimeter_aa(15, 15, 14)
img[rr, cc] = val * 255
plt.imshow(img,cmap='gray',vmin=0,vmax=1, interpolation = 'nearest')
plt.show()
```
the out side has too much straight area..
@soupault not sure how to do a PR... i didn't change the code so it won't be helpful if I do it?.. maybe @stefanv  can do it really quick?

**Comment by soupault** [comment]
@jamesbondo that is a drawing function for anti-aliased (which is usually non-binary) circle. You should remove `vmin` and `vmax` parameters from the call: `plt.imshow(img, cmap='gray', interpolation='nearest')`.

If you're interested about PR submission, we have quite an [awesome guide](http://scikit-image.org/docs/dev/contribute.html) on how to contribute to the project.

**Comment by jmetz** [comment]
@soupault, @jamesbondo 
@stefanv 's test code just contained a minor bug (setting `vmax` to 1), if you use the following you get a nice anti-aliased circle with no straight lines... 

import matplotlib.pyplot as plt
import numpy as np
from skimage.draw import circle_perimeter_aa
img = np.zeros((32, 32), dtype=np.uint8)
rr, cc, val = circle_perimeter_aa(15, 15, 14)
img[rr, cc] = val * 255
plt.imshow(img,cmap='gray',vmin=0,vmax=255, interpolation = 'nearest')
plt.show()

**Comment by soupault** [comment]
@jmetz I've pointer out the same thing. Either way, the question is about `circle`, not `circle_perimeter_aa`, isn't it?

**Comment by jmetz** [comment]
oops - apologies, should have read your last comment more closely!
Regarding `circle` vs `circle_perimeter_aa` - true - though as `circle` is not supposed to be anti-aliased given that it returns coordinates, I think the implementation is accurate and the OP is asking for something else, though I'm not clear as to what.

**Comment by jmetz** [comment]
Perhaps this should be relabelled as an enhancement, an re-titled to reflect the desire for an anti-aliased `draw.circle` analogue?

**Comment by soupault** [comment]
> I think the implementation is accurate and the OP is asking for something else, though I'm not clear as to what.

Mmm... So you're saying that the left one is correct, aren't you? https://github.com/scikit-image/scikit-image/issues/2112#issuecomment-222477195

**Comment by soupault** [comment]
> I think the implementation is accurate and the OP is asking for something else, though I'm not clear as to what.

@jmetz Mmm... So you're saying that the left one is correct, aren't you? https://github.com/scikit-image/scikit-image/issues/2112#issuecomment-222477195

**Comment by jmetz** [comment]
The left and right ones are generated by pretty much the same code, ie changing the radius to 15 + 1E-16 should achieve the same result for the original code, so whether it's `<` or `<=` doesn't really change the issue the OP seems to be concerned about...

**Comment by soupault** [comment]
@jmetz Sorry, I cannot see any implicit issue OP is talking about.

> changing the radius to 15 + 1E-16 should achieve the same result
No doubts, but it is all about defaults and expected behaviour. I'd suggest to submit that tiny fix and forget about this. :)

**Comment by jamesbondo** [comment]
shall we close?
