### ISSUE TITLE
Seed not defined in test_rank causes tests to randomly fail

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2113]
In `skimage/filters/rank/tests/test_rank.py`, many tests do not have a fixed seed, so they can fail  randomly (just happened to me).

TODO: Check if it could also happen elsewhere

**Comment by stefanv** [comment]
Good catch!  Let's set those seeds.

**Comment by stefanv** [comment]
I saw the discussion in #2100.  Is setting the seed at the top of the file not enough?  These tests are not being run in parallel, AFAIK.

**Comment by sciunto** [comment]
You meant #2098? 

I guess you are right. If it doesn't run in parallel, it should be fine. However, I'm wondering if for maintenance, it's not better to define a seed for each test. For instance, what would happen if we insert a new test in the middle of the suite?

**Comment by stefanv** [comment]
The seed should be set in a fixture, ie in a `def setup`.

**Comment by sciunto** [comment]
I see.

**Comment by sciunto** [comment]
But, in `skimage/filters/rank/tests/__init__.py`, _shared.testing.setup_test() is called...
