### ISSUE TITLE
not clearly description of label bbox in documentation

### ISSUE THREAD

**Issue by kuzkokov** [scikit-image/scikit-image#2116]
Hello.
So, I use bboxes of founded labels to create their copies and put them side by side with original ones. And it wasn't obviosly for me (as for newbie) that bbox's (max_row, max_col) is actually (max_row + 1, max_col + 1), as I found out in sources.

(How I thought | How it is)
![image](https://cloud.githubusercontent.com/assets/12381291/15632936/2097571a-25ba-11e6-942d-ebb5d72554b3.png)

So I think it would be nice to clarify this in the docs.

Also, maybe you should add something like bbox_area in region properties. I know about label.image.size, but it not obvious to.
Thanks.

**Comment by sciunto** [comment]
Regarding your first point, would this statement makes things clearer?

```
-        Bounding box ``(min_row, min_col, max_row, max_col)``
+        Bounding box ``(min_row, min_col, max_row, max_col)``.
+        Pixels belonging to the bounding box are in ``[min_row; max_row[``
+        and ``[min_col; max_col[``.
```

See #2100

**Comment by kuzkokov** [comment]
I guess, it's better to change second "[" to ")", like in half-closed interval.

**Comment by sciunto** [comment]
They are both the same: https://en.wikipedia.org/wiki/Interval_%28mathematics%29#Including_or_excluding_endpoints

**Comment by jni** [comment]
@sciunto although both notations are equivalent, in the context of monospace fonts and coding, `[a, b[` is more likely to return a `SyntaxError` from my brain's parser than `[a, b)`. Would you mind updating #2100 to this alternative notation? I would also explicitly say "to the bounding box are in the half-open interval `[min_row, max_row)`, `[min_col, max_col)`".

**Comment by jni** [comment]
(ie add the words "the half-open interval", to prepare brain-embedded parsers. =P)

**Comment by sciunto** [comment]
@jni Oki, done.

**Comment by kuzkokov** [comment]
I agree with @jni 
Thanks, @sciunto :relieved:

And what about the bbox_area?

**Comment by sciunto** [comment]
About bbox_area, I think it's a good idea but I need to look more closely.
