### ISSUE TITLE
Slightly inconsistent function names in thresholding.py

### ISSUE THREAD

**Issue by nvdv** [scikit-image/scikit-image#2121]
I've noticed that names of the functions in `thresholding.py` do not fully reflect actions they perform: 
`threshold_adaptive` applies threshold to an image and others return calculated threshold. 
I can fix it if maintainers approve.

**Comment by sciunto** [comment]
I confirm. Even local `otsu` in rank filters return a threshold, not a thresholded image.

However, we need to break the API here but I think it's worth it.

**Comment by soupault** [comment]
:+1: for breaking API, but I strongly prefer to have a discussion first.

From my point of view, there are several considerations:

1. All functions on thresholding have to return the same kind of output, let's call it `THR`. Some of them may return tuple `(THR, ...)` if there is any important and/or useful extra information user would like to have;
2. `THR` has to be one of these two alternatives:

    A. integer/float which is used as _global_ threshold (`img > THR`), or numpy array of the same shape as input image (binarization also via `img > THR`) if the threshold values are computed using _local_ algorithms and therefore aren't always equal;
    B. copy of input image already thresholded (binary).
    I do prefer the first alternative, but we could let user choose between them using extra function argument. In any case, I think that returning the threshold number/array should be the preffered way (`return_threshold=True` by default).

**Comment by nvdv** [comment]
I'm not very familiar with underlying algorithms and API of `thresholding.py`, but I can suggest that all `threshold_*` functions will return threshold and `apply_threshold` function will apply resulting threshold.

**Comment by sciunto** [comment]
Just to bring food to the discussion, #2076 will return an array of threshold values.

**Comment by nvdv** [comment]
@sciunto it might also be handled by `apply_threshold` function

**Comment by alexandrejaguar** [comment]
Hi all, my two cents on that.
I believe each threshold function should behave as @soupault said in _2.B._: calling a function should be, for instance, `thresh_image, thresh_value = threshold_*(image, arguments)`. Thinking on that, I have a consideration: implementing another function (such as `apply_threshold()`) or another argument (`return_threshold=...`)  would bring more complication to the end user.

**Comment by stefanv** [comment]
@alexandrejaguar I think that API would be more consistent than the one we currently have, and I would support us moving in that direction.

**Comment by jni** [comment]
Two notes:

- Whatever final API we have, I strongly support returning the actual threshold (in addition to the thresholded image, or not). There are many uses for the actual threshold value. For example, a user might want to find the average threshold value over many images (too many to hold in memory).
- Although I agree that we should break the API and be consistent, we definitely need to use the usual two-release deprecation cycle for this. Extrapolating from my own use, thresholding functions are among the most used in skimage. It would be chaos to break the API with no deprecation warning.

**Comment by sciunto** [comment]
If I try to summarize, we need
* to deprecate API of functions that do not return the threshold for 0.13 and change the return value for 0.15
* write a `apply_threshold` function that takes an image and a threshold, milestone 0.15. Eventually, we can implement it now, but keep it hidden because it won't work for all functions we have so far.

**Comment by sciunto** [comment]
Another idea. Should we make a distinction between local and global threshold names? The list is growing and it becomes difficult to distinguish. Suggestion: keep `threshold_*` for global ones, and `local_threshold_*` for the others.

**Comment by jni** [comment]
👎 for local_threshold. The main point of the threshold_ prefix is to enable autocompletion, which local_ breaks.

**Comment by sciunto** [comment]
Or `threshold_local_*` or we leave as it is.

**Comment by alexandrejaguar** [comment]
Hi all,
please don't add another function for returning image thresholds. Couldn't we implement functions returning the thresholds and the resulting images? It would be done with small effort (and it would avoid blowing the TK with somewhat unnecessary functions).
Again, just a humble opinion :)

**Comment by sciunto** [comment]
I think I do not understand your comment at all @alexandrejaguar

**Comment by alexandrejaguar** [comment]
@sciunto, repeating the last comment:
* I believe each threshold function should behave as @soupault said in 2.B.: calling a function should be, for instance:
`thresh_image, thresh_value = threshold_*(image, arguments)`.
* Another function (such as `apply_threshold()`) or another argument (`return_threshold=`) would bring more complication to the end user.

**Comment by sciunto** [comment]
Your solution is a big jump in term of API breakage. I'm not sure I want that.

**Comment by sciunto** [comment]
@scikit-image/core We need to take a decision before 0.13.

**Comment by alexandrejaguar** [comment]
@sciunto I continue being against creating another function/argument to solve this issue. My opinion remains as on the last comment.
About the API breakage: I believe some "homogeneity" would be nice; there are functions which use the same variables, but with different names, or different position in the arguments. I believe if we pursue a strong API, we will need the break some stuff eventually (better sooner than later).

**Comment by blink1073** [comment]
I'm in favor of `thresh_image = threshold_*(image, arguments, return_threshold=False)`, with a deprecation warning attached to the existing functions that currently not return an image.

**Comment by jni** [comment]
I'm strongly in favor of option 2A in @soupault's original [comment](https://github.com/scikit-image/scikit-image/issues/2121#issuecomment-223235076): all functions return a value `t` that can be used as `im > t` to obtain the thresholded image.
