### ISSUE TITLE
skimage._shared tests not run

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#2127]
Our skimage._shared tests are not run using "make test". After a quick look, I couldn't figure out how to fix this.

**Comment by sciunto** [comment]
Looks like the explanation is here: https://stackoverflow.com/questions/23615924/nosetests-discover-code-in-test-folder

Hardcoded in nose to skip directories starting by an underscore. https://github.com/nose-devs/nose/blob/00ae0930e3bfad41279a0899e8c699f2ac1ff209/nose/loader.py#L164

**Comment by soupault** [comment]
@sciunto great catch!

**Comment by sciunto** [comment]
I tried last time to find a workaround but nothing worked for me as far as I remember...

**Comment by sciunto** [comment]
Upstream suggests a switch to nose2. Won't be fix in nose1.  

Any comment on this?

**Comment by soupault** [comment]
Looks good to me if it is fully functional and stable.

**Comment by soupault** [comment]
I've given `nose2` a deep look, and would say that it is not yet ready (e.g. many plugins are missing).
If we decide to move onto `nose2` there is also a lot of work to do as it is not compatible with `nose` in terms of config and usage practices.

**Comment by jni** [comment]
@soupault why nose2 and not pytest? Pytest runs nose tests out of the box.

**Comment by soupault** [comment]
@jni Hmm, ok. I'll evaluate it as well.

**Comment by sciunto** [comment]
Thanks for looking at this @soupault  That's precious :)

**Comment by soupault** [comment]
Closed via #2468.
See https://travis-ci.org/scikit-image/scikit-image/jobs/221129994#L6322-L6341 for the confirmation.
