### ISSUE TITLE
rgb2gray duplicates rgb2gray in v0.12

### ISSUE THREAD

**Issue by korvin14** [scikit-image/scikit-image#2133]
I was playing with scikit functions and noticed, that in **color** module there are two same function **rgb2gray** and **rgb2grey** with similar description and functionality. Is it made just for convenience to write gray\grey?)

PS. in v0.13dev these functions exist as well.

**Comment by soupault** [comment]
@korvin14 Yes, it is indeed so. If you look through the source code, you will notice that those functions don't add any superfluous code (see https://github.com/scikit-image/scikit-image/blob/master/skimage/color/colorconv.py#L744).
