### ISSUE TITLE
Add rotation to `draw.ellipse`

### ISSUE THREAD

**Issue by jmetz** [scikit-image/scikit-image#2135]
Update the `draw.ellipse` function to optionally take an angle e.g. `theta` (defaults to 0) which specifies the angle between the major axis and the x-axis.

**Comment by sciunto** [comment]
Cc @alexandrejaguar

**Comment by alexandrejaguar** [comment]
Hi all,
I checked that `skimage.draw.ellipse_perimeter()` has the `orientation` argument implemented. However, that function is implemented in Cython...
Let me see if I can implement that.

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image/pull/2366.
