### ISSUE TITLE
Normal estimation of depth image

### ISSUE THREAD

**Issue by wkentaro** [scikit-image/scikit-image#2138]
## Description

Is that possible to support depth image processing in scikit-image?
I'd like to add normal estimation code for depth image.

The implementation with opencv is provided here:
http://answers.opencv.org/question/82453/calculate-surface-normals-from-depth-image-using-neighboring-pixels-cross-product/

**Comment by soupault** [comment]
@wkentaro Hi! Thanks for your interest!
I'm not speaking for the whole team, but I think that at the moment we're lacking algorithms which could benefit from using this routine. If you have something in mind to justify this addition, feel free to put it forward.

**Comment by wkentaro** [comment]
@soupault Thank you for the quick reply.
I usually use scikit-image for visualization and mask operation for object recognition/segmentation with machine learning.
Recently I'm going to work for object recognition using depth image, and firstly implementing normal estimation as the most popular approach.
There are also other features proposed by some papers, and hope these are available from one place (I mean from scikit-image).

- Normal feature
  - [implementation](http://answers.opencv.org/question/82453/calculate-surface-normals-from-depth-image-using-neighboring-pixels-cross-product/)
- HHA feature
  - [implementation](https://github.com/s-gupta/rcnn-depth/blob/master/rcnn/saveHHA.m)
  - [paper](http://people.eecs.berkeley.edu/~sgupta/pdf/rcnn-depth.pdf)
- Jet colormap feature
  - [implementation](http://matplotlib.org/examples/color/colormaps_reference.html)
  - [paper](http://arxiv.org/pdf/1507.06821v2.pdf)

**Comment by sciunto** [comment]
The normal feature looks really interesting to me, and I can imagine plenty of applications in my research.

**Comment by stefanv** [comment]
This falls squarely in the computer vision territory, so I'm considering this out-of-scope for now.  @scikit-image/core please re-open for discussion if you disagree.
