### ISSUE TITLE
Gaussian filter does not have default value for sigma

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#2147]
Most functions of ``scikit-image`` have only one non-keyword argument, which is an input image, and all other arguments are optional keyword arguments. I would suggest that we make the ``sigma`` parameter of ``filters.gaussian`` optional (eg with the default value of 1), for more consistency between functions. In addition, having only one non-kw parameter, which is an image, makes introspection and testing easier.

What do you think?

**Comment by emmanuelle** [comment]
And I would also add a default value for the ``selem`` parameter of ``filters.median``.

**Comment by stefanv** [comment]
That sounds good to me.
​

**Comment by jni** [comment]
:+1: ! I thought we already had a default selem for median!

**Comment by soupault** [comment]
:+1: from me as well.
@jni which one should be default, `disk` or `square`?

**Comment by emmanuelle** [comment]
I think it should be square for the median filter, that s what people usually do

**Comment by ahojnnes** [comment]
+1 for square.
