### ISSUE TITLE
Unusual output when reading image - MpoImagePlugin

### ISSUE THREAD

**Issue by AbdealiJK** [scikit-image/scikit-image#2154]
## Description
I was trying to read the image at https://commons.wikimedia.org/wiki/File:JoeSimpson2012.JPG using `skimage.io.imread`. The [docs](http://scikit-image.org/docs/dev/api/skimage.io.html#skimage.io.imread) mention that the output will be an ndarray with the different colour bands/channels stored in the third dimension, such that a grey-image is MxN, an RGB-image MxNx3 and an RGBA-image MxNx4.

When doing this, I found that the output was a ndarray with 2 items. The first item has the ndarray mentioned in the docs, the second was an array whose repr gave: `array(<PIL.MpoImagePlugin.MpoImageFile image mode=RGB size=4320x3240 at 0xAC4FDF4C>, dtype=object)`.

## Way to reproduce
Here's a minimal example:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import (division, absolute_import, unicode_literals,
                        print_function)

import os
from shutil import copyfileobj

try:
    from urllib2 import urlopen
except ImportError:
    from urllib.request import urlopen

from skimage.io import imread

def download(url, filename, overwrite=False):
    if not os.path.exists(filename) or overwrite:
        response = urlopen(url)
        with open(filename, 'wb') as out_file:
            copyfileobj(response, out_file)

download('https://upload.wikimedia.org/wikipedia/commons/e/ea/JoeSimpson2012.JPG',
         'JoeSimpson2012.JPG')

im = imread('JoeSimpson2012.JPG')
print('Shape of image data', im.shape)
print('Second element is an array with:', im[1])
print(im)
```

Note that `im[0]` is the output I was expecting. And it does work with other images I've used.

Versions:
 - scikit-image 0.12.3
 - python v2.7.11 (From Miniconda)
 - pip 8.1.1
 - numpy 1.11.0
 - Pillow 1.1.7

**Comment by stefanv** [comment]
Thanks, I can confirm this behavior.  While we look into fixing it, load
the image using

io.imread('filename.jpg', plugin='matplotlib')

**Comment by stefanv** [comment]
Turns out this is a multiple object JPEG.  Trying to figure out why the
second JPEG did not get decoded.​

**Comment by stefanv** [comment]
After digging around a bit, I saw that this is a two layer image, but when
you try to access the second layer you see:

*** OSError: image file is truncated (0 bytes not processed)

**Comment by stefanv** [comment]
![00](https://cloud.githubusercontent.com/assets/45071/16141234/3dbad08a-340e-11e6-98b8-40ecbe284200.jpg)
![01](https://cloud.githubusercontent.com/assets/45071/16141235/3dc992aa-340e-11e6-9e6c-5d72fd6bd3a9.jpg)

Here are the two layers as Pillow extracts them.  It looks like the second layer is a thumbnail of the first, but I'm not sure PIL knows how to handle it (perhaps because it's a different size?).

Either way, this is probably not a problem we'll be able to fix in scikit-image; please report to Pillow.

You can include the following code snippet:

```
>>> image = Image.open('/tmp/JoeSimpson2012.JPG')
>>> image.seek(1)
>>> image.getdata()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-ed29e097bae2> in <module>()
----> 1 image.getdata()

/usr/lib/python3/dist-packages/PIL/Image.py in getdata(self, band)
   1137         """
   1138 
-> 1139         self.load()
   1140         if band is not None:
   1141             return self.im.getband(band)

/usr/lib/python3/dist-packages/PIL/ImageFile.py in load(self)
    216                         else:
    217                             raise IOError("image file is truncated "
--> 218                                           "(%d bytes not processed)" % len(b))
    219 
    220                     b = b + s

OSError: image file is truncated (0 bytes not processed)
```

**Comment by AbdealiJK** [comment]
@stefanv Thanks for the analysis :+1: Created the issue in Pillow at https://github.com/python-pillow/Pillow/issues/1960

Also, don't you think the error should have been raised by `skimage` or the error by `Pillow` should have been allowed to be raised ?
I was expecting a grey/RGB/RGBA image - and the output I got was unexpected. Hence, the behavior is contrary to the documentation.

PS: Although this argument will become invalid if/when Pillow solves the issue.

**Comment by stefanv** [comment]
I do agree with you.  The strange thing that happens here is that the call
to `array(frame)` succeeds, despite the internal error in PIL.  I guess we
could try and issue a ``.getdata`` before converting the frame to an
array--I'm not sure if that's the "standard" protocol, but at least we'll
catch the error.  I'm open to suggestions on how to handle this situation
better.

**Comment by AbdealiJK** [comment]
@stefanv I'm not very sure how to solve it either - maybe doing a `.getdata()` would be a good idea as you suggested ?
On the Pillow issue it was concluded that the image was faulty. Hence, there should be an error when trying to read it.

Although I'm not sure of the best solution on how to implement it, Could we reopen this so that others can find the issue and comment on it too ?
