### ISSUE TITLE
Three segfaults testing scikit-image

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2163]
@matthew-brett discovered the following

https://travis-ci.org/scikit-image/scikit-image-wheels/builds/138974413

We should file a separate issue for each, but I'm noting them here for now.

**Comment by matthew-brett** [comment]
Segfaults on Python 2 and Python 3.  Another example of segfault, on Python 3:

https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/147798535#L1206

There are also test failures in 32-bit runs without segfaults - new issue at #2224

**Comment by soupault** [comment]
Duplicate of #2527, #2528, #2529.
