### ISSUE TITLE
No ValueError when using rgb2grey with 4D arrays

### ISSUE THREAD

**Issue by AbdealiJK** [scikit-image/scikit-image#2167]
## Description
I seem to have found another unusual behaviour with the `skimage.color.rgb2grey()`. When I read the file [File:123_Numbers.gif](https://commons.wikimedia.org/wiki/File:123_Numbers.gif), it is read correctly and gives an array of shape `(3, 146, 124, 3)`. But when I do a `rgb2grey()` it gives me an array of shape `(3, 146, 3)`.

According to the documentation at [skimage.color.html#skimage.color.rgb2grey](http://scikit-image.org/docs/dev/api/skimage.color.html#skimage.color.rgb2grey) if I give `rgb2grey()` anything other than a 3D array with 3/4 channels (RGB or RGBA), it should give me a `ValueError`. But it seems to ignore the invalid dimension and still attempts to convert the image.

## Way to reproduce
Made a script to test this easily:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import (division, absolute_import, unicode_literals,
                        print_function)

import os
from shutil import copyfileobj

try:
    from urllib2 import urlopen
except ImportError:
    from urllib.request import urlopen

from skimage.io import imread
from skimage.color import rgb2grey

def download(url, filename, overwrite=False):
    if not os.path.exists(filename) or overwrite:
        response = urlopen(url)
        with open(filename, 'wb') as out_file:
            copyfileobj(response, out_file)

download('https://upload.wikimedia.org/wikipedia/commons/d/d7/123_Numbers.gif',
         '123_Numbers.gif')

image = imread('123_Numbers.gif')
print(image.shape)
grey_image = rgb2grey(image)
print(grey_image.shape)
```

Versions:
 - scikit-image 0.11.3
 - python v2.7.11 (From Miniconda)
 - pip 8.1.1
 - numpy 1.9.3
 - Pillow  PIL.VERSION = 1.1.7, PIL.PILLOW_VERSION = 3.2.9

**Comment by soupault** [comment]
@AbdealiJK Thanks for reporting!
On the latest stable `skimage` (`0.12.3`) your script returns:
```
(3, 146, 124, 3)
(3, 146, 124)
```

The documentation, in its turn, has to updated: `rgb2gray` declares to work with 3-D arrays (2-D images) only, but support 3-D/4-D arrays (2-D/3-D images), and actually can support arbitrary number of spatial dimensions.

Would you like to contribute on this?
