### ISSUE TITLE
Finding color space information about image

### ISSUE THREAD

**Issue by AbdealiJK** [scikit-image/scikit-image#2175]
## Description

I notice that currently after I read an image from skimage, there is no metadata that is further provided. For example, if I want to check if the image is greyscale or not, In Pillow I could do:

``` python
>>> im = Image.open('image.jpg')
>>> is_grey = lambda im: im.mode == 'L'
```

to make a function for checking if grey or not. In skimage, I'd have to do:

``` python
>>> im = skimage.io.imread('image.jpg')
>>> is_grey = lambda im: im.ndim == 2
```

But the ndim checkingmethods are not very nice because I may have a GIF file or TIFF file with multiple pages which is black and white - Making the `ndim == 3`.

Is there a better way to do this ? I found `skimage` does some similar dimension checking internally - https://github.com/scikit-image/scikit-image/blob/master/skimage/color/colorconv.py#L63

I was wondering whether it would be possible for `skimage` to expose helper functions to use Pillow's (or the plugin's) mode checking (Which [uses header info and so on to detect the color space](https://github.com/python-pillow/Pillow/blob/d3727b523ece4f75def72bfc960e1abd104b5dcb/PIL/JpegImagePlugin.py#L146))

**Comment by soupault** [comment]
@AbdealiJK yes, that is a well known issue. See the following related pages: https://github.com/scikit-image/scikit-image/issues/1940, https://github.com/scikit-image/scikit-image/pull/1995.

The discussion in https://github.com/scikit-image/scikit-image/pull/1995 is still open, feel free to contribute to it.

**Comment by soupault** [comment]
Another story is how to improve type/ndim checking, which we have almost everythere. And that one could be addressed via some kind of fused types - https://github.com/scikit-image/scikit-image/pull/2126#discussion_r66417179. I think we need to start a discussion some day on this as well. :)

**Comment by stefanv** [comment]
scikit-image operates on numpy arrays exclusively, so we have no way of knowing (independently of the underlying plugin used) metadata about the image.

I think we can extend all io plugins to have imread_metadata that returns both the image and any metadata  available, in a dictionary with well specified keys, which should solve the problem.

Any thoughts? /cc @jni

**Comment by soupault** [comment]
@stefanv yes, I think we've converged on this: https://github.com/scikit-image/scikit-image/pull/1995, https://github.com/scikit-image/scikit-image/pull/2240#issuecomment-257805997. I'll prepare SKIEP on this soon as the topic is being raised over and over again.

**Comment by jni** [comment]
@stefanv I think the goal is to outsource IO to imageio sometime soon. At that point, we can just do


```python
def imread(x, **kwargs):
    return np.array(imageio.imread(x, **kwargs), copy=False)

def imread_meta(x, **kwargs):
    im = imageio.imread(x, **kwargs)
    return np.array(im, copy=False), im.meta
```

and forget about "plugins"...

**Comment by stefanv** [comment]
See https://github.com/scikit-image/scikit-image/issues/2709
