### ISSUE TITLE
rgb2hsv and hsv2rgb can convert ubyte -> float, but docs say it assumes float

### ISSUE THREAD

**Issue by AbdealiJK** [scikit-image/scikit-image#2183]
## Description
The code of `rgb2hsv()` and `hsv2rgb()` [on master](https://github.com/scikit-image/scikit-image/blob/master/skimage/color/colorconv.py#L237) uses the `_prepare_colorarray()` function which has `return dtype.img_as_float(arr)`. Hence, the input image is converted to float when needed. Currently, the docs at http://scikit-image.org/docs/dev/api/skimage.color.html say:

```
Notes:
The conversion assumes an input data range of [0, 1] for all color components.
```
Which is invalid, as it can also accept ubyte.

**Comment by soupault** [comment]
Closed via #2354.
