### ISSUE TITLE
Thresholding examle has wrong histogram

### ISSUE THREAD

**Issue by hirschbeutel** [scikit-image/scikit-image#2186]
# Description
The histogram in the thresholding example using Otsu's method should be calculated on the flatten image. The example can be found at the following link:
[http://scikit-image.org/docs/dev/auto_examples/plot_otsu.html
](url)

## Way to reproduce
Run the python code:
[http://scikit-image.org/docs/dev/_downloads/plot_otsu.py](url)

line 25:
ax2.hist(image) -> ax2.hist(image.flatten())

**Comment by soupault** [comment]
@hirschbeutel thanks for reporting! Would you like to submit a fix?

**Comment by hirschbeutel** [comment]
I would like to submit a fix. could you give me some directions how to do
that, since this is my first bug report?

2016-07-13 10:33 GMT+02:00 Egor Panfilov <notifications@github.com>:

**Comment by soupault** [comment]
Actually, nevermind. :)
`plot_otsu.py` was removed with https://github.com/scikit-image/scikit-image/pull/2110.
Actual version of the example is already fixed and available as http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_thresholding.html.

`plot_otsu.py` has to be removed in accordance with https://github.com/scikit-image/scikit-image/issues/2059 .

Closing.

**Comment by JDWarner** [comment]
@hirschbeutel if you would like to submit fixes or improvements in the future, we have a [step-by-step guide for new contributors](http://scikit-image.org/docs/stable/contribute.html#development-process) available. It will walk you through the process of making your first PR, when ready!
