### ISSUE TITLE
compare_ssim - Is result mssim always a float ?

### ISSUE THREAD

**Issue by AbdealiJK** [scikit-image/scikit-image#2201]
## Description
In http://scikit-image.org/docs/0.12.x/api/skimage.measure.html#skimage.measure.compare_ssim it says that the output `mssim` can be a float or a ndarray. But in the code, I see [L114](https://github.com/scikit-image/scikit-image/blob/068663b7fe30573250e256962d447bfb0e8e7862/skimage/measure/_structural_similarity.py#L114) output and [L204](https://github.com/scikit-image/scikit-image/blob/068663b7fe30573250e256962d447bfb0e8e7862/skimage/measure/_structural_similarity.py#L204) finds the `.mean()` of the mssim. before returning So, it would always be a float right ?

**Comment by jni** [comment]
@AbdealiJK I think you are absolutely right! Would you like to submit a PR to fix the docstring?

**Comment by soupault** [comment]
Closed via #2218.
