### ISSUE TITLE
restoration.unwrap_phase could take dtype into account for default wrapping period

### ISSUE THREAD

**Issue by anntzer** [scikit-image/scikit-image#2213]
Currently, `restoration.unwrap_phase` uncondtionally casts its data to double and uses a period of `[-pi, pi]`.  I'd argue that when the input type is an integer type, this is probably never the expected behavior; especially for "small" integer types ((u)int{8,16}), the "correct" period is probably just the span of the dtype (so 0..255 for uint8, etc).  So I'd suggest
- if the input dtype is one of uint8, int8, uint16, int16: use the span of the dtype as period, return an image of the "next" dtype (so uint8->uint16, etc.) (this can overflow if there are more than 256 wraps in an image but I expect this to be unlikely in practice?  also this can always be worked around by switching to the second point)
- if the input dtype is a 32 or 64 bit integer, or floating, cast to double and proceed as before (one could argue that (u)int32 should fall under the first point, I don't really care either way).
  The alternative would be to provide a "period" kwarg to, well, indicate the period, but we'd still need dtype upcast rules anyways and I think these are sensible defaults (and the previous behavior can always be recovered with an explicit cast to double).

**Comment by stefanv** [comment]
All this code was written with phase wrapping on +- pi in mind.  Yes, the code can be extended to do what is suggestion, but I'd argue that that is an entirely new feature.  If we receive a PR, we can review, but for now this is not a high priority.
