### ISSUE TITLE
docstring of equalize_adapthist does not show the default kernel size

### ISSUE THREAD

**Issue by anntzer** [scikit-image/scikit-image#2214]
See http://scikit-image.org/docs/dev/api/skimage.exposure.html#skimage.exposure.equalize_adapthist
I guess both kernel_size and ntiles_{x,y} default to None so that both APIs stay present.  Unfortunately, this has the effect of hiding the default kernel size.

**Comment by soupault** [comment]
@anntzer thanks!
I'd add to this couple one request more: sort the function parameters in the same order they are presented in the docstring or vise versa.

**Comment by soupault** [comment]
@emmanuelle hi! do you have any ideas why the generated URL for the `[source]` link in http://scikit-image.org/docs/dev/api/skimage.exposure.html#equalize-adapthist points at `adapt_rgb.py` file? I mean, it is probably related to a decoration of the function (https://github.com/scikit-image/scikit-image/blob/master/skimage/exposure/_adapthist.py#L27). but is there anything we can do about this?

**Comment by kjacks21** [comment]
@soupault wouldn't the default `kernel_size` depend on the input `image`? How should this be represented in the docstring?

https://github.com/scikit-image/scikit-image/blob/c7f386b955bb32f19716598613a296178ace1ddd/skimage/exposure/_adapthist.py#L84-L88

**Comment by soupault** [comment]
@kjacks21 one could add a short summary of https://github.com/scikit-image/scikit-image/blob/c7f386b955bb32f19716598613a296178ace1ddd/skimage/exposure/_adapthist.py#L87-L88 to `Parameters -> kernel_size` section of the docsting.

**Comment by kjacks21** [comment]
I can submit a PR for this, though I'm not sure how to address the URL for `[source]` pointing to `adapt_rgb.py`.

**Comment by soupault** [comment]
@kjacks21 sure, feel free to sumbit!
As for the link, I'll raise a separate issue. Have to check if this appears somewhere else.

**Comment by anntzer** [comment]
@soupault: missed your comment, I already opened the issue as #2221.

As an additional doc improvement, it may be worth explaining how the clip_limit kwarg (in [0, 1] similarly to MATLAB's implementation (http://www.mathworks.com/help/images/ref/adapthisteq.html) is related to the >=1 clim limit as defined by Wikipedia (https://en.wikipedia.org/wiki/Adaptive_histogram_equalization), OpenCV (http://docs.opencv.org/master/d5/daf/tutorial_py_histogram_equalization.html#gsc.tab=0) and most of the literature I've found so far.

**Comment by soupault** [comment]
Closed via #2220.
