### ISSUE TITLE
docs link to decorator rather than function itself

### ISSUE THREAD

**Issue by anntzer** [scikit-image/scikit-image#2221]
e.g. http://scikit-image.org/docs/dev/api/skimage.exposure.html#equalize-adapthist
the `[source]` link goes to the `adapt_rgb` decorator: https://github.com/scikit-image/scikit-image/blob/master/skimage/color/adapt_rgb.py#L35

A quick test locally suggests that at least Sphinx 1.4.5 on Python 3.5.2 is able to link to the inner decorator object instead.

**Comment by sciunto** [comment]
We can test against different sphinx version. Nevertheless, if the latest sphinx versions have a correct behavior, I would say that we can drop this issue as fixed by upstream. As time goes, it's gonna to be fixed by itself (`self.fix()` :) ).

**Comment by soupault** [comment]
xref https://github.com/scikit-image/scikit-image/issues/1813

**Comment by grlee77** [comment]
I just noticed this and came across this existing issue, so it seems the problem persists. It occurs for  the decorators `change_default_value` and `deprecate_kwarg` as well.

An example from the current dev docs for a function using `@change_default_value`:
https://scikit-image.org/docs/dev/api/skimage.color.html#skimage.color.label2rgb
where the [source] link goes to: https://github.com/scikit-image/scikit-image/blob/master/skimage/_shared/utils.py#L61

Fortunately, the places where those decorators are used aren't very extensive.

**Comment by lagru** [comment]
I think it's possible to solve this by patching 
https://github.com/scikit-image/scikit-image/blob/86c1d5e8bb06f17830f35f66692a69a14e9315fb/doc/source/conf.py#L395
with [`inspect.unwrap`](https://docs.python.org/3/library/inspect.html#inspect.unwrap) similar to this to [this example](https://gitlab.com/tud-mst/ptvpy/-/blob/0e1dce0389088004b4da69a2a95e6d70fbbc245d/doc/conf.py#L223-224).
