### ISSUE TITLE
Salt and Pepper noise yields possibly wrong result

### ISSUE THREAD

**Issue by LukasDrude** [scikit-image/scikit-image#2222]
## Description
I investigated salt and pepper noise (from ``skimage.util.random_noise``) with a few small input sizes. The results differ from what I expected for black-and-white images.

## Way to reproduce
``` python
import numpy as np
from skimage.util import random_noise
print(random_noise(np.zeros((2, 3)), mode='salt', amount=1.0))
```

Yields:
```
[[ 1.  1.  0.]
 [ 0.  0.  0.]]
```

But I expected salt everywhere (ones everywhere).
``` python
print(random_noise(np.ones((2, 3)), mode='pepper', amount=1.0))
```

Yields:
```
[[ 0.  0.  1.]
 [ 1.  1.  1.]]
```

But I expected pepper everywhere.

Same holds for larger images. I.e.
``` python
print(np.sum(random_noise(np.zeros((1000, 1000)), mode='salt', amount=1.0)))
```

Yields:
```
632022.0
```

whereas I expected 1M.

Reshaping an arbitrary image yields a ``ValueError``, although the intermediate result is two-dimensional.
``` python
print(random_noise(np.zeros((2, 3, 4)).reshape(1, -1), mode='salt', amount=1.0))
```

Yields:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-175-57dba4fbf87a> in <module>()
----> 1 print(random_noise(np.zeros((2, 3, 4)).reshape(1, -1), mode='salt', amount=1.0))

/net/ssd/software/anaconda/envs/py35/lib/python3.5/site-packages/skimage/util/noise.py in random_noise(image, mode, seed, clip, **kwargs)
    159         # Re-call function with mode='s&p' and p=1 (all salt noise)
    160         out = random_noise(image, mode='s&p', seed=seed,
--> 161                            amount=kwargs['amount'], salt_vs_pepper=1.)
    162 
    163     elif mode == 'pepper':

/net/ssd/software/anaconda/envs/py35/lib/python3.5/site-packages/skimage/util/noise.py in random_noise(image, mode, seed, clip, **kwargs)
    175             kwargs['amount'] * image.size * kwargs['salt_vs_pepper'])
    176         coords = [np.random.randint(0, i - 1, int(num_salt))
--> 177                   for i in image.shape]
    178         out[coords] = 1
    179 

/net/ssd/software/anaconda/envs/py35/lib/python3.5/site-packages/skimage/util/noise.py in <listcomp>(.0)
    175             kwargs['amount'] * image.size * kwargs['salt_vs_pepper'])
    176         coords = [np.random.randint(0, i - 1, int(num_salt))
--> 177                   for i in image.shape]
    178         out[coords] = 1
    179 

mtrand.pyx in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:14492)()

ValueError: low >= high
```

My ``skimage.__version__`` is 0.11.3.b

**Comment by jni** [comment]
Ah, that's an off-by-one error on randint. I can confirm that this happens on master, too.

In addition to the off-by-one error, the way that we are generating S&P noise is incorrect. With a probability of 1.0, we say, "generate `image.size` coordinates at random, then replace those with 1s". Of course the problem is that generating that many random coordinates results in repeated coordinates, and we end up replacing ~2/3 of the coordinates at random, on average. For small probabilities this doesn't matter, which is probably why it's gone unnoticed for so long.

@LukasDrude thanks for the report! Fix upcoming! =)

**Comment by JDWarner** [comment]
If you hadn't already fixed this, @jni, I'd have taken care of my own mess ;) - this is my fault from the SciPy 2013 sprints.
