### ISSUE TITLE
Problem with references and sphinx (warning treated as error)

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2237]
We have repeatedly observed some problems with sphinx and travis. This issue gathers the messages...

Relevant issues:
- #2211
- #2141
- #2010 (upd @soupault)

**Comment by sciunto** [comment]
For #2211, @jni said:

@sciunto the problem is that the docs build correctly on my machine... =\

**Comment by sciunto** [comment]
For #2211 @sciunto said:

@jni I can reproduce:
```
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user_guide/viewer
<autosummary>:1: WARNING: citation not found: R314
<autosummary>:1: WARNING: citation not found: R373
generating indices... genindex py-modindex
writing additional pages... search

```


@jni looks like it's solved by applying this:

```
diff --git a/skimage/morphology/watershed.py b/skimage/morphology/watershed.py
index 639182f..e67742c 100644
--- a/skimage/morphology/watershed.py
+++ b/skimage/morphology/watershed.py
@@ -133,7 +133,7 @@ def _compute_neighbors(image, structure, offset):
 
 def watershed(image, markers, connectivity=1, offset=None, mask=None,
               compactness=0):
-    """Find watershed basins [1]_ in `image` flooded from given `markers`.
+    """Find watershed basins in `image` flooded from given `markers`.
 
     Parameters
     ----------
@@ -154,7 +154,7 @@ def watershed(image, markers, connectivity=1, offset=None, mask=None,
         Array of same shape as `image`. Only points at which mask == True
         will be labeled.
     compactness : float, optional
-        Use compact watershed [3]_ with given compactness parameter.
+        Use compact watershed with given compactness parameter.
         Higher values result in more regularly-shaped watershed basins.
 
     Returns
@@ -172,7 +172,7 @@ def watershed(image, markers, connectivity=1, offset=None, mask=None,
 
     Notes
     -----
-    This function implements a watershed algorithm [1]_ that apportions pixels
+    This function implements a watershed algorithm that apportions pixels
     into marked basins. The algorithm uses a priority queue to hold the pixels
     with the metric for the priority queue being pixel value, then the time of
     entry into the queue - this settles ties in favor of the closest marker.

```

**Comment by sciunto** [comment]
@sciunto said:

@jni Please, have a look to this: https://travis-ci.org/sciunto/scikit-image/jobs/150032649  (a commit for #2236). You'll see what I meant about weird errors on references. Here, i didn't touch to pyramid at all... Do you agree with me that's unexpected?
I think that sphinx-gallery causes that. Any idea how to report this?

**Comment by sciunto** [comment]
For #2211 @jni said:

@sciunto, @stefanv and I are trying to get to the bottom of this... There appears to be an error in reference renumbering. I checked out numpydoc and sphinx and used `pdb.set_trace()` to try to get to the bottom of it. My current problem is that sphinx is *very heavyweight*, objects everywhere, and I don't really know where to look now. But:

- numpydoc:
```
> /Users/jni/projects/numpydoc/numpydoc/numpydoc.py(89)mangle_docstrings()
-> for r in references:
(Pdb) p line
'.. [3] Peer Neubert & Peter Protzel (2014). Compact Watershed and'
(Pdb) p lines[i]
'.. [R314] Peer Neubert & Peter Protzel (2014). Compact Watershed and'
```

Sphinx:

```
(Pdb) p doctree.document.document
<document: <comment...><section "module: morphology"...>>
(Pdb) p doctree.document.citations
[<citation "r315": <label...><paragraph...>>, <citation "r316": <label...><paragraph...>>, <citation "r317": <label...><paragraph...>>, <citation "r318": <label...><paragraph...>>, <citation "r319": <label...><paragraph...>>, <citation "r320": <label...><paragraph...>>, <citation "r321": <label...><paragraph...>>, <citation "lee94": <label...><paragraph...>>, <citation "r322": <label...><paragraph...>>, <citation "r323": <label...><paragraph...>>, <citation "r324": <label...><paragraph...>>]
(Pdb) p doctree.document.citations[0]
<citation "r315": <label...><paragraph...>>
(Pdb) p doctree.document.citations[0].astext()
'R315\n\nhttp://blogs.mathworks.com/steve/2011/10/04/binary-image-convex-hull-algorithm-notes/'
(Pdb) p doctree.document.citations[-1].astext()
'R324\n\nPeer Neubert & Peter Protzel (2014). Compact Watershed and\nPreemptive SLIC: On Improving Trade-offs of Superpixel Segmentation\nAlgorithms. ICPR 2014, pp 996-1001. DOI:10.1109/ICPR.2014.181\nhttps://www.tu-chemnitz.de/etit/proaut/forschung/rsrc/cws_pSLIC_ICPR.pdf'
```

As you can see, somewhere in between the reference indices were offset by 10. I haven't narrowed things down yet.

Incidentally, sphinx master caused an error; I had to check out the 1.4.1 tag. Something to look out for.

**Comment by sciunto** [comment]
travis build: https://travis-ci.org/scikit-image/scikit-image/builds/150230844
PR: #2141 

As observed by @jni, travis fails but I can't reproduce on my machine with sphinx 1.4.5, 1.4.2 and 1.4.1.
Procedure for each trial:
```
cd doc && make clean && make install
```

**Comment by sciunto** [comment]
Another thing I just observed on travis. Another PR #2238. First run, all tests failed and I saw that it was for references. I restarted the tests and they are passing now.

**Comment by JDWarner** [comment]
This has the sound of a race condition, perhaps? Is there a way to locally emulate a Travis container?

**Comment by soupault** [comment]
Unfortunately, this doesn't seem to be closed via #2257. I've seen a case of this today on a branch rebased on `master`.

**Comment by sciunto** [comment]
I've seen that also. Nevertheless, I tend to see it less.

**Comment by jni** [comment]
Agreed with @soupault and @sciunto . Interestingly, for [this build](https://travis-ci.org/scikit-image/scikit-image/builds/158437798), *all* the individual builds failed with a duplicate reference error, then, upon restarting, *all* the builds worked. So the effect might be due to the availability of some external resource? Dunno. Weird. =(

CC @stefanv

**Comment by soupault** [comment]
I think I've got a clue. It seems to appear in PRs which fall behind the `master` in terms of new docstring references.
Travis is probably configured to cache the old reference list, and this leads to some collisions when some PR is merged into `master` without being preliminary rebased onto it. Clicking `Restard Build` in Travis web-UI seems to wipe this cache.

**Comment by jni** [comment]
@soupault you just blew my mind.

**Comment by soupault** [comment]
@jni :face_with_head_bandage: 
Let me try to visualize (I remember you like ASCII):
```
master
   |
   o--------o
   |\        \
   | \ PR#1   \ PR#2
   |  o        o
   |  |        |	
   |  |        |
   | [+] new   |
   | [b] refs  |
   |  |       [c]
   |  |       [b]
   |  o        |
   | /         | 
   |/          |
  [m]          |
  [b]          |
   |          [c]
   |          [b] ERROR#1
   |           |
   |           o
   |          /
   |         /
  [m]-------o
  [b] ERROR#2
   |
  [B] OK!
   |

 o  - nothing, just a visual sugar :)
[c] - commit without change of references
[+] - commit with the addition/change of reference
[m] - merge
[b] - CI automatically triggered build
[B] - CI manually triggered build
```

`ERROR#1` happens as the cached list of references (in Travis container or somewhere) is different (with the addition of a new one *into the middle* of list, not at the end), and some reference numbers from `master` and `PR#2` collide, i.e.
```
`master` with PR#1 merged (goes to cache):
[R1-articleA][R2-articleB]***added[R3-articleD]***[R4-articleC]

PR#2
[R1-articleA][R2-articleB][R3-articleC]
```
I'm not sure how exactly our CI handles this case. From my point of view, it probably uses a cached version and overwrites the references presented in `PR#2`.

`ERROR#2` happens as we use `Create merge commit` button for merging PRs, not `Rebase and merge`. If the PR branch is rebased before merge, everything should work fine (IMO).

**P.S. All of the above is just an assumption and must not be used against myself in a court of law.**

**Comment by jni** [comment]
@soupault Oh, sorry, I understood the first time, I just thought it was clever, out-of-the-box thinking as to what could be causing it, and it is certainly plausible that it could happen!

Nice ASCII though! ;)

**Comment by soupault** [comment]
JFYI:
I've tried to force `doc` directory cleanup before the build changing https://github.com/scikit-image/scikit-image/blob/master/tools/travis_script.sh#L26 to
```
export SPHINXCACHE=$HOME/.cache/sphinx; make -C doc clean; make html
```
Unfortunately, the results is the same - see the failing build in https://travis-ci.org/soupault/scikit-image/builds/199918037

**Comment by soupault** [comment]
I haven't seen this one or a long time, just saying :v:.

**Comment by sciunto** [comment]
good point! I'm closing. Please, issue 2237, sleep tight.
