### ISSUE TITLE
Incorrect use of `dynamic_range` name

### ISSUE THREAD

**Issue by norok2** [scikit-image/scikit-image#2245]
The term `dynamic range` is often improperly used in the field of image processing as an extension to the usage in audio signal processing. This problem also appears in `scikit-image`.

From https://en.wikipedia.org/wiki/Dynamic_range the dynamic range of a value is:

```
max(values interval) / min(values interval)
```

while most of the functions in scikit-image actually want:

```
abs(max(values interval) - min(values interval))
```

For sound signals, which are often expressed in decibel, the max - min definition is an acceptable extension (because the logarithm function used to define the decibel maps ratios to differences). For images, and in general for mathematical objects whose values are not defined in logarithmic terms, this nomenclature is less appropriate.

Therefore, I would suggest to change the scikit-image nomenclature from `dynamic_range` to one of: 
- `values_interval_size`: that would be the exact (but long) name
- `values_interval`: shorter; `interval` is often used as a synonym of `interval_size`
- `peak_to_peak`: quite clumsy to me, but consistent with `numpy` (i.e. `numpy.ptp`)

**Comment by soupault** [comment]
Hi @norok2! Thank you for your detailed proposal!
I'd be in favour of `values_interval` or `values_range`. Sad part is that we have to deprecate.
Would you like to submit a PR for this?

**Comment by norok2** [comment]
Besides the deprecation (which I would need some hints on how you normally handle this) I can certainly submit a pull request with the refactoring soon.

**Comment by sciunto** [comment]
+1 with the global idea and +1 for `values_range`.

For the deprecation procedure, you can get inspiration from https://github.com/scikit-image/scikit-image/pull/2228

**Comment by norok2** [comment]
I am afraid that https://github.com/scikit-image/scikit-image/pull/2228 is not really applicable here, because I see no way of supporting both at the same time without changing the signature, unless all callables involved do make use of the *args/**kwargs magic (which does not seem to be the case).

**Comment by soupault** [comment]
@norok2 You can see an example of similar deprecation in https://github.com/scikit-image/scikit-image/blob/master/skimage/restoration/_denoise.py#L11-L114 (`sigma_range` and `sigma_color`). Pretty much the same case.

**Comment by norok2** [comment]
Ok, thanks. This can be done easily, I was just thinking that this approach can still break some code out there in the wild :-)

**Comment by stefanv** [comment]
@jni I would appreciate your input on this one.

**Comment by jni** [comment]
@stefanv thanks for the ping but I don't have a strong opinion. I quite like @JDWarner's suggestion in #2384 of `data_range`.

**Comment by soupault** [comment]
Addressed by https://github.com/scikit-image/scikit-image/issues/2245.
