### ISSUE TITLE
Remove unused `_shared.extend_image`

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2249]
## Description
I propose to remove `extend_image` (https://github.com/scikit-image/scikit-image/blob/master/skimage/_shared/interpolation.pyx#L12), as it duplicates the behaviour of `skimage.util.pad`, and it is not really used anywhere (https://github.com/scikit-image/scikit-image/search?utf8=%E2%9C%93&q=extend_image).

**Comment by jni** [comment]
👍 ! It probably predates pad but now is definitely superseded by it.
