### ISSUE TITLE
filters.frangi fails with default parameters on Py3

### ISSUE THREAD

**Issue by jmetz** [scikit-image/scikit-image#2250]
When running the documentation example for the Frangi, fails because of default parameters to `frangi` **on Python 3**. Note this is fine on Python 2. 

```
Traceback (most recent call last):
  File "sktest.py", line 15, in <module>
    ax[1].imshow(frangi(image), cmap=plt.cm.gray)
  File "skimage/filters/_frangi.py", line 119, in frangi
    beta1, beta2)
  File "skimage/filters/_frangi.py", line 47, in _frangi_hessian_common_filter
    (Dxx, Dxy, Dyy) = hessian_matrix(image, sigma)
  File "skimage/feature/corner.py", line 154, in hessian_matrix
    mode=mode, cval=cval)
  File "/usr/lib/python3/dist-packages/scipy/ndimage/filters.py", line 292, in gaussian_filter
    sigmas = _ni_support._normalize_sequence(sigma, input.ndim)
  File "/usr/lib/python3/dist-packages/scipy/ndimage/_ni_support.py", line 63, in _normalize_sequence
    normalized = list(input)
TypeError: 'numpy.int64' object is not iterable
```
## Reproducing

Copy and run the official example: http://scikit-image.org/docs/dev/auto_examples/filters/plot_frangi.html

**Comment by soupault** [comment]
@jmetz Could you elaborate more on your setup? Works well for me on Py3:
```
In [6]: np.version.full_version
Out[6]: '1.11.1'
In [7]: scipy.version.full_version
Out[7]: '0.18.0'
In [8]: skimage.__version__
Out[8]: '0.13dev'
In [9]: %run test.py
In [10]: 
```

**Comment by jmetz** [comment]
I get 
```
1.11.1
0.13.3
0.13dev
```
... so same Numpy and Scikit-Image, but older Scipy. 

Just updated Scipy and all works as expected. Thanks for the pointer!

**Comment by jni** [comment]
Well, our scipy requirement is >=0.10, so I'm reopening this until we either push up our requirement or fix the issue with older scipy... Thanks for the report @jmetz!

**Comment by sciunto** [comment]
We recently bumped numpy to 1.11, released on March '16. Scipy 0.10 was released on March '12. 

I'll open a PR to bump scipy as well.

**Comment by sciunto** [comment]
PR opened. :)

**Comment by JDWarner** [comment]
The discrepancy between Python 2 and 3 makes me suspect something like true/truncating first and SciPy second.

**Comment by soupault** [comment]
OK, so there was a pretty old bug in type checking, which had been fixed via https://github.com/scipy/scipy/commit/3035cd949a421992bdb1ec1191d8143d132ae0cb#diff-0b507ce41065ac7f08d6750cd439298bL60 right before `scipy 0.17` came out.

**Comment by JDWarner** [comment]
This is a very minor problem easily caught and worked around on our end. IMO that is the correct approach, rather than bumping our SciPy requirement by over 5 years.

**Comment by jni** [comment]
@JDWarner is this issue closed?

**Comment by soupault** [comment]
@jni not even close :wink:. You should take a look at https://github.com/scikit-image/scikit-image/pull/2264 - there is a whole lot of things to be fixed before we address this.

**Comment by sciunto** [comment]
To me, it doesn't look realistic to fix this for 0.13. What do you think?

**Comment by jni** [comment]
@sciunto what do you mean? The easy fix (bump scipy requirement) is trivial, and just requires a tight enough deadline to convince the doubters. =P

**Comment by sciunto** [comment]
@jni you said here: #2416 that bumping scipy is not an option of 0.13.

IMHO, the argument based on the release dates of numpy and scipy that I exposed in both PR are sufficient. Is it realistic that a distribution provides one of the last numpy and a 5 years old scipy? I don't think so.

**Comment by jni** [comment]
@sciunto ha, touché. Having said that, I was merely pointing out that there is resistance from some core devs (CC @emmanuelle @JDWarner) to bumping the scipy version. The resistance is *not* from me, and my guess is that the others might be more yielding if a critical bug such as this one was blocking release and was not easily fixable without the newer SciPy. I hope they can chime in here.

**Comment by stonebig** [comment]
is the next release date of scikit-image-0.13, January 15th 2017,  still plausible ? with all this legacy version of scipy to drag, I have doubts.

**Comment by jni** [comment]
@JDWarner @emmanuelle do you still object to bumping to 0.17? imho, given that we depend on np 1.11 anyway *and* that this is now one of the last remaining blockers for 0.13, I think we should make the leap. @scikit-image/core should also weigh in here. Otherwise @sciunto, @soupault, and I will probably make a quorum and "go rogue", so to speak. =P

**Comment by sciunto** [comment]
FYI, I reopened #2254 to do that. #2254

**Comment by sciunto** [comment]
@jni, looks like we can go ahead...
