### ISSUE TITLE
NumPy error when no descriptors are found in ORB

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#2253]
## Description

When you pass a blurry image to an ORB object's `detect_and_extract` method, and it finds no keypoints, it crashes with an error inside of `np.hstack` because `scales_list` is empty:

``` python
extractor_em.detect_and_extract(simlight)
```

``` pytb
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-37-caefda1c8359> in <module>()
----> 1 extractor_em.detect_and_extract(simlight8)

/Users/jni/conda/envs/ana3/lib/python3.5/site-packages/skimage/feature/orb.py in detect_and_extract(self, image)
    321         keypoints = np.vstack(keypoints_list)
    322         responses = np.hstack(responses_list)
--> 323         scales = np.hstack(scales_list)
    324         orientations = np.hstack(orientations_list)
    325         descriptors = np.vstack(descriptors_list).view(np.bool)

/Users/jni/conda/envs/ana3/lib/python3.5/site-packages/numpy/core/shape_base.py in hstack(tup)
    275     arrs = [atleast_1d(_m) for _m in tup]
    276     # As a special case, dimension 0 of 1-dimensional arrays is "horizontal"
--> 277     if arrs[0].ndim == 1:
    278         return _nx.concatenate(arrs, 0)
    279     else:

IndexError: list index out of range
```
## Way to reproduce

Using the image attached below, run:

``` python
from skimage import io, feature
im = io.imread('simlight.png')
extractor_im = feature.ORB(n_keypoints=50)
extractor_im.detect_and_extract(im)
```

**upd:** fixed code snippet /soupault

Affects skimage master. The problem is in [this `if` clause](https://github.com/scikit-image/scikit-image/blob/58e613e49677cf5a25d23abd6c13cf5ec0a880e0/skimage/feature/orb.py#L305), which updates all the necessary lists with empty arrays, _except_ `scales_list`.

![simlight](https://cloud.githubusercontent.com/assets/492549/17913343/af8b22b0-69dc-11e6-90de-269bbbe01178.png)

**Comment by jni** [comment]
Suggested fix: detect when no keypoints have been found at any level, and raise a `RuntimeError`, perhaps suggesting what kinds of features ORB likes to find.

**Comment by dgtlmoon** [comment]
Yes, from reading the documentation this also hit me.. it's quite hard to know that the image was too blurry

**Comment by JDWarner** [comment]
Closed by #2537

**Comment by janedoesrepo** [comment]
Is there a way to ignore this Runtime Error?

When processing many images it would be helpful to ignore the error and commence with the next image in the pipeline instead of aborting the run. opencv for example afaik returns an empty keypoint and descriptor list.

**Comment by hmaarrfk** [comment]
Can you use try except statements in your loop?
