### ISSUE TITLE
profile_line gives wrong output for a binary mask

### ISSUE THREAD

**Issue by gatagat** [scikit-image/scikit-image#2258]
## Description

As of now (skimage 0.12.3), profile_line sometimes returns wrong output for binary masks (np.array(dtype=bool)). See below for an example. If the image is cast to an uint8 first, it returns the expected result.

A possible patch might be even just specifying the allowed dtypes in the docstring.
## Way to reproduce

``` python
from numpy import meshgrid, pi, cos, sin, all, uint8
from skimage.measure import profile_line

shape = (200, 200)
center_x, center_y = (140, 150)
radius = 20
x, y = meshgrid(range(shape[1]), range(shape[0]))
mask = (y - center_y)**2 + (x - center_x)**2 < radius**2
src = (center_y, center_x)
phi = 4*pi/9.
dy = 31 * cos(phi)
dx = 31 * sin(phi)
dst = (center_y + dy, center_x + dx)

profile_uint8 = profile_line(mask.astype(uint8), src, dst)
print profile_uint8
assert all(profile_uint8[:radius] == 1)

profile_bool = profile_line(mask, src, dst)
print profile_bool
assert all(profile_bool[:radius] == 1) # Fails

assert all(profile_bool == profile_uint8) # Fails
```

The output is (there is a zero in the middle of the profile_line output):

```
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0. (ZERO HERE?!)  1.  1.
  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-24-1a94903a5586> in <module>()
     19 profile_bool = profile_line(mask, src, dst)
     20 print profile_bool
---> 21 assert all(profile_bool[:radius] == 1) # Fails
     22 
     23 assert all(profile_bool == profile_uint8) # Fails

AssertionError: 
```

**Comment by jmetz** [comment]
This is an issue with the `ndi.map_coordinates` call, and related to the order of the spine used. 
If `order` is set to `0`, the test passes.

**Comment by jni** [comment]
@jmetz that's a nice workaround, but I don't understand why the interpolation works better in that case...?

**Comment by jmetz** [comment]
@jni - I'm not sure about that either :/ poked around here : https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_interpolation.c#L358 as this is where I think the magic is happening, but can't figure out why `bool` should behave differently to `uint8`.

**Comment by stefanv** [comment]
@jmetz I believe you have stumbled upon a bug in ndimage.  If you are still interested, can you create a small test case, that illustrates something like:

```
In [59]: ndi.map_coordinates(mask.astype(np.uint8), perp_lines, order=1, cval=0)[:, 0]
Out[59]: 
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [60]: ndi.map_coordinates(mask, perp_lines, order=1, cval=0)[:, 0].astype(np.uint8)
Out[60]: 
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)
```

And then file it with scipy?

If you don't have time to do that, please let me know.

**Comment by jmetz** [comment]
Hey @stefanv - sure no problem, just filed the issue with Scipy. 

Please comment and improve the issue as needed : https://github.com/scipy/scipy/issues/7051

**Comment by rfezzani** [comment]
Using the `order=0` for the interpolation fixes the issue.
```python
>>> profile_bool = profile_line(mask, src, dst, order=0)
>>> print(profile_bool)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```
It seems reasonable when a boolean array is provided (what means interpolating between `True` and `False`?).
Should we set the order to 0 when input dtype is bool?
May I close or do you still consider this as a bug?
