### ISSUE TITLE
felzenswalb does not raise error when passed a 3D image

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#2267]
The current implementation of ``segmentation.felzenswalb`` is for 2D grayscale of RGB images only. However, it is possible to pass a 3D image to the function without an error being raised. This should be corrected in the short term. And of course, it would be great to write a 3-D compatible version of felzenswalb in the long term :-).

**Comment by sciunto** [comment]
@emmanuelle If you want to keep track of 3D for felzenswalb, I let you open another ticket ;)
