### ISSUE TITLE
problem with dtype float limit checking

### ISSUE THREAD

**Issue by thypad** [scikit-image/scikit-image#2277]
## Description

After loading a certain image and doing some preprocessing I tried to do a watershed transform like the one described here: http://scikit-image.org/docs/dev/auto_examples/plot_marked_watershed.html

During the processing, an error kept showing up after calling filters.rank.gradient(), with the following traceback:

```
/home/thypad/local/miniconda3/envs/anchor/lib/python2.7/site-packages/skimage/util/dtype.pyc in convert(image, dtype, force_copy, uniform)
    203     if kind_in == 'f':
    204         if np.min(image) < -1.0 or np.max(image) > 1.0:
--> 205             raise ValueError("Images of type float must be between -1 and 1.")
    206         if kind == 'f':
    207             # floating point -> floating point

ValueError: Images of type float must be between -1 and 1.
```

I checked a bunch of times, and the image passed is float64, but then I discovered that with this specific steps and image, the image I pass to filters.rank.gradient() has image.max() equal to 1.0000000002 or something like that, so it fails on this condition on module dtype.py.

I'm not sure it's necessary for me to inform how to reproduce the bug, because it's somewhat obvious that this condition checking for floats fails in the situation I just said, and the situation is possible, and appeared right after running filters.gaussian(image).

I just checked the dtype.py module on the repo, and this condition checking is still there. My suggestion is changing it so that it will take into account small errors in floating-point precision.

**Comment by sciunto** [comment]
Thank for reporting this.

Similar issues: #1529 #1616

**Comment by sciunto** [comment]
@jni and @stefanv seem to agree on a solution: https://github.com/scikit-image/scikit-image/issues/1529#issuecomment-107141553

**Comment by grlee77** [comment]
I believe this issue is outdated since `img_as_float` no longer requires floats in range [0, 1] or [-1, 1] when the input is of floating point type. 

However, using any of the `skimage.filters.rank` filters will still require floats strictly in the range [-1, 1] or [0, 1] so that the internal conversion from float to uint8 as used for the rank filters is well defined. This may require that you use ``image = np.clip(image, -1, 1)`` before calling `rank.gradient`.
