### ISSUE TITLE
Visual aspect + text of superpixels gallery example could be improved

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#2280]
As a result of the compact watershed being added to the superpixel gallery example (http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_segmentations.html), the subplots are now tiny. They should be made bigger (change aspect ratio + tight_layout).

Also, the text is not completely up to date (first paragraph says "This example compares three popular low-level image segmentation methods").

**Comment by soupault** [comment]
xref #2144

**Comment by soupault** [comment]
Closed via #2144
