### ISSUE TITLE
Change 2D Hessian matrix order from y/x to r/c

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#2301]
Hessian matrix computation used to return the matrix elements as "Hxx, Hxy, Hyy", which is equivalent to "Hcc, Hrc, Hrr". This goes against our array order conventions, for no particular reason other than history. See [this comment](https://github.com/scikit-image/scikit-image/pull/2194#r71079486) for more context.

Currently, this means that the 2D Hessian matrix is returned in a different order to the 3D+ matrix. This is messy and annoying.

Many functions and tests depend on this output, and the deprecation path is not going to be fun, but I would say that this is a necessary change in the long term (e.g. before 1.0).

**Comment by jni** [comment]
I've labelled this "easy" because it is not a technically challenging job, just a time-consuming one.

We do need to agree on how deprecations are going to work with output arguments when using a function correctly. It will be annoying to have no way of removing a warning.

Here's a suggestion: add an "order=None" kwarg that defaults to 'F' but warns with a deprecation. When passing "order='C'", the warning goes away. If we don't want to overload numpy's kwarg, we could also do the same thing with "coord_order=None", with possible values being "cr", "rc", and "yx".

**Comment by ahojnnes** [comment]
+1 to fix this asap and I like the proposed order="C|F" approach.

**Comment by sciunto** [comment]
I put 0.13 as a milestone to fix it asap. Sooner is better.

**Comment by soupault** [comment]
@jni has this been addressed?

**Comment by jni** [comment]
@soupault Yes! Which is awesome. *BUT*, there is also `structure_tensor` in that file, which should probably be updated also...!

**Comment by jni** [comment]
I'm going to close this. The structure tensor is probably not going to make it into 0.13.
