### ISSUE TITLE
Rename `px`, `py` variables in `draw.bezier_curve`

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2305]
## Description
See https://github.com/scikit-image/scikit-image/blob/master/skimage/draw/_draw.pyx#L776.

```
    px.extend(rr)
    py.extend(cc)
```
Should be renamed (`px->py`, `py->px`) to avoid confusion.

Xref #2319 .

**Comment by sciunto** [comment]
closed by #2321
