### ISSUE TITLE
Feature request: Total Variation Inpainting

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2309]
## References
- https://github.com/scikit-image/scikit-image/issues/631#issuecomment-244057138;
- http://www.ipol.im/pub/art/2012/g-tvi/

**Comment by dvolgyes** [comment]
It is probably even more complicated than the referenced TV method, 
but this one is also based on TV, but it can restore textures too with impressive results:
http://dx.doi.org/10.1137/090753504

For future work, it might be interesting.

**Comment by soupault** [comment]
@dvolgyes Very nice results! I'd be happy to see this in `skimage` one day.

I'm in no doubt that we could build a lot on top of the simplest TV-based inpainting, but it is one of the fundamental algorithms in the field, and is very nice suited for the educational purposes of `skimage`. Also, almost every other library (OpenCV, ImageJ, whatever) has it, so we should fall behind :).
