### ISSUE TITLE
Investigate doctr for deploying docs on Travis

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2317]
See https://drdoctr.github.io/doctr/

**Comment by souravsingh** [comment]
@stefanv I would like to work on the issue. Do we remove the script for deploying docs in the tools directory first before using doctr on Travis?

**Comment by shashankredemption** [comment]
We have concluded that this is much more work than it would be worth, and that doctr is not far enough along for us to make this move.

**Comment by sciunto** [comment]
@shashankredemption Who is we?

**Comment by shashankredemption** [comment]
@stefanv and I, my apologies!

**Comment by sciunto** [comment]
Ok :)

@stefanv and @shashankredemption Shall we close as WONTFIX?
