### ISSUE TITLE
New stereo images in data directory

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#2318]
For https://github.com/scikit-image/scikit-image/pull/1357, I would need to add a pair of stereo images and I suggest to use one from the dataset at http://vision.middlebury.edu/stereo/data/. Any objections or other proposals?

**Comment by soupault** [comment]
I'd be glad to see any pair of stereo images supplemented with the ground truth (depth map). Could be useful also for https://github.com/scikit-image/scikit-image/issues/2138.

**Comment by emmanuelle** [comment]
:+1: from me as well.

**Comment by sciunto** [comment]
Addressed in #1357

**Comment by soupault** [comment]
Closed via #1357.
