### ISSUE TITLE
bezier_curve returns arrays in a reverse order (column/line convention)

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2319]
## Description

In #2303
@soupault said "As I can understand, this is not correct. `_bezier_curve` returns arrays in a reverse order (`px, py` ==> `cc, rr`)."

* [ ] Check that the API does not conform to our standards and fix it
* [ ] Introduce deprecation if necessary
* [ ] Fix examples.

**Comment by soupault** [comment]
Hmm... https://github.com/scikit-image/scikit-image/issues/2305?
