### ISSUE TITLE
could measure.regionprops() work on squares and rectangles ?

### ISSUE THREAD

**Issue by stonebig** [scikit-image/scikit-image#2320]
## Description

regionprops works well on circles and ellipses, but not on squares and rectangles.
## Way to reproduce

example and images below:
- on rectangle, axis minor and major length are larger than the rectangle,
- on square, axis minor-length is larger than minor length.

I was trying to find circles, ellipses, rectangles and squares on an image, for teaching purposes.

Windows 10, Python 3.4, scikit-image-0.12.3

```

import math
import matplotlib.pyplot as plt
import numpy as np

from skimage.draw import ellipse, polygon
from skimage.measure import label, regionprops
from skimage.transform import rotate


image = np.zeros((600, 600))

#polygon
x = np.array([200, 400, 400, 200, 200])

# rectangle
y = np.array([100, 100, 350, 350, 100])

# square
#y = np.array([150, 150, 350, 350, 150])

#rr, cc = ellipse(300, 350, 100, 220)
rr, cc = polygon(y, x)

image[rr, cc] = 1

#image = rotate(image, angle=15, order=0)

label_img = label(image)
regions = regionprops(label_img)

fig, ax = plt.subplots()
ax.imshow(image, cmap=plt.cm.gray)

for props in regions:
    y0, x0 = props.centroid
    orientation = props.orientation
    x1 = x0 + math.cos(orientation) * 0.5 * props.major_axis_length
    y1 = y0 - math.sin(orientation) * 0.5 * props.major_axis_length
    x2 = x0 - math.sin(orientation) * 0.5 * props.minor_axis_length
    y2 = y0 - math.cos(orientation) * 0.5 * props.minor_axis_length

    ax.plot((x0, x1), (y0, y1), '-r', linewidth=2.5)
    ax.plot((x0, x2), (y0, y2), '-r', linewidth=2.5)
    ax.plot(x0, y0, '.g', markersize=15)

    minr, minc, maxr, maxc = props.bbox
    bx = (minc, maxc, maxc, minc, minc)
    by = (minr, minr, maxr, maxr, minr)
    ax.plot(bx, by, '-b', linewidth=2.5)

ax.axis((0, 600, 600, 0))
plt.show()
```

rectangle:
![scikit-rectangle](https://cloud.githubusercontent.com/assets/4312421/18823120/3c3d4726-83b7-11e6-95d0-a60ebdcdd924.png)

square:
![scikit-square](https://cloud.githubusercontent.com/assets/4312421/18823119/3c3bd986-83b7-11e6-9e3c-7e52c09df793.png)

**Comment by sciunto** [comment]
Regarding the rectangle, if you print `props.bbox`, you'll see that the values are correct. It's just a matter of convention with matplotlib.

**Comment by stevendbrown** [comment]
is this really a bug? doesn't the major_axis_length and minor_axis_length refer to the ellipse that best approximates the region rather than to the exact region itself?

**Comment by jmetz** [comment]
I agree with @stevendbrown - not sure this should be labelled a bug. 

At most it amounts to an enhancement, but even then it's not clear what the desired result would be??

**Comment by stevendbrown** [comment]
@jmetz i believe the "correct" answer which @stonebig is seeking could be the the Feret diameter or something like it (e.g. PR #1780) which does a point-by-point evaluation of all the diameters of an object as-is. for rectangles & squares, this would return a corner-to-corner distance. modifying the function in that PR to return the _minimum_ distance would give a cross-section pretty close to the short distance of the rectangle edge:

```
def feret_diameter_minimum(self):
    # self: a RegionProp object
    from ..morphology.convex_hull import convex_hull_image
    label_image = self._label_image
    label = self.label
    identity_convex_hull = convex_hull_image(label_image == label)
    coordinates = np.vstack(find_contours(identity_convex_hull, 0.5, 
                                              fully_connected = 'high'))
    distances = pdist(coordinates, 'sqeuclidean')
    return sqrt(np.min(distances))
```

alternatively, given the RegionProp.major_axis_length and RegionProp.orientation, one can compute the *actual* length of these cross-sections with something like this (some values like`1linewidth=2` were specific to my application), which in the rectangle case is parallel to the sides of the object:

```
def get_lw(rps, b_image):
    # rps: the RegionProp object for an object
    # b_images: binary image of the object in question
    # i think b_image could be replaced by rps._label_image
    # but it has been a while since i worked i this code
    y0, x0 = rps.centroid
    cosorient = math.cos(rps.orientation)
    sinorient = math.sin(rps.orientation)

    x1 = x0 + cosorient * 0.5 * rps.major_axis_length
    y1 = y0 - sinorient * 0.5 * rps.major_axis_length
    x2 = x0 - cosorient * 0.5 * rps.major_axis_length
    y2 = y0 + sinorient * 0.5 * rps.major_axis_length

    l_profile = np.array(profile_line(b_image, (y1, x1), (y2, x2), 
                                      linewidth = 2, 
                                      order = 0)).astype('float64')
    l_imp = (l_profile.sum() * rps.major_axis_length)/float(len(l_profile))

    x1 = x0 - sinorient * 0.5 * rps.minor_axis_length
    y1 = y0 - cosorient * 0.5 * rps.minor_axis_length
    x2 = x0 + sinorient * 0.5 * rps.minor_axis_length
    y2 = y0 + cosorient * 0.5 * rps.minor_axis_length

    w_profile = np.array(profile_line(b_image, (y1, x1), (y2, x2), 
                                      linewidth = 2, 
                                      order = 0)).astype('float64')
    w_imp = (w_profile.sum() * rps.minor_axis_length)/float(len(w_profile))
    
    return (l_imp, w_imp)
```

**Comment by jmetz** [comment]
Ahha - thanks for the explanation @stevendbrown - in that case this would amount to an enhancement, as the `major_axis_length` and `minor_axis_length` are still correct.

**Comment by stevendbrown** [comment]
@jmetz i agree!

**Comment by stonebig** [comment]
hi, my fonctionnal expectation would have been to get:
- "this is rather an ellipse", with blabla axes,
- "this is rahter a rectangle", with blibli axes.

I understand that current implementation is only looking for ellipses, and finding ellipses.

**Comment by stevendbrown** [comment]
@stonebig, the function doesn't "look for ellipses" but instead computes the mean orientation of the segment based on the distribution of the pixels that comprise the segment. the major and minor axes are a fairly standard measure in computer vision, the definition of which is restricted to the mathematical moments of an image or segment.

writing an algorithm to judge how "round" an object is seems like it might be beyond the scope of the skimage library. there are a variety of techniques for judging roundness and my limited experience with those methods suggests that no one method is perfect for all situations; it depends on what you are ultimately trying to do: http://www.itl.nist.gov/div898/handbook/mpc/section3/mpc344.htm

**Comment by stonebig** [comment]
I close the issue, as it looks not coherent with the spirit of the function.
