### ISSUE TITLE
Error in extracting normal of the faces in marching cube.

### ISSUE THREAD

**Issue by ShahramKa** [scikit-image/scikit-image#2329]
Hi,

Try to use the isosurface extraction using marching cube and got an error when asking for the normal direction.

It is working when using:
 verts, faces = measure.marching_cubes(ellip_double, 0)

 but give this error

 verts, faces, normal = measure.marching_cubes(ellip_double, 0)
ValueError: need more than 2 values to unpack

I thought might be because not specifying the gradient direction however, that would not help either. 
verts, faces, normal = measure.marching_cubes(ellip_double, 0, gradient_direction='descent')

Same error:
ValueError: need more than 2 values to unpack

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

from skimage import measure
from skimage.draw import ellipsoid
# Generate a level set about zero of two identical ellipsoids in 3D

ellip_base = ellipsoid(6, 10, 16, levelset=True)
ellip_double = np.concatenate((ellip_base[:-1, ...],
                               ellip_base[2:, ...]), axis=0)
# Use marching cubes to obtain the surface mesh of these ellipsoids

verts, faces = measure.marching_cubes(ellip_double, 0)
# Display resulting triangular mesh using Matplotlib. This can also be done
# with mayavi (see skimage.measure.marching_cubes docstring).

fig = plt.figure(figsize=(10, 12))
ax = fig.add_subplot(111, projection='3d')
# Fancy indexing: `verts[faces]` to generate a collection of triangles

mesh = Poly3DCollection(verts[faces])
ax.add_collection3d(mesh)

ax.set_xlabel("x-axis: a = 6 per ellipsoid")
ax.set_ylabel("y-axis: b = 10")
ax.set_zlabel("z-axis: c = 16")

ax.set_xlim(0, 24)  # a = 6 (times two for 2nd ellipsoid)
ax.set_ylim(0, 20)  # b = 10
ax.set_zlim(0, 32)  # c = 16

plt.show()

**Comment by almarklein** [comment]
A function can not (without awful hacks) be aware of its output arguments. The current version of `marching_cubes()` returns two, and there is no way to "ask" for more. That error is therefore to be expected.

The *current* version returns two values. In the current master  (and upcoming release) of scikit-image, the function will return four values (including normals). The old version will stay available as `measure.marching_cubes_classic()`.

PS: in markdown comments on Github, you can use tripple backticks to create code blocks:
```
` ` ` py
code here
` ` `
```
(without the spaces)

**Comment by almarklein** [comment]
>  In the current master (and upcoming release) of scikit-image, the function will return four values (including normals).

Correction: we *do* use some black magic hack to detect the number of output args in an attempt to be backward compatible.

**Comment by JZK00** [comment]
you need write:
verts, faces, normals, values = measure.marching_cubes(p, threshold)
