### ISSUE TITLE
Add dask as opt dep.

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2330]
See https://github.com/scikit-image/scikit-image/pull/2238#issuecomment-247765620 and https://github.com/scikit-image/scikit-image/pull/2238#issuecomment-251874188

Add `dask[array]>=0.5.0`

**Comment by soupault** [comment]
@matthew-brett could you comment on this issue? (see #2238 also)
Would `dask` be a suitable addition to the rackspace of #2451?

**Comment by stefanv** [comment]
Dask has no compiled parts, so I don't see why we would need a wheel.
