### ISSUE TITLE
Parallel computing skimage.feature.peak_local_max

### ISSUE THREAD

**Issue by simone-codeluppi** [scikit-image/scikit-image#2333]
## Description

I have an image and I want to run `skimage.feature.peak_local_max` using different thresholds. I would like to run the function in parallel using `joblib`. The parallelisation won't work  and I think because `labels` cannot be modified in each core. 

I made this naive hack by creating a `.copy()` of the labels variable in the function. Now each core can modify the `labels` value.

```
...................
# In the case of labels, recursively build and return an output
    # operating on each label separately
    if labels is not None:
        labels_copy=labels.copy()
        label_values = np.unique(labels)
        # Reorder label values to have consecutive integers (no gaps)
        if np.any(np.diff(label_values) != 1):
            mask = labels >= 1
            labels_copy[mask] = 1 + rank_order(labels[mask])[0].astype(labels.dtype)
        labels_copy = labels.astype(np.int32)

        # New values for new ordering
        label_values = np.unique(labels_copy)
        for label in label_values[label_values != 0]:
            maskim = (labels_copy == label)

..................
```

Sorry if it is not elegant (labels can be a big matrix) but I though to bring up the issue because I think that it will be really useful to be able to run this function in parallel.

Thanks

**Comment by jni** [comment]
@simone-codeluppi thanks for the report!

I have a surprising number of thoughts on this. =P

1. I would think that a more elegant hack would be to pass a new labels copy in each joblib call? Then there is no need to modify the original source?
2. It seems that `labels` is only modified if it contains non-consecutive integers, so perhaps joblib will only fail if you pass such an array — you could use `segmentation.relabel_sequential` to relabel ahead of time and avoid the modification.
3. Holy crap we are modifying an input array in-place without warning! That's actually a massive bug imho!
4. From what I can tell, it is actually completely unnecessary and a huge waste of time to reorder the label values, why is that even a thing here?

So, if you want to submit a PR that removes the relabeling, I for one would most welcome it! In the meantime, thanks for the report, as it's very valuable!

**Comment by jmetz** [comment]
@jni - had a quick bash at this - see following link

**Comment by soupault** [comment]
@simone-codeluppi hello! Could you verify the fix from #2341?

**Comment by soupault** [comment]
@simone-codeluppi gentle ping.

**Comment by jni** [comment]
@simone-codeluppi I believe #2341 should have fixed your use case, so please try running the latest skimage version on github. If it's not fixed, feel free to reopen this issue!

Thanks!
