### ISSUE TITLE
Hog features normalization

### ISSUE THREAD

**Issue by aplavin** [scikit-image/scikit-image#2335]
## Description

When normalizing HOG feature blocks, currently scikit-image [uses](https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/_hog.py#L187) this formula: `normalised_blocks[y, x, :] = block / np.sqrt(block.sum() ** 2 + eps)`. What's the point of squaring and immediately taking square root? I guess `np.sqrt(block.sum() ** 2 + eps)` can be replaced with `np.abs(block.sum()) + eps` for less confusion (maybe changing the `eps` values also - it's here just to prevent division by zero, as I know).
Or possibly to `np.sqrt((block ** 2).sum() + eps)`, if that was intended initially?

**Comment by soupault** [comment]
@aplavin Hi! Thanks for reporting! I don't see a strong reason either. Will address this shortly.
If you are looking for a different block normalization methods, they will come in with https://github.com/scikit-image/scikit-image/pull/2040.
