### ISSUE TITLE
Broken example: plot_rag_merge.py

### ISSUE THREAD

**Issue by EvanWeiner** [scikit-image/scikit-image#2339]
REPRO STEPS:
1. Run the plot_rag_merge.py in latest scikit-image example and look at the image.

RESULT:

The result looks far from the image in 
http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_rag_merge.html#sphx-glr-auto-examples-segmentation-plot-rag-merge-py

It appears no one actually tested this after the example was updated (it's history shows 2 updates).

REMARKS:

The original version of plot_rag_merge.py works pretty close to the image in the docs. After debug, it seems the bug is that return value in `_weight_mean_color` function should not be `return {'weight': diff}` just `return diff`

**Comment by soupault** [comment]
Here is the ourcome on my setup (Python 3.5, latest `skimage` master branch commit, numpy 1.11.2, Linux x86_64):
![figure_1](https://cloud.githubusercontent.com/assets/1315589/19355543/6794b11a-9173-11e6-96c3-28d9dfde2623.png)
Pretty much the same image as the one from the gallery.

Could you elaborate on your environment?

**Comment by EvanWeiner** [comment]
Python 2.7, numpy==1.8.2, Linux(Ubuntu 14) x86_64

**Comment by EvanWeiner** [comment]
Here's the output when I run it:

![image](https://cloud.githubusercontent.com/assets/8980169/19374213/9cc0744e-91fc-11e6-8a2a-b3b2ff792cac.png)

Note: if I run the older version of this script from here, then the output looks like yours and matches the example:
http://scikit-image.org/docs/0.11.x/auto_examples/plot_rag_merge.html#example-plot-rag-merge-py

**Comment by soupault** [comment]
@jni @vighneshbirodkar could anyone of you verify this, please?

**Comment by KhaledTo** [comment]
I got similar result as @EvanWeiner. 

Ubuntu14.04 x86-64 
Python 2.7.12
Numpy 1.10.4
skimage 0.11.3

**Comment by vighneshbirodkar** [comment]
@KhaledTo Could you try updating your scikit-image installation ?
@EvanWeiner What version  of scikit-image are you using ?

I am getting the same result as the docs webpage. My versions are 
```
>>> import skimage, numpy, scipy, networkx
>>> skimage.__version__
'0.13dev'
>>> numpy.__version__
'1.11.2'
>>> scipy.__version__
'0.18.1'
>>> networkx.__version__
'1.11'
```
on `Python 2.7.11+`

**Comment by KhaledTo** [comment]
Hi @vighneshbirodkar, 

So I updated to `0.13dev` and now I have the expected result.

**Comment by EvanWeiner** [comment]
In [1]: import skimage, numpy, scipy, networkx

In [2]: skimage.__version__
Out[2]: '0.12.3'

In [3]: numpy.__version__
Out[3]: '1.8.2'

In [4]: scipy.__version__
Out[4]: '0.18.1'

In [5]: networkx.__version__
Out[5]: '1.11'

Python 2.7, Ubuntu 14

@vighneshbirodkar

**Comment by soupault** [comment]
I'm closing the issue as it works as expected in 0.13dev. @EvanWeiner , please, notice that RAG-tools are located in `future` module, means that they are expected to have experimental API and implementation.
In case of urgent need, please, update to 0.13dev or wait till the next release (which is to be out soon).
