### ISSUE TITLE
[ENH] Fractal dimension (Minkowski–Bouligand)

### ISSUE THREAD

**Issue by rougier** [scikit-image/scikit-image#2347]
I've coded a fractal dimension computation for a colleague and I saw on #1730 there may be some interest. If this is the case, I can make a PR but I'm not sure where to put this (small) code.

Code is at https://gist.github.com/rougier/e5eafc276a4e54f516ed5559df4242c0
You'll need a Sierpinski image to test, I attached the one I use below.

The wikipedia reference is: https://en.wikipedia.org/wiki/Minkowski–Bouligand_dimension  
See also http://hypertextbook.com/chaos/fractal/

Code has only been tested on the Sierpenski triangle.

![sierpinski](https://cloud.githubusercontent.com/assets/327203/19587148/61653cc6-975c-11e6-8a22-2c434a7a2acc.png)

Output:

```
Minkowski–Bouligand dimension (computed):  1.59108814501
Haussdorf dimension (theoretical):         1.58496250072
```

**Comment by sciunto** [comment]
@stefanv Do you have  a comment for the inclusion of such feature?

**Comment by stefanv** [comment]
@rougier Do you have any practical usage examples for this code?

**Comment by rougier** [comment]
Not really, I'm not using it myself. #1730 seems to indicate it might be utilized in biomedical imaging, that's all I know (and it was also the case for the colleague who asked me).

**Comment by softwaremechanic** [comment]
I'll bat for this. It is useful in cases where you want to check if an attribute/dimension of has a dependency on previous values of the attribute.(Something similar to [time-series stationarity test ](https://en.wikipedia.org/wiki/Dickey%E2%80%93Fuller_test) ). 
The point is if there's a fractal dimension then we know that this series of values have some dependency on previous values and will change depending on what the initial conditions were. 

It can help us identify, strange attractors / local optima.

**Comment by softwaremechanic** [comment]
In the case of biomedical imaging, I can imagine it being useful in identifying certain issues like malignant growth(aka cancerous growth). According to [Dr.Sapolsky ](https://youtu.be/_njf8jwEGRo?t=3907) a lot of our tissues and inner organs have growth functions/programmed in iterated function systems method/approach. Cancerous tissues would be ignoring the stopping rules.

**Comment by softwaremechanic** [comment]
A paper summarizing various applications of fractal geometry and dimension found [here.](http://www.noar.technion.ac.il/images/attachments/Scitech/FractalGeometryImageProcessing.pdf) Can be relevant, even if it seems lacking in originality..

**Comment by softwaremechanic** [comment]
@rougier : How can we generalize the code to more than 2 dimensions? I'd like to feed it a nx4 matrix and see if there's an fractal interaction between the 4 variables.. Can you help creating test sets for the same?. I'll try generalizing the code.

**Comment by rougier** [comment]
I don't know actually but you can contact me by mail if you have some ideas.

**Comment by stefanv** [comment]
I think this is cute, but probably slightly outside scope.  I'm going to close for now, but if you find a well cited paper out there, let me know!

**Comment by jankaWIS** [comment]
Hi all, first of all, I believe this has potential use. Besides what has been mentioned, I have encountered it now as well and I also started working on implementing a fractal analysis for my colleague. First of all, there has been [this extension to 3D](https://github.com/ChatzigeorgiouGroup/FractalDimension) together with some applications. Second of all, in biology for image processing, FiJi/ImageJ is used a lot and I have used that together with work from @rougier ([this one](https://gist.github.com/rougier/e5eafc276a4e54f516ed5559df4242c0)) for writing my first pieces of code. The relevant documentation is on those pages: [box counting](https://imagej.nih.gov/ij/plugins/fraclac/FLHelp/BoxCounting.htm) but more importantly, this [glossary](https://imagej.nih.gov/ij/plugins/fraclac/FLHelp/Glossary.htm#grayscale) which defines three measures for grayscale images (notice that this Is basically looking at 3D) 
> FracLac reports 3 basic types of fractal dimension for grayscale scans. 
> DB
> DM
> Dx̄

Besides all of this, this tool also controls for other problems (tbh I think that some are negligible like the grid position which they sample), eg see [this link](https://imagej.nih.gov/ij/plugins/fraclac/FLHelp/BoxCountingOptions.htm). 

For more reference as @stefanv requested, see this page:
https://bmcresnotes.biomedcentral.com/articles/10.1186/1756-0500-2-130
or this article
https://imagej.nih.gov/ij/plugins/fraclac/FLHelp/Fractals.htm#fractalanalysisinpractice
or what has been mentioned in the related issue by @SalvatoreScaramuzzino :
http://cdn.intechopen.com/pdfs-wm/39360.pdf

As I said, I have already written something on top of @rougier following the ImageJ implementation but at the moment being puzzled what a negative dimension means (I'm getting one of them, D_b, negative, and trying to figure out what's going on) but I would be happy to contribute/collaborate. Just to note, I have never worked on any program development and my contributions are so far quite marginal but I'd be happy to learn :).

**Comment by rougier** [comment]
Ok. Maybe it's time to create a small project on GitHub given the regular interests in fractal dimension. This will ease the collaboration and the many corrections. What do you think?
