### ISSUE TITLE
Add different methods for HOG block normalization

### ISSUE THREAD

**Issue by coderforlife** [scikit-image/scikit-image#2350]
It would be nice if HOG implemented the other types of normalization mentioned in the paper (including L2-hys, L2-norm, L1-sqrt, and L1-norm). Right now L1-norm is always used and it was the worst method according to the original paper (besides not normalizing at all). Also, the L1-norm is done in an odd way that looks like it was supposed to be one of the other norms but it wasn't quite complete.

The code at https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/_hog.py#L187 could be done like the following (given an argument `norm` that is equal to `'L1-norm'`, `'L1-sqrt'`, `'L2-norm'`, or `'L2-hys'` (and validated earlier):

```
if norm == 'L1-norm':
    normalised_blocks[y, x, :] = block / (block.sum() + eps)
elif norm == 'L1-sqrt':
    normalised_blocks[y, x, :] = np.sqrt(block / (block.sum() + eps))
elif norm == 'L2-sqrt':
    normalised_blocks[y, x, :] = block / np.sqrt((block*block).sum() + eps)
else: #if norm == 'L2-hys':
    block_norm = np.clip(block / np.sqrt((block*block).sum() + eps)), max=0.2)
    normalised_blocks[y, x, :] = block / np.sqrt((block_norm*block_norm).sum() + eps)
```

Even if not all of these normalization methods are made available, the default should not be the odd implemented L1-norm that it currently is (except for backwards compatibility I guess).

**Comment by soupault** [comment]
@coderforlife Hello! Are you looking for https://github.com/scikit-image/scikit-image/pull/2040? :)
Unfortunately, it is stil lacking of reviews, so I'd be grateful if you move there and stress core team members a little :wink:.

**Comment by coderforlife** [comment]
Duplicate of #1345, #2040, and #2335.

**Comment by soupault** [comment]
Not fixed yet, so I reopen to have this as an extra reminder. :smiling_imp:

**Comment by sciunto** [comment]
Close by @soupault

**Comment by NicholasJohnson9149** [comment]
I seem to be getting this same warning, how do I get ride of it? skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)

**Comment by coderforlife** [comment]
@NicholasJohnson9149 This wasn't about a warning, this was about the fact that L1 used to be the only method. To get rid of the warning use a newer block normalization, like the following:
```
hog(..., block_norm='L2-Hys')
```

**Comment by soupault** [comment]
I agree that the warning (as it is currently implemented) is kind of annoying, but I couldn't come up with a more convenient alternative. Setting `block_norm` to `L2-Hys` (as @coderforlife already mentioned) should fix the issue.
