### ISSUE TITLE
Frangi filter is seemingly missing

### ISSUE THREAD

**Issue by VOK1973** [scikit-image/scikit-image#2378]
Experience an error trying to replicate this tutorial:

http://scikit-image.org/docs/dev/auto_examples/filters/plot_frangi.html#sphx-glr-auto-examples-filters-plot-frangi-py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-5cdc9a583d42> in <module>()
      1 from skimage.data import camera
----> 2 from skimage.filters import frangi, hessian
      3 
      4 import matplotlib.pyplot as plt
      5 

ImportError: cannot import name 'frangi'

I cannot find any reference to frangi filter in __init__ files of the site packages either

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example - comes directly from the 
- [ ] Relevant images (if any) - irrelevant
- [ ] Operating system and version - Ubuntu 14.04
- [ ] Python version - 3.5.1
- [ ] scikit-image version (run `skimage.__version__`) 0.12.3

**Comment by soupault** [comment]
@VOK1973 `frangi` filter hasn't yet been released (i.e. it is only available in `0.13dev`).
To install development version, please, follow this guide - http://scikit-image.org/docs/dev/install.html#running-the-development-version.

**Comment by VOK1973** [comment]
Thank you, Egor

This explains
