### ISSUE TITLE
Why is `gaussian` so opinionated about the image value range

### ISSUE THREAD

**Issue by b52** [scikit-image/scikit-image#2383]
## Description

Trying to apply `skimage.filters.gaussian` to a floating image may result in a `ValueError` if any value is outside [0, 1]. For `gaussian` it shouldn't matter what values are in the image.

```pytb
In [1]: import numpy as np
In [2]: from skimage.filters import gaussian
In [3]: img = np.array([[10.0, -10.0], [-4, 3]], dtype=np.float32)
In [4]: gaussian(img, 1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-b8596e79c5dc> in <module>()
----> 1 gaussian(img, 1)

/home/oli/Projects/pbl2/env/lib/python3.5/site-packages/skimage/filters/_gaussian.py in gaussian(image, sigma, output, mode, cval, multichannel)
    102         if len(sigma) != image.ndim:
    103             sigma = np.concatenate((np.asarray(sigma), [0]))
--> 104     image = img_as_float(image)
    105     return ndi.gaussian_filter(image, sigma, mode=mode, cval=cval)

/home/oli/Projects/pbl2/env/lib/python3.5/site-packages/skimage/util/dtype.py in img_as_float(image, force_copy)
    299
    300     """
--> 301     return convert(image, np.float64, force_copy)
    302
    303

/home/oli/Projects/pbl2/env/lib/python3.5/site-packages/skimage/util/dtype.py in convert(image, dtype, force_copy, uniform)
    203     if kind_in == 'f':
    204         if np.min(image) < -1.0 or np.max(image) > 1.0:
--> 205             raise ValueError("Images of type float must be between -1 and 1.")
    206         if kind == 'f':
    207             # floating point -> floating point

ValueError: Images of type float must be between -1 and 1.
```

## Way to reproduce

Simply run the code snippet:

```python
import numpy as np
from skimage.filters import gaussian
img = np.array([[10.0, -10.0], [-4, 3]], dtype=np.float32)
gaussian(img, 1)
```

**Comment by JDWarner** [comment]
Floating point input images have the expectation that they will be on the range [0, 1] (for positive image) or [-1, 1] (for signed images).  There has been talk about relaxing this, but it's not always straightforward as certain algorithms - particularly in contrast adjustment and color conversions - use exponentiation and depend on this assumption.  The output from any algorithm in this package will pass in as the input here without issue. 

We have an "anything in, anything out" policy when it comes to datatypes.  We try to understand what was passed, and hopefully we can work with it, but we don't guarantee it will be returned as the original datatype.  Often we hand it back as a floating point image, so we don't compound rounding error through multiple steps.

The way to try and break this is passing a floating point array - which is a dtype we understand - with values outside this range.  That's what you're doing here.  We could squash the range, but doing so is fraught with a number of assumptions meaning the calculation might be wrong several ways.  Instead, we prefer to throw an informative error and allow the user to correct the problem.

All that said, we probably could remove the `img_as_float` line here without too much trouble.  However, that just means the _next_ function you use will throw this same error at you.  Ideally, get in the habit of following conventions for floating point images.

**Comment by b52** [comment]
Well, there are images (to be exact volumes), which use floating values but are outside the range of [-1, 1] because the represent physical units. Normalizing these is for me right now not an option.

However, for the time being I found a workaround by converting the image/volume to `np.float64`, which somehow doesn't trigger this error.

```
import numpy as np
from skimage.filters import gaussian
img = np.array([[10.0, -10.0], [-4, 3]], dtype=np.float64)
gaussian(img, 1)
```

Yet, this is only a **workaround**, not a real solution for me.

**Comment by jni** [comment]
I'm with @b52 here. For the exact reason mentioned by him, (image units are often have physical meaning) it's often desirable to keep the input units intact. We have added `preserve_range=` as a keyword argument to several functions to support this, but library-wide, we are still not consistent. I think the policy going forward should be that ranges will be enforced **when strictly necessary**. Clearly, that's not the case here, so I'm classifying this as a bug.

Thanks for the report, @b52!
