### ISSUE TITLE
has shape_index disappeared ?

### ISSUE THREAD

**Issue by jmmugnes** [scikit-image/scikit-image#2389]
hello,

after installing scikit-image v0.12.3 using pip3, i downloaded the script plot_shape_index.py and when running it this is what i get:

~/Documents/Python/Scripts$ python3.4 plot_shape_index.py
Traceback (most recent call last):
  File "plot_shape_index.py", line 46, in <module>
    from skimage.feature import shape_index
ImportError: cannot import name 'shape_index'

I looked in the package corner.py and the function shape_index is gone. 
Could it be that the installed corner.py is not the good one?

By the way i'm on ubuntu 14.04 and the installation of scikit-image went smoothly:

~/Desktop$ sudo pip3 install scikit-image --upgrade
Collecting scikit-image
  Downloading scikit-image-0.12.3.tar.gz (20.7MB)
    100% |████████████████████████████████| 20.7MB 29kB/s 
Requirement already up-to-date: six>=1.7.3 in /usr/local/lib/python3.4/dist-packages (from scikit-image)
Requirement already up-to-date: networkx>=1.8 in /usr/local/lib/python3.4/dist-packages (from scikit-image)
Requirement already up-to-date: pillow>=2.1.0 in /usr/local/lib/python3.4/dist-packages (from scikit-image)
Requirement already up-to-date: dask[array]>=0.5.0 in /usr/local/lib/python3.4/dist-packages (from scikit-image)
Requirement already up-to-date: decorator>=3.4.0 in /usr/local/lib/python3.4/dist-packages (from networkx>=1.8->scikit-image)
Requirement already up-to-date: toolz>=0.7.2; extra == "array" in /usr/local/lib/python3.4/dist-packages (from dask[array]>=0.5.0->scikit-image)
Requirement already up-to-date: numpy; extra == "array" in /usr/local/lib/python3.4/dist-packages (from dask[array]>=0.5.0->scikit-image)
Installing collected packages: scikit-image
  Found existing installation: scikit-image 0.10.0
    Uninstalling scikit-image-0.10.0:
      Successfully uninstalled scikit-image-0.10.0
  Running setup.py install for scikit-image ... done
Successfully installed scikit-image-0.12.3

As you can see i tried older versions to no avail. Am i missing something?

**Comment by soupault** [comment]
Hi @jmmugnes !
See https://github.com/scikit-image/scikit-image/issues/2336.
