### ISSUE TITLE
Blending two color images

### ISSUE THREAD

**Issue by manuSrep** [scikit-image/scikit-image#2400]
## Description
I am relatively new to skimage but I could not find a proper and easy way to blend two colore images as it is for example possible in pillow: http://pillow.readthedocs.io/en/3.0.x/reference/ImageChops.html
Would it not be useful to have such a function also in skimage. Such a function is also useful when working with label masks. As far as I know label blending in skimage is currently always converting the image into gray values.

I would also like to help implementing if the community deciders positive on this request.

Best Regards 
Manuel

**Comment by manuSrep** [comment]
By the way:
how can I add a label to the issue???

**Comment by jni** [comment]
@manuSrep Thanks for the suggestion! However, in scikit-image, all [images are just numpy arrays](http://scikit-image.org/docs/dev/user_guide/numpy_images.html), so it's completely straightforward arithmetic to blend two images:

```python
alpha = 0.5
blended = alpha * image0 + (1 - alpha) * image1
```

As such I don't think a blend function is necessary. I will close this issue for now, please re-open if you disagree!

**Comment by jni** [comment]
btw, I think only core developers of scikit-image can change labels... But we will always listen to suggestions in the comments, if you want to suggest a label! =)

**Comment by harshays98** [comment]
blended = `img1+(0.001*img2)`
