### ISSUE TITLE
warping by PiecewiseAffineTransform

### ISSUE THREAD

**Issue by Borda** [scikit-image/scikit-image#2402]
## Description
not sure if it is bug or a wrong usage, but using transformation which should be identity, I was not able to get complete image, it seems to me that the output image is cut by another input image size (example, the input image has shape 1100x1600 and the output image looks like 1100x1100)

```
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from skimage.transform import warp, PiecewiseAffineTransform

path_image = 'Rat_Kidney_HE.jpg'
image = np.array(Image.open(path_image))

tform = PiecewiseAffineTransform()

corners = np.array([
    [0., 0.],
    [image.shape[0], 0.],
    [0., image.shape[1]],
    [image.shape[0], image.shape[1]],
])

tform.estimate(corners, corners)
img_warped = warp(image, tform, output_shape=(2000, 2000))

plt.imshow(img_warped), plt.show()
```

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example
- [x] Relevant images ![rat_kidney_he](https://cloud.githubusercontent.com/assets/6035284/21195571/9f9871f4-c234-11e6-8945-b53909aedbb4.jpg)
- [x] Operating system and version
- [x] Python version - 2.7
- [x] scikit-image version ('0.11.3' and '0.13dev')

**Comment by Borda** [comment]
well, swapping the coordinates I got the correct image back
if it is the proper usage (it is not intuitive) int would be nice to have it in [doc](http://scikit-image.org/docs/dev/api/skimage.transform.html#piecewiseaffinetransform)

```
corners = np.array([
    [0., 0.],
    [0., image.shape[0]],
    [image.shape[1], 0.],
    [image.shape[1], image.shape[0]],
])
```

**Comment by Borda** [comment]
and also missing real corner points does a cut of the selection, is it correct?

```
N = 150
corners = np.array([
    [N, N],
    [N, image.shape[0] - N],
    [image.shape[1] - N, N],
    [image.shape[1] - N, image.shape[0] - N],
])
```

**Comment by REDVM** [comment]
I think that's correct behaviour.
Numpy Array shape is rows (y) first and columns (x) after, but _estimate_ method use coordinates in (x, y).

For your last example, warping will always warp what's inside the convex hull of coordinates, thus resulting image is correct.

Related : #1789 Check coordinate convention of transform.warp

**Comment by jni** [comment]
@Borda yeah, sorry! (And sorry for the long lag in response!) Unfortunately the `transform` module uses x/y coordinates, which is the opposite of NumPy arrays. We have an n-dimensional transform module in the roadmap (see https://github.com/scikit-image/scikit-image/issues/2397 in addition to #1789 as pointed out by @REDVM), but we aren't there yet...! In the meantime I'll close this as it is expected behaviour. We will definitely welcome a doc fix! But know that the more intuitive behaviour is on its way.

**Comment by Borda** [comment]
Ok, I will have look at the doc and maybe create a PR with something...

**Comment by zihaozhang9** [comment]
Coordinates (xy or yx) are really confusing. The coordinates of `estimate(self, src, dst)` in the function [`PiecewiseAffineTransform `](https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/_geometric.py#L847-L978)is [`(x, y)`](https://github.com/scikit-image/scikit-image/blob/f71be82423e73cda4f3026a0eb656614db937bbc/skimage/transform/_geometric.py#L660), namely `(cols, rows)`.  <br>
However, the [`output_shape `](https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/_warps.py#L726)of `warp` is` (rows, cols)`.
