### ISSUE TITLE
API resize/rescale redundant?

### ISSUE THREAD

**Issue by gongzhitaao** [scikit-image/scikit-image#2405]
## Description
Any difference between the two API, [`skimage.transform.rescale`](http://scikit-image.org/docs/stable/api/skimage.transform.html#rescale) vs [`skimage.transform.resize`](http://scikit-image.org/docs/stable/api/skimage.transform.html#resize)?  It seems to me having both is redundant and confusing.  And as for code, `rescale` is just a thin wrapper around `resize`.

Concretely the only difference between `rescale` and `resize` is the parameter type, i.e., `float` vs `int`.

One possible way to combine the `rescale` and `resize` is allowing both type of inputs.  For example, [`pandas.DataFrame.sample(n=None, frac=None, ...)`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sample.html) takes two mutually exclusive parameters `n` and `frac`, which is similar in the case of `rescale` and `resize`.

**Comment by soupault** [comment]
Hi @gongzhitaao !
I fully understand your point. However, I find the current implementation more convenient for the users.
I think that beginners often mess these two terms (rescale, resize), and having both of the names exposed in the API increase the chance of finding the required one.
Above said, I vote :-1: for this change, but would be glad to hear more opinions from the core team.

**Comment by gongzhitaao** [comment]
@soupault 

> and having both of the names exposed in the API increase the chance of finding the required one.

At least I totally agree with this.

Another quick question (maybe should open another issue), is it good to implement `keep_aspect` in the `resize` function?  Just like the [`PIL thumbnail`](http://pillow.readthedocs.io/en/3.4.x/reference/Image.html#PIL.Image.Image.thumbnail)?

**Comment by soupault** [comment]
@gongzhitaao 

>Another quick question (maybe should open another issue), is it good to implement keep_aspect in the resize function? Just like the Pillow Image.thumbnail?

Sounds like a valuable addition for me. Feel free to submit a PR :wink: .

**Comment by soupault** [comment]
Closing as wontfix.
