### ISSUE TITLE
image read by skimage.io.imread have the wrong shape

### ISSUE THREAD

**Issue by jdhao** [scikit-image/scikit-image#2406]
## Description
I am trying to read an RGB image using the skimage.io.imread. But after reading the image, I found that the image shape is wrong, `print(img.shape)` shows that the image shape is `(2,)`.

I also tried to read the image using opencv's python package, the returned shape is correct (height \times width \times 3).

### Code sample to reproduce the problem
```
from skimage import io
img = io.imread(path/to/the/image)
print(img.shape)
```
### The test image
~~[click here for the test image](https://i.stack.imgur.com/oI5lA.jpg)~~
[the original test image which is not altered](https://github.com/csucat/markdown_photos/blob/master/156.jpg)

### Operating system and version
The problem appears both in **Windows 8.1 Enterprise Edition**( version **6.3.9600**)
and **CentOS** (version  **7.2.1511**)

### Python version
The version of Python for **Windows** is **3.5.2**, and the  for **CentOS**, the version 
is **2.7.12**.

### scikit-image version used
The version of scikit-image **both** for Windows and CentOS is **0.12.3**, the latest version.

## note
The scikit-image and Python used for Windows and CentOS are provided by Anaconda3 and Anaconda2.

**Comment by soupault** [comment]
Hi @csucat !
Everything is fine in my environment: shape is (978, 2000, 3).

What do you see with `io.available_plugins` and `io.plugin_order()`?

**Comment by csucat** [comment]
For `io.available_plugins`, on my Windows system and CentOS system, the outputs are the same:
>{'fits': ['imread', 'imread_collection'],
 'freeimage': ['imread', 'imsave', 'imread_collection'],
 'gdal': ['imread', 'imread_collection'],
 'gtk': ['imshow'],
 'imageio': ['imread', 'imsave', 'imread_collection'],
 'imread': ['imread', 'imsave', 'imread_collection'],
 'matplotlib': ['imshow', 'imread', 'imshow_collection', 'imread_collection'],
 'pil': ['imread', 'imsave', 'imread_collection'],
 'qt': ['imshow', 'imsave', 'imread', 'imread_collection'],
 'simpleitk': ['imread', 'imsave', 'imread_collection'],
 'test': ['imsave',
  'imshow',
  'imread',
  'imread_collection',
  'imshow_collection'],
 'tifffile': ['imread', 'imsave', 'imread_collection']}

For `io.plugin_order()`, on the Windows and CentOS system, both the outputs are:
>{'_app_show': ['matplotlib'],
 'imread': ['pil', 'matplotlib'],
 'imread_collection': ['pil', 'matplotlib'],
 'imsave': ['pil'],
 'imshow': ['matplotlib'],
 'imshow_collection': ['matplotlib']}

**Comment by csucat** [comment]
@soupault , my friends' Linux system installs an older version of skimage(version 0.9.3). The output image shape using that version is correct.

**Comment by soupault** [comment]
@csucat I have the same output for the calls above.

The thing is we don't actually ship image coders/decoders but rather use them via plugin system (with several exceptions, like `.tiff`). So, frankly speaking, I'd not expect any issues from our side.

Could you try to update `matplotlib` and `pillow` to the latest versions and check your example again?

**Comment by soupault** [comment]
@csucat hi! Any news?

**Comment by csucat** [comment]
@soupault , I have updated  `matplotlib` and `pillow` to the latest version, but the problem still exists.

**Comment by csucat** [comment]
@soupault , maybe I should also open an issue on the Pillow github repo?

**Comment by soupault** [comment]
@csucat wouldn't harm, I think :). I'm out of ideas for the moment.

What do you see with: ?
```
import PIL
img = PIL.Image.open(%your_img%)
img.size
```

Are you by any chance using the wrong environment in Conda?

**Comment by csucat** [comment]
@soupault , the size is (2000, 978)

**Comment by soupault** [comment]
@csucat okaaay... Thanks, that's interesting!

>I am not sure where to open the issue, pillow or matplotlib repo?

Let's do one thorough check before you raise it (`pillow` is a better place, for sure).
Could you play with different plugins returned by `io.available_plugins` and check which one is actually failing (i.e. for each plugin (1) `skimage.io.use_plugin(...)`, (2) `skimage.io.imread(...)`)?

**Comment by csucat** [comment]
@soupault , for all the available, actually only pil and matplotlib can read the image, the other plugins all raise all kinds of exceptions. 
The code I use is:
```
from skimage import io
img_path = 'f:\\156.jpg'

plugin_list = io.available_plugins
valid_plugin = []

for key in plugin_list.keys():
    if 'imread' in plugin_list[key]:
        valid_plugin.append(key)

for plugin in valid_plugin:
    try:
        io.use_plugin(name=plugin, kind='imread')
        img = io.imread(img_path)
        print("use plugin {}, img size is {}".format(plugin, img.shape))
    except:
        continue
```
The output is
>use plugin pil, img size is (2,)
>use plugin matplotlib, img size is (978, 2000, 3)

Maybe it is pil that is causing the problem.

**Comment by soupault** [comment]
@csucat  :face_with_thermometer: .
Just to be fully informed:
```
import numpy
import PIL
import skimage

print(numpy.version.full_version)
print(PIL.VERSION)
print(PIL.PILLOW_VERSION)
print(skimage.__version__)
```

**Comment by csucat** [comment]
@soupault , the version are:
```
1.11.1  # for numpy.version.full_version
1.1.7   # for PIL.VERSION
3.4.2   # for PIL.PILLOW_VERSION
0.12.3  # for skimage.__version__
```

**Comment by jni** [comment]
This is super weird, I also can't reproduce...

Since using a direct read with Pillow correctly produces the image size, I don't think it's a good idea raising an issue in the pillow repository. @csucat have you used pdb before? I think you should do

```python
from skimage import io
import pdb

img_path = 'f:\\156.jpg'

io.use_plugin('pil')
pdb.runcall(io.imread, img_path)
```

and step through the code to see where the size is getting corrupted...

**Comment by sciunto** [comment]
I can't reproduce as well. @csucat Can you check the integrity of the image (ie the one you gave to us is the same as the one you have; we don't know what the website is doing once the image is uploaded so I have no guarantee that we are playing with the same picture).

On my side, the md5sum is 7f3f746b557c0004fb365d8d875f2451

**Comment by csucat** [comment]
@sciunto ,yes, unfortunately, the image uploaded has been changed since the two md5sums are not the same.
I have uploaded the image to [this repo](https://github.com/csucat/markdown_photos/blob/master/156.jpg), the md5sum of downloaded image is not altered. So it may reproduce the problem.

**Comment by jni** [comment]
@csucat I can indeed reproduce now! Current md5 is:

6bc94ff2d3a2ea82b514051ec182ee97

**Comment by csucat** [comment]
@jni , yeah, that is the correct md5sum.

**Comment by jni** [comment]
Ok so I don't know enough about the depths of PIL but it seems to me that the error is either there or in the image itself. The problem is that PIL sees two frames in the image, the actual image, and an empty one behind it. [Here's my full exploration using pdb](https://gist.github.com/jni/f6345843a9fcc37c7eecf9a4f55bc8d3), but here's the executive summary:

```python
In [9]: from PIL import Image

In [10]: im = Image.open('156.jpg')

In [11]: im.n_frames
Out[11]: 2
```

Then, [this line](https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_plugins/pil_plugin.py#L123) tries to concatenate all the frames together. When the frames aren't the same size (in this case, `frames[0]` has shape `(978, 2000, 3)`, while `frames[1]` has shape `()`), you get an array of dtype `O`. The image is actually at `im[0]`.

So, as a first workaround, I suggest using `im = io.imread('156.jpg', img_num=0)`. That should give you the result you want. In the future, I see four options:

- don't fix, consider this a corrupted image
- raise upstream with PIL
- explicitly handle the case of an empty final frame and discard it
- proceed with dismantling our entire IO infrastructure and handing it off to imageio, which handles this image correctly (though, I suspect, at the expense of other, actually multi-frame images).

CC @blink1073 @almarklein

**Comment by blink1073** [comment]
`imageio` is tests against multi-frame GIFs in PIL, and uses `tifffile` for multi-frame TIFFs

https://github.com/imageio/imageio/blob/30437ec06e5afce28a1459a1cdd365a355d39c84/tests/test_pillow.py#L239
https://github.com/imageio/imageio/blob/30437ec06e5afce28a1459a1cdd365a355d39c84/tests/test_tifffile.py#L40

Another reason to switch over  ;).

**Comment by stefanv** [comment]
We will be switching over to imageio in the near future.  Meanwhile, a workaround for empty frames seems reasonable.

**Comment by xinleipan** [comment]
I've also had the same issue with skimage.io which actually reads in the image with a wrong shape.
