### ISSUE TITLE
Better documentation for `peak_local_max`s `exclude_border` boolean variant

### ISSUE THREAD

**Issue by b52** [scikit-image/scikit-image#2407]
## Description

The documentation of [`peak_local_max`](http://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.peak_local_max) says nothing about the boolean variant of the `exclude_border` parameter, although it defaults to `True`. So it's unclear from the documentation what that is supposed to mean.

By looking at the corresponding [code](https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/peak.py#L115), one can see that `min_distance` is used for `exclude_border` when it is passed `True`.

**First improvement:** Update the corresponding documentation to make this invariant clear.

Additionally, I think the default value of `True` might lead to subtle problems, that people might not be aware of. For instance, I wasn't aware of this fact until now and just found it by visual inspection. My mental model of NMS doesn't seem to fit the default implementation of `peak_local_max`, which I find problematic.

**Second improvement:** Don't use `True` as default for `exclude_border`, instead use `0`.

**Comment by soupault** [comment]
Thanks for reporting this @b52 !

**Comment by b52** [comment]
So, what's the state on this one? I would be willing to write a PR for this.

**Comment by soupault** [comment]
@b52 regarding your issue message: I also find the results very difficult to understand (although from the implementation point of view they are pretty clear). We already faced this in https://github.com/scikit-image/scikit-image/issues/1831, https://github.com/scikit-image/scikit-image/issues/1832.

Unless you are willing to go deep into the function and significantly rework it, I'd suggest only to document the default behaviour more clearly (your Improvement#1), i.e. write that "...by default, if exclude_border is True, uses min_distance... bla-bla-bla". In that case, IMO, `True` is a good choice for the default value (better than `0`, `-1` or `None`).

**Comment by b52** [comment]
@soupault I disagree that `True` is a good default value for `exclude_border`. This is very counter intuitive and to my knowledge in no other NMS function used out there as a default.

**Comment by soupault** [comment]
@b52 Sorry, I wasn't clear. I meant that `True` is the best alternative among others with the same effect (border exclusion).
If you would like to change the default value, feel free to start the discussion. Or maybe we could converge on a PR with the brand new NMS algorithm with `exclude_border=False` :wink: ...

@jni @ahojnnes do you have any thoughts on this?

**Comment by b52** [comment]
I see, nonetheless I think `exclude_border` should be an effect the user had to opt in explicitly.

**Comment by jni** [comment]
@soupault @b52 Oops, this response has been sitting in an open tab for the past couple of days:

I agree with @b52 that `True` is not a good default value — it's a little too active/prescriptive. In the past, when we have tried to do such "good defaults", we've often gotten into trouble (e.g. sigma=1 and convert2lab=True for SLIC) and had to backtrack on the API. I think the worst case behaviour is better for do-nothing defaults — people who want the advanced behaviour can find it, otherwise the function does what it says it does and nothing more.

Having said that, I suggest a default of `False` (assuming we want to keep the bool option), as it reads a little better than 0. And yes, the documentation should definitely mention what bool options do.

**Comment by b52** [comment]
Alright, if it's fine with you guys I would write up an appropriate PR. Sounds good?

**Comment by b52** [comment]
@soupault Mind merging #2435 before that?

**Comment by soupault** [comment]
In accordance with the policy, it is all up to the 2nd reviewer. :)
