### ISSUE TITLE
Loading indexed png file.

### ISSUE THREAD

**Issue by warmspringwinds** [scikit-image/scikit-image#2408]
#Hello,

I have recently tried to an indexed png image in scikit-image, but didn't find a way to
make it using ```skimage.io``` ```imread```.

Basically if a png file is an indexed array, in matlab you can load it as two separate arrays. One of them
will be a one dimensional array and another one will represent a look up table which will map
each index to a unique color.

In matlab it can be done using:
```
[im, colormap] = imread('indexed.png');
```

Using PIL library:
```
from PIL import Image
import numpy as np
im = Image.open("image.png") # Replace with your image name here
indexed = np.array(im) 
```

There is more about this problem here:
http://stackoverflow.com/questions/33022983/read-in-an-indexed-color-image-in-python

Is it possible to do the same but using ```skimage.io``` ```imread``` and ```plugin``` argument, assuming
that I have PIL installed?

Thank you.

**Comment by caron** [comment]
Would love to see this implemented into `skimage.io` to keep to using one API and not mix in directly using `pillow`

**Comment by alexdesiqueira** [comment]
Hey @warmspringwinds @caron,
I'm truly sorry for not answering the issue before. I remember discussing embedded LUTs somewhere, but I don't exactly recall where... @scikit-image/core could someone help me on that? Thanks!

**Comment by grlee77** [comment]
copying the answer from the Discussion page back here:

> @stefanv
> The pillow approach outlined above is what I'd recommend (see also https://stackoverflow.com/a/33023875/214686). We are not planning on expanding the I/O functionality in skimage, so all feature suggestions should please be made at https://github.com/imageio/imageio
