### ISSUE TITLE
Documentation should present default values for optional parameters

### ISSUE THREAD

**Issue by alexdesiqueira** [scikit-image/scikit-image#2409]
Hi all,
the documentation for all functions should present the default values for optional parameters. This does not happen for several functions. One example is #2407.

In `feature.peak_local_max`, `exclude_border` is:
```
    exclude_border : int, optional
```
It could be:
```
    exclude_border : int, optional (default : True)
```
I think we should have this for every function, thus helping the user to check this values when using the `skimage` library.

**Comment by jni** [comment]
@alexandrejaguar this is by design, because they can (in most cases) be determined by introspection of the function signature. However, I just saw that NumPy's [how-to-document](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) allows specification of defaults — I'd thought that it recommended against them. I think it does make things more readable not to have to glance back and forth between the docstring and the function signature, so I'd be in favour of adding these defaults.

**Comment by JDWarner** [comment]
I'm :-1: on this because it's redundant.  IMO the best course would be to have NumPyDoc inspect the signature and pull in the info.

**Comment by alexandrejaguar** [comment]
@JDWarner I think this would make defaults clear and readable on an eventual help: `peak_local_max?`. Actually, there are some functions in `skimage` with this:
* `morphology.remove_small_objects(): min_size, connectivity, in_place`
* `segmentation.felzenszwalb(): multichannel`
How would NumPyDoc work?

**Comment by b52** [comment]
Just a side note, that the mentioned issue #2407 is problematic because the default value `True`, which is listed in the signature, is not properly explained. Only the `integer` variant is properly documented and rest is left unclear, so one has to consult the source code.

**Comment by alexandrejaguar** [comment]
@b52 you're right. I mentioned your issue because I was thinking on the documentation style in a while. It is unclear how to operate with the defaults on these functions at a glance. Several functions with a lot of parameters, such as `peak_local_max()`, would benefit from this.

**Comment by stefanv** [comment]
I don't think it would be too tricky to add; but it would be even better if we had a Default class, as suggested by Juan, so that we knew what the defaults were even if set to "None".

**Comment by sciunto** [comment]
@alexandrejaguar Would you mind opening issues to upstream projects to ask for this new feature?

**Comment by hmaarrfk** [comment]
I'm not sure I really agree with the general premise. The example showed a case where the default is presented by Sphinx in the signature. A little jarring, but the default value is presented. In more complicated cases, we do explain in words, so is there really an information issue.

The pr that closed that issue didn't require True to be stated, but it required explanation on the behaviour of true in the case it was set.

The challenge with redundancy is that it leads to inconsistency with the true behavior hard to guess.

Asking for a feature in numpy doc is probably the way to go. I played with introspection in 

https://github.com/hmaarrfk/wabisabi

It will work for non complicated use cases, but what about when the default is some list, or array that can't be put in the signature?

**Comment by alexandrejaguar** [comment]
Hey everyone. Is this something we'd like to see? I'm glad we're still discussing it, at least.
Hey @sciunto. What projects are we talking about? Numpy, as @hmaarrfk pointed?
@hmaarrfk maybe, to reduce redundancy, we could implement something as @stefanv suggested on his last comment. I honestly don't know how we could implement this to every function without brute force. Please help me here, ok?

**Comment by alexdesiqueira** [comment]
Closed due to lack of interest. Feel free to reopen if necessary.
