### ISSUE TITLE
Update sphinx-gallery before release 0.13

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2410]
As we patched sphinx-gallery embeded in scikit-image, we need to update the plugin before the release, either against their master branch or with their new release (should come soon).

See https://github.com/scikit-image/scikit-image/pull/2395

* A line has been added in TODO.txt. The task has to be removed from that file.
* Waiting for merge of https://github.com/sphinx-gallery/sphinx-gallery/pull/190
* Waiting for 0.1.8 or larger: https://github.com/sphinx-gallery/sphinx-gallery/releases

**Comment by soupault** [comment]
0.1.8 is out - https://github.com/sphinx-gallery/sphinx-gallery/releases/tag/v0.1.8 !

**Comment by sciunto** [comment]
Thanks for the ping, I'll take care of it.
