### ISSUE TITLE
Remove nose dependancies for our test suite

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2424]
Discussed on the Mailing List:
https://mail.python.org/pipermail/scikit-image/2016-December/005020.html

Nose is not maintained anymore and we have two major issues:
* #2414  DeprecationWarning for inspect.getargspec() in Python 3.5, expected to be broken in Python 3.6.
* #2127 skimage._shared tests not run 

One possibility is to switch to pytest

TODO list:

- [ ] Remove nose imports
- [ ] Check that tests in folders starting by an underscore are run
- [ ] Update the instructions in https://github.com/scikit-image/scikit-image/wiki/Testing-in-32-bit-environment (@soupault)

**Comment by souravsingh** [comment]
@sciunto Do we have to take care of anything while removing the nose imports?

**Comment by sciunto** [comment]
Of course, rewrite the tests that depend on nose.

**Comment by sarwatfatimam** [comment]
Hi, Is this issue solved? We were testing our code but we are getting depreciation warning as well. Is scikit-image migrated to Pytest?

**Comment by souravsingh** [comment]
@sarwatfatimam The issue is currently being fixed at #2468.

**Comment by sarwatfatimam** [comment]
Okay. Thank you.
