### ISSUE TITLE
Add `np.lookfor` as a discoverability tip to the User Guide

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#2426]
scikit-image's package structure is problematic for functions that span categories. For example, `watershed` segmentation is in morphology, because it is traditionally viewed as a morphological transformation. Conversely, `find_boundaries` is in segmentation, but some users have [looked for it](https://github.com/scikit-image/scikit-image/pull/2396#issuecomment-270022280) in morphology.

I've advocated for creating a flat scikit-image namespace before (https://github.com/scikit-image/scikit-image/issues/1608), but that discussion stalled when `np.lookfor` was [mooted](https://github.com/scikit-image/scikit-image/issues/1608#issuecomment-121798358) as an 80% solution.

However, that is a solution only for those who know about it. So, I propose that we add a section on API discovery to the [user guide](scikit-image.org/docs/dev/user_guide.html).

```python
import numpy as np
np.lookfor('boundaries', 'skimage')
```
or
```python
import skimage
np.lookfor('boundaries', skimage)
```

**Comment by alexandrejaguar** [comment]
@jni I think that's a nice idea!

**Comment by souravsingh** [comment]
@jni I am interested in working on the issue.

**Comment by jni** [comment]
@souravsingh Go for it! I'm not aware of anyone else working on it atm. Let us know if you need help!

**Comment by stefanv** [comment]
Should we provide `skimage.lookfor`?

```
def lookfor(search_text):
    return np.lookfor(search_text, sys.modules[__name__])
```

**Comment by alexandrejaguar** [comment]
@stefanv what about `skimage.util.lookfor`? :)

**Comment by stefanv** [comment]
Sure, although importing it to the `skimage` namespace seems like the first place a person would look for help.

**Comment by jni** [comment]
I agree with @stefanv, let's keep it as simple as possible.

**Comment by arjunsuri** [comment]
This is my first contribution.Where should I start?

**Comment by arjunsuri** [comment]
I want to contribute in this but this is my first ever conytibution. Please help me.

**Comment by souravsingh** [comment]
@arjunsuri There is a patch made already at #2639

**Comment by arjunsuri** [comment]
Please tell me where to start.I have learnt python and i really want to
contribute to scikit image.I am a complete newbie to open source.please
help.

**Comment by stefanv** [comment]
See https://github.com/scikit-image/scikit-image/pull/2713
