### ISSUE TITLE
16 bit image io in the upcomming version 0.13 

### ISSUE THREAD

**Issue by nadavhoresh** [scikit-image/scikit-image#2436]
## Description
Deprecating freeimage in favour of imageio as imread/imsave plugin leaves no way to read 16 bits image as uint16 or to write 16 bits image

## Way to reproduce
OS: Archlinux
Python version: 3.5/3.6
scikit-image version  0.13dev

**Comment by sciunto** [comment]
@nadavhoresh Could you give a minimal code to reproduce.

On my side,
```
import numpy as np
from skimage.io
a = np.zeros((4, 5), dtype=np.uint16)
io.imsave('/tmp/toto.tif', a, plugin='freeimage')
io.imread('/tmp/toto.tif')
```
works as intended.

**Comment by nadavhoresh** [comment]
Do you use 0.13 dev?

On Jan 8, 2017 8:11 PM, Fran?ois Boulogne <notifications@github.com> wrote:

@nadavhoresh<https://github.com/nadavhoresh> Could you give a minimal code to reproduce.

On my side,

import numpy as np
from skimage.io
a = np.zeros((4, 5), dtype=np.uint16)
io.imsave('/tmp/toto.tif', a, plugin='freeimage')
io.imread('/tmp/toto.tif')


works as intended.

-

**Comment by sciunto** [comment]
Of course.

**Comment by nadavhoresh** [comment]
This is my test:


Python 3.6.0 (default, Dec 24 2016, 08:03:08)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import skimage

In [2]: from skimage import io

In [3]: skimage.__version__
Out[3]: '0.13dev'

In [4]: img = io.imread('test.png', plugin='freeimage')
/usr/lib/python3.6/site-packages/skimage/io/_plugins/freeimage_plugin.py:6: skimage_deprecation: Call to deprecated function ``imread``. Use ``imageio plugin`` instead.
  def imread(filename):

In [5]: img.dtype
Out[5]: dtype('uint8')

In [6]: !identify test.png
test.png PNG 1276x956 1276x956+0+0 16-bit sRGB 4.544MB 0.000u 0:00.000

I see also in the file
 scikit-image-master/skimage/io/_plugins/freeimage_plugin.py that the calls are redirected to the imageio module.

Nadav.




________________________________

**Comment by soupault** [comment]
@nadavhoresh could you attach the image you used? This would help us to better understand the case.

**Comment by nadavhoresh** [comment]
Attached here an extract from the original image, in order to save space.


   Nadav.

________________________________

**Comment by sciunto** [comment]
@nadavhoresh it's not attached. You need to upload on the web interface.

**Comment by nadavhoresh** [comment]
Attaching a sample tile test.png (hope it is the proper way)
![test](https://cloud.githubusercontent.com/assets/8288049/21764370/645027cc-d66b-11e6-88a1-eab07653779d.png)

**Comment by soupault** [comment]
@nadavhoresh Did you mean to close?

**Comment by sciunto** [comment]
Same result on my side, with this image, it's converted in uint8.

**Comment by sciunto** [comment]
If I open the image with imagej or gimp, it's read as a 8 bit image...

**Comment by soupault** [comment]
```
In [5]: img
Out[5]: 
Image([[[  0,  47, 209, 255],
        [ 11,  47, 184, 255],
        [ 15,  51, 185, 255],
        ..., 
        [ 30,  72, 236, 255],
        [ 27,  70, 234, 255],
        [ 37,  71, 217, 255]]], dtype=uint8)

In [6]: !file test.png
test.png: PNG image data, 313 x 258, 16-bit/color RGBA, non-interlaced

In [7]: !identify test.png
test.png PNG 313x258 313x258+0+0 16-bit sRGB 485KB 0.000u 0:00.000
```

```
In [18]: img = img.astype(np.uint16)

In [20]: img.shape
Out[20]: (258, 313, 4)

In [21]: img[0,0,0] = 20000

In [24]: io.imsave(arr=img, fname='test16.png', plugin='imageio')
/home/egor/workspace/scikit-image/skimage/io/_io.py:132: UserWarning: test16.png is a low contrast image
  warn('%s is a low contrast image' % fname)
/usr/lib/python3.6/site-packages/imageio/core/util.py:81: UserWarning: Lossy conversion from uint16 to uint8, loosing 8 bits of resolution
  warn('Lossy conversion from uint16 to uint8, '
```

**Comment by nadavhoresh** [comment]
*   Reading the image with gimp 2.9.x and clicking on Image->Precision you get 16 bit (I think that gimp 2.8 does not support 16 bit processing).
  *   Using skimage 12.x imread(f'test.png', plugin='freeimage') or via opencv: cv2.imread('test.png', cv2.IMREAD_ANYDEPTH+cv2.IMREAD_ANYCOLOR) results in a uint16 dtype image.

Nadav

________________________________

**Comment by soupault** [comment]
@nadavhoresh see https://github.com/imageio/imageio/issues/204 (and, especially, https://github.com/imageio/imageio/issues/204#issuecomment-271566703).
For the moment, you can use `freeimage` from `imageio`.

**Comment by OrganicIrradiation** [comment]
As @soupault mentioned, 48-bit (16-bit/channel RGBA) PNGs can be imported with imageio by specifying the format. See: https://github.com/imageio/imageio/issues/146#issuecomment-281509008

**Comment by mehditlili** [comment]
The fact that this issue is closed referring to using imageio is just ridiculous. Why isn't this considered as a valid issue?

**Comment by hmaarrfk** [comment]
I can't speak for what was done in 2017. But I think the sentiment was that skimage should probably not focus too much on loading and writing images.

In the upcoming version, imageio is now a dependency of skimage and will be the default way to load and save images.

https://github.com/scikit-image/scikit-image/pull/3126

**Comment by jni** [comment]
@mehditlili to reiterate what @hmaarrfk said, in the long term, scikit-image might offload *all* IO functionality to imageio. It simply makes more sense to separate the concerns of IO and analysis, rather than have seven separate implementations of imread, each with slightly different properties. Therefore, we won't actually devote effort to fixing this in scikit-image. It needs to be fixed either in imageio or in Pillow (not sure which).

**Comment by mehditlili** [comment]
@jni thanks for the clarification. In imageio it works well already. Looking forward to having it as default image reader for sickit-image

**Comment by OrganicIrradiation** [comment]
@mehditlili and @jni, has 16-bit reading/writing been addressed in imageio?

For many image formats, imageio is a wrapper for Pillow, so it comes with all of the same limitations including not being able to load multichannel (e.g., RGB) 16-bit PNGs. The only way to do that is via the freeimage backend, which requires loading/installing a separate dependency: https://github.com/imageio/imageio/issues/204
