### ISSUE TITLE
Allow rectangular window sizes in threshold_niblack and threshold_sauvola

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#2442]
## Description
The functions `filters.threshold_{niblack,sauvola}` accept a `window_size` parameter, which defines a square/cubic window along which to threshold. However, any cuboid shape would work fine, and would be desirable e.g. in anisotropic 3D data, or even in 2D data where the lighting changes more rapidly along one dimension than the other.

**Comment by souravsingh** [comment]
Is a fix for this submitted in #2441?

**Comment by jni** [comment]
@souravsingh no, that is only a bug fix. #2441 is critical to get merged before 0.13, whereas the added convenience of rectangular/cuboid window is a luxury that can wait.

**Comment by aqsaahmed** [comment]
According to this issue, do we need to work on the window_size parameter for 2D & 3D data, to decide accordingly what would be the window size for these?

**Comment by soumyag213** [comment]
I want to attempt this

**Comment by sarwatfatimam** [comment]
Is there any particular reference work (this issue points to) on 2D or 3D window sizes for local thresholding techniques?

**Comment by jni** [comment]
Hi all,

If you look at the code for `threshold_niblack` and `threshold_sauvola`, you'll see that the window-size parameter accepts only an integer. The idea here would be to accept a tuple with the same number of elements as the input image has dimensions. So, for example, `window_size=(3, 5)` would create a window of 3 rows by 5 columns. `window_size=(3, 15, 15)` would create a 3D window size of 3 planes by 15 rows by 15 columns. (Please refer to our documentation on [coordinate conventions](http://scikit-image.org/docs/dev/user_guide/numpy_images.html#coordinate-conventions), too.

This is the same way that Gaussian filter accepts both a single sigma as well as a tuple sigma.

I hope this helps!

**Comment by sarwatfatimam** [comment]
Thank you, Juan.  It did help.

**Comment by sinha-kirti** [comment]
I want to attempt this.

**Comment by meriki** [comment]
@sinha-kirti we are already working on this.

**Comment by sinha-kirti** [comment]
Alright! Please let me know if you require any help.

**Comment by alexandrejaguar** [comment]
Hi @sarwatfatimam and @meriki, have you had any progress in this one? Thanks!
