### ISSUE TITLE
HOG visualization should use midpoints of bins

### ISSUE THREAD

**Issue by vnavkal** [scikit-image/scikit-image#2453]
## Description
The HOG visualization draws lines that are perpendicular to the edges of orientation bins.  It would be clearer if the lines were perpendicular to the _midpoints_ of bins, instead of the edges.

For example, if `hog` is applied with two orientation bins (`orientations=2`) to the image on the left below (reproducible by the code below), I would have expected the visualization to produce something looking like "concentric diamonds."  But it instead looks like the image to its right.

![comparison](https://cloud.githubusercontent.com/assets/5924638/21959910/293b0192-da8b-11e6-8ba9-c72c5085a368.png)

If others agree that this would be a worthwhile change, I'd be happy to work on a pull request for it.

## Way to reproduce
Here is the code to reproduce the images above:
```python
import numpy as np
from matplotlib import pyplot as plt
from skimage.feature import hog

X,Y = np.mgrid[-256:256,-256:256]
image = np.sqrt(X**2 + Y**2)
_, hog_image = hog(
    image,
    orientations=2,
    pixels_per_cell=(32, 32),
    cells_per_block=(1, 1),
    visualise=True
)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))
ax1.imshow(image, cmap=plt.cm.gray, interpolation='nearest')
ax2.imshow(hog_image, cmap=plt.cm.gray, interpolation='nearest')
```
(I'm using Python 3.5.2, scikit-image 0.12.3)

**Comment by soupault** [comment]
@vnavkal could you provide some image (from Google, for example) of your proposed version, please?

**Comment by vnavkal** [comment]
Sure, I propose for the visualization to generate an image like the one below, when `orientations=2`.
![comparison](https://cloud.githubusercontent.com/assets/5924638/21994811/6a615d1e-dbd6-11e6-8a31-4214d0297a3e.png)

When it is run with `orientations=2`, as above, the HOG function groups gradients into two bins:
* one bin contains gradient vectors lying in the (+x, +y) and (-x, -y) quadrants
* the other bin contains gradient vectors lying in the (-x, +y) and (+x, -y) quadrants

The current visualization scheme associates a horizontal line segment with the first bin and a vertical line segment with the second.

I propose that instead the first bin should be associated with a line segment of slope -1, and the second bin should be associated with a line segment of slope 1.  Each line segment would then better represent the range of gradient vectors that could fall into its bin.

**Comment by stefanv** [comment]
@vnavkal But would you then just bias the gradient directions in the diagonal directions?  I think what you want is `orientations=4`.

**Comment by vnavkal** [comment]
> @vnavkal But would you then just bias the gradient directions in the diagonal directions?

I'm not sure I understand what this means, maybe you could elaborate a little?  If I understand correctly, the visualization is meant to display lines that are roughly orthogonal to the gradient directions, and my proposed visualization comes closer to doing that than the current implementation.

> I think what you want is `orientations=4`.

This wouldn't give me the visualization I generated; instead, it would produce the following.
![hog_4_orientations](https://cloud.githubusercontent.com/assets/5924638/23052098/807e97ae-f483-11e6-85fc-6533029b9433.png)

@stefanv I have a feeling I'm missing something in your comment; please let me know if this doesn't clarify things.

**Comment by stefanv** [comment]
@vnavkal That's convincing!  Want to make a PR to address this?

**Comment by vnavkal** [comment]
Sure, I'll create a PR to change it, thanks!
