### ISSUE TITLE
Wavelet denoising fails on odd-sized dimension images

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2463]
From @grlee77 https://github.com/scikit-image/scikit-image/pull/2461#issuecomment-273717628

If you truncate the odd-sized dimension from 451 to 450 this issue will not occur.  This is a known issue with odd-sized inputs with `dwtn/idwtn` (https://github.com/PyWavelets/pywt/issues/80)

The proper fix is probably for to have `denoise_wavelet` itself either:
- [ ] raise an error if any non-channels dimension of the input has odd size

@stsievert Would you like to fit that in a new PR?

**Comment by grlee77** [comment]
see #2462 for a simple solution that will work for arbitrarily sized inputs
