### ISSUE TITLE
Fix the name of code coverage tool in Contributing Guidelines

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2471]
## Description
Change `coveralls` to `codecov`. Fix the link correspondingly.

See http://scikit-image.org/docs/dev/contribute.html#activate-travis-ci-for-your-fork-optional 

**Please, do not submit a PR until https://github.com/scikit-image/scikit-image/pull/2468 is merged to avoid conflicts.**

**Comment by rishikksh20** [comment]
I am up for this.
