### ISSUE TITLE
Memory Management of Created Images with Scikit Image

### ISSUE THREAD

**Issue by pfigliozzi** [scikit-image/scikit-image#2475]
I am working on some trajectory analysis of objects in images using python in a Jupyter notebook. In order to help me understand what is going on in a certain frame (or series of frames) I wrote a function that will create a stack of images that show my trajectories and display them so I can flip through frame by frame to see where the objects are moving similar to [this](http://i.imgur.com/CcuuYYz.png). The problem is that calling the function uses up memory to create the images and display them but that memory is not released or garbage collected after the function ends. This means that if I call the function too many times in my notebook then my OS (Windows) will run out of memory. The only solution I have found so far is to restart the notebook kernel every so often once the python memory limit approaches the maximum in my computer.

I have included a modified version of the function (leaving only the important parts) to show what I am doing. The input is a pandas data frame that contains information about the frame, x position, and y position of each of the objects. I found it easier to use PIL (pillow) to create the images and draw objects on a new image. Finally I use skimage's CollectionViewer which pops open a new window where I can view the image stack and flip through the frames. Then I close the window and go back to doing some analysis in the the Jupyter notebook and call the function again later after some more analysis.

```python
from PIL import Image
from PIL import ImageDraw
import pandas as pd
import skimage

def view_trajectories(data_frame, obj_size=6.0, image_size=(380,380)):
    """Visualize all the trajectories in the data frame

    :param data_frame: the data_frame that contains the trajectory information
    :param obj_size: the size of each object to draw (in pixels)
    :param image_size: Tuple containing the size of the original image
    """

    image_frames = []
    for frame, grp in data_frame.groupby('frame'):
        # Create and new PIL Image Object to draw object on
        img_frame = Image.new('RGB', image_size, 'black')
        img_draw = ImageDraw.Draw(img_frame)

        for idx, obj in grp.iterrows():
            # Draw a circle for a object in each frame
            ellipse_bb = [tuple(obj['x pos':'y pos'].values-obj_size),
                          tuple(obj['x pos':'y pos'].values+obj_size)]
            img_draw.ellipse(ellipse_bb, outline='red')

        # Convert image to array and display it
        image_frame_array = np.array(img_frame)
        img_frame.close()
        image_frame_array = image_frame_array/255.0
        image_frames.append(image_frame_array)

    skimage.viewer.CollectionViewer(image_frames).show()
```
Like I said, ideally I would like to call this function whenever I need to get an idea what the trajectories are doing while I am analyzing them in my Jupyter notebook but release the memory for later use. I have even tried forcing a garbage collect using `gc.collect()`. Is there something I am missing here?

**Comment by stefanv** [comment]
Python should free your memory, but if `gc.collect` doesn't work, I don't know what else we can do.  I'm sorry that I can't help, but this is outside the scope of skimage, and you may be better off asking @fabianp, @carreau, or @ivanov

**Comment by fabianp** [comment]
You might be able to localize the line that is consuming most memory using memory profiler (https://pypi.python.org/pypi/memory_profiler)

**Comment by Carreau** [comment]
IPython get a hold of returned results in its history. Try clearing the `Out` and `In` variables, and look at the `%who` and `%who_ls` magic to see where the memory is.

**Comment by jni** [comment]
@Carreau would adding a semicolon to `.show();` stop IPython from caching that value?

**Comment by Carreau** [comment]
> @Carreau would adding a semicolon to .show(); stop IPython from caching that value?

likely no. IPython only cache the value of the last expression of a cell. If it's in a function a `;` will have no effects. My guess is that  the cell display something that get cached by IPython and indirectly keep a ref to a large object. 

I'll see if I can reproduce with a dummy example.

**Comment by Carreau** [comment]
That does not seem to seem to be IPython's fault: 

```
import numpy as np
from PIL import Image
from PIL import ImageDraw
import skimage.viewer
from weakref import ref 

class List(list): #builtins list does nto allow weakref
    pass
def view_trajectories(obj_size=6.0, image_size=(380,380)):
    """Visualize all the trajectories in the data frame

    :param data_frame: the data_frame that contains the trajectory information
    :param obj_size: the size of each object to draw (in pixels)
    :param image_size: Tuple containing the size of the original image
    """

    image_frames = List()
    r0 = ref(image_frames, lambda w: print(f">>> image_frames not finalized <<<"))

    img_frame = Image.new('RGB', image_size, 'black')

    r1 = ref(img_frame, lambda w: print("img_frame finalized"))
    img_draw = ImageDraw.Draw(img_frame)
    r2 = ref(img_draw, lambda w: print("img_draw finalized"))

    image_frame_array = np.array(img_frame)
    r3 = ref(image_frame_array, lambda w: print("image_frame_array finalized"))
    img_frame.close()
    image_frame_array = image_frame_array/255.0
    image_frames.append(image_frame_array)
    
    viewer =  skimage.viewer.CollectionViewer(image_frames)
    viewer.show()
    r4 = ref(viewer, lambda w: print(">> viewer not finalized <<< "))
    return r0

wref = view_trajectories()
```

the viewer seem to keep a ref to image_frames and the viewer itself it not gc'd

I maneged to get references to stuff like dict of  `_blit_manager`, `_event_manager`;  `<skimage.viewer.viewers.core.CollectionViewer at 0x10df5c4c8>` and `<bound method CollectionViewer.update_index of <skimage.viewer.viewers.core.CollectionViewer object at 0x10df5c4c8>>`

and that's definitively reproducible in plain python with `python -i  <file with above code>` so that's definitively not IPython.
