### ISSUE TITLE
Implement unsharp masking

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2477]
http://homepages.inf.ed.ac.uk/rbf/HIPR2/unsharp.htm

For color images, first convert to HSV and only apply sharping to value channel.

## Additional references

- http://ieeexplore.ieee.org/abstract/document/826787/

**Comment by soupault** [comment]
Implemented via https://github.com/scikit-image/scikit-image/pull/2772, https://github.com/scikit-image/scikit-image/commit/372c393176af42443a64eddd5f44f0547addcfad.
