### ISSUE TITLE
Failure to import the segmentation from skimage

### ISSUE THREAD

**Issue by xfsm1912** [scikit-image/scikit-image#2483]
## Description
I just install the scikit-image lib by anaconda. I want to test the function of segmentation of skimage. So I download the "plot_ncut.ipynb" from (http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_ncut.html#sphx-glr-auto-examples-segmentation-plot-ncut-py). But I cannot run this notebook. 

As I run the ipy file, it returns:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-5078c863f30e> in <module>()
----> 1 from skimage import data, segmentation, color
      2 from skimage.future import graph
      3 from matplotlib import pyplot as plt
      4 
      5 

/Users/Jianhua/anaconda/lib/python2.7/site-packages/skimage/segmentation/__init__.py in <module>()
      1 from .random_walker_segmentation import random_walker
      2 from .active_contour_model import active_contour
----> 3 from ._felzenszwalb import felzenszwalb
      4 from .slic_superpixels import slic
      5 from ._quickshift import quickshift

/Users/Jianhua/anaconda/lib/python2.7/site-packages/skimage/segmentation/_felzenszwalb.py in <module>()
      2 
      3 from .._shared.utils import warn
----> 4 from ._felzenszwalb_cy import _felzenszwalb_grey
      5 
      6 

ImportError: cannot import name _felzenszwalb_grey
```

## Way to reproduce
- [x] Code example
from skimage import segmentation
- [x] Relevant images (if any)
img = data.coins()
- [x] Operating system and version
mac sirera 12.10.3
- [x] Python version
2.7
- [x] scikit-image version (run `skimage.__version__`)
0.12.3

If someone can help me, thank you very much.

**Comment by sciunto** [comment]
Weird. Looks similar to https://github.com/scikit-image/scikit-image/issues/401

Could you try to reinstall as suggested please?

**Comment by sciunto** [comment]
@xfsm1912 What's the status of this issue please?

**Comment by xfsm1912** [comment]
I have solved this issue, thank you

**Comment by invernoa** [comment]
How did you fix it?

**Comment by jni** [comment]
Hi @jh0w3l05 

scikit-image needs a whole bunch of compiled binary files to work. As do e.g. pandas and SciPy. That's why PyInstaller has issues like this: 

https://github.com/pyinstaller/pyinstaller/issues/3422

You probably need a fix like this:

https://stackoverflow.com/questions/33001327/importerror-with-pyinstaller-and-pandas/36146649#36146649

that crawls the scikit-image path and grabs all the C compiled binaries. As an alternative, you can add hiddenimports to your PyInstaller .spec file, just like for pandas in the issues above:

```
hiddenimports = ['skimage.segmentation._slic']
```

I think this might fix your problem, but it's impossible to know. It is a PyInstaller error, not a scikit-image error.

**Comment by jh0w3l05** [comment]
@jni Thanks for the response.
I did the following but still NO luck.
- add hiddenimports in .spec file
- add hook-skimage file with ALL the .pyd in skimage in the PyInstaller hooks directory
- even followed this implementation
  https://stackoverflow.com/questions/33001327/importerror-with-pyinstaller-and-pandas/36146649#36146649

**Comment by jni** [comment]
@jh0w3l05 

The first thing you need to check is whether skimage works outside of PyInstaller? If not, then you need to compile it. That is, from anaconda prompt, can you run `python -c "from skimage.segmentation import slic"`?

If not, then it means you need to build scikit-image from source or install the correct bundle (such as using `conda install scikit-image`). See our installation instructions here: http://scikit-image.org/docs/dev/install.html

If it does work, then it is a PyInstaller issue, and you should ask for help there: either on [StackOverflow with the PyInstaller tag](https://stackoverflow.com/questions/tagged/pyinstaller) or on their [github repo](https://github.com/pyinstaller/pyinstaller)
