### ISSUE TITLE
Fix gallery examples to work correctly with matplotlib 2.0

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2486]
## Description
The following examples look pretty bad with the update of `matplotlib` to 2.0 and should be updated:

- http://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_regional_maxima.html (all viridis :man_facepalming: );
- http://scikit-image.org/docs/dev/auto_examples/edges/plot_marching_cubes.html (one blob);
- http://scikit-image.org/docs/dev/auto_examples/filters/plot_entropy.html (plot [1,3]).

**Comment by alexandrejaguar** [comment]
@soupault do you attribute this issue to the new default colormap, `viridis`? If this is the case, changing the colormap on these examples should solve it, right?

**Comment by soupault** [comment]
@alexandrejaguar yes, exactly. Should investigate better the 2nd case (marching cubes) though.

**Comment by alexandrejaguar** [comment]
@soupault I could start working on that in approx. 10 days :)

**Comment by jni** [comment]
@soupault can you elaborate on what you think looks bad on the first and last entries? I think viridis looks great in this context.

**Comment by soupault** [comment]
@jni 
Hmm... Alright, OK for 3rd case. Regarding the 1st - even if it represents the results of the processing quite well, it looks very unnatural to me and hard to interprete. I think that the old grayscale version would be much easier to perceive.

**Comment by alexandrejaguar** [comment]
@soupault @jni what about using `magma` in the 3rd example? :) Please check this fix.

**Comment by soupault** [comment]
> I could start working on that in approx. 10 days

@alexandrejaguar Well scheduled! :+1: 

Fixed via #2504 .
