### ISSUE TITLE
Does scikit-image provide SIFT and SURF methods 

### ISSUE THREAD

**Issue by kirk86** [scikit-image/scikit-image#2488]
Hi everyone, I was wondering whether scikit-image provides a method to compute sift and surf features? Is that possible at the moment?

Thanks!

**Comment by soupault** [comment]
@kirk86 Hi! No, we do not ship these detectors. For more information see https://github.com/scikit-image/scikit-image/blob/master/skimage/io/sift.py#L14-L23 .

**Comment by kirk86** [comment]
@soupault thanks

**Comment by joshualmitchell** [comment]
The patent expired on SIFT recently. ^^

**Comment by soupault** [comment]
@joshualmitchell we are waiting for a volunteer - https://github.com/scikit-image/scikit-image/issues/4499 :wink: .
