### ISSUE TITLE
Add a section to the user guide, showing how to interact between skimage and opencv

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2500]
See also http://stackoverflow.com/questions/16156788/how-can-i-convert-images-from-scikit-image-to-opencv2-and-other-libraries/16168076?noredirect=1#comment71528270_16168076

**Comment by aksh98** [comment]
I would like to work on this. Can I ?

**Comment by soupault** [comment]
@aksh98 There is work on this in #2519 already. You are welcome to contribute there.

**Comment by soupault** [comment]
Closed via #2519
