### ISSUE TITLE
Expose truncate parameter in skimage.filters.gaussian

### ISSUE THREAD

**Issue by cancan101** [scikit-image/scikit-image#2501]
[`skimage.filters.gaussian`](http://scikit-image.org/docs/dev/api/skimage.filters.html#skimage.filters.gaussian) calls into [`scipy.ndi.gaussian_filter`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.ndimage.filters.gaussian_filter.html#scipy.ndimage.filters.gaussian_filter), however the underlying function takes in a `truncate` parameter, but this is not exposed in `skimage`.

**Comment by soupault** [comment]
@cancan101 Hi! Feel free to submit a PR!

**Comment by sciunto** [comment]
It will require scipy 0.14. We will need to merge #2254 before. I agree with @soupault If you want to submit a PR, feel free :)

**Comment by soupault** [comment]
>It will require scipy 0.14

Hmm, why? There are ways to pass arguments without being explicit.

**Comment by sciunto** [comment]
OK, we can always rewrite the function to make [0.13 and lower work](https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.ndimage.filters.gaussian_filter.html#scipy.ndimage.filters.gaussian_filter), but if we want to take the easiest slope, with [0.14](https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.ndimage.filters.gaussian_filter.html#scipy.ndimage.filters.gaussian_filter) it's as easy as adding two lines and we are close to bump scipy's version.

Frankly, I'm not a big fan to add code for workarounds when it could be avoided as it increases the effort both at the implementation stage and for maintenance.

**Comment by jni** [comment]
We now require 0.17! =)
