### ISSUE TITLE
Object Detection Process

### ISSUE THREAD

**Issue by ErenPhayte** [scikit-image/scikit-image#2502]
Hi,

I am busy building an app where you can put an object in front of a solid colour (or other) and will automatically detect the object and "crop" it in the app (or crop the background out) - you can then put a background image behind the object i.e. for argument sake say, you can stand in front of a green screen, and it will automatically crop the green and place a background image of a mountain. 

I am going through all the documents, but unable to figure out the best process to achieve this.

**Comment by soupault** [comment]
Hi @ErenPhayte !
Franky speaking, I'm sure what `all the documents` means, but there is a massive amount of papers and books on these matters in the web.
What you are describing in your message are two quite different classes of computer vision problems: object detection, and object segmentation. For the latter we have plenty of different methods already implemented (see http://scikit-image.org/docs/dev/api/skimage.segmentation.html), although the detection is typically a more complex task and, at the moment, is presented only by http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_label.html and https://github.com/scikit-image/scikit-image/pull/1570.
If you introduce additional constraints to you image acquisition system, you could potentially solve the described tasks using simpler multi-stage pipeline.

Don't hesitate to look through our comprehensive gallery of examples: http://scikit-image.org/docs/dev/auto_examples/ . Probably you could find the solution to your problem there.

You can also search the web using these keywords, investigate OpenCV algorithms, ITK, ImageJ, etc.

P.S. GitHub is not the best place to post the questions, we use it mostly as a bug-tracker and for other matters of development. For general questions, please, consider using our mailing list (https://mail.python.org/mailman/listinfo/scikit-image) and/or StackOverflow (most of us monitor it for questions tagged with `scikit-image`).

Closing the issue, but feel free to continue the discussion here.

**Comment by ErenPhayte** [comment]
Thanks so much Egor, for the quick response. Will look through the links
you sent. The closes example that I was using was the tinting example
using entropy, but didn't think to look at the segmentations.

Appreciate the support and apologies for logging this here, I did join the
google group but didnt have the option to create a topic.

**Comment by soupault** [comment]
@ErenPhayte Please, use the link above to join the mailing list.
The one on GoogleGroups is old, and is not maintained anymore.
