### ISSUE TITLE
Add AppVeyor to wheel builder repository

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2514]
And produce wheels for 3.4, 3.5, 3.6

https://github.com/scikit-image/scikit-image-wheels

**Comment by andrewleech** [comment]
Now that scipy has official wheel for windows this would be really great!

http://wheels.scipy.org/scipy-1.0.0-cp35-none-win_amd64.whl
https://pypi.python.org/pypi/scipy/1.0.0
https://github.com/scipy/scipy/pull/7616

**Comment by stefanv** [comment]
AppVeyor already builds wheels and saves them, FWIW.

**Comment by andrewleech** [comment]
Ah whoops, I missed there is the appveyor definition file in the repo.  
Badges to link to the travis and appveyor projects would be great in the README.md

What would it take to get these builds onto http://wheels.scipy.org and pypi?

**Comment by stefanv** [comment]
I think adding this to scikit-image-wheels, like you proposed, is the correct solution.  @matthew-brett ?

**Comment by andrewleech** [comment]
Any chance of this getting a closer look?

**Comment by matthew-brett** [comment]
Oh - whoops - sorry - I didn't see this before.  @andrewleech - any chance of a PR to scikit-image/scikit-image-wheels pulling across the appveyor file?

**Comment by andrewleech** [comment]
@stefanv I've added a (possibly naive) AppVeyor config for the wheels builder project.
I haven't used appveyor before (I use gitlab ci for everything) so I expect there to be some basic mistakes... ? 
Does it make sense to add this to your existing AppVeyor account?
