### ISSUE TITLE
hough_circle_peaks absent from conda and pip installations?

### ISSUE THREAD

**Issue by calocedrus** [scikit-image/scikit-image#2521]
## Description
Can't import hough_circle_peaks from skimage.transform

## Way to reproduce
Install scikit-image from anaconda and:
```
>>> from skimage.transform import hough_circle_peaks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'hough_circle_peaks'
```
I've tried in a different anaconda environment to install it with pip but got the same import error.
Upon closer inspection of `transform.py` in `anaconda3/pkgs/scikit-image-0.12.3-np111py35_1/lib/python3.5/site-packages/skimage/transform` I've found no hough_circle_peaks function.
Is it possible to directly replace the (outdated?) `transform.py` by the one in this scikit-image github (didn't seem to work)?
If not, how to install scikit-image directly from source in a given anaconda environment?
- [ ] Operating system and version
linux, ubuntu 16.04
- [ ] Python version
3.5
- [ ] scikit-image version (run `skimage.__version__`)
```
>>> import skimage
>>> skimage.__version__
'0.12.3'
```

**Comment by soupault** [comment]
Hi @calocedrus ! `hough_circle_peaks` is a very new addition (see https://github.com/scikit-image/scikit-image/pull/2109, 5 days ago), therefore it is not presented in `skimage 0.12.x`.
To use development version in conda environment, you need to [1] activate the environment, [2] install `skimage` from sources as described in http://scikit-image.org/docs/stable/install.html#running-the-development-version .
Let us know if you face any issues.

@sciunto very useful addition, it seems :wink: .
