### ISSUE TITLE
Swirl center coordinates are reversed

### ISSUE THREAD

**Issue by adius** [scikit-image/scikit-image#2523]
```py
from skimage import data, transform, io

swirled = transform.swirl(
    image=data.text(),
    center=(224, 86),
    strength=5,
    mode='reflect',
)

io.imshow(swirled)
io.show()
```

This gives the correct result:

![figure_1](https://cloud.githubusercontent.com/assets/969983/23105342/b6952ec6-f6d5-11e6-93c2-12aed3fc95fe.png)

However, it shouldn't as the center coordinates are reversed. They are (column, row) but should be (row, column).

**Comment by adius** [comment]
Mh, sounds like a complicated problem. Maybe we can at least fix the documentation in the meantime, or do you want to keep it broken in order to be able to fix it later instead of having to announce a breaking change by reversing the coordinates 😂🙈

**Comment by stefanv** [comment]
Yes, monkey-covering-face-with-hands is about right :/  We'll get this sorted, but in the mean time kindly file a documentation patch.
