### ISSUE TITLE
Draw circle returns AttributeError

### ISSUE THREAD

**Issue by alexandrejaguar** [scikit-image/scikit-image#2534]
## Description
`skimage.draw.circle`does not work for me anymore. Could you check it, please?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-146-f48324c65cfc> in <module>()
----> 1 rows, cols = circle(0, 0, radius=10)

/home/jaguar/Documents/git-repos/scikit-image/skimage/draw/draw.py in circle(r, c, radius, shape)
    132            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)
    133     """
--> 134     return ellipse(r, c, radius, radius, shape)
    135 
    136 

/home/jaguar/Documents/git-repos/scikit-image/skimage/draw/draw.py in ellipse(r, c, r_radius, c_radius, orientation, shape)
     66     center = np.array([r, c])
     67     radiuses = np.array([r_radius, c_radius])
---> 68     orientation = np.radians(orientation)
     69 
     70     # The upper_left and lower_right corners of the

AttributeError: 'NoneType' object has no attribute 'radians'
```

## Way to reproduce
One example:

    rows, cols = circle(0, 0, radius=10)

## Possible fix
I believe it could be fixed passing `orientation=0` to `skimage.draw.circle`, on

    return ellipse(r, c, radius, radius, shape)

`skimage.draw.ellipse` works fine.

[If reporting a bug, please include the following important information:]
- [X] Code example
- [ ] Relevant images (if any)
- [X] Operating system and version: Debian Linux, Stretch (current testing)
- [X] Python version: Continuum Anaconda, Python 3.6
- [X] scikit-image version: `0.13dev`

**Comment by stefanv** [comment]
Seems to work OK over here.

**Comment by alexandrejaguar** [comment]
@stefanv updated to the last version:
```
git checkout master
git pull
python setup.py build_ext -i
```
and... it worked. My `skimage.draw` wasn't updated.
Sorry about that :)
