### ISSUE TITLE
Clip option of downscale_local_mean has no effect

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2535]
in skimage.transform, the clip option of downscale_local_mean has obviously no effect and is not documented.

In addition, a note in the documentation saying that it's a wrapper around `measure.block_reduce` with a function np.mean would be a nice addition as well.

**Comment by stefanv** [comment]
This is because local averaging cannot give you values higher than the image content, so I think the behavior is correct for a consistent API.

**Comment by sciunto** [comment]
@stefanv I would say that clip has to be removed. Is that what you mean also?

**Comment by rfezzani** [comment]
Can be closed since `down_scale_local_mean`'s doc stipulates now:
>    clip : bool, optional
>        Unused, but kept here for API consistency with the other transforms
>        in this module. (The local mean will never fall outside the range
>        of values in the input image, assuming the provided `cval` also
>        falls within that range.)

**Comment by stefanv** [comment]
Thanks for the update, @rfezzani!
