### ISSUE TITLE
richardson_lucy returns NaN

### ISSUE THREAD

**Issue by radjkarl** [scikit-image/scikit-image#2551]
Hi guys,

I think there is a bug in your Richardson-Lucy implementation:

https://github.com/scikit-image/scikit-image/blob/master/skimage/restoration/deconvolution.py
line 389
`relative_blur = image / convolve_method(im_deconv, psf, 'same')`

as soon as  [image] contains 0, more and more NaN will be created and propagated due to convolution.
on my PC (win7, 64bit, anaconda py3.5) the given test case doe not work because of this.

##FIX
add  behind line 389
`relative_blur[np.isnan(relative_blur)] = 0`

Cheers,
Karl

**Comment by meriki** [comment]
@radjkarl I'm trying to solve this issue. Could you please give the test case where it fails?

**Comment by radjkarl** [comment]
Hi @meriki,
As it looks like,  the issue is already fixed: #2551 #2552
Can you please try the test case provided in the docstring?
Alternatively any input image with values=0 should work.

**Comment by meriki** [comment]
@radjkarl #2252 is closed. Look at #2253. A reviewer was asking for a test case where the old code fails. With all 0s as input, no NaNs are being generated. Following is the output. 
![image](https://cloud.githubusercontent.com/assets/17230557/23664117/6eea9484-0333-11e7-8ff0-acca67283a7a.png)

**Comment by radjkarl** [comment]
@meriki:
I tried the test case again. it workes - my fault.

BUT:
please add 'clip=False' to the docstring example.
since the input image is 0-255
and clip=True by default

the output image would be elsewise ==1

`import numpy as np
from skimage import color, data, restoration
from scipy.signal import convolve2d
import pylab as plt


camera = color.rgb2gray(data.camera())
psf = np.ones((5, 5)) / 25
camera = convolve2d(camera, psf, 'same')
camera += 0.1 * camera.std() * np.random.standard_normal(camera.shape)
#####added clip=False
deconvolved = restoration.richardson_lucy(camera, psf, 5, clip=False)

plt.imshow(deconvolved)
plt.show()
`

**Comment by aswalters** [comment]
I encountered this bug as well when trying to use this function to calculate maximum intensity values using a saturated psf. If you would like I can try and reproduce the bug using different input but below is the proper solution to just fix the code so this can never happen.

The solution is to use machine epsilon:

`eps = np.finfo(image.dtype).eps`
`x = convolve_method(im_deconv, psf, 'same')`
`np.place(x, x==0, eps)`
`relative_blur = image / x + eps`

**Comment by stefanv** [comment]
@aswalters Your solution looks like a very typical approach taken when applying inverse filters.  Can you please provide a failing test and make a PR?  We'd appreciate that very much, thank you.
