### ISSUE TITLE
Minor Omission from Morphology Module

### ISSUE THREAD

**Issue by nzoghb** [scikit-image/scikit-image#2554]
## Description
While working on #2538 I noticed that in `skimage.morphology`'s `__init__.py`, the `star` function is not being included under `__all__`.

Relevant code ([found here](https://github.com/scikit-image/scikit-image/blob/master/skimage/morphology/__init__.py)):

`from .selem import (square, rectangle, diamond, disk, cube, octahedron, ball,
                    octagon, star)`

`__all__ = ['binary_erosion',
           'binary_dilation',
           'binary_opening',
           'binary_closing',
           'erosion',
           'dilation',
           'opening',
           'closing',
           'white_tophat',
           'black_tophat',
           'square',
           'rectangle',
           'diamond',
           'disk',
           'cube',
           'octahedron',
           'ball',
           'octagon',
           'label',
           'watershed',
           'skeletonize',
           'skeletonize_3d',
           'thin',
           'medial_axis',
           'convex_hull_image',
           'convex_hull_object',
           'reconstruction',
           'remove_small_objects',
           'remove_small_holes']`

**Comment by soupault** [comment]
@nzoghb well spotted! Would you like to submit a PR?

P.S. Is still available in
http://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.star and
![image](https://cloud.githubusercontent.com/assets/1315589/23605425/be56ff74-026d-11e7-87c0-193656ebb417.png).

**Comment by nzoghb** [comment]
Will do soon, although I am working towards #2555; moving all the shapes functionality into their own module.

**Comment by soupault** [comment]
Closed via #2556
