### ISSUE TITLE
Import Statement Inconsistencies

### ISSUE THREAD

**Issue by nzoghb** [scikit-image/scikit-image#2557]
## Description
Many modules use `import` statements haphazardly and do not seem to follow a standard protocol. Some pull dependencies using relative pathways:

`from ..measure._label import label`

Whereas others use absolute ones:

`from skimage.measure._label import label`

1. Which should be the standard?
2. Additionally, sometimes files draw on entire modules when all they require are a couple of functions, should this be changed?
3. What is the protocol when only a single function is using a module? I am not a fan of importing within function definitions and would rather have the `import` at the beginning of the file. Example (from `skimage.morphology.selem`):

```
def octagon(m, n, dtype=np.uint8):
    from . import convex_hull_image
    ...
    selem = convex_hull_image(selem).astype(dtype)
    return selem
```

**Comment by JDWarner** [comment]
Relative imports should be the standard across the board.

I agree that with only very select exceptions, imports should happen at the top of the file rather than in functions.  However, on occasion imports within functions have been used to avoid circular imports.
