### ISSUE TITLE
transform.rescale only works on first 2 dimensions

### ISSUE THREAD

**Issue by kharris** [scikit-image/scikit-image#2568]
Rescale only works for 2d images, even though the description is that it works for N-D images. On the other hand, `scipy.ndimage.zoom` works on all dimensions, so I have a workaround.

```
pd.shape
```
(132, 80, 114)
```
from skimage.transform import rescale
test = rescale(pd, 10, order=0)
test.shape
```
(1320, 800, 114)

skimage 0.12.3, installed with Anaconda2-4.3.1

**Comment by soupault** [comment]
Closed via #1522 .
