### ISSUE TITLE
Consider making dask an optional dependency

### ISSUE THREAD

**Issue by astrofrog** [scikit-image/scikit-image#2571]
The conda package for scikit-image does not include dask as a dependency, which causes all kinds of problems with setuptools when loading entry points:

https://github.com/ContinuumIO/anaconda-recipes/pull/85

However, it looks like Continuum are not keen on adding dask as a dependency. Could you either weigh in on that issue to recommend dask be indeed included as a required dependency, or alternatively downgrade it to an optional dependency?

**Comment by soupault** [comment]
@astrofrog Hi! `dask` has been made an optional dependency recently (https://github.com/scikit-image/scikit-image/pull/2494). Will be shipped this way with `skimage` 0.13.

**Comment by astrofrog** [comment]
@soupault - ah, but it's still in ``requirements.txt`` though:

https://github.com/scikit-image/scikit-image/blob/master/requirements.txt

**Comment by soupault** [comment]
... That's a shame on my head :man_facepalming:. Is going to be fixed in no time.

**Comment by astrofrog** [comment]
@soupault - thanks!
