### ISSUE TITLE
skimage.color.rgb2ycbcr results in wrong value (modified)

### ISSUE THREAD

**Issue by germunwang** [scikit-image/scikit-image#2573]
I have got the solution by myself, please see the second comment, thanks a lot.

original problem:
==========================================
Hi guys, I found an wrong result in the function rgb2ycbcr (in version maybe pre-0.13?).
as the code in line 1687:
```
    arr = _convert(ycbcr_from_rgb, rgb)
    arr[..., 0] += 16
    arr[..., 1] += 128
    arr[..., 2] += 128
    return arr
```
however,  it will call the function `_prepare_colorarray()` in `_convert()`, as line in 157:
```
return dtype.img_as_float(arr)
```
causing the value scaling in [0,1] before adding the bias.

I suggest that you should do scaling them back to [0,255], just simple way as below or others:
```
    arr = _convert(ycbcr_from_rgb, rgb)
+   arr = arr * 255.0
    arr[..., 0] += 16
    arr[..., 1] += 128
    arr[..., 2] += 128
    return arr
```

I try this code with JPEG conversion, which Y is in [0,255], and get a correct answer same with using Pillow.
```
    arr = _convert(ycbcr_from_rgb, rgb)
+   arr = arr * 255.0
    arr[..., 0] += 0
    arr[..., 1] += 128
    arr[..., 2] += 128
    return arr
```
I'm not sure whether it is correct in your ITU-R BT.601 conversion, maybe you should recheck it again.

**Comment by germunwang** [comment]
Well, I'm sorry I offer an incorrect information.
By way of checking again, your code is surely correct while using ITU-R BT.601 conversion,
since the range of RGB is [0,1] in  ITU-R BT.601.
[https://en.wikipedia.org/wiki/YCbCr#ITU-R_BT.2020_conversion](https://en.wikipedia.org/wiki/YCbCr#ITU-R_BT.2020_conversion)

so it results in wrong value when i using JPEG conversion matrix since RGB ranging in [0,255]
[https://en.wikipedia.org/wiki/YCbCr#JPEG_conversion](https://en.wikipedia.org/wiki/YCbCr#JPEG_conversion)

Anyway, i decide to remain this post so we guys could know the difference between these two conversions. And maybe you could consider adding the JPEG conversion YCbCr to skimage.

Thanks a lot.

**Comment by stefanv** [comment]
@germunwang I'd like to clarify: do you think you've uncovered a bug here?

**Comment by germunwang** [comment]
Hi, @stefanv 
Actually I think it's not a bug in the end (for your *ITU-R_ BT.601 conversion YCbCr)*. 
But it will be a problem when using *JPEG conversion YCbCr* (What the rgb2ycbcr conversion  I need and using by PIL Image) for this function directly.

For example if i change the translation matrix (as the formula from wiki):

```
#ITU-R BT.601 conversion, Digital Y′CbCr: 
ycbcr_from_rgb = np.array([[    65.481,   128.553,    24.966],
                           [   -37.797,   -74.203,   112.0  ],
                           [   112.0  ,   -93.786,   -18.214]])
```
to
```
#JPEG conversion: (using by PIL Image)
ycbcr2_from_rgb = np.array([[     0.299,     0.587,     0.114],
                           [ -0.168736, -0.331264,       0.5],
                           [       0.5, -0.418688, -0.081312]])
```

then there will be a problem resulting an error value,
since the input range is difference between these two conversions as I explain in the second reply (although they both for YCbCr).

I left a post here because I didn't know why I get the difference YCbCr result value while comparing to PIL Image result in the begining.

But I found the cause in the end and solve it by myself, so now it's just a note here,
there may be someone have this problem or question as me one day.

So I don't know whether it's a bug or not now, but it may be in the future.

Thanks for your reply.

**Comment by stefanv** [comment]
Thank you for letting us know!  If you think we can clarify this in the documentation, please don't hesitate to make a PR.
