### ISSUE TITLE
compare_ssim doesn't work

### ISSUE THREAD

**Issue by Tutufa** [scikit-image/scikit-image#2581]
## Description
Hi, I'm trying to measure ssim metric between two images. I'm using compare_ssim. Images have same dimension and are grayscale. Yet method thoughts exception:

ValueError: shapes (850,1904) and (850,1904) not aligned: 1904 (dim 1) != 850 (dim 0)

What could be wrong?

Full error:

/home/*/anaconda3/lib/python3.6/site-packages/skimage/measure/_structural_similarity.py in compare_ssim(X, Y, win_size, gradient, dynamic_range, multichannel, gaussian_weights, full, **kwargs)
    178 
    179     # compute (weighted) variances and covariances
--> 180     uxx = filter_func(X * X, **filter_args)
    181     uyy = filter_func(Y * Y, **filter_args)
    182     uxy = filter_func(X * Y, **filter_args)

/home/*/anaconda3/lib/python3.6/site-packages/numpy/matrixlib/defmatrix.py in __mul__(self, other)
    341         if isinstance(other, (N.ndarray, list, tuple)) :
    342             # This promotes 1-D vectors to row vectors
--> 343             return N.dot(self, asmatrix(other))
    344         if isscalar(other) or not hasattr(other, '__rmul__') :
    345             return N.dot(self, other)

ValueError: shapes (850,1904) and (850,1904) not aligned: 1904 (dim 1) != 850 (dim 0)

**Comment by Tutufa** [comment]
are there any assumptions, that image is supposed to be square?

**Comment by sciunto** [comment]
Please, could you put a minimal code to reproduce (and eventually images if necessary).

**Comment by Tutufa** [comment]
found bug in my code, one of images was numpy matrix and it caused this strange behavior. Perhaps you should add assert to validate types of input images to by np.array ;-)

**Comment by sciunto** [comment]
@scikit-image/core can confirm our policy: we do not perform tests on data type. We eventually check the dimensions.

**Comment by JDWarner** [comment]
Confirmed, with limited exceptions.
