### ISSUE TITLE
Divide by Zero Error in exposure.py:465

### ISSUE THREAD

**Issue by FuriouslyCurious** [scikit-image/scikit-image#2591]
## Description
Skimage is throwing divide by zero error when running Sigmoid correction code:

`site-packages/skimage/exposure/exposure.py:465: RuntimeWarning: divide by zero encountered in true_divide out = (1 / (1 + np.exp(gain * (cutoff - image / scale)))) * scale
`

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example - 

> Running SIGMOID corrections on medical TIFF compressed images
Actual code need to be run on thousands of images, and some images will throw this error (approx 3-5% of images):
`
skimage.exposure.adjust_sigmoid(skimage.img_as_float(NPImage), cutoff=0.5030, gain=10, inv=False)`

- [x] Relevant images (if any) : 

> Cannot share medical images

- [x] Operating system and version : 

> Ubuntu 16.04 on Docker v1.17

- [x] Python version : 

> Intel Python v 3.5.2 (can be obtained from [https://anaconda.org/intel](https://anaconda.org/intel) 

- [x] scikit-image version (run `skimage.__version__`)  

> 0.12.3

**Comment by sciunto** [comment]
Hi, 

Could you provide the result of

```
from skimage.util.dtype import dtype_range, dtype_limits
print(image.dtype.type)
print(dtype_limits(NPImage, True))
```
please?

**Comment by FuriouslyCurious** [comment]
All dtypes and limits on system:

```
{<class 'numpy.float32'>: (-1, 1), <class 'numpy.int8'>: (-128, 127), <class 'numpy.uint8'>: (0, 255), <class 'numpy.float16'>: (-1, 1), <class 'numpy.int64'>: (-9223372036854775808, 9223372036854775807), <class 'numpy.uint64'>: (0, 18446744073709551615), <class 'numpy.int32'>: (-2147483648, 2147483647), <class 'numpy.uint32'>: (0, 4294967295), <class 'numpy.float64'>: (-1, 1), <class 'numpy.int16'>: (-32768, 32767), <class 'numpy.bool_'>: (False, True), <class 'numpy.uint16'>: (0, 65535)}
```

**dtypes of image:**

```
<class 'numpy.float64'>
<class 'numpy.float64'>
```

**Comment by sciunto** [comment]
Can you share one of your image in private? My contact can be found in my profile.

**Comment by sciunto** [comment]
@FuriouslyCurious Kind ping, is it possible to share your image in private? Otherwise, we would appreciate if you can inspect what's effectively wrong

**Comment by rfezzani** [comment]
Is this issue still relevant? Not sure we can reproduce the described bug... Can we close it @FuriouslyCurious ?

**Comment by FuriouslyCurious** [comment]
Dear devs, sorry I couldn't share the image because it is a HIPAA protected medical image.  I could not recreate the issue with other images despite trying.  I will close this issue.

**Comment by jni** [comment]
@FuriouslyCurious sorry that we couldn't fix this! Looking at the code:

https://github.com/scikit-image/scikit-image/blob/50fb2eff14b083f21d008cf76d05e85ffce07cba/skimage/exposure/exposure.py#L591-L600

I struggle to see how this could result in a divide by zero warning. The only thing we divide by is `scale` which comes from `dtype_limits`, which are guaranteed to be distinct.

My advice is for you to run each line in this code by itself (and maybe even parts of lines — eg. break up the mathematical expressions) with your input image, to pinpoint exactly where the failure is happening — is it that the dtype limits return invalid values in this context for some reason? Is it that the image dtype is somehow mangled? ...
