### ISSUE TITLE
C++ support?

### ISSUE THREAD

**Issue by ThomasWalter** [scikit-image/scikit-image#2594]
## Description
It is not really an issue, but rather a question on the programming style. 
I am working on some functions for skimage, for which it would be very handy to use some C++ class. I did not find an example in the current code, where people used C++, so I was wondering, whether you are strictly against this and whether it would imply a lot of change in the setup.py. Thanks !

**Comment by soupault** [comment]
To the best of my knowledge we do not use any C++ code. The only C++ source files are https://github.com/scikit-image/scikit-image/tree/master/skimage/measure/mc_meta, and they are only used as reference (there is also a Cython version of the same algorithm).

**Comment by ThomasWalter** [comment]
Thanks for your comment. 

And what is your feeling about having some part written in C++?

**Comment by soupault** [comment]
In the context of `skimage`, I don't think that we should incorporate any C++ code.
However, if you are able to express the same thing in Cython, that would be great and acceptable.

**Comment by jni** [comment]
I second @soupault's statement. Most C++ can be expressed in Cython. My own feeling about the future of the library, and scientific Python in general, is that we will shift focus to JITs, rather than pre-compiled languages. So I'm -1 on this. I'll leave it open for others to comment but I think support is unlikely.

**Comment by ThomasWalter** [comment]
Okay, thanks for the comments. I will give my best then :-)
