### ISSUE TITLE
Unexpected behavior of each_channel in adapt_rgb 

### ISSUE THREAD

**Issue by nkruglikov** [scikit-image/scikit-image#2601]
## Description
Implementation of `each_channel` in `color.adapt_rgb` is supposed to work like this:
- take each channel of an `image`;
- apply an `image_filter` on it;
- combine results.

In the current implementation, however, an `image_filter` is applied not on a channel, but on a transposed channel. It seems to me that it was done just for the code simplicity. Take a look at that particular line: https://github.com/scikit-image/scikit-image/blob/master/skimage/color/adapt_rgb.py#L77

It works well almost every time. However, I ran into a problem recently. What I want to do is to use a binary mask of the same shame as an image as a parameter of my filter. Consequently, the filter breaks because mask shape is (x, y), while channel shape is (y, x). It could be avoided by transposing mask inside a filter, but it feels like a hack.

What is more, I can imagine usage of `each_channel` with a convolution filter. If the kernel is not symmetrical, the current implementation of `each_channel` will cause unexpected results too.

## Way to reproduce
Here is my code. It is supposed to crop a fragment of an image by a boolean mask.

```python
from skimage.color.adapt_rgb import adapt_rgb, each_channel

def crop_zeros(matrix):
    crop_rows = matrix[~np.all(matrix == 0, axis=1)]
    crop_cols = crop_rows[:, ~np.all(crop_rows == 0, axis=0)]
    return crop_cols

@adapt_rgb(each_channel)
def crop_by_mask(image, mask):
    result = image.copy()
    result[~mask] = 0
    return crop_zeros(result).copy()
```

This code crashes at the line `result[~mask] = 0` with `ValueError: operands could not be broadcast together with shapes (x, y) (y, x)` if `image` is an RGB image, but works well with grayscale images.

**Comment by soupault** [comment]
@nkruglikov Thanks for reporting! :+1: from me to change this.

**Comment by jni** [comment]
@nkruglikov wow good catch! As you suggested, transposing the mask is a hack. I think the correct fix is to replace `image.T` with `np.rollaxis(image, -1, 0)`.

**Comment by jni** [comment]
And of course to add a test based on your use case to make sure there are no regressions in the future! ;)
