### ISSUE TITLE
Add warn keyword to img_as_* functions

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#2602]
Image conversion from float to uint8 is very, very common, and usually people know what they're doing when using it, and don't appreciate the annoying warning. A brief discussion in https://github.com/scikit-image/scikit-image/issues/543#issuecomment-292221966 suggests that users might like a `img_as_uint8(..., warn=False)` keyword argument as a way to suppress the warnings.

The same would be true for `imsave` and low contrast images.

Another idea would be to only warn when the apparent dynamic range is dramatically compressed, even when `warn=True`.

Discuss. =P

**Comment by sciunto** [comment]
I had the same thought last week during my lecture. +1 for the kwarg.

**Comment by sciunto** [comment]
See also #2531

**Comment by soupault** [comment]
I think it would be a good idea to add such argument as long as our empirics (e.g. https://github.com/scikit-image/scikit-image/blob/master/skimage/util/dtype.py#L115-L122) are not 100% precise.

Default value should be `warn=True`, in any case.

**Comment by mpt5** [comment]
+1 for the keyword proposal -- in my case hundreds of warnings get printed out since multiple files are converted sequentially in a loop

**Comment by stefanv** [comment]
Why don't we just remove this warning entirely?  It seemed like the proper thing to do at the time, but it's never been useful.

**Comment by thefiddler** [comment]
Any updates on this?
