### ISSUE TITLE
SKIP: gray vs grey

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2604]
## Description

Recently, I saw a student stuck after typing

```
io.imread('image.jpg', as_gray=True)
```
Silently, it loads as a RGB image.

Indeed, the API is `as_grey`. The problem is that our API is not homogeneous. It seems that US spelling is in majority in our library. I would suggest to either:
* make sure that both gray and grey are working
* raise a warning

Any suggestion @scikit-image/core ?

**Comment by jni** [comment]
What does RFC mean for those of us that are uninitiated? =)

My preference is for both to work. (I think this is what we do with rgb2grey/rgb2gray?)

**Comment by soupault** [comment]
Is seems that `skimage.io` is the only place where `as_gray` keyword is used.
It won't be a bad idea to support both `as_gray` and `as_grey` there.

**Comment by sciunto** [comment]
Request For Comments, but I have no idea what SKIEP means :D

**Comment by soupault** [comment]
@sciunto It is our new brand for labelling strategic discussions: SciKit-Image Enhancement Proposal (copy from PEP) :smile: .

**Comment by sciunto** [comment]
needs a little TM them :)

**Comment by sciunto** [comment]
Is it trivial to support `as_gray` along with `as_grey`? The **kwarg is used for the plugins... it doesn't seem nice to me to go that way. I would prefer to follow a deprecation cycle. Do you agree?

**Comment by sciunto** [comment]
I notice that in mrphology, we have grey.py and greyreconstruct.py. Ndimage uses grey as well...

**Comment by soupault** [comment]
matplotlib and Pillow use `gray`, `grayscale`.

@sciunto Sorry, I didn't catch your second proposal.

**Comment by sciunto** [comment]
What I meant is:
* solution 1: we use **kwargs to catch `as_gray` if `as_grey` is not set, but **kwargs is used for plugins, so it's not very clean.
* solution 2: we add a new option `as_gray` with `as_grey=None`. If `as_grey` is not None, raise a warning for deprecation.

I prefer solution 2.

**Comment by alexandrejaguar** [comment]
I'd go with `as_gray`, since this is the "most used" nomenclature in books, papers, et al. It could confuse some users (I was one of them). For me, @sciunto's solution 2 is the way to go.

**Comment by soupault** [comment]
@sciunto is there anything else to you would like to change?

**Comment by sciunto** [comment]
I just opened a small PR #3098 but ideally, it would be good to replace other places but deprecations are needed... :(

**Comment by PinkFloyded** [comment]
As a new user of skimage it seems very strange to keep two versions of the API whenever there is a gray. This pollutes the API surface and for no good reason. I think it makes sense to choose one, deprecate the other and remove it in a major version release.

**Comment by jni** [comment]
@PinkFloyded I actually agree with you and disagree with past me. :joy: 🤷‍♂️ The intention going forward is to follow US convention everywhere. However, this will take time as it requires breaking changes and deprecations. (Not least in `graycoprops`, which looks weird to me spelled that way. Anyone else?)
