### ISSUE TITLE
DOC: several broken examples in the stable version of the gallery

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2607]
## Description

See http://scikit-image.org/docs/stable/auto_examples/index.html

**Comment by soupault** [comment]
`File "/Users/jni/projects/scikit-image/doc/source/../ext/sphinx_gallery/gen_rst.py", line 498, in execute_script` :suspect: 

- http://scikit-image.org/docs/stable/auto_examples/segmentation/plot_rag_boundary.html#sphx-glr-auto-examples-segmentation-plot-rag-boundary-py
- http://scikit-image.org/docs/stable/auto_examples/segmentation/plot_compact_watershed.html#sphx-glr-auto-examples-segmentation-plot-compact-watershed-py
- http://scikit-image.org/docs/stable/auto_examples/segmentation/plot_thresholding.html#sphx-glr-auto-examples-segmentation-plot-thresholding-py
- http://scikit-image.org/docs/stable/auto_examples/segmentation/plot_rag_merge.html#sphx-glr-auto-examples-segmentation-plot-rag-merge-py
- http://scikit-image.org/docs/stable/auto_examples/segmentation/plot_boundary_merge.html#sphx-glr-auto-examples-segmentation-plot-boundary-merge-py

**Comment by jni** [comment]
Aaaaah!

I love how all the broken examples have my name on them. I feel like they should have my frowning picture and the caption "THIS GUY." =P

On it!

**Comment by jni** [comment]
Fixed! ;)
