### ISSUE TITLE
Fix two tests disabled by #2468

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2611]
Fix the two tests disabled by #2468:

- `test_coord_map`  in `test_interpolation.py` (see #2454)
- `test_gray2rgb` in `test_colorconv.py`

**Comment by jni** [comment]
@stefanv maybe you want to mention what those are? =D

**Comment by stefanv** [comment]
@jni Updated

**Comment by soupault** [comment]
I'll take care of both.

**Comment by sciunto** [comment]
Fixed by #2454
