### ISSUE TITLE
Improve the support for 1D images in `color.gray2rgb`

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2628]
## Description
Currently, it raises an error, but it is simple to change the behaviour to do the required conversion.

See https://github.com/scikit-image/scikit-image/pull/2454#issuecomment-295501725, https://github.com/scikit-image/scikit-image/pull/2454#issuecomment-295588504.

**Comment by Buntworthy** [comment]
I'd be happy to take this on, but it will be my first ever open source contribution so I might need some hand holding!

**Comment by soupault** [comment]
@Buntworthy just go for it! We are here to help.
Consider starting with Pull Request checklist: https://github.com/scikit-image/scikit-image/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by arjunsuri** [comment]
Sir, I also want to work on this issue.Mine will also be first.Please help me as well

**Comment by soupault** [comment]
@arjunsuri There is an ongoing work on this issue already - see #2645.

**Comment by arjunsuri** [comment]
@soupault ,Thank you sir for suggestion.
