### ISSUE TITLE
Support color images in montage2d

### ISSUE THREAD

**Issue by dwyatte** [scikit-image/scikit-image#2632]
Are there plans to support color images in skimage.util.montage.montage2d? I find myself wanting this functionality when doing image processing on color images.

**Comment by soupault** [comment]
@dwyatte Yep, on its way: https://github.com/scikit-image/scikit-image/pull/2626 .

**Comment by dwyatte** [comment]
Great, I'll keep this open until #2626 is merged

**Comment by soupault** [comment]
@dwyatte Kindly join us to celebrate the addition of `skimage.util.montage` (now multichannel!)!

**Comment by dwyatte** [comment]
Closed by #2626
