### ISSUE TITLE
Does skimage have a function that does the reverse of label2rgb?

### ISSUE THREAD

**Issue by mpt5** [scikit-image/scikit-image#2633]
I find myself in need of a function that produces a grayscale / one-channel matrix containing integers that represent several classes in an RGB mask for pixel-wise segmentation.  For example, the RGB mask has been labeled with red (object A), green (object B), blue (object C), and black (background) and I'd need those converted to 1, 2, 3 and 0.

**label2rgb** seems to do the reverse of this, which would be convenient for viewing a prediction, but I couldn't find any function in **module:color** that would do the opposite.

**Comment by soupault** [comment]
@mpt5 are you looking for http://scikit-image.org/docs/dev/api/skimage.measure.html#label?

**Comment by mpt5** [comment]
not really — I have masks (RGB) that are paired to grayscale images. The masks have manual segmentation of different objects, each one with a different color assigned to them (red, blue, green). I wondered if skimage has a function that will convert this RGB image (3 channels) to a single channel in which the colors are encoded as labels (1, 2, 3 respectively). This would be an extension of the usual binary masks used for semantic segmentation.

**Comment by jni** [comment]
@mpt5 are there only three colors, 100% Red, 100% Blue, and 100% Green? If so, you can just use a matrix multiplication:

```python
color1 = (image_rgb / np.max(image_rgb)).astype(int)
labels = color1 @ [1, 2, 3]
```

Otherwise, you can use some arithmetic to make sure you have a unique label for every unique rgb value:

```python
labels = image_rgb @ [256**2, 256, 1]
```

You can then (optionally) use `segmentation.relabel_sequential` to make sure these labels are sequential values starting from 1.

It *might* be worthwhile adding a function that does this. I'll let @scikit-image/core discuss.

**Comment by mpt5** [comment]
ok thanks @jni --- I'll try your suggestions -- it seems like this would be a reasonable feature request given that skimage provides a function that operates in one direction already

**Comment by soupault** [comment]
Such kind of a function sounds pretty specific to me. To the best of knowledge, way more general case is when the multiple ground truth masks are stored separately (each in a dedicated binary image), or in .csv-like file in the form of polygons.

Also, there is an ambiguity on how to represent multiple mask from different channels in a single grayscale image: should we sum the values from different channels, should we multiply them, should we take the highest one, etc.

**Comment by jni** [comment]
@soupault I think the above approach (1 unique RGB value = 1 segment id) makes the most sense for the problem in @mpt5's description.

However, it occurred to me that it actually doesn't do the opposite of `label2rgb` in any sense of the word: `label2rgb` has two modes, a color cycle mode, in which segments are given values from cycling over a list of limited colors, and an "average" mode, in which segments are given the average color of all the pixels in the segment from the underlying image. In neither of these cases will `rgb2label(label2rgb(segments, image))` guarantee that you get the same segmentation back.

So, given this, I don't think it's a good idea to provide that function — it'll be more misleading than useful.

I'm going to close this issue, but @mpt5, please reopen if the above code doesn't solve your problem! We are here to help!
