### ISSUE TITLE
A TODO list for code specific to lib/python version for future maintenance.

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2651]
## Description

@scikit-image/core In #2647, we have some lines of code to handle specific versions (python and numpy). Do we want to track that in a TODO file? The current TODO file could hardly collect that due to the current organization. However, I have the feeling that it would be helpful to write this down.

Typical entry:

* in skimage.morphology.something(), specific code for numpy<1.1

**Comment by soupault** [comment]
Would be nice to keep track of such things.
Instead of populating `TODO`, I'd suggest to file both the mentioned points and TODOs as GitHub issues (i.e. removing `TODO` at the end).

**Comment by sciunto** [comment]
I don't like the idea to transfer that on github. The day we will need to move from github to somewhere else, it's gonna to be a nightmare.

**Comment by jni** [comment]
I don't think it'll be a nightmare at all. Github provides APIs to access issues and PRs, and we will *definitely* need to write scripts to migrate everything out of it one day — whether or not we have todos there. (And in fact I'm going to be surprised if someone hasn't solved this problem already.)

**Comment by stefanv** [comment]
Please use the existing `TODO.txt` to track this information.
