### ISSUE TITLE
Can scikit-image flip an image horizontally or vertically?

### ISSUE THREAD

**Issue by hanfeisun** [scikit-image/scikit-image#2653]
Scikit-image has rotate function. But it doesn't seem to have the "flip" function

**Comment by grlee77** [comment]
You can flip by indexing using `::-1`.  For example, to flip the second axis of a 2D array
```python
a_flip = a[:, ::-1]
```
There is also a [flip](https://docs.scipy.org/doc/numpy/reference/generated/numpy.flip.html) function that does this as of numpy 1.12 (also see `fliplr`, `flipud` in older numpy):

**Comment by hanfeisun** [comment]
For newbies, it will be very convenient if a flip method could be provided under skimage.transform module..

**Comment by swiftdiaries** [comment]
Created a pull request for the feature used grlee77's comment for the flip function.
https://github.com/scikit-image/scikit-image/pull/2655

**Comment by stefanv** [comment]
Thanks for helping out, @swiftdiaries.  Since this is a NumPy array operation, we'll not include that functionality for now.

**Comment by drsxr** [comment]
Disappointing, as I have to use numpy for flipping, scikit learn for rotation, and cv2 for other things.  Limits my interest in using scikit-image.

**Comment by hmaarrfk** [comment]
the Notation numpy uses isn’t really specific to numpy. It is at the core of all of python.

**Comment by soupault** [comment]
@drsxr could you elaborate on your suggestion?
From the common perspective, adding a thin wrapper around `np.flip` doesn't add anything to the functionality of the ecosystem (especially, when `scikit-image` is built on top of and tightly integrated with NumPy and SciPy), while moderately increases the maintenance burden for the developers.
For rotation, I'm not sure that `scikit-learn` provides the rotation function. Did you mean different package?

I have to say that `scikit-image` is being developed to satisfy the wide range of needs, but isn't meant to include all existing image processing and computer vision algorithms (well, perhaps, we'd like to see them implemented, but open source software is often limited in terms of manpower for development and maintenance). If you feel that an important functionality is missing from the package, you are very welcome to initiate a constructive discussion in Issues or submit a Pull Request.

**Comment by jni** [comment]
@drsxr note that scikit-image requires NumPy to function, and really NumPy is a prerequisite for almost anything we do, so it doesn't make sense to duplicate that functionality: if you have installed scikit-image, you have installed NumPy.

Also, note that in addition to the above slicing suggestion, NumPy provides the functions `np.fliplr` (left-right) and `np.flipud` (up-down).

**Comment by hmaarrfk** [comment]
@jni I totally forgot about the `np.flip` functions. For images that might have color channels, you will probably want to have more control with [np.flip](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.flip.html#numpy.flip)

**Comment by hmaarrfk** [comment]
@jni I totally forgot about [np.flip](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.flip.html#numpy.flip) which provides an additional axis argument.

For reference, those are really convenience functions, and just call index with `::-1`

`np.flip` might be hard to read since it supports negative indexing, but just look at `np.fliplr`
https://github.com/numpy/numpy/blob/v1.15.1/numpy/lib/twodim_base.py#L83
