### ISSUE TITLE
pytest runs no tests on appveyor?

### ISSUE THREAD

**Issue by gatagat** [scikit-image/scikit-image#2654]
It seems `pytest` runs no tests in appveyor:
https://ci.appveyor.com/project/blink1073/scikit-image-qbl76/build/1.0.3216#L5406
Is this intentional?

I think the problem is the way `pytest` is called from `appveyor.yml` and that `pytest` interprets the arguments as paths, not as packages.

The solution that works for me in a different project is something like the following (see https://github.com/gatagat/lapjv/blob/lapmod/appveyor.yml#L69 and https://ci.appveyor.com/project/gatagat/lapjv/build/1.0.47/job/yimx8939n67qrvfl#L247).

    python -c "import pytest; from skimage import __file__ as d; d = os.path.dirname(d); pytest.main([d])"

**Comment by soupault** [comment]
@gatagat Thanks for the investigation! It is not intentional.
