### ISSUE TITLE
High execution time of several examples

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2657]
## Description
Should speedup the functions (especially, denoising) to facilitate the testing process.
```
Computation time summary (top 5):
	- plot_denoise.py : 1.2e+02 sec
	- plot_circular_elliptical_hough_transform.py : 48 sec
	- plot_rank_filters.py : 40 sec
	- plot_join_segmentations.py : 29 sec
	- plot_chan_vese.py : 14 sec
```

Also, from comment below:

```
skimage/future/graph/graph_cut.py::skimage.future.graph.graph_cut.cut_normalized 

The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by soupault** [comment]
Hmm... The numbers above are from AppVeyor.

Here are the Travis ones (top5, as well):
```
	- plot_rank_filters.py : 42 sec
	- plot_circular_elliptical_hough_transform.py : 19 sec
	- plot_ncut.py : 19 sec
	- plot_denoise.py : 13 sec
	- plot_active_contours.py : 13 sec
```

**Comment by grlee77** [comment]
I wonder what is making `plot_denoise.py` run an order of magnitude slower on Appveyor when some others are about the same duration?  There are a few different denoising algorithms within that same example so it is not obvious yet which is the culprit.  I will try to take a quick look at that one later once I have access to a windows machine.  On my OS X laptop I get 17 s which is in line with the Travis result.

**Comment by grlee77** [comment]
Looking into the long run time for `plot_denoise.py` on a windows machine, I can confirm that the two calls to `denoise_bilateral` account for almost all of the execution time (>50 s each on my machine).  This is compared to only 110 ms for the TV denoising and 12 ms for the wavelet one!  Haven't yet looked into the bilateral denoising internals to see why it might be so much slower on Windows than on OS X or linux.

Note:  I didn't want to hassle with building from master on Windows, so I just used the `conda` package for `scikit-image` 0.13.

**Comment by soupault** [comment]
This brings difficulties with the new Travis environment (IIUC they use Trusty now):
```
skimage/future/graph/graph_cut.py::skimage.future.graph.graph_cut.cut_normalized 

The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by cgohlke** [comment]
Looks like `plot_denoise.py`, `plot_circular_elliptical_hough_transform.py`, and `plot_join_segmentations.py` can be "fixed" by `x**2 -> x*x` as in #3032. I'll prepare a PR.

**Comment by cgohlke** [comment]
> `Computation time summary (top 5):`

Where can I find these numbers?

**Comment by stefanv** [comment]
They are shown in the Travis logs (ie docs build); not sure if there is a way to extract them programmatically from Sphinx gallery.

**Comment by cgohlke** [comment]
I see. Building the docs is disabled on AppVeyor. I ran it locally with #3035:
```
computation time summary:
        - plot_rank_filters.py: 22 sec
        - plot_chan_vese.py: 22 sec
        - plot_denoise.py: 16 sec
        - plot_circular_elliptical_hough_transform.py: 8.4 sec
        - plot_morphsnakes.py: 5.5 sec
        - plot_ncut.py: 3 sec
        - plot_rag_mean_color.py: 3 sec
        - plot_rag_draw.py: 3 sec
        - plot_inpaint.py: 2.9 sec
```
