### ISSUE TITLE
The value of circularity calculated from regionprops of skimage

### ISSUE THREAD

**Issue by stamaimer** [scikit-image/scikit-image#2660]
I use `[(4 * math.pi * region.area) / (region.perimeter * region.perimeter) for region in regionprops(label_image)]` to calculate the circularity of each labeled region in `label_image`. The value of that expression is large than 1. But the value of circularity must be (0, 1].

**Comment by soupault** [comment]
@stamaimer could you elaborate on your example?

Works OK to me:
```
In [1]: import numpy as np
In [2]: import math
In [3]: from skimage.measure import regionprops

In [4]: circ = lambda r: (4 * math.pi * r.area) / (r.perimeter * r.perimeter)

In [10]: ex1 = np.zeros((100, 100), dtype=np.uint)
In [12]: for i in range(100):
    ...:     ex1[i, i] = 1
In [13]: for i in range(100):
    ...:     ex1[-i, i] = 1
In [22]: [circ(region) for region in regionprops(ex1)]
Out[22]: [0.03339876750574667]

In [23]: ex2 = np.ones((100, 100), dtype=np.uint)
In [24]: [circ(region) for region in regionprops(ex2)]
Out[24]: [0.8013449274537785]
```

**Comment by stamaimer** [comment]
I add `label` before pass the image to `regionprops`. The original image is 
![figure_2](https://cloud.githubusercontent.com/assets/3755338/26150634/cdb5ed0c-3b31-11e7-9310-4eb126c4d9f3.png). And after `label`, The image is 
![figure_1](https://cloud.githubusercontent.com/assets/3755338/26150637/dc9a0498-3b31-11e7-954e-125e445daa81.png)

**Comment by soupault** [comment]
@stamaimer Sorry, I mean could you try to find the region on which the formula shows an unexpected value? It is not possible to do so using the images you attached.

**Comment by stamaimer** [comment]
@soupault I got `region.area = 9`  and `region.perimeter = 8.20710678119` for one region in the image i provided. and the circularity is `1.67908315807`.

**Comment by soupault** [comment]
@stamaimer Could you provide the source image (https://cloud.githubusercontent.com/assets/3755338/26150634/cdb5ed0c-3b31-11e7-9310-4eb126c4d9f3.png) as a numpy array (use https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html) instead of its plotted version?

>And some region's perimeter is 0.0 while the area of that region is not zero.

That's not a surprise, actually. See the docstring on how it is computed. Here is the case where the perimeter is 0:
```
ex3 = np.zeros((5, 5), dtype=np.uint)
for i in range(2, 4):
    ex3[i, i] = 1

for region in regionprops(ex3):
    print('Perimeter: {}\nCircularity: {}'
          .format(region.perimeter, circ(region)))

Perimeter: 0.0
Circularity: inf
```

**Comment by soupault** [comment]
@stamaimer Also, please, specify which versions of `numpy`, `scipy` and `scikit-image` you are using. Thanks!

**Comment by stefanv** [comment]
@stamaimer Are you still interested in resolving this issue?

**Comment by stamaimer** [comment]
In my current calculate of circular of shape, The value is correct which between 0 and 1. Thanks for your help.

**Comment by stefanv** [comment]
Thanks!
