### ISSUE TITLE
sphinx_gallery currently causing Travis failures

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#2661]
## Description
Travis builds are [failing](https://travis-ci.org/scikit-image/scikit-image/builds/233344234?utm_source=github_status&utm_medium=notification)  due to the following `sphinx-gallery` issue:
https://github.com/sphinx-gallery/sphinx-gallery/issues/241

It looks like we keep a copy of sphinx-gallery locally in `doc/ext`.  Should we apply the small fix from https://github.com/sphinx-gallery/sphinx-gallery/issues/242 now or wait until the next sphinx-gallery point release and just update to that?

(another temporary fix is to force Sphinx < 1.6.1 on Travis)

**Comment by soupault** [comment]
@grlee77 Typically, we stick to the released versions of `sphinx-gallery`.

>It looks like we keep a copy of sphinx-gallery locally in `doc/ext`.
JFYI, there were several discussions on this, and IIRC we decided to switch to `git submodule` link to their repo instead of copying files over and over.

**Comment by sciunto** [comment]
I do not remember that we decided to use git submodule (but I may have missed a discussion). I thought a script that would retrieve that last stable version...

**Comment by sciunto** [comment]
See #2663
