### ISSUE TITLE
Install lastest sphinx-gallery instead of re-distributing a copy in our source tree

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#2663]
## Current behavior

We have a copy of sphinx-gallery in our source tree

## A better behavior

Download the latest version or use git submodule to be always uptodate.

## TODO

unpin sphinx < 1.6.1, ie revert #2662

**Comment by grlee77** [comment]
sphinx-gallery made a new release last night (0.1.11) that should resolve the issues with sphinx 1.6.1

Our local copy is currently at version 0.1.8.  

By "download the latest source" do you mean adding sphinx-gallery via the `pip install` commands in the documentation build sections of `Makefile` and `appveyor.yml`?

**Comment by sciunto** [comment]
yes, something along this line. :)
