### ISSUE TITLE
Smooth images in resize/rescale

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#2668]
Currently, ``skimage.transform.resize`` or ``skimage.transform.rescale`` do not smooth images when down- or upscaling images. Most other image processing libraries do this by default in a similar manner as we do in our ``skimage.transform.pyramid_*`` functions. I suspect that many users are not aware of this and thus get aliasing effects when resizing images. What do you think about adding a ``smooth=True|False`` option?

**Comment by soupault** [comment]
>`smooth=True|False`

I'd rather support adding several smoothing/interpolation techniques (for reference, OpenCV - http://docs.opencv.org/3.1.0/da/d54/group__imgproc__transform.html#ga5bb5a1fea74ea38e1a5445ca803ff121).

**Comment by ahojnnes** [comment]
Interpolation is already implemented and can be easily extended. It does not necessarily solve the aliasing issues though.

**Comment by stefanv** [comment]
We definitely need to blur before downsamping; results are terrible otherwise.  I've just never had a good reference for this in the past; do you?

**Comment by soupault** [comment]
Closed via #2802
