### ISSUE TITLE
Plot a grid of images rather than a row with `imshow_collection`

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2678]
## Description
See https://github.com/scikit-image/scikit-image/issues/2676 for the current behaviour. I suggest to use `montage_nD` before plotting, or just plot the images on a square grid (n*n, where `n = ceil(sqrt(len(image_collection)))`).

**Comment by soupault** [comment]
@jni I guess that (https://github.com/scikit-image/scikit-image/issues/2676#issuecomment-307601196) is a +1 from you? :)

**Comment by jni** [comment]
Haha yes, although the "standard" aspect ratio for a mpl figure is 4:3, so we should aim for that ratio in our auto-grid. There is no doubt an interesting factorization problem in here that I am too lazy to solve at the present time. =)

**Comment by TheShadow29** [comment]
@jni Where is the factorization problem? Isn't it best to do something like `nrow = int(n ** .5)` where `n = len(img_collection)` and then `ncol = n/nrow + int((n%nrow + (n-1))/n)`, i.e. if the nrow divides n, `ncol = n/nrow` else `ncol = n/nrow + 1`.

**Comment by jni** [comment]
@TheShadow29 That assumes you want nrows ≈ ncols, which is less ideal than 4 nrows ≈ 3 ncols for common matplotlib figsizes. But, yes, that scheme would be much much better than what we have now.

**Comment by TheShadow29** [comment]
@jni I dont have a concrete proof that this will always result in the best factorization but here it goes. We need `4r ≈ 3c ≈ k` which implies `r ≈ k/4` and `c ≈ k/3`. Let `Total images = N`. Now `rc = N`, which implies `k^2 = 12*N`, which gives `k =  (12*N)**0.5`. Now we get `r = int(k/4)` or `r = int(k/4) + 1`, and get `c = N/r` or `c = N/r + 1`. And just check which of the two gives a closer ratio of `r:c = 3:4`

A few examples: 

- N = 20, k = 15.49, r = 3 or 4, c = 7 or 5, and we choose r = 4 , c = 5, giving 4r = 16, 3c = 15
- N = 33, k = 19.87, r = 4 or 5, c = 9 or 7, and we choose r = 5, c = 7, giving 4r = 20, 3c = 21
- N = 43, k = 22.71, r = 5 or 6, c = 9 or 8, and we choose r = 6, c = 8, giving 4r = 24, 3c = 24

Do correct me if I made some error.

**Comment by jni** [comment]
👏👏👏

That's what I meant I was too lazy to work out, very nice and clear. =)

**Comment by TheShadow29** [comment]
Well I was thinking that we could actually take a note of how many images are present and if it is more than a threshold, we can create a new figure window for the same. 
And if no one has started working on this, I would like to do so. But this would be my first contribution so I might need some help.

**Comment by soupault** [comment]
@TheShadow29 that sounds handy, although I'm not really a `imshow_collection` user. If we decide to implement such option, I'd prefer to have a parameter to the function (e.g. `batch_size`) which will default to `None` (users have a wide range of screen diagonals, so putting a fixed threshold be default is suboptimal :) ).

**Comment by jni** [comment]
@TheShadow29 please do, we will be happy to guide you! We try to provide lots of guidance to new contributors. Many stick around, such as myself or @soupault 👋 👋!  =)

**Comment by TheShadow29** [comment]
@soupault yes batch size would be more preferable, didn't think of the screen sizes. 
@jni Great. I will make the pull request in a day or two. Hoping to stick around as well.

**Comment by soupault** [comment]
Closed via #2689 .
