### ISSUE TITLE
colorconv cannot work

### ISSUE THREAD

**Issue by johnflux** [scikit-image/scikit-image#2679]
## Description

Doing:

    skimage.color.convert_colorspace(image, 'RGB', 'YCbCr')

Doesn't work, because skimage/color/colorconv.py  does:

    todict = {....  'YPbPr': rgb2ypbpr, 'YCbCr': rgb2ycbcr}
    tospace = tospace.upper()
    if tospace not in todict.keys():
        raise ValueError('tospace needs to be one of %s' % todict.keys())

Obviously 'tospace.upper()' can never match the mixed case 'YCbCr'.

Btw, just do:  if tospace not in todict:    rather than todict.keys()

Version:

scikit-image==0.13.0
scikit-learn==0.18.1

**Comment by soupault** [comment]
@johnflux Thanks for reporting!
