### ISSUE TITLE
scikit-image docs exhibit weird regression on firefox -- text doesn't show

### ISSUE THREAD

**Issue by pmagwene** [scikit-image/scikit-image#2685]
## Description

Using Firefox 53.0.3 (64-bit) on Linux, HTML documentation is missing text. Don't know if this is a Sphinx/Scikit-Image issue or Firefox, but no problem viewing scikit-learn or any other sites. Same sites/files view fine on Chromium.

## Way to reproduce
Fire-up fresh firefox instance and try and browse scikit-image documentation either on line or built locally.

**Comment by soupault** [comment]
@pmagwene any specific page where to check first? I've just tried browsing the site via Firefox 64.0 (64-bit), and haven't found any issues. Also, try to disable your extensions (if any).

**Comment by pmagwene** [comment]
I tried with a default firefox profile and got the same result. The PNG linked below shows what I'm seeing on the base page for the docs.  I've updated to Firefox 54, and am seeing the same issue. 

PNG screenshot showing issue:  https://raw.githubusercontent.com/pmagwene/bug-reports/master/scikit-no-text.png

I think this relates to the web fonts being used -- when I disable the "Allow pages to choose their own fonts" option than the text shows up correctly.

**Comment by pmagwene** [comment]
The font-family specification in custom.css seems to be the source of the issue. Changing the font-family to something other than Lato seems to fix the issue, which is weird since Lato is installed on my system.  In any case, I would expect the browser to fall back to the default sans-serif if Lato was missing.
```
body {
    font-family: "Helvetica", sans-serif;
    letter-spacing: 0.02em;
    font-size: 102%;
    line-height: 23px;
}
```

I'm guessing this is some weird interaction between Lato and Firefox that's particular to Ubuntu 17.04 (or maybe even my particular setup) so I'll go ahead and close this issue.
