### ISSUE TITLE
Fail to import Segmentation from skimage

### ISSUE THREAD

**Issue by RojunLin** [scikit-image/scikit-image#2686]
## Description
Hi, guys. I want to test the function of data augmentation with this python file（https://github.com/aleju/imgaug/blob/master/imgaug/augmenters.py）, and I have successfully import measure, transform module from scikit-image, but there is something wrong with importing the segmentation module from scikit-image. What's more, when I try to import segmentation module on the python terminal, it makes. What causes the problem?
As I want to import segmentation module in py file, it returns: 
`Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x7efcffa935d0>> ignored`

## Way to reproduce
- [ ] Code example
from skimage import segmentation 
- [ ] Relevant images (if any)
no input
- [ ] Operating system and version
ubuntu 14.04
- [ ] Python version
python2.7
- [ ] scikit-image version (run `skimage.__version__`)
0.9.3
If someone can help me, thank you very much. ^_^

**Comment by soupault** [comment]
@RojunLin Hi!
Before we start digging into the issue, I'd really encourage you to update your `numpy`, `scipy`, and `scikit-image` to the latest stable versions. `scikit-image==0.9.3` is, like, 4 releases (~ 4 years) behind, and is, most likely, significantly different in functionality and structure from the current version.

You could do this from the console by:
```
pip install -U numpy scipy scikit-image --user
```
Please, make the corresponding update, and try running your code again with the newer versions of the packages.

**Comment by RojunLin** [comment]
Hi, @soupault ! I have updated the version of the scikit-image to 0.12.3, but it still fail to import segmentation module.

**Comment by soupault** [comment]
@RojunLin perfect!
