### ISSUE TITLE
morphology.local_maxima errors when no maxima present

### ISSUE THREAD

**Issue by hko-gh** [scikit-image/scikit-image#2691]
## Description
When invoking morphology.local_maxima with an array where all values are equal, it should return zeros_like(image). Instead, it errors. The error is in _find_min_diff:
```
img_vec = np.unique(image.flatten())
min_diff = np.min(img_vec[1:] - img_vec[:-1])
```
img_vec has just 1, thus the argument for np.min is an empty array, which leads to the error
I guess, this could be easily fixed by returning 0 if img_vec.shape == (1,). Then, in case of 0 the local_maxima should return zeros_like(image).

## Way to reproduce
```
>>> import numpy as np
>>> from skimage import morphology
>>> a = np.ones((10,10), dtype=float)
>>> morphology.local_maxima(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/skimage/morphology/extrema.py", line 280, in local_maxima
    h = _find_min_diff(img)
  File "/usr/local/lib/python3.5/dist-packages/skimage/morphology/extrema.py", line 215, in _find_min_diff
    min_diff = np.min(img_vec[1:] - img_vec[:-1])
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 2372, in amin
    out=out, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```
skimage.__version__ is 0.13.0

**Comment by jni** [comment]
Thanks for the report @hko-gh!

**Comment by probinso** [comment]
May be helpful to add flat-image behavior to docstrings of `local_minima` and `local_maxima` as the current description doesn't in these cases

**Comment by stefanv** [comment]
@probinso Is the current behavior (after merging the other PR) different from what one would expect by default?  If so, we should document for sure.

**Comment by stefanv** [comment]
Closing this issue, since merged in #2699

**Comment by probinso** [comment]
@stefanv, In a flat image there are by definition no neighboring cells that are `strictly smaller than`, or `strictly less than`. Although I agree that the behavior should return `zeros`, the documentation is insufficient to describe this.

**Comment by stefanv** [comment]
@probinso Great, a docstring PR would be very welcome, then!
