### ISSUE TITLE
Odd keyword name `min_size` for morphology's `remove_small_holes`

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2696]
Should the `min_size` parameter be `max_size`, or something else entirely?  It's not a very intuitive naming.  At worst, we should document this well.

/cc @mcquin

**Comment by mcquin** [comment]
I think `max_size` is more intuitive than `min_size`. When I read `remove_small_x`, I think about removing x up to `max_size` rather than keeping x above `min_size`.

The word "size" is another point of confusion. It could help to define "size" as "total pixels".

**Comment by kne42** [comment]
I think that as `remove_small_holes` effectively _filters_ out the blobs based upon their area, a **threshold**-themed keyword name would make the most sense, such as `area_threshold`.
