### ISSUE TITLE
Broken link on inpainting example

### ISSUE THREAD

**Issue by ddasilva** [scikit-image/scikit-image#2697]
On the inpainting example at:
http://scikit-image.org/docs/dev/auto_examples/filters/plot_inpaint.html#sphx-glr-auto-examples-filters-plot-inpaint-py

The third link is 403 forbidden:
``
N.S.Hoang, S.B.Damelin, “On surface completion and image inpainting by biharmonic functions: numerical aspects”, http://www.ima.umn.edu/~damelin/biharmonic
``

**Comment by soupault** [comment]
I couldn't find any alternative links.

**Comment by ddasilva** [comment]
Fine by me. I fount it through google cache. Maybe it will reappear later.

**Comment by emmanuelle** [comment]
We should try to find another relevant link or just remove this one, because this paper does not seem to be published or have a DOI. Plus, the link is broken.

**Comment by nguyenwestga** [comment]
Here is an alternative link: https://arxiv.org/abs/1707.06567

**Comment by soupault** [comment]
@stefanv would you reconsider the removal of the algorithm from the library?

**Comment by stefanv** [comment]
Sorry, the ticket got closed with the merging of the other patch, but I agree with you that we should remove this function.

**Comment by soupault** [comment]
Wait... I'm not suggesting the removal, I'd rather vote to keep the functionality. It took me hell of a lot of time to push it into skimage several years ago :).

**Comment by stefanv** [comment]
Oh, I see ;)  Well, can you remind me why this specific method was chosen, and how we can motivate keeping it around, given that it seems to have zero citations?

**Comment by soupault** [comment]
@stefanv Mostly because it gives good results in practice, and the implementation was finalized (the feature which other inpainting algorithms staging into `skimage` are currently lacking).

>how we can motivate keeping it around, given that it seems to have zero citations

Doesn't mean that it is the only paper on the subject. I've just chosen the one which is closer to the topic of numerical implementation. The first paper in which the approach is described is http://www.sciencedirect.com/science/article/pii/S1063520309000578 . Also, the original paper has been uploaded to arxiv (see https://github.com/scikit-image/scikit-image/issues/2697#issuecomment-317301949).

P.S> If none of the above arguments convince you, I don't mind.

**Comment by stefanv** [comment]
@soupault If you say it gives good results in practice, then there's motivation for keeping it in itself.  Let's link to the relevant papers you describe for now, and leave it at that.

**Comment by soupault** [comment]
FYI, I've just found this article describing one of the top performing solutions from one of the latest Kaggle competitions - https://nikolasent.github.io/deeplearning/competitions/2018/10/24/Semantic-Segmentation-of-Seismic-Reflection-Images.html :slightly_smiling_face:  :
```
However, it was found out that it is better to pad images to the required input
size with biharmonic inpaint from skimage package. This led to a score improvement
for the most of used models.
```
Apparently, there __are__ people who are aware of the implementation and found it useful!

**Comment by jni** [comment]
Very nice! In other news, I was just at a deep learning workshop, and introducing myself to one of the participants:

- Me: I spend my "free research" time working on open source, mostly on scikit-image
- Participant: :astonished: Really??? I use scikit-image all the time! I love it!
- Me: :sob: :sob: :sob: :pray: :pray: :pray: :heart: :heart: :heart: 

And some of the instructors were telling me that all of their data preparation and augmentation is done with skimage. It was *so* motivating to hear so I thought I'd post it to the team somewhere, and this thread seems like a good spot now. =)

Another funny story:

- Me: **stares blankly at screen**
- Instructor: Where are you stuck?
- Me: Well, the objects are touching, so I think I want to learn borders, not foreground/background, I'm just trying to think of the best way to find them from the labelled volume.
- Instructor: Just use skimage `find_boundaries` and you're done?
- Me: ... Right :man_facepalming:

**Comment by soupault** [comment]
@jni Awesome! :)
Man, I wish there were some stats on the library usage (besides download counter - https://pypistats.org/packages/scikit-image). That would really bring a lot of food to the development table, and make us happier. Do we have a structured discussion on this topic somewhere (80% sure that we don't)?

**Comment by jni** [comment]
@soupault no, I don't think we do! One thing that has been nagging at me is to do a crawl of GitHub to find how many libraries/scripts/notebooks use us and which bits of skimage are most used.
