### ISSUE TITLE
Remove matplotlib as required dependency

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2710]
Matplotlib is a large dependency, and is not needed for the vast majority of skimage code.

1. Make sure matplotlib is imported when needed (and not in any top level submodules)
2. Ensure one of the entries in the test matrix runs without matplotlib
3. Check whether image IO runs properly on PIL when matplotlib is missing

See also: https://github.com/scikit-image/scikit-image/issues/2103

**Comment by FelixS90** [comment]
Hi there,

any progress concerning this issue in the meantime? Would be nice to have it resolved as soon as possible.

Kind regards

**Comment by soupault** [comment]
@FelixS90 not at the moment. You are welcome to submit a PR :)

**Comment by hmaarrfk** [comment]
Working on this now, I don't know a good way to lazy import in the [`viewer/canvastools/rectool.py`](https://github.com/scikit-image/scikit-image/blob/master/skimage/viewer/canvastools/recttool.py).

**Comment by grlee77** [comment]
closed by #5990
