### ISSUE TITLE
img_as_float is slower than it should be

### ISSUE THREAD

**Issue by florisvb** [scikit-image/scikit-image#2711]
## Description
In making an example to demonstrate how to convert RGB images to Gray images I stumbled upon the following observation: the img_as_float function takes about twice as long as simply dividing the image by 255. (where the '.' is of course important). It seems to me that this should not be the case. I'm not sure how best to handle this without possibly breaking things.

See below code snippet for an example. The image is being pulled from my website.. you have permission to use it for these purposes ;)

~~~~
import time
from skimage import io, util

rgb = io.imread('http://www.artinnaturephotography.com/images/xl/kofa-mountains-yucca-sunrise-20161124_6192.jpg')

t = time.time()
util.dtype.img_as_float(rgb)
print time.time()-t

t = time.time()
rgb/255.
print time.time()-t
~~~~

Output:
img_as_float:  0.0133371353149
rgb/255. :        0.00709295272827

Ubuntu 16.04 (running on a Macbook Pro)
Python 2.7
Most recent skimage ('0.14dev')

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x ] Code example
- [x ] Relevant images (if any)
- [x ] Operating system and version
- [x ] Python version
- [x ] scikit-image version (run `skimage.__version__`)

**Comment by stefanv** [comment]
Try the following in IPython:

```
from skimage import data, img_as_float
image = data.chelsea()

def conv(x):
    return x / 255

%timeit img_as_float(image)
%timeit conv(image)
```

On my system I see:

```
img_as_float:
2.69 ms ± 30.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

div 255:
2.19 ms ± 7.79 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Check out `skimage.util.dtype.convert` for why we can't simply use `/ 255` ;)

**Comment by florisvb** [comment]
For that test image I do get a comparable timing result to you. 

I think it might have to do with the image size. The data.chelsea() image is [300,451], whereas the image I used the my test example is [720, 1280].

I dug around a little in `skimage.util.dtype.convert` and it appears to me that there is a likely redundant call to `astype`, checking to see if this call is redundant before making the call shaves off most of the extra time. 

~~~~
    # signed/unsigned int -> float
    if kind_out == 'f':
        if itemsize_in >= itemsize_out:
            prec_loss()
        # use float type that can exactly represent input integers
        image = image.astype(_dtype_itemsize(itemsize_in, dtype_out,
                                             np.float32, np.float64))
        if kind_in == 'u':
            image /= imax_in
            # DirectX uses this conversion also for signed ints
            # if imin_in:
            #     np.maximum(image, -1.0, out=image)
        else:
            image *= 2.0
            image += 1.0
            image /= imax_in - imin_in
        return image.astype(dtype_out)
~~~~

In the above snippet from `skimage.util.dtype.convert`, replacing the last line with the below snippet nearly halves the processing time.

~~~~
        if image.dtype != dtype_out:
            return image.astype(dtype_out)
        else:
            return image
~~~~

I don't think this actually changes the functionality in any other way?

**Comment by grlee77** [comment]
Yes, that would avoid an extra copy.  The following would be a more concise way to achieve the same:

```python
return numpy.asarray(image, dtype=dtype_out)
```

(`asarray` only makes a copy when the dtype is not a match to the existing image).

**Comment by florisvb** [comment]
Thanks @grlee77 - that's a better approach. I didn't see it until after I filed the initial pull request, but have updated my PR to use your suggestion instead. Thanks!

**Comment by florisvb** [comment]
I messed up my previous pull requests since I'm a little new to git.. but I got it sorted out and filed a new PR.. sorry for any confusion! Still learning the process.
