### ISSUE TITLE
Scikit image-Python: Colored Image unresponsive and gives an error

### ISSUE THREAD

**Issue by pavanyvs** [scikit-image/scikit-image#2724]
## Description
[Please provide a general introduction to the issue/proposal.]
I am trying to read an image from the skimage.data. colored image appears but not responding . Also I am getting valurError. Here are my commands and errors.
[If reporting a bug, attach the entire traceback from Python.]
>>> import skimage
>>> import numpy as np
>>> import scipy as sp
>>> import matplotlib.pyplot as plt
>>> from skimage import data
>>> cat=data.chelsea()
>>> plt.imshow(cat,interpolation='nearest');
<matplotlib.image.AxesImage object at 0x0788BDF0>
>>> plt.show(cat)

Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    plt.show(cat)
  File "C:\Python36-32\lib\site-packages\matplotlib\pyplot.py", line 253, in show
    return _show(*args, **kw)
  File "C:\Python36-32\lib\site-packages\matplotlib\backend_bases.py", line 166, in __call__
    if block:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

I am using Python 3.6.2 and skimage version 0.13.0
Can anyone help me to get through this error?. Thankyou for your time.
## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by stefanv** [comment]
Answered on S/O.  `plt.show()` should be used, not `plt.show(cat)`.
