### ISSUE TITLE
Duplicate citation error in CI Python 2.7 build

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2726]
## Description

Potentially, introduced by https://github.com/scikit-image/scikit-image/pull/2723/ .

```
Warning, treated as error:
/home/travis/build/scikit-image/scikit-
image/doc/source/auto_examples/edges/plot_skeleton.rst:80:duplicate citation Zha84, other instance in 
/home/travis/build/scikit-image/scikit-image/doc/source/api/skimage.morphology.rst
make[1]: *** [html] Error 1
make[1]: Leaving directory `/home/travis/build/scikit-image/scikit-image/doc'
make: *** [html] Error 2
```

For example, see https://travis-ci.org/scikit-image/scikit-image/jobs/255458261.

**Comment by stefanv** [comment]
Does this only happen on Python 2?  Is it tied to Python version or Sphinx version?  I compiled the docs successfully on my machine.

**Comment by soupault** [comment]
Probably, a flashing Sphinx bug. Hasn't been seen recently. Closing for now.

**Comment by stefanv** [comment]
I think I stopped building the docs on 2.7.  Not very important, I don't think, since we host the docs.
