### ISSUE TITLE
Allow specifying random seed for probabilistic_hough_line

### ISSUE THREAD

**Issue by mcs07** [scikit-image/scikit-image#2734]
The `probabilistic_hough_line` algorithm contains a call to `rand` from `libc.stdlib` in the cython code. Would it be possible to add a seed parameter to the function, so the random seed could be controlled when calling from python?

**Comment by stefanv** [comment]
Yes, certainly; would you like to file a PR?

**Comment by mcs07** [comment]
I'll have a go...
