### ISSUE TITLE
Broken dev docs pushed to repo

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2735]

**Comment by soupault** [comment]
Fixed manually for now.
Potentially, there is an issue during the doc build process (missing `sphinx-gallery` or something).

Let's keep the issue open, and wait for some pushes to the `master`.

**Comment by stefanv** [comment]
@soupault Everything seems to work again.  Do you have any idea what went wrong?

**Comment by stefanv** [comment]
That's true---we now need to install `sphinx-gallery`.  I'll make a PR.

**Comment by soupault** [comment]
Dev docs are missing again...

**Comment by soupault** [comment]
@stefanv the docs are being pushed twice (e.g. https://github.com/scikit-image/docs/commit/e22fb42a3cc7f307c9e72afee1cac548948dd02f , https://github.com/scikit-image/docs/commit/8b23eea168b294da70617e400ebbbe6cc98dc53c ), but build only once for some reason.

**Comment by stefanv** [comment]
I keep forgetting: bash cares about spaces.  I pushed https://github.com/scikit-image/scikit-image/commit/acd065e0c5ace7c74b7df74aa7f79ad645744a9d as a quick fix (hopefully).

**Comment by soupault** [comment]
:astonished:
The docs are fine now. Closing.
