### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'orientations' in hog.

### ISSUE THREAD

**Issue by root-sudip** [scikit-image/scikit-image#2741]
I have written a small program to compute the hog,
here is my code=>
```
from skimage.feature import hog
import sys
import os

from PIL import Image

import numpy as np
class hog:
	def __init__(self,path):
		self.training_path = path
	def load_data(self):
		for dirnamelist,subdirlist,filelist in os.walk(self.training_path):
			for filename in filelist:
				im = np.asarray(Image.open(self.training_path+filename).resize((32,32), Image.ANTIALIAS))
				hd =  hog(im, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(3, 3),visualise=True)
				

obj = hog(sys.argv[1])
obj.load_data()
```
After doing this, I am getting this error `TypeError: __init__() got an unexpected keyword argument `'orientations'
I have checked the scikit-image version that is => `0.13.0`

How do i fix this problem?

**Comment by soupault** [comment]
>How do i fix this problem?

First of all, you do not override the imported function `from skimage.feature import hog` with a class definition (`class hog:`). Just follow PEP8 (https://www.python.org/dev/peps/pep-0008/#class-names), and it will bring you to the light :wink: .

**Comment by root-sudip** [comment]
opps, I totally forgot about this, thanks @soupault
