### ISSUE TITLE
Deprecate and remove `skimage.novice`

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2742]
`skimage.novice` was built by and for Software Carpentry.  I've recently learned that it is no longer being used, so I don't see much use for it remaining in the package.

If someone feels excited about turning it into a new package, please do so.

**Comment by JDWarner** [comment]
Two thumbs up for deprecation and removal.

**Comment by jondo** [comment]
@emmanuelle: Perhaps [adding the deprecation warning](http://scikit-image.org/docs/stable/contribute.html#deprecation-cycle) alone is easy? I would like to try it as my first time contribution at today's EuroPython coding sprint.

**Comment by soupault** [comment]
@jondo it should be pretty straightforward. It would be even better if you add a deprecation message also to the header of http://scikit-image.org/docs/stable/api/skimage.novice.html.

**Comment by jondo** [comment]
Yes, I thought it should be similar to [this depracation of sklearn/cross_validation.py](https://github.com/scikit-learn/scikit-learn/blob/65792205887c37316dd7da348179652d13e79b78/sklearn/cross_validation.py#L37).
