### ISSUE TITLE
How can I determine the number of windows generated by view_as_windows?

### ISSUE THREAD

**Issue by mptorr** [scikit-image/scikit-image#2743]
I'm trying to write a function that would provide me the number of windows output by `view_as_windows`, given the dimesions of _arr_in, window_shape, step_.

In a simple experiment using one grayscale image that is 256 x 256 I see that:

```
-- window_shape = (64, 64); step=64 generates this output
(4, 4, 64, 64) — 16 windows

-- window_shape = (64, 64); step=32 generates this output
(7, 7, 64, 64) — 49 windows

-- window_shape = (64, 64); step=16 generates this output
(13, 13, 64, 64) — 169 windows

-- window_shape = (64, 64); step=8 generates this output
(25, 25, 64, 64) — 625 windows

-- window_shape = (64, 64); step=4 generates this output
(49, 49, 64, 64) — 2,401 windows

-- window_shape = (64, 64); step=2 generates this output
(97, 97, 64, 64) — 9,409 windows

-- window_shape = (64, 64); step=1 generates this output
(193, 193, 64, 64) — 37,294 windows
```

[The documentation gives an example based on a 3D matrix](http://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.view_as_windows), but I wonder I anyone has a similar formula that could estimate the number of windows generated on a 2D example as above (other than simply multiplying the first 2 dimensions of the output matrix).

**Comment by stefanv** [comment]
How about something like:

```
step = 32
window = 64
nr_windows = np.prod(image.shape // step - window // step + 1)
```

**Comment by mptorr** [comment]
@stefanv thanks— I can't get `np.prod` to work with those floor divisions. 
Also, re `image.shape` did you mean `image.shape[0]`?

**Comment by stefanv** [comment]
Sorry, that should probably be `np.array(image.shape)`, I'll update the code above.
