### ISSUE TITLE
`peak_local_max` takes a very long time to complete

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2758]
From [StackOverflow/45682644](https://stackoverflow.com/questions/45682644/watershed-segmentation-in-python-with-skimage-does-not-stop-running):

The following script computing `peak_local_max` on a binary image takes a *very long time* to complete.

```
from scipy import ndimage as ndi
from skimage import feature, io, img_as_float, measure, color
import numpy as np

binary_image_of_interest = img_as_float(color.rgb2gray(io.imread('test.png'))) > 0.5
cells = binary_image_of_interest
distance = ndi.distance_transform_edt(cells)

local_maxi = feature.peak_local_max(
    distance,
    footprint=np.ones((3, 3), dtype=np.bool),
    indices=False,
    labels = measure.label(cells)
)
```
![test](https://user-images.githubusercontent.com/45071/29328440-675593fc-81a7-11e7-8940-c6be646002b8.png)

**Comment by soupault** [comment]
30 seconds on a moderate laptop. skimage 0.13

**Comment by rfezzani** [comment]
Running this example with current implementation (**0.17.2**) I measure ~0.3 seconds... Can we consider that this issue is Fixed?

**Comment by rfezzani** [comment]
I assume yes ^^

**Comment by FeryET** [comment]
It still takes a lot of time on my machine. The image in question is this: https://imgur.com/a/UZbKsw6

**Comment by rfezzani** [comment]
Hello @FeryET, can you please provide the code sample that takes a lot of time with your image?
