### ISSUE TITLE
Alternative to opencv

### ISSUE THREAD

**Issue by augmen** [scikit-image/scikit-image#2760]
Is scikit -image is alternative to opencv ?

**Comment by stefanv** [comment]
It depends a lot on what you want to do.  OpenCV is currently a better option for real time video stream processing, while we feel that scikit-image has a more Pythonic API for general image processing building blocks.  I suggest you scan the API docs for both libraries, and choose whichever best suits your problem.  The two libraries both expose NumPy arrays, and can be used together without a problem.

See, e.g., http://scikit-image.org/docs/stable/user_guide/data_types.html#working-with-opencv
