### ISSUE TITLE
matlab bwareaopen function equivalence in skimage

### ISSUE THREAD

**Issue by pd-Shah** [scikit-image/scikit-image#2763]
I want to convert this `matlab` code to `python`:

**Matlab:**
`bwareaopen(X,50,8)`

**python**:
` morphology.remove_small_objects(X, min_size=50, connectivity=8)`

1.   is `remove_small_objects` same as `bwareaopen`?

2.    `X` array contains `0` and `1` and `None`, then must be `float` type(because of `nan`)
but `remove_small_objects` function just accept `int` value. how fix this ?

**Comment by stefanv** [comment]
We don't have support for masking, so how would you like the operation to behave with NaNs?

I cannot comment on the similarity between `bwareaopen` and `remove_small_objects`; I do not have a Matlab license.

Please continue further discussion on the mailing list; we reserve this space for development issues.
