### ISSUE TITLE
Discussion about APIs in skimage

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#2794]
This issue is meant to hold the discussion started by @JDWarner in https://github.com/scikit-image/scikit-image/pull/2773#issuecomment-327069240. I've reproduced his comment and @emmanuelle's response below. Mine will follow in the next comment.

--------------

Quoting @JDWarner:

@emmanuelle thanks for raising the API question.  We should think deep thoughts about API more often.  I've been pondering this feature's API, in the context of a few choices made in the past which may not have been ideal.  Most of scikit-image is functional, and we've used this approach for drawing shapes.  However, it seems a class-based approach would be really powerful for generation - particularly iterative work.

Consider if we'd gone a different way:

``` python
novel_image = skimage.draw.ImageGenerator(shape)  # Placeholder name
novel_image.circle(center_coords, radius, label='Circle0')
novel_image.square(coords, label='Square0')
novel_image.show()  # via matplotlib, view in Jupyter

# Draw Circle0 'above' Square0
novel_image['Circle0'].level_raise()  
novel_image.show()

output_image = novel_image.generate()  # Final, full resolution image generated here
```

IMHO, this is very expressive and readable.

Contrast that to the current state; to do anything like the above requires painstaking full-array modification at every intermediate step, and if you want to change anything you have to redo everything.  Slower and less expressive.

``` python
# How it would work now
novel_image = np.zeros(shape)
novel_image[skimage.draw.circle(r, c, radius)] = 1
novel_image[skimage.draw.rectangle(start, end)] = 2
plt.imshow(novel_image)

# Cannot simply overwrite in nearly all real cases, must regenerate
novel_image = np.zeros(shape)
novel_image[skimage.draw.rectangle(start, end)] = 2
novel_image[skimage.draw.circle(r, c, radius)] = 1
plt.imshow(novel_image)
```

This isn't meant to block the PR, just to raise the question: which API would you prefer?  Happy to continue the discussion in another Issue, but it's at least close to on topic here.

-------------------

Quoting @emmanuelle:

@JDWarner I'm not sure I understand if your comment is about the feature proposed by this PR or about the ``draw`` module in general. I'm hardly using the ``draw`` module so I'm not the best person to ask. For the ``data`` module I would prefer to stick with just plain functions, as in this PR. However, reading your comment I realize that the utility functions defined in this PR (like ``_generate_rectangle_mask`` could just call our ``draw.rectangle``, which would simplify the code.

For the draw module I don't have a strong opinion. Performance might be better with your solution but then the API is a bit more complicated (I think) and less numpythonic. I think it really depends on how you use the module. It would be interesting to hear about other opinions.

**Comment by jni** [comment]
@JDWarner, others will speak for themselves but as for me, your first (OO) option made me nauseated. I really hope skimage stays away from such constructs. In this case, a list and a simple utility function could improve the reusability of the functional version, while remaining much simpler:

```python
objects = []
objects.append(skimage.draw.circle(r, c, radius))
objects.append(skimage.draw.rectangle(start, end))
image = skimage.draw.generate_image(shape, objects, labels=[1, 2])
plt.imshow(image)

# change the order
objects.append(objects.pop(0))  # or use objects.insert for specific index
image = skimage.draw.generate_image(shape, objects, labels=[2, 1])
```

There are many advantages to my eyes, but the main ones are:
- familiarity. The functional version uses objects that everyone knows and loves. Anyone who knows Python will recognise the functions being used there.
- discoverability. How is one supposed to know that `novel_image[key].level_raise()` exists? Sure, you can navigate the docs, but, for example, it's not obvious that (a) `novel_image` has a `__getitem__` API, (b) that it's keyed by object label, (c) that the returned objects have a `level_raise` method. And none of these would be discoverable with tab-completion from the IPython terminal.

**Comment by jni** [comment]
@JDWarner I apologise for the "nauseated" wording, re-reading makes me nauseated at my own choice of words. =P But suffice it to say, I don't like the OO API.

**Comment by stefanv** [comment]
!(Thimbleweed Park, Agent Reyes)[https://storage.googleapis.com/images.thimbleweedpark.com/vomit_reyes.gif]

**Comment by stefanv** [comment]
With OO, my general approach is to not use it, unless significant state needs to be carried around (which, in this specific case, I don't think needs to happen).

**Comment by jni** [comment]
@stefanv LOL That GIF was even less necessary than my initial comments!

**Comment by stefanv** [comment]
@jni @JDWarner is an MD; I'm pretty sure this sort of thing doesn't phase him in the least.

**Comment by jni** [comment]
*faze

**Comment by jni** [comment]
Closing this — the API it specifically related to has long been merged. We can reopen if anyone else thinks more discussion needs to happen or make a new issue for other specific API discussions.
