### ISSUE TITLE
Hough Transform: hough_line_peaks error

### ISSUE THREAD

**Issue by seheatwole** [scikit-image/scikit-image#2804]
In developing an image processing script scikit-image(0.13.0-2) that grabs images off a camera and detects lines using the hough_transform with hough_line_peaks, an error appeared related to a lack of lines in the image.  If there is no output from _prominent_peaks() on line 62 of hough_transform.py, the following error occurs:

Traceback (most recent call last):
  File "theodoliteAlign.py", line 82, in <module>
    a, angle, dist = hough_line_peaks(h,theta,d)
  File "/usr/lib/python3.6/site-packages/skimage/transform/hough_transform.py", line 66, in hough_line_peaks
    return (h, angles[a], dists[d])
IndexError: arrays used as indices must be of integer (or boolean) type

This is due to the fact that h, a, d returned from _prominent_peaks are empty matrices and a and d are being used as indexes for the function return.  This happens when grabbing a blank image but previous versions I have used of scikit-image (0.12.3-8) had a different algorithm that didn't fail on blank images.

**Comment by stefanv** [comment]
Thanks for catching that; do you mind submitting a pull request for a fix?  We'd be happy to guide you through that process.

**Comment by seheatwole** [comment]
Sure.  I am new to GitHub but not git.  How do I submit a pull request for
a fix?

**Comment by stefanv** [comment]
Thank you!  Please take a look at this document: http://scikit-image.org/docs/stable/contribute.html

Let me know if anything is unclear.
