### ISSUE TITLE
Backport #2766 to 0.13.x line

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#2807]
NetworkX 2.0 is out now. As such I expect some bug reports unless we backport #2766 to a new release, 0.13.1. (Even then we'll get bug reports but they'll be easier to fix/close. =)

**Comment by stefanv** [comment]
Note to self: build wheels for Python 3.7 too.

**Comment by stefanv** [comment]
Maybe also include #2690, #2716, #2692, #2650, #2640, #2524 ?

**Comment by jni** [comment]
@stefanv #2692 applies to components that are not in 0.13. =) Otherwise making progress towards release...!

**Comment by jni** [comment]
Soo, this actually happened. =P Closing!
