### ISSUE TITLE
Seam Carving Example

### ISSUE THREAD

**Issue by OdEfrV** [scikit-image/scikit-image#2808]
## Description
The example demonstrating seam carving 
(http://scikit-image.org/docs/dev/auto_examples/transform/plot_seam_carving.html) 
is wrong. It works ok for the chosen image but not in general. 

Check the code - 50% reduction - vertical:

```
from skimage import filters, color, io, transform, util, data
from matplotlib import pyplot as plt

original = data.clock()
# original = data.chelsea()
# original = data.coins()

img = util.img_as_float(original)

# as it is in the example
eimg = filters.sobel(color.rgb2gray(img))
wrong = transform.seam_carve(img, eimg, "vertical", int(img.shape[1] * 0.5))


# if we remove 1 seam in each loop
for i in range(int(img.shape[1] * 0.5)):
    eimg = filters.sobel(color.rgb2gray(img))
    img = transform.seam_carve(img, eimg, 'vertical', 1)

plt.figure()
plt.subplot(131), plt.imshow(original, 'gray'), plt.title("image")
plt.subplot(132), plt.imshow(wrong, 'gray'), plt.title("wrong")
plt.subplot(133),  plt.imshow(img, 'gray'), plt.title("correct")
plt.tight_layout()
plt.show()

```
 Resutls
![results](https://user-images.githubusercontent.com/10627297/30772633-fa86caea-a067-11e7-9e0c-eb5e46b34644.png)

The second one is a content aware result. The first seems like a cropping result.
Probably, the problem is  that the initial energy matrix is used unaltered for the entire reduction process. According to Avidan-Samir's paper the matrix should be updated in every iteration (the paper describes the removal of 1 seam only). This is simulated in the second part of the code

**Comment by stefanv** [comment]
The algorithm is supposed to not be entirely naive in this regard: https://github.com/scikit-image/scikit-image/pull/1459/files#diff-c6085e56110fa47a584ce0007fa3363aR61

However, your example undoubtedly shows buggy behavior.

@vighneshbirodkar Do you have time to take a look, or should we find another reviewer?

**Comment by vighneshbirodkar** [comment]
Removing 5 seams at a time also gives us the correct result. 
```python
from matplotlib import pyplot as plt
from skimage import color, data, filters, io, transform, util

original = data.clock()
# original = data.chelsea()
# original = data.coins()

img = util.img_as_float(original)

# as it is in the example
eimg = filters.sobel(color.rgb2gray(img))
wrong = transform.seam_carve(img, eimg, "vertical", int(img.shape[1] * 0.5))


# if we remove 1 seam in each loop
for i in range(0, int(img.shape[1] * 0.5), 5):
    eimg = filters.sobel(color.rgb2gray(img))
    img = transform.seam_carve(img, eimg, 'vertical', 5)

plt.figure()
plt.subplot(131), plt.imshow(original, 'gray'), plt.title("image")
plt.subplot(132), plt.imshow(wrong, 'gray'), plt.title("wrong")
plt.subplot(133),  plt.imshow(img, 'gray'), plt.title("correct")
plt.tight_layout()
plt.show()
```


My intention was to make this function remove as many seams as requested without recalculating the energy function and the user could call the function multiple times to remove multiple seams. The functions API right now does not allow for recalculating seams since the user specifies the energy image.

**Comment by stefanv** [comment]
This could potentially be fixed by either documenting this suggestion, or by adding another utility function that runs such a loop.

**Comment by vighneshbirodkar** [comment]
Does anyone in this thread or the community have a preference ? I prefer the documentation approach since the utility function will need to ask the user for a callback function and make matters more complicated.

**Comment by stefanv** [comment]
I'm sure @jni will have an opinion.

**Comment by jni** [comment]
@stefanv your prediction is incorrect. =P

However, I can provide a hastily-formed opinion. Namely, that most of our functions should *not* require writing a for-loop. I expect most users will want to say `seam_carve(image, new_size)` and be done with it. I don't know enough about the algorithm to know what the best approach is to achieve this, but a default of sobel filter as the energy function, and a kwarg like `energy_recalculation_frequency` but more concise would work well imho.

**Comment by stefanv** [comment]
Yes, having an algorithm that carves "badly" by default won't do, and agreed on not wanting to make users write loops when we know exactly how those loops should look.

**Comment by axu2** [comment]
I think the forward energy algorithm would be the best choice as the default since its similar to what Photoshop does:
https://github.com/scikit-image/scikit-image/issues/3082

(The thing is, I'm having trouble figuring out how to translate my code to cython and was wondering if anyone could offer a little guidance.)

**Comment by jni** [comment]
@axu2 here is a notebook from a lecture I gave on the topic:

https://github.com/jni/aspp-2017-cython

and here it is with solutions

https://github.com/jni/aspp-2017-cython-solutions

The super-short summary is:

- start with a Python function
- (optional: move the inner loop to a separate function; this is in case you want a Python interface. If you only want your function to be used in Cython, ignore this step.)
- move the function you want to Cythonise to a .pyx file
- annotate the input and output types
- use "cython -a file.pyx" to see an annotated output "file.html"
- annotate variable types until that annotated output is white

See also Cython's official tutorial:
http://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html

and the working with NumPy arrays page:
http://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#memoryviews

I hope this helps!

**Comment by sciunto** [comment]
Closed because this algorithm is not part of scikit image any more.
