### ISSUE TITLE
hog: gradient calculations are different from OpenCV 

### ISSUE THREAD

**Issue by rdabane** [scikit-image/scikit-image#2809]
## Description
I was trying to compare the HOG descriptor generation between scikit-image and OpenCV.

scikit-image/Features/_hog.py:

150:   gy, gx = [np.ascontiguousarray(g, dtype=np.double)
                          for g in np.gradient(image)]

The function np.gradient calculates as : 
![image](https://user-images.githubusercontent.com/15036829/30832196-194f0814-a1ff-11e7-8694-19e91669fbad.png)

In OpenCV: 
https://github.com/opencv/opencv/blob/master/modules/objdetect/src/hog.cpp
Line 456:
dx0 = lut[p2[2]] - lut[p0[2]];

So the gradients are off by a factor of 2.

**Comment by stefanv** [comment]
I'm not sure I understand: the numpy gradient computation seems correct?

**Comment by rdabane** [comment]
Assuming that intention is to reproduce functionality from original HoG paper(http://lear.inrialpes.fr/people/triggs/pubs/Dalal-cvpr05.pdf)  which suggests following : "Simple 1-D [−1, 0, 1] masks at σ=0 work best."

Then in this case, the OpenCV implementation looks correct.

**Comment by stefanv** [comment]
I see, thanks for the clarification.  OK, so should be fairly easy to fix.  And we'll have to compare with OpenCV output to make sure things look right.

/cc @ivoflipse @Korijn @TimSC

**Comment by rdabane** [comment]
Ok. Thanks! Please let me know if I can of any help.

**Comment by soupault** [comment]
@rdabane you might be interested in the comparison in https://github.com/scikit-image/scikit-image/pull/2040, especially, this comment https://github.com/scikit-image/scikit-image/pull/2040#issuecomment-207751721 .

**Comment by stefanv** [comment]
@soupault I think you are, perhaps, in the best position to make a call on this issue.

**Comment by Korijn** [comment]
Parameterize a choice between the two modes perhaps?

**Comment by soupault** [comment]
Yes, my bad. It was in line with the paper earlier - https://github.com/scikit-image/scikit-image/commit/cdff8254bad8f56b81047df92cc12beccff024aa#diff-d8734512e866681c570f51f5d398f882L104. I'd revert the corresponding changes (this would also imply regenerating reference HOG matrices in `skimage/data`), and update the comparison (https://github.com/scikit-image/scikit-image/pull/2040#issuecomment-207715794).
Parameterization is also a solution, although I think that the API is quite populated already.

**Comment by stefanv** [comment]
This feels more like a bug than a bad API---in which case, I think we should fix it.
