### ISSUE TITLE
Inconsistent behaviour of ImageCollection

### ISSUE THREAD

**Issue by maaleske** [scikit-image/scikit-image#2811]
# Problem
Calling `ImageCollection` with a string file pattern vs. a list of filenames produces different results when using a custom `load_func` to read files not supported by pillow. 

I ran into this while trying to use `open_rasterio` from [xarray](https://github.com/pydata/xarray)  as a load_func for `ImageCollection`, though this will undoubtedly come up with any files not readable with `Image.open` from PIL.

## Examples

This works:
```python
files = glob('*.dat')
ims = ImageCollection(files, load_func=open_rasterio)
ims[0] # prints the returned xarray
```

This does not:
```python
ims = ImageCollection('*.dat', load_func=open_rasterio)
ims[0] #  `IndexError: There are only 0 images in the collection`
```
## Cause

The reason is that with the pattern, `_find_images` sets `_numframes` to 0, since PIL cannot open any of the files (even though the load_func has no problems opening them):
https://github.com/scikit-image/scikit-image/blob/8c79a2c96f6e20bcfe4a3e6e4ea812ca74899b80/skimage/io/collection.py#L159-L169

https://github.com/scikit-image/scikit-image/blob/8c79a2c96f6e20bcfe4a3e6e4ea812ca74899b80/skimage/io/collection.py#L197-L221

This in turn results in an error later when `_numframes` is checked.

**Comment by stefanv** [comment]
This isn't exactly a bug, since the documentation specifies that the file pattern needs to be a list in this case:

```
ImageCollection can be modified to load images from an arbitrary
source by specifying a combination of `load_pattern` and
`load_func`.  For an ImageCollection ``ic``, ``ic[5]`` uses
``load_func(file_pattern[5])`` to load the image.
```

That said, I can see how that would be a useful feature to have, so feel free to add this in a PR.

**Comment by maaleske** [comment]
@stefanv I was quite confused by the documentation here. While that bit implicitly implies that a list is desired when specifying load_func, the latter example with `imread_convert` uses the normal pattern.

Another source of confusion is the fact that the `_files` attribute is not emptied by `_find_images` when it finds no images. This also means that whenever  any file matched by the pattern is not loaded by PIL, the `_files` attribute goes out of sync with the images in the collection. I doubt that this is intended functionality?

I'm willing to take a shot at fixing this, but I'm not clear on what the best solution is. It seems the possible options are to
 1. Always use `_find_images` to try and count the frames, which will fully disable loading any files not supported by PIL.
 2. Always set `_num_frames` to `len(_files)`, which makes the former parameter redundant, and breaks functionality for multi-image tiffs, etc.
 3. Somehow use the given `load_func` in place of PIL in `_find_images` to read the number of frames, which is probably not possibly without more specifications placed on `load_func`
 4. Keep the current behaviour and document it explicitly (and possibly fix the `_files` desync issue)

Any suggestions / comments?

**Comment by stefanv** [comment]
@maaleske You're right; that is very confusing!

1. We do not want to disable loading files not supported by PIL.
2. I think it is reasonable to set _num_frames to len(_files) when a load func is provided.
3. It's unclear to me how that would look in practice.
4. An option, but maybe (2) is more desirable?

**Comment by maaleske** [comment]
@stefanv Making the change only for the load_func case still breaks MultiImage, since it relies on the old behaviour. I think the sensible way to fix it would be to separate all multi-image branching in ImageCollection behind a parameter or to a separate class, but that's a more involved undertaking.

**Comment by mkcor** [comment]
@maaleske I'm closing this issue, since I can run successfully
```py
from glob import glob
import xarray as xr
from skimage import io

files = glob('data/*.tif')

ic_load_list = io.ImageCollection(files, load_func=xr.open_rasterio)
ic_load_pattern = io.ImageCollection('data/*.tif', load_func=xr.open_rasterio)

xr.testing.assert_equal(ic_load_list[1], ic_load_pattern[1])
```
on current `master`, where I've used the test data file which the [xarray docs](http://xarray.pydata.org/en/stable/io.html?highlight=rasterio#rasterio) link to. I've copied this test data file `RGB.byte.tif` into `RGB_2.byte.tif` under the same test data directory, so that the `ImageCollection` object would be of length 2. Likewise, I can run:
```py
from glob import glob
import numpy as np
from skimage import data_dir, io


def imread_convert(f):
    return io.imread(f).astype(np.float64)

files = glob(data_dir + '/chess*.png')

ic_load_list = io.ImageCollection(files, load_func=imread_convert)
ic_load_pattern = io.ImageCollection(data_dir + '/chess*.png', load_func=imread_convert)

np.array_equal(ic_load_list[1], ic_load_pattern[1])
```
