### ISSUE TITLE
plot_hog.py example has typo in hog() method visualise keyword argument

### ISSUE THREAD

**Issue by DrGFreeman** [scikit-image/scikit-image#2812]
## Description
plot_hog.py example has typo in `hog()` method `visualise` keyword argument. Keyword argument used is `visualize` whereas the [method documentation](http://scikit-image.org/docs/stable/api/skimage.feature.html#skimage.feature.hog) refers to `visualise`.

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-2-4607ce514679> in <module>()
      8 
      9 fd, hog_image = hog(image, orientations=8, pixels_per_cell=(16, 16),
---> 10                     cells_per_block=(1, 1), visualize=True)
     11 
     12 fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4), sharex=True, sharey=True)

TypeError: hog() got an unexpected keyword argument 'visualize'
```

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example: [doc/examples/features_detection/plot_hog.py](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/features_detection/plot_hog.py)
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [x] Python version: '3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]'
- [x] scikit-image version (run `skimage.__version__`): '0.13.0'

**Comment by soupault** [comment]
You, most likely, have a badly-version codebase.

For 0.13:
https://github.com/scikit-image/scikit-image/blob/v0.13.x/skimage/feature/_hog.py#L26
https://github.com/scikit-image/scikit-image/blob/v0.13.x/doc/examples/features_detection/plot_hog.py#L91

For 0.14 we have `visualize` as a new parameter name:
https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/_hog.py#L26
https://github.com/scikit-image/scikit-image/blob/master/doc/examples/features_detection/plot_hog.py#L91
