### ISSUE TITLE
`transform.hough_ellipse` raises error if called with an array of zeros (all black image)

### ISSUE THREAD

**Issue by Eskapp** [scikit-image/scikit-image#2820]
When calling `transform.hough_ellipse` with a all black image, the following error is raised:
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-4d14c0917102>", line 3, in <module>
    result = hough_ellipse(np.zeros((100, 100)))
  File "C:\Anaconda3\lib\site-packages\skimage\transform\hough_transform.py", line 163, in hough_ellipse
    min_size=min_size, max_size=max_size)
  File "skimage/transform/_hough_transform.pyx", line 150, in skimage.transform._hough_transform._hough_ellipse (skimage\transform\_hough_transform.c:3881)
ValueError: Buffer and memoryview are not contiguous in the same dimension.
```
Linked to the SO question: https://stackoverflow.com/questions/46470492/buffer-and-memoryview-are-not-contiguous-in-the-same-dimension-in-python/46513914#46513914 (`scikit-image 0.12.3`)

and reproduced with `scikit-image 0.13.0` running the following:

```
import numpy as np
from skimage.transform import hough_ellipse
result = hough_ellipse(np.zeros((100, 100)))
```

I believe that the appropriate behavior would be to return an empty list.

**Comment by stefanv** [comment]
Great catch, thanks @Eskapp.  Do you have time to prepare a PR to fix this?

**Comment by Eskapp** [comment]
Depends on the deadline. I defended my PhD thesis last week and hence have some sharp deadlines this week!
However this sounds like an easy bug to fix and could be great to start off working on this repo.
I will have a look at the link you gave me here: https://github.com/scikit-image/scikit-image/issues/2765
(You can also assign this to me btw)

If the deadline is not too sharp, assign this issue to me.

**Comment by stefanv** [comment]
Congratulations!  That's a big milestone in your life.

There's no urgent deadline for this, so I'm happy to have you take care of it next week.

**Comment by soupault** [comment]
@Eskapp Hi! Did you have a change to look at the issue?

**Comment by Eskapp** [comment]
I just updated my fork to look at it. I ran into another similar issue today using `hough_line_peaks`. When the `threshold` parameter does not allow the detection of any peaks, the function raises an `IndexError`.
It looks like the 2 errors stem from the same issue: Images with not enough contours (or all black).

I'll look at these 2 things tomorrow. And come with an update about whether I was able to fix this or not.

**Comment by Eskapp** [comment]
So I am having issues with my IDE (Pycharm) not recognizing `.pyx` files...
I could not solve the problem. Any idea of how I could fix it? (I have never used Cython before) @soupault

**Comment by Eskapp** [comment]
I'll keep on investigating tomorrow. I had problems with my IDE recognizing Cython files at first which I just solved.

**Comment by Eskapp** [comment]
So yeah, I cannot get out of my issue to even start working on solving the bug.
If I input:
`from skimage.transform.hough_transform import hough_line, hough_line_peaks`
I get:
```
Traceback (most recent call last):
  File "D:\scikit-image\skimage\__init__.py", line 153, in <module>
    from ._shared import geometry
ImportError: cannot import name 'geometry'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\scikit-image\skimage\__init__.py", line 156, in <module>
    _raise_build_error(e)
  File "D:\scikit-image\skimage\__init__.py", line 137, in _raise_build_error
    %s""" % (e, msg))
ImportError: cannot import name 'geometry'
It seems that scikit-image has not been built correctly.
Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
http://scikit-image.org/docs/stable/install.html 
```
