### ISSUE TITLE
Issue Installing scikit-image for python 3.6 from pip 

### ISSUE THREAD

**Issue by Tinanox** [scikit-image/scikit-image#2839]
## Description
I am having issues installing scikit-image from pip. While compiling, it stopped and give me the following error:

```
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'skimage._shared.geometry' extension
    compiling C sources
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\skimage
    creating build\temp.win32-3.6\Release\skimage\_shared
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo
 /Ox /W3 /GL /DNDEBUG /MD -Ic:\python36-32\lib\site-packages\numpy\core\include
-Ic:\python36-32\include -Ic:\python36-32\include -I"C:\Program Files (x86)\Micr
osoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\i
nclude\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Pro
gram Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows
Kits\8.1\include\winrt" /Tcskimage\_shared\geometry.c /Fobuild\temp.win32-3.6\Re
lease\skimage\_shared\geometry.obj
    Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\
cl.exe
    geometry.c
    c:\python36-32\include\pyconfig.h(222): fatal error C1083: Cannot open inclu
de file: 'basetsd.h': No such file or directory
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\c
l.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python36-32\lib\site-packages\num
py\core\include -Ic:\python36-32\include -Ic:\python36-32\include -I"C:\Program
Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\W
indows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits
\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\s
hared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program File
s (x86)\Windows Kits\8.1\include\winrt" /Tcskimage\_shared\geometry.c /Fobuild\t
emp.win32-3.6\Release\skimage\_shared\geometry.obj" failed with exit status 2

    ----------------------------------------
Command "c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='
C:\\Users\\Antoine\\AppData\\Local\\Temp\\pip-build-72i1uxwn\\scikit-image\\setu
p.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users
\Antoine\AppData\Local\Temp\pip-d0vobsgt-record\install-record.txt --single-vers
ion-externally-managed --compile" failed with error code 1 in C:\Users\Antoine\A
ppData\Local\Temp\pip-build-72i1uxwn\scikit-image\
```
It seem to be missing 'basetsd.h' but i didn't see any issues like this. Does someone know what's the problem ?
My configuration: Windows 8.1, python 3.6 (32bit), pip3 module up-to-date

Thank you.

**Comment by soupault** [comment]
@matthew-brett @cgohlke Could you, please, take a look? Thanks in advance!

**Comment by matthew-brett** [comment]
Sorry - I'm a bit out of the loop on scikit-image and Windows.  You aren't currently distributing Windows wheels, I believe because Scipy doesn't have them yet - although that is about to change - with the upcoming Scipy 1.0 release.    I guess it would be worth adding a Python 3.6 matrix entry to the appveyor file.  I'll send a PR.  But for the specific error - no I haven't seen it - but I have never tried to build scikit-image on Windows.

**Comment by matthew-brett** [comment]
Hmm - no crash for Python 3.6.1 32-bit on Appveyor : https://ci.appveyor.com/project/matthew-brett/scikit-image/build/1.0.3/job/f2gd8dwn8c3wuxfv

**Comment by stefanv** [comment]
@Tinanox Does this help? https://stackoverflow.com/a/42624713/214686

**Comment by Tinanox** [comment]
Thank you for the StackOverflow, this seems to be exactly my error and I will look into it.

**Comment by soupault** [comment]
@Tinanox any updates regarding the issue?

**Comment by cayman1021** [comment]
Same problem here.
"pip install scikit-image" ends up in these error messages.
Please help. :(

**Comment by jni** [comment]
@cayman1021 did you check the link provided by @stefanv? https://stackoverflow.com/a/42624713/214686

**Comment by AliceDinh** [comment]
This is the error I get:

error: Command "C:\Users\Dinh Nhan\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Id:\python\python\lib\site-packages\numpy\core\include -Id:\python\python\lib\site-packages\numpy\core\include -Id:\python\python\include -Id:\python\python\PC /Tcskimage\external\tifffile\tifffile.c /Fobuild\temp.win-amd64-2.7\Release\skimage\external\tifffile\tifffile.obj" failed with exit status 2

**Comment by alyato** [comment]
I install the `dev_version` in the ubuntu 14.04,following the installation
When i do this step `pip install -e .`
it show that

> Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/hey/scikit-image/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/hey/scikit-image/

how to fix it ? Thanks.

**Comment by stefanv** [comment]
@alyato Your issue is unrelated, so please file a new issue for further discussion.  Also please post the output of `python setup.py build_ext -i` there.

**Comment by FNicolai** [comment]
For me, this was the crazy solution! (Way to low score)
https://stackoverflow.com/questions/48226362/scikit-image-fails-to-install

**Comment by jni** [comment]
@FNicolai 😱😱😱😱 That *is* crazy.

**Comment by stefanv** [comment]
@FNicolai Which package is trying to print UTF-8 characters out during installation?  That definitely shouldn't happen.

**Comment by FNicolai** [comment]
@stefanv Ahhh... could you tell me how to find out?! 🙈 I'm new to python. Had the problem. Googled. Tried. Fixed. Reported the hint. I will try to help an give further information.

**Comment by stefanv** [comment]
I see this problem all over the place, but cannot find a good analysis of what happens.  The best we can do for now, I think, is to add a small note into the installation instructions for Windows.  Do you want to make a PR for that?

**Comment by FNicolai** [comment]
Crazy bug. No logs or something I could upload?!

I'll create a PR.

**Comment by ShyamSunderSuthar** [comment]
https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image
Download from the following location it definately helped me....
scikit_image-0.13.1-cp27-cp27m-win32.whl>> I dowloaded and 

to install type
pip install filename
here:
pip install scikit_image-0.13.1-cp27-cp27m-win32.whl

**Comment by Zulfidin** [comment]
same problem for: pip install -U scikit-learn

Error:
Collecting scikit-learn
  Using cached https://files.pythonhosted.org/packages/25/b6/454cf208be93efa3db50ce06b732328c57ede005d1dcfa71d9a1548530b0/scikit-learn-0.19.2.tar.gz
Building wheels for collected packages: scikit-learn
  Running setup.py bdist_wheel for scikit-learn ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rcwBc_/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-1BNAcX --python-tag cp27:
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "/tmp/pip-install-rcwBc_/scikit-learn/setup.py", line 148, in get_scipy_status
      import scipy
  ImportError: No module named scipy
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-rcwBc_/scikit-learn/setup.py", line 269, in <module>
      setup_package()
    File "/tmp/pip-install-rcwBc_/scikit-learn/setup.py", line 259, in setup_package
      .format(scipy_req_str, instructions))
  ImportError: Scientific Python (SciPy) is not installed.
  scikit-learn requires SciPy >= 0.13.3.
  Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
  
  
  ----------------------------------------
  Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Failed to build scikit-learn
Installing collected packages: scikit-learn
  Running setup.py install for scikit-learn ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rcwBc_/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-s27Ean/install-record.txt --single-version-externally-managed --compile:
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "/tmp/pip-install-rcwBc_/scikit-learn/setup.py", line 148, in get_scipy_status
        import scipy
    ImportError: No module named scipy
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rcwBc_/scikit-learn/setup.py", line 269, in <module>
        setup_package()
      File "/tmp/pip-install-rcwBc_/scikit-learn/setup.py", line 259, in setup_package
        .format(scipy_req_str, instructions))
    ImportError: Scientific Python (SciPy) is not installed.
    scikit-learn requires SciPy >= 0.13.3.
    Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rcwBc_/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-s27Ean/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-rcwBc_/scikit-learn/


pip 18.0

**Comment by Hareen-a** [comment]
C:\Users\Nuwantha>pip install skimage
Collecting skimage
  Using cached skimage-0.0.tar.gz (757 bytes)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nuwantha\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nuwantha\\AppData\\Local\\Temp\\pip-install-lgib4va6\\skimage_09474a48019a4022825b6b4a4d4df04c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nuwantha\\AppData\\Local\\Temp\\pip-install-lgib4va6\\skimage_09474a48019a4022825b6b4a4d4df04c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Nuwantha\AppData\Local\Temp\pip-pip-egg-info-s4bd9ewv'
         cwd: C:\Users\Nuwantha\AppData\Local\Temp\pip-install-lgib4va6\skimage_09474a48019a4022825b6b4a4d4df04c\
    Complete output (3 lines):

    *** Please install the `scikit-image` package (instead of `skimage`) ***

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Already i have downloaded the scikit-image. but this error occurs.so can you please tell how i fix this error.allready i have run this code also "pip3 install python-language-server"
