### ISSUE TITLE
Crash on 64-bit Windows build, maybe in test_finite_radon_transform

### ISSUE THREAD

**Issue by matthew-brett** [scikit-image/scikit-image#2841]
I just tried enabling more Windows builds in the Appveyor script:

https://github.com/scikit-image/scikit-image/pull/2840

One of the builds I enabled was the Python2.7 64-bit build.  It appears to crash:

```
Python27-x64\lib\site-packages\skimage\transform\tests\test_finite_radon_transform.py Command exited with code -1073740940
```

https://ci.appveyor.com/project/matthew-brett/scikit-image/build/1.0.2/job/kkqeg7ndq9fww5ty#L3073

**Comment by matthew-brett** [comment]
Crash appears to be specific to 64-bit Python 2.7 - no crash on Pythons 3 : https://ci.appveyor.com/project/matthew-brett/scikit-image/build/1.0.3

**Comment by grlee77** [comment]
closing as no longer relevant (Python 2 was dropped long ago)
