### ISSUE TITLE
Default argument set with mutable type in `draw_multiblock_lbp`

### ISSUE THREAD

**Issue by glemaitre** [scikit-image/scikit-image#2850]
## Description
In `skimage.feature.draw_multiblock_lbp`, some default arguments are set with a list which is a mutable argument:
https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/texture.py#L372

I think that you should use tuple instead for the following reason:
http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments

**Comment by soupault** [comment]
Absolutely! Thanks for the finding!

**Comment by AlexChum** [comment]
Hi! 
I was browsing through the scikit-image source files to get a better understanding of what I was using and looked at the issues out of curiosity. Found a novice tagged issue!
I submitted a pull request #2852 to fix it.
Let me know if this works out! 
My first commit to open source.

**Comment by soupault** [comment]
Closed via #2852
