### ISSUE TITLE
Frequency response of `iradon()` filters differs greatly from the same filters in MATLAB

### ISSUE THREAD

**Issue by TheChymera** [scikit-image/scikit-image#2853]
## Description
The frequency response I get with different filters from `skimage.transform.iradon()` is not consistent with the results from MATLAB. 

As `scikit-image` does not return the frequency response like MATLAB does, I have simply isolated the code which produces the filter from [the relevant site in `iradon()`](https://github.com/scikit-image/scikit-image/blob/5a0c5a5f03438ae483b2fc9612c9d634c74c2786/skimage/transform/radon_transform.py#L222) in order to create the example below.

## Way to reproduce
Run:

```
import matplotlib.pylab as plt
import numpy as np
from scipy.fftpack import fftfreq
from skimage import data_dir
from skimage.io import imread
from skimage.transform import iradon, radon

def frequency_response(filter, radon_image):
	projection_size_padded = \
        max(64, int(2 ** np.ceil(np.log2(2 * radon_image.shape[0]))))
	f = fftfreq(projection_size_padded).reshape(-1, 1)
	omega = 2 * np.pi * f                                # angular frequency
	fourier_filter = 2 * np.abs(f)                       # ramp filter
	if filter == "ramp":
		pass
	elif filter == "shepp-logan":
		# Start from first element to avoid divide by zero
		fourier_filter[1:] = fourier_filter[1:] * np.sin(omega[1:]) / omega[1:]
	elif filter == "cosine":
		fourier_filter *= np.cos(omega)
	elif filter == "hamming":
		fourier_filter *= (0.54 + 0.46 * np.cos(omega / 2))
	elif filter == "hann":
		fourier_filter *= (1 + np.cos(omega / 2)) / 2
	elif filter is None:
		fourier_filter[:] = 1
	else:
		raise ValueError("Unknown filter: %s" % filter)

	return fourier_filter

image = imread(data_dir + "/phantom.png", as_grey=True)
theta = np.linspace(0., 180., max(image.shape), endpoint=False)
sinogram = radon(image, theta=theta, circle=True)

filters = ['ramp', 'shepp-logan', 'cosine', 'hamming', 'hann']
fig, ax = plt.subplots(1, len(filters), figsize=(10,2))

for ix, f in enumerate(filters):
	reconstruction_fbp = iradon(sinogram, theta=theta, circle=True, filter=f)
	response = frequency_response(f, sinogram)
	ax[ix].plot(response)
	ax[ix].set_title('{} FBP'.format(f))
plt.show()
```

Compare to the frequency response from MATLAB (returned along the filtered back projection, e.g. `[F1, FH1] = iradon(sinogram, theta, 'linear', 'Ram-Lak');`):
![from_matlab](https://user-images.githubusercontent.com/950524/31863083-a315b35a-b748-11e7-956e-ce46ada18c86.png)

**Comment by stefanv** [comment]
@TheChymera Do you have time to look into this further?  Something's clearly not right.

**Comment by TheChymera** [comment]
@stefanv sadly I am very swamped atm, I can try to put it in my notes for when I have more time, but as PET is not my main line of work I feel this will always be outprioritized, I think providing a minimal working example is all I can do.

**Comment by oachkatzlschwoaf123** [comment]
Is this how the filters should look like?

![image](https://user-images.githubusercontent.com/6386428/33155772-f5ca1856-cfb8-11e7-8991-32953e181e9e.png)


[Source](https://www.researchgate.net/publication/251915833_A_prototype_system_for_infrared_computed_tomography_for_image_reconstruction)

**Comment by TheChymera** [comment]
Yes, and this is what MATLAB seems to do. In the `scikit-image` implementation, the cosine and particularly the Hamming filter don't look like that.

**Comment by oachkatzlschwoaf123** [comment]
I do not have access to the MATLAB functions, but I took a look at the [Octave rho_filter function](https://sourceforge.net/p/octave/image/ci/default/tree/inst/rho_filter.m#l130) and edited the code to match that.  They now appear to be the same as the MATLAB filters posted above.   

[Octave rho_filter ref]()

The frequencies from fftfreq that were originally used works for the Ram-Lak and Shepp-Logan filter, but not for the Cosine filter.  The Octave code actually uses sin to obtain the shape of the filter.  Cosine can be used, but it needs to go from -pi/2 to pi/2 to get the same shape.  For the Hamming and Hanning, I just used the respective functions from numpy and did a fftshift.  Not centering the zero frequency component gives an incorrect shape.  This shift is also performed for the cosine filter.

I can finalize the changes and submit a pull request sometime over the weekend.

![image](https://user-images.githubusercontent.com/6386428/33163182-cc6c85e0-cff2-11e7-9628-b298cb7bc7c8.png)
Corresponds to 0 -> 2 pi


![image](https://user-images.githubusercontent.com/6386428/33163177-c14b01f0-cff2-11e7-88c0-16aaa6763833.png)
Corresponds to 0 -> pi


```
import numpy as np
import matplotlib.pylab as plt
from scipy.fftpack import fftfreq
from skimage import data_dir
from skimage.io import imread
from skimage.transform import iradon, radon


def frequency_response(filter):
    
    projection_size_padded = 1024
    f = fftfreq(projection_size_padded).reshape(-1, 1)
    fourier_filter = 2 * np.abs(f)                       # ramp filter
    
    if filter == "ramp":
        pass
    elif filter == "shepp-logan":
        shepp_logan_filter = np.zeros((int(projection_size_padded)))
        shepp_logan_filter[1:] = np.sin(np.pi * np.abs(f[1:,0])) / (np.pi * np.abs(f[1:,0]))
        shepp_logan_filter[0] = 1
        fourier_filter[:,0] *= shepp_logan_filter
        
    elif filter == "cosine":
        freq = 0.5 * np.arange(0,projection_size_padded) / projection_size_padded 
        cosine_filter = np.fft.fftshift(np.sin(2 * np.pi * np.abs(freq)))
        fourier_filter[:,0] *= cosine_filter
    elif filter == "hamming":
        hamming_filter = np.fft.fftshift(np.hamming(projection_size_padded))
        fourier_filter[:,0] *= hamming_filter
    elif filter == "hann":
        hanning_filter = np.fft.fftshift(np.hanning(projection_size_padded))
        fourier_filter[:,0] *= hanning_filter
    elif filter is None:
        fourier_filter[:] = 1
    else:
        raise ValueError("Unknown filter: %s" % filter)
    
    return fourier_filter



filters = ['ramp', 'shepp-logan', 'cosine', 'hamming', 'hann']
fig, ax = plt.subplots(1, len(filters), figsize=(10,2))

for ix, f in enumerate(filters):
    response = frequency_response(f)
    ax[ix].plot(response)
    ax[ix].set_title('{} FBP'.format(f))


plt.tight_layout()
    
plt.show()    

```
## Code From Above Output 
![image](https://user-images.githubusercontent.com/6386428/33161825-a7cdea64-cfeb-11e7-9793-9f2dc6ec9a79.png)

## Octave Output
![deepinscreenshot_select-area_20171123013423](https://user-images.githubusercontent.com/6386428/33162317-9f7098f0-cfee-11e7-9f91-62080412b2fe.png)

**Comment by stefanv** [comment]
Thanks a bunch for identifying the problem! We look forward to your PR.
