### ISSUE TITLE
Investigate QT5 as an import point for our viewer dependencies

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2863]
Currently, we make use of Matplotlib as a QT4/5-agnostic import.  @tacaswell recommends investigating https://github.com/spyder-ide/qtpy

**Comment by soupault** [comment]
xref https://github.com/scikit-image/scikit-image/issues/2745

**Comment by stefanv** [comment]
Other option (from #2912): https://github.com/mottosso/Qt.py

**Comment by tacaswell** [comment]
The other option is just drop pyqt4 as riverbank has pulled the packages from pypi https://pypi.org/project/PyQt4/ 

On the other hand, even arch is still packaging qt4.

**Comment by soupault** [comment]
Some remarks by @hmaarrfk on the possibility to move the viewer onto `qtpy` - https://github.com/scikit-image/scikit-image/pull/3157#issuecomment-395803698, https://github.com/scikit-image/scikit-image/pull/3157#issuecomment-395810142.

**Comment by hmaarrfk** [comment]
@tacaswell, can you recommend what we should do for the following lines of code if we move to qtpy?

```python
if _qt_version == 5:
    from matplotlib.backends.backend_qt5 import FigureManagerQT
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
elif _qt_version == 4:
    from matplotlib.backends.backend_qt4 import FigureManagerQT
    from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg
else:
    FigureManagerQT = object
    FigureCanvasQTAgg = object
```

**Comment by jni** [comment]
Doesn't qtpy imply Qt5?

**Comment by hmaarrfk** [comment]
No, qtpy can do Qt4 and PySide, both of which are Qt5.

I'm also not sure that matplotlib qt5 `FigureManagerQT` is going to be compatible with PySide2

Apparently though, `backends_qt4` just points to `backends_qt5` as of matplotlib 2.2
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_qt4.py
2.2 might seem like a harsh dependency to have, but if 0.15 will roll out in 2019, then it is 2 years old, and maybe acceptable to have as a dependency at that point?

In 2.0, they were quite different, and in 2.1, only `FigureCanvasQT` was different.

**Comment by jni** [comment]
Well, as we've discussed, the plan is to rip out MPL as a hard dependency, as *that* is very heavy for scikit-image, and have the viewer etc in a separate repo, at which point making MPL2.2 a dependency works for me. (A brand new project can afford brand new dependencies, I think. =)

This is putting a new perspective on the MaskedArray debate over at NumPy. Specifically, I do think the viewer can do better as its own separate project than as part of scikit-image.

**Comment by tacaswell** [comment]
Matplotlib supports pyside2 and all versions of matplotlib still support qt4.  Most of the shimming is done in `qt_compat` or via a `__init__` decorator that lets us pretend that pyqt4/pyside/pyside2 support cooperative multiple inheritance.

@hmaarrfk Those lines should still be fine (you need to pick the right sub-classes to match the Qt version you are using) modulo asking qtpy which version you are on.

You may need to ensure the qtpy is imported before matplotlib and then set both `rcParams['backend']` and `rcParams['backend.qt{4,5}']` to match what qtpy found if you want to support older version of matplotlib (I don't know what the versions are where that will matter off the top of my head).

The code changes between 2.0 -> 2.1 -> 2.2 where were reducing redundant code not removing functionality.
