### ISSUE TITLE
Reconsider `skimage.draw.random_shapes` API

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2884]
From the discussion in https://github.com/scikit-image/scikit-image/pull/2773.

- [ ] Switch from parameter `gray` to `num_channels`, so to make the function truly multichannel;
- [ ] Change `min_pixel_intensity` to `intensity_range` or something with the parameter syntax similar to `np.pad(pad_width=...)`;
- [ ] [Optionally] Allow to specify the background intensity value;
- [ ] Update gallery example to make different images more distinguishable (see http://scikit-image.org/docs/dev/auto_examples/edges/plot_random_shapes.html), potentially, by enabling the axes;
- [ ] Gallery example again. Remove the output, or make it more informative;
- [ ] Check that new features, API changes, and deprecations are mentioned in
`doc/release/release_dev.rst` :smile: .

**Comment by stefanv** [comment]
Very good list of ideas!
