### ISSUE TITLE
Feature request: skimage.io.imdecode

### ISSUE THREAD

**Issue by dwSun** [scikit-image/scikit-image#2889]
## Description
We have to write the image to disk for skimage to read from it.
Why not let skimage.io to decode form a bytes  string directly inside memory.

**Comment by soupault** [comment]
@dwSun this would be a useful feature, I agree. One of the usecases is to decode a received via REST, gRPC bytesting.
Even if we decide not to incorporate such function, you can always use `imread` with `imageio` plugin which supports reading from `bytes` (see http://imageio.readthedocs.io/en/latest/userapi.html#imageio.imread):
```
import os
import skimage
from skimage import io

p = skimage.data_dir
with open(os.path.join(p, 'coins.png'), 'rb') as f:
    b = f.read()

img = imread(b, plugin='imageio')

img

Image([[ 47, 123, 133, ...,  14,   3,  12],
       [ 93, 144, 145, ...,  12,   7,   7],
       [126, 147, 143, ...,   2,  13,   3],
       ..., 
       [ 81,  79,  74, ...,   6,   4,   7],
       [ 88,  82,  74, ...,   5,   7,   8],
       [ 91,  79,  68, ...,   4,  10,   7]], dtype=uint8)
```

**Comment by dwSun** [comment]
@soupault thanks for your reply and your solution. I will use imageio plugin to decode my image bytestring.

**Comment by emmanuelle** [comment]
The solution by @soupault looks simple and straightforward. Do we need a specific function for that? Or should the example appear in the doc? It's my usual reaction to try to keep the API as short as possible :-).

**Comment by soupault** [comment]
@emmanuelle mentioning this case in the docstring will do it for me. :)

**Comment by stefanv** [comment]
Also, `imread` can detect when the object is a bytestream and automatically attempt to use `imageio`?  Also, we should just switch to `imageio` by default.

**Comment by jni** [comment]
I've changed the milestone, because I don't think this should hold up 0.14
