### ISSUE TITLE
ImportError: cannot import name "chan_vese"

### ISSUE THREAD

**Issue by abelguima** [scikit-image/scikit-image#2904]
## Description
[Please provide a general introduction to the issue/proposal.]
Hi guys
I want to use segmentation chan vese but got this error:
abel@abel-System-Product-Name:~/test$ python3
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from skimage import data, img_as_float
>>> from skimage.segmentation import chan_vese
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'chan_vese'
>>> 

[If reporting a bug, attach the entire traceback from Python.]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by abelguima** [comment]
abel@abel-System-Product-Name:~/test$ python3
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from skimage import data, img_as_float
>>> from skimage.segmentation import chan_vese
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'chan_vese'
>>>

**Comment by stefanv** [comment]
What version of scikit-image do you have installed?

**Comment by abelguima** [comment]
What is the command for I can see the version?

**Comment by abelguima** [comment]
>>> print('The skimage version is {}.'.format(skimage.__version__))
The skimage version is 0.13.1.

**Comment by soupault** [comment]
`segmentation.chan_vese` is available only in 0.14dev so far.

**Comment by abelguima** [comment]
ok I will try that thanks!!!
