### ISSUE TITLE
Use external Qt compatibility layer for viewer

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2912]
We currently use the Matplotlib Qt interface to achieve compatibility with PySide + Qt4 + Qt5, but their compatibility backend is not intended for external consumption.

Instead, consider moving to a library such as:

https://github.com/mottosso/Qt.py

See also this StackOverflow question: https://stackoverflow.com/questions/47640724/pyqt5-has-issue-while-importing-in-skimage

**Comment by grlee77** [comment]
Isn't this the same issue as #2863?  

Of particular interest may be the feature comparison table at https://github.com/mottosso/Qt.py#projects-similar-to-qtpy

It looks like the main advantage of https://github.com/mottosso/Qt.py vs https://github.com/spyder-ide/qtpy is in the **co-existence** feature which the `Qt.py` devs describe as:
> Qt.py should not affect other bindings running in same interpreter session.

**Comment by stefanv** [comment]
Ah, I was looking for #2863, couldn't find it earlier; thanks.

**Comment by stefanv** [comment]
Please continue discussion on #2863.
