### ISSUE TITLE
bug in multichannel non-local means if channels != 3

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#2913]
## Description
The non-local means Cython code currently assumes 3 channels when computing multi-channel patch weights, but there is no check that the input images are actually 3 channel.

code that assumes three channels: [here](https://github.com/scikit-image/scikit-image/blob/cf3cdaf35797b0ebbaf155c91ecf5f8b761e0ea5/skimage/restoration/_nl_means_denoising.pyx#L108) and [here](https://github.com/scikit-image/scikit-image/blob/cf3cdaf35797b0ebbaf155c91ecf5f8b761e0ea5/skimage/restoration/_nl_means_denoising.pyx#L467-L472)
Other code outside of the weights computation [already supports arbitrary number of channels](https://github.com/scikit-image/scikit-image/blob/cf3cdaf35797b0ebbaf155c91ecf5f8b761e0ea5/skimage/restoration/_nl_means_denoising.pyx#L637)

If the input images have more than 3 channels, denoising will still occur, but the patch weights will be determined based on only the first 3 channels.  In the off chance that a two-channel image is used, out-of-bounds memory access can occur during computation of the patch weights.

The Cython code should be updated to fully support an arbitrary number of channels.  One real world use case for > 3 channels:  [hyperspectral imaging](https://en.wikipedia.org/wiki/Hyperspectral_imaging).  I volunteer to make a PR to do this.

## Way to reproduce
see the example code linked that demonstrates where the problem lies

alternatively, modify the top of the non-local means Cython code to set `boundscheck=True` and then try denoising only the first two channels of an RGB image.  You will see a lot of messages regarding out-of-bounds access on the memory-views.

**Comment by soupault** [comment]
:+1: to support hyperspectral images, and fix the current behaviour.
Notice, that the first URL links to `patch_distance_2drgb` internals, so assuming 3 channels there makes complete sense.
