### ISSUE TITLE
conflict with networkx on conda?

### ISSUE THREAD

**Issue by zhiruiwang** [scikit-image/scikit-image#2916]
## Description
I use anaconda environment to do package management. When I use `conda update --all` to update my packages, there is a conflict between the newest version of scikit-image(0.13.1) and networkx(2.0). 
```
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::networkx-1.11-py36he1dbd48_0, defaults::scikit-image-0.13.1-py36hd1453f6_0
  - defaults::networkx-2.0-py36hefccab9_0, defaults::scikit-image-0.13.0-py36h398857d_1
```
Is it because scikit-image is using some features which only exist in networkx 1.11, or it is just created by accident?(scikit-image 0.13.0 works fine with networkx 2.0)

## Way to reproduce
`conda update --all` or `conda update networkx`
Showing
```
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::networkx-1.11-py36he1dbd48_0, defaults::scikit-image-0.13.1-py36hd1453f6_0
  - defaults::networkx-2.0-py36hefccab9_0, defaults::scikit-image-0.13.0-py36h398857d_1
```

**Comment by soupault** [comment]
To the best of my knowledge, skimage 0.13.0 is not fully compatible with networkx-2.0 (see https://github.com/scikit-image/scikit-image/pull/2766).

**Comment by jni** [comment]
Which conda channel are you using? It looks like whoever is maintaining the defaults recipe for scikit-image neglected to remove the 2.0 restriction for 0.13.0 when updating the recipe for 0.13.1. In conda-forge, the recipe was correctly updated:

https://github.com/conda-forge/scikit-image-feedstock/pull/16/files

I don't know whom to ping about getting the defaults recipe updated...

**Comment by zhiruiwang** [comment]
Yes, I am using  the default channel... Hope this can be fixed on default channel in the next release.

**Comment by jjhelmus** [comment]
Yes, the scikit-image 0.13.1 conda package in `defaults` has the incorrect requirement on networkx.  I'll create a new build shortly with the correct requirement.  

Feel free to ping me in the future with any issues related to the scikit-image conda packages in `defaults`.  I will try to get them addressed in a timely manner.

**Comment by soupault** [comment]
@jjhelmus great, thank you very much!

**Comment by jjhelmus** [comment]
New builds of the scikit-image 0.13.1 conda packages are now available in `defaults` which have the correct requirement on networkx. 

I believe this should address the multiple solution issue, let me know if it does not.

**Comment by stefanv** [comment]
Thanks, Jonathan!
