### ISSUE TITLE
document the use of circle_perimeter_aa with color image

### ISSUE THREAD

**Issue by ahundt** [scikit-image/scikit-image#2918]
## Description

I tried using circle_perimeter_aa with a color image, but ran into broadcasting issues. 

Is there a clean way to do this:

1. with a black and white circle?
2. with a color circle like (21, 244, 238)?

Here is my attempt:

```
import numpy as np
import skimage.draw as skd
img = np.zeros((500, 500, 3), dtype=np.double)
rr, cc, val = skd.circle_perimeter_aa(60, 40, 30)
img[rr, cc] = val
```

```
ValueError: shape mismatch: value array of shape (344,) could not be broadcast to indexing result of shape (344,3)
```

The closest I could get to something with the right shape is this:

```
aa = np.tile(np.expand_dims(aa, axis=-1), (1, 3)) * (21, 244, 238)
```

but I think that's incorrect....

**Comment by stefanv** [comment]
You need:

```
img[rr, cc] = val[:, np.newaxis] * [1, 0, 0]
```

or

```
skd.set_color(img, (rr, cc), [1, 0, 0], alpha=val)
```

But, agreed, how to manipulate color images should be included as an example of that function, and of all drawing functions.

**Comment by ahundt** [comment]
Worked great, thanks!

```python
rr, cc, aa = circle_perimeter_aa(coordinate[0], coordinate[1], 10, shape=frame.shape)
set_color(frame, (rr, cc), [0, 255, 255], alpha=aa)
```

Could you clarify where the origin is in this API's documentation as well?
