### ISSUE TITLE
Clear border does not work as intended on certain arrays

### ISSUE THREAD

**Issue by pskeshu** [scikit-image/scikit-image#2919]
## Description
My automated pipeline was crashing repeatedly. After a bit of investigation, I concluded that it's because of passing a timeseries array with a single dimension entry which had a shape of [1, N, M], which caused the problem.

## Test Code
```
import numpy as np
from skimage.segmentation import clear_border

a = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 1, 0, 0, 0],
              [0, 0, 1, 1, 1, 1, 1, 0, 0],
              [0, 1, 1, 1, 1, 1, 1, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0]])
print(a.shape)
print(clear_border(a))

a_exp = np.expand_dims(a, axis=0)
print(a_exp.shape)
print(clear_border(a_exp))

```
### Output:

```
(6, 9)
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0]]
(1, 6, 9)
[[[0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]]]
```
## Relevant information (?)
```
Python 3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import skimage; skimage.__version__
'0.13.1'
>>> 
```
Although, as an user, it's much easier to squeeze the dimensions of my mask before calling clear_border()`, but I think the function should also be squeezing the dimensions, just to avoid any confusion. If that's a valid argument, I would be glad to submit a PR for the same.

**Comment by stefanv** [comment]
Please refer to: http://scikit-image.org/docs/stable/user_guide/numpy_images.html#coordinate-conventions

The array with extended dimensions has shape `(1, 6, 9)` and is therefore seen as 9 bands of a `(1, 6)` image.  So, it is not surprising that the functionality is not working as expected.
