### ISSUE TITLE
cannot import name 'chan_vese'

### ISSUE THREAD

**Issue by sudhasubramaniam** [scikit-image/scikit-image#2920]
when I try to import chan_vese from skimage.segmentation , I'm getting the following error. Can some one help me fixing.
ImportError: cannot import name 'chan_vese'

**Comment by soupault** [comment]
@sudhasubramaniam what is the version of your `scikit-image` installation?

**Comment by sudhasubramaniam** [comment]
'0.13.1'

**Comment by soupault** [comment]
`0.13.x` versions do not contain this feature. To be available in `0.14`

**Comment by sudhasubramaniam** [comment]
Thanks for your reply sir
