### ISSUE TITLE
AttributeError: module 'skimage.graph' has no attribute 'rag_mean_color'

### ISSUE THREAD

**Issue by SaeedIqbal** [scikit-image/scikit-image#2926]
i have the following code: for segmentations
label_rgb = segmentation.mark_boundaries(label_rgb, labels, (0, 0, 0))
rag = graph.rag_mean_color(img,labels)
for region in reg:
    rag.node[region['label']]['centroid'] = region['centroid']

ERROR is:

    rag = graph.rag_mean_color(img,labels)
AttributeError: module 'skimage.graph' has no attribute 'rag_mean_color'

[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] UBUNTU 16.04
- [ ] python 3.5
- [ ] scikit-image version --  0.13.0

**Comment by KaptenDavidsson** [comment]
Did you do a 
from skimage.future import graph 
or 
from skimage import graph 

rag_mean_color is in future

What does dir(graph) say?

**Comment by SaeedIqbal** [comment]
Done, It has been resolved. Thanks,
