### ISSUE TITLE
plot_orb.py example not working 

### ISSUE THREAD

**Issue by aymbridge** [scikit-image/scikit-image#2929]
## Description
ORB feature detector and binary descriptor example doesn't work

[If reporting a bug, attach the entire traceback from Python.]
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: array([[ 0.51456067],
       [ 0.34857586],
       [ 0.8428185 ]])

[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ plot_orb.py example] Code   ##example
- [ Mac Os X 10.12.6 ] Operating system and version
- [ Python 2.7.11 --  64-bit ] Python version
- [0.13.0 ] scikit-image version

**Comment by soupault** [comment]
The issue occurs with skimage==0.13.0, but not with 0.13.1. Could you, please, update, and check if it works in your environment as well?

**Comment by soupault** [comment]
Closing due to the lack of feedback.
Feel free to reopen if the issue still occurs.
