### ISSUE TITLE
anaconda kernel dies when importing skimage

### ISSUE THREAD

**Issue by youkaichao** [scikit-image/scikit-image#2931]
hello, i encountered the same problem  as #2074 !

I want to import skimage in jupyter notebook and every time i try, the kernel died.
But when i launch python console and import skimage, it works fine.

I find an answer at stackoverflow which i think is relevant : [https://stackoverflow.com/questions/42912076/the-kernel-appears-to-have-died-it-will-restart-automatically](stackoverflow) , however, the problem remains the same after i update mkl from 2017.0.1-0 to 2017.0.3-0.

**Comment by soupault** [comment]
Could you share the information on your OS and the versions of installed Python + libraries?

**Comment by youkaichao** [comment]
OS : Ubuntu 14.04.5 LTS (GNU/Linux 3.19.0-80-generic x86_64)
python : 2.7.13
conda 4.3.24
skimage : 0.13.0
numpy : 1.13.3

any other things needed to be specified?

**Comment by jni** [comment]
@youkaichao does the problem happen only when you import skimage or also when you import numpy? I expect that this is a NumPy MKL error rather than a scikit-image error. Can you verify this?

**Comment by youkaichao** [comment]
well, the skimage package works now.
I don't know what happened to it. I never login to that remote host last month. Maybe it's because someone on that host changed something? After all, I'm not the only user.
So I think we can conclude that this has nothing to do with my local environment. Maybe it's concerned with some system dependencies.

I remember when I issued this issue, NumPy worked well. It was just skimage that didn't work.

Happy to be of any help 
@jni

**Comment by JDWarner** [comment]
Closing as resolved, likely due to resolved platform-dependent dependency issues.
