### ISSUE TITLE
Saving contour from find_contours as np array

### ISSUE THREAD

**Issue by vukovicnikola** [scikit-image/scikit-image#2933]
Hello!
Once I have a contour (i.e. (n,2)-ndarray) from measure.find_contours, is there a way to save it as an image numpy array? I would like to do some further image processing on just the contour image, but can't figure out how to get them saved in the proper format...
Many thanks for your help!
Nikola

**Comment by soupault** [comment]
If I correctly understood the question, you can use http://scikit-image.org/docs/dev/api/skimage.draw.html#skimage.draw.polygon or http://scikit-image.org/docs/dev/api/skimage.draw.html#skimage.draw.polygon_perimeter to plot the detected contours, and then save the resulting images via https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.save.html .

Closing as not an issue, but feel free to continue the discussion here.

**Comment by vukovicnikola** [comment]
Thank you so much, Egor! Skimage.draw.polygon is exactly what I needed!

**Comment by pinakiweb** [comment]
I want to segment lines from a paragraph and then words from the line. How can I do it using skimage.measure.find_contours. Any other skimage functions will even do. Please help
