### ISSUE TITLE
Median filter does not preserve dtype

### ISSUE THREAD

**Issue by rth** [scikit-image/scikit-image#2943]
The median filter documentation states that the output image will be of the same dtype and the input. However that's not true for gray (float64) inputs.

**Step to reproduce**

```py
from skimage.data import chelsea
from skimage.filters.rank import median
from skimage.color import rgb2gray

X_gray = rgb2gray(chelsea())
print("Input dtype: ", X_gray.dtype)
out = median(X_gray)
print("Output dtype:", out.dtype)
```
which returns
```
Input dtype:  float64
/home/datageek/src/scikit-image/skimage/util/dtype.py:123: UserWarning: Possible precision loss when converting from float64 to uint8
  .format(dtypeobj_in, dtypeobj_out))
Output dtype: uint8
```

Tested on the current master branch (0.14.dev) and 0.13.1 with Python 3.6 on Linux.  
cc @rogersamso

**Comment by soupault** [comment]
@rth see https://github.com/scikit-image/scikit-image/issues/1419, https://github.com/scikit-image/scikit-image/pull/1422 . We would appreciate if you decide to take care of the issue.

**Comment by rth** [comment]
Thanks for the response. I missed that issue. I will try to have a look.
