### ISSUE TITLE
'boolean subtract operator is deprecated' error on Ubuntu but not Mac

### ISSUE THREAD

**Issue by red-eight** [scikit-image/scikit-image#2944]
## Description
When I try to use to use skimage.feature.hog, the python code crashes.

    fd = feature.hog(
        image, 
        orientations=4,
        pixels_per_cell=(4, 4),
        cells_per_block=(4, 4),
        block_norm='L2-Hys')

Here is the traceback (modified my original filename):

>Traceback (most recent call last):
  File "myfile.py", line 205, in <module>
    main()
  File "myfile.py", line 121, in main
    train_data = img_clf.extract_image_features(train_raw)
  File "myfile.py", line 56, in extract_image_features
    block_norm='L2-Hys')
  File "/usr/local/lib/python3.4/dist-packages/skimage/feature/_hog.py", line 162, in hog
    for g in np.gradient(image)]
  File "/usr/local/lib/python3.4/dist-packages/numpy/lib/function_base.py", line 1771, in gradient
    out[slice1] = (f[slice4] - f[slice2]) / (2. * ax_dx)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

It seems like this issue is similar to [issue 2681](https://github.com/scikit-image/scikit-image/issues/2681), but issue 2681 is for an older version of numpy.

## Way to reproduce

I'm not sure what the best way is to provide the original code since it's for a school assignment. The code works without crashing on MacOS Sierra 10.12.4, but does not work on Ubuntu 14.04.5.

OS: Ubuntu 14.04.5 LTS
Python 3.4.3

Versions according to the interpreter:

    $ python3
    Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
    [GCC 4.8.4] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    import skimage
    skimage.__version__
    '0.13.1'
    import numpy
    numpy.__version__
    '1.14.0'

pip3 info:

    $ pip3 freeze
    Brlapi==0.6.1
    Cython==0.27.3
    Keras==2.0.8
    Mako==0.9.1
    MarkupSafe==0.18
    Pillow==5.0.0
    PyWavelets==0.5.2
    PyYAML==3.12
    apturl==0.5.2ubuntu4
    cairocffi==0.8.0
    cffi==1.11.4
    chardet==2.2.1
    checkbox-ng==0.3
    checkbox-support==0.2
    colorama==0.2.5
    command-not-found==0.3
    cycler==0.10.0
    decorator==4.2.1
    defer==1.0.6
    feedparser==5.1.3
    friends==0.1
    h5py==2.2.1
    html5lib==0.999
    httplib2==0.8
    language-selector==0.1
    louis==2.5.3
    lxml==3.3.3
    matplotlib==2.1.1
    networkx==2.0
    nose==1.3.1
    numpy==1.14.0
    oauthlib==0.6.1
    onboard==1.0.1
    oneconf==0.3.7.14.04.1
    piston-mini-client==0.7.5
    plainbox==0.5.3
    pycparser==2.18
    pycrypto==2.6.1
    pycurl==7.19.3
    pygobject==3.12.0
    pyparsing==2.2.0
    python-apt==0.9.3.5ubuntu2
    python-dateutil==2.6.1
    python-debian==0.1.21-nmu2ubuntu2
    pytz==2017.3
    pyxdg==0.25
    requests==2.2.1
    scikit-image==0.13.1
    scikit-learn==0.19.1
    scipy==1.0.0
    six==1.11.0
    software-center-aptd-plugins==0.0.0
    tornado==3.1.1
    ubuntu-drivers-common==0.0.0
    ufw==0.34-rc-0ubuntu2
    unattended-upgrades==0.1
    unity-scope-audacious==0.1
    unity-scope-calculator==0.1
    unity-scope-chromiumbookmarks==0.1
    unity-scope-clementine==0.1
    unity-scope-colourlovers==0.1
    unity-scope-devhelp==0.1
    unity-scope-firefoxbookmarks==0.1
    unity-scope-gdrive==0.7
    unity-scope-gmusicbrowser==0.1
    unity-scope-gourmet==0.1
    unity-scope-guayadeque==0.1
    unity-scope-manpages==0.1
    unity-scope-musique==0.1
    unity-scope-openclipart==0.1
    unity-scope-texdoc==0.1
    unity-scope-tomboy==0.1
    unity-scope-virtualbox==0.1
    unity-scope-yelp==0.1
    unity-scope-zotero==0.1
    urllib3==1.7.1
    usb-creator==0.2.23
    wheel==0.24.0
    xdiagnose==3.6.3build2
    xkit==0.0.0

On my mac (where the code works without crashing), I have numpy 1.13.3 instead of 1.14.0 and I'm using python 3.6.3 instead of python 3.4.3.

**Comment by soupault** [comment]
This is not a bug of `scikit-image` (see https://github.com/scipy/scipy/issues/7493), but I'll keep this issue open as a reminder.

@red-eight FYI, the latest implementation of `hog` (`master` branch) doesn't use `np.gradient` and fixes several bugs, so you should consider using it or wait for the release of `scikit-image=0.14`.

**Comment by reciprocal-space** [comment]
Is this still an issue for anyone else? I tried upgrading to the most stable releases of scipy (1.16.0) and skimage (0.14.2), but still encounter `
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.`

**Comment by hmaarrfk** [comment]
Can you provide a full stacktrace?

**Comment by reciprocal-space** [comment]
@hmaarrfk Sure thing!

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-27504e6480f2> in <module>()
      8     dummy = processIMG(None).imgProcessing(i,'Green')
      9     fd, hog_image1 = hog(dummy, block_norm='L1', orientations=8, pixels_per_cell=(16, 16),
---> 10                     cells_per_block=(1, 1), visualise=True)
     11     fd, hog_image2 = hog(dummy, block_norm='L1-sqrt', orientations=8, pixels_per_cell=(16, 16),
     12                     cells_per_block=(1, 1), visualise=True)

/home/Vision/local/lib/python2.7/site-packages/skimage/feature/_hog.pyc in hog(image, orientations, pixels_per_cell, cells_per_block, block_norm, visualize, visualise, transform_sqrt, feature_vector, multichannel)
    209         g_col = g_col_by_ch[rr, cc, idcs_max]
    210     else:
--> 211         g_row, g_col = _hog_channel_gradient(image)
    212 
    213     """

/home/Vision/local/lib/python2.7/site-packages/skimage/feature/_hog.pyc in _hog_channel_gradient(channel)
     37     g_row[0, :] = 0
     38     g_row[-1, :] = 0
---> 39     g_row[1:-1, :] = channel[2:, :] - channel[:-2, :]
     40     g_col = np.empty(channel.shape, dtype=np.double)
     41     g_col[:, 0] = 0

TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

`
I also have the following packages installed:

`
backports-abc                      0.5
backports.functools-lru-cache      1.5
backports.shutil-get-terminal-size 1.0.0
bleach                             3.0.2
Click                              7.0
cloudpickle                        0.6.1
configparser                       3.5.0
cycler                             0.10.0
dask                               1.0.0
decorator                          4.3.0
defusedxml                         0.5.0
distributed                        1.25.2
entrypoints                        0.2.3
enum34                             1.1.6
functools32                        3.2.3.post2
futures                            3.2.0
HeapDict                           1.0.0
ipaddress                          1.0.22
ipykernel                          4.10.0
ipython                            5.8.0
ipython-genutils                   0.2.0
ipywidgets                         7.4.2
Jinja2                             2.10
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.2.4
jupyter-console                    5.2.0
jupyter-core                       4.4.0
kiwisolver                         1.0.1
mahotas                            1.4.5
MarkupSafe                         1.1.0
matplotlib                         2.2.3
mistune                            0.8.4
msgpack                            0.6.0
nbconvert                          5.4.0
nbformat                           4.4.0
networkx                           2.2
notebook                           5.7.4
numpy                              1.16.0
opencv-python                      3.4.5.20
pandas                             0.23.4
pandocfilters                      1.4.2
pathlib2                           2.3.3
pexpect                            4.6.0
pickleshare                        0.7.5
Pillow                             5.4.1
pip                                19.0.1
prometheus-client                  0.5.0
prompt-toolkit                     1.0.15
psutil                             5.4.8
ptyprocess                         0.6.0
Pygments                           2.3.1
pyparsing                          2.3.0
python-dateutil                    2.7.5
pytz                               2018.9
PyWavelets                         1.0.1
PyYAML                             3.13
pyzmq                              17.1.2
qtconsole                          4.4.3
scandir                            1.9.0
scikit-image                       0.14.2
scikit-learn                       0.20.2
scipy                              1.2.0
Send2Trash                         1.5.0
setuptools                         40.6.3
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.12.0
sklearn                            0.0
sortedcontainers                   2.1.0
subprocess32                       3.5.3
tblib                              1.3.2
terminado                          0.8.1
testpath                           0.4.2
toolz                              0.9.0
tornado                            5.1.1
traitlets                          4.3.2
wcwidth                            0.1.7
webencodings                       0.5.1
wheel                              0.32.3
widgetsnbextension                 3.4.2
zict                               0.1.3
`
**running v1.2.0 of scipy no 1.16.0

**Comment by hmaarrfk** [comment]
Could you please open a new issue and provide a small self contained example that recreates the issue?

An easy fix might be to not use bool type. I don't think it is well supported due to peculiarities such as t his one.

`.astype(np.uint8)` should help you get going.

**Comment by hmaarrfk** [comment]
right, so if you open an issue, maybe we can add a better error message about boolean types not being supported for that specific function.
