### ISSUE TITLE
scikit-image installation problem Windows

### ISSUE THREAD

**Issue by florianvoigtlaender** [scikit-image/scikit-image#2948]
I tried to install scikit-image with pip 
`pip install scikit-image`

My Python version:
```
python -V
Python 2.7.14
```

My pip version is the following:
```
pip -V
pip 9.0.1 from c:\python27\lib\site-packages (python 2.7)
```

FAILED to install scikit-image ....

Output of pip install scikit-image: 
-file-
[log.txt](https://github.com/scikit-image/scikit-image/files/1658253/log.txt)

**Comment by soupault** [comment]
If you don't have VS installed and properly configured on your Windows machine, you should consider using pre-built wheels of `scikit-image` instead - https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image .

**Comment by florianvoigtlaender** [comment]
Thank you very much!
