### ISSUE TITLE
What is this warning:   warnings.warn("ome-xml: not an ome-tiff master file")

### ISSUE THREAD

**Issue by catubc** [scikit-image/scikit-image#2950]
Hi I'm converting many single-frame .tif files and concatenating them together. One of the warnings is this:   

warnings.warn("ome-xml: not an ome-tiff master file")

I assume it's nothing significant?
Thanks,
catubc

**Comment by stefanv** [comment]
Please provide the code you executed as well as an image.

Not to be annoying, but you managed to cut out the following request from the issue template while filing:

```
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)
```

**Comment by soupault** [comment]
Closing this issue as stale. Feel free to reopen if new info is available.
