### ISSUE TITLE
Error while trying to install scikit-image on Windows 10. Visual Studio 2015 Community.

### ISSUE THREAD

**Issue by SarthakJShetty** [scikit-image/scikit-image#2951]
I already updated Visual Studio and installed Visual C++ on the system, which took about 5 hours, installing and configuring the system. I tried to install scikit-image using `pip install scikit-image`, but it shows the same error. I tried changing the environment variables to include the files mentioned, but no changes to the error being displayed.

I'm using Visual Studio 2015, Community Version. I have already installed Windows 10 SDK and even Visual C++, on a Windows 10 machine. 

`python setup.py develop`

> C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\dist.py:355: UserWarning: Normalizing '0.14dev' to '0.14.dev0'
  normalized_version,
Partial import of skimage during the build process.
running develop
running build_scripts
running egg_info
running build_src
build_src
building extension "skimage._shared.geometry" sources
building extension "skimage._shared.transform" sources
building extension "skimage._shared.interpolation" sources
building extension "skimage.draw._draw" sources
building extension "skimage.feature.corner_cy" sources
building extension "skimage.feature.censure_cy" sources
building extension "skimage.feature.orb_cy" sources
building extension "skimage.feature.brief_cy" sources
building extension "skimage.feature._texture" sources
building extension "skimage.feature._hessian_det_appx" sources
building extension "skimage.feature._hoghistogram" sources
building extension "skimage.feature._haar" sources
building extension "skimage.restoration._unwrap_1d" sources
building extension "skimage.restoration._unwrap_2d" sources
building extension "skimage.restoration._unwrap_3d" sources
building extension "skimage.restoration._denoise_cy" sources
building extension "skimage.restoration._nl_means_denoising" sources
building extension "skimage.filters._ctmf" sources
building extension "skimage.filters.rank.core_cy" sources
building extension "skimage.filters.rank.generic_cy" sources
building extension "skimage.filters.rank.percentile_cy" sources
building extension "skimage.filters.rank.bilateral_cy" sources
building extension "skimage.future.graph._ncut_cy" sources
building extension "skimage.graph._spath" sources
building extension "skimage.graph._mcp" sources
building extension "skimage.graph.heap" sources
building extension "skimage.io._plugins._colormixer" sources
building extension "skimage.io._plugins._histograms" sources
building extension "skimage.measure._ccomp" sources
building extension "skimage.measure._find_contours_cy" sources
building extension "skimage.measure._moments_cy" sources
building extension "skimage.measure._marching_cubes_classic_cy" sources
building extension "skimage.measure._marching_cubes_lewiner_cy" sources
building extension "skimage.measure._pnpoly" sources
building extension "skimage.morphology._watershed" sources
building extension "skimage.morphology._skeletonize_cy" sources
building extension "skimage.morphology._convex_hull" sources
building extension "skimage.morphology._greyreconstruct" sources
building extension "skimage.morphology._skeletonize_3d_cy" sources
building extension "skimage.transform._hough_transform" sources
building extension "skimage.transform._warps_cy" sources
building extension "skimage.transform._radon_transform" sources
building extension "skimage.transform._seam_carving" sources
building extension "skimage.segmentation._felzenszwalb_cy" sources
building extension "skimage.segmentation._quickshift_cy" sources
building extension "skimage.segmentation._slic" sources
building extension "skimage.external.tifffile._tifffile" sources
building data_files sources
build_src: building npy-pkg config files
writing scikit_image.egg-info\PKG-INFO
writing entry points to scikit_image.egg-info\entry_points.txt
writing top-level names to scikit_image.egg-info\top_level.txt
writing dependency_links to scikit_image.egg-info\dependency_links.txt
writing requirements to scikit_image.egg-info\requires.txt
reading manifest file 'scikit_image.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'doc\build'
no previously-included directories found matching 'doc\gh-pages'
writing manifest file 'scikit_image.egg-info\SOURCES.txt'
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
customize MSVCCompiler using build_ext
building 'skimage.feature.brief_cy' extension
compiling C sources
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\include" -I"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\include" -I"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\include" -I"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\include" -I"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\include" -I"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\include" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /Tcskimage\feature\brief_cy.c /Fobuild\temp.win-amd64-3.5\Release\skimage\feature\brief_cy.obj
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\libs" /LIBPATH:"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\PCbuild\amd64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /EXPORT:PyInit_brief_cy build\temp.win-amd64-3.5\Release\skimage\feature\brief_cy.obj /OUT:skimage\feature\brief_cy.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\skimage\feature\brief_cy.cp35-win_amd64.lib
fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 246)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
  link!objf::ObjectCode::FCreateFromBytesW()+0xaab
  link!objf::ObjectCode::FCreateFromBytesW()+0xaab

> build\temp.win-amd64-3.5\Release\skimage\feature\brief_cy.obj : fatal error LNK1000: Internal error during IMAGE::Pass1

>Version 14.00.23026.0

  >ExceptionCode            = C0000005
  ExceptionFlags           = 00000000
  ExceptionAddress         = 6BADA2EB (6BAD0000) "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\msobj140.dll"
  NumberParameters         = 00000002
  ExceptionInformation[ 0] = 00000000
  ExceptionInformation[ 1] = 000D55E8

> CONTEXT:
  Eax    = 008FE1C4  Esp    = 008FE194
  Ebx    = 00000000  Ebp    = 008FE1A0
  Ecx    = 05AA05A8  Esi    = 000D55E8
  Edx    = 6BAD143C  Edi    = 05AA05A8
  Eip    = 6BADA2EB  EFlags = 00010246
  SegCs  = 00000023  SegDs  = 0000002B
  SegSs  = 0000002B  SegEs  = 0000002B
  SegFs  = 00000053  SegGs  = 0000002B
  Dr0    = 00000000  Dr3    = 00000000
  Dr1    = 00000000  Dr6    = 00000000
  Dr2    = 00000000  Dr7    = 00000000
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\libs" /LIBPATH:"C:\Users\Sarthak J Shetty\AppData\Local\Programs\Python\Python35\PCbuild\amd64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /EXPORT:PyInit_brief_cy build\temp.win-amd64-3.5\Release\skimage\feature\brief_cy.obj /OUT:skimage\feature\brief_cy.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\skimage\feature\brief_cy.cp35-win_amd64.lib" failed with exit status 100

**Comment by stefanv** [comment]
Binary windows installs are available from:

1. conda
2. Chris Gohlke
3. appveyor builds

**Comment by SarthakJShetty** [comment]
Hi! I tried all the methods. I installed conda and tried to scikit -image, it successfully installs with no hitch, but when I run ‘python my-program.py’ I get the error saying that there’s no module called skimage available. I also downloaded the wheels from Chris Gohlke’s site, but the wheels don’t appear to be working on my platform; that’s the message that I get at least. Will update with screenshots as soon as possible.

**Comment by SarthakJShetty** [comment]
An update: 
I downloaded all the skimage wheels from Chris Gholke's website, and tried installing each of them. One of them finally worked and am now able ti use the library. Thanks a lot for the help! I'll be closing this issue. Cheers.
