### ISSUE TITLE
rank.otsu slow on large images

### ISSUE THREAD

**Issue by chiffa** [scikit-image/scikit-image#2952]
## Description
I am currently performing analyses of relatively large images (2000x2000 px) and attempting a local Otsu thresholding on them. As a part of thresholding, I am running the `rank.otsu` function from `scikit-image` on one of the color channels in the image. 

While this approach worked fine for small images (512x512), for larger images `rank.otsu` is taking around 90-120 seconds. Is that an expected speed or is there a chance this is due to a bug/OS issue? 

The issue is currently present on Python 2.7.13; scikits-image 0.13.1; all installed through Anaconda Python and running on a Windows 10 - 1709 machine.

**Comment by jni** [comment]
Hi @chiffa,

If you could provide us with a sample image and code to benchmark, it would help us to troubleshoot this.

In the meantime, something to consider is that filters.rank are supposed to be very fast **for uint8 images** but slow for float images. That's because for uint8 they use a rolling histogram, which is not possible with floats. Having said that, I am not very familiar with the rank filters code, and it could be that Otsu doesn't use the rolling histogram at all.

Finally, if you can consider another method, I have a fast implementation of Sauvola thresholding here:
https://github.com/jni/skan/blob/master/skan/vendored/thresholding.py

However you will need to change your Python version to 3.6 to use it.

**Comment by chiffa** [comment]
It is a uint8 image with a uint8 selem - that's why I am a bit surprised. I will try to post the excerpt of failing code and a sample image for it shortly - it's buried pretty deep in my pipeline.

I was going to upgrade to python 3.x eventually anyway - 2.7 is a legacy requirement for that project.

**Comment by stefanv** [comment]
Can you give `skimage.filters.otsu` a try and see how that performs?

The rank filters are designed to be much faster, so this surprises me.  As Juan says, some benchmark images and code will go a long way to helping us debug the issue.

**Comment by chiffa** [comment]
You can find the minimal bug example and a (pickled) image triggering the issue here: https://gist.github.com/chiffa/2b967a79205a06995d91d38dc559a1c7

**Comment by chiffa** [comment]
@stefanv - we need a local Otsu. I assume you are talking about http://scikit-image.org/docs/dev/api/skimage.filters.html?highlight=filters%20otsu#threshold-otsu, which is a global one and is not really useful for us.

**Comment by stefanv** [comment]
That makes sense, thanks for clarifying.

**Comment by chiffa** [comment]
Would you need any additional info to reproduce and debug the issue?

**Comment by stefanv** [comment]
@chiffa I am unable to load your pickle on my machine (Pickle files are not very portable).  Can you export the test image to a `.npy` file with `np.save` and post it again?  Thanks.

**Comment by chiffa** [comment]
Here is the new image file: https://www.dropbox.com/sh/sxmydv9l289e1o4/AABVgO0oPUj8EHE22RiyIpi0a?dl=0

And proper import code Gist:
https://gist.github.com/chiffa/58163205d1cede5efd8d74f7754498a3

**Comment by stefanv** [comment]
```
base image (2044, 2048) uint8
mask (101, 101) uint8
local otsu time: 14.30 seconds
```

**Comment by stefanv** [comment]
Autolevel: 4.6s
Mean bilateral: 4.8s
Median: 3.97s

**Comment by emmanuelle** [comment]
I got similar results as @stefanv, so x10 faster than the 90-120 s you mentioned. Was it the same script?

**Comment by stefanv** [comment]
The 3 to 4 time slowdown is probably due to the extra complexity of calculating Otsu, but we should investigate.

**Comment by stefanv** [comment]
(I did run it through `cython -a` to verify that all types are correctly annotated; and they are.)

**Comment by rfezzani** [comment]
With `skimage` v0.19dev, timing gives
```python
In [12]: base_image = np.load('debug_image.npy')                                                         

In [13]: selem2 = disk(50)                                                                               

In [14]: %timeit rank.otsu(base_image, selem2)                                                           
4.96 s ± 6.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Not bad :wink:. Closing.
