### ISSUE TITLE
Installing scikit-image gives could not find a version that satisfies requirement

### ISSUE THREAD

**Issue by ManaliTapre** [scikit-image/scikit-image#2953]
I have been trying to install scikit-image using pip install scikit-image. However I keep getting an error  
Could not fetch URL https://pypi.python.org/simple/scikit-image/: There was a
problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certifi
cate verify failed (_ssl.c:777) - skipping
Could not find a version that satisfies the requirement scikit-image (from ver
sions: )
No matching distribution found for scikit-image

I get the same error while installing scikit-learn. I am working on python36.

**Comment by soupault** [comment]
Seems to me like a network/proxy issue.

Try to download and install pre-built binaries from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image (for Windows) or https://pypi.python.org/pypi/scikit-image (for Linux/Mac OS), and let us know the result.
