### ISSUE TITLE
Refactor setup.py to use setup_requires

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2958]
Newer versions of setuptools support `setup_requires`, which we can use to ensure that NumPy is installed:

http://setuptools.readthedocs.io/en/latest/setuptools.html

**Comment by stefanv** [comment]
Should rather use https://www.python.org/dev/peps/pep-0518/; see https://github.com/scikit-image/scikit-image/pull/3020

**Comment by grlee77** [comment]
I am closing this since we are now using `pyproject.toml` which will pull in an appropriate NumPy
