### ISSUE TITLE
Region filling not completely filling all holes in a binary inverted image

### ISSUE THREAD

**Issue by mayorcoded** [scikit-image/scikit-image#2969]
Hi guys, I am quite new to image processing and to scikit-image as well. I performed a binary invert on an image and some of the regions in the image remain unfilled. Here is an image of the regions that remain uunfilled.

![screen shot 2018-02-18 at 4 02 49 am](https://user-images.githubusercontent.com/17001801/36347798-d422b87e-1460-11e8-90ce-a659d6fa5281.png)

please how can I remove the black holes from the image. Thanks

**Comment by soupault** [comment]
You can start with something as simple as https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.ndimage.binary_closing.html#scipy.ndimage.binary_closing .

Closing this as not an issue. For general questions in the future, please, consider using StackOverflow (with `scikit-image` tag).
