### ISSUE TITLE
Extend feature.structure_tensor to 3D

### ISSUE THREAD

**Issue by scott-trinkle** [scikit-image/scikit-image#2972]
## Description
There should be an equivalent function to `feature.structure_tensor()` and the associated `feature.structure_tensor_eigvals()` extended to three dimensions. 

The tensor structure is described [here](https://en.wikipedia.org/wiki/Structure_tensor#The_3D_structure_tensor), and would just involve calculating a third partial derivative and including 3 more cross terms.

**Comment by laurentlouis** [comment]
Gents, Just ended up on this thread. I was wondering whether there had been any progress on this topic in the last year :-)
Best, Laurent.

**Comment by scott-trinkle** [comment]
Hi Laurent, 

I fell behind on working it into the scikit framework, but I have my own implementation - happy to share if you'd like.

**Comment by stefanv** [comment]
Gentle encouragement to please bring those changes over!

**Comment by Skielex** [comment]
@scott-trinkle could your implementation please? :)
Would like to use it until this hopefully gets into scikit-image.

**Comment by grlee77** [comment]
It looks like this has stalled. Should we remove from the 0.16 milestone?

**Comment by grlee77** [comment]
closed by #5002
