### ISSUE TITLE
Reduce the size of the skimage wheel by removing docs

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#2978]

**Comment by stefanv** [comment]
See also https://github.com/scikit-image/scikit-image/issues/1991#issuecomment-370572780

**Comment by hmaarrfk** [comment]
@stefanv, can you elaborate on this, it doesn't seem like `docs` are included in the wheel
![image](https://user-images.githubusercontent.com/90008/40748179-689b87b2-6414-11e8-8d0e-150b401f15df.png)

The tests are included though, which include demo datasets which can be large.

**Comment by hsiaoyi0504** [comment]
It seems to me that this can be close. Docs has been already excluded from wheel.
https://github.com/scikit-image/scikit-image/blob/0459233aa88ff199ab9c9312b8b5abf31291875c/setup.py#L207

**Comment by soupault** [comment]
Indeed. Conda package does not contain docs as well - https://anaconda.org/anaconda/scikit-image/files .
