### ISSUE TITLE
SLIC parameters from variables results in error

### ISSUE THREAD

**Issue by exsstas** [scikit-image/scikit-image#2980]
## Description
I'm trying to feed parameters for a slic superpixel from variables and get an error. The very same parameters as direct values works well. Why is that?

- Windows 10 - 64 bit
- Python 3.5.1
- scikit-image 0.13.1

## Way to reproduce
_any image_ 

```
from skimage.segmentation import slic
from skimage.util import img_as_float
image = cv2.imread("test.png", 1)
n_segments = 50
compactness = 20.0
sigma = 3
max_iter = 10
min_size_factor = 0.5
max_size_factor = 3.0
slic_zero = 0
segments = slic(img_as_float(image), n_segments, compactness, sigma, max_iter, min_size_factor, max_size_factor, slic_zero, spacing=None)
```
will  result in 
> TypeError: slic() got multiple values for argument 'spacing'

without "spacing=None" argument result is:

>   File "C:\Anaconda\envs\TFinTD\lib\site-packages\skimage\segmentation\slic_superpixels.py", line 134, in slic
    sigma /= spacing.astype(np.double)
AttributeError: 'float' object has no attribute 'astype'

However, if instead of variables I'll write absolutely the same arguments values in the function call, everything works just fine.
`segments = slic(img_as_float(image), n_segments=50, compactness=20.0, sigma=3, max_iter=10, min_size_factor=0.5, max_size_factor=3.0, slic_zero=0, spacing=None)`

**Comment by jni** [comment]
Hi @exsstas, this is not a scikit-image bug, but rather a fundamental feature of the Python language, called *positional* vs *keyword* arguments, that you are not using correctly.

When you don't use the argument names `(..., arg_name=var_name, ...)`, the arguments need to be given *in the order in which the appear in the `slic` signature*. The function call doesn't make use of the names of variables outside of the function call. So in your first call, you should do:

```python
segments = slic(img_as_float(image), n_segments=n_segments, compactness=compactness, ...)
```

Or you should reorder the arguments to match the order in the `slic` [function documentation](http://scikit-image.org/docs/dev/api/skimage.segmentation.html#skimage.segmentation.slic).

See this StackOverflow answer for an explanation of positional vs keyword arguments:

https://stackoverflow.com/a/9450673

Hope this helps!
