### ISSUE TITLE
AttributeError When Importing * from filters

### ISSUE THREAD

**Issue by htejeda-stanford** [scikit-image/scikit-image#2984]
When importing * from skimage.filters there is an attribute error stating that the module has no attribute 'denoise_tv_chambolle'.

```
Traceback (most recent call last):
  File "my_python_script.py", line 21, in <module>
    from skimage.filters import *
AttributeError: 'module' object has no attribute 'denoise_tv_chambolle'
```
(I am using **Python 2.7.13** and **skimage 0.13.1**)

Upon looking into the site-packages/skimage/filters/__init__.py file there are 3 functions which are not imported but are included in __all__ (denoise_tv_chambolle, denoise_bilateral, denoise_tv_bregman).

Two possible solutions:

1) Comment out the three lines inside of the __all__ with these functions (or simply delete them).
2) Add the following import:
```python
from ..restoration import (denoise_tv_chambolle, denoise_bilateral,
                           denoise_tv_bregman)
```

**Comment by stefanv** [comment]
I do not see this problem with the latest source version.  As an aside, note that it is considered bad practice to use `import *`, better to do `from skimage.filters import (a, b, c)`.
