### ISSUE TITLE
Adding target number of points to skimage.measure.approximate_polygon

### ISSUE THREAD

**Issue by ad-si** [scikit-image/scikit-image#2988]
I was thinking about implementing a mode for `approximate_polygon` where you specify the target number of points instead of the maximum tolerance.

E.g. `approximate_polygon(coords, target_count=10)` would then mean "simplify polygon until it has 10 coordinate points"

Shall I open a PR for this?

**Comment by soupault** [comment]
Yes, feel free to submit a PR.
Closing as a duplicate of https://github.com/scikit-image/scikit-image/issues/2212 .

**Comment by stefanv** [comment]
That sounds like a good feature to have, thanks @ad-si
