### ISSUE TITLE
convert 2D array of contour to Binary Labeled Image

### ISSUE THREAD

**Issue by SayanSeth** [scikit-image/scikit-image#2991]
How to convert 2D array of contour to Binary Labeled Image in scikit-image? I have found contour using active contour method.

```
snake = active_contour(I3,
                   init, alpha=.75, beta=0.01, gamma=0.01, w_edge=.5,
                   max_iterations=1000)
```
snake is a 2D-array. Now I have to apply regionprops for that I new binary labeled image.How to convert it?

The label should be such that the area inside the contour will be label 1 and outside area will be 0.
Its Opposite of find_contours function.

**Comment by jni** [comment]
Hi @SayanSeth! I think scipy.ndimage.binary_fill_holes will work here. Can you give it a try? I'll close this issue for now but please reopen if that doesn't solve your problem.
