### ISSUE TITLE
slic method  fail for initial  segmentation 

### ISSUE THREAD

**Issue by ElJAZRY** [scikit-image/scikit-image#2994]
## Description
I'm using segmentation.slic method to obtain initial segmentation for a graph-cut algorithm, but the result that I get is just grid of squares of different regions, I've applied it for Dicom medical images, but the data type is ' int64', with any other image the method work fine with me. 

```python
seg = segmentation.slic(Image, n_segments=50, compactness=10.0,
enforce_connectivity=True, sigma=3)

from skimage import color

io.imshow(color.label2rgb(seg, Image));
```
![Dicom image](https://github.com/ElJAZRY/BsC/blob/master/images/image.png)
 
![segmentation](https://github.com/ElJAZRY/BsC/blob/master/images/index.png)

- [ '0.13.0' ] scikit-image version

**Comment by jni** [comment]
@ElJAZRY What is happening is that your value of compactness is too high. You should do a parameter scan. I recommend using a log series to search for the right setting. (compactness = 0.001, 0.01, 0.1, 1, ...)

**Comment by ElJAZRY** [comment]
still give the same result, with any other image it works fine, I trayed to change the image data type nothing change also.

**Comment by jni** [comment]
Ah! scikit-image data types strike again! I think what’s happening is that your image intensity is being converted to a tiny range, so you would need a compactness = 2**(-32) to see a difference! Or even -64. You should manually rescale the image by a factor that makes sense (leaving the resulting float image in the range [0, 1])

**Comment by jni** [comment]
Sorry I meant to add this link to the docs: http://scikit-image.org/docs/dev/user_guide/data_types.html

**Comment by ElJAZRY** [comment]
ok, I used  exposure.rescale_intensity 
and compactness = 0.1 
it give  better result , thank you
