### ISSUE TITLE
colorconv.separate_stains should use np.log10() instead of np.log()?

### ISSUE THREAD

**Issue by markemus** [scikit-image/scikit-image#2995]
This method is used for stain deconvolution. It implements the method defined in this paper: http://www.math-info.univ-paris5.fr/~lomn/Data/2017/Color/Quantification_of_histochemical_staining.pdf
which is the original paper on color deconvolution. The algorithm is defined on page 6 of the paper:

ODC = -log10(IC/I0,C) = A*cC . 

Shouldn't line 1130: 
stains = np.dot(np.reshape(-np.log(rgb), (-1, 3)), conv_matrix)

really be:
stains = np.dot(np.reshape(-np.log10(rgb), (-1, 3)), conv_matrix)
?

Right now it uses ln instead of log10.

**Comment by jni** [comment]
I'm not sure this matters very much. One is a constant factor from the other, and neither appears to be guaranteed to be in the range of values recommended for skimage datatypes. Do you know whether absolute values make sense in this scale?

CC @cespenel @spotter

**Comment by markemus** [comment]
You seem to be right that it doesn't change the distribution, although I'm not sure why that's the case. However absolute values do matter. OD = A*C, where C is the absorption constant for a stain and A is the amount of stain present. As long as you determine your C with ln() in mind I guess it would be okay, but it doesn't follow the standard convention.

I'm pretty sure it's a bug and someone mistook np.log() for np.log10().

**Comment by emmanuelle** [comment]
@markemus you're probably right, can you please submit a PR about this ?

The discussion also shows that this function is very domain specific, maybe a bit too much for scikit-image.

**Comment by hmaarrfk** [comment]
Here is the a link to what seems like the paper: 

https://pdfs.semanticscholar.org/e0a0/dc42714dd8add295cb43c15110d86af95cf9.pdf

**Comment by bioimage-analysis** [comment]
@markemus, I’m not a specialist but If I understood well the matter, I believe you are right. In optic the Transmission (IC/I0,C) is always a percentage (or a decimal <1) and the Transmission is the anti-log of the negative of OD. So I believe the function should be log10 not ln. (cespenel)

**Comment by markemus** [comment]
There is a related quantity called optical depth: https://en.wikipedia.org/wiki/Optical_depth which uses ln instead of log10. But I think for this operation it should be using log10- that seems to be the standard.

**Comment by Pathai-Nle** [comment]
It looks like the log10 was reverted to natural log again after this commit - https://github.com/scikit-image/scikit-image/commit/23829977f23c957dbff24757069dbdc4d929248f. Was there a reason behind this? Could we use the log10 again for reasons described above?

**Comment by stefanv** [comment]
Yes, this was discussed extensively [here](https://github.com/scikit-image/scikit-image/pull/4725#issuecomment-629899916). Please let us know, after reading, if you are still concerned.
