### ISSUE TITLE
Version Bump to 0.13.2 on pypi?

### ISSUE THREAD

**Issue by duhaime** [scikit-image/scikit-image#2998]
## Description
There have been many commits to the project since 0.13.1, and some of the newly introduced features are present in the docs but not in the latest version on pypi (e.g. the `anti_aliasing` argument in `skimage.transform.resize` [docs](http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.resize)). Could you potentially consider packaging a release for pypi?

## Way to reproduce

Try to measure image similarity with the following script on v0.13.1 - the `anti_aliasing` keyword will be unrecognized:
```
import sys
from skimage.measure import compare_ssim
from skimage.transform import resize
from scipy.misc import imsave
from scipy.ndimage import imread

# get the images
img_a = imread(sys.argv[1])
img_b = imread(sys.argv[2])
resized_a = resize(img_a, (2**10, 2**10), anti_aliasing=True)
resized_b = resize(img_b, (2**10, 2**10), anti_aliasing=True)

# score: {-1:1} measure of the structural similarity between the images
score, diff = compare_ssim(resized_a, resized_b, full=True)
print(score)
```

scikit-image version: 0.13.1

**Comment by jni** [comment]
Yes! Sorry! It's been on our to-do for some time. I'm going to aim to get it out in the next week or so.

**Comment by duhaime** [comment]
In case anyone lands here in the meantime, it took me a minute to realize you need to run the following to install scikit-image locally:

```
python setup.py build_ext -i
python setup.py install --user
```

**Comment by jni** [comment]
A shorter version, documented [here](http://scikit-image.org/docs/dev/install.html) (amid a lot of mess, admittedly) is:

```
pip install --user --upgrade --editable .
```
(Notice the `.` at the end, meaning "current directory", when you are in the directory containing `setup.py`, as above. Otherwise you can replace `.` with the correct directory, like `/path/to/scikit-image`.)

**Comment by soupault** [comment]
We're working really hard to deliver 0.14 asap :). Stay tuned!
