### ISSUE TITLE
Use astropy instead of pyfits to read FITS images

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3002]
pyfits is not currently installable on 3.5, and it looks like AstroPy is more actively maintained.

**Comment by hmaarrfk** [comment]
@stefanv, I only found 2 references to `pyfits`
  *  [fits_plugin](https://github.com/scikit-image/scikit-image/blame/ef78faf04435717a1b5797bc1a02c73d9b5e8e7f/skimage/io/_plugins/fits_plugin.py#L6)
  *  [test_fits](https://github.com/scikit-image/scikit-image/blob/ef78faf04435717a1b5797bc1a02c73d9b5e8e7f/skimage/io/tests/test_fits.py#L11)

I searched for `import pyfits` and `from pyfits`.

Do you want somebody to completely rip out all mentions of `pyfits` and get rid of the logic that allows fallback?

**Comment by alexandrejaguar** [comment]
Closed; solved in #3930.

**Comment by stefanv** [comment]
Hold on, #3930 isn't merged yet!

**Comment by alexandrejaguar** [comment]
@stefanv sorry!

**Comment by hmaarrfk** [comment]
github's magic should close this automatically.
