### ISSUE TITLE
Regarding using skimage functions to replace scipy.misc.imread

### ISSUE THREAD

**Issue by wenouyang** [scikit-image/scikit-image#3005]
## Description
[Please provide a general introduction to the issue/proposal.]
I have an existing code that use scipy.misc to read image
```
from scipy import misc
im = misc.imread(self.file_image, True)
```

I would like to know are there any functionalities in `skimage`, that can replace the `scipy.misc` and get the same output?
[If reporting a bug, attach the entire traceback from Python.]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by jni** [comment]
Hi @wenouyang! As noted in the [SciPy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html), you should use `imageio.imread`. See https://imageio.github.io/ for usage information.

**Comment by wenouyang** [comment]
Hi Jni, would you like to elaborate why skimage would not be recommended?  Thanks
