### ISSUE TITLE
Provide a nodata parameter to measure.find_contours

### ISSUE THREAD

**Issue by dt99jay** [scikit-image/scikit-image#3006]
## Provide a nodata parameter to measure.find_contours
At the moment, contours found by `skimage.measure.find_contours` which intersect the array edge are left open and others are closed ([docs](http://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.find_contours)).

Where the data of interest is masked but the array can't be cropped to this data (e.g. the area of interest is rotated or an unusual shape) and surrounding 'pixels' are set to NaN, contours are closed where they meet the NaNs. There's an [illustration in this question](https://gis.stackexchange.com/questions/278516/how-could-i-avoid-extracting-incorrectly-closed-contours-from-a-raster-with-angl) on Stack Exchange.

Could a `nodata` parameter (e.g. `nodata=np.NaN` or `nodata=-9999`) be provided to `measure.find_contours` which treats the `nodata` value in the same way as the edge of the array, returning an open contour when it leaves the data of interest and meets a `nodata` pixel?

**Comment by acarapetis** [comment]
My experience is not that the contours are closed where they meet the `NaN`s, but they are messed up entirely there - a `NaN` value causes the linear interpolation function _get_fraction to return `NaN`, resulting in the contours having `NaN` coordinates. I'm working on a patch.
