### ISSUE TITLE
Feature request: histogram matching

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3012]
See, e.g. https://stackoverflow.com/a/33047048/214686

**Comment by solutusimmensus** [comment]
I'd like to work on this feature, but am not sure as to what the unit tests should look like. 
Can I just import some images from skimage.data (both rgb and gray-scale) and check whether the histograms of source and output are sufficiently close?

**Comment by jni** [comment]
@solutusimmensus yes that's what I would try I think!
