### ISSUE TITLE
Magic dimensionality guessing in gray2rgb

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3014]
## Description
Playing around with `label2rgb`, I noticed that we do a bit of magic in `gray2rgb` in order to make it a no-op when an RGB image is passed through:

https://github.com/scikit-image/scikit-image/blob/38b83c436be684baf6ee26bfa09c5e41edb516fb/skimage/color/colorconv.py#L835-L840

We have since sworn off this kind of magic, but I don't know how to fix this without breaking a million users' code. (Ok maybe I'm a little optimistic about how many people use our code. =P)

**Comment by soupault** [comment]
Too much magic for a simple function :). Can't we just deprecate this behaviour?

**Comment by hmaarrfk** [comment]
Maybe we can have an `ndcolor` module and get rid of the color module all together?

I have alot of the ndcolor written up somewhere, but I couldn't think of a good way of deprecating the magic behaviour.

**Comment by rfezzani** [comment]
This was addressed in #4440 ;-) Closing!

**Comment by jni** [comment]
@rfezzani i feel like we missed adding a TODO item to make sure that this is properly fixed before 0.19... 😬
