### ISSUE TITLE
No documentation for filters.threshold_local

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3017]
## Description
In resurrecting some old code, I found that my use of `threshold_adaptive` triggered a warning, "threshold_adaptive is deprecated, use threshold_local instead". Fine, I thought. Let me check the documentation for threshold_local to make sure my function call is still valid with the new function's API.

To my surprise, there is no documentation for threshold_local!

http://scikit-image.org/docs/dev/api/skimage.filters.html

**Comment by jni** [comment]
Ah, the cause: it wasn't added to the module `__all__`:

https://github.com/scikit-image/scikit-image/blob/aff33569589fcc972084c0c930d85d8471a70bea/skimage/filters/thresholding.py#L12-L23

**Comment by stefanv** [comment]
But it is in `skimage.filters.__init__` --- why isn't that enough?

**Comment by jni** [comment]
You're the sphinx expert @stefanv! =) But I should have said "a possible cause" rather than "the cause", above.
