### ISSUE TITLE
register_translation with sliced array

### ISSUE THREAD

**Issue by jeffgelb-sg** [scikit-image/scikit-image#3021]
## Description
I am working with the register_translation method to align a stack of images, and I'd like the ability to select a centered ROI for alignment (since sometimes the edges don't contain helpful data). Currently, I'm slicing a section of the 2d image data from the middle of the original array and copying that into a new array for the register_translation engine to process, but if I start the selection above pixel [y,x] (where y,x != 0 and is >25% the FOV) I get the following error:

```
Traceback (most recent call last):
  File "/Users/jgelb/Desktop/registerImages/test.py", line 18, in <module>
    shifts, error, phasediff = feature.register_translation(sourceImage, targetImage, upsample_factor=10)
  File "/anaconda2/lib/python2.7/site-packages/skimage/feature/register_translation.py", line 174, in register_translation
    src_freq = np.fft.fftn(src_image)
  File "/anaconda2/lib/python2.7/site-packages/numpy/fft/fftpack.py", line 736, in fftn
    return _raw_fftnd(a, s, axes, fft, norm)
  File "/anaconda2/lib/python2.7/site-packages/numpy/fft/fftpack.py", line 638, in _raw_fftnd
    a = function(a, n=s[ii], axis=axes[ii], norm=norm)
  File "/anaconda2/lib/python2.7/site-packages/numpy/fft/fftpack.py", line 192, in fft
    output = _raw_fft(a, n, axis, fftpack.cffti, fftpack.cfftf, _fft_cache)
  File "/anaconda2/lib/python2.7/site-packages/numpy/fft/fftpack.py", line 56, in _raw_fft
    % n)
ValueError: Invalid number of FFT data points (0) specified.
```

If it makes a difference, the images are 32-bit, 2048x2048. Generally it seems to fail when starting above pixel 512 in x and/or y, though smaller datasets seem to fail at correspondingly smaller start values. I'm a bit new still to Python and very new to the scikit-image library, though already I am a big fan (of both!). Am I doing something wrong here? Please see an example script below. 

## Way to reproduce
**Code example**
(myimage.tif is of shape 100x2048x2048, containing 32-bit floating point numbers)
```
from skimage import feature
from skimage import io

# get set up
filename = "myimage.tif"
pctImg = .3

# read the data file and store as a 3D array
datastack = io.imread(filename)

# set the window size range based on the pctImg value, centered on the original data window
xStart = int(datastack.shape[2]*(1-pctImg)/2)
xEnd = int(datastack.shape[2]*(1+pctImg)/2)
yStart = int(datastack.shape[1]*(1-pctImg)/2)
yEnd = int(datastack.shape[1]*(1+pctImg)/2)

# slice out the relevant portions of the array
sourceImage = datastack[0][yStart:yEnd][xStart:xEnd]
targetImage = datastack[1][yStart:yEnd][xStart:xEnd]

# do the registration
shifts, error, phasediff = feature.register_translation(sourceImage, targetImage, upsample_factor=10)

# report the shift
print "Found offset: " + str(shifts)
```

**Operating system and version:** MacOS 10.13.4
**Python version:** 2.7.14
**scikit-image version:** 0.13.1

**Comment by jni** [comment]
Ah! Took me a while. Here's the kicker:

```
>>> sourceImage.shape
(0, 2048)
```

The problem is in the indexing. Note that:

```
sourceImage = datastack[0][yStart:yEnd][xStart:xEnd]
```
is equivalent to:

```
sourceImage = ((( datastack[0] )[yStart:yEnd] )[xStart:xEnd] )
```
So you are grabbing the 0th element of `datastack` (this is a (2048, 2048)-shaped array), then you are grabbing the slice `yStart:yEnd` of that (this is a (615, 2048)-shaped array), and then the `xStart:xEnd` slice of that (this is empty, because `xStart > 615`). The correct NumPy indexing incantation is:

```
datastack[0, yStart:yEnd, xStart:xEnd]
```

> I'm a bit new still to Python and very new to the scikit-image library, though already I am a big fan (of both!)

Welcome to our community! A couple of starter tips:

- Use Python 3. Python 2 support is slowly being phased out across the scientific Python community. Let us know if you need help installing a Python 3 version of Anaconda, but it shouldn't be too onerous! If you **have** to use Python 2 because you are using some legacy code, try to write code that works in both, e.g.:

`print x` --> `from __future__ import print_function; [...] print(x)`

- By convention, Python uses `underscore_names` rather than `camelCaseNames`. Your peers will appreciate code consistent with the rest of the community! PEP8 is the official style guide:
https://www.python.org/dev/peps/pep-0008/

We are here to help!

**Comment by jeffgelb-sg** [comment]
Thank you so much for the helpful advice! And so quickly!! It is working beautifully on my end now. I also went ahead and implemented the underscore case (I think my C background might be showing... so this should help me to "tuck that back in"), and will look next at "future-proofing" the legacy statements. Yes, unfortunately there are some other modules we are using elsewhere that still rely on python2... we are working to bring those up to v3, but it's a slow process haha. I really like the idea of flexible code though, so I think it is a very good suggestion to buckle that up now so we don't have a headache later. 

Anyway, thanks again for the help! And glad to have this now logged online, since my Google searches turned up very little on that particular error. Not that I expect this to be a common use case, but still: it never hurts to add one more entry to the infinite library of the internet. :-)

Cheers!

**Comment by jni** [comment]
Yes, online logging of info/public note-taking is fantastic. You never know who it's going to help!

In that vein, here's a nice guide for writing Python 2/3 compatible code:
http://python-future.org/compatible_idioms.html

six is a very very common library for achieving this:
https://pythonhosted.org/six/
