### ISSUE TITLE
 Underlying algorithms in Scikit-Image module skimage.transform.PeicewiseAffineTransform.estimate

### ISSUE THREAD

**Issue by smyaknti** [scikit-image/scikit-image#3024]
## Description
I am currently working on a project that requires in-depth understanding of one of the modules available in scikit-image. In that regard I require a source(preferably a paper) for the algorithms being used in skimage.transform.PeicewiseAffineTransform.estimate in this file below.
[_geometric.py](https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/_geometric.py)

**Comment by soupault** [comment]
>I require a source

`Require` is, kind of, a strong word here.

For theory see, for example, http://www2.imm.dtu.dk/~aam/main/node13.html#SECTION04331000000000000000 .

For further questions, not directly related to the development of the library, consider using StackOverflow (and `scikit-image` tag).
