### ISSUE TITLE
Skeleton for voxel images faild.

### ISSUE THREAD

**Issue by DMST1990** [scikit-image/scikit-image#3027]
## Description
The skeleton extraction for a voxel based representation failed.

I created a simple 3D- Case of blobs.
If i use skeletonize_3d the resulting skeleton zero.

## Way to reproduce
Version: scikit-image 0.13-1

Example python program:

```
from skimage.morphology import skeletonize, skeletonize_3d
from skimage.data import binary_blobs
import numpy as np

#---- This one worked
# Use 2D example created by the documentation
data = binary_blobs(200, blob_size_fraction=.2, volume_fraction=.35, seed=1)
data = np.array(data)
skeleton = skeletonize(data)
skeleton3d = skeletonize_3d(data)

#---- This one doesn´t work
# Generate 3D-Data structure
data_3D = [data, data, data]
data_3D = np.array(data_3D, dtype='bool')

# Skeleton 3d is empty for this array
skeleton3d = skeletonize_3d(data_3D)
print(np.where(skeleton3d==True))
```

**Comment by soupault** [comment]
What exactly doesn't work for you?
Here are the resutls on my PC:
```
In [36]: fig, axes = plt.subplots(nrows=2, ncols=3)

In [37]: axes[0, 1].imshow(skeleton3d_A)
Out[37]: <matplotlib.image.AxesImage at 0x7f9eec1eac88>

In [38]: for i, plane in enumerate(skeleton3d_B):
    ...:     axes[1, i].imshow(plane)
    ...:     

In [39]: plt.show()
```

![figure_1](https://user-images.githubusercontent.com/1315589/39205258-d44e0a94-4802-11e8-9511-617156f25a9a.png)

**Comment by DMST1990** [comment]
Sorry for that, np.where() didn`t work as i would expect.

I changed the code into

```
 np.where(np.where(skeleton3d!=False))
```
and it worked.

**Comment by soupault** [comment]
>Shouldn`t there be a surface skeleton as well?
Not for skeletonization. You might take a look at thinning for this (http://scikit-image.org/docs/dev/auto_examples/edges/plot_skeleton.html, http://scikit-image.org/docs/dev/api/skimage.morphology.html#thin).
