### ISSUE TITLE
Image Inversion for signed types

### ISSUE THREAD

**Issue by ThomasWalter** [scikit-image/scikit-image#3028]
## Description
Image inversion for signed types does not yield the expected result. 

`In [7]: img = np.array([[0, 1, -125], [1, 0, 125]], dtype=np.int8)`

`In [8]: invert(img)`
`Out[8]: `
`array([[127, 126,  -4],
       [126, 127,   2]], dtype=int8)`

I guess, that image inversion should do different things depending on the data type. If the data type is signed, inversion should more or less multiply with (-1) (with the problem that the range is not symmetric). 

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by ThomasWalter** [comment]
So, in principle, it would be: 

- for unsigned integer: `img_inv = dtype_limits(image, clip_negative=False)[1] - image`
- for float: `img_inv = -image`
- for signed integer types: `img_inv = -1-image`

**Comment by soupault** [comment]
This one is tricky. I think implementing different behaviours for different dtypes is reasonable, but it makes the function so counter-intuitive...

>for float: img_inv = -image

I'm afraid it's more appropriate to distinguish [-1:1] and [0:1] representations of float ndarrays, performing `i = -x` for the former and `i = 1-x` for the latter.

**Comment by ThomasWalter** [comment]
True ... it is a bit ugly. 

> I'm afraid it's more appropriate to distinguish [-1:1] and [0:1] representations of float ndarrays, performing i = -x for the former and i = 1-x for the latter.

You are certainly right ... but how can I know the allowed range? 

I mean, I cannot infer the allowed range from the actual range. An image could live in the space of signed float images, yet - by coincidence - have only positive values.

**Comment by soupault** [comment]
>but how can I know the allowed range?

Unfortunately, this is currently not possible (see https://github.com/scikit-image/scikit-image/issues/2605).

I don't know... Maybe we should disable this function for float ndarrays for now?

**Comment by ThomasWalter** [comment]
Or we have an option for the inversion of float ndarrays.

**Comment by soupault** [comment]
Closed via #3030.
