### ISSUE TITLE
Weird matplotlib infinite loop Travis failure

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3034]
I'm not sure yet whether this is reproducible, but on Py2.7 with minimal requirements (MPL 1.3.1), we are getting a maximum recursion depth error:

https://travis-ci.org/scikit-image/scikit-image/jobs/372237528#L5768

It doesn't appear to be random OR due to a new Matplotlib release, so I really don't understand why it's popping up now. 

Environment variables:  
WITH_PYAMG=1  
MINIMUM_REQUIREMENTS=1  
WITH_QT=1

The failing example is `doc/examples/color_exposure/plot_ihc_color_separation.py`, line 72, `axis.imshow(zdh)`.

**Comment by soupault** [comment]
Some comments on this matter - https://github.com/scikit-image/scikit-image/pull/2977#issuecomment-370417245 .

**Comment by jni** [comment]
Thanks @soupault for that link! Though it does not help to resolve it. It appears to be repeatable, right? Very strange since it is an old version but a new problem. Perhaps it has to do with the Qt version? Or how Travis handles Qt might have changed?

**Comment by soupault** [comment]
>it does not help to resolve it

It doesn't, but, at least, we are all aligned now :).
I guess there is a room for investigation: try different backends, downgrade matplotlib, etc.

**Comment by jni** [comment]
Yes. Does Travis have a docker container one can download to experiment with? Because doing this over Travis builds in pushes is *painful*.

**Comment by jni** [comment]
Thanks @matthew-brett!!!!

**Comment by hmaarrfk** [comment]
@jni Honestly, I don't think we should hold the examples to the same "As compatible with old versions as possible". That makes it VERY difficult for people to actually write and contribute examples.

Examples should be simple and readable by people with basic knowledge of python + image processing.

My solution has been not to run the examples in communion with `MINIMUM_REQUIREMENTS` which I think is fair. Otherwise, you will likely have ALOT of code written to support multiple versions which makes things less readable....

Also matplotlib 1.4.0 is the first version to [claim to support](https://github.com/matplotlib/matplotlib/releases/tag/v1.4.0) python 3

**Comment by tacaswell** [comment]
It looks like this is related to https://github.com/scikit-image/scikit-image/pull/2977/files#diff-2718b1161d3808601068cca87c2e8ff9L73 , that you are sharing axes across figures, that the tests are running with a non-interactive backend, and all of the plots have aspect = 1

That you are in different figures causes https://github.com/matplotlib/matplotlib/blob/cfb6ac64578c1d9e042a55c1c62894ba0d9bf331/lib/matplotlib/axes.py#L2551-L2554 to be hit, that your are non-interactive mean `draw_idle` is the same as `draw` which causes the recursion, 

Given that the axes are different aspect ratios-on screen, I think they are trying (and failing) to match all of the constraints (aspect ratio 1, the same data limits, screen aspect ratios).  I am not sure of the top of my head what the right fix is. 

I am a _bit_ surprised that this works interactively, but there is a lot of subtle code around managing both shared axes and aspect ratio so _something_ is breaking out of the over-constrained system (this is what box-forced used to be doing for you).

attn @efiring

**Comment by efiring** [comment]
The failure is with an ancient matplotlib version.  I think you should drastically raise the minimum version of mpl you require.  I don't see how anyone is going to benefit from the combination of up-to-date scikit-image and ancient matplotlib.

**Comment by hmaarrfk** [comment]
We bumbed numpy to 2.0.0 and pillow to 4.3. This issue is no longer relevant.

**Comment by hmaarrfk** [comment]
Pillow needed to be bumped for jpeg.
