### ISSUE TITLE
`segmentation\tests\test_random_walker.py` tests fail

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#3036]
## Description

The are several test failures in AppVeyor, but despite this the builds are marked green.
For more info, see https://ci.appveyor.com/project/soupault/scikit-image/build/job/di8uxa5s295x4mo3#L3314

**Comment by emmanuelle** [comment]
Actually some of these tests also fail in Travis, but I can't reproduce the problem on my machine :-/

**Comment by soupault** [comment]
Closed via #3063
