### ISSUE TITLE
Link to docs whenever `preserve_range` is used

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3047]
Link to http://scikit-image.org/docs/dev/user_guide/data_types.html wherever preserve_range is used.

Suggestion made https://github.com/scikit-image/scikit-image/pull/2772#issuecomment-338517238 by @jni.

**Comment by Jathrone** [comment]
Please review Linking preserve_range parameter calls to docs #3109.

**Comment by soupault** [comment]
Closed via #3109
