### ISSUE TITLE
compare_psnr() got an unexpected keyword argument 'data_range'

### ISSUE THREAD

**Issue by fantasyzl** [scikit-image/scikit-image#3048]
## Description
[Please provide a general introduction to the issue/proposal.]

[If reporting a bug, attach the entire traceback from Python.]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

```
def batch_PSNR(img, imclean,1.0):
    Img = img.data.cpu().numpy().astype(np.float32)
    Iclean = imclean.data.cpu().numpy().astype(np.float32)
    PSNR = 0
    for i in range(Img.shape[0]):
        PSNR += compare_psnr(Iclean[i,:,:,:], Img[i,:,:,:], data_range=data_range)
    return (PSNR/Img.shape[0])
```

**Comment by JDWarner** [comment]
Did you define `data_range`?  The example code does not, and would be the simplest explanation.

**Comment by soupault** [comment]
In addition to the above, `data_range` argument is valid only since `scikit-image` 0.13.0.

I'm going to close this issue, but feel free to reopen if the problem has not been solved.
