### ISSUE TITLE
Images of type float must be between -1 and 1?

### ISSUE THREAD

**Issue by micklexqg** [scikit-image/scikit-image#3051]
I convert lab image to rgb using lab2rgb in skimage. and the input datatype is float32, L is in range (0,100),
A is (-128,127), B is (-128,127).
but came across error: ValueError: Images of type float must be between -1 and 1.

 is the input datatype for color.lab2rgb in skimage uint8? or  are  there other problems...

**Comment by jni** [comment]
Hi @micklexqg!

Are you sure the error is coming from `lab2rgb`?

```python
In [56]: from skimage import color

In [57]: color.lab2rgb?

In [58]: color.lab2rgb([[[10., 10., 10.]]])
Out[58]: array([[[ 0.17178949,  0.08558054,  0.04875568]]])

In [59]: color.lab2rgb([[[10., -10., -10.]]])
Out[59]: array([[[ 0.      ,  0.124338,  0.159546]]])

In [60]: color.lab2rgb([[[-10., -10., -10.]]])
Out[60]: array([[[ 0.,  0.,  0.]]])
```

Could you come up with a small example that reproduces your error?

In many situations in skimage, such as converting between data types, float values are indeed restricted to [-1, 1], and [0, 1] more commonly. However this is not (or should not be) the case for lab2rgb or many other functions. See this documentation for more details on data types and data ranges:

http://scikit-image.org/docs/dev/user_guide/data_types.html

**Comment by micklexqg** [comment]
@jni ,thanks for your hint. and I find out the reason. the input datatype need to be float64 (mine is float32).
just as the following:
![image](https://user-images.githubusercontent.com/13776012/39564750-113b75c2-4ee8-11e8-8a7e-d19c40d8021e.png)

**Comment by micklexqg** [comment]
@jni , you are welcome. And I think it is better to add annotation of input data type for a method.  Given a simple demo is the best just like that in matlab...

**Comment by HRLTY** [comment]
Thanks for figuring out this! I was confused by the range and this bug too.
