### ISSUE TITLE
Possible bug in skimage.transform.rotate: UserWarning: is a low contrast image

### ISSUE THREAD

**Issue by aarora8** [scikit-image/scikit-image#3053]
## Description
[Please provide a general introduction to the issue/proposal.]
I am performing following functions (read image, pad image, crop image, rotate image.  I am either using sk-image or basing python functions like concatenate.  If I don't rotate the image then there is no warning. If I rotate the image, I am getting following warning  

I tried using default rotate options and following option:
region_initial.rotate(degrees(rotation_angle_in_rad), resample = Image.BICUBIC)
/anaconda3/lib/python3.6/site-packages/skimage/util/dtype.py:122: UserWarning: Possible precision loss when converting from int64 to float64
  .format(dtypeobj_in, dtypeobj_out))

When I try to view the image, using imshow image values seemed to be in the range of (1e-17). I shared a link for this image. I guess image values got normalized somewhere but I am not able to find the location.

If I try to save the rotated image, I get completely black image.

> im = img_as_uint(image)
> imsave(image_path, im, plugin='imageio')

I tried removing img_as_uint, using default imsave, using (freeimage, imagio) as plugin option
 
[If reporting a bug, attach the entire traceback from Python.]

> /anaconda3/lib/python3.6/site-packages/skimage/util/dtype.py:122: UserWarning: Possible precision loss when converting from int64 to float64
>   .format(dtypeobj_in, dtypeobj_out))
> /anaconda3/lib/python3.6/site-packages/skimage/util/dtype.py:122: UserWarning: Possible precision loss when converting from float64 to uint16
>   .format(dtypeobj_in, dtypeobj_out))
> /anaconda3/lib/python3.6/site-packages/skimage/io/_io.py:132: UserWarning: /Users/ashisharora/google_Drive/madcat_arabic/lines/AAW_ARB_20061105.0017-S1_1_LDC0372_00z1.png is a low contrast image
>   warn('%s is a low contrast image' % fname)

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example

```
def pad_image(image):
    offset = int(args.padding // 2)
    max_val = max(map(max, image))
    height = image.shape[0]
    im_pad = np.concatenate((max_val * np.ones((height, offset),
                                        dtype=int), image), axis=1)
    im_pad1 = np.concatenate((im_pad, max_val * np.ones((height, offset),
                                                 dtype=int)), axis=1)

    width = im_pad1.shape[1]

    im_pad2 = np.concatenate((max_val * np.ones((offset, width),
                                         dtype=int), im_pad1), axis=0)
    im_pad3 = np.concatenate((im_pad2, max_val * np.ones((offset, width),
                                                  dtype=int)), axis=0)
    return im_pad3

```
```
im_wo_pad = imread(image_file_name)
im = pad_image(im_wo_pad)
region_initial = im[281:480, 2509:4766]
rotation_angle_in_rad = -0.00708
img2 = rotate(region_initial, degrees(rotation_angle_in_rad))
region_final = img2[15:298, 7:2263]
imshow(region_final)
```

- [ ] Relevant images (if any)
https://ibb.co/cSfzb7
- [ ] Operating system and version
10.11.6 OS X El capitan
- [ ] Python version
3.6.4 (/anaconda3/bin/python3.6)
- [ ] scikit-image version (run `skimage.__version__`)
0.13.1

**Comment by jni** [comment]
Hi @aarora8,

Please see #3009 and http://scikit-image.org/docs/dev/user_guide/data_types.html

What is happening here is that your input image has dtype int32/uint32 (you ensure this by setting `dtype=int` in your padding function), and it is getting rescaled by the conversion to float inside `rotate`. As I mention in #3009, I think this is not the correct policy, and we plan to fix it (somehow).

In the meantime, you can probably set `dtype=image.dtype` in your `pad` function, and things should work as expected.

I would also point you to the `np.pad` function, which does what you need, probably more efficiently, too. And `max_val * np.ones` can be replaced by `np.full`. =)

I'm going to close this issue because it is covered by #3009. We will work on a fix there. Please feel free to ask further questions here if my response isn't clear!

**Comment by maliho0803** [comment]
io.imsave('{}/{}'.format(save_folder1, image_name.replace('.jpg', '_posmap.jpg')), np.clip((uv_position_map)/max(image_h, image_w), -1, 1)) # only for show

UserWarning: ../../dataset/300W_LP_Posmap_img//HELEN_2330042311_1_10_posmap.jpg is a low contrast image
  warn('%s is a low contrast image' % fname)
the same code work well in linux, but get errors in Mac
