### ISSUE TITLE
Benchmark code location

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3059]
I would like to use this thread to start a discussion on where an appropriate place for benchmarking code would be.

Performance seems to be of interest to at least a few people using scikit-image (See Issue and pull requests tagged with type: performance).

I've been trying to include my code in commit messages, or in the pull requests, but I feel like that would get lost. Having a directory for benchmarking code is useful because:

- Future developers can quickly check that a certain routine was tested for speed.
- Meaningful discussions can be had by comparing other contributor's benchmarks.
- If a decision was made due to performance, it should be documented somewhere permenant.
- When a certain algorithm is no longer the best choice, other benchmarked algorithms can quickly replace it.
- This would also allow scikit-image to establish best practices for benchmarking.
   - I've noticed differences between ipython, and jupyter for example. Maybe we want to target one and not the other?

Would a directory such a `benchmark` next to `tests` be an acceptable solution?

**Comment by JDWarner** [comment]
A long standing goal has been setting up Airspeed Velocity for scikit-image.  It would absolutely be reasonable to start collecting benchmark code in a way compatible with airspeed velocity; might even provide the last necessary nudge to make it happen ;)

Our CI builds can take a while as it stands, so unfortunately I'm not sure running a benchmark suite on Travis will be feasible (but would love to be proved wrong).

**Comment by hmaarrfk** [comment]
@lagru thanks or your input. 

Regarding what SciPy has done, I feel like having things in a top level benchmarks directory makes things messy. People seem to have recreated the namespace with the filenames.

This can be solved by changing setup.py to exclude the benchmarks directory

```python
        packages=setuptools.find_packages(exclude=['doc', 'benchmarks']),
```

Don't know about CI's. I'm pretty new to them. They seem pretty limited for true benchmarking.

**Comment by lagru** [comment]
> This can be solved by changing setup.py to exclude the benchmarks directory -- @hmaarrfk 

I meant that not in regard to setuptools but to the capabilities of asv. The documentation of asv's configuration file hints that benchmarks are expected to live in a [single directory](https://asv.readthedocs.io/en/latest/asv.conf.json.html#benchmark-dir). But I may be wrong. ;)

**Comment by hmaarrfk** [comment]
@lagru dam. OK. Maybe we can glob, but that is a detail.

**Comment by hmaarrfk** [comment]
It seems a decision was made to have it in a single directory primarily due to `asv` limitations.

Closing this issue.
