### ISSUE TITLE
Migrate from GitHub Services

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#3061]
https://developer.github.com/changes/2018-04-25-github-services-deprecation/

![image](https://user-images.githubusercontent.com/1315589/39713500-9ddd52e4-522f-11e8-99a8-3807715fa931.png)

**Comment by jni** [comment]
Well, that was a pain in the ass. 

- GitHub is deprecating services in October and removing them at the end of January. That's a pretty aggressive timeline but ok. Let's get this done.
- go to Travis-ci.com, and you are told that you can't migrate to their new GitHub App until ~starting in Q2 2018, *unless you email them*. I've done this.
- go to gitter.im and they want read and write access to *all* (public and private) repos that I have access to. As far as I can tell there is no way to change these settings, so I reckon screw gitter.

**Comment by soupault** [comment]
@jni Should we revisit this issue?

**Comment by stefanv** [comment]
I deleted the Gitter (since we're trying Zulip anyway) and Travis-CI services (since we have the App).  Hopefully everything continues to run smoothly!
