### ISSUE TITLE
Cannot install skimage 0.14dev on Windows

### ISSUE THREAD

**Issue by luciaL** [scikit-image/scikit-image#3068]
## Description
[Please provide a general introduction to the issue/proposal.]

[If reporting a bug, attach the entire traceback from Python.]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [x] Operating system and version
- [ ] Python version
- [x] scikit-image version (run `skimage.__version__`)

**Comment by luciaL** [comment]
I have tried every method of installing in the docs.But I still got a version of 0.13.1 on ubuntu and windows. When i tried the build  way on my windows using python setup.py  build  ,I got  error. Failed with exit status 127.

**Comment by sciunto** [comment]
You can run
```
pip install git+https://github.com/scikit-image/scikit-image.git
```
Without further details on what you tried so far, it is difficult to guide you.

**Comment by luciaL** [comment]
I tried but got a the same error as before.
error is here:[https://github.com/luciaL/test/blob/master/TIM%E6%88%AA%E5%9B%BE20180511104903.png](url)

**Comment by luciaL** [comment]
I tried but got the same error as before.
Error is here:[https://github.com/luciaL/test/blob/master/TIM%E6%88%AA%E5%9B%BE20180511104903.png](url)

**Comment by luciaL** [comment]
https://github.com/luciaL/test/blob/master/TIM%E6%88%AA%E5%9B%BE20180511104903.png

**Comment by luciaL** [comment]
I tried but i got the same error as before.Error is here:
https://github.com/luciaL/test/blob/master/TIM%E6%88%AA%E5%9B%BE20180511104903.png
