### ISSUE TITLE
strange result of lab2rgb

### ISSUE THREAD

**Issue by micklexqg** [scikit-image/scikit-image#3078]
i run e=lab2rgb(f), where f is a ndarray and its datatype is float64, the value scope is in range (-255,255).
 the result is strange and as follow:
![image](https://user-images.githubusercontent.com/13776012/40032201-ad60d62c-5825-11e8-9716-186831e7a2dd.png)
is there anything wrong?

**Comment by soupault** [comment]
@micklexqg could you provide `f` array (or the corresponding image) and a code snippet so that we can reproduce the behaviour you are facing?

**Comment by micklexqg** [comment]
@soupault , sorry for replying late. I have sovled the problem. but i came across another strange problem,
for a given pil image, 
 b = color.rgb2lab(img)   (work)
 a = color.rgb2gray(img)  (not work)
  is there some notes and  differences between color.rgb2lab and color.rgb2gray?

**Comment by stefanv** [comment]
Can you clarify the ranges of the values in `f`?

Also see https://github.com/scikit-image/scikit-image/issues/1185

**Comment by micklexqg** [comment]
@stefanv , very sorry. it has been a long time and I have forgot. maybe it is float32 type.

**Comment by sciunto** [comment]
I'm closing for now as we are missing information to properly solve the potential issue. Please, reopen if the problem persists.
