### ISSUE TITLE
`test_wrap_around` sometimes fails on python 3.4

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3079]
## Description
In developing #3072, I found that `test_wrap_around.py` **sometimes** fail on python3.4.
I've been trying to [reproduce this](https://travis-ci.org/hmaarrfk/scikit-image/jobs/379259181#L5365), but it is generally difficult.

```bash
tests/test_unwrap.py::test_wrap_around[2-0] FAILED                                     [ 83%]
tests/test_unwrap.py::test_wrap_around[2-1] PASSED                                   [ 84%]
tests/test_unwrap.py::test_wrap_around[3-0] PASSED                                   [ 86%]
tests/test_unwrap.py::test_wrap_around[3-1] PASSED                                   [ 88%]
tests/test_unwrap.py::test_wrap_around[3-2] PASSED 
```

## Way to reproduce
The easiest way is probably to use [my branch](https://github.com/hmaarrfk/scikit-image/tree/bugfix_pass_test) since it passes many other tests than the one currently on scikit-image.
Specifically you should use `bugfix_pass_test_dont_skip_test_wrap_around` which actually runs the test instead of skipping it in `python 3.4`
```bash
git clone git@github.com:hmaarrfk/scikit-image.git scikit-image-34
cd scikit-image-34
git checkout bugfix_pass_test_dont_skip_test_wrap_around
pipenv --python 3.4
pipenv install --skip-lock -r 'requirements/test.txt'
pipenv install --skip-lock -r 'requirements/build.txt'
pipenv install --skip-lock -r 'requirements/docs.txt'
pipenv run python setup develop.py
pipenv run pytest -v
```
To specifically run the test that fails
```bash
pipenv run pytest -v skimage/restoration/tests/test_unwrap.py
```
and just press "up arrow"+"enter" a few times until the test fails.

**Comment by hmaarrfk** [comment]
And hopefully one of [these travis builds](https://travis-ci.org/hmaarrfk/scikit-image/builds/379410538) will be able to reproduce the issue:

**Comment by jni** [comment]
This is super weird. If you can make it fail on my machine, I recommend you run pytest with `--pdb`. This will drop you into a python debugger prompt when the test fails, and you can nose around to see if anything seems off. 

OR, come to think of it, we can just close this, since we are dropping 3.4 support after 0.14! :joy: Let me know what you'd prefer to do!

**Comment by hmaarrfk** [comment]
Just close it. I'm too lazy to make a virtual env.

**Comment by grlee77** [comment]
This turned up again today, but on a PyPy 3.7 build in the feedstock: https://github.com/conda-forge/scikit-image-feedstock/pull/91#issuecomment-1153888057
