### ISSUE TITLE
uint8 -> int16 does not have precision loss

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3080]
https://github.com/scikit-image/scikit-image/blob/05ac822219304d00426fb4e3b423c90c7b916fbf/skimage/_shared/testing.py#L130

Am I missing something or is there a bug in the above?

```python
def color_check(plugin, fmt='png'):
    """Check roundtrip behavior for color images.
    All major input types should be handled as ubytes and read
    back correctly.
    """
    img = img_as_ubyte(data.chelsea())
    # [...]
    with expected_warnings(['precision loss']):
        img4 = img_as_int(img)
```

  - `img` is a `uint8`
  - `img_as_int` says that it converts to `int16`
  - `uint8 -> int16` has no precision loss in my books.

**Comment by soupault** [comment]
Doesn't seem necessary, indeed.
