### ISSUE TITLE
How to: automatically close dialogs in Qt testing suite

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3081]
## Description
Qt tests use some old way to quit the file dialogs.

I had to skip the tests to finally get them to pass on Travis.
https://github.com/hmaarrfk/scikit-image/blob/my_version/skimage/viewer/tests/test_utils.py#L24

I don't know Qt enough to fix this.
Currently I simply skip the test.

If I enable the tests, they pass, I just have to close the box with my mouse.

**Comment by jni** [comment]
I don't know Qt very well at all either, but there must be some "modern" way to programmatically close windows?

**Comment by hmaarrfk** [comment]
I tried. but the Qt documentation is written for C, and some things just don't seem to work the same way in Python.

**Comment by jni** [comment]
Arrrgh. I know this problem. =(

**Comment by grlee77** [comment]
I could not reproduce this issue with our current CI configuration and Qt versions used there (see #5313)
