### ISSUE TITLE
`view_as_windows` incorrectly assumes that a contiguous array is needed

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3088]
See https://github.com/numpy/numpy/pull/10771#issuecomment-390881027

Mea culpa.

**Comment by eric-wieser** [comment]
`view_as_blocks` too

**Comment by stefanv** [comment]
Turns out my "mea culpa" is only applicable to my reviewing at the time, but if anything that may be worse.

**Comment by sciunto** [comment]
@stefanv Is the fix as simple as removing the condition?

**Comment by eric-wieser** [comment]
Yes
