### ISSUE TITLE
Fused type required for floating point Cython operations

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3111]
Since we're now (soon ;) letting through `float32` arrays in `img_as_float`, we need to add a fused dtype to all Cython code that consumes doubles to also accept single precision floats.

**Comment by grlee77** [comment]
Agreed, although some cases may need to use double precision internally for accuracy.  An example is the change from float32 to float64 when using the fast integral-image representation for non-local means.  A good image demonstrating the problem with float32 is here:  https://github.com/scikit-image/scikit-image/pull/2878#issuecomment-346344773

**Comment by jni** [comment]
@grlee77 for those functions we should be using `img_as_float64` instead of `img_as_float`.

**Comment by rfezzani** [comment]
A big :+1: for this!
The `np_floats` fused type is already defined in `skimage._shared.fused_numerics`. Generalizing its use in Cython operations may in fact save memory use and computation time.
It also prevent some hidden data casting from `float32` to `double`, like for example in `_slic_cython` where the input image is silently converted to `double`...

**Comment by rfezzani** [comment]
Oups, I just realized that this issue is more than one year old!!! :laughing:

**Comment by stefanv** [comment]
I think we still need someone to do a proper review of all changes required; but since this issue is so vague I'm going to close it.

**Comment by rfezzani** [comment]
I started this review yesterday when I noticed the silent cast to `double` in `_slic_cython`. That's how I found this discussion :-)
I will start by reporting the `_slic_cython` issue and refer to this one. I will try to investigate more on this.
