### ISSUE TITLE
Is tools/build_versions.py still necessary?

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3134]
## Description
the script tools/build_version.py prints the version of a few core dependencies such as cython, networkx, numpy and scipy. Is this still necessary?

We have the line `pip list` running in travis.
Appveyor doesn't seem to include that line. Though I suspect it should. It doesn't even use the build_versions.py to my knowledge

**Comment by stefanv** [comment]
This has been discussed, and the conclusion was that it should be kept because it prints only a useful subset of all packages.  It was refactored (by @hmaarrfk) in the mean time to use `requirements_parser`.

**Comment by hmaarrfk** [comment]
PR for reference #3211
