### ISSUE TITLE
Python versioneer?

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3144]
I wanted to ask if you all thought it was applicable to use [python-versioneer](https://github.com/warner/python-versioneer) to simplify the management of our versions.

It will automatically increment our dev versions the version according to the latest release tag as well as "how many commits we are ahead of it".

Furthermore, we get the skip the "increment the version number in the source".

This suggestion came from @jakirkham who uses it for his own projects and suggest that I use it for some of mine.

If you are all for it, I will try to create a PR to implement this feature.

**Comment by JDWarner** [comment]
At least at first glance, this seems to be a good solution.  :+1: 

We used to have a `_version.py`, but that one got created at setup and ended up causing significant problems related to permissions in some cases.  It appears this hooks in and creates/maintains the file itself, so it would be shipped with the package and permissions issues would be avoided.

**Comment by hmaarrfk** [comment]
As a note, once the package is built and released, the `_version.py` file becomes simply a json string and is very "human readable". It definitely doesn't contain the mess that is included in the repository.

**Comment by hmaarrfk** [comment]
@jni 
I wanted to continue the discussion here, seperate from the notes on the implementation.

When building the sdist, versioneer hooks into the build process with
```
cmdclass=versioneer.get_cmdclass(), 
```

When you issue the command `python setup.py sdist` it will manage the file `_version.py` and make it something like:

```python
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-02T11:57:19-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d1dd0218d60d09a4708ba021f441d7a08aa7b2d",
 "version": "0.12.0+1745.g9d1dd021"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
```

When I downloaded the tag from git using their gui:
```python
import json

version_json = '''
{
 "date": null,
 "dirty": false,
 "error": "no suitable tags",
 "full-revisionid": "e16376d09c138869b6936dfe887411a6c4aee1c5",
 "version": "0+unknown"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
```

From their README.md:
> _version.py also contains $Revision$ markers, and the installation process marks _version.py to have this marker rewritten with a tag name during the git archive command. As a result, generated tarballs will contain enough information to get the proper version.

So I think I'm missing something.

**Comment by jni** [comment]
I see. Well it looks damn cool, I'd heard the name but never investigated. Looking forward to when it works! =P

**Comment by hmaarrfk** [comment]
Ok, it seems that:
1. It works if you go to the ["realease"](https://github.com/hmaarrfk/scikit-image/releases) page.
2. It won't work if you download the tarball from the repo home page. I think this is a serious drawback. They must have a "fallback" way of doing this.

**Comment by matthew-brett** [comment]
I've used versioneer quite a bit, and it's convenient, but it can be pretty annoying that you can't do anything at all to the source tree, without changing the version.  For example, sometimes it's convenient to put extra licenses, or small build patches into the tree, for doing a release, but this will change the version in a way that's difficult to avoid.

**Comment by matthew-brett** [comment]
I know what you mean, but I can tell you that, in practice, this gets pretty annoying.  For example, for the numpy wheels, we copy a suitable license into the root of the tree when we're building the wheel, which has copyright info for the various libraries it will link against.  These differ for the different platforms (Windows, macOS, manylinux).

**Comment by hmaarrfk** [comment]
Right.... platform specific license files. 

I mean, my solution to that has been to keep one license file (which people do not read anyway) with the following:

> ### Licenses specific to Windows installation
> ### Licenses specfic to Linux installations
> [...]

I find that that probably simplifies the build process too since it is "one less unique thing"

**Comment by hmaarrfk** [comment]
@jni, regarding your concern, I think I most recently addressed it by providing a `fallback_version` that has to be manually updated. It allows for more lazy updating though which I think is a BIG bonus.

I made some noise on the [python-versioneer issue](https://github.com/warner/python-versioneer/issues/140) and sumitted to them a [WIP PR](https://github.com/warner/python-versioneer/pull/183). 

Lets see what they say.

**Comment by matthew-brett** [comment]
Yes, sure, it's usually possible to find workarounds for the various cases, but my experience is that this soon becomes frustrating.

**Comment by jni** [comment]
@hmaarrfk cool, but the bundled version is patched, right?

Let's see what @stefanv has to say given @matthew-brett's comments. My intuition is that we don't have anywhere near as complicated a build process, so we would run into fewer of these edge cases, and it would be useful to get people to automatically tell us *which* master they're on when reporting bugs.

**Comment by hmaarrfk** [comment]
Yeah. I patched things on the vendored version.

Matthew does raise some good points.

I personally want to get to nightly/weekly releases and this will go a long
way to helping that.

**Comment by hmaarrfk** [comment]
Just rounding up the conversation here. In PR #3145, @stefanv expressed that versioneer likely added too much code for too little benefit.

I tend to agree.
Along with 
  - the potential issue of having people download the zip from the main repo page.
  - The automated build issues brought up by @matthew-brett 

I think it is probably safe to keep using the existing system.
