### ISSUE TITLE
skimage.io rotates the image

### ISSUE THREAD

**Issue by fakesimon** [scikit-image/scikit-image#3150]
## Description
Some images are read with the wrong orientation.
For example, I have two images taken with the same phone, and looking at them from the file explorer they both seem ok:

![cattura](https://user-images.githubusercontent.com/19566501/40934509-51199b54-6835-11e8-8d7a-7f7bfddbc4ec.PNG)

but then one is read rotated of 90 degrees (see the code in the example below).

![bug](https://user-images.githubusercontent.com/19566501/40934281-9a3ffbf8-6834-11e8-8459-23c261fc8616.png)

Writing this issue I noticed that even GitHub rotates the first image, but if you try to open it in a new tab, it rotates back. The code is the same, but I don't know if there is a bug in the `io` module or some sort of problem with my image.

## Way to reproduce

**Example**
```
import numpy as np
from skimage import io
import matplotlib as mpl
import matplotlib.pyplot as plt

ok_img = io.imread('images/dataset_unibg/bug/C1P2F1.jpg')
error_img = io.imread('images/dataset_unibg/bug/C1P1F1.jpg')

fig, ax = plt.subplots(1, 2)
ax[0].imshow(ok_img), ax[1].imshow(error_img)
ax[0].set_title('Correct orientation'), ax[1].set_title('Wrong orientation')
plt.show()
```
**Relevant images**
Wrong image:
![c1p1f1](https://user-images.githubusercontent.com/19566501/40934712-f4c81a50-6835-11e8-9ba4-cb0a6f12ca3b.jpg)
Ok image:
![c1p2f1](https://user-images.githubusercontent.com/19566501/40934771-2d39b010-6836-11e8-893e-99f000055686.jpg)

**OS** Windows 10, v. 1803

**Python version**  3.6.5 on Anaconda

**scikit-image version** 0.13.1

**matplotlib version** 2.2.2

**Comment by soupault** [comment]
Could be related to orientation metatag - https://www.impulseadventure.com/photo/exif-orientation.html

**Comment by sciunto** [comment]
I have the same feeling as @soupault 

I had the chance to look at the possibilities to read exif metadata with python. Here are the options that I show in my lecture:

Wth pillow

```from PIL import Image
from PIL.ExifTags import TAGS


img = Image.open(img_path)
info = img._getexif() # returns a dictionnary
for k, v in info.items():
    # TAGS is a dictionnary containing human-readable entries
    nice = TAGS.get(k, k)
    print('%s (%s) = %s' % (nice, k, v))
```

With èxifread

```
import exifread


img = open(img_path, 'rb')

# Return Exif tags
tags = exifread.process_file(img)
print(tags)
```

with pyexiftool

Not available on pip :(

This is basically a wrapper on the excellent [exiftool](https://sno.phy.queensu.ca/~phil/exiftool/) (Windows, Linux, MacOS). A good idea to reuse this code instead of writing yours. It's a unique file that you can copy paste in the source tree of your project for the sake of easiness.

[Documentation](http://smarnach.github.io/pyexiftool/)

```
import exiftool

files = [img_path, img_path]
with exiftool.ExifTool() as et:
    # Single file...
    metadata = et.get_metadata(img_path)
    # Or a batch of files
    metadata = et.get_metadata_batch(files)
    
print(metadata)

```

**Comment by sciunto** [comment]
It does not sound too specific to me. Nevertheless, it's part of #2709 where we want to integrate imread_meta. Then, once tackled, we can add the re-orientation capability.

In the mean time, @fakesimon and others can use one of the libraries I mentioned above to handle the orientation. This should be fairly easy (more than at the scale of scikit-image).

**Comment by hmaarrfk** [comment]
Personally, I think this is better handled either down in `Pillow`, or in `imageio`.

`scikit-image` having their own additional features for reading in images seems problematic.

**Comment by stefanv** [comment]
Reference: http://sylvana.net/jpegcrop/exif_orientation.html

**Comment by JDWarner** [comment]
Agreed with @hmaarrfk - this is something which should be handled by the loading interface.  If either or both will not, consideration would be to see if they could pass the tag info and then we could orient on load with that particular plugin.

These tags are rampant and not new, pretty sure my 2007 DSLR used them, and it's a standard.  Pillow and imageio should be gently nudged toward handling them.

**Comment by jni** [comment]
The problematic image seems to open correctly when I use imageio. @fakesimon Can you try that? Long term we are aiming to defer all our io to `imageio` so that is what you should use by default. If imageio doesn't work for you, please raise an issue there.
