### ISSUE TITLE
Not all imported utility functions are described in the docs

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3156]
https://github.com/scikit-image/scikit-image/blob/1151b511a10ec2568d72b94469afb09040a5ed9d/skimage/__init__.py#L46

Proposed fix:
  1. Only import the utilities functions that we describe.
  2. Describe all utility functions that are actually imported.

To do 1. you would need to specify the functions we import in the line
```python
from .util.dtypes import *
```

To do 2. you would need to look at the file `skimage.util.dtypes` at the line
```python
__all__ = [ ... ]
```
and give a short description of the functions that are imported.

Python lesson: the list [`__all__`](https://docs.python.org/3.6/tutorial/modules.html#importing-from-a-package) describes the functions that are imported when you use `from XXXX import *`

**Comment by soupault** [comment]
In my opinion, we should get rid of `import *`, and import all the necessary functions by name (currently, that should be the full contents of util.dtypes.__all__, I think). The docstring should be updated accordingly.
