### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3165]
Is there any interest in having some kind of centralized nightly builds?

I've been working on it with my branch of the [conda-forge feedstock](https://github.com/hmaarrfk/scikit-image-feedstock)

conda-forge doesn't seem to have a good way to have a nightly branch, so it seems like the best way is to host them on a different channel.

**Comment by hmaarrfk** [comment]
Just a preview of what would be possible:
I have setup a [feedstock](https://github.com/hmaarrfk/scikit-image-feedstock) with a nightly build for `0.15.dev0+` that uploads the conda packages to a [custom channel](https://anaconda.org/mark.harfouche/scikit-image)

It tries to stick to `conda-forge`'s build tools as much as possible.

1. It clones (for now) my repository's master branch.
    - To clone from scikit-image's master, I would need a tag for `0.15.dev0`
2. It adds a patch for [versioneer](https://github.com/hmaarrfk/scikit-image/pull/2). See PR #3145 and Issue #3144
    - It needed me to manually install numpy in the root environment or else we cannot get the version number from the `setup.py` script. <- Custom edit to the CI files.
3. Once it builds things, it uploads them to a private anaconda channel so that it doesnt' compete with the stable builds.

Automated builds:
Appveyor didn't let me setup a cron job. I don't think this is available in the free tier for a regular user. For now, I think just force pushing an amended commit should be OK to trigger the builds "whenever".

Disclaimer:
My nightly branch adds a few other patches for things I think should be merged in upstream. 
Versioneer makes this explicit by letting you know you are installing a `dirty` branch.

**Comment by hmaarrfk** [comment]
@scikit-image/core would you consider please creating a tag for 0.15.x so that versioneer can work off the scikit-image/scikit-image repo as opposed to my own fork?

That would really go a long way toward getting these nightly builds streamlined

**Comment by jni** [comment]
@hmaarrfk what do you mean? A tag that constantly points to HEAD? Or...?

**Comment by hmaarrfk** [comment]
@jni, I think the appropriate tag would be the one when 0.14.x forked off. 

That is https://github.com/scikit-image/scikit-image/commit/be42f61150cc5d16c6618285d908d24f904b949e

`git tag -a be42f61150cc5d16c6618285d908d24f904b949e 0.15.dev0`

**Comment by jni** [comment]
Surely the one *after*, once the version has been bumped? ;)

**Comment by hmaarrfk** [comment]
Good point!

**Comment by hmaarrfk** [comment]
seems like it is this commit
https://github.com/scikit-image/scikit-image/commit/492b1958a14f351464a204f67e83c4d04c1b72cf

```
git tag -a 0.15.dev0 492b1958a14f351464a204f67e83c4d04c1b72cf
git push upstream 0.15.dev0
```

**Comment by jni** [comment]
@hmaarrfk done! Thanks for making it trivial for me. =)

**Comment by hmaarrfk** [comment]
@jni I'm glad that your pushing didn't go through.
I broke the convention in the command I gave you.

```
git tag -a v0.15.dev0 492b1958a14f351464a204f67e83c4d04c1b72cf
git push origin v0.15.dev0
git push upstream v0.15.dev0
```

**Comment by stefanv** [comment]
I don't think a 0.15.dev0 tag is necessary to build nightlies, and in fact I think such a tag is misleading, since it should always point to the latest HEAD on the development (master) branch.  @hmaarrfk can you clarify why this is absolutely necessary?  You'll notice that we don't have this kind of tag from before, and I am inclined to remove the tag that just got pushed.

Note also that if this branch was named `v0.15.dev0` instead, it would have broken the website versioning at http://scikit-image.org — something to watch out for!

**Comment by jni** [comment]
@hmaarrfk it did, see here: https://github.com/scikit-image/scikit-image/releases

Now @stefanv is berating me. =P

**Comment by hmaarrfk** [comment]
Gah, I didn't realize it would have broken the website. Definitely didn't mean to do that.

Regarding always pointing to HEAD. That is a fair interpretation of `.dev0`.

I guess it isn't necessary to build nightlies, but it makes it play better with versioneer. I'm glad to keep the tag only on my local branch as this is all very experimental.

versioneer keeps track of how many commits you are ahead compared to a specific `tag`, for example `.dev0+103` would be 103 commits ahead of the `.dev0` tag.

I could tag nightlies version by day, but that might create a conflict when running from a cron job and somebody accepts a PR between two jobs. Then builds of different arch's may actually have different commits included even though they have the same version number.

**Comment by jni** [comment]
@hmaarrfk I didn't realise either. =)

Can't versioneer be configured to read the version from some file and append a commit hash?

**Comment by hmaarrfk** [comment]
Commit hashes don't increment. The `+NUMBER` will increment provided you have a sane PR/Merge strategy.

**Comment by hmaarrfk** [comment]
```
git push --delete upstream 0.15.dev0
git tag --delete 0.15.dev0
```

**Comment by stefanv** [comment]
Note that you can still use the branch point commit SHA as a stable reference.

**Comment by stefanv** [comment]
I went ahead and removed the tag.  Thanks for being understanding.

**Comment by matthew-brett** [comment]
Just for cross-reference, the scikit-image-wheels repo is building nightlies too:

```
CDN_URL=https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com
pip install -U --pre -f $CDN_URL scikit-image
```

**Comment by hmaarrfk** [comment]
Nice! That is awesome @matthew-brett

**Comment by stefanv** [comment]
@matthew-brett Any way we can add Windows wheels, and provide a DNS entry?  Windows users struggle to install point releases.

**Comment by matthew-brett** [comment]
I don't know how to do the DNS entry for https, but I'm sure it's possible.  Anyone better informed on that out there in the scikit-ether?

For Windows wheels - someone needs to email Appveyor and ask for cron job permissions, for a relevant account.

**Comment by hmaarrfk** [comment]
@stefanv, would you consider a tag with a different prefix such that it doesn't interfere with the website?

I understand you are treating the `dev0` version number differently than the `0.14.0` release for example. For it, it would just make sense to keep things consistent, by having the `.dev0` point to the first time that the version number was incremented, just as it is for the `0.14.0` release no? Or am I missing something regarding how version numbers are kept track of?

**Comment by stefanv** [comment]
@matthew-brett Sorry for the noise; of course I can update the DNS entry.

I will email AppVeyor.

@hmaarrfk I do not understand why you need a tag to keep track of the information you need.  We have `HEAD` which is the latest development version (and the version is defined in `skimage.__version__`).  We then have a maintenance branch, like `v0.14.x`, tracking point releases.  You can use `git` itself to find the ancestor of `v0.14.x` and `master` if you need to isolate the branch point commit.

**Comment by hmaarrfk** [comment]
@stefanv got it

**Comment by matthew-brett** [comment]
@stefanv - sorry - I wasn't being diplomatic about the DNS thing, I really don't know how to do it - because I never bothered to think through the relationship of the domain name and the certificate.  The problem is, it has to be HTTPS, otherwise the pip command is annoying, and it's less secure.

**Comment by stefanv** [comment]
Matthew, it is done! (AppVeyor enabled cron for us.)

**Comment by stefanv** [comment]
That would be great; thank you!  I've added you as an administrator.
