### ISSUE TITLE
generic_filter slow on large images

### ISSUE THREAD

**Issue by cathoderaymission** [scikit-image/scikit-image#3166]
## Description
I am using the generic_filter function to compute an image quality assessment metric, the  image contrast,  per the following:

def fnc(buffer): np.sum(np.abs(buffer[:]-buffer[4]))

np.mean(generic_filter(img, fnc, 3))

While this works beautifully, and scitkit-image is awesome being the only package to provide the ability to attach a function to a filter, it is incredibly slow on over 2k x 2k images.

As I can't find any documentation about speeding this up, I'm filing this in hopes their is some possible means of performance increase in a future release.

**Comment by soupault** [comment]
Hi @cathoderaymission !
`generic_filter` is not something `scikit-image` provides. You've, probably, mixed up `scikit-image` with `scipy`, a library for scientific computing in Python.
I'm going to close this issue as it is not related to our library, but you are welcome to report it in the `scipy` repository bugtracker (https://github.com/scipy/scipy/issues)

**Comment by jni** [comment]
@cathoderaymission, while @soupault is correct that this is a SciPy question, I actually wrote a blog post about exactly this issue a year ago:

https://ilovesymposia.com/2017/03/12/scipys-new-lowlevelcallable-is-a-game-changer/

There is also a follow-up:

https://ilovesymposia.com/2017/03/15/prettier-lowlevelcallables-with-numba-jit-and-decorators/

I hope you find these useful!
