### ISSUE TITLE
Inconsistent submodule top-level imports

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3184]
For some reason that I don't understand, `feature` is not imported automatically with `skimage`, but `filters` is. This works:

```python
>>> import numpy as np
>>> import skimage
>>> skimage.filters.gaussian(np.random.random((5, 5)))
```

But this doesn't:

```python
>>> import numpy as np
>>> import skimage
>>> skimage.feature.structure_tensor(np.random.random((5, 5)))
AttributeError: module 'skimage' has no attribute 'feature'
```

`feature` is not imported at the top level automatically. Neither are `future` or `segmentation`. `morphology` and `transform` are.

Inspecting `skimage/__init__.py` didn't give me any insight as to why this is the case. Does anyone have any ideas?

(And tangentially, what is the *desired* behaviour here?)

**Comment by stefanv** [comment]
Nothing should be imported by default.

**Comment by stefanv** [comment]
```
In [1]: >>> import numpy as np
   ...: >>> import skimage
   ...: >>> skimage.filters.gaussian(np.random.random((5, 5)))
   ...: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-947e43ad5387> in <module>()
      1 import numpy as np
      2 import skimage
----> 3 skimage.filters.gaussian(np.random.random((5, 5)))

AttributeError: module 'skimage' has no attribute 'filters'
```

**Comment by jni** [comment]
@stefanv how rude! LOL

Well, indeed on my colleague @GenevieveBuckley's machine, I can observe the behaviour you show, but on mine it works perfectly fine. No idea what the cause is. If I figure it out I'll post again here.
