### ISSUE TITLE
Shadow detection using skimage

### ISSUE THREAD

**Issue by Megh-Thakkar** [scikit-image/scikit-image#3214]
## Description
I am new to using skimage. I have implemented [this](https://research.ijcaonline.org/volume42/number10/pxc3877805.pdf) paper in Matlab and was trying to do the same in Python using skimage.
The required result was not obtained. 
1. The **rgb2hsv** method gave substantially different values(in one case, the S value differed by 0.14) and since it is one of the initial steps, it became tough to monitor further errors. 
2. The threshold otsu values from filters.threshold_otsu and graythresh have a significant difference.

Can anyone help me with the implementation? 

## The Matlab code is as follows

```matlab

img = (imread('building.jpg'));

double_img = im2double(img);

HSV=rgb2hsv(double_img);
H=HSV(:,:,1);
S=HSV(:,:,2);
V=HSV(:,:,3);


NDI = (S-V)./(S+V);


level = graythresh(NDI);
BW = imbinarize(NDI,level);

labelled = bwlabel(BW);

selem = strel('square',3)

BW2 = imdilate(labelled,selem);

sub = double(BW2) - double(labelled);

vb = var(sub(:));
vi = var(labelled(:));
mb = mean(sub(:));
mi = mean(labelled(:));

final_img = mb + (((labelled - mi) ./ vb) .* vi) ;

out = im2double(final_img);

imshow(out);

```

TIA

**Comment by hmaarrfk** [comment]
@Megh-Thakkar I'm not going to be of much help, but if you are having discrepancies between `rgb2hsv` in matlab and scikit-image it might be due to the way `scikit-image` and matlab compute them.

I ran into this myself a while back Issue #3058

My first tip would be: make sure you images are floats in both scikit-image and matlab. There are strange things that can happen with implicit conversions. You may choose to go back to `uint8` after you figure out the peculiarities of the color conversion.

Since you are rather mathematical, go through the code for [rgb2hsv](https://github.com/scikit-image/scikit-image/blob/master/skimage/color/colorconv.py#L224) and make sure it is performing the color conversion you are expecting. Finally, go through it for [matlab](https://www.mathworks.com/help/matlab/ref/rgb2hsv.html) as well, though that one is harder to do since it is likely closed source ;).

**Comment by stefanv** [comment]
Please also post your Python code.

**Comment by stefanv** [comment]
(In the future, I suggest asking either on the mailing list or StackOverflow.  We try and reserve issues for technical issues with the library, not for support.)

**Comment by jni** [comment]
@Megh-Thakkar regarding the data type conversions mentioned by @hmaarrfk , see #3009.

**Comment by jni** [comment]
(And the documentation page linked from there: http://scikit-image.org/docs/dev/user_guide/data_types.html)

**Comment by Megh-Thakkar** [comment]
Thanks a lot for the quick replies! @hmaarrfk I will surely look through the implementations.
@stefanv here is the python code:
```python
from skimage import data, exposure, filters, color, morphology, io
import skimage
from skimage.measure import label
from PIL import Image
import numpy as np
np.set_printoptions(threshold='nan')
# camera = data.camera()

# print camera.shape

def im2double(im):
    min_val = np.min(im.ravel())
    max_val = np.max(im.ravel())
    out = (im.astype('float') - min_val) / (max_val - min_val)
    return out

def imbinarize(img, threshold):
    img[img >= threshold] = 1
    img[img < threshold] = 0
    return img

img = Image.open("building.jpg")
img = img.convert('RGB')
img_data = np.array(img)
double_img = skimage.img_as_float64(img_data)

hsv_img = color.rgb2hsv(img_data)
H = hsv_img[:, :, 0]
S = hsv_img[:, :, 1]
V = hsv_img[:, :, 2]
NDI = (S - V)/(S + V)

NDI[np.argwhere(np.isnan(NDI))] = 0	# prevent NaN

level = filters.threshold_otsu(NDI)
binary = imbinarize(NDI, level)
labelled = label(binary, connectivity=1) 
selem = morphology.square(3)
dilated = morphology.binary_dilation(labelled, selem)
sub = dilated.astype(np.float32) - labelled.astype(np.float32)

var_binary = np.var(sub)
var_labelled = np.var(labelled)
mean_binary = np.mean(sub)
mean_labelled = np.mean(labelled)
modified_img = mean_binary + ((labelled - mean_labelled)/var_binary)*var_labelled

final_img_data = im2double(modified_img)
final_img = Image.fromarray(final_img_data, "L")
final_img.show()

```
I will keep it in mind to not post for support here.
Thanks @jni I will go through it!

**Comment by stefanv** [comment]
You can save yourself some trouble doing the image loading:

```
from skimage import io, color, img_as_float

image = img_as_float(io.imread('building.jpg'))
hsv = color.rgb2hsv(image)
```

Then, if you can save the following, we can help debug:

1) The floating point image matrix in Matlab (as a .mat)
2) The HSV image matrix in Matlab (as a .mat)
3) The floating point image array in Python (using np.save, as a .npy file)
4) The HSV image array in Python (using np.save, as a .npy file)

Thanks!

**Comment by sciunto** [comment]
As it seems to be solved, I close this issue.
