### ISSUE TITLE
register_image numpy max of complex numbers

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3248]
https://github.com/scikit-image/scikit-image/blob/f21c52bc248b59197129d60b97285e1579fee6bf/skimage/feature/register_translation.py#L193-L197

numpy maximum of complex numbers is ordered in lexicographic order. not in terms of which number has the greater magnitude.

```python
import numpy as np
np.max([1, 5j])
```
gives `1` and not `5j`

There are a few other places where the code can be cleaned up. 
Did the author mean lexicographic order?

**Comment by grlee77** [comment]
Closing as it looks like this issue has since been fixed:

https://github.com/scikit-image/scikit-image/blob/24dfff0ab8cfc7cd98dbd40c2ebdd1c9d193d100/skimage/registration/_phase_cross_correlation.py#L244-L246
