### ISSUE TITLE
Make `io.ImageCollection` cross-platform compatible for same path specifier

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3258]
Currently, different path separators have to be used on Windows and Linux.

**Comment by jni** [comment]
to be clear, `ImageCollection('*.png:*.jpg')` works on *NIX, while `ImageCollection('*.png;*.jpg')` works on Windows. We should do a find and replace on the input string based on platform. However we have to be careful because `:` is a valid filename character in *NIX.

**Comment by stefanv** [comment]
https://stackoverflow.com/questions/54659897/skimage-io-imagecollection-not-showing-all-files-i-want-when-using-io-imagecolle

**Comment by stefanv** [comment]
@hmaarrfk That would be a good solution.  @jni If ':' is a valid filename in Unix, our current implementation is already broken.  Are semi-colons acceptable in Unix filenames?  Or are colons acceptable in Windows filenames?  Any of these options allow us to make a fix.  But Mark's suggestion is a better long-term solution, I think.

**Comment by jni** [comment]
@stefanv 

```
 $ ls -l
total 192
-rw-r--r--   1 jni  staff     0B 18 Feb 10:47 ;.txt
```

=P

I vote for Mark's suggestion. But honestly I agree with the first commenter that it's not a bug, and we should continue using `os.pathsep` even after we implement lists. It is an internally consistent solution.

**Comment by stefanv** [comment]
You can decide not to call it a bug, but I think the many users who
simply write `ImageCollection('some_glob:another_glob')` won't benefit
from such an assessment.

**Comment by jni** [comment]
I agree 100% (see my comment about our low dynamic range warnings), but I don't think the solution is to break the `os.pathsep` convention. Mark's suggestion is easy to remember and unambiguous.

**Comment by stefanv** [comment]
Agreed, that is a better API.

**Comment by stefanv** [comment]
This came up again at the 2024 tutorial; I think we should (a) have code work consistently across platforms and (b) implement @hmaarrfk's suggestion to have IC take lists as input (as a preferred API).

**Comment by stefanv** [comment]
Solution implemented already; should just update tutorial material.
