### ISSUE TITLE
segmentation.felzenszwalb document improvement

### ISSUE THREAD

**Issue by Page-David** [scikit-image/scikit-image#3264]
## Description
I tried to use felzenszwalb's segmentation algorithm in skimage, but some part of its doc is really confusing (at least for me).

Firstly, the `scale` parameter is described as `Free parameter. Higher means larger clusters.` but only after I read 
[the source code][1], I found it is exactly the constant `k` in the threshold function that described in the [original paper][2]. So I think the doc should add something like `the k used in threshold function`. By the way, I wonder why the default of `scale` is 1 but not a larger number that the author used like 150 or 300 which works better in common cases?

And secondly, I do not really understand that why `sigma` was described as `Width of Gaussian kernel used in preprocessing` especially the word `width`. But I think it is the `sigma` is standard deviation used in 2-D Gaussian function, isn't it?

[1]:https://github.com/scikit-image/scikit-image/blob/master/skimage/segmentation/_felzenszwalb_cy.pyx#L108
[2]:http://people.cs.uchicago.edu/~pff/papers/seg-ijcv.pdf

**Comment by JDWarner** [comment]
Hi @Page-David, thanks for the report.  I believe your understanding is correct in both cases.  

We try to expose parameters in ways which will make intuitive sense, which is likely why a variable from a paper (`k`) got changed to `scale`.  However, I would certainly approve of the suggested wording change.  As far as the default goes, I'm not sure why that specific value was chosen, but rarely is any single default appropriate in the majority of cases.  Oversegmentation is frequently desired behavior.

As for `sigma`, again the wording is intended to describe how the parameter works.  Conceptually, the width of the bell curve is controlled by `sigma`.  For those - including both you and I - who know what `sigma` means in the context of a Gaussian curve, the name of the parameter should be sufficient.  There's always a balance when it comes to making these things accessible.

Would you like to make a pull request with your suggested wording change in the `scale` parameter?

**Comment by Page-David** [comment]
@JDWarner I totally agree with your idea on docstring. But I still have doubts on `Oversegmentation is frequently desired behavior`. I tested it with following code:
```python
    res = skimage.segmentation.felzenszwalb(skimage.data.astronaut(), sigma=0.8, scale=300, min_size=20)
    import numpy as np # pick a random color for each region
    new = np.ndarray([512, 512, 3])
    for i in range(res.max()):
        new[res==i, :] = np.random.random_integers(255, size=(3,))
    cv2.imwrite('result.png', new) # save the segment image
```
![y](https://user-images.githubusercontent.com/15627425/42730151-4581b87a-8820-11e8-88e1-1c823068398d.png)
And this time change the `scale` to `1`, obviously, that cause the result far too fine and too over-segment.
![z](https://user-images.githubusercontent.com/15627425/42730152-464bc962-8820-11e8-9c69-840198ee7644.png)
So, I do not think that such small default `scale` is a good idea.

**Comment by sciunto** [comment]
For this issue, I would suggest to enhance the documentation as you pointed out. Regarding the second point, I would write `width (standard deviation) of the gaussian kernel`, so that we keep two levels of understanding.

For the default option, I guess it is difficult to find something "universal". Unity seems better to me than 100, 1000 or 863. :)

@Page-David Are you interested in writing a patch?

**Comment by Page-David** [comment]
@sciunto Good idea, I added this in my PR #3272. And for default value of `k`, I changed my opinion, if a universally ideal value is not exist, just remain it unchanged.
