### ISSUE TITLE
imread from terminal always starts UI

### ISSUE THREAD

**Issue by tindli** [scikit-image/scikit-image#3274]
Why does skimage.io always start the UI viewer
although I am not even showing the image?

I just want to read an image from the filesystem with imread().

Is this intended behavior when running the following script from the terminal?

```
from skimage.io import imread
img = imread('mypic.png', True)
```

MacOS 10.13.4
scikit-image Version 0.14.0
Python-version: 3.7.0

**Comment by jni** [comment]
This is possibly related to #3243. @tindli do you think you could install skimage from master and see whether your problem is resolved?

**Comment by stefanv** [comment]
No, that is certainly not intended behavior.  Can you attach a
screenshot of the viewer that is launched?
