### ISSUE TITLE
skimage.measure.regionprops can't be applied to image with one row/column

### ISSUE THREAD

**Issue by Daiver** [scikit-image/scikit-image#3278]
## Description
As far as i understand `skimage.measure.regionprops` raises `TypeError('Only 2-D and 3-D images supported.')` when applied to 2D image with one row/column.
If i understood correctly it happens due to `np.squeeze` and successive assertion in `skimage.measure.regionprops`

Part of `skimage.measure.regionprops` source code which raises exception
```
    label_image = np.squeeze(label_image)
    if label_image.ndim not in (2, 3):
        raise TypeError('Only 2-D and 3-D images supported.')
```

## Way to reproduce
Minimal example
```
import numpy as np
import skimage.measure
mask = np.array([
    [1],
], dtype=np.uint8)

print(mask.ndim) #2-D image
print(skimage.measure.regionprops(mask))
```
- Operating system and version: Ubuntu 17.10 
- Python version: 3.6.3
-  scikit-image version 0.14.0

PS Sorry for my poor English

**Comment by stefanv** [comment]
Your English is perfectly understandable, Kirill.  Thank you for the bug report!

I think this is indeed a bug, so would you like to file a pull request to fix it?

**Comment by ambrosejcarr** [comment]
Adding to this, it seems to occur when there is any 1-size axis. The project I'm working on processes a mixture of 2d and 3d data, so for simplicity we attempt to process 2d data as "fake 3d" data whenever possible. This triggers what I think is probably the same bug listed in this issue.
 
```python
>>> import numpy as np
>>> from skimage.measure import regionprops

>>> x = np.arange(4).reshape(1, 2, 2)
>>> y = np.arange(4).reshape(1, 2, 2)
>>> y.shape
(1, 2, 2)

# if you pre-squeeze out the 3rd axis, it works:
>>> regionprops(np.squeeze(y), np.squeeze(x))
[<skimage.measure._regionprops._RegionProperties at 0x1111e20b8>,
 <skimage.measure._regionprops._RegionProperties at 0x1111e23c8>,
 <skimage.measure._regionprops._RegionProperties at 0x1111e2518>]

# without the squeeze, an error is triggered
>>> regionprops(y, x)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-b46c4427f24e> in <module>()
----> 1 regionprops(y, x)

/usr/local/lib/python3.6/site-packages/skimage/measure/_regionprops.py in regionprops(label_image, intensity_image, cache, coordinates)
    563 
    564         props = _RegionProperties(sl, label, label_image, intensity_image,
--> 565                                   cache, coordinates=coordinates)
    566         regions.append(props)
    567 

/usr/local/lib/python3.6/site-packages/skimage/measure/_regionprops.py in __init__(self, slice, label, label_image, intensity_image, cache_active, coordinates)
    105         if intensity_image is not None:
    106             if not intensity_image.shape == label_image.shape:
--> 107                 raise ValueError('Label and intensity image must have the'
    108                                  'same shape.')
    109 

ValueError: Label and intensity image must have thesame shape.

```

**Comment by Daiver** [comment]
Hello Stefan! Thank you for answer. Yes i think that i can create pull request. Only problem is how to solve this problem. Simplest solution is just remove `label_image = np.squeeze(label_image)` line. This solution allow user to directly manage shape transformation of `label_image` before `skimage.measure.regionprops` call. Also it works for me :). But there are another ways to solve this problem. For example it's possible to call `np.squeeze` only if `label_image.ndim > 3`. I am not a experienced skimage user so i don't know which solution coincides with skimage "style".
Anyway currently I'm reading `https://github.com/scikit-image/scikit-image/blob/master/CONTRIBUTING.txt`

**Comment by ambrosejcarr** [comment]
@Daiver if it's possible, would you mind fixing the missing whitespace at the end of the first line in the `ValueError` that gets triggered by this bug? It results in a Typo. :-)

`ValueError: Label and intensity image must have thesame shape.`

**Comment by Daiver** [comment]
@ambrosejcarr Sorry for late answer. It looks like my pull request (https://github.com/scikit-image/scikit-image/pull/3284) currently is in the review process. So i am not sure that updating it currently is good idea.
But after accept/reject i definetly can create another pull request with typo fix =)
