### ISSUE TITLE
Failure to import jpgs correctly from canon camera

### ISSUE THREAD

**Issue by JLJ90** [scikit-image/scikit-image#3283]
When trying to load images into skimage that were taken on my canon g9x 2 it does not read the image correctly. It works perfectly fine when using cv2. The problem comes when I want to display it in matplotlib.pyplot

skimage works perfectly fine with all other images I have used (from different devices).

from skimage.io import imread
import matplotlib.pyplot as plt

image = imread(path)
image.dtype
>>> dtype('O')

![img_0065](https://user-images.githubusercontent.com/35571955/43034457-9fd21d2a-8cd4-11e8-8add-4a5c75e21efc.JPG)

-  Win 10 64 bit
-  Python version - 3.6.4  (using jupyter notebook)
-  scikit-image version 0.13.1

plt.imshow(image)

TypeError                                 Traceback (most recent call last)
<ipython-input-6-12ba6d47bd7e> in <module>()
----> 1 plt.imshow(image)

D:\Anaconda\lib\site-packages\matplotlib\pyplot.py in imshow(X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, hold, data, **kwargs)
   3099                         filternorm=filternorm, filterrad=filterrad,
   3100                         imlim=imlim, resample=resample, url=url, data=data,
-> 3101                         **kwargs)
   3102     finally:
   3103         ax._hold = washold

D:\Anaconda\lib\site-packages\matplotlib\__init__.py in inner(ax, *args, **kwargs)
   1715                     warnings.warn(msg % (label_namer, func.__name__),
   1716                                   RuntimeWarning, stacklevel=2)
-> 1717             return func(ax, *args, **kwargs)
   1718         pre_doc = inner.__doc__
   1719         if pre_doc is None:

D:\Anaconda\lib\site-packages\matplotlib\axes\_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   5129                               resample=resample, **kwargs)
   5130 
-> 5131         im.set_data(X)
   5132         im.set_alpha(alpha)
   5133         if im.get_clip_path() is None:

D:\Anaconda\lib\site-packages\matplotlib\image.py in set_data(self, A)
    616         if (self._A.dtype != np.uint8 and
    617                 not np.can_cast(self._A.dtype, float, "same_kind")):
--> 618             raise TypeError("Image data cannot be converted to float")
    619 
    620         if not (self._A.ndim == 2

TypeError: Image data cannot be converted to float

**Comment by sciunto** [comment]
I'm closing this issue as wontfix. As @jni said, we will sooner or later change the way we read/write images and it will be solved by this unspecific change. If the workarounds proposed doesn't work for you, let us know.

Thanks for reporting.
