### ISSUE TITLE
The python3-skimage package was removed from the "Debian Testing" repository

### ISSUE THREAD

**Issue by kraamis** [scikit-image/scikit-image#3298]
The python3-skimage package was removed from the "Debian Testing" repository

kraamis @ debian [~] $ sudo apt-get install python3-skimage
Reading Package Lists ... Done
Building a Dependency Tree
Reading status information ... Done
The python3-skimage package is not available, but is mentioned in the dependency list of another package.
This can mean that the package is missing, obsolete, or available from sources not mentioned in the sources.list

E: No installation candidate found for the "python3-skimage" package

**Comment by jni** [comment]
As I understand it we don't take responsibility for Debian packaging anymore. @stefanv?

@kraamis as a workaround, is there a reason why you can't install with pip/conda?

**Comment by kraamis** [comment]
"pip" work, but a prefer use "apt-get", when possible

**Comment by soupault** [comment]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901377, https://tracker.debian.org/pkg/skimage/news/.

**Comment by sciunto** [comment]
Debian testing is not a stable version of debian, so such removal can happen. As said by @jni, we are not officially involved in packaging. This work must be done on the debian side (even if we can see the same people :) ). So, I close it as invalid. If you feel that it must be reopened, feel free to speak ;)
