### ISSUE TITLE
Discussion: solution for large data files

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3323]
The size of the wheel is quite big. This has been identified as an issue in #2978 #3263 #1991
Ideally, we would just package conda and pypi subpackages  but I don't think those exist yet.... @jakirkham maybe you can confirm my suspicion?

We could decrease the size of the test images, but I feel like 5x5 images are quite boring :smile:  and may not even be possible with some of the algorithms.

I've identified 3 main sources for the large package size:
1. `data` directory: 15 MB
2. `restoration/tests`: 8MB (about to get moved to data with if PR #3324 is accepted)
3. Cythonized libraries. On my machine, there are about 48 files, totalling 50 MB uncompressed (15 MB compressed) . The cython issues seems to have been reported here: https://github.com/cython/cython/issues/2102 and more specifically in this comment https://github.com/cython/cython/issues/2102#issuecomment-397755796 See PR #3325

This proposal would split `scikit-image` into two packages:  `scikit-image` and `scikit-image-data`. It might look something like this:

![image](https://user-images.githubusercontent.com/90008/43690444-21055286-98d8-11e8-8673-a3e37664262d.png)

`scikit-image-data` would install in the data in the same directory as `scikit-image` so if a user wants to, they can have most of functionality by just installing `scikit-image` but to use the datasets we provide, they would have to install scikit-image-data

I'm trying to make sure that `scikit-image-data` depends on the same version `scikit-image`. This used to be possible with rpms and was how they dealt with development package dependencies. I was having trouble with this, and am willing to bet that this is a "non-issue" for many python packages. 
I think the `.dev0` was giving it trouble.
I don't know if it is really possible to do it with python to be honest. We might need help from upstream.

A things to ponder on:
  * We would need to tag the tests so that we know whether or not they depend on data. 
  * there are some complications in having both of these in the same top level folder. Maybe it would be easier to just have the data in a different repository. Since the data is likely going to be less volatile than the repo, this may be a pretty good idea.

If such a proposal would be accepted, there are a few things to do:
  * [ ] Update the instructions
  * [ ] Ensure the build process passes 
  * [ ] Update the conda feedstock
  * [ ] Update the wheel generation
  * [ ] Update release notes
  * [ ] (Try to) add a human readable message when a user tries to import `skimage.data` without having installed `scikit-image-data`.
  * [ ] Make sure that both packages do not have overlapping files.

If anybody wants to help, I can give them write access to my scikit-image fork.
Sample PR on my fork: https://github.com/hmaarrfk/scikit-image/pull/8

I was able to install both packages and run pytest after having installed them.
I don't want to keep working

**Comment by jni** [comment]
subpackages or something like it do exist in PyPI, not in conda, e.g. `pip install dask[array]`. We could have `pip install scikit-image[core]` to get a minimal package. In conda this is not yet possible, afaik. Also, in the core, we should have automatic downloading of the data when a user imports it, if it's not yet present, together with a sensible error message if there is no internet connection.

**Comment by hmaarrfk** [comment]
@jni, do you have docs for how I would go about implementing the subpackage? I couldn't find them....

**Comment by hmaarrfk** [comment]
@jni, from what I saw in dask, `dask[array]` would pull `numpy`, but not an other "internal" directory.

We should technically utilize more of these new `setup-tools` features to simplify the installtion of things like testing requirements, examples, and what not.

**Comment by soupault** [comment]
I'm not in favour of that subpackage thing as it is not equally supported by all the distribution channels (pip, conda, @cgohlke website).
What if we just don't package ´data´ (or the images inside) by default, write a decorator that will download the images from the GitHub repo or use the cached versions (if available), and wrap all the corresponding ´data.´ functions using it? Assuming that we don't move images within the repo, this implementation will have almost 0 maintenance cost increase.

**Comment by jni** [comment]
@soupault I agree that the conda status is a mess. But I'm hoping that [this issue](https://github.com/conda/conda/issues/7502) will be resolved soonish.

Subpackages have advantages over the url thing. Specifcially, if I want an offline environment where I can run scikit-image examples, this is easy to do with `pip install scikit-image[data]` or `pip install scikit-image[all]`, but hard with the automatic downloads, even if we add `skimage.data.download_all()`, which I would definitely want at a minimum if we go that route.

The other thing is that I also think it would be good to use subpackages for e.g. optional dependencies, the viewer, maybe typing stubs, etc.

**Comment by sciunto** [comment]
I'm sorry @soupault but I do not like much your proposition. To express differently what @jni said, there are plenty of situations where the internet is not reliable like during lectures because the infrastructure is not comfy. 

Also, have we checked that storing data on github for that use is allowed by the github's Terms of Use?

**Comment by sciunto** [comment]
Another thought. In case we go to the online solution, we have to ensure the integrity of these images with a checksum (imagine dealing with bug reports due to corrupted images...)

**Comment by jni** [comment]
I just saw a blog post that is highly relevant to this discussion:

http://www.leouieda.com/blog/introducing-pooch.html

I'll admit that my strongest reason for wanting to use this library is the cute name. =P But, apart from that, it's designed for exactly the use case we are discussing (here and in #3384), and based on the post, I quite like the design. I think we should contribute there and use it, perhaps with vendoring since it's so young.

**Comment by stefanv** [comment]
Nice! This is perfect: simple, Pythonic, and Good Enough For Now.

**Comment by hmaarrfk** [comment]
@jni, it seems that the 1 feature that is missing is a `fetch_all` function. Seems pretty easy to write a loop ourselves, but I wanted to bring up the "offline" requirement that was made earlier.

**Comment by jni** [comment]
@hmaarrfk yes, I noticed that, but I think it's a trivial fix that we can make either locally or upstream.

**Comment by grlee77** [comment]
I am closing this issue as it seems largely resolved by moving to pooch in #3945. Please reopen and comment with an updated summary of any remaining tasks if there are remaining aspects still to be addressed.
