### ISSUE TITLE
Coverage low hanging fruits

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3328]
It might be worthwhile to spend some time hacking together something that will get us closer to 90% coverage.

A few areas that I've identified that could use some work are:

| Feature                  | Dfficulty           | Desirability    | Codecov reference | 
|---------------------|------------------|---------------|---------------|
| Remove unused lines of code in test | Low | Medium | [For example](https://codecov.io/gh/scikit-image/scikit-image/src/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/_shared/tests/__init__.py) |
| Test testing suite | Medium-Low | High | [utils](https://codecov.io/gh/scikit-image/scikit-image/tree/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/_shared) |
| Friendly error messages  | Medium (needs CI knowledge) | Medium |[ __init__py](https://codecov.io/gh/scikit-image/scikit-image/src/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/__init__.py)  |
| Ignore skivi | Low | Low | [skivi](https://codecov.io/gh/scikit-image/scikit-image/src/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/scripts/skivi.py) | 
| Test skivi | Need Qt testing knowledge | Medium-Low | [skivi](https://codecov.io/gh/scikit-image/scikit-image/src/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/scripts/skivi.py) |
| gdal plugin | Low | Medium | [gdal_plugin.py](https://codecov.io/gh/scikit-image/scikit-image/src/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/io/_plugins/gdal_plugin.py) | 
| qt image plugins | High | Medium | [plugins](https://codecov.io/gh/scikit-image/scikit-image/tree/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/io/_plugins)| 
| Test tiffle plugin | High (needs tiff knowledge) | Medium | [tiffle.py](https://codecov.io/gh/scikit-image/scikit-image/src/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/external/tifffile/tifffile.py) |
| Viewer | Medium-High (needs Qt, there are examples) | Medium-Low | [viewer](https://codecov.io/gh/scikit-image/scikit-image/tree/f3757f23244e7ebebff931bdca87b4d4cfa2149d/skimage/viewer) |

Much of the difficulty arises in testing Qt apps. I am interested in learning how to do that for my own projects, so if anybody has a tutorial it would be nice to share :D.

**Comment by abhishekarya286** [comment]
Hi @hmaarrfk. I would like to work on the first part.

**Comment by hmaarrfk** [comment]
@abhishekarya286 go for it! I don't think @jni or @stefanv will have any issues with remove a few functions in the `__main__` guards, but maybe? The changes are pretty easy so I think that discussion can happen on the PR.

the `Test the testing suite` should be fun too! Keep that to a separate PR.

**Comment by jni** [comment]
:+1:

**Comment by sciunto** [comment]
at lease, skivi, tifffile, qt, and viewer can be removed from the todo list.

**Comment by hmaarrfk** [comment]
thx
