### ISSUE TITLE
Failure to import filter

### ISSUE THREAD

**Issue by lucilla7** [scikit-image/scikit-image#3333]
## Description

Failure to import skimage.filter on MacOSX

## Way to reproduce

<b>Code:</b>

`from skimage import filters`

<b>Traceback:</b>

> Traceback (most recent call last):
>   File "/Users/Apollo/PycharmProjects/CT_registration/spine_filtering.py", line 16, in <module>
>     from skimage import filters
>   File "/Users/Apollo/venv/lib/python2.7/site-packages/skimage/filters/__init__.py", line 11, in <module>
>     from .thresholding import (threshold_local,
>   File "/Users/Apollo/venv/lib/python2.7/site-packages/skimage/filters/thresholding.py", line 8, in <module>
>     from ..transform import integral_image
>   File "/Users/Apollo/venv/lib/python2.7/site-packages/skimage/transform/__init__.py", line 4, in <module>
>     from .radon_transform import (radon, iradon, iradon_sart,
>   File "/Users/Apollo/venv/lib/python2.7/site-packages/skimage/transform/radon_transform.py", line 7, in <module>
>     from ._radon_transform import sart_projection_update
> ImportError: dlopen(/Users/Apollo/venv/lib/python2.7/site-packages/skimage/transform/_radon_transform.so, 2): Symbol not found: ___sincos_stret
>   Referenced from: /Users/Apollo/venv/lib/python2.7/site-packages/skimage/transform/_radon_transform.so
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /Users/Apollo/venv/lib/python2.7/site-packages/skimage/transform/_radon_transform.so

<b>Environment:</b>

- Operating system and version: Mac OS X Lion 10.7.5
- Python version: 2.7.1 on virtualenv
- scikit-image version: 0.14.0, installed with wheel

**Comment by hmaarrfk** [comment]
Seems like you need to upgrade OSX:
https://stackoverflow.com/a/19039051/2321145

Or maybe try installing through conda? Conda installs some C dependencies for you

**Comment by lucilla7** [comment]
@hmaarrfk Thank you. At the moment I can't upgrade the operating system...I'll try with conda or stick with a previous version.

**Comment by hmaarrfk** [comment]
You can also try compiling it yourself.

**Comment by sciunto** [comment]
This issue is old and without a reply, i close it. Feel free to reopen if it is unsolved.
