### ISSUE TITLE
Better backport with Mr Meeseeks.

### ISSUE THREAD

**Issue by Carreau** [scikit-image/scikit-image#3339]
Hi all, in particular @jni and @stefanv 

I see that you are often mentioning the backport bot to do backport (in particular on the 0.14.x branch), and this lead to PRs where you forget to backport. 
In particular as you are using milestone, what you could do is setup the milestone so that the bot automatically issue the backport on merge. To do so edit the milestone description and add:

`on-merge: backport to 0.14.x`

Second thing:  now MrMeeseeks allow finer grained permission, so you could give individuals with not commit right the ability to talk to mr meeseeks and ask it to do specific commands like only tag, or backport. You do so by creating a .yml config file at the root of this repository. Haven't documented that yet, so let me know and I can send a PR.

**Comment by jni** [comment]
Hi @Carreau! Thanks for chiming in!

Regarding your first point, I knew about this behaviour but (a) it's a little too magical for me; and (b) I like to use milestones for issues that I consider blockers for that milestone. Whereas many of these PRs are "nice to haves" in the milestone and so I want to merge them "as soon as possible" and put them in "the next release", whatever that is, and not have any stalled PRs or issues hold up the milestone.

Maybe I'm doing GitHub management wrong but that's my mental model so far.

As to the second point, I very much would like contributors to be able to issue Meeseeks commands! Thanks!

**Comment by Carreau** [comment]
> Maybe I'm doing GitHub management wrong but that's my mental model so far.

No it's ok, it's your workflow so it's the good one. Let me know if another workflow could help. Now that MrMeeseeks can fetch config from repositories, we can try to accomodate for flexibility. 

> As to the second point, I very much would like contributors to be able to issue Meeseeks commands! 

Let me know who and which commands I can send a PR with the right configuration.

**Comment by soupault** [comment]
I see that MrMeeseeks can already work well with GitHub labels. Why not to use `on-merge: backport to 0.14.x` label instead of a modified milestone text?

**Comment by Carreau** [comment]
That is likely doable. I forgot tht labels also have a description, so commands would be put in the description as well and triggered on merge.

**Comment by soupault** [comment]
@Carreau I guess you might need to review the logic of copying labels from the original PR to the backport (so to avoid endless backporting), but that shouldn't be an issue.

**Comment by Carreau** [comment]
There is the same problem from milestone. Triggers of backport only apply if the branch is master.
The bot also tend to avoid to reply to itself, but yes that is something we need to be careful off. That's why you are the guinea pigs :-)

**Comment by Carreau** [comment]
> I forgot that labels also have a description,

Well, it's apparently recent and still experimental on the GH side.
MrMeeseeks now looks in labels description at merge time. If you modify a label description with `on-merge: backport ...` that should work... as long as GitHub does not change API of course. 
You can also use `on-merge: say ... `, or any other commands understood by MrMeeseeks.

**Comment by soupault** [comment]
Nice, thanks! Looking forward to seeing a MRG+1 PR: https://github.com/scikit-image/scikit-image/labels/on-merge%3A%20backport%20to%200.14.x .

**Comment by Carreau** [comment]
Oh, I was more thinking in this way, where I look at the description for commands, so you can put several commands per-description and have a short label.
![screen shot 2018-08-12 at 13 28 42](https://user-images.githubusercontent.com/335567/44006125-a8419128-9e33-11e8-9319-feaaa8d813ce.png)

I can implement both.

**Comment by soupault** [comment]
@Carreau That's even better! Let's follow your suggestion.

**Comment by emmanuelle** [comment]
A simple question: what is the procedure to backport a PR? Is it documented somewhere in our development doc?

**Comment by Carreau** [comment]
> A simple question: what is the procedure to backport a PR

I can't talk for the scikit image core team, but at least if you want to use the bot, you mention it on the PR and ask it `backport to <branchname>`
You can also have a label (or a milestone), that have in its `description` `on-merge: backport to <branchname>`, and the bot will try to backport and issue a backport-PR when the principal-PR get merged.

If it can't the bot will give instructions on how to cherry-pick manually (and resolve conflict) as well as add the tag "Still Needs manual backport" in order to make it easy to find the issues needing human attention.

The bot will only reply to committers, or people listed in its [per-repo config file ](https://github.com/scikit-image/scikit-image/blob/master/.meeseeksdev.yml#L2-L4) as being allowed to backport 

You can see (some) statistics of what the bot have done so far [here](https://meeseeksbox.github.io/), more to come.

I have test repos if you want to try how the bot works w/o playing with it here.

Does that answer at least part of your question ?

**Comment by jni** [comment]
Thanks @Carreau for the summary! =)

@emmanuelle no, the procedure is new and still not quite "standardised".

@Carreau quick question: can you add the original PR title to the commit message/description? I just realised that it's going to be a pain in the ass to trace back everything that's made it into the branch...

**Comment by Carreau** [comment]
It should already be in it, here is the hEAD of the commit graph of v0.14.x:

```
*   commit f4883e2feb74615e204467476e1831c3ab8db757 (HEAD -> v0.14.x, origin/v0.14.x)
|\  Merge: 1b285dd22 5f91f5456
| | Author: Juan Nunez-Iglesias <juan.nunez-iglesias@monash.edu>
| | Date:   Thu Aug 30 00:37:15 2018 +1000
| |
| |     Merge pull request #3382 from meeseeksmachine/auto-backport-of-pr-3370-on-v0.14.x
| |
| |     Add missing cval parameter to threshold_local
| |
| |     Backport PR #3370 on branch v0.14.x
| |
| * commit 5f91f5456e42370beb2fd05b75f5e4ac0fdc6364 (origin/pr/3382)
|/  Author: Egor Panfilov <egor.v.panfilov@gmail.com>
|   Date:   Wed Aug 29 15:01:58 2018 +0300
|
|       Backport PR #3370:  Missing cval parameter in threshold_local
|
```

Unless I don't understand your request.

I can add it as well to the GitHub PR Title. If you have other Formatting enhancement feel free to let me know.

**Comment by jni** [comment]
@Carreau in this case, it's there because I added it. See the full list for many merge commits that have no info other than PR numbers (we only look at merge commits when making release notes).

```
*   commit f9beda744e9a312cf5d2f38a4e512f939c69eaa6 (HEAD -> v0.14.x, upstream/v0.14.x)
|\  Merge: f4883e2f a47f97aa
| | Author: Juan Nunez-Iglesias <juan.nunez-iglesias@monash.edu>
| | Date:   Mon Sep 3 12:47:45 2018 +1000
| | 
| |     Merge pull request #3383 from hmaarrfk/0.14.x_reorg_backports
| |     
| |      Backport PR #3162 and #3161 on branch v0.14.x
| | 
| * commit a47f97aaa68bb50f6c9382254e0e0c8c01424a44
| | Author: Mark Harfouche <mark.harfouche@gmail.com>
| | Date:   Thu Aug 30 09:23:50 2018 -0700
| | 
| |     pep8
| | 
| * commit 4559b5e76602cb4ec25d7d9af3fbb436e890d833
| | Author: Mark Harfouche <mark.harfouche@gmail.com>
| | Date:   Thu Jun 7 19:00:30 2018 -0700
| | 
| |     moved data_dir to within `data/__init__.py`
| | 
| * commit a8ee8ebdc306ee8e0bb2cbd5073871931d728d2f
| | Author: Mark Harfouche <mark.harfouche@gmail.com>
| | Date:   Thu Jun 7 22:50:07 2018 -0700
| | 
| |     Added tests for lookfor
| | 
| * commit 41348e1f0063ff5f7fcac715b12697c3cd90aeae
|/  Author: Mark Harfouche <mark.harfouche@gmail.com>
|   Date:   Thu Jun 7 19:04:00 2018 -0700
|   
|       Moved the definition of lookfor out of __init__.py
|   
*   commit f4883e2feb74615e204467476e1831c3ab8db757
|\  Merge: 1b285dd2 5f91f545
| | Author: Juan Nunez-Iglesias <juan.nunez-iglesias@monash.edu>
| | Date:   Thu Aug 30 00:37:15 2018 +1000
| | 
| |     Merge pull request #3382 from meeseeksmachine/auto-backport-of-pr-3370-on-v0.14.x
| |     
| |     Add missing cval parameter to threshold_local
| |     
| |     Backport PR #3370 on branch v0.14.x
| | 
| * commit 5f91f5456e42370beb2fd05b75f5e4ac0fdc6364
|/  Author: Egor Panfilov <egor.v.panfilov@gmail.com>
|   Date:   Wed Aug 29 15:01:58 2018 +0300
|   
|       Backport PR #3370:  Missing cval parameter in threshold_local
|   
*   commit 1b285dd2250b54a9c07ad3c98957e9884812faa9
|\  Merge: 425c153b f9733a53
| | Author: Egor Panfilov <egor.v.panfilov@gmail.com>
| | Date:   Thu Aug 23 13:58:16 2018 +0300
| | 
| |     Merge pull request #3375 from meeseeksmachine/auto-backport-of-pr-3374-on-v0.14.x
| |     
| |     Backport PR #3374 on branch v0.14.x
| | 
| * commit f9733a53db007ed66e47682b51b31f624bc09c2f
|/  Author: Egor Panfilov <egor.v.panfilov@gmail.com>
|   Date:   Thu Aug 23 13:57:46 2018 +0300
|   
|       Backport PR #3374: add comma to measure init
|   
*   commit 425c153bc28beac7bea270cc902809ce70abb954
|\  Merge: 7fa148ba c78cc236
| | Author: François Boulogne <fboulogne@sciunto.org>
| | Date:   Wed Aug 22 15:07:49 2018 +0200
| | 
| |     Merge pull request #3314 from soupault/deprecation_leftovers_0.14.1
| |     
| |     Remove deprecated `dynamic_range` in `measure.compare_psnr` (backport)
| | 
| * commit c78cc2363d71aeef17786ff4bcfe009bd91be39b
| | Author: Egor Panfilov <egor.v.panfilov@gmail.com>
| | Date:   Thu Aug 2 20:35:05 2018 +0300
| | 
| |     Add a note on missed API change to release notes for 0.14.1
| |   
* |   commit 7fa148ba4df024838d9c48d5747bae677880be8e
|\ \  Merge: a1aeea97 bcf106bd
| |/  Author: Egor Panfilov <egor.v.panfilov@gmail.com>
|/|   Date:   Wed Aug 22 12:27:49 2018 +0300
| |   
| |       Merge pull request #3369 from meeseeksmachine/auto-backport-of-pr-3366-on-v0.14.x
| |       
| |       Backport PR #3366 on branch v0.14.x
| | 
```

**Comment by jni** [comment]
(Title is probably a good spot for the info, "Backport PR Foo ([Original title]) on [branch]"

**Comment by Carreau** [comment]
Oh, it's because you are only looking at the merge commit; I see. 

Well not the PR get the name in the tile so that should help: 

```
*   commit d132824d870e07dbb04ae223ddecc0a3d5182c79 (HEAD, origin/6.x)
|\  Merge: a7b969dae df5895868
| | Author: Matthias Bussonnier <bussonniermatthias@gmail.com>
| | Date:   Sat Sep 1 17:19:45 2018 -0700
| |
| |     Merge pull request #11280 from meeseeksmachine/auto-backport-of-pr-11277-on-6.x
| |
| |     Backport PR #11277 on branch 6.x (Actually run some tests.)
| |
| * commit df5895868634ca62533620e3deca58d7e8129256 (origin/pr/11280)
|/  Author: Matthias Bussonnier <bussonniermatthias@gmail.com>
|   Date:   Sat Sep 1 17:00:47 2018 -0700
|
|       Backport PR #11277: Actually run some tests.
```

We can pester GitHub for a Merge commit template or something along.
I can also implement it in Mr Meeseeks, when saying "merge" would actually read a template file and do the merge by itself (i'm not a huge fan of this solution) as it requires the bot to directly commit on skimage.

**Comment by jni** [comment]
@Carreau I think putting the original title in the PR title is totally sufficient, thanks! I agree that getting Meeseeks to actually perform the merge is not a great plan.

**Comment by stefanv** [comment]
It looks like the backporting is working pretty smoothly now?  If so, time to add this to the developer guidelines and close.

**Comment by jni** [comment]
I think this can be safely closed. ;) Thank you @Carreau!
