### ISSUE TITLE
skimage.io should not import matplotlib.pyplot on module import

### ISSUE THREAD

**Issue by Erotemic** [scikit-image/scikit-image#3347]
## Description
Matplotlib's pyplot module is tricky to work with because if you have some backend preference you have to call matplotlib.use before you import matplotlib.pyplot, otherwise it will cause an error. Ultimately this is an issue with matplotlib, because you have to be very cognistent of where you import it so any calls to `use` happen before you import pyplot. 

This is where scikit-image comes in. If you `import skimage.io`, you implicitly import the matplotlib plugins which import matplotlib.pyplot. Thus for those of us using matplotlib we now have to be careful of where we (1) import matplotlib and now (2) import skimage.io as well. To demonstrate the issue, I'll paste in a minimal snippet of code that causes an error

## MWE

```python
import skimage.io
import matplotlib as mpl
mpl.use('Agg')
```

```
test.py:3: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'Qt5Agg' by the following code:
  File "test.py", line 1, in <module>
    import skimage.io
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 95, in reset_plugins
    _load_preferred_plugins()
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 75, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 87, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 258, in use_plugin
    _load(name)
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 302, in _load
    fromlist=[modname])
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/skimage/io/_plugins/matplotlib_plugin.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/home/joncrall/venv3.6/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  mpl.use('Agg')
```

## Proposal for improvement

I think it would be desirable if this did not fail. It would make working with matplotlib easier because the developer would only need to keep track of the pyplot import. 

This issue can be resolved by changing skimage/io/_plugins/matplotlib_plugin.py such that all functions that use `plt` import it inside the function. Then instead of having to call `mpl.use` before importing skimage, you simply have to call it before calling one of skimage's matplotlib plugin functions, which makes much more sense. Additionally we would likely need to change lines 203 and 204 from this form 

```python
imread = plt.imread
```

to this form (which admittedly is a tad more ugly and has some loss of usefulness when you call help(imread), but I think is ultimately better than the alternative) 

```python
def imread(*args, **kw):
    """Wrapper around matplotlib.pyplot.imread """
    from matplotlib import pyplot as plt
    return plt.imread(*args, **kw)
``` 

## Version info
```
In [2]: skimage.__version__
Out[2]: '0.14.0'

In [3]: import matplotlib 
In [4]: matplotlib.__version__
Out[4]: '2.2.2'
```

**Comment by hmaarrfk** [comment]
Thank you for the detailed report!

This was fixed in this PR https://github.com/scikit-image/scikit-image/pull/3243

I think @jni wants to release 0.14.1 *soonish*

Lets keep this issue the fix is backported.

**Comment by jni** [comment]
Merged. Thanks @Erotemic! Hopefully the fix will be released very soon (we have another critical bug fix that needs backporting also), but you can avoid this problem temporarily by installing from master or from the v0.14.x branch.
