### ISSUE TITLE
Compilation failled on an unknown error for skimage._shared.geometry

### ISSUE THREAD

**Issue by VGib** [scikit-image/scikit-image#3350]
## Description
Compilation failed, from archlinux aur repository on an unknown error

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

It seems to be difficult to reproduce, since this should involve my configuration. I used the archlinux aur PKGBUILD to compile and falled on this exception:

building 'skimage._shared.geometry' extension
compiling C sources
C compiler: gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC

creating build/temp.linux-x86_64-3.7/skimage
creating build/temp.linux-x86_64-3.7/skimage/_shared
compile options: '-I/usr/lib/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c'
gcc: skimage/_shared/geometry.c
gcc: error: .7/site-packages/numpy/core/include: Aucun fichier ou dossier de ce type
gcc: error: .7m: Aucun fichier ou dossier de ce type
gcc: error: .7/site-packages/numpy/core/include: Aucun fichier ou dossier de ce type
gcc: error: .7m: Aucun fichier ou dossier de ce type
error: Command "gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c skimage/_shared/geometry.c -o build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o -MMD -MF build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o.d" failed with exit status 1
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

In english: Aucun fichier ou dossier de ce type => no file or folder of this type.

Unfortunally, I don't what kind of file or folder he's complaining, as I'm not a python expert.

Everything seems to be installed, cython is for sure.

Can someone help me ?

Thanks

**Comment by VGib** [comment]
The current version is 14.0 , I did install 13

**Comment by hmaarrfk** [comment]
Hi @VGib, It seems that you are trying to us python 3.7.

How did you install python 3.7? Currently, it doesn't seem that scikit-image has pip packages for python 3.7.

I would recommend (since you mentioned you aren't a python expert) one of:
1. Use python 3.6.
2. Use conda and conda-forge. It seems conda-forge compiled a package for python 3.7.

Are those two a possibility for you? That would be the easiest way.

FYI, it is complaining that it can't find numpy headers. did you install numpy before compilation?

**Comment by VGib** [comment]
Thanks,

that's what I was suspecing. Unfortunatelly, I'm using paperwork and rebuild all package for python 3.7 except this one. (I install python from archilinux repository extra)
 
I'll wait until this package is compatible, or the application maintener switch.

This python upgrade (not as bad as the python 2.7 -> 3.0 ) sucks with the aur package repository. Every packages need to be rebuild, because of the /usr/lib/python3.6 directory ....

Either way, I'll wait.

Thanks

**Comment by VGib** [comment]
Yes I did install numpy ....

**Comment by hmaarrfk** [comment]
Quel est le resultat de
```
ls -lah I/usr/lib/python3.7/site-packages/numpy/core/include
```
et 
```
ls -lah /usr/include/python3.7m
```

**Comment by VGib** [comment]
ls -lah I/usr/lib/python3.7/site-packages/numpy/core/include
/usr/bin/ls: impossible d'accéder à 'I/usr/lib/python3.7/site-packages/numpy/core/include': Aucun fichier ou dossier de ce type

ls -lah /usr/include/python3.7m
total 1004K
il y a beaucoup de fichiers
get
[include_python.txt](https://github.com/scikit-image/scikit-image/files/2284085/include_python.txt)
[pacaman_ql_numpy.txt](https://github.com/scikit-image/scikit-image/files/2284087/pacaman_ql_numpy.txt)

Je t'es ajouté la liste des fichiers installé avec le package numpy.

Du coup je réouvre.

merci pour ton coup de main

**Comment by hmaarrfk** [comment]
Is the a package like numpy-3.7 dev? It seems that the Pac-Man ql command
said that the package included the “ numpy include files”

**Comment by hmaarrfk** [comment]
ls -lah I/usr/lib/python3.7/site-packages/numpy/core/include

needs to be there hahhaa

**Comment by VGib** [comment]
I reinstall the python-numpy package, now there here:

PS /tmp> ls /usr/lib/python3.7/site-packages/numpy/core/include/numpy/
arrayobject.h   __multiarray_api.h  ndarraytypes.h                npy_1_7_deprecated_api.h  npy_cpu.h        npy_math.h               _numpyconfig.h  oldnumeric.h   ufuncobject.h
arrayscalars.h  multiarray_api.txt  _neighborhood_iterator_imp.h  npy_3kcompat.h            npy_endian.h     npy_no_deprecated_api.h  numpyconfig.h   __ufunc_api.h  utils.h
halffloat.h     ndarrayobject.h     noprefix.h                    npy_common.h              npy_interrupt.h  npy_os.h                 old_defines.h   ufunc_api.txt

still same mistake.

We agree the I before, it's just an option for the path. The true path is /usr/lib/python3.7/site-packages/numpy/core/include/numpy/ ?

Regards,

VGib

**Comment by hmaarrfk** [comment]
Python should set the path correcctly for. Maintenant que le dossier
` gcc: error: .7/site-packages/numpy/core/include: Aucun fichier ou dossier de ce type` existe, cette erreur ne devrais plus se passer. 

Peux-tu me montrer la nouvelle erreur?

**Comment by VGib** [comment]
exactement la même:
building 'skimage._shared.geometry' extension
compiling C sources
C compiler: gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC

creating build/temp.linux-x86_64-3.7/skimage
creating build/temp.linux-x86_64-3.7/skimage/_shared
compile options: '-I/usr/lib/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c'
gcc: skimage/_shared/geometry.c
gcc: error: .7/site-packages/numpy/core/include: Aucun fichier ou dossier de ce type
gcc: error: .7m: Aucun fichier ou dossier de ce type
gcc: error: .7/site-packages/numpy/core/include: Aucun fichier ou dossier de ce type
gcc: error: .7m: Aucun fichier ou dossier de ce type
error: Command "gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c skimage/_shared/geometry.c -o build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o -MMD -MF build/temp.linux-x86_64-3.7/skimage/_shared/geometry.o.d" failed with exit status 1
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

**Comment by hmaarrfk** [comment]
Dans mon système:
```
➤ which python                                                                                     (owl) 
/home/mark/miniconda3/envs/owl/bin/python

➤ python -c 'import numpy; print(numpy.get_include())'                                             (owl) 
/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/numpy/core/include

mark@markowl-X10SRA:~/git
➤ ls -lah /home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/numpy/core/include            (owl) 
total 12K
drwxrwxr-x 3 mark mark 4.0K Aug 10 15:22 ./
drwxrwxr-x 6 mark mark 4.0K Aug 10 15:22 ../
drwxrwxr-x 2 mark mark 4.0K Aug 10 15:22 numpy/
mark@markowl-X10SRA:~/git
➤ ls -alh /home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/numpy/core/include/numpy      (owl) 
total 388K
drwxrwxr-x 2 mark mark 4.0K Aug 10 15:22 ./
drwxrwxr-x 3 mark mark 4.0K Aug 10 15:22 ../
-rw-rw-r-- 3 mark mark  164 Jul 30 20:51 arrayobject.h
-rw-rw-r-- 3 mark mark 3.5K Jul 30 20:51 arrayscalars.h
-rw-rw-r-- 3 mark mark 1.9K Jul 30 20:51 halffloat.h
-rw-rw-r-- 3 mark mark  60K Jul 30 20:51 __multiarray_api.h
-rw-rw-r-- 3 mark mark  55K Jul 30 20:51 multiarray_api.txt
-rw-rw-r-- 3 mark mark  12K Jul 30 20:51 ndarrayobject.h
-rw-rw-r-- 3 mark mark  64K Jul 30 20:51 ndarraytypes.h
-rw-rw-r-- 3 mark mark 1.9K Jul 30 20:51 _neighborhood_iterator_imp.h
-rw-rw-r-- 3 mark mark 6.7K Jul 30 20:51 noprefix.h
-rw-rw-r-- 3 mark mark 4.5K Jul 30 20:51 npy_1_7_deprecated_api.h
-rw-rw-r-- 3 mark mark  13K Jul 30 20:51 npy_3kcompat.h
-rw-rw-r-- 3 mark mark  37K Jul 30 20:51 npy_common.h
-rw-rw-r-- 3 mark mark 3.8K Jul 30 20:51 npy_cpu.h
-rw-rw-r-- 3 mark mark 2.3K Jul 30 20:51 npy_endian.h
-rw-rw-r-- 3 mark mark 3.4K Jul 30 20:51 npy_interrupt.h
-rw-rw-r-- 3 mark mark  19K Jul 30 20:51 npy_math.h
-rw-rw-r-- 3 mark mark  567 Jul 30 20:51 npy_no_deprecated_api.h
-rw-rw-r-- 3 mark mark  817 Jul 30 20:51 npy_os.h
-rw-rw-r-- 3 mark mark 1010 Jul 30 20:51 _numpyconfig.h
-rw-rw-r-- 3 mark mark 1.2K Jul 30 20:51 numpyconfig.h
-rw-rw-r-- 3 mark mark 6.2K Jul 30 20:51 old_defines.h
-rw-rw-r-- 3 mark mark  708 Jul 30 20:51 oldnumeric.h
-rw-rw-r-- 3 mark mark  12K Jul 30 20:51 __ufunc_api.h
-rw-rw-r-- 3 mark mark 6.0K Jul 30 20:51 ufunc_api.txt
-rw-rw-r-- 3 mark mark  13K Jul 30 20:51 ufuncobject.h
-rw-rw-r-- 3 mark mark  729 Jul 30 20:51 utils.h
```


C'est étrange aussi le fait que même l'ancient package de arch utilisait le [même command](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-scikit-image#n60)

Peut-être ceci peut aider? https://github.com/jwilk/python-djvulibre/issues/5


Honestly though, having gone through this trouble with fedora, I have to say that the conda packaging system, and more so conda-forge is awesome at automatically building things when there are upgrades.
At one point, maybe not now, but later, you will use some kind of virtual env and conda is a great choice for scientific python.

@jni, are we planning on releasing a pip package for 3.7 with 0.14.1?

**Comment by VGib** [comment]
Non tout est bon:

```PS /tmp> which python
/usr/bin/python
```

Je pense que si je met la main sur le bin, je vais créer un PKGBUILD pour l'installer directement depuis le bin pour mon architecture ....

**Comment by hmaarrfk** [comment]
What does `/usr/bin/python` link to? (Un  accent grave fait du code "inline")

**Comment by VGib** [comment]
```
PS /tmp> ls -la /usr/bin/python
lrwxrwxrwx 1 root root 7 15 juil. 12:44 /usr/bin/python -> python3
```

**Comment by hmaarrfk** [comment]
et python3? I don't think it matters because it was able to find the correct numpy.

est-ce que ceci est-encore vrais?
```
PS /tmp> ls /usr/lib/python3.7/site-packages/numpy/core/include/numpy/
arrayobject.h __multiarray_api.h ndarraytypes.h npy_1_7_deprecated_api.h npy_cpu.h npy_math.h _numpyconfig.h oldnumeric.h ufuncobject.h
arrayscalars.h multiarray_api.txt _neighborhood_iterator_imp.h npy_3kcompat.h npy_endian.h npy_no_deprecated_api.h numpyconfig.h __ufunc_api.h utils.h
halffloat.h ndarrayobject.h noprefix.h npy_common.h npy_interrupt.h npy_os.h old_defines.h ufunc_api.txt
```

**Comment by VGib** [comment]
toujours,

```
PS /tmp> ls /usr/lib/python3.7/site-packages/numpy/core/include/numpy/
arrayobject.h   __multiarray_api.h  ndarraytypes.h                npy_1_7_deprecated_api.h  npy_cpu.h        npy_math.h               _numpyconfig.h  oldnumeric.h   ufuncobject.h
arrayscalars.h  multiarray_api.txt  _neighborhood_iterator_imp.h  npy_3kcompat.h            npy_endian.h     npy_no_deprecated_api.h  numpyconfig.h   __ufunc_api.h  utils.h
halffloat.h     ndarrayobject.h     noprefix.h                    npy_common.h              npy_interrupt.h  npy_os.h                 old_defines.h   ufunc_api.txt
```

**Comment by hmaarrfk** [comment]
Quesl est le resultat de 
```
python setup.py install --no-deps
```

**Comment by VGib** [comment]
no-deps is unknow:
```
PS /tmp/python-scikit-image/src/scikit-image-0.14.0> python setup.py install --no-deps
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --no-deps not recognized
```

**Comment by hmaarrfk** [comment]
gah,, pip vs setup....

du dossier de scikit-image

```
pip install . --no-deps --verbose
```

**Comment by VGib** [comment]
```
PS /tmp/python-scikit-image/src/scikit-image-0.14.0/skimage> python setup.py install --no-deps
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    config = configuration(top_path='').todict()
  File "setup.py", line 9, in configuration
    config.add_subpackage('_shared')
  File "/usr/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
    caller_level = 2)
  File "/usr/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1003, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 916, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "/usr/lib/python3.7/site-packages/numpy/compat/py3k.py", line 122, in npy_load_module
    return importlib.machinery.SourceFileLoader(name, fn).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./_shared/setup.py", line 5, in <module>
    from skimage._build import cython
ModuleNotFoundError: No module named 'skimage'
```

I don't have pip installed, is this a problem ?

**Comment by hmaarrfk** [comment]
yeah you need pip and probably wheel.

**Comment by hmaarrfk** [comment]
maybe...

**Comment by hmaarrfk** [comment]
wait sorry, maybe you are 1 directory in too deep. I didn't explain well.

`python setup.py install --no-deps` from the directory where you see

```
mark@markowl-X10SRA:~/g/scikit-image|deprecators✓
➤ ls 
asv.conf.json     doc/            README.md               skimage/
benchmarks/       INSTALL.rst     RELEASE.txt             temp.tif
build/            LICENSE.txt     requirements/           TODO.txt
conftest.py       Makefile        requirements.txt        tools/
CONTRIBUTING.txt  MANIFEST.in     scikit_image.egg-info/  viewer_examples/
CONTRIBUTORS.txt  __pycache__/    setup.cfg
dist/             pyproject.toml  setup.py
```

I might have a few more files.

**Comment by VGib** [comment]
I installed the both of them, still don't work 

With pip I may be able to create a PKGBUILD which install it when the python 3.7 package will be available
This is cheating, but seems to be the best solution

**Comment by hmaarrfk** [comment]
Yeah, I'm not sure. I would be curious to see the output of the command

```
python setup.py install --no-deps
```
from the scikit-image directory (the one with the .git file) one last time

**Comment by VGib** [comment]
```
PS /tmp/python-scikit-image/src/scikit-image-0.14.0/skimage> python setup.py install --no-deps
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    config = configuration(top_path='').todict()
  File "setup.py", line 9, in configuration
    config.add_subpackage('_shared')
  File "/usr/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
    caller_level = 2)
  File "/usr/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 1003, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib/python3.7/site-packages/numpy/distutils/misc_util.py", line 916, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "/usr/lib/python3.7/site-packages/numpy/compat/py3k.py", line 122, in npy_load_module
    return importlib.machinery.SourceFileLoader(name, fn).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./_shared/setup.py", line 5, in <module>
    from skimage._build import cython
ModuleNotFoundError: No module named 'skimage'
```

**Comment by VGib** [comment]
same for the last source

**Comment by hmaarrfk** [comment]
Are you sure you in the correct directory, it seems you need to be 1 directory up. 

The stack trace says the top level file is: https://github.com/scikit-image/scikit-image/blob/master/skimage/setup.py#L45

But you should be calling this file: https://github.com/scikit-image/scikit-image/blob/master/setup.py

**Comment by VGib** [comment]
When I call at the root git directory, I have the error message 
`error: option --no-deps not recognized`

**Comment by VGib** [comment]
I launched the command, and it failled
[pip_output.txt](https://github.com/scikit-image/scikit-image/files/2287745/pip_output.txt)
[pip_error.txt](https://github.com/scikit-image/scikit-image/files/2287746/pip_error.txt)

I need to tell you, I don't compile as root. I won't install package in /usr/lib/... with pip.

If I were a python developer, I would. But, I don't want to have packages conflict with archlinux package manager.

Regards.

**Comment by hmaarrfk** [comment]
yeah, i'm not sure, i was just able to compile it on Ubuntu in a conda python 3.7 environment.

That said, I'm on master. are you on a particular branch?

Make sure you have all the listed dependencies installed: http://scikit-image.org/docs/stable/install.html#id2

**Comment by hmaarrfk** [comment]
To conclude, I really don't know what is wrong. It could be a few things:

  1. arch compiler is too new, maybe there is a conflict in the order of the compilation options.
  2. Something weird with your include paths, though I don't think so.
  3. pip seems to be using it's own version of numpy as well. So it isn't with your numpy installation

But finally, you you aren't too pro with python, I would really not venture down the rabbit hole of trying to compile things yourself. Python 3.7 is REALLY new, and people are going to transition to it, but there is an order that things need to be compiled in that will cause a general delay.

My suggestion is really to use `conda` to install scikit-image in a way that doesn't conflict with your system python. The general consensus is that system python is for the system, not for your work analysis. Stick to python3.6 too, unless you want to run into missing packages for 3.7. I just tried to install jupyter-lab for example, and it used python3.6 automatically.

**Comment by VGib** [comment]
You're right. The problem is that archlinux has already switch to python 3.7. So I have no choice.

I know the risk to use an advance distribution, so I accept them.

I'll try to get something with conda and PKGBUILD. So I will do as usual, I'll try to manage.

Anyway, thanks for the time.
