### ISSUE TITLE
DOC: Broken link to Gabor tutorial

### ISSUE THREAD

**Issue by michaelaye** [scikit-image/scikit-image#3351]
## Description
On this page:

http://scikit-image.org/docs/dev/api/skimage.filters.html#skimage.filters.gabor_kernel

the link to the Gabor tutorial:

http://mplab.ucsd.edu/tutorials/gabor.pdf

is broken.

**Comment by sciunto** [comment]
It is still visible on the internet archive: https://web.archive.org/web/20180127125930/http://mplab.ucsd.edu/tutorials/gabor.pdf

**Comment by hmaarrfk** [comment]
Maybe we need to mirror it?

**Comment by sciunto** [comment]
@hmaarrfk It's something I wondered but regarding the copyright, I don't know if we want to do that...

**Comment by hmaarrfk** [comment]
Yeah....
