### ISSUE TITLE
DOC: Direct user questions to https://forum.image.sc (add link to project README)

### ISSUE THREAD

**Issue by GenevieveBuckley** [scikit-image/scikit-image#3355]
## Description
Now that the Scientific Community Image Forum exists at https://forum.image.sc/, scikit-image should have a link to it in the README (a good first issue!)

Very likely this also means we should remove the StackOverflow badge & link, so there is one clear preferred path for questions. That will probably mean less duplication (see [#1](https://forum.image.sc/t/image-gets-rescaling-after-normalize-using-opencv-and-scikit-image/19065), [#2](https://stackoverflow.com/questions/51850688/image-gets-rescaling-after-normalize-using-opencv-and-scikit-image), [#3](https://github.com/scikit-image/scikit-image/issues/3352)) for both question askers and answerers.
It would be a step towards alignment with the Scientific Community Image Forum [policy discussed here](https://forum.image.sc/t/formal-policy-for-project-to-be-a-software-partner/18834):
> A) the organization links to the forum in its documentation regarding how users should seek support and/or discussion; and 
> B) it does not promote additional, separate, project-specific discussion channels more prominently than this forum.

**Comment by soupault** [comment]
👍 . Thanks for sharing the link!

**Comment by stefanv** [comment]
Let's please wait for discussion on using the new forum to complete before merging.

**Comment by emmanuelle** [comment]
This new forum is interesting but StackOverflow has been there for a long time and has been very useful to the community. I would suggest to keep SO and add the new forum. 

Who is behind this initiative for the new forum?

**Comment by jni** [comment]
Curtis Rueden (Fiji) and the CellProfiler team (specifically Jeanelle Ackerman from what I can gather) started the forum.

My two cents: I think we should go all in. Here's my pitch:

- Our current mailing list situation is very poor. Specifically, it is not being indexed by Google, so everything said on the mailing list is effectively being cast down into a black hole.
- StackOverflow is a good place for advanced users but it is not well-regarded as a beginner-friendly forum. The Fiji forum on the other hand has always been very friendly and useful to image analysis newbies.
- in the same vein, I think it would be good publicity and exposure for scikit-image if skimage-based answers are intermingled with Fiji ones.
- The new forum is built on Discourse which is fully open source software and which I've found quite nice to use. It would be possible to configure it to work as a mailing list, as detailed by Matt McCormick [here](https://forum.image.sc/t/formal-policy-for-project-to-be-a-software-partner/18834/14).
- We would have more say in the direction of the forum if we take our role there wholeheartedly. For example, I have argued that commercial, closed-source software should not be featured in the forum, but I don't have much of a voice until we formally adopt the forum as our preferred Q&A platform. Curtis has also indicated that it *might* be possible to transfer our archives to it. I get the impression that they would make efforts to do this if it was a deal-breaker for us.

I will continue to subscribe to the scikit-image tag on SO. But the question is what we *promote*, on our home page and e.g. in lectures and tutorials for scikit-image. I think the forum is a good place.

Perhaps this would be a good thing to discuss in our core meeting next week.

**Comment by sciunto** [comment]
@scikit-image/core I propose to reopen the debate and that we take a decision on this issue soon.

I'm +1 with @emmanuelle.

**Comment by jni** [comment]
We already have both the forum and SO both at the top of the readme and on the website, and things have been working quite smoothly, so I'm going to just close this as resolved! =)

**Comment by sciunto** [comment]
I didn't notice :)
