### ISSUE TITLE
Redirect www.scikit-image.org ?

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3372]
Can it be redirect it to `scikit-image.org` ?

I spent 10 minutes the other day thinking my internet connection was down. 🐴

**Comment by soupault** [comment]
👍. This is more related to https://github.com/scikit-image/scikit-image-web, though.

**Comment by sciunto** [comment]
@hmaarrfk Use this website next time: http://downforeveryoneorjustme.com/
