### ISSUE TITLE
Performance improvement for `scikit-image/skimage/feature/_texture.pyx`

### ISSUE THREAD

**Issue by abTest-123** [scikit-image/scikit-image#3377]
## Description
When calculating GLCM using the _glcm_loop, the offset pixel calculation can be optimized slightly.
In lines 68-69 the pixel offset value is calculated per each element, those offset values are constant and require both the calculation of a trigonometric function and casting to a different variable type.
By calculating the rowOffset and columnOffset ouside of the loop those executions need only happen once.
                        row = r + <int>round(sin(angle) * distance)
                        col = c + <int>round(cos(angle) * distance)

Some further optimization can be done by using the offset size(s) to reduce the number of iterations by changing the range of the for loops in lines 63 and 64.
In my opinion it would be wiser to change the convention from distance and angle to  rowOffset and columnOffset, but that does not conform with the standard notations.

**Comment by soupault** [comment]
@abTest-123 sure! Feel free to submit a Pull Request with the proposed changes. I guess you might need to also measure the performance benefit in order to convince the other team members.

**Comment by abTest-123** [comment]
Thank you for suggesting that @soupault. I tried to test it locally and got stuck when needed to compile the .pyx code, this is out of my pythonic comfort zone.

**Comment by hmaarrfk** [comment]
If you want to expand your comfort zone, try giving this a read:

http://scikit-image.org/docs/dev/contribute.html

You might need a c compiler on windows. Visually studio 2015 or 2017 is fine

**Comment by jni** [comment]
@abTest-123 great catch! See #3378 for the fix, including benchmark measurements.

**Comment by abTest-123** [comment]
Thanks @hmaarrfk and @jni , Looking forward to test it!
