### ISSUE TITLE
Building the docs on CircleCI ?

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#3393]
For pull requests modifying the documentation (gallery examples, user guide, API), the only way to check the result at the moment is to fetch the branch and build the branch locally (which can be a pain when you want to review quickly a PR). Another possibility could be to use CircleCI, and to look at the html pages of the doc on CircleCI. scikit-learn uses CircleCI for this purpose, for example. What do you think?

**Comment by soupault** [comment]
See https://github.com/scikit-image/scikit-image/issues/2269 :trollface:

**Comment by jni** [comment]
@soupault @emmanuelle :joy::joy::joy::joy::joy: I think this is the most closely duplicated issue I have ever seen. =D I'm going to close as a duplicate. Personally, I think it's 100% necessary, though.
