### ISSUE TITLE
Error when converting polygon coordinates to mask

### ISSUE THREAD

**Issue by MalikAsif** [scikit-image/scikit-image#3411]
## Description
[Please provide a general introduction to the issue/proposal.]

[If reporting a bug, attach the entire traceback from Python.]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by jni** [comment]
@MalikAsif 

Here's a few links showing how to share code on GitHub or other help sites, as it's completely unreadable on the title:
- https://guides.github.com/features/mastering-markdown/
- https://help.github.com/articles/basic-writing-and-formatting-syntax/
- https://help.github.com/articles/about-writing-and-formatting-on-github/

Most importantly, we can't help you without being able to reproduce the error you're seeing. See this StackOverflow article on how to write a minimum, complete, verifiable example:
- https://stackoverflow.com/help/mcve

In your case, the code (below) seems correct to me, so I imagine you are calling it incorrectly, or you are having install issues with scikit-image... Impossible to know without the full text of the error.

```python
def poly2mask(vertex_row_coords, vertex_col_coords, shape):
    fill_row_coords, fill_col_coords = draw.polygon(vertex_row_coords, vertex_col_coords, shape)
    mask = np.zeros(shape, dtype=np.bool)
    mask[fill_row_coords, fill_col_coords] = True
    return mask
```

**Comment by MalikAsif** [comment]
@jni  Thanks, got it,
