### ISSUE TITLE
How do I suppress warnings for future deprecation?

### ISSUE THREAD

**Issue by muepsilonpsi** [scikit-image/scikit-image#3436]
I am running skimage 0.14 on python3.6 on Ubuntu. How do I suppress these incessant warnings for future deprecation?

```
/home/my/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/home/my/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
/home/my/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/home/my/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
/home/my/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/home/my/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "

```

**Comment by hmaarrfk** [comment]
Can you show us the calling code? You should likely specify some kwargs, maybe `mode` in the calling function.

Maybe we should use the `stacklevel` parameter to hint at where these parameters should be specified?

**Comment by hmaarrfk** [comment]
@muepsilonpsi I'm sorry you are dealing with strange warnings. I opened a PR that should hopefully help this for future users, https://github.com/scikit-image/scikit-image/pull/3438 , although it will only be out in 0.14.2 or 0.15.0 :/

As for you, this is a BIG UGLY HACK, but I think it might help you. You could:

1. Open the file `/home/my/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py`.
2. On lines 105 and 110, add the parameter `stacklevel=3` to the calls of `warn`
3. Restart your python instance, and now the warnings should point to **your** code as opposed to the internal one.

Generally, I would not advise you editing files in `/home/my/anaconda3`, so be very careful. In this case it might be OK.

**Comment by sliawatimena** [comment]
@hmaarrfk 
Line 105 warn ("The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.")

Where to put stacklevel=3, is it before or after the string? 
Thanks.

**Comment by mlaradji** [comment]
@sliawatimena After the string, since, in Python, keyword arguments must be specified after positional arguments. So, you can change line 105 to:
```
warn ("The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.", stacklevel=3)
```

**Comment by SRooj** [comment]
for anti_aliasing warning: adding two more attributes to skimage.transform.resize(), solves the issue
transform.resize(....., ......., ......,anti_aliasing=True, anti_aliasing_sigma=None)

**Comment by hmaarrfk** [comment]
Right, you need to specify all the parameters that will change behavior between versions.

@scikit-image/core if anybody would like to review
https://github.com/scikit-image/scikit-image/pull/3467

I think it would help the usability of the package. It probably won't make it for 0.15.0, but maybe for 0.15.1

**Comment by mcamila777** [comment]
I solved it by:

pip install --upgrade scikit-image

**Comment by siryne** [comment]
i solved it by : 
sudo pip3 install --upgrade scikit-image

**Comment by hmaarrfk** [comment]
using the command `sudo pip3` repeatedly is almost guaranteed to break your system 


For your sake, please consider using virtual environment
https://realpython.com/python-virtual-environments-a-primer/

or at the very least,

```
pip3 install --user scikit-image
```

**Comment by siryne** [comment]
well I didn't know about that. 
Thank you hmaarrfk.

**Comment by hmaarrfk** [comment]
glad to help. One of the most challenging things about python is knowing what tools you should use.

Best of luck!

**Comment by matteobsu** [comment]
> 
> 
> I solved it by:
> 
> pip install --upgrade scikit-image

Worked for me too! Thanks!

**Comment by sciunto** [comment]
I close this issue (See PR #3467). Thanks for reporting.
