### ISSUE TITLE
open peak_local_max TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by apiszcz** [scikit-image/scikit-image#3464]
The example given [here](http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_peak_local_max.html) works fine.
On a larger image I am testing, the following error message occurs.

(Pdb) coordinates = peak_local_max(b1, min_distance=pixelseparation, num_peaks=n, indices=True)
*** TypeError: slice indices must be integers or None or have an __index__ method

- [ ] Operating system and version, windows 10
- [ ] Python version, 3.5
- [ ] scikit-image version (run `skimage.__version__`), 0.14.1

SOLUTION : rescale the input data to 0.0 to 1.0.

**Comment by hmaarrfk** [comment]
Fyi. There is some talk about having a preserve range argument to many of the functions.

**Comment by apiszcz** [comment]
I need to read the documentation again, I'm guessing I missed it. Thanks for the reply!
Preservation would be good, but not needed in my case, it would save 'memory' with large images.
I will index back into the original data.

**Comment by hmaarrfk** [comment]
Alright, seems like peak_local_max has enough parameters for your to play with to get the normalization done correctly.

Normalizing huge matricies isn't free, so maybe you'll find them useful.

Goodluck
