### ISSUE TITLE
peak_local_max min_distance not working?

### ISSUE THREAD

**Issue by apiszcz** [scikit-image/scikit-image#3465]
peak_local_max does not appear to be separating the peaks by minimum distance.
In this example min_distance=277, num_points=3, indices=True
skimage = 0.14.1
python 3.5
Windows 10

In this example the points are separated by 3 pixels vertical, and 1 pixel minimum adjacent.

![image](https://user-images.githubusercontent.com/1430861/46687929-1fac0680-cbca-11e8-9c3c-46b27ae8196a.png)

**Comment by hmaarrfk** [comment]
Thank you for the bug report. That definitely looks strange.
Can you please post the full code that would reproduce this?

This might be challenging to do so here are some tips:

1. Try to slice your array into a small array that reproduces the problem.
2. Once the array is small enough, numpy should display it all on the repr.
3. Put the output of the repr into a `np.asarray()` call, and try to reproduce the problem again with that matrix. 

You could also save your matrix to a file, but making the smalest example that reproduce the bug is very helpful. That would really help us get to the bottom of the problem!

When posting code, please try to use tripple backticks "```"
See the link under the editor for more help.
![image](https://user-images.githubusercontent.com/90008/46690329-01490980-cbd0-11e8-991e-722c93116297.png)

**Comment by apiszcz** [comment]
The sample file/data is 18MB can I post it somewhere? I converted to greyscale and still have same behavior.  I am seeing this issue with multiple images it is not an isolated problem.

```
    ds = rasterio.open(ipath)
    b1 = ds.read(1)

    b2=np.interp(b1,(b1.min(),b1.max()),(0.0,1.0)) # scale input to 0 to 1
    crds = peak_local_max(b2,
                          min_distance=554,
                          num_peaks=3,
                          indices=True)

```

**Comment by hmaarrfk** [comment]
I understand your full dataset is very large. I don't think the best solution is to share it as is.

What if you select only a very small portion of the data? Say a 20x20 region around the problematic area.

Can you still recreate the problem?

If you can do that, we may:
1. Be able to solve the problem.
2. Integrate that small piece of data into the tests so the problem never shows up again.

**Comment by apiszcz** [comment]
[test_array.gz](https://github.com/scikit-image/scikit-image/files/2461828/test_array.gz)

Here is a small section, it produces another incorrect result. The highest value peaks are near the center of the image

![image](https://user-images.githubusercontent.com/1430861/46692363-13797680-cbd5-11e8-9dec-6076fc135730.png)

**Comment by hmaarrfk** [comment]
@apiszcz I really want to thank you for sharing with us this data. 

For example, running the little bit of information you gave me gives an output that is consistent with the documetnation:

```python
import numpy as np
from skimage.feature import peak_local_max
a = np.loadtxt('test_array.gz')
i = peak_local_max(a, min_distance=28,
                   num_peaks=3, indices=True)

print(np.max(a))

for r, c in i:
    print("a[{r}, {c}] = {value}".format(r=r, c=c, value=a[r, c]))
```
(P.S. next time, if possible, please provide this kind of code)

output
```
255.0
a[418, 477] = 255.0
a[411, 463] = 255.0
a[411, 454] = 255.0
```

The values at the 3 coordinates are local maximas.

According to the [documentation](http://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.peak_local_max):
> If peaks are flat (i.e. multiple adjacent pixels have identical intensities), the coordinates of all such pixels are returned.

```

>>> a[411:419, 454:464]
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```

Seems like your whole array is flat.

**Comment by apiszcz** [comment]
Hmm..

(Pdb) b1
array([[255., 255., 255., ..., 181., 180., 186.],
       [255., 255., 255., ..., 188., 192., 255.],
       [255., 255., 255., ..., 198., 198., 255.],
       ...,
       [177., 181., 186., ..., 255., 255., 255.],
       [179., 180., 183., ..., 255., 255., 255.],
       [180., 180., 181., ..., 255., 255., 255.]], dtype=float32)

**Comment by hmaarrfk** [comment]
@apiszcz what difference am I supposed to see?

You really won't insult me if you spell it out word for word. Your examples don't include any import statements, nor is it clear if it is important to be in `pdb`.

**Comment by apiszcz** [comment]
My issue was caused by rescaling in one case, and NOT rescaling in another.
I'm guessing others may run into the same issue.
I am starting to understand the parameters now, getting expected output.
Thank you.

**Comment by hmaarrfk** [comment]
I don't entirely understand but I suspect it has to do with rounding errors
for floating point numbers?

**Comment by hmaarrfk** [comment]
@apiszcz has this conversation solved your issue? If so, could you please close this issue?

Let me know if you have any more questions.
