### ISSUE TITLE
Issue with marching cube example in gallery

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#3466]
## Description

I just noticed that... http://scikit-image.org/docs/dev/auto_examples/edges/plot_marching_cubes.html#sphx-glr-auto-examples-edges-plot-marching-cubes-py

**Comment by robroooh** [comment]
is anyone currently working on this? I would like to work on this issue. it's my first contribution.

**Comment by sciunto** [comment]
Nobody identified :) Welcome and please go ahead!

**Comment by soupault** [comment]
Closed via #3474

**Comment by stefanv** [comment]
Does anyone else notice the "Note" at the top of the examples now? Annoying!
