### ISSUE TITLE
Doc suggestion: add sphinx-copybutton to the docs

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3482]
See the sphinx-copybutton README for details:

https://github.com/choldgraf/sphinx-copybutton

**Comment by thoo** [comment]
I just submitted the PR. It should look like this. ![](https://farm5.staticflickr.com/4861/45684567951_9f26f23455_b.jpg )

**Comment by thoo** [comment]
@jni  Could you review my PR ? Thanks.

**Comment by soupault** [comment]
Added in #3530
