### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by raaj043** [scikit-image/scikit-image#3487]
## Description
[Reading grey scale images]
Please update the documentation for reading grey scale images. The document shows 'as_gray=True', where as it should be 'as_grey=True'. I hope this is a spell mistake.

Thanks,
Basavaraj Hampiholi

**Comment by jni** [comment]
@raaj043 as an adopted Australian, I sympathise, but scikit-image has a policy of using US spelling everywhere, so indeed, although it used to be `as_grey`, the correct version going forward is `as_gray=`.
