### ISSUE TITLE
rank windowed_histogram computation of number of bins

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3498]
Should this be converted to an img_as_ubyte first?

https://github.com/scikit-image/scikit-image/blob/27f0de279f089ea15c1cba899a9633bac55bad21/skimage/filters/rank/generic.py#L1043

**Comment by hmaarrfk** [comment]
Maybe
```
    if n_bins is None:
        if image.dtype not in (np.uint8, np.uint16):
            n_bins = img_as_ubyte(image.max()) + 1
        else:
            n_bins = image.max() + 1
```

This kinda breaks tests

**Comment by soupault** [comment]
Uint8 is specified in the docstring - https://github.com/scikit-image/scikit-image/blob/27f0de279f089ea15c1cba899a9633bac55bad21/skimage/filters/rank/generic.py#L1006 .
>n_bins = img_as_ubyte(image.max()) + 1
I'd rather raise an error than perform such kind of implicit conversion. 🤔

**Comment by hmaarrfk** [comment]
This was changed in https://github.com/scikit-image/scikit-image/pull/3501
