### ISSUE TITLE
Python language level needs to be upgrade to Py3

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3510]
Cython gives this warning:
```
FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release!
```

Needs to be addressed at least for division.

**Comment by stefanv** [comment]
I started working on this in https://github.com/scikit-image/scikit-image/pull/3513  Feel free to push commits there; there's some issue with importing `mcp`.

**Comment by hmaarrfk** [comment]
I think this was resolved
