### ISSUE TITLE
Want to implement the requested feature - Image Colorization

### ISSUE THREAD

**Issue by Akshaj5** [scikit-image/scikit-image#3526]
Hi, I am new to scikit-image and wanted to implement the requested feature image colorization. If someone can help me?

**Comment by emmanuelle** [comment]
Hi @Akshaj5 where was feature requested? I could not find an issue on colorization.

**Comment by sciunto** [comment]
Here I guess: https://github.com/scikit-image/scikit-image/wiki/Requested-features

**Comment by emmanuelle** [comment]
Ah ok :-). We  should curate this list it was last edited in 2015!!

**Comment by Akshaj5** [comment]
Hi @emmanuelle, can I implement this one or is it already implemented?

**Comment by jni** [comment]
@Akshaj5, others will chime in, but I would consider this feature to be a low priority. In that list, enhanced correlation coefficient would be my top choice. But, as @emmanuelle, really we need to update it with priorities. Unfortunately we don't have the bandwidth right now to do so!

**Comment by Akshaj5** [comment]
@jni Actually I am a final year student and to implement the image colorization and get accepted my pull request on scikit-image is one of my course project.

**Comment by sciunto** [comment]
Being not our top priorities does not mean that we are not interested. If your decision is made, we will be happy to consider your code!

@emmanuelle @jni I put a warning at the top of the wiki page ;)

**Comment by soupault** [comment]
@jni I actually think that having a popular classic colorization algorithm might be useful. Although, only if its fully unsupervised.
A large number of pre-trained CNN models are designed for and trained on RGB-images. I've seen several blogposts saying that fine-tuning of such models on grayscale data (by tiling the image to (*original_shape, 3)) often doesn't work. At the same time, by performing fast and stupid """colorization""" (RGB->HSV, channel jittering, HSV->RGB) one can successfully apply such models to their grayscale data.
P.S. I'm definitely not saying that this feature is a must-have in any sense.

@Akshaj5 submitting a new feature to `scikit-image` almost always comes with the responsibility to maintain and, occasionally, improve own addition. I strongly suggest to keep it in mind. :wink:

**Comment by stefanv** [comment]
> @jni Actually I am a final year student and to implement the image colorization and get accepted my pull request on scikit-image is one of my course project.

Please note that there are never any guarantees that your code will be accepted into scikit-image, so this is not a wise goal to set for a course.  It may also take a significant amount of time to get the code ready for inclusion.  For your course, I suggest you find and solve a technical issue instead; those PRs are very likely to be included, if they are correct.

**Comment by emmanuelle** [comment]
Can I close this issue? I think it was decided that we did not want this feature in scikit-image, eventually.
