### ISSUE TITLE
Segmentation Module functions not found

### ISSUE THREAD

**Issue by SvenVoigt** [scikit-image/scikit-image#3527]
## Description
The issue is that I am getting an error trying to load functions that are in the documentation for the segmentation module.

These functions include checkerboard_level_set, chan_vese, morphological_chan_vese, and morphological_geodesic_active_contour.

The error is:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-10-0628b24570e0> in <module>()
>       1 import skimage.segmentation as seg
> ----> 2 seg.checkerboard_level_set()
>       3 seg.chan_vese()
>       4 seg.morphological_geodesic_active_contour()
> 
> AttributeError: module 'skimage.segmentation' has no attribute 'checkerboard_level_set'

## Way to reproduce
```
import skimage.segmentation as seg
seg.checkerboard_level_set()
seg.chan_vese()
seg.morphological_geodesic_active_contour()
```
Mac OS Sierra 10.12.1
Python=3.6.7
scikit-image=0.14.1

**Comment by hmaarrfk** [comment]
I get (on Linux):
```python
In [1]: import skimage.segmentation as seg 
   ...: seg.checkerboard_level_set() 
   ...: seg.chan_vese() 
   ...: seg.morphological_geodesic_active_contour()                           
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-814ba81d155e> in <module>
      1 import skimage.segmentation as seg
----> 2 seg.checkerboard_level_set()
      3 seg.chan_vese()
      4 seg.morphological_geodesic_active_contour()

TypeError: checkerboard_level_set() missing 1 required positional argument: 'image_shape'
```

**Comment by SvenPVoigt** [comment]
I apologize. I was checking versions in terminal and running on Jupyter but they were not using the same environment.
