### ISSUE TITLE
Port CI from AppVeyor to Azure

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3539]
Azure has more free cores, also does MacOS.

*Added by @soupault :*
- [x] Move https://github.com/scikit-image/scikit-image (https://github.com/scikit-image/scikit-image/pull/3612);
- [ ] Move https://github.com/scikit-image/scikit-image-wheels (https://github.com/scikit-image/scikit-image-wheels/issues/11);
- [ ] Update release instructions in https://github.com/scikit-image/scikit-image/blob/master/RELEASE.txt (remove the entry in https://github.com/scikit-image/scikit-image/blob/master/TODO.txt afterwards);
- [ ] Remove @scikit-image/ci team. Add the members directly in Azure;
- [ ] Review Issues and PR related to AppVeyor.

**Comment by stefanv** [comment]
https://github.com/scipy/scipy/pull/9542

**Comment by stefanv** [comment]
@soupault Were you still going to take this on?

**Comment by soupault** [comment]
@stefanv I'm actually having a training on Azure ecosystem tomorrow :), so yes.
Could you, please, create an Azure DevOps organization in the meanwhile?

**Comment by stefanv** [comment]
Done: https://dev.azure.com/scikit-image/scikit-image

**Comment by soupault** [comment]
@hmaarrfk if you still need manual control over Windows build, please, create a Microsoft account for Azure DevOps.

**Comment by hmaarrfk** [comment]
you know, I have an account and was just tyring to use it this last week. I couldn;t figure out how to link it to my github, especically using tokens. Too complicated .....

**Comment by soupault** [comment]
@hmaarrfk you should ask @stefanv to add you to `scikit-image` Azure organization (https://dev.azure.com/scikit-image/scikit-image) by email. That's how it worked for me.

**Comment by hmaarrfk** [comment]
We'll see how often Azure crashes. I think earlier on, there were many crashes on appveyor and it was literally impossible to get 2 builds in row to completion.

I tried to use Azure for my day job. the conda-smithy scripts moved to it, but I couldn't get my account setup to enable all their automation. I fell back to their older scripts, but I don't know how long that will be OK for.

**Comment by stefanv** [comment]
On Thu, 20 Dec 2018 13:44:19 +0000, Egor Panfilov wrote:
> @hmaarrfk you should ask @stefanv to add you to `scikit-image` Azure
> organization (https://dev.azure.com/scikit-image/scikit-image) by
> email. That's how it worked for me.

Let me know your Microsoft live account and I'll add you.  Egor, you
should also be an owner of the organization?  If not, I can fix that.

**Comment by soupault** [comment]
>Egor, you should also be an owner of the organization?

Judging from the number of buttons I see in UI, most likely, yes :).

**Comment by hmaarrfk** [comment]
We should enable azure for all branches not just master.

It isn't showing up on backports to 0.15

**Comment by soupault** [comment]
FWIW, Azure has Ubuntu 18.04 image now - https://github.com/microsoft/azure-pipelines-image-generation/issues/506#issue-385899472

**Comment by hmaarrfk** [comment]
Yeah. Conda forge now uses azure for all x86 builds.

It also uses docker in docker to customize exactly what image is used for the build machine

**Comment by grlee77** [comment]
closed by #6229 which removed CI on Appveyor (Azure was added in #3612)

**Comment by soupault** [comment]
If I understood correctly from the latest PRs, the complete CI is now done through Azure/GitHub Actions. Accordingly, the repo https://github.com/scikit-image/scikit-image-wheels no longer serves any purpose in the CI. Should it be archived/removed?

Also, the CI team (https://github.com/orgs/scikit-image/teams/ci) is to be removed, thus, crossing out the last bullet point.

@scikit-image/core kindly confirm that I am not missing anything.

**Comment by soupault** [comment]
@stefanv @jni kind reminder that https://github.com/orgs/scikit-image/teams/ci team can be removed since we no longer use AppVeyor.
