### ISSUE TITLE
Add shear axis argument to AffineTransform? 

### ISSUE THREAD

**Issue by jmetz** [scikit-image/scikit-image#3548]
## Description

**Disclaimer:** 
posting in response to a SO issue I was answering here: 
https://stackoverflow.com/questions/53298558/skimage-defining-vertical-shear/53300186

The OP asked about performing vertical shear, as the shear parameter implements horizontal 
shear. 

Would it make sense to add a `shear_axis` kwarg which defaults to `0`?

**Comment by jmetz** [comment]
NB The implementation of this will also be affected by #3239

**Comment by jni** [comment]
All of transforms is a huge mess that I hope to focus on next month. =) Thanks for flagging this.

Also it's super weird that as far as I can tell I wasn't notified about this SO post... Thanks for your thorough answer and comments! =)
