### ISSUE TITLE
_validate_lengths replaced in numpy/master leading to ImportError exception

### ISSUE THREAD

**Issue by pllim** [scikit-image/scikit-image#3551]
## Description

As seen in https://travis-ci.org/astropy/astropy/jobs/455917279 , `from skimage.measure import block_reduce` caused `ImportError` when used with numpy dev.

```python
    from skimage.measure import block_reduce
  File ".../skimage/measure/__init__.py", line 3, in <module>
    from ._marching_cubes_classic import (marching_cubes_classic,
  File ".../skimage/measure/_marching_cubes_classic.py", line 3, in <module>
    from .._shared.utils import warn
  File ".../skimage/_shared/utils.py", line 10, in <module>
    from ..util import img_as_float
  File ".../skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File ".../skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'
```
https://github.com/scikit-image/scikit-image/blob/29a22e17c8b4ccf26383e3007ab014eb18b81f12/skimage/util/arraycrop.py#L7

Caused by numpy/numpy#11966

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example
- [ ] Relevant images (if any)
- [x] Operating system and version -- Linux-4.14.12-041412-generic-x86_64-with-debian-jessie-sid
- [x] Python version -- 3.6.6
- [x] scikit-image version (run `skimage.__version__`) -- 0.14.0

All the info is in https://travis-ci.org/astropy/astropy/jobs/455917279 .

**Comment by sciunto** [comment]
Thanks for reporting!

**Comment by samohant** [comment]
Tried all still getting the below issue:
from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad'
Python Version : 1.16.1

**Comment by stefanv** [comment]
@samohant Please file a new issue, and fill out the issue template provided. Thanks!

**Comment by jni** [comment]
@samohant I suspect that you have scikit-image <0.14.2. Please install the latest version of scikit-image.

**Comment by hmaarrfk** [comment]
Once again, I'm going to close this issue because we have addressed the original request quiet extensively. If anybody does have similar installation issues, please make sure you have installed scikit-image 0.14.2. If that doesn't help, please open a new issue and we will gladly help you troubleshoot.
