### ISSUE TITLE
Building docs fails on macOS - nproc not found

### ISSUE THREAD

**Issue by PinkFloyded** [scikit-image/scikit-image#3562]
## Description
Running `make` in the `doc` directory fails on macOS as the `Makefile` uses `nproc` to find the number of processors, but it wasn't installed. Full error below:

```
python tools/build_modref_templates.py
*WARNING* API documentation not generated: Installed version does not match source version
Build API docs...done.
Copying release notes
make: nproc: Command not found
python -m sphinx -b html -d build/doctrees  -j  source build/html
Sphinx v1.6.6
Usage: __main__.py [options] sourcedir outdir [filenames...]

Filename arguments:
  without -a and without filenames, write new and changed files.
  with -a, write all files.
  with filenames, write these.

__main__.py: error: option -j: invalid integer value: 'source'
make: *** [html] Error 2
```

I think this can be fixed by checking if `nproc` is available before using it, and if not, use some other method to find number of processors.

Python version - 3.6.4
OS - macOS Mojave - 10.14.1

**Comment by sciunto** [comment]
You are not the first one to report this: https://github.com/scikit-image/scikit-image/pull/3530#discussion_r231380092

**Comment by sciunto** [comment]
Would you like to work on this? I don't use this OS, so it's not easy to write a patch...
