### ISSUE TITLE
ImportError: cannot import name 'compare_psnr'

### ISSUE THREAD

**Issue by dev-script** [scikit-image/scikit-image#3567]
I have installed scikit-image library for my system but when i'm running 
             "from skimage.measure import compare_psnr"
got an error - ImportError: cannot import name 'compare_psnr'

**Comment by hmaarrfk** [comment]
Please also provide the operating system you are using along with how you installed scikit image. Git? Conda? Pip? Virtualenv?

**Comment by grlee77** [comment]
closed as stale and with lack of details to reproduce

**Comment by Mellak** [comment]
If you are using Anaconda : conda install scikit-image will solve the problem.
https://scikit-image.org/docs/dev/install.html#install-via-conda

**Comment by Pizzanomicon** [comment]
Same issue, on MacOS 10.15.7, skimage version 0.18.1. Installed via pip.
This is maddening, all indications are that skimage is installed correctly, but "compare_psnr" is throwing this error when I attempt to import it.

**Comment by grlee77** [comment]
@Pizzanomicon

This function was renamed in release 0.16 and the older `compare_psnr` name was removed in 0.18. You should be able to import under the new name with
```Python
from skimage.metrics import peak_signal_noise_ratio
```

**Comment by Grace201940000019** [comment]
ModuleNotFoundError: No module named 'dictlearn'

Here is the tutorial I was following...
import matplotlib.pyplot as plt
import dictlearn as dl

denoise = dl.Denoise(r"E:\PNG\Manifest-a\denoised\POISSON-BILATERAL\lidc-0BNLM1.jpg")
denoised_image = denoise.train().denoise()
plt.imshow(denoised_image)
plt.show()

Please how do I solve this error, I have installed dictionary learning but it's not working with the line of code  2

**Comment by rfezzani** [comment]
@Grace201940000019, this is the `scikit-image` issue tracker!

I don't see any mention of `scikit-image` in your code sample.
You may have better luck with `dictlearn` repo https://github.com/permfl/dictlearn

**Comment by Grace201940000019** [comment]
> @Grace201940000019, this is the `scikit-image` issue tracker!
> 
> I don't see any mention of `scikit-image` in your code sample. You may have better luck with `dictlearn` repo https://github.com/permfl/dictlearn

Okay, thanks, @rfezzani

**Comment by fengwang** [comment]
> @Pizzanomicon
> 
> This function was renamed in release 0.16 and the older `compare_psnr` name was removed in 0.18. You should be able to import under the new name with
> 
> ```python
> from skimage.metrics import peak_signal_noise_ratio
> ```

Is there a reason to rename this function?
Is it difficult to keep the API compatibility?

**Comment by jjnpalak11** [comment]
> @Pizzanomicon
> 
> This function was renamed in release 0.16 and the older `compare_psnr` name was removed in 0.18. You should be able to import under the new name with
> 
> ```python
> from skimage.metrics import peak_signal_noise_ratio
> ```

this works, the nly solution on the internet which gives result, GREAT JOB !
