### ISSUE TITLE
pyproject.toml whoes

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3576]
pyproject.toml specifies the build dependencies for the project as described in https://www.python.org/dev/peps/pep-0518/

Unfortunately, the current one we wrote, doesn't specify a minimum version of numpy required to build the system. This is really unlikely to cause any issues since numpy 1.11 (which is what scikit-image supports) is probably installed on everybody's system.

But, if you are interested in building against a specific version, such as when we are building for the "minimum dependencies", the command `pip install .` will simply find "any version of numpy", likely 1.15 today, and build the package with that. If you are interested in running this with an older version of numpy, there is a high probability it won't work (e.g. build with 1.15 and run on 1.11).

The issue is opened out of an abundance of caution:
1. You are building a modern version of scikit-image (0.14.1)
2. For some reason, only numpy <1.11 is found.
3. The system will likely continue to the try the build, and fail with some strange message

It would be good if pyproject.toml caught the incompatible version at step `#2`, and just stopped the build there saying: "numpy 1.11 required but not found."

I'm not sure if the build requirement should be `numpy==1.11` or `numpy>1.11`.

I kinda ran into the bug developing https://github.com/scikit-image/scikit-image/pull/3311#discussion_r238172428

using 
```
pip install --no-build-isolation . 
```

Will use the current environment to build the package and therefore ensure that the build version of numpy is the same as the one installed in the virtual environment.

**Comment by stefanv** [comment]
Can you describe the issue in a bit more detail so that someone can take a look? Thanks!

**Comment by hmaarrfk** [comment]
After finishing the work on the issues referenced below, I'm not so sure pyproject.toml adds too much value.

Let me explain:
1. The sdist packages contain all the cythonized files.
This PR ensures that one can build from sdist without cython:
https://github.com/scikit-image/scikit-image/pull/3311
though probably needs a bit of cleanup.

2. Wheels are uploaded for x86 architectures.

3. Users that are building on unsupported architectures know how to read docs.

4. Pip's flags are confusing: https://github.com/pypa/pip/issues/5735
   - There were some other issues raised on conda-forge about this as well.

On conda-forge, what was happening was:
1. Numpy 1.11 was installed.
2. conda-forge had misconfigured their environment for (see 4.)
3. scikit-image was installed using `pip install . --no-deps` which decided to use  `pyproject.toml`
  - Pip creates a new environment, pulling everything from pypi, it pulled in numpy 1.15.x <-----
  - The package is compiled using numpy 1.15.x
4. A user reported the package not working numpy 1.13

Because's pips flags are so confusing, I think it is best to avoid it. 

conda-forge issues:
https://github.com/conda-forge/scikit-image-feedstock/pull/39
https://github.com/conda-forge/scikit-image-feedstock/pull/38

trying to fix the issue raised in
https://github.com/conda-forge/scikit-image-feedstock/issues/36

**Comment by stefanv** [comment]
Hrm, so what action do you recommend?  Removing pyproject.toml entirely?

**Comment by hmaarrfk** [comment]
yeah, that would be my vote.

That was my solution after struggling enough with pip for conda-forge.

**Comment by hmaarrfk** [comment]
I guess I'm saying that the issues that Matthew-Brett brought up in https://github.com/scikit-image/scikit-image/pull/3020
about it messing with version requirements for packages are still alive and well.

Take this as one (packager) user story about struggling with pyproject.toml

**Comment by stefanv** [comment]
OK, let's go ahead and remove.

**Comment by hmaarrfk** [comment]
Inertia is killing me. I probably won't submit that PR since I kinda permanently took care of the problem for my usecase.

cross linking scipy's discussion
https://github.com/scipy/scipy/issues/8734

**Comment by hmaarrfk** [comment]
It seems scipy is going to go the other direction. Maybe we should wait and
see what happens.

**Comment by hmaarrfk** [comment]
xref: https://github.com/scikit-image/scikit-image/issues/3685
