### ISSUE TITLE
Check if tifffile can be added as a requirement instead of vendoring it

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#3578]
## Description

So far, we have a modified copy of tifffile. See in particular #3452 

If wheels are available one day for tifffile, then we must consider removing this copy.

**Comment by hmaarrfk** [comment]
To my knowledge, tifffile itself has become a "pure python package" https://pypi.org/project/tifffile/#files

That said, it now depends on other binaries such as imagecodecs: https://pypi.org/project/imagecodecs/#files

which only offers wheels for windows.

**Comment by stefanv** [comment]
Are those image codecs required on any platform other than Windows?

**Comment by cgohlke** [comment]
> Are those image codecs required on any platform other than Windows?

`pip install tifffile` should not require `imagecodecs` on platforms other than Windows.

However, `tifffile` uses `imagecodecs` (if available) at runtime to decode LZW, JPEG, J2K, floating point predictor, etc encoded image data stored in TIFF. Out of those codecs, LZW is probably the most significant for skimage users.

 `imagecodecs` works for me on Ubuntu 18.04 (assuming all build requirements have been installed with apt-get) and there is an open [PR for conda-forge](https://github.com/conda-forge/staged-recipes/pull/6842).

**Comment by stefanv** [comment]
Would it be helpful for us to set up a wheel builder repo for
imagecodecs, or do you have an existing pipeline to build manylinux
wheels?

**Comment by cgohlke** [comment]
I don't have a setup to build manylinux or macos wheels. If someone could provide missing wheels for the PyPI releases, that would be helpful. Seems like a daunting or tedious task judging from the fact that none of the packages on PyPI that imagecodecs uses for testing provides manylinux wheels: `blosc`, `lzf`, `zstd`, `lz4`, `backports.lzma`.  The `numcodecs` package also does not provide wheels.

**Comment by hmaarrfk** [comment]
@cgohlke I think it should maybe be possible to use matthew brett's architecture to create wheels.

It might be easier to integrate if you had an official git(hub???) repository setup for tifffile. Do you have any intention of setting one up?

I managed to get part of the process working a while back
https://github.com/hmaarrfk/tifffile-wheels

If you want to go on this adventure, we can try to start with numcodecs.

**Comment by hmaarrfk** [comment]
xref https://github.com/zarr-developers/numcodecs/issues/70

**Comment by YubinXie** [comment]
imagecodecs does not work with Mac OS (can't install).

**Comment by sciunto** [comment]
@YubinXie Please, report this issue to imagecodecs dev.

**Comment by YubinXie** [comment]
@sciunto imagecodecs does not seem have a github page where I can report issue. I reported it in TIFFFILE github.

**Comment by sciunto** [comment]
Cc @cgohlke

**Comment by cgohlke** [comment]
The build and test dependencies for the `imagecodecs` package are listed in it's docstring and readme file. 

The `tifffile` and `imagecodecs` docs also refer to the [`imagecodecs-lite`](https://pypi.org/project/imagecodecs-lite/) package as an easier-to-build alternative for decoding LZW.

**Comment by YubinXie** [comment]
I was able to install `imagecodecs-lite ` and it works with latest tifffile without any issues. Perfect solution. All errors and warning are gone. Thanks!
