### ISSUE TITLE
Missing parameter description in `morphology.reconstruction() docstring

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#3581]
## Description

The parameter `offset` of `morphology.reconstruction` is not documented: http://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.reconstruction

Optional parameters are not marked with `, optional` in the docstring.

**Comment by FrAnCOisCokELaER** [comment]
@sciunto I could help on this one if needed ? (first contribution, have some mathematical morphology background)

**Comment by emmanuelle** [comment]
@FrAnCOisCokELaER please do! Depending on your level of experience with open-source development, you might find our contributing notes useful: http://scikit-image.org/docs/dev/contribute.html
Thanks :-)

**Comment by emmanuelle** [comment]
@FrAnCOisCokELaER I can see you pushed a commit to your branch, do you want to open a pull request now?

**Comment by sciunto** [comment]
Thanks @FrAnCOisCokELaER
