### ISSUE TITLE
Hit or miss morphological transform

### ISSUE THREAD

**Issue by PinkFloyded** [scikit-image/scikit-image#3583]
## Description
Not sure if this discussion has already happened before. All I could find was #1655 which was abruptly closed.

We can route this to [ndimage's implementation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.binary_hit_or_miss.html#scipy.ndimage.binary_hit_or_miss) like we do for other morphological operations.

Reference: https://homepages.inf.ed.ac.uk/rbf/HIPR2/hitmiss.htm

**Comment by stefanv** [comment]
We typically wrap `ndimage` functions when we have something to add, such as the `sigma` processing for the Gaussian filter.  Do you think we have anything to offer, currently, in addition to the default ndimage behavior?

**Comment by VeneetReddyK** [comment]
Nothing to offer really.

But, if a user needed hit-or-miss then they'd have to explicitly pull down `scipy` just for that. `scikit-image` already pulls it down as a transitive dependency, but, the user will have to explicitly list it in their requirements to use it as a good practice.

**Comment by PinkFloyded** [comment]
Nothing to offer really.

But, if a user needed hit-or-miss then they'd have to explicitly pull down scipy just for that. scikit-image already pulls it down as a transitive dependency, but, the user will have to explicitly list it in their requirements to use it as a good practice.

**Comment by soupault** [comment]
>But, if a user needed hit-or-miss then they'd have to explicitly pull down scipy just for that. scikit-image already pulls it down as a transitive dependency, but, the user will have to explicitly list it in their requirements to use it as a good practice.

I don't see any issues in working with scipy directly.

@PinkFloyded implementing 1-to-1 thin wrappers brings little to no benefit, while adding extra work for keeping the wrappers __and__ the corresponding tests up-to-date. We already had such experience with ndimage morphology functions (https://github.com/scikit-image/scikit-image/issues/1917, https://github.com/scikit-image/scikit-image/issues/2597, https://github.com/scikit-image/scikit-image/pull/2917), so I'd strongly prefer not to follow the same path without a significant reason (extra functionality, of course, could be one of those reasons).

For now, I'm going to close the issue as "wontfix", but thanks for your interest and suggestion.
