### ISSUE TITLE
Cannot use concatenate module

### ISSUE THREAD

**Issue by aconceicao** [scikit-image/scikit-image#3593]
I'm trying to load a stack of 2D tiff images, using the code below. 

import skimage.io as io

image_collection = io.ImageCollection('/recon_dir/*.tif')
image_3d = io.concatenate(image_collection).]

However, appears the following message:
'AttributeError: module 'skimage.io' has no attribute 'concatenate''

And when I try:

image_3d = io.concatenate_images(image_collection)

Arises: 'ValueError: Image dimensions must agree.'

Had anyone the same problem? How did you fix it?

Thank you in advance. 

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by alexandrejaguar** [comment]
Hi @aconceicao,
it seems that your images have different dimensions.
I tried the following in a folder with several images, all with the same dimensions, and it worked.
```
from skimage import io
image_collection = io.ImageCollection('*.tif')
image_3d = io.concatenate_images(image_collection)
```
However, when I tried the same with a cropped image, I had the same error. I used this code to check their dimensions:
```
for image in image_collection: 
    print(image.shape)
```
If that's the case, you could use [`transform.resize`](http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.resize) to get them all to the same size and try again. Please check it and let me know.
Cheers!

**Comment by alexandrejaguar** [comment]
Closed due to inactivity. Please reopen if necessary.
