### ISSUE TITLE
More general clear_border?

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#3594]
A colleague suggested that it might be interesting to have in ``segmentation`` a more general version of ``clear_border``, which would take a mask as optional argument and remove objects touching the edge of the mask (with respect to the border of the whole image as it is now). It should be straightforward to adapt the existing function. Would there be enough interest to include this feature or not?

**Comment by jni** [comment]
+1 from me

**Comment by stefanv** [comment]
On Mon, 17 Dec 2018 13:48:01 -0800, Emmanuelle Gouillart wrote:
> A colleague suggested that it might be interesting to have in
> ``segmentation`` a more general version of ``clear_border``, which
> would take a mask as optional argument and remove objects touching the
> edge of the mask (with respect to the border of the whole image as it
> is now). It should be straightforward to adapt the existing
> function. Would there be enough interest to include this feature or
> not?

That's a neat idea!

Another use case that cropped up today: return the removed objects,
instead of the cleaned up mask.  This is pretty easy to do with a `mask
!= cleaned_mask`, so I'm not even sure if it's worth adding in.

**Comment by alexandrejaguar** [comment]
@emmanuelle I implemented a version for cleaning the "right" and "down" borders of an input image, for the papers I'm working on:
```
def clear_rd_border(image):
    """
    Not documented yet. Sorry!
    """

    aux = np.pad(image, ([1, 0], [1, 0]), mode='constant')
    aux = clear_border(aux)
    
    return aux[:-2, 1:]
```
Such general function could be easily implemented making the `([1, 0], [1, 0])` argument on `np.pad` a variable, I think.
