### ISSUE TITLE
Orphan code in filters

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#3595]
I noticed that https://github.com/scikit-image/scikit-image/blob/master/skimage/filters/_ctmf.pyx is not imported in the ``__init__.py`` of ``filters`` or elsewhere in this submodule. I have the feeling that this code, which was originally taken from CellProfiler, is now orphan. Should we remove it?

**Comment by stefanv** [comment]
If you remove it, and Travis-CI is happy, trash it!
