### ISSUE TITLE
local tophat from rank filters has an unclear/unsufficient documentation

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#3599]
## Description

We had a quick look with @ThomasWalter and @emmanuelle on the top hat filter from rank and the docstring/behavior are unclear.

For instance, I understand

```
img = color.rgb2gray(data.hubble_deep_field())[:500, :500]

selem =  morphology.disk(1)
res = morphology.white_tophat(img, selem)

fig, ax = plt.subplots(ncols=3, figsize=(20, 8))
ax[0].set_title('Original')
ax[0].imshow(img, cmap='gray')
ax[1].set_title('White tophat')
ax[1].imshow(res, cmap='gray')
ax[2].set_title('Complementary')
ax[2].imshow(img - res, cmap='gray')

plt.show()
```

but not 
```
res = rank.tophat(img, selem)


fig, ax = plt.subplots(ncols=3, figsize=(20, 8))
ax[0].set_title('Original')
ax[0].imshow(img, cmap='gray')
ax[1].set_title('White tophat')
ax[1].imshow(res, cmap='gray')
ax[2].set_title('Complementary')
ax[2].imshow(img - res, cmap='gray')

```

**Comment by soupault** [comment]
@sciunto see https://github.com/scikit-image/scikit-image/issues/3580.

**Comment by sciunto** [comment]
I know, I opened that one :)

**Comment by ThomasWalter** [comment]
I looked at the image, and the function does not compute a top-hat. 

Just for recall: a white top-hat is defined as WTH = f - opening(f), a black top-hat as BTH = closing(f) - f. 

`rank.tophat` calculates an external gradient, i.e. dilation(f) - f: 

```img_orig = color.rgb2gray(data.hubble_deep_field())[:500, :500]
img = (255*img_orig).astype(np.uint8)
grad = morphology.dilation(img, selem) - img
th_rank = rank.tophat(img, selem)
delta = grad - th_rank
print(delta.max())
delta = th_rank - grad
print(delta.max())
```

The function needs to be renamed, I guess.

**Comment by sciunto** [comment]
I vote for removing the function. Other optinions @scikit-image/core

**Comment by soupault** [comment]
:+1: for removal. I think the next step should be to wrap scipy morphology functions - https://github.com/scikit-image/scikit-image/issues/1917.

**Comment by rfezzani** [comment]
Closing since #4423 deprecates filters.rank.tophat ;-)
