### ISSUE TITLE
Move histogram matching from transform to exposure

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3618]
We recently merged #3568, which added histogram matching to the `transform` module. @stefanv argued (and I agree) that it should go into `exposure` instead. Oops!

See https://github.com/scikit-image/scikit-image/pull/3568#pullrequestreview-186841972

**Comment by sciunto** [comment]
And there is a test that I commented that must be rewritten, due to the addition of the multichannel argument. The boolean must be left to False in that case.
