### ISSUE TITLE
Inconsistent annotation of image license in data module

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3623]
## Description
I've just been going through our `data` [documentation](http://scikit-image.org/docs/dev/api/skimage.data.html), and some images contain license information while others are vague ("no known copyright") or non-existent. I suggest that the ones that list "public domain" be renamed to CC0 (I think this is kosher?), and the ones that say "no known copyright" be relabeled to "probably CC0" or "CC0+BY" or somesuch.

**Comment by sciunto** [comment]
I disagree to change public domain for CC0. It's not the exactly same afaik. https://wiki.creativecommons.org/wiki/CC0_FAQ#What_is_the_difference_between_CC0_and_the_Public_Domain_Mark_.28.22PDM.22.29.3F


But some images have wrong copyright information. Ex: the horse must be CC0 (the website states that).

Keeping images with no known copyright is a bit dangerous, although we can argue to consider a fair use: https://en.wikipedia.org/wiki/Fair_use

**Comment by soupault** [comment]
Looks useful - https://tldrlegal.com/ .

**Comment by sciunto** [comment]
I think we have made efforts recently on this, and the situation is improved. I close the issue. We may come back on this once pooch will be in place.
