### ISSUE TITLE
Start a GitHub Queries wiki page to find neglected PRs or issues

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3629]
## Description
@stefanv pointed out that NumPy has a [GitHub Queries page](https://github.com/numpy/numpy/wiki/Github-Queries) that lets them find neglected issues and PRs. I think this is a useful thing to have (linked from the README perhaps), so that we don't let issues fall through the cracks. One can also think of significant tags (high priority, bugs, mrg+1) to add to such a page.

**Comment by soupault** [comment]
👍. Another useful thing could be to configure https://github.com/apps/meeseeksdev to automatically assign "Needs Decision" (or similar) tag to all the new issues and PRs, and the ones that haven't been updated (by comments or commits) in a while.

**Comment by sciunto** [comment]
I don't know what's the best procedure to set, but definitely +1 on a way to keep an eye on neglected issues/PR.

A suggestion. I find useful the milestones. Clearly, if each issue would have a milestone, it would force ourself to review regularly these issues and decide whether to solve it, to postpone it or to close it.

**Comment by sciunto** [comment]
@scikit-image/core What is your opinion on this?

**Comment by jni** [comment]
@sciunto I like milestones. I'm just not disciplined enough to deal with them. Also, many PRs end up being carried over several milestones because they are harder than anticipated, and we often have to push a release earlier than we want because of e.g. the NumPy 1.16 situation. But anyway, I do think that the labels are useful. But not a cure-all for what this issue is asking.

**Comment by sciunto** [comment]
I believe that labels and milestones are complementary. I think also that it is normal that some issues' milestones are postpones several times. It is an evidence that we reconsider the issue regularly. Perhaps, we do not consider often enough to close them, but that's more a human problem (responsibility?) rather than a problem of methodology.

**Comment by stefanv** [comment]
We'll be doing some work this year on the [Scientific Python devstats dashboard](https://devstats.scientific-python.org/).

**Comment by stefanv** [comment]
@lagru Also recently added a daily cronjob for adding dormant tags: https://github.com/scikit-image/scikit-image/labels/%3Asleeping%3A%20Dormant

**Comment by stefanv** [comment]
I've added a wiki page, as requested by the issue: https://github.com/scikit-image/scikit-image/wiki/Useful-Github-Queries

Feel free to update to make it more useful.
