### ISSUE TITLE
Documentation search results are polluted

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3640]
Documentation search results show snippets from raw RST, instead of plain text.  Some of these files also contain the text "AUTOGENERATED, DO NOT MODIFY", which search results should not show.

To reproduce: go to skimage.org, put "adjacency" in the search box, and go.

**Comment by clementkng** [comment]
@stefanv Does this issue still exist? I did the search, ending up at this [link](https://scikit-image.org/docs/dev/search.html?q=adjacency&check_keywords=yes&area=default) and couldn't find any raw RST or autogenerated files.

**Comment by sciunto** [comment]
Agreed. I close it for now.

**Comment by soupault** [comment]
Didn't expect this one though 🙂:
![image](https://user-images.githubusercontent.com/1315589/61636129-ab94a800-ac9d-11e9-865b-4a08a3ef5d47.png)
