### ISSUE TITLE
Seam carving is patented; remove from library

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3646]
https://patents.google.com/patent/US8213745B2/en

Ref: #2808 #3082 #3643 

This code may be made available outside of scikit-image under the same license, but our policy is not to include algorithms covered under active patents.

**Comment by hmaarrfk** [comment]
The cited paper is from 2007. 

The priority date on the patent is from 2009.

I think you are safe @stefanv.

**Comment by hmaarrfk** [comment]
Though it seems they cite a patent from the paper's authors, also from 2007. So :/

**Comment by jni** [comment]
Yep, here's the actual patent:
https://patents.google.com/patent/US20080219587A1/en

**Comment by soupault** [comment]
Affects https://github.com/scikit-image/scikit-image/issues/2808, https://github.com/scikit-image/scikit-image/issues/3082, and https://github.com/scikit-image/scikit-image/pull/3643.

**Comment by itaru-lauzun** [comment]
patent seems expired since 2022, could be great to restore seam_carve  https://www.patentguru.com/search?q=US20080219587A1

**Comment by stefanv** [comment]
I don't think seam-carving is a very useful algorithm; but I'm open to discussion.
