### ISSUE TITLE
AttributeError: 'numpy.ufunc' object has no attribute '__module__'

### ISSUE THREAD

**Issue by raphaeljolivet** [scikit-image/scikit-image#3654]
I just installed last version of **skimage** and **numpy**, and I get the following error when importing :

```
>>> import skimage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/local/lib/python2.7/site-packages/skimage/__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File ".venv/local/lib/python2.7/site-packages/skimage/util/__init__.py", line 6, in <module>
    from .apply_parallel import apply_parallel
  File ".venv/local/lib/python2.7/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File ".venv/local/lib/python2.7/site-packages/dask/array/__init__.py", line 9, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File ".venv/local/lib/python2.7/site-packages/dask/array/routines.py", line 256, in <module>
    @wraps(np.matmul)
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'
```
I am using python 2.7 in a **virtualenv** environment.
I have the following dependencies installed :

- scikit-image==0.14.1
- numpy==1.16.0 
- dask==1.0.0

Any help would be appreciated.
Thanks in advance.

**Comment by jni** [comment]
Thanks @raphaeljolivet! We have noticed this ourselves in trying to get 0.14.2 out the door! Please hold because we haven't figured this one out yet.

Currently the only fix is to install NumPy 1.15. (Although I'm not positive that would work here.)

By the way, how did you install scikit-image? Were any of your installations from source?

**Comment by hmaarrfk** [comment]
That particular bug has been fixed upstream: https://github.com/dask/dask/pull/4363

I think dask 1.0.0 is also broken for python 2.7 on numpy 1.16

I have a feeling that many libraries broke in 1.16. There were a few changes to the internals of numpy that cuased some downstream packages to break.

I would wait a few more weeks until all the big packages have released a new dot release.

**Comment by raphaeljolivet** [comment]
Fallbacking to Numpy 1.15 solves the issue for me.
Thanks.

**Comment by soupault** [comment]
Closed in favour of https://github.com/scikit-image/scikit-image/issues/3654 .

**Comment by stefanv** [comment]
@soupault Which ticket did you mean? This is #3654.

**Comment by soupault** [comment]
Yes, sorry for the typo. I meant https://github.com/scikit-image/scikit-image/issues/3649.
