### ISSUE TITLE
Why is skimage.restoration.inpaint_biharmonic to slow?

### ISSUE THREAD

**Issue by mleraa** [scikit-image/scikit-image#3665]
System specs:
Macbook Pro, 8 GB RAM, Intel HD Graphics, 
```
Python 3.6.3
>>> cv2.__version__
'4.0.0'
>>> skimage.__version__
'0.14.2'
```

I am trying to delete the watermarks from a few images. I have tried out the `cv2.inpaint` and `skimage.restoration.inpaint_biharmonic` and I saw some big differences at the result and at the performance.

General approach:
[![enter image description here][1]][1]

Original Image:
[![enter image description here][2]][2]

Mask:
[![enter image description here][3]][3]

Skimage approach:

    import numpy as np
    import skimage.io
    import skimage.restoration
    import skimage.exposure
    import time
    
    img = skimage.io.imread('x')
    msk = skimage.io.imread('x')
    start_time = time.time()
    msk = skimage.exposure.rescale_intensity(msk, in_range='image', out_range=(0,1))
    newimg = skimage.restoration.inpaint_biharmonic(img, msk, multichannel=True)
    print("--- %s seconds ---" % (time.time() - start_time))
    plt.imshow(newimg)
    plt.show()
[![enter image description here][5]][5]

Cv2 approach:

    import numpy as np
    import cv2 as cv
    import matplotlib.pyplot as plt
    
    import time
    
    img = cv.imread('x')
    mask = cv.imread('x',0)
    start_time = time.time()
    dst = cv.inpaint(img,mask,3,cv.INPAINT_TELEA)
    print("--- %s seconds ---" % (time.time() - start_time))
    plt.imshow(cv2.cvtColor(dst, cv2.COLOR_BGR2RGB))

[![enter image description here][4]][4]

Performance:

 - cv2: 0.04929995536804199 seconds 
 - skimage: 116.02286505699158 seconds

Result:
At the front end the deleting is harder on opencv than on skimage. With skimage the deleting is thus more successful, because it looks smoother than opencvs deleting.

**I would like to use skimage as it gives better results. But opencv is faster. What can I do?**

**Disclaimer: This process is for educational purposes only and will not be published, further processed or redistributed**

  [1]: https://i.stack.imgur.com/OLzvm.png
  [2]: https://i.stack.imgur.com/nvyY0.jpg
  [3]: https://i.stack.imgur.com/yLmI7.png
  [4]: https://i.stack.imgur.com/DaHYC.png
  [5]: https://i.stack.imgur.com/EXeIh.png

**Comment by soupault** [comment]
@mleraa Hi! It is a known issue, and I wrote some bullets on where the implementation can be optimized - https://github.com/scikit-image/scikit-image/issues/2008#issuecomment-197349560. I don't think that you can speedup things without going deep into the algorithm.

If you are really interested in "traditional" (i.e. without deep learning) inpainting algorithms and ready to implement one, I'd strongly suggest to take a look at https://github.com/soupault/scikit-inpaint/issues/4. That algorithm performs visually equal or superior to biharmonic method and, once properly turned into the code, can be really fast even for large images.

If you are looking just for a "fast and good enough" inpainting method, take a look at the numerous deep-learning-based solutions for inpainting on GitHub.

I going to close the issue as I don't have bandwidth to work on this in the observable future. However, if you are ready to take action, please, feel free to reopen.
