### ISSUE TITLE
Hide xy/rc warnings when computing regionprops not affected by the change

### ISSUE THREAD

**Issue by anntzer** [scikit-image/scikit-image#3667]
## Description

As of skimage 0.14.2, the xy-to-rc warning is emitted when computing certain regionprops that are not actually affected by the xy-to-rc change, e.g. the minor/major_axis_length:
```
import numpy as np
from skimage import measure
p, = measure.regionprops(np.array([[0, 1], [1, 0]]))
print(p.major_axis_length)
```
gives
```
$HOME/.local/lib/python3.7/site-packages/skimage/measure/_regionprops.py:250: UserWarning: regionprops and image moments (including moments, normalized moments, central moments, and inertia tensor) of 2D images will change from xy coordinates to rc coordinates in version 0.16.
See http://scikit-image.org/docs/0.14.x/release_notes_and_installation.html#deprecations for details on how to avoid this message.
  warn(XY_TO_RC_DEPRECATION_MESSAGE)
$HOME/.local/lib/python3.7/site-packages/skimage/measure/_regionprops.py:260: UserWarning: regionprops and image moments (including moments, normalized moments, central moments, and inertia tensor) of 2D images will change from xy coordinates to rc coordinates in version 0.16.
See http://scikit-image.org/docs/0.14.x/release_notes_and_installation.html#deprecations for details on how to avoid this message.
  warn(XY_TO_RC_DEPRECATION_MESSAGE)
2.8284271247461903
```
I guess that this is because the computation goes through the computation of moments, which *is* affected by the change, but the computation of the minor/major_axis_length should wrap itself using e.g. warningsfilter to hide that warning.

(I also think that forcing the warning to be emitted *every* time is a misfeature (you can easily end up overwhelmed by the same warning emitted thousands of times...), as argued in https://github.com/scikit-learn/scikit-learn/issues/8182, but that's a separate issue.)

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [X] Code example
- [N/A] Relevant images (if any)
- [X] Operating system and version: Fedora 29
- [X] Python version: 3.7
- [X] scikit-image version (run `skimage.__version__`): 0.14.2

**Comment by jni** [comment]
@anntzer both good points! Would you like to submit a PR to fix this? The two warnings are because one is emitted at the time of creation of the regionprops object, and the other one is emitted (incorrectly, as you point out) at the time of the moments computation. I agree that major/minor axes length computations should filter out the warnings.

**Comment by anntzer** [comment]
I gave up on using regionprops because of https://github.com/scikit-image/scikit-image/issues/3666 and now use my own code to handle weighted properties, so I'll leave this as it is.

**Comment by jni** [comment]
@anntzer would you mind pointing us to your code to see if we could use it to improve ours? ;)

**Comment by grlee77** [comment]
I am closing this as these warnings are no longer present.
