### ISSUE TITLE
io.imsave does not detect a Path argument that ends with .tiff as tiff file

### ISSUE THREAD

**Issue by tsvikas** [scikit-image/scikit-image#3669]
## Description
When using:
from skimage import io
from pathlib import Path
array = some np.array
io.imsave(Path('/Tmp/a.tiff'), array)
The resulted file a.tiff is a PNG file

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example
- [ ] Relevant images (if any)
- [x] Operating system and version Ubuntu 18.10
- [x] Python version 3.6
- [x] scikit-image version (run `skimage.__version__`) 0.14.1

**Comment by VeneetReddyK** [comment]
I think this is a duplicate of #3331

**Comment by PinkFloyded** [comment]
I think this is a duplicate of #3331

**Comment by sciunto** [comment]
Closed as a duplicate of #3331
