### ISSUE TITLE
libtiff 4.0.10 import error

### ISSUE THREAD

**Issue by jontwo** [scikit-image/scikit-image#3679]
## Description
I have reported this on libtiff (https://github.com/pearu/pylibtiff/issues/87), but there is an import error with the latest version of libtiff (4.0.10). Raising a ticket here to see if it is something that can be fixed at this end.

## Way to reproduce
OS: Windows Server 2012 R2
Python: 2.7.15
Conda: 4.5.12

At `libtiff` 4.0.9:

```
(c:\jenkins\workspace\Farmmap_commit_windows\venv) c:\jenkins\workspace\Farmmap_
commit_windows>python -c "import skimage;print skimage.__version__"
0.14.1
```

At `libtiff` 4.0.10:

```
(c:\jenkins\workspace\Farmmap_commit_windows\venv) c:\jenkins\workspace\Farmmap_
commit_windows>python -c "import skimage;print skimage.__version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\jenkins\workspace\Farmmap_commit_windows\venv\lib\site-packages\skima
ge\__init__.py", line 177, in <module>
    from .data import data_dir
  File "c:\jenkins\workspace\Farmmap_commit_windows\venv\lib\site-packages\skima
ge\data\__init__.py", line 15, in <module>
    from ..io import imread, use_plugin
  File "c:\jenkins\workspace\Farmmap_commit_windows\venv\lib\site-packages\skima
ge\io\__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "c:\jenkins\workspace\Farmmap_commit_windows\venv\lib\site-packages\skima
ge\io\manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "c:\jenkins\workspace\Farmmap_commit_windows\venv\lib\site-packages\skima
ge\io\collection.py", line 12, in <module>
    from PIL import Image
  File "c:\jenkins\workspace\Farmmap_commit_windows\venv\lib\site-packages\PIL\I
mage.py", line 94, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by cgohlke** [comment]
This is not a pylibtiff or scikit-image issue. Your version of Pillow was likely built against an older version of the libtiff DLL. The last version of libtiff changed the name of the DLL such that PIL/Pillow fails to load. Either rebuild Pillow against the new libtiff DLL or use the official, statically linked binaries at https://pypi.org/project/Pillow/#files

**Comment by hmaarrfk** [comment]
is there something you particularly need that makes  yu want to compile everything yourself?

**Comment by jontwo** [comment]
Sure. We're using conda though - not building anything locally. I'll raise a ticket over there.

**Comment by hmaarrfk** [comment]
what channels do you have enabled on conda? conda-forge?

**Comment by jontwo** [comment]
No, just the default channel. Every time we've tried conda-forge it has downgraded many of our packages and broken the build. The bad libtiff package is `4.0.10-he490001_1001`

**Comment by hmaarrfk** [comment]
Ok thanks.

Can you report this to them in that case? It seems they need to regenerate their package.

If it was an issue on conda-forge, then some of us here can help you. But since you are using the default channel, we can't do much but to support.

I think the correct place to report is:
https://github.com/anacondarecipes/scikit-image-feedstock

Provide them with your install commands and `conda config --show` (maybe remove sensitive info from there if you have it).

**Comment by hmaarrfk** [comment]
hmm, nvm looking back at the stacktrace, it probably best to post it on:
https://github.com/anacondarecipes/pillow-feedstock/issues

**Comment by jontwo** [comment]
Ok, will do. I wasn't sure this was the best place to report it, as the failure seemed to be upstream. Thanks for your help.
