### ISSUE TITLE
non-isotropic blob finding

### ISSUE THREAD

**Issue by ambrosejcarr** [scikit-image/scikit-image#3680]
## Non-isotropic blob finding (in 3d)

I work with RNA-FISH data that is captured by images that are isotropic in x, y, but _samples_ the z plane. The workflow involves blob finding to identify spots in the image, but the non-isotropic nature of the data require a smaller sigma in z. Concretely, spots may be 5-9 pixels wide in (x, y) but only 2-3 pixels in z. As a result, implemented skimage spot finders that support 3d (`blob_log, blob_dog`) have difficulty finding spots in my data. 

Would it be feasible to provide support for non-isotropic spot finding in `skimage`? At the moment we are using the `locate` function in `trackpy`, which implements support for this use case: 

http://soft-matter.github.io/trackpy/dev/generated/trackpy.locate.html

**Comment by jni** [comment]
Hi @ambrosejcarr! Thanks for the suggestion! I agree that the non-isotropic use case is important. It looks like this is tricky with the API, which effectively mirrors the arguments to `np.linspace` for `sigma`. I see two options for supporting this:

- allow vector-like `min_sigma` etc, broadcasting them together. So you would type `min_sigma=(2, 5, 5), max_sigma=(3, 9, 9), num_sigma=3`.
- allow a new argument `sigmas=` that provides directly a 2D array of size `(num_sigmas, ndim)`.

Both of these are ok, and maybe both are worth supporting. Do you have any thoughts about this?

After we settle the API question, from what I can tell the implementation will be easy.

**Comment by ambrosejcarr** [comment]
@jni Thanks for the quick response. I want to check my understanding -- the advantage of the latter case of directly providing the array is that a user could provide non-linear sigmas (e.g. log-space sigmas)? 

Our workflow won't require this, and the former case of vector-like sigmas + `num_sigma` seems simpler for a user, so I'd vote (weakly) in favor of the vector-sigmas case unless you can think of a use case requiring the latter. Both implementations would solve my issue, however, so I'd be fine with either choice.

**Comment by ambrosejcarr** [comment]
I investigated a bit more and I think allowing users to pass an array of sigmas could be potentially dangerous. I'm not an image-processing expert, but it looks like `blob_dog` expects sigmas to be linearly increasing over `(min_sigma, max_sigma)`. Allowing users to pass `sigmas=` could enable users to break the expectations of the algorithm. 

Some other questions arise for `blob_dog`:

1. how to multiply by a non-isotropic sigma to provide scale invariance (I blindly tested with L1 and L2 norms, both of which appear to "work", but I'm not sure which, if either, is correct)
2. how to summarize `sigma` in the output table (the existing implementation expects a scalar `sigma`

**Comment by jni** [comment]
@ambrosejcarr many good points, thank you! I don't know the algorithms in much detail so your help in understanding the assumptions is much appreciated.

One advantage I can think of for `sigmas` is that, long term, I would like to have a consistent interface over many different parts of the API, so the API would be the same whether the function assumes a linear scale or an arbitrary set of sigmas. I'm not sure whether that is enough to justify the choice. I think what I might do short term is start supporting tuples (since that is backwards compatible), and punt on the `sigmas=` idea, because that is also backwards compatible.

Regarding your point about summarising, I think we could use `ndim` columns if a tuple is provided, otherwise a single column.

**Comment by ambrosejcarr** [comment]
Great. I'm looking at `blob_log` now and that method seems easier to extend, since more of the algorithmic complexity is contained in `scipy.ndimage`. I'm happy to make a PR that reflects your advice here, as I've done most of the work for `blob_dog` already, and am following up on the question of invariance for non-isometric Gaussians. 

> I think what I might do short term is start supporting tuples (since that is backwards compatible), and punt on the sigmas= idea, because that is also backwards compatible.

It's a bit easier if instead of tuples, you accept numpy arrays -- will that work?

**Comment by stefanv** [comment]
On Mon, 28 Jan 2019 16:36:24 +0000, Ambrose J Carr wrote:
> It's a bit easier if instead of tuples, you accept numpy arrays --
> will that work?

Usually, we handle anything array-like—tuple, list, or ndarray.  You can
do that easily by using `np.asarray(arg)`.

**Comment by sciunto** [comment]
Closed by #3690.
