### ISSUE TITLE
Difference between paper and code implementation

### ISSUE THREAD

**Issue by qazsweet** [scikit-image/scikit-image#3693]
https://github.com/scikit-image/scikit-image/blob/ca61e8d8d3cd0b3d43e78a3ae1d38ff16595940f/skimage/segmentation/_slic.pyx#L14

I notice there are some differences between the paper (SLIC Superpixels Compared to State-of-the-Art Superpixel Methods) and the code implementation:

1. Instead of Moving cluster centers to the lowest gradient position in a 3*3 neighborhood, use Gaussian filter before RGB2CIELAB conversion. I do not know if they are relative. If yes, why?

2. I notice that the code implementation use the sum of squares of space and color differences, instead of the square root of that. Are these for the balance with m/S?
If this code is built based on slicmex.c which created by Radhakrishna Achanta on 12/01/15,  it defines that:
double invwt = 1.0/((STEP/compactness)*(STEP/compactness));
As this implementation uses: cdef double spatial_weight = float(1) / (step * step)
And in slic_superpixel.py defines:  ratio = 1.0 / compactness, and use as: image * ratio
    (1). the value of compactness should be multiplied by the image value， not be divided
    (2). as the step S is used as the square of S, compactness should also be squared.

**Comment by jni** [comment]
Hi @qazsweet,

1. I don't know about this one. @amueller did the original implementation, but I doubt he remembers much about it so many years later! :joy: There doesn't seem to have been a conscious discussion in #206 about matching exactly the paper implementation. However I do remember looking at their source code back in the day and seeing that it matched. **EDIT:** yeah actually I fixed our implementation! LOL #666 
2. (1) No, higher compactness => more weight to the spatial dimensions => less weight to the color dimensions, which means that we should divide the image (color dimensions) by the compactness. (2) what is happening in our code is that we clustering in euclidean xyzc is the same as clustering in `sqrt(x**2+y**2+z**2+c**2)` which is the same as clustering without the sqrt. I worked out the factors in #666 and you can follow the discussion there for details, including a comparison between the results our source code and the authors' source code.

For reference for future open source archeologists, I went down this trip by searching for closed PRs with the keyword SLIC:
https://github.com/scikit-image/scikit-image/pulls?page=2&q=is%3Apr+is%3Aclosed+slic&utf8=✓

A great advantage of open source development in git in general and on GitHub in particular is being able to look at this history!

**Comment by jni** [comment]
Oh, about the 3x3 movement at the start: I think this is unlikely to influence the results much if at all, so I wouldn't worry about it. The results in #666 bear this out. You can turn off Gaussian smoothing by passing `sigma=0`, but we found that using it gave better results.

**Comment by sciunto** [comment]
I close the issue as there is no update. Please, reopen if the answer is not satisfactory.
