### ISSUE TITLE
Issues with regionprops

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3699]
I'm reviewing `skimage.measure.regionprops` as a prelude to adding support for regionprops to dask-image. This has led me to discover a bunch of weirdnesses about the API that I wanted to agglomerate here. I'll edit this issue as I encounter more.

See also #3180 and #2755 

- [x] #3180 add `regionprops_table` to return a pandas dataframe (optionally)
- [ ] #2755 add keyword argument so that `rp[i]` corresponds to the properties of region `i`.
- [ ] `extent` is defined as the ratio of the object area to the bounding box area. I have no idea why that should be called extent.

**Comment by stefanv** [comment]
The 2nd point makes sense only if you have sequential labels.  Otherwise a dictionary?

**Comment by jni** [comment]
We could do an ordered dict, yes. `ndimage.find_objects` returns a list with `None` in the positions without labels. (Although it does not have an entry for 0 so *that's* annoying!)

**Comment by jni** [comment]
Closing in favour of #4358
