### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'dtype' while using canny edge detector

### ISSUE THREAD

**Issue by talhaanwarch** [scikit-image/scikit-image#3700]
I am trying to apply canny edge detector on an image, but i am getting an error 
AttributeError: 'Image' object has no attribute 'dtype' while using canny edge detector.

Though prewitt and sobel filter works well with no error
```
from PIL import Image
from matplotlib import pyplot as plt
from skimage import feature 

img=Image.open('ribs.jpg').convert('L')
plt.imshow(img)
edge=feature.canny(img, sigma=1)
```

Here is error i am getting 
edge=feature.canny(img,0.001)
Traceback (most recent call last):

  File "<ipython-input-12-ae1391bdb86e>", line 1, in <module>
    edge=feature.canny(img,0.001)

  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\feature\_canny.py", line 159, in canny
    low_threshold = 0.1 * dtype_limits(image, clip_negative=False)[1]

  File "C:\ProgramData\Anaconda3\lib\site-packages\skimage\util\dtype.py", line 49, in dtype_limits
    imin, imax = dtype_range[image.dtype.type]

AttributeError: 'Image' object has no attribute 'dtype'

Can any one help me please

**Comment by hmaarrfk** [comment]
PIL images are not numpy arrays.

So when you try to use `img.dtype`, it won't have a dtype.

The fastest fix for you would be to use `imageio` to load the images. It will use PIL internally, but make the image a `numpy` array for use with the numpy/scipy/scikit-image stack easily.

if you are interested in a more permanant fix, maybe you could issue a pull request.

All you would have to do is add
```
image = np.asarray(image)
```
and write a test.

as one of the first few lines in `canny`

**Comment by jni** [comment]
I don't think that line is necessary, as we only accept NumPy arrays. If anything, we should use `np.asanyarray` to prevent unnecessary copies.

Anyway, @talhaanwarch, I hope @hmaarrfk's comment helped, please continue to follow up if need more help. For now, I am closing the issue.
