### ISSUE TITLE
dask version requirement

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3702]
Why is dask 1.0 required in 0.14.x
https://github.com/scikit-image/scikit-image/blob/v0.14.x/requirements/optional.txt#L1

but dask 0.9.0 required in master
https://github.com/scikit-image/scikit-image/blob/master/requirements/optional.txt#L7

**Comment by stefanv** [comment]
We should require dask 1.0 in master.  This was an attempt to address the NumPy 1.16 incompatibility (which also existed in older versions of dask).

**Comment by hmaarrfk** [comment]
The functionality we use is available in older versions. If somebody installs numpy 1.14 (which we support) wouldn't they be able to use an older dask version?

**Comment by stefanv** [comment]
Yes, but we have no way of saying "dask 0.9 *if* numpy 1.14 otherwise dask 1.0", so upgrading it to 1.0 seems reasonable.  It's a pure Python package, ease to install.

**Comment by hmaarrfk** [comment]
ok

**Comment by hmaarrfk** [comment]
That is true, but python 3.4 doesn't have dask 1.0 on pypi
https://github.com/scikit-image/scikit-image/pull/3695/commits/e22886ef4e33a2268425346f4ca82e00eaeb8c1d

The minimum version requirements are problematic. The last time we tried to upgrade them, there was some incompatibility. 

I don't think we can expect scikit-image to be installed with any combination of software so long as they meet the minimum version requirements.

I would consider Numpy 1.16 + Dask 1.0.0 something that the package manager would have to do, not scikit-image.
