### ISSUE TITLE
scikit-image 0.14.2 failes to install into virtual environment with python 3.4.9.

### ISSUE THREAD

**Issue by odinsbane** [scikit-image/scikit-image#3713]
## Description

When attempting to pip install scikit-image the process fails with ImportError: No module named 'skimage'.

Here is a paste of the full output. https://paste.pound-python.org/show/hZVjxLQPbFLZGFmY8GLE/

## Way to reproduce

virtualenv3 test-env
./test-env/bin/pip install scikit-image

# Paste the output of the following python commands
```
>>> from __future__ import print_function
>>> import sys; print(sys.version)
3.4.9 (default, Aug 14 2018, 21:28:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
>>> import platform; print(platform.platform())
Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
>>> 
```

**Comment by soupault** [comment]
@odinsbane could you, please, try to install Cython before executing `pip install scikit-image` and report if that helps?

**Comment by odinsbane** [comment]
When I pip install cython from a fresh virtual environment nothing changes.

Installing collected packages: cython
Successfully installed cython-0.29.4

```
./scikit-test/bin/pip install cython
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting cython
  Using cached https://files.pythonhosted.org/packages/63/a4/80dd4bacb66736a7762b2a5b8dfc66ce18d52793fd884771db104f567390/Cython-0.29.4-cp34-cp34m-manylinux1_x86_64.whl
Installing collected packages: cython
Successfully installed cython-0.29.4
```
The output of of the pip install scikit-image doesn't appear to change. I can repaste it if the details matter.

**Comment by odinsbane** [comment]
Yes we are currently using centos. Thank you for the suggestions. We can get it to work, but I thought this should be reported. I can see needing to improve our install process in the near future.

It seemed odd to break an installation process at a minor revision, 0.14.2 vs 0.14.1. I also thought that pip/pypi has some sort of version checks so that if a version doesn't work with a python version it doesn't get selected. For example if version >=0.14.2 doesn't work with python 3.4.9, then that version wouldn't be available through pip.

**Comment by hmaarrfk** [comment]
I'm sympathetic with you. My suggestions were more to help you get going ASAP. Helping us debug would probably take longer than installing miniconda with python 3.6 or 3.7.

We don't really have ways, other than with CIs

**Comment by jni** [comment]
> It seemed odd to break an installation process at a minor revision, 0.14.2 vs 0.14.1. I also thought that pip/pypi has some sort of version checks so that if a version doesn't work with a python version it doesn't get selected. For example if version >=0.14.2 doesn't work with python 3.4.9, then that version wouldn't be available through pip.

@odinsbane you're absolutely right. It looks like our metadata on PyPI is incorrectly listed as `>= 2.7`, where it should only include 2.7 and 3.5+.

Regarding the patch release update, 0.14 is a funny beast because it's our LTS release for 2.7 support, so more major things are expected to happen on those patches than would normally be the case. We did not prioritise 3.4 support since most 3.4 users have been happy to upgrade to 3.5 and above.

@stefanv do you know if there's a way to change the classification without issuing a new release? And anyway a new release wouldn't solve this problem... =\

**Comment by stefanv** [comment]
Did we ever explicitly break 3.4 support?

**Comment by jni** [comment]
@stefanv iirc 3.4 wheels weren’t building so we dropped them in the crunch to get 0.14.2 out?

**Comment by stefanv** [comment]
Time to get 0.14.3 out.  @jni Do you have bandwidth for pushing a point release?

**Comment by jni** [comment]
@stefanv are the wheels building now?

**Comment by stefanv** [comment]
https://travis-ci.org/scikit-image/scikit-image-wheels/builds/489709632
https://ci.appveyor.com/project/scikit-image/scikit-image-wheels/builds/22177372

**Comment by jni** [comment]
Sooo... Yes and no. Ok.

**Comment by stefanv** [comment]
They're both green?

**Comment by jni** [comment]
There is no Py3.4 on AppVeyor as far as I can tell.
