### ISSUE TITLE
skip problematic corner tests

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3715]
## Description
coner has been segfaulting on OSX for a while

See: https://github.com/scikit-image/scikit-image/pull/3617
I'm about 90% sure this is an issue with the wheel that scipy has been shipping out:
https://github.com/scipy/scipy/issues/9751
or a compiler bug :/

Since we have isolated what we need to push this issue upstream, is it safe to skip the doctests and conditionally skip the tests that cause the segfault on OSX?

## Way to reproduce
https://github.com/scikit-image/scikit-image/pull/3695#issuecomment-460106872

- Scipy: modern 1.2, 1.1?
- Numpy: modern
- OSX, Xcode 9.0 10.12.

Passes on Xcode 9.4, 10.13

**Comment by jni** [comment]
I don't think we want to skip *all* the doctests, and I don't know how to skip specific ones. (note that in my testing, it seemed that doctest skip didn't prevent the code from being run, just the output from being checked... And anyway we only want to skip it in certain circumstances.)

**Comment by hmaarrfk** [comment]
Upgrading score worked for us. Could be a Mac bug
