### ISSUE TITLE
No module named skimage.feature

### ISSUE THREAD

**Issue by darrahts** [scikit-image/scikit-image#3731]
## Description
Continuously getting "no module named skimage.feature"

## Way to reproduce
```
import skimage.feature
```

## Version information
```
3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
Linux-4.4.0-134-generic-x86_64-with-LinuxMint-18.1-serena
numpy version: 1.16.1
AttributeError: module 'skimage' has no attribute '__version__'
```
## attempts to correctly install scikit-image
```
(autonomous) tdarrah@tdarrah-GE72-6QD ~/Documents/autonomousVehicles $ history | grep scikit-image
 2013  conda install -c conda-forge scikit-image
 2016  pip install scikit-image
 2017  conda remove scikit-image
 2018  pip install scikit-image
 2020  pip uninstall scikit-image
 2023  conda install scikit-image
 2026  history | grep scikit-image
```
## skimage imports fine, but nothing comes with it

```
(autonomous) tdarrah@tdarrah-GE72-6QD ~/Documents/autonomousVehicles $ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import skimage
>>> import skimage.feature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'skimage.feature'
>>> skimage.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'skimage' has no attribute '__version__'
>>> skimage.__dict__
{'__name__': 'skimage', '__doc__': None, '__spec__': ModuleSpec(name='skimage', loader=None, origin='namespace', submodule_search_locations=_NamespacePath(['/usr/lib/python3/dist-packages/skimage'])), '__package__': 'skimage', '__path__': _NamespacePath(['/usr/lib/python3/dist-packages/skimage']), '__loader__': <_frozen_importlib_external._NamespaceLoader object at 0x7f9d52ff2f28>}
>>> 

```

**Comment by darrahts** [comment]
So I noticed the path - I'm using conda install inside my conda environment but it isnt using my conda path... ??

**Comment by hmaarrfk** [comment]
do you have a directory called `skimage`? you shouldn't

**Comment by hmaarrfk** [comment]
What are the outputs of 
```
which python
echo $CONDA_PREFIX
```

**Comment by hmaarrfk** [comment]
Also, i'm pretty sure conda dropped support for Python 3.5. Are you trying to install python 3.5?

**Comment by darrahts** [comment]
here are all the directories on my machine with skimage:
```
/usr/lib/python3/dist-packages/skimage
/home/tdarrah/anaconda3/pkgs/scikit-image-0.13.1-py27h14c3975_1/lib/python2.7/site-packages/skimage
/home/tdarrah/anaconda3/pkgs/scikit-image-0.13.1-py27_0/lib/python2.7/site-packages/skimage
/home/tdarrah/anaconda3/pkgs/scikit-image-0.14.1-py37he6710b0_0/lib/python3.7/site-packages/skimage
/home/tdarrah/anaconda3/lib/python3.7/site-packages/skimage
/home/tdarrah/anaconda3/envs/autonomous/lib/python2.7/site-packages/skimage
```
So looking at this, skimage is installing for python 2.7 and 3.7, yet my conda environment is set to use 3.5.2. When using `conda install <package>` isn't it suppose to automatically resolve these version issues?

```
(autonomous) tdarrah@tdarrah-GE72-6QD ~ $ which python
/home/tdarrah/anaconda3/envs/autonomous/bin/python
(autonomous) tdarrah@tdarrah-GE72-6QD ~ $ echo $CONDA_PREFIX
/home/tdarrah/anaconda3/envs/autonomous
```

I just set up my conda environment yesterday and due to tensorflow not supporting 3.7 yet, and I've been using 3.5 for awhile now, I set up my environment for 3.5.2. I have not had any issues with any other package that is typically problematic such as tensorflow, keras, or opencv3.

**Comment by darrahts** [comment]
This seems to be an issue with my anaconda installation or environment. I dont have any issues importing skimage.feature outside of anaconda... If you can still help troubleshoot that would be very helpful but otherwise I understand if you close the issue.

**Comment by hmaarrfk** [comment]
Can you try creating a new environment? Please ensure that you aren't in the `(autonomous)` environment.

TF should support 3.6. Use that. Or 2.7.

**Comment by darrahts** [comment]
Sir thank you very much. Good to go.

**Comment by hmaarrfk** [comment]
nice, please close !

**Comment by bebosudo** [comment]
Hi, I'm getting the same error if I try to load the sub-module `feature` from the package name without a separate import, like:
```bash
python -c 'import skimage; print(skimage.feature)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'skimage' has no attribute 'feature'
```
while it works for other modules:
```bash
$ python -c 'import skimage; print(skimage.measure)'
<module 'skimage.measure' from '~/..venv../lib/python3.7/site-packages/skimage/measure/__init__.py'>

$ python -c 'import skimage; print(skimage.io)'
<module 'skimage.io' from '~/..venv../lib/python3.7/site-packages/skimage/io/__init__.py'>
```

If I import the sub-module explicitly, then it works:
```bash
$ python -c 'import skimage; from skimage import feature; print(skimage.feature)'
<module 'skimage.feature' from '~/..venv../lib/python3.7/site-packages/skimage/feature/__init__.py'>
```

**Comment by jni** [comment]
Theoretically, none of the submobules should work. I think this is a weird interaction of the fact that `skimage/__init__.py` imports things from `util/` and #3397. `util` ends up importing other submodules (such as `exposure`) which imports `color`, and so on. I haven't traced it back to `measure`, but I do expect that this is why this is happening.

At any rate, in Python, in general, sub-packages are not implicitly imported. To use `skimage.feature`, you shouldn't just `import skimage` but `import skimage.feature`.

**Comment by manish33scss** [comment]
function has been removed (use skimage.registration.phase_cross_correlation instead).
