### ISSUE TITLE
Visual image comparison 

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#3736]
## Description

Various techniques exist to help the eye to compare images. I haven't done a full bibliography on the topic, but we can list checkerboards, differences, fading...

See https://fr.mathworks.com/help/images/ref/imshowpair.html
 or play with https://www.diffchecker.com/image-diff

This can be used by users but also in our gallery to show edge detection, geometrical transformations...

Discussions are open on methods, API, etc.

**Comment by jni** [comment]
Cool, I like this idea. It should go wherever we put matplotlib-related stuff... =)

**Comment by lagru** [comment]
I'll give this a shot.

**Comment by sciunto** [comment]
@lagru I started to write a functions doing something similar to the matlab feature. Have you made some progress? I can open a PR to discuss on a concrete code. There are room for debates on the api.

**Comment by lagru** [comment]
@sciunto I've played around with it a little bit but got nothing worth a PR. Please go ahead and feel free to tag me!

**Comment by sciunto** [comment]
Ok, it's not very advanced on my side too, and your comments will be welcome.
