### ISSUE TITLE
Builds broken with QT 5.12

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3739]
## Description
Qt 5.12 was released today, and likely broke matplotlib. 
https://travis-ci.org/scikit-image/scikit-image/jobs/491337465#L1931

https://travis-ci.org/scikit-image/scikit-image/jobs/491337465#L2058

Windows seems ok???

## Way to reproduce
See travis, linux 5.12

**Comment by jni** [comment]
Fun times! Shall we pin PyQt!=5.12 in our testing dependencies?

**Comment by hmaarrfk** [comment]
5.12.0, or 5.12.1???

**Comment by jni** [comment]
5.12.anything, no? I mean, I don't know, you tell me LOL.

**Comment by hmaarrfk** [comment]
Did upstream identify anything?

**Comment by hmaarrfk** [comment]
OMG I pushed to master......... So sorry

**Comment by hmaarrfk** [comment]
Well it seemed to have worked..... But maybe we should keep the issue for now

**Comment by jni** [comment]
@hmarrfk I’d prefer if you reset the changes to master (being extra careful it should go without saying) and issued a pull request as usual.

**Comment by hmaarrfk** [comment]
Ok. I didn’t know if two wrongs made a right. I didn’t notice that the default behavior of the editor changed....

**Comment by jni** [comment]
@hmaarrfk well I used the word "reset" on purpose but it seems we don't have that power, which is a relief, tbh. ;) So it wasn't so much two wrongs (although they were two wrongs) as sweeping the first wrong under the rug.

At any rate, it seems my historical distrust of editor-based git remains warranted.

**Comment by tacaswell** [comment]
If you reset master there is a race condition where someone could have pulled after the bad push but before the reset. You will have to find everyone who did and hard-reset their local repositories.  I think once it is pushed to master on github it is out there with no (or only very very expensive) take-backs.

**Comment by stefanv** [comment]
Branch protection is enabled for `master`, I see.  @jni @hmaarrfk Did you toggle this after the incident?  If not, I am unsure why the commit went in.

**Comment by hmaarrfk** [comment]
no no, i didn't reset it, i just pushed an other commit. I've dealt with enough race conditions on my own machines to know better.

I Ididn't change any settings on scikit-image. Trying to use my rights sparingly.....

**Comment by jni** [comment]
@tacaswell 

> If you reset master there is a race condition where someone could have pulled after the bad push but before the reset.

I'm aware! =) Yesterday less than an hour after @hmaarrfk had pushed, I thought the risk was worthwhile. Now I don't. =)

@stefanv 

> did you toggle this after the incident?

No, neither of us touched the settings. It just so happens that the current settings (apparently) allow pushes but not force pushes.

**Comment by grlee77** [comment]
Yes, the default branch protection seems to only forbid deleting the branch and force-pushing to the branch:
https://help.github.com/articles/about-protected-branches/#branch-protection-settings

**Comment by stefanv** [comment]
> Typically, the panic sets in within much less than an hour, so within about three minutes you toggle the GitHub branch protection, and rip that commit right out of there.  *Mischief managed*, you sigh hopefully, until you realize that in your panic you pushed a few extra tags upstream, triggering Debian to start a new release. Fortunately, you realize your next mistake in time, too, despite all the adrenaline by now coursing through your veins, so you push everything carefully back into the pre-commit-that-nearly-ended-the-world shape.  Debian sends angry emails, but you just pretend to know nothing, and ensure them you have no idea what they're talking about.  Users start making PRs with odd commits that don't show up on the master branch, but you quickly instruct them to rebase, because they "obviously messed up their PRs".  And, within a few weeks, even the selective few people who noticed forgets all about the whole ordeal, and life returns to normal.

OK, jokes aside ;)  If you reset master within a minute or three, I think the risk would have been quite low.  And, even if a few people pulled, it's not the end of the world; git is very good at rewriting history :)  But, it's a good reminder to us all to follow good naming conventions on our branches.  I, personally, use `stefanv` for my own remote, and trained myself never to do `git push origin master`, unless, well, that's the intended course of action.  Other conventions are also to use `upstream` for skimage, which is even safer; but if you fork/clone from GitHub it's a bit inconvenient.

**Comment by hmaarrfk** [comment]
Yeah, I waas using the github editor on my tablet. When you don't have permissions, it creates a new branch on your own repo and a PR automatically.... (origin is my own fork hmaarrfk)

**Comment by stefanv** [comment]
I recently tried the GitHub online merge tool.  I had to do a force push to recover from that situation as well :)

**Comment by jni** [comment]
Ah, the whole thing makes more sense now. If it's like the desktop web editor, there's a tick box that you can check at the bottom. But I guess you've already seen this. =)

**Comment by hmaarrfk** [comment]
anyway, seem like there is some noise going on upstream in matplotlib 
https://github.com/matplotlib/matplotlib/pull/13406

**Comment by tacaswell** [comment]
> I, personally, use `stefanv` for my own remote, and trained myself never to do `git push origin master`, unless, well, that's the intended course of action.

I also have mine set up so 'origin' is read-only of the canonical repo and have a second remote named `DANGER` that is the read/write remote of the same.

**Comment by jni** [comment]
Well, none of our tricks would have worked in this case. Only GitHub changing the default to never be push to master on their web editor would have helped.

**Comment by jni** [comment]
BUT, the DANGER trick is nice. =)
