### ISSUE TITLE
local_maxima should return boolean array

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#3746]
Basically the output of `local_maxima` (and `local_minima`) should return a boolean array. Right now the returned dtype uses uint8 (1s and 0s) which can't be used to index numpy arrays as a mask. See this discussion thread in https://github.com/scikit-image/scikit-image/pull/3245#discussion_r255344610.

What is the correct depreciation strategy here?

cc @jni

**Comment by stefanv** [comment]
I think this can be considered a bug, and should simply be fixed.
