### ISSUE TITLE
v0.14.3 v0.15.0 and v0.16.0

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3754]
In light of the recent patent discussion in:
https://github.com/scikit-image/scikit-image/pull/3751

I suggest we release 0.15.0 breaking backward compatibility with 0.14.2 that removes seam carving bu keeps python 2.7 compatibility.

Release 0.16.0 should be the first python only 3 release.

cc: @scikit-image/core

**Comment by JDWarner** [comment]
Disagree, see ongoing discussion in linked PR.

**Comment by hmaarrfk** [comment]
@JDWarner said:

> I'm -1 on this, as it's just a backport in different clothing - also contradicts the long-term support guarantee and statements made about 0.14.x being the final 2.x support release. Also, the LTS of 0.14.x is broken unless we want to continually do TWO backports from the dev branch moving forward.
>
> It might be prudent not to start new issues about this until there's some consensus, as sometimes this sort of thing only becomes a problem with (bad) publicity.

**Comment by hmaarrfk** [comment]
Unfortunately, I think that something has to give. It seems that we have decided that the particular patent was worthy of removal from 0.15.

That said, we would still be actively supporting code that includes in in Feb 2019???

Seems like a contradiction.

The solution to me seems to appologize to packagers, and to tell them that due to new information, we cannot release 0.14.3, and because of backward incompatibility, we are releasing it as 0.15. It is then on them, to decide to release 0.14.3 in Feb/March 2019.

**Comment by hmaarrfk** [comment]
we can bump the deprecation warnings and whatnot. 

but the important thing here is that some version of scikit-image continues to support 2.7 users while they have enough time to transition to python 3.

In this sense, I feel like we are fufilling the intent of the LTS release, but clearly marking that we did break the API, on this one, single aspect, due to legal, and not technical reasons.

**Comment by jni** [comment]
No, personally I'm dismissing this out of hand. People interested in skimage for Py2.7 will have pinned their dependencies to 0.14.*, and that is the version that we have pledged to support. I certainly have zero interest in maintaining two LTS branches.

Alternative proposal: put a warning about the patent in the docstring and example. on 0.14.x that the algorithm is patented.

**Comment by JDWarner** [comment]
Agree with @jni.  None of the above is definite and this is overly complicated.  It's quite simple and in my strongest opinion correct to simply not backport the linked PR, which is merged into 0.15 as planned for future Python 3.x only release.

**Comment by jni** [comment]
@hmaarrfk there is no contradiction: it is merely a matter of what *cost* we are willing to pay to do the right thing. Happy to remove going forward, but complicating our release policy is too much. And I think the comment in the docstring and example would be sufficient.

**Comment by hmaarrfk** [comment]
yeah, i understand. 

Looking back, the cost of the LTS is definitely high.

I think effort on the LTS (this discussion included) has already delayed 0.15 enough.

On that note, are there any blockers left for 0.15?

**Comment by hmaarrfk** [comment]
Sorry for moving the discussion here @JDWarner I never know if people want discussions to happen in closed PRs or Issues. In this case, it definitely makes sense to have it there.
