### ISSUE TITLE
Error in compare_ssim documentation

### ISSUE THREAD

**Issue by NOhs** [scikit-image/scikit-image#3755]
## Description
In the documentation of the argument `full` in the compare_ssim documentation it reads:

> If True, return the full structural similarity image *instead* of the mean value.

(Emphasis mine).

However, the following snippet shows, that the full array is returned *in addition* to the mean value:

## How to reproduce
```python
a, b = compare_ssim(np.zeros((7,7,7)),np.zeros((7,7,7)), full=True)
print(a)
# 1.0
print(b.__class__.__name__)
# 'ndarray'
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Windows-10-10.0.16299-SP0
scikit-image version: 0.15dev
numpy version: 1.14.3
```

**Comment by hmaarrfk** [comment]
I'm not sure what was intended, but it seems that maybe if we change the behaviour it would break people's code.

Maybe the docs should be updated?

**Comment by soupault** [comment]
>Maybe the docs should be updated?

Yes, clearly.

@NOhs Good catch! Would you like to submit a Pull Request?
