### ISSUE TITLE
Implement efficient and elegant threshold_multiotsu

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3756]
In https://github.com/scikit-image/scikit-image/pull/3385, @alexandrejaguar got started on `threshold_multiotsu`. We ended up with two competing implementations: a fast Cython version that had a lot of repetitive code, and a slow Python version that elegantly used `itertools` to generalise to many classes. We were unable to reconcile the two versions but there's probably a way. I'm raising this issue as a TODO for future generations. =)

**Comment by alexandrejaguar** [comment]
@jni sorry for deleting the branch, did something really bad here! I think the best way would be to use the Cython version @emmanuelle implemented using `itertools`.

**Comment by alexandrejaguar** [comment]
Closed due to solution in #3872.
