### ISSUE TITLE
microaneurism image has no license description

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3769]
Also see https://github.com/scikit-image/scikit-image/pull/3765, https://github.com/scikit-image/scikit-image/issues/3623

**Comment by sciunto** [comment]
Cc @ThomasWalter

**Comment by ThomasWalter** [comment]
Which formula would you propose? 

`Notes`
`    -----`
`    No copyright restrictions. CC0 given by owner (Andreas Maier).`

**Comment by soupault** [comment]
Closed in #3778.
