### ISSUE TITLE
Use `mean` method in `threshold_mean`

### ISSUE THREAD

**Issue by jakirkham** [scikit-image/scikit-image#3782]
It would be helpful when using [`threshold_mean`]( http://scikit-image.org/docs/dev/api/skimage.filters.html#threshold-mean ) with other array libraries to preserve the input array type. An easy way to do this would be to use the `mean` method of the array instead of [`np.mean`]( https://github.com/scikit-image/scikit-image/blob/f9046b4f21d090417fb28a038b612d120c9fa5db/skimage/filters/thresholding.py#L714 ).

**Comment by jni** [comment]
@jakirkham but `__array_function__` should fix this issue, right?

**Comment by jakirkham** [comment]
That would only work for users on NumPy 1.16.0+.

However it looks like NumPy as old as 1.11.0 will [check and use the method first]( https://github.com/numpy/numpy/blob/4092a9e160cc247a4a45724579a0c829733688ca/numpy/core/fromnumeric.py#L2879-L2880 ).

So it looks like we have the behavior we want already :)

**Comment by jni** [comment]
Good-oh, I'm gonna close this, reopen if you disagree. =)

btw, based on the number of complaints from users on NumPy 1.16 / skimage<=0.14, I don't think it's a huge hurdle to only support future NumPy. =P

**Comment by jakirkham** [comment]
Well NEP 18 requires a bit more than that actually (e.g. other array libraries that support it and the end user opting in). So we do want to keep in mind solutions that bridge the gap for the interim. Though we have done this here already so agree this is good.
