### ISSUE TITLE
scikits_image-0.14.2 Build System is looking for nonexistant DEPENDS.txt

### ISSUE THREAD

**Issue by TheChymera** [scikit-image/scikit-image#3784]
## Description
The build process crashes due to an inability to find `DEPENDS.txt` which afaict from the code is never mentioned and nowhere present.

## Way to reproduce
```python
python2.7 setup.py build
```

## Version information
```python
In [1]: from __future__ import print_function

In [2]: import sys; print(sys.version)
3.6.8 (default, Mar  4 2019, 19:32:41) 
[GCC 8.2.0]

In [3]: import platform; print(platform.platform())
Linux-4.20.2-gentoo-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-gentoo-2.6

In [5]: import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.16.1
```

Here is the full [build.log](https://github.com/scikit-image/scikit-image/files/2933830/build.log).

**Comment by stefanv** [comment]
I don't see any mention of that file in the 0.14.2 source code.  Could you please ensure that you are doing a fully clean build?

**Comment by TheChymera** [comment]
You're right, this was left over from a previous version. Thanks :)
