### ISSUE TITLE
Anaconda Defaults doesn't have 0.14.2. Fails with numpy 1.16 (second time)

### ISSUE THREAD

**Issue by aopisco** [scikit-image/scikit-image#3786]
## Description

When doing 
`from numpy.lib.arraypad import _validate_lengths`

I'm getting the following error
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-30d1a12bd26c> in <module>
----> 1 from numpy.lib.arraypad import _validate_lengths

ImportError: cannot import name '_validate_lengths'
```
even after force-reinstalling scikit-image and numpy.

pip install scikit-image --force-reinstall
Successfully installed PyWavelets-1.0.2 cloudpickle-0.8.0 cycler-0.10.0 dask-1.1.3 decorator-4.3.2 kiwisolver-1.0.1 matplotlib-3.0.3 networkx-2.2 numpy-1.16.2 pillow-5.4.1 pyparsing-2.3.1 python-dateutil-2.8.0 scikit-image-0.14.2 scipy-1.2.1 setuptools-40.8.0 six-1.12.0 toolz-0.9.0

pip install numpy --force-reinstall
Successfully installed numpy-1.16.2

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
from numpy.lib.arraypad import _validate_lengths
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
Linux-4.4.0-1075-aws-x86_64-with-debian-stretch-sid
scikit-image version: 0.14.2
numpy version: 1.16.2
```

**Comment by stefanv** [comment]
This issue seems unrelated to scikit-image.  You are importing a private member of NumPy that no longer exists.

There used to be an issue with skimage 0.14.1, where we would trigger this issue.  But that no longer happens with 0.14.2.

**Comment by hmaarrfk** [comment]
@stefanfv unfortunately Anaconda Defaults didn't package 0.14.2 yet. 

@aopisco how are you installing your packages?

Do the solutions listed https://github.com/scikit-image/scikit-image/issues/3780 help?

**Comment by aopisco** [comment]
@hmaarrfk thanks for the link, I had to downgrade to `numpy 1.15`

**Comment by hmaarrfk** [comment]
no problem.

**Comment by stefanv** [comment]
@aopisco Please let us know how you installed 0.14.2.  It seems like you are running 0.14.1, but you are reporting 0.14.2.

**Comment by aopisco** [comment]
I installed 0.14.2 from conda-forge but I got the same error so I decided to downgrade numpy instead

**Comment by stefanv** [comment]
@hmaarrfk Is that expected? Should not be.

**Comment by jni** [comment]
There is a possibility of pip and conda versions of NumPy interfering with each other. (Perhaps also scikit-image.)

**Comment by hmaarrfk** [comment]
yeah, sometimes pip installs an other package that just messes with your environment.

I often have to nuke my environment if that happens.

Generally, I would use full conda-forge. I notice your build of python is from defaults, so your environment is probably a little frankenish.

I think we should just ask Anaconda to release 0.14.2

**Comment by grlee77** [comment]
Closing this as stale. Anaconda defaults does have 0.14.2 now (as well as 0.15.0 and 0.16.2)

**Comment by hmaarrfk** [comment]
Thanks for following up
