### ISSUE TITLE
0.14.2 test suite fails with `NameError: global name 'osp'`

### ISSUE THREAD

**Issue by TheChymera** [scikit-image/scikit-image#3789]
## Description

The test suite does not pass. As far as I know `osp` is a common alias for `os.path`. Is this a typo in the code? Or related to the base python version?

## Way to reproduce
```python
pytest -vv
```

## Version information
```python
2.7.16 (default, Mar  4 2019, 19:30:43) 
[GCC 8.2.0]
Linux-4.20.2-gentoo-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-gentoo-2.6
scikit-image version: 0.14.2
numpy version: 1.16.1
```
OR
```python
3.6.8 (default, Mar  4 2019, 19:32:41) 
[GCC 8.2.0]
Linux-4.20.2-gentoo-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-gentoo-2.6
scikit-image version: 0.14.2
numpy version: 1.16.1
```
## My output
[build.log](https://github.com/scikit-image/scikit-image/files/2937545/build.log)

**Comment by stefanv** [comment]
This was fixed in ddfec94351c3e1ccc6f5a79d41acaacea570b8af on master, but not backported.  Will do so now.

**Comment by TheChymera** [comment]
@stefanv @sciunto was this backported to any release, or is it only available via the live github download?

**Comment by hmaarrfk** [comment]
github for now

**Comment by jni** [comment]
@TheChymera we aim to release 0.14.3 with the fix in the next few days.

**Comment by TheChymera** [comment]
any uupdates on this?
