### ISSUE TITLE
Update draw.polygon example

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3805]
## Description

This SO question shows that polygons are considered closed by default by `draw.polygon`, but our docstring example repeats the first vertex for no good reason, which is confusing:

https://stackoverflow.com/questions/55114005/skimage-polygon-function-why-does-the-last-vertice-repeats-in-the-polygon-docum

I suggest we remove the trailing [1, 1] from the example.

**Comment by stefanv** [comment]
:+1:
