### ISSUE TITLE
skimage.segmentation.watershed not giving expected output.

### ISSUE THREAD

**Issue by Vapster** [scikit-image/scikit-image#3808]
## Description
watershed method from skimage.segmentation is not working as it supposed to with mask parameter (or at least not as I assumed)
I think it is even segmenting area outside of mask. Some kind of dots (at regular interval) are in segmented image.
I have attached original (image which I want to segment), mask and segmented image.

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
import SimpleITK
from matplotlib import pyplot as plt
from skimage.segmentation import clear_border, watershed, mark_boundaries

org = SimpleITK.ReadImage("original.png")
mask = SimpleITK.ReadImage("mask.png")
org_array = SimpleITK.GetArrayFromImage(org)
mask_array = SimpleITK.GetArrayFromImage(mask)

segments_watershed = watershed(org_array, 1000, mask=mask_array)
plt.imshow(segments_watershed, cmap="gray")
```
![original](https://user-images.githubusercontent.com/22271547/54581269-f07baa00-4a31-11e9-926f-87a7c5a9a7e3.png)
![mask](https://user-images.githubusercontent.com/22271547/54581275-f83b4e80-4a31-11e9-867b-ca4952ae7a2f.png)
![seg](https://user-images.githubusercontent.com/22271547/54581282-ff625c80-4a31-11e9-87d4-3f5452d471b8.png)

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
>>> from __future__ import print_function
>>> import sys; print(sys.version)
3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 64 bit (AMD64)]
>>> import platform; print(platform.platform())
Windows-10-10.0.17134-SP0
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.14.1
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.15.4
```

**Comment by jni** [comment]
Thanks for the report, @Vapster! [What's happening](https://github.com/scikit-image/scikit-image/blob/4f6bf7ae8af434e1be9fa83072fd7c84c1a7e758/skimage/morphology/watershed.py#L58-L60) is that we are creating markers (the points from which the watershed begins) over the whole image, rather than limiting ourselves to the mask. Then, the actual watershed only happens within the mask, but you're left with those tiny, unused markers everywhere.

It's a matter of making sure the marker creation is aware of the mask. Shouldn't be too hard to fix.
