### ISSUE TITLE
meijering and sato can't be imported in filters

### ISSUE THREAD

**Issue by nick917** [scikit-image/scikit-image#3814]
## Description
Hi, in skimage 0.15, it seems like it supports meijering and sato but they can't be imported.
Also argument 'black_ridges' is not supported, hessian and frangi

Example from document doesn't work.
http://scikit-image.org/docs/dev/auto_examples/edges/plot_ridge_filter.html

Thanks

## Way to reproduce
python
from skimage.filters import meijering
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```


## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]
Linux-4.4.0-142-generic-x86_64-with-Ubuntu-16.04-xenial
scikit-image version: 0.15.dev0
numpy version: 1.14.6

```python
# your output here
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'meijering'
![error](https://user-images.githubusercontent.com/4983968/54879811-a06a6200-4dfa-11e9-91fd-9b564b1bf794.PNG)

```

**Comment by hmaarrfk** [comment]
Can you please finish filling out the template. Include the two sections you did not complete.

![image](https://user-images.githubusercontent.com/90008/54875271-2c1bc880-4dd2-11e9-9237-e07215c3c6d5.png)

As you can see, it seems to work on my computer. Seeing your output would become very valuable...

**Comment by nick917** [comment]
oh, interesting. I thought the 0.15 dev features are not fully supported. 
One difference is you used anaconda. 
By the way, do you have windows whl, so I can test in windows also.

Thanks

**Comment by jni** [comment]
0.15 is not released yet, so no windows wheels are available. I suspect that what is happening here is that you have not updated your 0.15.dev0 to the latest master branch...?

**Comment by hmaarrfk** [comment]
You can try the nightly wheels
https://github.com/scikit-image/scikit-image-wheels#using-the-repository

But i never use those, so i'm not sure about how they work, otherwise you can read some new docs we wrote to setup your dev environment.
http://scikit-image.org/docs/dev/contribute.html#build-environment-setup

**Comment by nick917** [comment]
Actually I used nightly linux wheel:
scikit_image-0.15.dev0+20190227005104-cp35-cp35m-manylinux1_x86_64.whl
from 
https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/

Thanks Mark and Juan.
