### ISSUE TITLE
scikit image error

### ISSUE THREAD

**Issue by rutujar** [scikit-image/scikit-image#3815]
desc:
i use ubuntu version 16.04.  i am facing the issues in skimage in python 3.
sudo apt-get install python-skimage

error:

from skimage.filters import threshold_adaptive
  File "/usr/lib/python3/dist-packages/skimage/__init__.py", line 63, in <module>
    from skimage._shared.utils import deprecated as _deprecated
  File "/usr/lib/python3/dist-packages/skimage/_shared/utils.py", line 4, in <module>

**Comment by jni** [comment]
@rutujar the error message seems incomplete...

**Comment by rutujar** [comment]
when i am running a python file,

$ python recognize.py --images images/7.jpg
Traceback (most recent call last):
  File "license_plate.py", line 2, in <module>
    from skimage.filters import threshold_adaptive
ModuleNotFoundError: No module named 'skimage'
Traceback (most recent call last):
  File "recognize.py", line 17, in <module>
    for imagePath in sorted(list(paths.list_images(args["images"]))):
NameError: name 'paths' is not defined

**Comment by hmaarrfk** [comment]
Hi @rutujar, it is pretty hard to help you without seeing your actual code
Please have a quick skim through to help us help you.

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
https://stackoverflow.com/help/mcve

**Comment by rutujar** [comment]
Hi, i think it is not a issue with code. its pointing to import statement @hmaarrfk error in skimage package,

**Comment by hmaarrfk** [comment]
Hi @rutujar I understand, but can you please include the information that we requested in our issue template. You seem to have skipped quite a few critical parts

## Description


## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```


## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by hmaarrfk** [comment]
In your case, us understanding your python system version is critical.

**Comment by rutujar** [comment]
I am using python 3

**Comment by rutujar** [comment]
@hmaarrfk 
output:
3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609]
Linux-4.15.0-46-generic-x86_64-with-Ubuntu-16.04-xenial
scikit-image version: 0.14.2
numpy version: 1.16.2

**Comment by hmaarrfk** [comment]
Well scikot image is importing. Now maybe you can provide us with the exact line of code that makes things fail.


Finally, your packages seem a little too new for having been installed through apt. Not sure if you enabled some kind of non standard PPA
