### ISSUE TITLE
Add minimal distance argument to local_maxima

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#3816]
https://github.com/scikit-image/scikit-image/pull/3809#issuecomment-475874038 got me thinking that an argument specifying the minimal allowed euclidean distance between maxima could be very useful. I imagine it to work akin to [this implementation](https://github.com/scipy/scipy/blob/715f3ad659fbe1f8e4b9412bf4433f85cf21dff5/scipy/signal/_peak_finding_utils.pyx#L90-L157) in SciPy. The difficulty for the n-dimensional case is to only evaluate close neighbors as otherwise the complexity grows very unfavorably with the number of maxima. I wonder whether a [KDTree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html) could help optimizing that particular problem. 

It's only an idea right now but before I investigate I'd like to know if there is an interest in adding this feature.

**Comment by stefanv** [comment]
On Tue, 26 Mar 2019 05:43:20 -0700, Lars Grueter wrote:
> It's only an idea right now but before I investigate I'd like to know
> if there is an interest in adding this feature.

A big +1 from me.  This is requested very often, and I've needed to same
in the past (fully expecting the current implementation to do that, but
learning otherwise each time).

**Comment by lagru** [comment]
That's good to know. :)

Thinking about this there is another point that comes into play because [local maxima](http://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.local_maxima) are not restricted to a single sample. That means there are multiple approaches to how the distance between maxima is measured:
- (A) Minimal distance is measured between the center of maxima. The center would be calculated as the arithmetic mean (central moment?) of all samples connected to a particular maximum. In this case the center could very well lie outside a maximum's contours.
- (B) Minimal distance is the shortest distance between maximas' contours. 

Without taking algorithmic efficiency into consideration I find (B) more intuitive from a user perspective.
