### ISSUE TITLE
Tests fail with `ImportError: cannot import name geometry`

### ISSUE THREAD

**Issue by TheChymera** [scikit-image/scikit-image#3817]
## Way to reproduce
```python
python2.7 setup.py build
pytest -vv
```

## Version information
```python
>>> import sys; print(sys.version)
3.6.8 (default, Mar 22 2019, 03:44:52) 
[GCC 8.2.0]
>>> import platform; print(platform.platform())
Linux-5.0.3-gentoo-23-mars-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-gentoo-2.6
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.14.2
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
```

## Output

[build.log](https://github.com/scikit-image/scikit-image/files/3010171/build.txt)

**Comment by stefanv** [comment]
Can you please check the `0.14.x` branch?  It seems to pass our [build checks](https://travis-ci.org/scikit-image/scikit-image/builds/503415838).

**Comment by TheChymera** [comment]
I get a similar [build.log](https://github.com/scikit-image/scikit-image/files/3010652/build.log). Perhaps this is some missing dependency?

**Comment by hmaarrfk** [comment]
what command are you using to test?

```
pytest --pyargs skimage
```

from a clean directory should do the trick.

**Comment by TheChymera** [comment]
Before I was using 

```
pytest -vv
```

In the build directory. At any rate, I get the same errors: 
[build.log](https://github.com/scikit-image/scikit-image/files/3010832/build.log).

**Comment by hmaarrfk** [comment]
Are you sure you are in an empty directory,

This seems to indicate you are still in the build directory.

```
___________________________
ImportError while importing test module '/var/tmp/portage/sci-libs/scikits_image-9999/work/scikits_image-9999/skimage/morphology/tests/test_misc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
skimage/__init__.py:166: in <module>
    _raise_build_error(e)
skimage/__init__.py:147: in 
```

**Comment by TheChymera** [comment]
ah, soorry, I didn't realize by clean you meant empty. Uh, this is pretty uncommon, every other package I know runs the tests in the build directory. Any idea if that is doable, or do I have to create an empty dir in my sandbox?

**Comment by hmaarrfk** [comment]
I would say that I've seen both build systems.

Just make a directory called something like test, and change there before running the tests.

**Comment by stefanv** [comment]
On Tue, 26 Mar 2019 19:46:31 -0700, Mark Harfouche wrote:
> I would say that I've seen both build systems.
> 
> Just make a directory called something like test, and change there
> before running the tests.

We could probably detect and avoid this situation?

**Comment by TheChymera** [comment]
@hmaarrfk ok, I have tried to run the tests in a new empty dir, and they fail all the same:
[build.log](https://github.com/scikit-image/scikit-image/files/3020146/build.log)

This is the directory neighborhood where I run it:
[tree.txt](https://github.com/scikit-image/scikit-image/files/3020154/tree.txt)

**Comment by hmaarrfk** [comment]
I'm really not sure sorry. I typically test in a similar way. 

Maybe if you give me the commands you run I can try running them myself and seeing what is up.

I typically build without hitting that error.

That error often indicates that it doesn't find the so files that are from the results of the Cython compilation

**Comment by hmaarrfk** [comment]
so i'm kinda able to reproduce, I think.

```
git checkout v0.14.2
conda create --name sk27
conda activate sk27
conda install numpy cython
pip install . -vv
mkdir t
cd t
pip install pytest
pytest --pyargs skimage
```

I'm not too sure what is wrong, but I don't think you are alone.

My first instinct is to downgrade cython to 0.28, though not sure it will help.


Sigh... what ended up working is creating a temporary directory completely outside the git repo.
```
cd ..
# this directory contains skimage and the setup.py file
cd ..
# This directory contains scikit-image
mkdir t
cd t
pytest --pyargs skimage
```

**Comment by stefanv** [comment]
You have to switch out of the scikit-image repo, otherwise pytest will
discover the source version instead of the built version.  I presume
it's checking up the tree hierarchy.

We can detect this situation; I thought we did at some point and
explained to the user, so I am not sure why the error message is so
vague.

**Comment by TheChymera** [comment]
@stefanv @hmaarrfk ok, putting the empty dir outside the build hierarchy indeed silences the geometry error, but causes new ones (other module snot being detected): 
[build.log](https://github.com/scikit-image/scikit-image/files/3023804/build.log)

**Comment by stefanv** [comment]
On Fri, 29 Mar 2019 17:33:52 +0000, Horea Christian wrote:
> @stefanv @hmaarrfk ok, putting the empty dir outside the build hierarchy indeed silences the geometry error, but causes new ones (other module snot being detected): 
> [build.log](https://github.com/scikit-image/scikit-image/files/3023804/build.log)

When you do an in-place build (`python setup.py build_ext -i`), does the
test suite run?  Otherwise, this looks like a Cython issue, potentially.

**Comment by TheChymera** [comment]
No, I wasn't able to fix this (in the sense that the tests still won't pass). Much of the software (the bits I need) jun just fine. In addition to PIL, I get at least two other types of errors:

```
___________________________ ERROR collecting transform/tests/test_pyramids.py ___________________________
../scikit-image-0.14.3-python2_7/lib/skimage/transform/tests/test_pyramids.py:11: in <module>
    image = data.astronaut()
../scikit-image-0.14.3-python2_7/lib/skimage/data/__init__.py:106: in astronaut
    return load("astronaut.png")
../scikit-image-0.14.3-python2_7/lib/skimage/data/__init__.py:70: in load
    use_plugin('pil')
../scikit-image-0.14.3-python2_7/lib/skimage/io/manage_plugins.py:258: in use_plugin
    _load(name)
../scikit-image-0.14.3-python2_7/lib/skimage/io/manage_plugins.py:298: in _load
    raise ValueError("Plugin %s not found." % plugin)
E   ValueError: Plugin pil not found.
_______________________ ERROR collecting transform/tests/test_radon_transform.py ________________________
../scikit-image-0.14.3-python2_7/lib/skimage/transform/tests/test_radon_transform.py:17: in <module>
    as_gray=True)[::2, ::2]
../scikit-image-0.14.3-python2_7/lib/skimage/io/_io.py:62: in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
../scikit-image-0.14.3-python2_7/lib/skimage/io/manage_plugins.py:201: in call_plugin
    raise RuntimeError(msg % kind)
E   RuntimeError: No suitable plugin registered for imread.
E   
E   You may load I/O plugins with the `skimage.io.use_plugin` command.  A list of all available plugins are shown in the `skimage.io` docstring.
_____________________________ ERROR collecting viewer/tests/test_plugins.py _____________________________
ImportError while importing test module '/var/tmp/portage/sci-libs/scikits_image-0.14.3/work/scikit-image-0.14.3-python2_7/lib/skimage/viewer/tests/test_plugins.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../scikit-image-0.14.3-python2_7/lib/skimage/viewer/__init__.py:2: in <module>
    from .viewers import ImageViewer, CollectionViewer
../scikit-image-0.14.3-python2_7/lib/skimage/viewer/viewers/__init__.py:1: in <module>
    from .core import ImageViewer, CollectionViewer
../scikit-image-0.14.3-python2_7/lib/skimage/viewer/viewers/core.py:14: in <module>
    from ..plugins.base import Plugin
../scikit-image-0.14.3-python2_7/lib/skimage/viewer/plugins/__init__.py:2: in <module>
    from .canny import CannyPlugin
../scikit-image-0.14.3-python2_7/lib/skimage/viewer/plugins/canny.py:4: in <module>
    from ...feature import canny
../scikit-image-0.14.3-python2_7/lib/skimage/feature/__init__.py:21: in <module>
    from .orb import ORB
../scikit-image-0.14.3-python2_7/lib/skimage/feature/orb.py:12: in <module>
    from .orb_cy import _orb_loop
E   ImportError: cannot import name _orb_loop
```

Any help with either of these would be much appreciated.

What do you mean by not including all config files in the build system? Like which files might be missing? I download everything from the `scikits_image-0.14.3` release archive.

**Comment by TheChymera** [comment]
@hmaarrfk also, if by PIL you mean pillow, I have it installed (`=dev-python/pillow-6.1.0`), so I'm unsure why it would be unable to find it....  though it looks like it's not pillow causing the hold-up, but some scikit-image plugins for it? :-/

**Comment by TheChymera** [comment]
ok, so the geometry issue is fixed, [a new issue](https://github.com/scikit-image/scikit-image/issues/4388) might be a better place to discuss other test errors.
