### ISSUE TITLE
`io.imsave` inconsistently issues `is a low contrast` warning

### ISSUE THREAD

**Issue by maliho0803** [scikit-image/scikit-image#3819]
## Description
```
io.imsave('{}/{}'.format(save_folder1, image_name.replace('.jpg', '_posmap.jpg')), np.clip((uv_position_map)/max(image_h, image_w), -1, 1)) # only for show
```

```
UserWarning: ../../dataset/300W_LP_Posmap_img//HELEN_2330042311_1_10_posmap.jpg is a low contrast image
warn('%s is a low contrast image' % fname)
```
the same code work well in linux, but get warning in Mac

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by hmaarrfk** [comment]
@maliho,

Can you please give us more of the reproducing code. To fix the underlying cause of the issue quickly, we need something that will force your issue to happen start to finish in a new python instance. 

Here, we are missing all the code uv_position map

**Comment by wangken1994** [comment]
@hmaarrfk, 

I am doing brain tumor segmentation, and I also meet the save problem when I use `io.imsave` :

> UserWarning: *.png is a low contrast image warn.

My source codes are shown below:

`from skimage import io`
`from glob import glob`
`import cv2`
`def save_labels(fns):`

`    for label_idx in xrange(len(label)):`
`        slices = io.imread(label[label_idx], plugin = 'simpleitk')`
`        # slices = cv2.imread(label[label_idx])`
`        for slice_idx in xrange(len(slices)):`
`            io.imsave('.../{}_{}L.png'.format(label_idx, slice_idx), slices[slice_idx])`
`            # cv2.imwrite('.../{}_{}L.png'.format(label_idx, slice_idx), slices[slice_idx])`

`if __name__ == '__main__':`
    `label = glob('.../VSD.Brain.XX.O.MR_Flair.54512.mha')`
    `save_labels(label)`

**Comment by wangken1994** [comment]
@hmaarrfk ,

I also meet the same problem when I transform the `.mha` file (brain tumor image) to `.png` file.

My source codes are shown below:

```python
from skimage import io
from glob import glob
#import cv2

def save_labels(fns):
    '''
    INPUT list 'fns': filepaths to all labels
    '''
    for label_idx in xrange(len(label)):
        slices = io.imread(label[label_idx], plugin = 'simpleitk')
        for slice_idx in xrange(len(slices)):
            io.imsave('.../{}_{}L.png'.format(label_idx, slice_idx), slices[slice_idx])
            # cv2.imwrite('.../{}_{}L.png'.format(label_idx, slice_idx), slices[slice_idx])

if __name__ == '__main__':

    label = glob('.../VSD.Brain.XX.O.MR_Flair.54512.mha')
    save_labels(label)
```
This is the `.mha` file:
[VSD.Brain.XX.O.MR_Flair.54512.mha.tar.gz](https://github.com/scikit-image/scikit-image/files/3087583/VSD.Brain.XX.O.MR_Flair.54512.mha.tar.gz)
![IMG0054](https://user-images.githubusercontent.com/34388336/56255240-b7992880-60f6-11e9-818f-21dd3cd6995a.png)

If I use `io.imsave`, the warning will occur:
> UserWarning: .../*.png is a low contrast image warn('%s is a low contrast image' % fname)

Result of `io.imsave`:
![0_54L](https://user-images.githubusercontent.com/34388336/56255093-1dd17b80-60f6-11e9-8d8b-d0f8d426b954.png)

If I use `cv2.imwrite`, the warning disappears, but the results .png files seems too light.
Result of `cv2.imwrite`:
![0_54L](https://user-images.githubusercontent.com/34388336/56255133-49546600-60f6-11e9-9021-08fa3163e75e.png)

So could you kindly give me some tips?

**Comment by hmaarrfk** [comment]
@wangken1994 please output the result of

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by wangken1994** [comment]
```python
2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0]
Linux-4.15.0-47-generic-x86_64-with-debian-stretch-sid
scikit-image version: 0.13.0
numpy version: 1.13.3
```

**Comment by hmaarrfk** [comment]
I think you should go over 
https://scikit-image.org/docs/stable/user_guide/data_types.html

you show plots, but you don't show the command used to obtain them. This indicates to me that you are using some autoscaling function that is scaling your data for you.
opencv is having a hard time guessing the min and max values for your dataset.
OpenCV loves uint8 

different image formats use different min and max values.

I'm not too sure what PNGs support. They might only support unsigned int 16. It seems your data is *signed* 16 bit.

**Comment by hmaarrfk** [comment]
please upgrade to scikit-image 0.14.2

**Comment by hmaarrfk** [comment]
(unless something is specifically stopping you from doing that then please help us address that issue).

**Comment by wangken1994** [comment]
The PNGs are the results after running the program, so I don't use plot command in this program.

I will try your suggetions. Thank you very much!

**Comment by hmaarrfk** [comment]
i see, so the first one is from `skimage.io.imwrite`

i'm going to say, that in scikit-image 0.13 we used to use the backend PIL,
in 0.14 we changed to imageio

not sure if that will make a difference for you.

The real issue is the dtypes of your image.

Updating skimage should be a minor point

**Comment by hmaarrfk** [comment]
I'm going to close this issue for now. Please re open if things still persist. We are aware that dtypes can cause headaches.

We don't really have a perfect solution for this considering:
1. Performance
2. What users want
3. What users exect
4. backward compatibility.

When you do reopen the issue. pleave avoid the use of a loop so we can examine the image that is causing your troubles.
