### ISSUE TITLE
"Dilation" of drawing function outputs

### ISSUE THREAD

**Issue by dmontagu** [scikit-image/scikit-image#3828]
I've run into a common pattern when using the drawing functions that I'm not sure how to address:

**I would like to take the `(rows, columns)` output from a function like `skimage.draw.rectangle_perimeter` and apply a function that is equivalent to morphological dilation to expand the output (so I can draw a dilated version of the output).** (See below for a concrete example.)

However, all of the morphology functions seem to require an image as input (adding a lot of overhead for 1d drawing outputs), and none of the drawing functions seem to take anything along the lines of a width or dilation parameter. 

Since I would like similar functionality for the other skimage.draw functions (such as `polygon`,  `line`, `ellipse`, etc.), I'd prefer a general approach. I can think of some ways to implement this (e.g., numpy broadcasting, described below), but they are have potentially significant inefficiencies, and I would like to use this to draw updates in real time on potentially-large images, so it seems worthwhile to handle it more efficiently if possible.

I would think this would be a relatively common use case, but I can't seem to find any discussion of how to accomplish this more efficiently than a broadcasting-style approach.

**Is there any built-in functionality in scikit-image that can accomplish this?** If not, is there a simple way to accomplish it that is more efficient than the numpy broadcasting approach described below?

-------
Concretely, I'm looking for an approach that would accomplish the same result as:
```python
image = np.zeros((100, 100, 3), dtype=np.uint8)
selem = np.ones((5, 5))
rr, cc = skimage.draw.rectangle_perimeter((10, 10), (90, 90))
image[rr, cc] = 255
image = skimage.morphology.dilation(image, selem)
```
but look more like this when called:
```python
rr, cc = skimage.draw.rectangle_perimeter((10, 10), (90, 90))
selem = np.ones((5, 5))
rr, cc = special_dilation(rr, cc, selem)  # doesn't exist
image = np.zeros((100, 100, 3), dtype=np.uint8)
image[rr, cc] = 255
```
In practice, the image I want to update is more complex than all zeros, so I can't rely on the morphological dilation without also adding extra overhead related to array creation.

I recognize there is a cartesian-product-style approach:
```python
rr, cc = skimage.draw.rectangle_perimeter((10, 10), (90, 90))
rrs_offset, ccs_offset = [], []
row_offsets = col_offsets = np.arange(5)
for i in row_offsets:
    for j in col_offsets:
        rrs_offset.append(rr + i)
        ccs_offset.append(cc + j)
rr, cc = np.hstack(rrs_offset), np.hstack(ccs_offset)
```
and while I'm sure this could be made more efficient (if less readable) using numpy broadcasting, it still feels rather inefficient since there will be lots of redundancy in the offset arrays.

**Comment by dmontagu** [comment]
I did some digging into the OpenCV drawing functions and it looks like they implement drawing thickness by using convex polygons during the drawing process. So I'm guessing that the only way to accomplish my goal would be to be efficient during the actual drawing process, and so would require some changes to the way the drawing functions work.

Is there any plan to add a thickness parameter to the (1D) drawing functions? Would there be interest in a pull request? (I would understand if this feature has been excluded to reduce maintenance burden.)

**Comment by jni** [comment]
@dmontagu I'd certainly be up for adding this, and I think it's probably doable without too much code complexity.

**Comment by stefanv** [comment]
On Sat, 06 Apr 2019 21:00:22 -0700, Juan Nunez-Iglesias wrote:
> @dmontagu I'd certainly be up for adding this, and I think it's
> probably doable without too much code complexity.

Convert each line to polygons, with the box ends perpendicular to the
current line, and draw; should work?

**Comment by emmanuelle** [comment]
@dmontagu it's also a feature I'd be interested in; for dash-canvas (https://dash.plot.ly/canvas) I have SVG paths with the geometry of annotations and I need to dilate them with the thickness of the brush. At the moment I'm using morphological dilation but it takes quite some time for large thicknesses.
