### ISSUE TITLE
file not found error while using Skimage

### ISSUE THREAD

**Issue by baddemiya** [scikit-image/scikit-image#3842]
```
import os
import numpy
from skimage import io


dir_files = os.listdir('./pygame_images//')
print(len(dir_files))
bg_image = io.imread(fname = dir_files[0], as_grey=True)


for k in range(1, len(dir_files)):

    fname = dir_files[k]

    im = io.imread(fname=fname, as_grey=True)

    bg_image = bg_image + im



bg_image = bg_image/(len(dir_files))

bg_image_bin = bg_image > 0.5



io.imsave(fname='bg_model.jpg', arr=bg_image)
io.imsave(fname='bg_model_bin.jpg', arr=bg_image_bin*255)
```

> when i run above code i get below error:
```
Traceback (most recent call last):
  File "/home/pi/pygame_bg.py", line 9, in <module>
    bg_image = io.imread(fname = dir_files[0], as_grey=True)
  File "/usr/lib/python3/dist-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/lib/python3/dist-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'image_0.jpg'
```
i have the required file in the mentioned location.

**Comment by hmaarrfk** [comment]
You need to give the function the full relative path, not simply the filename

**Comment by baddemiya** [comment]
can youhttps://scikit-image.org/docs/dev/api/skimage.io.html#skimage.io.imread

on their official website it says we need to give filename or URL.

i tried entering full path, but is shows syntax error.

**Comment by hmaarrfk** [comment]
It seems that now image 0 was read but not image 1.

Can you cake us a screenshot of your directory structure?

**Comment by jni** [comment]
@baddemiya you should make sure that the files you are reading are in the same location as the listdir. Here's how I would write what you're doing:

```python
import os
from skimage import io

d = './pygames_images'
images = sorted(os.listdir(d))
print('found {} images'.format(len(images)))  # just to check that there's stuff there
bg = io.imread(os.path.join(d, images[0]))
```

I hope you can use that template to get to where you want.

As this is a Python error and not a skimage error, I'm going to close the issue, but please feel free to continue the discussion! We will help where we can.

**Comment by baddemiya** [comment]
> It seems that now image 0 was read but not image 1.
> 
> Can you cake us a screenshot of your directory structure?

@hmaarrfk. it starts reading randomly. not in sequential order. This was confirmed by print function. so its not that it is reading 0 but not reading 1.

**Comment by baddemiya** [comment]
> You need to give the function the full relative path, not simply the filename

you are right. 
actually it was a typo from my end. instead of pygame_images.... i typed.. pygames_images.

**Comment by baddemiya** [comment]
> @baddemiya you should make sure that the files you are reading are in the same location as the listdir. Here's how I would write what you're doing:
> 
> ```python
> import os
> from skimage import io
> 
> d = './pygames_images'
> images = sorted(os.listdir(d))
> print('found {} images'.format(len(images)))  # just to check that there's stuff there
> bg = io.imread(os.path.join(d, images[0]))
> ```
> 
> I hope you can use that template to get to where you want.
> 
> As this is a Python error and not a skimage error, I'm going to close the issue, but please feel free to continue the discussion! We will help where we can.

thank you. problem is solved

**Comment by ManukumarNM** [comment]
@baddemiya 
If I load the dataset locally from my PC, How can I edit this function def fetch_data_details(dataset)? Can you please help out of this.
Thanks in advance 

def fetch_dataset():
    dataset = os.listdir(r'C:/Users/dslab/Desktop/ICA/tcd-ai-group-project-master/Images')
    return dataset
 
**def fetch_data_details(dataset):**
    #print('found {} images'.format(len(dataset)))
    n_samples, height, width = dataset.images.shape

    X = dataset.data
    n_features = X.shape[1]

    # the label to predict is the id of the person
    y = dataset.target
    target_names = dataset.target_names
    n_classes = target_names.shape[0]

    print("Total DATASET size:")
    print("n_samples: %d" % n_samples)
    print("n_features: %d" % n_features)
    print("n_classes: %d" % n_classes)

    return n_samples, height, width, X, n_features, y, target_names, n_classes
