### ISSUE TITLE
skimage.transform.rotate returns an array full of zeros.

### ISSUE THREAD

**Issue by mattvend** [scikit-image/scikit-image#3844]
## Description

The rotate function does not work as expected on my Ubuntu 18.04 machine. When rotating the image below, I get a matrix full of zero instead of a matrix.

![example](https://user-images.githubusercontent.com/6509352/56148356-65e38780-5faa-11e9-903f-55f386ce0b08.jpg)

## Conda environment to recreate the issue
```text
name: sklearn-dev
channels:
  - defaults
dependencies:
   - opencv=3.3.1
   - scikit-image=0.14.0
   - scikit-learn=0.19.1
```
## Way to reproduce

```python

import cv2
import sklearn
import skimage.transform

if __name__ == '__main__':

    import sys; print(sys.version)
    import platform; print(platform.platform())
    import skimage; print("scikit-image version: {}".format(skimage.__version__))
    import numpy; print("numpy version: {}".format(numpy.__version__))

    img = cv2.imread('example.jpg', cv2.IMREAD_ANYDEPTH)
    img_ori = skimage.transform.rotate(img, float(90), preserve_range=True)
    print(img_ori)
```

```python
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
This is not what I expect
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]
Linux-4.15.0-47-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.14.0
numpy version: 1.15.4
```

## Investigation
Stepping into the code brings me to _warps.py around line 842 where the _warp_fast function returns an array full of zeros.
```python
                warped = _warp_fast(image, matrix,
                                    output_shape=output_shape,
                                    order=order, mode=mode, cval=cval)
```

This seems to be a call to a C function. Which library is actually sklearn using to do the rotation?

**Comment by jni** [comment]
@mattvend you need to pass `resize=True` to the function, otherwise it does not re-orient the image. 

```python
In [4]: img.shape
Out[4]: (1000, 2500, 3)
In [7]: out = transform.rotate(img, 90, preserve_range=True)
In [8]: out.shape
Out[8]: (1000, 2500, 3)
In [9]: out.max()
Out[9]: 255.0
In [14]: out2 = transform.rotate(img, 90, resize=True, preserve_range=True)
In [16]: out2.shape
Out[16]: (2500, 1001, 3)
```

(The 1001 is a bug that we are already tracking in #3071.)

Make sure you use

```python
import matplotlib.pyplot as plt

plt.imshow(out / 255)  # mpl expects float images in [0, 1]
plt.show()
```

to see your output, which would have made this problem apparent.

Also, please read our [documentation on data types](https://scikit-image.org/docs/dev/user_guide/data_types.html), as you might run into some display or other issues with float images in [0, 255] as `preserve_range=True` produces.

Thanks for chiming in, and let us know if you run into other issues!

**Comment by jni** [comment]
btw to clarify a bit what was happening: rotate was rotating the image about its centre, but then anything outside of the image was a 0, which resulted in black borders around the central part of the image:

![Figure_2](https://user-images.githubusercontent.com/492549/56154656-67d63680-5ffc-11e9-838d-296c611696a3.png)

**Comment by mattvend** [comment]
Dear @jni 

Thank you very much for the update and the quick answer!

However, this is **not** what is actually happening on my machine, the **complete** image is actually black. It is definitely not a border issue.

- can we reopen the ticket?
- is _warp_fast calling a library to perform the rotation ?

Kind regards

**Comment by jni** [comment]
Oh! Yes you can! Sorry, we always say this but this time I was SO confident I had it right I didn’t even mention it! 😅

_warp_fast is implemented in Cython within scikit-image.

**Comment by mattvend** [comment]
Dear @jni 

Issue was on my side, please close this issue as there is nothing to solve.
Thanks again for your help and your explanation.

cheers

**Comment by jni** [comment]
Ok! Always feel free to reach out!
