### ISSUE TITLE
References formatting is broken in plot_segmentations

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#3853]
## Description

See https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_segmentations.html

Not sure if there are other examples with such issue.

**Comment by sciunto** [comment]
All references look broken.

**Comment by stefanv** [comment]
A new numpydoc just came out; could be the culprit?

**Comment by soupault** [comment]
Something has definitely changed in the recent versions of numpydoc. I cannot even build the html pages with 0.9.0/0.9.1...
However, if built with 0.6.0, the documentation still has broken references. Could be a sphinx issue as well. 😞

**Comment by stefanv** [comment]
That sounds very much like a Sphinx issue; why would 0.6 otherwise still give broken references?

**Comment by soupault** [comment]
Issue in Sphinx repo - https://github.com/sphinx-doc/sphinx/issues/6324

**Comment by sciunto** [comment]
Although we merged https://github.com/scikit-image/scikit-image/pull/3900 we still have the issue in the [gallery](https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_floodfill.html#sphx-glr-auto-examples-segmentation-plot-floodfill-py), but not in the [API](https://scikit-image.org/docs/stable/api/skimage.feature.html#corner-shi-tomasi)

**Comment by soupault** [comment]
Example https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_segmentations.html:

`0.15.x`:
![image](https://user-images.githubusercontent.com/1315589/71770322-f0528980-2f33-11ea-8658-7473221be4c3.png)

`0.16.x`:
![image](https://user-images.githubusercontent.com/1315589/71770325-fe080f00-2f33-11ea-8aaa-6c9c3854b518.png)

`dev`:
![image](https://user-images.githubusercontent.com/1315589/71770335-15df9300-2f34-11ea-8572-8bee5aa6fc04.png)

Do we want to fix anything else or should we close? I'm fine with closing.

**Comment by sciunto** [comment]
A last improvement could be the brackets around ref numbers. That said, we can close, it's minor.
