### ISSUE TITLE
Debugging script

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3855]
## Description
@stefanv mentionned that it might be a good idea to have a "debug script".

Not sure how much I agree with that idea, but it could help us better understand things quickly.

The challenge is keeping that script updated with all the versions of python, environments, and operating systems. Finally it should also be easy to run.

Having the convo here instead of the original issue to keep things isolated.

**Comment by stefanv** [comment]
See comments [1](https://github.com/scikit-image/scikit-image/issues/3852#issuecomment-485633341) and [2](https://github.com/scikit-image/scikit-image/issues/3852#issuecomment-485916278)

**Comment by johanjeppsson** [comment]
Just a thought: would it make sense to make this debug script into a function that can be imported and called from the distributed scikit-image? E.g. something like

```python
from skimage import debug
debug.print_report()
```

I haven't seen that kind of thing in any other packages, and maybe that is because it is not a great idea, but it would make it trivial to run.

**Comment by hmaarrfk** [comment]
Vispy has a sys_info 
https://github.com/vispy/vispy/blob/master/vispy/util/config.py#L393

The issue occurs when users can't even import skimage, such as what happened in  https://github.com/scikit-image/scikit-image/issues/3852#issue-435415732

Users could also be using a wide variety of platforms.

We could ask users to copy paste in more commands, but that would make the commands we are asking them to use more scary.

Maybe we can all post helpful troubleshooting tips on the wiki???

**Comment by johanjeppsson** [comment]
Ah, yes you're right. 
Yeah, maybe a troubleshooting list is better, or at the very least more flexible :-)

**Comment by stefanv** [comment]
We have a little debug script in the issue filing form. Can expand that if necessary.
