### ISSUE TITLE
Inverse transformation issue 

### ISSUE THREAD

**Issue by notconvergingwtf** [scikit-image/scikit-image#3856]
I got different image output while transformation stayed the same:
```
im=np.ones((128,128))*255
src = np.array([
    [56., 60.],
    [81., 60.],
    [64., 80.],
    [49., 100.],
    [78., 100.]], dtype=np.float32)
q=np.array([
    [58.166317,39.124466],
    [86.10652,26.917824],
    [106.29474,39.68392],
    [90.64203,72.82854],
    [115.17699,63.91104]],dtype=np.float32)
tt=trans.SimilarityTransform()
tt.estimate(q,src)
dst1 = trans.warp(im,tt.inverse,preserve_range=True,output_shape=(128,128))
tt.estimate(src,q)
dst = trans.warp(im,tt,preserve_range=True,output_shape=(128,128))
```
![image](https://user-images.githubusercontent.com/48060406/56577618-1584af00-65d4-11e9-8956-d79cfe0fae31.png) ![image](https://user-images.githubusercontent.com/48060406/56577623-187f9f80-65d4-11e9-9a98-f450584ad8fb.png)

What is wrong here? 

## Version information
```python

Python 3.5.2
scikit-image version: 0.14.2
numpy version: 1.16.2
```

**Comment by stefanv** [comment]
I'm not sure what you are trying to do here.  It looks like you are applying two different transformations to the image, and got two different outcomes, as expected.  Here's the image diff:
![diff](https://user-images.githubusercontent.com/45071/56608112-e4e64a80-65be-11e9-969f-ab3cded01c21.png)

**Comment by hmaarrfk** [comment]
It should be the same, in the first case he is estimating the forward transform, in the second case he is estimating the inverse

**Comment by stefanv** [comment]
Thanks, @hmaarrfk, I see now.

It looks like the model used is unable to capture the transformation requested.  Is this because the model is not flexible enough, or because the data is degenerate?  Let's see:

## Provided data

| Model                  | Error → | Error ← |
|------------------------+---------+---------+
| EuclideanTransform     |   25.05 |   25.05 |
| SimilarityTransform    |   24.72 |   20.66 |
| AffineTransform        |   22.62 |   18.66 |
| ProjectiveTransform    |   21.62 |   21.26 |

## Random data

| Model                  | Error → | Error ← |
|------------------------+---------+---------+
| EuclideanTransform     |    1.11 |    1.11 |
| SimilarityTransform    |    0.93 |    0.75 |
| AffineTransform        |    0.88 |    1.24 |
| ProjectiveTransform    |    3.16 |    0.76 |

Looks like the latter, since the transform is able to fit randomly generated data much better.

See below for the code I used.

<details>

```python
import numpy as np
from skimage import transform as tf


src = np.array([
     [56., 60.],
     [81., 60.],
     [64., 80.],
     [49., 100.],
     [78., 100.]
], dtype=np.float32)

dst = np.array([
    [58.166317, 39.124466],
    [86.10652, 26.917824],
    [106.29474, 39.68392],
    [90.64203, 72.82854],
    [115.17699, 63.91104]
], dtype=np.float32)


def tf_err(src, dst, transform):
    E = np.ones((src.shape[0], 1))
    dst_est = np.block([src, E]) @ transform.params.T
    dst_est /= dst_est[:, 2, np.newaxis]
    dst_est = dst_est[:, :2]

    return np.linalg.norm(dst_est - dst)


for (dataset, src, dst) in [("Provided data", src, dst),
                            ("Random data",
                             np.random.random((5, 2)),
                             np.random.random((5, 2)))]:

    print(f'## {dataset}\n')

    print('| Model                  | Error → | Error ← |')
    print('|------------------------+---------+---------+')

    for Model in (tf.EuclideanTransform, tf.SimilarityTransform,
                  tf.AffineTransform, tf.ProjectiveTransform):
        print(f'| {Model.__name__:23}', end='')

        m=Model()
        m.estimate(src, dst)
        print(f'| {tf_err(src, dst, m):7.2f} ', end='')

        m.estimate(dst, src)
        print(f'| {tf_err(dst, src, m):7.2f} |')

    print()
```

</details>

**Comment by notconvergingwtf** [comment]
@stefanv i got you idea. But you are wrong at comparing `np.random`(uniform) on [0;1) and [0;128] points. From default you will have less error value. While compare `np.random.random((5, 2))*128` you'll have much higher error. 
To clarify the question: affine transformations is a group of transformations (R2->R2), where you have one determined inverse element for each (in our case - inverse transformation). In my question it appears that we have _different_ transformations to the same source points (two inverse elements).
Actually, there is not mistake anywhere, just misunderstanding `.inverse`  and `.estimate` function. `t.estimate(q, src).inverse !=t.estimate(src, q)` but `t.estimate(q, src).inverse ==t.estimate(t(q),q)`

**Comment by ShixingWang** [comment]
So which transform should I pass to `skimage.transform.warp`, if I want the `src` coords in the old image to appear at `q` coords in the transformed image?

And what's the coordinate convention for `AffineTransform.estimate()`, (row, column) or (x,y)?

Thanks.

**Comment by stefanv** [comment]
You have to provide the inverse transform, so output image coordinates mapped to input image coordinates.

Unfortunately, we currently use `(x, y)`; that will change in skimage2.
