### ISSUE TITLE
Indentation bug in skimage/morphology/_skeletonize_cy.pyx

### ISSUE THREAD

**Issue by dahart** [scikit-image/scikit-image#3861]
## Description

I noticed the indentation is incorrect in https://github.com/scikit-image/scikit-image/blob/master/skimage/morphology/_skeletonize_cy.pyx at latest version 138964a on Nov 19, 2018

In the function _skeletonize_loop, all lines starting from line 188 should be de-indented one level. I suspect the output might be incorrect in the top row any time there are foreground pixels in the top row, e.g., when result[ 0, : ] == 1

```python
            # Compute the configuration around the pixel
            if ii > 0:
                if jj > 0 and result[ii - 1, jj - 1]:
                    accumulator += 1
                if result[ii - 1, jj]:
                    accumulator += 2
                if jj < cols - 1 and result[ii - 1, jj + 1]:
                        accumulator += 4
                if jj > 0 and result[ii, jj - 1]:
                    accumulator += 8
                ...
```

should be:

```python
            # Compute the configuration around the pixel
            if ii > 0:
                if jj > 0 and result[ii - 1, jj - 1]:
                    accumulator += 1
                if result[ii - 1, jj]:
                    accumulator += 2
                if jj < cols - 1 and result[ii - 1, jj + 1]:
                        accumulator += 4
            if jj > 0 and result[ii, jj - 1]:
                accumulator += 8
            ...
```

**Comment by stefanv** [comment]
Hi @dahart, thank you for catching this!  Would you be willing to make a pull request with a test that can verify that the old behavior fails and the new behavior succeeds?
