### ISSUE TITLE
canny in 0.15.x cannot deal with all types of image properly

### ISSUE THREAD

**Issue by yingfhu** [scikit-image/scikit-image#3889]
## Description
`canny` sets percentile threshold if `low_threshold` and `high_threshold` are being set, otherwise, it sets  0.1 * dtype_max. 

Therefore, when inputting a uint8 image with no thresholds for instance, the new `fsmooth` function convert the image to float but the thresholds do not match the data type, so the canny returns all False.

##Version Info
3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
Linux-4.18.0-18-generic-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.15.0
numpy version: 1.16.3

**Comment by hmaarrfk** [comment]
Thank you for reporting this @yingfhu 

I think this is very likely a real issue. Would you like to help getting fixed?

I think the general steps would be:
1. Adapt the example to use an image of dtype `uint8` 
https://github.com/scikit-image/scikit-image/blob/master/doc/examples/edges/plot_canny.py
2. Making it into a test case that causes the automated tests to fail.
3. Modify the implementation to ensure that the range is respected in the canny function after smoothing.

We are glad to help you through this process if you want to be involved!

**Comment by soupault** [comment]
Looks like an issue!
We say that input `can be of any dtype.`, but the function is never tested against [u]int images and default `*_threshold` values.

**Comment by yingfhu** [comment]
Sorry for the late response, just finished my finals.
Sure, I would like to fix this issue, but I am not pretty familiar to the steps.
So, from my understandings, what I am going to do would be:
1. Change the dtype of image to `uint8`  in the example of `plot_canny.py`.
2. Add a test case such as `test_image_dtype` in the `test_canny.py`.
3. Modify the `canny.py` to make the test pass.
Are these correct steps? Please tell me if anything is inappropriate! Thanks a lot! @hmaarrfk

**Comment by hmaarrfk** [comment]
@yingfhu sorry for my late reply. 

i guess somebody started to address this
https://github.com/scikit-image/scikit-image/pull/3919

Thanks for reporting this though!

**Comment by sciunto** [comment]
Fixed by #3919
