### ISSUE TITLE
imread breaking builds

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3894]
Imread is being compiled from source which sometimes seems to break the build system.

https://travis-ci.org/scikit-image/scikit-image/jobs/530566603

xref: https://github.com/luispedro/imread/issues/35

* scikit-image: master
* OS: OSX
* Travis build: https://travis-ci.org/scikit-image/scikit-image/jobs/530566603
* PR example: https://github.com/scikit-image/scikit-image/pull/3893

**Comment by jni** [comment]
@hmaarrfk "sometimes"? This is not a reproducible error? Could it be "fixed" with a travis_retry?

**Comment by jni** [comment]
OR maybe we ignore the imread plugin on mac... I would like to minimise our churn with optional external libraries...

**Comment by hmaarrfk** [comment]
I think the correct solution is not to accept plugins that don't have wheels built. That said, it was probably added before wheels were a thing

**Comment by hmaarrfk** [comment]
We could skip on Mac. We've already out it in a different requirements file..would be pretty easy with an if statement
