### ISSUE TITLE
Getting ImportError: cannot import name '_validate_lengths'

### ISSUE THREAD

**Issue by abhinavsagar** [scikit-image/scikit-image#3906]
I am trying to make a flappy bird ai game that uses scikit image. But on running I am getting-
```
Traceback (most recent call last):
  File "qlearn.py", line 5, in <module>
    import skimage as skimage
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\util\__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths
```

**Comment by hmaarrfk** [comment]
I think this is related to:
https://github.com/scikit-image/scikit-image/issues/3649

can you give the output of

```python
import numpy as np
print(np.__version__)
```

If you know how, could you also give the output of 
```
pip list
```


My guess is that you need to update scikit-image from 0.14.0 to 0.14.2 or 0.15.0 (because you are running python 3.6).

FYI, for multi line code snippers, you need to put 3 ` in a row.

**Comment by jni** [comment]
@abhinavsagar I'm going to close this for the moment as I think @hmaarrfk is right that this is the same issue as #3649. Specifically, scikit-image 0.14.{0,1} are incompatible with NumPy 1.16.0 and higher. The solution is either:

- upgrade scikit-image to 0.14.2 or 0.15.0, OR
- downgrade NumPy to 1.15.

Please reopen the issue if these options don't fix the problem for you!

**Comment by ankitverma1510** [comment]
Install numpy==1.16
install skimage==0.15
restart the kernel
For me it worked

**Comment by ivan866** [comment]
`python -m pip install --upgrade scikit-image`
worked for me

**Comment by jianweili0** [comment]
> python -m pip install --upgrade scikit-image

Thanks that works for me as well! Appreciated

**Comment by bladeroy** [comment]
!pip install --user scikit-image. 

Worked for me.

**Comment by parveen99** [comment]
I use python2.7, I am having the same issue . What version of numpy and scikit should I install?

**Comment by parveen99** [comment]
from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name _validate_lengths

**Comment by soupault** [comment]
@parveen99 please, see the messages above. Also, please, note that Python 2.7 is no longer supported neither by numpy nor scikit-image.

**Comment by jni** [comment]
@parveen99 `pip install -U scikit-image=0.14.5` *should* work.

**Comment by saadwazir** [comment]
> `python -m pip install --upgrade scikit-image`
> worked for me

this worked for me also

**Comment by ggaziv** [comment]
For me the magic dependency was:
```
pip install scikit-image==0.13.1
pip install numpy==1.15
```
For python 3.5 and python 3.6

**Comment by sunsetjesus** [comment]
> `python -m pip install --upgrade scikit-image`
> worked for me

worked in my case as well

**Comment by JorgenWan** [comment]
python -m pip install --upgrade scikit-image
worked for me

worked in my case as well

**Comment by 0Rutuja28-97** [comment]
my python version is 3.8.6 and , I am having ,  ImportError: cannot import name 'pad' from 'skimage.util' , I tried python -m pip install --upgrade scikit-image but then also my error is not resolved , Can anyone please help me?

**Comment by rfezzani** [comment]
Hello @0Rutuja28-97, `skimage.util.pad` is deprecated since `v0.17` and planned to be removed in `v0.19`. You can simply replace it by `numpy.pad`.

**Comment by 0Rutuja28-97** [comment]
ok ty

________________________________

**Comment by 0Rutuja28-97** [comment]
my python version is 3.8.6 and , I am having ,ImportError: cannot import name 'ParserError' from 'dateutil.parser', Can you tell me how to resolve it?

**Comment by hmaarrfk** [comment]
Please open new issues. This issue was created in 2019 and is very likely unrelated to what you are seeing now.
