### ISSUE TITLE
 the result of  io function  is different between linux and windows

### ISSUE THREAD

**Issue by fengxiaoshuai** [scikit-image/scikit-image#3909]
## Description
scikit-image--version-0.15.0

from skimage import io 
img = io.imread("1.jpg")

# your output here
windows result: 
[[[ 69 110 200]
  [ 68 109 199]
  [ 67 108 198]
  ...
  [ 60 100 196]
  [ 61 101 197]
  [ 62 102 198]]

 [[ 69 110 200]
  [ 68 109 199]
  [ 67 108 198]
  ...
  [ 60 100 196]
  [ 61 101 197]
  [ 61 101 197]]

 [[ 69 110 200]
  [ 68 109 199]
  [ 67 108 198]
  ...
  [ 58  98 194]
  [ 59  99 195]
  [ 60 100 196]]

 ...

 [[162 164 161]
  [137 139 136]
  [151 153 152]
  ...
  [156 161 164]
  [153 158 161]
  [149 157 159]]

 [[150 152 149]
  [132 134 131]
  [141 143 140]
  ...
  [132 140 143]
  [133 141 144]
  [133 143 145]]

 [[155 157 154]
  [163 165 162]
  [150 152 149]
  ...
  [133 141 144]
  [129 139 141]
  [129 139 141]]]
linux:
[[[ 69 110 200]
  [ 68 109 199]
  [ 67 108 198]
  ...
  [ 60 100 196]
  [ 61 101 197]
  [ 62 102 198]]

 [[ 69 110 200]
  [ 68 109 199]
  [ 67 108 198]
  ...
  [ 60 100 196]
  [ 61 101 197]
  [ 61 101 197]]

 [[ 69 110 200]
  [ 68 109 199]
  [ 67 108 198]
  ...
  [ 58  98 194]
  [ 59  99 195]
  [ 60 100 196]]

 ...

 [[162 164 161]
  [137 139 136]
  [151 153 150]
  ...
  [154 162 164]
  [151 159 161]
  [149 157 159]]

 [[150 152 149]
  [132 134 131]
  [141 143 140]
  ...
  [132 140 143]
  [133 141 144]
  [134 142 145]]

 [[155 157 154]
  [163 165 162]
  [150 152 149]
  ...
  [132 142 144]
  [129 139 141]
  [129 139 141]]]

**Comment by hmaarrfk** [comment]
We hit this a while back. The conclusion was that jpeg images allow different decoders to take different shortcuts in order to display images. 

The conclusion is just not to use jpeg images for scientific analysis.

**Comment by jni** [comment]
@hmaarrfk that rings a bell, but I can't find that discussion to link to it. Do you remember where it was?

**Comment by stefanv** [comment]
From https://stackoverflow.com/a/23714501/214686:

> The JPEG standard does not require that decoder implementations produce bit-for-bit identical output images. Unfortunately the standards document specifying decoder requirements, ISO 10918-2, is apparently not freely available online but Wikipedia says:

> >  ...the JPEG standard (and the similar MPEG standards) includes some precision requirements for the decoding, including all parts of the decoding process (variable length decoding, inverse DCT, dequantization, renormalization of outputs); the output from the reference algorithm must not exceed: a maximum 1 bit of difference for each pixel component, low mean square error over each 8×8-pixel block, etc.

You are probably using different plugins on these different systems.  Try specifying the plugin as follows:

```
io.imread(..., plugin='matplotlib')
```

Plugin can also be `imageio` or `pil`.

**Comment by soupault** [comment]
@jni I remember https://github.com/scikit-image/scikit-image/issues/2293 , but it is not really about platform differences.

**Comment by jni** [comment]
@soupault brilliant, thanks for finding that! Reading that conversation reinforces @hmaarrfk's summary. I'm going to close this as not-a-bug/won't-fix. @fengxiaoshuai I hope you find the linked discussion as enlightening as I did! (And the ones linked there as well.)
