### ISSUE TITLE
move numpy pinning forward?

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3924]
scipy 1.3 now requires numpy 1.13.3.

pip is pretty at dependency solving and just installed numpy 1.11 and scipy 1.3 together and broke the build system.

Should we move our pinning to alleviate the task of doing it later?
It seems like a good idea to follow scipy, unless we have a good reason not to.

As a reference, numpy 1.13.3 was released in sept 2017
https://github.com/numpy/numpy/releases/tag/v1.13.3

**Comment by stefanv** [comment]
No objections from me.
