### ISSUE TITLE
camera(man) image must be removed for license issues

### ISSUE THREAD

**Issue by carandraug** [scikit-image/scikit-image#3927]
I am interested on the use of the `camera.png` image. The file is at `skimage/data/camera.png`. However, I am unable to find copyright information about this file on the scikit-image repository.

My understanding is that this image is copyright of MIT and one would need permission to use and redistribute it.

**Comment by jni** [comment]
Hmm, I couldn't find any info on the image online either. As policy we only include CC0/Public domain images, but I don't know the source here. @stefanv @ahojnnes @JDWarner ?

**Comment by matthew-brett** [comment]
I couldn't find any license information, except that the image is one of the most common of the images used for image processing demonstrations.

https://www.quora.com/What-are-the-most-common-example-images-used-in-image-processing-and-computer-vision

You can find quite a few papers using this image to demonstrate image processing algorithms.

I saw the claim that the image belongs to MIT, but nothing to support it:

https://www.npmjs.com/package/cameraman

**Comment by carandraug** [comment]
> I saw the claim that the image belongs to MIT, but nothing to support it:

On a Matlab installation, where this image is named "cameraman", in the file `toolbox/images/imdata/Contents.m`, it says the following "Copyright Massachusetts Institute of Technology.  Used with permission."

**Comment by matthew-brett** [comment]
Aha - then I guess we have to ask the Mathworks who they got permission from.

**Comment by stefanv** [comment]
That copyright claim is validated by Steve Eddins in [this entertaining blog post](https://blogs.mathworks.com/steve/2006/10/17/the-story-behind-the-matlab-default-image/) (see the comments).

I will write MIT and ask.

**Comment by stefanv** [comment]
I'm afraid we'll have to start looking for a new image to replace our existing cameraman image.  Does anyone have an antique camera and a suit, so they can go and pose on the lawn? :)

Peter Bebergal of MIT wrote:

> After much research,  it turns out that MIT cannot actually be certain the image
is owned by MIT and as such cannot be released under a CC license. The most we
can do is say that by whatever rights we do have in the image, we can grant its
use for the express purpose you need. While MIT has been giving permission in
the past, it is not clear we should have done so without this disclaimer.

I then asked:

> Thank you very much for taking the time to investigate. Did you happen upon any
clues as to whom may have taken or provided the original?
>
> When you say "for the express purpose you need": as a library, our purpose is to
let our users use images without having to fear any copyright infringement. As
far as MIT is concerned, I then understand this to mean that they will not take
action when this image is used for practically any purpose (since we cannot
control what our users do).
>
> Please correct me if I am interpreting your words too liberally.

To which he replied:

> So the image is not simply used an example, but you want to distribute it as
open source along with the software? If that is the case, we cannot give you any
permission to do so as we simply cannot confirm our copyright.

**Comment by stefanv** [comment]
See also: https://twitter.com/stefanvdwalt/status/1136039155119472640

**Comment by jni** [comment]
:scream: :scream: :scream:

**Comment by stefanv** [comment]
Who will let The Mathworks know :laughing:

**Comment by sciunto** [comment]
Found [this (CC0)](https://www.flickr.com/photos/wyncliffe/13184340485/in/photolist-m64c6g-Em5r69-7vTNoP-7vWip6-7vYEkh-DQtK3Q-EeHwkV-7vUvPz-DQtHds-N6Z6Kb-N5DTnQ-HU1XHm-4jYwkq-YrYtxv-2erywby-2fQvkh6-oa8UP4-o8oEoN-o8oyaW-nSVCBd-nSVWjf-nSVzYC-occ3Te-ocbKWP-4GD3dQ-nSWCL9-nSWUX5-oa8xGK-nSW6jm-oahSg3-oaqm6t-occbpM-nSVL69-oa7fi8-4wXFJ8-nSX1jC-nSWDim-oairFQ-nSWuc5-nSWsrw-oa8EVx-nSWqMC-oajUW7-ocbGpZ-FMEzhS-JHZweF-JYBPFP-23vdtmM-A4aZNA-LiHU64)

**Comment by stefanv** [comment]
On Thu, 06 Jun 2019 00:26:12 -0700, François Boulogne wrote:
> Found [this (CC0)](https://www.flickr.com/photos/wyncliffe/13184340485/in/photolist-m64c6g-Em5r69-7vTNoP-7vWip6-7vYEkh-DQtK3Q-EeHwkV-7vUvPz-DQtHds-N6Z6Kb-N5DTnQ-HU1XHm-4jYwkq-YrYtxv-2erywby-2fQvkh6-oa8UP4-o8oEoN-o8oyaW-nSVCBd-nSVWjf-nSVzYC-occ3Te-ocbKWP-4GD3dQ-nSWCL9-nSWUX5-oa8xGK-nSW6jm-oahSg3-oaqm6t-occbpM-nSVL69-oa7fi8-4wXFJ8-nSX1jC-nSWDim-oairFQ-nSWuc5-nSWsrw-oa8EVx-nSWqMC-oajUW7-ocbGpZ-FMEzhS-JHZweF-JYBPFP-23vdtmM-A4aZNA-LiHU64)

Thanks for searching, François.  I think we need a photo with some edges
and clear background objects to make a good test image.

**Comment by sciunto** [comment]
I also found that one: https://www.publicdomainpictures.net/en/view-image.php?image=197897&picture=reporter-camera

**Comment by stefanv** [comment]
Please hold for an update from MIT.

**Comment by JDWarner** [comment]
This just serves to illustrate how insane current copyright is.  If 14
years with one renewal was good enough for the printing press, 5 years with
one renewal should be entirely sufficient today as an upper bound.

If we had rational copyright and a robust public domain - the enrichment
thereof which is the supposed entire purpose of copyright - this whole
discussion would be moot.

**Comment by grlee77** [comment]
> Please hold for an update from MIT.

Anything new to report yet? This image is also currently included in PyWavelets, so I am trying to determine whether we will need to remove it there as well.

**Comment by stefanv** [comment]
MIT is in the process of releasing the image; they told us to go ahead and keep using it.

**Comment by grlee77** [comment]
Great, thanks @stefanv!

**Comment by emmanuelle** [comment]
I've removed the 0.17 milestone because hopefully nothing more to be done. Thanks @stefanv !

**Comment by carandraug** [comment]
I may be missing something but was the conclusion of this? I contacted MIT independently who told me the same, that they could not be sure of the copyright of it. Can someone clarify the status of that? I would also like to redistribute the cameraman image.

**Comment by hmaarrfk** [comment]
Seeing as this issue was quite contentious, stefanv, could you open a PR adding documentation on how you arrived at the conclusion that we do have the rights to continue to distribute this image?

**Comment by stefanv** [comment]
I was in conversation with Peter Bebergal, a Technology Licensing Officer at MIT.  We exchanged numerous emails, but the important pieces from August 14, 2019:

"It looks like we feel we have sufficient rights to be able to release the image under CC [...] I'll start that process. You can continue to use the image in the meantime."

**Comment by grlee77** [comment]
> "It looks like we feel we have sufficient rights to be able to release the image under CC [...] I'll start that process. You can continue to use the image in the meantime."

should we go ahead and close this, then or did you want to await final confirmation?

**Comment by stefanv** [comment]
As far as I am concerned, we have permission to continue as we are, and can do so until a new license is released.

**Comment by carandraug** [comment]
> As far as I am concerned, we have permission to continue as we are

Can you clarify, please, under what rights are you releasing this image? As downstream, under what conditions can I redistribute this image?

**Comment by stefanv** [comment]
@carandraug Yes, it's somewhat of a mystery, isn't it.  We know it is an open license, likely CC, but the particulars are unknown at this point in time.  We know that our users will not be exposed to risk by using this image but, technically, we should remove it until we get MIT's specifics on the CC license—but that incurs discomfort for little gain.

In the interim, how about we add a notice to the docstring that states MIT's intent to release this as a CC image?  I can also follow up with them to determine its status.

**Comment by carandraug** [comment]
> Yes, it's somewhat of a mystery, isn't it. We know it is an open license, likely CC, but the particulars are unknown at this point in time. 

Do we know that? The last message I got from them was also from Peter Berbegal on 15th of August was:

>  It turns out we will be able to release the image under a CC non-commercial license if you would still like to use it.

which is not an open license.

Also, I don't understand how MIT can tell us they have sufficient rights to release the image and at the same time it doesn't release the image after one year. They either know who the copyright holders are, in which case this could be solved easily, or they don't know who the copyright holders are, in which case they can't really decide the license.

> In the interim, how about we add a notice to the docstring that states MIT's intent to release this as a CC image? I can also follow up with them to determine its status.

They have the intent to do it but they don't after one year; they say a CC license which may or may not be an open license; and they say they have *sufficient* right (not *the* rights) and they were certain they didn't have the rights at the start. Not your fault obviously, but this limbo situation doesn't inspire a lot of trust.

**Comment by stefanv** [comment]
I've pinged MIT; let's see.  If I don't get a definitive response, we'll remove the image.

**Comment by stefanv** [comment]
I've just had confirmation that MIT *requires* the NC clause, so I believe we have no option but to remove cameraman from our library.

**Comment by alexdesiqueira** [comment]
Closing; solved on #4913, according to the discussion on #4914. Thank you everyone!
