### ISSUE TITLE
match_histograms import fails

### ISSUE THREAD

**Issue by changbaishan** [scikit-image/scikit-image#3941]
## Description
from skimage.transform import match_histograms
you end up with:
ImportError: cannot import name match_histograms

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
0.15.0
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by changbaishan** [comment]
This problem seems to be associated with conda install. I just had a pipenv, then pip installed scikit-image, this problem disappeared.

**Comment by keshav99** [comment]
Downgrading to 0.15.0 worked for me. Even in pipenv it didn't work for 0.16.2

**Comment by maliktalha370** [comment]
I have verified from code, It is moved 
`from skimage.exposure import histogram_matching`
