### ISSUE TITLE
should data_dir.load be a public function

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3947]
https://github.com/scikit-image/scikit-image/blob/822ad3edddaba91e43dfc1adf2fe4339dbefb97b/skimage/data/__init__.py#L23

it seems like it is mostly an internal function. In migrating to pooch, ~~I would like to really add some hacks that make it really only for our internal data~~
https://github.com/scikit-image/scikit-image/pull/3945

**Comment by jni** [comment]
I think you're right: this should be deprecated. @stefanv?

**Comment by stefanv** [comment]
On Mon, 03 Jun 2019 02:27:50 -0700, Juan Nunez-Iglesias wrote:
> I think you're right: this should be deprecated. @stefanv?

Yes, should be private.
