### ISSUE TITLE
Measuring usage of particular scikit-image APIs

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3954]
I recently came across this post from Christopher Ostrouchov at Quansight labs: [Measuring API usage for popular numerical and scientific libraries](https://labs.quansight.org/blog/2019/05/python-package-function-usage/).

They downloaded a bunch of packages using the libraries.io API and then analysed them with the ast module to find which APIs were most used from each of a bunch of packages, including scikit-image.

There's clearly stuff missing from libraries.io (perhaps they only do PyPI), but there is a lot of code to reuse in there, and even some interesting data in the current summary tables (visible from the blog post). Transform is among our most-used modules, so I'm having some second thoughts about deprecating the xy stuff. Perhaps we should directly add `ndtransform` or `ndwarp` or similar, and only "soft-deprecate" the current version of warp, removing examples from the site and discouraging use, but not removing for a long time, until we see those usage numbers decrease.

Or, maybe it's fine, we're still 0.x... 

Anyway, at the very least, it's something to think about!

We could probably re-do this analysis using GitHub's "used by" rather than the libraries.io API. That might get us some jupyter notebooks, which I think the current analysis overlooked (as far as I can tell, all the notebook statistics files are empty).

**Comment by jni** [comment]
I forgot to link to the code:

https://github.com/Quansight-Labs/python-api-inspect

**Comment by stefanv** [comment]
@jni This is probably better suited for the mailing list.  Since there is no obvious way to resolve the issue, I'm going to go ahead and close it for now.  Do you mind reposting to the list instead?

**Comment by jni** [comment]
>  Since there is no obvious way to resolve the issue,

Isn't there? My idea was that someone at some point might have time to download all the "used-by" libraries pointed by GitHub, and run the inspect-api code on them, then post the results here, at which point it could be closed.

The transform deprecation could probably be discussed on the list, yes.

**Comment by jni** [comment]
> The transform deprecation could probably be discussed on the list, yes.

... but I need to gather my own thoughts about it, and also make an example that clearly explains the problem and the proposal, before posting.
