### ISSUE TITLE
I am building a repo with all the demo examples for easy browsing by users

### ISSUE THREAD

**Issue by tirthajyoti** [scikit-image/scikit-image#3962]
## I am building a repo with all your demo

It looks like your [demo folder](https://github.com/scikit-image/skimage-demos) is out of date and **not actively maintained**.

I am building (self-learning purpose) a repo with pretty much all the examples that you have on your website. Users can easily come and download notebooks.

Right now, I am keeping the descriptions same as the website but **plan to change them by adding more links to image processing tutorials, videos, etc.**

Hope it is not an issue.

**[Here is my repo](https://github.com/tirthajyoti/Scikit-image-processing)**

**Comment by stefanv** [comment]
@tirthajyoti Thanks for the note.  You are right, the [demos](https://github.com/scikit-image/skimage-demos) are not regularly revised, but we would still appreciate any PRs with fixes.  You may reuse the material under the [license provided](https://github.com/scikit-image/skimage-demos/blob/master/LICENSE.txt).  The [tutorials](https://github.com/scikit-image/skimage-tutorials) are used more frequently, and should be more-or-less up to date.
