### ISSUE TITLE
Error installing 0.14.3 on Mac: zlib.error: Error -3 while decompressing data: invalid code lengths set

### ISSUE THREAD

**Issue by csala** [scikit-image/scikit-image#3972]
## Description

Installing scikit-image 0.14.3 using Python 3.6.8 on Mac OS crashes.

scikit-image 0.15.0 installs without issues, but I haven't had the option to try other versions of either python or scikit-image.

## Way to reproduce

Simply install scikit-image 0.14.3 on Mac OS using python 3.6.8.

I have been able to reproduce it in 3 different Macbook Pro Laptops, two of them brand new (right after the initial setup).

1. Download the Python 3.6.8 installer from the Python downloads site and install it.
2. Install virtualenv using pip3

```bash
pip3 install virtualenv
```

3. Create a virtualenv with pyhon3 interpreter

```bash
virtualenv -p $(which python3) scikit-image-test
```

4. Install scikit-image:

```bash
pip install scikit-image==0.14.3
```

## Version information

* Python: 3.6.8
* OS: Mac OS 10.14.[34]
* Clean virtualenv, so no other packages are installed.

## Output

This is the output when executing the pip install command:

```
$ pip install scikit-image==0.14.3
Collecting scikit-image==0.14.3
  Using cached https://files.pythonhosted.org/packages/73/fd/5f4f2a3819967fb87e3a6fc56470b6b0dd134ddca0f66b1b0b0a825af2d1/scikit_image-0.14.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/download.py", line 886, in unpack_url
    progress_bar=progress_bar
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/download.py", line 750, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 628, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/Users/dailab/scikit-image/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 524, in unzip_file
    shutil.copyfileobj(fp, destfp)
  File "/Users/dailab/scikit-image/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 872, in read
    data = self._read1(n)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 948, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code lengths set
```

**Comment by hmaarrfk** [comment]
Hmm i'm sorry, I probably can't be of much help since I don't use Mac too much. 
It is a pretty detailed response, so maybe somebody will be able to chime in.

0.14.3 is newly minted. It is technically newer than 0.15.0. 
It is very possible that there might be new bugs in the build process for mac osx.

It would be good to figure things out before we release 0.15.1

You seem to knnow what you are doing, and I got nothing better to say than I'm watching and hope we get this resolved :/

**Comment by jni** [comment]
I just downloaded that exact wheel on my Mac, unzipped it manually, and verified that it worked. (I could `import skimage` and use the contents of the wheel.) So my first guess right now is that your wheel download was corrupted. Three suggestions:

1. Try again with `pip install --no-cache-dir scikit-image==0.14.3` to avoid using the cached image
2. Find the cached file in `~/Library/Caches/pip/wheels`, and check its SHA256 sum with the command `shasum -a 256 [filenmae]` (Note, the files are in nested directories 4-deep, so you can find the files with `ls */*/*/*/scikit_image*`. The correct SHA256 sum can be found on PyPI.org: https://pypi.org/project/scikit-image/0.14.3/#files and is fb1de3dabbc7a429b38a016d01502920226b59d277578291fb18a28888ed5792.
3. Try to download the wheel file manually from the link above, and install it using these instructions: https://stackoverflow.com/questions/28002897/wheel-file-installation (installing the `wheel` package first, then `pip install my_wheel_file.whl`.

Please let us know if any of these options fix your problem!

**Comment by durden** [comment]
I've seen the same issue in Windows with Python 3.7 from Anaconda and doing a `pip install`:

![Screenshot 2019-06-27 10 21 39](https://user-images.githubusercontent.com/58063/60249625-7cb92b00-98c5-11e9-9537-2b75e07dbfde.png)

**Comment by soupault** [comment]
I can reproduce the original issue in Conda environment on Mac. Happens with Python 3.6.8 and scikit-image 0.14.3. Does not happen with scikit-image 0.14.2 and 0.15.0 + Py3.6.8 and/or scikit-image 0.14.3 + Py3.7.3.

Zlib version was the same for both tests - zlib-1.2.11-h1de35cc_3 .

**Comment by thehesiod** [comment]
I downloaded the whl and could not decompress it: https://files.pythonhosted.org/packages/73/fd/5f4f2a3819967fb87e3a6fc56470b6b0dd134ddca0f66b1b0b0a825af2d1/scikit_image-0.14.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

**Comment by csala** [comment]
It looks like 0.14.4 can be installed without issues on the same , so whatever caused this error is not affecting the current versions anymore.

I leave it up to the maintainers to close this issue.

**Comment by jni** [comment]
@csala great to hear! I guess this will be a mystery lost to time, but I'm happy that the problem is resolved for you. Feel free to ping or reopen if you encounter any more issues!
