### ISSUE TITLE
How to solve memory issue ? when i working with DICOM Volume 1000 X 1000X5000 Data sets?

### ISSUE THREAD

**Issue by selvakarna** [scikit-image/scikit-image#3979]
How to solve memory issue ? when i working with DICOM Volume 1000 X 1000X5000 Data sets?    

return clabel(input, neighbors, background, return_num, connectivity)
  File "skimage/measure/_ccomp.pyx", line 358, in skimage.measure._ccomp.label_cython
MemoryError

**Comment by jni** [comment]
Hi @selvakarna,

This is not a question and answer forum, so although I will answer briefly, I will also point you to:

forum.image.sc

and

stackoverflow.com

to get more detailed help. Please see [how to ask a question](https://stackoverflow.com/help/how-to-ask) for tips on how best to help people find an answer for you.

To briefly answer your question: for a label image (typically int32, sometimes int64), that size image will be 5 * 4 = 20GB or even 5 * 8 = 40GB. So on most machines you are not going to be able to process it in-memory. My favourite tool for working with large images is [Dask](https://dask.org) and https://github.com/dask/dask-image. @jakirkham recently wrote a [blog post](https://blog.dask.org/2019/06/20/load-image-data) about loading large images into dask-array, but you will need to adapt that to DICOM images, which won't be trivial (and is out of scope for scikit-image). For downstream processing, the functions in dask-image will be very useful, including `dask_image.ndimage.label`.
