### ISSUE TITLE
Packaging failures with Pytest 5.0

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3986]
## Description

Pytest 5.0 was just released. It builds-in pytest-faulthandler and causes errors during packaging because we have pytest-faulthandler in requirements.txt.

Failing build: https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=761&view=logs&jobId=38fa3105-a3d6-58c5-2eec-10e695f0c1d9&taskId=a0d33157-d94d-587b-eae8-ff8bf4466631&lineStart=5880&lineEnd=5881&colStart=1&colEnd=1

We should either pin to 4.x or to 5.0+. I'd rather avoid complicated dependency logic doing different things for different pytest versions.

**Comment by jni** [comment]
I slightly favour updating the dependency to 5.0, because it is pure python and it is worse to prevent people from upgrading than it is to force people to upgrade.

**Comment by hmaarrfk** [comment]
Just remove the dependency on pytest-faulthandler if it is built it. It was always a "nice to have" that helps us developers for when C stuff breaks. Not necessary for anybody to install really.

**Comment by hmaarrfk** [comment]
Anyway, i asked upstream to release a dummy package. It should help us out (and others presumably)
https://github.com/pytest-dev/pytest-faulthandler/issues/36

**Comment by hmaarrfk** [comment]
```

self = <skimage.util.tests.test_arraypad.ValueError3 testMethod=test_mode_not_set>

    def test_mode_not_set(self):
        arr = np.arange(30).reshape(5, 6)
        with testing.raises(TypeError):
>           pad(arr, 4)
E           Failed: DID NOT RAISE <class 'TypeError'>
```

This just seems like numpy decided to default padding to 0s if the mode wasn't set. I actually think that @stefanv  pushed for that change ^_^

**Comment by nicoddemus** [comment]
> Anyway, i asked upstream to release a dummy package. It should help us out (and others presumably)
pytest-dev/pytest-faulthandler#36

`2.0.1` has been released as a dummy package, hope that helps! 👍
