### ISSUE TITLE
Tiff-reading related warning 

### ISSUE THREAD

**Issue by YubinXie** [scikit-image/scikit-image#3989]
## Description

Got the following warning when read microscope TIFF images (some are tiled tiff). 
I compared results with PIL, which also requires some tuning to make it work (I need to reshape the image), the results are the same (the max value). I just do not know how to deal with the warning. (I am unable to upload these files)

```
/Users/xy/miniconda3/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py:2573: RuntimeWarning: py_decodelzw encountered unexpected end of stream
  tile = decompress(tile)
/Users/xy/miniconda3/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py:2579: UserWarning: invalid tile data
  warnings.warn("invalid tile data")
/Users/xy/miniconda3/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py:2546: UserWarning: unpack: string size must be a multiple of element size
  warnings.warn("unpack: %s" % e)

```
## Way to reproduce
```python
from skimage.external.tifffile import TiffFile, TiffWriter, imread
max_array_1 = np.array([np.max(imread(x),axis=(1,2)) for i,x in enumerate(tiff_images)  ])
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Darwin-18.5.0-x86_64-i386-64bit
scikit-image version: 0.14.2
numpy version: 1.16.0

```

**Comment by hmaarrfk** [comment]
I think we've included quite an old version of Tiffile. Maybe try installing tiffile yourself with Pip and seeing if the issue persists?

Can you also share the image with us? That way we can try to see if we can reproduce locally.

**Comment by YubinXie** [comment]
I updated the tifffile (and directly use it) and two of the warnings are gone. Only one left. 

```
UserWarning: invalid tile data
  warnings.warn("invalid tile data")
``` 

The data are still private so far. Sorry about that!

**Comment by hmaarrfk** [comment]
Yeah. We have a rather old version of tiff file. I would use the original package. And maybe raise an issue with @cgohlke

**Comment by sciunto** [comment]
I close this issue as #3992 must solve most of the problems (tifffile updated).
