### ISSUE TITLE
Bilateral filter is broken (going back to at least 0.14.x)

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#3995]
Current gallery example:
https://scikit-image.org/docs/stable/auto_examples/filters/plot_denoise.html

0.13.x gallery example:
https://scikit-image.org/docs/0.13.x/auto_examples/filters/plot_denoise.html

Same code.  Not subtle.

This may have been introduced in #3937, though it could have been earlier; the gallery example from the most current 0.14.x is also affected.  I'm rather surprised it passes tests.

**Comment by alexandrejaguar** [comment]
Running `git bisect` I tracked it to #3880. My guess is that changing the dtypes (`double` -> `np_real_numeric` messed our padding somehow. @hmaarrfk do you have a hint on how to fix this?

**Comment by alexandrejaguar** [comment]
Never mind. I'm on it
