### ISSUE TITLE
SKIP: remove interpolation=nearest in our examples

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#3998]
## Description

Since 1.1.x, matplotlib set interpolation to nearest [by default](https://matplotlib.org/3.1.0/api/prev_api_changes/api_changes_1.1.x.html). We have plenty of examples in which the option is set to nearest (and a few to None).

I think there is room for simplifying our examples by removing these options. Any comment?

**Comment by jni** [comment]
Do it! :tada: :fireworks:
