### ISSUE TITLE
Documentation issues with inertia_tensor

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#4004]
## Description

`skimage.measure.inertia_tensor` is correctly imported in `skimage/measure/__init__.py`, but it does not appear in the [`measure` docs](https://scikit-image.org/docs/dev/api/skimage.measure.html), I presume because it's not included in `__all__`.

Additionally, the regionprops.inertia_tensor and inertia_tensor_eigvals incorrectly specify 2D data instead of nD.

**Comment by marshuang80** [comment]
Should the issue be closed with PR #4013?

**Comment by alexandrejaguar** [comment]
Closing; solved on #4013. Please reopen if necessary.
