### ISSUE TITLE
task: unify FFT usage across scikit-image

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#4043]
## Description

There are a few issues related to the usage of FFTs in scikit-image that could use some maintainance. I will try to make PR(s) to address these in the near future. There are a few separate issues:

**1.)  unify FFT modules used**
FFTs are called from a variety of sources across the library.:

Functions from `scikit.fftpack` are called in:
    `skimage/transform/radon_transform.py`

Functions from `numpy.dual` are called in:
    `skimage/filters/lpi_filter.py`

(These `numpy.dual` call SciPy's fft when scipy.fftpack has been imported. Otherwise they fall back to the numpy implementations)

A number of other files/functions just call the functions from `numpy.fft` directly.

Unless there is a compelling reason otherwise, we should try to use a single convention.

**2.) replace any unitary FFT code that is no longer needed**

The unitary FFTs in `skimage.restoration.uft` seem to implement functionality that has since been implemented directly in NumPy / SciPy via the `norm='ortho'` argument (introduced in NumPy 1.10).

**3.) Take advantage of the new scipy.fft module when available**
As a result of a GSOC 2019 project, SciPy 1.4.0 will have a new `scipy.fft` module that has the same API as `scipy.fftpack`, but has a number of accuracy and performance improvements. [More details here](https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.4.0#scipyfft-added)

I think we should try to use these `scipy.fft` variants when available because they make it easy for the user to swap out the FFT backend to something like pyFFTW when desired via a simple context manager or a call to `scipy.fft.set_global_backend`. An example of how that would look can be seen at: https://github.com/pyFFTW/pyFFTW/pull/269#issuecomment-512336676

**Comment by jni** [comment]
@grlee77 brilliant! I very much like this task. =)

**Comment by sciunto** [comment]
Might be of interest: #3735

**Comment by grlee77** [comment]
Regarding items 1 and 3 above. I think there are a few possible options. I am interested to hear what other devs here prefer prior to working on this.

One option is to use `numpy.dual.fft`, more widely.  Upon import `scipy.fftpack` or the new `scipy.fft` configure the FFT functions in `numpy.dual` to point to the corresponding functions in their module instead of the numpy ones. However, `numpy.dual` has only a subset of the FFT functions in its namespace, so this would not work for functions like `rfft` or `irfft`. Also, that behaviour is not the most transparent or well documented and I think many devs/users are likely unaware that `numpy.dual` even exists. The module doesn't appear to be deprecated, but it also hasn't been updated in years.

A second alternative is something like
```Python
try:
    import scipy.fft  # scipy 1.4.0+
    fft_module = scipy.fft
except ImportError:
    fft_module = numpy.fft
```
and then use functions via `fft_module.fft`, etc... That logic could live somewhere like `skimage.util.fft` so the same logic wouldn't have to be duplicated in several locations.

Another consideration is that NumPy always uses double precision for its FFTs while the scipy-based ones do single-precision transforms on single-precision inputs. I'm not sure if always using double precision is a desired property in the locations where `np.fft` functions are currently being used.

@peterbell10, do you have any other ideas/recommendations for how downstream projects should transition to using the new `scipy.fft` module when it will likely be 1-2 years until we bump our requirements to scipy >= 1.4.
