### ISSUE TITLE
min_distance in feature.peak_local_max has an unexpected behavior

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4048]
## Description

Increasing the min_distance value in the example below does not suppress the closest detected peaks!

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
```
3.7.3 (default, Jun 24 2019, 04:54:02) 
[GCC 9.1.0]
Linux-4.19.59-1-MANJARO-x86_64-with-arch-Manjaro-Linux
scikit-image version: 0.16.dev0 and 0.15.0
numpy version: 1.16.1

```

```python
# your output here
import skimage
from skimage import feature
import matplotlib.pyplot as plt
%matplotlib inline

skimage.__version__


distance_map = skimage.io.imread('/tmp/toto.png')
peaks = feature.peak_local_max(distance_map)
peaks_filtered = feature.peak_local_max(distance_map, min_distance=10)

fig, ax = plt.subplots(nrows=2, figsize=(20, 20))
ax[0].imshow(distance_map)
for p in peaks:
    ax[0].plot(p[1], p[0], 'r.')
    
ax[1].imshow(distance_map)
for p in peaks_filtered:
    ax[1].plot(p[1], p[0], 'r.')

```

Input image

![toto](https://user-images.githubusercontent.com/335370/61796148-1fad8800-ae25-11e9-90c3-ba3c54a066e0.png)

result.

![index](https://user-images.githubusercontent.com/335370/61796158-2805c300-ae25-11e9-80c4-cad69526f4e1.png)

close pairs of peaks are still there... while single peaks are removed :(

**Comment by rfezzani** [comment]
Isn't this the expected result? The documentation says
> If there are multiple local maxima with identical pixel intensities inside the region defined with min_distance, the coordinates of all such pixels are returned.
What you are looking for is the `corner_peak` I think.

**Comment by jni** [comment]
@rfezzani I still think this behaviour is surprising.

**Comment by rfezzani** [comment]
For sure, we must then call `corner_peak` internally ;-)

**Comment by rfezzani** [comment]
I can't reproduce this bug :tada: 
```python
import imageio
import skimage
from skimage import feature
import matplotlib.pyplot as plt

print(skimage.__version__)

distance_map = imageio.imread('/tmp/toto.png')
peaks = feature.peak_local_max(distance_map)
peaks_filtered = feature.peak_local_max(distance_map, min_distance=10)

fig, ax_list = plt.subplots(ncols=3, figsize=(12, 4))

for d, ax in zip([1, 5, 10], ax_list):
    ax.imshow(distance_map)
    peaks = feature.peak_local_max(distance_map, min_distance=d)
    for p in peaks:
        ax.plot(p[1], p[0], 'r.')
    ax.set_axis_off()
    ax.set_title(f"min_distance={d}")

fig.tight_layout()
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/3438227/115682357-af170080-a355-11eb-847b-1223b9531441.png)
