### ISSUE TITLE
Consider deprecating `viewer` and `skivi`

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#4081]
It looks like [Napari](https://github.com/napari/napari) is shaping up nicely, so it may be time to consider deprecating our image viewer, and potentially our viewer widgets.

It looks like there are tens of thousands of imports of the viewer module, though, so it would be good to provide some kind of backward compatibility route, if at all possible.

https://github.com/search?p=3&q=from+skimage+import+viewer&type=Code
https://github.com/search?q=import+skimage.viewer&type=Code

**Comment by jni** [comment]
Given the high usage, I would say that we should deprecate it only once we can replicate the functionality in that module in napari, and then point users to a specific doc page in napari for migrating. That's probably about a week's work, but it's unlikely to happen before october at the earliest. See https://github.com/napari/napari/issues/301

**Comment by rfezzani** [comment]
What about moving `skimage.viewer` to `scikit-image-contrib`?

**Comment by jni** [comment]
@rfezzani I think we should move it to `scikit-image/skimage-viewer`.

**Comment by rfezzani** [comment]
Could we consider using [namspace packaging](https://packaging.python.org/guides/packaging-namespace-packages/) for this purpose?

**Comment by rfezzani** [comment]
Thank you @sciunto for reviving this! I am still in strong favor of removing as much package dependencies as possible:
Deprecating `skivi` and the `skimage.io` submodule allows to remove the dependency to `imageio`, `pillow`, `tifffile` and `matplotlib`!

**Comment by sciunto** [comment]
Good! I think we have other places where we depend on matplotlib, but I agree for the other lib. We might raise the question to maintain an API around imageio or not, but this out of the scope of this issue.
