### ISSUE TITLE
testsuite: Ubuntu 14.04 is End of Life

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#4085]
## Description
https://wiki.ubuntu.com/Releases

I'm not too sure how this affects the wheel builder. If we drop 14.04 from our test matrix, I think we need to update the manylinux standard to a newer one

https://www.python.org/dev/peps/pep-0571/

xref: https://github.com/scikit-image/scikit-image/pull/4082

**Comment by hmaarrfk** [comment]
https://github.com/matthew-brett/multibuild/issues/238

**Comment by grlee77** [comment]
closing this as stale. I don't think we still use Ubuntu 14.04 anywhere (GitHub actions appear to be using either 18.04 or 20.04)
