### ISSUE TITLE
label2rgb -- explain how to make the background label transparent in doc

### ISSUE THREAD

**Issue by VolkerH** [scikit-image/scikit-image#4091]
## Description

It appears that label2rgb does not provide the option to make the background label transparent when the labels are drawn on a greyvalue image.

## Way to reproduce

The coin segmentation example provides an exmaple. The whole image outside the coins is covered in a reddish tint (which happens to be the color for the backgroud label). When drawing over a greyvalue image it is often desirable, to keep large areas of background unmodified and only color in the actual foreground labels. Specifying the background color does not help, as there is no seperate transparency option.
I looked through the documentation but it appears that a transparent background label is not supported (@jni ?).

**Comment by jni** [comment]
@VolkerH looking at the code [here](https://github.com/scikit-image/scikit-image/blob/7a85970ed21d96366ddcb3136ad546c907436277/skimage/color/colorlabel.py#L192-L195), it looks like a transparent background is supported when `kind='overlay'` and `bg_color=None`. However, I don't see an equivalent line for `kind='avg'`, and anyway the documentation is lacking, so this should all be fixed. Thanks for the report!

**Comment by VolkerH** [comment]
Reading through the code it seems like the background label should be replaced by the image.
That's not what I am seeing however:

![image](https://user-images.githubusercontent.com/2210044/63065367-1f4a6d80-bf49-11e9-8fd3-6de955555b4c.png)

Plotting the background image by itself:
![image](https://user-images.githubusercontent.com/2210044/63065390-37ba8800-bf49-11e9-9e9e-8835befcbfbe.png)

and checking which areas have the label 0:

![image](https://user-images.githubusercontent.com/2210044/63065411-51f46600-bf49-11e9-867e-73b0c9cbf905.png)

Note that changing the background image to rgb before passing it in doesn't make a difference

![image](https://user-images.githubusercontent.com/2210044/63065480-9122b700-bf49-11e9-86c9-34eb66b0c842.png)

The skimage version is the one from the pull request with the `regionprops_table` feature.
I will see whether I can create a minimalist gist to reproduce this.

Note that I don't see any reason why the background should have a reddish tint in this example
https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_label.html as `kind='overlay'` and `bg_color=None` are the default values for `label2rgb`.

**Comment by VolkerH** [comment]
Digging deeper ...

the term `0 in mapped_labels_flat` equates to false for my examples in this line:

https://github.com/scikit-image/scikit-image/blob/7a85970ed21d96366ddcb3136ad546c907436277/skimage/color/colorlabel.py#L193

And `mapped_labels_flat` is returned from `_match_label_with_color`. Looking there, I don't fully understabnd the code block starting at this line:
https://github.com/scikit-image/scikit-image/blob/7a85970ed21d96366ddcb3136ad546c907436277/skimage/color/colorlabel.py#L60
My intuition tells me that the following line in combination with  `0 in mapped_labels_flat` 

https://github.com/scikit-image/scikit-image/blob/7a85970ed21d96366ddcb3136ad546c907436277/skimage/color/colorlabel.py#L65

would explain the observed behaviour.

**Comment by VolkerH** [comment]
Ok, I found my mistake. I had to explicitly pass `bg_label=0` as it defaults to `-1`. I was so convinced that the background label should default to `0` that I didn't check this.
Leaving the issue open, as documentation would indeed benefit from an enhancment and additional examples.

Just for completeness, this was the desired output that I now got when passing in `bg_label=0`.

![image](https://user-images.githubusercontent.com/2210044/63072162-ac9bbb00-bf65-11e9-827d-03335bd7ef92.png)

**Comment by sciunto** [comment]
Thanks for digging into this @VolkerH Would you like to open a PR and edit the documentation to get something that would have helped you?

**Comment by VolkerH** [comment]
Yes, I will make some edits.

**Comment by sciunto** [comment]
Thanks!

**Comment by sciunto** [comment]
@VolkerH Have you make progress on this task?

**Comment by soupault** [comment]
Closed via #4527 .

**Comment by VolkerH** [comment]
Sorry, I forgot about this and only just saw the notification. Thanks for fixing @lisabug  and @soupault .
