### ISSUE TITLE
How to use skimage on spark?

### ISSUE THREAD

**Issue by DonghaiYu** [scikit-image/scikit-image#4093]
## I want to use skimage package on spark cluster, but not installed on those servers.
I want to submit my task by '--py-files', but failed.

**Comment by DonghaiYu** [comment]
skimage version 0.14.2

**Comment by soupault** [comment]
Hi, @DonghaiYu. Please, post your question on https://stackoverflow.com. scikit-image team does not provide an official support for Spark integration.
I have little experience with Spark myself, so cannot recommend anything specific. However, you might be interested in checking how Spark integration is implemented for other libraries, for example, scikit-learn - https://github.com/databricks/spark-sklearn.
