### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#4100]
According to https://github.com/numpy/numpy/pull/14086
We should basically be dropping Python 3.5 support for scikit-image 0.16

https://github.com/numpy/numpy/pull/14086/files#diff-b37c3c8057e08a90d877a2ba31d8a215R107

**Comment by JDWarner** [comment]
NumPy has thought this through pretty well, I am :+1: on sticking with their cadence here.  Especially as our next release is going to 3.x only, it will simplify future support burden.

**Comment by sciunto** [comment]
This opens the use of f-strings. :tada:

**Comment by jni** [comment]
Woohoo! I'm so happy. =)

**Comment by hmaarrfk** [comment]
Of course this is now more difficult than just removing entries in the build matrix. We should decide on how we want to address the rest of that NEP:

If we aim for a september release date, then we could follow their: "all minor versions of NumPy released in the prior 24 months". We can use this to suggest new minimum versions to set.

1. Numpy: 1.14 as recommended (Released Jan 2018)
2. Scipy: 1.0.0 release Sept 2017
3. Matplotlib: 2.1. 2.1.0 Released in Oct 2017
4. Networkx: 2.0. 2.0 Released in Oct 2017
5. Pillow: 4.3.0 Released in Oct 2017
6. imageio: 2.3. Released in Oct 2018, 2.2 releaesd in March 2017
7. PyWavelets: 1.0. Released in Oct 2018. 0.5 was releaesd in March 2017.

I think all of these should basically be bumped to help modernize contribution too :D.

**Comment by soupault** [comment]
:+1: to @hmaarrfk. I think those versions are fine.

**Comment by hmaarrfk** [comment]
I guess we should think of version bumbs as they are needed. But we should keep in mind that there is no reason to support increasingly aging versions.
