### ISSUE TITLE
Download page should mention Conda also for Linux/MacOS

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#4104]
See https://scikit-image.org/download.html . Currently it looks like it is specific to Windows.

**Comment by hmaarrfk** [comment]
Also the fact that we now provide binaries on pypi

**Comment by hmaarrfk** [comment]
I think the download page should be renamed "install" and point to 
https://scikit-image.org/docs/stable/

**Comment by soupault** [comment]
@hmaarrfk do you mean https://scikit-image.org/docs/stable/install.html?

**Comment by hmaarrfk** [comment]
yeah, thanks!
