### ISSUE TITLE
Histogram matching: test is missing for multichannel=False

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4106]
## Description

Xref: https://github.com/scikit-image/scikit-image/issues/3618#issuecomment-448892397

**Comment by iliailmer** [comment]
Is anybody assigned to this issue? I would like to help out with it.

**Comment by jni** [comment]
@iliailmer apologies for the delay in responding. If you are still happy to work on this you would be more than welcome to do so! As I understand it, we did move the function to `exposure` but did not add the test described in that comment.

**Comment by sciunto** [comment]
my apologies as well, I missed the notification.

**Comment by soupault** [comment]
@robroooh yes, feel free. Any open issue is still valid.
