### ISSUE TITLE
DOC: simple backquotes have no special rendering in the doc

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4117]
# Work plan

In skimage/

* [ ] draw/      
* [ ] external/  
* [x] filters/  #4127
* [ ] graph/       
* [ ] io/       
* [ ] metrics/     
* [ ] novice/       
* [ ] restoration/  
* [ ] segmentation/  
* [ ] _shared/    
* [ ] util/
* [ ] color/     
* [ ] data/       
* [ ] exposure/  
* [ ] feature/   
* [ ] future/   
* [ ] measure/  
* [ ] morphology/  
* [ ] transform/  
* [ ] viewer/

In doc

## Description

Example:

[Source code](https://github.com/scikit-image/scikit-image/blob/v0.15.0/skimage/color/colorconv.py#L70)
There is one word with simple backquotes and one with double.

Here is the rendering:

https://scikit-image.org/docs/stable/api/skimage.color.html#skimage.color.guess_spatial_dimensions

![Module color — skimage v0 15 0 docs](https://user-images.githubusercontent.com/335370/63651201-97d3da00-c752-11e9-812d-6853af6357c9.png)

The html code is

```
 
 <tr class="field-even field"><th class="field-name">Returns:</th><td class="field-body"><dl class="first docutils">
 <dt><strong>spatial_dims</strong> <span class="classifier-delimiter">:</span> <span class="classifier">int or None</span></dt>
 <dd><p class="first last">The number of spatial dimensions of <cite>image</cite>. If ambiguous, the value
 is <code class="docutils literal notranslate"><span class="pre">None</span></code>.</p>

```

Simple backquotes give `<cite>image</cite>`

**Comment by jni** [comment]
This is a sad but expected difference between restructured text and markdown. The correct formatting is with double backticks. Single backticks are for links. See http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#external-links

**Comment by sciunto** [comment]
Thanks for the pointer. This turns into an issue: fix all the single backticks (I know I used them in PRs...).

**Comment by lagru** [comment]
> This is a sad but expected difference between restructured text and markdown. The correct formatting is with double backticks. Single backticks are for links. See http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#external-links

@jni I'd argue that the link doesn't support your statement. There is even a [note](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html?highlight=default_role#roles) in sphinx's docs that suggests using the default role (!= link) for variable names. 

I'd slightly prefer to be follow the example of NumPy and SciPy on this (using single backticks for variable names). At least as long as we are recommending the [NumPy docstring standard](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) in our contribution guide we should allow that syntax. 

But I recognize that this discussion is similar to the `"` vs `'` debate which is largely a matter of personal taste.

Does #4188 render this issue void?

**Comment by jni** [comment]
@lagru I'm out of my depth here, so the wrong person to debate. =) You seem to have a reasonable grip on things so an alternative to #4188 would be welcome. I don't understand at all the differences between our config and SciPy's, so I wouldn't know where to start.
