### ISSUE TITLE
How to detect Polygon shapes from satellite images?

### ISSUE THREAD

**Issue by tugsjargal1** [scikit-image/scikit-image#4119]
Hey guys,

I am a newer one for Deep Learning and AI technologies. My mission is to find polygon shape (such as lake, bunker, hole ...etc) from the satellite image if center coordinates of polygon shape are giving.

I found an example from your Library: https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_rag_merge.html#sphx-glr-auto-examples-segmentation-plot-rag-merge-py

But this does work on Satellite image.

Error message throwing as below:

```
Traceback (most recent call last):
  File "./plot_rag_merge.py", line 65, in <module>
    g = graph.rag_mean_color(img, labels)
  File "/Users/user1/work/lib/python3.7/site-packages/skimage/future/graph/rag.py", line 366, in rag_mean_color
    graph.node[current]['total color'] += image[index]

```
Do you have any solution for my case ?

Thanks in advance.

**Comment by soupault** [comment]
Hello,

> to find polygon shape (such as ..., bunker, ...) from the satellite image.

First of all, I would like to express my *personal* disapproval of using scikit-image in any applications from the moral grey areas (including, but not limited to military). In my opinion, the person who develops technologies and/or implements them into the final applications is largely (sometimes, solely) responsible for any consequencies.

Secondly, our GitHub tracker is mostly used for the development of the library. As for application specific questions, I encourage you to ask them at https://stackoverflow.com (adding `scikit-image` label to your question, if needed) or https://forum.image.sc/ .

Finally, it is extremely challenging to understand your case without actually seeing the code and the data you are experiencing issue with. Image processing and computer vision are still rather experimental, not theoretical sciences, so we, as `scikit-image` cannot give any promises or guarantees without actually seeing the image domain and understanding the case.

I am closing this as not an issue. Please, feel free to cross-post your question at the aforementioned forums or continue the discussion here.

**Comment by tugsjargal1** [comment]
@soupault  

Thank you for your recommendation. 
By the way, I agree and follow terms of service (github and scikit-image) and other legal terms. There is no illegal issue or wrong operation anyway. 

My code is just changing img in plot_rag_merge.py file as below:

```
#img = data.coffee()
img = data.satellite_img()
```
Also I have created satellite_img image file as same size as coffee.png in skimage/data folder. And I defined satellite_img in skimage/data/__init__.py

**Comment by soupault** [comment]
If you are not allowed to share the image, I would advise to:
- Try to systematically debug the code line-by-line, i.e. visualize `labels`, `g`, etc. You should also check how those intermediate results look for `coffee` and what do they represent. It is probable that the parateter values in `slic`, etc have to be different for your data.
- Make sure your image is either grayscale or RGB. I know that satellite images often multi-spectral - most of the functions in our library do not support such kind of input. If you have multi-spectral data, you will need to convert your image to grayscale or RGB explicitly.

**Comment by tugsjargal1** [comment]
@soupault 

Thank you for your immediate response. 🙏🏻
Here is my example image:

[https://aws1.discourse-cdn.com/business4/uploads/imagej/original/3X/f/9/f913f8417b03fc499db509ccad7e0ea0ec3380bf.jpeg](url)

Center coordinate is giving. Only to find edge coordinates of lake which is placed in the center of the image.

If I fill or draw polygon shape on the image, I can get coordinates.

**Comment by tugsjargal1** [comment]
Hi @soupault 

Awesome! It is working after I converted image to grayscale format. 
Wow, woow... 

Thank you very much. Unbelievable!

**Comment by soupault** [comment]
Good that it helped!
