### ISSUE TITLE
Confusing coordinate system

### ISSUE THREAD

**Issue by piotr-rarus** [scikit-image/scikit-image#4122]
Scikit-Image, opposing to OpenCV uses more human-friendly coordinate system.
First X coordinate, second Y coordinate.

Interface of methods in `draw` module is confisuing.

`skimage.draw.circle(r, c, radius, shape=None)`

This is documentation of `r` and `c` parameters:
- r, c: double

Centre coordinate of circle.

First of all, docs explain little of what these parameters do. 

Intuitive approach would be: it uses same dimension ordering.
It took me few hours, few bugs and searching through docs to find out that `r` - row, `c` - column. So dimension order is different. For me it should be plain `x` and `y` or `xc`, `yc`.

As changing interface will break a lot of existing projects, could we please at least consider making docs redundant but less guess work.

**Comment by soupault** [comment]
Hi,

Thank you for your interest.

>First of all, docs explain little of what these parameters do.

I believe they do explain it quite well. Have you seen this page - https://scikit-image.org/docs/stable/user_guide/numpy_images.html, particularly, https://scikit-image.org/docs/stable/user_guide/numpy_images.html#coordinate-conventions ?

>For me it should be plain x and y or xc, yc.

We are actually going into the opposite direction, `.draw` and `.transform` are the only remaining packages that still somewhat use `x, y` notation. However, that is planned to be changed in the future. Other functions use either `r, c, p[lane]` or direction-agnostic `d[imension]0, d[imension]1, ..., c[hannel]`.

Having said the above, there might be still some confusion or even bugs introduced by switching from `x, y` to `r, c` in `.draw`. We would appreciate if you could reiterate with those docstrings after reading the user guide and suggest the specific improvements (preferably, in the form of Pull Request).

I am going to close this issue, but feel free to continue the discussion.

P.S. You might be interested to contribute to the discussion in https://github.com/scikit-image/scikit-image/pull/3031 and https://github.com/scikit-image/scikit-image/pull/2278.

**Comment by jni** [comment]
@piotr-rarus would you mind explaining what a "human friendly" coordinate system means to you? In scikit-image, a top priority is compatibility with NumPy arrays, which we tend to think of as row/column based on how they are displayed. [This comment](https://github.com/scikit-image/scikit-image/pull/3031#issuecomment-390941115) emphasises that this is a display convention and calling these axes x/y makes no difference. The main thing that we are moving towards in scikit-image is to have the coordinate axes correspond exactly to the array axes, but we are not there yet *everywhere* in the library.

We'd love to improve the docs based on your expectations of the coordinates, so please let us know if you find anything confusing.
