### ISSUE TITLE
(with setup.py) Installing Error: Could not find a version that satisfies the requirement scikit-image

### ISSUE THREAD

**Issue by Hatchin** [scikit-image/scikit-image#4123]
## Description
I am trying to build a package which needs scikit-image. Every time I try to install the requires with setup.py, I am getting this error:

ERROR: Could not find a version that satisfies the requirement scikit-image (from ntd-hatchin-7) (from versions: none)
ERROR: No matching distribution found for scikit-image (from ntd-hatchin-7)

However, if I simply entered `pip install scikit-image`, then it worked fine.

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```
My setup.py was like:

install_requires=[ 'scipy','pillow','networkx','PyWavelets','imageio', 'matplotlib','SimpleITK', 'pydicom','scikit-learn','scikit-image']

**Comment by sciunto** [comment]
It is not easy to help without the full code to reproduce. Also, I'm not sure whether it is a bug with scikit-image or not.

**Comment by Hatchin** [comment]
Thanks @sciunto! 

I am trying to install a module by setup.py. 

It was like:


```
from setuptools import setup, find_packages
setup(
    name = "ntd",
    version = "0.0.1",
    description = "",
    long_description = "",
    url = "",
    packages = find_packages(),
    include_package_data = True,
    install_requires=['SimpleITK', 'pydicom', 'numpy>=1.13.3','scipy>=0.19.0','matplotlib>=2.0.0,!=3.0.0','networkx>=2.0','pillow>=4.3.0','imageio>=2.3.0','PyWavelets>=0.4.0','scikit-image'], 
)

```

Thank you!

**Comment by jni** [comment]
@Hatchin we need *all* the information from you, including what OS you're using, what command you're running, etc. I just tried this from scratch and it works:

- create a new environment with `conda create -n skimage-dep python=3.7`
- activate the environment: `conda activate skimage-dep`
- create a `setup.py` file exactly like the one above
- create a folder `ntd/` and a file `__init__.py` in that folder that contains only `def hello(): print('hello')`
- run `python setup.py install` or `pip install .`; either works.

**Comment by jni** [comment]
(I am using Ubuntu Linux and pip 19.2.2.)

**Comment by Hatchin** [comment]
Thank you! Sorry that I didn't describe it very well

My OS is Linux 4.4.0-17763-Microsoft, 64-bit. 

`pip install scikit-image` and `python setup.py install` worked for me as well. My problem happened when I uploaded it to pypitest and installed it. Its url is https://test.pypi.org/project/ntd/.
It could be downloaded via `pip install -i https://test.pypi.org/simple/ ntd`.

The structure of the folder was simply like:
```
.
├── README.md
├── requirements.txt
├── scr
│   └── __init__.py
└── setup.py
```

and the setup.py was like:

```
from setuptools import setup, find_packages
setup(
    name = "ntd-Hatchin-9",
    version = "0.0.1",
    description = "",
    long_description = "",
    url = "",
    packages = find_packages(),
    include_package_data = True,
    install_requires=['SimpleITK', 'pydicom', 'numpy>=1.13.3','scipy>=0.19.0','matplotlib>=2.0.0,!=3.0.0','networkx>=2.0','pillow>=4.3.0','imageio>=2.3.0','PyWavelets>=0.4.0','scikit-image'], 
)
```

I firstly ran:
```
python setup.py sdist bdist_wheel
```

and then I ran:
```
python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```
which was going to upload the package under my account. 

After that I copied the url in pypi test and tried to installed it in my local machine:
```
pip install -i https://test.pypi.org/simple/ ntd
```

And then I got the error message:

```
Looking in indexes: https://test.pypi.org/simple/
Collecting ntd
  Downloading https://test-files.pythonhosted.org/packages/ce/cf/1a72f11072b8798876b0920de2bec0bdcd0131115a69718dd924c388bcff/ntd-0.0.1-py3-none-any.whl
Requirement already satisfied: pydicom in /home/hatchin/anaconda3/envs/testing0/lib/python3.5/site-packages (from ntd) (1.3.0)
Requirement already satisfied: numpy>=1.13.3 in /home/hatchin/anaconda3/envs/testing0/lib/python3.5/site-packages (from ntd) (1.17.1)
Requirement already satisfied: scipy>=0.19.0 in /home/hatchin/anaconda3/envs/testing0/lib/python3.5/site-packages (from ntd) (1.3.1)
Requirement already satisfied: imageio>=2.3.0 in /home/hatchin/anaconda3/envs/testing0/lib/python3.5/site-packages (from ntd) (2.5.0)
Requirement already satisfied: pillow>=4.3.0 in /home/hatchin/anaconda3/envs/testing0/lib/python3.5/site-packages (from ntd) (6.1.0)
Requirement already satisfied: SimpleITK in /home/hatchin/anaconda3/envs/testing0/lib/python3.5/site-packages (from ntd) (1.2.2)
Requirement already satisfied: networkx>=2.0 in /home/hatchin/anaconda3/envs/testing0/lib/python3.5/site-packages (from ntd) (2.3)
Requirement already satisfied: PyWavelets>=0.4.0 in /home/hatchin/anaconda3/envs/testing0/lib/python3.5/site-packages (from ntd) (1.0.3)
Collecting scikit-image (from ntd)
  ERROR: Could not find a version that satisfies the requirement scikit-image (from ntd) (from versions: none)
ERROR: No matching distribution found for scikit-image (from ntd)
```

Thank you!

**Comment by hmaarrfk** [comment]
Why are you uploading all these packages to your own channel? Is there something specific you are trying to achieve?

**Comment by hmaarrfk** [comment]
It seems you are locking your install to your own channel,and you haven't actually uploaded scikit image there.

**Comment by hmaarrfk** [comment]
One more thing, we don't have anything uploaded to test.pypi.org

https://test.pypi.org/search/?q=scikit-image

**Comment by Hatchin** [comment]
Ok I got it. Thank you for reply!

**Comment by hmaarrfk** [comment]
Glad things are working out for you
