### ISSUE TITLE
BUG: morphology.rectangle() dimensions swapped

### ISSUE THREAD

**Issue by LiuSeeker** [scikit-image/scikit-image#4125]
## Description
The function `rectangle(width, height, dtype=np.uint8)`, from morphology, generates a rectangle structing element with these dimensions swapped. 

## Way to reproduce
```python
skimage.morphology.rectangle(3,1)
```

## Expected output:
```python
[[1 1 1]]
```

## Actual output:
```python
[[1]
 [1]
 [1]]
```

## Version information
```python
# your output here
3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.15.0
numpy version: 1.16.2
```

**Comment by aleblucher** [comment]
I'm on it.

**Comment by aleblucher** [comment]
https://github.com/scikit-image/scikit-image/pull/4126

This should fix it.
