### ISSUE TITLE
How to view the total image after warping

### ISSUE THREAD

**Issue by xactbupt** [scikit-image/scikit-image#4132]
## Description
In general, after warping image will have different size, while warp function outputs image with the same size as input by default, and this results in only parts of image can be viewed. I have tried to set the output_shape parameter manually, but it doesn't work.
Here is my code

## Way to reproduce
```
from skimage import io, data, color, transform
import matplotlib.pylab as plt
import numpy as np
#inline matplotlib

img = data.camera()

tform = transform.SimilarityTransform(scale=2, rotation=np.pi / 4,
                               translation=(10, -10))

img_forward  = transform.warp(img, tform.inverse)
img_backward = transform.warp(img_forward, tform)

fig, (ax1, ax2, ax3) = plt.subplots(ncols=3, figsize=(8, 3))

ax1.imshow(img)
ax1.set_title('Original')
ax1.axis('off')
ax2.imshow(img_forward)
ax2.set_title('Similarity')
ax2.axis('off')
ax3.imshow(img_backward)
ax3.set_title('Inverse')
ax3.axis('off')

**Comment by xactbupt** [comment]
<img width="705" alt="屏幕快照 2019-08-31 下午5 07 09" src="https://user-images.githubusercontent.com/54738223/64061811-111b7300-cc12-11e9-8b76-5318870af3bc.png">

**Comment by hmaarrfk** [comment]
I guess the warping transform will only plot on positive row (y) and column (x) coordinaes.

![image](https://user-images.githubusercontent.com/90008/64063812-6bdbad00-cbc7-11e9-963a-bedaadeaba80.png)

```python
img_forward  = transform.warp(img, tform.inverse, output_shape=(2048, 1024))
img_backward = transform.warp(img_forward, tform, output_shape=img.shape)
```

Add a translation so that your warped image is fully in the positive coordinates for x

**Comment by hmaarrfk** [comment]
please feel free to open if yo think the issue is sill not addressed.
