### ISSUE TITLE
ASV import time suite not showing correct results online

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#4133]
## Description
https://pandas.pydata.org/speed/scikit-image/#benchmark_import_time.ImportSuite.time_import

Seems to be erroring. I used to get 1 ms when python would error or the shell would simply exist.

Is the benchmark computer running windows?

**Comment by sciunto** [comment]
Cc @TomAugspurger

**Comment by jni** [comment]
We should probably start managing our own benchmark machine... =\

**Comment by TomAugspurger** [comment]
Sorry for the delay. It's a linux machine.

**Comment by grlee77** [comment]
I am going to close this as outdated (It doesn't look like we have been running benchmarks in this way since 0.18.0rc0). Please reopen if I am mistaken
