### ISSUE TITLE
Functions are not sorted in API guide

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#4135]
See, e.g., https://scikit-image.org/docs/dev/api/skimage.color.html

**Comment by hmaarrfk** [comment]
how should they be sorted? by themes or alphabetical?

**Comment by stefanv** [comment]
Alphabetical, I think.

**Comment by soupault** [comment]
I have not thotoughly checked, but it might be that the order in Sphinx follows precisely the one in `__init__.py` - https://github.com/scikit-image/scikit-image/blob/master/skimage/color/__init__.py#L1-L67.

**Comment by stefanv** [comment]
Yes, that's likely the case.

**Comment by dhirensr** [comment]
should i send a PR for sorting the functions alphabetically?

**Comment by soupault** [comment]
@dhirensr sure, go ahead!

**Comment by dhirensr** [comment]
@soupault : should i modify the all variable in __init__.py - https://github.com/scikit-image/scikit-image/blob/master/skimage/color/__init__.py#L1-L67 or the import order?
also how do i test locally before sending PR?

**Comment by jni** [comment]
@dhirensr you could try `_all_exported = [ ... ]  # the current list` and then `__all__ = sorted(_all_exported)`

To test locally, you should `cd doc`, then `make html`. You can then open the resulting page in `doc/build/html/index.html`. You will need to install everything in `requirements/docs.txt`, and possibly also pandoc and latex.

**Comment by dhirensr** [comment]
@jni : I am not sure if it picks up from modules __init__.py because I removed an element from __all__ and it did not remove it from docs.
also I did make clean and make html then also It did not remove the doc.
I am also checking where does it generate from! do you have any idea? @jni @soupault

**Comment by jni** [comment]
@dhirensr Hmm. I'm not actually sure. @stefanv?

**Comment by dhirensr** [comment]
@jni : sorry my bad! it works fine with __init__ file
have made a PR https://github.com/scikit-image/scikit-image/pull/4208 for review
also do we change all other modules where the functions are not sorted?

**Comment by mkcor** [comment]
Closing this, since functions / classes / submodules are now sorted ~alphabetically~ lexicographically.

Ultimately, the API reference should boast a new look (maybe using NumPy's or SciPy's theme?). But this would happen after 1.0 anyway.
