### ISSUE TITLE
reading array of shape (512, 512, 30) with a pathlib path returns array of shape (512, 30)

### ISSUE THREAD

**Issue by rbavery** [scikit-image/scikit-image#4138]
## Description
I'm reading a tif with a pathlib path. When I convert the pathlib path to a string with the `as_posix()` method, the array is correctly read in with shape (512, 512, 30)

## Way to reproduce
```python
import skimage.io as skio
import numpy as np
from pathlib import Path
arr = np.ones((512, 512, 30))

skio.imsave("test.tif", arr)

skio.imread(Path("test.tif")).shape
```
The shape is wrong, the first dim is dropped.

And if you try this with an array that has a third axis of size 3 it actually works for some reason.
```python
import skimage.io as skio
import numpy as np
from pathlib import Path
arr = np.ones((512, 512, 30))

skio.imsave("test.tif", arr)

skio.imread(Path("test.tif")).shape
```

## Version information
```python

3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
Linux-4.15.0-1056-azure-x86_64-with-debian-stretch-sid
scikit-image version: 0.15.0
numpy version: 1.17.1

```

**Comment by hmaarrfk** [comment]
please try to use tifffile directly. we have an old version.... on 0.15, we still use our versioned tiffile directly.

https://github.com/scikit-image/scikit-image/blob/v0.15.x/skimage/io/_plugins/tifffile_plugin.py#L1

@jni, should we add a warning to users asking them to install upstream tifffile?

**Comment by rbavery** [comment]
It looks like tifffile can't handle pathlib Paths

```python
import skimage.io as skio
import numpy as np
from pathlib import Path
arr = np.ones((512, 512, 30))

skio.imsave("test.tif", arr)

skio.imread(Path("test.tif"), plugin="tifffile").shape
```

results in this error

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-51d088a45905> in <module>
      6 skio.imsave("test.tif", arr)
      7 
----> 8 skio.imread(Path("test.tif"), plugin="tifffile").shape

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/io/_io.py in imread(fname, as_gray, plugin, flatten, **plugin_args)
     59 
     60     with file_or_url_context(fname) as fname:
---> 61         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     62 
     63     if not hasattr(img, 'ndim'):

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    208                                (plugin, kind))
    209 
--> 210     return func(*args, **kwargs)
    211 
    212 

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/io/_plugins/tifffile_plugin.py in imread(fname, dtype, **kwargs)
     35 
     36     # read and return tiff as numpy array
---> 37     with TiffFile(fname, **kwargs_tiff) as tif:
     38         return tif.asarray(**kwargs)

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py in __init__(self, arg, name, offset, size, multifile, multifile_close, pages, fastij, is_ome)
   1326 
   1327         self._fh = FileHandle(arg, mode='rb',
-> 1328                               name=name, offset=offset, size=size)
   1329         self.offset_size = None
   1330         self.pages = []

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py in __init__(self, file, mode, name, offset, size)
   3515         self._close = True
   3516         self.is_file = False
-> 3517         self.open()
   3518 
   3519     def open(self):

/data/anaconda/envs/cropmask/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py in open(self)
   3567                 pass
   3568         else:
-> 3569             raise ValueError("The first parameter must be a file name, "
   3570                              "seekable binary stream, or FileHandle")
   3571 

ValueError: The first parameter must be a file name, seekable binary stream, or FileHandle
```

**Comment by rbavery** [comment]
I think the easiest solution that doesn't require installing tifffile directly is to call the `as_posix()` method on the pathlib Path that is being read, so maybe that should be the warning?

**Comment by soupault** [comment]
I would say that it is clearly specified that neither `skimage.io.imread` nor `tifffile` support Path-type as an input.

`skimage` - https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_io.py#L19

`tifffile`:
```
def imread(files, **kwargs):
    """...

    Parameters
    ----------
    files : str, binary stream, or sequence
        File name, seekable binary stream, glob pattern, or sequence of
        file names.
```

**Comment by hmaarrfk** [comment]
If it is a pathlib issue, maybe report it upstream. I'm inclined not to fix pathlib in scikit image.

**Comment by soupault** [comment]
I agree with Mark. Although, it seems that patlib is getting some momentum lately and the module has become quite mature.

**Comment by jni** [comment]
The first error (dropped dimension) suggests some multichannel magic going on, which we should track down.

With regards to fully supporting pathlib, I don't have a strong inclination to do so... As @soupault mentioned, it's getting some traction, but it's still massively undersupported and easily fixed by the user by passing in `str(path_obj)`. (Does `as_posix()` work on Windows?) At any rate, long term, I think we should defer as much as possible to imageio, so that might be the place to fix this.

Finally, I think I would rather continually update vendored tifffile, or even adding tifffile as a dependency at this point, rather than warn people to install tifffile.

**Comment by hmaarrfk** [comment]
The only challenge with depending on tifffile is that ti has historically been a C dependency, so testing the installation process on a computer without a compiler, is not something the core dev team can vet.... you know because our computers are likely setup to do the compiling itself.

**Comment by jni** [comment]
@hmaarrfk isn't someone (@blink1073? @cgohlke?) putting up tifffile wheels on PyPI these days?

**Comment by hmaarrfk** [comment]
key word there was historically.

I would love to depend on tifffile, but all my windows machines have compilers installed on them. How would I check that I can install tiffile without a compiler? I'm worried about tifffile's dependencies.

**Comment by cgohlke** [comment]
> isn't someone putting up tifffile wheels on PyPI these days?

I am.

> I'm worried about tifffile's dependencies.

Since version 2018.10.18 tifffile is distributed as an universal wheel. The current requirements for installing the wheel are:
```
Requires-Python: >=2.7
Requires-Dist: numpy (>=1.11.3)
Requires-Dist: imagecodecs (>=2019.5.22) ; platform_system == "Windows"
Requires-Dist: pathlib ; python_version == "2.7"
Requires-Dist: enum34 ; python_version == "2.7"
Requires-Dist: futures ; python_version == "2.7"
Provides-Extra: all
Requires-Dist: matplotlib (>=2.2) ; extra == 'all'
Requires-Dist: imagecodecs (>=2019.5.22) ; extra == 'all'
```

The universal wheel no longer contains any C extensions. Those have been moved into the [`imagecodecs`](https://pypi.org/project/imagecodecs/) package, which is an optional dependency except on Windows, for which wheels are provided on PyPI.

Imagecodecs is hard to build for its many third-party library build dependencies. Alternatively, the [`imagecodecs-lite`](https://pypi.org/project/imagecodecs-lite/) package can be used to decode for example LZW and PackBits. This package does not depend on third-party C libraries.

**Comment by jni** [comment]
@cgohlke thank you very much for your response. My take on this is that we can depend on tifffile and imagecodecs-lite and things will be fine for the most part? I've seen many warnings with the LZW compression but nothing else, so I presume the rest of the stuff is more esoteric? And, if I understand correctly, only affects performance, not functionality?

**Comment by cgohlke** [comment]
> My take on this is that we can depend on tifffile and imagecodecs-lite and things will be fine for the most part? 

I think so. Although JPEG compression in tiled TIFF is not that uncommon (but messy).

I've seen many warnings with the LZW compression but nothing else, so I presume the rest of the stuff is more esoteric?

Yes. 8 and 12-bit JPEG are found in GeoTIFF. Whole-slide image formats use all kind of JPEG, JPEG2000, JXR, or PNG. ZSTD and WebP were recently added to libtiff. None of the FAX or Log codecs found in some TIFF files are supported by imagecodecs.

> And, if I understand correctly, only affects performance, not functionality?

Tifffile will simply fail to decode certain packed/predicted/compressed images if the imagecodecs package is not installed. Without imagecodecs, tifffile only supports delta predictors, deflate compression, and packed 1-bit integers, which are easy to implement using the Python stdlib and numpy. The Python LZW decoder has been removed from tifffile since it is practically too slow.

**Comment by jni** [comment]
Ooooooh. @rbavery thank you for the update, I missed it the first time around. So it's our dispatch that's broken. Looks like a fix would be:

```python
if plugin is None:
    if isinstance(fname, str) or isinstance(fname, pathlib.Path):
        if str(fname).lower().endswith(('.tiff', '.tif')):
            plugin = 'tifffile'
```

Would you mind submitting a PR for this?

**Comment by hmaarrfk** [comment]
Pathoib has a function that returns the suffix as a string. You can then call lower on that

**Comment by jni** [comment]
@hmaarrfk sure, but then we have the same check twice, once for the pathlib extension and once for a string.

I guess we could go all-in in the other direction: if we get a string, convert to a Pathlib object, then work with that?!

**Comment by rbavery** [comment]
@jni yep I'll do a PR, I think I'll just go with converting to a string like you suggested, since it's probably more likely folks will be more familiar with checks on strings than checks on Pathlib objects.

**Comment by VolkerH** [comment]
I have a similar issue that might likely be solved by the dispatch code snippet that @jni posted above. It is a 4-channel tiff file and I guess a plugin other than tifffile may be called. I get a different dimension ordering:

Sorry, this is not a stand-alone bit of code, but I'm sure you get it:
```
    def load_files_from_row(self, rownr):
        row: pd.Series = self.df.iloc[rownr]
        print(f"reading image {row['raw']}")
        comparison =  skimage.io.imread(str(row["raw"]))
        print(comparison.shape)
        self.raw = tifffile.imread(str(row["raw"]))
        print(self.raw.shape)
```

Output:
```
(1024, 1024, 4)
(4, 1024, 1024)
```

```
>>> tifffile.__version__
'2019.2.22'
>>> skimage.__version__
'0.16.2'
```

I haven't looked into the source code, but I assume that a backend such as PIL might have been dispatched that assumes this is an image of type RGBA.

**Comment by emmanuelle** [comment]
@rbavery did you have any chance to work on the PR :-) ?

**Comment by cgohlke** [comment]
> I get a different dimension orderings depending on whether I use tifffile directly or skimage

That is expected. Skimage promises to return an array where the samples (color bands/channels) are in the last dimension, while tifffile keeps the dimension order as described in the TIFF tags (except for some files using JPEG compression):

https://github.com/scikit-image/scikit-image/blob/d212cb5100abbb0c5c50cc340b766cae8e368d55/skimage/io/_io.py#L35-L40

The implementation is not foolproof as grayscale z or t series with 3 or 4 frames are also returned as MxNx3 or MxNx4:

https://github.com/scikit-image/scikit-image/blob/d212cb5100abbb0c5c50cc340b766cae8e368d55/skimage/io/_io.py#L53-L56

**Comment by VolkerH** [comment]
Thanks for the deep dive into the code @cgohlke. That clears things up for me. 
So the reshuffling behaviour is intentional in `skimage` it will be independent of the import plugin that's used. 
As I almost always want the other behaviour (i.e. `[c,y,x]` order) I will stick with `tifffile` exclusively in the future.

**Comment by jni** [comment]
@VolkerH note that the reshaping might be made obsolete by #4294, which is a great side effect of that proposal! =)

**Comment by VolkerH** [comment]
Ok, that solves my issues. However, I assume the original issue of despatching the correct import plugin still needs addressing.

**Comment by rbavery** [comment]
@emmanuelle sorry, forgot about this. I won't have time anytime soon to dive back into this, I'm focusing on contributing to some other open source projects that dovetail into my own work.

**Comment by rfezzani** [comment]
Is this issue still relevant since `tifffile` is no more vendored?

**Comment by hmaarrfk** [comment]
```python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.


In [1]: import skimage                                                                                                                                                                                             

In [2]: skimage.__version__                                                                                                                                                                                        
Out[2]: '0.17.dev0'

In [3]: import skimage.io as skio 
   ...: import numpy as np 
   ...: from pathlib import Path 
   ...: arr = np.ones((512, 512, 30)) 
   ...:  
   ...: skio.imsave("test.tif", arr) 
   ...:  
   ...: skio.imread(Path("test.tif")).shape                                                                                                                                                                        
/home/mark/miniconda3/envs/mcam_dev/bin/ipython:6: UserWarning: test.tif is a low contrast image
  
Out[3]: (512, 30)

In [4]: import tifffile                                                                                                                                                                                            

In [5]: tifffile.__version__                                                                                                                                                                                       
Out[5]: '2020.2.16'

In [6]: import imagecodecs_lite                                                                                                                                                                                    

In [7]: imagecodecs_lite.__version__                                                                                                                                                                               
Out[7]: '2019.12.3'

```

I'm still hitting it. Might be because i'm missing `imagecodecs` full.

This test is easy to add to our test suite if somebody wants to `close` this issue correctly. @rbavery gave a nice minimal example.

**Comment by grlee77** [comment]
> Isn't #5546 fixing this issue?

Yes, I think so. I will close, but please reopen if the issue persists
