### ISSUE TITLE
threshold_li fails on array with 2 values in it

### ISSUE THREAD

**Issue by bethac07** [scikit-image/scikit-image#4140]
## Description
For an array with only 2 values in it, threshold_li fails; this worked in 0.14.2, but fails in 0.14.3 and 0.14.4 .  This was causing 3 tests in CellProfiler to fail; I've bypassed it for two tests that were not in fact supposed to use threshold_li (which was our bad), but the third is still failing.  It's unlikely such images would exist directly off a microscope, but if someone fed in a binary mask (ala example "a" below), it would fail, which is definitely an issue.

## Way to reproduce
```python
a = numpy.array([0, 0, 1, 0, 0, 1, 0, 1])
b = numpy.array([0, 0, 0.1, 0, 0, 0.1, 0, 0.1])
c = numpy.array([0, 0, 0.1, 0, 0, 0.1, 0.01, 0.1])
d = numpy.array([0, 0, 1, 0, 0, 1, 0.5, 1])
e = numpy.array([1,1])
f = numpy.array([1,2])
skimage.filters.threshold_li(a)
skimage.filters.threshold_li(b)
skimage.filters.threshold_li(c)
skimage.filters.threshold_li(d)
skimage.filters.threshold_li(e)
skimage.filters.threshold_li(f)
```
This comes out this way in 0.14.2:

```
>>> skimage.filters.threshold_li(a)
/Users/bcimini/.virtualenvs/skimageli/lib/python2.7/site-packages/skimage/filters/thresholding.py:601: RuntimeWarning: divide by zero encountered in log
  (np.log(mean_back) - np.log(mean_fore)))
0.0
>>> skimage.filters.threshold_li(b)
0.0
>>> skimage.filters.threshold_li(c)
0.02505097742626249
>>> skimage.filters.threshold_li(d)
0.0
>>> skimage.filters.threshold_li(e)
1
>>> skimage.filters.threshold_li(f)
1.0
```

But this way in 0.14.3/4:

```
>>> skimage.filters.threshold_li(a)
/Users/bcimini/.virtualenvs/skimageli/lib/python2.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/bcimini/.virtualenvs/skimageli/lib/python2.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
nan
>>> skimage.filters.threshold_li(b)
nan
>>> skimage.filters.threshold_li(c)
0.02505097742626249
>>> skimage.filters.threshold_li(d)
/Users/bcimini/.virtualenvs/skimageli/lib/python2.7/site-packages/skimage/filters/thresholding.py:596: RuntimeWarning: divide by zero encountered in log
  (np.log(mean_back) - np.log(mean_fore)))
0.0
>>> skimage.filters.threshold_li(e)
1
>>> skimage.filters.threshold_li(f)
nan
```

## Version information
```python
2.7.12 (default, Aug 27 2019, 14:36:02) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)]
Darwin-18.7.0-x86_64-i386-64bit
scikit-image version: 0.14.4
numpy version: 1.16.5
```

**Comment by jni** [comment]
Ok, that's it, I'm calling it: we are removing `threshold_li` altogether! :joy:

*sigh* sorry about this, will investigate! :man_facepalming:

**Comment by jni** [comment]
Ok, this doesn't seem *too* bad: when the background is all zeros, `np.log(mean_back)` is nan. The fix is to subtract not `image_min` but rather `image_min - np.eps`, so that all values are *slightly* positive. What's pathological is not that it's few values but that the background is all zeros. Working on this! It's kinda weird that we haven't caught this already, but we will in the future thanks to your tests! =)

**Comment by jni** [comment]
amazing. `np.log(mean_back)` is actually `-inf`, which works fine, at least for recent versions of Python/NumPy. The outputs I get for your five arrays with skimage master are:

[0.0, 0.0, 0.025050977426262489, 0.0, 1, 1.0]

which is the same as 0.14.2... I'll check the 0.14.x branch next.

**Comment by bethac07** [comment]
It's all good dude :)

**Comment by jni** [comment]
Ok, got it: this is what I get for lazily not backporting #3966. In that PR, I ensured that `t_next`, which is used as the initial estimate, was within the data range.

I've added tests to master and will fix 0.14.

**Comment by jni** [comment]
@bethac07 any chance you guys want to wait for 0.14.5? =)

**Comment by bethac07** [comment]
The release needs to go out by middle of next week at the VERY latest, so if there's a new tag by then sure! Otherwise, CP4 (shipping skimage 0.15 at least) will be coming out in the next 4 months, so please don't feel compelled on our account to do a ton of extra work for what for us is mostly a patch CP release.

**Comment by jni** [comment]
@bethac07 0.14.5 is tagged and building [here](https://ci.appveyor.com/project/scikit-image/scikit-image-wheels/builds/27296752) and [here](https://travis-ci.org/scikit-image/scikit-image-wheels/builds/582950721). :crossed_fingers:

**Comment by jni** [comment]
@bethac07 0.14.5 is now available from PyPI!

**Comment by bethac07** [comment]
I juuuust finished our last builds last night, sorry :(

**Comment by bethac07** [comment]
I SUPER appreciate you fixing this though!  We're still checking the builds, if for whatever reason we run across any issues and need to rebuild we will definitely do it with 0.14.5!
