### ISSUE TITLE
Remove the numpy wrapper skimage.util.pad

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4147]
## Description

Decide whether the function wrapping np.pad is still needed:

ref https://github.com/scikit-image/scikit-image/pull/4142#discussion_r3219644300

https://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.pad

**Comment by alexdesiqueira** [comment]
@sciunto do we have a good reason to not have the function around? I think it's very useful to create pipelines.
What would be the alternatives? Not having a `pad` version at all, or maintain the wrapper?

**Comment by sciunto** [comment]
I thought not having a wrapper and teach how to use numpy :) If there is no added value, I do not see the point to have the burden to maintain a function.

**Comment by alexdesiqueira** [comment]
Geez... I whined a while ago we won't have any basic functions in a few... the time is coming! :sweat_smile:
