### ISSUE TITLE
Why exposure.equalize_hist return different pixel value for the same pixel value?

### ISSUE THREAD

**Issue by 12ycli** [scikit-image/scikit-image#4149]
As far as I know, histgram equalization calculate a mapping for one pixel value to map to another pixel value. The same pixel value should also be the same after histgram equalization. However, While I used exposure.equalize_hist I got different pixel value(though very close) for pixels have the same pixel value from the input. Why?

**Comment by sciunto** [comment]
This sounds like a rounding issue. Please, could you share a minimal code that reproduces the behavior?

**Comment by 12ycli** [comment]
Sorry! I checked that again and found they are the same. It is OK!
