### ISSUE TITLE
equalize_adapthist produces image with artifact

### ISSUE THREAD

**Issue by VasylVaskivskyi** [scikit-image/scikit-image#4160]
## Description

equalize_adapthist produces images that look like they aren't fully processed

Input
https://drive.google.com/file/d/1EWWAEzM_bXzm6_CwmG17BPnGYJUcjFBX/view
Output
https://drive.google.com/file/d/1Qr8BJl2OYgjCcMZw6a3tNbJ_rpB2JBhc/view

I cannot upload tifs on the github so, I put them on the my Gdrive.

## Way to reproduce

import tifffile as tif
import skimage.exposure as ex

input_img = 'path_to_img'
out_img = 'path_to_img'

img = tif.imread(input_img)
corrected = ex.equalize_adapthist(img, 11, 0.3, 256)
eq = skimage.img_as_ubyte(corrected)
tif.imwrite(out_img, eq)

## Version information

3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Windows-10-10.0.17134-SP0
scikit-image version: 0.15.0
numpy version: 1.16.4

**Comment by sciunto** [comment]
Thanks for reporting! I confirm the issue. The effect depends on the kernel size.

**Comment by rfezzani** [comment]
The artifacts comes from round-off errors in `map_array` shape computation in `_clahe` function ([here](https://github.com/scikit-image/scikit-image/blob/master/skimage/exposure/_adapthist.py#L119)).
It is fixed in #4349.
