### ISSUE TITLE
Reference document link for pyramid_reduce function is not working

### ISSUE THREAD

**Issue by durveshps** [scikit-image/scikit-image#4185]
For the function pyramid_reduce in skimage/transform/pyramids.py the hyperlink for reference pdf document does not direct to the required pdf.

Here is the link
    References
    ----------
    .. [1] http://web.mit.edu/persci/people/adelson/pub_pdfs/pyramid83.pdf

Does anybody know the new link or direct me some literature for theoretical background of implementation?

**Comment by soupault** [comment]
@durveshps Thanks for reporting! I think this is the new location - http://persci.mit.edu/pub_pdfs/pyramid83.pdf . Would you be interested in submitting a Pull Request?

**Comment by durveshps** [comment]
@soupault thanks for the link. I will submit a Pull request on coming weekend.

**Comment by durveshps** [comment]
@soupault  I tried pushing my branch to remote repository. But it doesn't seem to work. I am working on it.

**Comment by durveshps** [comment]
The change in doc-string is already been done by someone else.
