### ISSUE TITLE
skimage.util.convert not converting to 'float32' with numpy v1.13.3

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#4189]
## Description

During my explorations for PR #4161 CI failure, I found that `skimage.util.convert` doesn't convert double precision images to single precision with `numpy v1.13.3` when called with `dtype='float32'`. Even more strange, it works when `dtype=np.float32`

## Way to reproduce

```python
>>> import numpy as np
>>> from skimage.util.dtype import convert
>>> a = np.random.rand(5, 5)
>>> convert(a, 'float32').dtype
dtype('float64')
>>> convert(a, np.float32).dtype
dtype('float32')
>>> np.__version__
'1.13.3'
```

This doesn't happen with more recent numpy version:

```python
>>> a = np.random.rand(5, 5)
>>> convert(a, 'float32').dtype
dtype('float32')
>>> convert(a, np.float32).dtype
dtype('float32')
>>> np.__version__
'1.16.4'
```

## Version information

```python
3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0]
Linux-4.15.0-64-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.16.dev0
numpy version: 1.13.3

```

**Comment by jni** [comment]
@rfezzani Crazy outcome of your investigation! Can this issue be fixed by internally changing any `'float32'`s to `np.float32`?

**Comment by jni** [comment]
"internally" meaning inside the "convert" function

**Comment by rfezzani** [comment]
I am checking this ;)

**Comment by rfezzani** [comment]
OK, the bug comes from `np.issubdtype` that was fixed in `numpy v1.14`:

Using `numpy v1.13`, I obtain:
```python
>>> a = np.random.rand(5)
>>> a.dtype
dtype('float64')
>>> np.issubdtype(a.dtype, 'float32')
True
>>> np.issubdtype(a.dtype, np.dtype('float32'))
True
>>> np.issubdtype(a.dtype, np.float32)
False
>>> np.issubdtype(a.dtype, np.dtype(np.float32))
True
```
There is no obvious fix for `convert`, but I will investigate more ;-)

**Comment by hmaarrfk** [comment]
Numpy 1.13.3 is basically dead. Numpy doesn't recommend supporting older than 1.14. So let's just bump out version number

**Comment by rfezzani** [comment]
What about using `dtypeobj_in.kind == dtypeobj_out.kind and np.can_cast(dtypeobj_in, dtypeobj_out)` instead of `np.issubdtype(dtypeobj_in, type_out)` in the convert function?
I can come with a PR for this if you agree with this solution...

**Comment by jni** [comment]
@stefanv thoughts about bumping up NumPy dep?

@hmaarrfk I thought about that, but checked and NumPy 1.13 is only 2yo, which isn't that long. Having said that, if someone tried to support skimage from 2y ago simultaneously with today's skimage, they would not have fun, so perhaps we should move a bit faster.

**Comment by stefanv** [comment]
https://github.com/numpy/numpy/blob/e7bc0989ea9f99e070c8f54d23dbdd23b9703cda/doc/neps/nep-0029-deprecation_policy.rst

**Comment by stefanv** [comment]
```
On Jan 16, 2019 drop support for Numpy 1.12 (initially released on Jan 15, 2017)
On Mar 14, 2019 drop support for Python 3.5 (initially released on Sep 13, 2015)
On Jun 08, 2019 drop support for Numpy 1.13 (initially released on Jun 07, 2017)
On Jan 07, 2020 drop support for Numpy 1.14 (initially released on Jan 06, 2018)
On Jun 23, 2020 drop support for Python 3.6 (initially released on Dec 23, 2016)
On Jul 23, 2020 drop support for Numpy 1.15 (initially released on Jul 23, 2018)
On Jan 13, 2021 drop support for Numpy 1.16 (initially released on Jan 13, 2019)
On Jul 26, 2021 drop support for Numpy 1.17 (initially released on Jul 26, 2019)
On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)
```

**Comment by stefanv** [comment]
By the way, there is code at the bottom of that NEP to calculate this table, so we can automate a check so that we automatically upgrade our NumPy and Python deps.

**Comment by rfezzani** [comment]
This bug also affects `img_as_float32`:
```python
>>> img_as_float32(rand(5)).dtype
dtype('float64')
```

**Comment by rfezzani** [comment]
If you don't want to wait for numpy 1.13 drop, the PR #4193 fixes this issue ;-)

**Comment by hmaarrfk** [comment]
I thought we were saying the numpy drop is today. And we would support a PR that Drops it.  Most of time, unless there is a real big, we don't drop it, but maybe we should just drop regardless. That NEP is new.

**Comment by rfezzani** [comment]
Oh, I misread @stefanv comment, I though that the NEP was advising to drop `numpy 1.13` on On Jun 08, **2020** :smile: .
By the way, the PR includes also small refactoring of `skimage.utils.dtype` and some tests that may have avoided this issue.

**Comment by stefanv** [comment]
The NEP is likely to be accepted; there have been no objections.

Go ahead and drop 1.13 support.
