### ISSUE TITLE
"Download" link on website broken 

### ISSUE THREAD

**Issue by kgdunn** [scikit-image/scikit-image#4221]
## Description
Link to _Download_ broken, depending on the path you navigate. The path to navigate is not unusual, especially for a new user.

## Way to reproduce
1. Go to https://scikit-image.org/
2. Click on gallery first on the top menu (https://scikit-image.org/docs/stable/auto_examples/)
3. Then go to Download link (currently https://scikit-image.org/download.html)
4. You get a 404 error

**Comment by sciunto** [comment]
Thanks for reporting!

**Comment by sciunto** [comment]
On the dev version, the link is correct: https://scikit-image.org/docs/dev/

It's caused by recent changes that were not backported to older versions. @soupault Do you have an idea?

**Comment by soupault** [comment]
I will take a look!

**Comment by stefanv** [comment]
Fixed by @soupault in https://scikit-image.org/docs/stable/install.html

**Comment by stefanv** [comment]
So, yes, will have to go and edit the old builds.

**Comment by stefanv** [comment]
I updated the old builds.
