### ISSUE TITLE
AttributeError: module 'skimage' has no attribute 'transform'

### ISSUE THREAD

**Issue by rathaROG** [scikit-image/scikit-image#4241]
## Description
It only happens with version 0.16.1. There is no such problem with version 0.15.0.

## Version information
```python
# Paste the output of the following python commands
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.18362-SP0
scikit-image version: 0.16.1
numpy version: 1.16.5
```

```python
# your output here
AttributeError: module 'skimage' has no attribute 'transform'
```

**Comment by jni** [comment]
@rathaROG what command gave you that output?

**Comment by jni** [comment]
I suspect you are doing:

```python
import skimage
skimage.transform.(whatever)
```

but that was never designed to work: scikit-image uses "lazy importing", so you have to explicitly import submodules:

```python
import skimage.transform
skimage.transform.(whatever)
```

If it worked before it was an implementation error, not a design flaw.

Please let me know if my intuition above is correct and that fixes your issue...

**Comment by rathaROG** [comment]
Hi @jni ! `import skimage.transform` works. Thanks!

**Comment by meghajain0510** [comment]
import skimage.transform works .thanks
