### ISSUE TITLE
Speeding up CI

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#4242]
@bsipocz made a [PR to NumPy](https://github.com/numpy/numpy/pull/14703/files) to run a set of tests on *one worker* to catch early failures, before launching the full parallel suite.  This is a great way to save cores, since PRs are likely to fail quite often.

**Comment by bsipocz** [comment]
happy to open a PR here, too.

**Comment by stefanv** [comment]
@bsipocz That would be great!

**Comment by hmaarrfk** [comment]
Moving to azure would speed things up too

**Comment by bsipocz** [comment]
That would speed the total time for sure, but not solve the issue of wasting resources with trivially failing commits.

**Comment by stefanv** [comment]
@hmaarrfk We have Azure already; do you mean moving all jobs there?

**Comment by hmaarrfk** [comment]
yeah. seems to be pretty stable. test period over ;) but porting CIs isn't my favorite activity ;).

**Comment by bsipocz** [comment]
One could argue that there is value not to rely on only one CI platforms, but if you don't use any of their missing features, it may indeed make sense to move over  to Azure.  

Anyway, I'm opening the PR for the stages now, then you can take the time to migrate over.

**Comment by soupault** [comment]
@hmaarrfk I will take care of Azure, as anticipated. I am glad you are, finally, on the bright side :).
