### ISSUE TITLE
Histogram equalization before extracting HOG features?

### ISSUE THREAD

**Issue by MK2345** [scikit-image/scikit-image#4244]
Hello, 

I'm a beginner in using scikit-image. I want to extract HOG-features from traffic sign images.
The images were taken under different weather conditions.
Does it make sense to make a histogram equalization before extracting HOG features?

```from skimage import exposure
from skimage.feature import hog

img_eq = exposure.equalize_hist(img)
hog_img = hog(img_eq, orientations=9, pixels_per_cell=(4,4), cells_per_block=(2,2), visualize=False)
```
Or is it superfluous to use histogram equalization in combination with hog?
I'm asking because I have problems with memory if I do histogram equalization. Therefore, it would be good to know if this has any major impact on determining the HOG features.

**Comment by jni** [comment]
@MK2345 thanks for your interest in scikit-image!

I myself don't know the answer to your question. (Someone else in the team might, we'll see.) The original HOG paper is probably the best source to find the answer. Alternatively, you should take a small enough subset of your data that you can avoid your memory errors, then measure performance of your pipeline with and without histeq.

**Comment by jni** [comment]
I'm going to close this issue in favour of the [image.sc post](https://forum.image.sc/t/histogram-equalization-before-extracting-hog-features/30409), which is the better forum for this!
