### ISSUE TITLE
Flood_fill use "inplace" kwarg, and the library uses "in_place" elsewhere

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4248]
## Description

https://scikit-image.org/docs/dev/api/skimage.segmentation.html#skimage.segmentation.flood_fill

To be consistent, inplace must be deprecated in favor of in_place.

**Comment by robroooh** [comment]
is anyone working on this? I would like to contribute.

**Comment by rfezzani** [comment]
Fixed by #4250, thx @robroooh

**Comment by sciunto** [comment]
Great! Thank you @robroooh
