### ISSUE TITLE
Frangi artefacts around the image

### ISSUE THREAD

**Issue by wimthiels** [scikit-image/scikit-image#4249]
[img_raw.zip](https://github.com/scikit-image/scikit-image/files/3738350/img_raw.zip)

## Description
![frangi problem](https://user-images.githubusercontent.com/32536010/66994646-e4da8980-f0cd-11e9-950f-e154f3f1baf3.jpg)

Hi,
I upgraded Scikit from 0.14.2 to 0.16.1 and now I experience some problems. As illustrated in the picture, with the new Frangi I get a a bright square all across the image which I did not get using the old version (and also not present in the raw image)
I used Frangi in 2D and I still use the beta1 and beta2 parameters (instead of beta and gamma). Switching over to the new parameters does not solve it

                              'scale_range'= [5,6]
                              'scale_step' = 1
                              'beta1'=1         
                              'beta2'=0.0005
                              'black_ridges':True
I don't pass on the alpha parameter (because I work in 2D), but I do notice that this alpha is still used in calculations (maybe ok, I don't know)

I will have to revert to 14.01 for now, but if this could be fixed that would be great

thanks !
Wim

## Way to reproduce
from tifffile import TiffFile,imsave
from skimage.filters import frangi
from skimage import img_as_uint

with TiffFile("img_raw.tif") as tif:
    img_raw= tif.asarray()
frangi_img = frangi(img_raw,scale_range=[5,6],
                    scale_step=1,
                    beta1 = 1, 
                    beta2 = 0.0005,
                    black_ridges=True)

imsave("frangi.tif", img_as_uint(frangi_img))

## Version information
```python 3.7.3 

Running the previous version scikit : 
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
scikit-image version: 0.14.2
numpy version: 1.16.2

running  the new version scikit
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
scikit-image version: 0.16.1
numpy version: 1.16.2
frangi_issue_recreate.py:18: UserWarning: Use keyword parameter `beta` instead of `beta1` which will be removed in version 0.17.
  black_ridges=True)
frangi_issue_recreate.py:18: UserWarning: Use keyword parameter `gamma` instead of `beta2` which will be removed in version 0.17.
  black_ridges=True)
frangi_issue_recreate.py:18: UserWarning: Use keyword parameter `sigmas` instead of `scale_range` and `scale_range` which will be removed in version 0.17.
  black_ridges=True)

**Comment by jni** [comment]
Yikes, thank you for the report @wimthiels! We'll chase it down. I suspect it was accidentally introduced in #3515...

**Comment by rfezzani** [comment]
I found in #4343 that managing border conditions for `compute_hessian_eigenvalues` fixes this issue.
