### ISSUE TITLE
New PyWavelets version 1.1.0 breaks skimage 0.14.x due to python3 collections.abc incompatibility

### ISSUE THREAD

**Issue by willgraf** [scikit-image/scikit-image#4258]
## Description
The new version of `PyWavelets` (1.1.0) uses `from collections.abc import Iterable` which fails in python 2.7.  The scikit-image 0.14.x release should probably be updated to use `PyWavelets<1.1.0`  to resolve this.

## Way to reproduce
```python
# After installing scikit-image==0.14.5
from skimage.io import imread
```

**Comment by hmaarrfk** [comment]
pip should be smart enough not to install pywt since it would be tagged as python 3 release only.

how did you install pywt 1.1.0??? it isn't even released yet?

@grlee77 maybe you should add a python_requires line to your setup.py??? not too sure.

**Comment by willgraf** [comment]
Sorry my mistake it is PyWavelets==1.1.0 not pywt
(apparently pywt is a different package on pip but it is referenced by skimage as pywt)

```
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/pywt/_dwt.py:11: in <module>

    from ._utils import string_types, _as_wavelet

../../../miniconda/envs/test-environment/lib/python2.7/site-packages/pywt/_utils.py:7: in <module>

    from collections.abc import Iterable

E   ImportError: No module named abc
```

**Comment by emmanuelle** [comment]
I guess we should pin the `pywavelets` dep and do a bugfix release because this is going to be very annoying for the packages depending on us... (I arrived here because the CI of `plotly.py` broke since `scikit-image` is an optional dep)

**Comment by hmaarrfk** [comment]
I think this is a pywavelets bug. You should be able to on python 2.7 type
```
pip install pywavelets
```
without it installing an invalid version.

scikit-image will only install 0.14 while we have release python 3 only versions (0.15 and 0.16).
PyWavelets can do the same.
Lets wait for @grlee77  to respond.

**Comment by grlee77** [comment]
I can try to fix this on the PyWavelets end and make a 1.1.1 release ASAP.

I will try adding `python_requires='>=3.5'` to `setup.py`.

**Comment by grlee77** [comment]
I'm not sure that doing a new release would prevent pip from still trying to download 1.1.0 from source on Python 2.7, though?

**Comment by hmaarrfk** [comment]
Yeah. You might want to try and pull 1.1.0 .....

**Comment by grlee77** [comment]
@hmaarfk:  does PyWavelets/pywt/#529 look like it should work?

**Comment by grlee77** [comment]
I have removed the 1.1.0 source tarball from PyPI. I will upload a 1.1.1 release that prevents pip installation on Python <3.5 in some hours.

**Comment by hmaarrfk** [comment]
Not sure. Maybe it will work. It seems like that is the only difference between your setup.oy and scikit images

**Comment by hmaarrfk** [comment]
@willgraf do take this as a warning, that much of the scientific community has moved on from supporting python 2, and these growing pains are likely going to be quite common. :/ I hope you arent stuck on python 2.

**Comment by willgraf** [comment]
@hmaarrfk Happily not stuck, but the codebase I'm working on [deepcell-tf](https://github.com/vanvalenlab/deepcell-tf) relies on TensorFlow, and I am attempting to mimic their supported platforms.  If these issues do continue to come up (especially after 2020 EOL), I will likely abandon the python 2 support.

**Comment by hmaarrfk** [comment]
Looks like a cool project!

**Comment by grlee77** [comment]
I am going to close this as resolved on the PyWavelets end. The source tarballs for 1.1.0 were removed from PyPI and a 1.1.1 release was added. 

I tried pip installing PyWavelets from Python 2.7 and now it finds only 1.0.3 and older as expected. 1.1.1 will only be installed for Python 3.5+.

Thank you @willgraf for bringing this to our attention! Please reopen if you still experience the issue.

**Comment by hmaarrfk** [comment]
Thanks grlee, glad we were able to help others find a solution to this!
