### ISSUE TITLE
Bump numpy to >= 1.16

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4259]
## Description

In the TODO list, several tasks are about numpy >= 1.16. This version opens up the possibility to use linspace, logspace... functions in nD. As it is a goal to get nD algorithm in scikit-image, I propose to bump numpy for our next release to facilitate future contributions.

I assign this task to myself.

**Comment by hmaarrfk** [comment]
I love bleeding edge as much as the next person, but how does this affect things for popular distros? Would they be stuck on older versions of skimage due to this?

For example, I think ubuntu 19.10 is packaging Numpy 1.16.2 and skimage 0.14.2 for python3.

**Comment by sciunto** [comment]
1.16.x has been published in Jan. 2019. If we take 6 months to prepare the next release, the min req. version will be out for more than a year.

**Comment by hmaarrfk** [comment]
Right, that makes sense. But I'm more of the opinion that we should try to have more rolling release ;)

**Comment by jni** [comment]
@sciunto how does this fit in with the NEP-29 deprecation policy? Is it more aggressive or basically implementing the policy?

**Comment by sciunto** [comment]
It depends when we release the next version,  1.15 is supposed to be unsupported in Jul 23, 2020. It doesn't look so aggressive.

**Comment by hmaarrfk** [comment]
It seems a little aggressive for me:

Using: https://github.com/numpy/numpy/issues/15173  https://gist.github.com/hmaarrfk/0e2a01d57f07f55eb99d177da92691b6

I found that bumping to 1.16, even if we are to release in June 2020, would mean that we are only supporting versions in the last 18 months:
![image](https://user-images.githubusercontent.com/90008/71450747-b44e4600-2735-11ea-98b6-83b0f48f35a5.png)

**Comment by grlee77** [comment]
NumPy was bumped to 1.16.5 in #5016
