### ISSUE TITLE
module 'skimage' has no attribute 'measure'

### ISSUE THREAD

**Issue by gustavahlberg** [scikit-image/scikit-image#4266]
## Description
v.16.02
module 'skimage' has no attribute 'measure' 
just gone??

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
import skimage
skimage.measure.label
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.4 (default, Aug 13 2019, 15:17:50)
Darwin-17.7.0-x86_64-i386-64bit
scikit-image version: 0.16.2
numpy version: 1.17.3

```

**Comment by gustavahlberg** [comment]
aha ok I see. Great! thanks!

**Comment by Tianbe** [comment]
Maybe you should adjust your examples accordingly, because there you just import skimage, not explicitly skimage.measure (like here: http://soft-matter.github.io/trackpy/v0.4.2/tutorial/custom-feature-detection.html)

**Comment by soupault** [comment]
@Tianbe I think, in general, we have it done right. Would it be possible for you to point to specific examples of ours (the notebook you are referring to is provided by `trackpy` team)?

**Comment by Tianbe** [comment]
So if you follow the link, there is the example "custom feature detection" (In [6]) where you use skimage.measure, but if I haven't missed it, you never imported it
