### ISSUE TITLE
Imread fails to read multiple tiff files if certain letter and number combination is in the filename. 

### ISSUE THREAD

**Issue by matesumegi** [scikit-image/scikit-image#4272]
## Description
Imread fails to read multiple tiff files if certain letter and number combination is included in the filename. 
Tested on win10 and linux.
pls, see my output:
A
(1, 3, 4, 301, 219)
a
(1, 3, 4, 301, 219)
B
(2, 3, 4, 301, 219)
b
(2, 3, 4, 301, 219)
C
(1, 3, 4, 301, 219)
c
(1, 3, 4, 301, 219)
D
(2, 3, 4, 301, 219)
d
(2, 3, 4, 301, 219)
E
(2, 3, 4, 301, 219)
e
(2, 3, 4, 301, 219)
F
(2, 3, 4, 301, 219)
f
(2, 3, 4, 301, 219)
G
(2, 3, 4, 301, 219)
g
(2, 3, 4, 301, 219)
H
(2, 3, 4, 301, 219)
h
(2, 3, 4, 301, 219)
I
(2, 3, 4, 301, 219)
i
(2, 3, 4, 301, 219)
J
(2, 3, 4, 301, 219)
j
(2, 3, 4, 301, 219)
K
(2, 3, 4, 301, 219)
k
(2, 3, 4, 301, 219)
L
(1, 3, 4, 301, 219)
l
(1, 3, 4, 301, 219)
M
(2, 3, 4, 301, 219)
m
(2, 3, 4, 301, 219)
N
(2, 3, 4, 301, 219)
n
(2, 3, 4, 301, 219)
O
(2, 3, 4, 301, 219)
o
(2, 3, 4, 301, 219)
P
(1, 3, 4, 301, 219)
p
(1, 3, 4, 301, 219)
Q
(1, 3, 4, 301, 219)
q
(1, 3, 4, 301, 219)
R
(2, 3, 4, 301, 219)
r
(2, 3, 4, 301, 219)
S
(2, 3, 4, 301, 219)
s
(2, 3, 4, 301, 219)
T
(1, 3, 4, 301, 219)
t
(1, 3, 4, 301, 219)
U
(2, 3, 4, 301, 219)
u
(2, 3, 4, 301, 219)
V
(2, 3, 4, 301, 219)
v
(2, 3, 4, 301, 219)
W
(2, 3, 4, 301, 219)
w
(2, 3, 4, 301, 219)
X
(1, 3, 4, 301, 219)
x
(1, 3, 4, 301, 219)
Y
(1, 3, 4, 301, 219)
y
(1, 3, 4, 301, 219)
Z
(1, 3, 4, 301, 219)
z
(1, 3, 4, 301, 219)
## Way to reproduce
```python
# Place the full code we need to recreate your issue here
import skimage.external.tifffile
import numpy

for letter in list('AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz'):
    skimage.external.tifffile.imsave(letter + '1.tif', numpy.random.rand(3, 4, 301, 219))
    ims = skimage.external.tifffile.imread([letter + '1.tif', letter + '1.tif'])
    print (letter)
    print(ims.shape)
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Windows-10-10.0.17763-SP0
scikit-image version: 0.15.0
numpy version: 1.16.5

```

**Comment by cgohlke** [comment]
Use `skimage.external.tifffile.imread([...], pattern=None)` or install tifffile from [PyPI](https://pypi.org/project/tifffile/).

**Comment by matesumegi** [comment]
skimage.external.tifffile.imread([...], pattern=None) worked fine. Thanx!

Now I see in why XYCZT and others are behaving strangely.

TiffSequence
   pattern: str
Regular expression pattern that matches axes names and sequence indices in file names. **By default this matches Olympus OIF and Leica TIFF series.**
