### ISSUE TITLE
skimage.metrics structural_similarity() VS Original MatLab version

### ISSUE THREAD

**Issue by sendjasni** [scikit-image/scikit-image#4278]
## Description

I'm trying to compute SSIM (Structural SIMilarity) between two `bmp` images on Python. I've found structural_similarity() function implemented in the skimage python library and the equivalent code from the original MatLab implementation which is writing in matlab.

## Way to reproduce
```python
def structuralSimilarityIndex(ref_image, impaired_image, cs_map=False):

    window = Metric.fSpecialGauss(constant.SSIM_FILTER_SIZE,
                                  constant.SSIM_FILTER_SIGMA)
    C1 = (constant.SSIM_Constant_1 * constant.PIXEL_MAX) ** 2
    C2 = (constant.SSIM_Constant_2 * constant.PIXEL_MAX) ** 2

    mu1 = signal.fftconvolve(window, ref_image, mode='valid')
    mu2 = signal.fftconvolve(window, impaired_image, mode='valid')

    mu1_sq = mu1 * mu1
    mu2_sq = mu2 * mu2
    mu1_mu2 = mu1 * mu2

    sigma1_sq = signal.fftconvolve(
        window, ref_image*ref_image, mode='valid') - mu1_sq
    sigma2_sq = signal.fftconvolve(
        window, impaired_image*impaired_image, mode='valid') - mu2_sq
    sigma12 = signal.fftconvolve(
        window, ref_image*impaired_image, mode='valid') - mu1_mu2

    if cs_map:
        return (((2 * mu1_mu2 + C1) * (2 * sigma12 + C2)) / ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2)), (2.0 * sigma12 + C2) / (sigma1_sq + sigma2_sq + C2))
    else:
        return np.mean(((2 * mu1_mu2 + C1) * (2 * sigma12 + C2)) / ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2)))

# Uploading the images using Image from PIL
ref_image = np.asfarray(Image.open('ref_image.bmp').convert('L'))
impaired_image = np.asfarray(Image.open('impaired_image.bmp').covert('L)

# Calling both function 

# Using the above code
structuralSimilarityIndex(ref_image, impaired_image, cs_map=False)

# Using the function imported from skimage.metrics
structural_similarity(ref_image, impaired_image, gaussian_weights=False, use_sample_covariance=False) 

```

## Version information
```python
# Paste the output of the following python commands
3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.16.2
numpy version: 1.17.3
```

```python
# your output here

# The SSIM from the Skimage python library:
    SSIM : 0.38135154028457885

# The SSIM from the code above:
    SSIM : 0.8208087737160036

# The SSIM from the original MatLab version
   SSIM : 0.8424 
```

The images used are in `bmp` so i couldn't load them here. You can find theme in [here](https://drive.google.com/drive/folders/17Oak_5yOt9pAhHWhV-5J36iepca7en11?usp=sharing)

**Comment by grlee77** [comment]
I think the primary issue here is that the way you computed images from PIL results in floating point imgaes, but ones where the values are in the range [0, 255.0]. skimage will assume a range [-1.0, 1.0] for data_range when the input is floating point, so you will need to manually specify `data_range=255.`

Also, see the Notes section of the docstring for recommendations to set `gaussian_weights=True, sigma=1.5` to more closely match the Matlab script by Wang et. al. (I think recent Matlab also has its own built-in SSIM implementation, but I haven't tried comparing to that case and don't know if it is exactly the same).


```Python
ref_image = np.asfarray(Image.open('avion.bmp').convert('L'))
impaired_image = np.asfarray(Image.open('avion_jpeg_r5.bmp').convert('L'))
structural_similarity(ref_image, impaired_image, multichannel=True, gaussian_weights=True, sigma=1.5, use_sample_covariance=False, data_range=255)
```
gives `0.8292` when I tried it.


Alternatively you can use `skimage.io.imread` and `rgb2gray` to read in the data and convert it to grayscale. In that case, values will have been scaled within [0, 1.0] for you and data_range should be set to 1.0.
```Python
from skimage.io import imread
from skimage.color import rgb2gray
ref_image = imread('avion.bmp')
ref_image = rgb2gray(ref_image)
impaired_image = imread('avion_jpeg_r5.bmp')
impaired_image = rgb2gray(impaired_image)

structural_similarity(ref_image, impaired_image, multichannel=True, gaussian_weights=True, sigma=1.5, use_sample_covariance=False, data_range=1.0)
```
gives `0.8265`

**Comment by grlee77** [comment]
I think the small difference between the two cases above is probably due to `rgb2gray` using a different luminance conversion than PIL's `convert` method.

**Comment by jni** [comment]
Ah, thanks for the investigation, @grlee77! Another one for #3009!

@sendjasni does that answer your question satisfactorily? If so, please close the issue. Thank you!

**Comment by sendjasni** [comment]
It did answer my question. Thanks to @grlee77 for the answer.

**Comment by sendjasni** [comment]
By the way, I've posted a question in StackOverflow before opening this issue, It would be nice of you if you answer it there which could be helpfull for other people. [Here the post](https://stackoverflow.com/questions/58604326/which-ssim-is-correct-skimage-metrics-structural-similarity)
