### ISSUE TITLE
Docstring in util.pad returns <no docstring>

### ISSUE THREAD

**Issue by alexdesiqueira** [scikit-image/scikit-image#4281]
## Description

`util.pad()` returns an empty docstring; however, [the docstring is there](https://github.com/scikit-image/scikit-image/blob/v0.12.2/skimage/util/arraypad.py#L1117).
Any idea on what's happening? Thanks y'all!

## Way to reproduce
```python
In [1]: from skimage import util                                                                                                    

In [2]: util.pad?                                                                                                                   
Signature: util.pad(*args, **kwargs)
Docstring: <no docstring>
File:      ~/<__array_function__ internals>
Type:      function
```

## Version information
```python
# Paste the output of the following python commands
>>> from __future__ import print_function

>>> import sys; print(sys.version)
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]

>>> import platform; print(platform.platform())
Linux-5.3.0-20-generic-x86_64-with-debian-buster-sid

>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.16.2

>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.17.3
```

**Comment by jni** [comment]
@alexdesiqueira your link points to the v0.12.2 tag for some reason! 😂 

If you look at the latest master, pad is a wrapper around `numpy.pad`. It looks like we are doing a poor job wrapping it:

https://github.com/scikit-image/scikit-image/blob/d289b45299f44d85d4299f3f7c3ef803bcee344e/skimage/util/__init__.py#L15-L18

**Comment by alexdesiqueira** [comment]
> @alexdesiqueira your link points to the v0.12.2 tag for some reason! joy

:joy: go figure...
Maybe `copy_func` has something wrong? I'll check it out.

**Comment by sciunto** [comment]
xref #4147
