### ISSUE TITLE
inconsistent api gray2rgb

### ISSUE THREAD

**Issue by navneeth** [scikit-image/scikit-image#4286]
This is ultra silly. But I was wondering if the incosistency of gray (or grey) in 
```
skimage.color.gray2rgb(image[, alpha]) | Create an RGB representation of a gray-level image.

skimage.color.grey2rgb(image[, alpha]) | Create an RGB representation of a gray-level image.
```
is on purpose ?
Would be nice if they both pick the same gray/grey. 
Happy to submit a silly PR if it makes sense.

thanks,
navneeth

**Comment by hmaarrfk** [comment]
They are the same function

Both are kept for historical reasons.

You are free to use whatever you wish, but we are moving toward America spelling. We typically offer users a warning about 1 year before we remove functions.

https://github.com/scikit-image/scikit-image/blob/435cedcf50e34b8adbfa4720d3e6d3f45f4005d8/skimage/color/colorconv.py#L860

**Comment by navneeth** [comment]
Perfect. Makes sense. 
Thanks !
