### ISSUE TITLE
Rescaling boolean arrays yields plausible result or array of zeros depending on the scale factor

### ISSUE THREAD

**Issue by franciscomcm** [scikit-image/scikit-image#4292]
## Description
Hello!
I am using `skimage.transform.rescale` to down-scale boolean arrays that have a single connected component.
Depending on the scale factor selected, the output yields a result that seems correct or an array full of zeros.

If I convert the boolean array to float, the result is different than when I pass the array with values as bool or int. 
Setting 'anti-aliasing' to False yields the same result for int, bool or float values in the array.

Furthermore, the expression given in the `rescale` function documentation to compute the "anti_aliasing_sigma" is different than the actual expression used inside `skimage.transform.resize` (which is called in `skimage.transform.rescale`):
- `skimage.transform.rescale`: "By default, this value is chosen as (1 - s) / 2 where s is the down-scaling factor."
- `skimage.transform.resize`: "By default, this value is chosen as (s - 1) / 2 where s is the down-scaling factor, where s > 1."

## Way to reproduce
```python
import numpy as np
from skimage.transform import rescale

input_matrix_shape = (1000, 1200, 400)
high_resolution_matrix = np.zeros(input_matrix_shape)
high_resolution_matrix[200:800, 300:900, 100:300] = 1 # Fill matrix with some ones
high_resolution_matrix = high_resolution_matrix.astype(np.bool_)
scale_factor_list = [0.625, 0.305]

for current_scale_factor in scale_factor_list:
    rescaled_matrix = rescale(high_resolution_matrix, current_scale_factor, order = 0, anti_aliasing=True, multichannel=False, preserve_range=True)
    print('Scale factor: {}'.format(current_scale_factor))
    print('\tResult shape: {}'.format(rescaled_matrix.shape))
    print('\tTotal non-zero values: {}'.format(np.sum(rescaled_matrix > 0)))
    print()
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.5 (default, Oct 17 2019, 12:21:00) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
Linux-5.2.17-100.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
scikit-image version: 0.16.2
numpy version: 1.17.3
```

**Comment by rfezzani** [comment]
Confirmed! I can reproduce it :sob:  `resize` is also affected...

**Comment by rfezzani** [comment]
Thank you @franciscomcm for the report and sorry for answering so late :pray:

**Comment by rfezzani** [comment]
OK, deactivating anti-aliasing fixes the issue!
I think that it makes sens when a bool array is provided as input to set `order=0` and `anti-aliasing=False` by default and to raise a warning if the user provides different values. I will open a PR for this.
