### ISSUE TITLE
can't import threshold_adaptive from skimage

### ISSUE THREAD

**Issue by kothawadegs** [scikit-image/scikit-image#4301]
I tried to import threshold_adaptive from skimage filters, but its's giving me an error

```python
from skimage.filters import threshold_adaptive
```

**Comment by jni** [comment]
`threshold_adaptive` was deprecated in 0.13 and removed in 0.15 in favor of `threshold_local`. You should replace that call with:

```python
from skimage.filters import threshold_local
```

and things should work fine. =)

I'm closing the issue as resolved, but feel free to ask for further help if needed!

**Comment by kothawadegs** [comment]
It's working, but it's not giving results like an adaptive threshold.

**Comment by 943fansi** [comment]
At thresholding.py , look def threshold_local(), notice that: return thresh_image - offset.
this means that  It returns a threshold picture.
    you can change to : return image > (thresh_image - offset) 
then it will returns a real binary image.
  The version I'm using scikit-image is 0.17.2.
