### ISSUE TITLE
io documentation is incomplete

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#4309]
## Description

`skimage.io.collection.alphanumeric_key` is a useful function (my second addition to skimage! :smile:), but it is currently not documented (https://scikit-image.org/docs/dev/api/skimage.io.html), it is importable from `skimage.io.collection` instead of `skimage.io` (is this how we want it?), and cannot be found by `skimage.lookfor`.

## Way to reproduce
```python
import skimage
skimage.lookfor('alphanumeric_key')
from skimage.io.collection import alphanumeric_key  # works
```

**Comment by stefanv** [comment]
@jni I recommend renaming this function to something that hints at its function, and moving it to utilities from io.

**Comment by sciunto** [comment]
Replaced by #4513
