### ISSUE TITLE
Compressed TIFF files?

### ISSUE THREAD

**Issue by kmader** [scikit-image/scikit-image#4326]
## Description
I get error messages when trying to read various compressed tiff images using `skimage.io.imread` (both could be read using `PIL.Image.open`)

- PACKBITS
The first error is `ValueError: TiffPage 0: cannot decompress PACKBITS` and comes with this file https://gist.github.com/kmader/6cb706e52a58c6edc2f4c97678cea4a9/raw/a1dbd04aeb19c7d032f6a7555d4b69045fcddd3d/00215.tif 

And was found in a 3D tomography repository at https://datadryad.org/stash/dataset/doi:10.5061/dryad.c65b4j5

- LZW
The second error is `ValueError: TiffPage 0: cannot decompress LZW`
https://gist.github.com/kmader/6cb706e52a58c6edc2f4c97678cea4a9/raw/8100ea501cb1b60857891d49e0b9320766992e7f/Romundinactrpt0000.tif

## Way to reproduce
```python
from skimage.io import imread
imread('00215.tif')
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]
Linux-4.9.0-11-amd64-x86_64-with-debian-9.9
scikit-image version: 0.16.2
numpy version: 1.16.4
```

**Comment by kmader** [comment]
As I frequently use images like these in lectures (and would like to use skimage for as much as possible) I would like to fix the error, but am unsure how to best proceed.

**Comment by hmaarrfk** [comment]
can you try to install tifffile?

What is the output of `conda list`???

**Comment by hmaarrfk** [comment]
If you do need a newer version of tifffie than the one we vendor, I think eventually, you will find that you have many dependencies that are beyond scikit-image, e.g. jupyter, bokeh???. You might want to create an `environment.yml` file, that you can share and ask students to update as you add more dependencies
```
conda env update --file environment.yml
```
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by kmader** [comment]
@hmaarrfk I see this which seems like it very new.
```
tifffile                  2019.7.26                pypi_0    pypi
```

**Comment by hmaarrfk** [comment]
Ok, I can now reproduce, using the same version of tiffile 
```
tifffile                  2019.7.26        py37hc1659b7_1    conda-forge
```

<details> 
```python
$ ipython
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from skimage.io import imread                                           

In [2]: imread('00215.tif')                                                     
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-17e80188eb32> in <module>
----> 1 imread('00215.tif')

~/miniconda3/envs/dev/lib/python3.7/site-packages/skimage/io/_io.py in imread(fname, as_gray, plugin, **plugin_args)
     46 
     47     with file_or_url_context(fname) as fname:
---> 48         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     49 
     50     if not hasattr(img, 'ndim'):

~/miniconda3/envs/dev/lib/python3.7/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    208                                (plugin, kind))
    209 
--> 210     return func(*args, **kwargs)
    211 
    212 

~/miniconda3/envs/dev/lib/python3.7/site-packages/skimage/io/_plugins/tifffile_plugin.py in imread(fname, dtype, **kwargs)
     47     # read and return tiff as numpy array
     48     with TiffFile(fname, **kwargs_tiff) as tif:
---> 49         return tif.asarray(**kwargs)

~/miniconda3/envs/dev/lib/python3.7/site-packages/tifffile/tifffile.py in asarray(self, key, series, out, validate, maxworkers)
   2411         elif len(pages) == 1:
   2412             result = pages[0].asarray(out=out, validate=validate,
-> 2413                                       maxworkers=maxworkers)
   2414         else:
   2415             result = stack_pages(pages, out=out, maxworkers=maxworkers)

~/miniconda3/envs/dev/lib/python3.7/site-packages/tifffile/tifffile.py in asarray(self, out, squeeze, lock, reopen, maxsize, maxworkers, validate)
   4355             if self.compression not in TIFF.DECOMPESSORS:
   4356                 raise ValueError('TiffPage %i: cannot decompress %s'
-> 4357                                  % (self.index, self.compression.name))
   4358             if 'SampleFormat' in tags:
   4359                 tag = tags['SampleFormat']

ValueError: TiffPage 0: cannot decompress PACKBITS
```

For reference, this same output from your computer is useful in debugging other errors.
</details>

In here, we can see that it is in fact using the tifffile installed from conda-forge/(you installed it through pypi it seems).

In either case, this seems to be something related to the capabilities of tifffile itself.
https://www.lfd.uci.edu/~gohlke/

You can try to contact `@cgohlke` to see what the status on these two features is. To my knowledge, there isn't any official publically facing git repo.

**Comment by hmaarrfk** [comment]
hmm, strange enough, our vendored version of tifffile is able to read it.

**Comment by hmaarrfk** [comment]
From a previous conversation with cgohlke, I remember he mentionned something about needed https://pypi.org/project/imagecodecs/#files

That said, it doesn't install easily on linux.
https://github.com/conda-forge/staged-recipes/pull/6842

**Comment by hmaarrfk** [comment]
Ok, The solution is to install `imagecodecs`, but `imagecodecs` is hard to install on linux (not yet on pypi for linux or conda-forge for any platform). so maybe just install `imagecodecs-lite` + `tiffffile`.

```python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from skimage.io import imread
>>> imread("Romundinactrpt0000.tif")
array([[ 0,  1,  2, ..., 19, 18, 18],
       [ 0,  0,  0, ..., 17, 18, 19],
       [ 0,  0,  0, ..., 17, 15, 17],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=uint16)
```

<details>

```
$ conda list
# packages in environment at /home/mark/miniconda3/envs/dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask-core                 2.8.1                      py_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
imagecodecs-lite          2019.4.20        py37h516909a_0    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                hc3755c2_1    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
matplotlib-base           3.1.2            py37h250f245_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pillow                    6.2.1            py37hd70f55b_1    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scipy                     1.3.2            py37h921218d_0    conda-forge
setuptools                42.0.1                   py37_0    conda-forge
six                       1.13.0                   py37_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tifffile                  2019.7.26        py37hc1659b7_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```
</details>

Basically, two things need to be done:

1. Release `imagecodecs` wheels on linux64 bit on pypi
2. Ask `@cgohlke` to make `tifffile` depend on `imagecodecs`
3. Release `imagecodecs` on conda-forge. 
4. Make conda-forge `tiffffile` depend on `imagecodecs`

**Comment by cgohlke** [comment]
The options are

* uninstall the `tifffile` package. scikit-image will use the vendored tifffile module.
* `pip install imagecodecs-lite`. This will build and install the missing LZW and PackBits codecs.
* `pip install imagecodecs` after `sudo apt-get install ...` the build requirements. This will build and install the missing LZW and PackBits and additional JPEG, PNG etc codecs.
* install build artifacts from https://github.com/Czaki/imagecodecs/pull/1

**Comment by Czaki** [comment]
I have hope that I'm finishing process of automated creating wheels for imagecodecs (linux + macos). Whole pipeline is public and running on azure pipelines. Also in repository https://github.com/Czaki/imagecodecs there are scripts for building all needed libraries.  

I'm open for review. 

Initial wheels (not accepted yet) can be found here https://github.com/Czaki/imagecodecs/releases

**Comment by jni** [comment]
Yep, for reference from our last conversation and for future people stumbling on this issue, here's what happened:

- we decided to let people use installed tifffile if present, vendored tifffile otherwise, because a user asked for this and it seems like a reasonable thing to do (our vendored version is now quite old)
- tifffile was split up into a pure Python package with only zip decompression (I think), and two C packages containing codecs, imagecodecs-lite with a few codecs (including the two that you need, @kmader) and imagecodecs with lots more. These two packages don't currently provide wheels on PyPI for all platforms or conda-forge packages.
- now when users install tifffile, they can find that they cannot open files with `skimage.io` that they could before, which is counterintuitive to say the least.

@cgohlke perhaps tifffile decompression failures should suggest installing the above packages?

On the scikit-image side, a solution would be to fall back on our vendored tifffile if the packaged one fails. I think that might solve 95-99% of users' problems. @hmaarrfk what do you think about this? Actually, in general, I think it would be great if plugins were tried in preference order if they raise an error.

**Comment by hmaarrfk** [comment]
> On the scikit-image side, a solution would be to fall back on our vendored tifffile if the packaged one fails. I think that might solve 95-99% of users' problems. @hmaarrfk what do you think about this?

This is a huge feature, and likely to have many challenges in the implementation. Is this useful to include in scikit-image? Didn't we want scikit-image to be a thin wrapper over imageio?

Scikit-image releases too slowly anyway to make this a useful solution. Packaging tifffile on pypi + conda-forge is likely to come out first (well conda-forge has been trying for 1year+ now, so maybe i'm wrong).

**Comment by Czaki** [comment]
Current tifffile on windows depends on `imagecodecs` on macos it depends on `imagecodecs-lite` so all cases supported by `tifffile==0.x.x` will be handled out of box. 

Wheels for `imagecodecs` for macos and linux are build by my. All others by @cgohlke. Because of this there is difference in dependencies.

**Comment by rfezzani** [comment]
Is this issue still relevant? With #4235,  `tifffile` is no more included in `skimage`?

**Comment by hmaarrfk** [comment]
I guess it can be closed. We made the decision not to package tifffile but mearly to use the underlying user install.

@kmader If you are still facing issues, you should probably ask upstream to help you out.

If you disagree with our decision to no longer include tifffile, then you are of course, free to express your thoughts to ask us to reconsider.

**Comment by kmader** [comment]
Thanks for following up, 
I only had the problem in one project. Given the changes it seems reasonable to close it now and anyways someone will find it with a quick google search if they have the issue again
