### ISSUE TITLE
regionsprops_table is not mentioned in the doc

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4335]
We should use it in an existing example, or add a new example.

**Comment by emmanuelle** [comment]
@mkcor can be a good way to get started, writing a documentation example showing the table of props.

**Comment by jni** [comment]
Note that we probably want to add pandas to our docs dependencies for maximum effect here. =)

**Comment by mkcor** [comment]
(btw it's `regionprops_table` not `regionsprops_table`)

**Comment by mkcor** [comment]
@emmanuelle I'm not sure whether:

* I should have written a separate example script using `regionsprops_table`, instead of 'enhancing' an existing one;
* I should rebuild the docs locally and push the artifacts as part of the PR?

**Comment by mkcor** [comment]
@leGIT-bot @jni @emmanuelle Oh wow I totally didn't see #4346 -- didn't get any notification!

**Comment by emmanuelle** [comment]
great minds think alike... I think @leGIT-bot and you @mkcor starting working on this at the same time!

**Comment by emmanuelle** [comment]
@mkcor the artifacts are built automatically in the CI, we should not commit them. The part of our CI which generates the doc is https://github.com/scikit-image/scikit-image/blob/master/tools/travis/deploy_docs.sh called from https://github.com/scikit-image/scikit-image/blob/master/.travis.yml. By the way, if you find places where our `CONTRIBUTING.txt` notes could be improved, please take the time to suggest how!

**Comment by soupault** [comment]
Solved by #4356.
