### ISSUE TITLE
Bump PyWavelets min to 0.5.2

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#4373]
## Description
Currently PyWavelets 0.4 was released in Dec 2015. 

0.5.2 would give us even more than 36 months of support. The challenge with going all the way up to 1.0 is that 1.0 was only released in late 2018.

![image](https://user-images.githubusercontent.com/90008/71485079-70af1700-27dd-11ea-9702-25a8d049f7d7.png)

**Comment by grlee77** [comment]
0.5.2 should be fine. 

There are some minor simplifications possible with both 1.0 and 0.5.2 (documented in #3407), but nothing that makes it a high priority to update immediately.
