### ISSUE TITLE
Lucy Richardson return NaN value

### ISSUE THREAD

**Issue by yairif** [scikit-image/scikit-image#4378]
## Description
Hi all,
I'm using LR deconvolution for many times. unfortunately, in some cases LR return NaN value. 
I'm understand that this issue was already fixed according: #2551 #2552, but even with this change LR still give NaN value. 
I attached here an image and  psf  (pickle file), and I would like to get your help find the problem.

[image.zip](https://github.com/scikit-image/scikit-image/files/4007828/image.zip)
[psf.zip](https://github.com/scikit-image/scikit-image/files/4007830/psf.zip)

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by jni** [comment]
@yairif thanks for the report and the test data! As you can probably imagine, now is a busy time for most of our developers, but we will pick this up in the new year, as it seems like a significant bug.

Thanks again!

**Comment by yairif** [comment]
Thank you for the update.

**Comment by hmaarrfk** [comment]
@yairif thanks for opening this. I personally may not have the time to look into this issue, but it would be helpful for whoever does, if you provide them with exactly the code you used to go from:

1. A directory with the two pickle files
2. Loading and assembling the data
3. Operating on the data
4. Noticing that some entries are NaN

Finally, the output of:
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```
is very helpful for us to understand things.

**Comment by yairif** [comment]
Ok,  thanks for your comment. I will do it soon as possible.

**Comment by yairif** [comment]
Here I attached: 

- data -Image&PSF (zip file), 

- very simple code which loading the data, make RL deconvolution and plot the results.

- modules version

[image.zip](https://github.com/scikit-image/scikit-image/files/4011938/image.zip)
[psf.zip](https://github.com/scikit-image/scikit-image/files/4011939/psf.zip)

```
from zipfile import ZipFile
import numpy as np
from skimage import color, data, restoration
import matplotlib.pyplot as plt

Image = ZipFile('path_to_file/Image.zip', 'r')
Image.extractall('path_to_extract_folder')
Image.close()
Image = np.load('path_to_Image_file')

PSF = ZipFile('path_to_file/PSF.zip', 'r')
PSF.extractall('path_to_extract_folder')
PSF.close()
PSF = np.load('path_to_psf_file')

deconvolved_RL = restoration.richardson_lucy(Image, PSF, iterations=20)

fig, (ax0, ax1, ax2) = plt.subplots(1, 3)
c = ax0.pcolor(Image)
ax0.set_title('Interpulation')
c = ax1.pcolor(PSF)
ax1.set_title('psf')
c = ax2.pcolor(deconvolved_RL)
ax2.set_title('RL-deconv')
fig.tight_layout()
plt.show()
```
![RL_deconv](https://user-images.githubusercontent.com/56120502/71610964-1c6db380-2b9e-11ea-9d32-de5def06282b.png)

Matlab plot for the same input data (Image, PSF, 20 iteration)
![deconvolution](https://user-images.githubusercontent.com/56120502/71610911-c862cf00-2b9d-11ea-82af-c154efb57cd6.png)

############ version ######################
3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
Linux-4.15.0-72-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.15.0
numpy version: 1.15.2

**Comment by hmaarrfk** [comment]
I can confirm that this also occurs with modern versions of scikit-image and numpy:
```
import numpy as np
from skimage import color, data, restoration
import matplotlib.pyplot as plt

Image = np.load('path_to_file/image', allow_pickle=True)  
PSF = np.load('path_to_file/psf', allow_pickle=True)  
 
deconvolved_RL = restoration.richardson_lucy(Image, PSF, iterations=20) 
 
fig, (ax0, ax1, ax2) = plt.subplots(1, 3) 
c = ax0.pcolor(Image) 
ax0.set_title('Interpulation') 
c = ax1.pcolor(PSF) 
ax1.set_title('psf') 
c = ax2.pcolor(deconvolved_RL) 
ax2.set_title('RL-deconv') 
fig.tight_layout() 
plt.show()
```

```
3.7.6 | packaged by conda-forge | (default, Dec 27 2019, 00:09:34) 
[GCC 7.3.0]
Linux-5.3.0-24-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.16.2
numpy version: 1.17.3

**Comment by hmaarrfk** [comment]
The problem stems with exactly how the algorithm is implemented.

In the RL implementation as of `0.16.2`, these two lines are executed in a tight loop
```
        relative_blur = image / convolve(im_deconv, psf, mode='same')
        im_deconv *= convolve(relative_blur, psf_mirror, mode='same')
```
Therefore, if `image` is ever a long string of zeros,  then things do not look good since in the next iteration, you will be dividing by zero.

To fix this today, for your work, I would add a small offset to the image:

```
Image += Image.max() * 1E-5 * np.random.random(Image.shape)
Image += Image.max() * 1E-5

**Comment by hmaarrfk** [comment]
![image](https://user-images.githubusercontent.com/90008/71637797-5761fc80-2c1b-11ea-8f91-03e0ace4b746.png)

**Comment by yairif** [comment]
Yes, but this solution can be help just for this specific image, I have a
lot of images which not pass the RL deconvolution.
