### ISSUE TITLE
Bug when using the inverse of a Transform with params given as np.matrix

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4383]
```
>>> import numpy as np
>>> m = np.matrix(np.eye(3))                                                                                                                
>>> from skimage import transform as tf                                                                                                     
>>> tform = tf.EuclideanTransform(m)
>>> tf.warp(np.ones((10, 10)), tform.inverse)                                                                                                             
Traceback (most recent call last):
  File "<ipython-input-86-faf11f9a042f>", line 1, in <module>
    tf.warp(img, tform.inverse)
  File "/home/emma/code/scikit-image/skimage/transform/_warps.py", line 898, in warp
    coords = warp_coords(coord_map, output_shape)
  File "/home/emma/code/scikit-image/skimage/transform/_warps.py", line 603, in warp_coords
    tf_coords = coord_map(tf_coords)
  File "/home/emma/code/scikit-image/skimage/transform/_warps.py", line 889, in coord_map
    return inverse_map(*args, **map_args)
  File "/home/emma/code/scikit-image/skimage/transform/_geometric.py", line 594, in inverse
    return self._apply_mat(coords, self._inv_matrix)
  File "/home/emma/code/scikit-image/skimage/transform/_geometric.py", line 558, in _apply_mat
    dst[dst[:, 2] == 0, 2] = np.finfo(float).eps
IndexError: too many indices for array
```
The Error disappears when an array is passed to `EuclideanTransform` (it probably happens also for other classes of transforms).

**Comment by jni** [comment]
@emmanuelle do you think this is something we want to fix/support? Given than `np.matrix` is being deprecated anyway...

**Comment by hmaarrfk** [comment]
This is exactly the reason why np.matrix is being deprecated. I don't think we be fixing this.

**Comment by jni** [comment]
@hmaarrfk did you inadvertently leave out a "should"? "I don't think we *should* be fixing this." =) In which case I agree.

**Comment by hmaarrfk** [comment]
Nice catch.

**Comment by hmaarrfk** [comment]
I'm not sure this is a good first issue, this is actually quite esoteric and complex behavior. Catching subleties in multiple and matrix multiply is quite hard not easy for novice python programmers.

I would actually add a "won't fix" label.

**Comment by emmanuelle** [comment]
OK, given the controversy for sure it's not a good first issue :-). However, I don't know when `np.matrix` is going to disappear, the docstring just says "the class may be removed in the future". I was thinking of all the people who started doing linear algebra when this was the recommended way (like me, I caught this bug when playing around with transforms). But I won't fight a lot for this issue either.

**Comment by rfezzani** [comment]
A simple fix would be to call `np.asarray` over the input argument, but the `EuclideanTransform` [documentation](https://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.EuclideanTransform) specifies that the `matrix` argument should be an `array`. So I would not consider this issue as a bug since 3×3 list of list would also raise an error :-(

**Comment by hmaarrfk** [comment]
I think @emmanuelle's historical context is quite important. Thanks for bringing that up.

I think it is especially appropriate in the context of homographies where matricues are used to describe the physics.

**Comment by jni** [comment]
`np.asarray` works for me, if @emmanuelle wants to tackle this. It would be nice to support list-of-lists as input.
