### ISSUE TITLE
Improving preview in API gallery for "General-purpose images" 

### ISSUE THREAD

**Issue by kolibril13** [scikit-image/scikit-image#4384]
In the preview of [General-purpose images](https://scikit-image.org/docs/0.15.x/auto_examples/index.html) there is only one plot in the preview.
![123](https://user-images.githubusercontent.com/44469195/71658218-79569e80-2d43-11ea-816e-ad65f19359b2.png)
However, in the example itself, there are listed all example images.
![33](https://user-images.githubusercontent.com/44469195/71658221-7bb8f880-2d43-11ea-8eff-235ba828881c.png)
What do you think of the idea to change the multiple `figure` syntax to code with one figure and `suplots` instead? Then the preview would be more clear.

**Comment by jni** [comment]
I don't feel too strongly about this either way, but too many subplots would look very crowded in the preview...

**Comment by emmanuelle** [comment]
Yeah, four subplots could be an improvement over the existing situation but for this we would have to break the example in several sections (like natural RGB images, natural grayscale images, synthetic images...). Note that it is possible to tell sphinx-gallery which image you want to display as thumbnail.

**Comment by kolibril13** [comment]
@emmanuelle thats cool.
I created an image for the thumbnail.
![image](https://user-images.githubusercontent.com/44469195/71717882-d02ea780-2e19-11ea-9366-79429efd18ca.png)
In case that this is desired,  do you might add this?
Cause I don't have experience with sphinx.

Here is the code for it:
```py
import matplotlib.pyplot as plt
import numpy as np

from skimage import data
fig, axs = plt.subplots(nrows=3, ncols=2, tight_layout= True )
for ax in axs.flat:
    ax.axis('off');
axs[0, 0].imshow(data.astronaut())
axs[0, 1].imshow(data.binary_blobs(),cmap=plt.cm.gray)
axs[1, 0].imshow(data.brick(),cmap=plt.cm.gray)
axs[1, 1].imshow(data.colorwheel())
axs[2, 0].imshow(data.camera(),cmap=plt.cm.gray)
further_img= np.full((300,300),255)
size=10
further_img[150-size:150+size,150-size:150+size ]= 0
further_img[150-size:150+size,100-size:100+size ]= 0
further_img[150-size:150+size,200-size:200+size ]= 0
axs[2, 1].imshow(further_img,cmap=plt.cm.gray)
```

**Comment by grlee77** [comment]
Hi @kolibril13, I just came across this older issue today. It is a nice idea to add a subplot with an ellipsis. That seems a good way to indicate that there are also additional images within.

**Comment by kolibril13** [comment]
While I am on it, a similar thumbail for "Scientific images" would pe possible as well:
<img width="175" alt="image" src="https://user-images.githubusercontent.com/44469195/159553200-ffc3623d-1224-45c0-b8c3-21a68831fc39.png">
