### ISSUE TITLE
NameError: name 'regionprops' is not defined importing "skimage.measure"

### ISSUE THREAD

**Issue by mike-pt** [scikit-image/scikit-image#4397]
## Description
As the title suggests and as detailed bellow python 3.7.6 returns `NameError: name 'regionprops' is not defined when I try to import "skimage.measure"

## Way to reproduce
```
Python 3.7.6 (default, Jan  9 2020, 14:22:22) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import skimage.measure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miguelc/.virtualenvs/matp/lib/python3.7/site-packages/skimage/measure/__init__.py", line 5, in <module>
    from ._regionprops import regionprops, perimeter, regionprops_table
  File "/Users/miguelc/.virtualenvs/matp/lib/python3.7/site-packages/skimage/measure/_regionprops.py", line 963, in <module>
    _install_properties_docs()
  File "/Users/miguelc/.virtualenvs/matp/lib/python3.7/site-packages/skimage/measure/_regionprops.py", line 954, in _install_properties_docs
    prop_doc = _parse_docs()
  File "/Users/miguelc/.virtualenvs/matp/lib/python3.7/site-packages/skimage/measure/_regionprops.py", line 945, in _parse_docs
    doc = regionprops.__doc__ or ''
NameError: name 'regionprops' is not defined
```

## Version information
```
>>> from __future__ import print_function
>>> import sys; print(sys.version)
3.7.6 (default, Jan  9 2020, 14:22:22) 
[Clang 11.0.0 (clang-1100.0.33.16)]
>>> import platform; print(platform.platform())
Darwin-19.2.0-x86_64-i386-64bit
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.16.2
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.18.1
>>> 
```

**Comment by emmanuelle** [comment]
wow this is very weird. I could not reproduce on a fresh environment. Are you on a Mac? 

There seem to be a problem with our `_parse_docs` function. Since it is not called when `__debug__` is False, could you please help us diagnosing by launching a Python shell in optimized mode (`python3 -O`) and try the import again?

**Comment by soupault** [comment]
How did you install scikit-image?

**Comment by mike-pt** [comment]
Yeah I'm on a mac, and can try that, FWIW I installed with pip (this is inside a venv so not much else is there:
```
cat requirements.txt 
matplotlib
Pillow
scikit-image
```

and their deps ofc

**Comment by mike-pt** [comment]
here is the output with -O 

```
 python3 -O
Python 3.7.6 (default, Jan  9 2020, 14:22:22) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import skimage.measure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miguelc/.virtualenvs/matp/lib/python3.7/site-packages/skimage/measure/__init__.py", line 5, in <module>
    from ._regionprops import regionprops, perimeter, regionprops_table
ImportError: cannot import name 'regionprops' from 'skimage.measure._regionprops' (/Users/miguelc/.virtualenvs/matp/lib/python3.7/site-packages/skimage/measure/_regionprops.py)
```

**Comment by emmanuelle** [comment]
Hum... can you check that file `/Users/miguelc/.virtualenvs/matp/lib/python3.7/site-packages/skimage/measure/_regionprops.py` has a `regionprops` function? There's no reason why it shouldn't, though... Did you also try from a completely fresh environment? Quite generic questions I'm afraid but I'm having a hard time understanding what's going on...

**Comment by mike-pt** [comment]
this is a fresh venv but I can create another with just the single dep.... you never know

**Comment by mike-pt** [comment]
ah interesting with just that it works fine, tbh the other I need seem to be deps of this anyway, maybe there's some sort of conflit if I try to install matplotb or Pillow too?

**Comment by emmanuelle** [comment]
maybe conflicting versions but still why would the error message be an import error in a submodule of scikit-image? Anyway, any diagnosis you can bring here will be useful for us, so if you can tell us which one of the other packages causes the conflicts we are all ears. Thanks!

**Comment by mike-pt** [comment]
Gonna try experimenting see if I can isolate it, It could also be a rare case of a bad download (when I got this issue was actually yesterday but I had no time to post)

**Comment by mike-pt** [comment]
hum with the same requiremts file it simply just said all deps are satisfied, I tried on a yet a newer one and also no issues now, it does take a little to load the module (like 3 secs?) but I guess its just cause its a bit complex?

But I can no longer repo the original issue and yet the function was there

**Comment by mike-pt** [comment]
Well, I think the best I can do for now is keep an eye if it happens again. 

Yesterday I created to new venvs and both failed 🤷‍♂

**Comment by emmanuelle** [comment]
ok great, then I'll close and as you say feel free to reopen if needed. Happy image processing ;-) !
