### ISSUE TITLE
Stop probability in ransac

### ISSUE THREAD

**Issue by durveshps** [scikit-image/scikit-image#4403]
## Description

This may be a stupid question, but what is 'm' in the formula for dynamic number of trials in documentation of RANSAC?

https://github.com/scikit-image/scikit-image/blob/b7a1fde540d90d6e8009764abeec3e89c8b76928/skimage/measure/fit.py#L691

**Comment by sciunto** [comment]
Cc @ahojnnes

**Comment by sciunto** [comment]
This must be clarified in the docstring. The computation is done in another function and the corresponding line is https://github.com/scikit-image/scikit-image/blob/b7a1fde540d90d6e8009764abeec3e89c8b76928/skimage/measure/fit.py#L606

m is the min sample.

**Comment by sciunto** [comment]
Thank you @durveshps This type of issues is particularly useful to improve our documentation. It is now fixed in master.

**Comment by durveshps** [comment]
Thanks @sciunto for answering my question and incorporating the information in the Doc-Strings.
