### ISSUE TITLE
API: disk vs circle vs circle_perimeter

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4406]
## Description

In [morphology](https://scikit-image.org/docs/stable/api/skimage.morphology.html#disk) disk means a full circle
In [Hough transform](https://scikit-image.org/docs/stable/api/skimage.transform.html#hough-circle) circle means the edge of a circle
In [draw.circle](https://scikit-image.org/docs/stable/api/skimage.draw.html#circle) means a full circle
In [draw.circle_perimeter](https://scikit-image.org/docs/stable/api/skimage.draw.html#circle-perimeter) and [draw.circle_perimeter_aa](https://scikit-image.org/docs/stable/api/skimage.draw.html#circle-perimeter_aa) circle perimeter means the edge of a circle.
In [measure circleModel](https://scikit-image.org/docs/stable/api/skimage.measure.html#circlemodel), circle means edge of a circle
In [measure circle_level_set ](https://scikit-image.org/docs/stable/api/skimage.segmentation.html#circle-level-set) circle is a full circle.

I admit this can be disturbing.

I recommend to rename
* [x] draw.circle -> draw.disk (#4428)
* [ ] draw.circle_perimeter -> draw.circle
* [ ] draw.circle_perimeter_aa -> draw.circle_aa
* [x] skimage.segmentation.circle_level_set -> skimage.segmentation.disk_level_set (#4421) 

In my mind, disk = circle filled up with pixels, circle = mathematical line.

What do you think @scikit-image/core

**Comment by jni** [comment]
@sciunto I'm :+1: on this proposal! Great catch(es)!

**Comment by hmaarrfk** [comment]
How will you handle the deprecation cycle for the new circle? Will you do it in a single shot or two?

**Comment by alexdesiqueira** [comment]
Great catches indeed @sciunto, one more step for our consistency!

**Comment by sciunto** [comment]
@hmaarrfk Good question. The number/type of arguments for the new disk and the new circle functions are the same. Therefore, it's hard to detect users who have an outdated code, embarrassing for a single shot.

I would suggest:
* Step 1: warn that draw.circle is deprecated. Implement draw.disk. (For 2 versions).
* Step 2: move the code in draw.circle_perimeter in draw.circle. Deprecated the old function. (For 2 versions).

I think this will give the best user experience.

**Comment by hmaarrfk** [comment]
See PR https://github.com/scikit-image/scikit-image/pull/4462 por favor! Which addresses a few warnings introduced by the first few PRs.

**Comment by stefanv** [comment]
What is the plan for implementing perimeter drawing now?

**Comment by hmaarrfk** [comment]
I think it is:
1. Keep the status quo until 2021
2. In 2021 deprecate circle_perimeer in favor of circle

**Comment by alexdesiqueira** [comment]
> See PR #4462 por favor!

I guess this one was written specifically for me :)

**Comment by stefanv** [comment]
> I think it is:
> 
>     1. Keep the status quo until 2021
> 
>     2. In 2021 deprecate circle_perimeer in favor of circle

And, there will be a keyword parameter on `circle`?

**Comment by lagru** [comment]
Hey, what's the state on this? Is the transition "circle_perimeter -> circle" still something we care about? It's not something that seems very important to me.

And in any case, none of these issues seem like they require a skimage2-level API break. I'll remove it from milestone and project for now and close the issue. Please reopen if necessary. :wink:

**Comment by soupault** [comment]
Given the existence of `skimage.draw.polygon_perimeter`, `ellipse_perimeter`, and `rectangle_perimeter`, I think it is fine to keep the current API. The most important proposed changes have already been made.
