### ISSUE TITLE
Azure build for documentation is failing (times out)

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4408]
See for example https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=2301&view=logs&jobId=31eb6c88-23c5-50ae-eda4-a7f72508e1eb&j=31eb6c88-23c5-50ae-eda4-a7f72508e1eb&t=f7291549-81f8-5748-7064-2be81963872c: the build takes 60 minutes, is stopped, does not respond and is killed.

**Comment by jni** [comment]
This is the relevant part of the azure config file:

https://github.com/scikit-image/scikit-image/blob/b46a4961157510eb395028cd9b6cf8739cedb7c2/azure-pipelines.yml#L121-L132

Nothing amazingly suspicious there!

**Comment by jni** [comment]
@emmanuelle found this log of a working build. Amazingly, it looks like Azure should print stuff to the console before anything at all is run, but it is no longer doing this...

https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=2259&view=logs&jobId=97a3063c-824d-5691-874a-4213ba287284&j=31eb6c88-23c5-50ae-eda4-a7f72508e1eb&t=f7291549-81f8-5748-7064-2be81963872c

**Comment by jni** [comment]
@soupault @hmaarrfk if you have any ideas here, they would be much appreciated! In the meantime, @emmanuelle is going to experiment with a dummy PR.

**Comment by soupault** [comment]
That's really weird! You are right that Azure typically outputs the script lines before executing them. It looks like the workers cannote even start a Bash session for the failing task. I am investigating the logs now.

**Comment by soupault** [comment]
Here is an interactive output of the restarted job:
![image](https://user-images.githubusercontent.com/1315589/73090875-e512ce00-3ee1-11ea-8f67-0fdc53210420.png)

**Comment by soupault** [comment]
The issue `Input file specified two times.` is caused by this line https://github.com/scikit-image/scikit-image/blob/master/doc/Makefile#L50 . Removing `release_notes` target solves the issue. There seems to be some difference in the syntax of the used commands on Windows.

**Comment by soupault** [comment]
Indeed, it uses `sort` function from https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sort .
