### ISSUE TITLE
Dead "chat room" link on the "Governance" page

### ISSUE THREAD

**Issue by tjorda01** [scikit-image/scikit-image#4425]
Describe the issue linked to the documentation
On this page: https://scikit-image.org/docs/dev/skips/1-governance.html
...there this dead link:
project chat room,

Suggest a potential alternative/fix
Is there still an active chat room? If not, remove the reference to it.

**Comment by emmanuelle** [comment]
Thanks @tjorda01 the right link is https://skimage.zulipchat.com/. Would you like to make a pull request for this? Thanks again.

**Comment by aadideshpande** [comment]
I would like to work on this issue.

**Comment by aadideshpande** [comment]
#4432

**Comment by soupault** [comment]
Fixed in #4432 .
