### ISSUE TITLE
Dead link in “Canny edge detection”

### ISSUE THREAD

**Issue by tjorda01** [scikit-image/scikit-image#4426]
### Describe the issue linked to the documentation
On this page “Canny edge detection”
https://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.canny
... in the References section, this is the dead link:
"2 William Green’s Canny tutorial" http://dasl.unlv.edu/daslDrexel/alumni/bGreen/www.pages.drexel.edu/_weg22/can_tut.html

### Suggest a potential alternative/fix
Replace it with this updated Canny tutorial link:
http://www.pages.drexel.edu/~nk752/Research/cannyTut2.html

**Comment by emmanuelle** [comment]
Thanks @tjorda01 another solution is to just remove this link because it could be moved again. We could instead link to the wikipedia page https://en.wikipedia.org/wiki/Canny_edge_detector

**Comment by aadideshpande** [comment]
I would like to work on this issue.

**Comment by aadideshpande** [comment]
#4433

**Comment by soupault** [comment]
FIxed in #4433 .
