### ISSUE TITLE
Add multichannel to denoise_tv_bregman

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4427]
`skimage.restoration.denoise_tv_bregman` is I think the only denoising function which does not accept a `multichannel` argument. I hope it would be easy to adapt code from other denoising functions (for example `denoise_tv_chambolle`), so I'm tagging this as good first issue.

**Comment by rfezzani** [comment]
Fixed by #4446, thank you @erjel :tada:
