### ISSUE TITLE
Add examples to docstring for structuring elements to visualize the shape

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4431]
## Description

Add examples to show for each of these functions:

* [ ] skimage.morphology.square(width[, dtype])
* [ ] skimage.morphology.rectangle(width, height)
* [ ] skimage.morphology.diamond(radius[, dtype])
* [ ] skimage.morphology.disk(radius[, dtype])
* [ ] skimage.morphology.cube(width[, dtype])
* [ ] skimage.morphology.octahedron(radius[, dtype])
* [ ] skimage.morphology.ball(radius[, dtype])
* [ ] skimage.morphology.octagon(m, n[, dtype])
* [ ] skimage.morphology.star(a[, dtype])

the typical shape of the structuring element.

Cc ( @emmanuelle : another first issue idea).

**Comment by 07harshita** [comment]
Hi!
I would love to work on this issue.

**Comment by emmanuelle** [comment]
Hi @07harshita that's great to hear! Don't hesitate to submit a work in progress pull request with for example just one example in one function, if you want some early feedback to be sure that you're on the right track.

**Comment by b-z** [comment]
Hello :)
I created a PR, which has an example code for visualizing the above functions.
I didn't not docstring, because some results can be very unintuitive if using an array to show the results, such as:
```python
>>> ball(1)
array([[[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]], dtype=uint8)
```
And it's better to use a figure.
