### ISSUE TITLE
Feature suggestion: passing user-defined measurement functions to regionprops

### ISSUE THREAD

**Issue by VolkerH** [scikit-image/scikit-image#4466]
I have encountered the following pattern a number of times now:

1. I segment objects and calculate regionprops and export them to a table. `regionprops_table`) already facilitates this workflow. This is often done because users at our microscopy facility ask me to write a script that calculates these features from images.
2. The users sometimes want to measure some additional property that  is not implemented in scikit-image, say for example minimum Feret diameter. What I end up doing is writing a function that calculated this property and then implementing a loop over all regions to calculate the desired feature and then somehow concatenate the results from `regionprops` (or `regionprops_table`) with the results from my own loop over the regions.  

The desired behaviour would be to only have `regionprops{_table}`loop once over all regions and have a single output table returned. 
I envisage being able to pass an optional argument to `regionprops{_table}` such as
```
additional_measurements =( (prop1_func, prop1_name, prop1_return_dtype),   (prop2_func, prop2_name, prop2_return_dtype), ... )
```

Where `prop*_func` is a function that calculates the property given a region, `prop*_name` is the name of the property and `prop*_return_dtype` specifies what one would expect the function to return as output.

Other than just looping over the regions once, this would allow 3rd-party measurement functions that may be too specific (or not of high enough code quality, or only working for a specific number of dimensions) to include in the skimage code base to be distributed separately.

Does this make sense?

**Comment by jni** [comment]
I think this is a great idea! I don't love the proposed API, but I definitely think we can come up with an API I'm happy with. =)

**Comment by rfezzani** [comment]
Yes, that's cool ;-). I would prefer the optional argument to be of the form `extra={'name1': func1, ...}` without caring about return dtype but it looks like a great suggestion :+1:.

**Comment by VolkerH** [comment]
The API can be different, this was just a quick sketch of one option, I care more about having the functionality. Another option would be to have a function such as

```
register_measurement(func, name, ...)
```
and after registering one or many additional measurements like this they can just be used using the existing `regionprops` or `regionprops_table` functions.

**Comment by jni** [comment]
@VolkerH re: registering, I really do like the idea of arbitrary regionprops plugins. We could reuse the strategy from napari/napari#908, or more lightweight, something like our io plugins.

@rfezzani as currently implemented, the dtype is important because it specifies whether the property in the table is stored as an object or as one or more numeric types. e.g. the property `.image` has a different size for each region, so you need to use an object array for that column. etc.

**Comment by VolkerH** [comment]
As long as it is easy for the end-user to register a measurement function (as in: does not require reading a lengthy tutorial but simply cutting and pasting some example code). I haven't looked at pluggy yet so can't say whether it fits the bill.

**Comment by GenevieveBuckley** [comment]
I think registering measurement functions is likely to introduce more complexity than the average user is willing to deal with. I'm +1 for passing in custom functions like Volker suggests.

**Comment by VolkerH** [comment]
This feature has been added via https://github.com/scikit-image/scikit-image/pull/4810

Closing.
