### ISSUE TITLE
Add a link to forum at the bottom of gallery examples

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4488]
In order to increase participation to the Image.sc forum, we could add a footer in example pages saying "We hope that this example was useful. If you have question unanswered by our documentation, you can ask them on the Image.sc forum...".

I wonder what the best technical solution for this would be; either defining an html template for gallery pages (I think we're using the same for all pages of the website at the moment?), or at the rst level (I'm just not sure this can be done without hacking sphinx-gallery). Thoughts?

**Comment by jni** [comment]
I love this idea as you already know! Different html template seems the way to go.

**Comment by mingxiang1006** [comment]
Hi, where could I find the src code for this?

**Comment by emmanuelle** [comment]
The templates to define the layout of html pages are in https://github.com/scikit-image/scikit-image/tree/master/doc/source/themes/scikit-image (`layout.html`). I think it's better to have some previous experience with sphinx or web development to work on this issue.

**Comment by lagru** [comment]
@mingxiang1006 If you want to work on this, a good starting point might be the [Jinja documentation](https://jinja.palletsprojects.com/en/2.11.x/templates/) which is the templating syntax used in `layout.html`.  Feel free to reach out if you have any questions!
