### ISSUE TITLE
Possibility to have ellipses in random shapes

### ISSUE THREAD

**Issue by zaccharieramzi** [scikit-image/scikit-image#4491]
## Description

It could be interesting to have the possibility to draw random ellipses when using the [`random_shapes` function](https://scikit-image.org/docs/dev/auto_examples/edges/plot_random_shapes.html).
Random ellipses are often used as a toy example for different research papers, e.g.:
- https://arxiv.org/abs/2001.01258
- https://arxiv.org/abs/1707.06474

I can definitely try and submit a PR for this.

**Comment by emmanuelle** [comment]
Hi @zaccharieramzi ! Thanks for proposing to implement this feature, this would indeed be a useful addition.
