### ISSUE TITLE
Documentation doesn't build with Python 3.8

### ISSUE THREAD

**Issue by olebole** [scikit-image/scikit-image#4492]
## Description

Since a few days, the default Python for Debian "unstable" is Python 3.8, which also means that we use this version to build the documentation.

However, when trying to run sphinxdoc, we run into the following failure:
```
[…]
build succeeded, 146 warnings.

The HTML pages are in build/html.

Exception occurred:
  File "/usr/lib/python3/dist-packages/sphinx_gallery/gen_gallery.py", line 311, in sumarize_failing_examples
    raise ValueError("Here is a summary of the problems encountered when "
ValueError: Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/home/oles/Projects/2011/debian/python/skimage/doc/examples/features_detection/plot_hog.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/oles/Projects/2011/debian/python/skimage/doc/examples/features_detection/plot_hog.py", line 1
    ===============================
    ^
SyntaxError: invalid syntax
[…]
The full traceback has been saved in /tmp/sphinx-err-tw7kje7q.log, if you want to report the issue to the developers.
```
The `SyntaxError` repeats for other example files in `doc/examples`. The full traceback 
[sphinx-err-tw7kje7q.log](https://github.com/scikit-image/scikit-image/files/4293603/sphinx-err-tw7kje7q.log) is attached, but not really more enlighting.

This was also reported as [Debian#951768](https://bugs.debian.org/951768).

With Python 3.7, it works fine, I have no idea whether this is a problem to scikit-image or one of the involved packages, or Python 3.8; however I couldn't find another package with the same problem.

## Way to reproduce

Run `sphinx-build` with Python 3.8.

## Version information

```
3.8.2 (default, Feb 25 2020, 13:04:52) 
[GCC 9.2.1 20200220]
Linux-5.3.0-2-amd64-x86_64-with-glibc2.29
scikit-image version: 0.16.2
numpy version: 1.17.4
sphinx version: 1.8.5
sphinx_gallery version: 0.2.0
matplotlib_version: 3.1.2
```

**Comment by hmaarrfk** [comment]
I guess they don't like the top equal bar

**Comment by tacaswell** [comment]
My guess is you need to update sphinx gallery, I think this a version of https://github.com/sphinx-gallery/sphinx-gallery/issues/442 which looks like you need at least sg 0.3.0 to get the fix for.

**Comment by sciunto** [comment]
thanks @tacaswell
