### ISSUE TITLE
Key error when using skimage.measure.find_contours

### ISSUE THREAD

**Issue by robbibt** [scikit-image/scikit-image#4497]
## Description
I am using `skimage.measure.find_contours` to extract a large number of contours from a time-series of satellite imagery represented as `numpy.arrays`. Although this works perfectly for almost all my arrays, I am receiving a `KeyError` when `skimage.measure.find_contours` is applied to certain arrays, even though I can't see anything obviously different about these layers.

My original datasets are approximately 2000 x 2000 pixels in size, with values in `float32` ranging between -1.0 and 1.0 and containing `NaN`. I have isolated the problem area down to a small 100 x 100 pixel section of the problematic array (attached as a [zip file below](https://github.com/scikit-image/scikit-image/files/4295788/array.zip)):

![image](https://user-images.githubusercontent.com/17680388/76038049-bf76eb00-5f9c-11ea-814a-140acfcc03fd.png)

## Way to reproduce

Download and unzip 100 x 100 numpy array (`array.npy`): [array.zip](https://github.com/scikit-image/scikit-image/files/4295788/array.zip)

```python
import numpy as np
from skimage.measure import find_contours

# Load numpy array 
array = np.load('array.npy')
find_contours(array, 0)
```
Error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-de11203f72d2> in <module>
      3 
      4 array = np.load('array.npy')
----> 5 find_contours(array, 0)

/g/data/v10/public/modules/dea-env/20191127/lib/python3.6/site-packages/skimage/measure/_find_contours.py in find_contours(array, level, fully_connected, positive_orientation, mask)
    133                                                      fully_connected == 'high',
    134                                                      mask=mask)
--> 135     contours = _assemble_contours(_take_2(point_list))
    136     if positive_orientation == 'high':
    137         contours = [c[::-1] for c in contours]

/g/data/v10/public/modules/dea-env/20191127/lib/python3.6/site-packages/skimage/measure/_find_contours.py in _assemble_contours(points_iterator)
    199                     tail.extendleft(reversed(head))
    200                     # remove all traces of head:
--> 201                     del starts[head[0]]
    202                     del ends[from_point]
    203                     del contours[head_num]

KeyError: (9, 6.0)
```

## Version information

```python
3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0]
Linux-2.6.32-754.18.2.el6.x86_64-x86_64-with-centos-6.10-Final
scikit-image version: 0.16.2
numpy version: 1.17.3

```

**Comment by jni** [comment]
@robbibt Thank you for reporting this, and thanks especially for providing such minimal data and a code snippet! I can indeed reproduce locally, and it looks like a pretty nasty bug. We'll investigate. (The cause does not immediately jump out at me.)

**Comment by robbibt** [comment]
Thanks @jni. In case it helps with bug finding, I've found that the error does not occur if `fully_connected='high'` is specified instead of the default:

import numpy as np
from skimage.measure import find_contours

```
# Load numpy array 
array = np.load('array.npy')
find_contours(array, 0, fully_connected='high')
```

**Comment by rfezzani** [comment]
Looks like it's related to #817.

**Comment by rfezzani** [comment]
#4505 fixes this issue by performing dictionary values deletion using `dict.pop` instead of `del`.
