### ISSUE TITLE
saving a np.uint64 to png removes (low contrast) image content

### ISSUE THREAD

**Issue by psteinb** [scikit-image/scikit-image#4509]
## Description

I was trying to save an image to a png file. It appeared to me that `imsave` removed the content of this image. I am by means no expert with libpng, but that data is lost completely appears like a bug to me. Note for the following, when starting from `np.float64`, the problem does not appear. 

I had to dig down this route as I used some code that did `np.sum([np.uint8-array, np.uint8-array])` which gave an `np.ndarray` with `np.uint64` in the first place.

## Way to reproduce

```python
import numpy as np
from skimage.io import imsave, imread
img = np.zeros((32,32),dtype=np.uint64
img[8:24,8:24] = 1
imsave("test.png",img)
#this issue the usual warning 
#__main__:1: UserWarning: test.png is a low contrast image
#Lossy conversion from uint64 to uint8. Losing 56 bits of resolution. Convert image to uint8 prior to #saving to suppress this warning.
rimg = imread('test.png')
print(rimg.sum()) #Yikes, this prints 0
```
![test.png](https://user-images.githubusercontent.com/1465603/76629234-40eef000-653e-11ea-8264-0b0382b108f0.png)
![expected](https://user-images.githubusercontent.com/1465603/76629390-7d225080-653e-11ea-83aa-9f03fa9d1346.png)

## Version information
```python
>>> import sys; print(sys.version)
3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0]
>>> import platform; print(platform.platform())
Linux-5.5.8-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.16.2


>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.17.2
```

**Comment by rfezzani** [comment]
Thank you @psteinb for reporting this, but this is the expected result, and that's what the raised warning says :-(

**Comment by psteinb** [comment]
true, but I see no reason why that should be. I have `0` and `1` intensities inside the `np.ndarray`. Why should they be gone? These 8 bits fit can just be cropped from 64 and everything would be fine.

**Comment by rfezzani** [comment]
`scikit-image` uses `imageio` internally, and it produces the same exact behavior:
```python
>>> import imageio
>>> img = np.zeros((32,32),dtype=np.uint64)
>>> img[8:24,8:24] = 1
>>> imageio.imsave("/tmp/test.png", img)
Lossy conversion from uint64 to uint8. Losing 56 bits of resolution. Convert image to uint8 prior to saving to suppress this warning.
>>> rimg = imageio.imread('/tmp/test.png')
>>> print(rimg.sum()) #Yikes, this prints 0
0
```
I agree, this can be surprising :no_mouth:. 
A workaround is to determine the minimum data type fitting your data before saving it as image:
```python
out_dtype = np.result_type(np.min_scalar_type(img.max()), np.min_scalar_type(img.min()))
imageio.imsave("/tmp/test.png", img.astype(out_dtype))
```

**Comment by psteinb** [comment]
Thanks for providing this 'workaround'. I'll close this for now.

**Comment by rfezzani** [comment]
@psteinb, I opened the #4510 PR including the proposed workaround.

**Comment by rfezzani** [comment]
Closing again, please see https://github.com/scikit-image/scikit-image/pull/4510#issuecomment-599383504
