### ISSUE TITLE
ValueError raised when bool array saving with imageio plugin

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#4511]
## Description

A `ValueError` is raised when attempting to save a bool array using the 'imageio' plugin

## Way to reproduce

```python
>>> from skimage import io
>>> a = np.ones((5, 5), bool)
>>> io.imsave('/tmp/test.png', a, 'imageio')
__main__:1: UserWarning: /tmp/test.png is a low contrast image
__main__:1: UserWarning: /tmp/test.png is a boolean image: setting True to 1 and False to 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".conda/envs/skimage-debug/lib/python3.6/site-packages/skimage/io/_io.py", line 131, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "conda/envs/skimage-debug/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "conda/envs/skimage-debug/lib/python3.6/site-packages/imageio/core/functions.py", line 293, in imwrite
    raise ValueError("Image is not numeric, but {}.".format(imt.__name__))
ValueError: Image is not numeric, but ndarray.
```
## Version information

```python
>>> from __future__ import print_function
>>> import sys; print(sys.version)
3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0]
>>> import platform; print(platform.platform())
Linux-4.4.0-174-generic-x86_64-with-debian-stretch-sid
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.16.2
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.18.1
```

**Comment by hmaarrfk** [comment]
I'm not sure this is something we should be focusing on. Bool supportive quite bad, and might give non sensical images.

Not many file formats truelu support it, and it isn't any more computationally effecient in many computing architectures.

Again, this is good to discuss in the broader sense, but I wouldn't jump for an ad hoc fix quite yet.

**Comment by rfezzani** [comment]
My main concern here is that a warning is raised `__main__:1: UserWarning: /tmp/test.png is a boolean image: setting True to 1 and False to 0`, but what it stipulate is not made...

**Comment by rfezzani** [comment]
Btw, xref your https://github.com/scikit-image/scikit-image/issues/3331#issuecomment-411820482, I agree with you concerning the 'convenience functions'. I would be OK for moving such function to `scikit-image-contrib` as I already proposed for the `skimage.viewer` module https://github.com/scikit-image/scikit-image/issues/4081#issuecomment-599152032

**Comment by hmaarrfk** [comment]
Png seems to support 1 bit pallet grayscale. This should really be brought up downstream with imageio. Keeping support for all types of back ends is a huge burden. I would rather reduce the barrier for people bringing on new backends rather than checking edge cases for backends.

**Comment by rfezzani** [comment]
I don't understand how a one line fix can hurt...

**Comment by jni** [comment]
@hmaarrfk I think, based on the wording of the warning, that this code predates from our imageio plugin days, maybe actually it comes from when freeimage was our default plugin.

@rfezzani I think what @hmaarrfk is concerned about is that now, if users encounter this error, they will be forced to convert the image by hand, and they will thus remember that the saved image contains integers, not bools, and they might have a chance to remember to convert it back upon reading. Warnings, though sometimes useful, tend to get ignored.

My suggestion is the following:

- do the conversion with a warning, but,
- change the wording of the warning to say, "to silence this warning, convert the image to uint8 format manually".

Having said this, if png supports saving boolean images, perhaps @hmaarrfk is right that we should push for a fix there. It is better to be able to round-trip including the dtype...

**Comment by sciunto** [comment]
I like @jni's suggestion. How about applying this + opening an issue in imageio adksing for 1 bit png support?

**Comment by rfezzani** [comment]
Thank you @sciunto for the ping, I somehow forgot about this issue :worried:. I updated the associated PR ;-)
