### ISSUE TITLE
Specify that rgb2lab function is relative only to sRGB colorspace

### ISSUE THREAD

**Issue by giacomomarchioro** [scikit-image/scikit-image#4514]
## Description
Hi all,
I think it should be written in the docstring of the rgb2lab function that the function is relative to sRGB colourspace, there are many color spaces used normaly (e.g. Adobe1988, ECI_rgb_v2...).  Otherwise, the user has to go in the source code to understand what colour space it's using.

## Way to reproduce
```python
from skimage.color import rgb2lab
help(rgb2lab)
```

## Version information
3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Darwin-15.3.0-x86_64-i386-64bit
scikit-image version: 0.15.0
numpy version: 1.17.3

```python

rgb2lab(rgb, illuminant='D65', observer='2')
    RGB to lab color space conversion.
```

I would expect something like this in the documentation. 

> Conversion from the sRGB color space (IEC 61966-2-1:1999 ) to the CIE Lab colorspace under the given illuminant and observer.
> 
> Note: RGB is a device-dependent color space so, if you use this function, be sure that the image you are analyzing has been mapped to the sRGB color space.

**Comment by alexdesiqueira** [comment]
Hey @giacomomarchioro,
thank you for reaching out! I noticed that the documentation contains these notes:
```
    References
    ----------
    .. [1] https://en.wikipedia.org/wiki/Standard_illuminant

    Notes
    -----
    This function uses rgb2xyz and xyz2lab.
    By default Observer= 2A, Illuminant= D65. CIE XYZ tristimulus values
    x_ref=95.047, y_ref=100., z_ref=108.883. See function `get_xyz_coords` for
    a list of supported illuminants.
```
Isn't this info sufficient to describe the color space?
Thank you again!

**Comment by giacomomarchioro** [comment]
Hello @alexdesiqueira  I don't think is sufficient. What is written is just the observer angle, the  normalized XYZ tristimulus values  of the illuminant D65. Color spaces are more complicated. For instance in mycase I have images in Adobe1998 color space so there is another way to convert them to XYZ coordinates. It should be stated somewhere that this is sRGB to XYZ conversion. sRGB is a colorspace while RGB is not and is not possible to map it to XYZ coordinates.
I hope it helps!
Thanks a lot for your quick reply!

**Comment by alexdesiqueira** [comment]
Hey @giacomomarchioro,
thank you for clarifying! Would you like to submit a pull request fixing this? Please take a look on [our contributor's guide](https://scikit-image.org/docs/dev/contribute.html) :)
Thanks again!

**Comment by cedarfall** [comment]
I would like to take this for the sprint!

**Comment by emmanuelle** [comment]
Great! If you're not there already, we're chatting on zulip https://skimage.zulipchat.com/#narrow/shatream/176555-sprint if you need rapid feedback about anything.
