### ISSUE TITLE
Image color deconvolution tutorial

### ISSUE THREAD

**Issue by asmagen** [scikit-image/scikit-image#4532]
I have followed the image deconvolution tutorial [here](https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_ihc_color_separation.html#sphx-glr-auto-examples-color-exposure-plot-ihc-color-separation-py) and got the following outputs for which I'm not sure how to proceed to save an image file with only the color intensities corresponding to the DAB only. The goal in my analysis is to identify positive marker pixels so I used the non-deconvoluted image as input to an pixel classifier ML module, but the accuracy is poor probably because of the Hematoxylin intensities which I would like to remove or reduce.
How is that possible?
<img width="1284" alt="Screen Shot 2020-03-26 at 11 09 01 AM" src="https://user-images.githubusercontent.com/11299568/77667477-a25c8900-6f58-11ea-84bf-db31f82c2eb4.png">
<img width="397" alt="Screen Shot 2020-03-26 at 11 11 20 AM" src="https://user-images.githubusercontent.com/11299568/77667486-a4bee300-6f58-11ea-9756-8e21afdee778.png">

**Comment by soupault** [comment]
@asmagen this is a skimage development tracker. For general questions on the library use, please, consider posting to https://forum.image.sc/tag/scikit-image.

Above said, in the example you referred to, `ihc_hed[:, :, 2]` is the image you are looking for. You can save it, for example, using `skimage` - `skimage.io.imsave('test.png', ihc_hed[:, :, 2])` or `matplotlib` - `plt.imsave('test.png', ihc_hed[:, :, 2], cmap=plt.cm.gray)`.

**Comment by asmagen** [comment]
How do I get the common representation of grayscale 0-255 without saving and loading again?
