### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage' for OSX

### ISSUE THREAD

**Issue by marimeireles** [scikit-image/scikit-image#4533]
## Way to reproduce
I've tried in two different ways, both failed.
First I installed scikit-image with `pip3 install scikit-image` inside a virtual environment which was using pyenv's python 3.6.8.
Then I tried by creating a conda environment with `conda install -c conda-forge scikit-image` using the python that comes with conda version 3.8.2 and also didn't work.

Both times I get the same error when trying to execute code in a jupyter notebook:
```
ModuleNotFoundError: No module named 'skimage'
```

I had the same problem in my Arch linux which I fixed by installing the AUR [package](https://aur.archlinux.org/packages/python-scikit-image/) `python-scikit-image`, I saw similar solutions for Ubuntu, etc. But there is no such package in brew.
I feel like I'm missing something stupid here... But who knows, might be a real bug.

Let me know if I can help with anything.
Thanks, cheers!

**Comment by soupault** [comment]
Hi,

- Do you have pyenv/conda properly configured to change the environment variables?
- Did you activate the right conda environment before starting the notebook server?
- Are you running the notebook server from a directory with Python modules?

This code has to work:
```Bash
conda create --name test python=3.7 -y
conda install scikit-image ipython -y
mkdir exp
cd exp
conda activate test
jupyter notebook
```

**Comment by hmaarrfk** [comment]
I think you want to make sure that jupyter is also installed in your venv / conda environment.

OTherwise, the command `jupyter` could refere to `jupyter` in an other environment.

Can you provide us the output of `pip list` or `conda list` to help debug?

**Comment by jni** [comment]
@marimeireles did the above suggestions help? I suspect @sciunto and @hmaarrfk's suspicion is correct, that you are starting jupyter from a different environment to the one in which you installed scikit-image.

**Comment by marimeireles** [comment]
Hi! Thank you all for the answers!

No it didn't. Neither in my environment created with `virtualenv` nor with the steps given by @soupault.
Same output for both cases
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0cb68e743b12> in <module>
----> 1 from pyxelate import Pyxelate
      2 from skimage import io
      3 import matplotlib.pyplot as plt
      4 
      5 img = io.imread("1.png")

~/Development/pyxelate/pyxelate.py in <module>
      2 import warnings
      3 
----> 4 from skimage.color.adapt_rgb import adapt_rgb, each_channel
      5 from skimage.util import view_as_blocks
      6 from skimage.morphology import square, dilation

ModuleNotFoundError: No module named 'skimage'

```

>Do you have pyenv/conda properly configured to change the environment variables?

What do you mean by that?

> Did you activate the right conda environment before starting the notebook server?

Yes, both in my setup and now following yours.

> Are you running the notebook server from a directory with Python modules?

There are python modules inside the `env` directory created by my `virtualenv`, but I just `rm rf` my environment and tested again and it's still the same! 

Thanks again.

**Comment by hmaarrfk** [comment]
Hey thanks for the followup, I guess that my question probably got lost in a few followups, could you provide us the the output of 

1.  `python --version`
2. `pip list`
3. `which ipython`

It would help us get to the bottom of things I think.

**Comment by jni** [comment]
`which jupyter` is also good before running jupyter. This tells us whether the jupyter you are running is the one in the newly created virtualenv, or whether it is from some other location. If it is a different one, then it will not have accessed to your newly-installed skimage. You need to install *both* skimage and jupyter in the same virtualenv, and then make sure you run *that* jupyter.

**Comment by Genius-farmer** [comment]
Hello, I have an issue after following this.

conda create --name test python=3.7 -y
conda install scikit-image ipython -y
mkdir exp
cd exp
conda activate test
jupyter notebook


Instead of test, i actually use "tensorflow" because i initially have installed tensorflow for my virtual environment.
However, i think the system replaced my initial set-up that i followed from another video to download tensorflow and it seems like i can't start my jupyter notebook now. It says "command not found: jupyter"

Initially i did it with "test" and also couldn't start up jupyter notebook. It says "command not found: jupyter"

Please assist if possible.

**Comment by Genius-farmer** [comment]
(base) ➜  ~ python --version
Python 3.8.5
(base) ➜  ~ pip list
Package                Version
---------------------- -------------------
appnope                0.1.2
backcall               0.2.0
brotlipy               0.7.0
certifi                2020.12.5
cffi                   1.14.3
chardet                3.0.4
cloudpickle            1.6.0
conda                  4.9.2
conda-package-handling 1.7.2
cryptography           3.2.1
cycler                 0.10.0
cytoolz                0.11.0
dask                   2021.1.1
decorator              4.4.2
idna                   2.10
imagecodecs            2021.1.11
imageio                2.9.0
ipython                7.19.0
ipython-genutils       0.2.0
jedi                   0.18.0
kiwisolver             1.3.0
matplotlib             3.3.2
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
networkx               2.5
numpy                  1.19.2
olefile                0.46
parso                  0.8.1
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.1.0
pip                    20.2.4
prompt-toolkit         3.0.8
ptyprocess             0.7.0
pycosat                0.6.3
pycparser              2.20
Pygments               2.7.4
pyOpenSSL              19.1.0
pyparsing              2.4.7
PySocks                1.7.1
python-dateutil        2.8.1
PyWavelets             1.1.1
PyYAML                 5.4.1
requests               2.24.0
ruamel-yaml            0.15.87
scikit-image           0.17.2
scipy                  1.5.2
setuptools             50.3.1.post20201107
six                    1.15.0
tifffile               2021.1.14
toolz                  0.11.1
tornado                6.1
tqdm                   4.51.0
traitlets              5.0.5
urllib3                1.25.11
wcwidth                0.2.5
wheel                  0.35.1
(base) ➜  ~ which ipython
/Users/xxxx/opt/miniconda3/bin/ipython
(base) ➜  ~

**Comment by VolkerH** [comment]
@Genius-farmer : If I interpret your posts correctly you created an environment named `tensorflow` when you already had an environment named `tensorflow` ? 

Your `pip list` is from the base environment. You need to activate the environment that you need with `conda activate` followed by the environment name.

It sounds like you did not install `jupyter` in the environment.

These are not really `skimage` issues, but general `conda` / python environment issues. I think we've all struggled with those at some point, so I am sympathetic.

**Comment by Genius-farmer** [comment]
@VolkerH Yes. I created an environment named "tensorflow" when i already had an environment named "tensorflow" It seems to cause more problem more...

I think i understood better this whole environment thing. It's like a "place" all of these program needs to be in, in order for softwares to work.

Hence, do I have to install jupyter in that environment "tensorflow" now?

but, now when i tried to 
conda activate tensorflow
import tensorflow as tf
it gives "no module named 'tensorflow' , previously it would show tensorflow version.... it kinda messed up my tensor flow now... is there any way to fix or undo what i did?

**Comment by marimeireles** [comment]
> Hey thanks for the followup, I guess that my question probably got lost in a few followups, could you provide us the the output of
> 
>     1. `python --version`
> 
>     2. `pip list`
> 
>     3. `which ipython`
> 
> 
> It would help us get to the bottom of things I think.

Sorry for missing this, I'm not with my mac for the next 2 months, I can try it when we're reunited, but I remember trying for a while and the only way I got it working was on an linux.
