### ISSUE TITLE
Put our example data on a GitHub pages site

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#4538]
## Description

With pooch, we are able to download large datasets on demand, and no longer need to distribute them with scikit-image. We need a place to host the datasets now.

For my [blog](https://github.com/jni/ilovesymposia.com), I host on GitHub pages and add Cloudflare CDN on top of it, and this might work really well.

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/
https://www.codementor.io/@landonpatmore/how-to-setup-a-static-website-using-github-pages-and-cloudflare-with-your-own-domain-name-jb99nbuoe

We can also consider GitLab, which has more generous bandwidth limits — in fact, no bandwidth limits, just a 5GB storage limit, which should be plenty.

**Comment by emmanuelle** [comment]
Hi @jni, some naive questions on my end
- why github pages instead of just a github repo, where we would put the link to the master code arborescence in the registry?
- do we think we'll have so many downloads that we'll need the CDN / SSL ?

I agree that Gitlab is an interesting alternative since the total size of the example files could exceed 1 Go. 

We should also make sure that we don't use `download_all` in our tests when the repo starts to be big...

**Comment by jni** [comment]
> why github pages instead of just a github repo, where we would put the link to the master code arborescence in the registry?

(a) because github URLs are not super nice, compared to eg. `data.scikit-image.org/astronaut.png`.
(b) I don't know what github bandwidth limits are, if any, but I was suspicious that several CI runs failed after we started using pooch. I'm not sure whether they were related but I became paranoid about hitting bandwidth limits or some other kind of distribution issues, e.g. too many simultaneous hits to the same file getting an IP blocked as suspicious.

> do we think we'll have so many downloads that we'll need the CDN / SSL ?

As above, I'm not sure but I was suspicious. I don't remember the setup being hard, and if we start using large files, it might actually speed things up for data downloads around the world.

**Comment by emmanuelle** [comment]
> (a) because github URLs are not super nice, compared to eg. `data.scikit-image.org/astronaut.png`.

ok but the idea is to put the URL in the registry and just use `load`, right? So we should not really care about how URLs look?

**Comment by emmanuelle** [comment]
About bandwidth, we will probably want to add the files to the CI cache if this is possible, so that we don't download the files every time the doc is built (since we will probably want to write examples using our datasets).
