### ISSUE TITLE
Broken plot in userguide

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4540]
## Description
In this section.
https://scikit-image.org/docs/stable/user_guide/numpy_images.html#color-images

**Comment by emmanuelle** [comment]
This is weird because we are using matplotlib's plot directive, which is correctly imported (I checked it in #4554). Note that we are only using the plot directive for this example so if we completely change this example maybe you can remove this dependency.

**Comment by dsandeep0138** [comment]
@emmanuelle Can you please review the PR? Plot directive is working now with the changes. Below is the screenshot of the page after the fix.


![scikit-image](https://user-images.githubusercontent.com/3874111/85373702-42df2c80-b4f9-11ea-8f58-5968f78742f5.PNG)
