### ISSUE TITLE
Examples in `doc/examples/registration` are not displayed in the gallery

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4553]
This is because  `sphinx_gallery_conf['subsection_order']` does not include this subdirectory (see https://github.com/scikit-image/scikit-image/blob/master/doc/source/conf.py#L59). Also, some examples of `doc/examples/transform` should be moved to `doc/examples/registration`.

**Comment by rfezzani** [comment]
Please see #4503 and #4502. The register functions are moved to the `skimage.register` module and the corresponding examples are moved to `doc/example/registration`
