### ISSUE TITLE
Memory leak in CollectionViewer with repeated use

### ISSUE THREAD

**Issue by nodice73** [scikit-image/scikit-image#4559]
## Description

This may be related to issue #2475.

We are using CollectionViewer to analyze sets of movies. Every time we open a new movie in the CollectionViewer, additional memory is used (amount is about the size of the stack) and is not freed when the object instance goes out of scope. Using `gc.collect` makes no difference.

I was able to reproduce this using minimal code and no additional libraries except for numpy. It generates a random 3D stack and displays it. Close the window to have the next one show up.

I've included code that will print out `tracemalloc` snapshots, showing that the memory increases in each instance of the loop.

If this is not a memory leak, and we are just cleaning up incorrectly, what is the correct way to free up the memory used by a `CollectionViewer` object?

I'm using Python 3.6.6 (see version output, below), but we can also reproduce this on 3.8.1.

Thank you for all your hard work!

## Way to reproduce
```python
import tracemalloc
import numpy as np
import gc
from skimage.viewer import CollectionViewer

class ViewerTest(CollectionViewer):

    def __init__(self):
        print('generating random stack...', end='')
        self.stack = np.random.rand(300,100,500)
        print('done')

        super(ViewerTest, self).__init__(self.stack)
        self.show()


if __name__ == '__main__':
    tracemalloc.start()
    mem_start = tracemalloc.take_snapshot()
    mem_prev = mem_start
    top_stats = mem_start.statistics('lineno')

    print('\nMem at start')
    for stat in top_stats[:5]:
        print(stat)
    print('\n')

    for i in range(5):
        tester = ViewerTest()

        print('collecting garbage')
        gc.collect()

        mem_cur = tracemalloc.take_snapshot()

        print('\nMem since start')
        top_stats = mem_cur.compare_to(mem_start, 'lineno')
        for stat in top_stats[:5]:
            print(stat)
        print('\n')

        print('\nMem since prev')
        top_stats = mem_cur.compare_to(mem_prev, 'lineno')
        for stat in top_stats[:5]:
            print(stat)
        print('\n')

        mem_prev = mem_cur
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Darwin-19.4.0-x86_64-i386-64bit
scikit-image version: 0.16.2
numpy version: 1.18.2
```

**Comment by sciunto** [comment]
Thanks for reporting.

It is likely that sooner or later, we will remove viewers from scikit-image. Other libraries specialized for this use are appearing, like [napari](https://github.com/Napari/napari). Have you ever tried napari for your application?

**Comment by emmanuelle** [comment]
Thank you very much for the detailed and informative bug report @nodice73. As @sciunto said we are not planning to spend a lot of resources on the viewer since it's likely to be deprecated in version 1.0. We are interested in your feedback regarding napari, would it be easy for you to transition to napari?

**Comment by nodice73** [comment]
It would take us a little while to get up and running with Napari, but we definitely have plans to start using it. Actually, this might be the motivation to start using it.

I can accept that you probably won't fix it, but do you have any idea what could be causing it to not release memory? I am very curious from a programming perspective.

**Comment by sciunto** [comment]
@nodice73 No, I have no idea. I'm not an expert with this part of the library.

**Comment by mkcor** [comment]
Dear @nodice73,

Were you able to get started with Napari?

I'll close this issue since we have now removed the viewer module (#6160).
