### ISSUE TITLE
SKIP: in_place vs out kwarg

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4563]
## Description

I just noticed that in future, morphology, segmentation, we use the argument "in_place". In filters, and particularly rank, we use the kwarg "out".

I'm opening this issue for discussion.

**Comment by emmanuelle** [comment]
So `in_place` is very pandas-ish and `out` numpy-ish. Actually pandas uses mostly `inplace` (but `in_place` in places ha ha)

**Comment by soupault** [comment]
I do not have a strong preference, but slightly in favour of `in_place`/`inplace`.

**Comment by JDWarner** [comment]
This is one where probably most of us have a gut preference based on prior usage and if we were exposed earlier to NumPy or Pandas.  Personally I have more experience with NumPy/SciPy and thus my gut response is `out`.

From my admittedly biased perspective, `out` seems more concise and more versatile.  To me, `inplace` as a kwarg only makes intuitive sense as a boolean toggle, whereas `out` is much more versatile.  You can an operation inplace with `out`, or you can do other things.

With `out`, both of these are valid and makes sense and nothing is returned

``` python
do_this(with_this_var, out=output_goes_here)  # output_here need not be same as the input
do_this(with_this_var, out=with_this_var)  # inplace usage
```

whereas with `inplace`, it only really makes sense (IMHO) to have a motif like
``` python
do_this(with_this, inplace=True)
```

Again, though, I'm biased.  My other thought is that going with NumPy's syntactical preferences has virtually always been a good idea, as the choices made at the core of the ecosystem tend to radiate outward.  Though I'm sure Pandas has their reasons for `inplace`.

**Comment by lagru** [comment]
I find @JDWarner's argument convincing that `out` provides more flexibility. It covers the use case where the target may already be allocated but isn't identical with the input array. With regards to expressivity I find both options satisfying.

**Comment by emmanuelle** [comment]
I agree with the choice of `out` because
- we have more reasons to be compatible/similar with numpy than pandas
- out is more flexible

**Comment by jni** [comment]
I'd like to point out two things:

1. `scipy.ndimage` actually uses `output=`, not `out=`. Unfortunate, but true. So we would have to decide between the two options.
2. `out=` works for buffers, but not other data types, such as networkx graphs (RAGs). So unfortunately we'll be stuck with `inplace=` in some places.

Having said that, I totally agree with @JDWarner (and everyone) that `out=` is the better choice any time that arrays are involved. :+1: 

btw I don't think this is a SKIP. ;) SKIPs come at the *end* of a discussion that includes substantial uncertainty or disagreement about the way forward. =)

**Comment by emmanuelle** [comment]
About the SKIP, I interpreted it here as "please give your opinion" so it was great since it caught my attention (which is hard these days :-p). But we can find another code for this of course.

**Comment by jni** [comment]
The standard is "RFC" for "request for comment". =)

**Comment by rfezzani** [comment]
I vote for `out` for the flexibility that it offers as exposed by @JDWarner.

**Comment by sciunto** [comment]
> The standard is "RFC" for "request for comment". =)

This reminds me when I opened this issue: https://github.com/scikit-image/scikit-image/issues/2604#issuecomment-292770036 I entitled it RFC, you created SKIP and we changed it, and now you want me to put RFC :D 

So, RFC, SKIP, pre-SKIP... (no need to debate here). ;)

**Comment by jni** [comment]
Awesome, thanks for that @emmanuelle!

Re-reading this discussion, I realised that `out=my_rag` *does* work, because we can check the graphs for identity. So out with in_place, and in with out! :joy:

**Comment by rfezzani** [comment]
#5216, #5217 and #5218 deprecate `in_place` in favor of `out` in respectively `morphology.remove_small_objects`, `morphology.remove_small_holes` and `segmentation.clear_border`. Reviews are welcome :wink:

**Comment by rfezzani** [comment]
Now that #5216, #5217 and #5218 are merged, we close this one :tada:. Thank you all :wink:
