### ISSUE TITLE
Broken travis CI for mac

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4564]
## Description

`+++sudo tlmgr update --self

/Library/TeX/texbin/tlmgr: unexpected return value from verify_checksum: -5`

See #4560 #4562

**Comment by sciunto** [comment]
Explanation and workaround: https://tex.stackexchange.com/questions/537376/tlmgr-unexpected-return-value-from-verify-checksum-5-for-main-repository

**Comment by rfezzani** [comment]
An other interesting [post](https://tex.stackexchange.com/questions/528634/tlmgr-unexpected-return-value-from-verify-checksum-5): this is apparently related to a bug in `tlmgr`.
