### ISSUE TITLE
Avoid importing skimage.transform as tf

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#4572]
## Description

The module `skimage.transform` is imported as `tf` in multiple gallery examples ([plot_brief](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/features_detection/plot_brief.py#L15), [plot_orb](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/features_detection/plot_orb.py#L16), [plot_censure](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/features_detection/plot_censure.py#L12) and [plot_geometric](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/applications/plot_geometric.py#L16)), but this abbreviation is usually used for the `tendorflow` package.

I think that we need to find an alternative abbreviation. Two candidates have been mentioned in #4385: `transform` and `sktf`. Any opinion/suggestion is welcome.

**Comment by JDWarner** [comment]
I would favor `transform`.  `sktf` might imply to those more familiar with `tensorflow` that we have some `tensorflow` integration we don't, and to most other people it seems as obtuse as for example XKCD.  Also `transform` is shorter when spoken aloud.

**Comment by jni** [comment]
I agree with @JDWarner, I much prefer transform. We also generally use the full module name when we don't import functions directly, e.g. `from skimage import filters`.

**Comment by DCtheTall** [comment]
@rfezzani I'd be interested in writing a quick PR with the fix.

**Comment by soupault** [comment]
@DCtheTall you are very welcome!

**Comment by emmanuelle** [comment]
Thank you @DCtheTall :smiling_face_with_three_hearts:
