### ISSUE TITLE
Broken CI on OSX

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4573]
The travis build stops at

```
+++sudo tlmgr --verify-repo=none install ucs dvipng anyfontsize

tlmgr: The TeX Live versions supported by the repository

http://mirrors.ibiblio.org/pub/mirrors/CTAN/systems/texlive/tlnet

  (2016--2019)

do not include the version of the local installation

  (2020).

```

**Comment by sciunto** [comment]
I've seen this failure but I ignored that this would prevent our doc to be pushed.

After the key issue that texlive faced, I guess they tried to react quickly and they are working to put things in order.

**Comment by emmanuelle** [comment]
Looks like it got fixed.
