### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by klonuo** [scikit-image/scikit-image#458]
Hi,

can someone provide documentation preferably in PDF or CHM, but also zipped HTML is fine.

I want to be able to browse reference on a node without internet connections while documentation generator doesn't work here:

```
Making output directory...
Running Sphinx v1.1.3
C:\Python27\lib\site-packages\matplotlib\__init__.py:1005: UserWarning:  This call to matplotlib.use() has no effect
because the the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
loading pickled environment... not yet created

Theme error:
no theme named 'scikit-image' found (missing theme.conf?)
```

Thanks

**Comment by MSC19950601** [comment]
No LaTeX version?

**Comment by ratijas** [comment]
Since LaTeX / latexpdf build is _great again_, I would propose adding a pdf file to the scikit-image website available for download. Not sure where to start though. Can someone point me out to the website build configuration, please?

**Comment by jni** [comment]
The scikit-image website lives on another repo, https://github.com/scikit-image/scikit-image-web

**Comment by alexdesiqueira** [comment]
Closing this one, since we didn't have any discussions for the last _five years_ :joy: Thank you everyone for your interest and opinions! Please feel free to reopen if necessary.
