### ISSUE TITLE
corner_harris returns peaks in a non "natural" order when the peaks have the same amplitude

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#4580]
## Description

@emmanuelle [caught](https://github.com/scikit-image/scikit-image/pull/4218#issuecomment-612629627) a bug in `corner_peaks`: it returns the peaks coordinates in the wrong order when the peaks have the same amplitude.

**Comment by jni** [comment]
Well, is "wrong" the correct word here? =) But, granted, it would be unintuitive to get this result. =)
