### ISSUE TITLE
funky behavior of `rescale_intensity` 

### ISSUE THREAD

**Issue by d-v-b** [scikit-image/scikit-image#4583]
## Description
Looks like `rescale_intensity` does some weird stuff when the `in_range` argument has `np.int8` dtype. Unfortunately, this naturally arises when `in_range` is a result computed from the data to be rescaled. E.g., if I have an array of `int8` that I want to rescale, the min and max of that array will also be `int8`, which apparently induces weird output from `rescale_intensity`.   

## Way to reproduce
```python
from skimage.exposure import rescale_intensity
import numpy as np

out_range = 'uint8'
arr = np.array([-128, 0, 127]).astype('int16')

print("arr:", arr)

clims_a = (-128, 127)
a = rescale_intensity(arr, in_range=clims_a, out_range=out_range)
print("a:  ", a)

clims_b = (np.int8(-128), np.int8(127))
b = rescale_intensity(arr, in_range=clims_b, out_range=out_range)
print("b:  ", b)
```

## Version information
```python
3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0]
Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-glibc2.10
scikit-image version: 0.16.2
numpy version: 1.18.1
```

## Output
```python
arr: [-128    0  127]
a:   [  0 128 255]
b:   [     0 -32640    511]
```

**Comment by jni** [comment]
That is indeed a crazy bug! Looks like overflow:

```python
In [7]: exposure.rescale_intensity(arr, in_range=clims_b, out_range='uint8')                                                                                                                  
/home/jni/projects/scikit-image/skimage/exposure/exposure.py:361: RuntimeWarning: overflow encountered in byte_scalars
  image = (image - imin) / float(imax - imin)
Out[7]: array([     0, -32640,    511], dtype=int16)

In [8]: exposure.rescale_intensity(arr2, in_range=clims_b, out_range='uint8')                                                                                                                 
/home/jni/projects/scikit-image/skimage/exposure/exposure.py:361: RuntimeWarning: overflow encountered in byte_scalars
  image = (image - imin) / float(imax - imin)
Out[8]: array([   0, -128,   -1], dtype=int8)
```

(arr2 is the same array but int8 type).

I mean, the weird and crazy thing is that, at a minimum, the output dtype should be the dtype requested, and we can't even do that. Thanks for reporting!

**Comment by jni** [comment]
Ok, so the whole function is actually tiny, and imho not fit for purpose:

https://github.com/scikit-image/scikit-image/blob/9aac8495b7b9e50d8660c0e32f2301835bc1ddb2/skimage/exposure/exposure.py#L344-L362

Specifically:

- calculations are done in the input dtype (see `float(imax - imin)`), virtually guaranteeing overflow for signed integers
- the output is given in the same dtype as the input, even if a different dtype was selected for the output.

imho both of these things should be fixed, along with corresponding tests:

- computations should be in float. We end up in float anyway when doing the division, so this would not be a big hit on performance, and it is the only way (?) to prevent under/overflow errors without complicated logic about integer dtypes.
- if a dtype is given as the output range, the output image should be in that dtype.
- if a *range* is given as the output range... Well, I'm not sure what to do about the output range, but my intuition is that we should either make it float, *or*, based on the input dtypes, find the smallest dtype which contains the requested range. I lean towards float.

@scikit-image/core this should be an easyish PR to do, *once* a decision is made on all three points above. Any thoughts? I won't be at the Atlantic meeting but I've added this to the agenda for discussion. Thanks!

**Comment by stefanv** [comment]
I am +3 on all suggestions, and avoiding magical dtype guessing.

**Comment by stefanv** [comment]
@lagru noticed this additional problem:

```
Use `rescale_intensity` to rescale to the proper range for float dtypes:

>>> image_float = 1.0 * image
>>> rescale_intensity(image_float)
array([0. , 0.5, 1. ])
```

In the future, we want to move away from this kind of dtype based rescaling.

**Comment by emmanuelle** [comment]
Also +1 about the three points.

**Comment by jni** [comment]
@stefanv @lagru I think the 0-1 rescaling behaviour can be changed when we make a library-wide push. For now, it is consistent with existing behaviour, so let's just leave it. See #4585.
