### ISSUE TITLE
Broken link in `separate_stains` docstring

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4594]
https://mecourse.com/landinig/software/cdeconv/cdeconv.html returns a 404. I could not find an equivalent from an (extremely quick) google search.

**Comment by sciunto** [comment]
How about switching to an archive: https://web.archive.org/web/20160624145052/http://www.mecourse.com/landinig/software/cdeconv/cdeconv.html

**Comment by jni** [comment]
I like your idea @sciunto !
