### ISSUE TITLE
Misleading "ValueError: Input array has to be either 3- or 4-dimensional" in montage

### ISSUE THREAD

**Issue by bersbersbers** [scikit-image/scikit-image#4606]
## Description
When inputting a 4-dimensional array into `skimage.util.montage`, I get a misleading error message:
> ValueError: Input array has to be either 3- or 4-dimensional

But the input array *is* 4-dimensional already, what is missing is `multichannel=True`.

## Way to reproduce
```python
import numpy as np
from skimage.util import montage

data = np.zeros((10, 128, 128, 3))
print(f"'data' is {data.ndim}-dimensional.")

montage(data)
```

> 'data' is 4-dimensional.
> ValueError: Input array has to be either 3- or 4-dimensional

## Version information
```
3.8.2 (default, Feb 26 2020, 09:52:54) 
[GCC 7.5.0]
Linux-4.12.14-lp151.28.32-default-x86_64-with-glibc2.26
scikit-image version: 0.16.2
numpy version: 1.18.3
```

**Comment by soupault** [comment]
@bersbersbers good point! Would you like to submit a PR for fixing the message?

**Comment by bersbersbers** [comment]
@soupault not really, I'm not a bit git user (yet). Also, there's a number of options.

One could simply modify 
https://github.com/scikit-image/scikit-image/blob/11bb9be96b126960bc3b1a68bf27b7d9a13d3aea/skimage/util/_montage.py#L97

to say
```
raise ValueError('Input array has to be 3-dimensional, or 4-dimensional with `multichannel=True`')
```

Alternatively, one could set `multichannel=None` by default and auto-detect it based on `np.asarray(arr_in).ndim`.

**Comment by sciunto** [comment]
Thank you. I agree with the edit on the error message. We do not want to perform guessing based on input values to avoid magic behaviors in the library. I'll open a PR.

**Comment by bersbersbers** [comment]
I would like this re-opened, I do not agree that #4607 fixes this (yet).

**Comment by sciunto** [comment]
I shouldn't have pushed the commit. I implemented @jni's suggestion, wanted to read again the function, and after switching to something else I pushed I forgot to come back to it. :/ I wanted to check the unittests as well.

**Comment by sciunto** [comment]
I'll have a look again later on, except if someone else want to do it sooner.
