### ISSUE TITLE
Can't load most images from data package

### ISSUE THREAD

**Issue by pythonic2020** [scikit-image/scikit-image#4611]
Hello, this is my first day with scikit-image.  I cannot load certain sample images from the embedded data depository.

I'm running 0.16.2 within a miniconda installation of Python 3.7.7.  I installed scikit-image (build py37h47e9c7a_0) from conda pkgs/main today.

I can load the "rocket," "retina," and "binary_blobs" images, but no others so far.  For example, if I try and load the "coffee" image thus:

```
from skimage import data, color, io, filters

coffee_image = data.coffee()
io.imshow(coffee_image)
io.show()
```

I get this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-4246c051095d> in <module>
----> 1 coffee_image = data.coffee()
      2 io.imshow(coffee_image)
      3 io.show()

~\Miniconda3\envs\forge\lib\site-packages\skimage\data\__init__.py in coffee()
    561         Coffee image.
    562     """
--> 563     return _load("coffee.png")
    564 
    565 

~\Miniconda3\envs\forge\lib\site-packages\skimage\data\__init__.py in _load(f, as_gray)
     94     # we lazy import it here
     95     from ..io import imread
---> 96     return imread(_os.path.join(data_dir, f), plugin='pil', as_gray=as_gray)
     97 
     98 

~\Miniconda3\envs\forge\lib\site-packages\skimage\io\_io.py in imread(fname, as_gray, plugin, **plugin_args)
     46 
     47     with file_or_url_context(fname) as fname:
---> 48         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     49 
     50     if not hasattr(img, 'ndim'):

~\Miniconda3\envs\forge\lib\site-packages\skimage\io\manage_plugins.py in call_plugin(kind, *args, **kwargs)
    208                                (plugin, kind))
    209 
--> 210     return func(*args, **kwargs)
    211 
    212 

~\Miniconda3\envs\forge\lib\site-packages\skimage\io\_plugins\pil_plugin.py in imread(fname, dtype, img_num, **kwargs)
     34         with open(fname, 'rb') as f:
     35             im = Image.open(f)
---> 36             return pil_to_ndarray(im, dtype=dtype, img_num=img_num)
     37     else:
     38         im = Image.open(fname)

~\Miniconda3\envs\forge\lib\site-packages\skimage\io\_plugins\pil_plugin.py in pil_to_ndarray(image, dtype, img_num)
     64     while 1:
     65         try:
---> 66             image.seek(i)
     67         except EOFError:
     68             break

~\Miniconda3\envs\forge\lib\site-packages\PIL\PngImagePlugin.py in seek(self, frame)
    746         for f in range(self.__frame + 1, frame + 1):
    747             try:
--> 748                 self._seek(f)
    749             except EOFError:
    750                 self.seek(last_frame)

~\Miniconda3\envs\forge\lib\site-packages\PIL\PngImagePlugin.py in _seek(self, frame, rewind)
    789 
    790             try:
--> 791                 cid, pos, length = self.png.read()
    792             except (struct.error, SyntaxError):
    793                 break

AttributeError: 'NoneType' object has no attribute 'read'
```
Here is a listing of the contents of the data depository:
```
> dir(data)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_binary_blobs',
 '_detect',
 '_load',
 '_np',
 '_os',
 'astronaut',
 'binary_blobs',
 'brick',
 'camera',
 'cell',
 'checkerboard',
 'chelsea',
 'clock',
 'coffee',
 'coins',
 'colorwheel',
 'data_dir',
 'grass',
 'gravel',
 'horse',
 'hubble_deep_field',
 'img_as_bool',
 'immunohistochemistry',
 'lbp_frontal_face_cascade_filename',
 'lfw_subset',
 'load',
 'logo',
 'microaneurysms',
 'moon',
 'osp',
 'page',
 'retina',
 'rocket',
 'rough_wall',
 'shepp_logan_phantom',
 'stereo_motorcycle',
 'text',
 'warn']
```

Could someone help me understand what's going on?  Let me know if you need more info on my installation, etc.  Thank you in advance.

**Comment by emmanuelle** [comment]
Hum this is weird. Can you please do
```
import skimage
import os
print(skimage.data_dir)
print(os.listdir(skimage.data_dir))
```
and paste the result here?

**Comment by pythonic2020** [comment]
Here you go:

C:\Users\Me\Miniconda3\envs\forge\lib\site-packages\skimage\data
['astronaut.png', 'astronaut_GRAY_hog_L1.npy', 'astronaut_GRAY_hog_L2-Hys.npy', 'block.png', 'brick.png', 'bw_text.png', 'bw_text_skeleton.npy', 'camera.png', 'cell.png', 'checker_bilevel.png', 'chelsea.png', 'chessboard_GRAY.png', 'chessboard_GRAY_U16.tif', 'chessboard_GRAY_U16B.tif', 'chessboard_GRAY_U8.npy', 'chessboard_GRAY_U8.npz', 'chessboard_RGB.png', 'chessboard_RGB_U8.npy', 'chessboard_RGB_U8.npz', 'clock_motion.png', 'coffee.png', 'coins.png', 'color.png', 'diamond-matlab-output.npz', 'disk-matlab-output.npz', 'foo3x5x4indexed.png', 'grass.png', 'gravel.png', 'gray_morph_output.npz', 'green_palette.png', 'horse.png', 'hubble_deep_field.jpg', 'ihc.png', 'lbpcascade_frontalface_opencv.xml', 'lfw_subset.npy', 'logo.png', 'microaneurysms.png', 'moon.png', 'motorcycle_disp.npz', 'motorcycle_left.png', 'motorcycle_right.png', 'mssim_matlab_output.npz', 'multi.fits', 'multipage.tif', 'multipage_rgb.tif', 'no_time_for_that_tiny.gif', 'orb_descriptor_positions.txt', 'page.png', 'palette_color.png', 'palette_gray.png', 'phantom.png', 'rank_filter_tests.npz', 'retina.jpg', 'rocket.jpg', 'simple.fits', 'tests', 'text.png', 'truncated.jpg', '_binary_blobs.py', '_blobs_3d_fiji_skeleton.tif', '_detect.py', '__init__.py', '__pycache__']

**Comment by pythonic2020** [comment]
'hubble_deep_field.jpg' works fine also.

**Comment by emmanuelle** [comment]
ok so you have the `coffee.png` file which is used for `data.coffee`. It looks like you're able to open the `jpg` files but not the `png` ones...

**Comment by pythonic2020** [comment]
Yes, I just updated my last post 2 seconds before your post!

**Comment by pythonic2020** [comment]
All the images work on my system using other Windows programs, and are displayed normally in File Explorer...

**Comment by emmanuelle** [comment]
:-). Could be a problem of PIL, the backend library used for opening images. Let me check if PIL is the default backend.

**Comment by pythonic2020** [comment]
Ok, thank you very much for your help!!!  :-)

**Comment by pythonic2020** [comment]
PIL and all its plugins are installed...

**Comment by emmanuelle** [comment]
Your problem seems to be related to https://github.com/python-pillow/Pillow/issues/4518

**Comment by pythonic2020** [comment]
Yes it sure does. I have pillow 7.1.1 installed...

**Comment by emmanuelle** [comment]
Can you manually downgrade Pillow? It's probably the easiest option.

**Comment by pythonic2020** [comment]
Trying now...

**Comment by pythonic2020** [comment]
Yes, that works.  Thank you for your help!!!!!!   :-)

**Comment by emmanuelle** [comment]
Cool. I'll close the issue then. Happy skimaging ;-).

**Comment by hugovk** [comment]
Pillow 7.1.2 was released yesterday with a fix for https://github.com/python-pillow/Pillow/issues/4518.
