### ISSUE TITLE
Search links broken in dev documentation

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4616]
When searching a function name in the search bar of the dev doc, many links are found but they are incorrect, since following the links result in a 404 error. 

Is this related to the new sphinx version?

**Comment by emmanuelle** [comment]
It'd be great to fix this before the release. Maybe this is related to https://github.com/sphinx-doc/sphinx/pull/7192 but not sure.

**Comment by mkcor** [comment]
This issue is very annoying, indeed... :s

**Comment by emmanuelle** [comment]
thanks for the reminder @mkcor I had forgotten about it and I believe this will be blocking the release...

**Comment by emmanuelle** [comment]
@mkcor please note that the search works fine in the stable doc

**Comment by emmanuelle** [comment]
Also see https://github.com/panda3d/panda3d-docs/issues/42
