### ISSUE TITLE
Image Viewer produces two windows in Jupyter notebook

### ISSUE THREAD

**Issue by amichaut** [scikit-image/scikit-image#4626]
## Description
Using ImageViewer opens two windows when run from a Jupyter notebook: one empty window named 'Figure 1' and a second named 'image viewer' which is the right viewer. The same code run from a terminal produces only the viewer as expected.

## Way to reproduce
```python
from pylab import *
from skimage.viewer import ImageViewer
from skimage import data
image = data.coins()
viewer = ImageViewer(image)
viewer.show()
```

## Version information
```python
3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Darwin-18.7.0-x86_64-i386-64bit
scikit-image version: 0.16.2
numpy version: 1.18.1
jupyter-notebook version: 6.0.3
```

**Comment by jni** [comment]
Hi @amichaut. Unfortunately, we are doing almost no maintenance on the ImageViewer and it is going to be spun-off into its own project, while scikit-image focuses on analysis. Have you looked at the [napari](https://napari.org) project and whether that meets your needs?

**Comment by amichaut** [comment]
I didn't but now I do. thanks!

**Comment by sciunto** [comment]
I propose to close this as won't fix. Thanks you.
