### ISSUE TITLE
Master broken after commit bcd03b4ba147ce00cb646b4fc8c750434213f637

### ISSUE THREAD

**Issue by m-albert** [scikit-image/scikit-image#4656]
## Description

```python
In [1]: import skimage
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-aa248544dc2e> in <module>
----> 1 import skimage

~/software/scikit-image/skimage/__init__.py in <module>
    123
    124     # All skimage root imports go here
--> 125     from .util.dtype import (img_as_float32,
    126                              img_as_float64,
    127                              img_as_float,

~/software/scikit-image/skimage/util/__init__.py in <module>
     15 from ._invert import invert
     16 from ._montage import montage
---> 17 from ._map_array import map_array
     18
     19

~/software/scikit-image/skimage/util/_map_array.py in <module>
      1 import numpy as np
----> 2 from ._remap import _map_array
      3
      4
      5 def map_array(input_arr, input_vals, output_vals, out=None):

ModuleNotFoundError: No module named 'skimage.util._remap'
```

## Way to reproduce
```python
import skimage
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 17:55:48)
[Clang 9.0.1 ]
macOS-10.14.6-x86_64-i386-64bit
```

**Comment by emmanuelle** [comment]
Hey @m-albert could you please also copy your skimage version?

**Comment by emmanuelle** [comment]
pretty urgent question since I'm in the middle of a release and of course I don't want to release a broken skimage.

**Comment by rfezzani** [comment]
It will be hard to answer since the error is thrown at `skimage` import :confused: 
@m-albert, how `skimage` is installed? Is it a fresh install, (conda or pip) or clone from github? Are you in dev mode (`pip install -e`)?

**Comment by m-albert** [comment]
I'm in dev mode installing from a github clone.

**Comment by JDWarner** [comment]
Was it a clean clone or installed/updated over a previous existing install of scikit-image?  This kind of thing can happen when old files are lying around.

**Comment by m-albert** [comment]
It was a clean clone from some weeks ago, however I've been switching branches if that can make any difference. Currently installing from scratch to see if the problem persists.

**Comment by JDWarner** [comment]
If you had any uncommitted files it could.  Please keep us posted on the clean attempt.

**Comment by rfezzani** [comment]
Try to uninstall and reinstall:
```
cd skimage_repo/
python setup.py develop -u
pip install -ve .
```
It helps some times in dev mode ;)

**Comment by m-albert** [comment]
Trying both approaches, it's aking some time...

**Comment by m-albert** [comment]
> It helps some times in dev mode ;)

Ok it worked. Sorry guys should have tried a fresh install before opening the issue!
