### ISSUE TITLE
data_dir always falling back to legacy_data_dir

### ISSUE THREAD

**Issue by tlambert03** [scikit-image/scikit-image#4659]
## Description

I'm not sure if I'm misunderstanding how I'm supposed to access the new pooch-handled data... but it seems that if all goes according to plan with the download in `data.__init__`, the `data_dir` variable will always fall back on the `legacy_data_dir`.  (i.e. if there's no break statement in the following clause, it will go to the else statement):

https://github.com/scikit-image/scikit-image/blob/f5290e1d0f10426dc8c54dc3046f795b4c2016bc/skimage/data/__init__.py#L168-L175

am I missing something?

PS.  thank you and congrats on the new release!

## Version information
3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 17:55:48) 
[Clang 9.0.1 ]
macOS-10.13.6-x86_64-i386-64bit
scikit-image version: 0.17.0
numpy version: 1.18.4

**Comment by jni** [comment]
@hmaarrfk got any ideas on this?

**Comment by hmaarrfk** [comment]
Ah sorry for not replying to this.

Work was just insane this week.

**Comment by hmaarrfk** [comment]
Somehow pooch became a hard dependency.

I think that for loop as supposed to be indented, and there was supposed to be an ifstatrment checking if pooch was installed.
