### ISSUE TITLE
pooch is a hard requirement

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#4665]
## Description

I thought we wanted pooch to be a soft requirement.
Do you want me to make a PR Todo that.

It seems that got lost in a few rebases maybe. Maybe I'm forgetting a discussion 

## Version information
0.17.1

**Comment by emmanuelle** [comment]
If we could have pooch as a soft requirement that'd be great, as long as we can still load the usual "legacy" data arrays (astronaut, chelsea etc.) if pooch is not present. I think you're right, it got lost in the lengthy review process :-).

 I think @jni is also preparing a PR for pooch to do things in a more lazy way, so depending whichever of this two PRs comes first there might be some merging and conflicts solving for the other one.

**Comment by hmaarrfk** [comment]
Have you been using me meseeks to backport to 0.17?

**Comment by emmanuelle** [comment]
no just cherry-picking for now for 0.17.1, should I use meseeks instead?

**Comment by hmaarrfk** [comment]
I think a few PRs have been created for it. So I'm going to try to build off those, assuming they will be backported in order.

**Comment by hmaarrfk** [comment]
It seems that pooch was made a hard dependency in

8e08610

I really don't remember why

**Comment by jni** [comment]
#4666 already implements my fix so we should just fast-track it. @emmanuelle if you are going to make a release today, and you like my suggestions there, I can push them and we can merge and release.

**Comment by jni** [comment]
Oops, I take it back, it doesn't, because it makes the function but then runs it by default. That can be fixed there also. I'll push a suggestion.
