### ISSUE TITLE
ORB detection doesn't work on 32 bit float input

### ISSUE THREAD

**Issue by SuborbitalPigeon** [scikit-image/scikit-image#4675]
## Description

Trying to use ORB feature detection of an image of dtype 'f4' fails, as the function [_corner_fast](https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/corner_cy.pyx#L110) requires `double` input, but nothing converts it to double on the way. Integer input works however.

## Way to reproduce
```python
from skimage import data, feature

img = data.checkerboard().astype('f4')
orb = feature.ORB()
orb.detect(img)
```

## Version information

```python
3.8.2 (default, Feb 28 2020, 00:00:00) 
[GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)]
Linux-5.6.8-300.fc32.x86_64-x86_64-with-glibc2.2.5
scikit-image version: 0.17.1
numpy version: 1.18.4

```

**Comment by rfezzani** [comment]
Thank you @SuborbitalPigeon for reporting.
I suspect that this comes from Cython version change. I think that previously, any input was implicitly converted to `double` (which is already bad).
`np_floats` fused type use must be generalized.

**Comment by rfezzani** [comment]
`BRIEF` is also affected:
```python
>>> from skimage import data
>>> from skimage.feature import (corner_peaks, corner_harris, BRIEF)
>>> from skimage.color import rgb2gray
>>> img1 = rgb2gray(data.astronaut())
>>> keypoints1 = corner_peaks(corner_harris(img1), min_distance=5)
__main__:1: FutureWarning: Until version 0.16, threshold_rel was set to 0.1 by default. Starting from version 0.16, the default value is set to None. Until version 0.18, a None value corresponds to a threshold value of 0.1. The default behavior will match skimage.feature.peak_local_max. To avoid this warning, set threshold_rel=0.
>>> extractor = BRIEF()
>>> extractor.extract(img1.astype('f4'), keypoints1)
...
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```
And, I imagine, all the functions declaring a buffer of `double` in their signature are also affected.

**Comment by jklaise** [comment]
Segmentation on `float32` inputs doesn't work either:

```python
from skimage.segmentation import slic
import numpy as np
im = np.random.rand(28, 28).astype(np.float32)
slic(im)

skimage.measure.label's indexing starts from 0. In future version it will start from 1. To disable this warning, explicitely set the `start_label` parameter to 1.
Traceback (most recent call last):
  File "/home/janis/.conda/envs/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-61-1f8b517e73c1>", line 1, in <module>
    slic(im)
  File "/home/janis/.conda/envs/py37/lib/python3.7/site-packages/skimage/segmentation/slic_superpixels.py", line 298, in slic
    start_label=start_label)
  File "skimage/segmentation/_slic.pyx", line 21, in skimage.segmentation._slic._slic_cython
ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'
```

**Comment by rfezzani** [comment]
Thank you @jklaise for the report. May be should we open separate Issues for each affected function to keep track of each of them...

**Comment by jklaise** [comment]
@rfezzani sounds like this could affect most of the library. Is it the case that pre-0.17 most functions supported `float32` by implicitly casting to `float64` and some others supported it natively?

**Comment by rfezzani** [comment]
In fact, it seems that many cython functions will be affected :confused:
My hypothesis is that cython stopped implicitly supporting `float32` dtype when double precision arrays are in function's signature... That's the right thing to do IMHO, despite that it will introduce a lot of breaking changes in `skimage`...

**Comment by grlee77** [comment]
Another potential cause is the change to `image_as_float` made in #3110 to preserves single precision inputs rather than automatically promoting them to double. However, that change happened a couple releases prior (either 0.14 or 0.15), so probably does not explain the issue if it only recently started occurring.

**Comment by rfezzani** [comment]
Well, I checked, and it seems that this bug already existed in v0.16:
```python
>>> import skimage
>>> skimage.__version__
'0.16.2'
>>> from skimage import data, feature
>>> 
>>> img = data.checkerboard().astype('f4')
>>> orb = feature.ORB()
>>> orb.detect(img)
...
File "skimage/feature/corner_cy.pyx", line 110, in skimage.feature.corner_cy._corner_fast
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```
My hypothesis was all wrong, sorry...

**Comment by rfezzani** [comment]
@jklaise, I also checked for `slic`, v0.16 is also affected
```python
>>> from skimage.segmentation import slic
>>> import numpy as np
>>> im = np.random.rand(28, 28).astype(np.float32)
>>> slic(im)
...
  File "skimage/segmentation/_slic.pyx", line 13, in skimage.segmentation._slic._slic_cython
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
>>> skimage.__version__
'0.16.2'
```

**Comment by jklaise** [comment]
@rfezzani that's strange as our tests were working with 0.16.2... I'll see what other differences we have in the environment.
