### ISSUE TITLE
BRIEF fails for float32 data type

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#4677]
## Description

As ORB in #4675, `BRIEF` stopped supporting single precision float images.

## Way to reproduce
```python
>>> from skimage import data
>>> from skimage.feature import (corner_peaks, corner_harris, BRIEF)
>>> from skimage.color import rgb2gray
>>> img1 = rgb2gray(data.astronaut())
>>> keypoints1 = corner_peaks(corner_harris(img1), min_distance=5, threshold_rel=0.1)
>>> extractor = BRIEF()
>>> extractor.extract(img1.astype('f4'), keypoints1)
.
.
.
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```

## Version information

```
3.8.2 (default, May  7 2020, 20:00:49) 
[GCC 7.3.0]
Linux-4.4.0-178-generic-x86_64-with-glibc2.10
scikit-image version: 0.17.1
numpy version: 1.18.4
```

**Comment by emmanuelle** [comment]
Thanks @rfezzani. Did you check that this came up with 0.17?

**Comment by rfezzani** [comment]
The issue https://github.com/SeldonIO/alibi/issues/215 opened by @jklaise suggests that these `ValueError` caused by single precision arrays are introduced with v0.17 :confused:

**Comment by rfezzani** [comment]
I checked @emmanuelle, this bug already existed in v0.16:
```python
>>> from skimage import data
>>> from skimage.feature import (corner_peaks, corner_harris, BRIEF)
>>> from skimage.color import rgb2gray
>>> img1 = rgb2gray(data.astronaut())
>>> keypoints1 = corner_peaks(corner_harris(img1), min_distance=5, threshold_rel=0.1)
>>> extractor = BRIEF()
>>> extractor.extract(img1.astype('f4'), keypoints1)
...
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
>>> import skimage
>>> skimage.__version__
'0.16.2'
```
....

**Comment by emmanuelle** [comment]
thanks @rfezzani this is still pretty bad but at least we don't feel compelled to fix it in 0.17.2. Since you made this investigation could you please report it back to the `alibi` project?

**Comment by jklaise** [comment]
@rfezzani @emmanuelle we were previously running 0.16.2 on CI with no issues with the segmentation functions (`slic` in particular), so the regression for `slic` must have happened with 0.17.

How involved would it be to run the test suite on different types of inputs (e.g. `int`, `float32`, `float64` etc.) so we can find out exactly which functions work with what datatypes?

**Comment by emmanuelle** [comment]
@jklaise basically we intend to support `float32` wherever we support `float64`, when it's not the case it can be considered as a bug on our side. We are lacking a proper test infrastructure which would test systematically that float32 is supported when float data are accepted but this will be easier once we introduce type hints in scikit-image functions #3153. 

Thanks for reporting this problem upstream, it definitely helps to improve the quality of scikit-image.
