### ISSUE TITLE
Allow for calculation of single property in regionprops

### ISSUE THREAD

**Issue by 1minus1** [scikit-image/scikit-image#4679]
It would be great to be able to access the output of regionprops without the overhead of calculating every property. I am working on a set of 1000^3 pixel images with a few hundred labeled regions, and the only metric I care about is bbox. I currently had to extract the bbox code from meaure.regionprops to speed up my code.

**Comment by sciunto** [comment]
Thanks for reporting @1minus1 Could you indicate which scikit-image version are you using?

It seemed to me that properties are calculated upon request and cached, so I'm surprised...
https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_regionprops.py

Could you eventually share a simple code that highlights the performance issue?

**Comment by jni** [comment]
I agree with @sciunto, this is certainly a performance issue, since properties are evaluated lazily, and should be investigated regardless of whether we provide the API you suggest — which I'm inclined to do anyway.

It could be that the overhead of creating a regionprops object is high.

Having said that, @1minus1, for finding bounding boxes you can just use [`scipy.ndimage.find_objects`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.find_objects.html#scipy.ndimage.find_objects), which is the very first step of regionprops.

Thanks for the report!

**Comment by 1minus1** [comment]
sci-image version = 0.16.2

Well, I am not sure why, but I couldn't replicate this in my example code. I used porespy to generate an image, and the two methods I described take the same amount of time to find the bboxes. I'll report back if I find out what happened the first time around. Thanks for taking the time to respond.

Note: If you're running this code, it'll take several minutes for structure generation.

```
import porespy as ps
import skimage
import scipy
import time

#im = ps.generators.cylinders([500,500,500], 5,5000,  0,90,None)
#im = ps.generators.cylinders([700,700,700], 5,7000,  0,90,None)
im = ps.generators.cylinders([1000,1000,1000], 5,10000,  0,90,None)
labeledim = skimage.measure.label(im)

props_start = time.time()
props = skimage.measure.regionprops(labeledim)
bboxes1 = [prop['bbox'] for prop in props]
print('regionprops time - '+str(time.time()-props_start))

extracted_start = time.time()
objs = scipy.ndimage.find_objects(labeledim)
bboxes2 = []
for i, sl in enumerate(objs):
    thisbbox = tuple([sl[i].start for i in range(3)] + [sl[i].stop for i in range(3)])
    bboxes2.append(thisbbox)
print('find_objects time = '  + str(time.time()-extracted_start))

print(bboxes1==bboxes2)
```

Output:
```
regionprops time - 8.211904048919678
find_objects time = 8.3150954246521
True
```

**Comment by 1minus1** [comment]
More context for this bug in case it helps. 

I had this analysis buried in some other code, and got an error when calling skimage.measure.regionprops(labeledim) on an image, and the error was related to the calculation of convex hull (might have been a memory issue, since it's constrained). I assumed it was trying to do all the calculations when making that call, but it might have been mistaken.

Sorry if that's not too helpful. I'll see if I can replicate it.

**Comment by 1minus1** [comment]
Sorry, I think this is a porespy bug. They implement regionprops_3d, which first calls skimage.measure.regionprops, then extends it.

```
import porespy as ps
import skimage
import scipy
import time

im = ps.generators.cylinders([100,100,100], 5,250,  0,90,None)
#im = ps.generators.cylinders([500,500,500], 5,5000,  0,90,None)
#im = ps.generators.cylinders([700,700,700], 5,7000,  0,90,None)
#im = ps.generators.cylinders([1000,1000,1000], 5,10000,  0,90,None)
labeledim = skimage.measure.label(im)

props_start = time.time()
props = skimage.measure.regionprops(labeledim)
bboxes1 = [prop['bbox'] for prop in props]
print('regionprops time - '+str(time.time()-props_start))

psprop_start = time.time()
# fail
psprops = ps.metrics.regionprops_3D(labeledim)
bboxes3 = [prop['bbox'] for prop in psprops]
print('psprops time - '+str(time.time()-psprop_start))

extracted_start = time.time()
objs = scipy.ndimage.find_objects(labeledim)
bboxes2 = []
for i, sl in enumerate(objs):
    thisbbox = tuple([sl[i].start for i in range(3)] + [sl[i].stop for i in range(3)])
    bboxes2.append(thisbbox)
print('find_objects time = '  + str(time.time()-extracted_start))

print(bboxes1==bboxes2)
print(bboxes1==bboxes3)
```

error:
```

Exception has occurred: QhullError
QH6214 qhull input error: not enough points(1) to construct initial simplex (need 4)

While executing:  | qhull i Qt
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 926775319  incidence  Qtriangulate  _pre-merge  _zero-centrum
  _maxoutside  0
```

**Comment by jni** [comment]
@1minus1 no worries, glad we could help narrow down your problem! I was not aware of PoreSpy, which looks super cool! There's definitely bound to be code there that we want to move upstream to skimage. =)

I'll also note that we are aiming to get full or near-full support for 3D/nD regionprops within scikit-image. If you look at cell 23 of [this notebook](https://github.com/jni/skimage-tutorials/blob/monash-df2020-05-completed/lectures/three_dimensional_image_processing.ipynb) you'll see that most properties are supported in 3D already.

We also have an issue open to allow user-defined properties, see #4466. All this to say I hope that the `regionprops_3D` object becomes redundant soon!

**Comment by sciunto** [comment]
I think @emmanuelle would like to know about porespy as well, if she doesn't yet ;)

**Comment by jgostick** [comment]
@jni I agree completely about regions_props_3d becoming redundant soon!  I wrote it is a quick patch job a few years ago before the skimge version had 3d support.  I did not get the cache thing working, as @1minus1 points out here. I have a discussion going over on the [porespy repo](https://github.com/PMEAL/porespy/issues/241) about which metrics in our version are still needed, if any.
