### ISSUE TITLE
slic float32 support regression

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#4682]
## Description

As reported by @jklaise in https://github.com/scikit-image/scikit-image/issues/4675#issuecomment-626794531, `slic` no more supports `float32`.

## Way to reproduce
```python
from skimage.segmentation import slic
import numpy as np
im = np.random.rand(28, 28).astype(np.float32)
slic(im)
```

## Version information

```python
3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]
Linux-4.4.0-178-generic-x86_64-with-glibc2.10
scikit-image version: 0.16.2
numpy version: 1.18.1
```

**Comment by jklaise** [comment]
@rfezzani thanks, I've narrowed down the issue to having `pooch` as a dependency for `scikit-image=0.17.1`.If I install `scikit-image=0.16.2` without `pooch` then the tests pass (https://github.com/SeldonIO/alibi/issues/215)
