### ISSUE TITLE
single scale AffineTransform not supported

### ISSUE THREAD

**Issue by christian-rauch** [scikit-image/scikit-image#4711]
## Description

The documentation for [`AffineTransform`](https://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.AffineTransform) mentions that `scale` can be a single value.

However, when setting a scalar value, the error
```
TypeError: 'float' object is not iterable
```
is returned.

## Way to reproduce
```python
scale = 1.2
print("scalar?", np.isscalar(scale)) # True
tf = AffineTransform(scale = scale)
```

## Version information
```
3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
Linux-5.3.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.16.2
numpy version: 1.18.2
```

**Comment by jni** [comment]
@christian-rauch this feature is only present in scikit-image 0.17 and higher, which was released recently. Please update your scikit-image installation to find the feature!

**Comment by lagru** [comment]
@jni should I add a `.. versionchanged` mentioning this?

**Comment by jni** [comment]
Great idea @lagru !
