### ISSUE TITLE
Install fails on rpi due to missing imagecodecs from tifffile

### ISSUE THREAD

**Issue by natxopedreira** [scikit-image/scikit-image#4721]
Rapi 3b+ running Buster
python 3.7

Trying to install
`pip3 install scikit-image`

`ERROR: Failed building wheel for scikit-image`

Thanks!

**Comment by jni** [comment]
@natxopedreira unfortunately that's not enough information for us to figure out what is causing your problem. I suggest looking at similar issues such as #4673 and #4705, as well as others linked from those.

Additionally, lately pip has been silencing a lot of the compilation messages. I would suggest downloading the source code from GitHub, and running `python setup.py install`. That will show you the exact part of the compilation that fails, which you can then share with us.

**Comment by natxopedreira** [comment]
I compiled from source and now i get a more verbose error

`imagecodecs/_brotli.c:602:10: fatal error: brotli/types.h: No existe el fichero o el directorio
 #include "brotli/types.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1`

**Comment by hmaarrfk** [comment]
Is there a particular reason you are choosing to build from source? If so, please share we can try to help.

Building from source requires many more dependencies than just `pip`. Consider using:
https://www.piwheels.org/

I think it is included automatically in the rpi.

That error comes from building the image codecs source, not the scikti-image source.
And while I am sympathetic to your plight:
- We still don't support RPi
- I think installing from wheels is going to be of help to you.


For now:
- i suggest you install the dependencies of scikit-image one by one (we don't have that many)
- Install tifffile, but install imagecodecs-lite, not imagecodecs

You should be OK.

**Comment by natxopedreira** [comment]
Hello no particular reason @hmaarrfk .

I opened this issue because i was unable to install from pip and i get a non verbose error and i was suggested to install from source to get a verbose output

Ah sorry i didn't know you don't support RPi, i will close it then

**Comment by hmaarrfk** [comment]
So I would open a message on pip's support page.

Personally, I think pip's error messages are non-sensical for starters like you. And they are interested in feedback.

In terms of us, we are interested in offering arm builds, but for rpi (at least 32 bit) there should exist piwheels

I would add a `--prefer-binary` at the end of your install.
https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-prefer-binary

It will give you wheels, even though they are a version old.

It is likely that 0.17.2 is now on pypi before it appeared as a wheel on piwheels.

Do let me know if your install worked.

**Comment by natxopedreira** [comment]
Pip build errors are not useful, not give any clue on what to search for.

I was able to make it work with an old version 0.15.0 wheel
scikit_image-0.15.0-cp37-cp37m-linux_armv7l.whl

Maybe this will help if someone try to install this

**Comment by hmaarrfk** [comment]
I think you should be able to use 0.16

The main difference between 0.17 is that now we depend on tifffile, and tifffile is a hard dependency to build.
https://www.piwheels.org/project/scikit-image/

But again, are you using piwheels?
https://www.piwheels.org/project/imagecodecs/
where are you getting your wheels from?

**Comment by natxopedreira** [comment]
Yep, sorry i used a wheel from piwheels as you suggested, if you are interested i can try with 0.16.

Is a fresh raspbian Buster install

[https://www.piwheels.org/simple/scikit-image/scikit_image-0.15.0-cp37-cp37m-linux_armv7l.whl#sha256=c0b07fdb26928123ff1c10a949064af4c2fabadff8da2321320029fa5f2c1ce7](https://www.piwheels.org/simple/scikit-image/scikit_image-0.15.0-cp37-cp37m-linux_armv7l.whl#sha256=c0b07fdb26928123ff1c10a949064af4c2fabadff8da2321320029fa5f2c1ce7)

**Comment by hmaarrfk** [comment]
Yeah, rawpbian should enable piwheels by default.

Please leave this open as a reference that our users care about rpi.

If I had an other 10 mins, I would try to install with the flag `--prefer-binary` and see what pip finds.

Make sure you update pip first.

Pip install -U pip

That might actually solve everything

**Comment by natxopedreira** [comment]
i will try tomorrow and put here results

**Comment by hmaarrfk** [comment]
hmm, nevermind,

imagecodecs is so complicated piwheels is failing at building it.

![image](https://user-images.githubusercontent.com/90008/81980951-68b50f80-95e4-11ea-9fb4-5add23d14c34.png)
so sorry.

Yeah..... we've been considering how to depend on tifffile.

I still haven't been able to build imagecodecs myself, so i know the pain of piwheels

**Comment by natxopedreira** [comment]
I do not remeber exactly but i was able to install imagecodecs and imagecodecs-lite (not remember exact version but i can look) but when trying to install scikit-image it tries to install again and fails.... that makes me think on installing a previous version of scikit-image

**Comment by hmaarrfk** [comment]
I think the way you will have to do it is:

```
pip install numpy scipy matplotlib networkx pillow imageio PyWavelets
# Notice how we skipped tifffile
pip install --no-deps tifffile
# Gahh, too recent imagecodecs-lite is just a pointer to imagecodecs....
pip install imagecodecs-lite==2019.12.3
pip install scikit-image --no-deps
```

**Comment by hmaarrfk** [comment]
I think what I'll try to do is turn tifffile into an optional dependency, at least for arm.
I'm not too sure how to test that with our infrastructure though

**Comment by bennuttall** [comment]
I've fixed the imagecodecs build on piwheels, so it should just work now.

**Comment by bennuttall** [comment]
The error given above:

```
imagecodecs/_brotli.c:602:10: fatal error: brotli/types.h: No existe el fichero o el directorio #include "brotli/types.h" ^~~~~~~~~~~~~~~~ compilation terminated. error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

is an unfortunately uninformative error (not only because it's not in English in this case). All it means is there's a shared library missing, which can be resolved by installing an apt package.

There is a painstaking process for manual dependency calculation I documented some time ago here: https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/

However we now automate this process after building a wheel, and include them on the project pages.

To install scikit-image on Raspberry Pi, as well as `pip install scikit-image`, you need to browse the project pages of all dependencies, and install any apt dependencies listed, e.g: https://piwheels.org/project/imagecodecs/

**Comment by natxopedreira** [comment]
yes sorry is in spanish, means no file or directory.

I tried installing apt brotli but not work i have to downgrade to scikit-image 0.15 using a wheel from your site.

Thanks for maintaining that site, its great!

**Comment by bennuttall** [comment]
You need to install more than just brotli - imagecodecs has a whole load of dependencies listed here: https://piwheels.org/project/imagecodecs/

**Comment by hmaarrfk** [comment]
@bennuttall i see, you don't use typically wheel packaging standards that would embed all libraries in the package itself.

One day I'll see if we can adapt our manylinux builders to make arm stuff.

Just hard to convince myself to do it when the conda-forge process has been much more of a challenge than I ever anticipated.

Thanks for the quick turnaround!

**Comment by hmaarrfk** [comment]
I'm going to consider this issue resolved from our end.

@natxopedreira if the instructions suggested by @bennuttall work, please close this issue.

**Comment by bennuttall** [comment]
> @bennuttall i see, you don't use typically wheel packaging standards that would embed all libraries in the package itself.

I think the latest manylinux wheel standard has only recently been finalised, and is only supported by the newest versions of pip - we need piwheels to work out the box with pip from Debian.

Plus manylinux2014 doesn't support armv6 (PI 1/Zero arch).

Might be something to consider for future (many the next Debian release).

**Comment by bennuttall** [comment]
If you want to look into producing a manyllinux2014 armv7 wheel, and/or automating testing on a Pi, I can recommend the Mythic Beasts Pi cloud (which is what all of piwheels is running on): https://www.mythic-beasts.com/order/rpi

**Comment by natxopedreira** [comment]
Yep i installed all imagecodec dependences, and im able to install imagecodecs:
`sudo apt install libsnappy1v5 liblcms2-2 libblosc1 libopenjp2-7 libtiff5 libaec0 libwebp6 libzstd1 libjxr0 libjbig0`

I uninstalled my previous version of scikit-image and im able to install again with `pip3 install scikit-image`

Thanks to all

**Comment by hmaarrfk** [comment]
@bennuttall i take that that is your company? Nice stuff. Well laid out and a clear value!

Are are all getting hit really hard by these giant cloud providers that are able to provide free options?

At conda-forge, we've been using drone for native builds (64 bit I think) as well as qemu on Azure. We tried shippable, but the lack of the free API killed it ;)

**Comment by bennuttall** [comment]
Not my company, they host raspberrypi.org, the Raspbian archive and they donate hosting to the piwheels project.

They provide an API for Pi hosting so you can spin one up for a specific job and pay minutely - might be worth looking at.
