### ISSUE TITLE
Broken CI on py3.8 and Windows following Cython 0.29.18 release

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4727]
See for example https://ci.appveyor.com/project/scikit-image/scikit-image/build/job/ialf1e7b3wni5wh7
Build with Cython 0.29.17 were fine, 0.29.18 was released yesterday.

The error is in `restoration/_unwrap_1d.pyx`,  `M_PI` is not recognized (it's imported as `from libc.math cimport M_PI`).

**Comment by sciunto** [comment]
First, I do not see anything related in the [changelog.](https://github.com/cython/cython/blob/master/CHANGES.rst#02918-2020-05-18)

**Comment by emmanuelle** [comment]
Right. We might have to ask for help in the Cython repo :-). Wouldn't be the first time ;-).

**Comment by sciunto** [comment]
I'll do
