### ISSUE TITLE
does scikit-image have C or C++ version code?

### ISSUE THREAD

**Issue by sofzh** [scikit-image/scikit-image#4728]
## Description
Hello, does scikit-image have C or C++ version code?

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by grlee77** [comment]
The question is a little unclear to me. Are you asking whether we use C or C++ (or both)? Or are you asking about what versions of C/C++ standards are required to compile?

scikit-image has quite a bit of Cython code which gets compiled to either C or C++ (we have instances of both, although C is more common).
Cython->C++ example: `./skimage/morphology/_skeletonize_3d_cy.pyx`
Cython->C example: `./skimage/morphology/_watershed.pyx`

There are also a small number of native C files such as `skimage/restoration/_unwrap_2d.c`

**Comment by sofzh** [comment]
> The question is a little unclear to me. Are you asking whether we use C or C++ (or both)? Or are you asking about what versions of C/C++ standards are required to compile?
> 
> scikit-image has quite a bit of Cython code which gets compiled to either C or C++ (we have instances of both, although C is more common).
> Cython->C++ example: `./skimage/morphology/_skeletonize_3d_cy.pyx`
> Cython->C example: `./skimage/morphology/_watershed.pyx`
> 
> There are also a small number of native C files such as `skimage/restoration/_unwrap_2d.c`

sry for not specify the question. I want to know if a standard version of C or C++ code is provided, not this Python or Cython version code

**Comment by sciunto** [comment]
I guess you mean whether we have a port in pure C/C++. The answer is no. You might think about opencv, but our history and approach is different.
