### ISSUE TITLE
RuntimeWarning in blob.py (division by zero)

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4729]
see for example the warning in https://scikit-image.org/docs/dev/auto_examples/features_detection/plot_blob.html#sphx-glr-auto-examples-features-detection-plot-blob-py 

The warning is initiated in the `_blob_overlap` function.

Also mentioned in the forum https://forum.image.sc/t/runtime-warning-with-blob-detection-when-threshold-is-too-low/37965

**Comment by emmanuelle** [comment]
Oh this `imagesc-bot` is nice :-).

**Comment by dsandeep0138** [comment]
@emmanuelle when sigma of both the blobs are 0 (i.e., ``radius of blobs = sqrt(2) * sigma = 0``) we can return the _blob_overlap as 0.0 right? Please check below which would resolve the issue and let me know your comments.

```
if blob1[-1] == 0 and blob2[-1] == 0:
    return 0.0
elif blob1[-1] > blob2[-1]:
    max_sigma = blob1[-sigma_dim:]
    r1 = 1
    r2 = blob2[-1] / blob1[-1]
else:
    max_sigma = blob2[-sigma_dim:]
    r2 = 1
    r1 = blob1[-1] / blob2[-1]
```

**Comment by jni** [comment]
@dsandeep0138 I think that fix would work! If you could open a PR (including a test), that would be wonderful!
