### ISSUE TITLE
warp on rotated image provides wrong results

### ISSUE THREAD

**Issue by christian-rauch** [scikit-image/scikit-image#4732]
## Description
Function `skimage.transform.warp` with `mode='wrap'` shows warped image feautres twice on a rotated image.

## Way to reproduce
```python
#!/usr/bin/env python3
from skimage.transform import AffineTransform, warp
import sys
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
if __name__ == "__main__":
    img = np.array(Image.open(sys.argv[1]))
    plt.figure("orig")
    plt.imshow(img)
    tf = AffineTransform(rotation = 0.42787830409943145)
    tf_f = lambda x : warp(x, tf, mode='wrap')
    img = tf_f(img)
    plt.figure("tf")
    plt.imshow(img)
    plt.show()
```

With the test image:
![test](https://user-images.githubusercontent.com/8226248/82443485-7dd4e700-9a99-11ea-93b1-c7c469014dda.png)
I get a rotation:
![tf](https://user-images.githubusercontent.com/8226248/82443597-a8bf3b00-9a99-11ea-8fa6-7c75efdde488.png)
with a wrong warp. Features in the image (such as the dark spot on the lock) should no appear twice when warped around image edges.

I've not seen this issue with translations.

## Version information
```python
3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
Linux-5.3.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.17.2
numpy version: 1.18.2
```

**Comment by emmanuelle** [comment]
Hi @christian-rauch I don't understand why features should not appear twice : If you draw the image padded with repetitions of itself and you rotate this padded image around the origin of the initial image it is possible to have the same object twice in the rotated image, if the original image is not square.

**Comment by christian-rauch** [comment]
You are right. For some reason, I had in mind that object should rotate about its centre. Sorry, my bad :facepalm: .

What I actually expected was that the image first rotates about the object centre and then potentially translates with edge wrapping.
