### ISSUE TITLE
Turn checkmarks in pull request templates into bullet points

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#4741]
My impression is that the checkmarks in our pull request template are very rarely used. Looking at the [list of merged pull requests](https://github.com/scikit-image/scikit-image/pulls?q=is%3Apr+is%3Amerged) almost all of them mark 0 out of 3 or 8 tasks as completed and those that don't usually ignore the template altogether. 

In my view we wouldn't loose anything by turning them into bullet points but would allow the feature and the UI hints to stand out more for contributors who actually care and do use them.

@scikit-image/core any strong opinions?

**Comment by jni** [comment]
I don't have a strong opinion either way, but I agree that people have developed blindness to the templates.

**Comment by hmaarrfk** [comment]
What would you like to use the list for? Is there a good use of checkmarks you would like to move to?

Maybe just leave: "title makes sense" in there as checkmark
to generate the release notes more cleanly.

That seems like the only important one.

**Comment by stefanv** [comment]
I don't have strong feelings either way.

**Comment by sciunto** [comment]
If github could put a checklist close to the merge button, and mandatory to check, that would make checklists useful.

**Comment by lagru** [comment]
> What would you like to use the list for? Is there a good use of checkmarks you would like to move to?

@hmaarrfk I've found checklists quite useful for large PRs I was working on. My first PR to scikit-image #3022 might be a good example (if a bit overdone) where I used it to highlight talking points and decision for the reviewers. 

Basically I hope to make the few places where a checklist is actually useful more visible by removing them from a template.

> If github could put a checklist close to the merge button, and mandatory to check, that would make checklists useful.

Agreed, that could be really powerful.

**Comment by hmaarrfk** [comment]
Alright, curious to see what you want to come up with for a succinct checklist.

**Comment by lagru** [comment]
Oh, perhaps I wasn't precise enough earlier. I don't want to change the content, just remove the checkboxes in favor of bullet points.

Please see the PR #4747.

**Comment by kleinerELM** [comment]
Since I made my first PR last week and I am fairly new to git/github, some things were initially not completely clear for me:
Maybe it would be nice to change **Checklist** to **Checklist for Author**, at least if the checklist is explicitly directed to authors. If autors have to check these boxes themself, then add a comment like this after the Author checklist:
_Please change [ ] to [x] if checkpoint is fulfilled_
