### ISSUE TITLE
Deprecate edge cases in peak_local_max

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#4749]
## Description

While investigating for #3990, I found that `peak_local_max` manages two edge cases that can be deprecated:

- `min_distance=0` and `footprint=None`
- `footprint.size=1`

in this cases `peak_local_max` is equivalent to applying a threshold. I think that these settings must be forbidden.

## Version information

```python
3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0]
Linux-4.4.0-179-generic-x86_64-with-debian-stretch-sid
scikit-image version: 0.18.dev0
numpy version: 1.18.4

```

**Comment by sciunto** [comment]
The issue sounds reasonable. Please, do not forget to add a meaningful task in TODO.txt :)

**Comment by alexdesiqueira** [comment]
Hey y'all, sorry for missing this.
I personally don't like the "forbidden" word, and the `ValueError` we're proposing to return in #4760. I will discuss it better there.
