### ISSUE TITLE
CI broken following dask 2.17.0 release

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4757]
See for example https://travis-ci.org/github/scikit-image/scikit-image/jobs/691743493 all tests using dask are failing. I'm currently investigating, I think it's a problem related to dask and numpy: I can't reproduce in an env with numpy 1.16 and new dask but I can reproduce with numpy 1.18 and new dask.

**Comment by jni** [comment]
It broke napari also, here's the cause:

https://github.com/dask/dask/pull/6198#issuecomment-629993387

the quick fix is to add PyYAML to our test dependencies. I don't know if there's a slow-but-better fix.

**Comment by emmanuelle** [comment]
or we could forbid 2.17.0 in our requirements. I guess the dask team will push a patch release since Jim seemed to consider that this was a bug on their side.

**Comment by jni** [comment]
Yep, I agree. Looking at the discussion and the fact that many packages are referencing those issues, I expect that this will be solved upstream with the next release.

**Comment by emmanuelle** [comment]
PR open!
