### ISSUE TITLE
Arctan2 being passed arguments in wrong order in Approximate_polygon

### ISSUE THREAD

**Issue by Styxny** [scikit-image/scikit-image#4759]
## Description
I think arguments being passed to arctan2 in approximate_polygon are swapped. Looking at lines 42-47 in _polygon.py it appears r0,r1 are the x coordinates from the input coordinates, but their difference is passed in the y value slot of np.arctan2 in line 49.

```python
    while not end_of_chain:
        start, end = pos_stack.pop()
        # determine properties of current line segment
        r0, c0 = coords[start, :]
        r1, c1 = coords[end, :]
        dr = r1 - r0
        dc = c1 - c0
        segment_angle = - np.arctan2(dr, dc)
        segment_dist = c0 * np.sin(segment_angle) + r0 * np.cos(segment_angle)
```

## Version information
```python
3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.18362-SP0
scikit-image version: 0.17.2
numpy version: 1.18.2

```

[Link to numpy arctan2 doc](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html?highlight=arctan2#numpy.arctan2)

**Comment by jni** [comment]
@Styxny thanks for the report! After doing a quick review I think I agree with you, although there might be some complexity because of the way some older skimage functions are written using x/y coordinates rather than row/column. Have you encountered a bug/weird behaviour because of this?

**Comment by jl-wynen** [comment]
Tested with switched args, it doesn't work. But this is because the rest of `approximate_polygon` assumes the current argument order.
It is possible to make additional modifications and recover the current (correct AFAIK) behaviour:
```.py
        segment_angle = - np.arctan2(dc, dr)
        segment_dist = r0 * np.sin(segment_angle) + c0 * np.cos(segment_angle)
# [...]
        segment_dists[perp] = np.abs(
            segment_coords[perp, 0] * np.sin(segment_angle)
            + segment_coords[perp, 1] * np.cos(segment_angle)
            - segment_dist
        )
```
current:
```.py
        segment_angle = - np.arctan2(dr, dc)
        segment_dist = c0 * np.sin(segment_angle) + r0 * np.cos(segment_angle)
# [...]
        segment_dists[perp] = np.abs(
            segment_coords[perp, 0] * np.cos(segment_angle)
            + segment_coords[perp, 1] * np.sin(segment_angle)
            - segment_dist
        )
```
All that happened here is that I switched the meaning of 'rows' and 'columns' inside the algorithm. But this does not affect the result.

I suggest to close as there does not seem to be a bug here.

**Comment by lagru** [comment]
@jl-wynen, thanks for investigating and the write up. I tend to agree. So I'll close this for now. @Styxny, you are welcome to reopen this if you think we are missing something here or want to add to this. Thanks everyone. :)
