### ISSUE TITLE
phase_cross_correlation with NaN pixels returns an invalid result

### ISSUE THREAD

**Issue by GenevieveBuckley** [scikit-image/scikit-image#4763]
## Description
The `skimage.registration.phase_cross_correlation()` function returns an invalid result if one of the input images contains NaN pixels. I think an error should be raised here instead, suggesting the user pass in a mask array to exclude the NaNs.

Alternatively, another solution could be modifying the function to handle masking the NaN pixels itself. I'd be happy to implement this as a feature.

## Way to reproduce
```python
import numpy as np
from skimage import data
from skimage.registration import phase_cross_correlation
from skimage.util import img_as_float

reference_image = img_as_float(data.camera())
EXPECTED_SHIFT = 20  # PIXELS
moving_image = np.roll(reference_image, EXPECTED_SHIFT, axis=1)

result1 = phase_cross_correlation(reference_image, moving_image)
print("Result 1 (no NaN pixels) - ", result1)

# Add a single NaN pixel to one of the images
reference_image[0][0] = np.nan

result2 = phase_cross_correlation(reference_image, moving_image)
print("Result 2 (with NaN pixels) - ", result2)

# Mask out the NaN pixels
mask = ~np.isnan(reference_image)
result3 = phase_cross_correlation(reference_image, moving_image, reference_mask=mask)

print("Result 3 (masked NaN pixels) - ", result3)
```

Which gives us this output:
```
Result 1 (no NaN pixels):-  (array([  0., -20.]), 2.1073424255447017e-08, 8.150775661402915e-18)
Result 2 (with NaN pixels) -  (array([0., 0.]), nan, nan)
Result 3 (masked NaN pixels) -  [  0. -20.]
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.17134-SP0
scikit-image version: 0.18.dev0
numpy version: 1.16.4
```

**Comment by rfezzani** [comment]
Thank you @GenevieveBuckley for your report. I am pretty sure that a majority of functions in `skimage` are sensitive to NaNs... =)
I consider this is more like an edge case that shouldn't be managed internally, since users can handle it as you did in the example that you provided. But this is of course open to discussion ^^

**Comment by hmaarrfk** [comment]
i don't think you should raise an informative message.

If you do want to, could you please add a switch so as to remove the check.

Checking for NaN is expensive on imaegs as it often requires a full pass of the memory in python.

**Comment by alexdesiqueira** [comment]
@hmaarrfk I'd not be fond of a switch for NaN's, please let's think on decluttering and tidiness :smile: However, now that you're telling that, this would be expensive indeed.
I would be in favor of 1. testing all data before entering in every function, or 2. not testing at all and returning an error when bumping into it — it seems your data cannot be processed... for 2, how about some tutorials on handling NaN's on images?
Any ideas? I think the others on @scikit-image/core would want to weigh on that too.

**Comment by hmaarrfk** [comment]
The problem fundamentally, is that `NaN` is not a real number. In situations where "averaging" is inherently part of the algorithm, yes ignoring a few pixels will give the user the expected result.
But for me, this goes back to

The user provided junk data in, we should not be expected to provide output.

Numpy has `nansafe` functions. They don't perform as well as their standard equivalents.
```
In [21]: %timeit np.sum(a)                                                                               
398 µs ± 10.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [22]: %timeit np.nansum(a)                                                                            
1.55 ms ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Should we ignore NaNs? I feel like it is emblematic of a deeper problem in the user's code or their understanding of their particular dataset.

If you want to check for NaN, you might as well just use something faster like:

```
In [17]: a = np.ones((1024, 1024))                                                                       

In [18]: a[-1, -1] = np.nan                                                                              

In [19]: %timeit np.isnan(a.sum())                                                                       
395 µs ± 6.66 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [20]: %timeit np.isnan(a).any()                                                                       
486 µs ± 19.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

```

The truth is, that this is a non-negligible cost, however you look at it.

Numpy has a whole slew of `nansafe` operations:
https://numpy.org/doc/stable/reference/generated/numpy.nanmax.html

Astopy also provides switches with `mask` 
https://docs.astropy.org/en/stable/api/astropy.convolution.convolve.html

Generally speaking, I think the `NaN` safe operation is a bandaid operation to help the particular issue a particular user encountered. NaN-safe operations have their place, but they need to be able to be disabled.
