### ISSUE TITLE
Is cross_correlate_masked() now superseded by phase_cross_correlation() with kwargs?

### ISSUE THREAD

**Issue by GenevieveBuckley** [scikit-image/scikit-image#4765]
## Description

The `__all__` dunder for the scikit-image registration module contains two functions: 
* `optical_flow_tvl1`, and
* `phase_cross_correlation`.

But there is also a function named `cross_correlate_masked` in `skimage/registration/_masked_phase_cross_correlation.py`. 

Should `cross_correlate_masked()`:
1. Be added to the `__all__` dunder of the module?
2. Be marked as deprecated and removed in line with the scikit-image deprecation policy.
3. Something else?

**Comment by rfezzani** [comment]
> Is cross_correlate_masked() now superseded by phase_cross_correlation() with kwargs?

Yes, this change was introduced in #4503. `feature.cross_correlate_masked` is already deprecated ;)

**Comment by GenevieveBuckley** [comment]
Oh good - I didn't see a deprecation warning when I ran it, but I did import it from `skimage.registration` instead of `skimage.feature`. Thanks!
