### ISSUE TITLE
Missing attribute 'offsets' in skimage.graph.MCP_Geometric

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#4766]
## Description

Context for this issue is this SO question:

https://stackoverflow.com/questions/62135639/mcp-geometrics-for-calculating-marketsheds

While investigating the question, I created an `skimage.graph.MCP_Geometric` object, which inherits from `skimage.graph.MCP`. You can see that `MCP` defines the offsets attribute in this line:

https://github.com/scikit-image/scikit-image/blob/f71be82423e73cda4f3026a0eb656614db937bbc/skimage/graph/_mcp.pyx#L330

and that `MCP_Geometric.__init__` calls `MCP.__init__` here:

https://github.com/scikit-image/scikit-image/blob/f71be82423e73cda4f3026a0eb656614db937bbc/skimage/graph/_mcp.pyx#L747

And yet:

```python
import numpy as np
from skimage import graph

image = np.array([[1, 1, 2, 2], [2, 1, 1, 3], [3, 2, 1, 2], [2, 2, 2, 1]])
mcp = graph.MCP_Geometric(image)
print(mcp.offsets)
```
results in

```pytb
AttributeError: 'skimage.graph._mcp.MCP_Geometric' object has no attribute 'offsets'
```

I don't know if this is because these classes are defined in Cython, or maybe I'm missing something obvious. But maybe these class definitions can be moved to Python.

## Version information

```
3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]
Linux-4.15.0-29-generic-x86_64-with-glibc2.10
scikit-image version: 0.18.dev0
numpy version: 1.19.0rc1
```

**Comment by jni** [comment]
I'll note that the offsets attribute should be public, as it is the only way to interpret the `traceback` return value.

**Comment by jjerphan** [comment]
Hi @jni

I am interested in solving this issue.
Should other attributes be made public? :slightly_smiling_face:
