### ISSUE TITLE
segmentation.random_walker error, masking problem

### ISSUE THREAD

**Issue by gletreut** [scikit-image/scikit-image#4770]
## Description
The method segmentation.random_walker produces an error when passing labels with negative values. The code below worked with the `segmentation/random_walker.py` file from commit d61625b3950ffa9ee3d59e91295b49357be03b27. It produces an error starting from commit 8f76f0fb48908ba2ca92816d3611bba5cd09b998 (the next one modifying the file). I am attaching below the arrays used for the image and the labels in calling the random_walker method.
[image.txt](https://github.com/scikit-image/scikit-image/files/4720149/image.txt)
[labels.txt](https://github.com/scikit-image/scikit-image/files/4720150/labels.txt)

## Way to reproduce
The error can be reproduced using the following code:
```
import numpy as np
from skimage import segmentation

labels = np.loadtxt('labels.txt')
img = np.loadtxt('image.txt')

labeled_image = segmentation.random_walker(img, labels, mode='bf', beta=130., return_full_prob=False)
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.8.2 (default, Apr 23 2020, 14:32:57) 
[GCC 8.3.0]
Linux-4.15.0-101-generic-x86_64-with-glibc2.2.5
scikit-image version: 0.18.dev0
numpy version: 1.18.4
```

**Comment by rfezzani** [comment]
Thank you @gletreut for reporting this bug. I had a look at you data and found that `labels` contains isolated areas... I will investigate in this direction ;)
