### ISSUE TITLE
sigma_range not used in denoiser calibration examples

### ISSUE THREAD

**Issue by notmatthancock** [scikit-image/scikit-image#4779]
The variable `sigma_range` is defined in both tutorials, but a different range and in-line instantiation of the sigma range is used when the `parameter_ranges` dict is defined:

https://github.com/scikit-image/scikit-image/blob/f71be82423e73cda4f3026a0eb656614db937bbc/doc/examples/filters/plot_j_invariant.py#L39-L41

https://github.com/scikit-image/scikit-image/blob/f71be82423e73cda4f3026a0eb656614db937bbc/doc/examples/filters/plot_j_invariant_tutorial.py#L44-L46 

In the latter "full" tutorial, this seems to be limited to just the wavelet denoiser calibration portion, which appears to be a copy/paste of the former "short" tutorial.

**Comment by emmanuelle** [comment]
Hi @notmatthancock thanks for reporting this, it indeed looks like we had a copy and paste mistake here! Could you be interested in correcting this and submitting a pull request? Thanks either way :-).

**Comment by notmatthancock** [comment]
> Could you be interested in correcting this and submitting a pull request? 

Yep: https://github.com/scikit-image/scikit-image/pull/4792
