### ISSUE TITLE
label2rgb only color the contour not the area

### ISSUE THREAD

**Issue by liang-minhui** [scikit-image/scikit-image#4787]
## I'm trying to use label2rgb to color different segments, but only color the contour, not the area.

    def edgedetect (vadd):
    cap = cv2.VideoCapture(vadd)
    fgbg = cv2.createBackgroundSubtractorMOG2()

    while (1):
     ret, frame = cap.read()
     fgmask = fgbg.apply(frame)
     retthre,fgthre = cv2.threshold(fgmask,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
     fgclose = skm.closing(fgthre, square(4))
     fgopen = skm.opening(fgclose, square(4))
     fgclose = skm.closing(fgopen, square(15))
     fgcanny = cv2.Canny(fgclose, 500,600)

     #aboved is for object segmentation, below to color different objects

     fglabel = skmeas.label(fgcanny)
     overlay = label2rgb(fglabel, image=fgclose, bg_label=0)
     cv2.imshow('fgmask', overlay)

     # label2rgb

     k = cv2.waitKey(30) & 0xff
     if k == 27:
        break
 
my result:
<img width="142" alt="Screenshot 2020-06-12 at 5 32 33 PM" src="https://user-images.githubusercontent.com/66628745/84488499-db440880-acd2-11ea-8a79-e21a8ad9e292.png">

what I want:
<img width="232" alt="Screenshot 2020-06-12 at 5 33 58 PM" src="https://user-images.githubusercontent.com/66628745/84488552-f282f600-acd2-11ea-83d6-ae6ebec561be.png">

**Comment by rfezzani** [comment]
I think that in your example
```python
 fglabel = skmeas.label(fgcanny)
```
should be
```python
 fglabel = skmeas.label(fgclose)
```

**Comment by liang-minhui** [comment]
> I think that in your example
> 
> ```python
>  fglabel = skmeas.label(fgcanny)
> ```
> 
> should be
> 
> ```python
>  fglabel = skmeas.label(fgclose)
> ```

thanks, that works.
