### ISSUE TITLE
Monitor the decision taken by sphinx-gallery dev on the thumbnail size in future release

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4801]
## Description
See https://github.com/sphinx-gallery/sphinx-gallery/issues/717

We recently set a reduced thumbnail size to improve the loading time of our gallery. S-G might change its default behavior and we may want to re-adapt our choice.

**Comment by timhoffm** [comment]
The default changed from size (400, 280) to (320, 224), i.e. twice the CSS value to render nicely on HiDPI screens. See https://github.com/sphinx-gallery/sphinx-gallery/pull/719.

**Comment by sciunto** [comment]
many thanks @timhoffm !
