### ISSUE TITLE
threshold_otsu check for single-colour is slow on large arrays

### ISSUE THREAD

**Issue by OGordon100** [scikit-image/scikit-image#4811]
Currently in the threshold_otsu function, the code checks if the image has a single colour

    if image.min() == image.max():
        raise ValueError("threshold_otsu is expected to work with images "
                         "having more than one color. The input image seems "
                         "to have just one color {0}.".format(image.min()))`

However, for extremely large arrays min and max become increasingly slow, performing a basically identical sorting algorithm twice over.

I propose replacing this with a much simpler logical check, which will inevitably be more efficient

    np.all(image == image[0])

Checking with timeit:

    import timeit
    setup = '''
    import numpy as np
    
    arr = np.zeros((10000,10000))
    '''

    timeit.timeit("arr.min() == arr.max()", setup=setup, number=50)
    5.534767805999763

    timeit.timeit("np.all(arr == arr[0])", setup=setup, number=50)
    2.377352842999244

As expected, this time disparity gets greater and greater with increasing size.

Further, I disagree with the error statement. It seems very... unconfident in the code! "We think it's maybe possibly not the right thing, so let's throw an error, whatevs". If we genuinely do not have faith in what that code is doing, it should not be public code. It should be more assertive. I propose "threshold_otsu cannot threshold single-valued images", or better yet "cannot threshold single-valued images", as the former implies that other methods can threshold single-valued images - which is of course nonsense!

**Comment by emmanuelle** [comment]
Hi @OGordon100, thanks for your interest in scikit-image. Interestingly, when I tried on my local machine the two checks take the same time
```
In [1]: arr = np.zeros((10000, 10000))                                          

In [2]: %timeit arr.min() == arr.max()                                          
53.9 ms ± 56.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]: %timeit np.all(arr == arr[0])                                           
60 ms ± 836 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
So the "inevitably more efficient" should be moderated :-). You are right that this check is not completely satisfying. What we would like is a function which would loop through the array and exit as soon as two different values have been found. That said, this check represents 5% of the total computation time for threshold_otsu (for this specific array and on my machine), which is at the same time not negligible but probably not worth writing a cython function for the check.

**Comment by jni** [comment]
@emmanuelle @OGordon100 I think the problem is that `arr[0]` is an entire row so we are doing a rather expensive broadcasting here. It *is* faster when we get *just* the first element:

```python
In [3]: arr = np.random.random((10000, 10000))

In [4]: %timeit arr.min() == arr.max()
119 ms ± 2.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [5]: %timeit np.all(arr == arr.ravel()[0])
89.4 ms ± 368 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: %timeit np.all(arr == arr[0])
107 ms ± 304 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Having said this, maybe we shouldn't even raise a ValueError and simply return the input value?

**Comment by jni** [comment]
@OGordon100 A side note:

> If we genuinely do not have faith in what that code is doing, it should not be public code.

The free and open source community has a different philosophy: all code should be public, giving everyone the opportunity to improve it in perpetuity — as you are doing now! Thank you! 😊

**Comment by rfezzani** [comment]
> Having said this, maybe we shouldn't even raise a ValueError and simply return the input value?

:+1: good point @jni!

**Comment by OGordon100** [comment]
> @emmanuelle @OGordon100 I think the problem is that arr[0] is an entire row so we are doing a rather expensive broadcasting here. It is faster when we get just the first element:

@jni Hold on, I thought arr[0] was just the first element? Oh darn I'm stupid. So so stupid! I'd +1 using ravel, or if we want to enforce 2D inputs instead of 3D, we could just use arr[0,0]? 

I know the code accepts 3d inputs (just with a warning), but I don't think it actually runs with 3D inputs before the PR (plus there's no tests for it). Potentially it makes sense to raise another PR for changing the warning to a hard error, but that's another discussion

**Comment by OGordon100** [comment]
> @emmanuelle @OGordon100 I think the problem is that `arr[0]` is an entire row so we are doing a rather expensive broadcasting here. It _is_ faster when we get _just_ the first element:
> 
> ```python
> In [3]: arr = np.random.random((10000, 10000))
> 
> In [4]: %timeit arr.min() == arr.max()
> 119 ms ± 2.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
> 
> In [5]: %timeit np.all(arr == arr.ravel()[0])
> 89.4 ms ± 368 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
> 
> In [6]: %timeit np.all(arr == arr[0])
> 107 ms ± 304 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
> ```
> 
> Having said this, maybe we shouldn't even raise a ValueError and simply return the input value?

Would make sense, except the function currently returns a single valued intensity threshold, not a 2D thresholded array. So I think it makes more sense to just error out, as it may cause some issues for users using the output to create a thresholded array as a result.

**Comment by rfezzani** [comment]
> except the function currently returns a single valued intensity threshold, not a 2D thresholded array.

You are right, but in this case, returning `image[0]` instead of raising still makes sense :)

**Comment by OGordon100** [comment]
> Hi @OGordon100, thanks for your interest in scikit-image. Interestingly, when I tried on my local machine the two checks take the same time
> 
> ```
> In [1]: arr = np.zeros((10000, 10000))                                          
> 
> In [2]: %timeit arr.min() == arr.max()                                          
> 53.9 ms ± 56.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
> 
> In [3]: %timeit np.all(arr == arr[0])                                           
> 60 ms ± 836 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
> ```
> 
> So the "inevitably more efficient" should be moderated :-). You are right that this check is not completely satisfying. What we would like is a function which would loop through the array and exit as soon as two different values have been found. That said, this check represents 5% of the total computation time for threshold_otsu (for this specific array and on my machine), which is at the same time not negligible but probably not worth writing a cython function for the check.

Surely that would give a really high risk of false positives for the check? If you have an image with integer values (very likely if converting a loaded colour image),, then it's almost inevitable there will be many datapoints at the same pixel intensity that would still want to be thresholded

**Comment by OGordon100** [comment]
> > except the function currently returns a single valued intensity threshold, not a 2D thresholded array.
> 
> You are right, but in this case, returning `image[0]` instead of raising still makes sense :)

Good point. Maybe return it, along with a warning?

**Comment by jni** [comment]
> if we want to enforce 2D inputs

We do not. =)

> but I don't think it actually runs with 3D inputs before the PR

It does:

```python
In [1]: arr = np.random.random((64, 64, 64))
In [2]: from skimage import filters
In [3]: filters.threshold_otsu(arr)
Out[3]: 0.4980475443444041
```

> (plus there's no tests for it)

Sure, that's a problem. =)

> as it may cause some issues for users using the output to create a thresholded array as a result.

Well, users will get either all foreground or all background, depending on their choice of operator. I think that's correct behaviour. Having said this, let's just keep the current behaviour for now, and make a separate issue for our policy for flat images.

**Comment by jni** [comment]
> Surely that would give a really high risk of false positives for the check? 

I think you misunderstand @emmanuelle's proposal. If all the pixels are identical, we have to traverse the whole image to make sure. But if the image is `np.random.random((10000, 10000))`, then after observing two pixels you can already be sure that you don't have a flat image.

**Comment by jni** [comment]
> Good point. Maybe return it, along with a warning?

LOL. As I said, I'd be ok with this. Indeed some of our functions already do this so it would be consistent:

```python
In [4]: image = np.ones((5, 5))

In [5]: filters.threshold_li(image)
Out[5]: 1.0
```

I might even skip the warning.

**Comment by OGordon100** [comment]
> I might even skip the warning.

Good point! There's no point deliberately making something inconsistent, and I don't think it's worth updating the other functions to match a warning. 

Should I go ahead and change to just return it then?
