### ISSUE TITLE
Make level parameter optional in measure.find_contours

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4813]
## Description

I think that we could put a default value to level in find_contours. I would suggest (image.max() - image.min())/2. This would make this function able to be used with an image and I think this default value is meaningful.

I'm open to discussion.

**Comment by emmanuelle** [comment]
:+1: for having default values whenever it is possible! The default which you are suggesting works well for binary arrays.

**Comment by sciunto** [comment]
cool.

**Comment by emmanuelle** [comment]
I added the good first issue label because it would indeed be a good first issue, but we need to make a decision first. I'm :+1:

**Comment by jni** [comment]
I'm :+1: also. The mean or median might also be good defaults.

**Comment by sciunto** [comment]
I started to play with this function a lot recently, and my first choice was the mean as you suggested. Then, it appeared to be a bad idea in practice. On an image sequence, although the light conditions were invariant, the quantity of bright and dark regions were changing, which changed the level significantly. This is not meaningful at all in my application.

Perhaps there are applications where mean or median can be relevant, but then, I thought max/min to be more robust from the universality perspective.

**Comment by jni** [comment]
Sure, I was going off intuition, not any actual experience!

**Comment by emmanuelle** [comment]
I would not say that using max and min is more robust because max and min are very sensitive to noise and outliers. For me the strongest argument in favor of using min and max is that it works well for binary arrays.

**Comment by emmanuelle** [comment]
Ming is working on this issue at the sprint.

**Comment by rubywerman** [comment]
Mentioned this idea in the PR listed above ^ but will put here for the sake of discussion. Could it be beneficial to have two default values, (max - min) / 2 and median, depending on whether it's a binary or float array?

**Comment by sciunto** [comment]
I find this disturbing.

**Comment by jni** [comment]
Disturbing seems a bit strong! 😂 

Another suggestion, in light of Emma's comments: the "robust" min and max would be `np.quantile(image, (0.005, 0.995))`, for example. Perhaps that can be the default?
