### ISSUE TITLE
IndexError when calling hough_line_peaks

### ISSUE THREAD

**Issue by Mark531** [scikit-image/scikit-image#4814]
## Description
Sometimes, when the list of tested angles passed to Hough_line is too narrow, hough_line_peaks triggers an IndexError.

## Way to reproduce
```
tested_angles = np.array([np.pi / 2])
h, theta, d = hough_line(image, theta=tested_angles)
accum, angles, dists = hough_line_peaks(h, theta, d, threshold=2)
```
triggers
```
Traceback (most recent call last):
  File "<ipython-input-147-b875ad1f50fd>", line 3, in <module>
    accum, angles, dists = hough_line_peaks(h, theta, d, threshold=2)
  File "C:\Users\Mark4\anaconda3\lib\site-packages\skimage\transform\hough_transform.py", line 63, in hough_line_peaks
    num_peaks=num_peaks)
  File "C:\Users\Mark4\anaconda3\lib\site-packages\skimage\feature\peak.py", line 316, in _prominent_peaks
    img_max[ycoords_nh, xcoords_nh] = 0
IndexError: index -9 is out of bounds for axis 1 with size 1
```

But
```
tested_angles = np.linspace(np.pi / 2 - 0.01, np.pi / 2  + 0.01, 100)
h, theta, d = hough_line(image, theta=tested_angles)
accum, angles, dists = hough_line_peaks(h, theta, d, threshold=2)
```
works.

I don't understand what the problem is, it seems that no line is found with the given angle. But in that case, the Hough accumulator should stay to 0. I uploaded the image that is needed to reproduce the issue. It can be loaded with `numpy.load`.

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.18362-SP0
scikit-image version: 0.16.2
numpy version: 1.18.1
```
[image.zip](https://github.com/scikit-image/scikit-image/files/4861273/image.zip)

**Comment by jni** [comment]
I can reproduce this on master with just a random image:

```python
import numpy as np
from skimage.transform import hough_line, hough_line_peaks

image = np.random.random((512, 512))
tested_angles = np.array([np.pi / 2])
h, theta, d = hough_line(image, theta=tested_angles)
accum, angles, dists = hough_line_peaks(h, theta, d, threshold=2)
```

gives me the exact same error.

Thanks for the report @Mark531, we'll investigate!

**Comment by emmanuelle** [comment]
Thanks @Mark531. The problem comes from the `min_xdistance` parameter of ` _prominent_peaks` which is set to the `min_angle` parameter of `hough_line_peaks` (here 10 degrees), while the size of the accumulator array is `(1450, 1)`. I'd suggest to transform 
```
min_angle = min(min_angle, hspace.shape[1])
```
before calling `_prominent_peaks` in `hough_line_peaks`. In the example of @jni, adding `min_angle=1` solves the issue.

**Comment by Mark531** [comment]
Thank you very much for investigating the issue!

**Comment by stefanv** [comment]
> Thanks @Mark531. The problem comes from the `min_xdistance` parameter of ` _prominent_peaks` which is set to the `min_angle` parameter of `hough_line_peaks` (here 10 degrees), while the size of the accumulator array is `(1450, 1)`. I'd suggest to transform
> 
> ```
> min_angle = min(min_angle, hspace.shape[1])
> ```
> 
> before calling `_prominent_peaks` in `hough_line_peaks`. In the example of @jni, adding `min_angle=1` solves the issue.

Thanks for figuring out the fix for this!
