### ISSUE TITLE
rename `feret_diameter` -> `max_feret_diameter` ?

### ISSUE THREAD

**Issue by VolkerH** [scikit-image/scikit-image#4817]
## Description

Sorry, I meant to comment on this while it was still an open PR, but then forgot to do so.
As it has not been in a release, maybe it is not too late to rename the new region property
`feret_diameter` to `max_feret_diameter`. 
Tagging @emmanuelle as she added it.

The simple reason being is that sometimes the minimum feret diameter is of interest and
it would be nice to be able to have naming consistency so that a `min_feret_diameter` property
can get added later.

**Comment by jni** [comment]
A good point! I'd be 👍 on this. (And yes it's totally fine to change this pre-release.)

**Comment by emmanuelle** [comment]
I'm fine with this!

**Comment by VolkerH** [comment]
thanks for considering this. Then I need to tidy up the code I have for minimum feret diameter (unfortunately only 2D) next. 

Also saw that @maxfrei750 already created a pull request. Not sure whether that'll need rebasing now that the new custom regionprop feature has been merged.

**Comment by maxfrei750** [comment]
@VolkerH 

> Then I need to tidy up the code I have for minimum feret diameter

Is your code for the minimum Feret diameter already available in scikit-image or somewhere else?

**Comment by VolkerH** [comment]
Hi @maxfrei750 ,
sorry for not replying earlier was not on Github much for the last couple of weeks.
No, it isn't in scikit-image yet. 
I only have code for 2D min feret diameter, will look for it in the coming days.

**Comment by VolkerH** [comment]
@maxfrei750 and others who are interested.

Here is a gist https://gist.github.com/VolkerH/0d07d05d5cb189b56362e8ee41882abf that contains code for calculating minimum feret diameters in the 2D case.

This would still need a bit of tidying before it could go into scikit image and I currently don't have the time. What needs tidying?

- tests required
- this code snippet brings its own code to compute upper and lower convex hulls. IIRC correctly, scikit-image uses scipy functions to to compute convex hulls in other places. It would be somewhat redundant to include another implementation of convex hull caclulation just for min feret diameter. OTOH I don't know whether the existing code supports upper and lower convex hulls.
- it is 2D only. I believe 3D is siginificantly more complex.

I a probably should open a new issue for this, but then I feel I have to work on it.
Pinging @emmanuelle who has worked on the maximum feret diameter code.
