### ISSUE TITLE
Work on structure_tensor: gallery example, row/col notation, port to 3D

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4831]
This issue is about improvements to `feature.structure_tensor`.

- [x] First of all, it does not have a gallery example. https://docs.opencv.org/master/d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html has a nice example which could be adapted.

- [x] Second, the code of structure_tensor uses x and y instead of r and c. See https://github.com/scikit-image/scikit-image/pull/2987 for a discussion on how to adapt what has been done for `hessian_matrix` to `structure_tensor`.

- [x] Finally, https://github.com/scikit-image/scikit-image/pull/2987 provided a 3D implementation, which should be integrated into the main `structure_tensor` function. https://github.com/scikit-image/scikit-image/pull/2489/ had an nD implementation as well. Also see the [wikipedia page on structure tensor](https://en.wikipedia.org/wiki/Structure_tensor) for merging the two docstrings.

These points can be addressed in separate pull requests.

**Comment by coreysharris** [comment]
I am working on this, starting with updating the row/col notation.

**Comment by grlee77** [comment]
Welcome @coreysharris!

I happened to just recently come across the [structure-tensor](https://github.com/Skielex/structure-tensor) respository which also has a [3D implementation](https://github.com/Skielex/structure-tensor/blob/master/structure_tensor/st3d.py) that is MIT-licensed. I haven't looked into whether it provides any benefit over the versions already in the open PRs here. Any help sorting that out would be appreciated.

**Comment by grlee77** [comment]
Stage 1 of the 3D implementation was completed during the sprint in #4841. 

@coreysharris, You had previously [indicated additional progress](https://skimage.zulipchat.com/#narrow/stream/176555-sprint/topic/structure-tensor). Is it mainly a need for test cases that is still pending?

I just wanted to check in. Feel free to open a work-in-progress PR (start the PR title with WIP: ), even if you don't have time to finish it in the near future. That will help us make sure what you have done so far does not get lost!

**Comment by coreysharris** [comment]
@grlee77, sorry for the delay on this. Life gets in the way 😄

I have written test cases. They could maybe use some work, but I'm happy to open a WIP PR to get some visibility. I'll try to get it done in the next couple days.

**Comment by emmanuelle** [comment]
@coreysharris if you open a WIP PR it could be taken over if you don't have the time, maybe in the course of Hacktoberfest if contributors are interested (what remains to be done in this issue is to make the `structure_tensor` function compatible with 3-D arrays).

**Comment by coreysharris** [comment]
@emmanuelle, @grlee77 I have finally opened the PR!

**Comment by emmanuelle** [comment]
With #5002 which is about to be merged, the only remaining point in this issue is the gallery example. @mkcor are you interested in tackling this? Otherwise I'm happy to do it.

**Comment by mkcor** [comment]
> With #5002 which is about to be merged, the only remaining point in this issue is the gallery example. @mkcor are you interested in tackling this? Otherwise I'm happy to do it.

@emmanuelle yes, I'm interested, thanks for thinking of me! I'll be on it tomorrow, is it okay?

**Comment by emmanuelle** [comment]
> @emmanuelle yes, I'm interested, thanks for thinking of me! I'll be on it tomorrow, is it okay?

sounds great, thank you!

**Comment by coreysharris** [comment]
Just checking in here... It looks like this issue could be closed?

**Comment by mkcor** [comment]
You're absolutely right, @coreysharris! Thanks for your diligence.
