### ISSUE TITLE
measure.label speed

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4833]
This is triggered by [this Stackoverflow question](https://stackoverflow.com/questions/62804953/performance-differences-between-bwlabeln-on-matlab-and-skimage-measure-label-on/62842582#62842582). When I have large binary arrays to label and performance issues, I usually resort to calling the ndimage version. Could we imagine having a `fast_binary` flag which would call the ndimage function? A factor of 3-4 (from a few tests I just ran) is not bad...

**Comment by jni** [comment]
Why don't we just automatically call ndimage on binary arrays? In that case the functions are equivalent, right?

**Comment by jni** [comment]
In which case this makes for a nice sprint issue! 😊

**Comment by jni** [comment]
To clarify, what I'm proposing is that at the top of the [`skimage.measure._label.label`](https://github.com/scikit-image/scikit-image/blob/7b62ec14e995af4d392d0cff81db304b6d8f9aa5/skimage/measure/_label.py#L92) function we do something like:

```python
if input.dtype == bool:
    # use ndimage.label
else:
    # current call to clabel
```

**Comment by emmanuelle** [comment]
Your suggestion sounds good to me @jni. I think @stefanv implemented the original algorithm so maybe he can comment.

**Comment by emmanuelle** [comment]
Confirmed by Stéfan (off Github), so definitely a good issue for the sprint!

**Comment by sciunto** [comment]
Seems to be not achieved during the sprint. I take it.
