### ISSUE TITLE
[doc] width and height order

### ISSUE THREAD

**Issue by hubutui** [scikit-image/scikit-image#4842]
According to the [doc](https://scikit-image.org/docs/stable/user_guide/numpy_images.html#numpy), image in `scikit-image` is represent as a numpy array in shape of `(rows, cols)` or `(rows, cols, channel)`, aka `(height, width)` or `(height, width, channels)`. However, [quickshift doc](https://github.com/scikit-image/scikit-image/blob/master/skimage/segmentation/_quickshift.py#L20 says `(width, height, channels)`. Is that a typo? https://scikit-image.org/docs/stable/api/skimage.segmentation.html#felzenszwalb also says `(width, height)`.

**Comment by sciunto** [comment]
Is it the use of plural on channels that bugs you?

**Comment by hubutui** [comment]
@sciunto Sorry for my typo, check my updated question. I mean the mismatching of `width` & `height` order.

**Comment by jni** [comment]
Yes, it should be (height, width), but more generally, (M, N). See #4869 for more. @hubutui do you think it would be ok if we close this issue as superseded by #4869, and continue further discussion there?
