### ISSUE TITLE
Problem in variation of infromation, should we ignore 0 in pred?

### ISSUE THREAD

**Issue by Keep-Passion** [scikit-image/scikit-image#4856]
## Description
I found there are problem in the calculation of variation of information.
I found that the codes of vi in skimage and cremi are also based on gala's code.
*gala: https://github.com/janelia-flyem/gala/blob/master/gala/evaluate.py
*cremi: https://github.com/cremi/cremi_python/blob/master/cremi/evaluation/voi.py
But there is a tiny question: Where and why to ignore 0 in VI?
If I don't ignore 0 in the prediction, I match [1, 1, 0] in pred to [1, 2, 3] in GT, and I get 2/3 * 1 + 1/3 * 0 = 2/3 for the VI.

Beside
For gala code,  they ignore 0 both in gt and pred (Default)
For cremi code, they only ignore 0 in gt, not in pred (Deafult)
For skimage, you did not ignore 0 in gt and pred (Default)
I made a simple comparison below, and i found that different setting will draw out different result. 
![image](https://user-images.githubusercontent.com/6437651/88139255-e9663c80-cc21-11ea-97f7-194d043efc30.png)

**Comment by jni** [comment]
For background, @Keep-Passion first raised the issue in the gala repo here: https://github.com/janelia-flyem/gala/issues/96

I think that the default values (ignore nothing) are good for skimage, but the different result in scenario 3 in the screenshot is concerning, and from my calculations the 2/3 value is correct, so this is probably a bug in our implementation.

**Comment by rfezzani** [comment]
I tend to agree with the `skimage` "ignore nothing" behavior and I am not sure to qualify this is a bug: actual implementation considers all the labels equivalently and doesn't assume 0 is background (even if it is reasonable to do so).
Should we assume anything about function's input? Maybe a simple side note in the doc can do the job here...

**Comment by jni** [comment]
@rfezzani the issue is not with our default behaviour, it is that we offer the *option* to ignore particular labels — and it seems we do the wrong thing when the user passes that parameter. See the third group of measurements in the screenshot provided by @Keep-Passion.

**Comment by Keep-Passion** [comment]
The implementation of VI in GALA and skimage is not exactly same. Then there are different outputs when i feed same input for skimage and gala. 
```python
from vi_cremi import split_vi
from vi_gala import split_vi as split_vi_gala
from vi_skimage import variation_of_information

im1 = np.zeros((2, 2), np.uint8) # gt
im2 = np.zeros((2, 2), np.uint8) # pred
im1[0, 0] = 1; im1[0, 1] = 0; im1[1, 0] = 2; im1[1, 1] = 3
im2[0, 0] = 1; im2[0, 1] = 1; im2[1, 0] = 1; im2[1, 1] = 0

false_splits, false_merges = variation_of_information(im1, im2, ignore_labels=(0, ))
print("Skimage: noignore 0 in pred, ignore 0 in gt,    false_splits:{}, false_merges:{}".format(false_splits, false_merges))
false_merges, false_splits = split_vi(im2, im1, ignore_x=[])
print("Cremi:   noignore 0 in pred, ignore 0 in gt,    false_splits:{}, false_merges:{} (Default)".format(false_splits, false_merges))
false_merges, false_splits = split_vi_gala(im2, im1, ignore_x=[])
print("Gala :   noignore 0 in pred, ignore 0 in gt,    false_splits:{}, false_merges:{}".format(false_splits, false_merges))
>>>
Skimage: noignore 0 in pred, ignore 0 in gt,    false_splits:0.0, false_merges:0.5
Cremi:     noignore 0 in pred, ignore 0 in gt,    false_splits:0.0, false_merges:0.6666666666666666 (Default)
Gala :      noignore 0 in pred, ignore 0 in gt,    false_splits:0.0, false_merges:0.6666666666666666
```
So that, we think there may be a bug about the calculation of VI in skimage when ignore_labels=(0, )

**Comment by rfezzani** [comment]
> See the third group of measurements in the screenshot provided by @Keep-Passion.

:facepalm: Now I see! Sorry...
