### ISSUE TITLE
More default values for parameters

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4868]
A large fraction of functions in our API are of the form `func(img, **kwarg)` where `img` is the only positional argument.

I started this issue to list functions which have positional arguments not corresponding to image arrays, and for which it would be possible to add a default value to help users get started.

- `restoration.denoise_tv_bregman`: `weight` parameter. A value of 1.0 should be a reasonable default. See for example https://www.ipol.im/pub/art/2012/g-tvd/article.pdf for examples.
- `measure.block_reduce`: `block_size` parameter. If we modify the way `block_size` is handled so that it's possible to pass an int and not only an array_like, then 2 would be a reasonable default.
-  `filters.threshold_local`: we could also have a heuristic for `block_size`

**Comment by lilisako** [comment]
It's a bit late but I'm working on this issue!
