### ISSUE TITLE
Incorrect deprecation message for `draw.circle`

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#4884]
## Description

`draw.circle` is deprecated in favour of `draw.disk`. But the deprecation warning says that it's deprecated in favour of `disk.circle`! 🤦 Oops!

## Way to reproduce

```python
from skimage import draw
_ = draw.circle(5, 5, 5)  # r, c, radius
```

gives

```pytb
FutureWarning: circle is deprecated in favor of disk.circle will be removed in version 0.19
```

## Version information

```
skimage 0.17.2/master
```

**Comment by sciunto** [comment]
I think it was supposed to say "circle is deprecated in favor of disk. circle will be removed in version 0.19"
