### ISSUE TITLE
Proposing a substitute for cameraman

### ISSUE THREAD

**Issue by alexdesiqueira** [scikit-image/scikit-image#4914]
## Description

Hey @scikit-image/core,
I am dealing with #3927 on #4913. We wanted a substitute for cameraman for a while, and I propose this image:

![eagle](https://user-images.githubusercontent.com/5776022/90188433-4dd37200-dd70-11ea-9deb-3a1ac195c49a.png)

@daymachado took it; she's releasing it under CC0.
What do you think? Is it a good substitute?

**Comment by alexdesiqueira** [comment]
Its histogram:
![histogram_eagle](https://user-images.githubusercontent.com/5776022/90192854-a27aeb00-dd78-11ea-8f6d-62c247e0f7ca.png)

**Comment by stefanv** [comment]
I like it! Although, perhaps that should become `eagle`, and cameraman should go with depreciation?

**Comment by matthew-brett** [comment]
How about http://krvarshney.github.io/kush_varshney.png as suggested in https://twitter.com/stefanvdwalt/status/1136039155119472640

**Comment by alexdesiqueira** [comment]
@matthew-brett thank you for remembering that discussion, Matt! That's indeed a nice candidate as well.
How could we proceed, Stéfan?

- Would you like to use @krvarshney's camera (http://krvarshney.github.io/kush_varshney.png) as `camera.png`?
- If yes: how about `eagle`? Would that still be a good fit?

**Comment by stefanv** [comment]
@krvarshney's is a good replacement for camera, then we can add eagle separately. Presuming that is an eagle :)

**Comment by sciunto** [comment]
I see in @alexdesiqueira image an eagle glaring the cameraman who is imposing a NC usage of himself. :)

**Comment by alexdesiqueira** [comment]
We can always name it `eagle_or_hawk` :wink:

**Comment by jni** [comment]
`or_falcon`!

How about `data.bird_of_prey_of_some_sort`? =P

**Comment by jni** [comment]
@alexdesiqueira The more I think about it the more I love that picture. In addition to being beautiful, it seems so great for so many examples — contrast adjustment, circular and line hough transforms, corner detection... Probably multi-otsu thresholding...! So thanks for the nomination!

**Comment by hmaarrfk** [comment]
I thought the conclusion from the whole MIT cameraman copyright was that they were OK with us using it. We mostly have to document their emails.

**Comment by sciunto** [comment]
> How about `data.bird_of_prey_of_some_sort`? =P

Or we give a name. After all, we don't have a cat, we have chelsea. :)

**Comment by emmanuelle** [comment]
`data.bird`? For what it's worth, pasting the image in Google images links to the wikipedia article on hawk.

We might want to downsample the image a bit so that its linear size is ~1000 instead of 2000.

**Comment by hmaarrfk** [comment]
> We might want to downsample the image a bit so that its linear size is ~1000 instead of 2000.

Why? Many people are using higher and higher resolution images. I think it would be awesome if we had something standard that challenged the state of the art in terms of interactive image display for Python

**Comment by alexdesiqueira** [comment]
Joking aside y'all, it's supposed to be an eagle — @daymachado took this pic when we were at an eagle exposition; we can't recall their precise name, though.

**Comment by emmanuelle** [comment]
> > We might want to downsample the image a bit so that its linear size is ~1000 instead of 2000.
> 
> Why? Many people are using higher and higher resolution images. I think it would be awesome if we had something standard that challenged the state of the art in terms of interactive image display for Python

You've got a point!

**Comment by alexdesiqueira** [comment]
Okay @scikit-image/core,
let's go with @sciunto's idea and give their a name. Please vote on the options:

- :tada: for Rufus
- :heart: for Charlie
- :rocket: for Ace

**Comment by emmanuelle** [comment]
no, no, please call it `data.eagle`! I always want to type `data.cat` and then only after the error I remember it's chelsea! (With all due respect to chelsea and its master)

**Comment by alexdesiqueira** [comment]
@emmanuelle you got it :sweat_smile:

**Comment by alexdesiqueira** [comment]
Okay, what we took from this issue:

- `data.camera` will point to a new [`camera.png`](http://krvarshney.github.io/kush_varshney.png);
- We'll have `data.eagle`. @daymachado is checking the species once more to be sure :smile:

**Comment by alexdesiqueira** [comment]
Yep, it's a [golden eagle](https://www.allaboutbirds.org/guide/Golden_Eagle/id) y'all.

**Comment by alexdesiqueira** [comment]
> Okay, what we took from this issue:
> 
>     * `data.camera` will point to a new [`camera.png`](http://krvarshney.github.io/kush_varshney.png);
> 
>     * We'll have `data.eagle`. @daymachado is checking the species once more to be sure smile

Alright, we're dealing with these points on #4913, #4922. Thanks y'all, appreciate your help!

**Comment by stefanv** [comment]
FWIW, happy to add an alias to `cat` :)

**Comment by krvarshney** [comment]
I consent to the use of http://krvarshney.github.io/kush_varshney.png as a test image in scikit-image.

**Comment by krvarshney** [comment]
We place the  http://krvarshney.github.io/kush_varshney.png image under the CC0 license. https://creativecommons.org/share-your-work/public-domain/cc0/

**Comment by alexdesiqueira** [comment]
Thank you @krvarshney, we appreciate your help! Could you please tell us the name of the photographer? We'll put it into that function's documentation. Thank you again!

**Comment by stefanv** [comment]
The photo was taken by @krvarshney's brother, Lav Varshney.

**Comment by krvarshney** [comment]
That is correct.

**Comment by jni** [comment]
... Who worked with my postdoc advisor Mitya Chklovskii and whose work features heavily in Elegant SciPy! Small world! =D

@stefanv We use cameraman in various places in ES... We should get cracking on the second edition with this new image, then both Lav and Kush can appear together in the book. =D

**Comment by krvarshney** [comment]
yes, one and the same

**Comment by mkcor** [comment]
@alexdesiqueira would you mind adding an entry for `eagle.png` over at https://gitlab.com/scikit-image/data/-/blob/master/README.md? One day we'll reorder them alphabetically. Thanks!

**Comment by alexdesiqueira** [comment]
@mkcor sorry, I missed this one. Sure thing, done at [#9](https://gitlab.com/scikit-image/data/-/merge_requests/9).
