### ISSUE TITLE
Memory corruption in flood_fill

### ISSUE THREAD

**Issue by mgmalheiros** [scikit-image/scikit-image#4918]
## Description

When using `flood_fill`, there is a consistent double free error and a dying kernel (as shown in the output from Jupyter) when using a negative row coordinate for the point where the fill starts.

## Way to reproduce

```python
import numpy as np
from skimage import segmentation

a = np.random.randint(0, 2, (100,100))

#for r in range(a.shape[0]):
#    segmentation.flood_fill(a, (r,  0), 1, in_place=True)
#    segmentation.flood_fill(a, (r, a.shape[1]-1), 1, in_place=True)
#    segmentation.flood_fill(a, (r, -1), 1, in_place=True)
    
for c in range(a.shape[1]):
#    segmentation.flood_fill(a, ( 0, c), 1, in_place=True)
#    segmentation.flood_fill(a, (a.shape[0]-1, c), 1, in_place=True)
    segmentation.flood_fill(a, (-1, c), 1, in_place=True)
```
All commented lines work, except the last one, which consistently triggers the error. The `flood` function also fails likewise with `segmentation.flood(a, (-1, c))`.

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0]
Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid
scikit-image version: 0.17.2
numpy version: 1.19.1
```
This error was present in version 0.16.2 too.

**Comment by jni** [comment]
Yikes! Thank you @mgmalheiros for reporting this!

I think we can manually normalise the input coordinates. There might even be a NumPy function for doing this.

@emmanuelle I think a fix for this should be merged and backported before we release 0.17.3, hopefully this week. =)

**Comment by emmanuelle** [comment]
I don't think there is a NumPy function for this, since it's as easy as `index % img.shape[0]` etc., i.e. you use the modulo operator. I therefore flagged this PR as "good first issue". I think my plate is a bit too full to release 0.17.3 this coming week and the next week I'm away on vacation, so there is a two-week window to address this issue :-).

**Comment by FirefoxMetzger** [comment]
I tried to reproduce this just now, and it runs without error on `0.18.dev0`

Code:

```
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))


import numpy as np
from skimage import segmentation

a = np.random.randint(0, 2, (100,100))

#for r in range(a.shape[0]):
#    segmentation.flood_fill(a, (r,  0), 1, in_place=True)
#    segmentation.flood_fill(a, (r, a.shape[1]-1), 1, in_place=True)
#    segmentation.flood_fill(a, (r, -1), 1, in_place=True)
    
for c in range(a.shape[1]):
#    segmentation.flood_fill(a, ( 0, c), 1, in_place=True)
#    segmentation.flood_fill(a, (a.shape[0]-1, c), 1, in_place=True)
    segmentation.flood_fill(a, (-1, c), 1, in_place=True)

```
Output:

```
>python foo.py
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Windows-10-10.0.17134-SP0
scikit-image version: 0.18.dev0
numpy version: 1.19.1
```

Is this an issue known to be specific to `0.17.2`? If so, what makes cherry-picking from `0.18.0` impossible?

**Comment by FirefoxMetzger** [comment]
Same result for 0.17.2.
```
>python foo.py
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Windows-10-10.0.17134-SP0
scikit-image version: 0.17.2
numpy version: 1.19.1
```

@mgmalheiros could you update skimage and see if this still reproduces on your machine? If so, could you share the full trace, so I can try to reproduce it?

**Comment by mgmalheiros** [comment]
Note that my installation is based on GCC running in Linux, so it seems a platform-specific bug.

The same error still occurs for me with the previous code snipped (for both 0.16.2 or 0.17.2). From the command line:

    3.8.5 | packaged by conda-forge | (default, Aug 21 2020, 18:21:27) 
    [GCC 7.5.0]
    Linux-5.4.0-42-generic-x86_64-with-glibc2.10
    scikit-image version: 0.17.2
    numpy version: 1.19.1
    double free or corruption (out)
    Aborted

As it seems a memory management issue, it only triggers for my case with a large enough test matrix (in the code, 100 by 100). Small matrices run unnoticed. Perhaps you may try with a matrix with more columns?

I could not generate a Python stack trace, as the underlying allocation library aborts. What should I do?

I've also tested a few low-level debugging tools (`gdb`, glibc2's `MALLOC_CHECK_`, `duma` and `libtcmalloc_minimal`), but they gave minimal information, just restating a bad allocation.

**Comment by FirefoxMetzger** [comment]
Thanks for the update @mgmalheiros . I will spin up a Linux VM later and check if I can reproduce it :) (if I can get my Hyper-V to work the way it should). 

In the meantime, I manually inspected the code. The bug you found appears to be caused by
https://github.com/scikit-image/scikit-image/blob/90a2b670e165b93b9ad1bf9a2145de1cc462f8d6/skimage/morphology/_flood_fill.py#L245

Which is the reason you can do `flood_fill(seed_point=(-1, c), ...)`, which would otherwise raise a `ValueError`. You can try your example with
```
segmentation.flood_fill(a, (-2, c), 1, in_place=True)
```
and should get a `ValueError: invalid entry in coordinates array`.

I'll submit a PR that catches this and that consistently raises errors on negative numbers.

**Comment by mgmalheiros** [comment]
Thanks for spotting that!

Indeed, using a `-2` coordinate always raises a `ValueError`.
