### ISSUE TITLE
morphology.extrema.h_maxima and h_minima: slightly confusing function descriptions

### ISSUE THREAD

**Issue by juliangilbey** [scikit-image/scikit-image#4928]
## Description

Consider this very short piece of code:

```python
testimg = np.array([0, 1, 2, 3, 4, 3.5, 4, 5, 4, 3, 2, 1, 0])
morphology.h_maxima(testimg, 1)
morphology.h_maxima(testimg, 2)
morphology.h_maxima(testimg, 3)
```

The results show that the element with value 5 is always picked up by this function, even though it is not a local maximum with height h for any h; rather it is the global maximum, so will always satisfy the condition tested for by this function.

The function description should therefore mention that the global maximum is also included.  The same goes for the h_minima function.

Best wishes,

Julian

## Version information

As at GitHub commit https://github.com/scikit-image/scikit-image/commit/9fcb6c9d9cadb8efa6426f29c94ab59928f41761

**Comment by sciunto** [comment]
thanks for reporting @juliangilbey In my mind, a global extremum is also a local extremum. (This page, randomly chosen from a search engine, is supporting it: https://brilliant.org/wiki/extrema/ )

Nevertheless, I agree, it would be helpful to add a note to these function to clarify this point. Would you like to submit a PR?

**Comment by juliangilbey** [comment]
OK; shall do!  Indeed, a global extremum is also a local extremum, but the global maximum does not satisfy the definition of "local maximum of height h".

**Comment by juliangilbey** [comment]
I didn't include a description of how to exclude the global maxima; I doubt that is something people are likely to want to do, and if they do, it is straightforward enough: if the output of `h_maxima(img, h)` is `hmax`, then we can exclude the global maxima with `hmax[img == np.amax(img)] = 0`, and likewise for `h_minima`.
