### ISSUE TITLE
Raster-to-vector conversion of colorful images using scikit-image.

### ISSUE THREAD

**Issue by hongyi-zhao** [scikit-image/scikit-image#4961]
Hi,

Can I convert colorful images in raster formats, say, JPG, PNG, GIF, etc., to PDF, SVG, or EPS formats with scikit-image?

Best regards,
HY

**Comment by sciunto** [comment]
@hongyi-zhao This is supported by scikit-image, and likely not the purpose of our library. Instead, you may try pillow which seems to support [SVG](https://pillow.readthedocs.io/en/4.2.x/handbook/image-file-formats.html#fully-supported-formats). You can also check https://pypi.org/project/pypotrace/

I can also recommend you to ask this sort of questions on: https://forum.image.sc/
I'm closing this issue.

**Comment by hongyi-zhao** [comment]
> and likely not the purpose of our library.

Why do you have this point of view?

**Comment by sciunto** [comment]
We bring image processing algorithms and we defer the IO to other libraries.

**Comment by hongyi-zhao** [comment]
IMO, bitmap tracing itself is done by image processing algorithms and not just relevant to IO.

**Comment by sciunto** [comment]
your question were about changing the file format, not tracing :/

**Comment by hongyi-zhao** [comment]
In order to generate a vector image based on a raster one, IMHO, the bitmap tracing processing algorithm, say, for edge/path detection, must be used for this purpose. Am I wrong?

**Comment by FirefoxMetzger** [comment]
I think vectorization is a pretty fascinating topic; I will have to agree with @sciunto though in that the capabilities of skimage in this regard will be somewhat limited.

One of the fundamental assumptions of the library is that images are representable as (multi-dimensional) numpy arrays, which is almost equivalent to saying "we process rasterized images" (very efficiently ;D ). Subsequentially, most functions (all? not 100% sure) that you will find here take a rasterized image as input and output something that can be interpreted as a numpy array (often a rasterized image).

This ndarray representation really doesn't lend itself well to vectorized images, which are sets of objects (often, polygons with added properties). Hence, you will not find a lot of functions that process images in this representation. and have to handle the image yourself after switching representations.

That said, you can certainly do some of the preprocessing necessary to do vectorization in skimage (denoising, small object removal, finding shapes, etc.). There is also some discussion on adding a boundary tracing algorithm (relevant topic: https://github.com/scikit-image/scikit-image/issues/1131 PR: https://github.com/scikit-image/scikit-image/pull/4853) which can serve as a very nice starting point for constructing polygon chains. However, development is community-driven and, as @sciunto pointed out, appears to not be a core focus currently. If you fancy contributing something I think everybody here would be quite thrilled and I'll be happy to review and discuss.

**Comment by kolibril13** [comment]
Hi!
It would be really nice to have a Raster-to-vector conversion for python!
Online versions to drag and drop images are already out there (e.g. https://www.vectorizer.io/)

After some research on the internet, the ideas I found at
https://stackoverflow.com/questions/31427903/convert-png-to-svg-using-python
are not very straight forward.

It would be amazing to have somewhere a solid package, which enables you to get vector-graphics from raster images with python.
With the above-mentioned pypotrace, one at least make paths from images, however, the svg export is not supported.
(To mention that there  is an inactive pull request for that feature https://github.com/flupke/pypotrace/pull/24)
From this discussion, I gather that scikit-image might not be the best place to implement a solid solution for svg export, but do you have any other ideas, where this feature could be implemented?

The package pycairo https://github.com/pygobject/pycairo is very good in making svg files from python code.
What about a new project, that uses scikit-image for path-finding and pycairo for path writing?
