### ISSUE TITLE
Write a piece of documentation on data.download_all() in the install procedure

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4971]
## Description

In https://scikit-image.org/docs/stable/install.html
write about https://scikit-image.org/docs/stable/api/skimage.data.html#download-all

**Comment by jni** [comment]
Good idea @sciunto! =)

One idea is whether it would be possible to add an optional extra, `pip install scikit-image[data]`, that runs download all after installation. That would make it a very nice user experience I think!

**Comment by sciunto** [comment]
That would be cool. I'm searching how to achieve this, and I found this discussion that seems to indicate it is not possible: https://stackoverflow.com/questions/55737009/how-to-get-extras-from-pip-install-in-custom-cmdclass-command

My understanding is that to do what you suggest, data must be a package.

Have you ever done that @jni?

**Comment by sciunto** [comment]
All I'm able to do is to download file with `python setup.py ...`.

**Comment by jni** [comment]
@sciunto ah, very sad. No, I had not done it, I just thought it might be possible with setup.py.

**Comment by emmanuelle** [comment]
That said, moving our data to a skimage_data package and having it an `extras_require` dependency of `skimage["data"]` could also be a solution for #4964. But then in the setup.py of `skimage_data`, would we be able to call `download_all`?
