### ISSUE TITLE
graph module goal_reached method not implemented?

### ISSUE THREAD

**Issue by tretherington** [scikit-image/scikit-image#4976]
## Description

For context, I am interested in being able to run `find_costs()` on one of the graph class objects returned by for example `MCP_Geometric()` but with the condition that the `find_costs()` stops once a maximum cumulative cost is reached.

From reading the [`find_costs()`](https://scikit-image.org/docs/0.17.x/api/skimage.graph.html?highlight=find_costs#skimage.graph.MCP.find_costs) documentation it seems that this is somehow possible using the `goal_reached()` method, but quite how this is implemented was not clear to me from the documentation.

So I went to look at the [code](https://github.com/scikit-image/scikit-image/blob/8135c2f3505d77134162846abf1b06c0b18d5a56/skimage/graph/_mcp.pyx#L422) to see if I could understand how to use the functionality, but I have become more confused as while I can see the idea that the current node and cumulative costs is checked at each iteration:

```python
            # Get current cumulative cost and index from the heap
            cumcost = costs_heap.pop_fast()
            index = costs_heap._popped_ref

            # Record the cost we found to this point
            flat_cumulative_costs[index] = cumcost

            # Check if goal is reached
            goal_reached = self.goal_reached(index, cumcost)
            if goal_reached > 0:
                if goal_reached == 1:
                    continue  # Skip neighbours
                else:
                    break  # Done completely
```

The `goal_reached()` method does not seem to actually check either the index or cumulative cost value, and instead always returns a 0 and hence the algorithm will never stop.

```python
    cpdef int goal_reached(self, INDEX_T index, FLOAT_T cumcost):
        """ int goal_reached(int index, float cumcost)
        This method is called each iteration after popping an index
        from the heap, before examining the neighbours.
        This method can be overloaded to modify the behavior of the MCP
        algorithm. An example might be to stop the algorithm when a
        certain cumulative cost is reached, or when the front is a
        certain distance away from the seed point.
        This method should return 1 if the algorithm should not check
        the current point's neighbours and 2 if the algorithm is now
        done.
        """
        return 0
```

Returning to my original context of simply wanting a way of stopping `find_costs()` once a maximum cumulative cost is reached, I'm also confused that `find_costs()` has two parameters `max_cumulative_cost` and `max_cost` that seem to be suggestive of the functionality that I would like, but neither parameter is described in the docstring or is used anywhere that I can find.

```python
    def find_costs(self, starts, ends=None, find_all_ends=True,
                   max_coverage=1.0, max_cumulative_cost=None, max_cost=None):
        """
        Find the minimum-cost path from the given starting points.
        This method finds the minimum-cost path to the specified ending
        indices from any one of the specified starting indices. If no end
        positions are given, then the minimum-cost path to every position in
        the costs array will be found.
        Parameters
        ----------
        starts : iterable
            A list of n-d starting indices (where n is the dimension of the
            `costs` array). The minimum cost path to the closest/cheapest
            starting point will be found.
        ends : iterable, optional
            A list of n-d ending indices.
        find_all_ends : bool, optional
            If 'True' (default), the minimum-cost-path to every specified
            end-position will be found; otherwise the algorithm will stop when
            a a path is found to any end-position. (If no `ends` were
            specified, then this parameter has no effect.)
```

I apologise for the slightly rambling thought process here, but I don't feel like I'm confident that I've understand the logic sufficiently, and my Cython skills are essentially non-existent, so I was hoping I could start a discussion to clarify if my understanding is correct before attempting to suggest a fix.  If I've understood this correctly then I'm thinking of suggesting the following changes:

1. Remove the `goal_reached()` method as it currently doesn't do anything, and as the `find_costs()` method already has an `ends` parameter to stop the algorithm when a certain index is reached - which is the first `goal_reached()` check.
2. Make use of the `max_cumulative_cost` parameter and replace the current `goal_reached()` execution with a simple check to see if the `max_cumulative_cost` value has been reached.

Hope someone can help!

**Comment by jni** [comment]
@tretherington Thanks for raising the issue, not rambling at all. =) Looking at the implementation I was also puzzled, until I read the docstring:

> This method can be overloaded to modify the behavior of the MCP algorithm.

The way to do this is to define your own class, in Cython, that *inherits* from MCP but redefines `goal_reached`. You can see inheritance later in the same file:

https://github.com/scikit-image/scikit-image/blob/83e857ca8f974bb560315a00989673b4b52f8a93/skimage/graph/_mcp.pyx#L715

where you can see that `_travel_cost` is redefined in that subclass:

https://github.com/scikit-image/scikit-image/blob/83e857ca8f974bb560315a00989673b4b52f8a93/skimage/graph/_mcp.pyx#L752

Unfortunately, you *will* need to upskill in Cython, since doing this in Python (a) probably won't work, and (b) if it did, it would be super super slow. You can see an example of importing an "external" Cython function/class here:

https://github.com/scikit-image/scikit-image/blob/83e857ca8f974bb560315a00989673b4b52f8a93/skimage/feature/_cascade.pyx#L14

In your case, I think you would do something along these lines:

```cython
import numpy as np
from skimage.graph cimport mcp


cdef class MCPMaxCumulative(mcp.MCP):
    def __init__(self, costs, offsets=None, fully_connected=True,
                 sampling=None, max_cumulative_cost=np.inf):
        super().__init__(costs, offsets, fully_connected, sampling)
        cdef float self.max_cumulative_cost = max_cumulative_cost

    cpdef int goal_reached(self, INDEX_T index, FLOAT_T cumcost):
        if self.flat_cumulative_costs[index] > self.max_cumulative_cost:
            return 1
        return 0
```

You can also see here how to configure a Cython build to look in specific places for C definitions:

https://github.com/scikit-image/scikit-image/blob/83e857ca8f974bb560315a00989673b4b52f8a93/skimage/feature/setup.py#L44

Having said all that, I don't think scikit-image provides the equivalent of `get_numpy_include_dirs()`. Perhaps @stefanv or others from @scikit-image/core have more experience with this...

**Comment by tretherington** [comment]
Hi @jni 👋 thanks for the lightning quick response! 😆

OK, I think I get how `goal_reached` is supposed to be implemented.  I was totally confused, but I now appreciate the relevance of the **overloading** which was not a concept I had come across before.

Massive thanks also for taking the time to provide an example that tries to do what I want.  I can see the logic now, and hopefully others who may be confused about how to use `goal_reached` will find this discussion useful.

Clearly `goal_reached` is set up to do what it is supposed to, so I'm going to close this issue, and then I'll try to make some time to learn Cython to give your example a go!

**Comment by jni** [comment]
Awesome, good luck! fyi this page in the Cython docs is invaluable:

https://cython.readthedocs.io/en/latest/src/userguide/numpy_tutorial.html#numpy-tutorial

Other things like cross-file importing I always have to refer back to, but the NumPy stuff is reasonably straightforward after reading that tutorial.
