### ISSUE TITLE
Issue in Structural_Similarity and SSIM MATLAB implementation

### ISSUE THREAD

**Issue by mugheesahmad** [scikit-image/scikit-image#4985]
## Description

this is kind of extension to the #4278 but the results are not matched right now as well with by default function of matlab r2019 ssim function.
## Way to reproduce
```python
!wget 'https://raw.githubusercontent.com/mugheesahmad/Fun_testing/master/LR0000001.jpg' 
!wget 'https://raw.githubusercontent.com/mugheesahmad/Fun_testing/master/HR0000001.jpg' 

from skimage.io import imread
from skimage.color import rgb2gray

ref_image = imread('/content/HR0000001.jpg')
ref_image = rgb2gray(ref_image)
impaired_image = imread('/content/LR0000001.jpg')
impaired_image = rgb2gray(impaired_image)
structural_similarity(ref_image, impaired_image, multichannel=True, gaussian_weights=True, sigma=1.5, use_sample_covariance=False, data_range=1.0)
# output is: 0.789570251107564 but the value on matlab is 0.8433 for same images

## Place the full code we need to recreate your issue here 
# upload all necessary images to github too!
```
The colab file containing all the code to reproduce is [available here](https://colab.research.google.com/drive/1fGW80rfhdgFCrO0D75ZMZyBUuaNyyV_C?usp=sharing)

## Version information
```python
# Paste the output of the following python commands
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.16.2
numpy version: 1.18.5
```

```python
# your output here

```

**Comment by grlee77** [comment]
I can verify that the built-in SSIM in Matlab does seem to do something different than ours for **color** images. In our implementation, the value returned is just the average of the SSIM of the individual channels.

Here is Matlab code I ran in R2017a that agrees with what was stated above:
```Matlab
>> img_LR = imread('/home/lee8rx/LR0000001.jpg');
>> img_HR = imread('/home/lee8rx/HR0000001.jpg');
>> ssim(img_HR, img_LR)
ans =

   0.843341310047354
```

However, running Matlab individually on the channels and averaging does give a result very similar to ours:
```Matlab
>> ch1_ssim = ssim(img_HR(:, :, 1), img_LR(:, :, 1))

ch1_ssim =

   0.757219192754735

>> ch2_ssim = ssim(img_HR(:, :, 2), img_LR(:, :, 2))

ch2_ssim =

   0.757181571271941

>> ch3_ssim = ssim(img_HR(:, :, 3), img_LR(:, :, 3))

ch3_ssim =

   0.757456615726399

>> (ch1_ssim + ch2_ssim + ch3_ssim) / 3

ans =

   0.757285793251025
```
This channel average value is quite similar to the value of 0.7577930222389057 that you obtained from scikit-image (and pytorch) in your collab notebook.


The Matlab version we had validated against was actually not Matlab's commercial implementation (which I think was only added to Matlab in the last few years), but was instead the original author's version [available here](https://ece.uwaterloo.ca/~z70wang/research/ssim/ssim.m).

**Comment by grlee77** [comment]
Based on the description in Matlab's docs, I think they do not have an equivalent of multichannel = True, so when you pass in an RGB image, it is also applying filters along the size 3 axis as if this is a "grayscale" 3D volume.

I verified that if I change the internals of the scikit-image function so that it does not raise an error regarding this array size and remove cropping of the edges, then `structural_similarity` run on the RGB images with
```structural_similarity(ref_image, impaired_image, multichannel=False, gaussian_weights=False, sigma=1.5, use_sample_covariance=False, data_range=1.0)```
gives: 0.850204719890714

which would seem to confirm this suspicion

**Comment by grlee77** [comment]
In Matlab you need to either manually do the channel averaging as above or convert to grayscale using
```Matlab
>> ssim(rgb2gray(img_HR), rgb2gray(img_LR))

ans =

   0.757009755144454
```

**Comment by grlee77** [comment]
I am closing this issue as there does not seem to be anything needed on our end, but feel free to comment or ask for clarifications

**Comment by mugheesahmad** [comment]
thankyou so much @grlee77 for such a nice and detailed explanation. Actually, I was also reached on a somewhat similar conclusion that its a problem at the end of Matlab, and I also raised [an error](https://www.mathworks.com/matlabcentral/answers/599182-ssim-function-is-not-consistent?s_tid=srchtitle) at their forum where their implementation was consistent with original authors' implementation only for the gray images which you also explained in this post.  Anyway thanks alot again.

**Comment by JDWarner** [comment]
Completely agree with @grlee77 and - for posterity - I want to add that MATLAB's approach for color images is naive and incorrect.  A _structural_ similarity metric has no business being applied across color channels, each which is independent of the others.  MATLAB likely just exposed this as an n-D function and didn't think more about it.

**Comment by mayorx** [comment]
> thankyou so much @grlee77 for such a nice and detailed explanation. Actually, I was also reached on a somewhat similar conclusion that its a problem at the end of Matlab, and I also raised [an error](https://www.mathworks.com/matlabcentral/answers/599182-ssim-function-is-not-consistent?s_tid=srchtitle) at their forum where their implementation was consistent with original authors' implementation only for the gray images which you also explained in this post. Anyway thanks alot again.

I reproduce the matlab ssim in pytorch (with en error < 0.0001) . If you are still interested, you can see it here: https://github.com/mayorx/matlab_ssim_pytorch_implementation.

**Comment by mugheesahmad** [comment]
@mayorx Thanks for sharing. I came across this implementation, which is also consistent with Matlab,and corrently I am usnig this for my workarouund.  see this https://github.com/hzwer/arXiv2020-RIFE/blob/15cb7f2389ccd93e8b8946546d4665c9b41541a3/benchmark/pytorch_msssim/__init__.py#L81
