### ISSUE TITLE
Update documentation to new data.camera()

### ISSUE THREAD

**Issue by alexdesiqueira** [scikit-image/scikit-image#4993]
## Description

Some of our examples were written to use the old image `cameraman`. They need to be updated to the replacement image (please see #4913).
A small list to start follows (thank you @rfezzani!):

* [Multi-Otsu Thresholding](https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_multiotsu.html#sphx-glr-auto-examples-segmentation-plot-multiotsu-py)
* [Markers for watershed transform](https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_marked_watershed.html#sphx-glr-auto-examples-segmentation-plot-marked-watershed-py)
* [Flood Fill](https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_floodfill.html#sphx-glr-auto-examples-segmentation-plot-floodfill-py)
* [Rank filters](https://scikit-image.org/docs/stable/auto_examples/applications/plot_rank_filters.html#sphx-glr-auto-examples-applications-plot-rank-filters-py)

If you see an example that uses the new image and needs to be updated, please add it here.

**Comment by emmanuelle** [comment]
For people interested in contributing to this issue, the idea is to update the examples listed above so that they look as good or better with the new image than with the old one (which we had to remove due to copyright issues).

**Comment by sciunto** [comment]
I would also say that we can authorize the use of another image of our dataset.

**Comment by kalpanab-psg** [comment]
Hi, I would like to work on this! Could you assign this to me please?

**Comment by alexdesiqueira** [comment]
Sure thing @kalpanab-psg, thank you for your help!

**Comment by sciunto** [comment]
Just FIY, I had a quick look at the multi-otsu, and it seems that we do not have very nice candidates in our dataset.

**Comment by kalpanab-psg** [comment]
Just a quick question. Can we use any other image other than camerman in some filter functions.

**Comment by emmanuelle** [comment]
@kalpanab-psg sure, other images in `skimage.data` can be used alternatively.

**Comment by emmanuelle** [comment]
Actually the multi-otsu result is not so bad compared to the old camera image, it's just that there seems to be an aliasing problem which makes some edges look pink. Maybe just change the colors used here?
