### ISSUE TITLE
Active Contour does not work properly

### ISSUE THREAD

**Issue by chihyanghsu0805** [scikit-image/scikit-image#4995]
## Description
active_contour does not work.

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```
I ran the astronaut tutorial notebook.
https://scikit-image.org/docs/dev/auto_examples/edges/plot_active_contours.html

I also tried it in Google Colab and resulted in same issue.

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Windows-10-10.0.19041-SP0
scikit-image version: 0.15.0
numpy version: 1.16.5

```

**Comment by jni** [comment]
@chihyanghsu0805 can you elaborate on the error? The script is running fine locally. I notice that your scikit-image version is old (0.15 — current version is 0.17), so probably you should either

(a) update your version of scikit-image, or
(b) download the example corresponding to your version, found here:

https://scikit-image.org/docs/0.15.x/auto_examples/edges/plot_active_contours.html#sphx-glr-auto-examples-edges-plot-active-contours-py

(you can see where you linked, on the left there is a place to click "all versions", then you can find the version you need.)

I suspect your issue has to do with the version mismatch, so I am going to close this. If neither of the above solution fixes your problem, please do reopen the issue and we will be happy to help further!

**Comment by chihyanghsu0805** [comment]
@jni Thanks, it works. The error was the algorithm not converging, or blows up. It was the coordinate system (rc/xy) difference between v0.15 and v0.17. Thanks again.
