### ISSUE TITLE
CI broken on master following tifffile release

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4996]
See the Azure CI failure https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=4513&view=logs&jobId=eeafdf3e-6518-596e-3f31-4f6be6dd535c&j=eeafdf3e-6518-596e-3f31-4f6be6dd535c&t=42e5ba94-5a2b-5af3-282c-f8497361abb3

I've seen on Pypi that there has been a release of tifffile a few hours ago. It's a problem with the `multifile` argument.

**Comment by emmanuelle** [comment]
From https://github.com/cgohlke/tifffile#revisions it seems that `multifile` is not supported any more. Should we deprecate this parameter?
(@cgohlke @ing you just to let you know and if you want to comment but no action needed from you I think)

**Comment by cgohlke** [comment]
Should be fixed in tifffile v2020.10.1.  #4997 lets `tifffile.imread` handle additional keyword arguments so skimage doesn't have to keep track.

**Comment by emmanuelle** [comment]
Fixed, thank you @cgohlke
