### ISSUE TITLE
Resizing a binary image as a bool array failed to produced the result as expected. 

### ISSUE THREAD

**Issue by jingweimo** [scikit-image/scikit-image#4998]
I am using skimage '0.17.2' in Python 3.7. Here below is my code for resizing a bool array object mask:

```
MASK_SHAPE = (56, 56)
skimage_resized = skimage.transform.resize(mask.astype(np.float), MASK_SHAPE, 
                                           order=1, mode='constant', cval=0, clip=True) # mask is of bool type
```
In the above, I converted the input bool type to float before resizing.  If the bool type is input, there is a warning message printed out: `FutureWarning: Input image dtype is bool. Interpolation is not defined with bool data type. Please set order to 0 or explicitely cast input image to another data type. Starting from version 0.19 a ValueError will be raised instead of this warning.`

However the resizing produced noticeable distortions. Here are the original and resized image: 
![image](https://user-images.githubusercontent.com/18681637/94863945-3bd58d80-0409-11eb-9145-a72e7726e257.png)

How to perform the resizing of bool array with minimal artifacts?

**Comment by mkcor** [comment]
Hi @jingweimo,

Could you please share the `mask` object you are using, so we can reproduce your issue?

Also, it looks like this 'issue' would rather belong in our forum or chat: see https://github.com/scikit-image/scikit-image/blob/master/INSTALL.rst#additional-help -- @emmanuelle am I right in redirecting the user this way?

**Comment by rfezzani** [comment]
Thank you @jingweimo for reporting, as the warning message is saying, boolean values interpolation other then nearest neighbor (order=0) is not defined: how to obtain a linear interpolation between `True` and `False`? (Please also see #4292)

Now, looking at the axis of your figure, I see that you are resizing a ~1000×1000 image to 56×56 which is approximately 18 times smaller!! Even with a regular image, you can't expect a better result with such a rescale factor:

```python
>>> from skimage import data
>>> from skimage.transform import rescale
>>> img = data.coins()
>>> img_0 = rescale(img, 1/18)
>>> fig, (ax0, ax1) = plt.subplots(1, 2)
>>> ax0.imshow(img, cmap="gray")
<matplotlib.image.AxesImage object at 0x7f28c4168358>
>>> ax1.imshow(img_0, cmap="gray")
<matplotlib.image.AxesImage object at 0x7f28c4107d30>
```

![Figure_2](https://user-images.githubusercontent.com/3438227/94924979-c6c48f80-04be-11eb-9ff8-02aa8825d448.png)
