### ISSUE TITLE
Docstring of the function random_noise requires correction

### ISSUE THREAD

**Issue by neeraj3029** [scikit-image/scikit-image#5000]
## Description

The docstring in `random_noise` function [line 30](https://github.com/scikit-image/scikit-image/blob/e19fa1f4c19f4df88a12307409efd8d2de1c4836/skimage/util/noise.py#L30) says Speckle noise is 'uniform', which should be changed to 'gaussian'.

## Way to reproduce

The issue refers to docstring

## Version information

Any, as the issue refers to docstring

**Comment by mkcor** [comment]
Hi @neeraj3029,

In this context, `n` is uniformly distributed random noise with mean `mean` and variance `var`.

When trying to understand what you meant, I stumbled across this paragraph, which mentions a common incorrect assumption: https://en.wikipedia.org/wiki/White_noise#Statistical_properties

**Comment by mkcor** [comment]
@sciunto sorry, I hadn't seen your review of the corresponding PR. Between 'gaussianity' and 'uniformity,' one refers to the intensity distribution and the other to the spatial distribution, right? Thanks!

**Comment by neeraj3029** [comment]
Hi @mkcor, the above line in docstring defines the 'speckle' noise as 'uniformly' distributed.

However, the speckle noise never follows uniform distribution, but 'gaussian'. 

In fact, the [function for speckle noise addition at line 184](https://github.com/scikit-image/scikit-image/blob/e19fa1f4c19f4df88a12307409efd8d2de1c4836/skimage/util/noise.py#L184)  adds random gaussian (normal) noise.

**Comment by mkcor** [comment]
@neeraj3029 oh, right, `mean` and `var` being the mean and variance, respectively, of that Gaussian (normal) distribution. :facepalm:

Thanks for bearing with me!

**Comment by neeraj3029** [comment]
That's alright @mkcor! If possible, can you have a look at the PR, as the Travis CI test is failing and I couldn't figure out how to fix that. Thanks!

**Comment by mkcor** [comment]
@emmanuelle #5001 closes this issue (poking you because I don't have 'closing' rights).
