### ISSUE TITLE
Expression for speckle noise addition might need correction

### ISSUE THREAD

**Issue by neeraj3029** [scikit-image/scikit-image#5004]
## Description

[The expression for speckled image](https://github.com/neeraj3029/scikit-image/blob/4c31a1be728c760919bafdae21449bcbf2698178/skimage/util/noise.py#L186) is `out = img + img * noise` which translates to <code>out = img * (noise+ <b>1</b>)</code> where noise is with given mean and variance. Speckle is a multiplicative noise, in my opinion should just be `out = img * noise`

**Comment by mkcor** [comment]
@neeraj3029 could you please share some references (textbooks and/or papers)? We may want to point to them even in the docs... Maybe it's just 'well-known' but, personally, my memories from grad school are not fresh at all, so I'd be happy to check out a good reference on the topic. :)

**Comment by neeraj3029** [comment]
Sure @mkcor! I got to know about it while working on the following papers from IEEE. 

1. [SAR Image Despeckling Using a Convolutional
Neural Network (arXiv)](https://arxiv.org/pdf/1706.00552.pdf) ([IEEE](https://ieeexplore.ieee.org/document/8053792)) - Equation (1) and the paragraph above

2. [A Practical Approach for SAR Image Despeckling Using Deep Learning](https://ieeexplore.ieee.org/abstract/document/8897918/authors#authors) -  Equation (1)

I could not find much implementations of multiplicative noise over the web, so I am not sure if the change I suggest is absolutely correct or not. However, after referring to the papers I thought I should point this out.

**Comment by mkcor** [comment]
Dear @neeraj3029,

Thank you for looking this up. I checked and the implementation is correct. Indeed, `noise` in `out = img * (noise + 1)` is speckle noise of *zero mean*:
https://github.com/scikit-image/scikit-image/blob/a69d49272145d9839df75f3ee398c0bbde32f448/skimage/util/noise.py#L39-L41

When the formula is expressed as `Y = FX` where `X` is the noise-free image and `Y` the noisy image, `F` is speckle noise of *unit mean* (so it's the same as a zero-mean speckle noise + 1).

References:
* https://arxiv.org/pdf/0912.1845.pdf
* https://medium.com/@sunil7545/speckle-vs-gaussian-noise-7f4f47230d82
