### ISSUE TITLE
(Windows 10) import skimage.io is not work for me

### ISSUE THREAD

**Issue by amirhesam2998** [scikit-image/scikit-image#5005]
i want to open Landsat sattlite image (for example blue band)
but when i use scikit-image package to open the band i receve module 'skimage' has no attribute 'io'

full error
File "c:/Users/Hesam/Desktop/python/.vscode/import/landsat.py", line 4, in <module>
    blue = skm.io.imread("E:/python_image_processing/Image/Image/Landsat/Blue.tif")
AttributeError: module 'skimage' has no attribute 'io'
PS C:\Users\Hesam\Desktop\python\.vscode\import>

**Comment by emmanuelle** [comment]
Hi @amirhesam2998 could you please paste the information about the scikit-image version as required in the issue template (see below I copied it again for you), tell us how you installed scikit-image, and also paste the exact command which resulted in the above error?

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by grlee77** [comment]
scikit-image does not automatically import all submodules when you import the top level module. If your imports are just
```Python
import skimage as skm
```
you will not be able to access `skm.io` because the `io` module hasn't been imported.

The following should work, though
```Python
import skimage as skm
import skimage.io
```

If this does not solve your issue, please post additional details as requested by @emmanuelle

**Comment by amirhesam2998** [comment]
Hi @emmanuelle  thank you for attention
i install it by windows powershell 
and it is the output :
3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.18362-SP0
scikit-image version: 0.17.2
numpy version: 1.19.2

**Comment by amirhesam2998** [comment]
Hi @grlee77  thank you for attention
It does not solve my issue

**Comment by amirhesam2998** [comment]
Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Hesam\Desktop\python\.vscode\import> & C:/Users/Hesam/AppData/Local/Programs/Python/Python38/python.exe c:/Users/Hesam/Desktop/python/.vscode/import/landsat.py
Traceback (most recent call last):
  File "c:/Users/Hesam/Desktop/python/.vscode/import/landsat.py", line 4, in <module>
    blue = skm.io.imread("E:/python_image_processing/Image/Image/Landsat/Blue.tif")
AttributeError: module 'skimage' has no attribute 'io'
PS C:\Users\Hesam\Desktop\python\.vscode\import>

**Comment by hmaarrfk** [comment]
Can you provide the output of 

```
import skimage
print(skimage.__path__)
```

**Comment by amirhesam2998** [comment]
Hi yes thank u @hmaarrfk 
['C:\\Users\\Hesam\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\skimage']

**Comment by hmaarrfk** [comment]
i'm not really sure.

Can you provide us with the full landsat.py file? Or at least the 5 lines that recreate the issue. @grlee77 's solution worked for me locally.

**Comment by amirhesam2998** [comment]
my code become okay i install 0.14 scikit image and its ok now .. thank u

**Comment by soupault** [comment]
Good that you have managed to solved the issue. 👍 Closing...
