### ISSUE TITLE
TypeError: _open() got an unexpected keyword argument 'as_grey'

### ISSUE THREAD

**Issue by alinasahoo** [scikit-image/scikit-image#5008]
# TypeError: _open() got an unexpected keyword argument 'as_grey'

As I am new to scikit-image, I am unable to understand what went wrong here. So, just adding the following files here:

I am successfully able to read the image file in RGB format but not in grayscale format. This is the error that I am getting. I also checked the official documentation and it showed that the syntax is as follows:

>> skimage.io.imread(fname, as_gray=False, plugin=None, **plugin_args)

Here, I am unable to understand the argument **plugin_args. Updating the necessary files:

![TypeError](https://user-images.githubusercontent.com/71794673/95293249-b599cb00-0890-11eb-9f9d-5611b9b3ea67.PNG)
![Error2](https://user-images.githubusercontent.com/71794673/95293759-b121e200-0891-11eb-952a-5c05e9ba218f.PNG)

## Version Information: 
![VersionInfo](https://user-images.githubusercontent.com/71794673/95293831-d1ea3780-0891-11eb-9e77-e6067c53f5c6.png)

**Comment by sciunto** [comment]
`as_gray` and not `as_grey`. Does it solve the issue?

**Comment by alinasahoo** [comment]
@sciunto , yes this works fine. Thank you.

**Comment by FruityOVGU** [comment]
Hi, I am also new to skimge, and I was also facing same problem, but my proble is just solved by just replacing 
img = io.imread("example grids/circuit.tif", as_gray=True)
to 
img = io.imread("example grids/circuit.tif", as_grey=True)

Thanks for this post
