### ISSUE TITLE
AttributeError: module 'skimage' has no attribute 'filters' (On Ubuntu 20.04, conda-forge channel installation)

### ISSUE THREAD

**Issue by MarkCarbonell98** [scikit-image/scikit-image#5009]
## Description

When I install scikit-image using conda by doing `conda install -c conda-forge scikit-image`  I get an attribute error when I import the package.

Example:

```python
import skimage
skimage.filters # AttributeError 
```
on ubuntu 20.04
scikit-image version is 0.17.2

![Screenshot from 2020-10-07 12-55-11](https://user-images.githubusercontent.com/32847477/95322611-13ccab00-089d-11eb-8e7a-f2628db6b040.png)

**Comment by emmanuelle** [comment]
Hi @MarkCarbonell98 can you try `from skimage import filters` or `import skimage.filters`? Submodules are not automatically imported when importing `skimage` in order to save time.

**Comment by MarkCarbonell98** [comment]
@emmanuelle Thank worked nicely! Thanks a lot
