### ISSUE TITLE
Remove usage of numpy's private functions

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#5028]
In `skimage/util/arraycrop.py`, we are using `_as_pairs` which belongs to numpy and is a private function.

The main issue is that the API may change at any time (and did happen). We must consider adding this code in our library.

Bonus: check if other private functions are used elsewhere (likely not).

**Comment by jjerphan** [comment]
Hey @sciunto,

I am interested do a PR for this issue. Is there a place for the vendor code in the repository? :slightly_smiling_face:

**Comment by Harry-Kwon** [comment]
Hi I've attempted to modify the method to remove to reference to numpy's private functions in this pull request [https://github.com/scikit-image/scikit-image/pull/5081](https://github.com/scikit-image/scikit-image/pull/5081). Are these modifications ok?

I also didn't find any other uses of numpy's private functions in the codebase.

**Comment by jni** [comment]
Closed by #5081
