### ISSUE TITLE
Local testing discovery is broken on master

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#5043]
## Description

I first noticed this [here](https://github.com/scikit-image/scikit-image/pull/5041#discussion_r515039017) but I thought it was something weird with pooch and fetch because those tests are meant to be skipped under certain conditions. Then @FirefoxMetzger noticed [here](https://github.com/scikit-image/scikit-image/pull/4851#issuecomment-719435024) that he couldn't get tests to run on his machine. Bizarrely, on Travis things work, and pytest does find setup functions:

```
 $ pytest skimage/filters/tests/test_thresholding.py -v
================================= test session starts =================================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /home/jni/miniconda3/envs/all/bin/python
cachedir: .pytest_cache
PySide2 5.14.2.1 -- Qt runtime 5.14.2 -- Qt compiled 5.14.2
rootdir: /home/jni/projects/scikit-image, inifile: setup.cfg
plugins: timeout-1.3.4, napari-plugin-engine-0.1.6, ome-zarr-0.0.14, httpserver-0.3.4, ordering-0.6, qt-3.3.0, cov-2.8.1
collected 1 item                                                                      

skimage/filters/tests/test_thresholding.py::TestSimpleImage::setup PASSED       [100%]

================================== 1 passed in 0.26s ==================================
```

I don't have time right now to investigate.

**Comment by FirefoxMetzger** [comment]
This doesn't just affect calling individual files. For me, a generic `pytest` skips a large chunk of tests, too.

```
>pytest
================================================= test session starts =================================================
platform win32 -- Python 3.7.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\scikit-image, configfile: setup.cfg
plugins: cov-2.10.1, localserver-0.5.0
collected 276 items / 3 skipped / 273 selected
```

This is significantly less than the 6000+ tests that currently make up the entire test suit.

**Comment by FirefoxMetzger** [comment]
On further inspection, it appears that pytest skips (doesn't discover) tests that are defined as functions and only discovers tests that are declared as classes.

**Comment by FirefoxMetzger** [comment]
Okay, weirdly enough adding an empty `pytest.ini` in the project's root directory fixed this on my machine. `pytest` now discovers 6275 tests. I don't really know why it does fix things, nor do I know what the cause was; I stumbled across this while searching for people with similar issues and thought I'll give it a shot.

@jni Could you check if this fixes things on your machine as well?

**Comment by jni** [comment]
Yup, fixes things for me also.

**Comment by jni** [comment]
Git bisect traces it to #3329

**Comment by jni** [comment]
Found it: setup.cfg adds a pytest configuration. I think it's missing `test_*` under python_functions. pytest.ini probably makes it ignore the config section in setup.cfg

**Comment by jni** [comment]
Yup, adding `test_*` under `python_functions` fixes the problem. PR incoming. Thank you @FirefoxMetzger for troubleshooting with me!

**Comment by FirefoxMetzger** [comment]
Anytime.
