### ISSUE TITLE
pip install error: implicit declaration of function 'unwrap2D' is invalid in C99

### ISSUE THREAD

**Issue by gduffley** [scikit-image/scikit-image#5051]
## Description
I'm getting an installation error on MacOS using pip

## Way to reproduce
```python
pip install scikit-image
```

## Version information
```python
# Paste the output of the following python commands
3.9.0 (default, Oct 27 2020, 14:15:17) 
[Clang 12.0.0 (clang-1200.0.32.21)]
macOS-10.15.7-x86_64-i386-64bit
numpy version: 1.19.4
```

skimage/restoration/_unwrap_2d.c:2285:9: error: implicit declaration of function 'unwrap2D' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

See the attached log file the for the full dump:
[scikit_install_log.txt](https://github.com/scikit-image/scikit-image/files/5492160/scikit_install_log.txt)

**Comment by jni** [comment]
Thanks for the report @gduffley!

`_unwrap_2d.c` is actually generated from a Cython source, `_unwrap_2d.pyx`. What version of Cython do you have installed? (`cython --version`). I suspect that this is actually a Cython issue rather than a skimage issue, based on the above.

**Comment by gduffley** [comment]
@jni Thanks for the quick reply. My Cython version is: ``Cython version 0.29.21``

**Comment by jni** [comment]
Thanks! Would you mind upgrading to 3.0a and trying again? You can do this with `pip install -U --pre cython`.

**Comment by gduffley** [comment]
I tried with the latest cython, and got the same error. I have reverted to python38 for now, and everything is working fine. I really appreciate the help!

**Comment by johnnypcc** [comment]
I have the same issue, how do I solve it? Don't want to downgrade to 3.8.
Thanks

**Comment by jni** [comment]
@johnnypcc I'm not sure but I think that this issue should probably go in https://github.com/cython/cython. Perhaps @hmaarrfk has a better idea?

**Comment by hmaarrfk** [comment]
I think stricter rules in the C compiler may be tripping it off.

It seems that the `unwrap2D` (capital 2D) is a function defined in `unwrap_2d_ljmu.c`. I think we should probably define a header or something for cython to import, rather than importing `*`.



> Don't want to downgrade to 3.8.

Python 3.9 came out [1 month ago](https://www.python.org/downloads/release/python-390/), and it takes us time to adjust to all the new challenges.

We would be very grateful for PRs addressing this issue.

**Comment by healther** [comment]
I'm seeing this also with Python3.8. I think it is triggered by the new behaviour of XCode12, which treats implicit function declarations as an error, rather than a warning. See [here](https://github.com/spack/spack/issues/19905#issuecomment-727268429) for the context. I'm not sure where the problem originates, but specifying `-Wno-implicit-function-declaration` at least let's my build proceed further

**Comment by hmaarrfk** [comment]
Thanks for helping out. can you provide people with the full command? 

We dont' use XCode12 to ensure we stay compatible with very old macs, but it will be nice to address this issue.

**Comment by healther** [comment]
something like
```
export CFLAGS='$CFLAGS -Wno-implicit-function-declaration'
```
before doing the `python setup.py` or `pip install sk-image`

**Comment by ChenghaoZHU** [comment]
> something like
> 
> ```
> export CFLAGS='$CFLAGS -Wno-implicit-function-declaration'
> ```
> 
> before doing the `python setup.py` or `pip install sk-image`

Life saver, I pass the building via 
`export CFLAGS='-Wno-implicit-function-declaration'`

**Comment by jni** [comment]
ah, sorry, I missed

> It seems that the unwrap2D (capital 2D) is a function defined in unwrap_2d_ljmu.c. I think we should probably define a header or something for cython to import, rather than importing *.

Thank you @david-a-joy for the specific fix! Preparing a PR now. 🙏

**Comment by Dan609** [comment]
I had the same issue and managed to solve it with

`python3 -m pip install -U scikit-image[optional]`

To include a selection of other scientific Python packages that expand scikit-image's capabilities to include, e.g., parallel processing, you can install the package scikit-image[optional].

**Comment by Hyaloid** [comment]
> > something like
> > ```
> > export CFLAGS='$CFLAGS -Wno-implicit-function-declaration'
> > ```
> > 
> > 
> > before doing the `python setup.py` or `pip install sk-image`
> 
> Life saver, I pass the building via
> `export CFLAGS='-Wno-implicit-function-declaration'`

Thx a lot, I successfully compiled the package via
`export CFLAGS='-Wno-implicit-function-declaration'`
