### ISSUE TITLE
pip install scikit-image fails for python3.9 freshly installed with brew

### ISSUE THREAD

**Issue by mmarras** [scikit-image/scikit-image#5063]
## Description

On macOS using python3.9 installed via brew and using pip I fail to install scikit-image. I have logged pip which can be found [here](https://github.com/mmarras/mytest/blob/master/test3.log). It aborts saying that `clang -options failed with exit status 1'. I also tried llvm-gcc as alternative compiler, same result. 
Also tried to install 0.16.2 to try if an earlier version would work. Same result. 
Any idea what to try?

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
pip install scikit-image
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.9.0 (default, Oct 27 2020, 14:15:17) 
[Clang 12.0.0 (clang-1200.0.32.21)]
macOS-10.15.7-x86_64-i386-64bit
<Import of skimage fails obviously>
numpy version: 1.19.4

```

```pip 
pip 20.2.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by mmarras** [comment]
Tried it on a different machine, alas same macOS and python3.9 via Brew. Same result does not install.

**Comment by hmaarrfk** [comment]
Can you upload the build log?

Without the build log, the only thing I can think of is for you to try to disable build isolation

**Comment by mmarras** [comment]
Sorry, I don't know exactly what you are referring to. Do you mean something else than the `pip --log` which I have linked in the OP?

**Comment by asabbas** [comment]
macOS Catalina Version 10.15.7
Python 3.9.0
pip 20.2.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Apple clang version 12.0.0 (clang-1200.0.32.27)
numpy               1.19.4
Attached the pip log file: 
line 1581: 2020-11-13T23:05:14,662   ERROR: Failed building wheel for scikit-image 
This seems to cause the problem because on python 2.7 on the same computer it installed scikit-image with no issues
[scikit_log.txt](https://github.com/scikit-image/scikit-image/files/5540336/scikit_log.txt)

**Comment by hmaarrfk** [comment]
@asabbas thanks for the output.

This seems to be the same error as 

https://github.com/scikit-image/scikit-image/issues/5051

I suggest we continue the conversation there with the 2 of you.
