### ISSUE TITLE
enable scipy grid-constant boundary handling

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#5064]
## Convert 'constant' -> 'grid-constant' when calling scipy.ndimage.interpolation functions

#1514 covered the difference in mode='constant' for scikit-image vs. scipy.ndimage. At that time, we switched the default mode away from constant, but as of SciPy 1.6, we will can also use mode 'grid-constant' in scipy.ndimage which should be equivalent to scikit-image's own constant interpolation mode.

I am just opening this issue as a future TODO as this may need to wait awhile until SciPy >=1.6 is a dependency. Specifically, at the following location:
https://github.com/scikit-image/scikit-image/blob/ed889ba3deb17cd94d1f0f9b730f6564585936ee/skimage/transform/_geometric.py#L11-L12

we should possibly add `constant='grid-constant'`.

**Comment by jni** [comment]
Thanks @grlee77! I think we should detect the scipy version and add that mode translation if it's after 1.6. That can be done immediately which is nice.

**Comment by jni** [comment]
Also, thanks to NEP-29, we can immediately know the date when we can remove the detection. =)
