### ISSUE TITLE
poetry add scikit-image fails with WinError 123

### ISSUE THREAD

**Issue by adam-grant-hendry** [scikit-image/scikit-image#5065]
## Description

Running `poetry add scikit-image` on Windows 10 yields an `EnvCommandError`:

```
ERROR: Could not install packages due to an EnvironmentError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"c:'
```

## Way to reproduce
```
poetry add scikit-image
```

## Version information
```
OS: Windows 10, Version 1909, Build 18363.1139
Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
```

**Comment by emmanuelle** [comment]
Hi @adam-grant-hendry thanks for reporting this. Does the error appear only with scikit-image? For example if you try to add `numpy` instead, does it work?

**Comment by emmanuelle** [comment]
Also I'm not sure if this is related (don't know much about poetry) but we don't provide wheels for python 3.9 (we will for the next release).

**Comment by adam-grant-hendry** [comment]
@emmanuelle Thank you for your help. I have `numpy` installed, so I don't believe `numpy` is failing, which is good. In fact, I believe it might have something to do with spaces in a path name. Similar searches for `WinError 123` errors with `pip` and `poetry` installations seem to indicate this. Unfortunately, I do believe the recommended fix is to install a wheel until the package can be updated.

**Comment by Harmon758** [comment]
Possibly related to https://github.com/numpy/numpy/issues/11451

**Comment by grlee77** [comment]
This seems to be a non scikit-image specific problem. Probably best to just track via the numpy/numpy#11451 issue linked above
