### ISSUE TITLE
Bug in ImageCollection

### ISSUE THREAD

**Issue by cosinus11** [scikit-image/scikit-image#5069]
## Description

The example provided by the documentation (https://scikit-image.org/docs/stable/api/skimage.io.html?highlight=collection#skimage.io.ImageCollection)
is not working. The example works only on version before commit https://github.com/scikit-image/scikit-image/pull/3928 
is there a problem in code or in the example that is not updated?

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```
class AVILoader:
    video_file = 'myvideo.avi'

    def __call__(self, frame):
        return video_read(self.video_file, frame)

avi_load = AVILoader()

frames = range(0, 1000, 10) # 0, 10, 20, ...
ic = ImageCollection(frames, load_func=avi_load)

x = ic[5] # calls avi_load(frames[5]) or equivalently avi_load(50)

## Version information
```python
# Paste the output of the following python commands

3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19041-SP0
scikit-image version: 0.17.2
numpy version:1.19.3

```python
# your output here

Traceback (most recent call last):
  File "test_avi.py", line 11, in <module>
    ic = ImageCollection(frames, load_func=avi_load)
  File "C:\ProgramData\Miniconda3\lib\site-packages\skimage\io\collection.py", line 188, in __init__
    raise TypeError('Invalid pattern as input.')
TypeError: Invalid pattern as input.
```

**Comment by mkcor** [comment]
Hi @cosinus11,

I'm not sure the example is supposed to just run, as it looks like it's defining a mock class... :thinking: 
But, yes, there is a change in behaviour with #3928: @alexdesiqueira could you please enlighten us? Thanks!

**Comment by alexdesiqueira** [comment]
Hi @cosinus11 @mkcor,
thank you for the issue, @cosinus11! I will check it and get back to y'all.

**Comment by cosinus11** [comment]
Thank you very much!

**Comment by alexdesiqueira** [comment]
Hey @cosinus11,
I think we started a discussion in #3928 to "simplify" `ImageCollection` (please check [this comment](https://github.com/scikit-image/scikit-image/pull/3928#discussion_r303211107) and the following ones).
That said, if that's still the case, it's time to deprecate that example — or maybe to offer an alternative to it. What do you think, @jni?

**Comment by mkcor** [comment]
I just realized that this issue was related to #2815, which I'm reviewing now.

**Comment by alexdesiqueira** [comment]
Related to #4859 as well; cross-linking it here.

**Comment by grlee77** [comment]
The current documentation example involving `vidread_step` worked fine when I tried today on a small `.mp4` video file. I got a sequence of color video frames each of shape (720, 1280, 3) as expected.

I think this has been resolved, but please reopen if not.
