### ISSUE TITLE
misleading commentary for peak_local_max example

### ISSUE THREAD

**Issue by odoublewen** [scikit-image/scikit-image#5078]
In the example `plot_peak_local_max.py`, the intro at the top states:

> The ``peak_local_max`` function returns the coordinates of local peaks (maxima)
in an image. __A maximum filter is used for finding local maxima. This operation
dilates the original image and merges neighboring local maxima closer than the
size of the dilation. Locations where the original image is equal to the
dilated image are returned as local maxima.__

Everything after the first sentence is either wrong or misleading.  The output of `maximum_filter()`, called `image_max`, is not used for locating the maxima.  It is only used for making a panel in the visualization, and its utility is not evident. 

I suspect this was left over from some previous approach.

https://github.com/scikit-image/scikit-image/blob/ad737acfc8515eb17f7ac731aa92ad77918c3b8b/doc/examples/segmentation/plot_peak_local_max.py#L20-L22

**Comment by mkcor** [comment]
Hi @odoublewen,

You are absolutely right, thanks for reporting!

The `peak_local_max` function changed multiple times since this example was written. Recently, it even underwent a global refactoring by @rfezzani (#4760).

Would you take a stab at updating the example? ;-)

**Comment by odoublewen** [comment]
Easy for examples like this to become out of sync with a rapidly improving codebase.  (And yes, elsewhere I already shouted out kudos to @rfezzani for the recent big improvements!)

I would be more than happy to open a PR with updated examples.  In this example, my first stab would be to simply eliminate the call `maxiumum_filter`, since I don't see how it is useful.  (Actually, it appears that even in the [earliest commit](https://github.com/scikit-image/scikit-image/blame/8c9777b9677d943f335d87cccb12d89e17614b96/doc/examples/plot_peak_local_max.py) of this example, `image_max` wasn't really used.)   I'll go ahead and make this update, and perhaps throw in some other stuff that might be of interest for peak finding.

Also, while I've got your attention: I found another discrepancy in the example documentation: the [API documentation for `peak_local_max()`](https://scikit-image.org/docs/dev/api/skimage.feature.html#peak-local-max) states: 
> `indices` `bool, optional`
... indices is deprecated and will be removed in version 0.20. Default behavior will be to always return peak coordinates. **You can obtain a mask as shown in the example below.**

The problem is, the "example below" (both the inline ones and the "examples using" references) _don't_ actually show how to obtain a mask from indices.  I am wanting to future-proof some of my code, so I would like to do this very thing.  My simple minded approach would be:

```
indices = peak_local_max(im)
mask = zeros_like(im)
for coord in indices:
    mask[coord] = 1
```

Is there a more "numpythonic" way to do it?  (I thought there might be an optimized method to do this, but haven't come across it yet.)  @mkcor Give me a pointer here, and I will also include this update to my PR.

**Comment by mkcor** [comment]
Hi again @odoublewen,

Wonderful! Thank you very much.

Parameter `indices` is meant to obtain either the coordinates (indices) or the mask of the peaks, so it's straightforward:
```py
mask = peak_local_max(im, indices=False)
```
or, in the context of the existing example,
```py
mask = peak_local_max(im, min_distance=20, indices=False)
```
:slightly_smiling_face:

**Comment by mkcor** [comment]
Oh, sorry, by 'future-proof' you probably meant without relying on the `indices` parameter? :woman_facepalming: 
Anyway, we probably want to remove this sentence:
https://github.com/scikit-image/scikit-image/blob/310b47f3a74d40c012d8522821b9e9e35b4b960e/skimage/feature/peak.py#L161-L162
or actually provide an example using `indices=False`.

**Comment by odoublewen** [comment]
> Oh, sorry, by 'future-proof' you probably meant without relying on the indices parameter?

Yes, exactly.  The deprecation warning even shows up in the online examples, [here for example](https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_watershed.html#sphx-glr-auto-examples-segmentation-plot-watershed-py):

> indices argument is deprecated and will be removed in version 0.20. To avoid this warning, please do not use the indices argument. Please see peak_local_max documentation for more details.

So if `indices` is going away and already generates a deprecation warning, rather than provide examples of using `indices=False` (which, by the way, two of the examples DO do), we should actually provide examples of NOT using the deprecated argument.

OK, so I should have thought of this -- I dug into peak_local_max to see how they handle `indices=False` internally:

It's here: https://github.com/scikit-image/scikit-image/blob/310b47f3a74d40c012d8522821b9e9e35b4b960e/skimage/feature/peak.py#L309-L314

I'll use this approach in my PR.

**Comment by mkcor** [comment]
> So if `indices` is going away and already generates a deprecation warning, rather than provide examples of using `indices=False` (which, by the way, two of the examples DO do), we should actually provide examples of NOT using the deprecated argument.

Yes, you are right. We should update these two gallery examples (i.e., "Watershed segmentation" and "Segment human cells (in mitosis)").

> https://github.com/scikit-image/scikit-image/blob/310b47f3a74d40c012d8522821b9e9e35b4b960e/skimage/feature/peak.py#L309-L314
> 
> I'll use this approach in my PR.

Good. I don't think `np.zeros_like` is necessary... Simply:
```py
mask = np.zeros(im.shape, dtype=bool)
mask[tuple(indices.T)] = True
```
Thanks again!
