### ISSUE TITLE
SLIC does not work for grayscale images, or RGB with convert2lab = False

### ISSUE THREAD

**Issue by oconnor127** [scikit-image/scikit-image#5093]
Hey,

for some reason slic does not work for grayscale images. Looking at the oversegmented images using mark_boundaries, I get a regular shaped chessboard (I guess the initial start with equally distributed seed points). 

rgb = io.imread(curr_img_path)           #shape (352,1216,3)
gray = color.rgb2gray(rgb)                   #shape (352,1216)
assignment_gray = slic(image=gray, n_segments=500, max_iter = 100, convert2lab=False)   #equally distributed, does not work
assignment_rgb = slic(image=rgb, n_segments=500, max_iter = 100, convert2lab=False)   #equally distributed, does not work

lab = color.rgb2lab(rgb)
assignment_lab1 = slic(image=lab, n_segments=500, max_iter = 100, convert2lab=False)   #works, but I dont want to convert to lab-space
assignment_lab2 = slic(image=rgb, n_segments=500, max_iter = 100) #works, but I dont want to convert to lab-space

Is that an issue or am I doing something wrong?

**Comment by emmanuelle** [comment]
Hi @oconnor127 you'll need to reduce the `compactness` parameter by a fair amount for slic to work on grayscale images. Compare for example
```
from skimage import segmentation, data, color
img = data.chelsea()
segments = segmentation.slic(img, n_segments=100)
import matplotlib.pyplot as plt
plt.imshow(segmentation.mark_boundaries(img, segments))
plt.show()
```
![image](https://user-images.githubusercontent.com/263366/100846079-60d49400-347e-11eb-91fb-921341023972.png)
and 
```
from skimage import segmentation, data, color
img = color.rgb2gray(data.chelsea())
segments = segmentation.slic(img, n_segments=100, compactness=.1)
import matplotlib.pyplot as plt
plt.imshow(segmentation.mark_boundaries(img, segments))
plt.show()
```
![image](https://user-images.githubusercontent.com/263366/100846175-79dd4500-347e-11eb-9aa9-7d454e617b77.png)

**Comment by emmanuelle** [comment]
Also you wrote in comments that you don't want to covert to Lab space but this is really recommended for slic segmentation!

**Comment by oconnor127** [comment]
Thanks for your answer :)

Yepp thats true that the docs says it. But sometimes either have just grayscale images or want to avoid the lab-conversion time ;)

**Comment by jni** [comment]
@oconnor127 I think @emmanuelle's response answers your question? I'll close this, but feel free to reopen if you have more questions!
