### ISSUE TITLE
skimage.measure.label is not working correctly for non binary 3d array

### ISSUE THREAD

**Issue by anillspawar** [scikit-image/scikit-image#5100]
skimage.measure.label is giving a lot more than expected number of connected components for non binary image. But when I am passing after binarization it’s giving likely correct result with very less number of connected components.
So is this API works on binary images only, although document says it works for int type images?

**Comment by jni** [comment]
Resolved in https://forum.image.sc/t/skimage-measure-label-is-not-working-correctly-for-non-binary-3d-array/46171

Thanks @anillspawar for the question!
