### ISSUE TITLE
feret_diameter_max not available

### ISSUE THREAD

**Issue by annukkaa** [scikit-image/scikit-image#5102]
I would like to access feret_diameter_max property but it is not available, even though it is described in the documentation.
I recently updated scikit-image (using conda update) to version 0.17.2.
I'm using python 3.7.0

Plus I have an additional question: how to obtain feret_diameter_max or other properties of the image which depend on the spacing between voxels? How to take this spacing into consideration?

**Comment by jni** [comment]
@annukkaa 

> I recently updated scikit-image (using conda update) to version 0.17.2.

Unfortunately, you've found the documentation for the development version of scikit-image! You can try it out by installing the pre-release 0.18.0rc0 with pip. We hope 0.18 will be out very shortly, including in conda-forge, but there's a lot of last minute adjustments we're trying to make. Hold please! 😬 

> how to obtain feret_diameter_max or other properties of the image which depend on the spacing between voxels?

Unfortunately, we don't support spacing in regionprops yet: everything is assumed to be isotropic. Could you raise another issue as a feature request to add voxel spacing to regionprops? skimage.measure is an ongoing area of priority for us so we might fix that for the next (0.19) release.

**Comment by annukkaa** [comment]
Thanks for your reply! I will raise another issue

**Comment by annukkaa** [comment]
May I also ask if the feret_diameter_max property available in 0.18.0rc0 supports 3D images? 

I've read in some of the issues that most of the properties in regionprops are available for 3D images, however this doesn's seem to be clear from the documentation

**Comment by grlee77** [comment]
> May I also ask if the feret_diameter_max property available in 0.18.0rc0 supports 3D images?

Yes, 3D is also supported for this measurement.

**Comment by jni** [comment]
> I will raise another issue

Great! I'll close this one then since it is fixed on master. Thank you!
