### ISSUE TITLE
Feature request: add voxel spacing to skimage.measure.regionprops

### ISSUE THREAD

**Issue by annukkaa** [scikit-image/scikit-image#5112]
No support yet for anisotropic images in the properties of regionprops

**Comment by jni** [comment]
Thanks for raising, @annukkaa! I hope we can implement this before the next release, as it would be very useful!

**Comment by jni** [comment]
Another request for this on SO: https://stackoverflow.com/questions/66318020/set-scale-of-pixels-in-microns-in-python

This should be a high priority.

**Comment by tibuch** [comment]
Hello everyone,

What is the state of this feature request? I am also at a point where I would like to use anisotropic spacings with regionprops. I looked a bit into the code and I think most of the features will work once the moments computation supports spacings.

Is there someone working on this already? Otherwise I am happy to start.

Thanks and best wishes!

**Comment by grlee77** [comment]
Hi @tibuch. Yes, it would be great to have this. I have been working on a couple things related to the moments code recently, but not specifically to do with anisotropic spacing. If you wanted to add that, it would be great. I think it should be fairly straightforward to add this to the existing Python `moments` functions and am happy to help review the code or chat with you if you get stuck.

This recent PR refactors how central moments are calculated from the raw moments: https://github.com/scikit-image/scikit-image/pull/6188. Don't worry about breaking anything in that PR with your changes. I will refactor it as necessary to take into account the anisotropic functionality.

**Comment by grlee77** [comment]
There was also a recent request for anisotropic regionprops on the image.sc forum: https://forum.image.sc/t/scaling-regionprops-for-non-isotropic-images/61971/3. @jni linked to a branch where he had started that at one point. As far as I know he is not actively working on that at the moment and would be happy for someone to take this up.
