### ISSUE TITLE
Possible bug in label connected regions in large volume crushes all kernel

### ISSUE THREAD

**Issue by JuanIgnacioCG** [scikit-image/scikit-image#5124]
## Description
I have used several times the label function of scikit but this is the largest volume I have used so far. I tried the label with connectivity = 3 but the kernel was crushing repeatly, then changed it to connectivity =2 and after taking almost 80 GB of RAM was able to throw a result. Then I compaired it with the label feature of ndimage library, it finished faster and not taking even 20 GB of RAM. Out of curiosity, visualize both of them using the napari library.

In the video below the tag "labels[1]" is the result of the ndimage label, while "label" tag is the scikit-image label output.
https://youtu.be/waXdlIVgk2M
I uploaded to youtube to make it more accesible

## Way to reproduce

#LIBRARIES
### work in jupyterlab
import Pred_tomo as ptom
import pandas as pd
import numpy as np
from skimage.measure import regionprops
from pathlib import Path
from PIL import Image
import napari
from scipy.ndimage import label, generate_binary_structure
%gui qt5

## Code to open a tif volume as numpy array from path..etc I get a numpy array called "prob_l"
prob_l.shape          #output (7443, 1771, 234)

## Compute the labels with the 2 libraries
import skimage.measure
skimage_labels_p_l = skimage.measure.label(prob_l,connectivity=2)
labels_p_l = label(prob_l)  #NDimage label

##### ptom.axis_napari is a simple func I defined to have the same coordinate system in napari visualizer than Imagej.
'''
def axis_napari(array):
    array = np.transpose(array, (2,0,1))
    return(array)
'''
viewer = napari.view_labels(ptom.axis_napari(skimage_labels_p_l))
viewer.add_labels(ptom.axis_napari(labels_p_l[0]))

## Version information
```python
# Paste the output of the following python commands
>>> import sys; print(sys.version)
3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
>>> import platform; print(platform.platform())
Windows-10-10.0.18362-SP0
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.16.2
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.18.1
```

**Comment by alexdesiqueira** [comment]
Hey @JuanIgnacioCG, thank you very much for the detailed issue! I'm also very fond of the video, thank you for your effort on that.
Could we have access to the data you are using on your tests? If that's not possible, could you provide more details on that?
File size, data type, and so on.
Again, thank you for your help!

**Comment by jni** [comment]
I think the problem here is that `prob_l` is a grayscale image, which `scipy.ndimage.label` implicitly converts to bool, while `skimage.measure.label` finds all the same-valued connected components. Coincidentally, this very closely related issue was raised only a few days ago: #5100. See the link therein for a more thorough explanation.

@JuanIgnacioCG in order to match the `ndimage` output, you should use `measure.label(prob_l > 0)`. Does this resolve your issue?

**Comment by JuanIgnacioCG** [comment]
> 
> 
> I think the problem here is that `prob_l` is a grayscale image, which `scipy.ndimage.label` implicitly converts to bool, while `skimage.measure.label` finds all the same-valued connected components. Coincidentally, this very closely related issue was raised only a few days ago: #5100. See the link therein for a more thorough explanation.
> 
> @JuanIgnacioCG in order to match the `ndimage` output, you should use `measure.label(prob_l > 0)`. Does this resolve your issue?

**Comment by JuanIgnacioCG** [comment]
Hello again, 
my first choice was to not share the data but I think it is fine. The following is a link to download prob_l, a binary 2.9 GB multiframe tiff:
https://upm365-my.sharepoint.com/:i:/g/personal/juanignacio_caballero_upm_es/EUYB6NPsa6VEj7z4iHYuFLMBG5QArkK3Lo-n6p4t5RpxXQ?e=styg6a

the full code to load it and perform labels is:
## LIBRARIES
import Pred_tomo as ptom
import importlib
importlib.reload(ptom)
import pandas as pd
import numpy as np
from skimage.measure import regionprops
from pathlib import Path
from PIL import Image
import napari
from scipy.ndimage import label, generate_binary_structure
%gui qt5

## READING IMG VOLS
### ptom is an utils library, this is the function to read tiff I have
'''
def napari_read_tiff(pathlibpath,start=0, folder=False, nframes='all'):
    '''
    Read a multiframe tif image and loads it in a numpy array
    '''
    if not folder:
        with Image.open(str(pathlibpath), mode='r') as img:
            stack = []
            if nframes == 'all':

                try:
                    for i in range(start,img.n_frames):
                        img.seek(i)
                        stack.append(np.array(img))
                except:
                    print(i)
                    pass
        #     else:
        #         for i in range(start,nframes):
        #             img.seek(i)
        #             stack.append(np.array(img))
    if folder:
        files = listdir(pathlibpath)
        stack = []
        for file in files:
            filepath = pathlibpath / file
            with Image.open(str(filepath),mode='r') as img:
                stack.append(np.array(img))
    
    return np.transpose(np.array(stack), (1, 2, 0))  # to match imagej coordinate system
'''
directorio = Path(r"folder_to_read")
imagen1 = "couponL"

then it follows with the code I posted before.
ruta1 = directorio /  imagen1
prob_l = ptom.napari_read_tiff(ruta2)

**Comment by JuanIgnacioCG** [comment]
> 
> 
> I think the problem here is that `prob_l` is a grayscale image, which `scipy.ndimage.label` implicitly converts to bool, while `skimage.measure.label` finds all the same-valued connected components. Coincidentally, this very closely related issue was raised only a few days ago: #5100. See the link therein for a more thorough explanation.
> 
> @JuanIgnacioCG in order to match the `ndimage` output, you should use `measure.label(prob_l > 0)`. Does this resolve your issue?

I double check and the histograms of the volume in the image is totally binary.

**Comment by jni** [comment]
Ok, finally figured this out. The problem is that the volume is bigger than 2GB, and we [use raveled coordinates](https://github.com/scikit-image/scikit-image/blob/576885f67753fdd9c8245740244ee0338a93b5c5/skimage/measure/_ccomp.pyx#L189), and those coordinates are defined as being of type `long`, and that [resolves to int32](https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges?view=msvc-160) on certain Windows compilers.

Therefore, you're getting overflow on the indices, and things don't resolve to being in the same neighbourhood anymore, and you get massive growth in the number of connected components.

We should at least throw an informative error when the data size exceeds 2GB and the platform `long` resolves to int32. Thanks for reporting @JuanIgnacioCG! 

I'm not sure how one gets a Python version with `long == int64` on Windows. Does anyone at @scikit-image/core know?

**Comment by rfezzani** [comment]
Can't using `size_t` instead of `long` solve the problem?

**Comment by alexdesiqueira** [comment]
@JuanIgnacioCG could you check if this is solves your issue? You'd need to use the [development version](https://scikit-image.org/docs/dev/install.html#installing-scikit-image-for-contributors) to test that.

**Comment by JuanIgnacioCG** [comment]
> 
> 
> @JuanIgnacioCG could you check if this is solves your issue? You'd need to use the [development version](https://scikit-image.org/docs/dev/install.html#installing-scikit-image-for-contributors) to test that.

Yeah I will, probably tomorrow. I'm glad to be of help! @jni

**Comment by jni** [comment]
Note that you can get pre-compiled wheels from our GitHub Actions tab, in this case here:

https://github.com/scikit-image/scikit-image/actions/runs/426166668

Once unzipped you can `pip install path/to/<wheel-for-your-platform>.whl`

**Comment by alexdesiqueira** [comment]
> Note that you can get pre-compiled wheels from our GitHub Actions tab, in this case here:
> 
> https://github.com/scikit-image/scikit-image/actions/runs/426166668
> 
> Once unzipped you can `pip install path/to/<wheel-for-your-platform>.whl`

+1; it's easier to follow @jni's suggestion here @JuanIgnacioCG.

**Comment by JuanIgnacioCG** [comment]
Hello to all,
I installed the wheels and perform the test and everything is fine. The number of regions matches the one of ndi. Thanks for the support!

**Comment by rfezzani** [comment]
:tada: That's an excellent news! Thank you for your help @JuanIgnacioCG!

**Comment by jni** [comment]
Awesome! @JuanIgnacioCG out of curiosity, did this improve RAM usage by skimage?

**Comment by JuanIgnacioCG** [comment]
> 
> 
> Awesome! @JuanIgnacioCG out of curiosity, did this improve RAM usage by skimage?

I did not check carefully, but well of course it is now better than when it was failing.  If I compare it to  ndi label I think they are approximately using the same RAM also.
