### ISSUE TITLE
Confusing error message when Cython is not installed

### ISSUE THREAD

**Issue by mok0** [scikit-image/scikit-image#5127]
## Description

When building `scikit-image` using `python3 setup.py install`, and you do not have Cython installed, an error message tells you to install NumPy. This happens in `setup.py` around line 199 after an ImportError exception has been thrown in line 178.

## Way to reproduce
```python
pip3 uninstall cython
python3 setup.py build

```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
#import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.9.0 (default, Dec  6 2020, 18:02:34)
[Clang 12.0.0 (clang-1200.0.32.27)]
macOS-10.15.7-x86_64-i386-64bit
# skimage not installed yet
numpy version: 1.19.4


```

**Comment by hmaarrfk** [comment]
can you provide us the error log?

**Comment by mok0** [comment]
I'm not really sure why you need it? `setup.py` attempts to import cython, and if that triggers an ImportError, it writes the following errormessage and halts:

```
To install scikit-image from source, you will need NumPy.
Install NumPy with pip using:
    pip install numpy
 Or use your operating system package manager. For more
 details, see:
   https://scikit-image.org/docs/stable/install.html
```

All you have to do is to edit setup.py and change the message to:

```
To install scikit-image from source, you will need Cython.
Install Cython with pip using:
    pip install cython
 Or use your operating system package manager. For more
 details, see:
   https://scikit-image.org/docs/stable/install.html

```

**Comment by hmaarrfk** [comment]
Thanks. Pull requests are welcome!

**Comment by mok0** [comment]
Oh, c'mon, it's litterally 3 words you need to change.

**Comment by jni** [comment]
@mok0 thanks for the report. We do have a long backlog of issues including [constant](https://github.com/scikit-image/scikit-image/issues/5103) [churn](https://github.com/scikit-image/scikit-image/issues/5130) in the ecosystem so any little help is appreciated! Including this report. 🙏 

We do aim to ultimately deprecate `python setup.py install` in favour of `pip install -e .`, which bypasses this problem altogether by using pyproject.toml to declare build dependencies.

**Comment by hmaarrfk** [comment]
Sorry for my short response that didn't explain context.

There were a few PRs that we had to be involved in to get things working for Python 3.9. It wasn't as smooth of a migration (especially on OSX).

We are trying to get it 0.18 through which should get wheel builds for python 3.9.

Do note that github makes it really easy to suggest 1 line changes on their web interface without the usual fork, clone, and PR model. Since you had done the hard work of tracking it all down, I thought it would have been interesting to get your name on the PR.
