### ISSUE TITLE
0.18.x missing on github 

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#5185]
## Description

See https://github.com/scikit-image/scikit-image/releases :)

**Comment by jni** [comment]
How does one fix this? 😂

**Comment by sciunto** [comment]
I pushed two "releases" on github, v0.18.0 and v0.18.1. For v0.18.1, the content is somehow duplicated, but I guess it is ok.

**Comment by jni** [comment]
Closed by #5187 + manual updates by @sciunto. Thanks @sciunto for the PR and pushing those releases!
