### ISSUE TITLE
Most skimage.measure._moments module functions don't support float32 operations

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#5199]
## Description

Most of `skimage.measure._moments` module functions only supports double precision float operations. It is even explicitly stated in some functions' documentation that the input must be `double` or `uint8` ([`moments`](https://scikit-image.org/docs/stable/api/skimage.measure.html?highlight=moments_hu#moments), [`moments_central`](https://scikit-image.org/docs/stable/api/skimage.measure.html?highlight=moments_hu#moments-central), [`moments_coords`](https://scikit-image.org/docs/stable/api/skimage.measure.html?highlight=moments_hu#moments-coords)...). I don't understand why :confused:.

**Comment by rfezzani** [comment]
Related to #4308 :sweat_smile:

**Comment by grlee77** [comment]
Also related to #5205. @rfezzani, I just merged your `moments_hu` PR. Are you planning to work on the other moments functions? (I can spend some time this week looking at float32 stuff again, but don't want to duplicate effort)

**Comment by rfezzani** [comment]
Hi @grlee77, and sorry for my late answer, I am too busy these days :confused:. I didn't planned to spend time on this topic, you can go ahead if you wish :wink:
