### ISSUE TITLE
Small typo in utils.py

### ISSUE THREAD

**Issue by Devanshu24** [scikit-image/scikit-image#5203]
## Description
Small typo in the docs

The class docs have the argument name as `arg_mapping`
https://github.com/scikit-image/scikit-image/blob/87a8806cca7fb5366b6e5ddbe5e46364b44f90fe/skimage/_shared/utils.py#L119
However, the actual `__init__` method takes the argument with the name `kwarg_mapping`
https://github.com/scikit-image/scikit-image/blob/87a8806cca7fb5366b6e5ddbe5e46364b44f90fe/skimage/_shared/utils.py#L131

**Comment by rfezzani** [comment]
Good catch, thank you for the report @Devanshu24 :wink:

**Comment by Devanshu24** [comment]
@rfezzani Your welcome! I'll send a PR right away :)
