### ISSUE TITLE
3.7 minimum requirements test builds are failing

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#5211]
Example failed run:

https://github.com/scikit-image/scikit-image/runs/1801995691?check_suite_focus=true

**Comment by grlee77** [comment]
I think this is due to a combination of recent changes in `pip` with the lack of Python 3.7 wheels for our minimum scipy and matplotlib and pillow.

I will make a PR bumping to more recent minimum versions that are still >= 48 months old.
