### ISSUE TITLE
regionprops_table max_intensity and min_intensity are clipped to integer for a float intensity_image

### ISSUE THREAD

**Issue by yfukai** [scikit-image/scikit-image#5222]
## Description

When I use `measure.regionprops_table` with a float intensity_image, I found the `max_intensity` and `min_intensity` are clipped to the floor integer and inconsistent with the result of `measure.regionprops`. I suppose this is a bug and would like to ask for opinion.

## Way to reproduce
```python
from skimage import measure
testimg=(np.arange(0,9)*0.1).reshape((3,3))
testmask=np.zeros((3,3),dtype=np.int16)
testmask[:,1]=1

print(testimg)
print(testmask)

res1=measure.regionprops(testmask,testimg)[0]
print(res1.max_intensity,res1.min_intensity,res1.mean_intensity)
properties=["label","area","max_intensity","min_intensity","mean_intensity"]
res2=measure.regionprops_table(testmask,testimg,properties=properties)
print(res2)

""" 
the output is
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
[[0 1 0]
 [0 1 0]
 [0 1 0]]
0.7000000000000001 0.1 0.4000000000000001
{'label': array([1]), 'area': array([3]), 'max_intensity': array([0]), 'min_intensity': array([0]), 'mean_intensity': array([0.4])}
"""
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-debian-buster-sid
scikit-image version: 0.18.0
numpy version: 1.19.1
```

Thanks!

**Comment by rfezzani** [comment]
Thank you for the report @yfukai, I confirm the bug... It is probably related to the fact that `min_intensity` and `max_intensity` are marked as `int` in [COL_DTYPES](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_regionprops.py#L72).

**Comment by yfukai** [comment]
Thank you @rfezzani for your response! If still no one is working on this, I'd like to consider writing a test and fix for this. I think adding some test in [regionprops test](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/tests/test_regionprops.py) would be useful, but what is a good strategy do you think? Could I just add a variable, for example `SAMPLE_FLOAT` to test this issue, or is there any better way to rewrite?

**Comment by jni** [comment]
@yfukai we would absolutely love a PR with a fix!

> Could I just add a variable, for example SAMPLE_FLOAT to test this issue

This seems reasonable to me. I'd say go for it!

**Comment by mkcor** [comment]
@yfukai I think that, in the [PR description](https://github.com/scikit-image/scikit-image/pull/5239#issue-573848175), you wanted to write "Fixes #5222" (instead of "Fixes issue #5222") for this issue to get closed automatically (upon merging #5239 into `master`).

**Comment by mkcor** [comment]
@yfukai confirming, just found a reference: https://github.blog/2013-05-14-closing-issues-via-pull-requests/

**Comment by yfukai** [comment]
Oh yeah, I just noticed I wrote in a wrong way. Thanks a lot to letting me know this!
