### ISSUE TITLE
Wrong order in hessian_matrix?

### ISSUE THREAD

**Issue by catalys1** [scikit-image/scikit-image#5230]
## Description

In `hessian_matrix`, when `order='rc'`, the elements are supposed to be returned as `(Hrr, Hrc, Hcc)`. But if I'm understanding the code correctly, it instead returns `(Hcc, Hrc, Hrr)`:
```python
    gradients = np.gradient(gaussian_filtered)
    axes = range(image.ndim)

    if order == 'rc':  # I think this line is wrong -- should be if order == 'xy'
        axes = reversed(axes)

    H_elems = [np.gradient(gradients[ax0], axis=ax1)
               for ax0, ax1 in combinations_with_replacement(axes, 2)]
```

Note that when `order == 'rc'`, then
```python
axes = reversed(range(2))
combinations = list(combinations_with_replacement(axes, 2))
combinations
```
which yeilds `[(1, 1), (1, 0), (0, 0)]`, putting columns first instead of rows.

Am I correct that this isn't the intended behavior?

**Comment by grlee77** [comment]
Thanks, @catalys1. Apologies that this one slipped through the cracks. You are correct that this function does the opposite order of what is described in the docstring.

I opened #6624 to resolve the issue.
