### ISSUE TITLE
exposure.equalize_adapthist doesn't work for 3D data, and error with calling cells3d

### ISSUE THREAD

**Issue by aziabari** [scikit-image/scikit-image#5237]
## Description
when I ran this code:
https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_adapt_hist_eq_3d.html#sphx-glr-download-auto-examples-color-exposure-plot-adapt-hist-eq-3d-py

I get this error:

ImportError: cannot import name 'cells3d' from 'skimage.data' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/skimage/data/__init__.py)

it seems it cannot find the data

**Comment by jni** [comment]
@aziabari can you update your installed version of scikit-image? That function is only available in scikit-image v0.18.1. You probably have an earlier version.

Additionally, it seems you are using the macOS system Python, which is generally a bad idea. You should instead work in an *environment*, which is like a little isolated Python installation. Here's a couple of guides about this:

- https://realpython.com/effective-python-environment/
- https://realpython.com/python-virtual-environments-a-primer/
- https://towardsdatascience.com/getting-started-with-python-environments-using-conda-32e9f2779307

I don't think this is an issue with our software, but rather with an installation, so I'm going to close the issue, but feel free to continue the discussion if you need more guidance!
