### ISSUE TITLE
Where is the warp api of python but not the 'fast_warp' of cython?

### ISSUE THREAD

**Issue by Joevaen** [scikit-image/scikit-image#5248]
## Description
The 'fast_warps' api is here. It is based on Cython.I want to know where is the old python 'warp' api?
![image](https://user-images.githubusercontent.com/46133615/108931294-5f33fa00-7682-11eb-8a77-b336492dcd11.png)
Is it here?
![image](https://user-images.githubusercontent.com/46133615/108931581-d5386100-7682-11eb-9379-fb7c777df209.png)

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
Linux-5.4.0-65-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.17.2
numpy version: 1.19.2
```

**Comment by jni** [comment]
@Joevaen I don't really understand your question? Here is our documentation for `skimage.transform.warp`, which is what I think you're after:

https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.warp

It hasn't changed places in about a decade so I don't know where the confusion is! 😅 

I'm going to close this issue as I don't think it's a code issue, but please feel free to continue the discussion if you need further clarification!

**Comment by Joevaen** [comment]
Sorry about not describe my question clearly. 
I notice there is two file about warp in scikit-image/skimage/transform/. Usually, some projects like to using the _warps_cy.pyx because it is based on Cython and it is faster. Am I right? 
But it is not enough quickly for me, so I want to try to modify the python 'warp' which doesn't use Cython. Maybe Cupy taking place of Numpy will be better option to speed it up. I just wanna try.
In the _warps_cy.pyx, there is api named `_warp_fast` like below:
![image](https://user-images.githubusercontent.com/46133615/108959881-05e2bf80-76b0-11eb-88da-ccfa946e192c.png)
Does it correspond to the api named `warp`in _warps.py like below:
![image](https://user-images.githubusercontent.com/46133615/108960056-46423d80-76b0-11eb-80f3-0848eb9de582.png)
if they have same input image, do they have same output?
Thank for your kindness!
Best,
Joevaen.

**Comment by jni** [comment]
Yes, *under certain circumstances*, they are the same. You can see that the `_warp_fast` Cython function is imported into Python in this line:

https://github.com/scikit-image/scikit-image/blob/be6e3dc108835e1dbf851eecd7fabf355940800a/skimage/transform/_warps.py#L8

And then `warp` calls `_warp_fast` here:

https://github.com/scikit-image/scikit-image/blob/be6e3dc108835e1dbf851eecd7fabf355940800a/skimage/transform/_warps.py#L871-L884

This is used when the transform is linear and the interpolation is of order 0, 1, or 3. If those conditions aren't met, then a slower path is taken.
