### ISSUE TITLE
Add rolling ball example for ECG data

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#5255]
## Description

The demo I made for this response in the PyWavelets google group would be nice to include in our gallery to show that the "n-dimensional" implementation of rolling ball allows application to signals as well:
https://groups.google.com/g/pywavelets/c/b3ErI_GmNBo

Fortunately, the short ECG waveform used for the example there is already bundled by PyWavelets.

**Comment by sebgoti** [comment]
Hello :) May I take this issue?

**Comment by grlee77** [comment]
sure, that would be great! Please let us know if you need help/guidance. The current rolling ball example is located at `doc/examples/segmentation/plot_rolling_ball.py`. I think it may make sense to extend that one, but another possibility is making a new file.

**Comment by sebgoti** [comment]
> sure, that would be great! Please let us know if you need help/guidance. The current rolling ball example is located at `doc/examples/segmentation/plot_rolling_ball.py`. I think it may make sense to extend that one, but another possibility is making a new file.

Thanks @grlee77, this is my first contribution and I followed all the guidelines, I hope everything is in order but please let me know about any errors. I wanted to ask you about an idea I had to extend the rolling ball example by creating a short animation of a circle rolling on the ECG data while generating the background output. I thought that it might be a good visualization to understand better the whole rolling ball concept. Cheers, Sebastian
