### ISSUE TITLE
label() segfault with arrays of shape (n,0,m) on linux + anaconda

### ISSUE THREAD

**Issue by dogenstein** [scikit-image/scikit-image#5260]
## Description

Hello!

I know this is a very weirdly shaped array to be labeling, but it was unintentional :~)

I haven't seen any similar issues, but sorry if this is a duplicate. #1479 seems similar but the code there runs without problems for me.

Also checked on windows and it doesn't happen there btw. Also, I'm using anaconda..

## Way to reproduce
```python
import numpy as np
from skimage.measure import label

a = np.zeros((300,300,300))
a = a[:,0:0,:]

label(a)
```

## Version information
```python
>>> from __future__ import print_function
>>> import sys; print(sys.version)
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
>>> import platform; print(platform.platform())
Linux-5.8.0-44-generic-x86_64-with-glibc2.10
>>> import skimage; print("scikit-image version: {}".format(skimage.__version__))
scikit-image version: 0.17.2
>>> import numpy; print("numpy version: {}".format(numpy.__version__))
numpy version: 1.19.2
```

```python
# your output here
Segmentation fault (core dumped)
```

**Comment by rfezzani** [comment]
Thank you @dogenstein for the report.

I can reproduce the issue with v16.2, v17.2 but not with current dev version :tada:, so this will hopefully be solved in next release :wink:

**Comment by jni** [comment]
Hmmm, unfortunately I can reproduce on the main branch, @rfezzani...

**Comment by rfezzani** [comment]
Hum, strange...
```python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from skimage.measure import label
>>> 
>>> a = np.zeros((300,300,300))
>>> a = a[:,0:0,:]
>>> 
>>> label(a)
array([], shape=(300, 0, 300), dtype=int64)
>>> import skimage
>>> skimage.__version__
'0.19.0.dev0'
>>> 
```

**Comment by jni** [comment]
yeah sorry, I just realised that master was very old on this computer, trying again, hold please...

**Comment by jni** [comment]
> very old

9d502e25e to be precise

**Comment by jni** [comment]
Gah. Nope, still segfaulting, platform info:

```
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from skimage.measure import label
>>> 
>>> a = np.zeros((300,300,300))
>>> a = a[:,0:0,:]
>>> 
>>> label(a)
Segmentation fault (core dumped)
```

My commit is f5e9b61e2c4935f181a2de6fcbc4f728e03baa23

@rfezzani seems unlikely that it would be a 3.7 vs 3.8 bug but can you check anyway?

**Comment by jni** [comment]
Also my local cython version is 0.29.21.

**Comment by rfezzani** [comment]
@jni, I confirm the segfault using python 3.8, cython 0.29.22 and numpy 1.19.2 :sob:
