### ISSUE TITLE
rescale and other warp functions should preserve input range and dtype

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#5268]
## Description

See this StackOverflow question for the motivation:

https://stackoverflow.com/questions/66585291/skimage-rescale-segmentation-mask

For higher-order interpolation, we need to do floating point arithmetic so it makes sense to convert to float and change the intensity scale as per our data type rules. For order=0, though, I think it makes most sense to preserve the input dtype and range.

```python
In [1]: import numpy as np
In [2]: from skimage import transform
In [3]: seg_mask = np.random.randint(0, 2**16, size=(16, 16)).astype(np.uint16)
In [4]: transform.rescale(seg_mask, 0.5, order=0)
Out[4]:
array([[0.5222858 , 0.55330739, 0.76211185, 0.61666285, 0.45897612,
        0.19795529, 0.52283513, 0.56203555],
       [0.57460899, 0.81582361, 0.61560998, 0.68281071, 0.3169604 ,
        0.19830625, 0.40459297, 0.48615244],
       [0.47759213, 0.62240024, 0.76609445, 0.333196  , 0.88154421,
        0.43877317, 0.50019074, 0.65618372],
       [0.84681468, 0.58448157, 0.56137942, 0.2824445 , 0.76746777,
        0.75156786, 0.47310597, 0.66036469],
       [0.18850996, 0.60334173, 0.25194171, 0.83747616, 0.56156252,
        0.61664759, 0.80070192, 0.48683909],
       [0.29718471, 0.3195697 , 0.32796216, 0.58196384, 0.81673915,
        0.50057221, 0.48458076, 0.27048142],
       [0.52285039, 0.35194934, 0.84243534, 0.68207828, 0.66150912,
        0.46347753, 0.23147936, 0.84484627],
       [0.51114672, 0.35536736, 0.87023728, 0.44734874, 0.6835584 ,
        0.54543374, 0.43472953, 0.78928817]])

In [5]: transform.rescale(seg_mask, 0.5, order=0, preserve_range=True)
Out[5]:
array([[34228., 36261., 49945., 40413., 30079., 12973., 34264., 36833.],
       [37657., 53465., 40344., 44748., 20772., 12996., 26515., 31860.],
       [31299., 40789., 50206., 21836., 57772., 28755., 32780., 43003.],
       [55496., 38304., 36790., 18510., 50296., 49254., 31005., 43277.],
       [12354., 39540., 16511., 54884., 36802., 40412., 52474., 31905.],
       [19476., 20943., 21493., 38139., 53525., 32805., 31757., 17726.],
       [34265., 23065., 55209., 44700., 43352., 30374., 15170., 55367.],
       [33498., 23289., 57031., 29317., 44797., 35745., 28490., 51726.]])
```

## Way to reproduce
```python
import numpy as np
from skimage import transform
seg_mask = np.random.randint(0, 2**16, size=(16, 16)).astype(np.uint16)
print(transform.rescale(seg_mask, 0.5, order=0))
print(transform.rescale(seg_mask, 0.5, order=0, preserve_range=True))
```

**Comment by grlee77** [comment]
I agree about doing this for order=0. Should also do it for all other orders?

By default, all functions in `scipy.ndimage.interpolation` preserve dtype. If the `output` argument is not specified then an output array is allocated with the same dtype as the input. Internally interpolations are always done in double precision in the C code, but the result is cast back to the output dtype for storage into the output array.

I think the current conversions to float in current scikit-image code are there mainly for compatibility with the `_warp_fast` Cython code used in some 2D cases. When using `ndimage.zoom`, `ndimage.map_coordinates`, etc, we do not have to convert the input to float first. Even if you want float output for integer input you don't have to cast the input to integers first, you only have to specify `output=float`.

**Comment by rfezzani** [comment]
I have no strong opinion for `order > 0`, my only fear is that it is a major behaviour change, so it launches a deprecation cycle may be painful for `skimage` users. We can let the responsibility to the user if a recast to input dtype is needed since internal computations are always performed with floating points operations.

Concerning `order = 0`, we can consider it a bug fIx, so no deprecation...

**Comment by grlee77** [comment]
I agree that it would be a sudden change in behavior that might annoy users. That is why I wanted to determine if this was desired so we could plan it for the 1.0 release if needed.

**Comment by mkcor** [comment]
Speaking of preserving input ranges, PR #5281 makes our Gaussian filter preserve them *by default*... :eyes:
