### ISSUE TITLE
Error in documentation for watershed

### ISSUE THREAD

**Issue by Make42** [scikit-image/scikit-image#5278]
The [documentation for watershed](https://scikit-image.org/docs/dev/api/skimage.segmentation.html#skimage.segmentation.watershed) says

> image : ndarray (2-D, 3-D, …) of integers
> Data array where the lowest value points are labeled first.

But when I look into the code and the [official example](https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_watershed.html), it seems that watershed is actually dealing with float arrays, not integer arrays. I think this might be a mistake in the documentation. If not, please explain how so. If so, I would be happy if someone - who knows how - could correct the documentation.

**Comment by mkcor** [comment]
Hi @Make42,

Thank you for reporting! You are absolutely right; and even if the `image` ndarray does not already have dtype float64, it gets cast into a float array at
https://github.com/scikit-image/scikit-image/blob/a69d49272145d9839df75f3ee398c0bbde32f448/skimage/segmentation/_watershed.py#L204
through
https://github.com/scikit-image/scikit-image/blob/a69d49272145d9839df75f3ee398c0bbde32f448/skimage/segmentation/_watershed.py#L90

To submit this tiny change, I used the GitHub interface: Right from the [source file](https://github.com/scikit-image/scikit-image/blob/main/skimage/segmentation/_watershed.py#L95-L228), I clicked "Edit this file" in the top right corner, removed " of integers" in the online editor, and went ahead with the pull request. In the general case, you would follow these steps: https://scikit-image.org/docs/stable/contribute.html
