### ISSUE TITLE
exposure.histogram flattens color images

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#529]
In the exposure.histogram function, the histogram is computed on the flattened array. This is fine for grayscale images, but is it what we want for color images? Another possibility would be to return one histogram per channel. What do you think? At least the behavior for color images should be documented in the docstring.

**Comment by soupault** [comment]
@emmanuelle I suppose this issue already adressed and should be closed - see https://github.com/scikit-image/scikit-image/blob/master/skimage/exposure/exposure.py#L29 .

**Comment by JDWarner** [comment]
@soupault That's correct, this one is done.
