### ISSUE TITLE
old and new camera images are used randomly in the gallery

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#5292]
## Description

Ex: Old version: https://scikit-image.org/docs/stable/auto_examples/edges/plot_edge_filter.html#sphx-glr-auto-examples-edges-plot-edge-filter-py
New version : https://scikit-image.org/docs/stable/auto_examples/registration/plot_masked_register_translation.html#sphx-glr-auto-examples-registration-plot-masked-register-translation-py

Looks like there is a cache issue (not cleared after the change in the dataset).

**Comment by jni** [comment]
Wow!

**Comment by grlee77** [comment]
I think this is no longer an issue (current stable docs look like they are all the new cameraman)
