### ISSUE TITLE
MrMeeseeks and main

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#5300]
I feel like mrmeeseeks isn't doing well with the master->main migration.

Is there anything we can do about this?

**Comment by jni** [comment]
What do you mean by "isn't doing well"? We should create an issue at https://github.com/MeeseeksBox/MeeseeksDev/issues, but it should have more details than this. :joy:

**Comment by hmaarrfk** [comment]
xref:
- https://github.com/scikit-image/scikit-image/pull/5283#issuecomment-809343983
- https://github.com/scikit-image/scikit-image/pull/5243#issuecomment-809031809

**Comment by jni** [comment]
Ok I made an issue: https://github.com/MeeseeksBox/MeeseeksDev/issues/47

**Comment by Carreau** [comment]
That should be fixed, "master" was hardcoded, and I now look at the default_branch and clone it instead of trying to clone master.  It does work on the test repo with a master renamed to "trunk", so my guess is "main" should be ok.

**Comment by jni** [comment]
Thanks @Carreau! 🎉
