### ISSUE TITLE
find the angles of the objects in the binary image ? 

### ISSUE THREAD

**Issue by mikelars16** [scikit-image/scikit-image#5312]
Respected All,
I have a binary image in which there are 12 white objects. I want to find the angle of each object using scikit-image library. I was researching and found the scikit-image library. I am very excited to work with this library. Based on this, I tried to find the angles but I am getting the wrong angles.
I would like to know how to work with a scikit-image to get such a kind of angle.
Any leads will be appreciated.
Thanks in advance
[binary img](https://drive.google.com/file/d/13A-P069YXOGw6AUz6MwjgHhjU81EnkTm/view?usp=sharing)

**Comment by sciunto** [comment]
Dear @mikelars16 

Thank you for your interest.

This issues page is dedicated to bug reports. You will have a better chance to get help by posting the question to the community, either through this [forum](https://forum.image.sc/tags/scikit-image) or [stackoverflow](https://stackoverflow.com/questions/tagged/scikit-image).

I close this post. Feel free to reopen if you identified a bug, with a minimal code to reproduce.
