### ISSUE TITLE
Allow imsave to save to a file handle, rather than just a file name

### ISSUE THREAD

**Issue by jsundram** [scikit-image/scikit-image#533]
I'd like to use `sklearn.io.imsave` in conjunction with `StringIO` as mentioned in [this StackOverflow post](http://stackoverflow.com/questions/16164283/scikit-image-save-image-to-a-bytestring/16165168#16165168). Apparently, the only way to do this right now is by using `matplotlib.pyplot.imsave`, which seems a bit odd. 

@stefanv suggested that I create an issue here, so here it is.

**Comment by GitHunter0** [comment]
I had to use `plugin='pil'` instead of `plugin='PIL'` to make it work
