### ISSUE TITLE
prune release 0.18 items from release_dev.rst

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#5341]
## Description

It seems that items from release 0.18 are still in `release_dev.rst`. This came up in https://github.com/scikit-image/scikit-image/pull/4946#issuecomment-823988824 where the documentation section was pruned. We should check over the remainder of the file to avoid having duplicate entries from the prior release.

**Comment by hmaarrfk** [comment]
We should really move to towncrier. It has been a dream of mine to suggest the infrastructure changes but I never had time to complete it. It really makes release notes painless.

**Comment by grlee77** [comment]
Yes, towncrier is one of the items we discussed recently for CI work funded under the CZI grant. I think @leej3 and @viniciusdc will be taking a look at this in the relatively near future.

**Comment by leej3** [comment]
Yes. If all goes well I would say in 2-4weeks. My confidence interval shall shrink rapidly at the end of the week.
