### ISSUE TITLE
API consistency: seed vs random_seed vs sample_seed

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#5359]
## Description

See [this comment](https://github.com/scikit-image/scikit-image/pull/5357#issuecomment-827075682) from @grlee77:

> it seems we were not very consistent in naming the argument seed vs. random_seed across the library (I think I also saw sample_seed in one place). Making this more consistent is something to consider separately for the 1.0 API.

For 1.0, we should make sure we pick one specific name. My vote is for `random_seed=`.

**Comment by tupui** [comment]
There are lot of `random_state` as well.

**Comment by jni** [comment]
Of course there are. 😂

**Comment by jni** [comment]
BUT. Maybe it should be `random_state` which allows passing in both integer seeds and an rng instance? That makes it more versatile. What do you think @tupui?

**Comment by tupui** [comment]
IMO in all case you should allow to pass `None, int, np.random.Generator`. It is what I proposed in the aforementioned PR. As for how it should be named, I don't know what people are using the most currently. I guess you know which functions are used the most and then which is the most common practice on these. It could help to make a choice.

**Comment by rfezzani** [comment]
Grep gives:
- `random_seed` in
  - `segmentation.quickshift`,
  - `draw.random_shape`,
- `random_state` in
  - `feature.draw_haar_like_feature`,
  - `measure.ransac`,
  - `future.graph.cut_normalized`,
- `sample_seed` in:
  -  `feature.BREAF`
-  `seed` in:
   - `transform.probabilistic_hough_line`,
   -  `restoration.unwrap_phase`,
   -  `data.binary_blobs`,
   -  `util.random_noise`.

**Comment by alexdesiqueira** [comment]
@scikit-image/core I think it's time for us to vote this one :slightly_smiling_face: 
[TL;DR] I'm in favor of `seed=`.
I really like verbose arguments, but I'd go for `seed=` here for consistency. It's what a lot of other computational packages, scientific languages and stuff use — [NumPy](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html?highlight=seed#numpy.random.seed) included.

It seems that [SciPy](https://scipy.github.io/devdocs/reference/generated/scipy.sparse.random.html?highlight=random#scipy.sparse.random) uses `random_state` at `scipy.sparse.random`, though:
> `random_state{None, int, numpy.random.Generator, numpy.random.RandomState}, optional`
> If `seed` is `None` (or `np.random`), the `numpy.random.RandomState` singleton is used. If seed is an int, a new `RandomState` instance is used, seeded with seed. If `seed` is already a `Generator` or `RandomState` instance then that instance is used. This random state will be used for sampling the sparsity structure, but not necessarily for sampling the values of the structurally nonzero entries of the matrix.

Didn't look into that too much, though.

**Comment by tupui** [comment]
For new code: If `seed` is none or int, it should return a `Generator`. `RandomState` should only be returned when provided. And the global `no.random.seed` should not be supported. This is what we did in `scipy.stats.qmc` after lot of discussions on the topic. https://github.com/scipy/scipy/blob/main/scipy/stats/_qmc.py

**Comment by JDWarner** [comment]
I'm happy to defer to the upstream and agree with @alexdesiqueira that it seems like `seed=` is the most common approach in NumPy/SciPy.  I also like the conciseness.

**Comment by rfezzani** [comment]
I also vote for `seed` as it is already majority in our API (please see my last https://github.com/scikit-image/scikit-image/issues/5359#issuecomment-827509867).

**Comment by grlee77** [comment]
I agree that `seed` seems best given the self-consistency and NumPy consistency.

**Comment by mkcor** [comment]
I'll add my voice to `seed=`.
