### ISSUE TITLE
RAG does not correctly merge weights

### ISSUE THREAD

**Issue by sjtugzx** [scikit-image/scikit-image#5360]
## Description

Hi there,
I have a question about the example of merging RAG 1. I just wondering how does the parameters are passed to the identified function max_edge. For example, I wanna merge the node of 1 and 3, as far as I concerned the ‘src’ and ‘dst’ are supposed to be 1 and 3, however, the result is 1 and 5. Moreover, after merging these 2 nodes, if we choose the max weights, the result should be 40 and 20 but we just got 40 and 10. Obviously there is some problems about this part. Here is the link of the [example code](https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_rag.html#sphx-glr-auto-examples-segmentation-plot-rag-py) and the link from the [foum](https://forum.image.sc/t/question-about-the-example-of-merging-rag-from-the-tutorial/51946).

**Comment by jni** [comment]
Thanks for raising @sjtugzx! Clearly there is a bug here in how the weights are handled.

Re the ID of the new node, (src, dst) indeed becomes dst if in_place=True, but otherwise, a new node is created, which requires a new node ID. So that bit is behaving as expected.

**Comment by lagru** [comment]
I think I found the bug. See #6692 for the fix.
