### ISSUE TITLE
Convex Hull - dependent features can trip up regionprops calculation

### ISSUE THREAD

**Issue by VolkerH** [scikit-image/scikit-image#5363]
## Description

For some degenerate objects (e.g. intrinisically one less dimension, too few voxels), convex hull calculation throws exceptions.
This has been reported by Yi (@sunyi000 on Github) here 
 https://forum.image.sc/t/scikit-image-regionprops-and-regionprops-table-questions/52021/2
for intrinsically 1d objects. In this scase scipy throws the following exception. @jni has also been part of that image.sc thread.

```
scipy.spatial.qhull.QhullError: QH6013 qhull input error: input is less than 3-dimensional since all points have the same x coordinate    0
```
Other objects that can cause such exceptions are those with too few points, see for example:
https://github.com/scikit-image/scikit-image/issues/4865#issuecomment-711069382

## Way to reproduce
Still working on a minimal reproducible example

## Suggested way to fix

IMO,
rather than having `measure.regionprops` fail for such object, `QHullErrors` should be caught and the affected label should have a `NaN` in the relevant features. A warning should also be issued if this occurs.

**Comment by jni** [comment]
>  rather than having measure.regionprops fail for such object, QHullErrors should be caught and the affected label should have a NaN in the relevant features. A warning should also be issued if this occurs.

In general, this is a good idea. However in some cases (e.g. three colinear points), the convex hull image should simply be the same as the input image... What do you think @VolkerH ?

**Comment by VolkerH** [comment]
I think so. IMO that is really a bug in `qhull`, but on the other hand I am not firm enough on the mathematical definitions to say  with confidence what the correct output is for these degenerate cased.  In any case, that is something that would have to be fixed upstream, but this isn't even in scipy but some external library.

So for the time being I would suggest adding a try/except around
https://github.com/scikit-image/scikit-image/blob/178e05f17855859d6661ebb6e04d8ddcb50c1cc5/skimage/measure/_regionprops.py#L315
and catch `scipy.spatial.qhull.QhullError`
Just not sure whether the convex image in that case should be an image of `NaN`s and how that would propagate through the other features dependent on the convex image.

**Comment by VolkerH** [comment]
Or do that in 
`morphology.convex_hull.convex_hull_image`
