### ISSUE TITLE
metric.structural_similarity throws the wrong error for small sizes

### ISSUE THREAD

**Issue by Pomax** [scikit-image/scikit-image#5366]
## Description

when using `structural_similarity` when the images are small (<7 in any dimension) a `ValueError` gets thrown, but with the wrong text:

```
ValueError: win_size exceeds image extent.  If the input is a multichannel (color) image, set multichannel=True.
```

Instead of misleading the user into thinking there's something wrong with the way they read in, or converted, their image data, this error should read:

```
ValueError: image data too small to perform SSIM analysis on, please ensure that your images are at least 7x7.
```

## Way to reproduce
```python
import cv2
from skimage.metrics import structural_similarity

def gray(img):
	return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

image = cv2.imread('test.jpg', cv2.IMREAD_COLOR)

# a 7x7 crop will work just fine
crop1 = image[0:7, 0:7]
crop2 = image[8:15, 8:15]
structural_similarity(gray(crop1), gray(crop2))

# a 6x6 crop will cause a ValueError, with the wrong message
crop1 = image[0:6, 0:6]
crop2 = image[8:14, 8:4]
structural_similarity(gray(crop1), gray(crop2))
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Windows-10-10.0.19041-SP0
scikit-image version: 0.18.1
numpy version: 1.20.2
```

**Comment by Pomax** [comment]
Additionally it might be worth updating the documentation for the structural_similarity function to explicitly mention this, as well as explain which function(s) people should be using instead if they need to compare (parts of an) image data that is very thin or very shallow.

**Comment by grlee77** [comment]
Thanks for reporting this @Pomax. Indeed this error message should be updated to be more useful in this case.

`normalized_root_mse` and `peak_signal_noise_ratio` may be better for very small images

**Comment by lilisako** [comment]
Can I take this issue?

**Comment by grlee77** [comment]
> Can I take this issue?

Sure! Let us know if you need any help/guidance

**Comment by Pomax** [comment]
@grlee77 @lilisako Small note, but the PR as merge is using the wrong syntax for the string argument to ValueError. So that's something you probably want to patch.

**Comment by mkcor** [comment]
> The test does not confirm that the message in the ValueError is actually the expected error, which is probably why this wasn't caught before merging.

@Pomax right, we didn't go [this route](https://github.com/scikit-image/scikit-image/pull/5395#discussion_r632939114) in the end.
