### ISSUE TITLE
Double requirements clash with development environment setup in installation guide 

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#5377]
## Description

The [pip installation of the development environment](https://github.com/scikit-image/scikit-image/blob/main/INSTALL.rst#build-environment-setup) doesn't work because pip finds conflicting/double requirements:
```bash
# Create a virtualenv named ``skimage-dev``
python -m venv skimage-dev
# Activate it. On Linux and MacOS:
source skimage-dev/bin/activate
# Install all development and runtime dependencies of scikit-image
pip install -r <(cat requirements/*.txt)
```
will return
```
ERROR: Double requirement given: numpy>=1.17.0 (from -r /dev/fd/63 (line 7)) (already in numpy!=1.18.0,>=1.17.0 (from -r /dev/fd/63 (line 5)), name='numpy')
```
Looking into the files:
```bash
$ grep numpy requirements/*.txt
requirements/build.txt:numpy>=1.17.0,!=1.18.0
requirements/default.txt:numpy>=1.17.0
```
This applies to matplotlib, tifffile, ... as well. I'm unsure how to proceed (therefore the issue rather than a PR). I think updating the installation guide rather than bumping the default requirements is the way to go? For now a workaround is to simply use each of the requirement files in a separate call to pip:
```bash
find requirements/ -iname "*.txt" -exec pip install -r "{}" \;
```
But that is a Linux only solution? So no good? 

Happy to do a PR once I know how to address this. :blush: 

## Version information
```
3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0]
Linux-5.11.16-arch1-1-x86_64-with-glibc2.10
scikit-image version: 0.19.0.dev0
numpy version: 1.20.2
```

**Comment by lagru** [comment]
False alarm. :sweat_smile:  `pip install -r <(cat requirements/*.txt)` works fine with pip 21.1.1. The error mentioned above is thrown for pip 20.2.3.

**Comment by grlee77** [comment]
I think the instructions probably require pip>=20.3 (when the [new dependency resolver became the default](https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html)). 

Perhaps we need to update the instructions with something like the following
`pip install –upgrade pip`
or
`pip install "pip>=20.3"`

**Comment by grlee77** [comment]
I see that you have already made a PR for that in #5378, thanks!
