### ISSUE TITLE
clarify the meaning of the weights term for TV denoising functions

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#5379]
## Description
In the Zulip chat, there was [a question regarding the "weight" term](https://skimage.zulipchat.com/#narrow/stream/175598-general/topic/total.20variation.20documentation) in `denoise_tv_bregman`.

In that implementation, smaller weights lead to more smoothing whereas the opposite is true for `denoise_tv_chambolle`.

The underlying cause seems just to be which term in the cost function the weight applies to (i.e. either the data-consistency or the TV regularization term). We should update the docstrings to clarify where the weight is being applied to make its function less opaque.

**Comment by gmelon** [comment]
Is this issue still valid? If so, I would like to revise it.

**Comment by rfezzani** [comment]
Any PR is welcome :wink:. Thank you @gmelon!
