### ISSUE TITLE
The RANSAC example uses the ransac function in an inappropriate way

### ISSUE THREAD

**Issue by KojiOchiai** [scikit-image/scikit-image#5396]
# Description
In the [example of the RANSAC function](https://scikit-image.org/docs/dev/auto_examples/transform/plot_matching.html), there is a part where the coordinates calculated by `corner_peaks` and `corner_subpix` are used as arguments of `AffineTransform.estimate` and `ransac`.
```python
# estimate affine transform model using all coordinates
model = AffineTransform()
model.estimate(src, dst)

# robustly estimate affine transform model with RANSAC
model_robust, inliers = ransac((src, dst), AffineTransform, min_samples=3,
                               residual_threshold=2, max_trials=100)
outliers = inliers == False
```

The output of `corner_peaks` is in the form (row, col), but the arguments of `estimate` and `ransac` are in the form (col, row).

Since the necessary coordinate conversion has not been done, the coordinates are exchanged and minus is added to the rotation direction in the print section.

```python
# compare "true" and estimated transform parameters
print("Ground truth:")
print(f"Scale: ({tform.scale[1]:.4f}, {tform.scale[0]:.4f}), "
      f"Translation: ({tform.translation[1]:.4f}, "
      f"{tform.translation[0]:.4f}), "
      f"Rotation: {-tform.rotation:.4f}")
print("Affine transform:")
print(f"Scale: ({model.scale[0]:.4f}, {model.scale[1]:.4f}), "
      f"Translation: ({model.translation[0]:.4f}, "
      f"{model.translation[1]:.4f}), "
      f"Rotation: {model.rotation:.4f}")
print("RANSAC:")
print(f"Scale: ({model_robust.scale[0]:.4f}, {model_robust.scale[1]:.4f}), "
      f"Translation: ({model_robust.translation[0]:.4f}, "
      f"{model_robust.translation[1]:.4f}), "
      f"Rotation: {model_robust.rotation:.4f}")
```

I think it would be less confusing for the reader if we exchange row and col just before passing to `estimate` and `ransac`, and just print the parameters directly.
Like this.
```python
# exchange coordinates
def flipxy(points):
    return np.stack([points[:, 1], points[:, 0]]).T

# estimate affine transform model using all coordinates
model = AffineTransform()
model.estimate(flipxy(src), flipxy(dst))

# robustly estimate affine transform model with RANSAC
model_robust, inliers = ransac((flipxy(src), flipxy(dst)),
                               AffineTransform, min_samples=3,
                               residual_threshold=2, max_trials=100)
```

```python
def print_tform(tform):
    print(f"Scale: ({tform.scale[0]:.4f}, {tform.scale[1]:.4f}), "
          f"Translation: ({tform.translation[0]:.4f}, "
          f"{model.translation[1]:.4f}), "
          f"Rotation: {tform.rotation:.4f}")

# compare "true" and estimated transform parameters
print("Ground truth:")
print_tform(tform)
print("Affine transform:")
print_tform(model)
print("RANSAC:")
print_tform(model_robust)
```
By the way, the `plot_matches` used at the end of the example assumes the format (row, col), so I think it is better to leave the src and dst in the global space in the current format (row, col).

**Comment by KojiOchiai** [comment]
As I checked, funcions in `skimage.transform` assume (col, row), and `skimage.feature` assumes (row, col) in IO.

**Comment by KojiOchiai** [comment]
This was an issue that was already mentioned in the following issues, so I will close.
#1749,  #1752, #1789

**Comment by jni** [comment]
Thank you @KojiOchiai for investigating and apologies that we haven't tackled that inconsistency yet. Hopefully we can do so soon!

**Comment by KojiOchiai** [comment]
@jni  Thank you for your kind attention and daily maintenance, and I wish scikit-image all the best in the future.
