### ISSUE TITLE
imshow does not work on binary images

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#5398]
Because of a change in how NumPy handles bools.

dtype can be detected so image can be converted appropriately before display.

See https://forum.image.sc/t/skimage-io-imshow-crashes-when-showing-binary-images/52796/4 for original report.

**Comment by haesleinhuepf** [comment]
It appears a fix is already in the making 🙂 
https://github.com/scikit-image/scikit-image/pull/5247

**Comment by mkcor** [comment]
Fixed by #5467
