### ISSUE TITLE
Error randomly appearing line 188 in "assemble_contours" while using find_contours

### ISSUE THREAD

**Issue by aberut** [scikit-image/scikit-image#5401]
Hi,

I'm using skimage.measure.find_contours in a script where I loop over thousands of images, and I sometimes encounter the following error:
```
line 188, in _assemble_contours
    ends.pop(tail[-1])

KeyError: (0.0, 963)
```
The key is not always the same, but the error appears randomly for about one in ~100 images (it's not always on the same image, it depends on how I crop my images before running the loop).

I never had this error before updating skimage, and I noticed that in older versions, there was a `try` that forbid the error to occur. See for example lines 189 to 192 in v.0.16:
https://github.com/scikit-image/scikit-image/blob/99c4902e26c9ec586b51120efcae26ffbae9eb0f/skimage/measure/_find_contours.py#L189-L192

In case this might help, I was told on twitter by @Glyg7 to replace:
`ends.pop(tail[-1])`
by:
`ends.pop(tails[-1], (None, None))`
in line 188 of the current version:
https://github.com/scikit-image/scikit-image/blob/28e53a24b460883758bb71dddf71900d4c723635/skimage/measure/_find_contours.py#L188
and it seems to work fine for me now.

Best regards,
Antoine.

**Comment by sciunto** [comment]
Would it be possible for you to share one of these failing images?

**Comment by aberut** [comment]
Sure.
For example if I use this image (I zipped the file because github does not accept .tiff files)
[test.zip](https://github.com/scikit-image/scikit-image/files/6517775/test.zip)
, and try to do:
```
import skimage as sk
img = sk.io.imread('test.tiff')
ListeContours = sk.measure.find_contours(img,130)
```
Then I get the following error:

```
Traceback (most recent call last):

  File "<ipython-input-5-a51b93c65676>", line 1, in <module>
    ListeContours = sk.measure.find_contours(img,130)

  File "C:\Users\Antoine\anaconda3\lib\site-packages\skimage\_shared\utils.py", line 156, in fixed_func
    return func(*args, **kwargs)

  File "C:\Users\Antoine\anaconda3\lib\site-packages\skimage\measure\_find_contours.py", line 151, in find_contours
    contours = _assemble_contours(segments)

  File "C:\Users\An
[test.zip](https://github.com/scikit-image/scikit-image/files/6517771/test.zip)

toine\anaconda3\lib\site-packages\skimage\measure\_find_contours.py", line 188, in _assemble_contours
    ends.pop(tail[-1])

KeyError: (0.0, 943)
```

**Comment by sciunto** [comment]
It appears that it comes out in a particular combination during the reconstruction of the contour, this is the reason for the rareness. jpeg has a destructive compression, the resulting image is not identical, that's why you do not have necessarily the same behavior.

@grlee77 I understand why you suggested this workaround, but do you have a deep understanding of the algorithm? I'm facing difficulties to propose a simple testcase for this.

**Comment by alex-jw-brooks** [comment]
Hi, is anyone actively looking at this?

I'm not particularly familiar with this algorithm, but have worked with contour finding algorithms in the past. I did reproduce the error with the given image and would love to read up on the algorithm to help figure out what's going on here & think of a potential test case to verify the fix assuming nobody is currently working on it.

**Comment by grlee77** [comment]
> Hi, is anyone actively looking at this?

I don't think so. If you want to try sorting this out that would be very welcome!

> @grlee77 I understand why you suggested this workaround, but do you have a deep understanding of the algorithm? I'm facing difficulties to propose a simple testcase for this.

I was not the person who suggested the workaround (it was a different twitter user mentioned up top) and have not looked into this issue

**Comment by alex-jw-brooks** [comment]
Great, thanks for the quick response @grlee77. I'll look into it this week 😄
