### ISSUE TITLE
Image conversion routines should allow users to suppress warnings

### ISSUE THREAD

**Issue by tonysyu** [scikit-image/scikit-image#543]
The image conversion routines (i.e. `img_as_*`) should allow users to suppress warnings due to loss-of-precision/-sign. These warnings are particularly annoying when a program prints other info to stdout.

**Comment by goretkin** [comment]
I skimmed this thread a few times looking for the solution, but missed it even though it was alluded to a few times. For someone else's sake, concretely, if you don't want a call to emit any warnings, you can do:

```python
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    skimage.io.imsave("test.png", all_white_image
```

**Comment by mpt5** [comment]
thanks @goretkin this works nicely -- do you know if this has any major impact on performance? I will be looping across thousands of images and this will be inside the loop so I can catch other warnings. I guess best would be to have it outside, but then it would suppress other warnings.

**Comment by goretkin** [comment]
@mpt5 I'm glad it helped. I don't know about the performance of suppressing and unsuppressing warnings, but that is probably something that isn't specific to this project.

**Comment by kootenpv** [comment]
It's absurd to expect such a code for end users, I'd almost say it is unacceptable. Even if I want to explicitly cast, I don't see any way to avoid these messages (other than using a context manager which is super ugly in this case). Very frustrating.

**Comment by soupault** [comment]
Hello @kootenpv ! Thanks for the negative feedback, but we'd strongly encourage you to approach this issue in a constructive way as well. Remind yourself, that `skimage` is an open-source library (means that we are open for the proposals), and it serves many purposes (each with different level of required control on image processing process). It might perform not as expected in your particular case, but is optimal in general.

Context manager seems like a natural method of wrapping things in Python, and I personally do not see any issues with that. We have some plans to refactor that piece of code, but, in any case, it will stay the main pain point: a bridge between a static and a dynamic typing.

**Comment by jni** [comment]
@soupault "is optimal in general" seems like a very strong statement. =)

@kootenpv I think you're right regarding warnings on conversions. As @soupault hinted, we are welcome to suggestions. Here are two options off the top of my head:

- we have our own context manager that is perhaps nicer to use. We could move it to a more public space:

```python
In [4]: from skimage._shared._warnings import expected_warnings

In [5]: image = np.ones((5, 5))

In [6]: with expected_warnings(['precision']):
   ...:     image_uint8 = img_as_ubyte(image)
   ...:

In [7]:
```

- For some functions, we could add a `warn=True` keyword argument that users could then turn off as needed.

- For some functions, we might consider turning warnings off by default, but I suspect this would require some strong lobbying. =)

Any thoughts?

**Comment by kootenpv** [comment]
@soupault My apologies for the strong tone. That was frustration speaking, quite unprofessionally.

@jni I would say that a warn keyword would be a great solution. I don't mind it being turned on by default, as long as it is easy to switch it off. Adding an import and indentation for the same effect seems wrong to me. So `+1` to the warn keyword from me :)

**Comment by jni** [comment]
@kootenpv I've opened #2602 for continued discussion. Hopefully we can find a good solution for everyone! =)
