### ISSUE TITLE
scikit-image installation fails with : #warning "Using deprecated NumPy API, disable it with....."

### ISSUE THREAD

**Issue by IAM-P-LP** [scikit-image/scikit-image#5430]
I was trying to install scikit-image in a virtual environment using pip install scikit-image.It fails with the following error.

/face-alignment/face-alignment-virtual/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \

## Way to reproduce
pip install scikit-image -vv

## Version information
Python 3.6.9
pip 21.1.2

The packages installed already are as follows.
Package         Version
--------------- -------
cycler          0.10.0
imutils         0.5.4
kiwisolver      1.3.1
matplotlib      3.3.4
numpy           1.18.5
Pillow          8.2.0
pip             21.1.2
pyparsing       2.4.7
python-dateutil 2.8.1
setuptools      57.0.0
six             1.16.0
wheel           0.36.2

NB :pip is already the latest version.

**Comment by hmaarrfk** [comment]
hello. thank you for reaching out. 

unfortunately, the error above isn't the underlying issue. it is simply a warning.

are you able to share the full output of the build?

what operating system are you using? what hardware are you using?

**Comment by grlee77** [comment]
deleted the discussion, but not reopening the issue due to lack of feedback
