### ISSUE TITLE
'subpixel' boundaries at the edges of an image

### ISSUE THREAD

**Issue by firerain42** [scikit-image/scikit-image#5432]
## Description

When using the function `find_boundaries` with `mode='subpixel'` the behavior at the edges of the image seems strange to me.

From the documentation it is not clear to me what the intended behavior should be. Without an option to explicitly specify the behavior at the edges of the image, I would expect a constant input image to have no boundary at all or maybe straight lines at the edges of the image. However, for constant images with a non-zero value the actual image alternates between `True` and `False`. If the image is completely zero, there is no such effect.

## Way to reproduce
```python
import skimage.segmentation
import numpy as np
skimage.segmentation.find_boundaries(np.ones((3,3), dtype=int), mode='subpixel')
```
returns
```python
array([[False,  True, False,  True, False],
       [ True, False, False, False,  True],
       [False, False, False, False, False],
       [ True, False, False, False,  True],
       [False,  True, False,  True, False]])

```

I would expect the same output as `np.zeros((5,5), dtype=bool)`.

## Version information
```python
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37)
[GCC 9.3.0]
Linux-5.4.0-74-generic-x86_64-with-debian-bullseye-sid
scikit-image version: 0.18.1
numpy version: 1.20.3
```

**Comment by mkcor** [comment]
Hello @firerain42,

Thanks for reporting! I agree with you, the current behaviour is not consistent.

Would you like to try and investigate by yourself? https://github.com/scikit-image/scikit-image/blob/a1c58462b7fe752a9d05d99c997d2d4825bc3644/skimage/segmentation/boundaries.py#L11

You could run this function line by line, starting with `label_img = np.ones((3, 3), dtype=int)` and comparing with `label_img = np.zeros((3, 3), dtype=int)` to see what happens. Let me know, thanks!

**Comment by firerain42** [comment]
Hello @mkcor,

I think the problem is the padding in
https://github.com/scikit-image/scikit-image/blob/23fd40b20a7f6dbd2c78ca85103d42c1c97ae17d/skimage/segmentation/boundaries.py#L37-L39
which introduces 0 as an image value. Replacing it with `np.pad(label_img_expanded, 1, mode='edge')` should do the trick. I would have sent a pull request, but I couldn't get the tests running on my PC (and don't have the time to find the cause).
