### ISSUE TITLE
measure.find_contours() draws contours at the boundary too unlike gdal_contour 

### ISSUE THREAD

**Issue by shubham9436** [scikit-image/scikit-image#5440]
I have a raster file for which I need to find the contours at certain elevation. There is difference in contours drawn by measure.find_contours() function and gdal_contour. There is an extra boundary line appearing which needs to be filtered out.

Contours generated by measure.find_contours() function:
![find_contours](https://user-images.githubusercontent.com/19433739/123080346-74574480-d43a-11eb-93a8-564fa567be31.PNG)

Contours generated by gdal:
![gdal](https://user-images.githubusercontent.com/19433739/123086037-9358d500-d440-11eb-8677-2197ba29b602.PNG)

DTM file:
[dtm.zip](https://github.com/scikit-image/scikit-image/files/6701271/dtm.zip)

I am trying to find the elevation at 497.5 meters.

Please help to solve the issue.

**Comment by grlee77** [comment]
If I load these images, the non-negative pixels all fall in the range [495.9575, 502.32675] with some regions near the edges set to a negative value -32767.

I am not familiar with GDAL conventions, but it seems like perhaps it masks out these "negative" regions by default?

I think you can get the same behavior here by explicit setting the mask argument so that only non-negative regions are considered

```Python
contours = measure.find_contours(img, level=497.5, mask=img > 0)
```

**Comment by shubham9436** [comment]
> If I load this image, the non-negative pixels all fall in the range [495.9575, 502.32675] with some regions near the edges set to a negative value -32767.
> 
> I am not familiar with GDAL conventions, but it seems like perhaps it masks out these "negative" regions by default?
> 
> I think you can get the same behavior here by explicit setting the mask argument so that only non-negative regions are considered
> 
> ```python
> contours = measure.find_contours(img, level=497.5, mask=img > 0)
> ```

I am getting this error:
```
TypeError: find_contours() got an unexpected keyword argument 'mask'
```
Is this a version issue?

My current version is 0.15.0.

**Comment by grlee77** [comment]
> Is this a version issue?

Yes, it looks like the `mask` keyword argument was added in 0.16. If possible, I would recommend updating to the latest release (0.18.1)

**Comment by shubham9436** [comment]
> If I load this image, the non-negative pixels all fall in the range [495.9575, 502.32675] with some regions near the edges set to a negative value -32767.
> 
> I am not familiar with GDAL conventions, but it seems like perhaps it masks out these "negative" regions by default?
> 
> I think you can get the same behavior here by explicit setting the mask argument so that only non-negative regions are considered
> 
> ```python
> contours = measure.find_contours(img, level=497.5, mask=img > 0)
> ```

I masked the data using:
```
srcData = np.ma.masked_array(srcData, mask=(srcData < -1000))
```
Still I am getting the contours at the boundary.
