### ISSUE TITLE
skeletonize_3d does not seem to do anything on my 3d input array

### ISSUE THREAD

**Issue by joooohnny** [scikit-image/scikit-image#5464]
## Description
Hi guys, I'm currently trying to generate the skeleton of a 3d object (stl file). I voxelized it into a 3d array and then used the skeletonize function. But skeletonize function does not seem to do anything on my array (compare skeleton and array in the code). And when I plot my skeleton, I have the same shape (a torus) as I had in input.
You can download the stl file needed to run the code here: http://www.filedropper.com/tore.

## Way to reproduce
```python
import numpy as np
import matplotlib.pyplot as plt
from skimage.morphology import skeletonize
import trimesh
from trimesh.voxel import creation
from mpl_toolkits.mplot3d import Axes3D #don't delete this line

mesh = trimesh.load_mesh('../objet 3d/tore.stl')
volume = trimesh.voxel.creation.voxelize(mesh=mesh, pitch=mesh.extents.max() / 128)
array = volume.matrix

copy_array = np.zeros(array.shape)
for i in range(len(array)): #changing True value by 1 and False by 0 in the array
    for j in range(len(array[i])):
        for k in range(len(array[i, j])):
            if array[i, j, k] == True:
                copy_array[i, j, k] = 1

array = copy_array

skeleton = skeletonize(array) #if you compare skeleton and array, they are not much different, even tough they should, I don't understand why

skeleton_list = skeleton.tolist()

#plotting skeleton

X = []
Y = []
Z = []

for i in range(len(skeleton_list)):
    for j in range(len(skeleton_list[i])):
        for k in range(len(skeleton_list[i][j])):
            if skeleton_list[i][j][k] == 255:
                X.append(i)
                Y.append(j)
                Z.append(k)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(X, Y, Z, zdir='z', s=20, c=None, depthshade=True)
plt.show()

```

In output, I have a torus (this is exactly what I had in input), but I would expect to have a circle.

![image](https://user-images.githubusercontent.com/86359014/124892893-8d372c80-dfda-11eb-833e-f61c50e3c836.png)

Anyone knows what's happening there ?

Thank you in advance.

**Comment by jni** [comment]
The issue is that the output of `trimesh` is a *hollow* torus. Here is a screenshot of a cross-section of `array`:

![napari-torus](https://user-images.githubusercontent.com/492549/124926368-10e51f00-dfc3-11eb-9233-709ba2aaf968.png)

The following code gets you what you want:

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi
from skimage.morphology import skeletonize
import trimesh
from trimesh.voxel import creation
from mpl_toolkits.mplot3d import Axes3D #don't delete this line

mesh = trimesh.load_mesh('../objet 3d/tore.stl')
volume = trimesh.voxel.creation.voxelize(mesh=mesh, pitch=mesh.extents.max() / 128)
array = volume.matrix

# note: all the copying code was totally unnecessary...

filled = ndi.binary_fill_holes(array)
skeleton = skeletonize(filled)
```

Note also, for viewing 3D data, I recommend [napari](https://napari.org). Being able to quickly slice through the array is what made me realise the problem.

**Comment by joooohnny** [comment]
Thanks a lot. It works for me.
