### ISSUE TITLE
`.format()` in (legacy) code could be converted to f-strings.

### ISSUE THREAD

**Issue by mkcor** [scikit-image/scikit-image#5474]
## Description

To address this issue, a new contributor could start with a recursive grep for `\.format\(` on a subpackage of interest to them (or on the entire package). Replacing instances of `.format()` with f-strings can be a good pretext to explore the codebase.

Reference: https://www.python.org/dev/peps/pep-0498/

**Comment by abrooks9944** [comment]
Hello! May I work on this issue?

**Comment by Xyno18** [comment]
I'd like to work on this

**Comment by mkcor** [comment]
For sure! @alex-jw-brooks could do it for the `filters` subpackage and @Xyno18 for the `segmentation` subpackage: How does that sound?

**Comment by alex-jw-brooks** [comment]
That sounds great, thanks!

**Comment by Xyno18** [comment]
Sounds great. I'm on it

**Comment by Larkinnjm1** [comment]
Hey folks looking to contribute to a first issue on this repo can I look to work on this issue for other sub modules such as `restoration` and `registration?`

**Comment by mkcor** [comment]
Hi @Larkinnjm1,

> can I look to work on this issue for other sub modules such as restoration and registration?

Sure, please go for it!

**Comment by MariosAchilias** [comment]
Hello, i'd also like to contribute, can I work on this for the ``color``, ``exposure``, ``transform`` and ``util`` modules?

**Comment by mkcor** [comment]
Hi @MariosAchilias,

> Hello, i'd also like to contribute, can I work on this for the `color`, `exposure`, `transform` and `util` modules?

Ok!

**Comment by Larkinnjm1** [comment]
> Hi @Larkinnjm1,
> 
> > can I look to work on this issue for other sub modules such as restoration and registration?
> 
> Sure, please go for it!

Cool great on it!

**Comment by jstriebel** [comment]
Just a recommendation: pyupgrade is a tool which can automatically apply new python-features on code, such as converting `"".format()` calls to f-strings:
https://github.com/asottile/pyupgrade#f-strings

It might also do too many other conversions you don't want in the code-base, not sure about that, just a suggestion :-)

**Comment by mkcor** [comment]
Hi @jstriebel,

> It might also do too many other conversions you don't want in the code-base, not sure about that, just a suggestion :-)

Exactly! But, it might be worth considering each pyupgrade item, to decide whether to include it or not. Thanks for the suggestion!

**Comment by mkcor** [comment]
To track this issue more finely and eventually close it, I'm listing all the skimage subpackages below (check the box once the corresponding PR is merged):

- [x] color (#5508)
- [ ] data
- [ ] draw
- [x] exposure (#5508)
- [ ] external
- [ ] feature
- [ ] filters (#5478)
- [ ] future
- [ ] graph
- [ ] io
- [ ] measure
- [ ] metrics
- [ ] morphology
- [ ] registration (#5510)
- [ ] restoration (#5510)
- [ ] scripts
- [x] segmentation (#5479)
- [ ] _share
- [x] transform (#5508)
- [x] util (#5508)
- [ ] viewer

**Comment by ovynnej** [comment]
Hello @mkcor! Should this issue be closed? Running `grep -r ".format(" .` on the package returns only these instances, which are not relevant to the issue:

./_shared/utils.py:                    warnings.warn(self.warning_msg.format(
./_shared/utils.py:                warnings.warn(warning_msg.format(func_name=func.__name__),
./_shared/utils.py:                warnings.warn(self.warning_msg.format(

Thank you!

**Comment by grlee77** [comment]
Thanks for the reminder, @ovynnej. Indeed, we had several contributors in July/August and I think all of these have been addressed.
