### ISSUE TITLE
Is there any reason we don't have a xyz to cieluv transformation in skimage.color?

### ISSUE THREAD

**Issue by jsundram** [scikit-image/scikit-image#548]
I'd like to do some color calculations in a perceptually uniform color space, but XYZ is about as good as it gets in skimage.color, as far as I can tell.

There's [a formula](http://www.easyrgb.com/index.php?X=MATH&H=16#text16) (and [an inversion](http://www.easyrgb.com/index.php?X=MATH&H=17#text17)) on easyrgb.com, but I'm hesitant to add them if there's a good reason they weren't included.

**Comment by jni** [comment]
Closed as CIELUV is now in skimage... And has been for a while!
