### ISSUE TITLE
Allow use of complex numbers with denoise_nl_means

### ISSUE THREAD

**Issue by shirawerman** [scikit-image/scikit-image#5483]
The code of non_local_means.py  converts the dataset to 'float', but I have a dataset with complex numbers. Is there a possibility to support more data types? 

Thanks
```

**Comment by grlee77** [comment]
It would likely require substantial work to refactor the underlying Cython code to support complex types directly, but there are a couple of other options:

1.) Run non-local means independently on the real and imaginary components. 

2.) If the data is 2D it might also be possible to stack the real and imaginary data along a new axis (e.g. np.stack((image.real, image.imag), axis=-1) and call it with `multichannel=True`. This would consider both components together when determining patch similarity. If your data is 3D, we would need to add support for `3D multichannel` for this to work. but I do already have an implementation for that which I never officially submitted for review. Let me know if your data is 3D and I can see about reviving that.

**Comment by shirawerman** [comment]
Thank you for the quick reply!
I am working on 3D data so if you can let me know when that code is ready, that would be great! 
For now I will work with the first solution, although is will generate different weights for the real and imaginary part.

**Comment by grlee77** [comment]
Hi @shirawerman, I opened a PR for 3D+multichannel (and 4D) support in #5488. If you want to compile scikit-image from that branch you can try it out. 

We are hoping to make a 0.19 release soon, but I don't know that the PR will be reviewed in time for that.
