### ISSUE TITLE
AttributeError: module 'skimage' has no attribute 'measure'

### ISSUE THREAD

**Issue by wusaifei** [scikit-image/scikit-image#5484]
According to the official website tutorial, `pip` and `conda` are installed. The installation result is successful, and you can `import skimage`, but `skimage.measure` will report an error. Test the `0.18.1`, `0.17.2` and other versions.

**Comment by wusaifei** [comment]
@sergeyk @rtack @zeroth @adamw523 Looking forward to your reply, thank you very much!

**Comment by jni** [comment]
The submodules are not imported by default. This means you need to either:

```python
import skimage.measure

result = skimage.measure.regionprops(...)  # for example
```

or

```python
from skimage import measure

result = measure.regionprops(...)  # for example
```

After #5101 is merged, `import skimage; skimage.measure.regionprops(...)` will work. But not yet.

**Comment by wusaifei** [comment]
@jni Thank you very much for your reply! This means that in order to improve the loading speed of `skimage`, the default is not to load sub modules such as `measure`.
