### ISSUE TITLE
issue with rgb2hed and hed2rgb

### ISSUE THREAD

**Issue by bm-93** [scikit-image/scikit-image#5494]
The example code snippet does not give the results that were shown in the documentation:
![Screenshot from 2021-07-29 10-28-37](https://user-images.githubusercontent.com/59984233/127538591-dc0da26c-0f50-45be-9198-e9108dd1e1cf.png)

**Comment by grlee77** [comment]
Hi @bm-93,
can you please specify which version of scikit-image you are seeing this with?

**Comment by grlee77** [comment]
There was an issue with this example that was resolved earlier this year (#5164), but the image above does not look the same as the one shown there.

**Comment by bm-93** [comment]
The skimage version is 0.16.2
