### ISSUE TITLE
peak_local_max should raise error when given >2D array

### ISSUE THREAD

**Issue by nguyenlienviet** [scikit-image/scikit-image#5500]
## Description

[peak_local_max](https://github.com/scikit-image/scikit-image/blob/e128e0743bb2cded104654352a13ed5b4e53efb8/skimage/feature/peak.py#L113-L319) returns empty array when `image` argument's dimension is greater than 2 instead of raising an error.

## Way to reproduce
```python
>>> import numpy as np
>>> from skimage.feature import peak_local_max
>>> a = np.random.rand(4, 5)
>>> peak_local_max(a)
array([[1, 1],
       [2, 3]])
>>> peak_local_max(np.reshape(a, [4, 5, 1]))
array([], shape=(0, 3), dtype=int64) 
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]
Linux-5.4.0-80-generic-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.17.2
numpy version: 1.19.5
```

**Comment by jni** [comment]
Ah, this is actually not an error — peak local max works for 3D arrays, and even higher dimensions. The issue you are running into is that `peak_local_max` ignores a border of width=1 by default (see `exclude_border=True` in the [docs](https://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.peak_local_max)). But when your array has thickness of only 1, it's *all* border, so no maxima can be found.

**Comment by nguyenlienviet** [comment]
Oh I see. Thanks for the clarification!
