### ISSUE TITLE
Downsampling an image

### ISSUE THREAD

**Issue by jagruti8** [scikit-image/scikit-image#5520]
Hi, while downsampling an image do we need to do gaussian blurring to prevent aliasing even if we are using linear or cubic interpolation. Since, by interpolating we are already doing some smoothing. I am really confused. It will be great to get some insights on this?

**Comment by grlee77** [comment]
In general, yes you will still need smoothing. In practice, you may or may not be able to tell a visible difference if the downsampling factor is not large and/or the image doesn't have much high frequency content.

Here is an example of a test pattern with high frequency content:
![zone_plate_orig](https://user-images.githubusercontent.com/6528957/130378917-de9a4fa5-b126-41f0-9ee3-ba3683590dd7.png)

If I downsample this by a factor of 5, you can see a large amount of aliasing regardless of interpolation order. Using the default `antialising_sigma` suppresses, but does not entirely remove the aliasing. Increasing the anti-aliasing smoothing factor would further suppress the aliasing at cost of additional resolution loss:

![zone_plate_ds5](https://user-images.githubusercontent.com/6528957/130378925-e080b8b5-0dba-4c8a-b638-1270364fef5f.png)

**Comment by jagruti8** [comment]
Hi, thanks a lot for the reply. But may I know which interpolation would be good for downscaling meaning bilinear or bicubic if I am doing Gaussian smoothing with a proper anti-aliasing smoothing factor?

**Comment by jagruti8** [comment]
> In general, yes you will still need smoothing. In practice, you may or may not be able to tell a visible difference if the downsampling factor is not large and/or the image doesn't have much high frequency content.
> 
> Here is an example of a test pattern with high frequency content:
> ![zone_plate_orig](https://user-images.githubusercontent.com/6528957/130378917-de9a4fa5-b126-41f0-9ee3-ba3683590dd7.png)
> 
> If I downsample this by a factor of 5, you can see a large amount of aliasing regardless of interpolation order. Using the default `antialising_sigma` suppresses, but does not entirely remove the aliasing. Increasing the anti-aliasing smoothing factor would further suppress the aliasing at cost of additional resolution loss:
> 
> ![zone_plate_ds5](https://user-images.githubusercontent.com/6528957/130378925-e080b8b5-0dba-4c8a-b638-1270364fef5f.png)



> In general, yes you will still need smoothing. In practice, you may or may not be able to tell a visible difference if the downsampling factor is not large and/or the image doesn't have much high frequency content.
> 
> Here is an example of a test pattern with high frequency content:
> ![zone_plate_orig](https://user-images.githubusercontent.com/6528957/130378917-de9a4fa5-b126-41f0-9ee3-ba3683590dd7.png)
> 
> If I downsample this by a factor of 5, you can see a large amount of aliasing regardless of interpolation order. Using the default `antialising_sigma` suppresses, but does not entirely remove the aliasing. Increasing the anti-aliasing smoothing factor would further suppress the aliasing at cost of additional resolution loss:
> 
> ![zone_plate_ds5](https://user-images.githubusercontent.com/6528957/130378925-e080b8b5-0dba-4c8a-b638-1270364fef5f.png)

Hi, thanks a lot for the reply. But may I know which interpolation would be good for downscaling meaning bilinear or bicubic if I am doing Gaussian smoothing with a proper anti-aliasing smoothing factor?

**Comment by jagruti8** [comment]
Hi, thanks a lot for the reply. But may I know which interpolation would be good for downscaling meaning bilinear or bicubic if I am doing Gaussian smoothing with a proper anti-aliasing smoothing factor?

**Comment by grlee77** [comment]
I think they may look very similar for downscaling and would probably just go with linear. I don't think there is one good answer that is best for all scenarios. 

If you have not seen it, I would encourage use of https://forum.image.sc/ for these types of questions as there is a broader community there. We mostly use the issue tracker here for bug reports, feature requests, etc.
