### ISSUE TITLE
Request that PR #5249 be included in next 0.18.x patch release

### ISSUE THREAD

**Issue by erykoff** [scikit-image/scikit-image#5562]
## Description

The Rubin Observatory science pipelines is pinned on scikit-image<0.18 because 0.18.x doesn't run when installed on read-only filesystems (as is one of our distribution methods).  This was fixed in #5249 .  I was hoping that this could be backported to 0.18.x for the next minor release.

**Comment by mkcor** [comment]
ping @hmaarrfk

**Comment by hmaarrfk** [comment]
I think that https://github.com/scikit-image/scikit-image/pull/5564 should be ready to go. I think I found the source of the failing tests and am more confident about it.

I'm not super sure I will have time to go through the motions of a release.

But hopefully that should help others release.

**Comment by erykoff** [comment]
Thank you!

**Comment by hmaarrfk** [comment]
do you use conda by any chance? once the PR makes it through, i might be able to release it there on conda-forge faster

**Comment by hmaarrfk** [comment]
othwr solutions might involve settinf an enviornment variable. or uninstalling pooch.

let eme know if those work for you then i can help craft them.

**Comment by erykoff** [comment]
We use conda-forge for distributing our third-party environment, yes.  Getting it there would be ideal.  Thanks!

I believe we tried other workarounds, and #5249 was the most straightforward.

**Comment by hmaarrfk** [comment]
Ok. I'll release a conda-forge patch as soon as the PR makes it through.

**Comment by hmaarrfk** [comment]
Or rather, I"ll make the PR to the conda-forge repo to let others review it and give their input on if we should release a conda-forge fix before a pypi fix.

**Comment by hmaarrfk** [comment]
The PR has been merged.

The release process kinda scares me, so I haven't had a chance to go through it yet.

**Comment by hmaarrfk** [comment]
Since 0.19.0 just got released, I'm going to close this issue. I'm sorry this took so long to get fixed. Hopefully you should be able to use the pypi package or the soon to be released conda  package on conda-forge.
