### ISSUE TITLE
FileExistsError: [Errno 17] File exists in data cache directory when running in multi-threaded environment

### ISSUE THREAD

**Issue by manuel-lang** [scikit-image/scikit-image#5575]
## Description

I am trying to run scikit-image with FastAPI in a multi-threaded environment. The application is built with Docker and run with Google Cloud Run. While for most requests it just works fine, occasionally it leads to an error such as the following.

```shell
FileExistsError: [Errno 17] File exists: '/home/.cache/scikit-image/0.18.3/data/../data/astronaut.png'
at copyfile (/usr/local/lib/python3.8/shutil.py:261)
at copy2 (/usr/local/lib/python3.8/shutil.py:432)
at _fetch (/usr/local/lib/python3.8/site-packages/skimage/data/__init__.py:222)
at _init_pooch (/usr/local/lib/python3.8/site-packages/skimage/data/__init__.py:262)
```

The specific file can vary and for instance also be `'/home/.cache/scikit-image/0.18.3/data/../data/camera.png'`.

## References

This issue seems to be heavily linked to [https://github.com/scikit-image/scikit-image/issues/4660](https://github.com/scikit-image/scikit-image/issues/4660). I tried adding the command `RUN python -c "import skimage"` to the Dockerfile, but this did not solve the problem.

## Way to reproduce

As it only happens occasionally, I could not find a pattern to reproduce the behavior yet.

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
3.8.12 (default, Sep  3 2021, 20:28:07) 
[GCC 10.2.1 20210110]
Linux-5.13.14-200.fc34.x86_64-x86_64-with-glibc2.2.5
scikit-image version: 0.18.3
numpy version: 1.18.5
```

**Comment by manuel-lang** [comment]
Thank you for the explanation, @hmaarrfk .

I have added the following line to my Dockerfile before starting the app. 

```docker
RUN python -c "import skimage; skimage.data.download_all()"
```

I'll update the comment once I have tested it a bit more in-depth.

**Comment by hmaarrfk** [comment]
since you are using docker, it might be better to only download the files you need.

That can be done by accessing the data you need the first time.

```
RUN python -c "from skimage.data import eagle; _ = eagle()"
```
for a specific file.

**Comment by manuel-lang** [comment]
Thank you @hmaarrfk. This makes a lot of sense as download_all() needs quite some time. In my case the required command was 
```
RUN python -c "from skimage.data import data_dir"
```

With the command everything perfectly worked! :tada:
