### ISSUE TITLE
HOG feature is slow

### ISSUE THREAD

**Issue by TimSC** [scikit-image/scikit-image#594]
The hog feature appears to do unnecessary computation and is rather slow. I have a rough cython optimised version available if anyone is interested. 

https://gist.github.com/TimSC/5810681

I thought about doing a pull request but I have build problems and I don't know if it is wanted.

Tim

**Comment by ivoflipse** [comment]
Is there anything I can do to help to get a more optimised version merged in? 

We have some computations that make repeated calls to the current hog function and its one of the main bottlenecks for speeding it up.

**Comment by ivoflipse** [comment]
This issue can be closed, since the PR for fasthog has been merged in.

**Comment by JDWarner** [comment]
Closed by #595
