### ISSUE TITLE
RANSAC: Check for updates

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#5952]
### Discussed in https://github.com/scikit-image/scikit-image/discussions/5938

<div type='discussions-op-text'>

<sup>Originally posted by **stefanv** July 11, 2017</sup>
RANSAC was implemented in scikit-image & scikit-learn around the same time, by the same @ahojnnes.  In the mean time, some improvements have landed on either side.

We should compare the two implementations, and port fixes to either side as needed.
</div>

**Comment by Gmelon** [comment]
Hello! May I try this issue?
I'll compare it to sklearn and try to modify it.

**Comment by stefanv** [comment]
@gmelon Yes, you are very welcome to work on it.  Thank you :)
