### ISSUE TITLE
EXAMPLES: Change use of `scipy.fftpack` to `scipy.fft`

### ISSUE THREAD

**Issue by srvanrell** [scikit-image/scikit-image#5986]
## Description

Examples like [this band pass](https://scikit-image.org/docs/stable/auto_examples/filters/plot_dog.html) or [this use of windows](https://scikit-image.org/docs/stable/auto_examples/filters/plot_window.html) are using deprecated `scipy.fftpack`. They could use `scipy.fft` module instead. I will kindly make a PR if you consider that is appropiate.

**Comment by srvanrell** [comment]
I submitted a PR on this, just changing examples and setup.py. Would you prefer that I update skimage internal functions too? The detail of files using fftpack is below. Just let me know.

```
./skimage/registration/_masked_phase_cross_correlation.py:194:    # transform axes unchanged which was not possible with scipy.fftpack's
./skimage/registration/_phase_cross_correlation.py:12:    from scipy.fftpack import fftn, ifftn
./skimage/registration/_phase_cross_correlation.py:13:from scipy.fftpack import fftfreq
./skimage/transform/radon_transform.py:13:    # fallback from scipy.fft to scipy.fftpack instead of numpy.fft
./skimage/transform/radon_transform.py:14:    # (fftpack preserves single precision while numpy.fft does not)
./skimage/transform/radon_transform.py:15:    from scipy.fftpack import fft, ifft
./skimage/_shared/fft.py:15:    from scipy.fftpack import next_fast_len
```

**Comment by hmaarrfk** [comment]
Yes that would be good.

I think that there is also a TODO in the file `TODO.txt`

```
Other (2022)
------------
* Remove conditional import of ``scipy.fft`` in ``skimage._shared.fft`` and
  `skimage.registration._phase_cross_correlation.py` once the minimum supported
  version of ``scipy`` reaches 1.4.
```

**Comment by grlee77** [comment]
Thanks @hmaarrfk, I was just about to link those!

@srvanrell, If there is any confusion on those items, let me know and I can help out. I added float32 support to some functions relying on FFTs, but unfortunately numpy.fft only supports double precision, so I still had to use astype. Now that `skimage._shared.fft` can always assume scipy.fft is available, these astype calls won't be necessary since the SciPy FFTs support float32.

**Comment by srvanrell** [comment]
Should I completly remove `skimage._shared.fft`? It seems useless to have that file just to import `next_fast_len` and `scipy.fft`  that could be imported elsewhere

**Comment by hmaarrfk** [comment]
yeah, it would be a nice cleanup. It seems only _masked_phase_cross_correlation.p use next_fast_len
