### ISSUE TITLE
How to pip install to a specific directory

### ISSUE THREAD

**Issue by parulsingh23** [scikit-image/scikit-image#6003]
I am running the installation pip command with the extra ending of '-t' on an amazon linux ec2 instance (so that I am able to pip install to a specific directory on it). The command is: `sudo python -m pip install scikit-image -t /mnt/efs` However, when accessing that directory, when I call the `import skimage`, I get the following error:
```
ImportError: cannot import name 'geometry' from 'skimage._shared' (/mnt/efs/skimage/_shared/__init__.py)
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 
```
I have also tried simply pip installing to a specific directory on my local computer, zipping that folder, and uploading it to the ec2 instance and unzipping it there (but I get the same error). To give a bit of background, I am trying to install the skimage dependency on the `efs` directory in my ec2, because I am accessing it with an AWS Lambda function.

**Comment by hmaarrfk** [comment]
i think the general strategy is to use virtual environments or Conda environments. have you tried those?

**Comment by rfezzani** [comment]
Hello @parulsingh23, and thank you for your interest in `scikit-image`. I will convert your issue to Github discussion. I hope you don't mind :wink:.

**Comment by grlee77** [comment]
### comments moved back from Discussion

> @rfezzani on Nov 4, 2021
Following @hmaarrfk suggestion, did you tried
## Conda
```
conda create --name my_env
conda activate my_env
conda install scikit-image
```
## Virtual env
### Linux / Mac
```
python -m venv my_env
source my_env/bin/activate 
pip install scikit-image
```
### Windows
```
python -m venv my_env
my_env\bin\activate 
pip install scikit-image
```
