### ISSUE TITLE
Segfault in peak_local_max with large numbed of segments

### ISSUE THREAD

**Issue by arogozhnikov** [scikit-image/scikit-image#6010]
## Description

scikit-image dives to (absolutely uncatchable and untrackable) segfault in peak_local_max.

## Way to reproduce
```python
import numpy as np
from scipy.ndimage import distance_transform_edt
from skimage.feature import peak_local_max


def segment(binary_image):
    distance = distance_transform_edt(binary_image)
    peak_local_max(
        distance, min_distance=100, footprint=np.ones((3, 3)), labels=binary_image,
    )

for p in [0.05, 0.95, 0.001, 0.999]:
    print(p)
    segment(np.random.random([2048, 2048]) < p)


```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
Linux-5.10.47-linuxkit-x86_64-with-glibc2.29
scikit-image version: 0.18.3
numpy version: 1.21.4
```

**Comment by arogozhnikov** [comment]
additional comment: looks like 0.17.2 does not have this issue

**Comment by jni** [comment]
>  (which I can't use on mac because wheels are not provided for mac + python 3.8)

Um, they are...?

https://pypi.org/project/scikit-image/0.17.2/#files

Are you on an older macOS perhaps?

At any rate, though, thanks for the bug report, we need to fix it. We (by which I mean @rfezzani 🙏 🙏 🙏 ) fixed a large number of bugs with 0.18, so it'd be great to get you using that version. Currently your reproducer works fine for me on main + macOS, though, so I'm wondering whether you could try to run it on main and see if you still have the issue? I'll also try it on Linux later.

**Comment by arogozhnikov** [comment]
@jni it is reproduced in linux

**Comment by arogozhnikov** [comment]
I think you're right about wheels are available, but for some reasons they are not recognized. 
Mac os is fresh: 11.5.2
```python
~ pip install scikit-image== --only-binary=scikit-image
ERROR: Could not find a version that satisfies the requirement scikit-image== (from versions: 0.18.0rc0, 0.18.0rc1, 0.18.0rc2, 0.18.0, 0.18.1, 0.18.2rc1, 0.18.2rc2, 0.18.2, 0.18.3)
ERROR: No matching distribution found for scikit-image==
```

**Comment by arogozhnikov** [comment]
@jni tested on main branch and it did not fail (on mac). Do you have guesses where is was fixed?

**Comment by jni** [comment]
Hmm, on main on *Linux* I get a "Killed" message. So I guess it *wasn't* fixed and it is platform specific? Which is, well, the worst. 😂 Can you check main on your Linux machine?

At any rate, to check potential changes to this function I recommend `git log skimage/feature/peak.py`. It shows a few changes since 0.18 (Dec 2020), but none that I think could account for a fixed segfault here.

However, I stepped through in a debugger and traced the Killed error to this line:

https://github.com/scikit-image/scikit-image/blob/9fea28b7d5708152e0b96dea2f3635fa2fe6d4a0/skimage/_shared/coord.py#L33

called with ~85,000 points as input. I can reproduce the error with just this snippet:

```python
import numpy as np
from scipy.spatial import cKDTree

coord = np.random.randint(low=0, high=1848, size=(85000, 2))
tree = cKDTree(coord)
indices = tree.query_ball_point(coord, r=100, p=np.inf)
```

(By the way, @rfezzani, why is it np.inf, shouldn't we use p=2??? But that doesn't change the error anyway.)

So, I don't know at this point whether there's anything to be done here or we should raise upstream to SciPy...

**Comment by rfezzani** [comment]
Thank you for your investigation @jni. https://github.com/scipy/scipy/issues/12956 reports memory issues with cKDTree but the memory saving strategy suggested there is already implemented in `scikit-image` :confused: 

> (By the way, @rfezzani, why is it np.inf, shouldn't we use p=2??? But that doesn't change the error anyway.)

`np.inf` is used for retro-compatibility with previous implementation :wink:.

**Comment by jni** [comment]
@rfezzani 

> the memory saving strategy suggested there is already implemented in scikit-image 😕

Yeah, I remembered, but, do we actually? Is there a bug somewhere? Walking through the code now, how did I get to 85,000 points? I get to that in the first call to _ensure_spacing`...! See the code I see that it shouldn't happen with a batch size of 50...!

> np.inf is used for retro-compatibility with previous implementation 😉

I feel like that's a bug and we should use 2?

**Comment by rfezzani** [comment]
> Yeah, I remembered, but, do we actually? Is there a bug somewhere? Walking through the code now, how did I get to 85,000 points? I get to that in the first call to _ensure_spacing`...! See the code I see that it shouldn't happen with a batch size of 50...!

OK, I got it: we are not using a batch size, but a minimum batch size of 50! This comes for the strategy we adopted to manage a worst case https://github.com/scikit-image/scikit-image/pull/5062#pullrequestreview-535202840! Maybe should we change our mind.

> I feel like that's a bug and we should use 2?

I don't really see it as a bug, but we can change this and break the behaviour of v0.18

**Comment by jni** [comment]
@rfezzani but I think we just found a bug in the implementation! Here's what happens when I look at the split indices in debugging:

```python
>>> split_idx                                                                                        
array([ 85098, 127647, 148921, 159558, 164876, 167535, 168864, 169528,                               
       169860, 170026, 170109])        
```                                                              
ie we are using *decreasing* batch sizes instead of increasing them!!!! :facepalm: From the discussion in #5062:

> So you build with the top 10, 20, 40, ... n peaks, removing points each time.

So, currently, we have an 85000 point cKDTree and check 85000 points, when in fact we should have a much *smaller* cKDTree by the time we get to the final 85000 points!

**Comment by rfezzani** [comment]
:facepalm: oups!...

**Comment by rfezzani** [comment]
@jni, after a closer look, I don't think that increasing or decreasing order matters... One way or the other, all the batch needs to be processed, no matter the order. Do you agree?.. I performed some tests and found no time/memory consumption difference between the two strategies...
To tackle this issue I think that we need to define a `max_split_size` argument to bound the memory consumption.

**Comment by arogozhnikov** [comment]
woohoo, thanks @jni @rfezzani ! 🎉
