### ISSUE TITLE
skimage.data doesn't have an entry in the API reference

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#6015]
## Description

Our datasets have nice NumPy docstrings specifying data shape and origin, so they should be a part of the docs! Our [API reference page](https://scikit-image.org/docs/dev/api/api.html) doesn't list the `.data` module at all. Presumably the fix is adding a simple Sphinx TOC entry...

**Comment by gmelon** [comment]
![image](https://user-images.githubusercontent.com/33623106/144701641-41528b43-7a75-40c6-baf0-8d97d2a154f8.png)
Aren't you talking about this? Is there another part?

**Comment by grlee77** [comment]
Thanks, @gmelon, this was very recently fixed by #6075 (I should have found this existing issue rather than opening a duplicate one at #6074).
