### ISSUE TITLE
Coordinate order of `measure.find_contours` / Wrong Docs?

### ISSUE THREAD

**Issue by khdlr** [scikit-image/scikit-image#6020]
## Description

The docs for `find_contours` state that the output consists "of n (x, y) coordinates along the contour", but the returned values appear to be in (y, x) order.

The corresponding tutorial (https://scikit-image.org/docs/dev/auto_examples/edges/plot_contours.html) also uses `ax.plot(contour[:, 1], contour[:, 0])`, further indicating that the values are indeed (y, x).

## Way to reproduce

According to the docs, the plotted contour should fit the image in the following example, however it does not (while swapping x and y does):

```python
import numpy as np
import matplotlib.pyplot as plt
from skimage.measure import find_contours


a = np.zeros([10, 10])
a[5:, :5] = 1

contour = find_contours(a, 0.5)[0]

x = contour[:, 0]
y = contour[:, 1]

plt.imshow(a)
plt.plot(x, y)
```

Output:
![image](https://user-images.githubusercontent.com/9249838/140907267-11cf8226-e5c6-4dab-adfa-25c3b8aa263a.png)

## Version information
```python
3.9.7 (default, Oct 10 2021, 15:13:22) 
[GCC 11.1.0]
Linux-5.14.16-zen1-1-zen-x86_64-with-glibc2.33
scikit-image version: 0.18.3
numpy version: 1.21.2
```

**Comment by norabelrose** [comment]
I just ran into this issue today as well. This behavior is quite unexpected and it took me a while to figure out that it was `measure.find_contours` that was causing the problem. At the very least the docs should be updated, although this kind of behavior is so odd that it seems like it might be prudent to deprecate the whole function and replace it with a new one that behaves as you would expect.

**Comment by jni** [comment]
Hi @khdlr and @norabelrose!

Sorry about the confusion. The coordinate conventions for scikit-image are detailed [in this document](https://scikit-image.org/docs/dev/user_guide/numpy_images.html#coordinate-conventions). In summary: almost all of scikit-image uses row/column coordinates (which means that the coordinate order matches the NumPy array indexing order), but as a historical artifact some functions and some bits of the docs still have the transposed x/y order. We would very much welcome a pull request changing the documentation of find_contours to read "row/column"!

**Comment by norabelrose** [comment]
@jni Thanks for the clarification about this. I would love to make a PR to address this issue but to be honest I am sort of clueless about how the documentation works exactly. I was under the impression that it was auto-generated from the docstrings, but I noticed that the actual docstring for the `find_contours` function actually _does_ read "row, column" (see [here](https://github.com/scikit-image/scikit-image/blob/461a8a0a10ddc482ce8fd676d7f884c811b7b6da/skimage/measure/_find_contours.py#L51))! Not sure why it's different on the website.

**Comment by norabelrose** [comment]
UPDATE: Okay, I think I figured out the problem. I think both me and @khdlr have been looking at the docs for version 0.8.0, which is the version that pops up first on DuckDuckGo and Google, instead of the most recent version, which has the correct "row, column" reading. So I guess it's a search engine problem that we can't really fix, unless we want to try going back and retroactively changing the docs for older versions.

**Comment by jni** [comment]
Wow! I'm also a DDG user and I hadn't noticed that! 🤯 

We actually do attempt to prevent this with [robots.txt](https://github.com/scikit-image/scikit-image-web/blob/main/robots.txt), but apparently DDG ignores this???? That's disappointing. (... though scikit-image.org/robots.txt is 404, maybe we inadvertently stopped uploading that file? Will need to check with @stefanv!)

We won't fix old versions of the docs, no — we'd be stuck doing that forever.

Will check whether that file is being handled correctly by us and if so, I might tweet at DDG to ask what gives. 😂 

I've created an issue at https://github.com/scikit-image/scikit-image-web/issues/78, but will close this one in the meantime. Thanks for figuring this one out @norabelrose!

**Comment by stefanv** [comment]
Update on #78: looks like we were keeping our robots.txt up to date very nicely, without ever uploading it :man_facepalming:  This is now fixed, so hopefully DDG will update soon.

**Comment by khdlr** [comment]
Wow, this issue went in a completely different direction than I thought it would :sweat_smile: Cheers to you guys for figuring it out! I can confirm that a Google search now points to the right page while DDG still points to v0.8.0, but I guess they shouldn't take too long to also update their db.
