### ISSUE TITLE
Sphinx 4.3.0 broke documentation generation; unpin when resolved

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#6030]
## Description
It seems that Sphinx 4.3.0 broke documentation generation. We should unpin when we get to the bottom of it.

https://github.com/scikit-image/scikit-image/pull/6029

**Comment by rfezzani** [comment]
Fixed by #6029, Thank you!

**Comment by jni** [comment]
@rfezzani you misunderstood @hmaarrfk, this issue is to remind us to *unpin* once we can fix this properly. It turns out that we can: [sphinx-gallery 0.10.1 fixes things](https://twitter.com/lucyleeow/status/1459319723250761733). We can close this issue once we unpin.
