### ISSUE TITLE
DeprecationWarning raised under Python 3.10

### ISSUE THREAD

**Issue by johnthagen** [scikit-image/scikit-image#6043]
## Way to reproduce
```python
from skimage import exposure
```

Run with `python -Werror` using Python 3.10

```
    from skimage import exposure
.tox/py/lib/python3.10/site-packages/skimage/__init__.py:135: in <module>
    from .data import data_dir
.tox/py/lib/python3.10/site-packages/skimage/data/__init__.py:8: in <module>
    from distutils.version import LooseVersion
/usr/local/lib/python3.10/distutils/__init__.py:19: in <module>
    warnings.warn(_DEPRECATION_MESSAGE,
E   DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```

This code was recently moved in #5996 to:

https://github.com/scikit-image/scikit-image/blob/fa43626bd6c3db027ae339b7ecbef9f433070010/skimage/data/_fetchers.py#L8

Probably best would be to search for and replace all usages of `distutils`.

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

- Python 3.10.0
- `python:3.10` Docker image
- scikit-image 0.18.3
- numpy 1.21.4

**Comment by grlee77** [comment]
Thanks @jonathagen, we recently fixed part of this in the main branch (#6007), but a couple of imports of error classes remain. With the recently released `setuptools` 59 we can remove those as well. I will make a PR to go ahead and do that via a try/except so that we can still fall back to `distutils` for users with older `setuptools`.
