### ISSUE TITLE
skimage.transform.resize 

### ISSUE THREAD

**Issue by page200** [scikit-image/scikit-image#6047]
## Description

It seems that `skimage.transform.resize` with `anti_aliasing=True` smoothes too much. For example, if we want to resize a 100×100 image to 100×17, it should smoothen only the second dimension before downsampling, but it smoothes both dimensions.

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```
>>> from __future__ import print_function
>>> import sys; print(sys.version)
2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]
>>> import platform; print(platform.platform())
Windows-10-10.0.19041
>>> import skimage; print(f'scikit-image version: {skimage.__version__}')
  File "<stdin>", line 1
    import skimage; print(f'scikit-image version: {skimage.__version__}')
                                                                       ^
SyntaxError: invalid syntax
>>> import numpy; print(f'numpy version: {numpy.__version__}')
  File "<stdin>", line 1
    import numpy; print(f'numpy version: {numpy.__version__}')
                                                            ^
SyntaxError: invalid syntax
```

**Comment by page200** [comment]
@mkcor My setup is dictated by attempts to get some other projects to run (not related to `skimage`). The attempts succeeded and then there was no need to "change the running system". Anyway, the bug seems unrelated to the Python version.

**Comment by grlee77** [comment]
Can you specify what version of scikit-image you are having problems with? Apparently the commands suggested above don't work on whatever version it is, but if had installed it using pip you can check with `pip list`.

It looks like since scikit-image v0.14.x, the default standard deviation for the smoothing is related to the downsampling factors:

https://github.com/scikit-image/scikit-image/blob/d316fbf882e5fec53d03e1714dd87edef5e376eb/skimage/transform/_warps.py#L169-L170

It also possible to specify `anti_aliasing_sigma` as a sequence of floats to set specific user-defined values on a per-axis basis.

**Comment by page200** [comment]
@grlee77

`scikit-image` version is 0.14.5 according to `pip list`.

When not manually specifying per-axis values, the **automatically chosen** values should be appropriate rather than too large. For example, for dimensions along which the image size doesn't change, sigma should be zero.

**Comment by grlee77** [comment]
I agree, but it looks like that is what the [code is doing even in v0.14.5](https://github.com/scikit-image/scikit-image/blob/v0.14.5/skimage/transform/_warps.py#L127-L132)? In your case:
    factors = (100/100, 100/17) = (1.0, 5.88) so `anti_aliasing_sigma` should end up being `((1 - 1)/2, (5.882 - 1)/2)` which is (0.0, 2.441)

**Comment by page200** [comment]
Maybe I misinterpreted from which dimension the blurredness comes from in the results. I'll further test with toy data.
