### ISSUE TITLE
unneeded use of np.mean(s) in feature.blob_log

### ISSUE THREAD

**Issue by odoublewen** [scikit-image/scikit-image#6052]
https://github.com/scikit-image/scikit-image/blob/d316fbf882e5fec53d03e1714dd87edef5e376eb/skimage/feature/blob.py#L530

Taking the mean of one number is just the number.  So `np.mean(s)` seems like either (1) a code fragment from some earlier approach that is now harmless code cruft, or (2) possibly a genuine bug, if it is supposed to be something other than just `s`.

But either way, seems like it should be removed or changed.

cc:  @mkcor

**Comment by odoublewen** [comment]
Also cc: @grlee77

**Comment by rfezzani** [comment]
@odoublewen, this is to manage anisotropic case (when `min_sigma` or `max_sigma` are sequences) :wink:.

**Comment by odoublewen** [comment]
Ah!  

> The standard deviations of the Gaussian filter are given for each axis as a sequence, or as a single number, in which case it is equal for all axes.

I missed that part in the documentation.  Thank you for clarifying and sorry for the issue-chatter!

**Comment by rfezzani** [comment]
You welcome @odoublewen, thank you for your interest in `skimage` :wink:.
