### ISSUE TITLE
Convert CONTRIBUTING.txt to md or rst format

### ISSUE THREAD

**Issue by gmelon** [scikit-image/scikit-image#6054]
## Description
Scikit-image have a contributing guide document in txt format.
This txt file is internally described using some markdown grammar.
If we convert this into .md or .rst I think readability will be better.
Therefore, I would like to proceed with this work.
Before that, I ask for community's opinion. What do you think?

Converting the current document has no problem in most cases, but it seems that some content or grammar modifications are needed.

**Comment by hmaarrfk** [comment]
It looks like it uses alot of `rst` to me. I think changing the extension is a good place to start. It might be specified in a few places in the source.

If you want to read it in a formatted way, then you can see it online at :

https://scikit-image.org/docs/stable/contribute.html

I do agree that having it render more correctly on fancy editors would be a plus!

**Comment by gmelon** [comment]
I'll try it! Thanks you :)
