### ISSUE TITLE
Add SUPPORT file to help users

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#6058]
## Description

If we add a `SUPPORT.md` file to the repository the GitHub UI will show a link to it when users create a new issue. This can be used to guide users on how to get support or make a contribution. It is a relatively new feature of GitHub [described here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project).

**Comment by mkcor** [comment]
Interesting!

> This can be used to guide users on how to [...] make a contribution.

I guess this is taken care of by `CONTRIBUTING.txt`, right?

We can move this note https://github.com/scikit-image/scikit-image/blame/main/.github/ISSUE_TEMPLATE.md#L4 from `.github/ISSUE_TEMPLATE.md` to `.github/SUPPORT.md`. Also, I just noticed this:
![old_issue_template](https://user-images.githubusercontent.com/2227806/143616231-02707cd1-ae38-4225-953a-38da232fda8f.png)
