### ISSUE TITLE
PyPI size limit reached

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#6086]
## Description

Wheels for 0.19.0 built succesfully, but the upload to PyPI failed with the following error about exceeding a size limit:

```
 Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Project size too large. Limit for project 'scikit-image' total size is 10 GB. See https://pypi.org/help/#project-size-limit
Error: Process completed with exit code 1.
```

**Comment by grlee77** [comment]
Should we delete some older pre-releases to make space? (There are currently 7 pre-releases showing up here: https://pypi.org/project/scikit-image/#history)

**Comment by stefanv** [comment]
+1 for deleting old RCs

**Comment by hmaarrfk** [comment]
It seems that the wheels got uploaded? Did you remove rcs already? Can we check our current storage size somehow?

**Comment by grlee77** [comment]
Yes, I removed all RCs except 0.19.0rc0. I think there were five with files, so that made enough space.

**Comment by grlee77** [comment]
Will have to look if there is a way to check total space. We will probably run out again in another few releases, so may want to go ahead and request more.

**Comment by grlee77** [comment]
We are currently at 9.5 GB:
![skimage-quota](https://user-images.githubusercontent.com/6528957/144691528-1a6cbf41-26df-42cc-9a23-843c58ce6778.png)

This info was visible under "Settings" for project "owners" on PyPI. 

I just made a request to increase the total limit to 25 GB here: https://github.com/pypa/pypi-support/issues/1509

We also have a per-wheel limit of 100 MB which seems okay for now (not sure how large `universal2` wheels will be if we eventually add them, though)

**Comment by stefanv** [comment]
Thanks, Greg!

**Comment by grlee77** [comment]
On a related notes, I am curious why the individual wheels for [for 0.18.3](https://pypi.org/project/scikit-image/0.18.3/) are so much smaller than [those from 0.19.0](https://pypi.org/project/scikit-image/0.19.0/).

They are 11-30 MB for 0.18.3 vs. 34-60 MB for 0.19.0. We did add some new compiled things like SIFT and higher dimensional non-local means, but it doesn't seem like that would explain this large of a change. There are also some Cython codes where we extended from float64 only to fused type (float32 or float64).

**Comment by grlee77** [comment]
Unzipping the wheels I see that the 0.19.0 ones have all of the `.pxd`, `.pyx`, `.c` and `.cpp` files in addition to the expected `.py` files and `.so` binaries.

**Comment by hmaarrfk** [comment]
fused types basically replicate the size of the binary. it is rather unscalable IMO. I remember when I was working on it, it really increased compile time (which I was monitoring since I was waiting for it to compile)

**Comment by hmaarrfk** [comment]
The thing about the text files is that the compress quite well.

![image](https://user-images.githubusercontent.com/90008/144724350-b55f7608-0c1e-4862-b4ff-1fa0475213f1.png)
![image](https://user-images.githubusercontent.com/90008/144724355-9d707ef5-41cd-403e-83dd-fa73a413989c.png)
![image](https://user-images.githubusercontent.com/90008/144724361-f52669c7-f8c1-4899-a2e7-93a0eedd9b61.png)
![image](https://user-images.githubusercontent.com/90008/144724371-13f43e90-d0ed-410f-b8e3-b2dd10e18bc6.png)
![image](https://user-images.githubusercontent.com/90008/144724374-7a027bd1-7faa-472c-955c-462bd021da06.png)
![image](https://user-images.githubusercontent.com/90008/144724394-93af0ebb-5b33-4d83-aee8-6250d0f4cbbb.png)

I guess some of the C files do look quite huge.

**Comment by grlee77** [comment]
We were granted the increase to 25 GB, so I will close this issue and open a new one related specifically to the size of the wheels.
