### ISSUE TITLE
`0.19.0` `multichannel` change for `pyramid_expand` is not backwards compatible for single-channel images

### ISSUE THREAD

**Issue by joshuacwnewton** [scikit-image/scikit-image#6092]
## Description

With default values, the `0.19.0` version of `pyramid_expand` produces different results than the `0.18.3` version of `pyramid_expand`.

The root cause is due to a backwards-incompatible change to the default parameters of the function. (Looking at the `git blame`, I think this issue was introduced in https://github.com/scikit-image/scikit-image/pull/5285.)

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

Run this call in both `0.18.3` and `0.19.0`:

```python
import numpy as np
from skimage import transform

array_r = transform.pyramid_expand(np.ones([17, 13]))  # NB: This call doesn't use `multichannel`
```

Then check the value of `multichannel` inside `pyramid_expand`:

* For `0.18.3`, it will be `False` by default.
* For `0.19.0`, the default value should (in theory) still be `False` (I presume?):
  
  https://github.com/scikit-image/scikit-image/blob/5d594d70ffbcb04db108a8560fb684ba85884a3a/skimage/transform/pyramids.py#L35  

  However, this value gets overwritten by the following line:

  https://github.com/scikit-image/scikit-image/blob/5d594d70ffbcb04db108a8560fb684ba85884a3a/skimage/transform/pyramids.py#L84

  Since the default value of the new `channel_axis` parameter is `-1` (i.e. `not None`):

  https://github.com/scikit-image/scikit-image/blob/5d594d70ffbcb04db108a8560fb684ba85884a3a/skimage/transform/pyramids.py#L36

As a result, the resized image has its last axis treated as the channel axis (`[17, 13] -> [34, 13]`) rather than resizing that axis (`[17, 13] -> [34, 26]`).

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
# for 0.18.3 venv
3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0]
Linux-5.11.0-41-generic-x86_64-with-debian-bullseye-sid
scikit-image version: 0.18.3
numpy version: 1.18.5

# for 0.19.0 venv
3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0]
Linux-5.11.0-41-generic-x86_64-with-debian-bullseye-sid
scikit-image version: 0.19.0
numpy version: 1.18.5
```

**Comment by joshuacwnewton** [comment]
Was this intentional? i.e. is `multichannel=True` the new default? If so, should I manually be setting `channel_axis=None` in my calls to this function?

**Comment by jni** [comment]
Definitely not intentional @joshuacwnewton, thank you for the report! In the future, grayscale images will be the default for all skimage functions. This was a mistake and a PR to fix it would be most welcome! We'll backport the fix to release 0.19.1 as we don't make backwards-incompatible API changes without a deprecation period (except in exceptional circumstances such as broken/buggy functionality).

If you are too busy to submit a PR we will aim to get this fixed very shortly.

**Comment by grlee77** [comment]
Thanks for reporting this @joshuacwnewton. Indeed, this was an unintentional change to the default behavior.

**Comment by joshuacwnewton** [comment]
> In the future, grayscale images will be the default for all skimage functions.

Thanks for the quick reply! I appreciate the clarification here. :heart: 

> and a PR to fix it would be most welcome!

Will do! :)
