### ISSUE TITLE
unintentional change to skimage.data public API

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#6096]
## Description

The `skimage.data.image_fetcher` is no longer available. This has caused test failures in napari for scikit-image 0.19.0.

I will open a PR now to restore it to the public API.

## Way to reproduce
```Python
from skimage.data import image_fetcher`
```
will result in an `ImportError`

## Version information
0.19.0

**Comment by hmaarrfk** [comment]
can we maybe deprecate it?

**Comment by grlee77** [comment]
@hmaarrfk, I found three functions as listed in #6097 that were formerly public. Now we need to decide which can/should be deprecated.

Here is the downstream issue: https://github.com/napari/napari/issues/3747 and the pytest configuration file [where `napari` is currently using it](https://github.com/napari/napari/blob/main/napari/conftest.py)

**Comment by grlee77** [comment]
I haven't looked into why `image_fetcher` is being used directly for the test configuration, but we can probably rewrite it as needed on the napari side.

**Comment by hmaarrfk** [comment]
I think starting a deprecation cycle is a good cleanup, but the issue of removing something from the public API should definitely be addressed quickly.
