### ISSUE TITLE
Reduce the wheel size relative to 0.19.0 for upcoming releases

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#6102]
## Description

Continuing the discussion from https://github.com/scikit-image/scikit-image/issues/6086#issuecomment-986063471

We have seen a recent increase in wheel size by nearly a factor of two for 0.19.0 vs. 0.18.3. In order to be a good citizen, preserving PyPI and CI resources we should try to reduce this if possible.

So far, one difference I noticed was that the 0.19.0 wheels have various `.c`, `.cpp` and `.pyx` files that should not need to be in the wheel.

**Comment by grlee77** [comment]
I checked for one of the linux wheels that the wheel size without the extra source files goes from 59.7 MB -> 52.4MB so ~7.3 MB improvement. The difference is bigger once the wheel is unzipped: 234 MB -> 144 MB.

@hmaarrfk, do you happen to know why these source files are suddenly being included in the wheels? We were already using `cibuildwheel` for 0.18.3 too, just without the automated deployment. I just tried `pip wheel . -vv` locally and the resulting wheel does not include these extra source files.

**Comment by hmaarrfk** [comment]
wow! no i really don't tbh. the difference in size is quite staggering. I didn't expect that.

**Comment by erykoff** [comment]
I don't know about any specific recent changes in wheel building for scikit-image or other packages, but for whatever reason including the cythonized `.c` files in the pypi wheels seems to be the norm.  

And the cythonized .c files are _enormous_.  Something like x20 the number of lines of the associated .pyx files.

**Comment by grlee77** [comment]
> including the cythonized .c files in the pypi wheels seems to be the norm.

Maybe, but I looked at a wheel from the most recent SciPy and PyWavelets releases and see only `.py` and `.so` files. SciPy is using a different build toolchain, but PyWavelets is using a `cibuildwheel` script that I copied from the one here, so I don't see why it should be different!

**Comment by erykoff** [comment]
Interesting!  Then I think we want to get to the bottom of this and then file issues wherever we see extra c files creating extra large packages (e.g. pytables wheels have the c files as well).

**Comment by grlee77** [comment]
To avoid use of deprecated distutils, we recently changed some imports to use setuptools instead. For some reason the following 1 line change to setup.py gets us back to smaller wheels (no source files included) when using `python setup.py bdist_wheel`.

```Python
from setuptools.command.build_py import build_py
```
vs. the import we had in 0.18.3
```Python
from distutils.command.build_py import build_py
```

When the import is from `distutils` the wheel size is ~40MB vs. when the import is from `setuptools` it ends up ~63 MB.

Another option that can result in smaller wheels is to strip debug symbols by adding `-Wl,--strip-debug` to the LDFLAGS environment variable. For example, NumPy does this here: https://github.com/MacPython/numpy-wheels/blob/df5cb747e055ec5c60298c936e9c68709f05bcd6/env_vars.sh#L7

Using that flag further shrinks the wheel from ~40MB to ~14MB and even the uncompressed size is only around 32MB!

The same applies when `pip wheel` is used instead of `python setup.py bdist_wheel`

**Comment by erykoff** [comment]
Good catch on the `setuptools` vs `distutils`!  And I _think_ that with `setuptools` the issue is that `include_package_data=True` which will package up all the files, while if you explicitly list what extra files you want with the `package_data` kwarg then I think it won't include the extra pyx and c files.

Then if you strip the debug symbols you get the additional amazing space savings!
