### ISSUE TITLE
Handling of vertex coordinates greater than the image size

### ISSUE THREAD

**Issue by pedrogalher** [scikit-image/scikit-image#6111]
I have a JSON file generated by the VIA Annotation software that contains the vertex of the annotated objects. I then use the draw.polygon (skimage==0.17.2) to convert the image with the annotations to binary by means of:
``
rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])  
mask[rr, cc] = 255
``
These lines used to work well and automatically handled the vertex whose coordinates were greater than the image size. However, I have recently updated to skimage=0.19.0 and when I specify the shape of the image by using: ``rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'],shape=(130,130))`` , the binary images generated are not exactly the same (small changes in the border) as the ones generated with skimage=0.17.2. 

What did it change in the code? I'm really curious as I generate these masks as part of my research and I eventually need to be consistent.

Thank you!

**Comment by rfezzani** [comment]
@pedrogalher, can you please provide a small failing example such that we can investigate?

**Comment by pedrogalher** [comment]
Hi,

Here is the [google colab](https://drive.google.com/drive/folders/1ar_O4ehc5hO0qKzd9IvWg3JVyggfVLYI?usp=sharing) to reproduce the difference in the mask generated by the versions 0.17.2 and 0.19.0: 

To reproduce the issue just install the corresponding version of skimage and change the preffix of the mask to account for the change and the mask is not override.

Thanks
Pedro

**Comment by grlee77** [comment]
The behavior seems to have changed with this specific commit sometime before v0.18.0:
https://github.com/scikit-image/scikit-image/commit/61f037c3ab9dd7df522134b3048cebcf3f62e43f#

The actual loop range used in the `_polygon` function looks the same both before and after that PR though (specifying shape constrains the loop to the image shape). I ran your example, though and it completes without specifying the shape arg for the commit immediately before that one and fails on that commit.

**Comment by jni** [comment]
@pedrogalher you can read the discussion in the pull request that changed things here:

https://github.com/scikit-image/scikit-image/pull/5029

Based on my re-reading of it, the new coordinates should be considered correct. Please reopen if you find a case that you think is *incorrect* in the new method. (Rather than just inconsistent with the previous results, which, as discussed in #5029, were not correct at the edges.)

Thanks!

**Comment by pedrogalher** [comment]
@jni Thank you very much for the explanation.

I just want to point out that the difference in the binary masks generated by both versions not only occur in the vertex in the images edges, but also in the vertex of objects that are not in the edges (centre of image).
I generated the masks,in the colab, of the same image using both versions so that you can check it. 
You could see that the bottom and right-hand side border of the objects in the centre slightly differ from one version to the other. The mask generated by the 0.19v is slightly thicker than the mask generated by the 0.17v.
The images are named: "sk_17_0050" and "sk_19_0050" for the 0.17 and 0.19 versions, respectively.

Thanks!
Pedro

**Comment by rfezzani** [comment]
@pedrogalher, as mentioned by @jni, the changes introduced in #5029 are the consequences of a bug fix.
These changes are located at the edges and vertices of the polygons, not the edge of the image :wink:
Concerning your research reproducibility requirement, as you need to register your scripts and your data, you also need to save your code dependencies! I recommend you use virtual environments (`pipenv`, `conda`...) and save the corresponding configuration file (`requirements.txt`, `env.yml`..) alongside your code...

**Comment by pedrogalher** [comment]
@rfezzani aha! I had not clearly understood it the first time. Now it is clear :)
Yes, I always save the dependencies I use in my code so it should be fine from that side.
Thank you very much for the clarification and the quick answer.

Best
Pedro
