### ISSUE TITLE
external modulss missing since version > 0.16

### ISSUE THREAD

**Issue by abbioinfo** [scikit-image/scikit-image#6120]
## Description
I am trying to load TiffFile, TiffWriter functions but can't get the external functions going. 

>from skimage.external.tifffile import TiffFile, TiffWriter
ModuleNotFoundError: No module named 'skimage.external'

## skimage is already installed.

> from skimage.feature import corner_harris, corner_peaks

**Comment by grlee77** [comment]
We don't bundle tifffile with scikit-image anymore. Please just directly install tifffile separately via pip or conda.

See: 
https://pypi.org/project/tifffile/
