### ISSUE TITLE
Website: Launch Binder: only supports Python 3.8 and above

### ISSUE THREAD

**Issue by talkdirty** [scikit-image/scikit-image#6136]
Sorry, no idea if it's the right place to post this, but just noticed that on [this page](https://scikit-image.org/docs/dev/auto_examples/transform/plot_fundamental_matrix.html), pressing "launch Binder" will result in the following error:

```
"scikit-image supports only Python 3.8 and above"
```

**Comment by hmaarrfk** [comment]
hmm. thanks for the report. i tried to look into it, but i couldn't find how to specify the version of python used for binder.

**Comment by grlee77** [comment]
closed by #6152 (Python 3.9 will be launched instead of Python 3.7 when running gallery examples from the dev docs).
