### ISSUE TITLE
Incorrect stacklevel for  deprecate_multichannel_kwarg  deprecation warnings.

### ISSUE THREAD

**Issue by Carreau** [scikit-image/scikit-image#6137]
## Description

deprecate_multichannel_kwarg and alike properly set the stacklevel to 2, 
But for functions with this decorator are also decorated with `@utils.channel_as_last_axis()`, which adds at  1 level between the caller and the final warning location.

This mean that 1) the warning messages are less useful, they all point to `skimage/_shared/utils.py:338`.
2) filter set for dependees  turn warnings into errors don't become error (e.g Napari)

## Way to reproduce
```python
# foo.py
from skimage.transform import pyramid_gaussian
pyramid_gaussian(None, multichannel=True)
```
```
$ python foo.py
/Users/bussonniermatthias/dev/scikit-image/skimage/_shared/utils.py:338: FutureWarning: `multichannel` is a deprecated argument name for `pyramid_gaussian`. It will be removed in version 1.0.Please use `channel_axis` instead.
  return func(*args, **kwargs)
```

## Version information

e37fc660aeb96d53db27c9e2f1a0a88920bc2b65 (dec 15th), orther info 

deprecate_multichannel_kwarg could gain and "extra_stacklevel" to properly place the warning where relevant.

**Comment by anntzer** [comment]
I haven't checked the skimage internals wrt. warnings, but you may be interested in how we're doing it on matplotlib's side:
https://github.com/matplotlib/matplotlib/blob/a35921c407aced5e65d39b29fd942676ee03679b/lib/matplotlib/_api/__init__.py#L287-L306
```python
def warn_external(message, category=None):
    """
    `warnings.warn` wrapper that sets *stacklevel* to "outside Matplotlib".

    The original emitter of the warning can be obtained by patching this
    function back to `warnings.warn`, i.e. ``_api.warn_external =
    warnings.warn`` (or ``functools.partial(warnings.warn, stacklevel=2)``,
    etc.).
    """
    frame = sys._getframe()
    for stacklevel in itertools.count(1):  # lgtm[py/unused-loop-variable]
        if frame is None:
            # when called in embedded context may hit frame is None
            break
        if not re.match(r"\A(matplotlib|mpl_toolkits)(\Z|\.(?!tests\.))",
                        # Work around sphinx-gallery not setting __name__.
                        frame.f_globals.get("__name__", "")):
            break
        frame = frame.f_back
    warnings.warn(message, category, stacklevel)
```

**Comment by Carreau** [comment]
Yeah I had a similar suggestion in #6138.

Those kind of utils should really be in core CPython warnings...
