### ISSUE TITLE
SIFT wrong octave values for keypoints

### ISSUE THREAD

**Issue by longjoke** [scikit-image/scikit-image#6173]
Thank you for including SIFT in skimage. I think there is a small problem with how the octave values are calculated for keypoints. If there are no keypoint candidates (local extremas) found in one octave it is skipped.  See:
https://github.com/scikit-image/scikit-image/blob/ed642e2bc822f362504d24379dee94978d6fa9de/skimage/feature/sift.py#L338

Later, when the octave indices are calculated, the lower octave is not included. See:
https://github.com/scikit-image/scikit-image/blob/ed642e2bc822f362504d24379dee94978d6fa9de/skimage/feature/sift.py#L421
So, keypoints in higher octaves have indices too low. The empty octave has to be included for the correct indices.

I hope this makes sense.

Edit: there is also a typo  here:
https://github.com/scikit-image/scikit-image/blob/ed642e2bc822f362504d24379dee94978d6fa9de/skimage/feature/sift.py#L154
it should be scales

**Comment by alexdesiqueira** [comment]
Hey @longjoke,
thank you for opening this issue!

> I think there is a small problem with how the octave values are calculated for keypoints. If there are no keypoint candidates (local extremas) found in one octave it is skipped. See:

I am not an expert on the SIFT algorithm, so I'll ask for help: @grlee77 @faberno @AlexanderZeilmann could y'all help me here? Thank you! :slightly_smiling_face:

>  it should be scales

For our SIFT implementation, we used the following paper:
```
    The implementation here closely follows the
    detailed description in [3]_, including use of the same default parameters.
    .. [3] I. R. Otero and M. Delbracio. "Anatomy of the SIFT Method",
           Image Processing On Line, 4 (2014), pp. 370–396.
           :DOI:`10.5201/ipol.2014.82`
```
Maybe there is a difference in notation from the implementation you're referring to. Could you point me to a reference that describes the algorithm as you see it?
Thanks again @longjoke!

**Comment by longjoke** [comment]
Thanks for the reply. I think there was a misunderstanding regarding the second issues. The attribute is called scales, just the documentation contains a typo. The sigmas attribute is just above. The implementation is great.

**Comment by alexdesiqueira** [comment]
@longjoke oh, thanks for clarifying! I see it. Would you like to fix it opening a PR? :slightly_smiling_face:
Thanks again!

**Comment by faberno** [comment]
Hey @longjoke, thanks a lot for pointing this out. It's definitely an issue, but luckily an easy fixable one :D
I think adding `extrema_pos.append(np.empty((0, 2)))` to `if keys.size == 0:` should do the job, right?

Also thanks for finding the typo!
