### ISSUE TITLE
License for data/cells3d.tif is "unknown" on GL:skimage/data

### ISSUE THREAD

**Issue by alexdesiqueira** [scikit-image/scikit-image#6181]
Hey everyone,

[TL;DR] It would be great to define the license for `data/cells3d.tif`, so we can update the README info on [GL:skimage/data](https://gitlab.com/scikit-image/data).

while checking #6178, @mkcor pointed out that the license for `data/cells3d.tif` is defined as "unknown":
```
cells3d.tif

    * origin: Allen Institute for Cell Science
    * licence: Unknown
    * description: 3D fluorescence image of a monolayer of cells, including both
    membrane and nuclear stains. Image shape is (60, 2, 256, 256). The axes are
    in ZCYX order.
```
We use it also at [`scikit-image/skimage-tutorials`](https://www.github.com/scikit-image/skimage-tutorials/); e.g., [`skimage-tutorials/images/cells.tif`](https://github.com/scikit-image/skimage-tutorials/blob/main/images/cells.tif) is a slice of that image.
All images there are [distributed as CC0](https://github.com/scikit-image/skimage-tutorials/blob/main/LICENSE.txt) (except for `skimage-tutorials/data/diatom*.jpg`, `skimage-tutorials/data/keras_model-diatoms-pores.h5`).
@stefanv I think we confirmed this image as being CC0 a while ago, with the help of the Allen Institute. Is that so? I remember we discussed this a while ago, but maybe it's my memory tricking me.
@scikit-image/core could* we _pull the capybara_ (investigate it further, in good BR Portuguese) of this file? It would be great to be certain about the license for that file. Please point issues/PRs if we discussed this before. Documents pointing the license would also help.
Thanks y'all!

**Comment by stefanv** [comment]
I have an email from @mcquin stating with "99% certainty" that the image is CC0 and released by the Allen Institute.  I will write an email to the relevant parties today to confirm.

I'm not sure what it means to pull the capybara!

**Comment by stefanv** [comment]
```
From: Kimberly Metzler <...@alleninstitute.org>
To: Susanne Rafelski <...@alleninstitute.org>, Anne Carpenter
	<...@broadinstitute.org>
CC: Stefan van der Walt <...@berkeley.edu>
Date: Thu, 13 Jan 2022 16:39:33 +0000
Message-ID: <MW3PR12MB458695CDEF316B94CE3A203FE1539@MW3PR12MB4586.namprd12.prod.outlook.com>

[...]

I double checked, and the you are still able to distribute the image in question under CCO. 

[...]

```

**Comment by alexdesiqueira** [comment]
Thank you for confirming, @stefanv!
@mkcor asked @haesleinhuepf to update this info on [GL:scikit-image/data](https://gitlab.com/scikit-image/data/-/merge_requests/17), so I will close this one as solved. :heavy_check_mark: 
Thanks y'all!
