### ISSUE TITLE
hough_line_peaks() returning incorrect angle and distance arrays for certain line detections

### ISSUE THREAD

**Issue by pdinnen** [scikit-image/scikit-image#6187]
## Description

The bug shows up in the case where peak._prominent_peaks() detects peaks and the all peaks are angle index 0.

Those are valid results but the `a.any()` test in hough_transform  evaluates to false for zero values. So the returned angle and distance indexes are replaced with empty arrays.

## Way to reproduce
```import numpy as np
from skimage.transform import hough_line, hough_line_peaks

# create an empty test image
img = np.zeros((100, 100), dtype=bool)
# draw a horizontal line into our test image
img[30, :] = 1

hough_space, angles, dist = hough_line(img)

best_h_space, best_angles, best_dist = hough_line_peaks(hough_space, angles, dist)
```
`best_angles` and `best_dist` are empty arrays. They should not be empty.

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) 
[Clang 6.0 (clang-600.0.57)]
macOS-10.14.6-x86_64-i386-64bit
scikit-image version: 0.19.1
numpy version: 1.22.0

```

**Comment by mkcor** [comment]
Dear @thrdr,

Are you comfortable submitting a fix for this bug?

Don't hesitate to reach out, either here or in the [chat](https://skimage.zulipchat.com), should you have questions on the [contribution process](https://scikit-image.org/docs/stable/contribute.html).

Cheers,
Marianne

**Comment by grlee77** [comment]
It looks like this is actually the same issue as #4129, so I referenced that one here and will go ahead and close this one.
