### ISSUE TITLE
General help on the usage of restoration.richardson_lucy

### ISSUE THREAD

**Issue by Taoboan1999** [scikit-image/scikit-image#6194]
ValueError: convolve2d inputs must both be 2D arrays

当我使用restoration.richardson_lucy函数处理图片是反馈这个bug，请问如何解决，我的图片是rgb图像

**Comment by alexdesiqueira** [comment]
Hi @Taoboan1999,
thank you for your issue! Could you share some code as an example, and maybe a couple of test images? This way we could try to reproduce the bug you're facing. Thanks!

**Comment by Taoboan1999** [comment]
> 

您好，非常感谢。我现在调试成功，能够运行代码了，因为我是rgb三通道图像，我对每个分量做处理就能运行了，但是生成的图像是全黑色的图像，请问这是为什么呢，以下是我的核心代码

        train_image_path = os.path.join(train_images_path, image_name)
        DB_train_image = cv2.imread(train_image_path, cv2.IMREAD_COLOR)

        DB_train_image = img_as_float(DB_train_image)
        psf = np.ones((5, 5)) / 25

        for i in range(DB_train_image.shape[-1]):
            DB_train_image[:, :, i] = convolve2d(DB_train_image[:, :, i], psf, mode="same")

        rng = np.random.default_rng()
        DB_train_image += 0.1 * DB_train_image.std() * rng.standard_normal(DB_train_image.shape)
        fixed = np.zeros(DB_train_image.shape)
        for i in range(DB_train_image.shape[-1]):
            fixed[:, :, i] = restoration.richardson_lucy(DB_train_image[:, :, i], psf, 5)

        cv2.imwrite(os.path.join(DB_train_images_path, image_name), fixed)

**Comment by alexdesiqueira** [comment]
Hey @Taoboan1999,
I think your issues are coming from reading an image with OpenCV and not converting it before applying scikit-image functions.
I'd guess that your issues start here:
```python
DB_train_image = cv2.imread(train_image_path, cv2.IMREAD_COLOR)
DB_train_image = img_as_float(DB_train_image)
```
I'm not sure this conversion works the way you expect :slightly_smiling_face: I'd bet that's why the images you're receiving are black. 
Could I suggest you using scikit-image functions, instead of OpenCV ones? This way, you would have:
```python
from skimage import io, util
# reading it this way you would have a grayscale, 2D image. No need to break the RGB channels:
DB_train_image = io.imread(train_image_path, as_gray=True)
DB_train_image = util.img_as_float(DB_train_image)
(...)
io.imsave(fname=os.path.join(DB_train_images_path, image_name), arr=fixed)
```
... something more or less like that.
Sorry if this doesn't solve the issue for you, my Chinese is kinda rusty nowadays and maybe I misunderstood you somewhere :slightly_smiling_face: Please let us know if it works. Thanks!

**Comment by Taoboan1999** [comment]
> 
实在是太感谢您了，您的思路是使用skimage内的io流读取图片信息，我成功地实现了代码的功能，实在是感谢您的帮助。我希望用restoration.richardson_lucy函数实现“盲反卷积”图像恢复的功能，可是效果并不是很好，请问您在代码的参数方面有什么调试的建议吗？
        for i in range(DB_train_image.shape[-1]):
            fixed[:, :, i] = restoration.richardson_lucy(DB_train_image[:, :, i], psf, 50)
非常抱歉我的英语水平不是很好，希望您能谅解。

**Comment by alexdesiqueira** [comment]
Hey @Taoboan1999,

> 实在是太感谢您了，您的思路是使用skimage内的io流读取图片信息，我成功地实现了代码的功能，实在是感谢您的帮助。

I'm glad you could solve the issue!

> 非常抱歉我的英语水平不是很好，希望您能谅解。

Don't worry about that, I can train my reading a little bit :wink: 

> 我希望用restoration.richardson_lucy函数实现“盲反卷积”图像恢复的功能，可是效果并不是很好，请问您在代码的参数方面有什么调试的建议吗？
for i in range(DB_train_image.shape[-1]):
fixed[:, :, i] = restoration.richardson_lucy(DB_train_image[:, :, i], psf, 50)

For the `richardson_lucy` function, I'd advise you to play with the values of `num_iter` (`skimage.restoration.richardson_lucy(image, psf, num_iter=50)`) a little. Maybe the default parameter is too high or too low for your images; it would be nice to vary this parameter in, let's say, steps of two from 0 to 100 and see the difference.
I'll close this issue now, but please feel free to reach out for support in our [skimage/Discussions](https://github.com/scikit-image/scikit-image/discussions) page.
Thanks again!
