### ISSUE TITLE
Histogram matching looks broken

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#6196]
## Description

I just noticed that histogram matching looks broken, either on my RGB images and in the gallery: https://scikit-image.org/docs/stable/auto_examples/color_exposure/plot_histogram_matching.html#sphx-glr-auto-examples-color-exposure-plot-histogram-matching-py

Thus, I do not put a minimal example, I guess the gallery is enough.

It appears that some channels are at 0, explaining the runtime warning.

**Comment by rfezzani** [comment]
Thank you @sciunto for the bug report, happy to see you around :wink: 

Histogram matching looks in fact broken, comparing current gallery example  to [v0.18](https://scikit-image.org/docs/0.18.x/auto_examples/color_exposure/plot_histogram_matching.html#sphx-glr-auto-examples-color-exposure-plot-histogram-matching-py)  for example...

**Comment by mkcor** [comment]
Hello @sciunto!

Nice to see you around, indeed.

@rfezzani this bug has already been reported, fixed, and backported: see #6168 and #6169 -- let's wait for the upcoming release of v0.19.2! I'll let you close the issue, thanks.

**Comment by rfezzani** [comment]
> @rfezzani this bug has already been reported, fixed, and backported: see #6168 and #6169 -- let's wait for the upcoming release of v0.19.2! I'll let you close the issue, thanks.

:facepalm: Thank you @mkcor, you are right! @sciunto, please see [dev doc]( https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_histogram_matching.html#sphx-glr-auto-examples-color-exposure-plot-histogram-matching-py) :wink:

**Comment by sciunto** [comment]
thank you ! :)
