### ISSUE TITLE
Confusing example on perimeter measurements

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#6199]
## Description

Looking at the gallery, I'm confused by this example: https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_perimeters.html#sphx-glr-auto-examples-segmentation-plot-perimeters-py

The text speaks about a square and its rotated version, but the code is about a square and a disk. Am I missing something?

**Comment by mkcor** [comment]
You are right, @sciunto; the example is quite confusing the way it is written. I have improved the writing in #6200, fixing a few terms along the way (error vs. uncertainty, estimate vs. evaluate).
