### ISSUE TITLE
Consistent ProjectiveTransform params value when estimate fails

### ISSUE THREAD

**Issue by chrisroat** [scikit-image/scikit-image#6205]
## Description

The two `ProjectiveTransform.estimate` failure modes will leave the object in different states.  See below, where the first failure path sets `self.params` to `np.nan` while the second leaves them untouched.

https://github.com/scikit-image/scikit-image/blob/1544b32de29440f787d3d038ca912ad85e54d616/skimage/transform/_geometric.py#L704-L706

https://github.com/scikit-image/scikit-image/blob/1544b32de29440f787d3d038ca912ad85e54d616/skimage/transform/_geometric.py#L735-L736

Should these both do the same thing?

(Also, I believe the `self.params` should have shape `(d+1,d+1)`, but perhaps this is irrelevant in failure cases)

**Comment by grlee77** [comment]
Yeah, it seems like these should be consistent. Also agree about shape `(d + 1, d + 1)`.
