### ISSUE TITLE
Allow output_shape to be any iterable in resize and resize_local_mean

### ISSUE THREAD

**Issue by jinfagang** [scikit-image/scikit-image#6218]
/skimage/transform/_warps.py", line 63, in _preprocess_resize_output_shape
    output_shape = output_shape + (image.shape[-1], )
TypeError: can only concatenate list (not "tuple") to list

**Comment by rfezzani** [comment]
Hello @jinfagang, and thank you for your interest in `skimage`. As the error message you kindly copy/pasted stipulates, `output_shape` must be tuple for `resize` or `resize_local_mean` to work properly.
This condition can in fact be relaxed... I modified the title of your this issue accordingly. Thank you for the report.
