### ISSUE TITLE
Label graph structure

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#622]
We often have need to operate over regions in the image identified by labels.  In order to handle this efficiently, a graph structure could be created.  Operations can then be performed on the graph structure, e.g.

```
g = graph_from_label(labeled_image)

areas = [len(pixels) for pixels in g]
x_centroid = np.mean([x for x, y in g.positions])

g2 = graph_from_label(another_image)

join = g1 + g2
```

**Comment by jni** [comment]
I feel like this describes something akin to region adjacency graphs, which are now in `skimage.future.graph.rag`. Shall we close this issue?

**Comment by jni** [comment]
Imma gonna close it. =P Reopen if you feel strongly otherwise.
