### ISSUE TITLE
Incorrect center normal calculated in marching_cubes_lewiner

### ISSUE THREAD

**Issue by praeclarum** [scikit-image/scikit-image#6226]
I believe there is a typo in the code to calculate the normal of the center of a cube.

The code is:

https://github.com/scikit-image/scikit-image/blob/84df56fae72b284b6ec38ab1290c52f4dd3412ad/skimage/measure/_marching_cubes_lewiner_cy.pyx#L732-L740

I believe the last line should be calculating the Z norm, and not reassigning the X value:

Change from:

```python
        self.v12_xg = ( v0*self.vg[0*3+2] + v1*self.vg[1*3+2] + v2*self.vg[2*3+2] + v3*self.vg[3*3+2] +
                        v4*self.vg[4*3+2] + v5*self.vg[5*3+2] + v6*self.vg[6*3+2] + v7*self.vg[7*3+2] )
```

To this:

```python
        self.v12_zg = ( v0*self.vg[0*3+2] + v1*self.vg[1*3+2] + v2*self.vg[2*3+2] + v3*self.vg[3*3+2] +
                        v4*self.vg[4*3+2] + v5*self.vg[5*3+2] + v6*self.vg[6*3+2] + v7*self.vg[7*3+2] )
```

## Version information
```python
3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
Linux-5.11.0-43-generic-x86_64-with-glibc2.29
scikit-image version: 0.16.2
numpy version: 1.21.4
```

**Comment by grlee77** [comment]
closed by #6227, thanks again @praeclarum
