### ISSUE TITLE
non-integer used as index deprecated in numpy master

### ISSUE THREAD

**Issue by juliantaylor** [scikit-image/scikit-image#623]
current numpy master (1.8.0dev) deprecates non-integers used as indices in several places, this affects skimage in several places.
see https://github.com/numpy/numpy/pull/3243

do get a list of warnings build run skimage with a recent numpy checkout using this command:

    python3 -W all -c "import skimage; skimage.test()"

here a list of warnings I found on my system with recent git numpy and scipy:
http://paste.ubuntu.com/5811683/

note that the list of issues will be larger when built with python3 due to the change of division to true_division.

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image/pull/1005.
