### ISSUE TITLE
skimage.transform.PiecewiseAffineTransform.estimate Missing 'self' argument error

### ISSUE THREAD

**Issue by aloerch** [scikit-image/scikit-image#6243]
## Description

skimage.transform.PiecewiseAffineTransform.estimate() takes 3 positional arguments, 'self', 'src' and 'dst'. Obviously, 'self' should not be specified when when using the function. Unfortunately, it is complaining that 'self' is missing when I specify the src and dst arguments. 

## Way to reproduce
I tried:
1)
from skimage import transform
transform.PiecewiseAffineTransform.estimate(src_points, dst_points)
TypeError: estimate() missing 1 required positional argument: 'dst'

2) 
from skimage import transform
transform.PiecewiseAffineTransform.estimate(src=src_points, dst=dst_points)
TypeError: estimate() missing 1 required positional argument: 'self'

3)
import skimage
skimage.transform.PiecewiseAffineTransform.estimate(src=src_points, dst=dst_points)
TypeError: estimate() missing 1 required positional argument: 'self'

## Version information
```python
Python 3.8.12
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```
```python
3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07) 
[GCC 9.4.0]
Linux-5.11.0-41-generic-x86_64-with-glibc2.10
scikit-image version: 0.19.1
numpy version: 1.22.2
```

**Comment by rfezzani** [comment]
Hi @aloerch, and thank you for your interest in `skimage`. You need to instantiate the `transform.PiecewiseAffineTransform` object before calling its `estimate` method :wink:! This will work as expected:
```python
from skimage import transform
transform.PiecewiseAffineTransform().estimate(src_points, dst_points)
```
Note the parenthesis before the `estimate` call...
