### ISSUE TITLE
Error when using SLIC with a mask

### ISSUE THREAD

**Issue by Romain3Ch216** [scikit-image/scikit-image#6275]
Hi everyone,

I have a strange error when I add a mask argument in my SLIC segmentation:

```
File "..", line 209, in clustering
    self.segmentation = slic(img, n_segments=n_segments, compactness=compactness, mask=mask)
  File "../envs/ml/lib/python3.8/site-packages/skimage/segmentation/slic_superpixels.py", line 252, in slic
    centroids, steps = _get_mask_centroids(mask, n_segments)
  File "../envs/ml/lib/python3.8/site-packages/skimage/segmentation/slic_superpixels.py", line 38, in _get_mask_centroids
    idx = np.sort(rnd.choice(np.arange(len(coord), dtype=int),
  File "mtrand.pyx", line 982, in numpy.random.mtrand.RandomState.choice
TypeError: 'float' object cannot be interpreted as an integer
```

I cannot see where the problem is. My mask is a boolean ndarray. It works fine without the mask argument. Do you have any clue?

Thanks for your help,
Romain

**Comment by rfezzani** [comment]
Hello @Romain3Ch216, thank you for the report. It seems that you are using skimage v0.17 or lower. Can you please update your package to a newer version and see if you still face this bug?

In this case can you please come with some lines of codes to ease our investigation.

**Comment by rfezzani** [comment]
Excellent, happy to see your problem gone :wink:. I close the issue as it is fixed.
