### ISSUE TITLE
Maximum array size for `morphology.reconstruction`?

### ISSUE THREAD

**Issue by JamesSample** [scikit-image/scikit-image#6277]
## Description

When used with large arrays, `morphology.reconstruction` crashes my Python kernel (without any other error - I just see `The kernel for xxx.ipynb appears to have died. It will restart automatically`).

Is there a limit to the size of array this function can handle (beyond the memory limits of the system)? My problem is similar to [this issue](https://github.com/scikit-image/scikit-image/issues/4078), except my array does not contain any NaNs. If I split the array into smaller chunks, everything works as expected, but unfortunately I need to process the whole file in one go. 

I've encountered the same problem with several different datasets, so I don't think it's specific to my data. I also have plenty of memory on my machine: I'm running on Google Cloud and have tried various machines with up to 1 TB of RAM. On these, the kernel crashes when memory usage is less than 1% (as indicated by `top`).

## Way to reproduce

An example array (saved as a `.pkl` file) can be downloaded [here](https://drive.google.com/file/d/1n2GsBPYiLeOdkMnitC_ZI0vsLb4lWcJH/view?usp=sharing) (***warning**: it's about 5 GB*).

The following code runs for 5 to10 minutes, then crashes the kernel:

```python
import pickle
import numpy as np
import skimage.morphology

with open("glomma.pkl", "rb") as f:
    data = pickle.load(f)

assert ~np.isnan(data).any()

# Keep perimeter cells equal to the original values and set all other cells to max
seed = data.copy()
seed[1:-1, 1:-1] = data.max()

filled = skimage.morphology.reconstruction(seed, data, method="erosion")
```

If I use the code below to subset the array into tiles/quadrants, I can process each tile fine (but of course the combined result is not the same as the output for the full array).

```python
# Process just one quadrant
rows, cols = data.shape
data = data[: int(rows / 2), : int(cols / 2)] 
```

Does anyone have any tips, please? I've already split the original image into "coherent" subsets to make each dataset as small as possible. 260 out of 262 subsets are processed OK, but the two largest crash the kernel and I haven't managed to find a workaround yet.

Thank you! :-)

## Version information

```python
3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
Linux-5.4.144+-x86_64-with-glibc2.31
scikit-image version: 0.18.3
numpy version: 1.21.5
```

**Comment by hmaarrfk** [comment]
Many alogorithms don't scale well with input data that is very large.

The general issue is that ALOT of cython code assumes that data is contiguous. Therefore, you end up copying the data man ytimes.

Finally, you need to allocate RAM quickly when you use such large datasets. look at hugetlbfs or something similar.

Help improving the speed of algorithms for large arrays is definitely helpful.

My immediate tip would be:

1. Chunk up your data into small pieces.
2. Pass in the output arrays to avoid reallocating output arrays when possible.

**Comment by JamesSample** [comment]
Thanks for the fast reply!

This might be a silly question, but is it possible to "chunk" data passed to `morphology.reconstruction` without knowing in advance what regions the algorithm will need to "grow" into?

My use case is perhaps a little unusual: my array is actually a single-band elevation dataset (i.e. pixel intensities represent heights above sea level) and I'm trying to perform hydrological "terrain conditioning" by filling depressions. I'm using [PySheds](https://github.com/mdbartos/pysheds) to do this (original issue [here](https://github.com/mdbartos/pysheds/issues/187)), but PySheds just calls `morphology.reconstruction` behind the scenes, which is how I ended up here. 

I'm not very familiar with morphological reconstruction in general, but I don't think I can just split my dataset into pieces and then stitch the results back together (?). 

Thanks for the tips! I've never worked with Cython code before, so I suspect I might be out of my depth here, but I'll take a look at `hugetlbfs` and report back if I make any progress.

**Comment by hmaarrfk** [comment]
I'm not really able to help too much in the algorithm development. This is in fact your task. But I can give some general tips:

With a 5GB dataset, you really have to start worrying about silly things like:
```
assert ~np.isnan(data).any()
```

Assuming your data is `float32`, this would create an other 1.25 GB array of bools.
That allocation isn't exactly "free" and can slow you down quite a bit as you scale up.

I know you added that line to prove to us that your data was well behaved, I just wanted to show you what to look out for.

Finally, pickle files are notoriously bad in terms of portability. THere is little chance anybody other than yourself, on the exact same python environment, will be able to reopen that pickle file. Try 
https://numpy.org/doc/stable/reference/generated/numpy.save.html

I hope that helps.

**Comment by JamesSample** [comment]
OK, thanks. I wasn't aware of the portability issues with pickle files. I was just looking for a convenient way of sharing a large array without relying on much outside the standard library. It's good to know about `np.save` instead. My data files are actually GeoTiffs, but for simplicity I thought it best to keep the geospatial aspect out of this issue to begin with. For the sake of completeness, [here's](https://drive.google.com/file/d/11pnrLuhr8ePoAxCPY1dD9JsBMXRbrQim/view?usp=sharing) a link to a version created using `np.save`.

I understand the performance issues relating to creating/copying data unnecessarily, and in my code I've tried to avoid it where possible. However, does creating that array of bools in my example above actually make my code more likely to crash? As noted above, I have access to a machine with lots of RAM and I don't mind waiting a while for this to complete, but the kernel seems to die before I see significant memory usage.

I had a go this evening using the latest code from CellProfiler ([here](https://github.com/CellProfiler/centrosome/blob/fdc2aea28811285e01a14f83464b978879f1f5f4/centrosome/_cpmorphology2.pyx#L190)), but the result was the same. I'll keep trying. 

Thanks for the tips!

**Comment by grlee77** [comment]
Based on a quick look, I think it is likely that we can make a modest improvement to the memory requirements without having to modify the Cython code (i.e. possibly around a factor of 2). In particular, an internal `images` variable is currently always allocated in double precision, but this doesn't seem to be necessary in cases where the `seed` or `mask` inputs are lower precision. What is `data.dtype` in your case?

Also, I have not worked with this function much, but did you find it necessary to perform the 
```Python
# Keep perimeter cells equal to the original values and set all other cells to max
seed = data.copy()
seed[1:-1, 1:-1] = data.max()
```
step? It looks like there is already [some internal padding that may take care of this automatically](https://github.com/scikit-image/scikit-image/blob/660899ae7027c68a6aec085794d2a5bcc440fd32/skimage/morphology/grayreconstruct.py#L159-L175). I am just wondering if that is redundant (or perhaps was only required with older versions of scikit-image).

**Comment by grlee77** [comment]
I think the default should remain to automatically handle that boundary, but we could reduce memory usage a bit by skipping the padding if the user passed in a parameter indicating they had already taken care of this and wanted to skip internal boundary handling.

**Comment by grlee77** [comment]
It also looks like we should add a check that `seed.size` <= 2**32 since various indices into the raveled array are in uint32.

**Comment by hmaarrfk** [comment]
> It also looks like we should add a check that seed.size <= 2**32 since various indices into the raveled array are in uint32.

This might be a real bug. we should likely check that the number of pixels is less than that.

The algorithm seems to create 4 of these. So it is likely at least 20GB.

If your images are uint8, then at this line of code
https://github.com/scikit-image/scikit-image/blob/main/skimage/morphology/grayreconstruct.py#L173

You would be creating a 40GB array. not fun.

I would also say that the use of `flatten` is a bug:
https://github.com/scikit-image/scikit-image/blob/main/skimage/morphology/grayreconstruct.py#L188
it is returning a copy of a newly created array.
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html

Again, these kinds of optimization don't matter, until you pass in a 5GB array.

You help tracking these down and making a PR would be helpful, otherwise

**Comment by hmaarrfk** [comment]
I really don't mean to bash the implementation of this algorithm, because actually, it uses numpy tools quite well.

However, in terms of scalability, line of code like this
https://github.com/scikit-image/scikit-image/blob/main/skimage/morphology/grayreconstruct.py#L191
Assuming your images are uint8, then you have 5GPixels
```
    index_sorted = np.argsort(images).astype(np.int32)
```

Would create 40GB temporary array of the sorted argument (`ssize_t = uint64`), then it would convert that array into an array of `uint32`, But this is a copy, so it would indeed be a new 20GB GB array.

So your "small" algorithm has been allocating and deallocating data many times.

What can you do?

If your image is truely 5GPixels, I don't know what you can do "easily" since as @grlee77 pointed you, the cython code uses uint32. You could rewrite the cython code, but that requires you know how to compile cython (not sure about your skill level there)

However, I think that many parts before the cython loop starts can be optimized for large arrays in python.

You could them experiment by
```
from skimage.morphology ._grayreconstruct import reconstruction_loop
```
and optimize the code path before the code calls `reconstruction_loop`:
https://github.com/scikit-image/scikit-image/blob/main/skimage/morphology/grayreconstruct.py#L209

Then you could synthesize your findings in a PR :D

**Comment by JamesSample** [comment]
OK, having spent most of my afternoon going round in circles, I finally realised that non-array 64-bit integers in Cython/C are called `long`. I wish I'd looked this up a few hours ago! Anyway, after changing [these lines](https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/morphology/_grayreconstruct.pyx#L52-L54) from `int` to `long` (and having already changed all the array data types to 64-bit), I think my 64-bit version is now working correctly. I'll do some more testing next week.

I'm not sure how this should look as a PR. My current version converts everything to 64-bit regardless, which is fine if you have lots of memory and know or suspect your datasets are too big for `int32`. However, for the majority of use cases it's just inefficient. Is it possible to setup the correct data types in Cython based on the input data, or do we need two versions of `_grayreconstruct.pyx` (32 and 64 bit) and have `morphology.reconstruction` choose the appropriate one based on the size of the input data... or something else?

**Comment by hmaarrfk** [comment]
You should change the cast to int32 to uint32.

That is a real big. The cython code assumes unsigned int.

Try changing to unsigned and i think it should work.

**Comment by JamesSample** [comment]
I think the Cython code needs changing too, doesn't it?

The arrays `prev` and `next` both contain values up to the maximum rank (`2.6e9` in my example), but in the Python code they're also set to `np.int32` ([here](https://github.com/scikit-image/scikit-image/blob/660899ae7027c68a6aec085794d2a5bcc440fd32/skimage/morphology/grayreconstruct.py#L195-L199)) and in Cython they're defined as `cnp.int32_t` ([here](https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/morphology/_grayreconstruct.pyx#L19-L22)). Similarly, I think some of the Cython variables defined [here](https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/morphology/_grayreconstruct.pyx#L53-L54) as `int` (i.e. 32-bit signed) need to accept values up to the maximum rank.

**Comment by grlee77** [comment]
Yeah, looks like this will need some auditing of the data types. I wouldn't encourage use of `long` as I think it is 32-bit on Windows, but 64-bit on linux/MacOS. 

I think `Py_ssize_t` is generally what is encouraged for indices in Cython code. [See for example here](https://stackoverflow.com/questions/20987390/cython-why-when-is-it-preferable-to-use-py-ssize-t-for-indexing). I think `np.intp_t` is also equivalent to `Py_ssize_t` (We went with `np.int_p` in [scipy.signal.upfirdn](https://github.com/scipy/scipy/blob/main/scipy/signal/_upfirdn_apply.pyx)). The drawback to those is that they will be 64-bit on most systems so memory usage would increase relative to the current choice. However, we could use a smaller type in cases where we know the indices aren't going to exceed a certain range. To support multiple types on the Cython side there is a feature called "fused types" that will generate versions of the function for multiple types. For instance we have some fused types defined [in a shared utilities file](https://github.com/scikit-image/scikit-image/blob/main/skimage/_shared/fused_numerics.pxd#L10). We might want something like that, although potentially only with uint32 and uint64 so we don't bloat the size of the scikit-image binary wheels too much.

**Comment by grlee77** [comment]
@JamesSample I can potentially help take a look as well after Tuesday or so if you run into problems.

**Comment by JamesSample** [comment]
Thanks. I probably won't get chance to look at it again until the middle of next week either. I suspect submitting usable code involving "fused types" etc. may be beyond my Cython skills at present, although I'm keen to learn how all this stuff hangs together.

**Comment by grlee77** [comment]
I think the previous #3857 could also be from the same issue. Let's keep this one open as well, though since we have more concrete discussion of the cause here.
