### ISSUE TITLE
Problem with skimage ??

### ISSUE THREAD

**Issue by Zazz96** [scikit-image/scikit-image#6281]
Help please!!!

I am running the following code:

from skimage import io
my_image = io.imread("Images/image002_ICC")
print(my_image)
and I am getting the following error:

File "S:\GENERAL\Shazeb\Image Analysis\Python\untitled4.py", line 9, in <module>
    my_image = io.imread("Images/image002_ICC")

  File "C:\Users\haa19\Anaconda3\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)

  File "C:\Users\haa19\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)

  File "C:\Users\haa19\Anaconda3\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))

  File "C:\Users\haa19\Anaconda3\lib\site-packages\imageio\core\functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)

  File "C:\Users\haa19\Anaconda3\lib\site-packages\imageio\core\functions.py", line 172, in get_reader
    request = Request(uri, "r" + mode, **kwargs)

  File "C:\Users\haa19\Anaconda3\lib\site-packages\imageio\core\request.py", line 124, in __init__
    self._parse_uri(uri)

  File "C:\Users\haa19\Anaconda3\lib\site-packages\imageio\core\request.py", line 260, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)]([url](url))
I do not understand what is wrong?

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
# your output here

```

**Comment by hmaarrfk** [comment]
Did you resolve your issue?

**Comment by Zazz96** [comment]
@hmaarrfk yes. Thank you very much :) 

But now I have another problem. When I am running the following code: 
```
#Pillow
#pip install pillow

from PIL import Image
import numpy as np


img = Image.open("Images/image002_ICC.TIF")
print(type(img))

#img.show()

#Format of the image
print(img.format)

img1 = np.asarray(img)
print(type(img1))


##############################

#Matplotlib
#Pyplot

#pip install matplotlib

import matplotlib.image as mpimg 
import matplotlib.pyplot as plt

img = mpimg.imread("Images/image002_ICC.TIF")
print(type(img))
print(img.shape)
plt.imshow(img)
plt.colorbar()
```

I am getting notification that Python has stopped working. I cannot able to figure out so far?

**Comment by hmaarrfk** [comment]
its best if you can:
1. Provide all requested information in an issue template. For example we ask that users provide the output of a few commands, that would be extremely helpful in us debugging with you.2
2. The source images that seem to cause the problems.

It is also unclear at what line python stops working. 

I would suggest opening an issue with matplotlib. They will request similar information.

**Comment by Zazz96** [comment]
Sure, Thank you very much!
