### ISSUE TITLE
warp/rotate: inconsistency with clipping when cval is outside of the input range

### ISSUE THREAD

**Issue by ayshih** [scikit-image/scikit-image#6305]
## Description

For warp/rotate, when specifying `clip=True` (which is the default), the behavior when `cval` is outside of the range of the input image depends on the specified interpolation order.  For orders 0, 1, and 3 (which use native code), any pixels in the output image that are `cval` are preserved as `cval`.  For orders 2, 4, and 5 (which fall back to SciPy code), the pixels in the output image that are `cval` invariably get clipped to be within the input range.  This happens because the check in `_clip_warp_output()`:
https://github.com/scikit-image/scikit-image/blob/e562d9f8914c804151b5247bd2e778d53510904f/skimage/transform/_warps.py#L727
is too strict now that the SciPy code is called using the mode `grid-constant` instead of `constant` as of scikit-image 0.19.  That is, values outside of the original image are no longer exactly equal to `cval` because of the way `grid-constant` works.

## Way to reproduce
```python
import matplotlib.pyplot as plt
import numpy as np
from skimage.transform import rotate

image = np.ones((20, 20))
image[5:-5, 5:-5] = 2

fig, axs = plt.subplots(2, 6, figsize=(13, 4))

for i in range(6):
    axs[0, i].set_title(f'order={i}')
    axs[0, i].imshow(rotate(image, 30, order=i, cval=0, resize=True, clip=False), vmin=0, vmax=3)
    axs[1, i].imshow(rotate(image, 30, order=i, cval=0, resize=True, clip=True), vmin=0, vmax=3)
    
axs[0, 0].set_ylabel('clip=False')
axs[1, 0].set_ylabel('clip=True')

plt.show()
```
![download (49)](https://user-images.githubusercontent.com/991759/160432313-b1e9696d-4f1c-451f-84ff-f96f2110df02.png)

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19041-SP0
scikit-image version: 0.19.2
numpy version: 1.20.2
```
And scipy is 1.8.0

**Comment by grlee77** [comment]
Thanks for reporting this @ayshih. Indeed, it looks like we should adjust the clipping range to take `cval` into account when `mode='constant'`. Are you interested in making a PR to fix this?

**Comment by ayshih** [comment]
PR opened.  As I fixed the issue for orders 2, 4, and 5, I realized that orders 1 and 3 were _also_ wrong, just to a less obvious extent.  For those orders, the pixels just outside the boundary of the input image would be interpolated to have values between `cval` and the bounds of the input range, so would fail the same equality check and not be preserved through the clipping.
