### ISSUE TITLE
Euler's elastica inpainting

### ISSUE THREAD

**Issue by tbekolay** [scikit-image/scikit-image#631]
Last year I implemented an inpainting algorithm for an image processing course in Matlab. It takes a while to run, and tuning the parameters for it can be a pain, but the results are not bad for non-textured images; you can see some examples in our [project writeup](https://dl.dropboxusercontent.com/u/6182929/rasmussen-bekolay-elastica-inpainting.pdf). I'm interested in converting the code to Python for inclusion in scikit-image, but I figured I would check to see if there's interest before I convert it and optimize it to be not-too-terribly slow. Is there interest in having inpainting in scikit-image?

**Comment by soupault** [comment]
@tbekolay, hi! Could you share your `MATLAB` implementation of the algorithm?

**Comment by soupault** [comment]
@tbekolay, hi! Would you be so kind to share your MATLAB implementation of the algorithm? I'm interested on porting it to Python.

**Comment by soupault** [comment]
Kind ping @tbekolay

**Comment by tbekolay** [comment]
Apologies for the extreme tardiness! I tracked down the code again and it can be found at https://dl.dropboxusercontent.com/u/6182929/inpainting.zip

The zip contains the original report (linked above but now a 404), Elastica inpainting in Matlab, and TV inpainting in Python. Feel free to adapt it all as you see fit; attribution would be appreciated but not necessary.

**Comment by soupault** [comment]
Thanks a lot! I think, it'd be finally possible to manage this addition. Sadly, my previous efforts to implement the Elastica model weren't successful.
