### ISSUE TITLE
broken CircleCI documentation artifact links

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#6311]
## Description

In a couple of recent PRs (e.g. #6307), the documentation artifact link is broken despite the job being completed successfully. The artifact is still available by following the link to the main CI run and clicking in the artifacts tab. 

The broken link in the PR mentioned above looks like:
https://3711-2014929-gh.circle-artifacts.com/0/doc/build/html/index.html

while the working link found via manual navigation from the Artifacts tab looks like
https://output.circle-artifacts.com/output/job/a8fc78bf-0802-4856-b488-1fe00913a4a3/artifacts/0/doc/build/html/index.html

## Way to reproduce

see CircleCI links in #6307 for an example

**Comment by lagru** [comment]
This seems to work again now/currently ...? See [recent commits](https://github.com/scikit-image/scikit-image/commits/main), e.g. https://github.com/scikit-image/scikit-image/commit/de5f862c65c83b32c2edfc4fa7fa10b9565e47f6.

**Comment by grlee77** [comment]
Closing as this seems to have resolved itself
