### ISSUE TITLE
General help on the usage of restoration.richardson_lucy

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#6331]
### Moved to issue from deleted Discussion in https://github.com/scikit-image/scikit-image/discussions/6198

<div type='discussions-op-text'>

<sup>Originally posted by **Taoboan1999** January 21, 2022</sup>
我希望用restoration.richardson_lucy函数实现“盲反卷积”图像恢复的功能，可是效果并不是很好，核心代码如下：
    for image_name in tqdm(train_images):
        train_image_path = os.path.join(train_images_path, image_name)
        RL_train_image = io.imread(train_image_path)
        RL_train_image = util.img_as_float(RL_train_image)
        psf = np.ones((3, 3)) / 9
        for i in range(RL_train_image.shape[-1]):
            RL_train_image[:, :, i] = convolve2d(RL_train_image[:, :, i], psf, mode="same")
        rng = np.random.default_rng()
        RL_train_image += 0.001 * RL_train_image.std() * rng.standard_normal(RL_train_image.shape)
        fixed = np.zeros(RL_train_image.shape)
        for i in range(RL_train_image.shape[-1]):
            fixed[:, :, i] = restoration.richardson_lucy(RL_train_image[:, :, i], psf, iters)
        fixed = util.img_as_ubyte(fixed)
        io.imsave(fname=os.path.join(RL_train_images_path, image_name), arr=fixed)

请问各位有什么关于richardson_lucy调参的建议吗，或者是其他有关图像修复技术方面的建议
</div>

------

> @mkcor on Jan 21
> @alexdesiqueira is this discussion related to issue https://github.com/scikit-image/scikit-image/issues/6194?

-------

>@alexdesiqueira on Jan 21

> @mkcor yes, @Taoboan1999 would like suggestions to improve their results when using restoration.richardson_lucy slightly_smiling_face
Hey @Taoboan1999, could you provide us a couple of test images? Maybe we could help. slightly_smiling_face Thanks!

> @Taoboan1999 on Jan 21

![00001](https://user-images.githubusercontent.com/61101005/150628824-1ffcb981-b39c-4673-8245-eb2578d7032b.png)
![00002](https://user-images.githubusercontent.com/61101005/150628896-f7b8ae16-15d0-419e-b895-9c1c6c7faf47.png)
![00003](https://user-images.githubusercontent.com/61101005/150628925-b0873bd8-92b5-4565-9b57-fe7ba06f2062.png)
上面这两张是原始图片

通过代码处理，生成图像修复的图片如下所示：
![00001](https://user-images.githubusercontent.com/61101005/150629384-454773c9-bffe-4960-b7ec-9ee5080a8b0e.png)
![00002](https://user-images.githubusercontent.com/61101005/150629394-9e963ecc-47a3-471e-94f9-26ad9977556a.png)
![00003](https://user-images.githubusercontent.com/61101005/150629405-525f3090-1373-4910-8769-b07a41726549.png)

代码参数如下所示：
        train_image_path = os.path.join(train_images_path, image_name)
        RL_train_image = io.imread(train_image_path)
        RL_train_image = util.img_as_float(RL_train_image)
        psf = np.ones((3, 3)) / 9
        for i in range(RL_train_image.shape[-1]):
            RL_train_image[:, :, i] = convolve2d(RL_train_image[:, :, i], psf, mode="same")
        rng = np.random.default_rng()
        RL_train_image += 0.0001 * RL_train_image.std() * rng.standard_normal(RL_train_image.shape)
        fixed = np.zeros(RL_train_image.shape)
        for i in range(RL_train_image.shape[-1]):
            fixed[:, :, i] = restoration.richardson_lucy(RL_train_image[:, :, i], psf, iters)
        fixed = util.img_as_ubyte(fixed)
        io.imsave(fname=os.path.join(RL_train_images_path, image_name), arr=fixed)

我觉得关键在于
psf = np.ones((3, 3)) / 9
RL_train_image += 0.0001 * RL_train_image.std() * rng.standard_normal(RL_train_image.shape)
iters=10
这三个参数配置，请问您有什么建议么，谢谢您

**Comment by alexdesiqueira** [comment]
Closing. Thank you @taoboan1999 @grlee77!
