### ISSUE TITLE
Typo in `_probabilistic_hough_line` docstring

### ISSUE THREAD

**Issue by MSutt** [scikit-image/scikit-image#6338]
Hello,

I think I spotted a small typo in `_probabilistic_hough_line` docstring.
https://github.com/scikit-image/scikit-image/blob/a4681561fa3b4614db1d81a494924a9890c4538b/skimage/transform/_hough_transform.pyx#L362-L364

I think in the lines format, the second coordinate of the second point defining the line should be y1 instead of y0 : 
`((x0, y0), (x1, y1))` instead of `((x0, y0), (x1, y0))`

**Comment by grlee77** [comment]
agreed. Do you want to submit a fix? (no worries if not, we are also happy to take care of it)
