### ISSUE TITLE
Canny outputs border artifacts when image is constant with default parameters

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#6346]
I believe the change occurred in 372b901065d5712237105fb1a70c5c6cde530a15

The resulting behavior is that the canny edge detector now returns edge pixels on the border of any image that does not have a black background.

This is a change in behavior from previous versions of skimage.

**Comment by stefanv** [comment]
```python
import numpy as np
import skimage as ski

x = np.ones((10, 10))
print(ski.feature.canny(x))
```

```
[[False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True False]
 [False  True False False False False False False  True False]
 [False  True False False False False False False  True False]
 [False  True False False False False False False  True False]
 [False  True False False False False False False  True False]
 [False  True False False False False False False  True False]
 [False  True False False False False False False  True False]
 [False  True  True  True  True  True  True  True  True False]
 [False False False False False False False False False False]]

```

**Comment by grlee77** [comment]
I think this should just be `mode='nearest'`.  Definitely agree that constant does not seem desirable for this function.

**Comment by rfezzani** [comment]
> I believe the change occurred in [372b901](https://github.com/scikit-image/scikit-image/commit/372b901065d5712237105fb1a70c5c6cde530a15)

For clarification, `constant` was already the default mode before this commit. This commit simply exposes `mode` and `cval` in `canny` API. `constant` mode was kept for backward compatibility.
@stefanv, is this a behaviour change or a bug?

**Comment by stefanv** [comment]
I know the behavior changed, because a tutorial I had written the year before suddenly started malfunctioning, detecting edges on the border.

**Comment by rfezzani** [comment]
> I believe the change occurred in https://github.com/scikit-image/scikit-image/commit/372b901065d5712237105fb1a70c5c6cde530a15

@stefanv, you spotted the right commit. I will investigate :wink:

**Comment by rfezzani** [comment]
More precisely, here is the exact commit https://github.com/scikit-image/scikit-image/pull/4342/commits/4c60efe2d3932c758a4f86e3247b0ae5bd3c2a2a introducing the change!
I will fix this and add a UT :wink:
