### ISSUE TITLE
SegFault in test_simpleitk

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#6349]
## Description

This causes CI failures in `linux-cp3.8-mini-req-optional-deps` and `linux-cp3.9-optional-deps`.
Please see https://github.com/scikit-image/scikit-image/runs/6091707280?check_suite_focus=true and https://github.com/scikit-image/scikit-image/runs/6091707434?check_suite_focus=true for example.

**Comment by grlee77** [comment]
I can reproduce locally when using simpleitk 2.1.1.2 from pip (released on April 18). With conda, the most recent is 2.1.0 and I do not see the issue there.

**Comment by grlee77** [comment]
I opened SimpleITK/SimpleITK/issues/1631. The immediate workaround here will be to block this specific release in our requirements file.

**Comment by grlee77** [comment]
This has resolved itself since the SimpleITK team removed the problematic wheels. The bug that lead to the failures has already been resolved for the upcoming 2.2 release.
