### ISSUE TITLE
AttributeError: module 'skimage.feature' has no attribute 'multiscale_basic_features'

### ISSUE THREAD

**Issue by protist33** [scikit-image/scikit-image#6350]
Hello. I simple tried to repit one example frome the gallery
https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_trainable_segmentation.html#sphx-glr-auto-examples-segmentation-plot-trainable-segmentation-py

I have scimage, installed by conda on Windows 10, and have  the Attribute Error
AttributeError: module 'skimage.feature' has no attribute 'multiscale_basic_features'

[features_func](https://docs.python.org/3.8/library/functools.html#functools.partial) = [partial](https://docs.python.org/3.8/library/functools.html#functools.partial)([feature.multiscale_basic_features](https://scikit-image.org/docs/stable/api/skimage.feature.html#skimage.feature.multiscale_basic_features),
                        intensity=True, edges=False, texture=True,
                        [sigma_min](https://docs.python.org/3.8/library/functions.html#int)=[sigma_min](https://docs.python.org/3.8/library/functions.html#int), [sigma_max](https://docs.python.org/3.8/library/functions.html#int)=[sigma_max](https://docs.python.org/3.8/library/functions.html#int),
                        channel_axis=-1)

**Comment by hmaarrfk** [comment]
Thank you for reaching out. 

There is alot of information we ask for when you create an issue. Please take the time to provide it.

![image](https://user-images.githubusercontent.com/90008/164508913-54977f52-2bf7-4e74-ab1e-81a1e25a7e15.png)


Without out, we would simply be guessing and you would not get your issue resolved.

You've also reduced the stack trace. The full stack trace is often helpful for us to debug.

**Comment by jni** [comment]
Answered in [StackOverflow](https://stackoverflow.com/questions/71953621/attributeerror-module-skimage-feature-has-no-attribute-multiscale-basic-feat/71962218#71962218)
