### ISSUE TITLE
`imsave` has incorrect type in docstring

### ISSUE THREAD

**Issue by johnthagen** [scikit-image/scikit-image#6360]
## Description

The docstring for `skimage.io.imsave` is incorrect:

https://github.com/scikit-image/scikit-image/blob/376d30f5ba83e98d2745622d9d4951914e0c91f7/skimage/io/_io.py#L106

The actual implementation accepts `str | Path`

https://github.com/scikit-image/scikit-image/blob/376d30f5ba83e98d2745622d9d4951914e0c91f7/skimage/io/_io.py#L131-L132

IDEs such as PyCharm read the docstring and provide a warning when passing in a `Path`, even though this is valid.

The problem as a whole would probably be better solved by moving this information into true type annotations:
- #3153

**Comment by hmaarrfk** [comment]
Thank you for this. I think helping IDEs is an important consideration (there are other considerations of course!)

I think you can change the docstring to `path-like` or something similar. I would support a PR doing this.

You can try by simply editing the source and changin it to `Pathlike` and seeing if the complaints go away. Then you can make a easy PR to scikit-image.
