### ISSUE TITLE
EuclideanTransform and SimilarityTransform does not give correct properties for dimensionality=3

### ISSUE THREAD

**Issue by sandeepnmenon** [scikit-image/scikit-image#6365]
## Description
EuclideanTransform and SimilarityTransform does not give correct properties for dimensionality=3.

This is because the rotation, translaton and scale properties only take care of dimensionality=2
Rotation and translation
https://github.com/scikit-image/scikit-image/blob/30a426cc7f63be50e60faf682c0ac48231a328f0/skimage/transform/_geometric.py#L1250-L1256

Scale
https://github.com/scikit-image/scikit-image/blob/30a426cc7f63be50e60faf682c0ac48231a328f0/skimage/transform/_geometric.py#L1367-L1370

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
from skimage.transform import warp, SimilarityTransform
import math

src_points = np.array([[1,0,0], [2,0,0], [3,0,0]])
dst_points = np.array([[4,1,1], [7,1,1], [10,1,1]]) # scale = 3, rotation = 0, tx = 1, ty = 1, tz = 1

model = SimilarityTransform(dimensionality=3)
model.estimate(src_points, dst_points)

print(model.scale, model.rotation, model.translation)
# 5.196152422706632 0.0 [0. 0.]

print(model.params)
# [[3. 0. 0. 1.]
#  [0. 3. 0. 1.]
#  [0. 0. 3. 1.]
#  [0. 0. 0. 1.]]

# upload all necessary images to github too!
```

Model output should be 
scale = 3
rotation = [0.0, 0.0, 0.0]
transation = [1, 1, 1]

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
# your output here
3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0]
Linux-5.4.0-107-generic-x86_64-with-glibc2.10
scikit-image version: 0.19.0
numpy version: 1.22.2
```

**Comment by sandeepnmenon** [comment]
Fix would be to use the dimensionality param as a check in the properties like in the __init__ function for the two models.
I can raise PR with the fix

**Comment by sandeepnmenon** [comment]
Decomposing rotation would fail when the points are colinear. When I tested the code with random points the `transformation matrix[:3,:3]` gives the rotation and we can get the euler angles from it.
Am I missing something?

**Comment by jni** [comment]
No no, you're not, I am just not well versed in the maths for decomposing scale, rotation, and skew from the 3D matrix! :sweat_smile: When I searched for it ages ago I must have been missing the right search terms.

**Comment by sandeepnmenon** [comment]
@jni Raised PR #6367 
Kindly review.
