### ISSUE TITLE
A question about the source code of the skimage.measure.LineModeND.estimate

### ISSUE THREAD

**Issue by Esperer105** [scikit-image/scikit-image#6370]
## the official source code of the skimage.measure.LineModelND.estimate
```python
 def estimate(self, data):
        """Estimate line model from data.
        This minimizes the sum of shortest (orthogonal) distances
        from the given data points to the estimated line.
        Parameters
        ----------
        data : (N, dim) array
            N points in a space of dimensionality dim >= 2.
        Returns
        -------
        success : bool
            True, if model estimation succeeds.
        """
        _check_data_atleast_2D(data)

        origin = data.mean(axis=0)
        data = data - origin

        if data.shape[0] == 2:  # well determined
            direction = data[1] - data[0]
            norm = np.linalg.norm(direction)
            if norm != 0:  # this should not happen to be norm 0
                direction /= norm
        elif data.shape[0] > 2:  # over-determined
            # Note: with full_matrices=1 Python dies with joblib parallel_for.
            _, _, v = np.linalg.svd(data, full_matrices=False)
            direction = v[0]
        else:  # under-determined
            raise ValueError('At least 2 input points needed.')

        self.params = (origin, direction)

        return True
```

## where I am confused 
```python
_, _, v = np.linalg.svd(data, full_matrices=False)
            direction = v[0]
```
## the description of the problem
From the document I notice that we use the estimator that  minimizes the orthogonal distances of points to the estimated line, that is, we use the total least square method to fit a line. And I tried to deduce the **direction**, and I found that **direction** should be the  eigenvector corresponding to the smallest eigenvalue in orthogonal matrix **v**. As we know, the eigenvectors in orthogonal matrix **v**  are arranged from largest to smallest, so I think the code should be as follows:
```python
direction=v[-1] 
```
Do I misunderstand something? Could you please offer me further explanation? Thank you !

**Comment by jni** [comment]
I don't know the answer here off the top of my head but maybe @stefanv or @grlee77 do...

**Comment by Esperer105** [comment]
@jni Thank you for your response! I have figured out the problem!

**Comment by stefanv** [comment]
Just so we understand, can you post your insight here?

**Comment by Esperer105** [comment]
@stefanv Sure! The source code is right ! I 'll post the proof in a few days.
