### ISSUE TITLE
Docs for skimage graycomatrix are outdated and not matching the implementation

### ISSUE THREAD

**Issue by jankaWIS** [scikit-image/scikit-image#6390]
## Description
As mentioned in this [stack question](https://stackoverflow.com/questions/67537650/cannot-import-name-graycomatrix-from-skimage-feature/67546660#67546660), the [documentation about GLCM](https://scikit-image.org/docs/dev/auto_examples/features_detection/plot_glcm.html) shows an example on how to use it with this line of code:

## Way to reproduce
```python
from skimage.feature import graycomatrix, graycoprops
```
which yields an error:
```python
ImportError: cannot import name 'graycomatrix' from 'skimage.feature' 
```
Launching it on binder works. The function linked from the example ([github](https://github.com/scikit-image/scikit-image/blob/main/skimage/feature/texture.py#L15-L156) and [docs](https://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.graycomatrix)) both say it with `gray` so I guess there has been some silent update. Could that be fixed/unified?

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
3.8.11 (default, Aug  6 2021, 08:56:27) 
[Clang 10.0.0 ]
macOS-10.16-x86_64-i386-64bit
scikit-image version: 0.18.1
numpy version: 1.22.3
```

**Comment by lagru** [comment]
Hey @jankaWIS, thank you for reaching out and sorry for the late reply. 

The function was renamed to `graycomatrix` in #5385 in order to reduce the confusion between `grey` and `gray` (the latter is prefered now). Your version information indicates that you are using scikit-image 0.18.1 which is before this patch was applied. 

> Could that be fixed/unified?

What would you like to be fixed or unified? If you want to import the function prior to version 0.19, you'll need to use `greycomatrix`. From 0.19 onwards this feature is deprecated but still "available" till version 1.0.

**Comment by jankaWIS** [comment]
Hi @lagru, thanks for coming back to me. I think that the main reason for raising this issue was the confusion I had. Even now when I started answering I misunderstood how it works. Maybe some red box in docs that for earlier versions it was `grey`? Just to prevent future confusion :).
Thanks

**Comment by alexdesiqueira** [comment]
> Maybe some red box in docs that for earlier versions it was grey? Just to prevent future confusion :).

@jankaWIS that's a great idea! Would you like to open a PR, adding the information that @lagru described? As in,

> If you would like to import the function prior to version 0.19, you need to use `greycomatrix`. From 0.19 onwards, this feature is deprecated.

We can help you in the process.
Thanks again!

**Comment by lagru** [comment]
Yes, I think the docstring would be an obvious place to do so. You could add something like 
```
.. versionchanged:: 0.19
           `greymatrix` was renamed to `graymatrix` in 0.19.
```
just before the the [Parameters section](https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/feature/texture.py#L22). The same would be very useful as well for the `greycoprops` function. :)
