### ISSUE TITLE
"Installing scikit-image > Build environment setup" instructions won't work for `conda`

### ISSUE THREAD

**Issue by alexdesiqueira** [scikit-image/scikit-image#6392]
## Description

```
Looking for: ['asv', 'codecov', 'flake8', "matplotlib[version='>=3.3']", "pooch[version='>=1.3.0']",
              "pytest[version='>=5.2.0']", "pytest-cov[version='>=2.7.0']", 'pytest-localserver',
              'pytest-faulthandler']

pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - nothing provides requested asv
  - nothing provides requested pytest-faulthandler
```

## Way to reproduce

Follow instructions on [Installing scikit-image > Build environment setup > conda](https://scikit-image.org/docs/stable/install.html#id6).
More specifically,

```sh
$ mamba install --file requirements/test.txt
```

**Comment by alexdesiqueira** [comment]
To fix, we need to add the `conda-forge` repository:
```
mamba install -c conda-forge --file requirements/test.txt
```

**Comment by alexdesiqueira** [comment]
Got it. Thanks for letting us know, @hmaarrfk!

**Comment by hmaarrfk** [comment]
In my experience, adding `-c conda-forge` does hurt more than things just failing. Users get packages from mixed channels they don't understand.

And then, things really start to break.

While conda-forge "used" to track defaults and be rather compatible, the scope of conda-forge really expanded which means that conda-forge no longer plays nicely with defaults.

Others at conda-forge might disagree, but I think that the instructions that conda-forge provides are also less than ideal. We had an issue in https://github.com/conda-forge/miniforge/issues that we somewhat tracked that request.

We somewhat dismissed a while back, but I'm happy to reconsider it. Maybe we can provide an option to override the user's existing channels?

**Comment by hmaarrfk** [comment]
I think improvements on the instructions are welcome, but in reality conda-forge moves quickly, is cross platform, and has many of its own caveats.

When you click on the link we provide, on the first screen (you may have to scroll a tiny bit)
![image](https://user-images.githubusercontent.com/90008/171523512-c1e9c766-170d-4661-a7e4-4a39c812002a.png)
conda-forge provides you with two options to install it.

I am not enthusiastic about copying them, but if you can improve the current state, then that would definitely be welcome!

**Comment by alexdesiqueira** [comment]
TBH I don't feel strongly about any of the alternatives. Let's keep it as is, then.
