### ISSUE TITLE
Add alpha parameter to adapted_rand_error()

### ISSUE THREAD

**Issue by lucas-johnson** [scikit-image/scikit-image#6433]
## Description
Thanks for a great package! I'm wondering if you'd be open to adding an alpha parameter to the `adapted_rand_error()` function, to better align with the description in the [SNEMI3D contest paper](https://www.frontiersin.org/articles/10.3389/fnana.2015.00142/full) as follows:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/10555272/177831890-03f5437a-69ad-42cc-8ae8-068da10a7abe.png">

This would allow for weighting precision and recall errors differently, rather than equally. I'd be happy to open a PR adding this change if that would be helpful.

## Version information
```python
# Paste the output of the following python commands
3.9.6 (default, Jun 29 2021, 06:20:32) 
[Clang 12.0.0 (clang-1200.0.32.29)]
macOS-10.15.7-x86_64-i386-64bit
scikit-image version: 0.19.3
numpy version: 1.22.4
```

**Comment by grlee77** [comment]
It seems okay to me, if you can also update the docstring to reference the alternative form used when `alpha` is provided (assuming that variant is not already discussed in the referenced publication).

In the function signature, the default value will need to match the current behavior for backwards compatiblity.

**Comment by jni** [comment]
I'm 👍 on this also, thanks for the proposal @lucas-johnson and yes, a PR would be great! 🙏
