### ISSUE TITLE
Links no. 4 and 7 in SKIP 3 need to be replaced  

### ISSUE THREAD

**Issue by judafe** [scikit-image/scikit-image#6444]
## Description

References no. 4 and 7 in SKIP 3 links to a no-longer existing discussion page. The link needs to be changed to a corresponding issue page.

## Fix
Link no. 4 references a SciPy release document. 
* Current broken link: https://docs.scipy.org/doc/scipy/reference/release.1.0.0.html
* New link: https://docs.scipy.org/doc/scipy/release.1.0.0.html

Link no. 7 references a Scikit Image discussion.
* Current broken link: https://github.com/scikit-image/scikit-image/discussions/5651\
* New link: https://github.com/scikit-image/scikit-image/issues/5439

**Comment by grlee77** [comment]
closed by #6445
