### ISSUE TITLE
Alert users when insufficient inliers are detected in ransac

### ISSUE THREAD

**Issue by judafe** [scikit-image/scikit-image#6449]
##  Description

[```ransac```](https://scikit-image.org/docs/stable/api/skimage.measure.html?highlight=ransac#skimage.measure.ransac) with ```model_class=LineModelND``` will not detect a sufficient number of inliers if the ```min_samples``` input is too large and/or the ```residual_threshold``` is too low.  In these cases, the  function returns the following value error.

```
ValueError: At least 2 input points needed
```

The error message is accurate but a little misleading.  **Users might benefit if they are explicitly notified that the algorithm failed because an insufficient number of inliers were detected given their ```min_samples``` and/or ```residual_threshold``` specifications.**

~~**I propose to modify the logic within the ```ransac``` function so as to produce a ValueError whenever an insufficient number of inliers were detected.**  However, I think it's important to first hear from scikit-image users and developers that often work with the ```ransac``` function. Is this proposal a good idea? Do you have any suggestions?~~

```LineModelND``` is the only model that raises a ValueError when the number of input points is under-determined, although ```CircleModel``` is scheduled to produce a ValueError in version>=1.0. All other models, including those in the ```transform``` module, make an effort to perform an estimation, even if under-determined, and return False if they fail.  

## Proposed solution
1. Make ```LineModelND``` consistent with the other models. Have it return "False" whenever only one point is provided. 
2. Do not change ```CircleModel``` to produce ValueError, as scheduled.
3. Modify tests in [test_fit.py](https://github.com/scikit-image/scikit-image/blob/main/skimage/measure/tests/test_fit.py) that check for corresponding ValueError

## Way to reproduce
A [question on StackOverflow](https://stackoverflow.com/questions/73028649/skimage-ransacregressor-at-least-2-input-points-needed/) led me to submit this issue. Their reproducible code snippet is copied and pasted here: 

```python
from skimage.measure import LineModelND, ransac
import numpy as np

pts = np.array([[579,298],
 [604,276],
 [354,241],
 [156,240],
 [124,157],
 [625,105]])

model, inliers = ransac(pts, LineModelND, min_samples=4,residual_threshold=2, max_trials=1000)
```

## Edits
7/24: 
* Specify that behavior occurs when ```LineModelND``` is used.
* Emphasize some important points.
* Note differences between LineModelND and other models deployable in ```ransac```

## Version information
This is the version information from my machine...
```
4.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:42:03) [Clang 12.0.1 ]
macOS-12.4-arm64-arm-64bit
scikit-image version: 0.19.2
numpy version: 1.22.4
```

**Comment by mkcor** [comment]
Dear @judafe,

> `CircleModel` is scheduled to produce a ValueError in version>=1.0.

Can you please point me to a reference where this is stated? Thanks!

**Comment by judafe** [comment]
@mkcor line 295 of skimage/measure/fit.py

```python
if rank != 3:
    warn("Input data does not contain enough significant data points. "
              "In scikit-image 1.0, this warning will become a ValueError.")
```

**Comment by judafe** [comment]
Issue #6452 and the corresponding PR supplanted this issue. I am closing it.
