### ISSUE TITLE
api_changes.md not updated since 0.16

### ISSUE THREAD

**Issue by moi90** [scikit-image/scikit-image#6450]
## Description

[API Changes](https://scikit-image.org/docs/0.19.x/api_changes.html) has not been updated since 0.16, although notable changes took place.

**Comment by mkcor** [comment]
Hmm, the [source file](https://github.com/scikit-image/scikit-image/blob/main/doc/source/api_changes.md) hasn't been edited in two years indeed... and it's not entirely clear to me that each version entry would be a summary of the more detailed "API Changes" section for each minor version release (release notes found at: https://github.com/scikit-image/scikit-image/tree/main/doc/release).

**Comment by moi90** [comment]
It seems that the release notes should be the single source of truth. The are already linked on the docs main page, but I overlooked them, because of the prominent "API Reference ([**changes**](https://scikit-image.org/docs/0.19.x/api_changes.html))" link.

If `api_changes` is not updated anymore, it should be dropped, I think.

**Comment by mkcor** [comment]
@moi90 you are right. Would you be able to submit a PR removing `api_changes.md` and all references to it (seeing references to `api_changes.txt` as well, although this file doesn't exist)? Thanks anyway!

**Comment by moi90** [comment]
`CONTRIBUTING.rst` and `TODO.txt` currently reference api_changes.

> If your change introduces any API modifications, please update `doc/source/api_changes.txt`.

What is the current appropriate place? `doc/release/release_dev.rst`?

Although I can create a pull request with search&replace, I think the @scikit-image/core developers should define and phrase a proper policy.
