### ISSUE TITLE
Return False from LineModelND and CircleModel when inputs are underdetermined 

### ISSUE THREAD

**Issue by judafe** [scikit-image/scikit-image#6452]
### Proposed Changes
1. Replace the [ValueError](https://github.com/scikit-image/scikit-image/blob/38b595d60befe3a0b4c0742995b9737200a079c6/skimage/measure/fit.py#L94) in ```LineModelND.estimate()``` with ```return False```
2. Modify the [corresponding tests](https://github.com/scikit-image/scikit-image/blob/main/skimage/measure/tests/test_fit.py#L25) to assert a ```False``` return, instead of checking for a ValueError
3. Add a ```return False``` to ```CircleModel.estimate()``` after the warning under the [if-statement](https://github.com/scikit-image/scikit-image/blob/38b595d60befe3a0b4c0742995b9737200a079c6/skimage/measure/fit.py#L295) that checks for collinearity.
4. Remove the second statement in the above mentioned warning, which states, "In scikit-image 1.0, this warning will become a ValueError."

### Justification: Make classes more consistent with analogs
[```LineModelND```](https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.LineModelND) raises a ValueError when the input data are under-determined. Similarly, [```CircleModel```](https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.CircleModel) is scheduled to raise a ValueError when the input data are collinear. 

```LineModelND``` and ```CircleModel``` are part of a wider set of classes that include an ```estimate``` method for fitting points to a model and may be applied in algorithms such as [```ransac```](https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.ransac). Examples include the transforms in [```_geometric.py```](https://github.com/scikit-image/scikit-image/blob/main/skimage/transform/_geometric.py) and ```EllipseModel()``` in [```fit.py```](https://github.com/scikit-image/scikit-image/blob/main/skimage/measure/fit.py). **None of analogous other classes raise a ValueError when the inputs are underdetermined but instead return False.** 

```LineModelND``` and ```CircleModel``` will be more consistent with their analogs if they do not raise ValueErrors when the input data are underdetermined.

## Way to reproduce

Not applicable.

## Version information
Not sure if applicable, but...
```python
# Paste the output of the following python commands
3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ]
macOS-12.4-arm64-arm-64bit
scikit-image version: 0.19.3
numpy version: 1.23.1
```

**Comment by alexdesiqueira** [comment]
Thank you for investigating, @judafe! I like your solution — @scikit-image/core please check this and #6453, and let me know what you think — also, if we need deprecations here.

**Comment by rfezzani** [comment]
Thank you @judafe, I :+1: your solution :wink:
@alexdesiqueira, I assume that deprecation is necessary if we don't want to breaking users existing code, but we need to address #6448 before...
