### ISSUE TITLE
Address new matplotlib >= 3.5 dependency in skimage.future.graph.rag.show_rag

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6486]
## Description

With #6483, `skimage.future.graph.rag.show_rag` now requires matplotlib >= 3.5 which trips up our CI when matplotlib 3.4 or earlier are used. We can either (a) bump our matplotlib for the whole package (currently >=3.3) or (b) we configure our test suite to ignore it "for now". I'm voting for the first (a).

## Way to reproduce

Run doctests with matplotlib < 3.5.

**Comment by jarrodmillman** [comment]
+1 for (a) bump our matplotlib for the whole package
