### ISSUE TITLE
Isotropic versions of binary_dilation and binary_erosion

### ISSUE THREAD

**Issue by moi90** [scikit-image/scikit-image#6491]
## Description

This is a feature request for isotropic implementations of morphological operators.

`binary_dilation` and `binary_erosion` are slow when used with large structuring elements. In the case of a circular structuring element, they [can be implemented using the distance transform](https://blogs.mathworks.com/steve/2010/08/16/isotropic-dilation-using-the-distance-transform/), with a significant performance advantage.

See https://gist.github.com/moi90/28539fa82e55399a254d8e6938eefe56 for a demonstration.

**Comment by alexdesiqueira** [comment]
Thank you for suggesting, @moi90!
@scikit-image/core for context: the paper @moi90 implements in #6492 is [Cuisenaire & Macq (1999)](https://ieeexplore.ieee.org/document/791184). Please let us know your opinions on this.
Thanks again!

**Comment by mkcor** [comment]
In theory, why not adding these binary morphological operators which perform faster for large circular footprints, but the functions are such thin wrappers around ndimage's (and/or cuCIM's?) [distance_transform_edt](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html) that... I find it embarrassing to have such long (and repeated) docstrings (for little original code)... plus, the docstrings don't even mention ndimage (cf. issue description, ["Also, ..."](https://github.com/scikit-image/scikit-image/issues/2597#issue-220288822)). :thinking: 

I would prefer updating the docstrings for (current) `dilation`, `erosion`, ... with a note such as: "If you are using large circular structuring elements, you may be interested in running ``ndi.distance_transform_edt`` on your image."

**Comment by moi90** [comment]
I agree for the docstring part. I could try to reduce them to a minimum. (Currently, I reproduce most of what is in `binary_*`.) And I will include a reference to `distance_transform_edt`.

But I nevertheless think, that this would be a valuable addition.

First, it is cumbersome to implement something based on `distance_transform_edt` again and again. (Initially, I was thinking of releasing the functionality as an individual package on PyPI to circumvent this, but then: Why not in skimage?)

Second, it is error-prone (because you have to get ~, <= and > right; For my part, I would have to do trial and error every time). The implementation in my pull request, on the other hand, is tested for full compatibility with the `binary_*` implementations.

Third, the isotropic implementation enables easy handling of non-uniform pixel spacing with float values. (One could also use `binary_*` an `ellipse` selem, but that does not handle floats and is also not exact (`disk(6)!=ellipse(6,6)`).

**Comment by moi90** [comment]
> Can you please point me to the parts where the " ~, <= and >" are specified / figured out?

In `isotropic_[erosion|dilation]`, `dist` is either `ndi.distance_transform_edt(image)` or `ndi.distance_transform_edt(image == 0)` and we have to use either `np.greater` or `np.less_equal`. For me, that would be too much to remember :)

> This could either be a new example or an addition to an existing example, in order to specifying that, alternatively, isotropic_* may be used.

I will look into that.

**Comment by moi90** [comment]
Currently, there are no examples specifically targeting morphological operators. They are just used where applicable (doc/examples/segmentation/plot_fluorescence_nuclear_envelope.py, doc/examples/segmentation/plot_inpaint.py, doc/examples/segmentation/plot_floodfill.py).
I don't think it makes sense to include a isotropic alternative there.

Writing a new full example for morphological operators in general is a whole new project. I will happily provide isotropic examples once something exists, but doing everything from scratch would take too much of my time.

**Comment by rfezzani** [comment]
> I would prefer updating the docstrings for (current) `dilation`, `erosion`, ... with a note such as: "If you are using large circular structuring elements, you may be interested in running `ndi.distance_transform_edt` on your image."

Why not adding a **See also** section in `binary_*` docstrings referencing the corresponding `isotropic_*` functions?
