### ISSUE TITLE
Sato filter memory usage with multiple sigmas

### ISSUE THREAD

**Issue by tkumpumaki** [scikit-image/scikit-image#6507]
## Description

Sato filter and other ridge filters in _ridges.py_ have quite large unnecessary memory usage if called with multiple sigma values. It is basically allocating for all results, storing results and then taking maximum, while it is possible to just take max after each sigma.

Original code:
```python
    # Generate empty (n+1)D arrays for storing auxiliary images filtered
    # at different (sigma) scales
    filtered_array = np.zeros(sigmas.shape + image.shape, dtype=float_dtype)

    # Filtering for all (sigma) scales
    for i, sigma in enumerate(sigmas):

        # Calculate (sorted) eigenvalues
        lamba1, *lambdas = compute_hessian_eigenvalues(image, sigma,
                                                       sorting='val',
                                                       mode=mode, cval=cval)

        # Compute tubeness, see  equation (9) in reference [1]_.
        # np.abs(lambda2) in 2D, np.sqrt(np.abs(lambda2 * lambda3)) in 3D
        filtered = np.abs(np.multiply.reduce(lambdas)) ** (1/len(lambdas))

        # Remove background and store results in (n+1)D matrices
        filtered_array[i] = np.where(lambdas[-1] > 0, filtered, 0)

    # Return for every pixel the maximum value over all (sigma) scales
    return np.max(filtered_array, axis=0)
```

Modified code:
```python
    # Generate empty (n+1)D arrays for storing auxiliary images filtered
    # at different (sigma) scales
    filtered_array = np.zeros(image.shape, dtype=float_dtype)

    # Filtering for all (sigma) scales
    for i, sigma in enumerate(sigmas):

        # Calculate (sorted) eigenvalues
        lamba1, *lambdas = compute_hessian_eigenvalues(image, sigma,
                                                       sorting='val',
                                                       mode=mode, cval=cval)

        # Compute tubeness, see  equation (9) in reference [1]_.
        # np.abs(lambda2) in 2D, np.sqrt(np.abs(lambda2 * lambda3)) in 3D
        filtered = np.abs(np.multiply.reduce(lambdas)) ** (1/len(lambdas))

        # Remove background and store results in (n+1)D matrices
        filtered = np.where(lambdas[-1] > 0, filtered, 0)
        filtered_array = np.maximum(filtered_array,filtered)

    # Return for every pixel the maximum value over all (sigma) scales
    return filtered_array
```

## Way to reproduce
Call sato filter with huge image and multiple sigmas and observe memory use.

## Version information
`
3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19043-SP0
scikit-image version: 0.19.2
numpy version: 1.21.5
`

**Comment by lagru** [comment]
@tkumpumaki, thanks for the report. It looks like you already figured out a solution? Would you be up for a pull request with your suggested performance improvement? :slightly_smiling_face: In that case have a look have a look at our [contribution guide](https://scikit-image.org/docs/stable/contribute.html) and feel free to ask and ping me!

**Comment by tkumpumaki** [comment]
Sure, have to take a look on other filters if solution works in them too so that implementations would be consistent and do some tests.

**Comment by mkcor** [comment]
@tkumpumaki don't hesitate to submit a (small) PR for a single function. "Many small PRs get in faster than a single larger one." (cf. https://github.com/scikit-image/scikit-image/issues/1185#issuecomment-522335391)
