### ISSUE TITLE
Status of nightly wheels

### ISSUE THREAD

**Issue by bsipocz** [scikit-image/scikit-image#6514]
I'm in the process of moving the CI of a few projects to use nightly wheel builds whenever available for testing with the development version of dependencies.

During this, I run into the issue, that while scikit-image seems to be opted in the `scipy-wheels-nightly` "project", the last wheel made available there is very much outdated. Is there maybe another location for the wheels or they are not being built routinely atm? I'm browsed through the GH issues but haven't found anything relevant about this.

**Comment by lagru** [comment]
I'm not sure either. Pinging @scikit-image/core for feedback on this.

**Comment by mkcor** [comment]
In my understanding, wheels are being built only upon releases -- not routinely indeed, @bsipocz. Pinging @grlee77 for confirmation.

**Comment by grlee77** [comment]
Yes, we don't build nightly or weekly wheels at the moment.

I had used that `scipy-wheels-nightly` project briefly when we were still using a separate repository and `multibuild` for our wheel builds, but don't think we were ever actually doing it nightly. As far as I know, we haven't used it since we switched over to GitHub Actions and `cibuildwheel`.

**Comment by grlee77** [comment]
For new minor version releases, our current strategy has been to upload release candidate wheels to PyPI itself and users can test with them by pip installing using the `--pre` option. For example, here are the ones from `0.19.0rc0` (https://pypi.org/project/scikit-image/0.19.0rc0/). We have not done these pre-releases for the 0.19.1-0.19.3 patch releases, but I think we would for 0.20.0. 

Does that seem sufficient for your use case?

**Comment by bsipocz** [comment]
Thanks for the summary.  I feel it's still good practice to encourage downstream users to include dev testing in their CI, that would mean a faster feedback cycle and potential issues to be discovered before they end up in an RC. 

For us there wasn't really a bug or sudden API change that triggered this issue, we just simply have that dev version testing job (mostly to keep an eye on the most used upstream libraries). And if you would have had a nightly wheel (which doesn't necessarily need to be nightly, but a weekly or so) it would have made sense for us to switch to using it.

**Comment by pllim** [comment]
I just stumbled upon this. I saw https://pypi.anaconda.org/scipy-wheels-nightly/simple/scikit-image/ and thought I would get nightly wheel from there but then I noticed the version wasn't dev in the log.

**Comment by bsipocz** [comment]
I'm reopening this as try to make sure all core scientific-python libraries are producing and distributing nightlies.

**Comment by bsipocz** [comment]
Nightly wheels are now building, so I'm closing this issue. Thank you so much for making them happen!
