### ISSUE TITLE
Python 3.11 wheels

### ISSUE THREAD

**Issue by EpicWink** [scikit-image/scikit-image#6517]
Build wheels for Python 3.11

Should be just adding `cibw_python: "cp311-*"` to the build-wheels CI job matrix

Note you'll likely be waiting for the Python 3.11 wheels for:
* scipy: scipy/scipy#16851
* astropy: astropy/astropy#13671
* imread: luispedro/imread#41
* matplotlib: matplotlib/matplotlib#23637
* pywavelets: PyWavelets/pywt#649

**Comment by skshetry** [comment]
> * imread: https://github.com/luispedro/imread/issues?q=3.11 (via [Add cp311-cp311 to defaults RalfG/python-wheels-manylinux-build#54](https://github.com/RalfG/python-wheels-manylinux-build/pull/54))

You can add `cp311-cp311` to the `python-versions`, that PR only changes the default. However, you may need to update the version of `RalfG/python-wheels-manylinux-build` to the latest.
See [dulwich/pythonwheels.yml](https://github.com/jelmer/dulwich/blob/4a8381ffb284e626605eefe7664e796823b159e2/.github/workflows/pythonwheels.yml#L55-L58) for an example.

**Comment by grlee77** [comment]
Thanks, I was planning to open a PR soon, porting the same changes I did for `PyWavelets` here. Aside from the small .yaml file updates, we have to update the NumPy version pinnings in our `pyproject.toml` to be consistent with current Values in SciPy/PyWavelets (where they were recently updated to account for Python 3.11).

I will tag the new PyWavelets release tonight or tomorrow.

For SciPy we definitely won't want it to build from source, but it looks like we can start testing from the nightly 3.11 wheels [here](https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/).

**Comment by lagru** [comment]
See #6519 for progress on this.

**Comment by papr** [comment]
Scipy has released [3.11 wheels in their latest release](https://pypi.org/project/scipy/1.9.2/#files).

**Comment by stefanv** [comment]
In progress: https://github.com/scikit-image/scikit-image/pull/6566
After this, we'll enable wheels.

**Comment by lagru** [comment]
Reopening so that we have an issue tracking this request. See #6581 for the second step of the progress.

**Comment by Erotemic** [comment]
Any updates on this? It seems like all that's left to do is make the release.

**Comment by stefanv** [comment]
Yes, @grlee77 will be working on fixing broken Windows wheels this week.

**Comment by sebwr** [comment]
Is there also an estimate for linux? 
As I tried it at the beginning of November it looked like the wheels were also broken on linux.

**Comment by grlee77** [comment]
I pushed an update that fixed the AMD64 Windows wheels and dropped 32-bit Windows support. The linux ones were already working aside from a couple of 32-bit ones (also dropped in that PR). See this comment and link therein:
https://github.com/scikit-image/scikit-image/pull/6581#issuecomment-1336206370

**Comment by lagru** [comment]
Can we close this now that #6581 is merged? Or should we wait until we've actually released 3.11 wheels?

**Comment by sebwr** [comment]
Is there an estimate, when the 3.11 wheels are released?

**Comment by lagru** [comment]
We have been meaning to release version 0.20 a few weeks ago but it got stalled. I'm not expecting much to happen before the new year but hope that we will push a pre-release candidate soon after that. @sebwr, sorry for the wait.

**Comment by sebwr** [comment]
No hurries, Im also done for this year. Happy holidays for everyone involved.

**Comment by sebwr** [comment]
Any news to the v0.20 update including the 3.11 wheels?

**Comment by lagru** [comment]
Hey @sebwr, we are working on a release candidate 0.20.0rc1 right now. It's currently blocked by #6667 but after that is resolved, the proper release shouldn't be far away.

**Comment by sebwr** [comment]
Are there infos for the release date?

**Comment by stefanv** [comment]
The wheels are building just fine, the pre-releases are out on PyPi, and the main release itself will be available in a week.

@pllim If `--pre` works, then there's nothing else to be done right now.

**Comment by pllim** [comment]
@stefanv , correct, the pre-release installs fine. I see that RCs are actively being pushed. Good luck in the release!

**Comment by jarrodmillman** [comment]
See https://pypi.org/project/scikit-image/0.20.0rc8/#files

**Comment by stefanv** [comment]
We're about to publish the next release, so I'm going to close this to clear the milestone. Thanks for your feedback, all.
