### ISSUE TITLE
"run-benchmarks" label is triggering workflow which is then skipped

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6518]
## Description

Adding the "run-benchmarks" label to a PR is supposed to trigger our [benchmark workflow](https://github.com/scikit-image/scikit-image/blob/main/.github/workflows/benchmarks.yml#L13). Adding this seems to trigger "something" and causes to GitHub to display that workflow. However, it's always shown as "Skipped".

E.g. https://github.com/scikit-image/scikit-image/pull/3255/commits/be1eb8c168f60b1987700ea9d219d00dd7d12878, https://github.com/scikit-image/scikit-image/pull/6509#issuecomment-1242954025 (https://github.com/scikit-image/scikit-image/pull/6509/commits/1d0e9d377f1836f911d2ee04271432a6dbf2a7ec), https://github.com/scikit-image/scikit-image/pull/6511/commits/70322e6dcc4b9cf89a13fe5e115393a77202d65a, ...

I think https://github.com/scikit-image/scikit-image/pull/6182/commits/b589052bb8884e07249f2eefbde3e8ee07f3dfc5 is the most recent commit I could find where it still works.

**Comment by grlee77** [comment]
Can confirm that removing and re-adding `run-benchmark` in #6509 just now launched this immediately skipped action: https://github.com/scikit-image/scikit-image/actions/runs/3068201753

@jaimergp, any idea what may be causing this?

**Comment by grlee77** [comment]
I at first thought maybe it was permissions changes as in #6504, but that hasn't been merged yet

**Comment by grlee77** [comment]
Actually, there was indeed an earlier change in #6426. Perhaps we need to ammend the changes made there

**Comment by grlee77** [comment]
I suspect just reverting this change will fix it:

https://github.com/scikit-image/scikit-image/pull/6426/files#diff-22eef62c9d7b36d02f5fd5aaada92702e22d6795c464239cb7b8fe0f26ea1e1cR8-R10

**Comment by lagru** [comment]
I'm not sure it's actually the permissions...? Triggering the benchmark workflow manually through the "Run workflow" button in GitHub's UI seems to work: https://github.com/scikit-image/scikit-image/actions/runs/3068608577/jobs/4956277449 

If it's an issue with permissions, shouldn't that one fail to? #6520 may be still worth testing still.

**Comment by jaimergp** [comment]
I think we might need `pull-requests: read` too so it can read the label event.

**Comment by grlee77** [comment]
Should now be resolved in #6520 (updated the title of the PR to match the eventual solution)

**Comment by jaimergp** [comment]
That's quite surprising behaviour o.o Nice find!
