### ISSUE TITLE
Remove reliance of scikit-image on distutils

### ISSUE THREAD

**Issue by grlee77** [scikit-image/scikit-image#6540]
## Description

Our current way of building scikit-image relies on `distutils` via `numpy.distutils`. 

`distutils` is scheduled for removal in Python 3.12
- [PEP 632 - Deprecate distutils module](https://peps.python.org/pep-0632/)
- Python 3.12 release is [anticipated for Oct. 2023](https://peps.python.org/pep-0693/)

`numpy.distutils` is [also deprecated](https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration)

## Meson-based alternative

SciPy is addressing this by moving to Meson for their build system. We are trying out this approach for scikit-image in #6536

More context/background regarding benefits and tradeoffs of Meson:
SciPy docs: [How to build SciPy with Meson](https://scipy.github.io/devdocs/dev/contributor/meson.html)
SciPy docs: [advanced Meson build topics](https://docs.scipy.org/doc/scipy/dev/contributor/meson_advanced.html)
Quansight Labs blog: [Moving SciPy to the Meson build system](https://labs.quansight.org/blog/2021/07/)

## Other alternatives

Approaches based on other build systems are open to consideration. If you are aware of other possible approaches, please post more info in this issue.

One other tool I am aware of for CMake-based builds is [scikit-build](https://scikit-build.readthedocs.io/en/latest/), but at the moment it still relies on `distutils` internally. I assume they will also update to avoid this in the future, but don't know what the plan/timeline for that is.

## Community consensus

Aside from the ease of adaptation to scikit-image itself, we should also consider what direction the community as a whole moves toward. It seems like best practices around moving away from distutils could be a reasonable candidate for a new [Scientific Python SPEC](https://scientific-python.org/specs/).

**Comment by cclauss** [comment]
Given #6044 (merged) what are the remaining TODOs on this issue?

**Comment by jarrodmillman** [comment]
The only remaining reference to distutils is in this comment:
```
    if outfile is None:
        # We're dealing with a distutils build here, write in-place
        outfile = os.path.splitext(fromfile)[0]
```
in `skimage/_build_utils/tempita.py`.
