### ISSUE TITLE
tifffile deprecation warning

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#6558]
When running the test suite, I see:

```
/test_pil.py::test_imread_separate_channels
  /home/stefan/envs/py310/lib64/python3.10/site-packages/tifffile/tifffile.py:1155: DeprecationWarning: <tifffile.TiffWriter.write> data with shape (3, 16, 8) and dtype 'float64' are stored as RGB with separate component planes. Future versions will store such data as MINISBLACK in separate pages by default, unless the 'photometric' and 'planarconfig' parameters are specified.
    result = tif.write(
```

**Comment by cgohlke** [comment]
Add the `photometric='rgb', planarconfig='separate'` arguments to the `imsave` call in `test_imread_separate_channels`.

**Comment by rosdyana** [comment]
@stefanv please ignore and close my PR (https://github.com/scikit-image/scikit-image/pull/6570), I didn't see this issue was assigned to @kushal-gopal in the first place. I am sorry @kushal-gopal

**Comment by lagru** [comment]
As I understand the deprecation warning, the changed default value should have not impact on the roundtripping behavior and will only impact the internal storage. I'd argue that there is actually a value in ignoring this deprecating warning (see https://github.com/scikit-image/scikit-image/pull/6573#discussion_r991102339) and testing with the provided defaults.

**Comment by grlee77** [comment]
I had previously opened a PR to address these (#6460). I resolved the conflicts and applied @mkcor's suggestions there today
