### ISSUE TITLE
Inconsistent warning types for deprecations

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6585]
Currently our decorators that are used in deprecation use different warning types:

- [`remove_arg` raises `FutureWarning`](https://github.com/scikit-image/scikit-image/blob/c3cfd5fca4180883a0e304e1616424c8d4cc14d9/skimage/_shared/utils.py#L155)
- [`deprecated_kwarg` raises `FutureWarning`](https://github.com/scikit-image/scikit-image/blob/c3cfd5fca4180883a0e304e1616424c8d4cc14d9/skimage/_shared/utils.py#L276)
- [`deprecated` raises `skimage_deprecation`](https://github.com/scikit-image/scikit-image/blob/c3cfd5fca4180883a0e304e1616424c8d4cc14d9/skimage/_shared/utils.py#L473)

Is there a reason to use different types? Otherwise I'd consider this an unnecessary for our users and an API inconsistency.

**Comment by lagru** [comment]
Hmm, I'm skeptical about the first scenario "`skimage_deprecation` deprecations in the future". Have there every been cases where we wanted to say this will be deprecated at a future point, but we don't want to deprecate it yet (implying that we will still maintain it)? Is the user supposed to stop using it at that point knowing that it will be deprecated in the future. In that case it seems just like a normal deprecation with extra confusion and steps.

In any case, `deprecated` is used for already deprecated objects. So I take from this that we should change it to the same as the other decorators, according to the [Python docs FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning) seems to be a good fit indeed.

**Comment by stefanv** [comment]
Frankly, I don't think it matters much.
