### ISSUE TITLE
deprecated decorator warning does not point at calling location

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6586]
### Description:

Contrary to our other decorators such as `deprecate_kwarg`, `deprecated` points at the source code of the decorated function and not at the calling location which would be more useful to the user:

https://github.com/scikit-image/scikit-image/blob/c3cfd5fca4180883a0e304e1616424c8d4cc14d9/skimage/_shared/utils.py#L470-L475

I think these decorators could use some cleanup and love in general. See also #6585. I'm happy to look into this, but want to get the other WIP for the release done before.

### Way to reproduce:

```Python
import numpy as np
from skimage.filters.lpi_filter import inverse

def filt_func(r, c, sigma = 1):
    return np.exp(-np.hypot(r, c)/sigma)

inverse(np.ones((3, 3)), filt_func)
```

### Traceback or output:

```Shell
scikit-image/skimage/filters/lpi_filter.py:171: skimage_deprecation: Function ``inverse`` is deprecated and will be removed in version 0.21. Use ``skimage.filters.lpi_filter.filter_inverse`` instead.
  removed_version='0.21')
Out[2]: 
array([[0.78918759, 0.41273506, 0.66250022],
       [0.41273506, 0.03946844, 0.37050594],
       [0.66250022, 0.37050594, 0.95194294]])
```

### Version information:

```Shell
3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
Linux-6.0.2-arch1-1-x86_64-with-glibc2.36
scikit-image version: 0.20.0.dev0+git20221016.c3157562e
numpy version: 1.23.3
```

**Comment by stefanv** [comment]
This is pretty bad: it instructs users to user private API.
