### ISSUE TITLE
`segmentation.watershed` returns wrong data type

### ISSUE THREAD

**Issue by kostrykin** [scikit-image/scikit-image#6587]
### Description:

The documentation of `segmentation.watershed` says that:

> ### Returns
>   **out**: ndarray
>   A labeled matrix of the same type and shape as markers

[[0.18.x]](https://scikit-image.org/docs/0.18.x/api/skimage.segmentation.html#skimage.segmentation.watershed) [[0.19.x]](https://scikit-image.org/docs/0.19.x/api/skimage.segmentation.html#skimage.segmentation.watershed)

I have tested this with 0.18.1:

```python
import skimage.segmentation
import numpy as np
print(skimage.segmentation.watershed(np.zeros((100, 100)), np.zeros((100, 100), np.uint16)).dtype)
```

Gives `int32` but `uint16` is expected.

### Way to reproduce:

```Python
import skimage.segmentation
import numpy as np
print(skimage.segmentation.watershed(np.zeros((100, 100)), np.zeros((100, 100), np.uint16)).dtype)
```

### Traceback or output:

```Shell
int32
```

### Version information:

```Shell
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
Linux-5.8.0-36-generic-x86_64-with-glibc2.10
scikit-image version: 0.18.1
numpy version: 1.20.3
```

**Comment by stefanv** [comment]
Confirmed on `0.20.0.dev0+git20221013.385b3cae5`. Could be fixed by returning correct dtype (ideal) or by changing docs.

**Comment by decorouz** [comment]
`_validate_inputs()` function of the `_watershed.py` file validates and formats the input `markers` array to `astype(np.int32)`.
