### ISSUE TITLE
Contributing developer setup instructions for conda produce an error

### ISSUE THREAD

**Issue by GenevieveBuckley** [scikit-image/scikit-image#6588]
### Description:

The [`CONTRIBUTING.rst`](https://github.com/scikit-image/scikit-image/blob/main/CONTRIBUTING.rst) instructions for setting up a development environment with conda do not work. This is not ideal for encouraging new contributors.

Attempting to `conda install -c conda-forge --file requirements.txt` (or even `conda install -c conda-forge --file requirements/default.txt`) produces an error with conda.

Perhaps those lines need to be changed to install the requirements with pip instead of conda?

The instructions as written are currently:
```
# Create a conda environment named ``skimage-dev``
conda create --name skimage-dev
# Activate it
conda activate skimage-dev
# Install main development and runtime dependencies of networkx
conda install -c conda-forge --file requirements.txt
# Install scikit-image from source
pip install -e .
# Test your installation
pytest --pyargs skimage
```

### Way to reproduce:

```Python
git clone https://github.com/scikit-image/scikit-image.git
cd scikit-image
conda create -n testenv
conda activate testenv
conda install -c conda-forge --file requirements.txt

# and/or
conda install -c conda-forge --file requirements/default.txt
```
```


### Traceback or output:

```Shell
conda install -c conda-forge --file requirements.txt

CondaValueError: could not parse '-r requirements/default.txt' in: requirements.txt
```

```
conda install -c conda-forge --file requirements/default.txt

InvalidVersionSpec: Invalid version '1.9.2;python_version<="3.9"': invalid character(s)
```
```


### Version information:

```Shell
Operating system: macOS Monterey 12.3.1 (21E258)
conda verstion 4.14.0

No python, scikit-image, or numpy versions to report, the development installation errors while installing dependencies into the conda environment.
```

**Comment by stefanv** [comment]
Looks like conda can't parse some of these advanced specs; I've added a commit to https://github.com/scikit-image/scikit-image/pull/6497 to simplify the `requirements/default.txt`

**Comment by stefanv** [comment]
> Also, shouldn't cython be included somewhere in one of the requirements files (eg: `requirements/developer.txt`)?

It's in `build.txt`, but I agree we have too many of these.  How best to simplify? Maybe add `-r build.txt` to `developer.txt`?

**Comment by hmaarrfk** [comment]
It isn't easy to simplify them because we want to make sure optional dependencies stay optional.

**Comment by rfezzani** [comment]
@GenevieveBuckley, please see #6888, I think it fixes this issue.

**Comment by rfezzani** [comment]
This issue is obsolete after merging #6770.

I tried the [INSTALL.rst](https://github.com/scikit-image/scikit-image/blob/main/INSTALL.rst#conda-1) instructions, and I observed no errors.
Can we close?

**Comment by GenevieveBuckley** [comment]
> I tried the [INSTALL.rst](https://github.com/scikit-image/scikit-image/blob/main/INSTALL.rst#conda-1) instructions, and I observed no errors.

Can confirm, new conda setup instructions work well.
