### ISSUE TITLE
more comprehensive documentation for deltae calculations

### ISSUE THREAD

**Issue by vvizzo** [scikit-image/scikit-image#6615]
### Description:

I am very happy that scikit-image has deltae calculations in color module. 

Note that results of calculation can vary depending on illuminant. 

CIE standard has three standard illuminants (https://cie.co.at/publications/colorimetry-part-2-cie-standard-illuminants-0)

A, D65, D50

Scikit implements only one of them - D50. And I am very glad because it is dominant in industry. But please document it. Without documentation it is harder to use and can lead to unconscious changing to 'proper' values in a future. Just adding few lines to documentation could make life easier and more secure for people depending on this code.

Of course implementation of other illuminants and standard observers (2 and 10 degrees) would be great addition too :)

**Comment by stefanv** [comment]
That is an important observation, @vvizzo! Would you be willing to help us fix the documentation, or perhaps add the other illuminants

**Comment by vvizzo** [comment]
I am stupid... delta is of course illuminant/observer independent. Conversion to/from are dependent :/

**Comment by stefanv** [comment]
Nice, easy fix! :D
