### ISSUE TITLE
Fix deprecation warning in plot_thresholding

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#6640]
### Description:

/home/runner/work/scikit-image/scikit-image/doc/examples/applications/plot_thresholding.py:125: MatplotlibDeprecationWarning:

Auto-removal of overlapping axes is deprecated since 3.6 and will be removed two minor releases later; explicitly call ax.remove() as needed.

**Comment by mkcor** [comment]
This file was renamed in #6644, so this path must be `/home/runner/work/scikit-image/scikit-image/doc/examples/applications/plot_thresholding_guide.py:125` now.

**Comment by lagru** [comment]
Still relevant, see https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_thresholding.html#sphx-glr-auto-examples-segmentation-plot-thresholding-py

**Comment by lagru** [comment]
Fix in https://github.com/scikit-image/scikit-image/pull/7026.
