### ISSUE TITLE
Add support for pathlib2

### ISSUE THREAD

**Issue by Raindow** [scikit-image/scikit-image#6642]
### Description:

 The original pathlib package that tracked the original module is no longer maintained. Thus, I use pathlib2 instead. However, scikit-image does not support pathlib2. I think it would be nice to support pathlib2.
Thanks!

**Comment by hmaarrfk** [comment]
What version of python are you using? Isn't pathlib part of the python standard library now, which means we don't need external modules.

**Comment by hmaarrfk** [comment]
Just import pathlib with python 3.7+. It is built in.

**Comment by Raindow** [comment]
Thank you!!
&nbsp;


卷苏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mark ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scikit-image/scikit-image] Add support for pathlib2 (Issue #6642)





 
If there is a particular feature you want from pathlib2 feel free to make the case again. We can reopen this issue or you can simply open a new one
