### ISSUE TITLE
Gallery example uses private `_invariant_denoise`

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6643]
### Description:

Our gallery example [Full tutorial on calibrating Denoisers Using J-Invariance](https://scikit-image.org/docs/dev/auto_examples/filters/plot_j_invariant_tutorial.html#the-self-supervised-loss-and-j-invariance) imports the private function `_invariant_denoise` from `skimage.restoration.j_invariant`. 
 
I don't think our documentation should encourage the use of private objects. I propose making `_invariant_denoise` part of our public API which should be a quick fix.

### Version information:

```Shell
3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
Linux-6.0.11-arch1-1-x86_64-with-glibc2.36
scikit-image version: 0.20.0.dev0+git20221206.4007a76a1
numpy version: 1.23.4
```

**Comment by stefanv** [comment]
Agreed. Consistently named and grouped with other denoisers.
