### ISSUE TITLE
Decomposing, augmenting, and Recombining gives purple output

### ISSUE THREAD

**Issue by stevekangLunit** [scikit-image/scikit-image#6648]
### Description:

Hello. 
I am using version 0.18.2.
I am currently running a simple experiment that style transfers for each hematoxylin channel[Image 1] and dab[image 2] channel.
After style transferring, I attempted to recombine to produce image.
To do so, I decomposed the h channel from hematoxylin image and d channel from dab image and concatenated, and plugged in hed2rgb.

However, recombining only produces purple-yish output [image3].

After playing around with eosin values, I found out that eosin also plays role in making the color "blue-yish".

How can I correctly recombine augmented/style transferred hematoxylin and dab 
channel? 

Original image is as [image 4]

![1_A_hema](https://user-images.githubusercontent.com/86951507/207513761-4b6d478f-335e-46ee-b292-31122f75d2c1.jpg)
![1_A_dab](https://user-images.githubusercontent.com/86951507/207513781-4b151ba9-44a6-47e3-839d-902c0b2c8bd6.jpg)
![combined_1](https://user-images.githubusercontent.com/86951507/207513794-855f2146-d4ac-4e31-8dae-e7aa0ad4a001.jpg)
![1_A](https://user-images.githubusercontent.com/86951507/207513801-4140ba0a-4afc-4900-9f26-c18147359fd1.jpg)

### Way to reproduce:

```Python
from skimage import data
from skimage.color import rgb2hed, hed2rgb

hema = cv2.imread("./transfered_hema/4_A.jpg")
original = cv2.imread("./datasets/stain_images/testA/4_A.jpg")
dab = cv2.imread("./transfered_dab/4_A.jpg")

hema = cv2.cvtColor(hema, cv2.COLOR_BGR2RGB)
original = cv2.cvtColor(original, cv2.COLOR_BGR2RGB)
dab = cv2.cvtColor(dab, cv2.COLOR_BGR2RGB)

ihc_hed = hed2rgb(np.stack((hema[:, :, 0], original[:, :, 1] , dab[:, :, 2]), axis=-1))

cv2.imwrite("combined_2.jpg",ihc_hed)
```

### Version information:

```Shell
import skimage
print(skimage.__version__)

output : 0.18.2
```

**Comment by mkcor** [comment]
Hi @stevekangLunit,

Please upgrade scikit-image to the latest version (0.19.3). Indeed, there was a bug in version 0.18.2 for handling these color channels:
![v018](https://user-images.githubusercontent.com/2227806/207839931-fa49640a-3e50-4b02-8adc-419661904fee.png)

vs. now:
![vstable](https://user-images.githubusercontent.com/2227806/207839963-20c03afc-d453-482b-a187-7f21df39e994.png)

**Comment by lagru** [comment]
Hey @stevekangLunit, I hope you could resolve your problem. I am taking the liberty to close this for now. If this problem still persists even after upgrading or you still want to add something here, please feel encouraged to reopen this issue! :)
