### ISSUE TITLE
typos：“closing” should be “opening”， and “opening” should be “closing”

### ISSUE THREAD

**Issue by li1127217ye** [scikit-image/scikit-image#6651]
### Description:

Some typos in the demo：
https://scikit-image.org/docs/stable/auto_examples/applications/plot_rank_filters.html#image-morphology

“closing” should be “opening”， and “opening” should be “closing”.

![image](https://user-images.githubusercontent.com/3051351/207770119-61b0a877-59ff-4110-a9d3-e69c9fc35d3c.png)

**Comment by mkcor** [comment]
Hi @li1127217ye,

Thank you so much for reporting!  Would you mind submitting a pull request to fix this mistake? You want to edit this source file: https://github.com/scikit-image/scikit-image/blob/main/doc/examples/applications/plot_rank_filters.py Let me know if you need any guidance on this process (see https://scikit-image.org/docs/stable/contribute.html#development-process).

**Comment by li1127217ye** [comment]
I have  submitted a pull request to fix this mistake, please check the pull request and merge it.

**Comment by mkcor** [comment]
Thanks, @li1127217ye.

Oh, I thought this [comment](https://github.com/scikit-image/scikit-image/pull/6652#issuecomment-1355050332) would automatically close this issue... I usually write "Closes ..." Anyway, closing manually now!
