### ISSUE TITLE
Input image dtype is bool. Interpolation is not defined with bool data type. Please set order to 0 or explicitely cast input image to another data type.

### ISSUE THREAD

**Issue by Rathodkumar** [scikit-image/scikit-image#6662]
![Screenshot (4)](https://user-images.githubusercontent.com/119750735/209441924-da935d28-4104-4f79-a7b7-d7407462e96a.png)
![Screenshot (5)](https://user-images.githubusercontent.com/119750735/209441925-a76183d9-6260-4dc8-b29d-5f42a78a4a92.png)
![Screenshot (6)](https://user-images.githubusercontent.com/119750735/209441927-996de2e4-a29d-4694-82c5-2e5084128275.png)
![Screenshot (7)](https://user-images.githubusercontent.com/119750735/209441928-0116ed84-b267-4335-ae20-1d025de99a3f.png)
I am getting these type of error while doing the object detection with mrcnn in kangaroo dataset,,
i have saw your post  regarding this one but i cant get it how to solve that error in my program plzzzz solve this error..................

**Comment by hmaarrfk** [comment]
You took the effort to delete and not provide the requested information that we asked for.

It is likely that the external library you are calling isn't compatible with the version of scikit image you have installed.

I might post on the Kangaroo forum if I were you.

**Comment by hmaarrfk** [comment]
Could you please post here wjth the missing information we originally requested? You can find it by drafting a new issue. You don't need to create a new issuez just get the commands from the provided template.
