### ISSUE TITLE
NumPy 1.24 deprecation warning

### ISSUE THREAD

**Issue by sergiud** [scikit-image/scikit-image#6663]
### Description:

Starting NumPy 1.24 I observe a deprecation warning during `pytest` execution. 

### Way to reproduce:

```bash
$ python -W always -c 'import skimage.util'
```

### Traceback or output:

```console
/usr/lib/python3.10/site-packages/skimage/util/dtype.py:27: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
```

### Version information:

```Shell
3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
Linux-6.1.1-arch1-1-x86_64-with-glibc2.36
scikit-image version: 0.19.3
numpy version: 1.24.0
```

**Comment by lagru** [comment]
Thanks for the report @sergiud. I think this was addressed in 74e0652fbbd2bf5600aacc3937e2b566dddb7374 already. We haven't yet published a release with that patch but hopefull soon. :crossed_fingers: 

I'm closing this fixed but please feel welcome to comment if you want to add something.
