### ISSUE TITLE
Build wheels for arm64 on macos

### ISSUE THREAD

**Issue by jarrodmillman** [scikit-image/scikit-image#6667]
### Description:

Here is the failing action:
- https://github.com/scikit-image/scikit-image/actions/runs/3913527445/jobs/6689521045

Here is the error:
```
    The Meson build system
    Version: 1.0.0
    Source dir: /Users/runner/work/scikit-image/scikit-image
    Build dir: /Users/runner/work/scikit-image/scikit-image/.mesonpy-zikfwp0q/build
    Build type: cross build
    Project name: scikit-image
    Project version: 0.20.0.dev0
    C compiler for the host machine: cc -arch arm64 (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.102)")
    C linker for the host machine: cc -arch arm64 ld64 819.6
  
    ../../meson.build:1:0: ERROR: Unknown compiler(s): [['cpp', '-arch', 'arm64']]
  
    A full log can be found at /Users/runner/work/scikit-image/scikit-image/.mesonpy-zikfwp0q/build/meson-logs/meson-log.txt
    + meson setup --prefix=/Library/Frameworks/Python.framework/Versions/3.9 /Users/runner/work/scikit-image/scikit-image /Users/runner/work/scikit-image/scikit-image/.mesonpy-zikfwp0q/build --native-file=/Users/runner/work/scikit-image/scikit-image/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --cross-file /Users/runner/work/scikit-image/scikit-image/.mesonpy-cross-file.ini
    error: subprocess-exited-with-error
```

**Comment by jarrodmillman** [comment]
@lagru @jni  FYI, we have an issue with the arm64 wheels. I am looking into it and will likely need Stefan's help with this.

**Comment by stefanv** [comment]
I'm going to tag @eli-schwartz here, just in case he knows the answer off-hand.

**Comment by stefanv** [comment]
I notice that we are not building Github's MacOS platform directly, but [cross-compiling on the latest ubuntu via cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/faq/#arm64)—so that's a clue on where to investigate.

**Comment by stefanv** [comment]
Perhaps @henryiii may have thoughts as well.

**Comment by eli-schwartz** [comment]
> ```
> Unknown compiler(s): [['cpp', '-arch', 'arm64']]
> ```

Is it trying to use the C Pre-Processor (cpp) here instead of the C Plus Plus compiler (c++)?

**Comment by eli-schwartz** [comment]
See https://github.com/mesonbuild/meson-python/pull/261

**Comment by dnicolodi** [comment]
This was a silly bug in meson-python. @eli-schwartz submitted a PR that fixes it. You can use meson-python from git master in your CI jobs to test.

**Comment by stefanv** [comment]
Thanks very much @eli-schwartz and @dnicolodi!

**Comment by jarrodmillman** [comment]
@stefanv It looks like it is still failing. E.g., https://github.com/scikit-image/scikit-image/actions/runs/3927096001/jobs/6728030995

**Comment by eli-schwartz** [comment]
`pip wheel` is collecting build dependencies again and installing PyPI's `meson_python-0.12.0-py3-none-any.whl`.
