### ISSUE TITLE
rgb2gray autocasts array to float and returns [0.0, 1.0]

### ISSUE THREAD

**Issue by EricZimmermann** [scikit-image/scikit-image#6689]
### Description:

Converting to grayscale with rgb2gray autocasts a np.uint8 to np.float64 under the hood. Since it detects a float, it renormalizes the array to [0.0,1.0]. I believe this behaviour should be noted in the docs.

### Way to reproduce:

```Python
import numpy as np
from skimage.color import rgb2gray

n, m = 128, 128
img = np.random.randint(low=0, high=256, size=(n,m,3), dtype=np.uint8)
grayscale = rgb2gray(img)

print(img.min(), img.max()) # [0, 255]
print(grayscale.min(), grayscale.max()) # [0.0, 1.0]
```

### Traceback or output:

```Shell
0 255
0.0022619607843137254 0.982521568627451
```

### Version information:

```Shell
3.7.13 (default, Mar 16 2022, 20:50:24) 
[Clang 13.0.0 (clang-1300.0.29.30)]
Darwin-22.1.0-x86_64-i386-64bit
scikit-image version: 0.19.3
numpy version: 1.19.5
```

**Comment by stefanv** [comment]
This is expected, see: https://scikit-image.org/docs/stable/user_guide/data_types.html

In the forthcoming skimage 2.0, we will no longer do those kinds of casts where they can be avoided.

**Comment by EricZimmermann** [comment]
@stefanv thanks!
is there a reason this is not directly documented in the docstring to note different behaviours?

**Comment by stefanv** [comment]
@EricZimmermann Yes, primarily because this happens *all over the place* in skimage, so it's documented as a "general principle" rather than being pointed out for each function. In retrospect, this was not a wise design, but it made it easy to construct pipelines and we didn't have the experience to know better.
