### ISSUE TITLE
Outdated comment?

### ISSUE THREAD

**Issue by moi90** [scikit-image/scikit-image#6702]
This comment mentions a local import due to timing reasons (#4039):

https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/data/_binary_blobs.py#L51

However, the import was made global in #5872. Is the comment outdated or should the import have remained local?

**Comment by lagru** [comment]
I think it's outdated as the replacing import `from .._shared.filters import gaussian` no longer imports `scipy.signal` (as far as I can see). But it does import `from scipy import ndimage as ndi` and I'm not sure if the same logic applies here. @grlee77  do you remember or can you deduct why you changed it this way?

@moi90, thanks for checking in!

**Comment by moi90** [comment]
Cool!
