### ISSUE TITLE
Wrong explanation of VOI

### ISSUE THREAD

**Issue by MOAMSA** [scikit-image/scikit-image#6707]
Hi, 
Not sure where to post it but there is a typo error in VOI description.

https://github.com/scikit-image/scikit-image/blob/00177e14097237ef20ed3141ed454bc81b308f82/skimage/metrics/_variation_of_information.py#L14

**Comment by stefanv** [comment]
Thanks! What should the sentence read like? And are you interested in filing a pull-request to make it right?
