### ISSUE TITLE
0.20.0rc2: incorrect metadata

### ISSUE THREAD

**Issue by neutrinoceros** [scikit-image/scikit-image#6720]
### Description:

attempting to install `0.20.0rc2` with
```shell
python -m pip install scikit-image --pre
```

takes a couple minute to resolve with

```
Collecting scikit-image
  Using cached scikit-image-0.20.0rc2.tar.gz (22.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/8f/93/fee0734783a0394d240682fe58204c39f14be2a5979ecf05ec5d0ad3ffb3/scikit-image-0.20.0rc2.tar.gz (from https://pypi.org/simple/scikit-image/) (requires-python:>=3.8): Requested scikit-image from https://files.pythonhosted.org/packages/8f/93/fee0734783a0394d240682fe58204c39f14be2a5979ecf05ec5d0ad3ffb3/scikit-image-0.20.0rc2.tar.gz has inconsistent version: expected '0.20.0rc2', but metadata has '0.20.0.dev0'
  Downloading scikit_image-0.20.0.dev0-cp311-cp311-macosx_12_0_x86_64.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 4.7 MB/s eta 0:00:00
Collecting numpy>=1.21.1
  Using cached numpy-1.24.1-cp311-cp311-macosx_10_9_x86_64.whl (19.8 MB)
Installing collected packages: numpy, scikit-image
Successfully installed numpy-1.24.1 scikit-image-0.20.0.dev0
```

in fact it looks like something went off during publication and there are two pre-releases present on PyPI instead of one
<img width="774" alt="Screenshot 2023-02-01 at 22 45 43" src="https://user-images.githubusercontent.com/14075922/216170467-c4b31a09-f523-4987-8019-51121fcc758d.png">

What's worse is that even `0.20.0dev0` (which I assume wasn't an intentional release) isn't testable out of the box, as it appears that `lazy_loader` isn't correctly declared as a runtime dependency

```
E   ModuleNotFoundError: No module named 'lazy_loader'
```

**Comment by jarrodmillman** [comment]
Still working to fix this, but I've yanked the broken release.

**Comment by neutrinoceros** [comment]
`0.20.0rc4` doesn't have any of the defects I reported here, and it works out of the box for me. Thank you !

**Comment by bgitschlag** [comment]
I'm having the same problem (July 2, 2024).

I installed 0.24.1rc0.dev0 with

`git clone https://github.com/scikit-image/scikit-image.git`

When my python script reaches this line:

`import skimage`

I encounter the following:

`ModuleNotFoundError: No module named 'lazy_loader'`
