### ISSUE TITLE
Display inherited methods in our API documentation

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6746]
### Description:

Our API documentation currently doesn't show methods that a class inherits, e.g. [`AffineTransform`](https://github.com/scikit-image/scikit-image/blob/f4978b11499e499cc006c417b3bf0ccf245ca72c/skimage/transform/_geometric.py#L813) inherits the method [`inverse`](https://github.com/scikit-image/scikit-image/blob/f4978b11499e499cc006c417b3bf0ccf245ca72c/skimage/transform/_geometric.py#L629) but it [doesn't show up in our HTML docs for the class](https://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.AffineTransform). It helps that the parent class is linked but at least in the current stable version that link doesn't seem to work.

Not a huge problem but I think it would be nice to have so I'm keeping track of this with an issue.

**Comment by stefanv** [comment]
Agreed!

**Comment by Br-Al** [comment]
@lagru  I would like to work on this issue.

**Comment by Br-Al** [comment]
Hello @lagru 
I added a for the autodoc extension to display inherited methods in the `config.py`. 
I'm having an error when trying to build the doc.

> build-install/usr/lib/python3.11/site-packages/skimage/color/colorconv.py:docstring of skimage.color.colorconv.combine_stains:1:duplicate object description of skimage.color.combine_stains, other instance in api/skimage.color, use :noindex: for one of them
make: *** [html] Error 2

**Comment by mkcor** [comment]
I wonder if it could be an issue similar to https://github.com/sphinx-doc/sphinx/issues/8664...?

**Comment by Br-Al** [comment]
> I wonder if it could be an issue similar to [sphinx-doc/sphinx#8664](https://github.com/sphinx-doc/sphinx/issues/8664)...?

I will check the issue and let you know.

**Comment by lagru** [comment]
Addressed in #6968, see https://github.com/scikit-image/scikit-image/pull/6968/files#diff-510521eb63780de1a92fda3385bdc73f34351a31d1cce796d771dc008c54ebf9R306.
