### ISSUE TITLE
README license is incorrect

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#6767]
### Description:

The BSD license listed in our README is *not* the skimage license. The full license is:

https://github.com/scikit-image/scikit-image/blob/main/LICENSE.txt

This is the one that should be linked to, instead of inlining it in the README.

**Comment by ana42742** [comment]
Hi! I would like to work on this issue. Could this be assigned to me?

**Comment by stefanv** [comment]
Thanks for your interest @ana42742! We don't assign issues, so feel free to jump right in.

**Comment by dhruv1345** [comment]
Hi @stefanv,

I can help by correcting the README file. 
I can make changes.
Please assign the issue to me.

**Comment by stefanv** [comment]
Thanks @dhruv1345, for your offer to help. This one has now been completed. Please note that we don't assign issues; you can simply start working on one and file a PR.
