### ISSUE TITLE
Provide pyinstaller hooks for better support of pyinstaller freezeing app

### ISSUE THREAD

**Issue by Czaki** [scikit-image/scikit-image#6772]
### Description:

The Pyinstaller allows for providing entry point to attach pyinstaller hook to the package. 
[pyinstaller.org/en/stable/hooks.html#providing-pyinstaller-hooks-with-your-package](https://pyinstaller.org/en/stable/hooks.html#providing-pyinstaller-hooks-with-your-package)

Providing a hook in the package reduces the maintenance cost for people who try to deliver some GUI application to a noncoding person.

As `scikit-image` start using `lazy-import` from `0.20` provide a list of files to attach, and `hiddenimports` may simplify the life of multiple users (like #5406). 

For the current `rc0` release after freezes with pyinstaller try of application start fails with lack of stub files/ 

```
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "skimage/__init__.py", line 74, in <module>
  File "lazy_loader/__init__.py", line 243, in attach_stub
ValueError: Cannot load imports from non-existent stub '/home/runner/work/PartSeg/PartSeg/dist/PartSeg/skimage/__init__.pyci'
[11749] Failed to execute script 'launcher_main' due to unhandled exception!
```

(this is reported also https://github.com/scientific-python/lazy_loader/issues/38, as `lazy-loader` is also included)

EDIT.

After add `__init__.pyi` to bundle then I got this error:

```
  File "skimage/__init__.py", line 141, in <module>
  File "lazy_loader/__init__.py", line 76, in __getattr__
  File "importlib/__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'skimage.data._fetchers'
```

So the declaration of the list of `hiddenimports` in the hook will be really helpful.

**Comment by stefanv** [comment]
This is a PyInstaller-specific problem, and I don't think it's necessary for skimage to provide you with the hiddenimports. Have you tried the alternative solutions suggested at https://pyinstaller.org/en/stable/when-things-go-wrong.html#listing-hidden-imports? Specifically, run it in debug mode with the environment variable `EAGER_IMPORT` set to `1`.

**Comment by Czaki** [comment]
I'm able to solve my issue using (in the spec file) `[x for x in collect_submodules("skimage") if "tests" not in x]` and `collect_data_files("skimage")` when using patched lazy loader from `https://github.com/scientific-python/lazy_loader/pull/39`.

Also, the community maintains some hooks: 

https://github.com/pyinstaller/pyinstaller-hooks-contrib/tree/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks (for example `hook-skimage.feature.py` file).

But in the past, you already had issues related to pyinstaller (ex. #4987  #5406).
So yes, the problem is easy to workaround for the advanced users who understand pyinstaller but it may be harder for scientific folks who try to ship their script to noncoding friends/colaborators. 

Providing hooks in scikit-image reduces a global number of issues and maintenance but increases maintenance in the project. 

So the core question is if scikit-image would like to support pyinstaller bundle out of the box or rely on the community for this.

**Comment by jni** [comment]
@Czaki the scikit-image maintenance burden is already too high for the current developers, so I don't think we would want to add this to our plate.

If you make some hooks in a separate repo and they see significant adoption, I think it would be possible to consider moving that repo under the scikit-image org.

Does this sound like a reasonable compromise for now?

**Comment by Czaki** [comment]
> If you make some hooks in a separate repo and they see significant adoption, I think it would be possible to consider moving that repo under the scikit-image org.

Because of discoverability, such hooks should be here at https://github.com/pyinstaller/pyinstaller-hooks-contrib/. So maybe I should make PR to the `pyinstaller-hooks-contrib` repository.

**Comment by stefanv** [comment]
That sounds good; I agree that this is not a maintenance task we want to take on right now. We're happy to make the patches to lazy loader etc. that you need.

**Comment by amirbehbahanian** [comment]
> 

@Czaki I have structured my .spec file as you suggested but I still get the same error. Would you expand on your comment? Please find my .spec file the following:


`# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import is_module_satisfies, collect_data_files, collect_submodules

block_cipher = None

datas  = []
datas += collect_data_files('timm', include_py_files=True)
datas += collect_data_files("skimage", includes=["*.py","*.pyi"])

hiddenimports = []
hiddenimports += [x for x in collect_submodules("skimage") if "tests" not in x]

a = Analysis(
    ['Main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
a.datas += [
    ('Models/Model_dict_1.pth', './Models/Model_dict1.pth', 'BINARY'),
    ('Models/Model_dict2.pth', './Models/Model_dict2.pth', 'BINARY'),
    ('Models/Model_dict3.pth', './Models/Model_dict3.pth', 'BINARY'),
    ('Models/Model_dict4.pth', './Models/Model_dict4.pth', 'BINARY')
]
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='FixtureClassifier',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='FixtureClassifier',
)`

Error:
`ValueError: Cannot load imports from non-existent stub 'D:\\FixtureClassifier\\dist\\FixtureClassifier\\skimage\\__init__.pyci'`

**Comment by Czaki** [comment]
I fix this bug 5 months ago. https://github.com/scientific-python/lazy_loader/commit/e1e48fa531101fee99036c397b5c97afb4b432e8

I also download the latest lazy-loaded from Pypi and check that this code is still there. You either use a different environment or have corrupted metadata state.

**Comment by amirbehbahanian** [comment]
@Czaki I fixed my environment and the error is gone. Thanks
