### ISSUE TITLE
Feature request: peak_local_min

### ISSUE THREAD

**Issue by raybellwaves** [scikit-image/scikit-image#6807]
### Description:

scipy has both a maximum and minimum function ndimage filters:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.maximum_filter.html (https://github.com/scipy/scipy/blob/main/scipy/ndimage/_filters.py#L1234)
https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.minimum_filter.html (https://github.com/scipy/scipy/blob/main/scipy/ndimage/_filters.py#L1192)
Note the difference of these functions is specified by using a minimum parameter of either 0 (maximum) or 1 (minimum) which is passed to the underlying function [`_min_or_max_filter`](https://github.com/scipy/scipy/blob/main/scipy/ndimage/_filters.py#L1112) 

I think it scikit-image could follow upstream here and create a peak_local_min which is a min version of:
https://scikit-image.org/docs/dev/api/skimage.feature.html#peak-local-max (https://github.com/scikit-image/scikit-image/blob/main/skimage/feature/peak.py#L120)

**Comment by jni** [comment]
I'm ambivalent on this feature, since `peak_local_min(arr)` is exactly equivalent to `peak_local_max(-arr)`, so it's increasing the API surface for little gain — though of course you save an array copy. Anyway, wouldn't be opposed, just something to consider.

**Comment by mkcor** [comment]
I'm also 0- on this, for the same reasons as given by @jni.

**Comment by lagru** [comment]
Also -0.5. At least I am interpreting our [4th value](https://scikit-image.org/docs/dev/about/values.html) that way in this context.

**Comment by mkcor** [comment]
Since three maintainers are 0- on this issue, shall we close it as "won't do?"

**Comment by jni** [comment]
It's not a bad idea, since we have very limited bandwidth as it is. Sorry @raybellwaves, and thank you sincerely for the suggestion! I hope the negative image workaround is sufficient for your use case... 🙏 And do feel free to continue discussing your issues here to see if we can help!
