### ISSUE TITLE
skimage > 0.17.2 required

### ISSUE THREAD

**Issue by albe-jj** [scikit-image/scikit-image#6851]
### Description:

With skimage version '0.17.2' you get error: `binary_dilation() got an unexpected keyword argument 'footprint'` when using `gf.fill_rectangle(...)` function.
Upgrading to latest version of scikit-image fixes the error.

### Version information:

```Shell
gf version '6.70.0'
```

**Comment by stefanv** [comment]
Might be a bug in an older version. Glad to hear it is fixed!
