### ISSUE TITLE
`data.create_image_fetcher` should be private

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6854]
### Description:

https://github.com/scikit-image/scikit-image/blob/c90bfccbc930262eebd1149b10660bfa4f56ec61/skimage/data/__init__.pyi#L16

has no docstring and is probably intended as a private initializer for pooch. So remove it from the PYI file and probably add an underscore to the function name to be totally explicit about it. :wink: 

### Way to reproduce:

```python
import skimage as ski
assert ski.data.create_image_fetcher.__doc__   # passes
```

### Version information:

```Shell
3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
Linux-6.2.7-arch1-1-x86_64-with-glibc2.37
scikit-image version: 0.21.0rc0.dev0+git20230323.c90bfccbc
numpy version: 1.24.1
```

**Comment by lagru** [comment]
@hmaarrfk, pinging you here because you initially added the pooch machinery. Do you have any qualms with making this function private?

**Comment by stefanv** [comment]
This is internal functionality that shouldn't be exposed. Same for `image_fetcher` itself.

**Comment by jni** [comment]
@stefanv do you think there should be a deprecation cycle for this? See #6855, which removes it without deprecation.

**Comment by lagru** [comment]
Probably a good idea, seeing that it was included in [`skimage/data/__init__.pyi`](https://github.com/scikit-image/scikit-image/pull/6855/files#diff-8c8ed5622886c88fa75b5c243deae86f7f185b35d9b5682fbf1551cbeadbec2a). I consider everything in those `__all__` lists to be part of the public API, even if it entered them accidentally...

**Comment by stefanv** [comment]
I searched github for usage and couldn't find any. And since it's skimage specific, I don't think deprecation is necessary.

**Comment by mkcor** [comment]
Is it too late to add #6855 to the `0.21` milestone? :pray:

**Comment by stefanv** [comment]
If it gets merged today, it will still go into the release.

**Comment by mkcor** [comment]
@stefanv ok, thanks. I'm resolving the conflicts right now; I couldn't take over @seanpquinn's PR, I had to create a new branch and cherry-pick their commits; will push it soon.

**Comment by stefanv** [comment]
Thanks!

**Comment by mkcor** [comment]
Please see #6950.
