### ISSUE TITLE
circleci-artifacts-redirector-action fails with undefined "length"

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6877]
### Description:

I think we have the same issue as https://github.com/numpy/numpy/issues/23548.

There seems to have been a similar issue with the action in the past, see https://github.com/larsoner/circleci-artifacts-redirector-action/issues/38.

### Way to reproduce:

Look at https://github.com/scikit-image/scikit-image/actions/workflows/circleci.yml the redirector currently fails with 
```
Error: Cannot read properties of undefined (reading 'length')
```

**Comment by jarrodmillman** [comment]
See https://github.com/larsoner/circleci-artifacts-redirector-action/issues/40

**Comment by soupault** [comment]
Fixed in https://github.com/scikit-image/scikit-image/pull/6894.
