### ISSUE TITLE
Can I detect many ellipses in the same picture?

### ISSUE THREAD

**Issue by MysteryNull** [scikit-image/scikit-image#6878]
Can I detect many ellipses in the same picture?

**Comment by stefanv** [comment]
https://scikit-image.org/docs/stable/auto_examples/edges/plot_circular_elliptical_hough_transform.html

**Comment by MysteryNull** [comment]
what is the meaning of the argument "accuracy" of this function?And how to choose the value?Thank you!

**Comment by adfoucart** [comment]
You should probably check the [reference paper](https://ieeexplore.ieee.org/document/1048464) and the [implementation](https://github.com/scikit-image/scikit-image/blob/5e74a4a3a5149a8a14566b81a32bb15499aa3857/skimage/transform/_hough_transform.pyx#L103), but the basic idea is:

* Potential ellipses in the edge image are characterized by their major & minor axis length.
* For any pair of edge pixels (p1, p2), an *accumulator* keeps track of the minor axis lengths of potential ellipses formed with the other points (see the illustration in the reference paper).
* If any bin in the histogram of those accumulated minor axis lengths is above a certain threshold, an ellipse is found and added to the results.

The *accuracy* parameters determines the *bin size* (with `bin_size = accuracy * accuracy`). So if you use a *larger accuracy*, you'll have larger bins and it's more likely that one of these bins will catch enough values to pass the threshold, but you lose some precision on the exact value of the minor axis length.

So `accuracy` and `threshold` give you a trade-off between catching more ellipses and having a more precise estimation of the shape of the ellipses.

**Comment by stefanv** [comment]
We'd welcome a PR to clarify the docstring with this information.
