### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [scikit-image/scikit-image#6880]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by stefanv** [comment]
Our code is not used in a context where security vulnerabilities are particularly relevant. Feel free to email the core team if something urgent comes up, our contact information is on the website.
