### ISSUE TITLE
Numpy array for list of AffineTransform not working since Numpy '1.24.2'

### ISSUE THREAD

**Issue by StefanBaar** [scikit-image/scikit-image#6885]
Since I updated Numpy, I can't compute the cumsum of a set of AffineTransfrorms anymore.

For example:

` trafos = [transform.AffineTransform(translation=(0, 0)), 
                   transform.AffineTransform(translation=(1, 1))]
   newts = np.cumsum(np.asarray(trafos))`

worked with older versions of numpy, but now throws the following error.

`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.`

Is this a numpy or skimage issue?

**Comment by jni** [comment]
Can you provide a minimum, reproducible code example that works with earlier NumPy but doesn't work with more recent NumPy?

**Comment by StefanBaar** [comment]
Yes,  the following 4 lines do not work with numpy =< 1.24 but do work with all versions 1.23 and earlier:

`import numpy as np` 
`from skimage.transform import AffineTransform` 
`t = [AffineTransform(translation=(0,0)),AffineTransform(translation=(1,1))]` 
`np.asarray(t)` 

numpy version >= 1.24 gives the following error message:

`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.`

**Comment by lagru** [comment]
I can reproduce with NumPy 1.23 which throws the following 2 warnings

> \<stdin>:1: FutureWarning: The input object of type 'AffineTransform' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'AffineTransform', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
\<stdin>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.

I think it's the second warning that's changed over 1.23 to 1.24. If you specify the dtype manually it works for your given example with NumPy 1.24:
```python
import numpy as np
from skimage.transform import AffineTransform
t = [AffineTransform(translation=(0,0)),AffineTransform(translation=(1,1))]
np.asarray(t, dtype=object)
```

Not sure yet if we need to do something about the first warning. :thinking:

**Comment by jni** [comment]
yeah, actually, I was wondering what the earlier output was. It looks like it was always an array of objects, which I think is sub-optimal anyway. So @StefanBaar, I think the fix is on your end to use either:

```python
np.asarray(t, dtype=object)
```

as suggested by @lagru, which will give you the old behaviour back, or something like:

```python
np.asarray(list(map(np.asarray, t)))
```

which will give you a 3D array of shape `(n_transforms, ndim+1, ndim+1)` (which is what I thought you were after... 😅).

**Comment by StefanBaar** [comment]
@jni @lagru Thanks a lot for the help. That solves it.
