### ISSUE TITLE
Module `skimage` has no `__all__` attribute at runtime

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6904]
### Description:

Even though [`skimage/__init__.pyi` defines `__all__`](https://github.com/scikit-image/scikit-image/blob/f03a55fe4b63ae494586cfbe39143528902747b0/skimage/__init__.pyi#L21) it is not available at runtime. In this line 

https://github.com/scikit-image/scikit-image/blob/f03a55fe4b63ae494586cfbe39143528902747b0/skimage/__init__.py#L74

`attach_stub`'s third return value is the content of `__all__` from the PYI file but it is ignored. It seems intentional but I doubt that it's a good thing to leave `__all__` undefined for our `skimage` top-level namespace.

As far as I'm aware the only [import related effect of `__all__` is on the result of  `from skimage import *`](https://docs.python.org/3/tutorial/modules.html?highlight=__all__#importing-from-a-package). While that use case may be discouraged, I also tend to rely on the `__all__` variable to see what's intended to be part of our public API. I think this assumption may be also common to a lot of users and is also taken by tools such as [Sphinx's autosummary extension](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_ignore_module_all).

I suggest to update the above mentioned line to 
```python
__getattr__, __lazy_dir__, __all__ = lazy.attach_stub(__name__, __file__) 
```

Context: I noticed this while looking into a way to crawl our public API.

Related #6892.

### Way to reproduce:

```python
import skimage
skimage.__all__  
# AttributeError: No skimage attribute __all__
```

### Version information:

```Shell
3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
Linux-6.2.11-arch1-1-x86_64-with-glibc2.37
scikit-image version: 0.21.0rc1.dev0+git20230420.f03a55fe4
numpy version: 1.24.2
```

**Comment by stefanv** [comment]
Yes, we can add `__all__`. It's just the value returned by lazy-loader + `__version__`:

```
In [3]: dir(skimage)
Out[3]:
['__version__',
 'color',
 'data',
 'draw',
 'exposure',
 'feature',
 'filters',
 'future',
 'graph',
 'io',
 'measure',
 'metrics',
 'morphology',
 'registration',
 'restoration',
 'segmentation',
 'transform',
 'util']
```

**Comment by lagru** [comment]
Okay, I'll add it to #6892.
