### ISSUE TITLE
ImageIO v2.28 breaks our CI

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6908]
### Description:

It seems like the recent release of imageio v2.28 breaks some of our tests. See https://github.com/scikit-image/scikit-image/pull/6907#issuecomment-1519876801 for more information.

I'm still unsure what we need to do about it. I'm assuming it's not a bug but an API change on imageio's side? However, then I would have expected to notice a warning somewhere before. 

### Way to reproduce:

```
pip install imageio==2.28
spin test
```

### Version information:

```Shell
3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
Linux-6.2.11-arch1-1-x86_64-with-glibc2.37
scikit-image version: 0.21.0rc1.dev0+git20230424.5756032d2
numpy version: 1.24.3
```

**Comment by FirefoxMetzger** [comment]
It's actually a refactor of internals deep inside ImageIO. The result of this is that you can now use v3 plugins through the v2 API ("new plugins", hence the new feature version), but otherwise, the API stayed the same. (We want this change for many reasons, some relevant ones include: (1) access to all of `tifffile`'s kwargs instead of only those present since 2018-ish, (2) access to performant video reading via pyav, (3) a smoother migration path once deprecations are removed in v3.)

There is probably nothing specific to be done from skimage's side beyond letting me know what broke (so I can create regression tests and fixes), and excluding v2.28.0 until the issues are fixed.

**Comment by lagru** [comment]
Thanks for the explanation and no worries. I already created https://github.com/scikit-image/scikit-image/pull/6909 to temporarily pin it in the meantime.

How can I help with debugging the breakage? I think a good start and might be to start with the [eagle image](https://github.com/scikit-image/scikit-image/blob/c30ffa27b6ae2945dccf193a3fc0c69c136b4110/skimage/data/_fetchers.py#L362-L377)? That function [seems to return a different shape than it did previously](https://github.com/scikit-image/scikit-image/actions/runs/4788699232/jobs/8515647417?pr=6907#step:5:527)?

**Comment by FirefoxMetzger** [comment]
> How can I help with debugging the breakage? I think a good start and might be to start with the [eagle image](https://github.com/scikit-image/scikit-image/blob/c30ffa27b6ae2945dccf193a3fc0c69c136b4110/skimage/data/_fetchers.py#L362-L377)? That function [seems to return a different shape than it did previously](https://github.com/scikit-image/scikit-image/actions/runs/4788699232/jobs/8515647417?pr=6907#step:5:527)?

@lagru See @stefanv 's comment here for the discussion of the eagle image: https://github.com/scikit-image/scikit-image/pull/6764#issuecomment-1498276962 it ended with a (slightly longer) comment from my end that summarizes the difference: https://github.com/scikit-image/scikit-image/pull/6764#issuecomment-1502737516

I think we should discuss the desired behavior in https://github.com/scikit-image/scikit-image/pull/6764 but to summarize the main question: If we save an image as RGB, but it actually is a "gray via RGB" (RGB colorspace, but all channels have the same value) should ImageIO return the image as stored (RGB) or should it reduce the image to grayscale (converting the colorspace internally before returning). Depending on how we decide this is either a regression (ImageIO needs changes) or a bug that has been fixed (skimage test suite needs updating).
