### ISSUE TITLE
Typo in the formula of the documentation of skimage.restoration.wiener

### ISSUE THREAD

**Issue by RJournet** [scikit-image/scikit-image#6920]
### Description:

There seems to be a missing "1/..." in the formula of the Wiener filter displayed in the documentation of skimage.restoration.wiener compared to what the code does. The formula reads:
$(|\Lambda_H|^2 + \lambda|\Lambda_D|) \Lambda_H^\dagger$
while the codes does (line 127-128):
$\Lambda_H^\dagger / (|\Lambda_H|^2 + \lambda|\Lambda_D|)$

Hope that might help.

**Comment by lagru** [comment]
Good catch! Thank you for raising an issue about it. :) 

You're right there is a mismatch in the docstring and actual implementation. From briefly scanning the first linked source it looks like the implementation could be correct (see lines 3 and 4 in Fig. 9 in https://arxiv.org/abs/1004.5538). Not entirely sure though?

**Comment by lagru** [comment]
@RJournet, would you like to submit a fix updating the docstring? :slightly_smiling_face:

**Comment by mkcor** [comment]
@lagru I'm not sure about the ":bug: Bug" label here: A bug is something functional, it involves code which runs...

**Comment by RJournet** [comment]
> 

I wish I knew how to do the correction, but I am afraid that it would be way more efficient if someone more used to git would take care of the correction. 

The code looked fine to me. The structure was what I expected to find for a Wiener filter. Anyway, thanks a lot for looking at the issue.

**Comment by lagru** [comment]
No problem. I made a quick PR to update the docstring. Thanks for the report!

**Comment by mkcor** [comment]
> I don't don't have strong feelings on whether it involves code or not, rather if it is "Unexpected or incorrect behavior" of what we distribute to users. In that sense my gut feeling has usually been and is also in this case that outright false or misleading documentation is a bug.
> 
> Though, our labels have always (and maybe intentionally) been a bit fuzzy and it's semantics. I'm happy to update the label name and description if you feel something else might be more fitting. :D But I like having a label that signals "this should be fixed" regardless if code, dependencies or docstrings are involved.

@lagru I see: Basically by "bug" you mean "needs fixing." Well, I admit I haven't quite followed the recent changes involving (the importance of) labels (such as the requirement for PRs to be *labelled*). The intent would be different because "bug" is descriptive vs. "needs fixing" is prescriptive.

Speaking of which, what's the expected label for a PR which fixes a bug? Do we have "bug fix?" Do we want to use the same label as that of the issue it closes (thinking of "feature request" / "new feature")?

**Comment by lagru** [comment]
I've been using it that way. :shrug: "Bug" for the reporting issue, "Bug fix" for the fixing PR. I don't think we necessarily have to do it this way but I have come to like the soothing teal color of the "Bug fix" label that tells me it will be okay. :smile:

**Comment by stefanv** [comment]
My intuition is that "bug" is a fine label for a documentation error, but that the `type: ` label would probably be `documentation`. But, really, it doesn't matter nearly as much as the problem being fixed, so do whatever feels right and makes sense :)
