### ISSUE TITLE
io.imread not closing file?

### ISSUE THREAD

**Issue by jarrodmillman** [scikit-image/scikit-image#6939]
### Description:

I just noticed we are seeing this on Windows (tests are passing, but this warning is being raised:
```
io/tests/test_io.py::test_imread_file_url
  C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\contextlib.py:120: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Users\\VssAdministrator\\AppData\\Local\\scikit-image\\scikit-image\\Cache\\main\\data\\camera.png'>
    next(self.gen)
  Enable tracemalloc to get traceback where the object was allocated.
```

We were seeing a similar issue on Linux and Mac when using `expected_warnings`. I suspect something is wrong with io.imread. Here is the test:
```
def test_imread_file_url():
    # tweak data path so that file URI works on both unix and windows.
    data_path = str(fetch('data/camera.png'))
    data_path = data_path.replace(os.path.sep, '/')
    image_url = f'file:///{data_path}'
    image = io.imread(image_url)
    assert image.shape == (512, 512)
```

**Comment by jarrodmillman** [comment]
I noticed this on #6934, but the warnings are appearing on main to:
https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=9689&view=logs&j=c266ee3e-f298-5c55-b78e-d135f25941c2&t=76d8336e-2ec7-54e7-5531-ad7a9096482b&l=8088

**Comment by stefanv** [comment]
Also letting @FirefoxMetzger know.

**Comment by FirefoxMetzger** [comment]
That's a strange, but interesting find. I built skimage from master just now and I can reproduce the warning. (I'm on Windows.) 

Interestingly ImageIO calls `file.close()` twice on the `_io.BufferedReader` object during this test. First via pillow when the pillow plugin cleans up after itself (line 123 inside `imageio/plugins/pillow.py`), and then again later by our `Request` object when it cleans up after itself (line 570 in `imageio/core/Request.py`). A following `assert _io.BufferedReader.closed` doesn't raise (so the buffered reader object, too, thinks it has been closed).

I also stepped through how we open the file and instantiate the plugin and our `Request` object - in case we re-open a file somewhere and lose the reference. However, we open it exactly once (in `imageio/core/request.py:492`) and then just keep reusing that reference. Pillow, too, reuses the reference at least up until it passes the file to it's internal PNG reader, so no leaked pointers there neither.

When I do the suggested thing and trace the malloc via `python -X tracemalloc -m pytest .\skimage\io\tests\test_io.py::test_imread_file_url` it traces the malloc into python's internal contextlib:

```
skimage/io/tests/test_io.py::test_imread_file_url
  C:\Users\Sebastian\AppData\Local\Programs\Python\Python311\Lib\contextlib.py:144: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Users\\Sebastian\\AppData\\Local\\scikit-image\\scikit-image\\Cache\\main\\data\\..\\data\\camera.png'>
    next(self.gen)

  Object allocated at:
    File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144
      next(self.gen)
```

Which also isn't particularly helpful.

---

Unfortunately, I will have to put this down for today but if - in the mean time - somebody has an idea of where the problem originates I'd be happy to check if ImageIO can do something to fix it.

**Comment by stefanv** [comment]
Thank you for the detailed investigation, @FirefoxMetzger! Quite a head-scratcher.

**Comment by FirefoxMetzger** [comment]
I found the culprit in `skimage.io.util.py:file_or_url_context` ☠️ 

https://github.com/scikit-image/scikit-image/blob/42f134a63735fda4903ea8f6ff0023b66bdd31d0/skimage/io/util.py#L26-L41

`skimage.io.imread` uses `file_or_url_context(fname)` which passes a (temporary) copy of the file to ImageIO. ImageIO dutifully closes this copy, but can't do anything about the original file because it never sees that reference.  Instead, skimage leaks the handle since it opens the original file via `urllib.request.urlopen` but never closes it.

Adding a context manager for `urlopen` like so:

```python
with urllib.request.urlopen(resource_name) as u:
    f.write(u.read())
```

fixes the problem and makes the warning disappear. (Proving once again that it is way too easy to forget about calling `resource.close()` and that my zealousness regarding resource context managers is justified ⛪)

**Comment by stefanv** [comment]
🙈 Oh, jeez, that's embarrassing. Thank you for your careful sluething!
