### ISSUE TITLE
Consistently use lazy loading for all `skimage.*` submodules

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6964]
### Description:

With `lazy_loader` successfully being used for `skimage`, `skimage.data` and `skimage.filters` why not use it for every of our public submodules? I see no significant disadvantage here (when using the approach with PYI files) and it is what is proposed in [SPEC 1](https://scientific-python.org/specs/spec-0001/).

Feel free to remove the good first issue label if there are concerns. Otherwise I would suggest to tackle this with separate PRs for each module that copy the examples mentioned above.

**Comment by stefanv** [comment]
No reason not to.

**Comment by decorouz** [comment]
**Observation:** 
The `skimage.filters` level dunder `__all__` is implemented using double-quotes. This isn't consistent with the single-quoted strings style used in other submodules.
