### ISSUE TITLE
`release_dev.rst` should probably not be included for stable releases

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#6986]
### Description:

See the first item [scikit-image 0.X.0 release notes](https://scikit-image.org/docs/0.21.x/release_notes/release_dev.html) in the TOC at https://scikit-image.org/docs/0.21.x/release_notes/index.html. Per our current release process `release_dev` should contain no items at the time of a stable release. So including it is unnecessary and confusing.

Not sure how to automate this process. One approach might be to make our [custom directive](https://github.com/scikit-image/scikit-image/blob/7ed623f47755ab0783ff409a0be356ee44a4e65e/doc/ext/skimage_extensions.py#L50-L63) that is used to create the TOC https://github.com/scikit-image/scikit-image/blob/7ed623f47755ab0783ff409a0be356ee44a4e65e/doc/source/release_notes/index.rst?plain=1#L9

smarter.

**Comment by jarrodmillman** [comment]
I don't think we need release_dev.py going forward. I will draft an updated release process and we can iterate there.
