### ISSUE TITLE
Test failure with imageio==2.31.0

### ISSUE THREAD

**Issue by jarrodmillman** [scikit-image/scikit-image#7000]
### Description:

@stefanv @lagru @FirefoxMetzger We are seeing the following warning with imageio 2.31.0:
```
FAILED io/tests/test_imageio.py::TestSave::test_imsave_roundtrip[shape1-uint16] - UserWarning: Loading 16-bit (uint16) PNG as int32 due to limitations in pillow's PNG decoder. This will be fixed in a future version of pillow which will make this warning dissapear.
```

The only difference in installed packages between these two test runs
- https://github.com/scikit-image/scikit-image/actions/runs/5164697057/jobs/9303764094
- https://github.com/scikit-image/scikit-image/actions/runs/5175699070/jobs/9323613452

is that the first one has imageio 2.30.0 and the second one is 2.31.0, which came out yesterday.

It looks like #6994 may be reporting the same issue.

**Comment by lagru** [comment]
Seems like it should be safe to add a line to ignore this warning in our test suite?

**Comment by FirefoxMetzger** [comment]
@lagru is correct. The backstory here is that pillow only has limited support for 16-bit types. It thus chooses to unpack compressed PNG into a 32-bit buffer to allow better interaction with its conversion functions. Direct decompression into 16-bit was not supported until recently (https://github.com/python-pillow/Pillow/issues/7124) and the PR adding it has not been rolled out yet.

ImageIO v3 (and pillow) have always returned 32-bit integers in this case, which is (technically) incorrect and this has caused repeated reports along the lines of "16-bit grayscale PNG results in int32 array, which is wrong". It can also trip some users when they pass the returned buffer into a C-extension that doesn't inspect the buffer and just assumes that the data is arranged in a certain way. Hence I've added this warning to raise awareness when this scenario occurs. Once the above-mentioned enhancement is rolled out, the warning will disappear automatically and ImageIO will do the correct thing of unpacking the data into uint16.

**Comment by lagru** [comment]
So once https://github.com/python-pillow/Pillow/issues/7124 is merged, `imread` will actually no longer return 32-bit but 16-bit for this case? We will see whether this changed output will trip up the test (it shouldn't): https://github.com/scikit-image/scikit-image/blob/74db9d59e6a90bb857a72fecffd6f504749f0f4b/skimage/io/tests/test_imageio.py#L58-L75
