### ISSUE TITLE
Source distribution for release 0.21.0 missing on PyPI

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#7012]
### Description:

It seems that for our recent release 0.21.0, the [workflow failed to push the source distribution to PyPI](https://github.com/scikit-image/scikit-image/actions/runs/5151128779/jobs/9276968871). It seems like an authentication issue?

Thus the distribution archives are missing from https://pypi.org/project/scikit-image/0.21.0/#files as reported on [image.sc](https://forum.image.sc/t/scikit-image-0-21-0-released/82051/2). 

@jarrodmillman, should / can we push this missing archive manually after the fact?

**Comment by stefanv** [comment]
Sdist has been uploaded.
