### ISSUE TITLE
Building skimage on windows leads to 'ninja: build stopped: subcommand failed.'

### ISSUE THREAD

**Issue by Coilm** [scikit-image/scikit-image#7048]
### Description:

I am trying to build skimage to test some new code I would like to test before making a PR.

I initially tried using the VSCode compiler, but thanks to issue #6710 I was able to find that it would not work with it.

Therefore I installed the gcc compiler found in cygwin64 and added it to my path (after uninstalling VSCode to be sure it would not conflict)

When I launch `spin build` I get the following header:

```
The Meson build system
Version: 1.1.1
Source dir: C:\<PATH>\scikit-image
Build dir: C:\<PATH>\scikit-image\build
Build type: native build
Project name: scikit-image
Project version: 0.22.0rc0.dev0
C compiler for the host machine: gcc (gcc 11.4.0 "gcc (GCC) 11.4.0")
C linker for the host machine: gcc ld.bfd 2.40
C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (GCC) 11.4.0")
C++ linker for the host machine: c++ ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-function: YES
Library m found: YES
Checking if "-Wl,--version-script" : links: YES
Program cython found: YES (C:\Users\<USERNAME>\anaconda3\envs\skimage-dev\Scripts\cython.EXE)
Program pythran found: YES (C:\Users\<USERNAME>\anaconda3\envs\skimage-dev\Scripts\pythran.EXE)
Program cp found: YES (C:\cygwin64\bin\cp.EXE)
Program python3 found: YES (C:\U<ENV-PATH>\python.exe)
Program _build_utils/cythoner.py found: YES (python C:\<PATH>\skimage\_build_utils/cythoner.py)
Compiler for C++ supports arguments -Wno-cpp: YES
Build targets in project: 58

scikit-image 0.22.0rc0.dev0

  User defined options
    prefix: /usr

Found ninja-1.11.1.git.kitware.jobserver-1 at C:\Users\<USERNAME>\anaconda3\envs\skimage-dev\Scripts\ninja.EXE
```
Then it starts building, but at some point an error appear (too long to even fit in the windows CMD, therefore I cannot past it here) and the build fail with the last line being:

```
ninja: build stopped: subcommand failed.
Could not rebuild C:\<PATH>\scikit-image\build
```

I was able to grabe the first fail and it was:

```
[6/168] Compiling C object skimage/_shared/fast_exp.cp39-win_amd64.pyd.p/meson-generated_fast_exp.c.obj
FAILED: skimage/_shared/fast_exp.cp39-win_amd64.pyd.p/meson-generated_fast_exp.c.obj
```

EDIT: I managed to get the output of the command in a txt file: [output.txt](https://github.com/scikit-image/scikit-image/files/11965470/output.txt)

### Way to reproduce:

```
conda create -n skimage-dev python=3.9
conda activate skimage-dev
```
Here the commands proposed in `INSTALL.rst` using conda does not work (`lazy_loader` is not found when using conda), therefore I am trying the one in `meson.md` 
```
pip install -r requirements.txt
pip install -r requirements/build.txt
```

and finally I use:

```
spin build
```

### Version information:

```Shell
3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
N/A
numpy version: 1.25.0
```

**Comment by stefanv** [comment]
@Coilm I'd love to help you debug this, but I'd need to see the actual error message from Meson. Is it perhaps in the meson build log? Otherwise, feel free to paste it into a `<details> ... </details>` block here.

**Comment by Coilm** [comment]
@stefanv I managed to store the output of the command in a file. The file is 14240 lines long! So I'll just share it as a .txt file if it works for you.

[output.txt](https://github.com/scikit-image/scikit-image/files/11965337/output.txt)

Let me know if there is anything else I can do.

**Comment by stefanv** [comment]
That compiler looks very unhappy. Can you try compiling with clang? I don't think in principle there should be a problem with MSVC, but we may need to debug the build a bit.

**Comment by stefanv** [comment]
We're working on 0.21 for conda-forge right now: https://github.com/conda-forge/scikit-image-feedstock/pull/103

**Comment by Coilm** [comment]
I'll try to use llvm. But just so we have no misunderstanding. I don't think I am using MSVC right now.

**Comment by stefanv** [comment]
No, looks like you are using gcc from Cygwin.

**Comment by Coilm** [comment]
@stefanv I tried to install LLVM and add it to the PATH. Know have an other kind of error. It seems that I am missing a linker.
I am not very confortable with this, so I am probably missing something simple. 

Note that I don't have VSCode installed right now, and I see that clang is giving me a warning about that. Might it be the solution?

[meson-log.txt](https://github.com/scikit-image/scikit-image/files/11965962/meson-log.txt)

**Comment by Coilm** [comment]
### How to fix it:

Install LLVM and VSCode
Add LLVM to your PATH

```
conda create -n skimage-dev python=3.9
conda activate skimage-dev

pip install -r requirements.txt
pip install -r requirements/build.txt

spin build
```

`spin build` should then use clang as compiler and the compilation will end without errors.

**Comment by stefanv** [comment]
Awesome, I am so glad it worked for you!
