### ISSUE TITLE
cpselect alternative for python

### ISSUE THREAD

**Issue by arunoruto** [scikit-image/scikit-image#7055]
### Description:

I am comming from matlab and I used their [cpselect](https://de.mathworks.com/help/images/ref/cpselect.html) tool to generate control points for transformations. There is a lack of an alternative software in the python community.
Many images have different illumination angles or have been acquired at different times, and therefore represent a hard problem for automated coregistration of images, so a GUI for selecting control points would help out.

One project tackling this problem is [hofmann-tobias/cpselect](https://github.com/hofmann-tobias/cpselect), written using PyQt5. This can be used or altered with an alternative GUI engine like [Kivy](https://kivy.org/). Aditional features like control point prediction would be also nice (if one image has more points than the other, they will be predicted).

I already [proposed this to opencv](https://github.com/opencv/opencv/issues/23784), but it seems like just using the automated procedures is enough for them.

**Comment by lagru** [comment]
Thanks for the suggestion and sorry that this fell through the cracks for a little bit! :pray: That indeed looks like a useful feature to have in Python land though I am not sure that this fits within the scope of scikit-image. Generally we try to stay away from GUI and we even removed our `skimage.viewer` module somewhat recently (https://github.com/scikit-image/scikit-image/pull/6160). 

Though, this might be a good fit for a [napari plugin](https://napari.org/stable/plugins/index.html). Cc'ing @jni in case he has more context on the landscape in that regard.

I am closing this for now, but don't let that dissuade you from continuing the discussion if you have something to add!
