### ISSUE TITLE
Broken link to "user guide" on homepage

### ISSUE THREAD

**Issue by DFEvans** [scikit-image/scikit-image#7068]
### Description:

On the homepage for https://scikit-image.org/, there is a sentence in "Getting started":

> You can read more in our [user guide](https://scikit-image.org/docs/stable/user_guide.html).

However, the link for "user guide" is broken, leading to a 404 error page.

https://scikit-image.org/docs/stable/user_guide/ without the .html is a valid link, but doesn't feel very "welcoming", so I'm unsure if it's the intended link.

Alternatively, "Get Started" from the base documentation page links to https://scikit-image.org/docs/stable/user_guide/install.html which looks a bit more like the intended location.

**Comment by decorouz** [comment]
Great spot @DFEvans 

> https://scikit-image.org/docs/stable/user_guide/ without the .html is a valid link, but doesn't feel very "welcoming", so I'm unsure if it's the intended link.

Yes, you have identified the correct url. It appears to be the intended link to the resources. 
Here are a few urls that follow a similar pattern:

- **about** - https://scikit-image.org/docs/stable/about/
- **skips**  - https://scikit-image.org/docs/stable/skips/ 
- **release notes** - https://scikit-image.org/docs/stable/release_notes/

**Comment by soupault** [comment]
Fixed in https://github.com/scikit-image/skimage-web/pull/99 .
