### ISSUE TITLE
Consider making PyWavelets an optional dependency

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#7079]
### Description:

Right now, we need to wait for its wheels before making a release.
It would be good to narrow down our basic dependency list.

**Comment by yangtcai** [comment]
Hi, could you provide me with some suggestions on where to start if I want to fix this bug? :P

**Comment by lagru** [comment]
@stefanv, I'm +0.5.

@yangtcai, I think pywavelets / `pywt` is only used [3 files right now](https://github.com/search?q=repo%3Ascikit-image%2Fscikit-image+pywt&type=code). For that to become optional we'd have to make sure that our library deals gracefully with it's absence. E.g. `denoise_wavelet` would have to raise a descriptive error message only if the user is trying to use the function. Oh, and also move it from `requirements/default.txt` to `requirements/optional.txt` I think.

**Comment by jakirkham** [comment]
IIUC this was done in PR ( https://github.com/scikit-image/scikit-image/pull/7156 ). Should this issue be closed?

**Comment by stefanv** [comment]
Thanks for the reminder, @jakirkham
