### ISSUE TITLE
phase_cross_correlation returns tuple instead of np.array when disambiguate=True

### ISSUE THREAD

**Issue by m-albert** [scikit-image/scikit-image#7083]
### Description:

According to its documentation, `ski.registration.phase_cross_correlation` returns a numpy array as a shift. However, when using the function with `disambiguate=True`, a tuple is returned.

### Way to reproduce:

```python

import numpy as np
import skimage as ski

im = np.random.randint(0, 100, ((10,10)))

r1 = ski.registration.phase_cross_correlation(im, im)
assert(isinstance(r1[0], np.ndarray)) # r1[0] is a numpy array

r2 = ski.registration.phase_cross_correlation(im, im, disambiguate=True)
assert(isinstance(r2[0], np.ndarray)) # r2[0] is a tuple

```

### Version information:

```Shell
3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
macOS-12.6-arm64-arm-64bit
3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
macOS-12.6-arm64-arm-64bit
scikit-image version: 0.21.0
numpy version: 1.25.2
```

**Comment by jni** [comment]
😬 

Well a PR would be most welcome anyway! 😅

**Comment by decorouz** [comment]
Hi @m-albert! May I create a PR that closes this issue?
The bug seems to be from the `_disambiguate_shift` function which returns a 'tuple of floats'. One possible fix I have explored is to make `_disambiguate_shift` return an `ndarray` instead of a tuple. This is more robust. The other would be to update the `if` block like this.
```py
if disambiguate:
        if space.lower() != 'real':
            reference_image = ifftn(reference_image)
            moving_image = ifftn(moving_image)
        shift = np.array(_disambiguate_shift(reference_image, moving_image, shift), dtype=np.float32)
```
The latter seems like a simpler approach.

**Comment by m-albert** [comment]
Hey @decorouz, thanks for working on this :) I haven't had the time and happy to help.

> One possible fix I have explored is to make _disambiguate_shift return an ndarray instead of a tuple.

I agree that that's probably the best fix, since there's no reason for a shift sometimes being a tuple and sometimes a numpy array.

Ideally the fixed return type could also be checked for in the tests.

I'd guess scikit-image would welcome your PR on this :)

**Comment by lagru** [comment]
Fixed in https://github.com/scikit-image/scikit-image/pull/7112.
