### ISSUE TITLE
phase_cross_correlation with disambiguate=True can fail with TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by petsuter** [scikit-image/scikit-image#7089]
### Description:

`phase_cross_correlation` with `disambiguate=True` can fails with `TypeError: 'NoneType' object is not iterable`.

For example this happens if one of the images is empty.

### Way to reproduce:

```python
import numpy as np
import skimage as ski

im = np.random.randint(0, 100, ((10,10)))

ski.registration.phase_cross_correlation(im, im * 0, disambiguate=True)
```

```
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    ski.registration.phase_cross_correlation(im, im*0, disambiguate=True)
  File "C:\Python311\Lib\site-packages\skimage\registration\_phase_cross_correlation.py", line 401, in phase_cross_correlation
    shift = _disambiguate_shift(reference_image, moving_image, shift)
  File "C:\Python311\Lib\site-packages\skimage\registration\_phase_cross_correlation.py", line 171, in _disambiguate_shift
    for sl, pos_shift, neg_shift in zip(
TypeError: 'NoneType' object is not iterable
```

### Version information:

```Shell
3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: 0.21.0
numpy version: 1.24.3
```
```

**Comment by petsuter** [comment]
Stepping through the code in the debugger confirms: [Here](https://github.com/scikit-image/scikit-image/blob/v0.21.0/skimage/registration/_phase_cross_correlation.py#L160) `max_slice` is never changed from `None` and `max_corr` remains `-1`, because `corr` is always `-1` or `nan`.

Probably a line like `if max_slice is None: return shift` should be added between the two loops. Possibly a warning should be logged.

**Comment by lagru** [comment]
Thanks for reporting and already suggesting a solution, @petsuter! I can reproduce and your suggestion seems like an appropriate fix at a first glance. Do you have time and desire to do a pull request? :D

**Comment by petsuter** [comment]
I can create a tiny PR if that's all that's needed. Feel free to edit / extend or completely redo it from scratch.
