### ISSUE TITLE
skeletonize_3d output pixel values are doubled from input pixel values

### ISSUE THREAD

**Issue by petsuter** [scikit-image/scikit-image#7090]
### Description:

`skeletonize` seems to preserve the pixel value of the input image. This is fine.

`skeletonize_3d` seems to *double* the pixel value of the input image. Not sure if this is considered a bug, but depending on the pixel value and pixel data type it can overflow and be confusing.

### Way to reproduce:

Slightly modified from [example](https://scikit-image.org/docs/stable/auto_examples/edges/plot_skeleton.html):
```python
from skimage.morphology import skeletonize, skeletonize_3d
from skimage import data
import matplotlib.pyplot as plt
from skimage.util import invert

image = invert(data.horse()) * 55

skeleton = skeletonize(image)
skeleton_3d = skeletonize_3d(image)

print(skeleton.max())
print(skeleton_3d.max())
```

Output:
```
55
110
```

### Version information:

```Shell
3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: 0.21.0
numpy version: 1.24.3
```
```

**Comment by decorouz** [comment]
Thanks @petsuter for reporting this. I can not reproduce this. 
```
from skimage.morphology import skeletonize, skeletonize_3d
from skimage import data
import matplotlib.pyplot as plt
from skimage.util import invert

image = invert(data.horse()) * 55

skeleton = skeletonize(image)
skeleton_3d = skeletonize_3d(image)

print(skeleton.max())
True
print(skeleton_3d.max())
55
```

`skeletonize` returns a boolean which is the expected [behavior](https://github.com/scikit-image/scikit-image/blob/49a98547e909697f6ee89ec70691c7cad7eeb823/skimage/morphology/_skeletonize.py#L79C1-L80C66) given `image.ndim = 2` and `method` is None.

Did I miss something?

**Comment by petsuter** [comment]
Hi @decorouz
Thanks for trying to reproduce. Indeed, today I get the same results as you, which seem fine. I don't know why I got different results before. I will investigate what happened when I'm back on the other computer.

**Comment by petsuter** [comment]
Ah, sorry for the confusion. The problem occurs with `image = image.astype('int8')`, but for some reason I messed up copying the example above.

```python
from skimage.morphology import skeletonize, skeletonize_3d
from skimage import data
import matplotlib.pyplot as plt
from skimage.util import invert

image = (invert(data.horse()) * 55)

skeleton = skeletonize(image)
skeleton_3d = skeletonize_3d(image)

print(skeleton.max())
print(skeleton_3d.max())

image = image.astype('int8')

skeleton = skeletonize(image)
skeleton_3d = skeletonize_3d(image)

print(skeleton.max())
print(skeleton_3d.max())
```

Output:
```
Warning (from warnings module):
  File "C:\Python311\Lib\site-packages\skimage\util\dtype.py", line 550
    return _convert(image, np.uint8, force_copy)
UserWarning: Downcasting int32 to uint8 without scaling because max value 55 fits in uint8
True
55
True
110
```
Not sure if the warning is related.

----
(55 is just a random value that would probably not occur in practice.) But the value 255 is quite commonly used, and with that value it's even worse:
```
from skimage.morphology import skeletonize, skeletonize_3d
from skimage import data
import matplotlib.pyplot as plt
from skimage.util import invert

image = (invert(data.horse()) * 255)

skeleton = skeletonize(image)
skeleton_3d = skeletonize_3d(image)

print(skeleton.max())
print(skeleton_3d.max())

image = image.astype('int8')

skeleton = skeletonize(image)
skeleton_3d = skeletonize_3d(image)

print(skeleton.max())
print(skeleton_3d.max(), skeleton_3d.min())
```

```
True
255
True
0 0
```
Presumably due to overflow there are no results at all.

**Comment by jni** [comment]
Oof, that's nasty. The culprit here is our [data type range conversion](https://scikit-image.org/docs/dev/user_guide/data_types.html), as per usual, which is why we will no longer do them in skimage2. The line that does the conversion is here:

https://github.com/scikit-image/scikit-image/blob/8c3c324be43a057643fee8d0c92253e82a837223/skimage/morphology/_skeletonize.py#L621

You can verify the problem easily:

```python
In[1]: import numpy as np
In [2]: np.uint8(255).astype(np.int8)  # overflow happens here!
Out[2]: -1

In [3]: import skimage as ski
In [4]: ski.util.img_as_ubyte(np.uint8(255).astype(np.int8))  # clips negative values!
Out[4]: array(0, dtype=uint8)

In [5]: ski.util.img_as_ubyte(np.uint8(55).astype(np.int8))  # positive values are doubled according to dtype range
Out[5]: array(110, dtype=uint8)
```

Given the docstring of skeletonize3d for the input image:

> A binary image containing the objects to be skeletonized. Zeros represent background, nonzero values are foreground.

My suggestion is that we modify the preprocessing code to do as described:

```
if image.dtype is not np.dtype('bool'):
    image = (image != 0)
```

(Removing also the now-redundant `np.ascontiguousarray` — this is not needed because `np.pad` will make a new array anyway.)

**Comment by lagru** [comment]
Hmm, the doubling originates from https://github.com/scikit-image/scikit-image/blob/b6be0cec15a2f3ecbfc58eee9960077a5e91efb6/skimage/util/dtype.py#L361

From [`skimage.util.img_as_ubyte`'s docstring](https://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.img_as_ubyte)

> Positive values are scaled between 0 and 255.

I find the docstring and the implementation of `skeletonize_3d` conflicting. The docstring expects a binary image, but the implementation silently accepts other types and tries to return the output range. The function has only a single doctest so there is not much that indicates the intended API.

I am not sure if that is the best option but what do you think about deprecating in- and output dtypes other than bool? I find the current behavior unexpected and unnecessarily complicated.

**Comment by lagru** [comment]
Haha, just now saw your comment @jni. :smile:
