### ISSUE TITLE
Import error in skimage.morphology.convex_hull_image

### ISSUE THREAD

**Issue by aParsecFromFuture** [scikit-image/scikit-image#7113]
### Description:

When I import convex_hull_image I got the error below. Scikit-image version 0.19.3 works fine but the latest version (0.21.0) produces this error. I'm coding on kaggle environment python=3.10.

```
ImportError: cannot import name 'QhullError' from 'scipy.spatial' (/opt/conda/lib/python3.10/site-packages/scipy/spatial/__init__.py)
```

### Way to reproduce:
```python
from skimage.morphology import convex_hull_image
```

### Version information:

```Shell
0.21.0
```

**Comment by lagru** [comment]
Hey @aParsecFromFuture, could be that scikit-image and SciPy are out of sync. Could you check your SciPy version with
```python
import scipy; print(scipy.__version__)
```

**Comment by How-Wang** [comment]
same error when I used `from skimage.feature import graycomatrix, graycoprops`

**Comment by How-Wang** [comment]
@lagru Can you recommend which version of SciPy and scikit-image we should use?

**Comment by aParsecFromFuture** [comment]
> ```python
> import scipy; print(scipy.__version__)
> ```

On the CPU, scipy is using the latest version and scikit-image works fine. When the GPU is active, the scipy version becomes 1.7.3. Although I use "pip install scipy=1.11.3" and "pip show scipy" shows version 1.11.3, it is using scipy version 1.7.3 during import. Thank you for the quick response. The problem seems to be caused by the versions

**Comment by aParsecFromFuture** [comment]
> Hey @aParsecFromFuture, could be that scikit-image and SciPy are out of sync. Could you check your SciPy version with
> 
> ```python
> import scipy; print(scipy.__version__)
> ```

On the CPU, scipy is using the latest version and scikit-image works fine. When the GPU is active, the scipy version becomes 1.7.3. Although I use "pip install scipy=1.11.3" and "pip show scipy" shows version 1.11.3, it is using scipy version 1.7.3 during import. Thank you for the quick response. The problem seems to be caused by the versions

**Comment by How-Wang** [comment]
So it means we cannot use scikit-image on GPU? Otherwise I don't see the solution...

**Comment by aParsecFromFuture** [comment]
> So it means we cannot use scikit-image on GPU? Otherwise I don't see the solution...

I get same error if I try to run "from scipy.spatial import QhullError" while on GPU. Upgrading scipy to the last version would solve it. Strangely I can't upgrade scipy but I can downgrade scikit-image to workaround. If you're on kaggle you can try "pip install scikit-image==0.19.3"
