### ISSUE TITLE
module 'skimage.measure' has no attribute 'blur_effect'

### ISSUE THREAD

**Issue by kienld3049** [scikit-image/scikit-image#7132]
### Description:

module 'skimage.measure' has no attribute 'blur_effect'

**Comment by lagru** [comment]
Hey @kienld3049, thanks for reaching out. :) Could I ask you to provide a code snippet to reproduce the error and your version information as printed by 
```python
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

**Comment by stefanv** [comment]
This was added in skimage v0.19.

**Comment by stefanv** [comment]
I'm fairly confident that this is because of an old version of skimage. If that's not the case, please reopen.
