### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by fuzzy-boiii23a** [scikit-image/scikit-image#7143]
### Description:

Hi all,

Just enquiring to see if there is interest with regards to integrating this project into OSS-Fuzz? this would allow continuous testing of this project in order to identify memory corruption vulnerabilities using google's infrastructure with no monetary cost to this project. Google's OSS-Fuzz has identified 10,000 vulnerabilities and 36,000 bugs in 1000 open source projects as per https://google.github.io/oss-fuzz/#trophies. The process can be seen at https://google.github.io/oss-fuzz/architecture/ and I'm willing to integrate this project into OSS-Fuzz and write harnesses to test key functionalities of this project.

If this is something that everyone would like to see could you please let me know and provide me with an email or two in order to receive new issues found via fuzzing? I'm also happy to support with writing patches for any issues found.

**Comment by mkcor** [comment]
Next-generation spam, I presume... @scikit-image/core

**Comment by fuzzy-boiii23a** [comment]
> Next-generation spam, I presume... @scikit-image/core 

Not spam and I assume there's no interest, hope you have a great day my bad

**Comment by lagru** [comment]
Hey @fuzzy-boiii23a, thanks for reaching out and I hope you don't feel that this is directed at you personally. We have gotten similar requests in the past and the fact that you are a very new account and opened this kind of issue in multiple places may have led to the conclusion of this being spam. 

To speak on the content: This probably doesn't seem like something we want to maintain for a probably very small benefit in the case of scikit-image.

**Comment by fuzzy-boiii23a** [comment]
> Hey @fuzzy-boiii23a, thanks for reaching out and I hope you don't feel that this is directed at you personally. We have gotten similar requests in the past and the fact that you are a very new account and opened this kind of issue in multiple places may have led to the conclusion of this being spam. 
> 
> 
> 
> To speak on the content: This probably doesn't seem like something we want to maintain for a probably very small benefit in the case of scikit-image.

Understood, thanks for letting me know :) I hope you also have a great rest of your day
