### ISSUE TITLE
Reported ValueError: win_size exceeds image extent. Given the win_size = 7 and Image shape (592,400,3)

### ISSUE THREAD

**Issue by allanchan339** [scikit-image/scikit-image#7144]
### Description:

Hi, 

I am using SSIM to evaluate the image with the following code
```
from skimage.metrics import structural_similarity as compare_ssim

def _ssim(tf_img1, tf_img2):
    # NOTE: see multichannel=True for RGB images
    return compare_ssim(tf_img1, tf_img2, multichannel=True, data_range=255)
```

Given the image tf_img1 (both in 0-255):
![image](https://github.com/scikit-image/scikit-image/assets/38370649/f95af0b8-c115-4489-9a79-c57526124b03)
and tf_img2:
![image](https://github.com/scikit-image/scikit-image/assets/38370649/6865c2b5-5d5e-4d0f-8117-9b5af8c3236b)

The error reported as 
```
ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the function call, with an odd value less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to the axis number corresponding to the channels.
```
However, the image size is clearly larger than 7*7 and multichannel=True. 

### Version information:

```Shell
3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
Linux-6.2.0-33-generic-x86_64-with-glibc2.35
scikit-image version: 0.21.0
numpy version: 1.26.0
```

**Comment by mkcor** [comment]
Hi @allanchan339,

`multichannel` is deprecated, please use `channel_axis` (see [docs](https://scikit-image.org/docs/stable/api/skimage.metrics.html#skimage.metrics.structural_similarity)).

**Comment by allanchan339** [comment]
@mkcor now it works ! thx for help
