### ISSUE TITLE
phase_cross_correlation with disambiguate=True can lead to numpy runtime warning

### ISSUE THREAD

**Issue by m-albert** [scikit-image/scikit-image#7146]
### Description:

I find the shift disambiguation functionality @jni incorporated into `skimage.registration.phase_cross_correlation` tremendously useful.

Here I wanted to report that when using `skimage.registration.phase_cross_correlation` together with `disambiguate=True`, very often the following warning appears:

```python
numpy/lib/function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
```
The reason for this: `disambiguate=True` determines the correct real-space shift from the periodic shift obtained from phase cross-correlation in fourier space. For this it calculates the correlation coefficient between images transformed according to different shift candidates. When the standard deviation of one of these images is zero, `np.corrcoef` warns about a zero division in line 166:

https://github.com/scikit-image/scikit-image/blob/de8f04ad6b73be9ff8c3b42ff1651491db5a01b7/skimage/registration/_phase_cross_correlation.py#L159-L168

The resulting `corr` value is `nan` and the "shift candidate" is correctly discarded in the comparison in line 167.

So this is not a bug in the sense that the output is correct as intended, but the console can be cluttered with warnings (and in my experience the warning occurs very often).

### Way to reproduce:

```python
import numpy as np
from skimage import registration

# Create two images with a known shift
im1 = np.zeros((100, 100))
im1[50, 50] = 1
im2 = np.zeros((100, 100))
im2[60, 60] = 1

# Calculate shift
shift, error, diffphase = registration.phase_cross_correlation(im1, im2, disambiguate=True)
```

### Version information:

```Shell
3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
macOS-12.6-arm64-arm-64bit
scikit-image version: 0.22.0rc0.dev0+git20230921.de8f04ad6
numpy version: 1.26.0
```

**Comment by lagru** [comment]
Closed in #7147.
