### ISSUE TITLE
Dev wheel for Python 3.12

### ISSUE THREAD

**Issue by pllim** [scikit-image/scikit-image#7149]
Would be nice to at least have a manylinux dev wheel for py312 for this package. 🙏 🙇‍♀️

**Comment by jarrodmillman** [comment]
We are waiting on pywt 1.5, which I have been working to get released. I am working on  3.12 wheels for scikit-image here #7082.

**Comment by jarrodmillman** [comment]
Python 3.12 nightly wheels are now available:
https://anaconda.org/scientific-python-nightly-wheels/scikit-image/files

We plan to release 0.22.0rc0 later today with Python 3.12 wheels as well.

**Comment by pllim** [comment]
Thank you!!!
