### ISSUE TITLE
Gallery backlinks are underlined now since pydata-sphinx-theme 0.14

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#7157]
I just noticed that in or dev docs the [backlinks in gallery examples are currently underlined](https://scikit-image.org/docs/dev/auto_examples/numpy_operations/plot_structuring_elements.html#sphx-glr-auto-examples-numpy-operations-plot-structuring-elements-py). I think that's due to the update to PyData theme 0.14 (was there before https://github.com/scikit-image/scikit-image/pull/7155 got merged). Do we want to override that in our CSS? I don't particularly mind it as it makes the links more visible...

**Comment by jarrodmillman** [comment]
I would just use the theme. They have a team of people reviewing things for accessibility.

**Comment by lagru** [comment]
Happy to do that. Though, I am not sure they are doing so with hyperlinks in code blocks in mind. That seems like an edge case that's specific to sphinx-gallery. Maybe they'd be grateful for a ping about it..?

**Comment by soupault** [comment]
I would also keep it as is. Looks quite useful to me.

**Comment by anamfatima1304** [comment]
@lagru Thank You for mentioning this. Is this Issue still open? @soupault  If it is, I would like to contribute. 
To remove these underlines, We can probably use
 a {
  text-decoration: none;
}
in scikit-image/doc/source/_static/theme_overrides.css
Thank You for your consideration. Looking forward to your suggestions.

**Comment by lagru** [comment]
Thanks for the suggestion, but it would probably not be as easy as your suggested selector. That one would remove the underline from every link.

Although there are a few things that don't quite appeal aesthetically to me - e.g. those comically thick underlines on hovered links - I think @jarrodmillman is right that we should just try to use the theme. Less maintenance that way. :crossed_fingers: 

So I am closing this. For now. Feel free to reopen if someone disagrees.

**Comment by lagru** [comment]
> e.g. those comically thick underlines on hovered links

I now realize the underline thickness is probably to increase the accessibility for people with color-blindness. So :+1: to leaving it and a :facepalm: to my previous comment.
