### ISSUE TITLE
Adding a mask parameter to SLIC segmentation

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#716]
Would it make sense to add a mask parameter (array of bools) to the SLIC segmentation function, so that only a subset of the pixels are segmented in superpixels? This could be useful for cases when the background has been segmented beforehand. 

However, I'm not completely sure that the algorithm as it is would work if we remove some background pixels (would it converge to something sensible?). @amueller, @jni, any idea?

**Comment by jaewooklee93** [comment]
Is it implemented now?
