### ISSUE TITLE
Line length in PR is currently not checked?

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#7195]
Our ruff configuration specifies
https://github.com/scikit-image/scikit-image/blob/c2e2c22c778fe0acbc70c53bff9c6d1b063d02d8/pyproject.toml#L156

but then ignores line-length explicitly in
https://github.com/scikit-image/scikit-image/blob/c2e2c22c778fe0acbc70c53bff9c6d1b063d02d8/pyproject.toml#L164-L165

Since PR linting with pep8speaks was recently disabled in favor of pre-commit.ci, line length is currently not checked at all in PRs. Do we care?

This seems like an oversight to me and I would have simply made a PR to remove the ignored rule. However, ruff runs on the complete file and not on the diff. This is a problem because I don't want to force contributors to reformat code they haven't touched.

There might be ways to achieve this feature (see https://github.com/astral-sh/ruff/discussions/4049#discussioncomment-5678146 or https://github.com/dorschw/riff) but they don't look ideal.

I am not sure if I dare suggest this, but we could also re-enable [pep8speaks](https://github.com/pep8speaks-org/pep8speaks) as it supports this use case with its default `diff_only: True` option.

... or we revive a slightly [Sisyphean discussion](https://discuss.scientific-python.org/t/adding-black-as-linter/548) around introducing a code formatter like black. :sweat_smile: This would be my long-term preference.

**Comment by lagru** [comment]
Noticed this in https://github.com/scikit-image/scikit-image/pull/7192.

**Comment by mkcor** [comment]
> This is a problem because I don't want to force contributors to reformat code they haven't touched.

Absolutely.

> I am not sure if I dare suggest this, but we could also re-enable [pep8speaks](https://github.com/pep8speaks-org/pep8speaks) as it supports this use case with its default diff_only: True option.

I'm not opposed.
