### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by psmoros** [scikit-image/scikit-image#7198]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@zer0h-bb) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by lagru** [comment]
Dear @psmoros, thanks for reaching out. After some discussion, we will probably not add a SECURITY.md in the new future. Our project is quite small and developed and reviewed mostly in the open. So even if something were to be disclosed to us on a private channel, we’d have to fix it in the open.

That said, I want to welcome you to either open an issue on your findings or reach out to us via [skimage-core@discuss.scientific-python.org](mailto:skimage-core@discuss.scientific-python.org). Emails to the latter mailing list are only visible to our core maintainers and can be considered as a private channel.

**Comment by lagru** [comment]
You're welcome. :) Closing this then. Feel welcome to reopen if you want to add anything.
