### ISSUE TITLE
match_histograms turn high values into very low

### ISSUE THREAD

**Issue by simonreise** [scikit-image/scikit-image#7212]
### Description:

I am trying to match histograms, but in the resulting image the values that were the highest in the original image turned into very low.

The images are Landsat satellite thermal images in tif format ([here](https://drive.google.com/drive/folders/1v-iUwBhkKEx5sF7c87sMXxaxxKUI1vaB?usp=sharing))

Original image
![image](https://github.com/scikit-image/scikit-image/assets/43753582/f4ac6fd5-5ed2-4b5f-b2b6-9af6907f1770)

After histogram match
![image](https://github.com/scikit-image/scikit-image/assets/43753582/e2df5363-c19b-4a5f-ba90-42e32c25083c)

### Way to reproduce:

Images are [here](https://drive.google.com/drive/folders/1v-iUwBhkKEx5sF7c87sMXxaxxKUI1vaB?usp=sharing)

```
import matplotlib.pyplot as plt 
from skimage import exposure 
from skimage.exposure import match_histograms 
import cv2
import numpy as np

# Reading original file
image = cv2.imread(r"path/to/image/B11.TIF", cv2.IMREAD_UNCHANGED)
# Masking 0 nodata value
mask = np.where(image == 0, True, False)
image = np.ma.array(data = image, mask = mask)

# Reading reference file
reference = cv2.imread(r"path/to/image/B11_2.TIF", cv2.IMREAD_UNCHANGED)
# Masking 0 nodata value
mask = np.where(reference == 0, True, False)
reference = np.ma.array(data = reference, mask = mask)

# Matching histograms
matched = match_histograms(image, reference)
# Masking 0 nodata value
mask = np.where(matched == 0, True, False)
matched = np.ma.array(data = matched, mask = mask)

# Plotting
fig, (ax1, ax2, ax3) = plt.subplots(nrows=1, ncols=3,  
                                    figsize=(8, 3), 
                                    sharex=True, sharey=True) 

for aa in (ax1, ax2, ax3): 
    aa.set_axis_off() 
  
ax1.imshow(image) 
ax1.set_title('Source') 
ax2.imshow(reference) 
ax2.set_title('Reference') 
ax3.imshow(matched) 
ax3.set_title('Matched') 
  
plt.tight_layout() 
plt.show()
```

### Version information:

```Shell
3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]
Windows-10-10.0.22621-SP0
scikit-image version: 0.22.0
numpy version: 1.26.0
```

**Comment by stefanv** [comment]
Hi Simon, I see you have a lot of missing data. Almost none of the skimage functions support masks, unless they have an explicit `mask` argument.  I would not expect passing in `np.ma` arrays to work, and would instead expect the zeros in the original image to spread out.

**Comment by simonreise** [comment]
Yes, using non-masked arrays solved the problem. Sorry.

**Comment by stefanv** [comment]
Glad that worked out for you!
