### ISSUE TITLE
pixel_graph causes TypeError in map_array if mask is not given but edge_dunction is given

### ISSUE THREAD

**Issue by mao1756** [scikit-image/scikit-image#7233]
### Description:

If you give `edge_function` to `pixel_graph` but don't give `mask,` `mask` stays to be the default `None,` which would cause `TypeError 'The type of an array to be remapped should be an integer.'` in `map_array` even if we make sure the input image is integer.

I believe this is caused by the if statement at the beginning of the function. The if statement at the beginning does not cover the specific case I mentioned above, and the mask would not be changed from None.

The following is the lines I mentioned:

```python
if image.dtype == bool and mask is None:
        mask = image
if mask is None and edge_function is None:
        mask = np.ones_like(image, dtype=bool)
        edge_function = _weighted_abs_diff
```

As the solution, I think separating if statement for `mask` and the one for `edge_function` works:

```python
if image.dtype == bool and mask is None:
        mask = image
if mask is None:
        mask = np.ones_like(image, dtype=bool)
if edge_function is None:
        edge_function = _weighted_abs_diff
```

### Way to reproduce:

```python
import numpy as np
import skimage

image = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
) 

func = lambda x, y, z: np.abs(x-y)
adj1 = skimage.graph.pixel_graph(image) # No error
adj2 = skimage.graph.pixel_graph(image, edge_function = func) # TypeError
```

### Version information:

```Shell
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Linux-5.15.120+-x86_64-with-glibc2.35
scikit-image version: 0.19.3
numpy version: 1.23.5
```

**Comment by jni** [comment]
Oops! Nice catch @mao1756. Thanks for reporting. Your fix looks right to me. Would you like to submit a pull request to fix it, adding your reproducible example as a test?

**Comment by mao1756** [comment]
@jni Sounds good; I will work on it today.
