### ISSUE TITLE
typo in swirl default mode

### ISSUE THREAD

**Issue by tokiAi** [scikit-image/scikit-image#7240]
### Description:

function [swirl](https://github.com/scikit-image/scikit-image/blob/main/skimage/transform/_warps.py#L520): 

`def swirl(...mode='reflect',...):`

 ```
"""Perform a swirl transformation. ... 
mode : {'constant', 'edge', 'symmetric', 'reflect', 'wrap'}, optional
        Points outside the boundaries of the input are filled according
        to the given mode, with 'constant' used as the default. Modes match
        the behaviour of `numpy.pad`.
```

The declaration and the documentation do not match: "mode=**'reflect**'"  and "with **'constant'** used as the default"

**Comment by soupault** [comment]
@tokiAi thanks for reporting! If you are interested to submit a PR with the fix, please, feel free to do so.

**Comment by tokiAi** [comment]
@soupault done
