### ISSUE TITLE
Inconsistency in Default Values of shift_x and shift_y in skimage.filters.rank.mean_percentile

### ISSUE THREAD

**Issue by tokiAi** [scikit-image/scikit-image#7246]
### Description:

https://github.com/scikit-image/scikit-image/blob/main/skimage/filters/rank/_percentile.py#L155

There is an inconsistency in the default values of the `skimage.filters.rank.mean_percentile` function and the documentation. The default values for `shift_x` and `shift_y` are documented as `False`, but further in the description, these parameters are identified as integers (`int`). This inconsistency can lead to confusion about the expected data type and usage of these parameters.

`def mean_percentile(image, footprint, out=None, mask=None, shift_x=False, shift_y=False, p0=0, p1=1): ...`

```
    Parameters
    ----------
    ...
    shift_x, shift_y : int
        Offset added to the footprint center point. Shift is bounded to the
        footprint sizes (center must be inside the given footprint).
```

#### Proposed Solution:

Change the default values of `shift_x` and `shift_y` in the `skimage.filters.rank.mean_percentile` function from `False` to `0` (zero), to correctly reflect their intended use as integers specifying the offset for the footprint center.

**Comment by mkcor** [comment]
Good catch, @tokiAi! I'm afraid this is the case for other rank filters as well... I agree with your proposed solution. PR welcome! :heart:

**Comment by tokiAi** [comment]
> Good catch, @tokiAi! I'm afraid this is the case for other rank filters as well... I agree with your proposed solution. PR welcome! ❤️

Yes, I just saw it. PR will follow later.

**Comment by tokiAi** [comment]
I fixed it and add a new PR.

**Comment by lagru** [comment]
Closing since https://github.com/scikit-image/scikit-image/pull/7320 addressed this.
