### ISSUE TITLE
ValueError when using flood_fill on Standard RGB Image

### ISSUE THREAD

**Issue by tokiAi** [scikit-image/scikit-image#7253]
### Description:

I am encountering a `ValueError` when attempting to use the `flood_fill` function from the `segmentation` module on a standard RGB image provided by `skimage.data`. The issue arises even when using seemingly correct dimensions for the image and seed point.

#### Expected Behavior:

The flood_fill function should fill an area of an image starting from a seed point with a specified color, without raising a broadcasting error, especially when the dimensions of the seed point and the image appear to be compatible.

#### Current Behavior:

The function raises a ValueError indicating a broadcasting issue between the dimensions of the seed point and the image.

#### Additional Information:

- The image shape is `(512, 512, 3)`, and the seed point is a 2D tuple `(100, 100)`.
- The error message received is: `ValueError: operands could not be broadcast together with shapes (2,) (3,)`.
- I have tried various adjustments to the seed point and tolerance values without success.

Any guidance or suggestions for resolving this issue would be greatly appreciated.

### Way to reproduce:

```python
from skimage import data, segmentation

# Load an example RGB image
image = data.astronaut()

# Seed point coordinates (row, column)
seed_point = (100, 100)

# New color to fill (R, G, B)
new_color = (0, 255, 0)  # Green color

# Apply flood fill
try:
    filled_image = segmentation.flood_fill(image, seed_point, new_color, tolerance=30)
except ValueError as e:
    print(f"Error occurred: {e}")
```

### Version information:

```Shell
3.9.6 (default, Mar 10 2023, 20:16:38) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]
macOS-13.3.1-x86_64-i386-64bit
scikit-image version: 0.22.0
numpy version: 1.26.2
```

**Comment by lagru** [comment]
Hey @tokiAi, I think thats because `flood_fill` doesn't support images with a color channel directly und thus it expects a third coordinate for the provided `seed` that corresponds to the color channel dimension. Instead, use `flood` to create a mask first:

```python
import skimage as ski
import matplotlib.pyplot as plt

image = ski.data.astronaut()
image_gray = ski.color.rgb2gray(image)
seed_point = (100, 100)
new_color = (0, 255, 0)

mask = ski.segmentation.flood(image_gray, seed_point, tolerance=30 / 256)
image[mask, :] = new_color

fig, ax = plt.subplots()
ax.imshow(mask)
fig.show()
```

Note, that I `rgb2gray` scales the value range from (256, 0] to [1, 0]. So I adjusted the tolerance accordingly.

Does that help you?

**Comment by tokiAi** [comment]
Thank you!
