### ISSUE TITLE
Faster map_array function

### ISSUE THREAD

**Issue by thorstenwagner** [scikit-image/scikit-image#7262]
### Description:

In another project ( BiAPoL/napari-clusters-plotter#283 ) we faced the problem that the map_array function is quite slow when it comes to large arrays. We came up with a faster method and I thought the new method might be worth considering as a replacement for map_array. Here is a script comparing the old and new methods:

```python
import numpy as np
from skimage.util import map_array
from time import perf_counter

shape = (1,1024,1024)
total = shape[0]*shape[1]*shape[2]
NUM_LABELS=100000
input_data = np.random.randint(NUM_LABELS,size=total).reshape(shape).astype("int64")
from_values = np.arange(NUM_LABELS)
to_values = np.copy(from_values)
np.random.shuffle(to_values)

def generate_cluster_image(label_image, label_list, predictionlist):
    """
    Generates a clusters image from a label image and a list of cluster predictions,
    where each label value corresponds to the cluster identity.
    It is assumed that len(predictionlist) == max(label_image)

    Parameters
    ----------
    label_image: ndarray or dask array
        Label image used for cluster predictions
    predictionlist: Array-like
        An array containing cluster identities for each label

    Returns
    ----------
    ndarray: The clusters image as a numpy array.
    """

    predictionlist_new = np.array(predictionlist) + 1
    plist = np.zeros(np.max(label_image) + 1, dtype=np.uint32)
    plist[label_list] = predictionlist_new

    predictionlist_new = plist

    return predictionlist_new[label_image]

def generate_cluster_image_old(label_image, label_list, predictionlist):
    """
    Generates a clusters image from a label image and a list of cluster predictions,
    where each label value corresponds to the cluster identity.
    It is assumed that len(predictionlist) == max(label_image)

    Parameters
    ----------
    label_image: ndarray or dask array
        Label image used for cluster predictions
    predictionlist: Array-like
        An array containing cluster identities for each label

    Returns
    ----------
    ndarray: The clusters image as a numpy array.
    """
    from skimage.util import map_array

    # reforming the prediction list, this is done to account
    # for cluster labels that start at 0, conveniently hdbscan
    # labelling starts at -1 for noise, removing these from the labels
    predictionlist_new = np.array(predictionlist) + 1
    label_list = np.array(label_list)

    return map_array(np.asarray(label_image), label_list, predictionlist_new).astype(
        "uint32"
    )

t1 = perf_counter()
res_new = generate_cluster_image(input_data, from_values, to_values)
t_new = perf_counter() - t1
print(t_new)

t1 = perf_counter()
res_old = generate_cluster_image_old(input_data, from_values, to_values)
t_old = perf_counter() - t1
print(t_old)

print(f"Speedup {t_old/t_new}")

print(np.array_equal(res_new,res_old))
```

The new method is 15x-30x faster than the old one. 

If you guys think that this is worth it, I can come up with a PR.

**Comment by jni** [comment]
@thorstenwagner wow, coincidentally we are playing with this on napari, [here](https://github.com/napari/napari/pull/6439#discussion_r1420231107).

Unfortunately if you look back at the PR that added `map_array`, #4612, your implementation is actually what was there before. The big issue with it is that you need an array of size `np.max(labels) + 1`, which can be extremely large, even for tiny `label` arrays.

We could do something like a switch based on `np.max(array)`, if it's, say, less than 2x the size of the array, use the NumPy array mapping solution, and if it's greater, use `map_array`. I'm not 100% sure it's worth it, but I'd be happy to explore it.

It's also worth noting that while exploring napari/napari#6439, I found that the version with numba prange was ~10x faster on my machine. There's a note in [our cython implementation](https://github.com/scikit-image/scikit-image/blob/441fe68b95a86d4ae2a351311a0c39a4232b6521/skimage/util/_remap.pyx#L1-L22) about prange not working, but it predates Cython 3 — maybe it's worth trying prange now and seeing whether things improve.

**Comment by thorstenwagner** [comment]
Looking forward to see the prange solution merged :-)
