### ISSUE TITLE
Cannot import name `selem` from `skimage.morphology`

### ISSUE THREAD

**Issue by nkanrar** [scikit-image/scikit-image#7304]
### Description:

Hi, thanks for this great package! I just ran into an issue importing `selem` from scikitimage morphology and can't find a way around this issue.

### Way to reproduce:

`from skimage.morphology import medial_axis, selem`

### Version information:

```Shell
`ImportError                               Traceback (most recent call last)
Cell In[1], line 14
     12 from skimage.measure import label
     13 from skimage.segmentation import clear_border, active_contour
---> 14 from skimage.morphology import medial_axis, selem

ImportError: cannot import name 'selem' from 'skimage.morphology' (/Users/niveditakanrar/opt/anaconda3/envs/image_/lib/python3.10/site-packages/skimage/morphology/__init__.py)`
```

**Comment by decorouz** [comment]
Hi @nkanrar, thanks for reporting this. However, `selem` has being deprecated. Use `skimage.morphology import footprint` instead
