### ISSUE TITLE
Adjust variable naming in registration.optical_flow_tvl1 - Optical Flow TVL1

### ISSUE THREAD

**Issue by dfvr1994** [scikit-image/scikit-image#7313]
### Description:

Documentation provided here [optical_flow_tvl1](https://scikit-image.org/docs/stable/api/skimage.registration.html#skimage.registration.optical_flow_tvl1) gives "Tightness" a value of 0.3 and describes it as: "Tightness parameter. It should have a small value in order to **maintain attachment and regularization parts in correspondence**."

![image](https://github.com/scikit-image/scikit-image/assets/45764991/f3863eac-643e-4e04-84bf-0e86bac38dae)

The function cites [TV-L1 optical flow estimation. Image Processing On Line. Pérez, J. S., Meinhardt-Llopis, E., & Facciolo, G. (2013)](https://doi.org/10.5201/ipol.2013.26), where "Tightness" is described as "It serves as a link between the attachment and the regularization terms. In theory, **it should have a small value in order to maintain both parts in correspondence.**" and is also given a value of 0.3

![image](https://github.com/scikit-image/scikit-image/assets/45764991/75895379-10ab-45b6-9900-41bbaa456d92)

The paper has **θ** for Tightness, and the documentation has **τ**. So, should τ be replaced by θ in the documentation? 

The function also defines `dt` = 0.25 for a grayscale image: 

> https://github.com/scikit-image/scikit-image/blob/441fe68b95a86d4ae2a351311a0c39a4232b6521/skimage/registration/_optical_flow.py#L59

So is `dt` = τ???? τ is described as "the time step of the numerical scheme" in the paper. 

Thanks

**Comment by jni** [comment]
Yes, you are right, I think calling it tau in the docs was a typo/mistake. I think this just needs a PR to change that tau to a theta in the docstring, and perhaps a separate PR to add a comment to the `dt = ` line to point out that it corresponds to tau. Thanks for spotting @dfvr1994! If you would like to contribute those changes they should be quick to merge, otherwise we can fix them in a bit.
