### ISSUE TITLE
Collections attribute is used in gallery but was deprecated in Matplotlib 3.8.

### ISSUE THREAD

**Issue by mkcor** [scikit-image/scikit-image#7361]
### Description:

We can see this output in the [Segment human cells](https://scikit-image.org/docs/stable/auto_examples/applications/plot_human_mitosis.html) gallery example:

```bash
/home/runner/work/scikit-image/scikit-image/doc/examples/applications/plot_human_mitosis.py:59: MatplotlibDeprecationWarning:

The collections attribute was deprecated in Matplotlib 3.8 and will be removed two minor releases later.


[14000, 4731, 1057, 353, 59, 15]
```

### Way to reproduce:

Visit https://scikit-image.org/docs/0.22.x/auto_examples/applications/plot_human_mitosis.html

### Version information:

v0.22.x

**Comment by mkcor** [comment]
Oops! Current main (9e8bf6805fde48126008480920f02d316ebbbd98 ?) doesn't show this deprecation warning, but the values are entirely different:
![len_seg](https://github.com/scikit-image/scikit-image/assets/2227806/7f8d2301-06ab-4f97-ac7f-dbc6cfd3cc39)

Different again from v0.21.x and prior:
```py
[0, 320, 270, 48, 19, 3, 1, 0]
```

**Comment by lagru** [comment]
Hmm, even though `[len(seg) for seg in [qcs.allsegs]` changed between 0.22 and 0.23 (I think due to a change on matplotlib's side. The plot and `qcs.levels` still look identical. An @mkcor do you want to investigate this more or should be close?

**Comment by mkcor** [comment]
Yes, the change comes from matplotlib. Basically, it 'appeared' with [matplotlib 3.8](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#contourset-is-now-a-single-collection) and 'disappeared' with matplotlib 3.9 (I couldn't find 'why' exactly from the [release notes](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html)).

The expected behaviour is that of v0.21.x and prior; at intensity levels 0 and 280 (which is > 255), there is 0 segment, not 1. I'm looking at https://discourse.matplotlib.org/t/collections-attribute-deprecation-in-version-3-8/24164/15 and will try to fix this (quickly).

**Comment by mkcor** [comment]
Ok, it's just that the 'segment' for the first and last levels are empty arrays:
```py
qcs.allsegs[0]
# [array([], shape=(0, 2), dtype=float64)]

qcs.allsegs[-1]
# [array([], shape=(0, 2), dtype=float64)]
```
So maybe I can tweak the list comprehension a bit so that only non-empty arrays be counted as segments. See:
```py
len(qcs.allsegs[-1])
# 1

len(qcs.allsegs[-1][0])
# 0

len(qcs.allsegs[-2])
# 1

len(qcs.allsegs[-2][0])
# 15
```
