### ISSUE TITLE
A typo in source code comment and document

### ISSUE THREAD

**Issue by aldehyde-rcho** [scikit-image/scikit-image#7380]
### Description:

Check the [doc](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.EuclideanTransform) and the [source code](https://github.com/scikit-image/scikit-image/blob/441fe68b95a86d4ae2a351311a0c39a4232b6521/skimage/transform/_geometric.py#L1192).
For Eclidian Transform, the homogeneous transformation matrix should be like:

$$
\begin{bmatrix}
a_0&-b_0&a_1\\
b_0&a_0&b_1\\
0&0&1
\end{bmatrix}
$$

which equals to:

$$
\begin{bmatrix}
\cos\theta&-\sin\theta&t_x\\
\sin\theta&\cos\theta&t_y\\
0&0&1
\end{bmatrix}
$$

But now, in both of the source code comment and the document, it’s writen as this:

```
        [[a0  b0  a1]
         [b0  a0  b1]
         [0   0    1]]
```

Check the `__doc__`  in `Class SimilarityTransfrom`，it was written correctly:
```
        [[a0  -b0  a1]
         [b0  a0  b1]
         [0   0    1]]
```

I think maybe it’s a typo here. But it actually confused me for a minute :joy:

[First posted here](https://forum.image.sc/t/is-this-a-tiny-bug-in-source-code-comment-and-document-eclidian-transform-in-skimage-trasform-geometric/94605)

### Way to reproduce:

just found a little typo in code comment

### Version information:

```Shell
3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)]
Windows-11-10.0.22631-SP0
scikit-image version: 0.22.0
numpy version: 1.26.4
```

**Comment by lagru** [comment]
Addressed in https://github.com/scikit-image/scikit-image/pull/7097.
