### ISSUE TITLE
Wheel building action fails with `actions/upload-artifact@v4`

### ISSUE THREAD

**Issue by jarrodmillman** [scikit-image/scikit-image#7383]
### Description:

In https://github.com/scikit-image/scikit-image/actions/runs/8635496260/job/23673331485, we had this error:
```
Error: Failed to CreateArtifact: Received non-retryable
error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
This was due to this breaking change in [actions/upload-artifact@v4](https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new):
```
Uploading to the same named Artifact multiple times.

Due to how Artifacts are created in this new version, it is no longer possible to upload
to the same named Artifact multiple times. You must either split the uploads into multiple
Artifacts with different names, or only upload once. Otherwise you will encounter an error.
```
I reverted the action update in 6a60e5b and released 0.23.1 bf08f8f.

**Comment by Czaki** [comment]
You may see how it is done in this example of cibuildwheel.

https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml
