### ISSUE TITLE
Investigate performance optimization in `_corner_fast`

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#7388]
As discussed in https://github.com/scikit-image/scikit-image/pull/7379 there might be an opportunity to improve the performance of `skimage.feature.corner_fast` by moving this snippet https://github.com/scikit-image/scikit-image/blob/b8ef57a285b9c09c850f56113cea45b3d734f473/skimage/feature/corner_cy.pyx#L160-L170

to a position earlier in the execution. Right now there's also this open question in https://github.com/scikit-image/scikit-image/pull/7379#discussion_r1557626440.

(Opening this issue so we won't forget)

**Comment by spdfghi** [comment]
@lagru i made a new pr #7394
I just made a test of time cost by corner_fast:
this pr: 1.35s and brefore: 3.22s

here is my test code as you provided before, and simply used a large image input.
import numpy as np
import timeit
from skimage.feature import corner_fast, corner_peaks
square = np.zeros((1200, 1200))
square.astype(int)
def test():
    corner_fast(square)

execution_time = timeit.timeit(test, number=100) 
print(execution_time)

Generally, the number of feature points relative to the total number of images is small, so I believe this test is representative.

**Comment by spdfghi** [comment]
and sorry，I have deleted the repository where my previous pull request was located
