### ISSUE TITLE
Discrepancy of skimage.filters.frangi output between 0.19.3 and 0.22.0

### ISSUE THREAD

**Issue by CielAl** [scikit-image/scikit-image#7403]
### Description:

The output of the ```skimage.filters.frangi``` using the exact same image seems to be different between 0.19.3 and 0.22.0

### Way to reproduce:

![pen_green](https://github.com/scikit-image/scikit-image/assets/10933828/949c7258-a655-4539-b94b-fe2c7f4b4503)
Use the attached image as ```img``` which is a 3-channel numpy.ndarray ubyte image, the sum of the result between 0.19.3 and 0.22.0 seems to be different (0.36 vs. 1.15) .

```
from skimage.color import rgb2gray 
sigmas=(1.0, 10.0, 2.0)
result = frangi(rgb2gray(img),sigmas=sigmas, beta=0.5, gamma=15.0, black_ridges=True).sum()
```

### Version information:

```Shell
Env of 0.19.3:

3.8.19 (default, Mar 20 2024, 19:58:24) 
[GCC 11.2.0]
Linux-5.4.0-169-generic-x86_64-with-glibc2.17
scikit-image version: 0.19.3
numpy version: 1.23.5

Env of 0.22.0:
3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
Linux-5.4.0-169-generic-x86_64-with-glibc2.31
scikit-image version: 0.22.0
numpy version: 1.26.4
```

**Comment by lagru** [comment]
Thanks for the report. I can reproduce this with Python 3.11 as well. The result changed between 0.19.3 and 0.20.0 from 1.15 to 0.36 (rounded). I haven't checked with git bisect but I am guessing that you are running into changes introduced by https://github.com/scikit-image/scikit-image/pull/6446. From the [release notes](https://scikit-image.org/docs/dev/release_notes/release_0.20.html#changes-and-new-deprecations)

> Rewrite skimage.filters.meijering, skimage.filters.sato, skimage.filters.frangi, and skimage.filters.hessian to match the published algorithms more closely. This change is backward incompatible and will lead to different output values compared to the previous implementation. The Hessian matrix calculation is now done more accurately. The filters will now be correctly set to zero whenever one of the Hessian eigenvalues has a sign which is incompatible with a ridge of the desired polarity. The gamma constant of the Frangi filter is now set adaptively based on the maximum Hessian norm ([#6446](https://github.com/scikit-image/scikit-image/pull/6446)).

In that case, we would consider this a fix and the changed values as intended behavior. Is this a problem for you? Would you have a reason to deem the previous value, 1.15, to be more correct?

**Comment by mkcor** [comment]
> I did attempt to compare the documentation of frangi between 0.19.x and 0.22 but kinda missed the takeaway of "Earlier versions of this filter were implemented by..." part since it doesn't explicitly address the different computation outputs.

@CielAl you didn't miss anything! The note "Earlier versions of this filter were implemented by..." does not concern *our* changes in implementations. It's some background information about the filter itself, regardless of the implementation in scikit-image.

Since explicit is better than explicit, I just submitted #7721. Thanks again for your report.
