### ISSUE TITLE
inconsistent image region labeling (labels vs regionprops)

### ISSUE THREAD

**Issue by Xyand** [scikit-image/scikit-image#741]
When using `label` the labels are represented by integers in the range [-1, maxint] when -1 denotes background (label to ignore). However, when using `regionprops` it seems to ignore the region labeled by 0 as well. Either `label` or `regionprops` should be fixed, depending on the original design. 

Notice that `scipy.ndimage.measurements.label` uses 0 to mark background. I guess this is the source of confustion in the first place.

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image/pull/1956 .
