### ISSUE TITLE
Typo in `skimage.measure.find_contours`

### ISSUE THREAD

**Issue by lvsltz** [scikit-image/scikit-image#7410]
### Description:

There is a typo in the `skimage.measure.find_contours` docstring: 
Uses the “marching squares” method to compute **a the** iso-valued contours

**Comment by lagru** [comment]
You are right @lvsltz, thanks for the report! Would you like to make a PR to fix it? :)

**Comment by lvsltz** [comment]
No. Many thanks!

**Comment by lagru** [comment]
No problem. Addressed in https://github.com/scikit-image/scikit-image/pull/7411.
