### ISSUE TITLE
Incompatibility with Numpy 2 (`numpy.dtype size changed`)

### ISSUE THREAD

**Issue by joshuacwnewton** [scikit-image/scikit-image#7445]
### Description:

Numpy released 2.0.0 on Sunday, June 16th. Release notes: https://numpy.org/devdocs/release/2.0.0-notes.html

(For now, users should probably downgrade to `numpy<2`, as the upgrade is causing many incompatibilities with other packages beyond `scikit-image`, too.)

Similar past issues:

- https://github.com/scikit-image/scikit-image/issues/3655

### Way to reproduce:

```
import skimage
```

### Version information:

```Shell
>>> import sys; print(sys.version)
>>> import platform; print(platform.platform())
>>> import numpy; print(f'numpy version: {numpy.__version__}')
>>> import skimage; print(f'scikit-image version: {skimage.__version__}')
3.9.19 (main, May  6 2024, 19:43:03) 
[GCC 11.2.0]
Linux-6.5.0-35-generic-x86_64-with-glibc2.35
numpy version: 2.0.0
Traceback (most recent call last):
  File "geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by hmaarrfk** [comment]
We anticipated these kinds of incompatibilities are are in the process of releasing 0.24.X soon to address this issue on python 3.9.

Thank you @jarrodmillman for the work on that front.

**Comment by joshuacwnewton** [comment]
Thank you for the update! And, thank you Jarrod for your hard work. :blush:

**Comment by stefanv** [comment]
@joshuacwnewton We're going to try and get 0.24 out ASAP, meanwhile if it is possible for you to use a newer version of Python, we have an skimage release out for Pythons 3.10, 3.11, and 3.12, and those are compatible with NumPy 2.0.

**Comment by jarrodmillman** [comment]
You can try/test the 0.24 release candidate:  https://pypi.org/project/scikit-image/0.24.0rc1/

**Comment by joshuacwnewton** [comment]
Looking good to me! No errors on import. :)

```python
>>> import numpy
>>> numpy.__version__
'2.0.0'
>>> import skimage
>>> skimage.__version__
'0.24.0rc1'
```

(I would run our full test suite, but I'm seeing errors across the board from many different incompatible packages, so it's difficult to actually trigger any skimage-specific logic right now.)

**Comment by jarrodmillman** [comment]
Thanks for testing! I plan to release 0.24 soon.

Btw, have you seen/tried https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin

**Comment by joshuacwnewton** [comment]
We're not currently using Ruff (yet!) but I'll put a pin in this to look into further. Thank you for the tip! :heart:

**Comment by jarrodmillman** [comment]
You can run it one-time just for the NumPy 2 stuff:
```
ruff check path/to/code/ --select NPY201
```

**Comment by jarrodmillman** [comment]
https://pypi.org/project/scikit-image/0.24.0/

**Comment by lagru** [comment]
This seems resolved now, so closing it. @joshuacwnewton, please re-open if the issue persists! 
Thank you @jarrodmillman for the release work. :D
