### ISSUE TITLE
morphology.thin change the original image from version 0.23

### ISSUE THREAD

**Issue by Jimmy228676** [scikit-image/scikit-image#7457]
### Description:

From version 0.23 document, the original image changes into thinned image.
https://scikit-image.org/docs/0.23.x/auto_examples/edges/plot_skeleton.html
![image](https://github.com/scikit-image/scikit-image/assets/72567578/e447b924-5ab8-49fb-9ac1-5dc024ee0f10)

In version 0.22, it seems ok.
https://scikit-image.org/docs/0.22.x/auto_examples/edges/plot_skeleton.html
![image](https://github.com/scikit-image/scikit-image/assets/72567578/9dd6243c-670a-4eee-8be4-21c97b9bbe55)

**Comment by jni** [comment]
Wow that's a pretty big bug. I don't think any of our functions should modify the input array unless explicitly requested by the user.
