### ISSUE TITLE
Wrong regex for generate_requirements files in pre-commit hook config

### ISSUE THREAD

**Issue by MarcBresson** [scikit-image/scikit-image#7460]
### Description:

Your current hook looks like

```yaml
  - repo: local
    hooks:
      - id: generate_requirements.py
        name: generate_requirements.py
        language: system
        entry: python tools/generate_requirements.py
        files: "pyproject.toml|requirements/.*\\.txt|tools/generate_requirements.py"
```

but I think `requirements/.*\\.txt` does not do what you want. To match any _.txt_ file inside the _requirements_ folder, you need to have `requirements/.*.txt`.

### Way to reproduce:

change a .txt file in the requirements folder, stage it, and see if the hook runs with `pre-commit run`

### Version information:

```Shell
>>> import sys; print(sys.version)
3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
>>> import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')macOS-14.4.1-arm64-arm-64bit
>>> import skimage; print(f'scikit-image version: {skimage.__version__}')
scikit-image version: 0.19.3
>>> import numpy; print(f'numpy version: {numpy.__version__}')
numpy version: 1.24.4
```

**Comment by stefanv** [comment]
Thanks Marc, we'll take a look. The suggested version also doesn't seem correct, though: dot cannot mean "full stop" and "any character" at the same time, so surely one needs to be escaped?

**Comment by MarcBresson** [comment]
with my version, I just tested :

- creating a file test.something, and it did not trigger the hook
- creating a file test.txt, and it did trigger the hook

For the current version of the hook in this repo, but the hook never triggered

**Comment by stefanv** [comment]
I think creating a new `.txt` file is not enough; you have to also stage the file before it triggers the pre-commit hook. It looks to me like the existing version does what it is supposed to; do you mind checking again? If you still observe that behavior, can you describe the steps you use to see the difference?

**Comment by MarcBresson** [comment]
I'm terribly confused. The requirements broke because it did not update on a personal project, and I when I tested the regex, I thought it was it.

But now that I'm trying to re-reproduce the bug, I can't do it, and your current version works.

I'm deeply sorry for that false alert. I'm gonna decline the associated PR.

**Comment by stefanv** [comment]
Hey, no worries at all. I'm so appreciative of your efforts and willingness to contribute.
