### ISSUE TITLE
skimage.draw.ellipsoid_stats doesn't give the result for a sphere if a=b=c

### ISSUE THREAD

**Issue by pamitabh** [scikit-image/scikit-image#7472]
### Description:
Calculation of surface area and volume using skimage.draw.ellipsoid_stats doesn't converge to the properties of a sphere. 

## Expected
We should get the surface area of a sphere when the three major axis dimensions (a, b, c) are same 

## Result
Get a divide by zero error

### Way to reproduce:

```python
import skimage as ski

a = b = c = 10
ellipsoid = ski.draw.ellipsoid(a, b, c)
vol, surf = ski.draw.ellipsoid_stats(a, b, c)
print(f'Theoritical volume = {vol}\nTheoritical Surface Area = {surf}')```

##Error Message
Traceback (most recent call last):
  File "c:\Users\...\test.py", line 5, in <module>
    vol, surf = ski.draw.ellipsoid_stats(a, b, c)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\Lib\site-packages\skimage\draw\draw3d.py", line 105, in ellipsoid_stats
    m = (a ** 2 * (b ** 2 - c ** 2) /
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ZeroDivisionError: float division by zero

### Version information:

```Shell
3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)]
Windows-11-10.0.22631-SP0
scikit-image version: 0.22.0
numpy version: 1.26.4
```

**Comment by stefanv** [comment]
Thanks for reporting @pamitabh. I can't reproduce with skimage 0.24.

**Comment by stefanv** [comment]
The surface area can be expressed in terms of $R_G$, one of the Carlson forms of the elliptic integals, which is [implemented in SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.elliprg.html#scipy-special-elliprg).

This should take care of the `a == b == c` degeneracy that plagues the denumerator of the current formula.

**Comment by stefanv** [comment]
```
In [34]: 4 * np.pi * a * b * c * sp.special.elliprg(1/a**2, 1/b**2, 1/c**2)
Out[34]: 1256.637061435917

In [35]: ski.draw.ellipsoid_stats(10, 10, 10 + 1e-6)
Out[35]: (4188.79062366541, 1256.6371452898388)
```

**Comment by pamitabh** [comment]
@stefanv  thanks for the quick fix! I think the function documentation should mention which surface area calculation method/formula is being used.

**Comment by stefanv** [comment]
Perhaps, although we don't typically do that unless there is a specific / known method involved. I'll let @mkcor weigh in on that.

**Comment by pamitabh** [comment]
> Perhaps, although we don't typically do that unless there is a specific / known method involved.
Got it! Can you provide a source for the Carlson's symmetric form of the elliptic integral used in the implementation, a quick search didn't bring up anything.

**Comment by stefanv** [comment]
https://en.m.wikipedia.org/wiki/Ellipsoid

**Comment by pamitabh** [comment]
> https://en.m.wikipedia.org/wiki/Ellipsoid

The Carson's symmetric integral form doesn't have any primary source on wikipedia.

**Comment by mkcor** [comment]
@pamitabh you can find primary sources under section "References" at the [SciPy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.elliprg.html#scipy-special-elliprg) which @stefanv pointed to.

**Comment by pamitabh** [comment]
@mkcor The scipy docs and references are for writing the incomplete elliptic integrals in carlson's symmetric form. I couldn't find any references for the formula used to express the **Surface area of the ellipsoid** using Carlson's symmetric integral **Rg**. I don't think that it is trivial but happy to be proven wrong!

**Comment by pamitabh** [comment]
@mkcor @stefanv  okay I found a derivation for the **Surface area of an ellipse** in terms of Carlson's symmetric integral **Rg** [here]( https://analyticphysics.com/Mathematical%20Methods/Surface%20Area%20of%20an%20Ellipsoid.htm). The last equation along with the property of **Rg**  [here](https://dlmf.nist.gov/19.20.ii), gives the formula used in the [wikipedia article](https://en.m.wikipedia.org/wiki/Ellipsoid) and this commit.

**Comment by mkcor** [comment]
Thank you, @pamitabh!

Too bad there is a typo right in: "... the Carlson completely symmetric integral [second kind](https://analyticphysics.com/Special%20Functions/Carlson%20Symmetric%20Elliptic%20Integrals.htm#legendre-rg) of the" (instead of "... the Carlson completely symmetric integral of the [second kind](https://analyticphysics.com/Special%20Functions/Carlson%20Symmetric%20Elliptic%20Integrals.htm#legendre-rg)"). :roll_eyes:

**Comment by pamitabh** [comment]
@mkcor I couldn't find any typo in the link that you shared ([second kind](https://analyticphysics.com/Special%20Functions/Carlson%20Symmetric%20Elliptic%20Integrals.htm#legendre-rg))

**Comment by mkcor** [comment]
@pamitabh nevermind, it's not the link, it's "integral second kind of the" which was meant to be "integral of the second kind" :upside_down_face: 

Now I'm hesitating between writing

$$S = 4 \pi a b c R_G\left(a^{-2}, b^{-2}, c^{-2}\right)$$

(as I was about to) and

$$S = 4 \pi b c R_G\left(1, \frac{a^2}{b^2}, \frac{a^2}{c^2}\right)$$

which is similar to the reference you provided and has the advantage, in my opinion, to be transparent dimension-wise: $R_G$ is dimensionless (which is cleaner) and it's clear from the $b c$ product that we have indeed a surface area.

**Comment by pamitabh** [comment]
I like the dimension argument!

**Comment by mkcor** [comment]
Ok, even if the code is
```py
surf = 4 * np.pi * a * b * c * elliprg(1 / a**2, 1 / b**2, 1 / c**2)
```
? Maybe I can write the sentence(s) in such a way that it doesn't imply "this is how it's implemented" but just "R_G is implemented as ..."

**Comment by pamitabh** [comment]
Isn't this the same as your comment [here ](https://github.com/scikit-image/scikit-image/pull/7473/commits/231ae4ad81edebbe1a5137c571b3b60c7de92d61#r1685060614) but with volume explicitly written out? I am fine with either one, but have a slight preference for the equation with R_g(1, a**2/b**2, a**2/c**2) due to the reasons that it's dimensionally clearer and it has a source that can be put in the docs.

**Comment by mkcor** [comment]
Well, there are two things (two levels):

* one is about background / context / motivation (potentially) for the function at hand: In this case, it's the fact that the expression for the surface area of an ellipsoid is not trivial + there are several possible expressions out there; so we share which one we have gone for, i.e., the one which uses a Carlson symmetric elliptic integral; basically, it's the math;
* the other one is about how our Python function (in this case, `ellipsoid_stats`) implements the above; basically, it's the implementation details.

In general you don't have to document both levels; it depends. I was just noticing, from our conversation, that both levels were being referred to.
