### ISSUE TITLE
Unexpected Core Dump When Executing inpaint_biharmonic

### ISSUE THREAD

**Issue by montgomerymao** [scikit-image/scikit-image#7474]
### Description:

I experienced a memory crash(?) when executing inpaint_biharmonic.
The attached [data.zip](https://github.com/user-attachments/files/16302311/data.zip) are the data I used. (Files that start with 'slice_defect' are the image arrays for fixing. Files that start with 'mask' are the arrays of masks. The numbers are the indexes)
When the index is 15, there is no problem:
![screenshot_15](https://github.com/user-attachments/assets/1ebdb431-453e-4f12-967f-4101dab6b69a)
When the index is 35, it displayed 'Not enough memory to perform factorization', and the program terminated:
![screenshot_35](https://github.com/user-attachments/assets/2414dc9a-5072-48a4-84f3-576cae81369a)

I tried them on a linux workstation with 256G RAM, and get the similar result:
![Screenshot from 2024-07-19 13-26-01](https://github.com/user-attachments/assets/9c38885b-f8e4-4850-ab0b-870608d2adc8)

I'm not sure if  is a bug or dues to a wrong way of using the inpainting function.

### Way to reproduce:

```python
import numpy as np
from skimage.restoration import inpaint

# for index 15
slice_defect = np.load('./slice_defect_15.npy')
mask = np.load('./mask_15.npy')
slice_inpaint = inpaint.inpaint_biharmonic(slice_defect, mask, channel_axis=-1)

# for index 35
slice_defect = np.load('./slice_defect_35.npy')
mask = np.load('./mask_35.npy')
slice_inpaint = inpaint.inpaint_biharmonic(slice_defect, mask, channel_axis=-1)
```

### Version information:

```Shell
3.9.16 (main, May 17 2023, 17:49:16) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: 0.22.0
numpy version: 1.26.4
```

**Comment by stefanv** [comment]
Looks the process runs out of memory. We'll take a look and find out why!

**Comment by montgomerymao** [comment]
Any progress?

**Comment by stefanv** [comment]
I don't think anyone is working on this issue actively; I'm afraid there's a sizable backlog of items we need to pay attention to.

I can verify the problem on my machine. I see some additional information:

```
Not enough memory to perform factorization.
sgstrf
```

So, looks like it happens during the SuperLU factorization, likely here:

https://github.com/scikit-image/scikit-image/blob/main/skimage/restoration/inpaint.py#L189

Since the problem is data, and not size, dependent, the matrix must have some problematic structure.

**Comment by stefanv** [comment]
As a workaround, perhaps you can do the inpainting in blocks:

```
As a workaround, perhaps you can do the inpainting in blocks:

```
N1 = 1000; N2 = N1 + 1000; ski.restoration.inpaint_biharmonic(X[N1:N2], mask[N1:N2], channel_axis=-1)
```

I am able to step through the entire array that way without a problem.

**Comment by stefanv** [comment]
My best guess right now is that the matrix that needs to be factorized simply becomes to big, hence why you can break the operation up and it works just fine:

In [30]: np.load('mask_15.npy').sum()
Out[30]: 5323457

In [31]: np.load('mask_35.npy').sum()
Out[31]: 6093439

**Comment by montgomerymao** [comment]
Issue solved. Many thanks.

**Comment by stefanv** [comment]
@montgomerymao What solved your issue, in the end?

**Comment by montgomerymao** [comment]
> My best guess right now is that the matrix that needs to be factorized simply becomes to big, hence why you can break the operation up and it works just fine:
> 
> ```
> In [30]: np.load('mask_15.npy').sum()
> Out[30]: 5323457
> 
> In [31]: np.load('mask_35.npy').sum()
> Out[31]: 6093439
> ```

@stefanv Following your comment, I reduced the sizes of the arrays for inpainting and the corresponding mask arrays. I tested with my data, and there was no error message as long as the number of 1 in the mask was small enough (for example, < 5M). So for me the issue is solved, although I don't know why this works.
