### ISSUE TITLE
autosummary.import_cycle warning breaks doc build on Windows CI

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#7485]
For some time now our doc building on Azure has been [broken because of a warning](https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=11464&view=logs&j=5b382255-19bb-59b2-9a36-539f25119b1b&t=41245e71-1633-5278-7581-af00eac25284&l=1092)

```
Warning, treated as error:
Summarised items should not include the current module. Replace 'skimage.color' with 'color'. [autosummary.import_cycle]
```
This seems related to recent changes on Sphinx's side. https://github.com/sphinx-doc/sphinx/issues/12589 claims it's [fixed for 7.4.6](https://github.com/sphinx-doc/sphinx/issues/12589#issuecomment-2236378063) but we are [still seeing this error using 7.4.7](https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=11464&view=logs&j=5b382255-19bb-59b2-9a36-539f25119b1b&t=41245e71-1633-5278-7581-af00eac25284&l=386). 

Throwing a debugger at this it seems like the warning is triggered when parsing this line https://github.com/scikit-image/scikit-image/blob/6e232f42376e11997ace56edaf80f2298a92a2f6/skimage/feature/corner.py#L1142

And indeed, setting `default_role = "py:obj"` like suggested in https://github.com/sphinx-doc/sphinx/issues/12589#issuecomment-2241091656 removes the warning. I'm not sure yet if this is the proper way to address the issue.

**Comment by lagru** [comment]
https://github.com/scikit-image/scikit-image/pull/7486 changed the default role to address the warning. However, this may not be a proper fix. We will have to monitor https://github.com/sphinx-doc/sphinx/issues/12589 and see how that issue is resolved.

**Comment by stefanv** [comment]
I just built with 8.0.2 and didn't see any warnings.

**Comment by stefanv** [comment]
@lagru All resolved?

**Comment by lagru** [comment]
Yes, it seems resolved now. Can always reopen if this resurfaces. :)
