### ISSUE TITLE
`filters.threshold_triangle` fails for Dask 2024.8 with "unkown chunk size"

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#7491]
Since our CI pulls in Dask 2024.8, the test `filters/tests/test_thresholding.py::test_thresholds_dask_compatibility[threshold_triangle-41-43]` fails with 
```plain
ValueError: Array chunk size or shape is unknown. 

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`
```
The error is actually triggered in this line https://github.com/scikit-image/scikit-image/blob/b3c70efc3052a613957813182354b0801e64b5ec/skimage/filters/thresholding.py#L958

when trying to index the result of `flatzero`. From reading the docs it makes sense that this might fail. However, I haven't figured out why it worked fine before with Dask 2024.7.

The suggested fixes by the error message points to also aren't ideal, I'd like avoid having a custom code path in our code just for Dask support.

**Comment by lagru** [comment]
I reached out to upstream in https://github.com/dask/dask/issues/11298.

**Comment by stefanv** [comment]
@lagru What's the status of this? I still see dask related failures on `main`.
