### ISSUE TITLE
pytest-runner deprecated?

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#7494]
Does anyone know what we use pytest-runner for? Tidelift let me know that the project has been archived:

https://github.com/pytest-dev/pytest-runner/

**Comment by lagru** [comment]
`git log -S pytest-runner` tells me that it was first mentioned / used in https://github.com/scikit-image/scikit-image/commit/63e8e0c672a3c21a8e477e1a064e861f457e5bee when upgrading from sphinx<1.6.

From the project description it seems related to `setup.py` and `setuptools` shenanigans, both of which we no longer use. I'm guessing that it's safe to remove now.
