### ISSUE TITLE
About the PyWavelets not installed error

### ISSUE THREAD

**Issue by ibilgen** [scikit-image/scikit-image#7498]
### Description:

I encountered a ImportError about 'pywt' package.  As I see in the _denoise.py script that this issue was handled by raising an error remarking to install PyWavelets module. Shouldn't skimage install this package as a dependency?

**Comment by stefanv** [comment]
Hi @ibilgen, thanks for your comment. Skimage has dependencies and *optional* dependencies. The latter are for less used, non-core functionality, and includes PyWavelets.

Was the error message enough to guide you to the solution? If not, that's something we should fix.

**Comment by ibilgen** [comment]
Yes, the message was pretty informative and helped to solve the issue. After installing PyWavelets package, the code executed without a problem. 

Thanks
