### ISSUE TITLE
One of our doc dependencies brings in numpy < 2

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#7500]

**Comment by mkcor** [comment]
That would be one among https://github.com/scikit-image/scikit-image/blob/f1892afb76e60b6fe41cf0c73be97f918581aa33/requirements/docs.txt but you haven't spotted which one? To investigate then...

**Comment by lagru** [comment]
Where did you see this issue? I can neither see it in our [CI building the docs](https://github.com/scikit-image/scikit-image/actions/runs/10597910754/job/29369168182) nor if I install all of our dependencies locally...

**Comment by stefanv** [comment]
I can't reproduce this any more.
