### ISSUE TITLE
`io.show` only shows the last image on macOS (M2)

### ISSUE THREAD

**Issue by pantheraleo-7** [scikit-image/scikit-image#7504]
### Description:

might be related: [#599](https://github.com/scikit-image/scikit-image/issues/599)

Documentation says that `io.show` displays all 'pending' images, so I was trying to display multiple images queued via `io.imshow` with a single `io.show` call at the end. But, if run via terminal as a script, a single matplotlib window opens with just one plot and the arrow keys [in the window] don't do anything, and when run in an interactive session, a single inline plot is output.

interactive:
<img width="636" alt="image" src="https://github.com/user-attachments/assets/8420a8e3-8a50-43c7-90a3-20c19a0d307a">

non-interactive:
<img width="638" alt="image" src="https://github.com/user-attachments/assets/7d073f40-ae39-4a8e-aa5b-d8aa64f38f34">
*the arrow keys at the bottom left do not do anything

### Way to reproduce:
```
from skimage import io

img1 = io.imread('forest.webp')
img2 = io.imread('olympic.png')

io.imshow(img1)
io.imshow(img2) # only this gets displayed
io.show()
```

### Version information:

```Shell
3.12.5 (main, Aug 11 2024, 16:53:33) [Clang 15.0.0 (clang-1500.3.9.4)]
macOS-14.6.1-arm64-arm-64bit
scikit-image version: 0.24.0
numpy version: 2.1.0
```

**Comment by michaelbratsch** [comment]
It is the same behaviour as one gets with matplotlib:
```python
import matplotlib.pyplot as plt

moon = data.moon()
camera = data.camera()
#plt.figure()
plt.imshow(moon)
#plt.figure()
plt.imshow(camera)

plt.show()
```
depending on the use of `plt.figure()`, a new plot is opened otherwise the image in the current figure is overwritten.

Funnily there has been a pull-request in the past to create a new figure for each image to display https://github.com/scikit-image/scikit-image/pull/1281 but it has been revoked by:

```
commit c6dff6942d88f54182797f10862d5e2568f11399
Author: Juan Nunez-Iglesias <juan.n@unimelb.edu.au>
Date:   Thu Jan 15 22:26:55 2015 +1100

    Don't create new plot automatically
    
    This behavior is a bit too magical and may interfere with creation of
    interactive ImageCollection browsers, for example
```

**Comment by stefanv** [comment]
We are in the process of moving away from our plugin system. These made sense in the early days of skimage, but now there are enough good libraries available that we can make opinionated choices. We'll probably keep `io.imread` (via `imageio`), but I think getting rid of `io.imshow` makes sense, given that image visualization happens on such a wide variety of interactive and non-interactive platforms.

As it is deprecated, we can recommend using matplotlib directly: `f, ax = plt.subplots(); ax.imshow(arr)` instead.

**Comment by lagru** [comment]
Let's keep this open until we release 0.25 which includes the deprecation from https://github.com/scikit-image/scikit-image/pull/7508.

**Comment by lagru** [comment]
We are preparing the release soon. So closing it already.
