### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by cyberfantics** [scikit-image/scikit-image#7506]
### Description:

I encountered this error despite having installed the latest version of the scikit-image library: 'ModuleNotFoundError: No module named ‘skimage.morphology._skeletonize_lee_cy’.

### Version information:

```Shell
3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: 0.24.1rc0.dev0
numpy version: 1.26.4
```

**Comment by lagru** [comment]
Thanks for reaching out. Could you please include the full traceback and the line that is triggering it?

**Comment by soupault** [comment]
Closing as stale. @cyberfantics feel free reopen with the requested details, thanks!
