### ISSUE TITLE
Back-references for sphinx gallery examples are missing in dev docs

### ISSUE THREAD

**Issue by lagru** [scikit-image/scikit-image#7543]
I noticed that the back-references to sphinx gallery examples seem to be missing from our docs. E.g. compare the [docs dev version](https://scikit-image.org/docs/dev/api/skimage.data.html#skimage.data.coins) with the [stable one](https://scikit-image.org/docs/stable/api/skimage.data.html#skimage.data.coins).

**Comment by mkcor** [comment]
Right... My first guess would be the pydata-sphinx-theme update #7511?
