### ISSUE TITLE
Inquiry About Deploying scikit-image Website in China

### ISSUE THREAD

**Issue by PmcFizz** [scikit-image/scikit-image#7559]
### Description:

Dear scikit-image team,

I hope this message finds you well.

I am writing to express my admiration for the scikit-image project and its incredible contributions to the field of image processing. Due to restrictions with internet access in China, it can sometimes be challenging to access your official website, especially for users within the country who rely on your documentation and resources for their work.

I would like to ask for your permission to deploy a mirror or localized version of your website in China. The goal is to ensure that more developers and researchers in China can easily access scikit-image’s documentation and resources. Of course, I would comply with your guidelines and ensure that the deployment accurately reflects your content and branding.

Please let me know your thoughts on this proposal and if there are any specific steps or requirements I should follow.

Thank you for your time, and I look forward to your response.
Best regards

**Comment by lagru** [comment]
Thanks for checking in with us and offering! I'll check in with the team. 

Is there anything we can do on our side to help users access our website?

And if we feel comfortable with your request, is there anything we can do to make that process easier? I'm guessing we wouldn't be able to control the content of the mirror, right?

**Comment by stefanv** [comment]
I think there are two questions here: mirror, and localized content. Localized content should happen via the Scientific Python translation infrastructure, and for that we have to switch the website to Hugo (which is on our roadmap). For hosting a mirror, there are some more subtle issues, such as ensuring readers know the original source of the material. How will the website be deployed to advertise where the content came from?
