### ISSUE TITLE
rgb2ind

### ISSUE THREAD

**Issue by alexsavio** [scikit-image/scikit-image#758]
Hi,

I'm interested in developing functions to transform images to indexed formats using these Scipy algorithms of kmeans and vector quantization.

I'm thinking of programming the function rgb2ind similar to Matlab:
http://www.mathworks.com/help/matlab/ref/rgb2ind.html

Are you interested? Where in the scikit-image code should I put this function?

Cheers,
Alex

**Comment by soupault** [comment]
@alexsavio Hi! Is there still an interest in this?

**Comment by alexsavio** [comment]
OMG A 2-years old issue. Sorry, I am not working on this currently.

Are you interested on this?

On Sat, 5 Mar 2016 11:05 Egor Panfilov, <notifications@github.com> wrote:

> @alexsavio <https://github.com/alexsavio> Hi! Is there still an interest
> in this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scikit-image/scikit-image/issues/758#issuecomment-192615766>
> .
>
-- 

Sent from my phone, sorry for brevity or typos.

**Comment by soupault** [comment]
This one has a bad luck, for sure :laughing: .
No, I'm rather interested in closing this issue. Would you agree?

**Comment by alexsavio** [comment]
Yes, please close it. Maybe I will have it solved in a couple of years.
Thanks!

On Sat, 5 Mar 2016 17:05 Egor Panfilov, <notifications@github.com> wrote:

> This one has a bad luck, for sure [image: :laughing:] .
> No, I'm rather interested in closing this issue. Would you agree?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scikit-image/scikit-image/issues/758#issuecomment-192679409>
> .
>
-- 

Sent from my phone, sorry for brevity or typos.
