### ISSUE TITLE
KeyError in _regionprops.py during Documentation Installation (__debug__) in Python 3.13

### ISSUE THREAD

**Issue by ticdenis** [scikit-image/scikit-image#7585]
When running tests on Python 3.13, a KeyError occurs in the skimage.measure._regionprops module during the installation of property documentation via _install_properties_docs(). The error is specifically triggered by an attempt to assign a documentation string to a non-existent or mismatched property, area_bbox, in the RegionProperties class.

The root cause appears to be that `__debug__` is enabled by default when running tests. This leads to the installation of the documentation even when `__debug__` is used to determine test-related behavior. The code might rely on the assumption that certain properties or keys exist, but they are either renamed or not present in this particular Python version or skimage release.

The error occurs in the following code: ([link](https://github.com/scikit-image/scikit-image/blob/1eec6600128e8db85531406d5c5cb00e3d2c61d3/skimage/measure/_regionprops.py#L1435))
```python3
getattr(RegionProperties, p).__doc__ = prop_doc[p]
```

Might be related to: https://github.com/scikit-image/scikit-image/pull/7463/files#r1678135375

The error:

```python3
/usr/local/lib/python3.13/site-packages/skimage/measure/_regionprops.py:1426: in <module>
    _install_properties_docs()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def _install_properties_docs():
        prop_doc = _parse_docs()
    
        for p in [member for member in dir(RegionProperties) if not member.startswith('_')]:
>           getattr(RegionProperties, p).__doc__ = prop_doc[p]
E           KeyError: 'area_bbox'

/usr/local/lib/python3.13/site-packages/skimage/measure/_regionprops.py:1421: KeyError
```

Also I'm trying to patching it but is not working...

```python3
from pytest import fixture
from unittest.mock import patch

@fixture(autouse=True)
def patch_install_properties_docs():
    print("Patching _install_properties_docs")
    with patch('skimage.measure._regionprops._install_properties_docs', lambda: None):
        yield
    print("Unpatching _install_properties_docs")
```

**Comment by mkcor** [comment]
Thanks for reporting, @ticdenis!

> The code might rely on the assumption that certain properties or keys exist, but they are either renamed or not present in this particular Python version or skimage release.

In this case, `area_bbox` is the current name, which should be available in `RegionProperties`:

https://github.com/scikit-image/scikit-image/blob/76490395683e892d1ab366971a0850f15e629956/skimage/measure/_regionprops.py#L450-L452

`BoundingBoxArea` or `bbox_area` would be old names:

https://github.com/scikit-image/scikit-image/blob/76490395683e892d1ab366971a0850f15e629956/skimage/measure/_regionprops.py#L33-L34

Let's keep investigating... :eyes:

**Comment by ticdenis** [comment]
> Thanks for reporting, @ticdenis!
> 
> > The code might rely on the assumption that certain properties or keys exist, but they are either renamed or not present in this particular Python version or skimage release.
> 
> In this case, `area_bbox` is the current name, which should be available in `RegionProperties`:
> 
> https://github.com/scikit-image/scikit-image/blob/76490395683e892d1ab366971a0850f15e629956/skimage/measure/_regionprops.py#L450-L452
> 
> `BoundingBoxArea` or `bbox_area` would be old names:
> 
> https://github.com/scikit-image/scikit-image/blob/76490395683e892d1ab366971a0850f15e629956/skimage/measure/_regionprops.py#L33-L34
> 
> Let's keep investigating... 👀

Thanks for the clarification.

By the way, my installed version is:

```toml
dependencies = [
  deskew==1.5.1", # installs scikit-image<=0.24 
]
```

**Comment by jarrodmillman** [comment]
`scikit-image<=0.24` doesn't support Python 3.13.  Support for Python 3.13 will be provided by `scikit-image==0.25`:
https://github.com/scikit-image/scikit-image/milestone/29

Here is a pre-release:
https://pypi.org/project/scikit-image/0.25.0rc1/

We will have one more pre-release before 0.25 final.

**Comment by PierreRaybaut** [comment]
Hi `scikit-image` friends,

Just bumped into this `KeyError: 'area_bbox'` issue while preparing the next release of [DataLab](https://datalab-platform.com) which—as you may know—relies on `scikit-image` for many image processing features.

@jarrodmillman: Could you share an estimated release date for version 0.25 with Python 3.13 support?
This would help me decide whether to wait for it in the upcoming DataLab release or plan Python 3.13 support for a later version.

Thanks a lot.
Pierre

**Comment by jarrodmillman** [comment]
I am looking into a couple of issues (e.g., our CI system is failing now). We should be close to making the new release and I will try to get an estimate by the end of the day.

**Comment by stefanv** [comment]
Will be solved with imminent release. Milestone is now empty 🎉
