### ISSUE TITLE
Support for Python 3.13

### ISSUE THREAD

**Issue by tifdes** [scikit-image/scikit-image#7596]
### Description:

I'm running into issues installing scikit. I'm on windows 11. I'm using VSCode + Python 13.3. This is working on my laptop, but I'd like to work on my desktop, and it is just not cooperating there.

I went through the listed dependencies and installed the necessary packages, all without issue. It keeps failing in the "generate metadata" portion. I had pip put out a log to try to trace the issue, but it's almost 11k lines long, so I'm not sure if it's worth uploading as well. 

I'll post here the portion where pip shows the failure, in case it's useful. Note I'm new to python. 

Thanks!

### Way to reproduce:

pip install scikit-image

[136/171] Generating 'skimage\\filters\\rank\\generic_cy.cp313-win_amd64.pyd.p\\generic_cy.c'
[137/171] Generating 'skimage\\transform\\_warps_cy.cp313-win_amd64.pyd.p\\_warps_cy.c'
ninja: build stopped: subcommand failed.
Activating VS 17.11.5
INFO: automatically activated MSVC compiler environment
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: C:\Users\...\AppData\Local\Temp\pip-build-env-pscyvwjh\normal\Scripts\ninja.EXE
ERROR: Preparing metadata (pyproject.toml) exited with 1

### Version information:

```Shell
3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]
Windows-11-10.0.22631-SP0
NameError: name 'skimage' is not defined
numpy version: 2.1.2
```

**Comment by jarrodmillman** [comment]
`scikit-image<=0.24` doesn't support Python 3.13.  Support for Python 3.13 will be provided by `scikit-image==0.25`:
https://github.com/scikit-image/scikit-image/milestone/29

Here is a pre-release:
https://pypi.org/project/scikit-image/0.25.0rc1/

We will have one more pre-release before 0.25 final.

**Comment by tifdes** [comment]
Ahh ok! Ty! I managed to install an older version of python and it did install. Turns out my laptop has two versions installed, which is a mystery to me, since I only downloaded 3.13, It defaulted to the older one. 

Ty!

**Comment by michealroberts** [comment]
@jarrodmillman Just a quick sense check, is 3.12 not supported either by 0.24.0 ... it looks to fail on the same error for 3.12.4 ...

**Comment by WilliamJamieson** [comment]
> `scikit-image<=0.24` doesn't support Python 3.13. Support for Python 3.13 will be provided by `scikit-image==0.25`: [scikit-image/scikit-image/milestone/29](https://github.com/scikit-image/scikit-image/milestone/29)
> 
> Here is a pre-release: [pypi.org/project/scikit-image/0.25.0rc1](https://pypi.org/project/scikit-image/0.25.0rc1/)
> 
> We will have one more pre-release before 0.25 final.

Any idea about when 0.25 maybe released? `scikit-image` is the only thing blocking Python 3.13 support for some of the packages I maintain.

**Comment by stefanv** [comment]
We've been working steadily on getting the release out (see https://github.com/scikit-image/scikit-image/milestone/29). Almost ready, and meanwhile you can pin to the pre-release if you absolutely need to.

**Comment by jarrodmillman** [comment]
We have a new release candidate: https://pypi.org/project/scikit-image/0.25.0rc2/

If there are no issues, we will release 0.25.0 in a few days.
