### ISSUE TITLE
Expose clip_negative as a parameter of rescale_intensithy

### ISSUE THREAD

**Issue by gnodar01** [scikit-image/scikit-image#7620]
### Description:

`skimage.exposure.rescale_intensity(image, in_range='dtype', out_range='float32'` will take an input image with `dtype` of `int[8,16,32,64]` and scale to be in the range of `[-1,1]`. This is the normal and expected behavior, but I would actually like it to scale in the range of `[0,1]` (as in the case for unsigned integers). I realize this is strange. Why have a signed image as input if I don't want to preserve negative values? The reason is that I am normalizing images from users / external sources, and I *need* all of my images to be in the range of `[0,1]` for subsequent operations. I currently just do the correction after the fact, but would prefer to avoid the extra cpu cycles.

As far as I can tell, the difference in behavior for unsigned and signed integers is captured by the `clip_negative` value that is passed on to `intensity_range`.

```
    omin, omax = map(float, intensity_range(image, out_range,
                                            clip_negative=(imin >= 0)))
```

It would be nice to expose this as an overridable parameter to `rescale_intensity` itself, so that I can force it to be `True` regardless of `imin`'s value.

I would be happy to open a PR. Just want to first make sure this is acceptable, given that it is an esoteric request, before going through the trouble.

**Comment by gnodar01** [comment]
Never mind. My brain didn't register that I can pass in a tuple as an arg for `out_range`.

**Comment by lagru** [comment]
That happens. Happy that you found a solution. :blush:
