### ISSUE TITLE
KeyError: 'area_bbox' when importing measure.regionprops

### ISSUE THREAD

**Issue by MaxNentwich** [scikit-image/scikit-image#7621]
### Description:

Hi, I am getting this key error when importing regionprops. 

```
Traceback (most recent call last):

  Cell In[11], line 1
    from skimage.measure import regionprops

  File <frozen importlib._bootstrap>:1412 in _handle_fromlist

  File ~/miniconda3/envs/attention_states/lib/python3.13/site-packages/lazy_loader/__init__.py:82 in __getattr__
    submod = importlib.import_module(submod_path)

  File ~/miniconda3/envs/attention_states/lib/python3.13/importlib/__init__.py:88 in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File ~/miniconda3/envs/attention_states/lib/python3.13/site-packages/skimage/measure/_regionprops.py:1426
    _install_properties_docs()

  File ~/miniconda3/envs/attention_states/lib/python3.13/site-packages/skimage/measure/_regionprops.py:1421 in _install_properties_docs
    getattr(RegionProperties, p).__doc__ = prop_doc[p]

KeyError: 'area_bbox'
```

I have recently updated my system and the scikit-image version I use. Is there any compatibility issue that you are aware of? 
I have tried installing older versions down to 0.21.0.

### Way to reproduce:

```from skimage.measure import regionprops```

### Version information:

```Shell
3.13.0 | packaged by Anaconda, Inc. | (main, Oct  7 2024, 21:29:38) [GCC 11.2.0]
Linux-6.8.0-49-generic-x86_64-with-glibc2.39
scikit-image version: 0.24.0
numpy version: 2.1.3
```

**Comment by MaxNentwich** [comment]
As a workaround I added an empty line after

```
    **area** : float
        Area of the region i.e. number of pixels of the region scaled by pixel-area.
```
in the regionprops function. Then prop_doc in _parse_docs() works. 

But I can see that the _parse_docs() function on github has and edit, that I assume fixes this. 

This is what I have:
```
def _parse_docs():
    import re
    import textwrap

    doc = regionprops.__doc__ or ''
    matches = re.finditer(
        r'\*\*(\w+)\*\* \:.*?\n(.*?)(?=\n    [\*\S]+)', doc, flags=re.DOTALL
    )
    prop_doc = {m.group(1): textwrap.dedent(m.group(2)) for m in matches}

    return prop_doc
```

**Comment by hmaarrfk** [comment]
you should recreate your environment with python 3.12 or 3.11.

We have some known incompatibilities with Python 3.13 (and likely many other packages will have some incompatibility as well).

**Comment by lagru** [comment]
Our next release has been delayed somewhat, but this should be addressed, once we get 0.25 out. For now, if you want you could explicitly install the latest release candidate with `pip install scikit-image==0.25.0rc1`.

**Comment by lagru** [comment]
Also reported in https://github.com/scikit-image/scikit-image/issues/7585

**Comment by MaxNentwich** [comment]
Thanks, it works with the release candidate!
