### ISSUE TITLE
Any interest in output functionality for 3D STL files?

### ISSUE THREAD

**Issue by thearn** [scikit-image/scikit-image#763]
I've been working on some python code that processes images in python to produce STL files for 3D printing 

https://github.com/thearn/stl_tools

Any interest in having this functionality in scikit-image (maybe under skimage.io)?

**Comment by emmanuelle** [comment]
This is a nice-to-have, but not at the core of scikit-image's goal (scientific image processing). Since no other people expressed interest, I would suggest to close this issue.

**Comment by hmaarrfk** [comment]
I don't really see the point in bundling image saving/plotting with image processing. They are two rather distinct tools.

I think an example would be cool and appropriate.

**Comment by soupault** [comment]
I agree with @emmanuelle, this is a nice feature, but should rather exist as a separate package.
