### ISSUE TITLE
Ignore test files for coveralls

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#826]
It does not make sense to produce coverage reports for test_*.py files... see e.g. https://coveralls.io/files/89556607.

**Comment by soupault** [comment]
Closing due to the lack of essence and activity.
Please, reopen if disagree.

**Comment by stefanv** [comment]
How do you ever reach 100% test coverage if your tests also need coverage? :)

**Comment by jni** [comment]
@stefanv the test scripts are considered covered when they run. The coverage drops when parts of your test scripts are not run. imho this is correct behaviour, as this might indicate an incorrectly written test.

**Comment by stefanv** [comment]
In that case, I agree with all said.

**Comment by JDWarner** [comment]
My understanding is that coverage is only reported from one CI build. This makes it functionally impossible to report true coverage thanks to tests skipped due to lack of optional dependencies at different places in the build matrix.

**Comment by stefanv** [comment]
We can add an entry to the test matrix that executes all unit tests.
Should be fairly straightforward.
