### ISSUE TITLE
TypeError: Image data can not convert to float

### ISSUE THREAD

**Issue by QCaudron** [scikit-image/scikit-image#842]
I apologise in advance, I'm sure this is an issue on my side rather than with skimage. However, I'm getting the following error on both 0.9.3 and 0.10dev :

TypeError: Image data can not convert to float

when trying to call io.imshow(), color.reg2grey(), or others. Full traceback is provided below. Matplotlib is on 1.3.1, everything else is up to date. I'm running OSX Maverick. The only thing I believe that has changed since all of my skimage code broke is that I updated XCode.

If I create an array using numpy, io.imshow() shows it correctly.

Traceback : http://pastebin.com/Bx66LExb

Thank you for any help ! Much appreciated.

**Comment by likeyiyy** [comment]
one reason of me is Matrix elements are imaginary

**Comment by swhshamsi** [comment]
What is that PIL linking issue?
I'm having the same problem here.

**Comment by QCaudron** [comment]
I can't honestly say I remember, sorry - this was three years ago. Ensure that you have PIL up to date and try rebuilding scikit-image, perhaps ?

**Comment by Firdaus2402** [comment]
???
