### ISSUE TITLE
Set up automatic update of the dev docs

### ISSUE THREAD

**Issue by cdeil** [scikit-image/scikit-image#883]
It would be really nice if someone could set up an automatic (per commit or nightly) build and push of the dev version of the scikit-image docs to http://scikit-image.org/docs/dev/ .

The current version is at least two months outdated (could be much more ... I don't see a date or  git commit version) because it doesn't contain the new `skimage.restoration` sub-package added in #800 .

I think having online docs especially for new functionality is important, so that users can give feedback before the API is solidified by a stable release.

Maybe http://readthedocs.org or a `cron` job on `scikit-image.org` or `ci.scipy.org` could be used for this?

**Comment by arve0** [comment]
Read the docs works, but is awfully slow. Build has been running for a day, but I'm unsure if it's been killed or failed, as examples is done, but API reference is not (a bit strange). Might though not be that a good solution, as it' slow and have limited feedback. Currently the build has no feedback after the installation.

http://scikit-image.readthedocs.org/en/latest/auto_examples/index.html

Here are the settings:
![skjermbilde 2015-02-25 kl 15 16 30](https://cloud.githubusercontent.com/assets/4810521/6372042/669c01fc-bd01-11e4-92b3-54ab6e945e6a.png)
![skjermbilde 2015-02-25 kl 15 16 41](https://cloud.githubusercontent.com/assets/4810521/6372044/679f5126-bd01-11e4-81cb-314d74cf4be8.png)
![skjermbilde 2015-02-25 kl 15 16 51](https://cloud.githubusercontent.com/assets/4810521/6372046/68962f96-bd01-11e4-82a0-f47da6c702ec.png)

**Comment by soupault** [comment]
Closing the issue as solved.
See https://github.com/scikit-image/scikit-image/issues/2005#issuecomment-198946609 for reference.
