### ISSUE TITLE
Regionprops equality

### ISSUE THREAD

**Issue by vighneshbirodkar** [scikit-image/scikit-image#965]
In #956 I addressed the equality of regionprops, which essentially compares all properties. We need a decorator for each function defined in the `_RegionProperties` class that would allow us to specify if a property is scale, rotation or translation invariant as @jni pointed out earlier.

The decorator would attach an extra attribute to each function, eg:`scale_invariant = True` so whenever required we can chack for `region.prop_xyz.scale_invariant` to determine if a property has to be compared or not.

To compare regionprops
1. The type of properties to be compared should be set by a method, like `skimage.set_compare_scale(True)` or
2. We could keep the `__eq__` method as it is and have seperate method for scale/rotation/translation invariant comparisons

**Comment by alexdesiqueira** [comment]
@vighneshbirodkar @stefanv @jni @ahojnnes thank you for the discussion on this one. I'll close it; if we're ready to re-discuss it, please reopen.

> One could also make the opposite argument, and say that we need to include
every single piece of known information about a parameter. Clearly, neither
extreme makes much sense.

My 2 :coin:: I like having all possible information accessible in one place only. It makes sense to me, but I'm an extreme myself :wink: Maybe you changed your mind, too — it's been _eight years_! :laughing:
