### ISSUE TITLE
LBP variance feature incorrectly computed

### ISSUE THREAD

**Issue by pberkes** [scikit-image/scikit-image#966]
I might be missing something here, but I think the `local_binary_pattern` algorithm for the `method='var'` is incorrectly computed.

The current implementation in `_texture.pyx` is

```
              if method == 'V':
                        var = np.var(texture)
                        if var != 0:
                            lbp /= var
                        else:
                            lbp = np.nan
```

which is not the formula given in the original paper (Ref 1, Eq 11), which is simply `var` in the code above.

In the paper, the authors go on talking about the joint distribution of LBP/VAR, but the `/` symbol seems to me to be just a matter of notation, meaning really `P(LBP, VAR)`. In the rest of the paper, they talk about discretizing VAR to compute a joint histogram over LBP and VAR, which is compatible with my interpretation.

[1] Multiresolution Gray-Scale and Rotation Invariant Texture Classification with Local Binary Patterns. Timo Ojala, Matti Pietikainen, Topi Maenpaa.

**Comment by marcelo-santos-12** [comment]
Could someone explain to me about the nan value in the code mentioned? 
And how could I compute the var LBP histogram?
