### ISSUE TITLE
threshold_adaptive: odd block_size justified? if yes, then no exception raised.

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#987]
Hi,

I played with threshold_adaptive and the docstring says that the block size must be odd (written uneven, is it common to say uneven?). I looked at the docstrings of ndimage and I didn't find that the functions used in threshold_adaptive need an odd argument. Maybe I missed something.

However, if one function needs an odd value and not the other, my suggestion would be to accept all values and to jump to a close odd value for the function and add a note in the docstring + an inline comment in the code as a reminder.

If we keep the constraint (odd values), then even values must raise an exception ValueError.

**Comment by OrkoHunter** [comment]
Regarding this issue, I'm not sure but would it be okay to step down (or up) the block_size if it's even and produce the result along with a very clear warning ? If there is no solution to this, then I think we should just raise a ValueError and leave.

**Comment by OrkoHunter** [comment]
The one [good example](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/segmentation/plot_threshold_adaptive.py#L29) for `threshold_adaptive`, and we use an even `block_size`. =P 
I don't know how this went unnoticed.

**Comment by JDWarner** [comment]
@OrkoHunter yikes, you're right!

**Comment by sciunto** [comment]
I prefer a ValueError exception. It's more explicit about the requirements of the algorithm.
Scipy does that. Exemple: https://github.com/scipy/scipy/blob/master/scipy/signal/_savitzky_golay.py#L10

**Comment by OrkoHunter** [comment]
I've fixed the example in #1907. Doctests will hopefully pass now.
