### ISSUE TITLE
Make it easy to browse example images

### ISSUE THREAD

**Issue by cdeil** [scikit-image/scikit-image#989]
It's very nice that `scikit-image` comes with example images in  [`skimage.data`](http://scikit-image.org/docs/dev/api/skimage.data.html)

In my opinion the following two changes would make it easier to browse and use them:
- [x] in the overview table and docstrings mention the shape and dtype. (closed via #2236)
- [x] Show a thumbnail (maybe show full image in new tab on click?) either as a collection in a separate section on this page or a Gallery page or with each API entry.

**Comment by soupault** [comment]
@stefanv Can we just add hyperlink to the docstrings (e.g. make some part of https://github.com/scikit-image/scikit-image/blob/master/skimage/data/__init__.py#L68-L73 a hyperlink to https://github.com/scikit-image/scikit-image/blob/master/skimage/data/astronaut.png), or would you prefer to pursue JavaScript solution?

**Comment by emmanuelle** [comment]
Part of this issue has been resolved by adding the shape of images to docstrings (#2236), but the gallery part didn't go through, maybe because solutions based on javascript were too complicated. Why not add a gallery example plotting all functions, like the code below? One problem which I can see is that we would require the image to take the whole width of the image, while gallery examples have small thumbnails.

```
import inspect
import numpy as np
import matplotlib.pyplot as plt
from skimage import data

datasets = data.__all__[2:] # remove load and data_dir
number = len(datasets)

functions = inspect.getmembers(data, inspect.isfunction)
functions = [_function for _function in functions if _function[0] in datasets]

fix, ax = plt.subplots(4, 5, figsize=(20, 25))
plt.gray()
ax_ravel = ax.ravel()

for i, axx in enumerate(ax_ravel[:number]):
    im = functions[i][1]()
    if functions[i][0] == 'lfw_subset':
        im = np.block([[im[0], im[1]], [im[2], im[3]]])
    if functions[i][0] == 'stereo_motorcycle':
        im = np.hstack((im[0], im[1]))
    axx.imshow(im)
    axx.set_title(functions[i][0])

for axx in ax_ravel:
    axx.axis('off')

plt.show()
```
![all_images](https://user-images.githubusercontent.com/263366/44918075-64768f00-ad3a-11e8-959b-ee34cfb7a52f.png)

**Comment by jni** [comment]
Nice code! =)

What will we do when we include a 3D image example? =)

**Comment by jni** [comment]
@emmanuelle no I really like your uses of inspect! They have inspired me to use it more in my own work. It's so useful!

**Comment by soupault** [comment]
@jni Well, do you think it would be easier to plot 3D data using JavaScript? 🙂Same applies for >3D images (e.g. taken from satellite cameras).

There is one thing I don't like about the approach of plotting all the data in a dedicated gallery example - the gallery is already quite populated, and it'll be challenging for the users to locate such page.

Maybe we should introduce `data` section to it, and have few examples: one for all 2D images, one for 3D, one for xD, etc, and pin such section to the top?

**Comment by jni** [comment]
@soupault very good points. It could be its own page, linked from "data types and what they mean", for example, or "getting started" directly.

I think we are pretty lackadaisical about doc dependencies (vs core dependencies), so we could certainly use ipyvolume or bokeh or something else to render 3D images in a widget.

**Comment by soupault** [comment]
The requested functionality has been finalised in https://github.com/scikit-image/scikit-image/pull/3388, see http://scikit-image.org/docs/dev/auto_examples/index.html -> `Data` section.
